// Liste officielle des spécialités médicales marocaines (CNOM).
// "Médecine générale" en première position (majorité de la cible), puis tri alphabétique.
// "Autre" en fin de liste — aucune liste ne sera jamais complète.
export const SPECIALITES: string[] = [
  'Médecine générale',
  'Allergologie',
  'Anatomie et cytologie pathologiques',
  'Andrologie',
  'Anesthésiologie-Réanimation',
  'Biologie médicale',
  'Cardiologie',
  'Chirurgie cardiovasculaire et thoracique',
  'Chirurgie générale',
  'Chirurgie orthopédique et traumatologique',
  'Chirurgie pédiatrique',
  'Chirurgie plastique et reconstructrice',
  'Chirurgie urologique',
  'Chirurgie vasculaire périphérique',
  'Chirurgie viscérale et digestive',
  'Dermatologie-Vénérologie',
  'Diabétologie',
  'Endocrinologie-Diabétologie et maladies métaboliques',
  'Gastro-entérologie et Hépatologie',
  'Génétique médicale',
  'Gériatrie',
  'Gynécologie médicale',
  'Gynécologie-Obstétrique',
  'Hématologie',
  'Immunologie clinique',
  'Infectiologie',
  'Médecine du sport',
  'Médecine du travail',
  'Médecine esthétique',
  "Médecine d'urgence",
  'Médecine interne',
  'Médecine légale et expertises médicales',
  'Médecine nucléaire',
  'Médecine physique et Réadaptation',
  'Médecine préventive et Santé publique',
  'Néonatologie',
  'Néphrologie',
  'Neurochirurgie',
  'Neurologie',
  'Nutrition',
  'Oncologie médicale',
  'Oncologie radiothérapique',
  'Ophtalmologie',
  'ORL et Chirurgie cervico-faciale',
  'Pédiatrie',
  'Pédopsychiatrie',
  'Phlébologie',
  'Pneumo-Phtisiologie',
  'Psychiatrie',
  'Radiologie et Imagerie médicale',
  'Réanimation médicale',
  'Rhumatologie',
  'Sexologie',
  'Stomatologie et chirurgie maxillo-faciale',
  'Toxicologie clinique',
  'Autre',
];
