-- chembl_batch_018.sql (80 rows)
INSERT INTO medicaments (nom, dci, forme, voie_administration, pays, classe_therapeutique)
SELECT v.nom, v.dci, v.forme, v.voie, v.pays, v.classe
FROM (VALUES
('VITAMIN A PALMITATE','vitamin a palmitate',NULL,NULL,'INT',NULL),
('FLUTICASONE FUROATE','fluticasone furoate',NULL,NULL,'INT',NULL),
('TACRINE HYDROCHLORIDE','tacrine hydrochloride',NULL,NULL,'INT',NULL),
('DONEPEZIL HYDROCHLORIDE','donepezil hydrochloride',NULL,NULL,'INT',NULL),
('CEFOPERAZONE','cefoperazone',NULL,NULL,'INT',NULL),
('ENFUVIRTIDE','enfuvirtide','Solution injectable','Intraveineuse','INT','Protéine thérapeutique'),
('LEUCOVORIN','leucovorin',NULL,NULL,'INT',NULL),
('OCTREOTIDE','octreotide','Solution injectable','Intraveineuse','INT','Protéine thérapeutique'),
('IODOHIPPURATE','iodohippurate',NULL,NULL,'INT',NULL),
('SORBITOL','sorbitol',NULL,NULL,'INT',NULL),
('NALFURAFINE HYDROCHLORIDE','nalfurafine hydrochloride',NULL,NULL,'INT',NULL),
('HYDROCORTISONE BUTYRATE','hydrocortisone butyrate',NULL,NULL,'INT',NULL),
('ELAGOLIX SODIUM','elagolix sodium',NULL,NULL,'INT',NULL),
('BENDROFLUMETHIAZIDE','bendroflumethiazide',NULL,NULL,'INT',NULL),
('SULFISOMIDINE','sulfisomidine',NULL,NULL,'INT',NULL),
('DEZOCINE','dezocine',NULL,NULL,'INT',NULL),
('MARIBAVIR','maribavir',NULL,NULL,'INT',NULL),
('CRISABOROLE','crisaborole',NULL,NULL,'INT',NULL),
('CARFILZOMIB','carfilzomib','Solution injectable','Intraveineuse','INT','Protéine thérapeutique'),
('NINTEDANIB','nintedanib',NULL,NULL,'INT',NULL),
('TOLAZOLINE HYDROCHLORIDE','tolazoline hydrochloride',NULL,NULL,'INT',NULL),
('HYDROXYCHLOROQUINE SULFATE','hydroxychloroquine sulfate',NULL,NULL,'INT',NULL),
('MEFLOQUINE HYDROCHLORIDE','mefloquine hydrochloride',NULL,NULL,'INT',NULL),
('BETAXOLOL HYDROCHLORIDE','betaxolol hydrochloride',NULL,NULL,'INT',NULL),
('HYDRALAZINE HYDROCHLORIDE','hydralazine hydrochloride',NULL,NULL,'INT',NULL),
('FINGOLIMOD HYDROCHLORIDE','fingolimod hydrochloride',NULL,NULL,'INT',NULL),
('IMIPRAMINE HYDROCHLORIDE','imipramine hydrochloride',NULL,NULL,'INT',NULL),
('DIETHYLPROPION HYDROCHLORIDE','diethylpropion hydrochloride',NULL,NULL,'INT',NULL),
('BENAZEPRIL HYDROCHLORIDE','benazepril hydrochloride',NULL,NULL,'INT',NULL),
('TIAGABINE HYDROCHLORIDE','tiagabine hydrochloride',NULL,NULL,'INT',NULL),
('DESIPRAMINE HYDROCHLORIDE','desipramine hydrochloride',NULL,NULL,'INT',NULL),
('DILTIAZEM HYDROCHLORIDE','diltiazem hydrochloride',NULL,NULL,'INT',NULL),
('BUPROPION HYDROCHLORIDE','bupropion hydrochloride',NULL,NULL,'INT',NULL),
('MEMANTINE HYDROCHLORIDE','memantine hydrochloride',NULL,NULL,'INT',NULL),
('SOTALOL HYDROCHLORIDE','sotalol hydrochloride',NULL,NULL,'INT',NULL),
('MEPERIDINE HYDROCHLORIDE','meperidine hydrochloride',NULL,NULL,'INT',NULL),
('ATOMOXETINE HYDROCHLORIDE','tomoxetine',NULL,NULL,'INT',NULL),
('METFORMIN HYDROCHLORIDE','metformin hydrochloride',NULL,NULL,'INT',NULL),
('CLONIDINE HYDROCHLORIDE','clonidine hydrochloride',NULL,NULL,'INT',NULL),
('NAPHAZOLINE HYDROCHLORIDE','naphazoline hydrochloride',NULL,NULL,'INT',NULL),
('LOPERAMIDE HYDROCHLORIDE','loperamide hydrochloride',NULL,NULL,'INT',NULL),
('SERTRALINE HYDROCHLORIDE','sertraline hydrochloride',NULL,NULL,'INT',NULL),
('RIMANTADINE HYDROCHLORIDE','rimantadine hydrochloride',NULL,NULL,'INT',NULL),
('ISOPROTERENOL HYDROCHLORIDE','isoproterenol hydrochloride',NULL,NULL,'INT',NULL),
('CHLORPROMAZINE HYDROCHLORIDE','chlorpromazine hydrochloride',NULL,NULL,'INT',NULL),
('KETAMINE HYDROCHLORIDE','ketamine hydrochloride',NULL,NULL,'INT',NULL),
('PIOGLITAZONE HYDROCHLORIDE','pioglitazone hydrochloride',NULL,NULL,'INT',NULL),
('CYPROHEPTADINE HYDROCHLORIDE','cyproheptadine hydrochloride',NULL,NULL,'INT',NULL),
('TICLOPIDINE HYDROCHLORIDE','ticlopidine hydrochloride',NULL,NULL,'INT',NULL),
('NALOXONE HYDROCHLORIDE','naloxone hydrochloride',NULL,NULL,'INT',NULL),
('TERODILINE HYDROCHLORIDE','terodiline hydrochloride',NULL,NULL,'INT',NULL),
('OLOPATADINE HYDROCHLORIDE','olopatadine hydrochloride',NULL,NULL,'INT',NULL),
('PALONOSETRON HYDROCHLORIDE','palonosetron hydrochloride',NULL,NULL,'INT',NULL),
('METHYLPHENIDATE HYDROCHLORIDE','methylphenidate hydrochloride',NULL,NULL,'INT',NULL),
('ALFUZOSIN HYDROCHLORIDE','alfuzosin hydrochloride',NULL,NULL,'INT',NULL),
('MEPENZOLATE BROMIDE','mepenzolate bromide',NULL,NULL,'INT',NULL),
('IOPROMIDE','iopromide',NULL,NULL,'INT',NULL),
('NISOLDIPINE','nisoldipine',NULL,NULL,'INT',NULL),
('CEPHALEXIN ANHYDROUS','cefalexin',NULL,NULL,'INT',NULL),
('LOMEFLOXACIN HYDROCHLORIDE','lomefloxacin hydrochloride',NULL,NULL,'INT',NULL),
('CISAPRIDE','cisapride',NULL,NULL,'INT',NULL),
('TREPROSTINIL SODIUM','treprostinil sodium',NULL,NULL,'INT',NULL),
('CEFOTAXIME','cefotaxime',NULL,NULL,'INT',NULL),
('MEZLOCILLIN','mezlocillin',NULL,NULL,'INT',NULL),
('DIHYDROERGOTAMINE','dihydroergotamine',NULL,NULL,'INT',NULL),
('TROLEANDOMYCIN','troleandomycin',NULL,NULL,'INT',NULL),
('VINORELBINE','vinorelbine',NULL,NULL,'INT',NULL),
('DABIGATRAN ETEXILATE','dabigatran etexilate',NULL,NULL,'INT',NULL),
('SOLIFENACIN','solifenacin',NULL,NULL,'INT',NULL),
('ACLIDINIUM BROMIDE','aclidinium bromide',NULL,NULL,'INT',NULL),
('INDINAVIR SULFATE','indinavir sulfate',NULL,NULL,'INT',NULL),
('METHYLENE BLUE','methylene blue',NULL,NULL,'INT',NULL),
('METRIZOIC ACID','metrizoic acid',NULL,NULL,'INT',NULL),
('CIPROFIBRATE','ciprofibrate',NULL,NULL,'INT',NULL),
('VINORELBINE TARTRATE','vinorelbine tartrate',NULL,NULL,'INT',NULL),
('SILDENAFIL CITRATE','sildenafil citrate',NULL,NULL,'INT',NULL),
('DEFERASIROX','deferasirox',NULL,NULL,'INT',NULL),
('FORODESINE HYDROCHLORIDE','forodesine hydrochloride',NULL,NULL,'INT',NULL),
('DEXRAZOXANE','dexrazoxane',NULL,NULL,'INT',NULL),
('METOCURINE IODIDE','metocurine iodide',NULL,NULL,'INT',NULL)
) AS v(nom, dci, forme, voie, pays, classe)
WHERE NOT EXISTS (
  SELECT 1 FROM medicaments m WHERE LOWER(m.nom) = LOWER(v.nom)
);
