-- chembl_batch_029.sql (80 rows)
INSERT INTO medicaments (nom, dci, forme, voie_administration, pays, classe_therapeutique)
SELECT v.nom, v.dci, v.forme, v.voie, v.pays, v.classe
FROM (VALUES
('TERIPARATIDE ACETATE','teriparatide acetate','Solution injectable','Intraveineuse','INT','Protéine thérapeutique'),
('ETANERCEPT','etanercept','Solution injectable','Intraveineuse','INT','Protéine thérapeutique'),
('LIPASE (PANCRELIPASE)','lipase (pancrelipase)','Solution injectable','Intraveineuse','INT','Enzyme'),
('CORTICOTROPIN ZINC HYDROXIDE','corticotropin zinc hydroxide',NULL,NULL,'INT',NULL),
('BECAPLERMIN','becaplermin','Solution injectable','Intraveineuse','INT','Protéine thérapeutique'),
('AMYLASE (PANCRELIPASE)','amylase (pancrelipase)','Solution injectable','Intraveineuse','INT','Enzyme'),
('SOMATREM','somatrem','Solution injectable','Intraveineuse','INT','Protéine thérapeutique'),
('INSULIN GLARGINE','insulin glargine','Solution injectable','Intraveineuse','INT','Protéine thérapeutique'),
('INSULIN SUSP ISOPHANE SEMISYNTHETIC PURIFIED HUMAN','insulin susp isophane semisynthetic purified human','Solution injectable','Intraveineuse','INT','Protéine thérapeutique'),
('RIMABOTULINUMTOXINB','rimabotulinumtoxinb','Solution injectable','Intraveineuse','INT','Protéine thérapeutique'),
('RASBURICASE','rasburicase','Solution injectable','Intraveineuse','INT','Enzyme'),
('ALGLUCERASE','alglucerase','Solution injectable','Intraveineuse','INT','Enzyme'),
('CORTICORELIN OVINE TRIFLUTATE','corticorelin ovine triflutate','Solution injectable','Intraveineuse','INT','Protéine thérapeutique'),
('CORTICOTROPIN','corticotropin',NULL,NULL,'INT',NULL),
('INTERFERON GAMMA-1B','interferon gamma','Solution injectable','Intraveineuse','INT','Protéine thérapeutique'),
('IMIGLUCERASE','imiglucerase','Solution injectable','Intraveineuse','INT','Enzyme'),
('PEGADEMASE BOVINE','pegademase','Solution injectable','Intraveineuse','INT','Enzyme'),
('LARONIDASE','laronidase','Solution injectable','Intraveineuse','INT','Enzyme'),
('ANTITHROMBIN ALFA','antithrombin alfa','Solution injectable','Intraveineuse','INT','Protéine thérapeutique'),
('FIBRINOGEN I 125','fibrinogen (125i)',NULL,NULL,'INT',NULL),
('ALBUMIN HUMAN','albumin human','Solution injectable','Intraveineuse','INT','Protéine thérapeutique'),
('ALBUMIN, IODINATED I 125 SERUM','iodinated (125i) human serum albumin','Solution injectable','Intraveineuse','INT','Protéine thérapeutique'),
('ALBUMIN, IODINATED I 131 SERUM','albumin, iodinated (131i) human serum','Solution injectable','Intraveineuse','INT','Protéine thérapeutique'),
('VASOPRESSIN TANNATE','vasopressin tannate','Solution injectable','Intraveineuse','INT','Protéine thérapeutique'),
('ALBUMIN, CHROMATED CR 51 SERUM','albumin, chromated cr 51 serum','Solution injectable','Intraveineuse','INT','Protéine thérapeutique'),
('NESIRITIDE','nesiritide','Solution injectable','Intraveineuse','INT','Protéine thérapeutique'),
('TECHNETIUM TC 99M ALBUMIN AGGREGATED','technetium tc 99m albumin aggregated','Solution injectable','Intraveineuse','INT','Protéine thérapeutique'),
('ETHIODIZED OIL','ethiodized oil',NULL,NULL,'INT',NULL),
('PEGAPTANIB SODIUM','pegaptanib sodium',NULL,NULL,'INT',NULL),
('BASILIXIMAB','basiliximab','Solution injectable','Intraveineuse','INT','Anticorps monoclonal'),
('TECHNETIUM TC-99M POLYPHOSPHATE KIT','technetium tc-99m polyphosphate kit',NULL,NULL,'INT',NULL),
('SERACTIDE ACETATE','seractide acetate','Solution injectable','Intraveineuse','INT','Protéine thérapeutique'),
('PENTOSAN POLYSULFATE SODIUM','pentosan polysulfate sodium',NULL,NULL,'INT',NULL),
('CELLULOSE SODIUM PHOSPHATE','cellulose sodium phosphate',NULL,NULL,'INT',NULL),
('ALTEPLASE','alteplase','Solution injectable','Intraveineuse','INT','Enzyme'),
('BENTOQUATAM','bentoquatam',NULL,NULL,'INT',NULL),
('FILGRASTIM','filgrastim','Solution injectable','Intraveineuse','INT','Protéine thérapeutique'),
('LEPIRUDIN','lepirudin','Solution injectable','Intraveineuse','INT','Protéine thérapeutique'),
('INSULIN SUSP ISOPHANE BEEF','insulin susp isophane beef','Solution injectable','Intraveineuse','INT','Protéine thérapeutique'),
('VERATRUM VIRIDE ROOT','veratrum viride root',NULL,NULL,'INT',NULL),
('INSULIN ASPART','insulin aspart','Solution injectable','Intraveineuse','INT','Protéine thérapeutique'),
('CALFACTANT','calfactant',NULL,NULL,'INT',NULL),
('NICOTINE POLACRILEX','nicotine polacrilex',NULL,NULL,'INT',NULL),
('INSULIN ASPART PROTAMINE RECOMBINANT','insulin aspart protamine recombinant','Solution injectable','Intraveineuse','INT','Protéine thérapeutique'),
('INSULIN LISPRO PROTAMINE RECOMBINANT','insulin lispro protamine recombinant','Solution injectable','Intraveineuse','INT','Protéine thérapeutique'),
('TECHNETIUM TC 99M RED BLOOD CELLS','technetium tc 99m red blood cells',NULL,NULL,'INT',NULL),
('POLYTETRAFLUOROETHYLENE','polytetrafluoroethylene',NULL,NULL,'INT',NULL),
('INSULIN PURIFIED BEEF','insulin purified beef','Solution injectable','Intraveineuse','INT','Protéine thérapeutique'),
('TECHNETIUM TC 99M SULFUR COLLOID','technetium tc 99m sulfur colloid',NULL,NULL,'INT',NULL),
('ENOXAPARIN SODIUM','enoxaparin sodium',NULL,NULL,'INT','Oligosaccharide'),
('INTRINSIC FACTOR','intrinsic factor',NULL,NULL,'INT',NULL),
('ALDESLEUKIN','aldesleukin','Solution injectable','Intraveineuse','INT','Protéine thérapeutique'),
('CRYPTENAMINE ACETATES','cryptenamine acetates',NULL,NULL,'INT',NULL),
('ARDEPARIN SODIUM','ardeparin sodium',NULL,NULL,'INT','Oligosaccharide'),
('ALSEROXYLON','alseroxylon',NULL,NULL,'INT',NULL),
('DEXTROMETHORPHAN POLISTIREX','dextromethorphan polistirex',NULL,NULL,'INT',NULL),
('CODEINE POLISTIREX','codeine polistirex',NULL,NULL,'INT',NULL),
('HYDROCODONE POLISTIREX','hydrocodone polistirex',NULL,NULL,'INT',NULL),
('POLYESTRADIOL PHOSPHATE','polyestradiol phosphate',NULL,NULL,'INT',NULL),
('QUINIDINE POLYGALACTURONATE','quinidine polygalacturonate',NULL,NULL,'INT',NULL),
('DIMYRISTOYL LECITHIN','dimyristoyl lecithin',NULL,NULL,'INT',NULL),
('HEPARIN CALCIUM','heparin calcium',NULL,NULL,'INT','Oligosaccharide'),
('PEGVISOMANT','pegvisomant','Solution injectable','Intraveineuse','INT','Protéine thérapeutique'),
('PHENYLPROPANOLAMINE POLISTIREX','phenylpropanolamine polistirex',NULL,NULL,'INT',NULL),
('TROLAMINE POLYPEPTIDE OLEATE CONDENSATE','trolamine polypeptide oleate condensate','Solution injectable','Intraveineuse','INT','Protéine thérapeutique'),
('INSULIN PORK','insulin pork','Solution injectable','Intraveineuse','INT','Protéine thérapeutique'),
('ALEFACEPT','alefacept','Solution injectable','Intraveineuse','INT','Protéine thérapeutique'),
('EFALIZUMAB','efalizumab','Solution injectable','Intraveineuse','INT','Anticorps monoclonal'),
('ADALIMUMAB','adalimumab','Solution injectable','Intraveineuse','INT','Anticorps monoclonal'),
('BEVACIZUMAB','bevacizumab','Solution injectable','Intraveineuse','INT','Anticorps monoclonal'),
('PALIVIZUMAB','palivizumab','Solution injectable','Intraveineuse','INT','Anticorps monoclonal'),
('OMALIZUMAB','omalizumab','Solution injectable','Intraveineuse','INT','Anticorps monoclonal'),
('HUMAN IMMUNOGLOBULIN G','human immunoglobulin g',NULL,NULL,'INT',NULL),
('TOSITUMOMAB','tositumomab','Solution injectable','Intraveineuse','INT','Anticorps monoclonal'),
('NATALIZUMAB','natalizumab','Solution injectable','Intraveineuse','INT','Anticorps monoclonal'),
('CHOLESTYRAMINE','colestyramine',NULL,NULL,'INT',NULL),
('VITAMIN K','vitamin k',NULL,NULL,'INT',NULL),
('ICODEXTRIN','icodextrin',NULL,NULL,'INT',NULL),
('DARBEPOETIN ALFA','darbepoetin alfa','Solution injectable','Intraveineuse','INT','Protéine thérapeutique'),
('SECRETIN SYNTHETIC PORCINE','secretin synthetic porcine','Solution injectable','Intraveineuse','INT','Protéine thérapeutique')
) AS v(nom, dci, forme, voie, pays, classe)
WHERE NOT EXISTS (
  SELECT 1 FROM medicaments m WHERE LOWER(m.nom) = LOWER(v.nom)
);
