-- chembl_batch_031.sql (80 rows)
INSERT INTO medicaments (nom, dci, forme, voie_administration, pays, classe_therapeutique)
SELECT v.nom, v.dci, v.forme, v.voie, v.pays, v.classe
FROM (VALUES
('PEGINTERFERON ALFA-2B','peginterferon alfa-2b','Solution injectable','Intraveineuse','INT','Protéine thérapeutique'),
('INFLIXIMAB','infliximab','Solution injectable','Intraveineuse','INT','Anticorps monoclonal'),
('INSULIN ZINC SUSP RECOMBINANT HUMAN','insulin zinc susp recombinant human','Solution injectable','Intraveineuse','INT','Protéine thérapeutique'),
('INULIN','inulin',NULL,NULL,'INT',NULL),
('SUGAR, INVERT','sugar, invert',NULL,NULL,'INT',NULL),
('ESTROGENS, CONJUGATED','estrogens, conjugated',NULL,NULL,'INT',NULL),
('PETROLATUM, WHITE','petrolatum, white',NULL,NULL,'INT',NULL),
('GONADOTROPIN, CHORIONIC','choriogonadotropin beta','Solution injectable','Intraveineuse','INT','Protéine thérapeutique'),
('IODINE POVACRYLEX','iodine povacrylex',NULL,NULL,'INT',NULL),
('MECASERMIN RINFABATE','mecasermin rinfabate','Solution injectable','Intraveineuse','INT','Protéine thérapeutique'),
('SINECATECHINS','sinecatechins',NULL,NULL,'INT',NULL),
('FOMIVIRSEN','fomivirsen','Solution injectable','Sous-cutanée','INT','Oligonucléotide'),
('MECASERMIN','mecasermin','Solution injectable','Intraveineuse','INT','Protéine thérapeutique'),
('LH (MENOTROPINS)','lh (menotropins)','Solution injectable','Intraveineuse','INT','Protéine thérapeutique'),
('FOLLITROPIN ALFA','follitropin alfa','Solution injectable','Intraveineuse','INT','Protéine thérapeutique'),
('POVIDONE-IODINE','povidone-iodine',NULL,NULL,'INT',NULL),
('UNDECOYLIUM CHLORIDE IODINE COMPLEX','undecoylium chloride iodine complex',NULL,NULL,'INT',NULL),
('DESVENLAFAXINE SUCCINATE','desvenlafaxine succinate',NULL,NULL,'INT',NULL),
('DRONEDARONE HYDROCHLORIDE','dronedarone hydrochloride',NULL,NULL,'INT',NULL),
('NEBIVOLOL HYDROCHLORIDE','nebivolol hydrochloride',NULL,NULL,'INT',NULL),
('PAZOPANIB HYDROCHLORIDE','pazopanib hydrochloride',NULL,NULL,'INT',NULL),
('BENDAMUSTINE HYDROCHLORIDE','bendamustine hydrochloride',NULL,NULL,'INT',NULL),
('BUPROPION HYDROBROMIDE','bupropion hydrobromide',NULL,NULL,'INT',NULL),
('NILOTINIB HYDROCHLORIDE MONOHYDRATE','nilotinib hydrochloride monohydrate',NULL,NULL,'INT',NULL),
('SAXAGLIPTIN HYDROCHLORIDE','saxagliptin hydrochloride',NULL,NULL,'INT',NULL),
('CHOLINE FENOFIBRATE','choline fenofibrate',NULL,NULL,'INT',NULL),
('PRALATREXATE','pralatrexate',NULL,NULL,'INT',NULL),
('ALCAFTADINE','alcaftadine',NULL,NULL,'INT',NULL),
('CABAZITAXEL','cabazitaxel',NULL,NULL,'INT',NULL),
('DIFLUPREDNATE','difluprednate',NULL,NULL,'INT',NULL),
('IXABEPILONE','ixabepilone',NULL,NULL,'INT',NULL),
('PITAVASTATIN','pitavastatin',NULL,NULL,'INT',NULL),
('RUFINAMIDE','rufinamide',NULL,NULL,'INT',NULL),
('BEPOTASTINE','bepotastine',NULL,NULL,'INT',NULL),
('BEPOTASTINE BESYLATE','bepotastine besylate',NULL,NULL,'INT',NULL),
('BESIFLOXACIN','besifloxacin',NULL,NULL,'INT',NULL),
('BESIFLOXACIN HYDROCHLORIDE','besifloxacin hydrochloride',NULL,NULL,'INT',NULL),
('FESOTERODINE','fesoterodine',NULL,NULL,'INT',NULL),
('FESOTERODINE FUMARATE','fesoterodine fumarate',NULL,NULL,'INT',NULL),
('FOSPROPOFOL','fospropofol',NULL,NULL,'INT',NULL),
('METHYLNALTREXONE BROMIDE','methylnaltrexone bromide',NULL,NULL,'INT',NULL),
('PRASUGREL','prasugrel',NULL,NULL,'INT',NULL),
('PRASUGREL HYDROCHLORIDE','prasugrel hydrochloride',NULL,NULL,'INT',NULL),
('SAPROPTERIN','sapropterin',NULL,NULL,'INT',NULL),
('SAPROPTERIN DIHYDROCHLORIDE','sapropterin dihydrochloride',NULL,NULL,'INT',NULL),
('TAPENTADOL','tapentadol',NULL,NULL,'INT',NULL),
('TAPENTADOL HYDROCHLORIDE','tapentadol hydrochloride',NULL,NULL,'INT',NULL),
('CARGLUMIC ACID','carglumic acid',NULL,NULL,'INT',NULL),
('FOSAPREPITANT DIMEGLUMINE','fosaprepitant dimeglumine',NULL,NULL,'INT',NULL),
('HEXAMINOLEVULINATE','hexaminolevulinate',NULL,NULL,'INT',NULL),
('HEXAMINOLEVULINATE HYDROCHLORIDE','hexaminolevulinate hydrochloride',NULL,NULL,'INT',NULL),
('LAPYRIUM','lapyrium',NULL,NULL,'INT',NULL),
('LAPYRIUM CHLORIDE','lapirium chloride',NULL,NULL,'INT',NULL),
('RIBOFLAVIN 5''-PHOSPHATE','riboflavin 5''-phosphate',NULL,NULL,'INT',NULL),
('PALIFERMIN','palifermin','Solution injectable','Intraveineuse','INT','Protéine thérapeutique'),
('GALSULFASE','galsulfase','Solution injectable','Intraveineuse','INT','Enzyme'),
('ABATACEPT','abatacept','Solution injectable','Intraveineuse','INT','Protéine thérapeutique'),
('ALGLUCOSIDASE ALFA','alglucosidase alfa','Solution injectable','Intraveineuse','INT','Enzyme'),
('RANIBIZUMAB','ranibizumab','Solution injectable','Intraveineuse','INT','Anticorps monoclonal'),
('IDURSULFASE','idursulfase','Solution injectable','Intraveineuse','INT','Enzyme'),
('PANITUMUMAB','panitumumab','Solution injectable','Intraveineuse','INT','Anticorps monoclonal'),
('ECULIZUMAB','eculizumab','Solution injectable','Intraveineuse','INT','Anticorps monoclonal'),
('RILONACEPT','rilonacept','Solution injectable','Intraveineuse','INT','Protéine thérapeutique'),
('CERTOLIZUMAB PEGOL','certolizumab pegol','Solution injectable','Intraveineuse','INT','Anticorps monoclonal'),
('ROMIPLOSTIM','romiplostim','Solution injectable','Intraveineuse','INT','Protéine thérapeutique'),
('GOLIMUMAB','golimumab','Solution injectable','Intraveineuse','INT','Anticorps monoclonal'),
('CANAKINUMAB','canakinumab','Solution injectable','Intraveineuse','INT','Anticorps monoclonal'),
('USTEKINUMAB','ustekinumab','Solution injectable','Intraveineuse','INT','Anticorps monoclonal'),
('OFATUMUMAB','ofatumumab','Solution injectable','Intraveineuse','INT','Anticorps monoclonal'),
('ECALLANTIDE','ecallantide','Solution injectable','Intraveineuse','INT','Protéine thérapeutique'),
('DEXLANSOPRAZOLE','dexlansoprazole',NULL,NULL,'INT',NULL),
('DIENOGEST','dienogest',NULL,NULL,'INT',NULL),
('VELAGLUCERASE ALFA','velaglucerase alfa','Solution injectable','Intraveineuse','INT','Enzyme'),
('FERUMOXYTOL','ferumoxytol',NULL,NULL,'INT',NULL),
('DEFLAZACORT','deflazacort',NULL,NULL,'INT',NULL),
('DILEVALOL HYDROCHLORIDE','dilevalol hydrochloride',NULL,NULL,'INT',NULL),
('GEPIRONE HYDROCHLORIDE','gepirone hydrochloride',NULL,NULL,'INT',NULL),
('PARECOXIB','parecoxib',NULL,NULL,'INT',NULL),
('ELAGOLIX','elagolix',NULL,NULL,'INT',NULL),
('ROSE BENGAL FREE ACID','rose bengal free acid',NULL,NULL,'INT',NULL)
) AS v(nom, dci, forme, voie, pays, classe)
WHERE NOT EXISTS (
  SELECT 1 FROM medicaments m WHERE LOWER(m.nom) = LOWER(v.nom)
);
