-- chembl_batch_032.sql (80 rows)
INSERT INTO medicaments (nom, dci, forme, voie_administration, pays, classe_therapeutique)
SELECT v.nom, v.dci, v.forme, v.voie, v.pays, v.classe
FROM (VALUES
('THIOSULFURIC ACID','thiosulfuric acid',NULL,NULL,'INT',NULL),
('THEOPHYLLINE GLYCINATE','theophylline glycinate',NULL,NULL,'INT',NULL),
('DOLUTEGRAVIR SODIUM','dolutegravir sodium',NULL,NULL,'INT',NULL),
('CEFTOLOZANE SULFATE','ceftolozane sulfate',NULL,NULL,'INT',NULL),
('CLOBENZOREX','clobenzorex',NULL,NULL,'INT',NULL),
('CLORAZEPIC ACID','clorazepic acid',NULL,NULL,'INT',NULL),
('PROPOXYPHENE','dextropropoxyphene',NULL,NULL,'INT',NULL),
('GIVINOSTAT','givinostat',NULL,NULL,'INT',NULL),
('PERAMPANEL','perampanel',NULL,NULL,'INT',NULL),
('DEXTROSE','dextrose',NULL,NULL,'INT',NULL),
('DOLUTEGRAVIR','dolutegravir',NULL,NULL,'INT',NULL),
('VEMURAFENIB','vemurafenib',NULL,NULL,'INT',NULL),
('ESTETROL ANHYDROUS','estetrol (anhydrous)',NULL,NULL,'INT',NULL),
('LEVOMEFOLIC ACID','levomefolic acid',NULL,NULL,'INT',NULL),
('KRYPTON','krypton',NULL,NULL,'INT',NULL),
('OXYGEN','oxygen',NULL,NULL,'INT',NULL),
('SULFUR','sulfur',NULL,NULL,'INT',NULL),
('TARTARIC ACID','tartaric acid',NULL,NULL,'INT',NULL),
('XENON','xenon',NULL,NULL,'INT',NULL),
('XYLOSE','xylose',NULL,NULL,'INT',NULL),
('LURASIDONE','lurasidone',NULL,NULL,'INT',NULL),
('TOCILIZUMAB','tocilizumab','Solution injectable','Intraveineuse','INT','Anticorps monoclonal'),
('DENOSUMAB','denosumab','Solution injectable','Intraveineuse','INT','Anticorps monoclonal'),
('PEGLOTICASE','pegloticase','Solution injectable','Intraveineuse','INT','Enzyme'),
('TESAMORELIN','tesamorelin','Solution injectable','Intraveineuse','INT','Protéine thérapeutique'),
('TRAMADOL','tramadol',NULL,NULL,'INT',NULL),
('PLICAMYCIN','plicamycin',NULL,NULL,'INT',NULL),
('HYDROMORPHONE HYDROCHLORIDE','hydromorphone hydrochloride',NULL,NULL,'INT',NULL),
('PITAVASTATIN CALCIUM','pitavastatin calcium',NULL,NULL,'INT',NULL),
('TRAMADOL HYDROCHLORIDE','tramadol hydrochloride',NULL,NULL,'INT',NULL),
('CALCIUM GLUCEPTATE','calcium glucoheptonate',NULL,NULL,'INT',NULL),
('MICAFUNGIN SODIUM','micafungin sodium',NULL,NULL,'INT',NULL),
('DIRITHROMYCIN','dirithromycin',NULL,NULL,'INT',NULL),
('GRANISETRON HYDROCHLORIDE','granisetron hydrochloride',NULL,NULL,'INT',NULL),
('MECAMYLAMINE HYDROCHLORIDE','mecamylamine hydrochloride',NULL,NULL,'INT',NULL),
('DOXACURIUM CHLORIDE','doxacurium chloride',NULL,NULL,'INT',NULL),
('LEVOCABASTINE HYDROCHLORIDE','levocabastine hydrochloride',NULL,NULL,'INT',NULL),
('PROPOXYPHENE HYDROCHLORIDE','propoxyphene hydrochloride',NULL,NULL,'INT',NULL),
('CARBOPROST TROMETHAMINE','carboprost tromethamine',NULL,NULL,'INT',NULL),
('TECHNETIUM TC 99M BICISATE','technetium (99mtc) bicisate',NULL,NULL,'INT',NULL),
('TREPROSTINIL','treprostinil',NULL,NULL,'INT',NULL),
('CARBOPROST','carboprost',NULL,NULL,'INT',NULL),
('DOXACURIUM','doxacurium',NULL,NULL,'INT',NULL),
('CLEVIDIPINE','clevidipine',NULL,NULL,'INT',NULL),
('MAPROTILINE HYDROCHLORIDE','maprotiline hydrochloride',NULL,NULL,'INT',NULL),
('LETERMOVIR','letermovir',NULL,NULL,'INT',NULL),
('LEVALLORPHAN','levallorphan',NULL,NULL,'INT',NULL),
('TETRACAINE HYDROCHLORIDE','tetracaine hydrochloride',NULL,NULL,'INT',NULL),
('METHAPYRILENE HYDROCHLORIDE','methapyrilene hydrochloride',NULL,NULL,'INT',NULL),
('FIDAXOMICIN','fidaxomicin',NULL,NULL,'INT',NULL),
('CYSTEAMINE HYDROCHLORIDE','cysteamine hydrochloride',NULL,NULL,'INT',NULL),
('PIRFENIDONE','pirfenidone',NULL,NULL,'INT',NULL),
('CARBETAPENTANE CITRATE','carbetapentane citrate',NULL,NULL,'INT',NULL),
('FORMOTEROL','formoterol',NULL,NULL,'INT',NULL),
('DEXTROMETHORPHAN HYDROBROMIDE','dextromethorphan hydrobromide',NULL,NULL,'INT',NULL),
('NIALAMIDE','nialamide',NULL,NULL,'INT',NULL),
('NOMIFENSINE MALEATE','nomifensine maleate',NULL,NULL,'INT',NULL),
('EPINEPHRINE BITARTRATE','epinephrine bitartrate',NULL,NULL,'INT',NULL),
('TRIFLUOPERAZINE HYDROCHLORIDE','trifluoperazine hydrochloride',NULL,NULL,'INT',NULL),
('TECOVIRIMAT','tecovirimat',NULL,NULL,'INT',NULL),
('SOFOSBUVIR','sofosbuvir',NULL,NULL,'INT',NULL),
('EDOXABAN','edoxaban',NULL,NULL,'INT',NULL),
('MIFEPRISTONE','mifepristone',NULL,NULL,'INT',NULL),
('FEDRATINIB','fedratinib',NULL,NULL,'INT',NULL),
('TIVOZANIB','tivozanib',NULL,NULL,'INT',NULL),
('LENVATINIB','lenvatinib',NULL,NULL,'INT',NULL),
('AXITINIB','axitinib',NULL,NULL,'INT',NULL),
('PROCHLORPERAZINE MALEATE','prochlorperazine maleate',NULL,NULL,'INT',NULL),
('TERBUTALINE SULFATE','terbutaline sulfate',NULL,NULL,'INT',NULL),
('PENTOLINIUM TARTRATE','pentolonium tartrate',NULL,NULL,'INT',NULL),
('PHENOTHRIN','phenothrin',NULL,NULL,'INT',NULL),
('ACETARSONE','acetarsol',NULL,NULL,'INT',NULL),
('PERHEXILINE MALEATE','perhexiline maleate',NULL,NULL,'INT',NULL),
('METHSCOPOLAMINE BROMIDE','methscopolamine bromide',NULL,NULL,'INT',NULL),
('THEOPHYLLINE','theophylline','Solution injectable','Intraveineuse','INT','Protéine thérapeutique'),
('PYRITHIONE','pyrithione',NULL,NULL,'INT',NULL),
('AMODIAQUINE HYDROCHLORIDE','amodiaquine hydrochloride',NULL,NULL,'INT',NULL),
('METHYLPREDNISOLONE ACETATE','methylprednisolone acetate',NULL,NULL,'INT',NULL),
('MINAPRINE HYDROCHLORIDE','minaprine hydrochloride',NULL,NULL,'INT',NULL),
('RITODRINE HYDROCHLORIDE','ritodrine hydrochloride',NULL,NULL,'INT',NULL)
) AS v(nom, dci, forme, voie, pays, classe)
WHERE NOT EXISTS (
  SELECT 1 FROM medicaments m WHERE LOWER(m.nom) = LOWER(v.nom)
);
