-- chembl_batch_012.sql (80 rows)
INSERT INTO medicaments (nom, dci, forme, voie_administration, pays, classe_therapeutique)
SELECT v.nom, v.dci, v.forme, v.voie, v.pays, v.classe
FROM (VALUES
('VILDAGLIPTIN','vildagliptin',NULL,NULL,'INT',NULL),
('TRIMETHAPHAN CAMSYLATE','trimetaphan camsilate',NULL,NULL,'INT',NULL),
('GANIRELIX','ganirelix','Solution injectable','Intraveineuse','INT','Protéine thérapeutique'),
('NAFTOPIDIL','naftopidil',NULL,NULL,'INT',NULL),
('DEGARELIX','degarelix','Solution injectable','Intraveineuse','INT','Protéine thérapeutique'),
('ABARELIX','abarelix','Solution injectable','Intraveineuse','INT','Protéine thérapeutique'),
('ISOFLURANE','isoflurane',NULL,NULL,'INT',NULL),
('NITROGEN','nitrogen',NULL,NULL,'INT',NULL),
('ENFLURANE','enflurane',NULL,NULL,'INT',NULL),
('METOCURINE','metocurine',NULL,NULL,'INT',NULL),
('CITRIC ACID','citric acid',NULL,NULL,'INT',NULL),
('OXICONAZOLE','oxiconazole',NULL,NULL,'INT',NULL),
('SALMETEROL','salmeterol',NULL,NULL,'INT',NULL),
('OXALIPLATIN','oxaliplatin',NULL,NULL,'INT',NULL),
('ADAPALENE','adapalene',NULL,NULL,'INT',NULL),
('GLAFENINE','glafenine',NULL,NULL,'INT',NULL),
('TETRAHYDROZOLINE','tetryzoline',NULL,NULL,'INT',NULL),
('ROMIDEPSIN','romidepsin','Solution injectable','Intraveineuse','INT','Protéine thérapeutique'),
('PENTOLINIUM','pentolinium',NULL,NULL,'INT',NULL),
('REPAGLINIDE','repaglinide',NULL,NULL,'INT',NULL),
('NILUTAMIDE','nilutamide',NULL,NULL,'INT',NULL),
('PERGOLIDE MESYLATE','pergolide mesylate',NULL,NULL,'INT',NULL),
('NARATRIPTAN','naratriptan',NULL,NULL,'INT',NULL),
('FROVATRIPTAN','frovatriptan',NULL,NULL,'INT',NULL),
('VERAPAMIL HYDROCHLORIDE','verapamil hydrochloride',NULL,NULL,'INT',NULL),
('PHENOBARBITAL SODIUM','phenobarbital sodium',NULL,NULL,'INT',NULL),
('IMIQUIMOD','imiquimod',NULL,NULL,'INT',NULL),
('CINCHOPHEN','cinchophen',NULL,NULL,'INT',NULL),
('LEVETIRACETAM','levetiracetam',NULL,NULL,'INT',NULL),
('HALOPROGIN','haloprogin',NULL,NULL,'INT',NULL),
('PENBUTOLOL','penbutolol',NULL,NULL,'INT',NULL),
('ANTRAFENINE','antrafenine',NULL,NULL,'INT',NULL),
('BECLOBRATE','beclobrate',NULL,NULL,'INT',NULL),
('METIPRANOLOL','metipranolol',NULL,NULL,'INT',NULL),
('CLOFAZIMINE','clofazimine',NULL,NULL,'INT',NULL),
('BETA CAROTENE','betacarotene',NULL,NULL,'INT',NULL),
('QUINIDINE','quinidine',NULL,NULL,'INT',NULL),
('BUTOCONAZOLE','butoconazole',NULL,NULL,'INT',NULL),
('CEFOTIAM','cefotiam',NULL,NULL,'INT',NULL),
('FENOPROFEN','fenoprofen',NULL,NULL,'INT',NULL),
('KETOCONAZOLE','ketoconazole',NULL,NULL,'INT',NULL),
('QUININE','quinine',NULL,NULL,'INT',NULL),
('DIAMTHAZOLE DIHYDROCHLORIDE','diamthazole dihydrochloride',NULL,NULL,'INT',NULL),
('HYDROXYSTILBAMIDINE','hydroxystilbamidine',NULL,NULL,'INT',NULL),
('ROTIGOTINE','rotigotine',NULL,NULL,'INT',NULL),
('ANTAZOLINE','antazoline',NULL,NULL,'INT',NULL),
('FOMEPIZOLE','fomepizole',NULL,NULL,'INT',NULL),
('ISOSORBIDE MONONITRATE','isosorbide mononitrate',NULL,NULL,'INT',NULL),
('TIOPRONIN','tiopronin',NULL,NULL,'INT',NULL),
('CARPROFEN','carprofen',NULL,NULL,'INT',NULL),
('MOXISYLYTE','moxisylyte',NULL,NULL,'INT',NULL),
('PROCARBAZINE','procarbazine',NULL,NULL,'INT',NULL),
('DARUNAVIR','darunavir',NULL,NULL,'INT',NULL),
('TOLCAPONE','tolcapone',NULL,NULL,'INT',NULL),
('PENTAGASTRIN','pentagastrin',NULL,NULL,'INT',NULL),
('SORAFENIB','sorafenib',NULL,NULL,'INT',NULL),
('CEVIMELINE','cevimeline',NULL,NULL,'INT',NULL),
('PIXANTRONE','pixantrone',NULL,NULL,'INT',NULL),
('NITISINONE','nitisinone',NULL,NULL,'INT',NULL),
('PHENFORMIN','phenformin',NULL,NULL,'INT',NULL),
('AMIFAMPRIDINE','amifampridine',NULL,NULL,'INT',NULL),
('LOMITAPIDE','lomitapide',NULL,NULL,'INT',NULL),
('VARDENAFIL HYDROCHLORIDE','vardenafil hydrochloride',NULL,NULL,'INT',NULL),
('METHOXYFLURANE','methoxyflurane',NULL,NULL,'INT',NULL),
('OXYBATE','oxybate',NULL,NULL,'INT',NULL),
('GUANETHIDINE MONOSULFATE','guanethidine monosulfate',NULL,NULL,'INT',NULL),
('DARIFENACIN','darifenacin',NULL,NULL,'INT',NULL),
('ORLISTAT','orlistat',NULL,NULL,'INT',NULL),
('RILPIVIRINE','rilpivirine',NULL,NULL,'INT',NULL),
('VALACYCLOVIR','valaciclovir',NULL,NULL,'INT',NULL),
('SPARSENTAN','sparsentan',NULL,NULL,'INT',NULL),
('NERATINIB','neratinib',NULL,NULL,'INT',NULL),
('TILUDRONIC ACID','tiludronic acid',NULL,NULL,'INT',NULL),
('CARBOPLATIN','carboplatin',NULL,NULL,'INT',NULL),
('BLONANSERIN','blonanserin',NULL,NULL,'INT',NULL),
('LORCASERIN','lorcaserin',NULL,NULL,'INT',NULL),
('RAMATROBAN','ramatroban',NULL,NULL,'INT',NULL),
('SODIUM BICARBONATE','sodium bicarbonate',NULL,NULL,'INT',NULL),
('SODIUM ACETATE','sodium acetate',NULL,NULL,'INT',NULL),
('SODIUM CITRATE','sodium citrate',NULL,NULL,'INT',NULL)
) AS v(nom, dci, forme, voie, pays, classe)
WHERE NOT EXISTS (
  SELECT 1 FROM medicaments m WHERE LOWER(m.nom) = LOWER(v.nom)
);
