-- chembl_batch_042.sql (80 rows)
INSERT INTO medicaments (nom, dci, forme, voie_administration, pays, classe_therapeutique)
SELECT v.nom, v.dci, v.forme, v.voie, v.pays, v.classe
FROM (VALUES
('POLATUZUMAB VEDOTIN','polatuzumab vedotin',NULL,NULL,'INT',NULL),
('ANDEXANET ALFA','andexanet alfa','Solution injectable','Intraveineuse','INT','Protéine thérapeutique'),
('DURVALUMAB','durvalumab','Solution injectable','Intraveineuse','INT','Anticorps monoclonal'),
('ENFORTUMAB VEDOTIN','enfortumab vedotin',NULL,NULL,'INT',NULL),
('SODIUM ZIRCONIUM CYCLOSILICATE','sodium zirconium cyclosilicate',NULL,NULL,'INT',NULL),
('FOSTEMSAVIR','fostemsavir',NULL,NULL,'INT',NULL),
('FERRIC CITRATE','ferric citrate',NULL,NULL,'INT',NULL),
('FOSTEMSAVIR TROMETHAMINE','fostemsavir tromethamine',NULL,NULL,'INT',NULL),
('GILTERITINIB FUMARATE','gilteritinib fumarate',NULL,NULL,'INT',NULL),
('RELEBACTAM','relebactam',NULL,NULL,'INT',NULL),
('FILGOTINIB','filgotinib',NULL,NULL,'INT',NULL),
('ABEMACICLIB','abemaciclib',NULL,NULL,'INT',NULL),
('AMIFAMPRIDINE PHOSPHATE','amifampridine phosphate',NULL,NULL,'INT',NULL),
('ENCORAFENIB','encorafenib',NULL,NULL,'INT',NULL),
('GILTERITINIB','gilteritinib',NULL,NULL,'INT',NULL),
('SETMELANOTIDE','setmelanotide','Solution injectable','Intraveineuse','INT','Protéine thérapeutique'),
('TENAPANOR HYDROCHLORIDE','tenapanor hydrochloride',NULL,NULL,'INT',NULL),
('DALBAVANCIN HYDROCHLORIDE','dalbavancin hydrochloride','Solution injectable','Intraveineuse','INT','Protéine thérapeutique'),
('DALBAVANCIN','dalbavancin','Solution injectable','Intraveineuse','INT','Protéine thérapeutique'),
('DIFEMERINE HYDROCHLORIDE','difemerine hydrochloride',NULL,NULL,'INT',NULL),
('LINACLOTIDE','linaclotide','Solution injectable','Intraveineuse','INT','Protéine thérapeutique'),
('TELAVANCIN HYDROCHLORIDE','telavancin hydrochloride','Solution injectable','Intraveineuse','INT','Protéine thérapeutique'),
('TENAPANOR','tenapanor',NULL,NULL,'INT',NULL),
('DIFEMERINE','difemerine',NULL,NULL,'INT',NULL),
('LUMATEPERONE','lumateperone',NULL,NULL,'INT',NULL),
('OTESECONAZOLE','oteseconazole',NULL,NULL,'INT',NULL),
('VABORBACTAM','vaborbactam',NULL,NULL,'INT',NULL),
('TOVORAFENIB','tovorafenib',NULL,NULL,'INT',NULL),
('TELOTRISTAT ETIPRATE','telotristat etiprate',NULL,NULL,'INT',NULL),
('PASIREOTIDE','pasireotide','Solution injectable','Intraveineuse','INT','Protéine thérapeutique'),
('OSIMERTINIB','osimertinib',NULL,NULL,'INT',NULL),
('ETRASIMOD','etrasimod',NULL,NULL,'INT',NULL),
('PARITAPREVIR','paritaprevir',NULL,NULL,'INT',NULL),
('FLUORODOPA F 18','fluorodopa (18f)',NULL,NULL,'INT',NULL),
('TEPOTINIB','tepotinib',NULL,NULL,'INT',NULL),
('TAZEMETOSTAT','tazemetostat',NULL,NULL,'INT',NULL),
('BENZPHETAMINE HYDROCHLORIDE','benzphetamine hydrochloride',NULL,NULL,'INT',NULL),
('AZATADINE MALEATE','azatadine maleate',NULL,NULL,'INT',NULL),
('CALCIFEDIOL','calcifediol',NULL,NULL,'INT',NULL),
('TEZACAFTOR','tezacaftor',NULL,NULL,'INT',NULL),
('CERLIPONASE ALFA','cerliponase alfa','Solution injectable','Intraveineuse','INT','Enzyme'),
('OBILTOXAXIMAB','obiltoxaximab','Solution injectable','Intraveineuse','INT','Anticorps monoclonal'),
('DEXTROAMPHETAMINE SULFATE','dextroamphetamine sulfate',NULL,NULL,'INT',NULL),
('CEFTAROLINE FOSAMIL ACETATE','ceftaroline fosamil acetate',NULL,NULL,'INT',NULL),
('ASENAPINE MALEATE','asenapine maleate',NULL,NULL,'INT',NULL),
('DASABUVIR SODIUM MONOHYDRATE','dasabuvir sodium monohydrate',NULL,NULL,'INT',NULL),
('PERINDOPRIL ARGININE','perindopril arginine',NULL,NULL,'INT',NULL),
('DAPRODUSTAT','daprodustat',NULL,NULL,'INT',NULL),
('VOLANESORSEN SODIUM','volanesorsen sodium','Solution injectable','Sous-cutanée','INT','Oligonucléotide'),
('IDARUCIZUMAB','idarucizumab','Solution injectable','Intraveineuse','INT','Anticorps monoclonal'),
('ACETYLDIGITOXIN','acetyldigitoxin',NULL,NULL,'INT',NULL),
('DEXTROTHYROXINE SODIUM','dextrothyroxine sodium',NULL,NULL,'INT',NULL),
('ALISKIREN FUMARATE','aliskiren fumarate',NULL,NULL,'INT',NULL),
('ERYTHROMYCIN GLUCEPTATE','erythromycin gluceptate',NULL,NULL,'INT',NULL),
('VELPATASVIR','velpatasvir',NULL,NULL,'INT',NULL),
('OSIMERTINIB MESYLATE','osimertinib mesylate',NULL,NULL,'INT',NULL),
('COPANLISIB HYDROCHLORIDE','copanlisib hydrochloride',NULL,NULL,'INT',NULL),
('RIBOCICLIB','ribociclib',NULL,NULL,'INT',NULL),
('PIBRENTASVIR','pibrentasvir',NULL,NULL,'INT',NULL),
('ISATUXIMAB','isatuximab','Solution injectable','Intraveineuse','INT','Anticorps monoclonal'),
('MIRVETUXIMAB SORAVTANSINE','mirvetuximab soravtansine',NULL,NULL,'INT',NULL),
('TIOTROPIUM BROMIDE','tiotropium bromide',NULL,NULL,'INT',NULL),
('ETELCALCETIDE HYDROCHLORIDE','etelcalcetide hydrochloride','Solution injectable','Intraveineuse','INT','Protéine thérapeutique'),
('ETELCALCETIDE','etelcalcetide','Solution injectable','Intraveineuse','INT','Protéine thérapeutique'),
('SELINEXOR','selinexor',NULL,NULL,'INT',NULL),
('LANADELUMAB','lanadelumab','Solution injectable','Intraveineuse','INT','Anticorps monoclonal'),
('EVINACUMAB','evinacumab','Solution injectable','Intraveineuse','INT','Anticorps monoclonal'),
('DOCETAXEL','docetaxel',NULL,NULL,'INT',NULL),
('FLORTAUCIPIR F 18','flortaucipir (18f)',NULL,NULL,'INT',NULL),
('SACITUZUMAB GOVITECAN','sacituzumab govitecan',NULL,NULL,'INT',NULL),
('LEFAMULIN ACETATE','lefamulin acetate',NULL,NULL,'INT',NULL),
('BRIGATINIB','brigatinib',NULL,NULL,'INT',NULL),
('BEMPEDOIC ACID','bempedoic acid',NULL,NULL,'INT',NULL),
('GLECAPREVIR','glecaprevir',NULL,NULL,'INT',NULL),
('LEMBOREXANT','lemborexant',NULL,NULL,'INT',NULL),
('PANOBINOSTAT LACTATE','panobinostat lactate',NULL,NULL,'INT',NULL),
('ERDAFITINIB','erdafitinib',NULL,NULL,'INT',NULL),
('IXAZOMIB CITRATE','ixazomib citrate',NULL,NULL,'INT',NULL),
('BENZPHETAMINE','benzfetamine',NULL,NULL,'INT',NULL),
('FLORTAUCIPIR','flortaucipir',NULL,NULL,'INT',NULL)
) AS v(nom, dci, forme, voie, pays, classe)
WHERE NOT EXISTS (
  SELECT 1 FROM medicaments m WHERE LOWER(m.nom) = LOWER(v.nom)
);
