-- chembl_batch_003.sql (80 rows)
INSERT INTO medicaments (nom, dci, forme, voie_administration, pays, classe_therapeutique)
SELECT v.nom, v.dci, v.forme, v.voie, v.pays, v.classe
FROM (VALUES
('DOCETAXEL ANHYDROUS','docetaxel anhydrous',NULL,NULL,'INT',NULL),
('ZILEUTON','zileuton',NULL,NULL,'INT',NULL),
('TACRINE','tacrine',NULL,NULL,'INT',NULL),
('DONEPEZIL','donepezil',NULL,NULL,'INT',NULL),
('LOVASTATIN','lovastatin',NULL,NULL,'INT',NULL),
('OZAGREL','ozagrel',NULL,NULL,'INT',NULL),
('ACETANILIDE','acetanilide',NULL,NULL,'INT',NULL),
('DIMETHYL SULFOXIDE','dimethyl sulfoxide',NULL,NULL,'INT',NULL),
('CHLORPHENIRAMINE','chlorphenamine',NULL,NULL,'INT',NULL),
('PRIMAQUINE','primaquine',NULL,NULL,'INT',NULL),
('MECLOFENAMIC ACID','meclofenamic acid',NULL,NULL,'INT',NULL),
('PYRILAMINE','mepyramine',NULL,NULL,'INT',NULL),
('SERTINDOLE','sertindole',NULL,NULL,'INT',NULL),
('CARMUSTINE','carmustine',NULL,NULL,'INT',NULL),
('LOMUSTINE','lomustine',NULL,NULL,'INT',NULL),
('CHLORAMBUCIL','chlorambucil',NULL,NULL,'INT',NULL),
('CYPROHEPTADINE','cyproheptadine',NULL,NULL,'INT',NULL),
('INAMRINONE','amrinone',NULL,NULL,'INT',NULL),
('DISOPYRAMIDE','disopyramide',NULL,NULL,'INT',NULL),
('VORINOSTAT','vorinostat',NULL,NULL,'INT',NULL),
('IBUPROFEN','ibuprofen',NULL,NULL,'INT',NULL),
('CLOMETACIN','clometacin',NULL,NULL,'INT',NULL),
('FLUNITRAZEPAM','flunitrazepam',NULL,NULL,'INT',NULL),
('METHOXAMINE','methoxamine',NULL,NULL,'INT',NULL),
('PROPOFOL','propofol',NULL,NULL,'INT',NULL),
('PIROXICAM','piroxicam',NULL,NULL,'INT',NULL),
('CEFTIZOXIME','ceftizoxime',NULL,NULL,'INT',NULL),
('PHENYLBUTAZONE','phenylbutazone',NULL,NULL,'INT',NULL),
('AZITHROMYCIN','azithromycin',NULL,NULL,'INT',NULL),
('AMDINOCILLIN','mecillinam',NULL,NULL,'INT',NULL),
('PERGOLIDE','pergolide',NULL,NULL,'INT',NULL),
('ERYTHROMYCIN','erythromycin',NULL,NULL,'INT',NULL),
('IBUTILIDE','ibutilide',NULL,NULL,'INT',NULL),
('PROGESTERONE','progesterone',NULL,NULL,'INT',NULL),
('KETOTIFEN','ketotifen',NULL,NULL,'INT',NULL),
('SUNITINIB','sunitinib',NULL,NULL,'INT',NULL),
('HYDROQUINONE','hydroquinone',NULL,NULL,'INT',NULL),
('ACETIC ACID','acetic acid',NULL,NULL,'INT',NULL),
('PHENOL','phenol',NULL,NULL,'INT',NULL),
('MEQUINOL','mequinol',NULL,NULL,'INT',NULL),
('CLOTRIMAZOLE','clotrimazole',NULL,NULL,'INT',NULL),
('MITOMYCIN','mitomycin',NULL,NULL,'INT',NULL),
('ALCOHOL','alcohol',NULL,NULL,'INT',NULL),
('OXPRENOLOL','oxprenolol',NULL,NULL,'INT',NULL),
('FLUCONAZOLE','fluconazole',NULL,NULL,'INT',NULL),
('ISOTRETINOIN','isotretinoin',NULL,NULL,'INT',NULL),
('ILOPERIDONE','iloperidone',NULL,NULL,'INT',NULL),
('DINOPROSTONE','dinoprostone',NULL,NULL,'INT',NULL),
('NEOSTIGMINE','neostigmine',NULL,NULL,'INT',NULL),
('REBOXETINE','reboxetine',NULL,NULL,'INT',NULL),
('CITALOPRAM','citalopram',NULL,NULL,'INT',NULL),
('PILOCARPINE','pilocarpine',NULL,NULL,'INT',NULL),
('COLCHICINE','colchicine',NULL,NULL,'INT',NULL),
('ERLOTINIB','erlotinib',NULL,NULL,'INT',NULL),
('LAPATINIB','lapatinib',NULL,NULL,'INT',NULL),
('CARBAMAZEPINE','carbamazepine',NULL,NULL,'INT',NULL),
('VALPROIC ACID','valproic acid',NULL,NULL,'INT',NULL),
('TEMAFLOXACIN','temafloxacin',NULL,NULL,'INT',NULL),
('BENZNIDAZOLE','benznidazole',NULL,NULL,'INT',NULL),
('DEFEROXAMINE','deferoxamine',NULL,NULL,'INT',NULL),
('MEXILETINE','mexiletine',NULL,NULL,'INT',NULL),
('DEXTROTHYROXINE','dextrothyroxine',NULL,NULL,'INT',NULL),
('RIMONABANT','rimonabant',NULL,NULL,'INT',NULL),
('NOMIFENSINE','nomifensine',NULL,NULL,'INT',NULL),
('LOMEFLOXACIN','lomefloxacin',NULL,NULL,'INT',NULL),
('GRISEOFULVIN','griseofulvin',NULL,NULL,'INT',NULL),
('FLURBIPROFEN','flurbiprofen',NULL,NULL,'INT',NULL),
('PROMAZINE','promazine',NULL,NULL,'INT',NULL),
('CLOFIBRATE','clofibrate',NULL,NULL,'INT',NULL),
('ACETAMINOPHEN','paracetamol',NULL,NULL,'INT',NULL),
('CAFFEINE','caffeine',NULL,NULL,'INT',NULL),
('PHENACETIN','phenacetin',NULL,NULL,'INT',NULL),
('PERPHENAZINE','perphenazine',NULL,NULL,'INT',NULL),
('OXAZEPAM','oxazepam',NULL,NULL,'INT',NULL),
('SULINDAC','sulindac',NULL,NULL,'INT',NULL),
('FENCLOFENAC','fenclofenac',NULL,NULL,'INT',NULL),
('INDALPINE','indalpine',NULL,NULL,'INT',NULL),
('PROCAINE','procaine',NULL,NULL,'INT',NULL),
('TRIFLUPROMAZINE','triflupromazine',NULL,NULL,'INT',NULL),
('KETOPROFEN','ketoprofen',NULL,NULL,'INT',NULL)
) AS v(nom, dci, forme, voie, pays, classe)
WHERE NOT EXISTS (
  SELECT 1 FROM medicaments m WHERE LOWER(m.nom) = LOWER(v.nom)
);
