-- chembl_batch_021.sql (80 rows)
INSERT INTO medicaments (nom, dci, forme, voie_administration, pays, classe_therapeutique)
SELECT v.nom, v.dci, v.forme, v.voie, v.pays, v.classe
FROM (VALUES
('LIDOCAINE HYDROCHLORIDE','lidocaine hydrochloride',NULL,NULL,'INT',NULL),
('PROCARBAZINE HYDROCHLORIDE','procarbazine hydrochloride',NULL,NULL,'INT',NULL),
('ROPINIROLE HYDROCHLORIDE','ropinirole hydrochloride',NULL,NULL,'INT',NULL),
('NANDROLONE PHENPROPIONATE','nandrolone phenpropionate',NULL,NULL,'INT',NULL),
('TETRAHYDROZOLINE HYDROCHLORIDE','tetrahydrozoline hydrochloride',NULL,NULL,'INT',NULL),
('TECHNETIUM TC 99M OXIDRONATE','technetium tc 99m oxidronate',NULL,NULL,'INT',NULL),
('DOBUTAMINE HYDROCHLORIDE','dobutamine hydrochloride',NULL,NULL,'INT',NULL),
('MOLINDONE HYDROCHLORIDE','molindone hydrochloride',NULL,NULL,'INT',NULL),
('MIDAZOLAM HYDROCHLORIDE','midazolam hydrochloride',NULL,NULL,'INT',NULL),
('TECHNETIUM TC 99M MEBROFENIN','technetium tc 99m mebrofenin',NULL,NULL,'INT',NULL),
('METRIZOATE SODIUM','sodium metrizoate',NULL,NULL,'INT',NULL),
('PENTETATE ZINC TRISODIUM','pentetate zinc trisodium',NULL,NULL,'INT',NULL),
('PARGYLINE HYDROCHLORIDE','pargyline hydrochloride',NULL,NULL,'INT',NULL),
('METHIXENE HYDROCHLORIDE','methixene hydrochloride',NULL,NULL,'INT',NULL),
('ESTRADIOL ACETATE','estradiol acetate',NULL,NULL,'INT',NULL),
('GADOPENTETATE DIMEGLUMINE','gadopentetic acid',NULL,NULL,'INT',NULL),
('METHYLDOPATE HYDROCHLORIDE','methyldopate hydrochloride',NULL,NULL,'INT',NULL),
('OXTRIPHYLLINE','choline theophyllinate',NULL,NULL,'INT',NULL),
('OXANDROLONE','oxandrolone',NULL,NULL,'INT',NULL),
('QUINIDINE GLUCONATE','quinidine gluconate',NULL,NULL,'INT',NULL),
('TIOCONAZOLE','tioconazole',NULL,NULL,'INT',NULL),
('IODOHIPPURATE SODIUM I 123','iodohippurate sodium i 123',NULL,NULL,'INT',NULL),
('MEPIVACAINE HYDROCHLORIDE','mepivacaine hydrochloride',NULL,NULL,'INT',NULL),
('MERETHOXYLLINE PROCAINE','merethoxylline procaine',NULL,NULL,'INT',NULL),
('PIRBUTEROL ACETATE','pirbuterol acetate',NULL,NULL,'INT',NULL),
('TRIPELENNAMINE HYDROCHLORIDE','tripelennamine hydrochloride',NULL,NULL,'INT',NULL),
('TILUDRONATE DISODIUM','tiludronate disodium',NULL,NULL,'INT',NULL),
('TRIAMCINOLONE DIACETATE','triamcinolone diacetate',NULL,NULL,'INT',NULL),
('INDIUM IN 111 OXYQUINOLINE','indium in 111 oxyquinoline',NULL,NULL,'INT',NULL),
('DOCOSANOL','docosanol',NULL,NULL,'INT',NULL),
('VALGANCICLOVIR HYDROCHLORIDE','valganciclovir hydrochloride',NULL,NULL,'INT',NULL),
('IOHEXOL','iohexol',NULL,NULL,'INT',NULL),
('GADOVERSETAMIDE','gadoversetamide',NULL,NULL,'INT',NULL),
('POTASSIUM CITRATE ANHYDROUS','potassium citrate anhydrous',NULL,NULL,'INT',NULL),
('POTASSIUM PHOSPHATE, DIBASIC','potassium phosphate, dibasic',NULL,NULL,'INT',NULL),
('MIDODRINE HYDROCHLORIDE','midodrine hydrochloride',NULL,NULL,'INT',NULL),
('OXAPROZIN POTASSIUM','oxaprozin potassium',NULL,NULL,'INT',NULL),
('PROPARACAINE HYDROCHLORIDE','proparacaine hydrochloride',NULL,NULL,'INT',NULL),
('HYDROXYZINE PAMOATE','hydroxyzine pamoate',NULL,NULL,'INT',NULL),
('MALATHION','malathion',NULL,NULL,'INT',NULL),
('PROMAZINE HYDROCHLORIDE','promazine hydrochloride',NULL,NULL,'INT',NULL),
('ESOMEPRAZOLE SODIUM','esomeprazole sodium',NULL,NULL,'INT',NULL),
('PYRITHIONE ZINC','pyrithione zinc',NULL,NULL,'INT',NULL),
('QUAZEPAM','quazepam',NULL,NULL,'INT',NULL),
('CYCLOPENTOLATE HYDROCHLORIDE','cyclopentolate hydrochloride',NULL,NULL,'INT',NULL),
('DEMECLOCYCLINE HYDROCHLORIDE','demeclocycline hydrochloride',NULL,NULL,'INT',NULL),
('DAUNORUBICIN CITRATE','daunorubicin citrate',NULL,NULL,'INT',NULL),
('ALLOPURINOL SODIUM','allopurinol sodium',NULL,NULL,'INT',NULL),
('DYCLONINE HYDROCHLORIDE','dyclonine hydrochloride',NULL,NULL,'INT',NULL),
('DICYCLOMINE HYDROCHLORIDE','dicyclomine hydrochloride',NULL,NULL,'INT',NULL),
('OCTREOTIDE ACETATE','octreotide acetate','Solution injectable','Intraveineuse','INT','Protéine thérapeutique'),
('CEFOPERAZONE SODIUM','cefoperazone sodium',NULL,NULL,'INT',NULL),
('PHENMETRAZINE HYDROCHLORIDE','phenmetrazine hydrochloride',NULL,NULL,'INT',NULL),
('SORAFENIB TOSYLATE','sorafenib tosylate',NULL,NULL,'INT',NULL),
('ETHACRYNATE SODIUM','ethacrynate sodium',NULL,NULL,'INT',NULL),
('CETRORELIX','cetrorelix','Solution injectable','Intraveineuse','INT','Protéine thérapeutique'),
('EPINASTINE HYDROCHLORIDE','epinastine hydrochloride',NULL,NULL,'INT',NULL),
('NEFAZODONE HYDROCHLORIDE','nefazodone hydrochloride',NULL,NULL,'INT',NULL),
('NAFTIFINE HYDROCHLORIDE','naftifine hydrochloride',NULL,NULL,'INT',NULL),
('GUANFACINE HYDROCHLORIDE','guanfacine hydrochloride',NULL,NULL,'INT',NULL),
('HYDROCORTISONE SODIUM SUCCINATE','hydrocortisone sodium succinate',NULL,NULL,'INT',NULL),
('CALCIUM','calcium',NULL,NULL,'INT',NULL),
('CYCLIZINE LACTATE','cyclizine lactate',NULL,NULL,'INT',NULL),
('ALATROFLOXACIN MESYLATE','alatrofloxacin mesylate',NULL,NULL,'INT',NULL),
('BECLOMETHASONE DIPROPIONATE','beclometasone',NULL,NULL,'INT',NULL),
('GOSERELIN ACETATE','goserelin acetate','Solution injectable','Intraveineuse','INT','Protéine thérapeutique'),
('BROMOCRIPTINE MESYLATE','bromocriptine mesylate',NULL,NULL,'INT',NULL),
('ERYTHROMYCIN LACTOBIONATE','erythromycin lactobionate',NULL,NULL,'INT',NULL),
('IODIXANOL','iodixanol',NULL,NULL,'INT',NULL),
('IOXAGLATE MEGLUMINE','ioxaglate meglumine',NULL,NULL,'INT',NULL),
('HISTRELIN ACETATE','histrelin acetate','Solution injectable','Intraveineuse','INT','Protéine thérapeutique'),
('ERYTHROMYCIN STEARATE','erythromycin stearate',NULL,NULL,'INT',NULL),
('GONADORELIN ACETATE','gonadorelin acetate','Solution injectable','Intraveineuse','INT','Protéine thérapeutique'),
('DEMECARIUM BROMIDE','demecarium bromide',NULL,NULL,'INT',NULL),
('DESERPIDINE','deserpidine',NULL,NULL,'INT',NULL),
('GONADORELIN HYDROCHLORIDE','gonadorelin hydrochloride','Solution injectable','Intraveineuse','INT','Protéine thérapeutique'),
('DIHYDROERGOTAMINE MESYLATE','dihydroergotamine mesylate',NULL,NULL,'INT',NULL),
('ALMOTRIPTAN MALATE','almotriptan malate',NULL,NULL,'INT',NULL),
('AVOBENZONE','avobenzone',NULL,NULL,'INT',NULL),
('CEFAZOLIN SODIUM','cefazolin sodium',NULL,NULL,'INT',NULL)
) AS v(nom, dci, forme, voie, pays, classe)
WHERE NOT EXISTS (
  SELECT 1 FROM medicaments m WHERE LOWER(m.nom) = LOWER(v.nom)
);
