-- chembl_batch_004.sql (80 rows)
INSERT INTO medicaments (nom, dci, forme, voie_administration, pays, classe_therapeutique)
SELECT v.nom, v.dci, v.forme, v.voie, v.pays, v.classe
FROM (VALUES
('NITROFURANTOIN','nitrofurantoin',NULL,NULL,'INT',NULL),
('INDOPROFEN','indoprofen',NULL,NULL,'INT',NULL),
('LINDANE','lindane',NULL,NULL,'INT',NULL),
('NIACIN','nicotinic acid',NULL,NULL,'INT',NULL),
('METHICILLIN','meticillin',NULL,NULL,'INT',NULL),
('TRICHLOROETHANE','trichloroethane',NULL,NULL,'INT',NULL),
('ENALAPRILAT ANHYDROUS','enalaprilat anhydrous',NULL,NULL,'INT',NULL),
('ENALAPRIL','enalapril',NULL,NULL,'INT',NULL),
('LORAZEPAM','lorazepam',NULL,NULL,'INT',NULL),
('ISOPROPYL ALCOHOL','isopropyl alcohol',NULL,NULL,'INT',NULL),
('GREPAFLOXACIN','grepafloxacin',NULL,NULL,'INT',NULL),
('SAQUINAVIR','saquinavir',NULL,NULL,'INT',NULL),
('INDINAVIR ANHYDROUS','indinavir anhydrous',NULL,NULL,'INT',NULL),
('NELFINAVIR','nelfinavir',NULL,NULL,'INT',NULL),
('AMPRENAVIR','amprenavir',NULL,NULL,'INT',NULL),
('TRIAMTERENE','triamterene',NULL,NULL,'INT',NULL),
('PRONETALOL','pronetalol',NULL,NULL,'INT',NULL),
('CELECOXIB','celecoxib',NULL,NULL,'INT',NULL),
('TRIMETREXATE','trimetrexate',NULL,NULL,'INT',NULL),
('FENOLDOPAM','fenoldopam',NULL,NULL,'INT',NULL),
('ROPINIROLE','ropinirole',NULL,NULL,'INT',NULL),
('MENADIONE','menadione',NULL,NULL,'INT',NULL),
('ETHCHLORVYNOL','ethchlorvynol',NULL,NULL,'INT',NULL),
('TERFENADINE','terfenadine',NULL,NULL,'INT',NULL),
('LEVORPHANOL','levorphanol',NULL,NULL,'INT',NULL),
('DELAVIRDINE','delavirdine',NULL,NULL,'INT',NULL),
('EMEDASTINE','emedastine',NULL,NULL,'INT',NULL),
('PIOGLITAZONE','pioglitazone',NULL,NULL,'INT',NULL),
('FENTANYL','fentanyl',NULL,NULL,'INT',NULL),
('ROSIGLITAZONE','rosiglitazone',NULL,NULL,'INT',NULL),
('MARALIXIBAT CHLORIDE','maralixibat chloride',NULL,NULL,'INT',NULL),
('LOFEXIDINE','lofexidine',NULL,NULL,'INT',NULL),
('PHENTOLAMINE','phentolamine',NULL,NULL,'INT',NULL),
('PLERIXAFOR','plerixafor',NULL,NULL,'INT',NULL),
('TOLOXATONE','toloxatone',NULL,NULL,'INT',NULL),
('MELOXICAM','meloxicam',NULL,NULL,'INT',NULL),
('ACETYLCYSTEINE','acetylcysteine',NULL,NULL,'INT',NULL),
('AMINOLEVULINIC ACID','aminolevulinic acid',NULL,NULL,'INT',NULL),
('CYSTEAMINE','mercaptamine',NULL,NULL,'INT',NULL),
('NALTREXONE','naltrexone',NULL,NULL,'INT',NULL),
('ZAFIRLUKAST','zafirlukast',NULL,NULL,'INT',NULL),
('CEFPROZIL ANHYDROUS, (E)-','cefprozil anhydrous, (e)-',NULL,NULL,'INT',NULL),
('ROFECOXIB','rofecoxib',NULL,NULL,'INT',NULL),
('MOXONIDINE','moxonidine',NULL,NULL,'INT',NULL),
('CUPRIC SULFATE','cupric sulfate',NULL,NULL,'INT',NULL),
('PROCAINAMIDE HYDROCHLORIDE','procainamide hydrochloride',NULL,NULL,'INT',NULL),
('MISOPROSTOL','misoprostol',NULL,NULL,'INT',NULL),
('MACIMORELIN','macimorelin',NULL,NULL,'INT',NULL),
('MEPERIDINE','pethidine',NULL,NULL,'INT',NULL),
('METHAQUALONE','methaqualone',NULL,NULL,'INT',NULL),
('PROBUCOL','probucol',NULL,NULL,'INT',NULL),
('LOXOPROFEN','loxoprofen',NULL,NULL,'INT',NULL),
('TRIENTINE','trientine',NULL,NULL,'INT',NULL),
('ZOMEPIRAC','zomepirac',NULL,NULL,'INT',NULL),
('TERAZOSIN','terazosin',NULL,NULL,'INT',NULL),
('LEVAMFETAMINE','levamfetamine',NULL,NULL,'INT',NULL),
('DEXTROAMPHETAMINE','dexamfetamine',NULL,NULL,'INT',NULL),
('SITAXENTAN','sitaxentan',NULL,NULL,'INT',NULL),
('PYRAZINAMIDE','pyrazinamide',NULL,NULL,'INT',NULL),
('IBUDILAST','ibudilast',NULL,NULL,'INT',NULL),
('SAQUINAVIR MESYLATE','saquinavir mesylate',NULL,NULL,'INT',NULL),
('PENICILLIN V','phenoxymethylpenicillin',NULL,NULL,'INT',NULL),
('CEPHALOTHIN','cefalotin',NULL,NULL,'INT',NULL),
('MILTEFOSINE','miltefosine',NULL,NULL,'INT',NULL),
('LINEZOLID','linezolid',NULL,NULL,'INT',NULL),
('CLIDINIUM','clidinium',NULL,NULL,'INT',NULL),
('MEROPENEM','meropenem',NULL,NULL,'INT',NULL),
('TRAZODONE','trazodone',NULL,NULL,'INT',NULL),
('ETODOLAC','etodolac',NULL,NULL,'INT',NULL),
('PRANLUKAST','pranlukast',NULL,NULL,'INT',NULL),
('NEFAZODONE','nefazodone',NULL,NULL,'INT',NULL),
('THIABENDAZOLE','tiabendazole',NULL,NULL,'INT',NULL),
('XANOMELINE','xanomeline',NULL,NULL,'INT',NULL),
('NAFTIFINE','naftifine',NULL,NULL,'INT',NULL),
('PENTOXIFYLLINE','pentoxifylline',NULL,NULL,'INT',NULL),
('AMITRIPTYLINE','amitriptyline',NULL,NULL,'INT',NULL),
('DIBROMSALAN','dibromsalan',NULL,NULL,'INT',NULL),
('TRIBROMSALAN','tribromsalan',NULL,NULL,'INT',NULL),
('SUMATRIPTAN','sumatriptan',NULL,NULL,'INT',NULL),
('PROPAFENONE','propafenone',NULL,NULL,'INT',NULL)
) AS v(nom, dci, forme, voie, pays, classe)
WHERE NOT EXISTS (
  SELECT 1 FROM medicaments m WHERE LOWER(m.nom) = LOWER(v.nom)
);
