-- chembl_batch_011.sql (80 rows)
INSERT INTO medicaments (nom, dci, forme, voie_administration, pays, classe_therapeutique)
SELECT v.nom, v.dci, v.forme, v.voie, v.pays, v.classe
FROM (VALUES
('AMINOREX','aminorex',NULL,NULL,'INT',NULL),
('MIGALASTAT','migalastat',NULL,NULL,'INT',NULL),
('METHYL SALICYLATE','methyl salicylate',NULL,NULL,'INT',NULL),
('POTASSIUM IODIDE','potassium iodide',NULL,NULL,'INT',NULL),
('PRAVASTATIN','pravastatin',NULL,NULL,'INT',NULL),
('TORSEMIDE','torasemide',NULL,NULL,'INT',NULL),
('LEVOCARNITINE','levocarnitine',NULL,NULL,'INT',NULL),
('PREDNISOLONE ACETATE','prednisolone acetate',NULL,NULL,'INT',NULL),
('CHLORMADINONE ACETATE','chlormadinone',NULL,NULL,'INT',NULL),
('SELENOMETHIONINE','selenomethionine',NULL,NULL,'INT',NULL),
('PINACIDIL ANHYDROUS','pinacidil anhydrous',NULL,NULL,'INT',NULL),
('MOMETASONE FUROATE','mometasone furoate',NULL,NULL,'INT',NULL),
('NORETHINDRONE','norethisterone',NULL,NULL,'INT',NULL),
('ATAZANAVIR','atazanavir',NULL,NULL,'INT',NULL),
('MOEXIPRIL','moexipril',NULL,NULL,'INT',NULL),
('ARGATROBAN','argatroban',NULL,NULL,'INT',NULL),
('SPECTINOMYCIN','spectinomycin',NULL,NULL,'INT',NULL),
('RAMIPRIL','ramipril',NULL,NULL,'INT',NULL),
('LISINOPRIL','lisinopril',NULL,NULL,'INT',NULL),
('AMINOSALICYLIC ACID','aminosalicylic acid',NULL,NULL,'INT',NULL),
('TESTOSTERONE PROPIONATE','testosterone propionate',NULL,NULL,'INT',NULL),
('PRUCALOPRIDE','prucalopride',NULL,NULL,'INT',NULL),
('DESLORATADINE','desloratadine',NULL,NULL,'INT',NULL),
('EPTIFIBATIDE','eptifibatide','Solution injectable','Intraveineuse','INT','Protéine thérapeutique'),
('DEQUALINIUM','dequalinium',NULL,NULL,'INT',NULL),
('DULOXETINE','duloxetine',NULL,NULL,'INT',NULL),
('PEMOLINE','pemoline',NULL,NULL,'INT',NULL),
('TETRABENAZINE','tetrabenazine',NULL,NULL,'INT',NULL),
('HYDROGEN PEROXIDE','hydrogen peroxide',NULL,NULL,'INT',NULL),
('ACETYLCHOLINE CHLORIDE','acetylcholine chloride',NULL,NULL,'INT',NULL),
('ZOLMITRIPTAN','zolmitriptan',NULL,NULL,'INT',NULL),
('PHOSPHORIC ACID','phosphoric acid',NULL,NULL,'INT',NULL),
('DEQUALINIUM CHLORIDE','dequalinium chloride',NULL,NULL,'INT',NULL),
('DECAMETHONIUM','decamethonium',NULL,NULL,'INT',NULL),
('TUBOCURARINE','tubocurarine',NULL,NULL,'INT',NULL),
('SULFAGUANIDINE','sulfaguanidine',NULL,NULL,'INT',NULL),
('SULFAMETHIZOLE','sulfamethizole',NULL,NULL,'INT',NULL),
('PHENIRAMINE','pheniramine',NULL,NULL,'INT',NULL),
('PRILOCAINE','prilocaine',NULL,NULL,'INT',NULL),
('PROPOXYCAINE','propoxycaine',NULL,NULL,'INT',NULL),
('PROPARACAINE','proxymetacaine',NULL,NULL,'INT',NULL),
('HEXYLCAINE','hexylcaine',NULL,NULL,'INT',NULL),
('PRAMOXINE','pramocaine',NULL,NULL,'INT',NULL),
('BENOXINATE','oxybuprocaine',NULL,NULL,'INT',NULL),
('THIOTHIXENE','tiotixene',NULL,NULL,'INT',NULL),
('BUTAMBEN','butamben',NULL,NULL,'INT',NULL),
('CIPROFLOXACIN HYDROCHLORIDE','ciprofloxacin hydrochloride',NULL,NULL,'INT',NULL),
('NELFINAVIR MESYLATE','nelfinavir mesylate',NULL,NULL,'INT',NULL),
('ETHOPROPAZINE','profenamine',NULL,NULL,'INT',NULL),
('CINOXACIN','cinoxacin',NULL,NULL,'INT',NULL),
('CANGRELOR','cangrelor',NULL,NULL,'INT',NULL),
('CARBENICILLIN','carbenicillin',NULL,NULL,'INT',NULL),
('BENOXAPROFEN','benoxaprofen',NULL,NULL,'INT',NULL),
('PHENYLEPHRINE','phenylephrine',NULL,NULL,'INT',NULL),
('RAMELTEON','ramelteon',NULL,NULL,'INT',NULL),
('RABEPRAZOLE','rabeprazole',NULL,NULL,'INT',NULL),
('TINIDAZOLE','tinidazole',NULL,NULL,'INT',NULL),
('SULCONAZOLE','sulconazole',NULL,NULL,'INT',NULL),
('ZOPICLONE','zopiclone',NULL,NULL,'INT',NULL),
('PENICILLIN G POTASSIUM','penicillin g potassium',NULL,NULL,'INT',NULL),
('SODIUM NITROPRUSSIDE','sodium nitroprusside',NULL,NULL,'INT',NULL),
('ACRIVASTINE','acrivastine',NULL,NULL,'INT',NULL),
('TOLVAPTAN','tolvaptan',NULL,NULL,'INT',NULL),
('OXYPHENBUTAZONE ANHYDROUS','oxyphenbutazone anhydrous',NULL,NULL,'INT',NULL),
('OSELTAMIVIR','oseltamivir',NULL,NULL,'INT',NULL),
('PERAMIVIR ANHYDROUS','peramivir anhydrous',NULL,NULL,'INT',NULL),
('IBUFENAC','ibufenac',NULL,NULL,'INT',NULL),
('OXYBUTYNIN','oxybutynin',NULL,NULL,'INT',NULL),
('ERTAPENEM SODIUM','ertapenem sodium',NULL,NULL,'INT',NULL),
('CARISOPRODOL','carisoprodol',NULL,NULL,'INT',NULL),
('DEFEROXAMINE MESYLATE','deferoxamine mesylate',NULL,NULL,'INT',NULL),
('LISINOPRIL ANHYDROUS','lisinopril anhydrous',NULL,NULL,'INT',NULL),
('AZELAIC ACID','azelaic acid',NULL,NULL,'INT',NULL),
('BENZYL BENZOATE','benzyl benzoate',NULL,NULL,'INT',NULL),
('PROPANTHELINE BROMIDE','propantheline bromide',NULL,NULL,'INT',NULL),
('TRIPELENNAMINE','tripelennamine',NULL,NULL,'INT',NULL),
('PHENAZOPYRIDINE','phenazopyridine',NULL,NULL,'INT',NULL),
('CYCLOFENIL','cyclofenil',NULL,NULL,'INT',NULL),
('SULFACARBAMIDE','sulfacarbamide',NULL,NULL,'INT',NULL),
('SULFABENZAMIDE','sulfabenzamide',NULL,NULL,'INT',NULL)
) AS v(nom, dci, forme, voie, pays, classe)
WHERE NOT EXISTS (
  SELECT 1 FROM medicaments m WHERE LOWER(m.nom) = LOWER(v.nom)
);
