-- chembl_batch_024.sql (80 rows)
INSERT INTO medicaments (nom, dci, forme, voie_administration, pays, classe_therapeutique)
SELECT v.nom, v.dci, v.forme, v.voie, v.pays, v.classe
FROM (VALUES
('CEFTAZIDIME SODIUM','ceftazidime sodium',NULL,NULL,'INT',NULL),
('TRIPELENNAMINE CITRATE','tripelennamine citrate',NULL,NULL,'INT',NULL),
('IOCETAMIC ACID','iocetamic acid',NULL,NULL,'INT',NULL),
('TRIDIHEXETHYL CHLORIDE','tridihexethyl chloride',NULL,NULL,'INT',NULL),
('WARFARIN POTASSIUM','warfarin potassium',NULL,NULL,'INT',NULL),
('TOCAINIDE HYDROCHLORIDE','tocainide hydrochloride',NULL,NULL,'INT',NULL),
('FLUPREDNISOLONE','fluprednisolone',NULL,NULL,'INT',NULL),
('LEUPROLIDE ACETATE','leuprolide acetate','Solution injectable','Intraveineuse','INT','Protéine thérapeutique'),
('CINACALCET HYDROCHLORIDE','cinacalcet hydrochloride',NULL,NULL,'INT',NULL),
('DEXRAZOXANE HYDROCHLORIDE','dexrazoxane hydrochloride',NULL,NULL,'INT',NULL),
('TROVAFLOXACIN MESYLATE','trovafloxacin mesylate',NULL,NULL,'INT',NULL),
('CITALOPRAM HYDROBROMIDE','citalopram hydrobromide',NULL,NULL,'INT',NULL),
('DEXTROAMPHETAMINE ADIPATE','dextroamphetamine adipate',NULL,NULL,'INT',NULL),
('PHENOXYBENZAMINE HYDROCHLORIDE','phenoxybenzamine hydrochloride',NULL,NULL,'INT',NULL),
('CISAPRIDE MONOHYDRATE','cisapride monohydrate',NULL,NULL,'INT',NULL),
('TRICLOFOS SODIUM','triclofos sodium',NULL,NULL,'INT',NULL),
('METHYPRYLON','methyprylon',NULL,NULL,'INT',NULL),
('OXYMETAZOLINE HYDROCHLORIDE','oxymetazoline hydrochloride',NULL,NULL,'INT',NULL),
('OXYMORPHONE HYDROCHLORIDE','oxymorphone hydrochloride',NULL,NULL,'INT',NULL),
('CLEMASTINE FUMARATE','clemastine fumarate',NULL,NULL,'INT',NULL),
('CYCLOPHOSPHAMIDE','cyclophosphamide',NULL,NULL,'INT',NULL),
('TECHNETIUM TC 99M SUCCIMER','technetium tc 99m succimer',NULL,NULL,'INT',NULL),
('TRAZODONE HYDROCHLORIDE','trazodone hydrochloride',NULL,NULL,'INT',NULL),
('TRAVOPROST','travoprost',NULL,NULL,'INT',NULL),
('CALCIUM ACETATE','calcium acetate',NULL,NULL,'INT',NULL),
('TALBUTAL','talbutal',NULL,NULL,'INT',NULL),
('SOLIFENACIN SUCCINATE','solifenacin succinate',NULL,NULL,'INT',NULL),
('DICLOFENAC POTASSIUM','diclofenac potassium',NULL,NULL,'INT',NULL),
('DILTIAZEM MALATE','diltiazem malate',NULL,NULL,'INT',NULL),
('NAPROXEN SODIUM','naproxen sodium',NULL,NULL,'INT',NULL),
('NORELGESTROMIN','norelgestromin',NULL,NULL,'INT',NULL),
('AZELASTINE HYDROCHLORIDE','azelastine hydrochloride',NULL,NULL,'INT',NULL),
('DOXERCALCIFEROL','doxercalciferol',NULL,NULL,'INT',NULL),
('ACEBUTOLOL HYDROCHLORIDE','acebutolol hydrochloride',NULL,NULL,'INT',NULL),
('ACETAZOLAMIDE SODIUM','acetazolamide sodium',NULL,NULL,'INT',NULL),
('LEVOMETHADYL ACETATE HYDROCHLORIDE','levomethadyl acetate hydrochloride',NULL,NULL,'INT',NULL),
('ARTICAINE HYDROCHLORIDE','articaine hydrochloride',NULL,NULL,'INT',NULL),
('PIPERACILLIN SODIUM','piperacillin sodium',NULL,NULL,'INT',NULL),
('PROPYLIODONE','propyliodone',NULL,NULL,'INT',NULL),
('FLECAINIDE ACETATE','flecainide acetate',NULL,NULL,'INT',NULL),
('IRON SUCROSE','iron sucrose',NULL,NULL,'INT',NULL),
('METHADONE HYDROCHLORIDE','methadone hydrochloride',NULL,NULL,'INT',NULL),
('LITHIUM CARBONATE','lithium carbonate',NULL,NULL,'INT',NULL),
('CYCRIMINE HYDROCHLORIDE','cycrimine hydrochloride',NULL,NULL,'INT',NULL),
('GLUCONOLACTONE','gluconolactone',NULL,NULL,'INT',NULL),
('FERROUS SULFATE','ferrous sulfate',NULL,NULL,'INT',NULL),
('SPIRAPRIL HYDROCHLORIDE','spirapril hydrochloride',NULL,NULL,'INT',NULL),
('TERBINAFINE HYDROCHLORIDE','terbinafine hydrochloride',NULL,NULL,'INT',NULL),
('DIPIVEFRIN HYDROCHLORIDE','dipivefrin hydrochloride',NULL,NULL,'INT',NULL),
('TECHNETIUM TC 99M ETIDRONATE','technetium tc 99m etidronate',NULL,NULL,'INT',NULL),
('OXICONAZOLE NITRATE','oxiconazole nitrate',NULL,NULL,'INT',NULL),
('LEVOBETAXOLOL HYDROCHLORIDE','levobetaxolol hydrochloride',NULL,NULL,'INT',NULL),
('DIATRIZOATE MEGLUMINE','diatrizoate meglumine',NULL,NULL,'INT',NULL),
('PROCAINE HYDROCHLORIDE','procaine hydrochloride',NULL,NULL,'INT',NULL),
('METHYLERGONOVINE MALEATE','methylergonovine maleate',NULL,NULL,'INT',NULL),
('HALCINONIDE','halcinonide',NULL,NULL,'INT',NULL),
('HYDROXYPROGESTERONE CAPROATE','hydroxyprogesterone caproate',NULL,NULL,'INT',NULL),
('GANCICLOVIR SODIUM','ganciclovir sodium',NULL,NULL,'INT',NULL),
('HOMATROPINE METHYLBROMIDE','homatropine methylbromide',NULL,NULL,'INT',NULL),
('PENICILLIN V POTASSIUM','penicillin v potassium',NULL,NULL,'INT',NULL),
('DYDROGESTERONE','dydrogesterone',NULL,NULL,'INT',NULL),
('FLUPHENAZINE DECANOATE','fluphenazine decanoate',NULL,NULL,'INT',NULL),
('TICARCILLIN DISODIUM','ticarcillin disodium',NULL,NULL,'INT',NULL),
('TECHNETIUM TC 99M TETROFOSMIN','technetium tc 99m tetrofosmin',NULL,NULL,'INT',NULL),
('ISOSULFAN BLUE','isosulfan blue',NULL,NULL,'INT',NULL),
('METYROSINE','metirosine',NULL,NULL,'INT',NULL),
('MELPHALAN HYDROCHLORIDE','melphalan hydrochloride',NULL,NULL,'INT',NULL),
('LOTEPREDNOL ETABONATE','loteprednol',NULL,NULL,'INT',NULL),
('PERFLUBRON','perflubron',NULL,NULL,'INT',NULL),
('PHENYL AMINOSALICYLATE','fenamisal',NULL,NULL,'INT',NULL),
('METRONIDAZOLE HYDROCHLORIDE','metronidazole hydrochloride',NULL,NULL,'INT',NULL),
('TIMOLOL MALEATE','timolol maleate',NULL,NULL,'INT',NULL),
('PHENTOLAMINE MESYLATE','phentolamine mesylate',NULL,NULL,'INT',NULL),
('TOLBUTAMIDE SODIUM','tolbutamide sodium',NULL,NULL,'INT',NULL),
('FLAVOXATE HYDROCHLORIDE','flavoxate hydrochloride',NULL,NULL,'INT',NULL),
('FLUMETHASONE PIVALATE','flumethasone pivalate',NULL,NULL,'INT',NULL),
('TRIAMCINOLONE HEXACETONIDE','triamcinolone hexacetonide',NULL,NULL,'INT',NULL),
('WARFARIN SODIUM','warfarin sodium',NULL,NULL,'INT',NULL),
('DIPHEMANIL METHYLSULFATE','diphemanil metilsulfate',NULL,NULL,'INT',NULL),
('MINOCYCLINE HYDROCHLORIDE','minocycline hydrochloride',NULL,NULL,'INT',NULL)
) AS v(nom, dci, forme, voie, pays, classe)
WHERE NOT EXISTS (
  SELECT 1 FROM medicaments m WHERE LOWER(m.nom) = LOWER(v.nom)
);
