-- chembl_batch_019.sql (80 rows)
INSERT INTO medicaments (nom, dci, forme, voie_administration, pays, classe_therapeutique)
SELECT v.nom, v.dci, v.forme, v.voie, v.pays, v.classe
FROM (VALUES
('CLARITHROMYCIN','clarithromycin',NULL,NULL,'INT',NULL),
('QUIZARTINIB','quizartinib',NULL,NULL,'INT',NULL),
('ARTEMETHER','artemether',NULL,NULL,'INT',NULL),
('OBETICHOLIC ACID','obeticholic acid',NULL,NULL,'INT',NULL),
('FLORBETABEN F18','florbetaben (18f)',NULL,NULL,'INT',NULL),
('FLUMEXADOL','flumexadol',NULL,NULL,'INT',NULL),
('SODIUM PHENYLBUTYRATE','sodium phenylbutyrate',NULL,NULL,'INT',NULL),
('FLUTEMETAMOL','flutemetamol',NULL,NULL,'INT',NULL),
('TOBRAMYCIN','tobramycin',NULL,NULL,'INT',NULL),
('SCOPOLAMINE','scopolamine',NULL,NULL,'INT',NULL),
('TIRBANIBULIN','tirbanibulin',NULL,NULL,'INT',NULL),
('EDETATE DISODIUM ANHYDROUS','edetate disodium anhydrous',NULL,NULL,'INT',NULL),
('CLOFARABINE','clofarabine',NULL,NULL,'INT',NULL),
('FENSPIRIDE','fenspiride',NULL,NULL,'INT',NULL),
('DIGOXIN','digoxin',NULL,NULL,'INT',NULL),
('DYPHYLLINE','diprophylline',NULL,NULL,'INT',NULL),
('CLINDAMYCIN','clindamycin',NULL,NULL,'INT',NULL),
('DOXAPRAM','doxapram',NULL,NULL,'INT',NULL),
('CONIVAPTAN','conivaptan',NULL,NULL,'INT',NULL),
('ESTRAMUSTINE PHOSPHATE','estramustine phosphate',NULL,NULL,'INT',NULL),
('FOSFOMYCIN','fosfomycin',NULL,NULL,'INT',NULL),
('TERBUTALINE','terbutaline',NULL,NULL,'INT',NULL),
('PROCYCLIDINE HYDROCHLORIDE','procyclidine hydrochloride',NULL,NULL,'INT',NULL),
('TOCAINIDE','tocainide',NULL,NULL,'INT',NULL),
('HYDROFLUMETHIAZIDE','hydroflumethiazide',NULL,NULL,'INT',NULL),
('LEVOMEPROMAZINE','levomepromazine',NULL,NULL,'INT',NULL),
('DESOXIMETASONE','desoximetasone',NULL,NULL,'INT',NULL),
('BETHANECHOL CHLORIDE','bethanechol chloride',NULL,NULL,'INT',NULL),
('PROPOXYCAINE HYDROCHLORIDE','propoxycaine hydrochloride',NULL,NULL,'INT',NULL),
('LEVAMISOLE HYDROCHLORIDE','levamisole hydrochloride',NULL,NULL,'INT',NULL),
('SODIUM ASCORBATE','sodium ascorbate',NULL,NULL,'INT',NULL),
('CLOPIDOGREL','clopidogrel',NULL,NULL,'INT',NULL),
('CAPECITABINE','capecitabine',NULL,NULL,'INT',NULL),
('MONOMETHYL FUMARATE','monomethyl fumarate',NULL,NULL,'INT',NULL),
('CRIZOTINIB','crizotinib',NULL,NULL,'INT',NULL),
('OLODATEROL','olodaterol',NULL,NULL,'INT',NULL),
('CHLORPHENESIN CARBAMATE','chlorphenesin',NULL,NULL,'INT',NULL),
('CARBENICILLIN DISODIUM','carbenicillin disodium',NULL,NULL,'INT',NULL),
('MIDOSTAURIN','midostaurin',NULL,NULL,'INT',NULL),
('BRIVARACETAM','brivaracetam',NULL,NULL,'INT',NULL),
('IMIPENEM','imipenem',NULL,NULL,'INT',NULL),
('ERLOTINIB HYDROCHLORIDE','erlotinib hydrochloride',NULL,NULL,'INT',NULL),
('METAXALONE','metaxalone',NULL,NULL,'INT',NULL),
('VARENICLINE','varenicline',NULL,NULL,'INT',NULL),
('MOMELOTINIB','momelotinib',NULL,NULL,'INT',NULL),
('ROPIVACAINE','ropivacaine',NULL,NULL,'INT',NULL),
('BENDAZAC','bendazac',NULL,NULL,'INT',NULL),
('OPICAPONE','opicapone',NULL,NULL,'INT',NULL),
('TRYPAN BLUE FREE ACID','trypan blue free acid',NULL,NULL,'INT',NULL),
('INDIGOTINDISULFONATE','indigotindisulfonate',NULL,NULL,'INT',NULL),
('METHYL AMINOLEVULINATE','methyl aminolevulinate',NULL,NULL,'INT',NULL),
('FLUDARABINE PHOSPHATE','fludarabine phosphate',NULL,NULL,'INT',NULL),
('IOTHALAMATE SODIUM','iothalamate sodium',NULL,NULL,'INT',NULL),
('PIRBUTEROL','pirbuterol',NULL,NULL,'INT',NULL),
('VALRUBICIN','valrubicin',NULL,NULL,'INT',NULL),
('NIRAPARIB','niraparib',NULL,NULL,'INT',NULL),
('BRETYLIUM TOSYLATE','bretylium tosilate',NULL,NULL,'INT',NULL),
('CEFUROXIME AXETIL','cefuroxime axetil',NULL,NULL,'INT',NULL),
('2-MERCAPTOETHANESULFONIC ACID','mesna free acid',NULL,NULL,'INT',NULL),
('INDACATEROL','indacaterol',NULL,NULL,'INT',NULL),
('CANGRELOR TETRASODIUM','cangrelor tetrasodium',NULL,NULL,'INT',NULL),
('EPLERENONE','eplerenone',NULL,NULL,'INT',NULL),
('WATER','water',NULL,NULL,'INT',NULL),
('PONESIMOD','ponesimod',NULL,NULL,'INT',NULL),
('SUVOREXANT','suvorexant',NULL,NULL,'INT',NULL),
('CLOPIDOGREL BISULFATE','clopidogrel bisulfate',NULL,NULL,'INT',NULL),
('AMIODARONE HYDROCHLORIDE','amiodarone hydrochloride',NULL,NULL,'INT',NULL),
('TRICLABENDAZOLE','triclabendazole',NULL,NULL,'INT',NULL),
('ENZALUTAMIDE','enzalutamide',NULL,NULL,'INT',NULL),
('SALMETEROL XINAFOATE','salmeterol xinafoate',NULL,NULL,'INT',NULL),
('VILANTEROL TRIFENATATE','vilanterol trifenatate',NULL,NULL,'INT',NULL),
('CLOBETASOL PROPIONATE','clobetasol',NULL,NULL,'INT',NULL),
('AMMONIA SOLUTION, STRONG','ammonia solution, strong',NULL,NULL,'INT',NULL),
('NITROUS ACID','nitrous acid',NULL,NULL,'INT',NULL),
('VINCAMINE','vincamine',NULL,NULL,'INT',NULL),
('IODIPAMIDE','adipiodone',NULL,NULL,'INT',NULL),
('FEBUXOSTAT','febuxostat',NULL,NULL,'INT',NULL),
('PONATINIB','ponatinib',NULL,NULL,'INT',NULL),
('AFATINIB','afatinib',NULL,NULL,'INT',NULL),
('RUCAPARIB','rucaparib',NULL,NULL,'INT',NULL)
) AS v(nom, dci, forme, voie, pays, classe)
WHERE NOT EXISTS (
  SELECT 1 FROM medicaments m WHERE LOWER(m.nom) = LOWER(v.nom)
);
