-- chembl_batch_036.sql (80 rows)
INSERT INTO medicaments (nom, dci, forme, voie_administration, pays, classe_therapeutique)
SELECT v.nom, v.dci, v.forme, v.voie, v.pays, v.classe
FROM (VALUES
('MAGNESIUM TRISILICATE','magnesium trisilicate',NULL,NULL,'INT',NULL),
('SODIUM CHROMATE CR 51','sodium chromate (51cr)',NULL,NULL,'INT',NULL),
('UREA C 14','urea c 14',NULL,NULL,'INT',NULL),
('BACITRACIN ZINC','bacitracin zinc','Solution injectable','Intraveineuse','INT','Protéine thérapeutique'),
('SODIUM PERTECHNETATE TC 99M','sodium pertechnetate tc 99m',NULL,NULL,'INT',NULL),
('INAMRINONE LACTATE','inamrinone lactate',NULL,NULL,'INT',NULL),
('AMINOSALICYLATE SODIUM','aminosalicylate sodium',NULL,NULL,'INT',NULL),
('LANTHANUM CARBONATE','lanthanum carbonate',NULL,NULL,'INT',NULL),
('UREA C 13','urea c 13',NULL,NULL,'INT',NULL),
('SODIUM THIOSULFATE','sodium thiosulfate',NULL,NULL,'INT',NULL),
('MANGAFODIPIR TRISODIUM','mangafodipir trisodium',NULL,NULL,'INT',NULL),
('CYANOCOBALAMIN CO 57','cyanocobalamin (57co)',NULL,NULL,'INT',NULL),
('TECHNETIUM TC 99M PENTETATE','technetium tc 99m pentetate',NULL,NULL,'INT',NULL),
('SAMARIUM SM 153 LEXIDRONAM PENTASODIUM','samarium sm 153 lexidronam pentasodium',NULL,NULL,'INT',NULL),
('NITROPRUSSIDE','nitroprusside',NULL,NULL,'INT',NULL),
('CETRORELIX ACETATE','cetrorelix acetate','Solution injectable','Intraveineuse','INT','Protéine thérapeutique'),
('FENOPROFEN CALCIUM','fenoprofen calcium',NULL,NULL,'INT',NULL),
('HYDROXOCOBALAMIN','hydroxocobalamin',NULL,NULL,'INT',NULL),
('LITHIUM CITRATE','lithium citrate',NULL,NULL,'INT',NULL),
('EMEDASTINE DIFUMARATE','emedastine difumarate',NULL,NULL,'INT',NULL),
('GADOXETATE DISODIUM','gadoxetate disodium',NULL,NULL,'INT',NULL),
('LEVOTHYROXINE SODIUM','levothyroxine sodium',NULL,NULL,'INT',NULL),
('MANGANESE SULFATE','manganese sulfate',NULL,NULL,'INT',NULL),
('TOFACITINIB CITRATE','tofacitinib citrate',NULL,NULL,'INT',NULL),
('MORPHINE SULFATE','morphine sulfate',NULL,NULL,'INT',NULL),
('PRAMLINTIDE','pramlintide','Solution injectable','Intraveineuse','INT','Protéine thérapeutique'),
('COSYNTROPIN','tetracosactide','Solution injectable','Intraveineuse','INT','Protéine thérapeutique'),
('AZILSARTAN KAMEDOXOMIL','azilsartan kamedoxomil',NULL,NULL,'INT',NULL),
('COLESTILAN CHLORIDE','colestilan',NULL,NULL,'INT',NULL),
('DAPAGLIFLOZIN PROPANEDIOL','dapagliflozin propanediol',NULL,NULL,'INT',NULL),
('TASIMELTEON','tasimelteon',NULL,NULL,'INT',NULL),
('DROXIDOPA','droxidopa',NULL,NULL,'INT',NULL),
('FOSTAMATINIB','fostamatinib',NULL,NULL,'INT',NULL),
('TAFAMIDIS','tafamidis',NULL,NULL,'INT',NULL),
('PIXANTRONE DIMALEATE','pixantrone dimaleate',NULL,NULL,'INT',NULL),
('OMADACYCLINE TOSYLATE','omadacycline tosylate',NULL,NULL,'INT',NULL),
('PLECANATIDE','plecanatide','Solution injectable','Intraveineuse','INT','Protéine thérapeutique'),
('CABOZANTINIB S-MALATE','cabozantinib s-malate',NULL,NULL,'INT',NULL),
('LUMACAFTOR','lumacaftor',NULL,NULL,'INT',NULL),
('CEFTOLOZANE','ceftolozane',NULL,NULL,'INT',NULL),
('MACITENTAN','macitentan',NULL,NULL,'INT',NULL),
('TRAMETINIB','trametinib',NULL,NULL,'INT',NULL),
('EFINACONAZOLE','efinaconazole',NULL,NULL,'INT',NULL),
('AVATROMBOPAG','avatrombopag',NULL,NULL,'INT',NULL),
('CYANOCOBALAMIN CO 60','cyanocobalamin (60co)',NULL,NULL,'INT',NULL),
('CLOMACRAN PHOSPHATE','clomacran phosphate',NULL,NULL,'INT',NULL),
('DIBENZEPIN HYDROCHLORIDE','dibenzepin hydrochloride',NULL,NULL,'INT',NULL),
('CYANOCOBALAMIN CO 58','cyanocobalamin (58co)',NULL,NULL,'INT',NULL),
('INSULIN DETEMIR','insulin detemir','Solution injectable','Intraveineuse','INT','Protéine thérapeutique'),
('MOXIDECTIN','moxidectin',NULL,NULL,'INT',NULL),
('ANAGESTONE ACETATE','anagestone',NULL,NULL,'INT',NULL),
('AMOPROXAN','amoproxan',NULL,NULL,'INT',NULL),
('PYROVALERONE HYDROCHLORIDE','pyrovalerone hydrochloride',NULL,NULL,'INT',NULL),
('SULFADICRAMIDE','sulfadicramide',NULL,NULL,'INT',NULL),
('TEDUGLUTIDE','teduglutide','Solution injectable','Intraveineuse','INT','Protéine thérapeutique'),
('VORTIOXETINE','vortioxetine',NULL,NULL,'INT',NULL),
('INDIGOTINDISULFONATE SODIUM','indigotindisulfonate sodium',NULL,NULL,'INT',NULL),
('PHOLCODINE','pholcodine',NULL,NULL,'INT',NULL),
('PROXIBARBAL','proxibarbal',NULL,NULL,'INT',NULL),
('POTASSIUM BITARTRATE','potassium bitartrate',NULL,NULL,'INT',NULL),
('PROPYLHEXEDRINE','propylhexedrine',NULL,NULL,'INT',NULL),
('PROPANIDID','propanidid',NULL,NULL,'INT',NULL),
('OSPEMIFENE','ospemifene',NULL,NULL,'INT',NULL),
('TAUROLIDINE','taurolidine',NULL,NULL,'INT',NULL),
('THENALIDINE','thenalidine',NULL,NULL,'INT',NULL),
('ZIPEPROL','zipeprol',NULL,NULL,'INT',NULL),
('TETRAZEPAM','tetrazepam',NULL,NULL,'INT',NULL),
('FENPROPOREX','fenproporex',NULL,NULL,'INT',NULL),
('VERALIPRIDE','veralipride',NULL,NULL,'INT',NULL),
('DIVALPROEX SODIUM','valproate semisodium',NULL,NULL,'INT',NULL),
('VINFLUNINE DITARTRATE','vinflunine ditartrate',NULL,NULL,'INT',NULL),
('DELAFLOXACIN','delafloxacin',NULL,NULL,'INT',NULL),
('DELAFLOXACIN MEGLUMINE','delafloxacin meglumine',NULL,NULL,'INT',NULL),
('PALOVAROTENE','palovarotene',NULL,NULL,'INT',NULL),
('LOMITAPIDE MESYLATE','lomitapide mesylate',NULL,NULL,'INT',NULL),
('TEDIZOLID PHOSPHATE','tedizolid phosphate',NULL,NULL,'INT',NULL),
('TAFAMIDIS MEGLUMINE','tafamidis meglumine',NULL,NULL,'INT',NULL),
('RIFAMYCIN SODIUM','rifamycin sodium',NULL,NULL,'INT',NULL),
('EDOXABAN TOSYLATE','edoxaban tosylate',NULL,NULL,'INT',NULL),
('SELUMETINIB SULFATE','selumetinib sulfate',NULL,NULL,'INT',NULL)
) AS v(nom, dci, forme, voie, pays, classe)
WHERE NOT EXISTS (
  SELECT 1 FROM medicaments m WHERE LOWER(m.nom) = LOWER(v.nom)
);
