-- icd10v2_batch_115.sql (80 rows)
INSERT INTO pathologies (nom_fr, nom_en, categorie, icd10_code)
VALUES
('Postprocedural hémorragie of ear and mastoid process following autre procedure','Postprocedural hemorrhage of ear and mastoid process following other procedure','Maladies de l''oreille et de l''apophyse mastoïde','H95.42'),
('Postprocedural hematoma of ear and mastoid process following a procedure on the ear and mastoid process','Postprocedural hematoma of ear and mastoid process following a procedure on the ear and mastoid process','Maladies de l''oreille et de l''apophyse mastoïde','H95.51'),
('Postprocedural hematoma of ear and mastoid process following autre procedure','Postprocedural hematoma of ear and mastoid process following other procedure','Maladies de l''oreille et de l''apophyse mastoïde','H95.52'),
('Postprocedural seroma of ear and mastoid process following a procedure on the ear and mastoid process','Postprocedural seroma of ear and mastoid process following a procedure on the ear and mastoid process','Maladies de l''oreille et de l''apophyse mastoïde','H95.53'),
('Postprocedural seroma of ear and mastoid process following autre procedure','Postprocedural seroma of ear and mastoid process following other procedure','Maladies de l''oreille et de l''apophyse mastoïde','H95.54'),
('Postprocedural sténose of right external ear canal','Postprocedural stenosis of right external ear canal','Maladies de l''oreille et de l''apophyse mastoïde','H95.811'),
('Postprocedural sténose of left external ear canal','Postprocedural stenosis of left external ear canal','Maladies de l''oreille et de l''apophyse mastoïde','H95.812'),
('Postprocedural sténose of external ear canal, bilateral','Postprocedural stenosis of external ear canal, bilateral','Maladies de l''oreille et de l''apophyse mastoïde','H95.813'),
('Postprocedural sténose of non spécifié external ear canal','Postprocedural stenosis of unspecified external ear canal','Maladies de l''oreille et de l''apophyse mastoïde','H95.819'),
('autre intraoperative complications and disorders of the ear and mastoid process, not elsewhere classified','Other intraoperative complications and disorders of the ear and mastoid process, not elsewhere classified','Maladies de l''oreille et de l''apophyse mastoïde','H95.88'),
('autre postprocedural complications and disorders of the ear and mastoid process, not elsewhere classified','Other postprocedural complications and disorders of the ear and mastoid process, not elsewhere classified','Maladies de l''oreille et de l''apophyse mastoïde','H95.89'),
('Rheumatic fever without heart involvement','Rheumatic fever without heart involvement','Maladies de l''appareil circulatoire','I00'),
('aigu rheumatic pericarditis','Acute rheumatic pericarditis','Maladies de l''appareil circulatoire','I01.0'),
('aigu rheumatic endocarditis','Acute rheumatic endocarditis','Maladies de l''appareil circulatoire','I01.1'),
('aigu rheumatic myocarditis','Acute rheumatic myocarditis','Maladies de l''appareil circulatoire','I01.2'),
('autre aigu rheumatic heart maladie','Other acute rheumatic heart disease','Maladies de l''appareil circulatoire','I01.8'),
('aigu rheumatic heart maladie, non spécifié','Acute rheumatic heart disease, unspecified','Maladies de l''appareil circulatoire','I01.9'),
('Rheumatic chorea with heart involvement','Rheumatic chorea with heart involvement','Maladies de l''appareil circulatoire','I02.0'),
('Rheumatic chorea without heart involvement','Rheumatic chorea without heart involvement','Maladies de l''appareil circulatoire','I02.9'),
('Rheumatic mitral sténose','Rheumatic mitral stenosis','Maladies de l''appareil circulatoire','I05.0'),
('Rheumatic mitral insufficiency','Rheumatic mitral insufficiency','Maladies de l''appareil circulatoire','I05.1'),
('Rheumatic mitral sténose with insufficiency','Rheumatic mitral stenosis with insufficiency','Maladies de l''appareil circulatoire','I05.2'),
('autre rheumatic mitral valve diseases','Other rheumatic mitral valve diseases','Maladies de l''appareil circulatoire','I05.8'),
('Rheumatic mitral valve maladie, non spécifié','Rheumatic mitral valve disease, unspecified','Maladies de l''appareil circulatoire','I05.9'),
('Rheumatic aortic sténose','Rheumatic aortic stenosis','Maladies de l''appareil circulatoire','I06.0'),
('Rheumatic aortic insufficiency','Rheumatic aortic insufficiency','Maladies de l''appareil circulatoire','I06.1'),
('Rheumatic aortic sténose with insufficiency','Rheumatic aortic stenosis with insufficiency','Maladies de l''appareil circulatoire','I06.2'),
('autre rheumatic aortic valve diseases','Other rheumatic aortic valve diseases','Maladies de l''appareil circulatoire','I06.8'),
('Rheumatic aortic valve maladie, non spécifié','Rheumatic aortic valve disease, unspecified','Maladies de l''appareil circulatoire','I06.9'),
('Rheumatic tricuspid sténose','Rheumatic tricuspid stenosis','Maladies de l''appareil circulatoire','I07.0'),
('Rheumatic tricuspid insufficiency','Rheumatic tricuspid insufficiency','Maladies de l''appareil circulatoire','I07.1'),
('Rheumatic tricuspid sténose and insufficiency','Rheumatic tricuspid stenosis and insufficiency','Maladies de l''appareil circulatoire','I07.2'),
('autre rheumatic tricuspid valve diseases','Other rheumatic tricuspid valve diseases','Maladies de l''appareil circulatoire','I07.8'),
('Rheumatic tricuspid valve maladie, non spécifié','Rheumatic tricuspid valve disease, unspecified','Maladies de l''appareil circulatoire','I07.9'),
('Rheumatic disorders of both mitral and aortic valves','Rheumatic disorders of both mitral and aortic valves','Maladies de l''appareil circulatoire','I08.0'),
('Rheumatic disorders of both mitral and tricuspid valves','Rheumatic disorders of both mitral and tricuspid valves','Maladies de l''appareil circulatoire','I08.1'),
('Rheumatic disorders of both aortic and tricuspid valves','Rheumatic disorders of both aortic and tricuspid valves','Maladies de l''appareil circulatoire','I08.2'),
('Combined rheumatic disorders of mitral, aortic and tricuspid valves','Combined rheumatic disorders of mitral, aortic and tricuspid valves','Maladies de l''appareil circulatoire','I08.3'),
('autre rheumatic multiple valve diseases','Other rheumatic multiple valve diseases','Maladies de l''appareil circulatoire','I08.8'),
('Rheumatic multiple valve maladie, non spécifié','Rheumatic multiple valve disease, unspecified','Maladies de l''appareil circulatoire','I08.9'),
('Rheumatic myocarditis','Rheumatic myocarditis','Maladies de l''appareil circulatoire','I09.0'),
('Rheumatic diseases of endocardium, valve non spécifié','Rheumatic diseases of endocardium, valve unspecified','Maladies de l''appareil circulatoire','I09.1'),
('chronique rheumatic pericarditis','Chronic rheumatic pericarditis','Maladies de l''appareil circulatoire','I09.2'),
('Rheumatic heart insuffisance','Rheumatic heart failure','Maladies de l''appareil circulatoire','I09.81'),
('autre specified rheumatic heart diseases','Other specified rheumatic heart diseases','Maladies de l''appareil circulatoire','I09.89'),
('Rheumatic heart maladie, non spécifié','Rheumatic heart disease, unspecified','Maladies de l''appareil circulatoire','I09.9'),
('Hypertension essentielle (primaire)','Essential (primary) hypertension','Maladies de l''appareil circulatoire','I10'),
('Cardiopathie hypertensive disease with heart failure','Hypertensive heart disease with heart failure','Maladies de l''appareil circulatoire','I11.0'),
('Cardiopathie hypertensive disease without heart failure','Hypertensive heart disease without heart failure','Maladies de l''appareil circulatoire','I11.9'),
('Néphropathie hypertensive chronique disease with stage 5 chronic kidney disease or end stage renal disease','Hypertensive chronic kidney disease with stage 5 chronic kidney disease or end stage renal disease','Maladies de l''appareil circulatoire','I12.0'),
('Néphropathie hypertensive chronique disease with stage 1 through stage 4 chronic kidney disease, or unspecified chronic kidney disease','Hypertensive chronic kidney disease with stage 1 through stage 4 chronic kidney disease, or unspecified chronic kidney disease','Maladies de l''appareil circulatoire','I12.9'),
('Cardiopathie hypertensive and chronic kidney disease with heart failure and stage 1 through stage 4 chronic kidney disease, or unspecified chronic kidney disease','Hypertensive heart and chronic kidney disease with heart failure and stage 1 through stage 4 chronic kidney disease, or unspecified chronic kidney disease','Maladies de l''appareil circulatoire','I13.0'),
('Cardiopathie hypertensive and chronic kidney disease without heart failure, with stage 1 through stage 4 chronic kidney disease, or unspecified chronic kidney disease','Hypertensive heart and chronic kidney disease without heart failure, with stage 1 through stage 4 chronic kidney disease, or unspecified chronic kidney disease','Maladies de l''appareil circulatoire','I13.10'),
('Cardiopathie hypertensive and chronic kidney disease without heart failure, with stage 5 chronic kidney disease, or end stage renal disease','Hypertensive heart and chronic kidney disease without heart failure, with stage 5 chronic kidney disease, or end stage renal disease','Maladies de l''appareil circulatoire','I13.11'),
('Cardiopathie hypertensive and chronic kidney disease with heart failure and with stage 5 chronic kidney disease, or end stage renal disease','Hypertensive heart and chronic kidney disease with heart failure and with stage 5 chronic kidney disease, or end stage renal disease','Maladies de l''appareil circulatoire','I13.2'),
('Renovascular hypertension','Renovascular hypertension','Maladies de l''appareil circulatoire','I15.0'),
('Hypertension secondaire to autre renal disorders','Hypertension secondary to other renal disorders','Maladies de l''appareil circulatoire','I15.1'),
('Hypertension secondaire to endocrine disorders','Hypertension secondary to endocrine disorders','Maladies de l''appareil circulatoire','I15.2'),
('autre secondaire hypertension','Other secondary hypertension','Maladies de l''appareil circulatoire','I15.8'),
('secondaire hypertension, non spécifié','Secondary hypertension, unspecified','Maladies de l''appareil circulatoire','I15.9'),
('Hypertensive urgency','Hypertensive urgency','Maladies de l''appareil circulatoire','I16.0'),
('Hypertensive emergency','Hypertensive emergency','Maladies de l''appareil circulatoire','I16.1'),
('Hypertensive crisis, non spécifié','Hypertensive crisis, unspecified','Maladies de l''appareil circulatoire','I16.9'),
('Resistant hypertension','Resistant hypertension','Maladies de l''appareil circulatoire','I1A.0'),
('Unstable angina','Unstable angina','Maladies de l''appareil circulatoire','I20.0'),
('Angina pectoris with documented spasm','Angina pectoris with documented spasm','Maladies de l''appareil circulatoire','I20.1'),
('Refractory angina pectoris','Refractory angina pectoris','Maladies de l''appareil circulatoire','I20.2'),
('Angina pectoris with coronary microvascular dysfunction','Angina pectoris with coronary microvascular dysfunction','Maladies de l''appareil circulatoire','I20.81'),
('autre forms of angina pectoris','Other forms of angina pectoris','Maladies de l''appareil circulatoire','I20.89'),
('Angina pectoris, non spécifié','Angina pectoris, unspecified','Maladies de l''appareil circulatoire','I20.9'),
('ST elevation (STEMI) myocardial infarction involving left main coronary artery','ST elevation (STEMI) myocardial infarction involving left main coronary artery','Maladies de l''appareil circulatoire','I21.01'),
('ST elevation (STEMI) myocardial infarction involving left anterior descending coronary artery','ST elevation (STEMI) myocardial infarction involving left anterior descending coronary artery','Maladies de l''appareil circulatoire','I21.02'),
('ST elevation (STEMI) myocardial infarction involving autre coronary artery of anterior wall','ST elevation (STEMI) myocardial infarction involving other coronary artery of anterior wall','Maladies de l''appareil circulatoire','I21.09'),
('ST elevation (STEMI) myocardial infarction involving right coronary artery','ST elevation (STEMI) myocardial infarction involving right coronary artery','Maladies de l''appareil circulatoire','I21.11'),
('ST elevation (STEMI) myocardial infarction involving autre coronary artery of inferior wall','ST elevation (STEMI) myocardial infarction involving other coronary artery of inferior wall','Maladies de l''appareil circulatoire','I21.19'),
('ST elevation (STEMI) myocardial infarction involving left circumflex coronary artery','ST elevation (STEMI) myocardial infarction involving left circumflex coronary artery','Maladies de l''appareil circulatoire','I21.21'),
('ST elevation (STEMI) myocardial infarction involving autre sites','ST elevation (STEMI) myocardial infarction involving other sites','Maladies de l''appareil circulatoire','I21.29'),
('ST elevation (STEMI) myocardial infarction of non spécifié site','ST elevation (STEMI) myocardial infarction of unspecified site','Maladies de l''appareil circulatoire','I21.3'),
('Non-ST elevation (NSTEMI) myocardial infarction','Non-ST elevation (NSTEMI) myocardial infarction','Maladies de l''appareil circulatoire','I21.4'),
('Infarctus aigu du myocarde, unspecified','Acute myocardial infarction, unspecified','Maladies de l''appareil circulatoire','I21.9')
ON CONFLICT (nom_fr) DO NOTHING;
