-- icd10v2_batch_244.sql (80 rows)
INSERT INTO pathologies (nom_fr, nom_en, categorie, icd10_code)
VALUES
('Human immunodeficiency virus [HIV] maladie complicating the puerperium','Human immunodeficiency virus [HIV] disease complicating the puerperium','Grossesse, accouchement et puerpéralité','O98.73'),
('autre maternal infectious and parasitic diseases complicating pregnancy, first trimester','Other maternal infectious and parasitic diseases complicating pregnancy, first trimester','Grossesse, accouchement et puerpéralité','O98.811'),
('autre maternal infectious and parasitic diseases complicating pregnancy, second trimester','Other maternal infectious and parasitic diseases complicating pregnancy, second trimester','Grossesse, accouchement et puerpéralité','O98.812'),
('autre maternal infectious and parasitic diseases complicating pregnancy, third trimester','Other maternal infectious and parasitic diseases complicating pregnancy, third trimester','Grossesse, accouchement et puerpéralité','O98.813'),
('autre maternal infectious and parasitic diseases complicating pregnancy, non spécifié trimester','Other maternal infectious and parasitic diseases complicating pregnancy, unspecified trimester','Grossesse, accouchement et puerpéralité','O98.819'),
('autre maternal infectious and parasitic diseases complicating childbirth','Other maternal infectious and parasitic diseases complicating childbirth','Grossesse, accouchement et puerpéralité','O98.82'),
('autre maternal infectious and parasitic diseases complicating the puerperium','Other maternal infectious and parasitic diseases complicating the puerperium','Grossesse, accouchement et puerpéralité','O98.83'),
('non spécifié maternal infectious and parasitic maladie complicating pregnancy, first trimester','Unspecified maternal infectious and parasitic disease complicating pregnancy, first trimester','Grossesse, accouchement et puerpéralité','O98.911'),
('non spécifié maternal infectious and parasitic maladie complicating pregnancy, second trimester','Unspecified maternal infectious and parasitic disease complicating pregnancy, second trimester','Grossesse, accouchement et puerpéralité','O98.912'),
('non spécifié maternal infectious and parasitic maladie complicating pregnancy, third trimester','Unspecified maternal infectious and parasitic disease complicating pregnancy, third trimester','Grossesse, accouchement et puerpéralité','O98.913'),
('non spécifié maternal infectious and parasitic maladie complicating pregnancy, non spécifié trimester','Unspecified maternal infectious and parasitic disease complicating pregnancy, unspecified trimester','Grossesse, accouchement et puerpéralité','O98.919'),
('non spécifié maternal infectious and parasitic maladie complicating childbirth','Unspecified maternal infectious and parasitic disease complicating childbirth','Grossesse, accouchement et puerpéralité','O98.92'),
('non spécifié maternal infectious and parasitic maladie complicating the puerperium','Unspecified maternal infectious and parasitic disease complicating the puerperium','Grossesse, accouchement et puerpéralité','O98.93'),
('Anémie complicating pregnancy, first trimester','Anemia complicating pregnancy, first trimester','Grossesse, accouchement et puerpéralité','O99.011'),
('Anémie complicating pregnancy, second trimester','Anemia complicating pregnancy, second trimester','Grossesse, accouchement et puerpéralité','O99.012'),
('Anémie complicating pregnancy, third trimester','Anemia complicating pregnancy, third trimester','Grossesse, accouchement et puerpéralité','O99.013'),
('Anémie complicating pregnancy, unspecified trimester','Anemia complicating pregnancy, unspecified trimester','Grossesse, accouchement et puerpéralité','O99.019'),
('Anémie complicating childbirth','Anemia complicating childbirth','Grossesse, accouchement et puerpéralité','O99.02'),
('Anémie complicating the puerperium','Anemia complicating the puerperium','Grossesse, accouchement et puerpéralité','O99.03'),
('autre diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism complicating pregnancy, first trimester','Other diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism complicating pregnancy, first trimester','Grossesse, accouchement et puerpéralité','O99.111'),
('autre diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism complicating pregnancy, second trimester','Other diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism complicating pregnancy, second trimester','Grossesse, accouchement et puerpéralité','O99.112'),
('autre diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism complicating pregnancy, third trimester','Other diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism complicating pregnancy, third trimester','Grossesse, accouchement et puerpéralité','O99.113'),
('autre diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism complicating pregnancy, non spécifié trimester','Other diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism complicating pregnancy, unspecified trimester','Grossesse, accouchement et puerpéralité','O99.119'),
('autre diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism complicating childbirth','Other diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism complicating childbirth','Grossesse, accouchement et puerpéralité','O99.12'),
('autre diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism complicating the puerperium','Other diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism complicating the puerperium','Grossesse, accouchement et puerpéralité','O99.13'),
('Obesity complicating pregnancy, non spécifié trimester','Obesity complicating pregnancy, unspecified trimester','Grossesse, accouchement et puerpéralité','O99.210'),
('Obesity complicating pregnancy, first trimester','Obesity complicating pregnancy, first trimester','Grossesse, accouchement et puerpéralité','O99.211'),
('Obesity complicating pregnancy, second trimester','Obesity complicating pregnancy, second trimester','Grossesse, accouchement et puerpéralité','O99.212'),
('Obesity complicating pregnancy, third trimester','Obesity complicating pregnancy, third trimester','Grossesse, accouchement et puerpéralité','O99.213'),
('Obesity complicating childbirth','Obesity complicating childbirth','Grossesse, accouchement et puerpéralité','O99.214'),
('Obesity complicating the puerperium','Obesity complicating the puerperium','Grossesse, accouchement et puerpéralité','O99.215'),
('Endocrine, nutritional and metabolic diseases complicating pregnancy, non spécifié trimester','Endocrine, nutritional and metabolic diseases complicating pregnancy, unspecified trimester','Grossesse, accouchement et puerpéralité','O99.280'),
('Endocrine, nutritional and metabolic diseases complicating pregnancy, first trimester','Endocrine, nutritional and metabolic diseases complicating pregnancy, first trimester','Grossesse, accouchement et puerpéralité','O99.281'),
('Endocrine, nutritional and metabolic diseases complicating pregnancy, second trimester','Endocrine, nutritional and metabolic diseases complicating pregnancy, second trimester','Grossesse, accouchement et puerpéralité','O99.282'),
('Endocrine, nutritional and metabolic diseases complicating pregnancy, third trimester','Endocrine, nutritional and metabolic diseases complicating pregnancy, third trimester','Grossesse, accouchement et puerpéralité','O99.283'),
('Endocrine, nutritional and metabolic diseases complicating childbirth','Endocrine, nutritional and metabolic diseases complicating childbirth','Grossesse, accouchement et puerpéralité','O99.284'),
('Endocrine, nutritional and metabolic diseases complicating the puerperium','Endocrine, nutritional and metabolic diseases complicating the puerperium','Grossesse, accouchement et puerpéralité','O99.285'),
('Alcohol use complicating pregnancy, non spécifié trimester','Alcohol use complicating pregnancy, unspecified trimester','Grossesse, accouchement et puerpéralité','O99.310'),
('Alcohol use complicating pregnancy, first trimester','Alcohol use complicating pregnancy, first trimester','Grossesse, accouchement et puerpéralité','O99.311'),
('Alcohol use complicating pregnancy, second trimester','Alcohol use complicating pregnancy, second trimester','Grossesse, accouchement et puerpéralité','O99.312'),
('Alcohol use complicating pregnancy, third trimester','Alcohol use complicating pregnancy, third trimester','Grossesse, accouchement et puerpéralité','O99.313'),
('Alcohol use complicating childbirth','Alcohol use complicating childbirth','Grossesse, accouchement et puerpéralité','O99.314'),
('Alcohol use complicating the puerperium','Alcohol use complicating the puerperium','Grossesse, accouchement et puerpéralité','O99.315'),
('Drug use complicating pregnancy, non spécifié trimester','Drug use complicating pregnancy, unspecified trimester','Grossesse, accouchement et puerpéralité','O99.320'),
('Drug use complicating pregnancy, first trimester','Drug use complicating pregnancy, first trimester','Grossesse, accouchement et puerpéralité','O99.321'),
('Drug use complicating pregnancy, second trimester','Drug use complicating pregnancy, second trimester','Grossesse, accouchement et puerpéralité','O99.322'),
('Drug use complicating pregnancy, third trimester','Drug use complicating pregnancy, third trimester','Grossesse, accouchement et puerpéralité','O99.323'),
('Drug use complicating childbirth','Drug use complicating childbirth','Grossesse, accouchement et puerpéralité','O99.324'),
('Drug use complicating the puerperium','Drug use complicating the puerperium','Grossesse, accouchement et puerpéralité','O99.325'),
('Smoking (tobacco) complicating pregnancy, non spécifié trimester','Smoking (tobacco) complicating pregnancy, unspecified trimester','Grossesse, accouchement et puerpéralité','O99.330'),
('Smoking (tobacco) complicating pregnancy, first trimester','Smoking (tobacco) complicating pregnancy, first trimester','Grossesse, accouchement et puerpéralité','O99.331'),
('Smoking (tobacco) complicating pregnancy, second trimester','Smoking (tobacco) complicating pregnancy, second trimester','Grossesse, accouchement et puerpéralité','O99.332'),
('Smoking (tobacco) complicating pregnancy, third trimester','Smoking (tobacco) complicating pregnancy, third trimester','Grossesse, accouchement et puerpéralité','O99.333'),
('Smoking (tobacco) complicating childbirth','Smoking (tobacco) complicating childbirth','Grossesse, accouchement et puerpéralité','O99.334'),
('Smoking (tobacco) complicating the puerperium','Smoking (tobacco) complicating the puerperium','Grossesse, accouchement et puerpéralité','O99.335'),
('autre mental disorders complicating pregnancy, non spécifié trimester','Other mental disorders complicating pregnancy, unspecified trimester','Grossesse, accouchement et puerpéralité','O99.340'),
('autre mental disorders complicating pregnancy, first trimester','Other mental disorders complicating pregnancy, first trimester','Grossesse, accouchement et puerpéralité','O99.341'),
('autre mental disorders complicating pregnancy, second trimester','Other mental disorders complicating pregnancy, second trimester','Grossesse, accouchement et puerpéralité','O99.342'),
('autre mental disorders complicating pregnancy, third trimester','Other mental disorders complicating pregnancy, third trimester','Grossesse, accouchement et puerpéralité','O99.343'),
('autre mental disorders complicating childbirth','Other mental disorders complicating childbirth','Grossesse, accouchement et puerpéralité','O99.344'),
('autre mental disorders complicating the puerperium','Other mental disorders complicating the puerperium','Grossesse, accouchement et puerpéralité','O99.345'),
('Diseases of the nervous system complicating pregnancy, non spécifié trimester','Diseases of the nervous system complicating pregnancy, unspecified trimester','Grossesse, accouchement et puerpéralité','O99.350'),
('Diseases of the nervous system complicating pregnancy, first trimester','Diseases of the nervous system complicating pregnancy, first trimester','Grossesse, accouchement et puerpéralité','O99.351'),
('Diseases of the nervous system complicating pregnancy, second trimester','Diseases of the nervous system complicating pregnancy, second trimester','Grossesse, accouchement et puerpéralité','O99.352'),
('Diseases of the nervous system complicating pregnancy, third trimester','Diseases of the nervous system complicating pregnancy, third trimester','Grossesse, accouchement et puerpéralité','O99.353'),
('Diseases of the nervous system complicating childbirth','Diseases of the nervous system complicating childbirth','Grossesse, accouchement et puerpéralité','O99.354'),
('Diseases of the nervous system complicating the puerperium','Diseases of the nervous system complicating the puerperium','Grossesse, accouchement et puerpéralité','O99.355'),
('Diseases of the circulatory system complicating pregnancy, first trimester','Diseases of the circulatory system complicating pregnancy, first trimester','Grossesse, accouchement et puerpéralité','O99.411'),
('Diseases of the circulatory system complicating pregnancy, second trimester','Diseases of the circulatory system complicating pregnancy, second trimester','Grossesse, accouchement et puerpéralité','O99.412'),
('Diseases of the circulatory system complicating pregnancy, third trimester','Diseases of the circulatory system complicating pregnancy, third trimester','Grossesse, accouchement et puerpéralité','O99.413'),
('Diseases of the circulatory system complicating pregnancy, non spécifié trimester','Diseases of the circulatory system complicating pregnancy, unspecified trimester','Grossesse, accouchement et puerpéralité','O99.419'),
('Diseases of the circulatory system complicating childbirth','Diseases of the circulatory system complicating childbirth','Grossesse, accouchement et puerpéralité','O99.42'),
('Diseases of the circulatory system complicating the puerperium','Diseases of the circulatory system complicating the puerperium','Grossesse, accouchement et puerpéralité','O99.43'),
('Diseases of the respiratory system complicating pregnancy, first trimester','Diseases of the respiratory system complicating pregnancy, first trimester','Grossesse, accouchement et puerpéralité','O99.511'),
('Diseases of the respiratory system complicating pregnancy, second trimester','Diseases of the respiratory system complicating pregnancy, second trimester','Grossesse, accouchement et puerpéralité','O99.512'),
('Diseases of the respiratory system complicating pregnancy, third trimester','Diseases of the respiratory system complicating pregnancy, third trimester','Grossesse, accouchement et puerpéralité','O99.513'),
('Diseases of the respiratory system complicating pregnancy, non spécifié trimester','Diseases of the respiratory system complicating pregnancy, unspecified trimester','Grossesse, accouchement et puerpéralité','O99.519'),
('Diseases of the respiratory system complicating childbirth','Diseases of the respiratory system complicating childbirth','Grossesse, accouchement et puerpéralité','O99.52'),
('Diseases of the respiratory system complicating the puerperium','Diseases of the respiratory system complicating the puerperium','Grossesse, accouchement et puerpéralité','O99.53'),
('Diseases of the digestive system complicating pregnancy, first trimester','Diseases of the digestive system complicating pregnancy, first trimester','Grossesse, accouchement et puerpéralité','O99.611')
ON CONFLICT (nom_fr) DO NOTHING;
