-- icd10v2_batch_052.sql (80 rows)
INSERT INTO pathologies (nom_fr, nom_en, categorie, icd10_code)
VALUES
('Histidinemia','Histidinemia','Maladies endocriniennes, nutritionnelles et métaboliques','E70.41'),
('autre disorders of histidine metabolism','Other disorders of histidine metabolism','Maladies endocriniennes, nutritionnelles et métaboliques','E70.49'),
('Disorders of tryptophan metabolism','Disorders of tryptophan metabolism','Maladies endocriniennes, nutritionnelles et métaboliques','E70.5'),
('Aromatic L-amino acid decarboxylase carence','Aromatic L-amino acid decarboxylase deficiency','Maladies endocriniennes, nutritionnelles et métaboliques','E70.81'),
('autre disorders of aromatic amino-acid metabolism','Other disorders of aromatic amino-acid metabolism','Maladies endocriniennes, nutritionnelles et métaboliques','E70.89'),
('trouble of aromatic amino-acid metabolism, non spécifié','Disorder of aromatic amino-acid metabolism, unspecified','Maladies endocriniennes, nutritionnelles et métaboliques','E70.9'),
('Maple-syrup-urine maladie','Maple-syrup-urine disease','Maladies endocriniennes, nutritionnelles et métaboliques','E71.0'),
('Isovaleric acidemia','Isovaleric acidemia','Maladies endocriniennes, nutritionnelles et métaboliques','E71.110'),
('3-methylglutaconic aciduria','3-methylglutaconic aciduria','Maladies endocriniennes, nutritionnelles et métaboliques','E71.111'),
('autre branched-chain organic acidurias','Other branched-chain organic acidurias','Maladies endocriniennes, nutritionnelles et métaboliques','E71.118'),
('Methylmalonic acidemia','Methylmalonic acidemia','Maladies endocriniennes, nutritionnelles et métaboliques','E71.120'),
('Propionic acidemia','Propionic acidemia','Maladies endocriniennes, nutritionnelles et métaboliques','E71.121'),
('autre disorders of propionate metabolism','Other disorders of propionate metabolism','Maladies endocriniennes, nutritionnelles et métaboliques','E71.128'),
('autre disorders of branched-chain amino-acid metabolism','Other disorders of branched-chain amino-acid metabolism','Maladies endocriniennes, nutritionnelles et métaboliques','E71.19'),
('trouble of branched-chain amino-acid metabolism, non spécifié','Disorder of branched-chain amino-acid metabolism, unspecified','Maladies endocriniennes, nutritionnelles et métaboliques','E71.2'),
('trouble of fatty-acid metabolism, non spécifié','Disorder of fatty-acid metabolism, unspecified','Maladies endocriniennes, nutritionnelles et métaboliques','E71.30'),
('Long chain/very long chain acyl CoA dehydrogenase carence','Long chain/very long chain acyl CoA dehydrogenase deficiency','Maladies endocriniennes, nutritionnelles et métaboliques','E71.310'),
('Medium chain acyl CoA dehydrogenase carence','Medium chain acyl CoA dehydrogenase deficiency','Maladies endocriniennes, nutritionnelles et métaboliques','E71.311'),
('Short chain acyl CoA dehydrogenase carence','Short chain acyl CoA dehydrogenase deficiency','Maladies endocriniennes, nutritionnelles et métaboliques','E71.312'),
('Glutaric aciduria type II','Glutaric aciduria type II','Maladies endocriniennes, nutritionnelles et métaboliques','E71.313'),
('Muscle carnitine palmitoyltransferase carence','Muscle carnitine palmitoyltransferase deficiency','Maladies endocriniennes, nutritionnelles et métaboliques','E71.314'),
('autre disorders of fatty-acid oxidation','Other disorders of fatty-acid oxidation','Maladies endocriniennes, nutritionnelles et métaboliques','E71.318'),
('Disorders of ketone metabolism','Disorders of ketone metabolism','Maladies endocriniennes, nutritionnelles et métaboliques','E71.32'),
('autre disorders of fatty-acid metabolism','Other disorders of fatty-acid metabolism','Maladies endocriniennes, nutritionnelles et métaboliques','E71.39'),
('trouble of carnitine metabolism, non spécifié','Disorder of carnitine metabolism, unspecified','Maladies endocriniennes, nutritionnelles et métaboliques','E71.40'),
('primitif carnitine carence','Primary carnitine deficiency','Maladies endocriniennes, nutritionnelles et métaboliques','E71.41'),
('Carnitine carence due to inborn errors of metabolism','Carnitine deficiency due to inborn errors of metabolism','Maladies endocriniennes, nutritionnelles et métaboliques','E71.42'),
('Iatrogenic carnitine carence','Iatrogenic carnitine deficiency','Maladies endocriniennes, nutritionnelles et métaboliques','E71.43'),
('Ruvalcaba-Myhre-Smith syndrome','Ruvalcaba-Myhre-Smith syndrome','Maladies endocriniennes, nutritionnelles et métaboliques','E71.440'),
('autre secondaire carnitine carence','Other secondary carnitine deficiency','Maladies endocriniennes, nutritionnelles et métaboliques','E71.448'),
('Peroxisomal trouble, non spécifié','Peroxisomal disorder, unspecified','Maladies endocriniennes, nutritionnelles et métaboliques','E71.50'),
('Zellweger syndrome','Zellweger syndrome','Maladies endocriniennes, nutritionnelles et métaboliques','E71.510'),
('Neonatal adrenoleukodystrophy','Neonatal adrenoleukodystrophy','Maladies endocriniennes, nutritionnelles et métaboliques','E71.511'),
('autre disorders of peroxisome biogenesis','Other disorders of peroxisome biogenesis','Maladies endocriniennes, nutritionnelles et métaboliques','E71.518'),
('Childhood cerebral X-linked adrenoleukodystrophy','Childhood cerebral X-linked adrenoleukodystrophy','Maladies endocriniennes, nutritionnelles et métaboliques','E71.520'),
('Adolescent X-linked adrenoleukodystrophy','Adolescent X-linked adrenoleukodystrophy','Maladies endocriniennes, nutritionnelles et métaboliques','E71.521'),
('Adrenomyeloneuropathy','Adrenomyeloneuropathy','Maladies endocriniennes, nutritionnelles et métaboliques','E71.522'),
('autre X-linked adrenoleukodystrophy','Other X-linked adrenoleukodystrophy','Maladies endocriniennes, nutritionnelles et métaboliques','E71.528'),
('X-linked adrenoleukodystrophy, non spécifié type','X-linked adrenoleukodystrophy, unspecified type','Maladies endocriniennes, nutritionnelles et métaboliques','E71.529'),
('autre group 2 peroxisomal disorders','Other group 2 peroxisomal disorders','Maladies endocriniennes, nutritionnelles et métaboliques','E71.53'),
('Rhizomelic chondrodysplasia punctata','Rhizomelic chondrodysplasia punctata','Maladies endocriniennes, nutritionnelles et métaboliques','E71.540'),
('Zellweger-like syndrome','Zellweger-like syndrome','Maladies endocriniennes, nutritionnelles et métaboliques','E71.541'),
('autre group 3 peroxisomal disorders','Other group 3 peroxisomal disorders','Maladies endocriniennes, nutritionnelles et métaboliques','E71.542'),
('autre peroxisomal disorders','Other peroxisomal disorders','Maladies endocriniennes, nutritionnelles et métaboliques','E71.548'),
('Disorders of amino-acid transport, non spécifié','Disorders of amino-acid transport, unspecified','Maladies endocriniennes, nutritionnelles et métaboliques','E72.00'),
('Cystinuria','Cystinuria','Maladies endocriniennes, nutritionnelles et métaboliques','E72.01'),
('Hartnup''s maladie','Hartnup''s disease','Maladies endocriniennes, nutritionnelles et métaboliques','E72.02'),
('Lowe''s syndrome','Lowe''s syndrome','Maladies endocriniennes, nutritionnelles et métaboliques','E72.03'),
('Cystinosis','Cystinosis','Maladies endocriniennes, nutritionnelles et métaboliques','E72.04'),
('autre disorders of amino-acid transport','Other disorders of amino-acid transport','Maladies endocriniennes, nutritionnelles et métaboliques','E72.09'),
('Disorders of sulfur-bearing amino-acid metabolism, non spécifié','Disorders of sulfur-bearing amino-acid metabolism, unspecified','Maladies endocriniennes, nutritionnelles et métaboliques','E72.10'),
('Homocystinuria','Homocystinuria','Maladies endocriniennes, nutritionnelles et métaboliques','E72.11'),
('Methylenetetrahydrofolate reductase carence','Methylenetetrahydrofolate reductase deficiency','Maladies endocriniennes, nutritionnelles et métaboliques','E72.12'),
('autre disorders of sulfur-bearing amino-acid metabolism','Other disorders of sulfur-bearing amino-acid metabolism','Maladies endocriniennes, nutritionnelles et métaboliques','E72.19'),
('trouble of urea cycle metabolism, non spécifié','Disorder of urea cycle metabolism, unspecified','Maladies endocriniennes, nutritionnelles et métaboliques','E72.20'),
('Argininemia','Argininemia','Maladies endocriniennes, nutritionnelles et métaboliques','E72.21'),
('Arginosuccinic aciduria','Arginosuccinic aciduria','Maladies endocriniennes, nutritionnelles et métaboliques','E72.22'),
('Citrullinemia','Citrullinemia','Maladies endocriniennes, nutritionnelles et métaboliques','E72.23'),
('autre disorders of urea cycle metabolism','Other disorders of urea cycle metabolism','Maladies endocriniennes, nutritionnelles et métaboliques','E72.29'),
('Disorders of lysine and hydroxylysine metabolism','Disorders of lysine and hydroxylysine metabolism','Maladies endocriniennes, nutritionnelles et métaboliques','E72.3'),
('Disorders of ornithine metabolism','Disorders of ornithine metabolism','Maladies endocriniennes, nutritionnelles et métaboliques','E72.4'),
('trouble of glycine metabolism, non spécifié','Disorder of glycine metabolism, unspecified','Maladies endocriniennes, nutritionnelles et métaboliques','E72.50'),
('Non-ketotic hyperglycinemia','Non-ketotic hyperglycinemia','Maladies endocriniennes, nutritionnelles et métaboliques','E72.51'),
('Trimethylaminuria','Trimethylaminuria','Maladies endocriniennes, nutritionnelles et métaboliques','E72.52'),
('primitif hyperoxaluria, type 1','Primary hyperoxaluria, type 1','Maladies endocriniennes, nutritionnelles et métaboliques','E72.530'),
('autre specified primitif hyperoxaluria','Other specified primary hyperoxaluria','Maladies endocriniennes, nutritionnelles et métaboliques','E72.538'),
('primitif hyperoxaluria, non spécifié','Primary hyperoxaluria, unspecified','Maladies endocriniennes, nutritionnelles et métaboliques','E72.539'),
('Dietary hyperoxaluria','Dietary hyperoxaluria','Maladies endocriniennes, nutritionnelles et métaboliques','E72.540'),
('Enteric hyperoxaluria','Enteric hyperoxaluria','Maladies endocriniennes, nutritionnelles et métaboliques','E72.541'),
('autre secondaire hyperoxaluria','Other secondary hyperoxaluria','Maladies endocriniennes, nutritionnelles et métaboliques','E72.548'),
('secondaire hyperoxaluria, non spécifié','Secondary hyperoxaluria, unspecified','Maladies endocriniennes, nutritionnelles et métaboliques','E72.549'),
('autre disorders of glycine metabolism','Other disorders of glycine metabolism','Maladies endocriniennes, nutritionnelles et métaboliques','E72.59'),
('Disorders of gamma aminobutyric acid metabolism','Disorders of gamma aminobutyric acid metabolism','Maladies endocriniennes, nutritionnelles et métaboliques','E72.81'),
('autre specified disorders of amino-acid metabolism','Other specified disorders of amino-acid metabolism','Maladies endocriniennes, nutritionnelles et métaboliques','E72.89'),
('trouble of amino-acid metabolism, non spécifié','Disorder of amino-acid metabolism, unspecified','Maladies endocriniennes, nutritionnelles et métaboliques','E72.9'),
('congénital lactase carence','Congenital lactase deficiency','Maladies endocriniennes, nutritionnelles et métaboliques','E73.0'),
('secondaire lactase carence','Secondary lactase deficiency','Maladies endocriniennes, nutritionnelles et métaboliques','E73.1'),
('autre lactose intolerance','Other lactose intolerance','Maladies endocriniennes, nutritionnelles et métaboliques','E73.8'),
('Lactose intolerance, non spécifié','Lactose intolerance, unspecified','Maladies endocriniennes, nutritionnelles et métaboliques','E73.9'),
('Glycogen storage maladie, non spécifié','Glycogen storage disease, unspecified','Maladies endocriniennes, nutritionnelles et métaboliques','E74.00')
ON CONFLICT (nom_fr) DO NOTHING;
