-- icd10_batch_025.sql (80 rows)
INSERT INTO pathologies (nom_fr, nom_en, categorie, icd10_code)
VALUES
('congénital malformations of salivary glands and ducts','Congenital malformations of salivary glands and ducts','Malformations congénitales et anomalies chromosomiques','Q38.4'),
('congénital malformations of palate, not elsewhere classified','Congenital malformations of palate, not elsewhere classified','Malformations congénitales et anomalies chromosomiques','Q38.5'),
('autre congénital malformations of mouth','Other congenital malformations of mouth','Malformations congénitales et anomalies chromosomiques','Q38.6'),
('congénital pharyngeal pouch','Congenital pharyngeal pouch','Malformations congénitales et anomalies chromosomiques','Q38.7'),
('autre congénital malformations of pharynx','Other congenital malformations of pharynx','Malformations congénitales et anomalies chromosomiques','Q38.8'),
('Atresia of esophagus without fistula','Atresia of esophagus without fistula','Malformations congénitales et anomalies chromosomiques','Q39.0'),
('Atresia of esophagus with tracheo-esophageal fistula','Atresia of esophagus with tracheo-esophageal fistula','Malformations congénitales et anomalies chromosomiques','Q39.1'),
('congénital tracheo-esophageal fistula without atresia','Congenital tracheo-esophageal fistula without atresia','Malformations congénitales et anomalies chromosomiques','Q39.2'),
('congénital sténose and stricture of esophagus','Congenital stenosis and stricture of esophagus','Malformations congénitales et anomalies chromosomiques','Q39.3'),
('Esophageal web','Esophageal web','Malformations congénitales et anomalies chromosomiques','Q39.4'),
('congénital dilatation of esophagus','Congenital dilatation of esophagus','Malformations congénitales et anomalies chromosomiques','Q39.5'),
('congénital diverticulum of esophagus','Congenital diverticulum of esophagus','Malformations congénitales et anomalies chromosomiques','Q39.6'),
('autre congénital malformations of esophagus','Other congenital malformations of esophagus','Malformations congénitales et anomalies chromosomiques','Q39.8'),
('congénital malformation of esophagus, non spécifié','Congenital malformation of esophagus, unspecified','Malformations congénitales et anomalies chromosomiques','Q39.9'),
('congénital hypertrophic pyloric sténose','Congenital hypertrophic pyloric stenosis','Malformations congénitales et anomalies chromosomiques','Q40.0'),
('congénital hiatus hernia','Congenital hiatus hernia','Malformations congénitales et anomalies chromosomiques','Q40.1'),
('autre specified congénital malformations of stomach','Other specified congenital malformations of stomach','Malformations congénitales et anomalies chromosomiques','Q40.2'),
('congénital malformation of stomach, non spécifié','Congenital malformation of stomach, unspecified','Malformations congénitales et anomalies chromosomiques','Q40.3'),
('autre specified congénital malformations of upper alimentary tract','Other specified congenital malformations of upper alimentary tract','Malformations congénitales et anomalies chromosomiques','Q40.8'),
('congénital malformation of upper alimentary tract, non spécifié','Congenital malformation of upper alimentary tract, unspecified','Malformations congénitales et anomalies chromosomiques','Q40.9'),
('congénital absence, atresia and sténose of duodenum','Congenital absence, atresia and stenosis of duodenum','Malformations congénitales et anomalies chromosomiques','Q41.0'),
('congénital absence, atresia and sténose of jejunum','Congenital absence, atresia and stenosis of jejunum','Malformations congénitales et anomalies chromosomiques','Q41.1'),
('congénital absence, atresia and sténose of ileum','Congenital absence, atresia and stenosis of ileum','Malformations congénitales et anomalies chromosomiques','Q41.2'),
('congénital absence, atresia and sténose of autre specified parts of small intestine','Congenital absence, atresia and stenosis of other specified parts of small intestine','Malformations congénitales et anomalies chromosomiques','Q41.8'),
('congénital absence, atresia and sténose of small intestine, part non spécifié','Congenital absence, atresia and stenosis of small intestine, part unspecified','Malformations congénitales et anomalies chromosomiques','Q41.9'),
('congénital absence, atresia and sténose of rectum with fistula','Congenital absence, atresia and stenosis of rectum with fistula','Malformations congénitales et anomalies chromosomiques','Q42.0'),
('congénital absence, atresia and sténose of rectum without fistula','Congenital absence, atresia and stenosis of rectum without fistula','Malformations congénitales et anomalies chromosomiques','Q42.1'),
('congénital absence, atresia and sténose of anus with fistula','Congenital absence, atresia and stenosis of anus with fistula','Malformations congénitales et anomalies chromosomiques','Q42.2'),
('congénital absence, atresia and sténose of anus without fistula','Congenital absence, atresia and stenosis of anus without fistula','Malformations congénitales et anomalies chromosomiques','Q42.3'),
('congénital absence, atresia and sténose of autre parts of large intestine','Congenital absence, atresia and stenosis of other parts of large intestine','Malformations congénitales et anomalies chromosomiques','Q42.8'),
('congénital absence, atresia and sténose of large intestine, part non spécifié','Congenital absence, atresia and stenosis of large intestine, part unspecified','Malformations congénitales et anomalies chromosomiques','Q42.9'),
('Meckel''s diverticulum (displaced) (hypertrophic)','Meckel''s diverticulum (displaced) (hypertrophic)','Malformations congénitales et anomalies chromosomiques','Q43.0'),
('Hirschsprung''s maladie','Hirschsprung''s disease','Malformations congénitales et anomalies chromosomiques','Q43.1'),
('autre congénital functional disorders of colon','Other congenital functional disorders of colon','Malformations congénitales et anomalies chromosomiques','Q43.2'),
('congénital malformations of intestinal fixation','Congenital malformations of intestinal fixation','Malformations congénitales et anomalies chromosomiques','Q43.3'),
('Duplication of intestine','Duplication of intestine','Malformations congénitales et anomalies chromosomiques','Q43.4'),
('Ectopic anus','Ectopic anus','Malformations congénitales et anomalies chromosomiques','Q43.5'),
('congénital fistula of rectum and anus','Congenital fistula of rectum and anus','Malformations congénitales et anomalies chromosomiques','Q43.6'),
('Persistent cloaca','Persistent cloaca','Malformations congénitales et anomalies chromosomiques','Q43.7'),
('autre specified congénital malformations of intestine','Other specified congenital malformations of intestine','Malformations congénitales et anomalies chromosomiques','Q43.8'),
('congénital malformation of intestine, non spécifié','Congenital malformation of intestine, unspecified','Malformations congénitales et anomalies chromosomiques','Q43.9'),
('Agenesis, aplasia and hypoplasia of gallbladder','Agenesis, aplasia and hypoplasia of gallbladder','Malformations congénitales et anomalies chromosomiques','Q44.0'),
('autre congénital malformations of gallbladder','Other congenital malformations of gallbladder','Malformations congénitales et anomalies chromosomiques','Q44.1'),
('Atresia of bile ducts','Atresia of bile ducts','Malformations congénitales et anomalies chromosomiques','Q44.2'),
('congénital sténose and stricture of bile ducts','Congenital stenosis and stricture of bile ducts','Malformations congénitales et anomalies chromosomiques','Q44.3'),
('Choledochal cyst','Choledochal cyst','Malformations congénitales et anomalies chromosomiques','Q44.4'),
('autre congénital malformations of bile ducts','Other congenital malformations of bile ducts','Malformations congénitales et anomalies chromosomiques','Q44.5'),
('Cystic maladie of liver','Cystic disease of liver','Malformations congénitales et anomalies chromosomiques','Q44.6'),
('autre congénital malformation of liver, non spécifié','Other congenital malformation of liver, unspecified','Malformations congénitales et anomalies chromosomiques','Q44.70'),
('Alagille syndrome','Alagille syndrome','Malformations congénitales et anomalies chromosomiques','Q44.71'),
('autre congénital malformations of liver','Other congenital malformations of liver','Malformations congénitales et anomalies chromosomiques','Q44.79'),
('Agenesis, aplasia and hypoplasia of pancreas','Agenesis, aplasia and hypoplasia of pancreas','Malformations congénitales et anomalies chromosomiques','Q45.0'),
('Annular pancreas','Annular pancreas','Malformations congénitales et anomalies chromosomiques','Q45.1'),
('congénital pancreatic cyst','Congenital pancreatic cyst','Malformations congénitales et anomalies chromosomiques','Q45.2'),
('autre congénital malformations of pancreas and pancreatic duct','Other congenital malformations of pancreas and pancreatic duct','Malformations congénitales et anomalies chromosomiques','Q45.3'),
('autre specified congénital malformations of digestive system','Other specified congenital malformations of digestive system','Malformations congénitales et anomalies chromosomiques','Q45.8'),
('congénital malformation of digestive system, non spécifié','Congenital malformation of digestive system, unspecified','Malformations congénitales et anomalies chromosomiques','Q45.9'),
('congénital absence of ovary, unilateral','Congenital absence of ovary, unilateral','Malformations congénitales et anomalies chromosomiques','Q50.01'),
('congénital absence of ovary, bilateral','Congenital absence of ovary, bilateral','Malformations congénitales et anomalies chromosomiques','Q50.02'),
('Developmental ovarian cyst','Developmental ovarian cyst','Malformations congénitales et anomalies chromosomiques','Q50.1'),
('congénital torsion of ovary','Congenital torsion of ovary','Malformations congénitales et anomalies chromosomiques','Q50.2'),
('Accessory ovary','Accessory ovary','Malformations congénitales et anomalies chromosomiques','Q50.31'),
('Ovarian streak','Ovarian streak','Malformations congénitales et anomalies chromosomiques','Q50.32'),
('autre congénital malformation of ovary','Other congenital malformation of ovary','Malformations congénitales et anomalies chromosomiques','Q50.39'),
('Embryonic cyst of fallopian tube','Embryonic cyst of fallopian tube','Malformations congénitales et anomalies chromosomiques','Q50.4'),
('Embryonic cyst of broad ligament','Embryonic cyst of broad ligament','Malformations congénitales et anomalies chromosomiques','Q50.5'),
('autre congénital malformations of fallopian tube and broad ligament','Other congenital malformations of fallopian tube and broad ligament','Malformations congénitales et anomalies chromosomiques','Q50.6'),
('Agenesis and aplasia of uterus','Agenesis and aplasia of uterus','Malformations congénitales et anomalies chromosomiques','Q51.0'),
('Doubling of uterus with doubling of cervix and vagina without obstruction','Doubling of uterus with doubling of cervix and vagina without obstruction','Malformations congénitales et anomalies chromosomiques','Q51.10'),
('Doubling of uterus with doubling of cervix and vagina with obstruction','Doubling of uterus with doubling of cervix and vagina with obstruction','Malformations congénitales et anomalies chromosomiques','Q51.11'),
('Complete doubling of uterus','Complete doubling of uterus','Malformations congénitales et anomalies chromosomiques','Q51.21'),
('Partial doubling of uterus','Partial doubling of uterus','Malformations congénitales et anomalies chromosomiques','Q51.22'),
('autre and non spécifié doubling of uterus','Other and unspecified doubling of uterus','Malformations congénitales et anomalies chromosomiques','Q51.28'),
('Bicornate uterus','Bicornate uterus','Malformations congénitales et anomalies chromosomiques','Q51.3'),
('Unicornate uterus','Unicornate uterus','Malformations congénitales et anomalies chromosomiques','Q51.4'),
('Agenesis and aplasia of cervix','Agenesis and aplasia of cervix','Malformations congénitales et anomalies chromosomiques','Q51.5'),
('Embryonic cyst of cervix','Embryonic cyst of cervix','Malformations congénitales et anomalies chromosomiques','Q51.6'),
('congénital fistulae between uterus and digestive and urinary tracts','Congenital fistulae between uterus and digestive and urinary tracts','Malformations congénitales et anomalies chromosomiques','Q51.7'),
('Arcuate uterus','Arcuate uterus','Malformations congénitales et anomalies chromosomiques','Q51.810'),
('Hypoplasia of uterus','Hypoplasia of uterus','Malformations congénitales et anomalies chromosomiques','Q51.811')
ON CONFLICT (nom_fr) DO NOTHING;
