-- icd10v2_batch_256.sql (80 rows)
INSERT INTO pathologies (nom_fr, nom_en, categorie, icd10_code)
VALUES
('congénital malformation of clitoris','Congenital malformation of clitoris','Malformations congénitales et anomalies chromosomiques','Q52.6'),
('non spécifié congénital malformations of vulva','Unspecified congenital malformations of vulva','Malformations congénitales et anomalies chromosomiques','Q52.70'),
('congénital absence of vulva','Congenital absence of vulva','Malformations congénitales et anomalies chromosomiques','Q52.71'),
('autre congénital malformations of vulva','Other congenital malformations of vulva','Malformations congénitales et anomalies chromosomiques','Q52.79'),
('autre specified congénital malformations of female genitalia','Other specified congenital malformations of female genitalia','Malformations congénitales et anomalies chromosomiques','Q52.8'),
('congénital malformation of female genitalia, non spécifié','Congenital malformation of female genitalia, unspecified','Malformations congénitales et anomalies chromosomiques','Q52.9'),
('Ectopic testis, non spécifié','Ectopic testis, unspecified','Malformations congénitales et anomalies chromosomiques','Q53.00'),
('Ectopic testis, unilateral','Ectopic testis, unilateral','Malformations congénitales et anomalies chromosomiques','Q53.01'),
('Ectopic testes, bilateral','Ectopic testes, bilateral','Malformations congénitales et anomalies chromosomiques','Q53.02'),
('non spécifié undescended testicle, unilateral','Unspecified undescended testicle, unilateral','Malformations congénitales et anomalies chromosomiques','Q53.10'),
('Unilateral intraabdominal testis','Unilateral intraabdominal testis','Malformations congénitales et anomalies chromosomiques','Q53.111'),
('Unilateral inguinal testis','Unilateral inguinal testis','Malformations congénitales et anomalies chromosomiques','Q53.112'),
('Ectopic perineal testis, unilateral','Ectopic perineal testis, unilateral','Malformations congénitales et anomalies chromosomiques','Q53.12'),
('Unilateral high scrotal testis','Unilateral high scrotal testis','Malformations congénitales et anomalies chromosomiques','Q53.13'),
('Undescended testicle, non spécifié, bilateral','Undescended testicle, unspecified, bilateral','Malformations congénitales et anomalies chromosomiques','Q53.20'),
('Bilateral intraabdominal testes','Bilateral intraabdominal testes','Malformations congénitales et anomalies chromosomiques','Q53.211'),
('Bilateral inguinal testes','Bilateral inguinal testes','Malformations congénitales et anomalies chromosomiques','Q53.212'),
('Ectopic perineal testis, bilateral','Ectopic perineal testis, bilateral','Malformations congénitales et anomalies chromosomiques','Q53.22'),
('Bilateral high scrotal testes','Bilateral high scrotal testes','Malformations congénitales et anomalies chromosomiques','Q53.23'),
('Undescended testicle, non spécifié','Undescended testicle, unspecified','Malformations congénitales et anomalies chromosomiques','Q53.9'),
('Hypospadias, balanic','Hypospadias, balanic','Malformations congénitales et anomalies chromosomiques','Q54.0'),
('Hypospadias, penile','Hypospadias, penile','Malformations congénitales et anomalies chromosomiques','Q54.1'),
('Hypospadias, penoscrotal','Hypospadias, penoscrotal','Malformations congénitales et anomalies chromosomiques','Q54.2'),
('Hypospadias, perineal','Hypospadias, perineal','Malformations congénitales et anomalies chromosomiques','Q54.3'),
('congénital chordee','Congenital chordee','Malformations congénitales et anomalies chromosomiques','Q54.4'),
('autre hypospadias','Other hypospadias','Malformations congénitales et anomalies chromosomiques','Q54.8'),
('Hypospadias, non spécifié','Hypospadias, unspecified','Malformations congénitales et anomalies chromosomiques','Q54.9'),
('Absence and aplasia of testis','Absence and aplasia of testis','Malformations congénitales et anomalies chromosomiques','Q55.0'),
('Hypoplasia of testis and scrotum','Hypoplasia of testis and scrotum','Malformations congénitales et anomalies chromosomiques','Q55.1'),
('non spécifié congénital malformations of testis and scrotum','Unspecified congenital malformations of testis and scrotum','Malformations congénitales et anomalies chromosomiques','Q55.20'),
('Polyorchism','Polyorchism','Malformations congénitales et anomalies chromosomiques','Q55.21'),
('Retractile testis','Retractile testis','Malformations congénitales et anomalies chromosomiques','Q55.22'),
('Scrotal transposition','Scrotal transposition','Malformations congénitales et anomalies chromosomiques','Q55.23'),
('autre congénital malformations of testis and scrotum','Other congenital malformations of testis and scrotum','Malformations congénitales et anomalies chromosomiques','Q55.29'),
('Atresia of vas deferens','Atresia of vas deferens','Malformations congénitales et anomalies chromosomiques','Q55.3'),
('autre congénital malformations of vas deferens, epididymis, seminal vesicles and prostate','Other congenital malformations of vas deferens, epididymis, seminal vesicles and prostate','Malformations congénitales et anomalies chromosomiques','Q55.4'),
('congénital absence and aplasia of penis','Congenital absence and aplasia of penis','Malformations congénitales et anomalies chromosomiques','Q55.5'),
('Curvature of penis (lateral)','Curvature of penis (lateral)','Malformations congénitales et anomalies chromosomiques','Q55.61'),
('Hypoplasia of penis','Hypoplasia of penis','Malformations congénitales et anomalies chromosomiques','Q55.62'),
('congénital torsion of penis','Congenital torsion of penis','Malformations congénitales et anomalies chromosomiques','Q55.63'),
('Hidden penis','Hidden penis','Malformations congénitales et anomalies chromosomiques','Q55.64'),
('autre congénital malformation of penis','Other congenital malformation of penis','Malformations congénitales et anomalies chromosomiques','Q55.69'),
('congénital vasocutaneous fistula','Congenital vasocutaneous fistula','Malformations congénitales et anomalies chromosomiques','Q55.7'),
('autre specified congénital malformations of male genital organs','Other specified congenital malformations of male genital organs','Malformations congénitales et anomalies chromosomiques','Q55.8'),
('congénital malformation of male genital organ, non spécifié','Congenital malformation of male genital organ, unspecified','Malformations congénitales et anomalies chromosomiques','Q55.9'),
('Hermaphroditism, not elsewhere classified','Hermaphroditism, not elsewhere classified','Malformations congénitales et anomalies chromosomiques','Q56.0'),
('Male pseudohermaphroditism, not elsewhere classified','Male pseudohermaphroditism, not elsewhere classified','Malformations congénitales et anomalies chromosomiques','Q56.1'),
('Female pseudohermaphroditism, not elsewhere classified','Female pseudohermaphroditism, not elsewhere classified','Malformations congénitales et anomalies chromosomiques','Q56.2'),
('Pseudohermaphroditism, non spécifié','Pseudohermaphroditism, unspecified','Malformations congénitales et anomalies chromosomiques','Q56.3'),
('Indeterminate sex, non spécifié','Indeterminate sex, unspecified','Malformations congénitales et anomalies chromosomiques','Q56.4'),
('Renal agenesis, unilateral','Renal agenesis, unilateral','Malformations congénitales et anomalies chromosomiques','Q60.0'),
('Renal agenesis, bilateral','Renal agenesis, bilateral','Malformations congénitales et anomalies chromosomiques','Q60.1'),
('Renal agenesis, non spécifié','Renal agenesis, unspecified','Malformations congénitales et anomalies chromosomiques','Q60.2'),
('Renal hypoplasia, unilateral','Renal hypoplasia, unilateral','Malformations congénitales et anomalies chromosomiques','Q60.3'),
('Renal hypoplasia, bilateral','Renal hypoplasia, bilateral','Malformations congénitales et anomalies chromosomiques','Q60.4'),
('Renal hypoplasia, non spécifié','Renal hypoplasia, unspecified','Malformations congénitales et anomalies chromosomiques','Q60.5'),
('Potter''s syndrome','Potter''s syndrome','Malformations congénitales et anomalies chromosomiques','Q60.6'),
('congénital renal cyst, non spécifié','Congenital renal cyst, unspecified','Malformations congénitales et anomalies chromosomiques','Q61.00'),
('congénital single renal cyst','Congenital single renal cyst','Malformations congénitales et anomalies chromosomiques','Q61.01'),
('congénital multiple renal cysts','Congenital multiple renal cysts','Malformations congénitales et anomalies chromosomiques','Q61.02'),
('Cystic dilatation of collecting ducts','Cystic dilatation of collecting ducts','Malformations congénitales et anomalies chromosomiques','Q61.11'),
('autre polycystic kidney, infantile type','Other polycystic kidney, infantile type','Malformations congénitales et anomalies chromosomiques','Q61.19'),
('Polycystic kidney, adult type','Polycystic kidney, adult type','Malformations congénitales et anomalies chromosomiques','Q61.2'),
('Polycystic kidney, non spécifié','Polycystic kidney, unspecified','Malformations congénitales et anomalies chromosomiques','Q61.3'),
('Renal dysplasia','Renal dysplasia','Malformations congénitales et anomalies chromosomiques','Q61.4'),
('Medullary cystic kidney','Medullary cystic kidney','Malformations congénitales et anomalies chromosomiques','Q61.5'),
('autre cystic kidney diseases','Other cystic kidney diseases','Malformations congénitales et anomalies chromosomiques','Q61.8'),
('Cystic kidney maladie, non spécifié','Cystic kidney disease, unspecified','Malformations congénitales et anomalies chromosomiques','Q61.9'),
('congénital hydronephrosis','Congenital hydronephrosis','Malformations congénitales et anomalies chromosomiques','Q62.0'),
('congénital occlusion of ureter, non spécifié','Congenital occlusion of ureter, unspecified','Malformations congénitales et anomalies chromosomiques','Q62.10'),
('congénital occlusion of ureteropelvic junction','Congenital occlusion of ureteropelvic junction','Malformations congénitales et anomalies chromosomiques','Q62.11'),
('congénital occlusion of ureterovesical orifice','Congenital occlusion of ureterovesical orifice','Malformations congénitales et anomalies chromosomiques','Q62.12'),
('congénital megaureter','Congenital megaureter','Malformations congénitales et anomalies chromosomiques','Q62.2'),
('congénital ureterocele, orthotopic','Congenital ureterocele, orthotopic','Malformations congénitales et anomalies chromosomiques','Q62.31'),
('Cecoureterocele','Cecoureterocele','Malformations congénitales et anomalies chromosomiques','Q62.32'),
('autre obstructive defects of renal pelvis and ureter','Other obstructive defects of renal pelvis and ureter','Malformations congénitales et anomalies chromosomiques','Q62.39'),
('Agenesis of ureter','Agenesis of ureter','Malformations congénitales et anomalies chromosomiques','Q62.4'),
('Duplication of ureter','Duplication of ureter','Malformations congénitales et anomalies chromosomiques','Q62.5'),
('Malposition of ureter, non spécifié','Malposition of ureter, unspecified','Malformations congénitales et anomalies chromosomiques','Q62.60'),
('Deviation of ureter','Deviation of ureter','Malformations congénitales et anomalies chromosomiques','Q62.61')
ON CONFLICT (nom_fr) DO NOTHING;
