-- icd10v2_batch_182.sql (80 rows)
INSERT INTO pathologies (nom_fr, nom_en, categorie, icd10_code)
VALUES
('Postural lordosis, lumbosacral region','Postural lordosis, lumbosacral region','Maladies de l''appareil locomoteur','M40.47'),
('Lordosis, non spécifié, site non spécifié','Lordosis, unspecified, site unspecified','Maladies de l''appareil locomoteur','M40.50'),
('Lordosis, non spécifié, thoracolumbar region','Lordosis, unspecified, thoracolumbar region','Maladies de l''appareil locomoteur','M40.55'),
('Lordosis, non spécifié, lumbar region','Lordosis, unspecified, lumbar region','Maladies de l''appareil locomoteur','M40.56'),
('Lordosis, non spécifié, lumbosacral region','Lordosis, unspecified, lumbosacral region','Maladies de l''appareil locomoteur','M40.57'),
('Infantile idiopathic scoliosis, site non spécifié','Infantile idiopathic scoliosis, site unspecified','Maladies de l''appareil locomoteur','M41.00'),
('Infantile idiopathic scoliosis, cervical region','Infantile idiopathic scoliosis, cervical region','Maladies de l''appareil locomoteur','M41.02'),
('Infantile idiopathic scoliosis, cervicothoracic region','Infantile idiopathic scoliosis, cervicothoracic region','Maladies de l''appareil locomoteur','M41.03'),
('Infantile idiopathic scoliosis, thoracic region','Infantile idiopathic scoliosis, thoracic region','Maladies de l''appareil locomoteur','M41.04'),
('Infantile idiopathic scoliosis, thoracolumbar region','Infantile idiopathic scoliosis, thoracolumbar region','Maladies de l''appareil locomoteur','M41.05'),
('Infantile idiopathic scoliosis, lumbar region','Infantile idiopathic scoliosis, lumbar region','Maladies de l''appareil locomoteur','M41.06'),
('Infantile idiopathic scoliosis, lumbosacral region','Infantile idiopathic scoliosis, lumbosacral region','Maladies de l''appareil locomoteur','M41.07'),
('Infantile idiopathic scoliosis, sacral and sacrococcygeal region','Infantile idiopathic scoliosis, sacral and sacrococcygeal region','Maladies de l''appareil locomoteur','M41.08'),
('Juvenile idiopathic scoliosis, cervical region','Juvenile idiopathic scoliosis, cervical region','Maladies de l''appareil locomoteur','M41.112'),
('Juvenile idiopathic scoliosis, cervicothoracic region','Juvenile idiopathic scoliosis, cervicothoracic region','Maladies de l''appareil locomoteur','M41.113'),
('Juvenile idiopathic scoliosis, thoracic region','Juvenile idiopathic scoliosis, thoracic region','Maladies de l''appareil locomoteur','M41.114'),
('Juvenile idiopathic scoliosis, thoracolumbar region','Juvenile idiopathic scoliosis, thoracolumbar region','Maladies de l''appareil locomoteur','M41.115'),
('Juvenile idiopathic scoliosis, lumbar region','Juvenile idiopathic scoliosis, lumbar region','Maladies de l''appareil locomoteur','M41.116'),
('Juvenile idiopathic scoliosis, lumbosacral region','Juvenile idiopathic scoliosis, lumbosacral region','Maladies de l''appareil locomoteur','M41.117'),
('Juvenile idiopathic scoliosis, site non spécifié','Juvenile idiopathic scoliosis, site unspecified','Maladies de l''appareil locomoteur','M41.119'),
('Adolescent idiopathic scoliosis, cervical region','Adolescent idiopathic scoliosis, cervical region','Maladies de l''appareil locomoteur','M41.122'),
('Adolescent idiopathic scoliosis, cervicothoracic region','Adolescent idiopathic scoliosis, cervicothoracic region','Maladies de l''appareil locomoteur','M41.123'),
('Adolescent idiopathic scoliosis, thoracic region','Adolescent idiopathic scoliosis, thoracic region','Maladies de l''appareil locomoteur','M41.124'),
('Adolescent idiopathic scoliosis, thoracolumbar region','Adolescent idiopathic scoliosis, thoracolumbar region','Maladies de l''appareil locomoteur','M41.125'),
('Adolescent idiopathic scoliosis, lumbar region','Adolescent idiopathic scoliosis, lumbar region','Maladies de l''appareil locomoteur','M41.126'),
('Adolescent idiopathic scoliosis, lumbosacral region','Adolescent idiopathic scoliosis, lumbosacral region','Maladies de l''appareil locomoteur','M41.127'),
('Adolescent idiopathic scoliosis, site non spécifié','Adolescent idiopathic scoliosis, site unspecified','Maladies de l''appareil locomoteur','M41.129'),
('autre idiopathic scoliosis, site non spécifié','Other idiopathic scoliosis, site unspecified','Maladies de l''appareil locomoteur','M41.20'),
('autre idiopathic scoliosis, cervical region','Other idiopathic scoliosis, cervical region','Maladies de l''appareil locomoteur','M41.22'),
('autre idiopathic scoliosis, cervicothoracic region','Other idiopathic scoliosis, cervicothoracic region','Maladies de l''appareil locomoteur','M41.23'),
('autre idiopathic scoliosis, thoracic region','Other idiopathic scoliosis, thoracic region','Maladies de l''appareil locomoteur','M41.24'),
('autre idiopathic scoliosis, thoracolumbar region','Other idiopathic scoliosis, thoracolumbar region','Maladies de l''appareil locomoteur','M41.25'),
('autre idiopathic scoliosis, lumbar region','Other idiopathic scoliosis, lumbar region','Maladies de l''appareil locomoteur','M41.26'),
('autre idiopathic scoliosis, lumbosacral region','Other idiopathic scoliosis, lumbosacral region','Maladies de l''appareil locomoteur','M41.27'),
('Thoracogenic scoliosis, site non spécifié','Thoracogenic scoliosis, site unspecified','Maladies de l''appareil locomoteur','M41.30'),
('Thoracogenic scoliosis, thoracic region','Thoracogenic scoliosis, thoracic region','Maladies de l''appareil locomoteur','M41.34'),
('Thoracogenic scoliosis, thoracolumbar region','Thoracogenic scoliosis, thoracolumbar region','Maladies de l''appareil locomoteur','M41.35'),
('Neuromuscular scoliosis, site non spécifié','Neuromuscular scoliosis, site unspecified','Maladies de l''appareil locomoteur','M41.40'),
('Neuromuscular scoliosis, occipito-atlanto-axial region','Neuromuscular scoliosis, occipito-atlanto-axial region','Maladies de l''appareil locomoteur','M41.41'),
('Neuromuscular scoliosis, cervical region','Neuromuscular scoliosis, cervical region','Maladies de l''appareil locomoteur','M41.42'),
('Neuromuscular scoliosis, cervicothoracic region','Neuromuscular scoliosis, cervicothoracic region','Maladies de l''appareil locomoteur','M41.43'),
('Neuromuscular scoliosis, thoracic region','Neuromuscular scoliosis, thoracic region','Maladies de l''appareil locomoteur','M41.44'),
('Neuromuscular scoliosis, thoracolumbar region','Neuromuscular scoliosis, thoracolumbar region','Maladies de l''appareil locomoteur','M41.45'),
('Neuromuscular scoliosis, lumbar region','Neuromuscular scoliosis, lumbar region','Maladies de l''appareil locomoteur','M41.46'),
('Neuromuscular scoliosis, lumbosacral region','Neuromuscular scoliosis, lumbosacral region','Maladies de l''appareil locomoteur','M41.47'),
('autre secondaire scoliosis, site non spécifié','Other secondary scoliosis, site unspecified','Maladies de l''appareil locomoteur','M41.50'),
('autre secondaire scoliosis, cervical region','Other secondary scoliosis, cervical region','Maladies de l''appareil locomoteur','M41.52'),
('autre secondaire scoliosis, cervicothoracic region','Other secondary scoliosis, cervicothoracic region','Maladies de l''appareil locomoteur','M41.53'),
('autre secondaire scoliosis, thoracic region','Other secondary scoliosis, thoracic region','Maladies de l''appareil locomoteur','M41.54'),
('autre secondaire scoliosis, thoracolumbar region','Other secondary scoliosis, thoracolumbar region','Maladies de l''appareil locomoteur','M41.55'),
('autre secondaire scoliosis, lumbar region','Other secondary scoliosis, lumbar region','Maladies de l''appareil locomoteur','M41.56'),
('autre secondaire scoliosis, lumbosacral region','Other secondary scoliosis, lumbosacral region','Maladies de l''appareil locomoteur','M41.57'),
('autre forms of scoliosis, site non spécifié','Other forms of scoliosis, site unspecified','Maladies de l''appareil locomoteur','M41.80'),
('autre forms of scoliosis, cervical region','Other forms of scoliosis, cervical region','Maladies de l''appareil locomoteur','M41.82'),
('autre forms of scoliosis, cervicothoracic region','Other forms of scoliosis, cervicothoracic region','Maladies de l''appareil locomoteur','M41.83'),
('autre forms of scoliosis, thoracic region','Other forms of scoliosis, thoracic region','Maladies de l''appareil locomoteur','M41.84'),
('autre forms of scoliosis, thoracolumbar region','Other forms of scoliosis, thoracolumbar region','Maladies de l''appareil locomoteur','M41.85'),
('autre forms of scoliosis, lumbar region','Other forms of scoliosis, lumbar region','Maladies de l''appareil locomoteur','M41.86'),
('autre forms of scoliosis, lumbosacral region','Other forms of scoliosis, lumbosacral region','Maladies de l''appareil locomoteur','M41.87'),
('Scoliosis, non spécifié','Scoliosis, unspecified','Maladies de l''appareil locomoteur','M41.9'),
('Juvenile osteochondrosis of spine, site non spécifié','Juvenile osteochondrosis of spine, site unspecified','Maladies de l''appareil locomoteur','M42.00'),
('Juvenile osteochondrosis of spine, occipito-atlanto-axial region','Juvenile osteochondrosis of spine, occipito-atlanto-axial region','Maladies de l''appareil locomoteur','M42.01'),
('Juvenile osteochondrosis of spine, cervical region','Juvenile osteochondrosis of spine, cervical region','Maladies de l''appareil locomoteur','M42.02'),
('Juvenile osteochondrosis of spine, cervicothoracic region','Juvenile osteochondrosis of spine, cervicothoracic region','Maladies de l''appareil locomoteur','M42.03'),
('Juvenile osteochondrosis of spine, thoracic region','Juvenile osteochondrosis of spine, thoracic region','Maladies de l''appareil locomoteur','M42.04'),
('Juvenile osteochondrosis of spine, thoracolumbar region','Juvenile osteochondrosis of spine, thoracolumbar region','Maladies de l''appareil locomoteur','M42.05'),
('Juvenile osteochondrosis of spine, lumbar region','Juvenile osteochondrosis of spine, lumbar region','Maladies de l''appareil locomoteur','M42.06'),
('Juvenile osteochondrosis of spine, lumbosacral region','Juvenile osteochondrosis of spine, lumbosacral region','Maladies de l''appareil locomoteur','M42.07'),
('Juvenile osteochondrosis of spine, sacral and sacrococcygeal region','Juvenile osteochondrosis of spine, sacral and sacrococcygeal region','Maladies de l''appareil locomoteur','M42.08'),
('Juvenile osteochondrosis of spine, multiple sites in spine','Juvenile osteochondrosis of spine, multiple sites in spine','Maladies de l''appareil locomoteur','M42.09'),
('Adult osteochondrosis of spine, site non spécifié','Adult osteochondrosis of spine, site unspecified','Maladies de l''appareil locomoteur','M42.10'),
('Adult osteochondrosis of spine, occipito-atlanto-axial region','Adult osteochondrosis of spine, occipito-atlanto-axial region','Maladies de l''appareil locomoteur','M42.11'),
('Adult osteochondrosis of spine, cervical region','Adult osteochondrosis of spine, cervical region','Maladies de l''appareil locomoteur','M42.12'),
('Adult osteochondrosis of spine, cervicothoracic region','Adult osteochondrosis of spine, cervicothoracic region','Maladies de l''appareil locomoteur','M42.13'),
('Adult osteochondrosis of spine, thoracic region','Adult osteochondrosis of spine, thoracic region','Maladies de l''appareil locomoteur','M42.14'),
('Adult osteochondrosis of spine, thoracolumbar region','Adult osteochondrosis of spine, thoracolumbar region','Maladies de l''appareil locomoteur','M42.15'),
('Adult osteochondrosis of spine, lumbar region','Adult osteochondrosis of spine, lumbar region','Maladies de l''appareil locomoteur','M42.16'),
('Adult osteochondrosis of spine, lumbosacral region','Adult osteochondrosis of spine, lumbosacral region','Maladies de l''appareil locomoteur','M42.17'),
('Adult osteochondrosis of spine, sacral and sacrococcygeal region','Adult osteochondrosis of spine, sacral and sacrococcygeal region','Maladies de l''appareil locomoteur','M42.18'),
('Adult osteochondrosis of spine, multiple sites in spine','Adult osteochondrosis of spine, multiple sites in spine','Maladies de l''appareil locomoteur','M42.19')
ON CONFLICT (nom_fr) DO NOTHING;
