-- icd10v2_batch_176.sql (80 rows)
INSERT INTO pathologies (nom_fr, nom_en, categorie, icd10_code)
VALUES
('autre specified acquired deformities of left thigh','Other specified acquired deformities of left thigh','Maladies de l''appareil locomoteur','M21.852'),
('autre specified acquired deformities of non spécifié thigh','Other specified acquired deformities of unspecified thigh','Maladies de l''appareil locomoteur','M21.859'),
('autre specified acquired deformities of right lower leg','Other specified acquired deformities of right lower leg','Maladies de l''appareil locomoteur','M21.861'),
('autre specified acquired deformities of left lower leg','Other specified acquired deformities of left lower leg','Maladies de l''appareil locomoteur','M21.862'),
('autre specified acquired deformities of non spécifié lower leg','Other specified acquired deformities of unspecified lower leg','Maladies de l''appareil locomoteur','M21.869'),
('non spécifié acquired deformity of non spécifié limb','Unspecified acquired deformity of unspecified limb','Maladies de l''appareil locomoteur','M21.90'),
('non spécifié acquired deformity of right upper arm','Unspecified acquired deformity of right upper arm','Maladies de l''appareil locomoteur','M21.921'),
('non spécifié acquired deformity of left upper arm','Unspecified acquired deformity of left upper arm','Maladies de l''appareil locomoteur','M21.922'),
('non spécifié acquired deformity of non spécifié upper arm','Unspecified acquired deformity of unspecified upper arm','Maladies de l''appareil locomoteur','M21.929'),
('non spécifié acquired deformity of right forearm','Unspecified acquired deformity of right forearm','Maladies de l''appareil locomoteur','M21.931'),
('non spécifié acquired deformity of left forearm','Unspecified acquired deformity of left forearm','Maladies de l''appareil locomoteur','M21.932'),
('non spécifié acquired deformity of non spécifié forearm','Unspecified acquired deformity of unspecified forearm','Maladies de l''appareil locomoteur','M21.939'),
('non spécifié acquired deformity of hand, right hand','Unspecified acquired deformity of hand, right hand','Maladies de l''appareil locomoteur','M21.941'),
('non spécifié acquired deformity of hand, left hand','Unspecified acquired deformity of hand, left hand','Maladies de l''appareil locomoteur','M21.942'),
('non spécifié acquired deformity of hand, non spécifié hand','Unspecified acquired deformity of hand, unspecified hand','Maladies de l''appareil locomoteur','M21.949'),
('non spécifié acquired deformity of right thigh','Unspecified acquired deformity of right thigh','Maladies de l''appareil locomoteur','M21.951'),
('non spécifié acquired deformity of left thigh','Unspecified acquired deformity of left thigh','Maladies de l''appareil locomoteur','M21.952'),
('non spécifié acquired deformity of non spécifié thigh','Unspecified acquired deformity of unspecified thigh','Maladies de l''appareil locomoteur','M21.959'),
('non spécifié acquired deformity of right lower leg','Unspecified acquired deformity of right lower leg','Maladies de l''appareil locomoteur','M21.961'),
('non spécifié acquired deformity of left lower leg','Unspecified acquired deformity of left lower leg','Maladies de l''appareil locomoteur','M21.962'),
('non spécifié acquired deformity of non spécifié lower leg','Unspecified acquired deformity of unspecified lower leg','Maladies de l''appareil locomoteur','M21.969'),
('Recurrent dislocation of patella, non spécifié knee','Recurrent dislocation of patella, unspecified knee','Maladies de l''appareil locomoteur','M22.00'),
('Recurrent dislocation of patella, right knee','Recurrent dislocation of patella, right knee','Maladies de l''appareil locomoteur','M22.01'),
('Recurrent dislocation of patella, left knee','Recurrent dislocation of patella, left knee','Maladies de l''appareil locomoteur','M22.02'),
('Recurrent subluxation of patella, non spécifié knee','Recurrent subluxation of patella, unspecified knee','Maladies de l''appareil locomoteur','M22.10'),
('Recurrent subluxation of patella, right knee','Recurrent subluxation of patella, right knee','Maladies de l''appareil locomoteur','M22.11'),
('Recurrent subluxation of patella, left knee','Recurrent subluxation of patella, left knee','Maladies de l''appareil locomoteur','M22.12'),
('Patellofemoral disorders, right knee','Patellofemoral disorders, right knee','Maladies de l''appareil locomoteur','M22.2X1'),
('Patellofemoral disorders, left knee','Patellofemoral disorders, left knee','Maladies de l''appareil locomoteur','M22.2X2'),
('Patellofemoral disorders, non spécifié knee','Patellofemoral disorders, unspecified knee','Maladies de l''appareil locomoteur','M22.2X9'),
('autre derangements of patella, right knee','Other derangements of patella, right knee','Maladies de l''appareil locomoteur','M22.3X1'),
('autre derangements of patella, left knee','Other derangements of patella, left knee','Maladies de l''appareil locomoteur','M22.3X2'),
('autre derangements of patella, non spécifié knee','Other derangements of patella, unspecified knee','Maladies de l''appareil locomoteur','M22.3X9'),
('Chondromalacia patellae, non spécifié knee','Chondromalacia patellae, unspecified knee','Maladies de l''appareil locomoteur','M22.40'),
('Chondromalacia patellae, right knee','Chondromalacia patellae, right knee','Maladies de l''appareil locomoteur','M22.41'),
('Chondromalacia patellae, left knee','Chondromalacia patellae, left knee','Maladies de l''appareil locomoteur','M22.42'),
('autre disorders of patella, right knee','Other disorders of patella, right knee','Maladies de l''appareil locomoteur','M22.8X1'),
('autre disorders of patella, left knee','Other disorders of patella, left knee','Maladies de l''appareil locomoteur','M22.8X2'),
('autre disorders of patella, non spécifié knee','Other disorders of patella, unspecified knee','Maladies de l''appareil locomoteur','M22.8X9'),
('non spécifié trouble of patella, non spécifié knee','Unspecified disorder of patella, unspecified knee','Maladies de l''appareil locomoteur','M22.90'),
('non spécifié trouble of patella, right knee','Unspecified disorder of patella, right knee','Maladies de l''appareil locomoteur','M22.91'),
('non spécifié trouble of patella, left knee','Unspecified disorder of patella, left knee','Maladies de l''appareil locomoteur','M22.92'),
('Cystic meniscus, non spécifié lateral meniscus, right knee','Cystic meniscus, unspecified lateral meniscus, right knee','Maladies de l''appareil locomoteur','M23.000'),
('Cystic meniscus, non spécifié lateral meniscus, left knee','Cystic meniscus, unspecified lateral meniscus, left knee','Maladies de l''appareil locomoteur','M23.001'),
('Cystic meniscus, non spécifié lateral meniscus, non spécifié knee','Cystic meniscus, unspecified lateral meniscus, unspecified knee','Maladies de l''appareil locomoteur','M23.002'),
('Cystic meniscus, non spécifié medial meniscus, right knee','Cystic meniscus, unspecified medial meniscus, right knee','Maladies de l''appareil locomoteur','M23.003'),
('Cystic meniscus, non spécifié medial meniscus, left knee','Cystic meniscus, unspecified medial meniscus, left knee','Maladies de l''appareil locomoteur','M23.004'),
('Cystic meniscus, non spécifié medial meniscus, non spécifié knee','Cystic meniscus, unspecified medial meniscus, unspecified knee','Maladies de l''appareil locomoteur','M23.005'),
('Cystic meniscus, non spécifié meniscus, right knee','Cystic meniscus, unspecified meniscus, right knee','Maladies de l''appareil locomoteur','M23.006'),
('Cystic meniscus, non spécifié meniscus, left knee','Cystic meniscus, unspecified meniscus, left knee','Maladies de l''appareil locomoteur','M23.007'),
('Cystic meniscus, non spécifié meniscus, non spécifié knee','Cystic meniscus, unspecified meniscus, unspecified knee','Maladies de l''appareil locomoteur','M23.009'),
('Cystic meniscus, anterior horn of medial meniscus, right knee','Cystic meniscus, anterior horn of medial meniscus, right knee','Maladies de l''appareil locomoteur','M23.011'),
('Cystic meniscus, anterior horn of medial meniscus, left knee','Cystic meniscus, anterior horn of medial meniscus, left knee','Maladies de l''appareil locomoteur','M23.012'),
('Cystic meniscus, anterior horn of medial meniscus, non spécifié knee','Cystic meniscus, anterior horn of medial meniscus, unspecified knee','Maladies de l''appareil locomoteur','M23.019'),
('Cystic meniscus, posterior horn of medial meniscus, right knee','Cystic meniscus, posterior horn of medial meniscus, right knee','Maladies de l''appareil locomoteur','M23.021'),
('Cystic meniscus, posterior horn of medial meniscus, left knee','Cystic meniscus, posterior horn of medial meniscus, left knee','Maladies de l''appareil locomoteur','M23.022'),
('Cystic meniscus, posterior horn of medial meniscus, non spécifié knee','Cystic meniscus, posterior horn of medial meniscus, unspecified knee','Maladies de l''appareil locomoteur','M23.029'),
('Cystic meniscus, autre medial meniscus, right knee','Cystic meniscus, other medial meniscus, right knee','Maladies de l''appareil locomoteur','M23.031'),
('Cystic meniscus, autre medial meniscus, left knee','Cystic meniscus, other medial meniscus, left knee','Maladies de l''appareil locomoteur','M23.032'),
('Cystic meniscus, autre medial meniscus, non spécifié knee','Cystic meniscus, other medial meniscus, unspecified knee','Maladies de l''appareil locomoteur','M23.039'),
('Cystic meniscus, anterior horn of lateral meniscus, right knee','Cystic meniscus, anterior horn of lateral meniscus, right knee','Maladies de l''appareil locomoteur','M23.041'),
('Cystic meniscus, anterior horn of lateral meniscus, left knee','Cystic meniscus, anterior horn of lateral meniscus, left knee','Maladies de l''appareil locomoteur','M23.042'),
('Cystic meniscus, anterior horn of lateral meniscus, non spécifié knee','Cystic meniscus, anterior horn of lateral meniscus, unspecified knee','Maladies de l''appareil locomoteur','M23.049'),
('Cystic meniscus, posterior horn of lateral meniscus, right knee','Cystic meniscus, posterior horn of lateral meniscus, right knee','Maladies de l''appareil locomoteur','M23.051'),
('Cystic meniscus, posterior horn of lateral meniscus, left knee','Cystic meniscus, posterior horn of lateral meniscus, left knee','Maladies de l''appareil locomoteur','M23.052'),
('Cystic meniscus, posterior horn of lateral meniscus, non spécifié knee','Cystic meniscus, posterior horn of lateral meniscus, unspecified knee','Maladies de l''appareil locomoteur','M23.059'),
('Cystic meniscus, autre lateral meniscus, right knee','Cystic meniscus, other lateral meniscus, right knee','Maladies de l''appareil locomoteur','M23.061'),
('Cystic meniscus, autre lateral meniscus, left knee','Cystic meniscus, other lateral meniscus, left knee','Maladies de l''appareil locomoteur','M23.062'),
('Cystic meniscus, autre lateral meniscus, non spécifié knee','Cystic meniscus, other lateral meniscus, unspecified knee','Maladies de l''appareil locomoteur','M23.069'),
('Derangement of non spécifié lateral meniscus due to old tear or injury, right knee','Derangement of unspecified lateral meniscus due to old tear or injury, right knee','Maladies de l''appareil locomoteur','M23.200'),
('Derangement of non spécifié lateral meniscus due to old tear or injury, left knee','Derangement of unspecified lateral meniscus due to old tear or injury, left knee','Maladies de l''appareil locomoteur','M23.201'),
('Derangement of non spécifié lateral meniscus due to old tear or injury, non spécifié knee','Derangement of unspecified lateral meniscus due to old tear or injury, unspecified knee','Maladies de l''appareil locomoteur','M23.202'),
('Derangement of non spécifié medial meniscus due to old tear or injury, right knee','Derangement of unspecified medial meniscus due to old tear or injury, right knee','Maladies de l''appareil locomoteur','M23.203'),
('Derangement of non spécifié medial meniscus due to old tear or injury, left knee','Derangement of unspecified medial meniscus due to old tear or injury, left knee','Maladies de l''appareil locomoteur','M23.204'),
('Derangement of non spécifié medial meniscus due to old tear or injury, non spécifié knee','Derangement of unspecified medial meniscus due to old tear or injury, unspecified knee','Maladies de l''appareil locomoteur','M23.205'),
('Derangement of non spécifié meniscus due to old tear or injury, right knee','Derangement of unspecified meniscus due to old tear or injury, right knee','Maladies de l''appareil locomoteur','M23.206'),
('Derangement of non spécifié meniscus due to old tear or injury, left knee','Derangement of unspecified meniscus due to old tear or injury, left knee','Maladies de l''appareil locomoteur','M23.207'),
('Derangement of non spécifié meniscus due to old tear or injury, non spécifié knee','Derangement of unspecified meniscus due to old tear or injury, unspecified knee','Maladies de l''appareil locomoteur','M23.209'),
('Derangement of anterior horn of medial meniscus due to old tear or injury, right knee','Derangement of anterior horn of medial meniscus due to old tear or injury, right knee','Maladies de l''appareil locomoteur','M23.211'),
('Derangement of anterior horn of medial meniscus due to old tear or injury, left knee','Derangement of anterior horn of medial meniscus due to old tear or injury, left knee','Maladies de l''appareil locomoteur','M23.212')
ON CONFLICT (nom_fr) DO NOTHING;
