-- icd10v2_batch_279.sql (80 rows)
INSERT INTO pathologies (nom_fr, nom_en, categorie, icd10_code)
VALUES
('External constriction of autre specified part of neck, subsequent encounter','External constriction of other specified part of neck, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S10.84XD'),
('External constriction of autre specified part of neck, sequela','External constriction of other specified part of neck, sequela','Traumatismes, empoisonnements et autres causes externes','S10.84XS'),
('Superficial foreign body of autre specified part of neck, initial encounter','Superficial foreign body of other specified part of neck, initial encounter','Traumatismes, empoisonnements et autres causes externes','S10.85XA'),
('Superficial foreign body of autre specified part of neck, subsequent encounter','Superficial foreign body of other specified part of neck, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S10.85XD'),
('Superficial foreign body of autre specified part of neck, sequela','Superficial foreign body of other specified part of neck, sequela','Traumatismes, empoisonnements et autres causes externes','S10.85XS'),
('Insect bite of autre specified part of neck, initial encounter','Insect bite of other specified part of neck, initial encounter','Traumatismes, empoisonnements et autres causes externes','S10.86XA'),
('Insect bite of autre specified part of neck, subsequent encounter','Insect bite of other specified part of neck, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S10.86XD'),
('Insect bite of autre specified part of neck, sequela','Insect bite of other specified part of neck, sequela','Traumatismes, empoisonnements et autres causes externes','S10.86XS'),
('autre superficial bite of autre specified part of neck, initial encounter','Other superficial bite of other specified part of neck, initial encounter','Traumatismes, empoisonnements et autres causes externes','S10.87XA'),
('autre superficial bite of autre specified part of neck, subsequent encounter','Other superficial bite of other specified part of neck, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S10.87XD'),
('autre superficial bite of autre specified part of neck, sequela','Other superficial bite of other specified part of neck, sequela','Traumatismes, empoisonnements et autres causes externes','S10.87XS'),
('non spécifié superficial injury of non spécifié part of neck, initial encounter','Unspecified superficial injury of unspecified part of neck, initial encounter','Traumatismes, empoisonnements et autres causes externes','S10.90XA'),
('non spécifié superficial injury of non spécifié part of neck, subsequent encounter','Unspecified superficial injury of unspecified part of neck, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S10.90XD'),
('non spécifié superficial injury of non spécifié part of neck, sequela','Unspecified superficial injury of unspecified part of neck, sequela','Traumatismes, empoisonnements et autres causes externes','S10.90XS'),
('Abrasion of non spécifié part of neck, initial encounter','Abrasion of unspecified part of neck, initial encounter','Traumatismes, empoisonnements et autres causes externes','S10.91XA'),
('Abrasion of non spécifié part of neck, subsequent encounter','Abrasion of unspecified part of neck, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S10.91XD'),
('Abrasion of non spécifié part of neck, sequela','Abrasion of unspecified part of neck, sequela','Traumatismes, empoisonnements et autres causes externes','S10.91XS'),
('Blister (nonthermal) of non spécifié part of neck, initial encounter','Blister (nonthermal) of unspecified part of neck, initial encounter','Traumatismes, empoisonnements et autres causes externes','S10.92XA'),
('Blister (nonthermal) of non spécifié part of neck, subsequent encounter','Blister (nonthermal) of unspecified part of neck, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S10.92XD'),
('Blister (nonthermal) of non spécifié part of neck, sequela','Blister (nonthermal) of unspecified part of neck, sequela','Traumatismes, empoisonnements et autres causes externes','S10.92XS'),
('Contusion of non spécifié part of neck, initial encounter','Contusion of unspecified part of neck, initial encounter','Traumatismes, empoisonnements et autres causes externes','S10.93XA'),
('Contusion of non spécifié part of neck, subsequent encounter','Contusion of unspecified part of neck, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S10.93XD'),
('Contusion of non spécifié part of neck, sequela','Contusion of unspecified part of neck, sequela','Traumatismes, empoisonnements et autres causes externes','S10.93XS'),
('External constriction of non spécifié part of neck, initial encounter','External constriction of unspecified part of neck, initial encounter','Traumatismes, empoisonnements et autres causes externes','S10.94XA'),
('External constriction of non spécifié part of neck, subsequent encounter','External constriction of unspecified part of neck, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S10.94XD'),
('External constriction of non spécifié part of neck, sequela','External constriction of unspecified part of neck, sequela','Traumatismes, empoisonnements et autres causes externes','S10.94XS'),
('Superficial foreign body of non spécifié part of neck, initial encounter','Superficial foreign body of unspecified part of neck, initial encounter','Traumatismes, empoisonnements et autres causes externes','S10.95XA'),
('Superficial foreign body of non spécifié part of neck, subsequent encounter','Superficial foreign body of unspecified part of neck, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S10.95XD'),
('Superficial foreign body of non spécifié part of neck, sequela','Superficial foreign body of unspecified part of neck, sequela','Traumatismes, empoisonnements et autres causes externes','S10.95XS'),
('Insect bite of non spécifié part of neck, initial encounter','Insect bite of unspecified part of neck, initial encounter','Traumatismes, empoisonnements et autres causes externes','S10.96XA'),
('Insect bite of non spécifié part of neck, subsequent encounter','Insect bite of unspecified part of neck, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S10.96XD'),
('Insect bite of non spécifié part of neck, sequela','Insect bite of unspecified part of neck, sequela','Traumatismes, empoisonnements et autres causes externes','S10.96XS'),
('autre superficial bite of non spécifié part of neck, initial encounter','Other superficial bite of unspecified part of neck, initial encounter','Traumatismes, empoisonnements et autres causes externes','S10.97XA'),
('autre superficial bite of non spécifié part of neck, subsequent encounter','Other superficial bite of unspecified part of neck, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S10.97XD'),
('autre superficial bite of non spécifié part of neck, sequela','Other superficial bite of unspecified part of neck, sequela','Traumatismes, empoisonnements et autres causes externes','S10.97XS'),
('Laceration without foreign body of larynx, initial encounter','Laceration without foreign body of larynx, initial encounter','Traumatismes, empoisonnements et autres causes externes','S11.011A'),
('Laceration without foreign body of larynx, subsequent encounter','Laceration without foreign body of larynx, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S11.011D'),
('Laceration without foreign body of larynx, sequela','Laceration without foreign body of larynx, sequela','Traumatismes, empoisonnements et autres causes externes','S11.011S'),
('Laceration with foreign body of larynx, initial encounter','Laceration with foreign body of larynx, initial encounter','Traumatismes, empoisonnements et autres causes externes','S11.012A'),
('Laceration with foreign body of larynx, subsequent encounter','Laceration with foreign body of larynx, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S11.012D'),
('Laceration with foreign body of larynx, sequela','Laceration with foreign body of larynx, sequela','Traumatismes, empoisonnements et autres causes externes','S11.012S'),
('Puncture wound without foreign body of larynx, initial encounter','Puncture wound without foreign body of larynx, initial encounter','Traumatismes, empoisonnements et autres causes externes','S11.013A'),
('Puncture wound without foreign body of larynx, subsequent encounter','Puncture wound without foreign body of larynx, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S11.013D'),
('Puncture wound without foreign body of larynx, sequela','Puncture wound without foreign body of larynx, sequela','Traumatismes, empoisonnements et autres causes externes','S11.013S'),
('Puncture wound with foreign body of larynx, initial encounter','Puncture wound with foreign body of larynx, initial encounter','Traumatismes, empoisonnements et autres causes externes','S11.014A'),
('Puncture wound with foreign body of larynx, subsequent encounter','Puncture wound with foreign body of larynx, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S11.014D'),
('Puncture wound with foreign body of larynx, sequela','Puncture wound with foreign body of larynx, sequela','Traumatismes, empoisonnements et autres causes externes','S11.014S'),
('Open bite of larynx, initial encounter','Open bite of larynx, initial encounter','Traumatismes, empoisonnements et autres causes externes','S11.015A'),
('Open bite of larynx, subsequent encounter','Open bite of larynx, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S11.015D'),
('Open bite of larynx, sequela','Open bite of larynx, sequela','Traumatismes, empoisonnements et autres causes externes','S11.015S'),
('non spécifié open wound of larynx, initial encounter','Unspecified open wound of larynx, initial encounter','Traumatismes, empoisonnements et autres causes externes','S11.019A'),
('non spécifié open wound of larynx, subsequent encounter','Unspecified open wound of larynx, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S11.019D'),
('non spécifié open wound of larynx, sequela','Unspecified open wound of larynx, sequela','Traumatismes, empoisonnements et autres causes externes','S11.019S'),
('Laceration without foreign body of trachea, initial encounter','Laceration without foreign body of trachea, initial encounter','Traumatismes, empoisonnements et autres causes externes','S11.021A'),
('Laceration without foreign body of trachea, subsequent encounter','Laceration without foreign body of trachea, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S11.021D'),
('Laceration without foreign body of trachea, sequela','Laceration without foreign body of trachea, sequela','Traumatismes, empoisonnements et autres causes externes','S11.021S'),
('Laceration with foreign body of trachea, initial encounter','Laceration with foreign body of trachea, initial encounter','Traumatismes, empoisonnements et autres causes externes','S11.022A'),
('Laceration with foreign body of trachea, subsequent encounter','Laceration with foreign body of trachea, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S11.022D'),
('Laceration with foreign body of trachea, sequela','Laceration with foreign body of trachea, sequela','Traumatismes, empoisonnements et autres causes externes','S11.022S'),
('Puncture wound without foreign body of trachea, initial encounter','Puncture wound without foreign body of trachea, initial encounter','Traumatismes, empoisonnements et autres causes externes','S11.023A'),
('Puncture wound without foreign body of trachea, subsequent encounter','Puncture wound without foreign body of trachea, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S11.023D'),
('Puncture wound without foreign body of trachea, sequela','Puncture wound without foreign body of trachea, sequela','Traumatismes, empoisonnements et autres causes externes','S11.023S'),
('Puncture wound with foreign body of trachea, initial encounter','Puncture wound with foreign body of trachea, initial encounter','Traumatismes, empoisonnements et autres causes externes','S11.024A'),
('Puncture wound with foreign body of trachea, subsequent encounter','Puncture wound with foreign body of trachea, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S11.024D'),
('Puncture wound with foreign body of trachea, sequela','Puncture wound with foreign body of trachea, sequela','Traumatismes, empoisonnements et autres causes externes','S11.024S'),
('Open bite of trachea, initial encounter','Open bite of trachea, initial encounter','Traumatismes, empoisonnements et autres causes externes','S11.025A'),
('Open bite of trachea, subsequent encounter','Open bite of trachea, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S11.025D'),
('Open bite of trachea, sequela','Open bite of trachea, sequela','Traumatismes, empoisonnements et autres causes externes','S11.025S'),
('non spécifié open wound of trachea, initial encounter','Unspecified open wound of trachea, initial encounter','Traumatismes, empoisonnements et autres causes externes','S11.029A'),
('non spécifié open wound of trachea, subsequent encounter','Unspecified open wound of trachea, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S11.029D'),
('non spécifié open wound of trachea, sequela','Unspecified open wound of trachea, sequela','Traumatismes, empoisonnements et autres causes externes','S11.029S'),
('Laceration without foreign body of vocal cord, initial encounter','Laceration without foreign body of vocal cord, initial encounter','Traumatismes, empoisonnements et autres causes externes','S11.031A'),
('Laceration without foreign body of vocal cord, subsequent encounter','Laceration without foreign body of vocal cord, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S11.031D'),
('Laceration without foreign body of vocal cord, sequela','Laceration without foreign body of vocal cord, sequela','Traumatismes, empoisonnements et autres causes externes','S11.031S'),
('Laceration with foreign body of vocal cord, initial encounter','Laceration with foreign body of vocal cord, initial encounter','Traumatismes, empoisonnements et autres causes externes','S11.032A'),
('Laceration with foreign body of vocal cord, subsequent encounter','Laceration with foreign body of vocal cord, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S11.032D'),
('Laceration with foreign body of vocal cord, sequela','Laceration with foreign body of vocal cord, sequela','Traumatismes, empoisonnements et autres causes externes','S11.032S'),
('Puncture wound without foreign body of vocal cord, initial encounter','Puncture wound without foreign body of vocal cord, initial encounter','Traumatismes, empoisonnements et autres causes externes','S11.033A'),
('Puncture wound without foreign body of vocal cord, subsequent encounter','Puncture wound without foreign body of vocal cord, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S11.033D'),
('Puncture wound without foreign body of vocal cord, sequela','Puncture wound without foreign body of vocal cord, sequela','Traumatismes, empoisonnements et autres causes externes','S11.033S')
ON CONFLICT (nom_fr) DO NOTHING;
