-- icd10v2_batch_466.sql (80 rows)
INSERT INTO pathologies (nom_fr, nom_en, categorie, icd10_code)
VALUES
('Activity, basketball','Activity, basketball','Causes externes de morbidité et de mortalité','Y93.67'),
('Activity, volleyball (beach) (court)','Activity, volleyball (beach) (court)','Causes externes de morbidité et de mortalité','Y93.68'),
('Activity, physical games generally associated with school recess, summer camp and children','Activity, physical games generally associated with school recess, summer camp and children','Causes externes de morbidité et de mortalité','Y93.6A'),
('Activity, autre involving autre sports and athletics played as a team or group','Activity, other involving other sports and athletics played as a team or group','Causes externes de morbidité et de mortalité','Y93.69'),
('Activity, boxing','Activity, boxing','Causes externes de morbidité et de mortalité','Y93.71'),
('Activity, wrestling','Activity, wrestling','Causes externes de morbidité et de mortalité','Y93.72'),
('Activity, racquet and hand sports','Activity, racquet and hand sports','Causes externes de morbidité et de mortalité','Y93.73'),
('Activity, frisbee','Activity, frisbee','Causes externes de morbidité et de mortalité','Y93.74'),
('Activity, martial arts','Activity, martial arts','Causes externes de morbidité et de mortalité','Y93.75'),
('Activity, autre specified sports and athletics','Activity, other specified sports and athletics','Causes externes de morbidité et de mortalité','Y93.79'),
('Activity, exercise machines primarily for cardiorespiratory conditioning','Activity, exercise machines primarily for cardiorespiratory conditioning','Causes externes de morbidité et de mortalité','Y93.A1'),
('Activity, calisthenics','Activity, calisthenics','Causes externes de morbidité et de mortalité','Y93.A2'),
('Activity, aerobic and step exercise','Activity, aerobic and step exercise','Causes externes de morbidité et de mortalité','Y93.A3'),
('Activity, circuit training','Activity, circuit training','Causes externes de morbidité et de mortalité','Y93.A4'),
('Activity, obstacle course','Activity, obstacle course','Causes externes de morbidité et de mortalité','Y93.A5'),
('Activity, grass drills','Activity, grass drills','Causes externes de morbidité et de mortalité','Y93.A6'),
('Activity, autre involving cardiorespiratory exercise','Activity, other involving cardiorespiratory exercise','Causes externes de morbidité et de mortalité','Y93.A9'),
('Activity, exercise machines primarily for muscle strengthening','Activity, exercise machines primarily for muscle strengthening','Causes externes de morbidité et de mortalité','Y93.B1'),
('Activity, push-ups, pull-ups, sit-ups','Activity, push-ups, pull-ups, sit-ups','Causes externes de morbidité et de mortalité','Y93.B2'),
('Activity, free weights','Activity, free weights','Causes externes de morbidité et de mortalité','Y93.B3'),
('Activity, pilates','Activity, pilates','Causes externes de morbidité et de mortalité','Y93.B4'),
('Activity, autre involving muscle strengthening exercises','Activity, other involving muscle strengthening exercises','Causes externes de morbidité et de mortalité','Y93.B9'),
('Activity, computer keyboarding','Activity, computer keyboarding','Causes externes de morbidité et de mortalité','Y93.C1'),
('Activity, hand held interactive electronic device','Activity, hand held interactive electronic device','Causes externes de morbidité et de mortalité','Y93.C2'),
('Activity, autre involving computer technology and electronic devices','Activity, other involving computer technology and electronic devices','Causes externes de morbidité et de mortalité','Y93.C9'),
('Activity, knitting and crocheting','Activity, knitting and crocheting','Causes externes de morbidité et de mortalité','Y93.D1'),
('Activity, sewing','Activity, sewing','Causes externes de morbidité et de mortalité','Y93.D2'),
('Activity, furniture building and finishing','Activity, furniture building and finishing','Causes externes de morbidité et de mortalité','Y93.D3'),
('Activity, autre involving arts and handcrafts','Activity, other involving arts and handcrafts','Causes externes de morbidité et de mortalité','Y93.D9'),
('Activity, personal bathing and showering','Activity, personal bathing and showering','Causes externes de morbidité et de mortalité','Y93.E1'),
('Activity, laundry','Activity, laundry','Causes externes de morbidité et de mortalité','Y93.E2'),
('Activity, vacuuming','Activity, vacuuming','Causes externes de morbidité et de mortalité','Y93.E3'),
('Activity, ironing','Activity, ironing','Causes externes de morbidité et de mortalité','Y93.E4'),
('Activity, floor mopping and cleaning','Activity, floor mopping and cleaning','Causes externes de morbidité et de mortalité','Y93.E5'),
('Activity, residential relocation','Activity, residential relocation','Causes externes de morbidité et de mortalité','Y93.E6'),
('Activity, autre personal hygiene','Activity, other personal hygiene','Causes externes de morbidité et de mortalité','Y93.E8'),
('Activity, autre interior property and clothing maintenance','Activity, other interior property and clothing maintenance','Causes externes de morbidité et de mortalité','Y93.E9'),
('Activity, caregiving, bathing','Activity, caregiving, bathing','Causes externes de morbidité et de mortalité','Y93.F1'),
('Activity, caregiving, lifting','Activity, caregiving, lifting','Causes externes de morbidité et de mortalité','Y93.F2'),
('Activity, autre caregiving','Activity, other caregiving','Causes externes de morbidité et de mortalité','Y93.F9'),
('Activity, food preparation and clean up','Activity, food preparation and clean up','Causes externes de morbidité et de mortalité','Y93.G1'),
('Activity, grilling and smoking food','Activity, grilling and smoking food','Causes externes de morbidité et de mortalité','Y93.G2'),
('Activity, cooking and baking','Activity, cooking and baking','Causes externes de morbidité et de mortalité','Y93.G3'),
('Activity, autre involving cooking and grilling','Activity, other involving cooking and grilling','Causes externes de morbidité et de mortalité','Y93.G9'),
('Activity, digging, shoveling and raking','Activity, digging, shoveling and raking','Causes externes de morbidité et de mortalité','Y93.H1'),
('Activity, gardening and landscaping','Activity, gardening and landscaping','Causes externes de morbidité et de mortalité','Y93.H2'),
('Activity, building and construction','Activity, building and construction','Causes externes de morbidité et de mortalité','Y93.H3'),
('Activity, autre involving exterior property and land maintenance, building and construction','Activity, other involving exterior property and land maintenance, building and construction','Causes externes de morbidité et de mortalité','Y93.H9'),
('Activity, roller coaster riding','Activity, roller coaster riding','Causes externes de morbidité et de mortalité','Y93.I1'),
('Activity, autre involving external motion','Activity, other involving external motion','Causes externes de morbidité et de mortalité','Y93.I9'),
('Activity, piano playing','Activity, piano playing','Causes externes de morbidité et de mortalité','Y93.J1'),
('Activity, drum and autre percussion instrument playing','Activity, drum and other percussion instrument playing','Causes externes de morbidité et de mortalité','Y93.J2'),
('Activity, string instrument playing','Activity, string instrument playing','Causes externes de morbidité et de mortalité','Y93.J3'),
('Activity, winds and brass instrument playing','Activity, winds and brass instrument playing','Causes externes de morbidité et de mortalité','Y93.J4'),
('Activity, walking an animal','Activity, walking an animal','Causes externes de morbidité et de mortalité','Y93.K1'),
('Activity, milking an animal','Activity, milking an animal','Causes externes de morbidité et de mortalité','Y93.K2'),
('Activity, grooming and shearing an animal','Activity, grooming and shearing an animal','Causes externes de morbidité et de mortalité','Y93.K3'),
('Activity, autre involving animal care','Activity, other involving animal care','Causes externes de morbidité et de mortalité','Y93.K9'),
('Activity, splitting wood','Activity, splitting wood','Causes externes de morbidité et de mortalité','Y93.L1'),
('Activity, autre outdoor activity','Activity, other outdoor activity','Causes externes de morbidité et de mortalité','Y93.L9'),
('Activity, refereeing a sports activity','Activity, refereeing a sports activity','Causes externes de morbidité et de mortalité','Y93.81'),
('Activity, spectator at an event','Activity, spectator at an event','Causes externes de morbidité et de mortalité','Y93.82'),
('Activity, rough housing and horseplay','Activity, rough housing and horseplay','Causes externes de morbidité et de mortalité','Y93.83'),
('Activity, sleeping','Activity, sleeping','Causes externes de morbidité et de mortalité','Y93.84'),
('Activity, choking game','Activity, choking game','Causes externes de morbidité et de mortalité','Y93.85'),
('Activity, autre specified','Activity, other specified','Causes externes de morbidité et de mortalité','Y93.89'),
('Activity, non spécifié','Activity, unspecified','Causes externes de morbidité et de mortalité','Y93.9'),
('Nosocomial condition','Nosocomial condition','Causes externes de morbidité et de mortalité','Y95'),
('Civilian activity done for income or pay','Civilian activity done for income or pay','Causes externes de morbidité et de mortalité','Y99.0'),
('Military activity','Military activity','Causes externes de morbidité et de mortalité','Y99.1'),
('Volunteer activity','Volunteer activity','Causes externes de morbidité et de mortalité','Y99.2'),
('autre external cause status','Other external cause status','Causes externes de morbidité et de mortalité','Y99.8'),
('non spécifié external cause status','Unspecified external cause status','Causes externes de morbidité et de mortalité','Y99.9'),
('Encounter for general adult medical examination without abnormal findings','Encounter for general adult medical examination without abnormal findings','Facteurs influant sur l''état de santé','Z00.00'),
('Encounter for general adult medical examination with abnormal findings','Encounter for general adult medical examination with abnormal findings','Facteurs influant sur l''état de santé','Z00.01'),
('Health examination for newborn under 8 days old','Health examination for newborn under 8 days old','Facteurs influant sur l''état de santé','Z00.110'),
('Health examination for newborn 8 to 28 days old','Health examination for newborn 8 to 28 days old','Facteurs influant sur l''état de santé','Z00.111'),
('Encounter for routine child health examination with abnormal findings','Encounter for routine child health examination with abnormal findings','Facteurs influant sur l''état de santé','Z00.121'),
('Encounter for routine child health examination without abnormal findings','Encounter for routine child health examination without abnormal findings','Facteurs influant sur l''état de santé','Z00.129'),
('Encounter for examination for period of rapid growth in childhood','Encounter for examination for period of rapid growth in childhood','Facteurs influant sur l''état de santé','Z00.2')
ON CONFLICT (nom_fr) DO NOTHING;
