-- icd10v2_batch_132.sql (80 rows)
INSERT INTO pathologies (nom_fr, nom_en, categorie, icd10_code)
VALUES
('chronique venous hypertension (idiopathic) without complications of left lower extremity','Chronic venous hypertension (idiopathic) without complications of left lower extremity','Maladies de l''appareil circulatoire','I87.302'),
('chronique venous hypertension (idiopathic) without complications of bilateral lower extremity','Chronic venous hypertension (idiopathic) without complications of bilateral lower extremity','Maladies de l''appareil circulatoire','I87.303'),
('chronique venous hypertension (idiopathic) without complications of non spécifié lower extremity','Chronic venous hypertension (idiopathic) without complications of unspecified lower extremity','Maladies de l''appareil circulatoire','I87.309'),
('chronique venous hypertension (idiopathic) with ulcer of right lower extremity','Chronic venous hypertension (idiopathic) with ulcer of right lower extremity','Maladies de l''appareil circulatoire','I87.311'),
('chronique venous hypertension (idiopathic) with ulcer of left lower extremity','Chronic venous hypertension (idiopathic) with ulcer of left lower extremity','Maladies de l''appareil circulatoire','I87.312'),
('chronique venous hypertension (idiopathic) with ulcer of bilateral lower extremity','Chronic venous hypertension (idiopathic) with ulcer of bilateral lower extremity','Maladies de l''appareil circulatoire','I87.313'),
('chronique venous hypertension (idiopathic) with ulcer of non spécifié lower extremity','Chronic venous hypertension (idiopathic) with ulcer of unspecified lower extremity','Maladies de l''appareil circulatoire','I87.319'),
('chronique venous hypertension (idiopathic) with inflammation of right lower extremity','Chronic venous hypertension (idiopathic) with inflammation of right lower extremity','Maladies de l''appareil circulatoire','I87.321'),
('chronique venous hypertension (idiopathic) with inflammation of left lower extremity','Chronic venous hypertension (idiopathic) with inflammation of left lower extremity','Maladies de l''appareil circulatoire','I87.322'),
('chronique venous hypertension (idiopathic) with inflammation of bilateral lower extremity','Chronic venous hypertension (idiopathic) with inflammation of bilateral lower extremity','Maladies de l''appareil circulatoire','I87.323'),
('chronique venous hypertension (idiopathic) with inflammation of non spécifié lower extremity','Chronic venous hypertension (idiopathic) with inflammation of unspecified lower extremity','Maladies de l''appareil circulatoire','I87.329'),
('chronique venous hypertension (idiopathic) with ulcer and inflammation of right lower extremity','Chronic venous hypertension (idiopathic) with ulcer and inflammation of right lower extremity','Maladies de l''appareil circulatoire','I87.331'),
('chronique venous hypertension (idiopathic) with ulcer and inflammation of left lower extremity','Chronic venous hypertension (idiopathic) with ulcer and inflammation of left lower extremity','Maladies de l''appareil circulatoire','I87.332'),
('chronique venous hypertension (idiopathic) with ulcer and inflammation of bilateral lower extremity','Chronic venous hypertension (idiopathic) with ulcer and inflammation of bilateral lower extremity','Maladies de l''appareil circulatoire','I87.333'),
('chronique venous hypertension (idiopathic) with ulcer and inflammation of non spécifié lower extremity','Chronic venous hypertension (idiopathic) with ulcer and inflammation of unspecified lower extremity','Maladies de l''appareil circulatoire','I87.339'),
('chronique venous hypertension (idiopathic) with autre complications of right lower extremity','Chronic venous hypertension (idiopathic) with other complications of right lower extremity','Maladies de l''appareil circulatoire','I87.391'),
('chronique venous hypertension (idiopathic) with autre complications of left lower extremity','Chronic venous hypertension (idiopathic) with other complications of left lower extremity','Maladies de l''appareil circulatoire','I87.392'),
('chronique venous hypertension (idiopathic) with autre complications of bilateral lower extremity','Chronic venous hypertension (idiopathic) with other complications of bilateral lower extremity','Maladies de l''appareil circulatoire','I87.393'),
('chronique venous hypertension (idiopathic) with autre complications of non spécifié lower extremity','Chronic venous hypertension (idiopathic) with other complications of unspecified lower extremity','Maladies de l''appareil circulatoire','I87.399'),
('autre specified disorders of veins','Other specified disorders of veins','Maladies de l''appareil circulatoire','I87.8'),
('trouble of vein, non spécifié','Disorder of vein, unspecified','Maladies de l''appareil circulatoire','I87.9'),
('Nonspecific mesenteric lymphadenitis','Nonspecific mesenteric lymphadenitis','Maladies de l''appareil circulatoire','I88.0'),
('chronique lymphadenitis, except mesenteric','Chronic lymphadenitis, except mesenteric','Maladies de l''appareil circulatoire','I88.1'),
('autre nonspecific lymphadenitis','Other nonspecific lymphadenitis','Maladies de l''appareil circulatoire','I88.8'),
('Nonspecific lymphadenitis, non spécifié','Nonspecific lymphadenitis, unspecified','Maladies de l''appareil circulatoire','I88.9'),
('Lymphedema, not elsewhere classified','Lymphedema, not elsewhere classified','Maladies de l''appareil circulatoire','I89.0'),
('Lymphangitis','Lymphangitis','Maladies de l''appareil circulatoire','I89.1'),
('autre specified noninfective disorders of lymphatic vessels and lymph nodes','Other specified noninfective disorders of lymphatic vessels and lymph nodes','Maladies de l''appareil circulatoire','I89.8'),
('Noninfective trouble of lymphatic vessels and lymph nodes, non spécifié','Noninfective disorder of lymphatic vessels and lymph nodes, unspecified','Maladies de l''appareil circulatoire','I89.9'),
('Idiopathic hypotension','Idiopathic hypotension','Maladies de l''appareil circulatoire','I95.0'),
('Orthostatic hypotension','Orthostatic hypotension','Maladies de l''appareil circulatoire','I95.1'),
('Hypotension due to drugs','Hypotension due to drugs','Maladies de l''appareil circulatoire','I95.2'),
('Hypotension of hemodialysis','Hypotension of hemodialysis','Maladies de l''appareil circulatoire','I95.3'),
('Postprocedural hypotension','Postprocedural hypotension','Maladies de l''appareil circulatoire','I95.81'),
('autre hypotension','Other hypotension','Maladies de l''appareil circulatoire','I95.89'),
('Hypotension, non spécifié','Hypotension, unspecified','Maladies de l''appareil circulatoire','I95.9'),
('Gangrene, not elsewhere classified','Gangrene, not elsewhere classified','Maladies de l''appareil circulatoire','I96'),
('Postcardiotomy syndrome','Postcardiotomy syndrome','Maladies de l''appareil circulatoire','I97.0'),
('Postprocedural cardiac insufficiency following cardiac surgery','Postprocedural cardiac insufficiency following cardiac surgery','Maladies de l''appareil circulatoire','I97.110'),
('Postprocedural cardiac insufficiency following autre surgery','Postprocedural cardiac insufficiency following other surgery','Maladies de l''appareil circulatoire','I97.111'),
('Postprocedural cardiac arrest following cardiac surgery','Postprocedural cardiac arrest following cardiac surgery','Maladies de l''appareil circulatoire','I97.120'),
('Postprocedural cardiac arrest following autre surgery','Postprocedural cardiac arrest following other surgery','Maladies de l''appareil circulatoire','I97.121'),
('Postprocedural heart insuffisance following cardiac surgery','Postprocedural heart failure following cardiac surgery','Maladies de l''appareil circulatoire','I97.130'),
('Postprocedural heart insuffisance following autre surgery','Postprocedural heart failure following other surgery','Maladies de l''appareil circulatoire','I97.131'),
('autre postprocedural cardiac functional disturbances following cardiac surgery','Other postprocedural cardiac functional disturbances following cardiac surgery','Maladies de l''appareil circulatoire','I97.190'),
('autre postprocedural cardiac functional disturbances following autre surgery','Other postprocedural cardiac functional disturbances following other surgery','Maladies de l''appareil circulatoire','I97.191'),
('Postmastectomy lymphedema syndrome','Postmastectomy lymphedema syndrome','Maladies de l''appareil circulatoire','I97.2'),
('Postprocedural hypertension','Postprocedural hypertension','Maladies de l''appareil circulatoire','I97.3'),
('Intraoperative hémorragie and hematoma of a circulatory system organ or structure complicating a cardiac catheterization','Intraoperative hemorrhage and hematoma of a circulatory system organ or structure complicating a cardiac catheterization','Maladies de l''appareil circulatoire','I97.410'),
('Intraoperative hémorragie and hematoma of a circulatory system organ or structure complicating a cardiac bypass','Intraoperative hemorrhage and hematoma of a circulatory system organ or structure complicating a cardiac bypass','Maladies de l''appareil circulatoire','I97.411'),
('Intraoperative hémorragie and hematoma of a circulatory system organ or structure complicating autre circulatory system procedure','Intraoperative hemorrhage and hematoma of a circulatory system organ or structure complicating other circulatory system procedure','Maladies de l''appareil circulatoire','I97.418'),
('Intraoperative hémorragie and hematoma of a circulatory system organ or structure complicating autre procedure','Intraoperative hemorrhage and hematoma of a circulatory system organ or structure complicating other procedure','Maladies de l''appareil circulatoire','I97.42'),
('Accidental puncture and laceration of a circulatory system organ or structure during a circulatory system procedure','Accidental puncture and laceration of a circulatory system organ or structure during a circulatory system procedure','Maladies de l''appareil circulatoire','I97.51'),
('Accidental puncture and laceration of a circulatory system organ or structure during autre procedure','Accidental puncture and laceration of a circulatory system organ or structure during other procedure','Maladies de l''appareil circulatoire','I97.52'),
('Postprocedural hémorragie of a circulatory system organ or structure following a cardiac catheterization','Postprocedural hemorrhage of a circulatory system organ or structure following a cardiac catheterization','Maladies de l''appareil circulatoire','I97.610'),
('Postprocedural hémorragie of a circulatory system organ or structure following cardiac bypass','Postprocedural hemorrhage of a circulatory system organ or structure following cardiac bypass','Maladies de l''appareil circulatoire','I97.611'),
('Postprocedural hémorragie of a circulatory system organ or structure following autre circulatory system procedure','Postprocedural hemorrhage of a circulatory system organ or structure following other circulatory system procedure','Maladies de l''appareil circulatoire','I97.618'),
('Postprocedural hémorragie of a circulatory system organ or structure following autre procedure','Postprocedural hemorrhage of a circulatory system organ or structure following other procedure','Maladies de l''appareil circulatoire','I97.620'),
('Postprocedural hematoma of a circulatory system organ or structure following autre procedure','Postprocedural hematoma of a circulatory system organ or structure following other procedure','Maladies de l''appareil circulatoire','I97.621'),
('Postprocedural seroma of a circulatory system organ or structure following autre procedure','Postprocedural seroma of a circulatory system organ or structure following other procedure','Maladies de l''appareil circulatoire','I97.622'),
('Postprocedural hematoma of a circulatory system organ or structure following a cardiac catheterization','Postprocedural hematoma of a circulatory system organ or structure following a cardiac catheterization','Maladies de l''appareil circulatoire','I97.630'),
('Postprocedural hematoma of a circulatory system organ or structure following cardiac bypass','Postprocedural hematoma of a circulatory system organ or structure following cardiac bypass','Maladies de l''appareil circulatoire','I97.631'),
('Postprocedural hematoma of a circulatory system organ or structure following autre circulatory system procedure','Postprocedural hematoma of a circulatory system organ or structure following other circulatory system procedure','Maladies de l''appareil circulatoire','I97.638'),
('Postprocedural seroma of a circulatory system organ or structure following a cardiac catheterization','Postprocedural seroma of a circulatory system organ or structure following a cardiac catheterization','Maladies de l''appareil circulatoire','I97.640'),
('Postprocedural seroma of a circulatory system organ or structure following cardiac bypass','Postprocedural seroma of a circulatory system organ or structure following cardiac bypass','Maladies de l''appareil circulatoire','I97.641'),
('Postprocedural seroma of a circulatory system organ or structure following autre circulatory system procedure','Postprocedural seroma of a circulatory system organ or structure following other circulatory system procedure','Maladies de l''appareil circulatoire','I97.648'),
('Intraoperative cardiac arrest during cardiac surgery','Intraoperative cardiac arrest during cardiac surgery','Maladies de l''appareil circulatoire','I97.710'),
('Intraoperative cardiac arrest during autre surgery','Intraoperative cardiac arrest during other surgery','Maladies de l''appareil circulatoire','I97.711'),
('autre intraoperative cardiac functional disturbances during cardiac surgery','Other intraoperative cardiac functional disturbances during cardiac surgery','Maladies de l''appareil circulatoire','I97.790'),
('autre intraoperative cardiac functional disturbances during autre surgery','Other intraoperative cardiac functional disturbances during other surgery','Maladies de l''appareil circulatoire','I97.791'),
('Intraoperative cerebrovascular infarction during cardiac surgery','Intraoperative cerebrovascular infarction during cardiac surgery','Maladies de l''appareil circulatoire','I97.810'),
('Intraoperative cerebrovascular infarction during autre surgery','Intraoperative cerebrovascular infarction during other surgery','Maladies de l''appareil circulatoire','I97.811'),
('Postprocedural cerebrovascular infarction following cardiac surgery','Postprocedural cerebrovascular infarction following cardiac surgery','Maladies de l''appareil circulatoire','I97.820'),
('Postprocedural cerebrovascular infarction following autre surgery','Postprocedural cerebrovascular infarction following other surgery','Maladies de l''appareil circulatoire','I97.821'),
('autre intraoperative complications of the circulatory system, not elsewhere classified','Other intraoperative complications of the circulatory system, not elsewhere classified','Maladies de l''appareil circulatoire','I97.88'),
('autre postprocedural complications and disorders of the circulatory system, not elsewhere classified','Other postprocedural complications and disorders of the circulatory system, not elsewhere classified','Maladies de l''appareil circulatoire','I97.89'),
('autre trouble of circulatory system','Other disorder of circulatory system','Maladies de l''appareil circulatoire','I99.8'),
('non spécifié trouble of circulatory system','Unspecified disorder of circulatory system','Maladies de l''appareil circulatoire','I99.9'),
('aigu nasopharyngitis [common cold]','Acute nasopharyngitis [common cold]','Maladies de l''appareil respiratoire','J00'),
('aigu maxillary sinusitis, non spécifié','Acute maxillary sinusitis, unspecified','Maladies de l''appareil respiratoire','J01.00')
ON CONFLICT (nom_fr) DO NOTHING;
