-- icd10v2_batch_149.sql (80 rows)
INSERT INTO pathologies (nom_fr, nom_en, categorie, icd10_code)
VALUES
('Furuncle non spécifié hand','Furuncle unspecified hand','Maladies de la peau et du tissu cellulaire sous-cutané','L02.529'),
('Carbuncle of right hand','Carbuncle of right hand','Maladies de la peau et du tissu cellulaire sous-cutané','L02.531'),
('Carbuncle of left hand','Carbuncle of left hand','Maladies de la peau et du tissu cellulaire sous-cutané','L02.532'),
('Carbuncle of non spécifié hand','Carbuncle of unspecified hand','Maladies de la peau et du tissu cellulaire sous-cutané','L02.539'),
('Cutaneous abscess of right foot','Cutaneous abscess of right foot','Maladies de la peau et du tissu cellulaire sous-cutané','L02.611'),
('Cutaneous abscess of left foot','Cutaneous abscess of left foot','Maladies de la peau et du tissu cellulaire sous-cutané','L02.612'),
('Cutaneous abscess of non spécifié foot','Cutaneous abscess of unspecified foot','Maladies de la peau et du tissu cellulaire sous-cutané','L02.619'),
('Furuncle of right foot','Furuncle of right foot','Maladies de la peau et du tissu cellulaire sous-cutané','L02.621'),
('Furuncle of left foot','Furuncle of left foot','Maladies de la peau et du tissu cellulaire sous-cutané','L02.622'),
('Furuncle of non spécifié foot','Furuncle of unspecified foot','Maladies de la peau et du tissu cellulaire sous-cutané','L02.629'),
('Carbuncle of right foot','Carbuncle of right foot','Maladies de la peau et du tissu cellulaire sous-cutané','L02.631'),
('Carbuncle of left foot','Carbuncle of left foot','Maladies de la peau et du tissu cellulaire sous-cutané','L02.632'),
('Carbuncle of non spécifié foot','Carbuncle of unspecified foot','Maladies de la peau et du tissu cellulaire sous-cutané','L02.639'),
('Cutaneous abscess of head [any part, except face]','Cutaneous abscess of head [any part, except face]','Maladies de la peau et du tissu cellulaire sous-cutané','L02.811'),
('Cutaneous abscess of autre sites','Cutaneous abscess of other sites','Maladies de la peau et du tissu cellulaire sous-cutané','L02.818'),
('Furuncle of head [any part, except face]','Furuncle of head [any part, except face]','Maladies de la peau et du tissu cellulaire sous-cutané','L02.821'),
('Furuncle of autre sites','Furuncle of other sites','Maladies de la peau et du tissu cellulaire sous-cutané','L02.828'),
('Carbuncle of head [any part, except face]','Carbuncle of head [any part, except face]','Maladies de la peau et du tissu cellulaire sous-cutané','L02.831'),
('Carbuncle of autre sites','Carbuncle of other sites','Maladies de la peau et du tissu cellulaire sous-cutané','L02.838'),
('Cutaneous abscess, non spécifié','Cutaneous abscess, unspecified','Maladies de la peau et du tissu cellulaire sous-cutané','L02.91'),
('Furuncle, non spécifié','Furuncle, unspecified','Maladies de la peau et du tissu cellulaire sous-cutané','L02.92'),
('Carbuncle, non spécifié','Carbuncle, unspecified','Maladies de la peau et du tissu cellulaire sous-cutané','L02.93'),
('Cellulitis of right finger','Cellulitis of right finger','Maladies de la peau et du tissu cellulaire sous-cutané','L03.011'),
('Cellulitis of left finger','Cellulitis of left finger','Maladies de la peau et du tissu cellulaire sous-cutané','L03.012'),
('Cellulitis of non spécifié finger','Cellulitis of unspecified finger','Maladies de la peau et du tissu cellulaire sous-cutané','L03.019'),
('aigu lymphangitis of right finger','Acute lymphangitis of right finger','Maladies de la peau et du tissu cellulaire sous-cutané','L03.021'),
('aigu lymphangitis of left finger','Acute lymphangitis of left finger','Maladies de la peau et du tissu cellulaire sous-cutané','L03.022'),
('aigu lymphangitis of non spécifié finger','Acute lymphangitis of unspecified finger','Maladies de la peau et du tissu cellulaire sous-cutané','L03.029'),
('Cellulitis of right toe','Cellulitis of right toe','Maladies de la peau et du tissu cellulaire sous-cutané','L03.031'),
('Cellulitis of left toe','Cellulitis of left toe','Maladies de la peau et du tissu cellulaire sous-cutané','L03.032'),
('Cellulitis of non spécifié toe','Cellulitis of unspecified toe','Maladies de la peau et du tissu cellulaire sous-cutané','L03.039'),
('aigu lymphangitis of right toe','Acute lymphangitis of right toe','Maladies de la peau et du tissu cellulaire sous-cutané','L03.041'),
('aigu lymphangitis of left toe','Acute lymphangitis of left toe','Maladies de la peau et du tissu cellulaire sous-cutané','L03.042'),
('aigu lymphangitis of non spécifié toe','Acute lymphangitis of unspecified toe','Maladies de la peau et du tissu cellulaire sous-cutané','L03.049'),
('Cellulitis of right axilla','Cellulitis of right axilla','Maladies de la peau et du tissu cellulaire sous-cutané','L03.111'),
('Cellulitis of left axilla','Cellulitis of left axilla','Maladies de la peau et du tissu cellulaire sous-cutané','L03.112'),
('Cellulitis of right upper limb','Cellulitis of right upper limb','Maladies de la peau et du tissu cellulaire sous-cutané','L03.113'),
('Cellulitis of left upper limb','Cellulitis of left upper limb','Maladies de la peau et du tissu cellulaire sous-cutané','L03.114'),
('Cellulitis of right lower limb','Cellulitis of right lower limb','Maladies de la peau et du tissu cellulaire sous-cutané','L03.115'),
('Cellulitis of left lower limb','Cellulitis of left lower limb','Maladies de la peau et du tissu cellulaire sous-cutané','L03.116'),
('Cellulitis of non spécifié part of limb','Cellulitis of unspecified part of limb','Maladies de la peau et du tissu cellulaire sous-cutané','L03.119'),
('aigu lymphangitis of right axilla','Acute lymphangitis of right axilla','Maladies de la peau et du tissu cellulaire sous-cutané','L03.121'),
('aigu lymphangitis of left axilla','Acute lymphangitis of left axilla','Maladies de la peau et du tissu cellulaire sous-cutané','L03.122'),
('aigu lymphangitis of right upper limb','Acute lymphangitis of right upper limb','Maladies de la peau et du tissu cellulaire sous-cutané','L03.123'),
('aigu lymphangitis of left upper limb','Acute lymphangitis of left upper limb','Maladies de la peau et du tissu cellulaire sous-cutané','L03.124'),
('aigu lymphangitis of right lower limb','Acute lymphangitis of right lower limb','Maladies de la peau et du tissu cellulaire sous-cutané','L03.125'),
('aigu lymphangitis of left lower limb','Acute lymphangitis of left lower limb','Maladies de la peau et du tissu cellulaire sous-cutané','L03.126'),
('aigu lymphangitis of non spécifié part of limb','Acute lymphangitis of unspecified part of limb','Maladies de la peau et du tissu cellulaire sous-cutané','L03.129'),
('Cellulitis of face','Cellulitis of face','Maladies de la peau et du tissu cellulaire sous-cutané','L03.211'),
('aigu lymphangitis of face','Acute lymphangitis of face','Maladies de la peau et du tissu cellulaire sous-cutané','L03.212'),
('Periorbital cellulitis','Periorbital cellulitis','Maladies de la peau et du tissu cellulaire sous-cutané','L03.213'),
('Cellulitis of neck','Cellulitis of neck','Maladies de la peau et du tissu cellulaire sous-cutané','L03.221'),
('aigu lymphangitis of neck','Acute lymphangitis of neck','Maladies de la peau et du tissu cellulaire sous-cutané','L03.222'),
('Cellulitis of abdominal wall','Cellulitis of abdominal wall','Maladies de la peau et du tissu cellulaire sous-cutané','L03.311'),
('Cellulitis of back [any part except buttock]','Cellulitis of back [any part except buttock]','Maladies de la peau et du tissu cellulaire sous-cutané','L03.312'),
('Cellulitis of chest wall','Cellulitis of chest wall','Maladies de la peau et du tissu cellulaire sous-cutané','L03.313'),
('Cellulitis of groin','Cellulitis of groin','Maladies de la peau et du tissu cellulaire sous-cutané','L03.314'),
('Cellulitis of perineum','Cellulitis of perineum','Maladies de la peau et du tissu cellulaire sous-cutané','L03.315'),
('Cellulitis of umbilicus','Cellulitis of umbilicus','Maladies de la peau et du tissu cellulaire sous-cutané','L03.316'),
('Cellulitis of buttock','Cellulitis of buttock','Maladies de la peau et du tissu cellulaire sous-cutané','L03.317'),
('Cellulitis of trunk, non spécifié','Cellulitis of trunk, unspecified','Maladies de la peau et du tissu cellulaire sous-cutané','L03.319'),
('Cellulitis of flank','Cellulitis of flank','Maladies de la peau et du tissu cellulaire sous-cutané','L03.31A'),
('aigu lymphangitis of abdominal wall','Acute lymphangitis of abdominal wall','Maladies de la peau et du tissu cellulaire sous-cutané','L03.321'),
('aigu lymphangitis of back [any part except buttock]','Acute lymphangitis of back [any part except buttock]','Maladies de la peau et du tissu cellulaire sous-cutané','L03.322'),
('aigu lymphangitis of chest wall','Acute lymphangitis of chest wall','Maladies de la peau et du tissu cellulaire sous-cutané','L03.323'),
('aigu lymphangitis of groin','Acute lymphangitis of groin','Maladies de la peau et du tissu cellulaire sous-cutané','L03.324'),
('aigu lymphangitis of perineum','Acute lymphangitis of perineum','Maladies de la peau et du tissu cellulaire sous-cutané','L03.325'),
('aigu lymphangitis of umbilicus','Acute lymphangitis of umbilicus','Maladies de la peau et du tissu cellulaire sous-cutané','L03.326'),
('aigu lymphangitis of buttock','Acute lymphangitis of buttock','Maladies de la peau et du tissu cellulaire sous-cutané','L03.327'),
('aigu lymphangitis of trunk, non spécifié','Acute lymphangitis of trunk, unspecified','Maladies de la peau et du tissu cellulaire sous-cutané','L03.329'),
('aigu lymphangitis of flank','Acute lymphangitis of flank','Maladies de la peau et du tissu cellulaire sous-cutané','L03.32A'),
('Cellulitis of head [any part, except face]','Cellulitis of head [any part, except face]','Maladies de la peau et du tissu cellulaire sous-cutané','L03.811'),
('Cellulitis of autre sites','Cellulitis of other sites','Maladies de la peau et du tissu cellulaire sous-cutané','L03.818'),
('aigu lymphangitis of head [any part, except face]','Acute lymphangitis of head [any part, except face]','Maladies de la peau et du tissu cellulaire sous-cutané','L03.891'),
('aigu lymphangitis of autre sites','Acute lymphangitis of other sites','Maladies de la peau et du tissu cellulaire sous-cutané','L03.898'),
('Cellulitis, non spécifié','Cellulitis, unspecified','Maladies de la peau et du tissu cellulaire sous-cutané','L03.90'),
('aigu lymphangitis, non spécifié','Acute lymphangitis, unspecified','Maladies de la peau et du tissu cellulaire sous-cutané','L03.91'),
('aigu lymphadenitis of face, head and neck','Acute lymphadenitis of face, head and neck','Maladies de la peau et du tissu cellulaire sous-cutané','L04.0'),
('aigu lymphadenitis of trunk','Acute lymphadenitis of trunk','Maladies de la peau et du tissu cellulaire sous-cutané','L04.1'),
('aigu lymphadenitis of upper limb','Acute lymphadenitis of upper limb','Maladies de la peau et du tissu cellulaire sous-cutané','L04.2')
ON CONFLICT (nom_fr) DO NOTHING;
