-- icd10v2_batch_224.sql (80 rows)
INSERT INTO pathologies (nom_fr, nom_en, categorie, icd10_code)
VALUES
('Pre-existing hypertension with pre-eclampsia, complicating childbirth','Pre-existing hypertension with pre-eclampsia, complicating childbirth','Grossesse, accouchement et puerpéralité','O11.4'),
('Pre-existing hypertension with pre-eclampsia, complicating the puerperium','Pre-existing hypertension with pre-eclampsia, complicating the puerperium','Grossesse, accouchement et puerpéralité','O11.5'),
('Pre-existing hypertension with pre-eclampsia, non spécifié trimester','Pre-existing hypertension with pre-eclampsia, unspecified trimester','Grossesse, accouchement et puerpéralité','O11.9'),
('Gestational edema, non spécifié trimester','Gestational edema, unspecified trimester','Grossesse, accouchement et puerpéralité','O12.00'),
('Gestational edema, first trimester','Gestational edema, first trimester','Grossesse, accouchement et puerpéralité','O12.01'),
('Gestational edema, second trimester','Gestational edema, second trimester','Grossesse, accouchement et puerpéralité','O12.02'),
('Gestational edema, third trimester','Gestational edema, third trimester','Grossesse, accouchement et puerpéralité','O12.03'),
('Gestational edema, complicating childbirth','Gestational edema, complicating childbirth','Grossesse, accouchement et puerpéralité','O12.04'),
('Gestational edema, complicating the puerperium','Gestational edema, complicating the puerperium','Grossesse, accouchement et puerpéralité','O12.05'),
('Gestational proteinuria, non spécifié trimester','Gestational proteinuria, unspecified trimester','Grossesse, accouchement et puerpéralité','O12.10'),
('Gestational proteinuria, first trimester','Gestational proteinuria, first trimester','Grossesse, accouchement et puerpéralité','O12.11'),
('Gestational proteinuria, second trimester','Gestational proteinuria, second trimester','Grossesse, accouchement et puerpéralité','O12.12'),
('Gestational proteinuria, third trimester','Gestational proteinuria, third trimester','Grossesse, accouchement et puerpéralité','O12.13'),
('Gestational proteinuria, complicating childbirth','Gestational proteinuria, complicating childbirth','Grossesse, accouchement et puerpéralité','O12.14'),
('Gestational proteinuria, complicating the puerperium','Gestational proteinuria, complicating the puerperium','Grossesse, accouchement et puerpéralité','O12.15'),
('Gestational edema with proteinuria, non spécifié trimester','Gestational edema with proteinuria, unspecified trimester','Grossesse, accouchement et puerpéralité','O12.20'),
('Gestational edema with proteinuria, first trimester','Gestational edema with proteinuria, first trimester','Grossesse, accouchement et puerpéralité','O12.21'),
('Gestational edema with proteinuria, second trimester','Gestational edema with proteinuria, second trimester','Grossesse, accouchement et puerpéralité','O12.22'),
('Gestational edema with proteinuria, third trimester','Gestational edema with proteinuria, third trimester','Grossesse, accouchement et puerpéralité','O12.23'),
('Gestational edema with proteinuria, complicating childbirth','Gestational edema with proteinuria, complicating childbirth','Grossesse, accouchement et puerpéralité','O12.24'),
('Gestational edema with proteinuria, complicating the puerperium','Gestational edema with proteinuria, complicating the puerperium','Grossesse, accouchement et puerpéralité','O12.25'),
('Gestational [pregnancy-induced] hypertension without significant proteinuria, first trimester','Gestational [pregnancy-induced] hypertension without significant proteinuria, first trimester','Grossesse, accouchement et puerpéralité','O13.1'),
('Gestational [pregnancy-induced] hypertension without significant proteinuria, second trimester','Gestational [pregnancy-induced] hypertension without significant proteinuria, second trimester','Grossesse, accouchement et puerpéralité','O13.2'),
('Gestational [pregnancy-induced] hypertension without significant proteinuria, third trimester','Gestational [pregnancy-induced] hypertension without significant proteinuria, third trimester','Grossesse, accouchement et puerpéralité','O13.3'),
('Gestational [pregnancy-induced] hypertension without significant proteinuria, complicating childbirth','Gestational [pregnancy-induced] hypertension without significant proteinuria, complicating childbirth','Grossesse, accouchement et puerpéralité','O13.4'),
('Gestational [pregnancy-induced] hypertension without significant proteinuria, complicating the puerperium','Gestational [pregnancy-induced] hypertension without significant proteinuria, complicating the puerperium','Grossesse, accouchement et puerpéralité','O13.5'),
('Gestational [pregnancy-induced] hypertension without significant proteinuria, non spécifié trimester','Gestational [pregnancy-induced] hypertension without significant proteinuria, unspecified trimester','Grossesse, accouchement et puerpéralité','O13.9'),
('Mild to moderate pre-eclampsia, non spécifié trimester','Mild to moderate pre-eclampsia, unspecified trimester','Grossesse, accouchement et puerpéralité','O14.00'),
('Mild to moderate pre-eclampsia, second trimester','Mild to moderate pre-eclampsia, second trimester','Grossesse, accouchement et puerpéralité','O14.02'),
('Mild to moderate pre-eclampsia, third trimester','Mild to moderate pre-eclampsia, third trimester','Grossesse, accouchement et puerpéralité','O14.03'),
('Mild to moderate pre-eclampsia, complicating childbirth','Mild to moderate pre-eclampsia, complicating childbirth','Grossesse, accouchement et puerpéralité','O14.04'),
('Mild to moderate pre-eclampsia, complicating the puerperium','Mild to moderate pre-eclampsia, complicating the puerperium','Grossesse, accouchement et puerpéralité','O14.05'),
('Severe pre-eclampsia, non spécifié trimester','Severe pre-eclampsia, unspecified trimester','Grossesse, accouchement et puerpéralité','O14.10'),
('Severe pre-eclampsia, second trimester','Severe pre-eclampsia, second trimester','Grossesse, accouchement et puerpéralité','O14.12'),
('Severe pre-eclampsia, third trimester','Severe pre-eclampsia, third trimester','Grossesse, accouchement et puerpéralité','O14.13'),
('Severe pre-eclampsia complicating childbirth','Severe pre-eclampsia complicating childbirth','Grossesse, accouchement et puerpéralité','O14.14'),
('Severe pre-eclampsia, complicating the puerperium','Severe pre-eclampsia, complicating the puerperium','Grossesse, accouchement et puerpéralité','O14.15'),
('HELLP syndrome (HELLP), non spécifié trimester','HELLP syndrome (HELLP), unspecified trimester','Grossesse, accouchement et puerpéralité','O14.20'),
('HELLP syndrome (HELLP), second trimester','HELLP syndrome (HELLP), second trimester','Grossesse, accouchement et puerpéralité','O14.22'),
('HELLP syndrome (HELLP), third trimester','HELLP syndrome (HELLP), third trimester','Grossesse, accouchement et puerpéralité','O14.23'),
('HELLP syndrome, complicating childbirth','HELLP syndrome, complicating childbirth','Grossesse, accouchement et puerpéralité','O14.24'),
('HELLP syndrome, complicating the puerperium','HELLP syndrome, complicating the puerperium','Grossesse, accouchement et puerpéralité','O14.25'),
('non spécifié pre-eclampsia, non spécifié trimester','Unspecified pre-eclampsia, unspecified trimester','Grossesse, accouchement et puerpéralité','O14.90'),
('non spécifié pre-eclampsia, second trimester','Unspecified pre-eclampsia, second trimester','Grossesse, accouchement et puerpéralité','O14.92'),
('non spécifié pre-eclampsia, third trimester','Unspecified pre-eclampsia, third trimester','Grossesse, accouchement et puerpéralité','O14.93'),
('non spécifié pre-eclampsia, complicating childbirth','Unspecified pre-eclampsia, complicating childbirth','Grossesse, accouchement et puerpéralité','O14.94'),
('non spécifié pre-eclampsia, complicating the puerperium','Unspecified pre-eclampsia, complicating the puerperium','Grossesse, accouchement et puerpéralité','O14.95'),
('Eclampsia complicating pregnancy, non spécifié trimester','Eclampsia complicating pregnancy, unspecified trimester','Grossesse, accouchement et puerpéralité','O15.00'),
('Eclampsia complicating pregnancy, second trimester','Eclampsia complicating pregnancy, second trimester','Grossesse, accouchement et puerpéralité','O15.02'),
('Eclampsia complicating pregnancy, third trimester','Eclampsia complicating pregnancy, third trimester','Grossesse, accouchement et puerpéralité','O15.03'),
('Eclampsia complicating labor','Eclampsia complicating labor','Grossesse, accouchement et puerpéralité','O15.1'),
('Eclampsia complicating the puerperium','Eclampsia complicating the puerperium','Grossesse, accouchement et puerpéralité','O15.2'),
('Eclampsia, non spécifié as to time period','Eclampsia, unspecified as to time period','Grossesse, accouchement et puerpéralité','O15.9'),
('non spécifié maternal hypertension, first trimester','Unspecified maternal hypertension, first trimester','Grossesse, accouchement et puerpéralité','O16.1'),
('non spécifié maternal hypertension, second trimester','Unspecified maternal hypertension, second trimester','Grossesse, accouchement et puerpéralité','O16.2'),
('non spécifié maternal hypertension, third trimester','Unspecified maternal hypertension, third trimester','Grossesse, accouchement et puerpéralité','O16.3'),
('non spécifié maternal hypertension, complicating childbirth','Unspecified maternal hypertension, complicating childbirth','Grossesse, accouchement et puerpéralité','O16.4'),
('non spécifié maternal hypertension, complicating the puerperium','Unspecified maternal hypertension, complicating the puerperium','Grossesse, accouchement et puerpéralité','O16.5'),
('non spécifié maternal hypertension, non spécifié trimester','Unspecified maternal hypertension, unspecified trimester','Grossesse, accouchement et puerpéralité','O16.9'),
('Threatened abortion','Threatened abortion','Grossesse, accouchement et puerpéralité','O20.0'),
('autre hémorragie in early pregnancy','Other hemorrhage in early pregnancy','Grossesse, accouchement et puerpéralité','O20.8'),
('hémorragie in early pregnancy, non spécifié','Hemorrhage in early pregnancy, unspecified','Grossesse, accouchement et puerpéralité','O20.9'),
('Mild hyperemesis gravidarum','Mild hyperemesis gravidarum','Grossesse, accouchement et puerpéralité','O21.0'),
('Hyperemesis gravidarum with metabolic disturbance','Hyperemesis gravidarum with metabolic disturbance','Grossesse, accouchement et puerpéralité','O21.1'),
('Late vomiting of pregnancy','Late vomiting of pregnancy','Grossesse, accouchement et puerpéralité','O21.2'),
('autre vomiting complicating pregnancy','Other vomiting complicating pregnancy','Grossesse, accouchement et puerpéralité','O21.8'),
('Vomiting of pregnancy, non spécifié','Vomiting of pregnancy, unspecified','Grossesse, accouchement et puerpéralité','O21.9'),
('Varicose veins of lower extremity in pregnancy, non spécifié trimester','Varicose veins of lower extremity in pregnancy, unspecified trimester','Grossesse, accouchement et puerpéralité','O22.00'),
('Varicose veins of lower extremity in pregnancy, first trimester','Varicose veins of lower extremity in pregnancy, first trimester','Grossesse, accouchement et puerpéralité','O22.01'),
('Varicose veins of lower extremity in pregnancy, second trimester','Varicose veins of lower extremity in pregnancy, second trimester','Grossesse, accouchement et puerpéralité','O22.02'),
('Varicose veins of lower extremity in pregnancy, third trimester','Varicose veins of lower extremity in pregnancy, third trimester','Grossesse, accouchement et puerpéralité','O22.03'),
('Genital varices in pregnancy, non spécifié trimester','Genital varices in pregnancy, unspecified trimester','Grossesse, accouchement et puerpéralité','O22.10'),
('Genital varices in pregnancy, first trimester','Genital varices in pregnancy, first trimester','Grossesse, accouchement et puerpéralité','O22.11'),
('Genital varices in pregnancy, second trimester','Genital varices in pregnancy, second trimester','Grossesse, accouchement et puerpéralité','O22.12'),
('Genital varices in pregnancy, third trimester','Genital varices in pregnancy, third trimester','Grossesse, accouchement et puerpéralité','O22.13'),
('Superficial thrombophlebitis in pregnancy, non spécifié trimester','Superficial thrombophlebitis in pregnancy, unspecified trimester','Grossesse, accouchement et puerpéralité','O22.20'),
('Superficial thrombophlebitis in pregnancy, first trimester','Superficial thrombophlebitis in pregnancy, first trimester','Grossesse, accouchement et puerpéralité','O22.21'),
('Superficial thrombophlebitis in pregnancy, second trimester','Superficial thrombophlebitis in pregnancy, second trimester','Grossesse, accouchement et puerpéralité','O22.22'),
('Superficial thrombophlebitis in pregnancy, third trimester','Superficial thrombophlebitis in pregnancy, third trimester','Grossesse, accouchement et puerpéralité','O22.23'),
('Deep phlebothrombosis in pregnancy, non spécifié trimester','Deep phlebothrombosis in pregnancy, unspecified trimester','Grossesse, accouchement et puerpéralité','O22.30')
ON CONFLICT (nom_fr) DO NOTHING;
