-- icd10v2_batch_038.sql (80 rows)
INSERT INTO pathologies (nom_fr, nom_en, categorie, icd10_code)
VALUES
('néoplasme of uncertain behavior of autre respiratory organs','Neoplasm of uncertain behavior of other respiratory organs','Tumeurs bénignes et in situ','D38.5'),
('néoplasme of uncertain behavior of respiratory organ, non spécifié','Neoplasm of uncertain behavior of respiratory organ, unspecified','Tumeurs bénignes et in situ','D38.6'),
('néoplasme of uncertain behavior of uterus','Neoplasm of uncertain behavior of uterus','Tumeurs bénignes et in situ','D39.0'),
('néoplasme of uncertain behavior of non spécifié ovary','Neoplasm of uncertain behavior of unspecified ovary','Tumeurs bénignes et in situ','D39.10'),
('néoplasme of uncertain behavior of right ovary','Neoplasm of uncertain behavior of right ovary','Tumeurs bénignes et in situ','D39.11'),
('néoplasme of uncertain behavior of left ovary','Neoplasm of uncertain behavior of left ovary','Tumeurs bénignes et in situ','D39.12'),
('néoplasme of uncertain behavior of placenta','Neoplasm of uncertain behavior of placenta','Tumeurs bénignes et in situ','D39.2'),
('néoplasme of uncertain behavior of autre specified female genital organs','Neoplasm of uncertain behavior of other specified female genital organs','Tumeurs bénignes et in situ','D39.8'),
('néoplasme of uncertain behavior of female genital organ, non spécifié','Neoplasm of uncertain behavior of female genital organ, unspecified','Tumeurs bénignes et in situ','D39.9'),
('Maternal care for anti-D [Rh] antibodies, first trimester, fetus 4','Maternal care for anti-D [Rh] antibodies, first trimester, fetus 4','Grossesse, accouchement et puerpéralité','O36.0114'),
('Maternal care for anti-D [Rh] antibodies, second trimester, fetus 4','Maternal care for anti-D [Rh] antibodies, second trimester, fetus 4','Grossesse, accouchement et puerpéralité','O36.0124'),
('Maternal care for anti-D [Rh] antibodies, third trimester, fetus 4','Maternal care for anti-D [Rh] antibodies, third trimester, fetus 4','Grossesse, accouchement et puerpéralité','O36.0134'),
('Maternal care for anti-D [Rh] antibodies, non spécifié trimester, fetus 4','Maternal care for anti-D [Rh] antibodies, unspecified trimester, fetus 4','Grossesse, accouchement et puerpéralité','O36.0194'),
('néoplasme of uncertain behavior of prostate','Neoplasm of uncertain behavior of prostate','Tumeurs bénignes et in situ','D40.0'),
('néoplasme of uncertain behavior of non spécifié testis','Neoplasm of uncertain behavior of unspecified testis','Tumeurs bénignes et in situ','D40.10'),
('néoplasme of uncertain behavior of right testis','Neoplasm of uncertain behavior of right testis','Tumeurs bénignes et in situ','D40.11'),
('néoplasme of uncertain behavior of left testis','Neoplasm of uncertain behavior of left testis','Tumeurs bénignes et in situ','D40.12'),
('néoplasme of uncertain behavior of autre specified male genital organs','Neoplasm of uncertain behavior of other specified male genital organs','Tumeurs bénignes et in situ','D40.8'),
('néoplasme of uncertain behavior of male genital organ, non spécifié','Neoplasm of uncertain behavior of male genital organ, unspecified','Tumeurs bénignes et in situ','D40.9'),
('néoplasme of uncertain behavior of non spécifié kidney','Neoplasm of uncertain behavior of unspecified kidney','Tumeurs bénignes et in situ','D41.00'),
('néoplasme of uncertain behavior of right kidney','Neoplasm of uncertain behavior of right kidney','Tumeurs bénignes et in situ','D41.01'),
('néoplasme of uncertain behavior of left kidney','Neoplasm of uncertain behavior of left kidney','Tumeurs bénignes et in situ','D41.02'),
('néoplasme of uncertain behavior of non spécifié renal pelvis','Neoplasm of uncertain behavior of unspecified renal pelvis','Tumeurs bénignes et in situ','D41.10'),
('néoplasme of uncertain behavior of right renal pelvis','Neoplasm of uncertain behavior of right renal pelvis','Tumeurs bénignes et in situ','D41.11'),
('néoplasme of uncertain behavior of left renal pelvis','Neoplasm of uncertain behavior of left renal pelvis','Tumeurs bénignes et in situ','D41.12'),
('néoplasme of uncertain behavior of non spécifié ureter','Neoplasm of uncertain behavior of unspecified ureter','Tumeurs bénignes et in situ','D41.20'),
('néoplasme of uncertain behavior of right ureter','Neoplasm of uncertain behavior of right ureter','Tumeurs bénignes et in situ','D41.21'),
('néoplasme of uncertain behavior of left ureter','Neoplasm of uncertain behavior of left ureter','Tumeurs bénignes et in situ','D41.22'),
('néoplasme of uncertain behavior of urethra','Neoplasm of uncertain behavior of urethra','Tumeurs bénignes et in situ','D41.3'),
('néoplasme of uncertain behavior of bladder','Neoplasm of uncertain behavior of bladder','Tumeurs bénignes et in situ','D41.4'),
('néoplasme of uncertain behavior of autre specified urinary organs','Neoplasm of uncertain behavior of other specified urinary organs','Tumeurs bénignes et in situ','D41.8'),
('néoplasme of uncertain behavior of non spécifié urinary organ','Neoplasm of uncertain behavior of unspecified urinary organ','Tumeurs bénignes et in situ','D41.9'),
('néoplasme of uncertain behavior of cerebral meninges','Neoplasm of uncertain behavior of cerebral meninges','Tumeurs bénignes et in situ','D42.0'),
('néoplasme of uncertain behavior of spinal meninges','Neoplasm of uncertain behavior of spinal meninges','Tumeurs bénignes et in situ','D42.1'),
('néoplasme of uncertain behavior of meninges, non spécifié','Neoplasm of uncertain behavior of meninges, unspecified','Tumeurs bénignes et in situ','D42.9'),
('néoplasme of uncertain behavior of brain, supratentorial','Neoplasm of uncertain behavior of brain, supratentorial','Tumeurs bénignes et in situ','D43.0'),
('néoplasme of uncertain behavior of brain, infratentorial','Neoplasm of uncertain behavior of brain, infratentorial','Tumeurs bénignes et in situ','D43.1'),
('néoplasme of uncertain behavior of brain, non spécifié','Neoplasm of uncertain behavior of brain, unspecified','Tumeurs bénignes et in situ','D43.2'),
('néoplasme of uncertain behavior of cranial nerves','Neoplasm of uncertain behavior of cranial nerves','Tumeurs bénignes et in situ','D43.3'),
('néoplasme of uncertain behavior of spinal cord','Neoplasm of uncertain behavior of spinal cord','Tumeurs bénignes et in situ','D43.4'),
('néoplasme of uncertain behavior of autre specified parts of central nervous system','Neoplasm of uncertain behavior of other specified parts of central nervous system','Tumeurs bénignes et in situ','D43.8'),
('néoplasme of uncertain behavior of central nervous system, non spécifié','Neoplasm of uncertain behavior of central nervous system, unspecified','Tumeurs bénignes et in situ','D43.9'),
('néoplasme of uncertain behavior of thyroid gland','Neoplasm of uncertain behavior of thyroid gland','Tumeurs bénignes et in situ','D44.0'),
('néoplasme of uncertain behavior of non spécifié adrenal gland','Neoplasm of uncertain behavior of unspecified adrenal gland','Tumeurs bénignes et in situ','D44.10'),
('néoplasme of uncertain behavior of right adrenal gland','Neoplasm of uncertain behavior of right adrenal gland','Tumeurs bénignes et in situ','D44.11'),
('néoplasme of uncertain behavior of left adrenal gland','Neoplasm of uncertain behavior of left adrenal gland','Tumeurs bénignes et in situ','D44.12'),
('néoplasme of uncertain behavior of parathyroid gland','Neoplasm of uncertain behavior of parathyroid gland','Tumeurs bénignes et in situ','D44.2'),
('néoplasme of uncertain behavior of pituitary gland','Neoplasm of uncertain behavior of pituitary gland','Tumeurs bénignes et in situ','D44.3'),
('néoplasme of uncertain behavior of craniopharyngeal duct','Neoplasm of uncertain behavior of craniopharyngeal duct','Tumeurs bénignes et in situ','D44.4'),
('néoplasme of uncertain behavior of pineal gland','Neoplasm of uncertain behavior of pineal gland','Tumeurs bénignes et in situ','D44.5'),
('néoplasme of uncertain behavior of carotid body','Neoplasm of uncertain behavior of carotid body','Tumeurs bénignes et in situ','D44.6'),
('néoplasme of uncertain behavior of aortic body and autre paraganglia','Neoplasm of uncertain behavior of aortic body and other paraganglia','Tumeurs bénignes et in situ','D44.7'),
('néoplasme of uncertain behavior of non spécifié endocrine gland','Neoplasm of uncertain behavior of unspecified endocrine gland','Tumeurs bénignes et in situ','D44.9'),
('Polycythemia vera','Polycythemia vera','Tumeurs bénignes et in situ','D45'),
('Refractory anemia without ring sideroblasts, so stated','Refractory anemia without ring sideroblasts, so stated','Tumeurs bénignes et in situ','D46.0'),
('Refractory anemia with ring sideroblasts','Refractory anemia with ring sideroblasts','Tumeurs bénignes et in situ','D46.1'),
('Refractory anemia with excess of blasts, non spécifié','Refractory anemia with excess of blasts, unspecified','Tumeurs bénignes et in situ','D46.20'),
('Refractory anemia with excess of blasts 1','Refractory anemia with excess of blasts 1','Tumeurs bénignes et in situ','D46.21'),
('Refractory anemia with excess of blasts 2','Refractory anemia with excess of blasts 2','Tumeurs bénignes et in situ','D46.22'),
('Refractory cytopenia with multilineage dysplasia','Refractory cytopenia with multilineage dysplasia','Tumeurs bénignes et in situ','D46.A'),
('Refractory cytopenia with multilineage dysplasia and ring sideroblasts','Refractory cytopenia with multilineage dysplasia and ring sideroblasts','Tumeurs bénignes et in situ','D46.B'),
('Myelodysplastic syndrome with isolated del(5q) chromosomal abnormality','Myelodysplastic syndrome with isolated del(5q) chromosomal abnormality','Tumeurs bénignes et in situ','D46.C'),
('Refractory anemia, non spécifié','Refractory anemia, unspecified','Tumeurs bénignes et in situ','D46.4'),
('autre myelodysplastic syndromes','Other myelodysplastic syndromes','Tumeurs bénignes et in situ','D46.Z'),
('Myelodysplastic syndrome, non spécifié','Myelodysplastic syndrome, unspecified','Tumeurs bénignes et in situ','D46.9'),
('Cutaneous mastocytosis','Cutaneous mastocytosis','Tumeurs bénignes et in situ','D47.01'),
('Systemic mastocytosis','Systemic mastocytosis','Tumeurs bénignes et in situ','D47.02'),
('autre mast cell neoplasms of uncertain behavior','Other mast cell neoplasms of uncertain behavior','Tumeurs bénignes et in situ','D47.09'),
('chronique myeloproliferative maladie','Chronic myeloproliferative disease','Tumeurs bénignes et in situ','D47.1'),
('Monoclonal gammopathy','Monoclonal gammopathy','Tumeurs bénignes et in situ','D47.2'),
('Essential (hemorrhagic) thrombocythemia','Essential (hemorrhagic) thrombocythemia','Tumeurs bénignes et in situ','D47.3'),
('Osteomyelofibrosis','Osteomyelofibrosis','Tumeurs bénignes et in situ','D47.4'),
('Post-transplant lymphoproliferative trouble (PTLD)','Post-transplant lymphoproliferative disorder (PTLD)','Tumeurs bénignes et in situ','D47.Z1'),
('Castleman maladie','Castleman disease','Tumeurs bénignes et in situ','D47.Z2'),
('autre specified neoplasms of uncertain behavior of lymphoid, hematopoietic and related tissue','Other specified neoplasms of uncertain behavior of lymphoid, hematopoietic and related tissue','Tumeurs bénignes et in situ','D47.Z9'),
('néoplasme of uncertain behavior of lymphoid, hematopoietic and related tissue, non spécifié','Neoplasm of uncertain behavior of lymphoid, hematopoietic and related tissue, unspecified','Tumeurs bénignes et in situ','D47.9'),
('néoplasme of uncertain behavior of bone and articular cartilage','Neoplasm of uncertain behavior of bone and articular cartilage','Tumeurs bénignes et in situ','D48.0'),
('Desmoid tumeur of head and neck','Desmoid tumor of head and neck','Tumeurs bénignes et in situ','D48.110'),
('Desmoid tumeur of chest wall','Desmoid tumor of chest wall','Tumeurs bénignes et in situ','D48.111'),
('Desmoid tumeur, intrathoracic','Desmoid tumor, intrathoracic','Tumeurs bénignes et in situ','D48.112')
ON CONFLICT (nom_fr) DO NOTHING;
