-- icd10v2_batch_151.sql (80 rows)
INSERT INTO pathologies (nom_fr, nom_en, categorie, icd10_code)
VALUES
('autre atopic dermatitis','Other atopic dermatitis','Maladies de la peau et du tissu cellulaire sous-cutané','L20.89'),
('Atopic dermatitis, non spécifié','Atopic dermatitis, unspecified','Maladies de la peau et du tissu cellulaire sous-cutané','L20.9'),
('Seborrhea capitis','Seborrhea capitis','Maladies de la peau et du tissu cellulaire sous-cutané','L21.0'),
('Seborrheic infantile dermatitis','Seborrheic infantile dermatitis','Maladies de la peau et du tissu cellulaire sous-cutané','L21.1'),
('autre seborrheic dermatitis','Other seborrheic dermatitis','Maladies de la peau et du tissu cellulaire sous-cutané','L21.8'),
('Seborrheic dermatitis, non spécifié','Seborrheic dermatitis, unspecified','Maladies de la peau et du tissu cellulaire sous-cutané','L21.9'),
('Diaper dermatitis','Diaper dermatitis','Maladies de la peau et du tissu cellulaire sous-cutané','L22'),
('Allergic contact dermatitis due to metals','Allergic contact dermatitis due to metals','Maladies de la peau et du tissu cellulaire sous-cutané','L23.0'),
('Allergic contact dermatitis due to adhesives','Allergic contact dermatitis due to adhesives','Maladies de la peau et du tissu cellulaire sous-cutané','L23.1'),
('Allergic contact dermatitis due to cosmetics','Allergic contact dermatitis due to cosmetics','Maladies de la peau et du tissu cellulaire sous-cutané','L23.2'),
('Allergic contact dermatitis due to drugs in contact with skin','Allergic contact dermatitis due to drugs in contact with skin','Maladies de la peau et du tissu cellulaire sous-cutané','L23.3'),
('Allergic contact dermatitis due to dyes','Allergic contact dermatitis due to dyes','Maladies de la peau et du tissu cellulaire sous-cutané','L23.4'),
('Allergic contact dermatitis due to autre chemical products','Allergic contact dermatitis due to other chemical products','Maladies de la peau et du tissu cellulaire sous-cutané','L23.5'),
('Allergic contact dermatitis due to food in contact with the skin','Allergic contact dermatitis due to food in contact with the skin','Maladies de la peau et du tissu cellulaire sous-cutané','L23.6'),
('Allergic contact dermatitis due to plants, except food','Allergic contact dermatitis due to plants, except food','Maladies de la peau et du tissu cellulaire sous-cutané','L23.7'),
('Allergic contact dermatitis due to animal (cat) (dog) dander','Allergic contact dermatitis due to animal (cat) (dog) dander','Maladies de la peau et du tissu cellulaire sous-cutané','L23.81'),
('Allergic contact dermatitis due to autre agents','Allergic contact dermatitis due to other agents','Maladies de la peau et du tissu cellulaire sous-cutané','L23.89'),
('Allergic contact dermatitis, non spécifié cause','Allergic contact dermatitis, unspecified cause','Maladies de la peau et du tissu cellulaire sous-cutané','L23.9'),
('Irritant contact dermatitis due to detergents','Irritant contact dermatitis due to detergents','Maladies de la peau et du tissu cellulaire sous-cutané','L24.0'),
('Irritant contact dermatitis due to oils and greases','Irritant contact dermatitis due to oils and greases','Maladies de la peau et du tissu cellulaire sous-cutané','L24.1'),
('Irritant contact dermatitis due to solvents','Irritant contact dermatitis due to solvents','Maladies de la peau et du tissu cellulaire sous-cutané','L24.2'),
('Irritant contact dermatitis due to cosmetics','Irritant contact dermatitis due to cosmetics','Maladies de la peau et du tissu cellulaire sous-cutané','L24.3'),
('Irritant contact dermatitis due to drugs in contact with skin','Irritant contact dermatitis due to drugs in contact with skin','Maladies de la peau et du tissu cellulaire sous-cutané','L24.4'),
('Irritant contact dermatitis due to autre chemical products','Irritant contact dermatitis due to other chemical products','Maladies de la peau et du tissu cellulaire sous-cutané','L24.5'),
('Irritant contact dermatitis due to food in contact with skin','Irritant contact dermatitis due to food in contact with skin','Maladies de la peau et du tissu cellulaire sous-cutané','L24.6'),
('Irritant contact dermatitis due to plants, except food','Irritant contact dermatitis due to plants, except food','Maladies de la peau et du tissu cellulaire sous-cutané','L24.7'),
('Irritant contact dermatitis due to metals','Irritant contact dermatitis due to metals','Maladies de la peau et du tissu cellulaire sous-cutané','L24.81'),
('Irritant contact dermatitis due to autre agents','Irritant contact dermatitis due to other agents','Maladies de la peau et du tissu cellulaire sous-cutané','L24.89'),
('Irritant contact dermatitis, non spécifié cause','Irritant contact dermatitis, unspecified cause','Maladies de la peau et du tissu cellulaire sous-cutané','L24.9'),
('Irritant contact dermatitis due to friction or contact with body fluids, non spécifié','Irritant contact dermatitis due to friction or contact with body fluids, unspecified','Maladies de la peau et du tissu cellulaire sous-cutané','L24.A0'),
('Irritant contact dermatitis due to saliva','Irritant contact dermatitis due to saliva','Maladies de la peau et du tissu cellulaire sous-cutané','L24.A1'),
('Irritant contact dermatitis due to fecal, urinary or dual incontinence','Irritant contact dermatitis due to fecal, urinary or dual incontinence','Maladies de la peau et du tissu cellulaire sous-cutané','L24.A2'),
('Irritant contact dermatitis due friction or contact with autre specified body fluids','Irritant contact dermatitis due friction or contact with other specified body fluids','Maladies de la peau et du tissu cellulaire sous-cutané','L24.A9'),
('Irritant contact dermatitis related to non spécifié stoma or fistula','Irritant contact dermatitis related to unspecified stoma or fistula','Maladies de la peau et du tissu cellulaire sous-cutané','L24.B0'),
('Irritant contact dermatitis related to digestive stoma or fistula','Irritant contact dermatitis related to digestive stoma or fistula','Maladies de la peau et du tissu cellulaire sous-cutané','L24.B1'),
('Irritant contact dermatitis related to respiratory stoma or fistula','Irritant contact dermatitis related to respiratory stoma or fistula','Maladies de la peau et du tissu cellulaire sous-cutané','L24.B2'),
('Irritant contact dermatitis related to fecal or urinary stoma or fistula','Irritant contact dermatitis related to fecal or urinary stoma or fistula','Maladies de la peau et du tissu cellulaire sous-cutané','L24.B3'),
('non spécifié contact dermatitis due to cosmetics','Unspecified contact dermatitis due to cosmetics','Maladies de la peau et du tissu cellulaire sous-cutané','L25.0'),
('non spécifié contact dermatitis due to drugs in contact with skin','Unspecified contact dermatitis due to drugs in contact with skin','Maladies de la peau et du tissu cellulaire sous-cutané','L25.1'),
('non spécifié contact dermatitis due to dyes','Unspecified contact dermatitis due to dyes','Maladies de la peau et du tissu cellulaire sous-cutané','L25.2'),
('non spécifié contact dermatitis due to autre chemical products','Unspecified contact dermatitis due to other chemical products','Maladies de la peau et du tissu cellulaire sous-cutané','L25.3'),
('non spécifié contact dermatitis due to food in contact with skin','Unspecified contact dermatitis due to food in contact with skin','Maladies de la peau et du tissu cellulaire sous-cutané','L25.4'),
('non spécifié contact dermatitis due to plants, except food','Unspecified contact dermatitis due to plants, except food','Maladies de la peau et du tissu cellulaire sous-cutané','L25.5'),
('non spécifié contact dermatitis due to autre agents','Unspecified contact dermatitis due to other agents','Maladies de la peau et du tissu cellulaire sous-cutané','L25.8'),
('non spécifié contact dermatitis, non spécifié cause','Unspecified contact dermatitis, unspecified cause','Maladies de la peau et du tissu cellulaire sous-cutané','L25.9'),
('Exfoliative dermatitis','Exfoliative dermatitis','Maladies de la peau et du tissu cellulaire sous-cutané','L26'),
('Generalized skin eruption due to drugs and medicaments taken internally','Generalized skin eruption due to drugs and medicaments taken internally','Maladies de la peau et du tissu cellulaire sous-cutané','L27.0'),
('Localized skin eruption due to drugs and medicaments taken internally','Localized skin eruption due to drugs and medicaments taken internally','Maladies de la peau et du tissu cellulaire sous-cutané','L27.1'),
('Dermatite due to ingested food','Dermatitis due to ingested food','Maladies de la peau et du tissu cellulaire sous-cutané','L27.2'),
('Dermatite due to other substances taken internally','Dermatitis due to other substances taken internally','Maladies de la peau et du tissu cellulaire sous-cutané','L27.8'),
('Dermatite due to unspecified substance taken internally','Dermatitis due to unspecified substance taken internally','Maladies de la peau et du tissu cellulaire sous-cutané','L27.9'),
('Lichen simplex chronicus','Lichen simplex chronicus','Maladies de la peau et du tissu cellulaire sous-cutané','L28.0'),
('Prurigo nodularis','Prurigo nodularis','Maladies de la peau et du tissu cellulaire sous-cutané','L28.1'),
('autre prurigo','Other prurigo','Maladies de la peau et du tissu cellulaire sous-cutané','L28.2'),
('Pruritus ani','Pruritus ani','Maladies de la peau et du tissu cellulaire sous-cutané','L29.0'),
('Pruritus scroti','Pruritus scroti','Maladies de la peau et du tissu cellulaire sous-cutané','L29.1'),
('Pruritus vulvae','Pruritus vulvae','Maladies de la peau et du tissu cellulaire sous-cutané','L29.2'),
('Anogenital pruritus, non spécifié','Anogenital pruritus, unspecified','Maladies de la peau et du tissu cellulaire sous-cutané','L29.3'),
('Cholestatic pruritus','Cholestatic pruritus','Maladies de la peau et du tissu cellulaire sous-cutané','L29.81'),
('autre pruritus','Other pruritus','Maladies de la peau et du tissu cellulaire sous-cutané','L29.89'),
('Pruritus, non spécifié','Pruritus, unspecified','Maladies de la peau et du tissu cellulaire sous-cutané','L29.9'),
('Subluxation of L3/L4 lumbar vertebra, sequela','Subluxation of L3/L4 lumbar vertebra, sequela','Traumatismes, empoisonnements et autres causes externes','S33.130S'),
('Luxation de L3/L4 lumbar vertebra, sequela','Dislocation of L3/L4 lumbar vertebra, sequela','Traumatismes, empoisonnements et autres causes externes','S33.131S'),
('Subluxation of L3/L4 lumbar vertebra, initial encounter','Subluxation of L3/L4 lumbar vertebra, initial encounter','Traumatismes, empoisonnements et autres causes externes','S33.130A'),
('Subluxation of L3/L4 lumbar vertebra, subsequent encounter','Subluxation of L3/L4 lumbar vertebra, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S33.130D'),
('Luxation de L3/L4 lumbar vertebra, initial encounter','Dislocation of L3/L4 lumbar vertebra, initial encounter','Traumatismes, empoisonnements et autres causes externes','S33.131A'),
('Luxation de L3/L4 lumbar vertebra, subsequent encounter','Dislocation of L3/L4 lumbar vertebra, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S33.131D'),
('non spécifié injury to L3 level of lumbar spinal cord, sequela','Unspecified injury to L3 level of lumbar spinal cord, sequela','Traumatismes, empoisonnements et autres causes externes','S34.103S'),
('Complete lesion of L3 level of lumbar spinal cord, sequela','Complete lesion of L3 level of lumbar spinal cord, sequela','Traumatismes, empoisonnements et autres causes externes','S34.113S'),
('Incomplete lesion of L3 level of lumbar spinal cord, sequela','Incomplete lesion of L3 level of lumbar spinal cord, sequela','Traumatismes, empoisonnements et autres causes externes','S34.123S'),
('non spécifié injury to L3 level of lumbar spinal cord, initial encounter','Unspecified injury to L3 level of lumbar spinal cord, initial encounter','Traumatismes, empoisonnements et autres causes externes','S34.103A'),
('non spécifié injury to L3 level of lumbar spinal cord, subsequent encounter','Unspecified injury to L3 level of lumbar spinal cord, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S34.103D'),
('Complete lesion of L3 level of lumbar spinal cord, initial encounter','Complete lesion of L3 level of lumbar spinal cord, initial encounter','Traumatismes, empoisonnements et autres causes externes','S34.113A'),
('Complete lesion of L3 level of lumbar spinal cord, subsequent encounter','Complete lesion of L3 level of lumbar spinal cord, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S34.113D'),
('Incomplete lesion of L3 level of lumbar spinal cord, initial encounter','Incomplete lesion of L3 level of lumbar spinal cord, initial encounter','Traumatismes, empoisonnements et autres causes externes','S34.123A'),
('Incomplete lesion of L3 level of lumbar spinal cord, subsequent encounter','Incomplete lesion of L3 level of lumbar spinal cord, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S34.123D'),
('Nummular dermatitis','Nummular dermatitis','Maladies de la peau et du tissu cellulaire sous-cutané','L30.0'),
('Dyshidrosis [pompholyx]','Dyshidrosis [pompholyx]','Maladies de la peau et du tissu cellulaire sous-cutané','L30.1'),
('Cutaneous autosensitization','Cutaneous autosensitization','Maladies de la peau et du tissu cellulaire sous-cutané','L30.2'),
('Infective dermatitis','Infective dermatitis','Maladies de la peau et du tissu cellulaire sous-cutané','L30.3')
ON CONFLICT (nom_fr) DO NOTHING;
