-- icd10v2_batch_532.sql (80 rows)
INSERT INTO pathologies (nom_fr, nom_en, categorie, icd10_code)
VALUES
('Contusion of non spécifié part of small intestine, sequela','Contusion of unspecified part of small intestine, sequela','Traumatismes, empoisonnements et autres causes externes','S36.429S'),
('Laceration of duodenum, initial encounter','Laceration of duodenum, initial encounter','Traumatismes, empoisonnements et autres causes externes','S36.430A'),
('Laceration of duodenum, subsequent encounter','Laceration of duodenum, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S36.430D'),
('Laceration of duodenum, sequela','Laceration of duodenum, sequela','Traumatismes, empoisonnements et autres causes externes','S36.430S'),
('Laceration of autre part of small intestine, initial encounter','Laceration of other part of small intestine, initial encounter','Traumatismes, empoisonnements et autres causes externes','S36.438A'),
('Laceration of autre part of small intestine, subsequent encounter','Laceration of other part of small intestine, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S36.438D'),
('Laceration of autre part of small intestine, sequela','Laceration of other part of small intestine, sequela','Traumatismes, empoisonnements et autres causes externes','S36.438S'),
('Laceration of non spécifié part of small intestine, initial encounter','Laceration of unspecified part of small intestine, initial encounter','Traumatismes, empoisonnements et autres causes externes','S36.439A'),
('Laceration of non spécifié part of small intestine, subsequent encounter','Laceration of unspecified part of small intestine, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S36.439D'),
('Laceration of non spécifié part of small intestine, sequela','Laceration of unspecified part of small intestine, sequela','Traumatismes, empoisonnements et autres causes externes','S36.439S'),
('autre injury of duodenum, initial encounter','Other injury of duodenum, initial encounter','Traumatismes, empoisonnements et autres causes externes','S36.490A'),
('autre injury of duodenum, subsequent encounter','Other injury of duodenum, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S36.490D'),
('autre injury of duodenum, sequela','Other injury of duodenum, sequela','Traumatismes, empoisonnements et autres causes externes','S36.490S'),
('autre injury of autre part of small intestine, initial encounter','Other injury of other part of small intestine, initial encounter','Traumatismes, empoisonnements et autres causes externes','S36.498A'),
('autre injury of autre part of small intestine, subsequent encounter','Other injury of other part of small intestine, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S36.498D'),
('autre injury of autre part of small intestine, sequela','Other injury of other part of small intestine, sequela','Traumatismes, empoisonnements et autres causes externes','S36.498S'),
('autre injury of non spécifié part of small intestine, initial encounter','Other injury of unspecified part of small intestine, initial encounter','Traumatismes, empoisonnements et autres causes externes','S36.499A'),
('autre injury of non spécifié part of small intestine, subsequent encounter','Other injury of unspecified part of small intestine, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S36.499D'),
('autre injury of non spécifié part of small intestine, sequela','Other injury of unspecified part of small intestine, sequela','Traumatismes, empoisonnements et autres causes externes','S36.499S'),
('non spécifié injury of ascending [right] colon, initial encounter','Unspecified injury of ascending [right] colon, initial encounter','Traumatismes, empoisonnements et autres causes externes','S36.500A'),
('non spécifié injury of ascending [right] colon, subsequent encounter','Unspecified injury of ascending [right] colon, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S36.500D'),
('non spécifié injury of ascending [right] colon, sequela','Unspecified injury of ascending [right] colon, sequela','Traumatismes, empoisonnements et autres causes externes','S36.500S'),
('non spécifié injury of transverse colon, initial encounter','Unspecified injury of transverse colon, initial encounter','Traumatismes, empoisonnements et autres causes externes','S36.501A'),
('non spécifié injury of transverse colon, subsequent encounter','Unspecified injury of transverse colon, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S36.501D'),
('non spécifié injury of transverse colon, sequela','Unspecified injury of transverse colon, sequela','Traumatismes, empoisonnements et autres causes externes','S36.501S'),
('non spécifié injury of descending [left] colon, initial encounter','Unspecified injury of descending [left] colon, initial encounter','Traumatismes, empoisonnements et autres causes externes','S36.502A'),
('non spécifié injury of descending [left] colon, subsequent encounter','Unspecified injury of descending [left] colon, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S36.502D'),
('non spécifié injury of descending [left] colon, sequela','Unspecified injury of descending [left] colon, sequela','Traumatismes, empoisonnements et autres causes externes','S36.502S'),
('non spécifié injury of sigmoid colon, initial encounter','Unspecified injury of sigmoid colon, initial encounter','Traumatismes, empoisonnements et autres causes externes','S36.503A'),
('non spécifié injury of sigmoid colon, subsequent encounter','Unspecified injury of sigmoid colon, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S36.503D'),
('non spécifié injury of sigmoid colon, sequela','Unspecified injury of sigmoid colon, sequela','Traumatismes, empoisonnements et autres causes externes','S36.503S'),
('non spécifié injury of autre part of colon, initial encounter','Unspecified injury of other part of colon, initial encounter','Traumatismes, empoisonnements et autres causes externes','S36.508A'),
('non spécifié injury of autre part of colon, subsequent encounter','Unspecified injury of other part of colon, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S36.508D'),
('non spécifié injury of autre part of colon, sequela','Unspecified injury of other part of colon, sequela','Traumatismes, empoisonnements et autres causes externes','S36.508S'),
('non spécifié injury of non spécifié part of colon, initial encounter','Unspecified injury of unspecified part of colon, initial encounter','Traumatismes, empoisonnements et autres causes externes','S36.509A'),
('non spécifié injury of non spécifié part of colon, subsequent encounter','Unspecified injury of unspecified part of colon, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S36.509D'),
('non spécifié injury of non spécifié part of colon, sequela','Unspecified injury of unspecified part of colon, sequela','Traumatismes, empoisonnements et autres causes externes','S36.509S'),
('primitif blast injury of ascending [right] colon, initial encounter','Primary blast injury of ascending [right] colon, initial encounter','Traumatismes, empoisonnements et autres causes externes','S36.510A'),
('primitif blast injury of ascending [right] colon, subsequent encounter','Primary blast injury of ascending [right] colon, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S36.510D'),
('primitif blast injury of ascending [right] colon, sequela','Primary blast injury of ascending [right] colon, sequela','Traumatismes, empoisonnements et autres causes externes','S36.510S'),
('primitif blast injury of transverse colon, initial encounter','Primary blast injury of transverse colon, initial encounter','Traumatismes, empoisonnements et autres causes externes','S36.511A'),
('primitif blast injury of transverse colon, subsequent encounter','Primary blast injury of transverse colon, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S36.511D'),
('primitif blast injury of transverse colon, sequela','Primary blast injury of transverse colon, sequela','Traumatismes, empoisonnements et autres causes externes','S36.511S'),
('primitif blast injury of descending [left] colon, initial encounter','Primary blast injury of descending [left] colon, initial encounter','Traumatismes, empoisonnements et autres causes externes','S36.512A'),
('primitif blast injury of descending [left] colon, subsequent encounter','Primary blast injury of descending [left] colon, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S36.512D'),
('primitif blast injury of descending [left] colon, sequela','Primary blast injury of descending [left] colon, sequela','Traumatismes, empoisonnements et autres causes externes','S36.512S'),
('primitif blast injury of sigmoid colon, initial encounter','Primary blast injury of sigmoid colon, initial encounter','Traumatismes, empoisonnements et autres causes externes','S36.513A'),
('primitif blast injury of sigmoid colon, subsequent encounter','Primary blast injury of sigmoid colon, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S36.513D'),
('primitif blast injury of sigmoid colon, sequela','Primary blast injury of sigmoid colon, sequela','Traumatismes, empoisonnements et autres causes externes','S36.513S'),
('primitif blast injury of autre part of colon, initial encounter','Primary blast injury of other part of colon, initial encounter','Traumatismes, empoisonnements et autres causes externes','S36.518A'),
('primitif blast injury of autre part of colon, subsequent encounter','Primary blast injury of other part of colon, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S36.518D'),
('primitif blast injury of autre part of colon, sequela','Primary blast injury of other part of colon, sequela','Traumatismes, empoisonnements et autres causes externes','S36.518S'),
('primitif blast injury of non spécifié part of colon, initial encounter','Primary blast injury of unspecified part of colon, initial encounter','Traumatismes, empoisonnements et autres causes externes','S36.519A'),
('primitif blast injury of non spécifié part of colon, subsequent encounter','Primary blast injury of unspecified part of colon, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S36.519D'),
('primitif blast injury of non spécifié part of colon, sequela','Primary blast injury of unspecified part of colon, sequela','Traumatismes, empoisonnements et autres causes externes','S36.519S'),
('Contusion of ascending [right] colon, initial encounter','Contusion of ascending [right] colon, initial encounter','Traumatismes, empoisonnements et autres causes externes','S36.520A'),
('Contusion of ascending [right] colon, subsequent encounter','Contusion of ascending [right] colon, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S36.520D'),
('Contusion of ascending [right] colon, sequela','Contusion of ascending [right] colon, sequela','Traumatismes, empoisonnements et autres causes externes','S36.520S'),
('Contusion of transverse colon, initial encounter','Contusion of transverse colon, initial encounter','Traumatismes, empoisonnements et autres causes externes','S36.521A'),
('Contusion of transverse colon, subsequent encounter','Contusion of transverse colon, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S36.521D'),
('Contusion of transverse colon, sequela','Contusion of transverse colon, sequela','Traumatismes, empoisonnements et autres causes externes','S36.521S'),
('Contusion of descending [left] colon, initial encounter','Contusion of descending [left] colon, initial encounter','Traumatismes, empoisonnements et autres causes externes','S36.522A'),
('Contusion of descending [left] colon, subsequent encounter','Contusion of descending [left] colon, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S36.522D'),
('Contusion of descending [left] colon, sequela','Contusion of descending [left] colon, sequela','Traumatismes, empoisonnements et autres causes externes','S36.522S'),
('Contusion of sigmoid colon, initial encounter','Contusion of sigmoid colon, initial encounter','Traumatismes, empoisonnements et autres causes externes','S36.523A'),
('Contusion of sigmoid colon, subsequent encounter','Contusion of sigmoid colon, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S36.523D'),
('Contusion of sigmoid colon, sequela','Contusion of sigmoid colon, sequela','Traumatismes, empoisonnements et autres causes externes','S36.523S'),
('Contusion of autre part of colon, initial encounter','Contusion of other part of colon, initial encounter','Traumatismes, empoisonnements et autres causes externes','S36.528A'),
('Contusion of autre part of colon, subsequent encounter','Contusion of other part of colon, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S36.528D'),
('Contusion of autre part of colon, sequela','Contusion of other part of colon, sequela','Traumatismes, empoisonnements et autres causes externes','S36.528S'),
('Contusion of non spécifié part of colon, initial encounter','Contusion of unspecified part of colon, initial encounter','Traumatismes, empoisonnements et autres causes externes','S36.529A'),
('Contusion of non spécifié part of colon, subsequent encounter','Contusion of unspecified part of colon, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S36.529D'),
('Contusion of non spécifié part of colon, sequela','Contusion of unspecified part of colon, sequela','Traumatismes, empoisonnements et autres causes externes','S36.529S'),
('Laceration of ascending [right] colon, initial encounter','Laceration of ascending [right] colon, initial encounter','Traumatismes, empoisonnements et autres causes externes','S36.530A'),
('Laceration of ascending [right] colon, subsequent encounter','Laceration of ascending [right] colon, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S36.530D'),
('Laceration of ascending [right] colon, sequela','Laceration of ascending [right] colon, sequela','Traumatismes, empoisonnements et autres causes externes','S36.530S'),
('Laceration of transverse colon, initial encounter','Laceration of transverse colon, initial encounter','Traumatismes, empoisonnements et autres causes externes','S36.531A'),
('Laceration of transverse colon, subsequent encounter','Laceration of transverse colon, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S36.531D'),
('Laceration of transverse colon, sequela','Laceration of transverse colon, sequela','Traumatismes, empoisonnements et autres causes externes','S36.531S'),
('Laceration of descending [left] colon, initial encounter','Laceration of descending [left] colon, initial encounter','Traumatismes, empoisonnements et autres causes externes','S36.532A')
ON CONFLICT (nom_fr) DO NOTHING;
