-- icd10v2_batch_084.sql (80 rows)
INSERT INTO pathologies (nom_fr, nom_en, categorie, icd10_code)
VALUES
('Equatorial staphyloma, right eye','Equatorial staphyloma, right eye','Maladies de l''œil et de ses annexes','H15.811'),
('Equatorial staphyloma, left eye','Equatorial staphyloma, left eye','Maladies de l''œil et de ses annexes','H15.812'),
('Equatorial staphyloma, bilateral','Equatorial staphyloma, bilateral','Maladies de l''œil et de ses annexes','H15.813'),
('Equatorial staphyloma, non spécifié eye','Equatorial staphyloma, unspecified eye','Maladies de l''œil et de ses annexes','H15.819'),
('Localized anterior staphyloma, right eye','Localized anterior staphyloma, right eye','Maladies de l''œil et de ses annexes','H15.821'),
('Localized anterior staphyloma, left eye','Localized anterior staphyloma, left eye','Maladies de l''œil et de ses annexes','H15.822'),
('Localized anterior staphyloma, bilateral','Localized anterior staphyloma, bilateral','Maladies de l''œil et de ses annexes','H15.823'),
('Localized anterior staphyloma, non spécifié eye','Localized anterior staphyloma, unspecified eye','Maladies de l''œil et de ses annexes','H15.829'),
('Staphyloma posticum, right eye','Staphyloma posticum, right eye','Maladies de l''œil et de ses annexes','H15.831'),
('Staphyloma posticum, left eye','Staphyloma posticum, left eye','Maladies de l''œil et de ses annexes','H15.832'),
('Staphyloma posticum, bilateral','Staphyloma posticum, bilateral','Maladies de l''œil et de ses annexes','H15.833'),
('Staphyloma posticum, non spécifié eye','Staphyloma posticum, unspecified eye','Maladies de l''œil et de ses annexes','H15.839'),
('Scleral ectasia, right eye','Scleral ectasia, right eye','Maladies de l''œil et de ses annexes','H15.841'),
('Scleral ectasia, left eye','Scleral ectasia, left eye','Maladies de l''œil et de ses annexes','H15.842'),
('Scleral ectasia, bilateral','Scleral ectasia, bilateral','Maladies de l''œil et de ses annexes','H15.843'),
('Scleral ectasia, non spécifié eye','Scleral ectasia, unspecified eye','Maladies de l''œil et de ses annexes','H15.849'),
('Ring staphyloma, right eye','Ring staphyloma, right eye','Maladies de l''œil et de ses annexes','H15.851'),
('Ring staphyloma, left eye','Ring staphyloma, left eye','Maladies de l''œil et de ses annexes','H15.852'),
('Ring staphyloma, bilateral','Ring staphyloma, bilateral','Maladies de l''œil et de ses annexes','H15.853'),
('Ring staphyloma, non spécifié eye','Ring staphyloma, unspecified eye','Maladies de l''œil et de ses annexes','H15.859'),
('autre disorders of sclera','Other disorders of sclera','Maladies de l''œil et de ses annexes','H15.89'),
('non spécifié trouble of sclera','Unspecified disorder of sclera','Maladies de l''œil et de ses annexes','H15.9'),
('non spécifié corneal ulcer, right eye','Unspecified corneal ulcer, right eye','Maladies de l''œil et de ses annexes','H16.001'),
('non spécifié corneal ulcer, left eye','Unspecified corneal ulcer, left eye','Maladies de l''œil et de ses annexes','H16.002'),
('non spécifié corneal ulcer, bilateral','Unspecified corneal ulcer, bilateral','Maladies de l''œil et de ses annexes','H16.003'),
('non spécifié corneal ulcer, non spécifié eye','Unspecified corneal ulcer, unspecified eye','Maladies de l''œil et de ses annexes','H16.009'),
('Central corneal ulcer, right eye','Central corneal ulcer, right eye','Maladies de l''œil et de ses annexes','H16.011'),
('Central corneal ulcer, left eye','Central corneal ulcer, left eye','Maladies de l''œil et de ses annexes','H16.012'),
('Central corneal ulcer, bilateral','Central corneal ulcer, bilateral','Maladies de l''œil et de ses annexes','H16.013'),
('Central corneal ulcer, non spécifié eye','Central corneal ulcer, unspecified eye','Maladies de l''œil et de ses annexes','H16.019'),
('Ring corneal ulcer, right eye','Ring corneal ulcer, right eye','Maladies de l''œil et de ses annexes','H16.021'),
('Ring corneal ulcer, left eye','Ring corneal ulcer, left eye','Maladies de l''œil et de ses annexes','H16.022'),
('Ring corneal ulcer, bilateral','Ring corneal ulcer, bilateral','Maladies de l''œil et de ses annexes','H16.023'),
('Ring corneal ulcer, non spécifié eye','Ring corneal ulcer, unspecified eye','Maladies de l''œil et de ses annexes','H16.029'),
('Corneal ulcer with hypopyon, right eye','Corneal ulcer with hypopyon, right eye','Maladies de l''œil et de ses annexes','H16.031'),
('Corneal ulcer with hypopyon, left eye','Corneal ulcer with hypopyon, left eye','Maladies de l''œil et de ses annexes','H16.032'),
('Corneal ulcer with hypopyon, bilateral','Corneal ulcer with hypopyon, bilateral','Maladies de l''œil et de ses annexes','H16.033'),
('Corneal ulcer with hypopyon, non spécifié eye','Corneal ulcer with hypopyon, unspecified eye','Maladies de l''œil et de ses annexes','H16.039'),
('Marginal corneal ulcer, right eye','Marginal corneal ulcer, right eye','Maladies de l''œil et de ses annexes','H16.041'),
('Marginal corneal ulcer, left eye','Marginal corneal ulcer, left eye','Maladies de l''œil et de ses annexes','H16.042'),
('Marginal corneal ulcer, bilateral','Marginal corneal ulcer, bilateral','Maladies de l''œil et de ses annexes','H16.043'),
('Marginal corneal ulcer, non spécifié eye','Marginal corneal ulcer, unspecified eye','Maladies de l''œil et de ses annexes','H16.049'),
('Mooren''s corneal ulcer, right eye','Mooren''s corneal ulcer, right eye','Maladies de l''œil et de ses annexes','H16.051'),
('Mooren''s corneal ulcer, left eye','Mooren''s corneal ulcer, left eye','Maladies de l''œil et de ses annexes','H16.052'),
('Mooren''s corneal ulcer, bilateral','Mooren''s corneal ulcer, bilateral','Maladies de l''œil et de ses annexes','H16.053'),
('Mooren''s corneal ulcer, non spécifié eye','Mooren''s corneal ulcer, unspecified eye','Maladies de l''œil et de ses annexes','H16.059'),
('Mycotic corneal ulcer, right eye','Mycotic corneal ulcer, right eye','Maladies de l''œil et de ses annexes','H16.061'),
('Mycotic corneal ulcer, left eye','Mycotic corneal ulcer, left eye','Maladies de l''œil et de ses annexes','H16.062'),
('Mycotic corneal ulcer, bilateral','Mycotic corneal ulcer, bilateral','Maladies de l''œil et de ses annexes','H16.063'),
('Mycotic corneal ulcer, non spécifié eye','Mycotic corneal ulcer, unspecified eye','Maladies de l''œil et de ses annexes','H16.069'),
('Perforated corneal ulcer, right eye','Perforated corneal ulcer, right eye','Maladies de l''œil et de ses annexes','H16.071'),
('Perforated corneal ulcer, left eye','Perforated corneal ulcer, left eye','Maladies de l''œil et de ses annexes','H16.072'),
('Perforated corneal ulcer, bilateral','Perforated corneal ulcer, bilateral','Maladies de l''œil et de ses annexes','H16.073'),
('Perforated corneal ulcer, non spécifié eye','Perforated corneal ulcer, unspecified eye','Maladies de l''œil et de ses annexes','H16.079'),
('non spécifié superficial keratitis, right eye','Unspecified superficial keratitis, right eye','Maladies de l''œil et de ses annexes','H16.101'),
('non spécifié superficial keratitis, left eye','Unspecified superficial keratitis, left eye','Maladies de l''œil et de ses annexes','H16.102'),
('non spécifié superficial keratitis, bilateral','Unspecified superficial keratitis, bilateral','Maladies de l''œil et de ses annexes','H16.103'),
('non spécifié superficial keratitis, non spécifié eye','Unspecified superficial keratitis, unspecified eye','Maladies de l''œil et de ses annexes','H16.109'),
('Macular keratitis, right eye','Macular keratitis, right eye','Maladies de l''œil et de ses annexes','H16.111'),
('Macular keratitis, left eye','Macular keratitis, left eye','Maladies de l''œil et de ses annexes','H16.112'),
('Macular keratitis, bilateral','Macular keratitis, bilateral','Maladies de l''œil et de ses annexes','H16.113'),
('Macular keratitis, non spécifié eye','Macular keratitis, unspecified eye','Maladies de l''œil et de ses annexes','H16.119'),
('Filamentary keratitis, right eye','Filamentary keratitis, right eye','Maladies de l''œil et de ses annexes','H16.121'),
('Filamentary keratitis, left eye','Filamentary keratitis, left eye','Maladies de l''œil et de ses annexes','H16.122'),
('Filamentary keratitis, bilateral','Filamentary keratitis, bilateral','Maladies de l''œil et de ses annexes','H16.123'),
('Filamentary keratitis, non spécifié eye','Filamentary keratitis, unspecified eye','Maladies de l''œil et de ses annexes','H16.129'),
('Photokeratitis, right eye','Photokeratitis, right eye','Maladies de l''œil et de ses annexes','H16.131'),
('Photokeratitis, left eye','Photokeratitis, left eye','Maladies de l''œil et de ses annexes','H16.132'),
('Photokeratitis, bilateral','Photokeratitis, bilateral','Maladies de l''œil et de ses annexes','H16.133'),
('Photokeratitis, non spécifié eye','Photokeratitis, unspecified eye','Maladies de l''œil et de ses annexes','H16.139'),
('Punctate keratitis, right eye','Punctate keratitis, right eye','Maladies de l''œil et de ses annexes','H16.141'),
('Punctate keratitis, left eye','Punctate keratitis, left eye','Maladies de l''œil et de ses annexes','H16.142'),
('Punctate keratitis, bilateral','Punctate keratitis, bilateral','Maladies de l''œil et de ses annexes','H16.143'),
('Punctate keratitis, non spécifié eye','Punctate keratitis, unspecified eye','Maladies de l''œil et de ses annexes','H16.149'),
('non spécifié keratoconjunctivitis, right eye','Unspecified keratoconjunctivitis, right eye','Maladies de l''œil et de ses annexes','H16.201'),
('non spécifié keratoconjunctivitis, left eye','Unspecified keratoconjunctivitis, left eye','Maladies de l''œil et de ses annexes','H16.202'),
('non spécifié keratoconjunctivitis, bilateral','Unspecified keratoconjunctivitis, bilateral','Maladies de l''œil et de ses annexes','H16.203'),
('non spécifié keratoconjunctivitis, non spécifié eye','Unspecified keratoconjunctivitis, unspecified eye','Maladies de l''œil et de ses annexes','H16.209'),
('Exposure keratoconjunctivitis, right eye','Exposure keratoconjunctivitis, right eye','Maladies de l''œil et de ses annexes','H16.211'),
('Exposure keratoconjunctivitis, left eye','Exposure keratoconjunctivitis, left eye','Maladies de l''œil et de ses annexes','H16.212')
ON CONFLICT (nom_fr) DO NOTHING;
