-- icd10v2_batch_352.sql (80 rows)
INSERT INTO pathologies (nom_fr, nom_en, categorie, icd10_code)
VALUES
('Effet indésirable de rifampicins, subsequent encounter','Adverse effect of rifampicins, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T36.6X5D'),
('Effet indésirable de rifampicins, sequela','Adverse effect of rifampicins, sequela','Traumatismes, empoisonnements et autres causes externes','T36.6X5S'),
('Underdosing of rifampicins, initial encounter','Underdosing of rifampicins, initial encounter','Traumatismes, empoisonnements et autres causes externes','T36.6X6A'),
('Underdosing of rifampicins, subsequent encounter','Underdosing of rifampicins, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T36.6X6D'),
('Underdosing of rifampicins, sequela','Underdosing of rifampicins, sequela','Traumatismes, empoisonnements et autres causes externes','T36.6X6S'),
('Intoxication par antifungal antibiotics, systemically used, accidental (unintentional), initial encounter','Poisoning by antifungal antibiotics, systemically used, accidental (unintentional), initial encounter','Traumatismes, empoisonnements et autres causes externes','T36.7X1A'),
('Intoxication par antifungal antibiotics, systemically used, accidental (unintentional), subsequent encounter','Poisoning by antifungal antibiotics, systemically used, accidental (unintentional), subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T36.7X1D'),
('Intoxication par antifungal antibiotics, systemically used, accidental (unintentional), sequela','Poisoning by antifungal antibiotics, systemically used, accidental (unintentional), sequela','Traumatismes, empoisonnements et autres causes externes','T36.7X1S'),
('Intoxication par antifungal antibiotics, systemically used, intentional self-harm, initial encounter','Poisoning by antifungal antibiotics, systemically used, intentional self-harm, initial encounter','Traumatismes, empoisonnements et autres causes externes','T36.7X2A'),
('Intoxication par antifungal antibiotics, systemically used, intentional self-harm, subsequent encounter','Poisoning by antifungal antibiotics, systemically used, intentional self-harm, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T36.7X2D'),
('Intoxication par antifungal antibiotics, systemically used, intentional self-harm, sequela','Poisoning by antifungal antibiotics, systemically used, intentional self-harm, sequela','Traumatismes, empoisonnements et autres causes externes','T36.7X2S'),
('Intoxication par antifungal antibiotics, systemically used, assault, initial encounter','Poisoning by antifungal antibiotics, systemically used, assault, initial encounter','Traumatismes, empoisonnements et autres causes externes','T36.7X3A'),
('Intoxication par antifungal antibiotics, systemically used, assault, subsequent encounter','Poisoning by antifungal antibiotics, systemically used, assault, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T36.7X3D'),
('Intoxication par antifungal antibiotics, systemically used, assault, sequela','Poisoning by antifungal antibiotics, systemically used, assault, sequela','Traumatismes, empoisonnements et autres causes externes','T36.7X3S'),
('Intoxication par antifungal antibiotics, systemically used, undetermined, initial encounter','Poisoning by antifungal antibiotics, systemically used, undetermined, initial encounter','Traumatismes, empoisonnements et autres causes externes','T36.7X4A'),
('Intoxication par antifungal antibiotics, systemically used, undetermined, subsequent encounter','Poisoning by antifungal antibiotics, systemically used, undetermined, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T36.7X4D'),
('Intoxication par antifungal antibiotics, systemically used, undetermined, sequela','Poisoning by antifungal antibiotics, systemically used, undetermined, sequela','Traumatismes, empoisonnements et autres causes externes','T36.7X4S'),
('Effet indésirable de antifungal antibiotics, systemically used, initial encounter','Adverse effect of antifungal antibiotics, systemically used, initial encounter','Traumatismes, empoisonnements et autres causes externes','T36.7X5A'),
('Effet indésirable de antifungal antibiotics, systemically used, subsequent encounter','Adverse effect of antifungal antibiotics, systemically used, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T36.7X5D'),
('Effet indésirable de antifungal antibiotics, systemically used, sequela','Adverse effect of antifungal antibiotics, systemically used, sequela','Traumatismes, empoisonnements et autres causes externes','T36.7X5S'),
('Underdosing of antifungal antibiotics, systemically used, initial encounter','Underdosing of antifungal antibiotics, systemically used, initial encounter','Traumatismes, empoisonnements et autres causes externes','T36.7X6A'),
('Underdosing of antifungal antibiotics, systemically used, subsequent encounter','Underdosing of antifungal antibiotics, systemically used, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T36.7X6D'),
('Underdosing of antifungal antibiotics, systemically used, sequela','Underdosing of antifungal antibiotics, systemically used, sequela','Traumatismes, empoisonnements et autres causes externes','T36.7X6S'),
('Intoxication par other systemic antibiotics, accidental (unintentional), initial encounter','Poisoning by other systemic antibiotics, accidental (unintentional), initial encounter','Traumatismes, empoisonnements et autres causes externes','T36.8X1A'),
('Intoxication par other systemic antibiotics, accidental (unintentional), subsequent encounter','Poisoning by other systemic antibiotics, accidental (unintentional), subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T36.8X1D'),
('Intoxication par other systemic antibiotics, accidental (unintentional), sequela','Poisoning by other systemic antibiotics, accidental (unintentional), sequela','Traumatismes, empoisonnements et autres causes externes','T36.8X1S'),
('Intoxication par other systemic antibiotics, intentional self-harm, initial encounter','Poisoning by other systemic antibiotics, intentional self-harm, initial encounter','Traumatismes, empoisonnements et autres causes externes','T36.8X2A'),
('Intoxication par other systemic antibiotics, intentional self-harm, subsequent encounter','Poisoning by other systemic antibiotics, intentional self-harm, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T36.8X2D'),
('Intoxication par other systemic antibiotics, intentional self-harm, sequela','Poisoning by other systemic antibiotics, intentional self-harm, sequela','Traumatismes, empoisonnements et autres causes externes','T36.8X2S'),
('Intoxication par other systemic antibiotics, assault, initial encounter','Poisoning by other systemic antibiotics, assault, initial encounter','Traumatismes, empoisonnements et autres causes externes','T36.8X3A'),
('Intoxication par other systemic antibiotics, assault, subsequent encounter','Poisoning by other systemic antibiotics, assault, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T36.8X3D'),
('Intoxication par other systemic antibiotics, assault, sequela','Poisoning by other systemic antibiotics, assault, sequela','Traumatismes, empoisonnements et autres causes externes','T36.8X3S'),
('Intoxication par other systemic antibiotics, undetermined, initial encounter','Poisoning by other systemic antibiotics, undetermined, initial encounter','Traumatismes, empoisonnements et autres causes externes','T36.8X4A'),
('Intoxication par other systemic antibiotics, undetermined, subsequent encounter','Poisoning by other systemic antibiotics, undetermined, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T36.8X4D'),
('Intoxication par other systemic antibiotics, undetermined, sequela','Poisoning by other systemic antibiotics, undetermined, sequela','Traumatismes, empoisonnements et autres causes externes','T36.8X4S'),
('Effet indésirable de other systemic antibiotics, initial encounter','Adverse effect of other systemic antibiotics, initial encounter','Traumatismes, empoisonnements et autres causes externes','T36.8X5A'),
('Effet indésirable de other systemic antibiotics, subsequent encounter','Adverse effect of other systemic antibiotics, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T36.8X5D'),
('Effet indésirable de other systemic antibiotics, sequela','Adverse effect of other systemic antibiotics, sequela','Traumatismes, empoisonnements et autres causes externes','T36.8X5S'),
('Underdosing of autre systemic antibiotics, initial encounter','Underdosing of other systemic antibiotics, initial encounter','Traumatismes, empoisonnements et autres causes externes','T36.8X6A'),
('Underdosing of autre systemic antibiotics, subsequent encounter','Underdosing of other systemic antibiotics, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T36.8X6D'),
('Subluxation of T4/T5 thoracic vertebra, sequela','Subluxation of T4/T5 thoracic vertebra, sequela','Traumatismes, empoisonnements et autres causes externes','S23.130S'),
('Luxation de T4/T5 thoracic vertebra, sequela','Dislocation of T4/T5 thoracic vertebra, sequela','Traumatismes, empoisonnements et autres causes externes','S23.131S'),
('Subluxation of T4/T5 thoracic vertebra, initial encounter','Subluxation of T4/T5 thoracic vertebra, initial encounter','Traumatismes, empoisonnements et autres causes externes','S23.130A'),
('Subluxation of T4/T5 thoracic vertebra, subsequent encounter','Subluxation of T4/T5 thoracic vertebra, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S23.130D'),
('Luxation de T4/T5 thoracic vertebra, initial encounter','Dislocation of T4/T5 thoracic vertebra, initial encounter','Traumatismes, empoisonnements et autres causes externes','S23.131A'),
('Luxation de T4/T5 thoracic vertebra, subsequent encounter','Dislocation of T4/T5 thoracic vertebra, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S23.131D'),
('Intoxication par opium, accidental (unintentional), initial encounter','Poisoning by opium, accidental (unintentional), initial encounter','Traumatismes, empoisonnements et autres causes externes','T40.0X1A'),
('Intoxication par opium, accidental (unintentional), subsequent encounter','Poisoning by opium, accidental (unintentional), subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T40.0X1D'),
('Intoxication par opium, accidental (unintentional), sequela','Poisoning by opium, accidental (unintentional), sequela','Traumatismes, empoisonnements et autres causes externes','T40.0X1S'),
('Intoxication par opium, intentional self-harm, initial encounter','Poisoning by opium, intentional self-harm, initial encounter','Traumatismes, empoisonnements et autres causes externes','T40.0X2A'),
('Intoxication par opium, intentional self-harm, subsequent encounter','Poisoning by opium, intentional self-harm, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T40.0X2D'),
('Intoxication par opium, intentional self-harm, sequela','Poisoning by opium, intentional self-harm, sequela','Traumatismes, empoisonnements et autres causes externes','T40.0X2S'),
('Intoxication par opium, assault, initial encounter','Poisoning by opium, assault, initial encounter','Traumatismes, empoisonnements et autres causes externes','T40.0X3A'),
('Intoxication par opium, assault, subsequent encounter','Poisoning by opium, assault, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T40.0X3D'),
('Intoxication par opium, assault, sequela','Poisoning by opium, assault, sequela','Traumatismes, empoisonnements et autres causes externes','T40.0X3S'),
('Intoxication par opium, undetermined, initial encounter','Poisoning by opium, undetermined, initial encounter','Traumatismes, empoisonnements et autres causes externes','T40.0X4A'),
('Intoxication par opium, undetermined, subsequent encounter','Poisoning by opium, undetermined, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T40.0X4D'),
('Intoxication par opium, undetermined, sequela','Poisoning by opium, undetermined, sequela','Traumatismes, empoisonnements et autres causes externes','T40.0X4S'),
('Effet indésirable de opium, initial encounter','Adverse effect of opium, initial encounter','Traumatismes, empoisonnements et autres causes externes','T40.0X5A'),
('Effet indésirable de opium, subsequent encounter','Adverse effect of opium, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T40.0X5D'),
('Effet indésirable de opium, sequela','Adverse effect of opium, sequela','Traumatismes, empoisonnements et autres causes externes','T40.0X5S'),
('Underdosing of opium, initial encounter','Underdosing of opium, initial encounter','Traumatismes, empoisonnements et autres causes externes','T40.0X6A'),
('Underdosing of opium, subsequent encounter','Underdosing of opium, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T40.0X6D'),
('Underdosing of opium, sequela','Underdosing of opium, sequela','Traumatismes, empoisonnements et autres causes externes','T40.0X6S'),
('Intoxication par heroin, accidental (unintentional), initial encounter','Poisoning by heroin, accidental (unintentional), initial encounter','Traumatismes, empoisonnements et autres causes externes','T40.1X1A'),
('Intoxication par heroin, accidental (unintentional), subsequent encounter','Poisoning by heroin, accidental (unintentional), subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T40.1X1D'),
('Intoxication par heroin, accidental (unintentional), sequela','Poisoning by heroin, accidental (unintentional), sequela','Traumatismes, empoisonnements et autres causes externes','T40.1X1S'),
('Intoxication par heroin, intentional self-harm, initial encounter','Poisoning by heroin, intentional self-harm, initial encounter','Traumatismes, empoisonnements et autres causes externes','T40.1X2A'),
('Intoxication par heroin, intentional self-harm, subsequent encounter','Poisoning by heroin, intentional self-harm, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T40.1X2D'),
('Intoxication par heroin, intentional self-harm, sequela','Poisoning by heroin, intentional self-harm, sequela','Traumatismes, empoisonnements et autres causes externes','T40.1X2S'),
('Intoxication par heroin, assault, initial encounter','Poisoning by heroin, assault, initial encounter','Traumatismes, empoisonnements et autres causes externes','T40.1X3A'),
('Intoxication par heroin, assault, subsequent encounter','Poisoning by heroin, assault, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T40.1X3D'),
('Intoxication par heroin, assault, sequela','Poisoning by heroin, assault, sequela','Traumatismes, empoisonnements et autres causes externes','T40.1X3S'),
('Intoxication par heroin, undetermined, initial encounter','Poisoning by heroin, undetermined, initial encounter','Traumatismes, empoisonnements et autres causes externes','T40.1X4A'),
('Intoxication par heroin, undetermined, subsequent encounter','Poisoning by heroin, undetermined, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T40.1X4D'),
('Intoxication par heroin, undetermined, sequela','Poisoning by heroin, undetermined, sequela','Traumatismes, empoisonnements et autres causes externes','T40.1X4S'),
('Intoxication par other opioids, accidental (unintentional), initial encounter','Poisoning by other opioids, accidental (unintentional), initial encounter','Traumatismes, empoisonnements et autres causes externes','T40.2X1A'),
('Intoxication par other opioids, accidental (unintentional), subsequent encounter','Poisoning by other opioids, accidental (unintentional), subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T40.2X1D'),
('Intoxication par other opioids, accidental (unintentional), sequela','Poisoning by other opioids, accidental (unintentional), sequela','Traumatismes, empoisonnements et autres causes externes','T40.2X1S'),
('Intoxication par other opioids, intentional self-harm, initial encounter','Poisoning by other opioids, intentional self-harm, initial encounter','Traumatismes, empoisonnements et autres causes externes','T40.2X2A')
ON CONFLICT (nom_fr) DO NOTHING;
