-- icd10v2_batch_172.sql (80 rows)
INSERT INTO pathologies (nom_fr, nom_en, categorie, icd10_code)
VALUES
('Gout due to renal impairment, non spécifié wrist','Gout due to renal impairment, unspecified wrist','Maladies de l''appareil locomoteur','M10.339'),
('Gout due to renal impairment, right hand','Gout due to renal impairment, right hand','Maladies de l''appareil locomoteur','M10.341'),
('Gout due to renal impairment, left hand','Gout due to renal impairment, left hand','Maladies de l''appareil locomoteur','M10.342'),
('Gout due to renal impairment, non spécifié hand','Gout due to renal impairment, unspecified hand','Maladies de l''appareil locomoteur','M10.349'),
('Gout due to renal impairment, right hip','Gout due to renal impairment, right hip','Maladies de l''appareil locomoteur','M10.351'),
('Gout due to renal impairment, left hip','Gout due to renal impairment, left hip','Maladies de l''appareil locomoteur','M10.352'),
('Gout due to renal impairment, non spécifié hip','Gout due to renal impairment, unspecified hip','Maladies de l''appareil locomoteur','M10.359'),
('Gout due to renal impairment, right knee','Gout due to renal impairment, right knee','Maladies de l''appareil locomoteur','M10.361'),
('Gout due to renal impairment, left knee','Gout due to renal impairment, left knee','Maladies de l''appareil locomoteur','M10.362'),
('Gout due to renal impairment, non spécifié knee','Gout due to renal impairment, unspecified knee','Maladies de l''appareil locomoteur','M10.369'),
('Gout due to renal impairment, right ankle and foot','Gout due to renal impairment, right ankle and foot','Maladies de l''appareil locomoteur','M10.371'),
('Gout due to renal impairment, left ankle and foot','Gout due to renal impairment, left ankle and foot','Maladies de l''appareil locomoteur','M10.372'),
('Gout due to renal impairment, non spécifié ankle and foot','Gout due to renal impairment, unspecified ankle and foot','Maladies de l''appareil locomoteur','M10.379'),
('Gout due to renal impairment, vertebrae','Gout due to renal impairment, vertebrae','Maladies de l''appareil locomoteur','M10.38'),
('Gout due to renal impairment, multiple sites','Gout due to renal impairment, multiple sites','Maladies de l''appareil locomoteur','M10.39'),
('autre secondaire gout, non spécifié site','Other secondary gout, unspecified site','Maladies de l''appareil locomoteur','M10.40'),
('autre secondaire gout, right shoulder','Other secondary gout, right shoulder','Maladies de l''appareil locomoteur','M10.411'),
('autre secondaire gout, left shoulder','Other secondary gout, left shoulder','Maladies de l''appareil locomoteur','M10.412'),
('autre secondaire gout, non spécifié shoulder','Other secondary gout, unspecified shoulder','Maladies de l''appareil locomoteur','M10.419'),
('autre secondaire gout, right elbow','Other secondary gout, right elbow','Maladies de l''appareil locomoteur','M10.421'),
('autre secondaire gout, left elbow','Other secondary gout, left elbow','Maladies de l''appareil locomoteur','M10.422'),
('autre secondaire gout, non spécifié elbow','Other secondary gout, unspecified elbow','Maladies de l''appareil locomoteur','M10.429'),
('autre secondaire gout, right wrist','Other secondary gout, right wrist','Maladies de l''appareil locomoteur','M10.431'),
('autre secondaire gout, left wrist','Other secondary gout, left wrist','Maladies de l''appareil locomoteur','M10.432'),
('autre secondaire gout, non spécifié wrist','Other secondary gout, unspecified wrist','Maladies de l''appareil locomoteur','M10.439'),
('autre secondaire gout, right hand','Other secondary gout, right hand','Maladies de l''appareil locomoteur','M10.441'),
('autre secondaire gout, left hand','Other secondary gout, left hand','Maladies de l''appareil locomoteur','M10.442'),
('autre secondaire gout, non spécifié hand','Other secondary gout, unspecified hand','Maladies de l''appareil locomoteur','M10.449'),
('autre secondaire gout, right hip','Other secondary gout, right hip','Maladies de l''appareil locomoteur','M10.451'),
('autre secondaire gout, left hip','Other secondary gout, left hip','Maladies de l''appareil locomoteur','M10.452'),
('autre secondaire gout, non spécifié hip','Other secondary gout, unspecified hip','Maladies de l''appareil locomoteur','M10.459'),
('autre secondaire gout, right knee','Other secondary gout, right knee','Maladies de l''appareil locomoteur','M10.461'),
('autre secondaire gout, left knee','Other secondary gout, left knee','Maladies de l''appareil locomoteur','M10.462'),
('autre secondaire gout, non spécifié knee','Other secondary gout, unspecified knee','Maladies de l''appareil locomoteur','M10.469'),
('autre secondaire gout, right ankle and foot','Other secondary gout, right ankle and foot','Maladies de l''appareil locomoteur','M10.471'),
('autre secondaire gout, left ankle and foot','Other secondary gout, left ankle and foot','Maladies de l''appareil locomoteur','M10.472'),
('autre secondaire gout, non spécifié ankle and foot','Other secondary gout, unspecified ankle and foot','Maladies de l''appareil locomoteur','M10.479'),
('autre secondaire gout, vertebrae','Other secondary gout, vertebrae','Maladies de l''appareil locomoteur','M10.48'),
('autre secondaire gout, multiple sites','Other secondary gout, multiple sites','Maladies de l''appareil locomoteur','M10.49'),
('Gout, non spécifié','Gout, unspecified','Maladies de l''appareil locomoteur','M10.9'),
('Hydroxyapatite deposition maladie, non spécifié site','Hydroxyapatite deposition disease, unspecified site','Maladies de l''appareil locomoteur','M11.00'),
('Hydroxyapatite deposition maladie, right shoulder','Hydroxyapatite deposition disease, right shoulder','Maladies de l''appareil locomoteur','M11.011'),
('Hydroxyapatite deposition maladie, left shoulder','Hydroxyapatite deposition disease, left shoulder','Maladies de l''appareil locomoteur','M11.012'),
('Hydroxyapatite deposition maladie, non spécifié shoulder','Hydroxyapatite deposition disease, unspecified shoulder','Maladies de l''appareil locomoteur','M11.019'),
('Hydroxyapatite deposition maladie, right elbow','Hydroxyapatite deposition disease, right elbow','Maladies de l''appareil locomoteur','M11.021'),
('Hydroxyapatite deposition maladie, left elbow','Hydroxyapatite deposition disease, left elbow','Maladies de l''appareil locomoteur','M11.022'),
('Hydroxyapatite deposition maladie, non spécifié elbow','Hydroxyapatite deposition disease, unspecified elbow','Maladies de l''appareil locomoteur','M11.029'),
('Hydroxyapatite deposition maladie, right wrist','Hydroxyapatite deposition disease, right wrist','Maladies de l''appareil locomoteur','M11.031'),
('Hydroxyapatite deposition maladie, left wrist','Hydroxyapatite deposition disease, left wrist','Maladies de l''appareil locomoteur','M11.032'),
('Hydroxyapatite deposition maladie, non spécifié wrist','Hydroxyapatite deposition disease, unspecified wrist','Maladies de l''appareil locomoteur','M11.039'),
('Hydroxyapatite deposition maladie, right hand','Hydroxyapatite deposition disease, right hand','Maladies de l''appareil locomoteur','M11.041'),
('Hydroxyapatite deposition maladie, left hand','Hydroxyapatite deposition disease, left hand','Maladies de l''appareil locomoteur','M11.042'),
('Hydroxyapatite deposition maladie, non spécifié hand','Hydroxyapatite deposition disease, unspecified hand','Maladies de l''appareil locomoteur','M11.049'),
('Hydroxyapatite deposition maladie, right hip','Hydroxyapatite deposition disease, right hip','Maladies de l''appareil locomoteur','M11.051'),
('Hydroxyapatite deposition maladie, left hip','Hydroxyapatite deposition disease, left hip','Maladies de l''appareil locomoteur','M11.052'),
('Hydroxyapatite deposition maladie, non spécifié hip','Hydroxyapatite deposition disease, unspecified hip','Maladies de l''appareil locomoteur','M11.059'),
('Hydroxyapatite deposition maladie, right knee','Hydroxyapatite deposition disease, right knee','Maladies de l''appareil locomoteur','M11.061'),
('Hydroxyapatite deposition maladie, left knee','Hydroxyapatite deposition disease, left knee','Maladies de l''appareil locomoteur','M11.062'),
('Hydroxyapatite deposition maladie, non spécifié knee','Hydroxyapatite deposition disease, unspecified knee','Maladies de l''appareil locomoteur','M11.069'),
('Hydroxyapatite deposition maladie, right ankle and foot','Hydroxyapatite deposition disease, right ankle and foot','Maladies de l''appareil locomoteur','M11.071'),
('Hydroxyapatite deposition maladie, left ankle and foot','Hydroxyapatite deposition disease, left ankle and foot','Maladies de l''appareil locomoteur','M11.072'),
('Hydroxyapatite deposition maladie, non spécifié ankle and foot','Hydroxyapatite deposition disease, unspecified ankle and foot','Maladies de l''appareil locomoteur','M11.079'),
('Hydroxyapatite deposition maladie, vertebrae','Hydroxyapatite deposition disease, vertebrae','Maladies de l''appareil locomoteur','M11.08'),
('Hydroxyapatite deposition maladie, multiple sites','Hydroxyapatite deposition disease, multiple sites','Maladies de l''appareil locomoteur','M11.09'),
('Familial chondrocalcinosis, non spécifié site','Familial chondrocalcinosis, unspecified site','Maladies de l''appareil locomoteur','M11.10'),
('Familial chondrocalcinosis, right shoulder','Familial chondrocalcinosis, right shoulder','Maladies de l''appareil locomoteur','M11.111'),
('Familial chondrocalcinosis, left shoulder','Familial chondrocalcinosis, left shoulder','Maladies de l''appareil locomoteur','M11.112'),
('Familial chondrocalcinosis, non spécifié shoulder','Familial chondrocalcinosis, unspecified shoulder','Maladies de l''appareil locomoteur','M11.119'),
('Familial chondrocalcinosis, right elbow','Familial chondrocalcinosis, right elbow','Maladies de l''appareil locomoteur','M11.121'),
('Familial chondrocalcinosis, left elbow','Familial chondrocalcinosis, left elbow','Maladies de l''appareil locomoteur','M11.122'),
('Familial chondrocalcinosis, non spécifié elbow','Familial chondrocalcinosis, unspecified elbow','Maladies de l''appareil locomoteur','M11.129'),
('Familial chondrocalcinosis, right wrist','Familial chondrocalcinosis, right wrist','Maladies de l''appareil locomoteur','M11.131'),
('Familial chondrocalcinosis, left wrist','Familial chondrocalcinosis, left wrist','Maladies de l''appareil locomoteur','M11.132'),
('Familial chondrocalcinosis, non spécifié wrist','Familial chondrocalcinosis, unspecified wrist','Maladies de l''appareil locomoteur','M11.139'),
('Familial chondrocalcinosis, right hand','Familial chondrocalcinosis, right hand','Maladies de l''appareil locomoteur','M11.141'),
('Familial chondrocalcinosis, left hand','Familial chondrocalcinosis, left hand','Maladies de l''appareil locomoteur','M11.142'),
('Familial chondrocalcinosis, non spécifié hand','Familial chondrocalcinosis, unspecified hand','Maladies de l''appareil locomoteur','M11.149'),
('Familial chondrocalcinosis, right hip','Familial chondrocalcinosis, right hip','Maladies de l''appareil locomoteur','M11.151'),
('Familial chondrocalcinosis, left hip','Familial chondrocalcinosis, left hip','Maladies de l''appareil locomoteur','M11.152'),
('Familial chondrocalcinosis, non spécifié hip','Familial chondrocalcinosis, unspecified hip','Maladies de l''appareil locomoteur','M11.159')
ON CONFLICT (nom_fr) DO NOTHING;
