-- icd10v2_batch_184.sql (80 rows)
INSERT INTO pathologies (nom_fr, nom_en, categorie, icd10_code)
VALUES
('Spinal enthesopathy, multiple sites in spine','Spinal enthesopathy, multiple sites in spine','Maladies de l''appareil locomoteur','M46.09'),
('Sacroiliitis, not elsewhere classified','Sacroiliitis, not elsewhere classified','Maladies de l''appareil locomoteur','M46.1'),
('Osteomyelitis of vertebra, site non spécifié','Osteomyelitis of vertebra, site unspecified','Maladies de l''appareil locomoteur','M46.20'),
('Osteomyelitis of vertebra, occipito-atlanto-axial region','Osteomyelitis of vertebra, occipito-atlanto-axial region','Maladies de l''appareil locomoteur','M46.21'),
('Osteomyelitis of vertebra, cervical region','Osteomyelitis of vertebra, cervical region','Maladies de l''appareil locomoteur','M46.22'),
('Osteomyelitis of vertebra, cervicothoracic region','Osteomyelitis of vertebra, cervicothoracic region','Maladies de l''appareil locomoteur','M46.23'),
('Osteomyelitis of vertebra, thoracic region','Osteomyelitis of vertebra, thoracic region','Maladies de l''appareil locomoteur','M46.24'),
('Osteomyelitis of vertebra, thoracolumbar region','Osteomyelitis of vertebra, thoracolumbar region','Maladies de l''appareil locomoteur','M46.25'),
('Osteomyelitis of vertebra, lumbar region','Osteomyelitis of vertebra, lumbar region','Maladies de l''appareil locomoteur','M46.26'),
('Osteomyelitis of vertebra, lumbosacral region','Osteomyelitis of vertebra, lumbosacral region','Maladies de l''appareil locomoteur','M46.27'),
('Osteomyelitis of vertebra, sacral and sacrococcygeal region','Osteomyelitis of vertebra, sacral and sacrococcygeal region','Maladies de l''appareil locomoteur','M46.28'),
('infection of intervertebral disc (pyogenic), site non spécifié','Infection of intervertebral disc (pyogenic), site unspecified','Maladies de l''appareil locomoteur','M46.30'),
('infection of intervertebral disc (pyogenic), occipito-atlanto-axial region','Infection of intervertebral disc (pyogenic), occipito-atlanto-axial region','Maladies de l''appareil locomoteur','M46.31'),
('infection of intervertebral disc (pyogenic), cervical region','Infection of intervertebral disc (pyogenic), cervical region','Maladies de l''appareil locomoteur','M46.32'),
('infection of intervertebral disc (pyogenic), cervicothoracic region','Infection of intervertebral disc (pyogenic), cervicothoracic region','Maladies de l''appareil locomoteur','M46.33'),
('infection of intervertebral disc (pyogenic), thoracic region','Infection of intervertebral disc (pyogenic), thoracic region','Maladies de l''appareil locomoteur','M46.34'),
('infection of intervertebral disc (pyogenic), thoracolumbar region','Infection of intervertebral disc (pyogenic), thoracolumbar region','Maladies de l''appareil locomoteur','M46.35'),
('infection of intervertebral disc (pyogenic), lumbar region','Infection of intervertebral disc (pyogenic), lumbar region','Maladies de l''appareil locomoteur','M46.36'),
('infection of intervertebral disc (pyogenic), lumbosacral region','Infection of intervertebral disc (pyogenic), lumbosacral region','Maladies de l''appareil locomoteur','M46.37'),
('infection of intervertebral disc (pyogenic), sacral and sacrococcygeal region','Infection of intervertebral disc (pyogenic), sacral and sacrococcygeal region','Maladies de l''appareil locomoteur','M46.38'),
('infection of intervertebral disc (pyogenic), multiple sites in spine','Infection of intervertebral disc (pyogenic), multiple sites in spine','Maladies de l''appareil locomoteur','M46.39'),
('Discitis, non spécifié, site non spécifié','Discitis, unspecified, site unspecified','Maladies de l''appareil locomoteur','M46.40'),
('Discitis, non spécifié, occipito-atlanto-axial region','Discitis, unspecified, occipito-atlanto-axial region','Maladies de l''appareil locomoteur','M46.41'),
('Discitis, non spécifié, cervical region','Discitis, unspecified, cervical region','Maladies de l''appareil locomoteur','M46.42'),
('Discitis, non spécifié, cervicothoracic region','Discitis, unspecified, cervicothoracic region','Maladies de l''appareil locomoteur','M46.43'),
('Discitis, non spécifié, thoracic region','Discitis, unspecified, thoracic region','Maladies de l''appareil locomoteur','M46.44'),
('Discitis, non spécifié, thoracolumbar region','Discitis, unspecified, thoracolumbar region','Maladies de l''appareil locomoteur','M46.45'),
('Discitis, non spécifié, lumbar region','Discitis, unspecified, lumbar region','Maladies de l''appareil locomoteur','M46.46'),
('Discitis, non spécifié, lumbosacral region','Discitis, unspecified, lumbosacral region','Maladies de l''appareil locomoteur','M46.47'),
('Discitis, non spécifié, sacral and sacrococcygeal region','Discitis, unspecified, sacral and sacrococcygeal region','Maladies de l''appareil locomoteur','M46.48'),
('Discitis, non spécifié, multiple sites in spine','Discitis, unspecified, multiple sites in spine','Maladies de l''appareil locomoteur','M46.49'),
('autre infective spondylopathies, site non spécifié','Other infective spondylopathies, site unspecified','Maladies de l''appareil locomoteur','M46.50'),
('autre infective spondylopathies, occipito-atlanto-axial region','Other infective spondylopathies, occipito-atlanto-axial region','Maladies de l''appareil locomoteur','M46.51'),
('autre infective spondylopathies, cervical region','Other infective spondylopathies, cervical region','Maladies de l''appareil locomoteur','M46.52'),
('autre infective spondylopathies, cervicothoracic region','Other infective spondylopathies, cervicothoracic region','Maladies de l''appareil locomoteur','M46.53'),
('autre infective spondylopathies, thoracic region','Other infective spondylopathies, thoracic region','Maladies de l''appareil locomoteur','M46.54'),
('autre infective spondylopathies, thoracolumbar region','Other infective spondylopathies, thoracolumbar region','Maladies de l''appareil locomoteur','M46.55'),
('autre infective spondylopathies, lumbar region','Other infective spondylopathies, lumbar region','Maladies de l''appareil locomoteur','M46.56'),
('autre infective spondylopathies, lumbosacral region','Other infective spondylopathies, lumbosacral region','Maladies de l''appareil locomoteur','M46.57'),
('autre infective spondylopathies, sacral and sacrococcygeal region','Other infective spondylopathies, sacral and sacrococcygeal region','Maladies de l''appareil locomoteur','M46.58'),
('autre infective spondylopathies, multiple sites in spine','Other infective spondylopathies, multiple sites in spine','Maladies de l''appareil locomoteur','M46.59'),
('autre specified inflammatory spondylopathies, site non spécifié','Other specified inflammatory spondylopathies, site unspecified','Maladies de l''appareil locomoteur','M46.80'),
('autre specified inflammatory spondylopathies, occipito-atlanto-axial region','Other specified inflammatory spondylopathies, occipito-atlanto-axial region','Maladies de l''appareil locomoteur','M46.81'),
('autre specified inflammatory spondylopathies, cervical region','Other specified inflammatory spondylopathies, cervical region','Maladies de l''appareil locomoteur','M46.82'),
('autre specified inflammatory spondylopathies, cervicothoracic region','Other specified inflammatory spondylopathies, cervicothoracic region','Maladies de l''appareil locomoteur','M46.83'),
('autre specified inflammatory spondylopathies, thoracic region','Other specified inflammatory spondylopathies, thoracic region','Maladies de l''appareil locomoteur','M46.84'),
('autre specified inflammatory spondylopathies, thoracolumbar region','Other specified inflammatory spondylopathies, thoracolumbar region','Maladies de l''appareil locomoteur','M46.85'),
('autre specified inflammatory spondylopathies, lumbar region','Other specified inflammatory spondylopathies, lumbar region','Maladies de l''appareil locomoteur','M46.86'),
('autre specified inflammatory spondylopathies, lumbosacral region','Other specified inflammatory spondylopathies, lumbosacral region','Maladies de l''appareil locomoteur','M46.87'),
('autre specified inflammatory spondylopathies, sacral and sacrococcygeal region','Other specified inflammatory spondylopathies, sacral and sacrococcygeal region','Maladies de l''appareil locomoteur','M46.88'),
('autre specified inflammatory spondylopathies, multiple sites in spine','Other specified inflammatory spondylopathies, multiple sites in spine','Maladies de l''appareil locomoteur','M46.89'),
('non spécifié inflammatory spondylopathy, site non spécifié','Unspecified inflammatory spondylopathy, site unspecified','Maladies de l''appareil locomoteur','M46.90'),
('non spécifié inflammatory spondylopathy, occipito-atlanto-axial region','Unspecified inflammatory spondylopathy, occipito-atlanto-axial region','Maladies de l''appareil locomoteur','M46.91'),
('non spécifié inflammatory spondylopathy, cervical region','Unspecified inflammatory spondylopathy, cervical region','Maladies de l''appareil locomoteur','M46.92'),
('non spécifié inflammatory spondylopathy, cervicothoracic region','Unspecified inflammatory spondylopathy, cervicothoracic region','Maladies de l''appareil locomoteur','M46.93'),
('non spécifié inflammatory spondylopathy, thoracic region','Unspecified inflammatory spondylopathy, thoracic region','Maladies de l''appareil locomoteur','M46.94'),
('non spécifié inflammatory spondylopathy, thoracolumbar region','Unspecified inflammatory spondylopathy, thoracolumbar region','Maladies de l''appareil locomoteur','M46.95'),
('non spécifié inflammatory spondylopathy, lumbar region','Unspecified inflammatory spondylopathy, lumbar region','Maladies de l''appareil locomoteur','M46.96'),
('non spécifié inflammatory spondylopathy, lumbosacral region','Unspecified inflammatory spondylopathy, lumbosacral region','Maladies de l''appareil locomoteur','M46.97'),
('non spécifié inflammatory spondylopathy, sacral and sacrococcygeal region','Unspecified inflammatory spondylopathy, sacral and sacrococcygeal region','Maladies de l''appareil locomoteur','M46.98'),
('non spécifié inflammatory spondylopathy, multiple sites in spine','Unspecified inflammatory spondylopathy, multiple sites in spine','Maladies de l''appareil locomoteur','M46.99'),
('Anterior spinal artery compression syndromes, occipito-atlanto-axial region','Anterior spinal artery compression syndromes, occipito-atlanto-axial region','Maladies de l''appareil locomoteur','M47.011'),
('Anterior spinal artery compression syndromes, cervical region','Anterior spinal artery compression syndromes, cervical region','Maladies de l''appareil locomoteur','M47.012'),
('Anterior spinal artery compression syndromes, cervicothoracic region','Anterior spinal artery compression syndromes, cervicothoracic region','Maladies de l''appareil locomoteur','M47.013'),
('Anterior spinal artery compression syndromes, thoracic region','Anterior spinal artery compression syndromes, thoracic region','Maladies de l''appareil locomoteur','M47.014'),
('Anterior spinal artery compression syndromes, thoracolumbar region','Anterior spinal artery compression syndromes, thoracolumbar region','Maladies de l''appareil locomoteur','M47.015'),
('Anterior spinal artery compression syndromes, lumbar region','Anterior spinal artery compression syndromes, lumbar region','Maladies de l''appareil locomoteur','M47.016'),
('Anterior spinal artery compression syndromes, site non spécifié','Anterior spinal artery compression syndromes, site unspecified','Maladies de l''appareil locomoteur','M47.019'),
('Vertebral artery compression syndromes, occipito-atlanto-axial region','Vertebral artery compression syndromes, occipito-atlanto-axial region','Maladies de l''appareil locomoteur','M47.021'),
('Vertebral artery compression syndromes, cervical region','Vertebral artery compression syndromes, cervical region','Maladies de l''appareil locomoteur','M47.022'),
('Vertebral artery compression syndromes, site non spécifié','Vertebral artery compression syndromes, site unspecified','Maladies de l''appareil locomoteur','M47.029'),
('autre spondylosis with myelopathy, site non spécifié','Other spondylosis with myelopathy, site unspecified','Maladies de l''appareil locomoteur','M47.10'),
('autre spondylosis with myelopathy, occipito-atlanto-axial region','Other spondylosis with myelopathy, occipito-atlanto-axial region','Maladies de l''appareil locomoteur','M47.11'),
('autre spondylosis with myelopathy, cervical region','Other spondylosis with myelopathy, cervical region','Maladies de l''appareil locomoteur','M47.12'),
('autre spondylosis with myelopathy, cervicothoracic region','Other spondylosis with myelopathy, cervicothoracic region','Maladies de l''appareil locomoteur','M47.13'),
('autre spondylosis with myelopathy, thoracic region','Other spondylosis with myelopathy, thoracic region','Maladies de l''appareil locomoteur','M47.14'),
('autre spondylosis with myelopathy, thoracolumbar region','Other spondylosis with myelopathy, thoracolumbar region','Maladies de l''appareil locomoteur','M47.15'),
('autre spondylosis with myelopathy, lumbar region','Other spondylosis with myelopathy, lumbar region','Maladies de l''appareil locomoteur','M47.16'),
('autre spondylosis with radiculopathy, site non spécifié','Other spondylosis with radiculopathy, site unspecified','Maladies de l''appareil locomoteur','M47.20'),
('autre spondylosis with radiculopathy, occipito-atlanto-axial region','Other spondylosis with radiculopathy, occipito-atlanto-axial region','Maladies de l''appareil locomoteur','M47.21')
ON CONFLICT (nom_fr) DO NOTHING;
