-- icd10v2_batch_028.sql (80 rows)
INSERT INTO pathologies (nom_fr, nom_en, categorie, icd10_code)
VALUES
('Diffuse follicle center lymphoma, lymph nodes of multiple sites','Diffuse follicle center lymphoma, lymph nodes of multiple sites','Tumeurs malignes','C82.58'),
('Diffuse follicle center lymphoma, extranodal and solid organ sites','Diffuse follicle center lymphoma, extranodal and solid organ sites','Tumeurs malignes','C82.59'),
('Diffuse follicle center lymphoma, in remission','Diffuse follicle center lymphoma, in remission','Tumeurs malignes','C82.5A'),
('Cutaneous follicle center lymphoma, non spécifié site','Cutaneous follicle center lymphoma, unspecified site','Tumeurs malignes','C82.60'),
('Cutaneous follicle center lymphoma, lymph nodes of head, face, and neck','Cutaneous follicle center lymphoma, lymph nodes of head, face, and neck','Tumeurs malignes','C82.61'),
('Cutaneous follicle center lymphoma, intrathoracic lymph nodes','Cutaneous follicle center lymphoma, intrathoracic lymph nodes','Tumeurs malignes','C82.62'),
('Cutaneous follicle center lymphoma, intra-abdominal lymph nodes','Cutaneous follicle center lymphoma, intra-abdominal lymph nodes','Tumeurs malignes','C82.63'),
('Cutaneous follicle center lymphoma, lymph nodes of axilla and upper limb','Cutaneous follicle center lymphoma, lymph nodes of axilla and upper limb','Tumeurs malignes','C82.64'),
('Cutaneous follicle center lymphoma, lymph nodes of inguinal region and lower limb','Cutaneous follicle center lymphoma, lymph nodes of inguinal region and lower limb','Tumeurs malignes','C82.65'),
('Cutaneous follicle center lymphoma, intrapelvic lymph nodes','Cutaneous follicle center lymphoma, intrapelvic lymph nodes','Tumeurs malignes','C82.66'),
('Cutaneous follicle center lymphoma, spleen','Cutaneous follicle center lymphoma, spleen','Tumeurs malignes','C82.67'),
('Cutaneous follicle center lymphoma, lymph nodes of multiple sites','Cutaneous follicle center lymphoma, lymph nodes of multiple sites','Tumeurs malignes','C82.68'),
('Cutaneous follicle center lymphoma, extranodal and solid organ sites','Cutaneous follicle center lymphoma, extranodal and solid organ sites','Tumeurs malignes','C82.69'),
('Cutaneous follicle center lymphoma, in remission','Cutaneous follicle center lymphoma, in remission','Tumeurs malignes','C82.6A'),
('autre types of follicular lymphoma, non spécifié site','Other types of follicular lymphoma, unspecified site','Tumeurs malignes','C82.80'),
('autre types of follicular lymphoma, lymph nodes of head, face, and neck','Other types of follicular lymphoma, lymph nodes of head, face, and neck','Tumeurs malignes','C82.81'),
('autre types of follicular lymphoma, intrathoracic lymph nodes','Other types of follicular lymphoma, intrathoracic lymph nodes','Tumeurs malignes','C82.82'),
('autre types of follicular lymphoma, intra-abdominal lymph nodes','Other types of follicular lymphoma, intra-abdominal lymph nodes','Tumeurs malignes','C82.83'),
('autre types of follicular lymphoma, lymph nodes of axilla and upper limb','Other types of follicular lymphoma, lymph nodes of axilla and upper limb','Tumeurs malignes','C82.84'),
('autre types of follicular lymphoma, lymph nodes of inguinal region and lower limb','Other types of follicular lymphoma, lymph nodes of inguinal region and lower limb','Tumeurs malignes','C82.85'),
('autre types of follicular lymphoma, intrapelvic lymph nodes','Other types of follicular lymphoma, intrapelvic lymph nodes','Tumeurs malignes','C82.86'),
('autre types of follicular lymphoma, spleen','Other types of follicular lymphoma, spleen','Tumeurs malignes','C82.87'),
('autre types of follicular lymphoma, lymph nodes of multiple sites','Other types of follicular lymphoma, lymph nodes of multiple sites','Tumeurs malignes','C82.88'),
('autre types of follicular lymphoma, extranodal and solid organ sites','Other types of follicular lymphoma, extranodal and solid organ sites','Tumeurs malignes','C82.89'),
('autre types of follicular lymphoma, in remission','Other types of follicular lymphoma, in remission','Tumeurs malignes','C82.8A'),
('Follicular lymphoma, non spécifié, non spécifié site','Follicular lymphoma, unspecified, unspecified site','Tumeurs malignes','C82.90'),
('Follicular lymphoma, non spécifié, lymph nodes of head, face, and neck','Follicular lymphoma, unspecified, lymph nodes of head, face, and neck','Tumeurs malignes','C82.91'),
('Follicular lymphoma, non spécifié, intrathoracic lymph nodes','Follicular lymphoma, unspecified, intrathoracic lymph nodes','Tumeurs malignes','C82.92'),
('Follicular lymphoma, non spécifié, intra-abdominal lymph nodes','Follicular lymphoma, unspecified, intra-abdominal lymph nodes','Tumeurs malignes','C82.93'),
('Follicular lymphoma, non spécifié, lymph nodes of axilla and upper limb','Follicular lymphoma, unspecified, lymph nodes of axilla and upper limb','Tumeurs malignes','C82.94'),
('Follicular lymphoma, non spécifié, lymph nodes of inguinal region and lower limb','Follicular lymphoma, unspecified, lymph nodes of inguinal region and lower limb','Tumeurs malignes','C82.95'),
('Follicular lymphoma, non spécifié, intrapelvic lymph nodes','Follicular lymphoma, unspecified, intrapelvic lymph nodes','Tumeurs malignes','C82.96'),
('Follicular lymphoma, non spécifié, spleen','Follicular lymphoma, unspecified, spleen','Tumeurs malignes','C82.97'),
('Follicular lymphoma, non spécifié, lymph nodes of multiple sites','Follicular lymphoma, unspecified, lymph nodes of multiple sites','Tumeurs malignes','C82.98'),
('Follicular lymphoma, non spécifié, extranodal and solid organ sites','Follicular lymphoma, unspecified, extranodal and solid organ sites','Tumeurs malignes','C82.99'),
('Follicular lymphoma, non spécifié, in remission','Follicular lymphoma, unspecified, in remission','Tumeurs malignes','C82.9A'),
('Small cell B-cell lymphoma, non spécifié site','Small cell B-cell lymphoma, unspecified site','Tumeurs malignes','C83.00'),
('Small cell B-cell lymphoma, lymph nodes of head, face, and neck','Small cell B-cell lymphoma, lymph nodes of head, face, and neck','Tumeurs malignes','C83.01'),
('Small cell B-cell lymphoma, intrathoracic lymph nodes','Small cell B-cell lymphoma, intrathoracic lymph nodes','Tumeurs malignes','C83.02'),
('Small cell B-cell lymphoma, intra-abdominal lymph nodes','Small cell B-cell lymphoma, intra-abdominal lymph nodes','Tumeurs malignes','C83.03'),
('Small cell B-cell lymphoma, lymph nodes of axilla and upper limb','Small cell B-cell lymphoma, lymph nodes of axilla and upper limb','Tumeurs malignes','C83.04'),
('Small cell B-cell lymphoma, lymph nodes of inguinal region and lower limb','Small cell B-cell lymphoma, lymph nodes of inguinal region and lower limb','Tumeurs malignes','C83.05'),
('Small cell B-cell lymphoma, intrapelvic lymph nodes','Small cell B-cell lymphoma, intrapelvic lymph nodes','Tumeurs malignes','C83.06'),
('Small cell B-cell lymphoma, spleen','Small cell B-cell lymphoma, spleen','Tumeurs malignes','C83.07'),
('Small cell B-cell lymphoma, lymph nodes of multiple sites','Small cell B-cell lymphoma, lymph nodes of multiple sites','Tumeurs malignes','C83.08'),
('Small cell B-cell lymphoma, extranodal and solid organ sites','Small cell B-cell lymphoma, extranodal and solid organ sites','Tumeurs malignes','C83.09'),
('Small cell B-cell lymphoma, in remission','Small cell B-cell lymphoma, in remission','Tumeurs malignes','C83.0A'),
('Mantle cell lymphoma, non spécifié site','Mantle cell lymphoma, unspecified site','Tumeurs malignes','C83.10'),
('Mantle cell lymphoma, lymph nodes of head, face, and neck','Mantle cell lymphoma, lymph nodes of head, face, and neck','Tumeurs malignes','C83.11'),
('Mantle cell lymphoma, intrathoracic lymph nodes','Mantle cell lymphoma, intrathoracic lymph nodes','Tumeurs malignes','C83.12'),
('Mantle cell lymphoma, intra-abdominal lymph nodes','Mantle cell lymphoma, intra-abdominal lymph nodes','Tumeurs malignes','C83.13'),
('Mantle cell lymphoma, lymph nodes of axilla and upper limb','Mantle cell lymphoma, lymph nodes of axilla and upper limb','Tumeurs malignes','C83.14'),
('Mantle cell lymphoma, lymph nodes of inguinal region and lower limb','Mantle cell lymphoma, lymph nodes of inguinal region and lower limb','Tumeurs malignes','C83.15'),
('Mantle cell lymphoma, intrapelvic lymph nodes','Mantle cell lymphoma, intrapelvic lymph nodes','Tumeurs malignes','C83.16'),
('Mantle cell lymphoma, spleen','Mantle cell lymphoma, spleen','Tumeurs malignes','C83.17'),
('Mantle cell lymphoma, lymph nodes of multiple sites','Mantle cell lymphoma, lymph nodes of multiple sites','Tumeurs malignes','C83.18'),
('Mantle cell lymphoma, extranodal and solid organ sites','Mantle cell lymphoma, extranodal and solid organ sites','Tumeurs malignes','C83.19'),
('Mantle cell lymphoma, in remission','Mantle cell lymphoma, in remission','Tumeurs malignes','C83.1A'),
('Diffuse large B-cell lymphoma, non spécifié site','Diffuse large B-cell lymphoma, unspecified site','Tumeurs malignes','C83.30'),
('Diffuse large B-cell lymphoma, lymph nodes of head, face, and neck','Diffuse large B-cell lymphoma, lymph nodes of head, face, and neck','Tumeurs malignes','C83.31'),
('Diffuse large B-cell lymphoma, intrathoracic lymph nodes','Diffuse large B-cell lymphoma, intrathoracic lymph nodes','Tumeurs malignes','C83.32'),
('Diffuse large B-cell lymphoma, intra-abdominal lymph nodes','Diffuse large B-cell lymphoma, intra-abdominal lymph nodes','Tumeurs malignes','C83.33'),
('Diffuse large B-cell lymphoma, lymph nodes of axilla and upper limb','Diffuse large B-cell lymphoma, lymph nodes of axilla and upper limb','Tumeurs malignes','C83.34'),
('Diffuse large B-cell lymphoma, lymph nodes of inguinal region and lower limb','Diffuse large B-cell lymphoma, lymph nodes of inguinal region and lower limb','Tumeurs malignes','C83.35'),
('Diffuse large B-cell lymphoma, intrapelvic lymph nodes','Diffuse large B-cell lymphoma, intrapelvic lymph nodes','Tumeurs malignes','C83.36'),
('Diffuse large B-cell lymphoma, spleen','Diffuse large B-cell lymphoma, spleen','Tumeurs malignes','C83.37'),
('Diffuse large B-cell lymphoma, lymph nodes of multiple sites','Diffuse large B-cell lymphoma, lymph nodes of multiple sites','Tumeurs malignes','C83.38'),
('primitif central nervous system lymphoma','Primary central nervous system lymphoma','Tumeurs malignes','C83.390'),
('Diffuse large B-cell lymphoma of autre extranodal and solid organ sites','Diffuse large B-cell lymphoma of other extranodal and solid organ sites','Tumeurs malignes','C83.398'),
('Diffuse large B-cell lymphoma, in remission','Diffuse large B-cell lymphoma, in remission','Tumeurs malignes','C83.3A'),
('Lymphoblastic (diffuse) lymphoma, non spécifié site','Lymphoblastic (diffuse) lymphoma, unspecified site','Tumeurs malignes','C83.50'),
('Lymphoblastic (diffuse) lymphoma, lymph nodes of head, face, and neck','Lymphoblastic (diffuse) lymphoma, lymph nodes of head, face, and neck','Tumeurs malignes','C83.51'),
('Lymphoblastic (diffuse) lymphoma, intrathoracic lymph nodes','Lymphoblastic (diffuse) lymphoma, intrathoracic lymph nodes','Tumeurs malignes','C83.52'),
('Lymphoblastic (diffuse) lymphoma, intra-abdominal lymph nodes','Lymphoblastic (diffuse) lymphoma, intra-abdominal lymph nodes','Tumeurs malignes','C83.53'),
('Lymphoblastic (diffuse) lymphoma, lymph nodes of axilla and upper limb','Lymphoblastic (diffuse) lymphoma, lymph nodes of axilla and upper limb','Tumeurs malignes','C83.54'),
('Lymphoblastic (diffuse) lymphoma, lymph nodes of inguinal region and lower limb','Lymphoblastic (diffuse) lymphoma, lymph nodes of inguinal region and lower limb','Tumeurs malignes','C83.55'),
('Lymphoblastic (diffuse) lymphoma, intrapelvic lymph nodes','Lymphoblastic (diffuse) lymphoma, intrapelvic lymph nodes','Tumeurs malignes','C83.56'),
('Lymphoblastic (diffuse) lymphoma, spleen','Lymphoblastic (diffuse) lymphoma, spleen','Tumeurs malignes','C83.57'),
('Lymphoblastic (diffuse) lymphoma, lymph nodes of multiple sites','Lymphoblastic (diffuse) lymphoma, lymph nodes of multiple sites','Tumeurs malignes','C83.58'),
('Lymphoblastic (diffuse) lymphoma, extranodal and solid organ sites','Lymphoblastic (diffuse) lymphoma, extranodal and solid organ sites','Tumeurs malignes','C83.59')
ON CONFLICT (nom_fr) DO NOTHING;
