-- icd10v2_batch_234.sql (80 rows)
INSERT INTO pathologies (nom_fr, nom_en, categorie, icd10_code)
VALUES
('Maternal care for (suspected) chromosomal abnormality in fetus, Turner syndrome, fetus 5','Maternal care for (suspected) chromosomal abnormality in fetus, Turner Syndrome, fetus 5','Grossesse, accouchement et puerpéralité','O35.14X5'),
('Maternal care for (suspected) chromosomal abnormality in fetus, Turner syndrome, autre fetus','Maternal care for (suspected) chromosomal abnormality in fetus, Turner Syndrome, other fetus','Grossesse, accouchement et puerpéralité','O35.14X9'),
('Maternal care for (suspected) chromosomal abnormality in fetus, sex chromosome abnormality, not applicable or non spécifié','Maternal care for (suspected) chromosomal abnormality in fetus, sex chromosome abnormality, not applicable or unspecified','Grossesse, accouchement et puerpéralité','O35.15X0'),
('Maternal care for (suspected) chromosomal abnormality in fetus, sex chromosome abnormality, fetus 1','Maternal care for (suspected) chromosomal abnormality in fetus, sex chromosome abnormality, fetus 1','Grossesse, accouchement et puerpéralité','O35.15X1'),
('Maternal care for (suspected) chromosomal abnormality in fetus, sex chromosome abnormality, fetus 2','Maternal care for (suspected) chromosomal abnormality in fetus, sex chromosome abnormality, fetus 2','Grossesse, accouchement et puerpéralité','O35.15X2'),
('Maternal care for (suspected) chromosomal abnormality in fetus, sex chromosome abnormality, fetus 3','Maternal care for (suspected) chromosomal abnormality in fetus, sex chromosome abnormality, fetus 3','Grossesse, accouchement et puerpéralité','O35.15X3'),
('Maternal care for (suspected) chromosomal abnormality in fetus, sex chromosome abnormality, fetus 4','Maternal care for (suspected) chromosomal abnormality in fetus, sex chromosome abnormality, fetus 4','Grossesse, accouchement et puerpéralité','O35.15X4'),
('Maternal care for (suspected) chromosomal abnormality in fetus, sex chromosome abnormality, fetus 5','Maternal care for (suspected) chromosomal abnormality in fetus, sex chromosome abnormality, fetus 5','Grossesse, accouchement et puerpéralité','O35.15X5'),
('Maternal care for (suspected) chromosomal abnormality in fetus, sex chromosome abnormality, autre fetus','Maternal care for (suspected) chromosomal abnormality in fetus, sex chromosome abnormality, other fetus','Grossesse, accouchement et puerpéralité','O35.15X9'),
('Maternal care for (suspected) chromosomal abnormality in fetus, autre chromosomal abnormality, not applicable or non spécifié','Maternal care for (suspected) chromosomal abnormality in fetus, other chromosomal abnormality, not applicable or unspecified','Grossesse, accouchement et puerpéralité','O35.19X0'),
('Maternal care for (suspected) chromosomal abnormality in fetus, autre chromosomal abnormality, fetus 1','Maternal care for (suspected) chromosomal abnormality in fetus, other chromosomal abnormality, fetus 1','Grossesse, accouchement et puerpéralité','O35.19X1'),
('Maternal care for (suspected) chromosomal abnormality in fetus, autre chromosomal abnormality, fetus 2','Maternal care for (suspected) chromosomal abnormality in fetus, other chromosomal abnormality, fetus 2','Grossesse, accouchement et puerpéralité','O35.19X2'),
('Maternal care for (suspected) chromosomal abnormality in fetus, autre chromosomal abnormality, fetus 3','Maternal care for (suspected) chromosomal abnormality in fetus, other chromosomal abnormality, fetus 3','Grossesse, accouchement et puerpéralité','O35.19X3'),
('Maternal care for (suspected) chromosomal abnormality in fetus, autre chromosomal abnormality, fetus 4','Maternal care for (suspected) chromosomal abnormality in fetus, other chromosomal abnormality, fetus 4','Grossesse, accouchement et puerpéralité','O35.19X4'),
('Maternal care for (suspected) chromosomal abnormality in fetus, autre chromosomal abnormality, fetus 5','Maternal care for (suspected) chromosomal abnormality in fetus, other chromosomal abnormality, fetus 5','Grossesse, accouchement et puerpéralité','O35.19X5'),
('Maternal care for (suspected) chromosomal abnormality in fetus, autre chromosomal abnormality, autre fetus','Maternal care for (suspected) chromosomal abnormality in fetus, other chromosomal abnormality, other fetus','Grossesse, accouchement et puerpéralité','O35.19X9'),
('Maternal care for autre (suspected) fetal abnormality and damage, fetal facial anomalies, not applicable or non spécifié','Maternal care for other (suspected) fetal abnormality and damage, fetal facial anomalies, not applicable or unspecified','Grossesse, accouchement et puerpéralité','O35.AXX0'),
('Maternal care for autre (suspected) fetal abnormality and damage, fetal facial anomalies, fetus 1','Maternal care for other (suspected) fetal abnormality and damage, fetal facial anomalies, fetus 1','Grossesse, accouchement et puerpéralité','O35.AXX1'),
('Maternal care for autre (suspected) fetal abnormality and damage, fetal facial anomalies, fetus 2','Maternal care for other (suspected) fetal abnormality and damage, fetal facial anomalies, fetus 2','Grossesse, accouchement et puerpéralité','O35.AXX2'),
('Maternal care for autre (suspected) fetal abnormality and damage, fetal facial anomalies, fetus 3','Maternal care for other (suspected) fetal abnormality and damage, fetal facial anomalies, fetus 3','Grossesse, accouchement et puerpéralité','O35.AXX3'),
('Maternal care for autre (suspected) fetal abnormality and damage, fetal facial anomalies, fetus 4','Maternal care for other (suspected) fetal abnormality and damage, fetal facial anomalies, fetus 4','Grossesse, accouchement et puerpéralité','O35.AXX4'),
('Maternal care for autre (suspected) fetal abnormality and damage, fetal facial anomalies, fetus 5','Maternal care for other (suspected) fetal abnormality and damage, fetal facial anomalies, fetus 5','Grossesse, accouchement et puerpéralité','O35.AXX5'),
('Maternal care for autre (suspected) fetal abnormality and damage, fetal facial anomalies, autre fetus','Maternal care for other (suspected) fetal abnormality and damage, fetal facial anomalies, other fetus','Grossesse, accouchement et puerpéralité','O35.AXX9'),
('Maternal care for autre (suspected) fetal abnormality and damage, fetal cardiac anomalies, not applicable or non spécifié','Maternal care for other (suspected) fetal abnormality and damage, fetal cardiac anomalies, not applicable or unspecified','Grossesse, accouchement et puerpéralité','O35.BXX0'),
('Maternal care for autre (suspected) fetal abnormality and damage, fetal cardiac anomalies, fetus 1','Maternal care for other (suspected) fetal abnormality and damage, fetal cardiac anomalies, fetus 1','Grossesse, accouchement et puerpéralité','O35.BXX1'),
('Maternal care for autre (suspected) fetal abnormality and damage, fetal cardiac anomalies, fetus 2','Maternal care for other (suspected) fetal abnormality and damage, fetal cardiac anomalies, fetus 2','Grossesse, accouchement et puerpéralité','O35.BXX2'),
('Polyhydramnios, first trimester, not applicable or non spécifié','Polyhydramnios, first trimester, not applicable or unspecified','Grossesse, accouchement et puerpéralité','O40.1XX0'),
('Polyhydramnios, first trimester, fetus 1','Polyhydramnios, first trimester, fetus 1','Grossesse, accouchement et puerpéralité','O40.1XX1'),
('Polyhydramnios, first trimester, fetus 2','Polyhydramnios, first trimester, fetus 2','Grossesse, accouchement et puerpéralité','O40.1XX2'),
('Polyhydramnios, first trimester, fetus 3','Polyhydramnios, first trimester, fetus 3','Grossesse, accouchement et puerpéralité','O40.1XX3'),
('Polyhydramnios, first trimester, fetus 4','Polyhydramnios, first trimester, fetus 4','Grossesse, accouchement et puerpéralité','O40.1XX4'),
('Polyhydramnios, first trimester, fetus 5','Polyhydramnios, first trimester, fetus 5','Grossesse, accouchement et puerpéralité','O40.1XX5'),
('Polyhydramnios, first trimester, autre fetus','Polyhydramnios, first trimester, other fetus','Grossesse, accouchement et puerpéralité','O40.1XX9'),
('Polyhydramnios, second trimester, not applicable or non spécifié','Polyhydramnios, second trimester, not applicable or unspecified','Grossesse, accouchement et puerpéralité','O40.2XX0'),
('Polyhydramnios, second trimester, fetus 1','Polyhydramnios, second trimester, fetus 1','Grossesse, accouchement et puerpéralité','O40.2XX1'),
('Polyhydramnios, second trimester, fetus 2','Polyhydramnios, second trimester, fetus 2','Grossesse, accouchement et puerpéralité','O40.2XX2'),
('Polyhydramnios, second trimester, fetus 3','Polyhydramnios, second trimester, fetus 3','Grossesse, accouchement et puerpéralité','O40.2XX3'),
('Polyhydramnios, second trimester, fetus 4','Polyhydramnios, second trimester, fetus 4','Grossesse, accouchement et puerpéralité','O40.2XX4'),
('Polyhydramnios, second trimester, fetus 5','Polyhydramnios, second trimester, fetus 5','Grossesse, accouchement et puerpéralité','O40.2XX5'),
('Polyhydramnios, second trimester, autre fetus','Polyhydramnios, second trimester, other fetus','Grossesse, accouchement et puerpéralité','O40.2XX9'),
('Polyhydramnios, third trimester, not applicable or non spécifié','Polyhydramnios, third trimester, not applicable or unspecified','Grossesse, accouchement et puerpéralité','O40.3XX0'),
('Polyhydramnios, third trimester, fetus 1','Polyhydramnios, third trimester, fetus 1','Grossesse, accouchement et puerpéralité','O40.3XX1'),
('Polyhydramnios, third trimester, fetus 2','Polyhydramnios, third trimester, fetus 2','Grossesse, accouchement et puerpéralité','O40.3XX2'),
('Polyhydramnios, third trimester, fetus 3','Polyhydramnios, third trimester, fetus 3','Grossesse, accouchement et puerpéralité','O40.3XX3'),
('Polyhydramnios, third trimester, fetus 4','Polyhydramnios, third trimester, fetus 4','Grossesse, accouchement et puerpéralité','O40.3XX4'),
('Polyhydramnios, third trimester, fetus 5','Polyhydramnios, third trimester, fetus 5','Grossesse, accouchement et puerpéralité','O40.3XX5'),
('Polyhydramnios, third trimester, autre fetus','Polyhydramnios, third trimester, other fetus','Grossesse, accouchement et puerpéralité','O40.3XX9'),
('Polyhydramnios, non spécifié trimester, not applicable or non spécifié','Polyhydramnios, unspecified trimester, not applicable or unspecified','Grossesse, accouchement et puerpéralité','O40.9XX0'),
('Polyhydramnios, non spécifié trimester, fetus 1','Polyhydramnios, unspecified trimester, fetus 1','Grossesse, accouchement et puerpéralité','O40.9XX1'),
('Polyhydramnios, non spécifié trimester, fetus 2','Polyhydramnios, unspecified trimester, fetus 2','Grossesse, accouchement et puerpéralité','O40.9XX2'),
('Polyhydramnios, non spécifié trimester, fetus 3','Polyhydramnios, unspecified trimester, fetus 3','Grossesse, accouchement et puerpéralité','O40.9XX3'),
('Polyhydramnios, non spécifié trimester, fetus 4','Polyhydramnios, unspecified trimester, fetus 4','Grossesse, accouchement et puerpéralité','O40.9XX4'),
('Polyhydramnios, non spécifié trimester, fetus 5','Polyhydramnios, unspecified trimester, fetus 5','Grossesse, accouchement et puerpéralité','O40.9XX5'),
('Polyhydramnios, non spécifié trimester, autre fetus','Polyhydramnios, unspecified trimester, other fetus','Grossesse, accouchement et puerpéralité','O40.9XX9'),
('Oligohydramnios, non spécifié trimester, not applicable or non spécifié','Oligohydramnios, unspecified trimester, not applicable or unspecified','Grossesse, accouchement et puerpéralité','O41.00X0'),
('Oligohydramnios, non spécifié trimester, fetus 1','Oligohydramnios, unspecified trimester, fetus 1','Grossesse, accouchement et puerpéralité','O41.00X1'),
('Oligohydramnios, non spécifié trimester, fetus 2','Oligohydramnios, unspecified trimester, fetus 2','Grossesse, accouchement et puerpéralité','O41.00X2'),
('Oligohydramnios, non spécifié trimester, fetus 3','Oligohydramnios, unspecified trimester, fetus 3','Grossesse, accouchement et puerpéralité','O41.00X3'),
('Oligohydramnios, non spécifié trimester, fetus 4','Oligohydramnios, unspecified trimester, fetus 4','Grossesse, accouchement et puerpéralité','O41.00X4'),
('Oligohydramnios, non spécifié trimester, fetus 5','Oligohydramnios, unspecified trimester, fetus 5','Grossesse, accouchement et puerpéralité','O41.00X5'),
('Oligohydramnios, non spécifié trimester, autre fetus','Oligohydramnios, unspecified trimester, other fetus','Grossesse, accouchement et puerpéralité','O41.00X9'),
('Oligohydramnios, first trimester, not applicable or non spécifié','Oligohydramnios, first trimester, not applicable or unspecified','Grossesse, accouchement et puerpéralité','O41.01X0'),
('Oligohydramnios, first trimester, fetus 1','Oligohydramnios, first trimester, fetus 1','Grossesse, accouchement et puerpéralité','O41.01X1'),
('Oligohydramnios, first trimester, fetus 2','Oligohydramnios, first trimester, fetus 2','Grossesse, accouchement et puerpéralité','O41.01X2'),
('Oligohydramnios, first trimester, fetus 3','Oligohydramnios, first trimester, fetus 3','Grossesse, accouchement et puerpéralité','O41.01X3'),
('Oligohydramnios, first trimester, fetus 4','Oligohydramnios, first trimester, fetus 4','Grossesse, accouchement et puerpéralité','O41.01X4'),
('Oligohydramnios, first trimester, fetus 5','Oligohydramnios, first trimester, fetus 5','Grossesse, accouchement et puerpéralité','O41.01X5'),
('Oligohydramnios, first trimester, autre fetus','Oligohydramnios, first trimester, other fetus','Grossesse, accouchement et puerpéralité','O41.01X9'),
('Oligohydramnios, second trimester, not applicable or non spécifié','Oligohydramnios, second trimester, not applicable or unspecified','Grossesse, accouchement et puerpéralité','O41.02X0'),
('Oligohydramnios, second trimester, fetus 1','Oligohydramnios, second trimester, fetus 1','Grossesse, accouchement et puerpéralité','O41.02X1'),
('Oligohydramnios, second trimester, fetus 2','Oligohydramnios, second trimester, fetus 2','Grossesse, accouchement et puerpéralité','O41.02X2'),
('Oligohydramnios, second trimester, fetus 3','Oligohydramnios, second trimester, fetus 3','Grossesse, accouchement et puerpéralité','O41.02X3'),
('Oligohydramnios, second trimester, fetus 4','Oligohydramnios, second trimester, fetus 4','Grossesse, accouchement et puerpéralité','O41.02X4'),
('Oligohydramnios, second trimester, fetus 5','Oligohydramnios, second trimester, fetus 5','Grossesse, accouchement et puerpéralité','O41.02X5'),
('Oligohydramnios, second trimester, autre fetus','Oligohydramnios, second trimester, other fetus','Grossesse, accouchement et puerpéralité','O41.02X9'),
('Oligohydramnios, third trimester, not applicable or non spécifié','Oligohydramnios, third trimester, not applicable or unspecified','Grossesse, accouchement et puerpéralité','O41.03X0'),
('Oligohydramnios, third trimester, fetus 1','Oligohydramnios, third trimester, fetus 1','Grossesse, accouchement et puerpéralité','O41.03X1'),
('Oligohydramnios, third trimester, fetus 2','Oligohydramnios, third trimester, fetus 2','Grossesse, accouchement et puerpéralité','O41.03X2'),
('Oligohydramnios, third trimester, fetus 3','Oligohydramnios, third trimester, fetus 3','Grossesse, accouchement et puerpéralité','O41.03X3'),
('Oligohydramnios, third trimester, fetus 4','Oligohydramnios, third trimester, fetus 4','Grossesse, accouchement et puerpéralité','O41.03X4')
ON CONFLICT (nom_fr) DO NOTHING;
