-- icd10v2_batch_060.sql (80 rows)
INSERT INTO pathologies (nom_fr, nom_en, categorie, icd10_code)
VALUES
('autre stimulant dependence with withdrawal','Other stimulant dependence with withdrawal','Troubles mentaux et du comportement','F15.23'),
('autre stimulant dependence with stimulant-induced mood trouble','Other stimulant dependence with stimulant-induced mood disorder','Troubles mentaux et du comportement','F15.24'),
('autre stimulant dependence with stimulant-induced psychotic trouble with delusions','Other stimulant dependence with stimulant-induced psychotic disorder with delusions','Troubles mentaux et du comportement','F15.250'),
('autre stimulant dependence with stimulant-induced psychotic trouble with hallucinations','Other stimulant dependence with stimulant-induced psychotic disorder with hallucinations','Troubles mentaux et du comportement','F15.251'),
('autre stimulant dependence with stimulant-induced psychotic trouble, non spécifié','Other stimulant dependence with stimulant-induced psychotic disorder, unspecified','Troubles mentaux et du comportement','F15.259'),
('autre stimulant dependence with stimulant-induced anxiety trouble','Other stimulant dependence with stimulant-induced anxiety disorder','Troubles mentaux et du comportement','F15.280'),
('autre stimulant dependence with stimulant-induced sexual dysfunction','Other stimulant dependence with stimulant-induced sexual dysfunction','Troubles mentaux et du comportement','F15.281'),
('autre stimulant dependence with stimulant-induced sleep trouble','Other stimulant dependence with stimulant-induced sleep disorder','Troubles mentaux et du comportement','F15.282'),
('autre stimulant dependence with autre stimulant-induced trouble','Other stimulant dependence with other stimulant-induced disorder','Troubles mentaux et du comportement','F15.288'),
('autre stimulant dependence with non spécifié stimulant-induced trouble','Other stimulant dependence with unspecified stimulant-induced disorder','Troubles mentaux et du comportement','F15.29'),
('autre stimulant use, non spécifié, uncomplicated','Other stimulant use, unspecified, uncomplicated','Troubles mentaux et du comportement','F15.90'),
('autre stimulant use, non spécifié, in remission','Other stimulant use, unspecified, in remission','Troubles mentaux et du comportement','F15.91'),
('autre stimulant use, non spécifié with intoxication, uncomplicated','Other stimulant use, unspecified with intoxication, uncomplicated','Troubles mentaux et du comportement','F15.920'),
('autre stimulant use, non spécifié with intoxication delirium','Other stimulant use, unspecified with intoxication delirium','Troubles mentaux et du comportement','F15.921'),
('autre stimulant use, non spécifié with intoxication with perceptual disturbance','Other stimulant use, unspecified with intoxication with perceptual disturbance','Troubles mentaux et du comportement','F15.922'),
('autre stimulant use, non spécifié with intoxication, non spécifié','Other stimulant use, unspecified with intoxication, unspecified','Troubles mentaux et du comportement','F15.929'),
('autre stimulant use, non spécifié with withdrawal','Other stimulant use, unspecified with withdrawal','Troubles mentaux et du comportement','F15.93'),
('autre stimulant use, non spécifié with stimulant-induced mood trouble','Other stimulant use, unspecified with stimulant-induced mood disorder','Troubles mentaux et du comportement','F15.94'),
('autre stimulant use, non spécifié with stimulant-induced psychotic trouble with delusions','Other stimulant use, unspecified with stimulant-induced psychotic disorder with delusions','Troubles mentaux et du comportement','F15.950'),
('autre stimulant use, non spécifié with stimulant-induced psychotic trouble with hallucinations','Other stimulant use, unspecified with stimulant-induced psychotic disorder with hallucinations','Troubles mentaux et du comportement','F15.951'),
('autre stimulant use, non spécifié with stimulant-induced psychotic trouble, non spécifié','Other stimulant use, unspecified with stimulant-induced psychotic disorder, unspecified','Troubles mentaux et du comportement','F15.959'),
('autre stimulant use, non spécifié with stimulant-induced anxiety trouble','Other stimulant use, unspecified with stimulant-induced anxiety disorder','Troubles mentaux et du comportement','F15.980'),
('autre stimulant use, non spécifié with stimulant-induced sexual dysfunction','Other stimulant use, unspecified with stimulant-induced sexual dysfunction','Troubles mentaux et du comportement','F15.981'),
('autre stimulant use, non spécifié with stimulant-induced sleep trouble','Other stimulant use, unspecified with stimulant-induced sleep disorder','Troubles mentaux et du comportement','F15.982'),
('autre stimulant use, non spécifié with autre stimulant-induced trouble','Other stimulant use, unspecified with other stimulant-induced disorder','Troubles mentaux et du comportement','F15.988'),
('autre stimulant use, non spécifié with non spécifié stimulant-induced trouble','Other stimulant use, unspecified with unspecified stimulant-induced disorder','Troubles mentaux et du comportement','F15.99'),
('Hallucinogen abuse, uncomplicated','Hallucinogen abuse, uncomplicated','Troubles mentaux et du comportement','F16.10'),
('Hallucinogen abuse, in remission','Hallucinogen abuse, in remission','Troubles mentaux et du comportement','F16.11'),
('Hallucinogen abuse with intoxication, uncomplicated','Hallucinogen abuse with intoxication, uncomplicated','Troubles mentaux et du comportement','F16.120'),
('Hallucinogen abuse with intoxication with delirium','Hallucinogen abuse with intoxication with delirium','Troubles mentaux et du comportement','F16.121'),
('Hallucinogen abuse with intoxication with perceptual disturbance','Hallucinogen abuse with intoxication with perceptual disturbance','Troubles mentaux et du comportement','F16.122'),
('Hallucinogen abuse with intoxication, non spécifié','Hallucinogen abuse with intoxication, unspecified','Troubles mentaux et du comportement','F16.129'),
('Hallucinogen abuse with hallucinogen-induced mood trouble','Hallucinogen abuse with hallucinogen-induced mood disorder','Troubles mentaux et du comportement','F16.14'),
('Hallucinogen abuse with hallucinogen-induced psychotic trouble with delusions','Hallucinogen abuse with hallucinogen-induced psychotic disorder with delusions','Troubles mentaux et du comportement','F16.150'),
('Hallucinogen abuse with hallucinogen-induced psychotic trouble with hallucinations','Hallucinogen abuse with hallucinogen-induced psychotic disorder with hallucinations','Troubles mentaux et du comportement','F16.151'),
('Hallucinogen abuse with hallucinogen-induced psychotic trouble, non spécifié','Hallucinogen abuse with hallucinogen-induced psychotic disorder, unspecified','Troubles mentaux et du comportement','F16.159'),
('Hallucinogen abuse with hallucinogen-induced anxiety trouble','Hallucinogen abuse with hallucinogen-induced anxiety disorder','Troubles mentaux et du comportement','F16.180'),
('Hallucinogen abuse with hallucinogen persisting perception trouble (flashbacks)','Hallucinogen abuse with hallucinogen persisting perception disorder (flashbacks)','Troubles mentaux et du comportement','F16.183'),
('Hallucinogen abuse with autre hallucinogen-induced trouble','Hallucinogen abuse with other hallucinogen-induced disorder','Troubles mentaux et du comportement','F16.188'),
('Hallucinogen abuse with non spécifié hallucinogen-induced trouble','Hallucinogen abuse with unspecified hallucinogen-induced disorder','Troubles mentaux et du comportement','F16.19'),
('Hallucinogen dependence, uncomplicated','Hallucinogen dependence, uncomplicated','Troubles mentaux et du comportement','F16.20'),
('Hallucinogen dependence, in remission','Hallucinogen dependence, in remission','Troubles mentaux et du comportement','F16.21'),
('Hallucinogen dependence with intoxication, uncomplicated','Hallucinogen dependence with intoxication, uncomplicated','Troubles mentaux et du comportement','F16.220'),
('Hallucinogen dependence with intoxication with delirium','Hallucinogen dependence with intoxication with delirium','Troubles mentaux et du comportement','F16.221'),
('Hallucinogen dependence with intoxication, non spécifié','Hallucinogen dependence with intoxication, unspecified','Troubles mentaux et du comportement','F16.229'),
('Hallucinogen dependence with hallucinogen-induced mood trouble','Hallucinogen dependence with hallucinogen-induced mood disorder','Troubles mentaux et du comportement','F16.24'),
('Hallucinogen dependence with hallucinogen-induced psychotic trouble with delusions','Hallucinogen dependence with hallucinogen-induced psychotic disorder with delusions','Troubles mentaux et du comportement','F16.250'),
('Hallucinogen dependence with hallucinogen-induced psychotic trouble with hallucinations','Hallucinogen dependence with hallucinogen-induced psychotic disorder with hallucinations','Troubles mentaux et du comportement','F16.251'),
('Hallucinogen dependence with hallucinogen-induced psychotic trouble, non spécifié','Hallucinogen dependence with hallucinogen-induced psychotic disorder, unspecified','Troubles mentaux et du comportement','F16.259'),
('Hallucinogen dependence with hallucinogen-induced anxiety trouble','Hallucinogen dependence with hallucinogen-induced anxiety disorder','Troubles mentaux et du comportement','F16.280'),
('Hallucinogen dependence with hallucinogen persisting perception trouble (flashbacks)','Hallucinogen dependence with hallucinogen persisting perception disorder (flashbacks)','Troubles mentaux et du comportement','F16.283'),
('Hallucinogen dependence with autre hallucinogen-induced trouble','Hallucinogen dependence with other hallucinogen-induced disorder','Troubles mentaux et du comportement','F16.288'),
('Hallucinogen dependence with non spécifié hallucinogen-induced trouble','Hallucinogen dependence with unspecified hallucinogen-induced disorder','Troubles mentaux et du comportement','F16.29'),
('Hallucinogen use, non spécifié, uncomplicated','Hallucinogen use, unspecified, uncomplicated','Troubles mentaux et du comportement','F16.90'),
('Hallucinogen use, non spécifié, in remission','Hallucinogen use, unspecified, in remission','Troubles mentaux et du comportement','F16.91'),
('Hallucinogen use, non spécifié with intoxication, uncomplicated','Hallucinogen use, unspecified with intoxication, uncomplicated','Troubles mentaux et du comportement','F16.920'),
('Hallucinogen use, non spécifié with intoxication with delirium','Hallucinogen use, unspecified with intoxication with delirium','Troubles mentaux et du comportement','F16.921'),
('Hallucinogen use, non spécifié with intoxication, non spécifié','Hallucinogen use, unspecified with intoxication, unspecified','Troubles mentaux et du comportement','F16.929'),
('Hallucinogen use, non spécifié with hallucinogen-induced mood trouble','Hallucinogen use, unspecified with hallucinogen-induced mood disorder','Troubles mentaux et du comportement','F16.94'),
('Hallucinogen use, non spécifié with hallucinogen-induced psychotic trouble with delusions','Hallucinogen use, unspecified with hallucinogen-induced psychotic disorder with delusions','Troubles mentaux et du comportement','F16.950'),
('Hallucinogen use, non spécifié with hallucinogen-induced psychotic trouble with hallucinations','Hallucinogen use, unspecified with hallucinogen-induced psychotic disorder with hallucinations','Troubles mentaux et du comportement','F16.951'),
('Hallucinogen use, non spécifié with hallucinogen-induced psychotic trouble, non spécifié','Hallucinogen use, unspecified with hallucinogen-induced psychotic disorder, unspecified','Troubles mentaux et du comportement','F16.959'),
('Hallucinogen use, non spécifié with hallucinogen-induced anxiety trouble','Hallucinogen use, unspecified with hallucinogen-induced anxiety disorder','Troubles mentaux et du comportement','F16.980'),
('Hallucinogen use, non spécifié with hallucinogen persisting perception trouble (flashbacks)','Hallucinogen use, unspecified with hallucinogen persisting perception disorder (flashbacks)','Troubles mentaux et du comportement','F16.983'),
('Hallucinogen use, non spécifié with autre hallucinogen-induced trouble','Hallucinogen use, unspecified with other hallucinogen-induced disorder','Troubles mentaux et du comportement','F16.988'),
('Hallucinogen use, non spécifié with non spécifié hallucinogen-induced trouble','Hallucinogen use, unspecified with unspecified hallucinogen-induced disorder','Troubles mentaux et du comportement','F16.99'),
('Nicotine dependence, non spécifié, uncomplicated','Nicotine dependence, unspecified, uncomplicated','Troubles mentaux et du comportement','F17.200'),
('Nicotine dependence, non spécifié, in remission','Nicotine dependence, unspecified, in remission','Troubles mentaux et du comportement','F17.201'),
('Nicotine dependence non spécifié, with withdrawal','Nicotine dependence unspecified, with withdrawal','Troubles mentaux et du comportement','F17.203'),
('Nicotine dependence, non spécifié, with autre nicotine-induced disorders','Nicotine dependence, unspecified, with other nicotine-induced disorders','Troubles mentaux et du comportement','F17.208'),
('Nicotine dependence, non spécifié, with non spécifié nicotine-induced disorders','Nicotine dependence, unspecified, with unspecified nicotine-induced disorders','Troubles mentaux et du comportement','F17.209'),
('Nicotine dependence, cigarettes, uncomplicated','Nicotine dependence, cigarettes, uncomplicated','Troubles mentaux et du comportement','F17.210'),
('Nicotine dependence, cigarettes, in remission','Nicotine dependence, cigarettes, in remission','Troubles mentaux et du comportement','F17.211'),
('Nicotine dependence, cigarettes, with withdrawal','Nicotine dependence, cigarettes, with withdrawal','Troubles mentaux et du comportement','F17.213'),
('Nicotine dependence, cigarettes, with autre nicotine-induced disorders','Nicotine dependence, cigarettes, with other nicotine-induced disorders','Troubles mentaux et du comportement','F17.218'),
('Nicotine dependence, cigarettes, with non spécifié nicotine-induced disorders','Nicotine dependence, cigarettes, with unspecified nicotine-induced disorders','Troubles mentaux et du comportement','F17.219'),
('Nicotine dependence, chewing tobacco, uncomplicated','Nicotine dependence, chewing tobacco, uncomplicated','Troubles mentaux et du comportement','F17.220'),
('Nicotine dependence, chewing tobacco, in remission','Nicotine dependence, chewing tobacco, in remission','Troubles mentaux et du comportement','F17.221'),
('Nicotine dependence, chewing tobacco, with withdrawal','Nicotine dependence, chewing tobacco, with withdrawal','Troubles mentaux et du comportement','F17.223'),
('Nicotine dependence, chewing tobacco, with autre nicotine-induced disorders','Nicotine dependence, chewing tobacco, with other nicotine-induced disorders','Troubles mentaux et du comportement','F17.228')
ON CONFLICT (nom_fr) DO NOTHING;
