-- icd10v2_batch_685.sql (80 rows)
INSERT INTO pathologies (nom_fr, nom_en, categorie, icd10_code)
VALUES
('Corrosion of first degree of non spécifié ankle, sequela','Corrosion of first degree of unspecified ankle, sequela','Traumatismes, empoisonnements et autres causes externes','T25.519S'),
('Corrosion of first degree of right foot, initial encounter','Corrosion of first degree of right foot, initial encounter','Traumatismes, empoisonnements et autres causes externes','T25.521A'),
('Corrosion of first degree of right foot, subsequent encounter','Corrosion of first degree of right foot, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T25.521D'),
('Corrosion of first degree of right foot, sequela','Corrosion of first degree of right foot, sequela','Traumatismes, empoisonnements et autres causes externes','T25.521S'),
('Corrosion of first degree of left foot, initial encounter','Corrosion of first degree of left foot, initial encounter','Traumatismes, empoisonnements et autres causes externes','T25.522A'),
('Corrosion of first degree of left foot, subsequent encounter','Corrosion of first degree of left foot, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T25.522D'),
('Corrosion of first degree of left foot, sequela','Corrosion of first degree of left foot, sequela','Traumatismes, empoisonnements et autres causes externes','T25.522S'),
('Corrosion of first degree of non spécifié foot, initial encounter','Corrosion of first degree of unspecified foot, initial encounter','Traumatismes, empoisonnements et autres causes externes','T25.529A'),
('Corrosion of first degree of non spécifié foot, subsequent encounter','Corrosion of first degree of unspecified foot, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T25.529D'),
('Corrosion of first degree of non spécifié foot, sequela','Corrosion of first degree of unspecified foot, sequela','Traumatismes, empoisonnements et autres causes externes','T25.529S'),
('Corrosion of first degree of right toe(s) (nail), initial encounter','Corrosion of first degree of right toe(s) (nail), initial encounter','Traumatismes, empoisonnements et autres causes externes','T25.531A'),
('Corrosion of first degree of right toe(s) (nail), subsequent encounter','Corrosion of first degree of right toe(s) (nail), subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T25.531D'),
('Corrosion of first degree of right toe(s) (nail), sequela','Corrosion of first degree of right toe(s) (nail), sequela','Traumatismes, empoisonnements et autres causes externes','T25.531S'),
('Corrosion of first degree of left toe(s) (nail), initial encounter','Corrosion of first degree of left toe(s) (nail), initial encounter','Traumatismes, empoisonnements et autres causes externes','T25.532A'),
('Corrosion of first degree of left toe(s) (nail), subsequent encounter','Corrosion of first degree of left toe(s) (nail), subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T25.532D'),
('Corrosion of first degree of left toe(s) (nail), sequela','Corrosion of first degree of left toe(s) (nail), sequela','Traumatismes, empoisonnements et autres causes externes','T25.532S'),
('Corrosion of first degree of non spécifié toe(s) (nail), initial encounter','Corrosion of first degree of unspecified toe(s) (nail), initial encounter','Traumatismes, empoisonnements et autres causes externes','T25.539A'),
('Corrosion of first degree of non spécifié toe(s) (nail), subsequent encounter','Corrosion of first degree of unspecified toe(s) (nail), subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T25.539D'),
('Corrosion of first degree of non spécifié toe(s) (nail), sequela','Corrosion of first degree of unspecified toe(s) (nail), sequela','Traumatismes, empoisonnements et autres causes externes','T25.539S'),
('Corrosion of first degree of multiple sites of right ankle and foot, initial encounter','Corrosion of first degree of multiple sites of right ankle and foot, initial encounter','Traumatismes, empoisonnements et autres causes externes','T25.591A'),
('Corrosion of first degree of multiple sites of right ankle and foot, subsequent encounter','Corrosion of first degree of multiple sites of right ankle and foot, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T25.591D'),
('Corrosion of first degree of multiple sites of right ankle and foot, sequela','Corrosion of first degree of multiple sites of right ankle and foot, sequela','Traumatismes, empoisonnements et autres causes externes','T25.591S'),
('Corrosion of first degree of multiple sites of left ankle and foot, initial encounter','Corrosion of first degree of multiple sites of left ankle and foot, initial encounter','Traumatismes, empoisonnements et autres causes externes','T25.592A'),
('Corrosion of first degree of multiple sites of left ankle and foot, subsequent encounter','Corrosion of first degree of multiple sites of left ankle and foot, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T25.592D'),
('Corrosion of first degree of multiple sites of left ankle and foot, sequela','Corrosion of first degree of multiple sites of left ankle and foot, sequela','Traumatismes, empoisonnements et autres causes externes','T25.592S'),
('Corrosion of first degree of multiple sites of non spécifié ankle and foot, initial encounter','Corrosion of first degree of multiple sites of unspecified ankle and foot, initial encounter','Traumatismes, empoisonnements et autres causes externes','T25.599A'),
('Corrosion of first degree of multiple sites of non spécifié ankle and foot, subsequent encounter','Corrosion of first degree of multiple sites of unspecified ankle and foot, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T25.599D'),
('Corrosion of first degree of multiple sites of non spécifié ankle and foot, sequela','Corrosion of first degree of multiple sites of unspecified ankle and foot, sequela','Traumatismes, empoisonnements et autres causes externes','T25.599S'),
('Corrosion of second degree of right ankle, initial encounter','Corrosion of second degree of right ankle, initial encounter','Traumatismes, empoisonnements et autres causes externes','T25.611A'),
('Corrosion of second degree of right ankle, subsequent encounter','Corrosion of second degree of right ankle, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T25.611D'),
('Corrosion of second degree of right ankle, sequela','Corrosion of second degree of right ankle, sequela','Traumatismes, empoisonnements et autres causes externes','T25.611S'),
('Corrosion of second degree of left ankle, initial encounter','Corrosion of second degree of left ankle, initial encounter','Traumatismes, empoisonnements et autres causes externes','T25.612A'),
('Corrosion of second degree of left ankle, subsequent encounter','Corrosion of second degree of left ankle, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T25.612D'),
('Corrosion of second degree of left ankle, sequela','Corrosion of second degree of left ankle, sequela','Traumatismes, empoisonnements et autres causes externes','T25.612S'),
('Corrosion of second degree of non spécifié ankle, initial encounter','Corrosion of second degree of unspecified ankle, initial encounter','Traumatismes, empoisonnements et autres causes externes','T25.619A'),
('Corrosion of second degree of non spécifié ankle, subsequent encounter','Corrosion of second degree of unspecified ankle, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T25.619D'),
('Corrosion of second degree of non spécifié ankle, sequela','Corrosion of second degree of unspecified ankle, sequela','Traumatismes, empoisonnements et autres causes externes','T25.619S'),
('Corrosion of second degree of right foot, initial encounter','Corrosion of second degree of right foot, initial encounter','Traumatismes, empoisonnements et autres causes externes','T25.621A'),
('Corrosion of second degree of right foot, subsequent encounter','Corrosion of second degree of right foot, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T25.621D'),
('Corrosion of second degree of right foot, sequela','Corrosion of second degree of right foot, sequela','Traumatismes, empoisonnements et autres causes externes','T25.621S'),
('Corrosion of second degree of left foot, initial encounter','Corrosion of second degree of left foot, initial encounter','Traumatismes, empoisonnements et autres causes externes','T25.622A'),
('Corrosion of second degree of left foot, subsequent encounter','Corrosion of second degree of left foot, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T25.622D'),
('Corrosion of second degree of left foot, sequela','Corrosion of second degree of left foot, sequela','Traumatismes, empoisonnements et autres causes externes','T25.622S'),
('Corrosion of second degree of non spécifié foot, initial encounter','Corrosion of second degree of unspecified foot, initial encounter','Traumatismes, empoisonnements et autres causes externes','T25.629A'),
('Corrosion of second degree of non spécifié foot, subsequent encounter','Corrosion of second degree of unspecified foot, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T25.629D'),
('Corrosion of second degree of non spécifié foot, sequela','Corrosion of second degree of unspecified foot, sequela','Traumatismes, empoisonnements et autres causes externes','T25.629S'),
('Corrosion of second degree of right toe(s) (nail), initial encounter','Corrosion of second degree of right toe(s) (nail), initial encounter','Traumatismes, empoisonnements et autres causes externes','T25.631A'),
('Corrosion of second degree of right toe(s) (nail), subsequent encounter','Corrosion of second degree of right toe(s) (nail), subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T25.631D'),
('Corrosion of second degree of right toe(s) (nail), sequela','Corrosion of second degree of right toe(s) (nail), sequela','Traumatismes, empoisonnements et autres causes externes','T25.631S'),
('Corrosion of second degree of left toe(s) (nail), initial encounter','Corrosion of second degree of left toe(s) (nail), initial encounter','Traumatismes, empoisonnements et autres causes externes','T25.632A'),
('Corrosion of second degree of left toe(s) (nail), subsequent encounter','Corrosion of second degree of left toe(s) (nail), subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T25.632D'),
('Corrosion of second degree of left toe(s) (nail), sequela','Corrosion of second degree of left toe(s) (nail), sequela','Traumatismes, empoisonnements et autres causes externes','T25.632S'),
('Corrosion of second degree of non spécifié toe(s) (nail), initial encounter','Corrosion of second degree of unspecified toe(s) (nail), initial encounter','Traumatismes, empoisonnements et autres causes externes','T25.639A'),
('Corrosion of second degree of non spécifié toe(s) (nail), subsequent encounter','Corrosion of second degree of unspecified toe(s) (nail), subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T25.639D'),
('Corrosion of second degree of non spécifié toe(s) (nail), sequela','Corrosion of second degree of unspecified toe(s) (nail), sequela','Traumatismes, empoisonnements et autres causes externes','T25.639S'),
('Corrosion of second degree of right ankle and foot, initial encounter','Corrosion of second degree of right ankle and foot, initial encounter','Traumatismes, empoisonnements et autres causes externes','T25.691A'),
('Corrosion of second degree of right ankle and foot, subsequent encounter','Corrosion of second degree of right ankle and foot, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T25.691D'),
('Corrosion of second degree of right ankle and foot, sequela','Corrosion of second degree of right ankle and foot, sequela','Traumatismes, empoisonnements et autres causes externes','T25.691S'),
('Corrosion of second degree of left ankle and foot, initial encounter','Corrosion of second degree of left ankle and foot, initial encounter','Traumatismes, empoisonnements et autres causes externes','T25.692A'),
('Corrosion of second degree of left ankle and foot, subsequent encounter','Corrosion of second degree of left ankle and foot, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T25.692D'),
('Corrosion of second degree of left ankle and foot, sequela','Corrosion of second degree of left ankle and foot, sequela','Traumatismes, empoisonnements et autres causes externes','T25.692S'),
('Corrosion of second degree of non spécifié ankle and foot, initial encounter','Corrosion of second degree of unspecified ankle and foot, initial encounter','Traumatismes, empoisonnements et autres causes externes','T25.699A'),
('Corrosion of second degree of non spécifié ankle and foot, subsequent encounter','Corrosion of second degree of unspecified ankle and foot, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T25.699D'),
('Corrosion of second degree of non spécifié ankle and foot, sequela','Corrosion of second degree of unspecified ankle and foot, sequela','Traumatismes, empoisonnements et autres causes externes','T25.699S'),
('Corrosion of third degree of right ankle, initial encounter','Corrosion of third degree of right ankle, initial encounter','Traumatismes, empoisonnements et autres causes externes','T25.711A'),
('Corrosion of third degree of right ankle, subsequent encounter','Corrosion of third degree of right ankle, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T25.711D'),
('Corrosion of third degree of right ankle, sequela','Corrosion of third degree of right ankle, sequela','Traumatismes, empoisonnements et autres causes externes','T25.711S'),
('Corrosion of third degree of left ankle, initial encounter','Corrosion of third degree of left ankle, initial encounter','Traumatismes, empoisonnements et autres causes externes','T25.712A'),
('Corrosion of third degree of left ankle, subsequent encounter','Corrosion of third degree of left ankle, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T25.712D'),
('Corrosion of third degree of left ankle, sequela','Corrosion of third degree of left ankle, sequela','Traumatismes, empoisonnements et autres causes externes','T25.712S'),
('Corrosion of third degree of non spécifié ankle, initial encounter','Corrosion of third degree of unspecified ankle, initial encounter','Traumatismes, empoisonnements et autres causes externes','T25.719A'),
('Corrosion of third degree of non spécifié ankle, subsequent encounter','Corrosion of third degree of unspecified ankle, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T25.719D'),
('Corrosion of third degree of non spécifié ankle, sequela','Corrosion of third degree of unspecified ankle, sequela','Traumatismes, empoisonnements et autres causes externes','T25.719S'),
('Corrosion of third degree of right foot, initial encounter','Corrosion of third degree of right foot, initial encounter','Traumatismes, empoisonnements et autres causes externes','T25.721A'),
('Corrosion of third degree of right foot, subsequent encounter','Corrosion of third degree of right foot, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T25.721D'),
('Corrosion of third degree of right foot, sequela','Corrosion of third degree of right foot, sequela','Traumatismes, empoisonnements et autres causes externes','T25.721S'),
('Corrosion of third degree of left foot, initial encounter','Corrosion of third degree of left foot, initial encounter','Traumatismes, empoisonnements et autres causes externes','T25.722A'),
('Corrosion of third degree of left foot, subsequent encounter','Corrosion of third degree of left foot, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T25.722D'),
('Corrosion of third degree of left foot, sequela','Corrosion of third degree of left foot, sequela','Traumatismes, empoisonnements et autres causes externes','T25.722S'),
('Corrosion of third degree of non spécifié foot, initial encounter','Corrosion of third degree of unspecified foot, initial encounter','Traumatismes, empoisonnements et autres causes externes','T25.729A')
ON CONFLICT (nom_fr) DO NOTHING;
