-- icd10v2_batch_211.sql (80 rows)
INSERT INTO pathologies (nom_fr, nom_en, categorie, icd10_code)
VALUES
('Connective tissue and disc sténose of intervertebral foramina of sacral region','Connective tissue and disc stenosis of intervertebral foramina of sacral region','Maladies de l''appareil locomoteur','M99.74'),
('Connective tissue and disc sténose of intervertebral foramina of pelvic region','Connective tissue and disc stenosis of intervertebral foramina of pelvic region','Maladies de l''appareil locomoteur','M99.75'),
('Connective tissue and disc sténose of intervertebral foramina of lower extremity','Connective tissue and disc stenosis of intervertebral foramina of lower extremity','Maladies de l''appareil locomoteur','M99.76'),
('Connective tissue and disc sténose of intervertebral foramina of upper extremity','Connective tissue and disc stenosis of intervertebral foramina of upper extremity','Maladies de l''appareil locomoteur','M99.77'),
('Connective tissue and disc sténose of intervertebral foramina of rib cage','Connective tissue and disc stenosis of intervertebral foramina of rib cage','Maladies de l''appareil locomoteur','M99.78'),
('Connective tissue and disc sténose of intervertebral foramina of abdomen and autre regions','Connective tissue and disc stenosis of intervertebral foramina of abdomen and other regions','Maladies de l''appareil locomoteur','M99.79'),
('autre biomechanical lesions of head region','Other biomechanical lesions of head region','Maladies de l''appareil locomoteur','M99.80'),
('autre biomechanical lesions of cervical region','Other biomechanical lesions of cervical region','Maladies de l''appareil locomoteur','M99.81'),
('autre biomechanical lesions of thoracic region','Other biomechanical lesions of thoracic region','Maladies de l''appareil locomoteur','M99.82'),
('autre biomechanical lesions of lumbar region','Other biomechanical lesions of lumbar region','Maladies de l''appareil locomoteur','M99.83'),
('autre biomechanical lesions of sacral region','Other biomechanical lesions of sacral region','Maladies de l''appareil locomoteur','M99.84'),
('autre biomechanical lesions of pelvic region','Other biomechanical lesions of pelvic region','Maladies de l''appareil locomoteur','M99.85'),
('autre biomechanical lesions of lower extremity','Other biomechanical lesions of lower extremity','Maladies de l''appareil locomoteur','M99.86'),
('autre biomechanical lesions of upper extremity','Other biomechanical lesions of upper extremity','Maladies de l''appareil locomoteur','M99.87'),
('autre biomechanical lesions of rib cage','Other biomechanical lesions of rib cage','Maladies de l''appareil locomoteur','M99.88'),
('autre biomechanical lesions of abdomen and autre regions','Other biomechanical lesions of abdomen and other regions','Maladies de l''appareil locomoteur','M99.89'),
('Biomechanical lesion, non spécifié','Biomechanical lesion, unspecified','Maladies de l''appareil locomoteur','M99.9'),
('aigu nephritic syndrome with minor glomerular abnormality','Acute nephritic syndrome with minor glomerular abnormality','Maladies de l''appareil génito-urinaire','N00.0'),
('aigu nephritic syndrome with focal and segmental glomerular lesions','Acute nephritic syndrome with focal and segmental glomerular lesions','Maladies de l''appareil génito-urinaire','N00.1'),
('aigu nephritic syndrome with diffuse membranous glomerulonephritis','Acute nephritic syndrome with diffuse membranous glomerulonephritis','Maladies de l''appareil génito-urinaire','N00.2'),
('aigu nephritic syndrome with diffuse mesangial proliferative glomerulonephritis','Acute nephritic syndrome with diffuse mesangial proliferative glomerulonephritis','Maladies de l''appareil génito-urinaire','N00.3'),
('aigu nephritic syndrome with diffuse endocapillary proliferative glomerulonephritis','Acute nephritic syndrome with diffuse endocapillary proliferative glomerulonephritis','Maladies de l''appareil génito-urinaire','N00.4'),
('aigu nephritic syndrome with diffuse mesangiocapillary glomerulonephritis','Acute nephritic syndrome with diffuse mesangiocapillary glomerulonephritis','Maladies de l''appareil génito-urinaire','N00.5'),
('aigu nephritic syndrome with dense deposit maladie','Acute nephritic syndrome with dense deposit disease','Maladies de l''appareil génito-urinaire','N00.6'),
('aigu nephritic syndrome with diffuse crescentic glomerulonephritis','Acute nephritic syndrome with diffuse crescentic glomerulonephritis','Maladies de l''appareil génito-urinaire','N00.7'),
('aigu nephritic syndrome with autre morphologic changes','Acute nephritic syndrome with other morphologic changes','Maladies de l''appareil génito-urinaire','N00.8'),
('aigu nephritic syndrome with non spécifié morphologic changes','Acute nephritic syndrome with unspecified morphologic changes','Maladies de l''appareil génito-urinaire','N00.9'),
('aigu nephritic syndrome with idiopathic immune membranoproliferative glomerulonephritis (IC-MPGN)','Acute nephritic syndrome with idiopathic immune membranoproliferative glomerulonephritis (IC-MPGN)','Maladies de l''appareil génito-urinaire','N00.B1'),
('aigu nephritic syndrome with secondaire immune complex membranoproliferative glomerulonephritis (IC-MPGN)','Acute nephritic syndrome with secondary immune complex membranoproliferative glomerulonephritis (IC-MPGN)','Maladies de l''appareil génito-urinaire','N00.B2'),
('Rapidly progressive nephritic syndrome with minor glomerular abnormality','Rapidly progressive nephritic syndrome with minor glomerular abnormality','Maladies de l''appareil génito-urinaire','N01.0'),
('Rapidly progressive nephritic syndrome with focal and segmental glomerular lesions','Rapidly progressive nephritic syndrome with focal and segmental glomerular lesions','Maladies de l''appareil génito-urinaire','N01.1'),
('Rapidly progressive nephritic syndrome with diffuse membranous glomerulonephritis','Rapidly progressive nephritic syndrome with diffuse membranous glomerulonephritis','Maladies de l''appareil génito-urinaire','N01.2'),
('Rapidly progressive nephritic syndrome with diffuse mesangial proliferative glomerulonephritis','Rapidly progressive nephritic syndrome with diffuse mesangial proliferative glomerulonephritis','Maladies de l''appareil génito-urinaire','N01.3'),
('Rapidly progressive nephritic syndrome with diffuse endocapillary proliferative glomerulonephritis','Rapidly progressive nephritic syndrome with diffuse endocapillary proliferative glomerulonephritis','Maladies de l''appareil génito-urinaire','N01.4'),
('Rapidly progressive nephritic syndrome with diffuse mesangiocapillary glomerulonephritis','Rapidly progressive nephritic syndrome with diffuse mesangiocapillary glomerulonephritis','Maladies de l''appareil génito-urinaire','N01.5'),
('Rapidly progressive nephritic syndrome with dense deposit maladie','Rapidly progressive nephritic syndrome with dense deposit disease','Maladies de l''appareil génito-urinaire','N01.6'),
('Rapidly progressive nephritic syndrome with diffuse crescentic glomerulonephritis','Rapidly progressive nephritic syndrome with diffuse crescentic glomerulonephritis','Maladies de l''appareil génito-urinaire','N01.7'),
('Rapidly progressive nephritic syndrome with autre morphologic changes','Rapidly progressive nephritic syndrome with other morphologic changes','Maladies de l''appareil génito-urinaire','N01.8'),
('Rapidly progressive nephritic syndrome with non spécifié morphologic changes','Rapidly progressive nephritic syndrome with unspecified morphologic changes','Maladies de l''appareil génito-urinaire','N01.9'),
('Recurrent and persistent hematuria with minor glomerular abnormality','Recurrent and persistent hematuria with minor glomerular abnormality','Maladies de l''appareil génito-urinaire','N02.0'),
('Recurrent and persistent hematuria with focal and segmental glomerular lesions','Recurrent and persistent hematuria with focal and segmental glomerular lesions','Maladies de l''appareil génito-urinaire','N02.1'),
('Recurrent and persistent hematuria with diffuse membranous glomerulonephritis','Recurrent and persistent hematuria with diffuse membranous glomerulonephritis','Maladies de l''appareil génito-urinaire','N02.2'),
('Recurrent and persistent hematuria with diffuse mesangial proliferative glomerulonephritis','Recurrent and persistent hematuria with diffuse mesangial proliferative glomerulonephritis','Maladies de l''appareil génito-urinaire','N02.3'),
('Recurrent and persistent hematuria with diffuse endocapillary proliferative glomerulonephritis','Recurrent and persistent hematuria with diffuse endocapillary proliferative glomerulonephritis','Maladies de l''appareil génito-urinaire','N02.4'),
('Recurrent and persistent hematuria with diffuse mesangiocapillary glomerulonephritis','Recurrent and persistent hematuria with diffuse mesangiocapillary glomerulonephritis','Maladies de l''appareil génito-urinaire','N02.5'),
('Recurrent and persistent hematuria with dense deposit maladie','Recurrent and persistent hematuria with dense deposit disease','Maladies de l''appareil génito-urinaire','N02.6'),
('Recurrent and persistent hematuria with diffuse crescentic glomerulonephritis','Recurrent and persistent hematuria with diffuse crescentic glomerulonephritis','Maladies de l''appareil génito-urinaire','N02.7'),
('Recurrent and persistent hematuria with autre morphologic changes','Recurrent and persistent hematuria with other morphologic changes','Maladies de l''appareil génito-urinaire','N02.8'),
('Recurrent and persistent hematuria with non spécifié morphologic changes','Recurrent and persistent hematuria with unspecified morphologic changes','Maladies de l''appareil génito-urinaire','N02.9'),
('Recurrent and persistent immunoglobulin A nephropathy with glomerular lesion','Recurrent and persistent immunoglobulin A nephropathy with glomerular lesion','Maladies de l''appareil génito-urinaire','N02.B1'),
('Recurrent and persistent immunoglobulin A nephropathy with focal and segmental glomerular lesion','Recurrent and persistent immunoglobulin A nephropathy with focal and segmental glomerular lesion','Maladies de l''appareil génito-urinaire','N02.B2'),
('Recurrent and persistent immunoglobulin A nephropathy with diffuse membranoproliferative glomerulonephritis','Recurrent and persistent immunoglobulin A nephropathy with diffuse membranoproliferative glomerulonephritis','Maladies de l''appareil génito-urinaire','N02.B3'),
('Recurrent and persistent immunoglobulin A nephropathy with diffuse membranous glomerulonephritis','Recurrent and persistent immunoglobulin A nephropathy with diffuse membranous glomerulonephritis','Maladies de l''appareil génito-urinaire','N02.B4'),
('Recurrent and persistent immunoglobulin A nephropathy with diffuse mesangial proliferative glomerulonephritis','Recurrent and persistent immunoglobulin A nephropathy with diffuse mesangial proliferative glomerulonephritis','Maladies de l''appareil génito-urinaire','N02.B5'),
('Recurrent and persistent immunoglobulin A nephropathy with diffuse mesangiocapillary glomerulonephritis','Recurrent and persistent immunoglobulin A nephropathy with diffuse mesangiocapillary glomerulonephritis','Maladies de l''appareil génito-urinaire','N02.B6'),
('autre recurrent and persistent immunoglobulin A nephropathy','Other recurrent and persistent immunoglobulin A nephropathy','Maladies de l''appareil génito-urinaire','N02.B9'),
('chronique nephritic syndrome with minor glomerular abnormality','Chronic nephritic syndrome with minor glomerular abnormality','Maladies de l''appareil génito-urinaire','N03.0'),
('chronique nephritic syndrome with focal and segmental glomerular lesions','Chronic nephritic syndrome with focal and segmental glomerular lesions','Maladies de l''appareil génito-urinaire','N03.1'),
('chronique nephritic syndrome with diffuse membranous glomerulonephritis','Chronic nephritic syndrome with diffuse membranous glomerulonephritis','Maladies de l''appareil génito-urinaire','N03.2'),
('chronique nephritic syndrome with diffuse mesangial proliferative glomerulonephritis','Chronic nephritic syndrome with diffuse mesangial proliferative glomerulonephritis','Maladies de l''appareil génito-urinaire','N03.3'),
('chronique nephritic syndrome with diffuse endocapillary proliferative glomerulonephritis','Chronic nephritic syndrome with diffuse endocapillary proliferative glomerulonephritis','Maladies de l''appareil génito-urinaire','N03.4'),
('chronique nephritic syndrome with diffuse mesangiocapillary glomerulonephritis','Chronic nephritic syndrome with diffuse mesangiocapillary glomerulonephritis','Maladies de l''appareil génito-urinaire','N03.5'),
('chronique nephritic syndrome with dense deposit maladie','Chronic nephritic syndrome with dense deposit disease','Maladies de l''appareil génito-urinaire','N03.6'),
('chronique nephritic syndrome with diffuse crescentic glomerulonephritis','Chronic nephritic syndrome with diffuse crescentic glomerulonephritis','Maladies de l''appareil génito-urinaire','N03.7'),
('chronique nephritic syndrome with autre morphologic changes','Chronic nephritic syndrome with other morphologic changes','Maladies de l''appareil génito-urinaire','N03.8'),
('chronique nephritic syndrome with non spécifié morphologic changes','Chronic nephritic syndrome with unspecified morphologic changes','Maladies de l''appareil génito-urinaire','N03.9'),
('Nephrotic syndrome with minor glomerular abnormality','Nephrotic syndrome with minor glomerular abnormality','Maladies de l''appareil génito-urinaire','N04.0'),
('Nephrotic syndrome with focal and segmental glomerular lesions','Nephrotic syndrome with focal and segmental glomerular lesions','Maladies de l''appareil génito-urinaire','N04.1'),
('Nephrotic syndrome with diffuse membranous glomerulonephritis, non spécifié','Nephrotic syndrome with diffuse membranous glomerulonephritis, unspecified','Maladies de l''appareil génito-urinaire','N04.20'),
('primitif membranous nephropathy with nephrotic syndrome','Primary membranous nephropathy with nephrotic syndrome','Maladies de l''appareil génito-urinaire','N04.21'),
('secondaire membranous nephropathy with nephrotic syndrome','Secondary membranous nephropathy with nephrotic syndrome','Maladies de l''appareil génito-urinaire','N04.22'),
('autre nephrotic syndrome with diffuse membranous glomerulonephritis','Other nephrotic syndrome with diffuse membranous glomerulonephritis','Maladies de l''appareil génito-urinaire','N04.29'),
('Nephrotic syndrome with diffuse mesangial proliferative glomerulonephritis','Nephrotic syndrome with diffuse mesangial proliferative glomerulonephritis','Maladies de l''appareil génito-urinaire','N04.3'),
('Nephrotic syndrome with diffuse endocapillary proliferative glomerulonephritis','Nephrotic syndrome with diffuse endocapillary proliferative glomerulonephritis','Maladies de l''appareil génito-urinaire','N04.4'),
('Nephrotic syndrome with diffuse mesangiocapillary glomerulonephritis','Nephrotic syndrome with diffuse mesangiocapillary glomerulonephritis','Maladies de l''appareil génito-urinaire','N04.5'),
('Nephrotic syndrome with dense deposit maladie','Nephrotic syndrome with dense deposit disease','Maladies de l''appareil génito-urinaire','N04.6'),
('Nephrotic syndrome with diffuse crescentic glomerulonephritis','Nephrotic syndrome with diffuse crescentic glomerulonephritis','Maladies de l''appareil génito-urinaire','N04.7'),
('Nephrotic syndrome with autre morphologic changes','Nephrotic syndrome with other morphologic changes','Maladies de l''appareil génito-urinaire','N04.8'),
('Nephrotic syndrome with non spécifié morphologic changes','Nephrotic syndrome with unspecified morphologic changes','Maladies de l''appareil génito-urinaire','N04.9'),
('Nephrotic syndrome with idiopathic immune complex membranoproliferative glomerulonephritis (IC-MPGN)','Nephrotic syndrome with idiopathic immune complex membranoproliferative glomerulonephritis (IC-MPGN)','Maladies de l''appareil génito-urinaire','N04.B1')
ON CONFLICT (nom_fr) DO NOTHING;
