-- icd10v2_batch_348.sql (80 rows)
INSERT INTO pathologies (nom_fr, nom_en, categorie, icd10_code)
VALUES
('Superficial frostbite of abdominal wall, lower back and pelvis, sequela','Superficial frostbite of abdominal wall, lower back and pelvis, sequela','Traumatismes, empoisonnements et autres causes externes','T33.3XXS'),
('Superficial frostbite of non spécifié arm, initial encounter','Superficial frostbite of unspecified arm, initial encounter','Traumatismes, empoisonnements et autres causes externes','T33.40XA'),
('Superficial frostbite of non spécifié arm, subsequent encounter','Superficial frostbite of unspecified arm, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T33.40XD'),
('Superficial frostbite of non spécifié arm, sequela','Superficial frostbite of unspecified arm, sequela','Traumatismes, empoisonnements et autres causes externes','T33.40XS'),
('Superficial frostbite of right arm, initial encounter','Superficial frostbite of right arm, initial encounter','Traumatismes, empoisonnements et autres causes externes','T33.41XA'),
('Superficial frostbite of right arm, subsequent encounter','Superficial frostbite of right arm, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T33.41XD'),
('Superficial frostbite of right arm, sequela','Superficial frostbite of right arm, sequela','Traumatismes, empoisonnements et autres causes externes','T33.41XS'),
('Superficial frostbite of left arm, initial encounter','Superficial frostbite of left arm, initial encounter','Traumatismes, empoisonnements et autres causes externes','T33.42XA'),
('Superficial frostbite of left arm, subsequent encounter','Superficial frostbite of left arm, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T33.42XD'),
('Superficial frostbite of left arm, sequela','Superficial frostbite of left arm, sequela','Traumatismes, empoisonnements et autres causes externes','T33.42XS'),
('Superficial frostbite of right wrist, initial encounter','Superficial frostbite of right wrist, initial encounter','Traumatismes, empoisonnements et autres causes externes','T33.511A'),
('Superficial frostbite of right wrist, subsequent encounter','Superficial frostbite of right wrist, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T33.511D'),
('Superficial frostbite of right wrist, sequela','Superficial frostbite of right wrist, sequela','Traumatismes, empoisonnements et autres causes externes','T33.511S'),
('Superficial frostbite of left wrist, initial encounter','Superficial frostbite of left wrist, initial encounter','Traumatismes, empoisonnements et autres causes externes','T33.512A'),
('Superficial frostbite of left wrist, subsequent encounter','Superficial frostbite of left wrist, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T33.512D'),
('Superficial frostbite of left wrist, sequela','Superficial frostbite of left wrist, sequela','Traumatismes, empoisonnements et autres causes externes','T33.512S'),
('Superficial frostbite of non spécifié wrist, initial encounter','Superficial frostbite of unspecified wrist, initial encounter','Traumatismes, empoisonnements et autres causes externes','T33.519A'),
('Superficial frostbite of non spécifié wrist, subsequent encounter','Superficial frostbite of unspecified wrist, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T33.519D'),
('Superficial frostbite of non spécifié wrist, sequela','Superficial frostbite of unspecified wrist, sequela','Traumatismes, empoisonnements et autres causes externes','T33.519S'),
('Superficial frostbite of right hand, initial encounter','Superficial frostbite of right hand, initial encounter','Traumatismes, empoisonnements et autres causes externes','T33.521A'),
('Superficial frostbite of right hand, subsequent encounter','Superficial frostbite of right hand, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T33.521D'),
('Superficial frostbite of right hand, sequela','Superficial frostbite of right hand, sequela','Traumatismes, empoisonnements et autres causes externes','T33.521S'),
('Superficial frostbite of left hand, initial encounter','Superficial frostbite of left hand, initial encounter','Traumatismes, empoisonnements et autres causes externes','T33.522A'),
('Superficial frostbite of left hand, subsequent encounter','Superficial frostbite of left hand, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T33.522D'),
('Superficial frostbite of left hand, sequela','Superficial frostbite of left hand, sequela','Traumatismes, empoisonnements et autres causes externes','T33.522S'),
('Superficial frostbite of non spécifié hand, initial encounter','Superficial frostbite of unspecified hand, initial encounter','Traumatismes, empoisonnements et autres causes externes','T33.529A'),
('Superficial frostbite of non spécifié hand, subsequent encounter','Superficial frostbite of unspecified hand, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T33.529D'),
('Superficial frostbite of non spécifié hand, sequela','Superficial frostbite of unspecified hand, sequela','Traumatismes, empoisonnements et autres causes externes','T33.529S'),
('Superficial frostbite of right finger(s), initial encounter','Superficial frostbite of right finger(s), initial encounter','Traumatismes, empoisonnements et autres causes externes','T33.531A'),
('Superficial frostbite of right finger(s), subsequent encounter','Superficial frostbite of right finger(s), subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T33.531D'),
('Superficial frostbite of right finger(s), sequela','Superficial frostbite of right finger(s), sequela','Traumatismes, empoisonnements et autres causes externes','T33.531S'),
('Superficial frostbite of left finger(s), initial encounter','Superficial frostbite of left finger(s), initial encounter','Traumatismes, empoisonnements et autres causes externes','T33.532A'),
('Superficial frostbite of left finger(s), subsequent encounter','Superficial frostbite of left finger(s), subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T33.532D'),
('Superficial frostbite of left finger(s), sequela','Superficial frostbite of left finger(s), sequela','Traumatismes, empoisonnements et autres causes externes','T33.532S'),
('Superficial frostbite of non spécifié finger(s), initial encounter','Superficial frostbite of unspecified finger(s), initial encounter','Traumatismes, empoisonnements et autres causes externes','T33.539A'),
('Superficial frostbite of non spécifié finger(s), subsequent encounter','Superficial frostbite of unspecified finger(s), subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T33.539D'),
('Superficial frostbite of non spécifié finger(s), sequela','Superficial frostbite of unspecified finger(s), sequela','Traumatismes, empoisonnements et autres causes externes','T33.539S'),
('Superficial frostbite of non spécifié hip and thigh, initial encounter','Superficial frostbite of unspecified hip and thigh, initial encounter','Traumatismes, empoisonnements et autres causes externes','T33.60XA'),
('Superficial frostbite of non spécifié hip and thigh, subsequent encounter','Superficial frostbite of unspecified hip and thigh, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T33.60XD'),
('Superficial frostbite of non spécifié hip and thigh, sequela','Superficial frostbite of unspecified hip and thigh, sequela','Traumatismes, empoisonnements et autres causes externes','T33.60XS'),
('Superficial frostbite of right hip and thigh, initial encounter','Superficial frostbite of right hip and thigh, initial encounter','Traumatismes, empoisonnements et autres causes externes','T33.61XA'),
('Superficial frostbite of right hip and thigh, subsequent encounter','Superficial frostbite of right hip and thigh, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T33.61XD'),
('Superficial frostbite of right hip and thigh, sequela','Superficial frostbite of right hip and thigh, sequela','Traumatismes, empoisonnements et autres causes externes','T33.61XS'),
('Superficial frostbite of left hip and thigh, initial encounter','Superficial frostbite of left hip and thigh, initial encounter','Traumatismes, empoisonnements et autres causes externes','T33.62XA'),
('Superficial frostbite of left hip and thigh, subsequent encounter','Superficial frostbite of left hip and thigh, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T33.62XD'),
('Superficial frostbite of left hip and thigh, sequela','Superficial frostbite of left hip and thigh, sequela','Traumatismes, empoisonnements et autres causes externes','T33.62XS'),
('Superficial frostbite of non spécifié knee and lower leg, initial encounter','Superficial frostbite of unspecified knee and lower leg, initial encounter','Traumatismes, empoisonnements et autres causes externes','T33.70XA'),
('Superficial frostbite of non spécifié knee and lower leg, subsequent encounter','Superficial frostbite of unspecified knee and lower leg, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T33.70XD'),
('Superficial frostbite of non spécifié knee and lower leg, sequela','Superficial frostbite of unspecified knee and lower leg, sequela','Traumatismes, empoisonnements et autres causes externes','T33.70XS'),
('Superficial frostbite of right knee and lower leg, initial encounter','Superficial frostbite of right knee and lower leg, initial encounter','Traumatismes, empoisonnements et autres causes externes','T33.71XA'),
('Superficial frostbite of right knee and lower leg, subsequent encounter','Superficial frostbite of right knee and lower leg, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T33.71XD'),
('Superficial frostbite of right knee and lower leg, sequela','Superficial frostbite of right knee and lower leg, sequela','Traumatismes, empoisonnements et autres causes externes','T33.71XS'),
('Superficial frostbite of left knee and lower leg, initial encounter','Superficial frostbite of left knee and lower leg, initial encounter','Traumatismes, empoisonnements et autres causes externes','T33.72XA'),
('Superficial frostbite of left knee and lower leg, subsequent encounter','Superficial frostbite of left knee and lower leg, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T33.72XD'),
('Superficial frostbite of left knee and lower leg, sequela','Superficial frostbite of left knee and lower leg, sequela','Traumatismes, empoisonnements et autres causes externes','T33.72XS'),
('Superficial frostbite of right ankle, initial encounter','Superficial frostbite of right ankle, initial encounter','Traumatismes, empoisonnements et autres causes externes','T33.811A'),
('Superficial frostbite of right ankle, subsequent encounter','Superficial frostbite of right ankle, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T33.811D'),
('Superficial frostbite of right ankle, sequela','Superficial frostbite of right ankle, sequela','Traumatismes, empoisonnements et autres causes externes','T33.811S'),
('Superficial frostbite of left ankle, initial encounter','Superficial frostbite of left ankle, initial encounter','Traumatismes, empoisonnements et autres causes externes','T33.812A'),
('Superficial frostbite of left ankle, subsequent encounter','Superficial frostbite of left ankle, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T33.812D'),
('Superficial frostbite of left ankle, sequela','Superficial frostbite of left ankle, sequela','Traumatismes, empoisonnements et autres causes externes','T33.812S'),
('Superficial frostbite of non spécifié ankle, initial encounter','Superficial frostbite of unspecified ankle, initial encounter','Traumatismes, empoisonnements et autres causes externes','T33.819A'),
('Superficial frostbite of non spécifié ankle, subsequent encounter','Superficial frostbite of unspecified ankle, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T33.819D'),
('Superficial frostbite of non spécifié ankle, sequela','Superficial frostbite of unspecified ankle, sequela','Traumatismes, empoisonnements et autres causes externes','T33.819S'),
('Superficial frostbite of right foot, initial encounter','Superficial frostbite of right foot, initial encounter','Traumatismes, empoisonnements et autres causes externes','T33.821A'),
('Superficial frostbite of right foot, subsequent encounter','Superficial frostbite of right foot, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T33.821D'),
('Superficial frostbite of right foot, sequela','Superficial frostbite of right foot, sequela','Traumatismes, empoisonnements et autres causes externes','T33.821S'),
('Superficial frostbite of left foot, initial encounter','Superficial frostbite of left foot, initial encounter','Traumatismes, empoisonnements et autres causes externes','T33.822A'),
('Superficial frostbite of left foot, subsequent encounter','Superficial frostbite of left foot, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T33.822D'),
('Superficial frostbite of left foot, sequela','Superficial frostbite of left foot, sequela','Traumatismes, empoisonnements et autres causes externes','T33.822S'),
('Superficial frostbite of non spécifié foot, initial encounter','Superficial frostbite of unspecified foot, initial encounter','Traumatismes, empoisonnements et autres causes externes','T33.829A'),
('Superficial frostbite of non spécifié foot, subsequent encounter','Superficial frostbite of unspecified foot, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T33.829D'),
('Superficial frostbite of non spécifié foot, sequela','Superficial frostbite of unspecified foot, sequela','Traumatismes, empoisonnements et autres causes externes','T33.829S'),
('Superficial frostbite of right toe(s), initial encounter','Superficial frostbite of right toe(s), initial encounter','Traumatismes, empoisonnements et autres causes externes','T33.831A'),
('Superficial frostbite of right toe(s), subsequent encounter','Superficial frostbite of right toe(s), subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T33.831D'),
('Superficial frostbite of right toe(s), sequela','Superficial frostbite of right toe(s), sequela','Traumatismes, empoisonnements et autres causes externes','T33.831S'),
('Superficial frostbite of left toe(s), initial encounter','Superficial frostbite of left toe(s), initial encounter','Traumatismes, empoisonnements et autres causes externes','T33.832A'),
('Superficial frostbite of left toe(s), subsequent encounter','Superficial frostbite of left toe(s), subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T33.832D'),
('Superficial frostbite of left toe(s), sequela','Superficial frostbite of left toe(s), sequela','Traumatismes, empoisonnements et autres causes externes','T33.832S'),
('Superficial frostbite of non spécifié toe(s), initial encounter','Superficial frostbite of unspecified toe(s), initial encounter','Traumatismes, empoisonnements et autres causes externes','T33.839A')
ON CONFLICT (nom_fr) DO NOTHING;
