-- icd10v2_batch_267.sql (80 rows)
INSERT INTO pathologies (nom_fr, nom_en, categorie, icd10_code)
VALUES
('Coma scale, best motor response, abnormal flexion, at arrival to emergency department','Coma scale, best motor response, abnormal flexion, at arrival to emergency department','Symptômes, signes et résultats anormaux','R40.2332'),
('Coma scale, best motor response, abnormal flexion, at hospital admission','Coma scale, best motor response, abnormal flexion, at hospital admission','Symptômes, signes et résultats anormaux','R40.2333'),
('Coma scale, best motor response, abnormal flexion, 24 hours or more after hospital admission','Coma scale, best motor response, abnormal flexion, 24 hours or more after hospital admission','Symptômes, signes et résultats anormaux','R40.2334'),
('Coma scale, best motor response, flexion withdrawal, non spécifié time','Coma scale, best motor response, flexion withdrawal, unspecified time','Symptômes, signes et résultats anormaux','R40.2340'),
('Coma scale, best motor response, flexion withdrawal, in the field [EMT or ambulance]','Coma scale, best motor response, flexion withdrawal, in the field [EMT or ambulance]','Symptômes, signes et résultats anormaux','R40.2341'),
('Coma scale, best motor response, flexion withdrawal, at arrival to emergency department','Coma scale, best motor response, flexion withdrawal, at arrival to emergency department','Symptômes, signes et résultats anormaux','R40.2342'),
('Coma scale, best motor response, flexion withdrawal, at hospital admission','Coma scale, best motor response, flexion withdrawal, at hospital admission','Symptômes, signes et résultats anormaux','R40.2343'),
('Coma scale, best motor response, flexion withdrawal, 24 hours or more after hospital admission','Coma scale, best motor response, flexion withdrawal, 24 hours or more after hospital admission','Symptômes, signes et résultats anormaux','R40.2344'),
('Coma scale, best motor response, localizes pain, non spécifié time','Coma scale, best motor response, localizes pain, unspecified time','Symptômes, signes et résultats anormaux','R40.2350'),
('Coma scale, best motor response, localizes pain, in the field [EMT or ambulance]','Coma scale, best motor response, localizes pain, in the field [EMT or ambulance]','Symptômes, signes et résultats anormaux','R40.2351'),
('Coma scale, best motor response, localizes pain, at arrival to emergency department','Coma scale, best motor response, localizes pain, at arrival to emergency department','Symptômes, signes et résultats anormaux','R40.2352'),
('Coma scale, best motor response, localizes pain, at hospital admission','Coma scale, best motor response, localizes pain, at hospital admission','Symptômes, signes et résultats anormaux','R40.2353'),
('Coma scale, best motor response, localizes pain, 24 hours or more after hospital admission','Coma scale, best motor response, localizes pain, 24 hours or more after hospital admission','Symptômes, signes et résultats anormaux','R40.2354'),
('Coma scale, best motor response, obeys commands, non spécifié time','Coma scale, best motor response, obeys commands, unspecified time','Symptômes, signes et résultats anormaux','R40.2360'),
('Coma scale, best motor response, obeys commands, in the field [EMT or ambulance]','Coma scale, best motor response, obeys commands, in the field [EMT or ambulance]','Symptômes, signes et résultats anormaux','R40.2361'),
('Coma scale, best motor response, obeys commands, at arrival to emergency department','Coma scale, best motor response, obeys commands, at arrival to emergency department','Symptômes, signes et résultats anormaux','R40.2362'),
('Coma scale, best motor response, obeys commands, at hospital admission','Coma scale, best motor response, obeys commands, at hospital admission','Symptômes, signes et résultats anormaux','R40.2363'),
('Coma scale, best motor response, obeys commands, 24 hours or more after hospital admission','Coma scale, best motor response, obeys commands, 24 hours or more after hospital admission','Symptômes, signes et résultats anormaux','R40.2364'),
('Glasgow coma scale score 13-15, non spécifié time','Glasgow coma scale score 13-15, unspecified time','Symptômes, signes et résultats anormaux','R40.2410'),
('Glasgow coma scale score 13-15, in the field [EMT or ambulance]','Glasgow coma scale score 13-15, in the field [EMT or ambulance]','Symptômes, signes et résultats anormaux','R40.2411'),
('Glasgow coma scale score 13-15, at arrival to emergency department','Glasgow coma scale score 13-15, at arrival to emergency department','Symptômes, signes et résultats anormaux','R40.2412'),
('Glasgow coma scale score 13-15, at hospital admission','Glasgow coma scale score 13-15, at hospital admission','Symptômes, signes et résultats anormaux','R40.2413'),
('Glasgow coma scale score 13-15, 24 hours or more after hospital admission','Glasgow coma scale score 13-15, 24 hours or more after hospital admission','Symptômes, signes et résultats anormaux','R40.2414'),
('Glasgow coma scale score 9-12, non spécifié time','Glasgow coma scale score 9-12, unspecified time','Symptômes, signes et résultats anormaux','R40.2420'),
('Glasgow coma scale score 9-12, in the field [EMT or ambulance]','Glasgow coma scale score 9-12, in the field [EMT or ambulance]','Symptômes, signes et résultats anormaux','R40.2421'),
('Glasgow coma scale score 9-12, at arrival to emergency department','Glasgow coma scale score 9-12, at arrival to emergency department','Symptômes, signes et résultats anormaux','R40.2422'),
('Glasgow coma scale score 9-12, at hospital admission','Glasgow coma scale score 9-12, at hospital admission','Symptômes, signes et résultats anormaux','R40.2423'),
('Glasgow coma scale score 9-12, 24 hours or more after hospital admission','Glasgow coma scale score 9-12, 24 hours or more after hospital admission','Symptômes, signes et résultats anormaux','R40.2424'),
('Glasgow coma scale score 3-8, non spécifié time','Glasgow coma scale score 3-8, unspecified time','Symptômes, signes et résultats anormaux','R40.2430'),
('Glasgow coma scale score 3-8, in the field [EMT or ambulance]','Glasgow coma scale score 3-8, in the field [EMT or ambulance]','Symptômes, signes et résultats anormaux','R40.2431'),
('Glasgow coma scale score 3-8, at arrival to emergency department','Glasgow coma scale score 3-8, at arrival to emergency department','Symptômes, signes et résultats anormaux','R40.2432'),
('Glasgow coma scale score 3-8, at hospital admission','Glasgow coma scale score 3-8, at hospital admission','Symptômes, signes et résultats anormaux','R40.2433'),
('Glasgow coma scale score 3-8, 24 hours or more after hospital admission','Glasgow coma scale score 3-8, 24 hours or more after hospital admission','Symptômes, signes et résultats anormaux','R40.2434'),
('autre coma, without documented Glasgow coma scale score, or with partial score reported, non spécifié time','Other coma, without documented Glasgow coma scale score, or with partial score reported, unspecified time','Symptômes, signes et résultats anormaux','R40.2440'),
('autre coma, without documented Glasgow coma scale score, or with partial score reported, in the field [EMT or ambulance]','Other coma, without documented Glasgow coma scale score, or with partial score reported, in the field [EMT or ambulance]','Symptômes, signes et résultats anormaux','R40.2441'),
('autre coma, without documented Glasgow coma scale score, or with partial score reported, at arrival to emergency department','Other coma, without documented Glasgow coma scale score, or with partial score reported, at arrival to emergency department','Symptômes, signes et résultats anormaux','R40.2442'),
('autre coma, without documented Glasgow coma scale score, or with partial score reported, at hospital admission','Other coma, without documented Glasgow coma scale score, or with partial score reported, at hospital admission','Symptômes, signes et résultats anormaux','R40.2443'),
('autre coma, without documented Glasgow coma scale score, or with partial score reported, 24 hours or more after hospital admission','Other coma, without documented Glasgow coma scale score, or with partial score reported, 24 hours or more after hospital admission','Symptômes, signes et résultats anormaux','R40.2444'),
('Nontraumatic coma due to underlying condition','Nontraumatic coma due to underlying condition','Symptômes, signes et résultats anormaux','R40.2A'),
('Persistent vegetative state','Persistent vegetative state','Symptômes, signes et résultats anormaux','R40.3'),
('Transient alteration of awareness','Transient alteration of awareness','Symptômes, signes et résultats anormaux','R40.4'),
('Disorientation, non spécifié','Disorientation, unspecified','Symptômes, signes et résultats anormaux','R41.0'),
('Anterograde amnesia','Anterograde amnesia','Symptômes, signes et résultats anormaux','R41.1'),
('Retrograde amnesia','Retrograde amnesia','Symptômes, signes et résultats anormaux','R41.2'),
('autre amnesia','Other amnesia','Symptômes, signes et résultats anormaux','R41.3'),
('Neurologic neglect syndrome','Neurologic neglect syndrome','Symptômes, signes et résultats anormaux','R41.4'),
('Age-related cognitive decline','Age-related cognitive decline','Symptômes, signes et résultats anormaux','R41.81'),
('Altered mental status, non spécifié','Altered mental status, unspecified','Symptômes, signes et résultats anormaux','R41.82'),
('Borderline intellectual functioning','Borderline intellectual functioning','Symptômes, signes et résultats anormaux','R41.83'),
('Attention and concentration deficit','Attention and concentration deficit','Symptômes, signes et résultats anormaux','R41.840'),
('Cognitive communication deficit','Cognitive communication deficit','Symptômes, signes et résultats anormaux','R41.841'),
('Visuospatial deficit','Visuospatial deficit','Symptômes, signes et résultats anormaux','R41.842'),
('Psychomotor deficit','Psychomotor deficit','Symptômes, signes et résultats anormaux','R41.843'),
('Frontal lobe and executive function deficit','Frontal lobe and executive function deficit','Symptômes, signes et résultats anormaux','R41.844'),
('Anosognosia','Anosognosia','Symptômes, signes et résultats anormaux','R41.85'),
('autre symptoms and signs involving cognitive functions and awareness','Other symptoms and signs involving cognitive functions and awareness','Symptômes, signes et résultats anormaux','R41.89'),
('non spécifié symptoms and signs involving cognitive functions and awareness','Unspecified symptoms and signs involving cognitive functions and awareness','Symptômes, signes et résultats anormaux','R41.9'),
('Dizziness and giddiness','Dizziness and giddiness','Symptômes, signes et résultats anormaux','R42'),
('Anosmia','Anosmia','Symptômes, signes et résultats anormaux','R43.0'),
('Parosmia','Parosmia','Symptômes, signes et résultats anormaux','R43.1'),
('Parageusia','Parageusia','Symptômes, signes et résultats anormaux','R43.2'),
('autre disturbances of smell and taste','Other disturbances of smell and taste','Symptômes, signes et résultats anormaux','R43.8'),
('non spécifié disturbances of smell and taste','Unspecified disturbances of smell and taste','Symptômes, signes et résultats anormaux','R43.9'),
('Auditory hallucinations','Auditory hallucinations','Symptômes, signes et résultats anormaux','R44.0'),
('Visual hallucinations','Visual hallucinations','Symptômes, signes et résultats anormaux','R44.1'),
('autre hallucinations','Other hallucinations','Symptômes, signes et résultats anormaux','R44.2'),
('Hallucinations, non spécifié','Hallucinations, unspecified','Symptômes, signes et résultats anormaux','R44.3'),
('autre symptoms and signs involving general sensations and perceptions','Other symptoms and signs involving general sensations and perceptions','Symptômes, signes et résultats anormaux','R44.8'),
('non spécifié symptoms and signs involving general sensations and perceptions','Unspecified symptoms and signs involving general sensations and perceptions','Symptômes, signes et résultats anormaux','R44.9'),
('Nervousness','Nervousness','Symptômes, signes et résultats anormaux','R45.0'),
('Restlessness and agitation','Restlessness and agitation','Symptômes, signes et résultats anormaux','R45.1'),
('Unhappiness','Unhappiness','Symptômes, signes et résultats anormaux','R45.2'),
('Demoralization and apathy','Demoralization and apathy','Symptômes, signes et résultats anormaux','R45.3'),
('Irritability and anger','Irritability and anger','Symptômes, signes et résultats anormaux','R45.4'),
('Hostility','Hostility','Symptômes, signes et résultats anormaux','R45.5'),
('Violent behavior','Violent behavior','Symptômes, signes et résultats anormaux','R45.6'),
('State of emotional shock and stress, non spécifié','State of emotional shock and stress, unspecified','Symptômes, signes et résultats anormaux','R45.7'),
('Low self-esteem','Low self-esteem','Symptômes, signes et résultats anormaux','R45.81'),
('Worries','Worries','Symptômes, signes et résultats anormaux','R45.82'),
('Excessive crying of child, adolescent or adult','Excessive crying of child, adolescent or adult','Symptômes, signes et résultats anormaux','R45.83')
ON CONFLICT (nom_fr) DO NOTHING;
