-- icd10v2_batch_093.sql (80 rows)
INSERT INTO pathologies (nom_fr, nom_en, categorie, icd10_code)
VALUES
('Cyst of ora serrata, non spécifié eye','Cyst of ora serrata, unspecified eye','Maladies de l''œil et de ses annexes','H33.119'),
('Parasitic cyst of retina, right eye','Parasitic cyst of retina, right eye','Maladies de l''œil et de ses annexes','H33.121'),
('Parasitic cyst of retina, left eye','Parasitic cyst of retina, left eye','Maladies de l''œil et de ses annexes','H33.122'),
('Parasitic cyst of retina, bilateral','Parasitic cyst of retina, bilateral','Maladies de l''œil et de ses annexes','H33.123'),
('Parasitic cyst of retina, non spécifié eye','Parasitic cyst of retina, unspecified eye','Maladies de l''œil et de ses annexes','H33.129'),
('autre retinoschisis and retinal cysts, right eye','Other retinoschisis and retinal cysts, right eye','Maladies de l''œil et de ses annexes','H33.191'),
('autre retinoschisis and retinal cysts, left eye','Other retinoschisis and retinal cysts, left eye','Maladies de l''œil et de ses annexes','H33.192'),
('autre retinoschisis and retinal cysts, bilateral','Other retinoschisis and retinal cysts, bilateral','Maladies de l''œil et de ses annexes','H33.193'),
('autre retinoschisis and retinal cysts, non spécifié eye','Other retinoschisis and retinal cysts, unspecified eye','Maladies de l''œil et de ses annexes','H33.199'),
('Serous retinal detachment, non spécifié eye','Serous retinal detachment, unspecified eye','Maladies de l''œil et de ses annexes','H33.20'),
('Serous retinal detachment, right eye','Serous retinal detachment, right eye','Maladies de l''œil et de ses annexes','H33.21'),
('Serous retinal detachment, left eye','Serous retinal detachment, left eye','Maladies de l''œil et de ses annexes','H33.22'),
('Serous retinal detachment, bilateral','Serous retinal detachment, bilateral','Maladies de l''œil et de ses annexes','H33.23'),
('non spécifié retinal break, right eye','Unspecified retinal break, right eye','Maladies de l''œil et de ses annexes','H33.301'),
('non spécifié retinal break, left eye','Unspecified retinal break, left eye','Maladies de l''œil et de ses annexes','H33.302'),
('non spécifié retinal break, bilateral','Unspecified retinal break, bilateral','Maladies de l''œil et de ses annexes','H33.303'),
('non spécifié retinal break, non spécifié eye','Unspecified retinal break, unspecified eye','Maladies de l''œil et de ses annexes','H33.309'),
('Horseshoe tear of retina without detachment, right eye','Horseshoe tear of retina without detachment, right eye','Maladies de l''œil et de ses annexes','H33.311'),
('Horseshoe tear of retina without detachment, left eye','Horseshoe tear of retina without detachment, left eye','Maladies de l''œil et de ses annexes','H33.312'),
('Horseshoe tear of retina without detachment, bilateral','Horseshoe tear of retina without detachment, bilateral','Maladies de l''œil et de ses annexes','H33.313'),
('Horseshoe tear of retina without detachment, non spécifié eye','Horseshoe tear of retina without detachment, unspecified eye','Maladies de l''œil et de ses annexes','H33.319'),
('Round hole, right eye','Round hole, right eye','Maladies de l''œil et de ses annexes','H33.321'),
('Round hole, left eye','Round hole, left eye','Maladies de l''œil et de ses annexes','H33.322'),
('Round hole, bilateral','Round hole, bilateral','Maladies de l''œil et de ses annexes','H33.323'),
('Round hole, non spécifié eye','Round hole, unspecified eye','Maladies de l''œil et de ses annexes','H33.329'),
('Multiple defects of retina without detachment, right eye','Multiple defects of retina without detachment, right eye','Maladies de l''œil et de ses annexes','H33.331'),
('Multiple defects of retina without detachment, left eye','Multiple defects of retina without detachment, left eye','Maladies de l''œil et de ses annexes','H33.332'),
('Multiple defects of retina without detachment, bilateral','Multiple defects of retina without detachment, bilateral','Maladies de l''œil et de ses annexes','H33.333'),
('Multiple defects of retina without detachment, non spécifié eye','Multiple defects of retina without detachment, unspecified eye','Maladies de l''œil et de ses annexes','H33.339'),
('Traction detachment of retina, non spécifié eye','Traction detachment of retina, unspecified eye','Maladies de l''œil et de ses annexes','H33.40'),
('Traction detachment of retina, right eye','Traction detachment of retina, right eye','Maladies de l''œil et de ses annexes','H33.41'),
('Traction detachment of retina, left eye','Traction detachment of retina, left eye','Maladies de l''œil et de ses annexes','H33.42'),
('Traction detachment of retina, bilateral','Traction detachment of retina, bilateral','Maladies de l''œil et de ses annexes','H33.43'),
('autre retinal detachments','Other retinal detachments','Maladies de l''œil et de ses annexes','H33.8'),
('Transient retinal artery occlusion, non spécifié eye','Transient retinal artery occlusion, unspecified eye','Maladies de l''œil et de ses annexes','H34.00'),
('Transient retinal artery occlusion, right eye','Transient retinal artery occlusion, right eye','Maladies de l''œil et de ses annexes','H34.01'),
('Transient retinal artery occlusion, left eye','Transient retinal artery occlusion, left eye','Maladies de l''œil et de ses annexes','H34.02'),
('Transient retinal artery occlusion, bilateral','Transient retinal artery occlusion, bilateral','Maladies de l''œil et de ses annexes','H34.03'),
('Central retinal artery occlusion, non spécifié eye','Central retinal artery occlusion, unspecified eye','Maladies de l''œil et de ses annexes','H34.10'),
('Central retinal artery occlusion, right eye','Central retinal artery occlusion, right eye','Maladies de l''œil et de ses annexes','H34.11'),
('Central retinal artery occlusion, left eye','Central retinal artery occlusion, left eye','Maladies de l''œil et de ses annexes','H34.12'),
('Central retinal artery occlusion, bilateral','Central retinal artery occlusion, bilateral','Maladies de l''œil et de ses annexes','H34.13'),
('Partial retinal artery occlusion, right eye','Partial retinal artery occlusion, right eye','Maladies de l''œil et de ses annexes','H34.211'),
('Partial retinal artery occlusion, left eye','Partial retinal artery occlusion, left eye','Maladies de l''œil et de ses annexes','H34.212'),
('Partial retinal artery occlusion, bilateral','Partial retinal artery occlusion, bilateral','Maladies de l''œil et de ses annexes','H34.213'),
('Partial retinal artery occlusion, non spécifié eye','Partial retinal artery occlusion, unspecified eye','Maladies de l''œil et de ses annexes','H34.219'),
('Retinal artery branch occlusion, right eye','Retinal artery branch occlusion, right eye','Maladies de l''œil et de ses annexes','H34.231'),
('Retinal artery branch occlusion, left eye','Retinal artery branch occlusion, left eye','Maladies de l''œil et de ses annexes','H34.232'),
('Retinal artery branch occlusion, bilateral','Retinal artery branch occlusion, bilateral','Maladies de l''œil et de ses annexes','H34.233'),
('Retinal artery branch occlusion, non spécifié eye','Retinal artery branch occlusion, unspecified eye','Maladies de l''œil et de ses annexes','H34.239'),
('Central retinal vein occlusion, right eye, with macular edema','Central retinal vein occlusion, right eye, with macular edema','Maladies de l''œil et de ses annexes','H34.8110'),
('Central retinal vein occlusion, right eye, with retinal neovascularization','Central retinal vein occlusion, right eye, with retinal neovascularization','Maladies de l''œil et de ses annexes','H34.8111'),
('Central retinal vein occlusion, right eye, stable','Central retinal vein occlusion, right eye, stable','Maladies de l''œil et de ses annexes','H34.8112'),
('Central retinal vein occlusion, left eye, with macular edema','Central retinal vein occlusion, left eye, with macular edema','Maladies de l''œil et de ses annexes','H34.8120'),
('Central retinal vein occlusion, left eye, with retinal neovascularization','Central retinal vein occlusion, left eye, with retinal neovascularization','Maladies de l''œil et de ses annexes','H34.8121'),
('Central retinal vein occlusion, left eye, stable','Central retinal vein occlusion, left eye, stable','Maladies de l''œil et de ses annexes','H34.8122'),
('Central retinal vein occlusion, bilateral, with macular edema','Central retinal vein occlusion, bilateral, with macular edema','Maladies de l''œil et de ses annexes','H34.8130'),
('Central retinal vein occlusion, bilateral, with retinal neovascularization','Central retinal vein occlusion, bilateral, with retinal neovascularization','Maladies de l''œil et de ses annexes','H34.8131'),
('Central retinal vein occlusion, bilateral, stable','Central retinal vein occlusion, bilateral, stable','Maladies de l''œil et de ses annexes','H34.8132'),
('Central retinal vein occlusion, non spécifié eye, with macular edema','Central retinal vein occlusion, unspecified eye, with macular edema','Maladies de l''œil et de ses annexes','H34.8190'),
('Central retinal vein occlusion, non spécifié eye, with retinal neovascularization','Central retinal vein occlusion, unspecified eye, with retinal neovascularization','Maladies de l''œil et de ses annexes','H34.8191'),
('Central retinal vein occlusion, non spécifié eye, stable','Central retinal vein occlusion, unspecified eye, stable','Maladies de l''œil et de ses annexes','H34.8192'),
('Venous engorgement, right eye','Venous engorgement, right eye','Maladies de l''œil et de ses annexes','H34.821'),
('Venous engorgement, left eye','Venous engorgement, left eye','Maladies de l''œil et de ses annexes','H34.822'),
('Venous engorgement, bilateral','Venous engorgement, bilateral','Maladies de l''œil et de ses annexes','H34.823'),
('Venous engorgement, non spécifié eye','Venous engorgement, unspecified eye','Maladies de l''œil et de ses annexes','H34.829'),
('Tributary (branch) retinal vein occlusion, right eye, with macular edema','Tributary (branch) retinal vein occlusion, right eye, with macular edema','Maladies de l''œil et de ses annexes','H34.8310'),
('Tributary (branch) retinal vein occlusion, right eye, with retinal neovascularization','Tributary (branch) retinal vein occlusion, right eye, with retinal neovascularization','Maladies de l''œil et de ses annexes','H34.8311'),
('Tributary (branch) retinal vein occlusion, right eye, stable','Tributary (branch) retinal vein occlusion, right eye, stable','Maladies de l''œil et de ses annexes','H34.8312'),
('Tributary (branch) retinal vein occlusion, left eye, with macular edema','Tributary (branch) retinal vein occlusion, left eye, with macular edema','Maladies de l''œil et de ses annexes','H34.8320'),
('Tributary (branch) retinal vein occlusion, left eye, with retinal neovascularization','Tributary (branch) retinal vein occlusion, left eye, with retinal neovascularization','Maladies de l''œil et de ses annexes','H34.8321'),
('Tributary (branch) retinal vein occlusion, left eye, stable','Tributary (branch) retinal vein occlusion, left eye, stable','Maladies de l''œil et de ses annexes','H34.8322'),
('Tributary (branch) retinal vein occlusion, bilateral, with macular edema','Tributary (branch) retinal vein occlusion, bilateral, with macular edema','Maladies de l''œil et de ses annexes','H34.8330'),
('Tributary (branch) retinal vein occlusion, bilateral, with retinal neovascularization','Tributary (branch) retinal vein occlusion, bilateral, with retinal neovascularization','Maladies de l''œil et de ses annexes','H34.8331'),
('Tributary (branch) retinal vein occlusion, bilateral, stable','Tributary (branch) retinal vein occlusion, bilateral, stable','Maladies de l''œil et de ses annexes','H34.8332'),
('Tributary (branch) retinal vein occlusion, non spécifié eye, with macular edema','Tributary (branch) retinal vein occlusion, unspecified eye, with macular edema','Maladies de l''œil et de ses annexes','H34.8390'),
('Tributary (branch) retinal vein occlusion, non spécifié eye, with retinal neovascularization','Tributary (branch) retinal vein occlusion, unspecified eye, with retinal neovascularization','Maladies de l''œil et de ses annexes','H34.8391'),
('Tributary (branch) retinal vein occlusion, non spécifié eye, stable','Tributary (branch) retinal vein occlusion, unspecified eye, stable','Maladies de l''œil et de ses annexes','H34.8392'),
('non spécifié retinal vascular occlusion','Unspecified retinal vascular occlusion','Maladies de l''œil et de ses annexes','H34.9'),
('non spécifié background retinopathy','Unspecified background retinopathy','Maladies de l''œil et de ses annexes','H35.00')
ON CONFLICT (nom_fr) DO NOTHING;
