-- icd10v2_batch_217.sql (80 rows)
INSERT INTO pathologies (nom_fr, nom_en, categorie, icd10_code)
VALUES
('Female pelvic peritonitis, non spécifié','Female pelvic peritonitis, unspecified','Maladies de l''appareil génito-urinaire','N73.5'),
('Female pelvic peritoneal adhesions (postinfective)','Female pelvic peritoneal adhesions (postinfective)','Maladies de l''appareil génito-urinaire','N73.6'),
('autre specified female pelvic inflammatory diseases','Other specified female pelvic inflammatory diseases','Maladies de l''appareil génito-urinaire','N73.8'),
('Female pelvic inflammatory maladie, non spécifié','Female pelvic inflammatory disease, unspecified','Maladies de l''appareil génito-urinaire','N73.9'),
('Female pelvic inflammatory disorders in diseases classified elsewhere','Female pelvic inflammatory disorders in diseases classified elsewhere','Maladies de l''appareil génito-urinaire','N74'),
('Cyst of Bartholin''s gland','Cyst of Bartholin''s gland','Maladies de l''appareil génito-urinaire','N75.0'),
('Abscess of Bartholin''s gland','Abscess of Bartholin''s gland','Maladies de l''appareil génito-urinaire','N75.1'),
('autre diseases of Bartholin''s gland','Other diseases of Bartholin''s gland','Maladies de l''appareil génito-urinaire','N75.8'),
('maladie of Bartholin''s gland, non spécifié','Disease of Bartholin''s gland, unspecified','Maladies de l''appareil génito-urinaire','N75.9'),
('aigu vaginitis','Acute vaginitis','Maladies de l''appareil génito-urinaire','N76.0'),
('Subacute and chronique vaginitis','Subacute and chronic vaginitis','Maladies de l''appareil génito-urinaire','N76.1'),
('aigu vulvitis','Acute vulvitis','Maladies de l''appareil génito-urinaire','N76.2'),
('Subacute and chronique vulvitis','Subacute and chronic vulvitis','Maladies de l''appareil génito-urinaire','N76.3'),
('Abscess of vulva','Abscess of vulva','Maladies de l''appareil génito-urinaire','N76.4'),
('Ulceration of vagina','Ulceration of vagina','Maladies de l''appareil génito-urinaire','N76.5'),
('Ulceration of vulva','Ulceration of vulva','Maladies de l''appareil génito-urinaire','N76.6'),
('Mucositis (ulcerative) of vagina and vulva','Mucositis (ulcerative) of vagina and vulva','Maladies de l''appareil génito-urinaire','N76.81'),
('Fournier maladie of vagina and vulva','Fournier disease of vagina and vulva','Maladies de l''appareil génito-urinaire','N76.82'),
('autre specified inflammation of vagina and vulva','Other specified inflammation of vagina and vulva','Maladies de l''appareil génito-urinaire','N76.89'),
('Ulceration of vulva in diseases classified elsewhere','Ulceration of vulva in diseases classified elsewhere','Maladies de l''appareil génito-urinaire','N77.0'),
('Vaginitis, vulvitis and vulvovaginitis in diseases classified elsewhere','Vaginitis, vulvitis and vulvovaginitis in diseases classified elsewhere','Maladies de l''appareil génito-urinaire','N77.1'),
('Endometriosis of the uterus, non spécifié','Endometriosis of the uterus, unspecified','Maladies de l''appareil génito-urinaire','N80.00'),
('Superficial endometriosis of the uterus','Superficial endometriosis of the uterus','Maladies de l''appareil génito-urinaire','N80.01'),
('Deep endometriosis of the uterus','Deep endometriosis of the uterus','Maladies de l''appareil génito-urinaire','N80.02'),
('Adenomyosis of the uterus','Adenomyosis of the uterus','Maladies de l''appareil génito-urinaire','N80.03'),
('Endometriosis of right ovary, non spécifié depth','Endometriosis of right ovary, unspecified depth','Maladies de l''appareil génito-urinaire','N80.101'),
('Endometriosis of left ovary, non spécifié depth','Endometriosis of left ovary, unspecified depth','Maladies de l''appareil génito-urinaire','N80.102'),
('Endometriosis of bilateral ovaries, non spécifié depth','Endometriosis of bilateral ovaries, unspecified depth','Maladies de l''appareil génito-urinaire','N80.103'),
('Endometriosis of ovary, non spécifié side, non spécifié depth','Endometriosis of ovary, unspecified side, unspecified depth','Maladies de l''appareil génito-urinaire','N80.109'),
('Superficial endometriosis of right ovary','Superficial endometriosis of right ovary','Maladies de l''appareil génito-urinaire','N80.111'),
('Superficial endometriosis of left ovary','Superficial endometriosis of left ovary','Maladies de l''appareil génito-urinaire','N80.112'),
('Superficial endometriosis of bilateral ovaries','Superficial endometriosis of bilateral ovaries','Maladies de l''appareil génito-urinaire','N80.113'),
('Superficial endometriosis of ovary, non spécifié ovary','Superficial endometriosis of ovary, unspecified ovary','Maladies de l''appareil génito-urinaire','N80.119'),
('Deep endometriosis of right ovary','Deep endometriosis of right ovary','Maladies de l''appareil génito-urinaire','N80.121'),
('Deep endometriosis of left ovary','Deep endometriosis of left ovary','Maladies de l''appareil génito-urinaire','N80.122'),
('Deep endometriosis of bilateral ovaries','Deep endometriosis of bilateral ovaries','Maladies de l''appareil génito-urinaire','N80.123'),
('Deep endometriosis of ovary, non spécifié ovary','Deep endometriosis of ovary, unspecified ovary','Maladies de l''appareil génito-urinaire','N80.129'),
('Endometriosis of right fallopian tube, non spécifié depth','Endometriosis of right fallopian tube, unspecified depth','Maladies de l''appareil génito-urinaire','N80.201'),
('Endometriosis of left fallopian tube, non spécifié depth','Endometriosis of left fallopian tube, unspecified depth','Maladies de l''appareil génito-urinaire','N80.202'),
('Endometriosis of bilateral fallopian tubes, non spécifié depth','Endometriosis of bilateral fallopian tubes, unspecified depth','Maladies de l''appareil génito-urinaire','N80.203'),
('Endometriosis of non spécifié fallopian tube, non spécifié depth','Endometriosis of unspecified fallopian tube, unspecified depth','Maladies de l''appareil génito-urinaire','N80.209'),
('Superficial endometriosis of right fallopian tube','Superficial endometriosis of right fallopian tube','Maladies de l''appareil génito-urinaire','N80.211'),
('Superficial endometriosis of left fallopian tube','Superficial endometriosis of left fallopian tube','Maladies de l''appareil génito-urinaire','N80.212'),
('Superficial endometriosis of bilateral fallopian tubes','Superficial endometriosis of bilateral fallopian tubes','Maladies de l''appareil génito-urinaire','N80.213'),
('Superficial endometriosis of non spécifié fallopian tube','Superficial endometriosis of unspecified fallopian tube','Maladies de l''appareil génito-urinaire','N80.219'),
('Deep endometriosis of right fallopian tube','Deep endometriosis of right fallopian tube','Maladies de l''appareil génito-urinaire','N80.221'),
('Deep endometriosis of left fallopian tube','Deep endometriosis of left fallopian tube','Maladies de l''appareil génito-urinaire','N80.222'),
('Deep endometriosis of bilateral fallopian tubes','Deep endometriosis of bilateral fallopian tubes','Maladies de l''appareil génito-urinaire','N80.223'),
('Deep endometriosis of non spécifié fallopian tube','Deep endometriosis of unspecified fallopian tube','Maladies de l''appareil génito-urinaire','N80.229'),
('Endometriosis of pelvic peritoneum, non spécifié','Endometriosis of pelvic peritoneum, unspecified','Maladies de l''appareil génito-urinaire','N80.30'),
('Superficial endometriosis of the anterior cul-de-sac','Superficial endometriosis of the anterior cul-de-sac','Maladies de l''appareil génito-urinaire','N80.311'),
('Deep endometriosis of the anterior cul-de-sac','Deep endometriosis of the anterior cul-de-sac','Maladies de l''appareil génito-urinaire','N80.312'),
('Endometriosis of the anterior cul-de-sac, non spécifié depth','Endometriosis of the anterior cul-de-sac, unspecified depth','Maladies de l''appareil génito-urinaire','N80.319'),
('Superficial endometriosis of the posterior cul-de-sac','Superficial endometriosis of the posterior cul-de-sac','Maladies de l''appareil génito-urinaire','N80.321'),
('Deep endometriosis of the posterior cul-de-sac','Deep endometriosis of the posterior cul-de-sac','Maladies de l''appareil génito-urinaire','N80.322'),
('Endometriosis of the posterior cul-de-sac, non spécifié depth','Endometriosis of the posterior cul-de-sac, unspecified depth','Maladies de l''appareil génito-urinaire','N80.329'),
('Superficial endometriosis of the right pelvic sidewall','Superficial endometriosis of the right pelvic sidewall','Maladies de l''appareil génito-urinaire','N80.331'),
('Superficial endometriosis of the left pelvic sidewall','Superficial endometriosis of the left pelvic sidewall','Maladies de l''appareil génito-urinaire','N80.332'),
('Superficial endometriosis of bilateral pelvic sidewall','Superficial endometriosis of bilateral pelvic sidewall','Maladies de l''appareil génito-urinaire','N80.333'),
('Superficial endometriosis of pelvic sidewall, non spécifié side','Superficial endometriosis of pelvic sidewall, unspecified side','Maladies de l''appareil génito-urinaire','N80.339'),
('Deep endometriosis of the right pelvic sidewall','Deep endometriosis of the right pelvic sidewall','Maladies de l''appareil génito-urinaire','N80.341'),
('Deep endometriosis of the left pelvic sidewall','Deep endometriosis of the left pelvic sidewall','Maladies de l''appareil génito-urinaire','N80.342'),
('Deep endometriosis of the bilateral pelvic sidewall','Deep endometriosis of the bilateral pelvic sidewall','Maladies de l''appareil génito-urinaire','N80.343'),
('Deep endometriosis of the pelvic sidewall, non spécifié side','Deep endometriosis of the pelvic sidewall, unspecified side','Maladies de l''appareil génito-urinaire','N80.349'),
('Endometriosis of the right pelvic sidewall, non spécifié depth','Endometriosis of the right pelvic sidewall, unspecified depth','Maladies de l''appareil génito-urinaire','N80.351'),
('Endometriosis of the left pelvic sidewall, non spécifié depth','Endometriosis of the left pelvic sidewall, unspecified depth','Maladies de l''appareil génito-urinaire','N80.352'),
('Endometriosis of bilateral pelvic sidewall, non spécifié depth','Endometriosis of bilateral pelvic sidewall, unspecified depth','Maladies de l''appareil génito-urinaire','N80.353'),
('Endometriosis of pelvic sidewall, non spécifié side, non spécifié depth','Endometriosis of pelvic sidewall, unspecified side, unspecified depth','Maladies de l''appareil génito-urinaire','N80.359'),
('Superficial endometriosis of the right pelvic brim','Superficial endometriosis of the right pelvic brim','Maladies de l''appareil génito-urinaire','N80.361'),
('Superficial endometriosis of the left pelvic brim','Superficial endometriosis of the left pelvic brim','Maladies de l''appareil génito-urinaire','N80.362'),
('Superficial endometriosis of bilateral pelvic brim','Superficial endometriosis of bilateral pelvic brim','Maladies de l''appareil génito-urinaire','N80.363'),
('Superficial endometriosis of the pelvic brim, non spécifié side','Superficial endometriosis of the pelvic brim, unspecified side','Maladies de l''appareil génito-urinaire','N80.369'),
('Deep endometriosis of the right pelvic brim','Deep endometriosis of the right pelvic brim','Maladies de l''appareil génito-urinaire','N80.371'),
('Deep endometriosis of the left pelvic brim','Deep endometriosis of the left pelvic brim','Maladies de l''appareil génito-urinaire','N80.372'),
('Deep endometriosis of bilateral pelvic brim','Deep endometriosis of bilateral pelvic brim','Maladies de l''appareil génito-urinaire','N80.373'),
('Deep endometriosis of the pelvic brim, non spécifié side','Deep endometriosis of the pelvic brim, unspecified side','Maladies de l''appareil génito-urinaire','N80.379'),
('Endometriosis of the right pelvic brim, non spécifié depth','Endometriosis of the right pelvic brim, unspecified depth','Maladies de l''appareil génito-urinaire','N80.381'),
('Endometriosis of the left pelvic brim, non spécifié depth','Endometriosis of the left pelvic brim, unspecified depth','Maladies de l''appareil génito-urinaire','N80.382'),
('Endometriosis of bilateral pelvic brim, non spécifié depth','Endometriosis of bilateral pelvic brim, unspecified depth','Maladies de l''appareil génito-urinaire','N80.383'),
('Endometriosis of the pelvic brim, non spécifié side, non spécifié depth','Endometriosis of the pelvic brim, unspecified side, unspecified depth','Maladies de l''appareil génito-urinaire','N80.389')
ON CONFLICT (nom_fr) DO NOTHING;
