-- icd10v2_batch_001.sql (80 rows)
INSERT INTO pathologies (nom_fr, nom_en, categorie, icd10_code)
VALUES
('Cholera due to Vibrio cholerae 01, biovar cholerae','Cholera due to Vibrio cholerae 01, biovar cholerae','Maladies infectieuses et parasitaires','A00.0'),
('Cholera due to Vibrio cholerae 01, biovar eltor','Cholera due to Vibrio cholerae 01, biovar eltor','Maladies infectieuses et parasitaires','A00.1'),
('Cholera, non spécifié','Cholera, unspecified','Maladies infectieuses et parasitaires','A00.9'),
('Typhoid fever, non spécifié','Typhoid fever, unspecified','Maladies infectieuses et parasitaires','A01.00'),
('Typhoid meningitis','Typhoid meningitis','Maladies infectieuses et parasitaires','A01.01'),
('Typhoid fever with heart involvement','Typhoid fever with heart involvement','Maladies infectieuses et parasitaires','A01.02'),
('Typhoid pneumonia','Typhoid pneumonia','Maladies infectieuses et parasitaires','A01.03'),
('Typhoid arthritis','Typhoid arthritis','Maladies infectieuses et parasitaires','A01.04'),
('Typhoid osteomyelitis','Typhoid osteomyelitis','Maladies infectieuses et parasitaires','A01.05'),
('Typhoid fever with autre complications','Typhoid fever with other complications','Maladies infectieuses et parasitaires','A01.09'),
('Paratyphoid fever A','Paratyphoid fever A','Maladies infectieuses et parasitaires','A01.1'),
('Paratyphoid fever B','Paratyphoid fever B','Maladies infectieuses et parasitaires','A01.2'),
('Paratyphoid fever C','Paratyphoid fever C','Maladies infectieuses et parasitaires','A01.3'),
('Paratyphoid fever, non spécifié','Paratyphoid fever, unspecified','Maladies infectieuses et parasitaires','A01.4'),
('Salmonella enteritis','Salmonella enteritis','Maladies infectieuses et parasitaires','A02.0'),
('Salmonella sepsis','Salmonella sepsis','Maladies infectieuses et parasitaires','A02.1'),
('Localized salmonella infection, non spécifié','Localized salmonella infection, unspecified','Maladies infectieuses et parasitaires','A02.20'),
('Salmonella meningitis','Salmonella meningitis','Maladies infectieuses et parasitaires','A02.21'),
('Salmonella pneumonia','Salmonella pneumonia','Maladies infectieuses et parasitaires','A02.22'),
('Salmonella arthritis','Salmonella arthritis','Maladies infectieuses et parasitaires','A02.23'),
('Salmonella osteomyelitis','Salmonella osteomyelitis','Maladies infectieuses et parasitaires','A02.24'),
('Salmonella pyelonephritis','Salmonella pyelonephritis','Maladies infectieuses et parasitaires','A02.25'),
('Salmonella with autre localized infection','Salmonella with other localized infection','Maladies infectieuses et parasitaires','A02.29'),
('autre specified salmonella infections','Other specified salmonella infections','Maladies infectieuses et parasitaires','A02.8'),
('Salmonella infection, non spécifié','Salmonella infection, unspecified','Maladies infectieuses et parasitaires','A02.9'),
('Shigellosis due to Shigella dysenteriae','Shigellosis due to Shigella dysenteriae','Maladies infectieuses et parasitaires','A03.0'),
('Shigellosis due to Shigella flexneri','Shigellosis due to Shigella flexneri','Maladies infectieuses et parasitaires','A03.1'),
('Shigellosis due to Shigella boydii','Shigellosis due to Shigella boydii','Maladies infectieuses et parasitaires','A03.2'),
('Shigellosis due to Shigella sonnei','Shigellosis due to Shigella sonnei','Maladies infectieuses et parasitaires','A03.3'),
('autre shigellosis','Other shigellosis','Maladies infectieuses et parasitaires','A03.8'),
('Shigellosis, non spécifié','Shigellosis, unspecified','Maladies infectieuses et parasitaires','A03.9'),
('Enteropathogenic Escherichia coli infection','Enteropathogenic Escherichia coli infection','Maladies infectieuses et parasitaires','A04.0'),
('Enterotoxigenic Escherichia coli infection','Enterotoxigenic Escherichia coli infection','Maladies infectieuses et parasitaires','A04.1'),
('Enteroinvasive Escherichia coli infection','Enteroinvasive Escherichia coli infection','Maladies infectieuses et parasitaires','A04.2'),
('Enterohemorrhagic Escherichia coli infection','Enterohemorrhagic Escherichia coli infection','Maladies infectieuses et parasitaires','A04.3'),
('autre intestinal Escherichia coli infections','Other intestinal Escherichia coli infections','Maladies infectieuses et parasitaires','A04.4'),
('Campylobacter enteritis','Campylobacter enteritis','Maladies infectieuses et parasitaires','A04.5'),
('Enteritis due to Yersinia enterocolitica','Enteritis due to Yersinia enterocolitica','Maladies infectieuses et parasitaires','A04.6'),
('Enterocolitis due to Clostridium difficile, recurrent','Enterocolitis due to Clostridium difficile, recurrent','Maladies infectieuses et parasitaires','A04.71'),
('Enterocolitis due to Clostridium difficile, not specified as recurrent','Enterocolitis due to Clostridium difficile, not specified as recurrent','Maladies infectieuses et parasitaires','A04.72'),
('autre specified bacterial intestinal infections','Other specified bacterial intestinal infections','Maladies infectieuses et parasitaires','A04.8'),
('Bacterial intestinal infection, non spécifié','Bacterial intestinal infection, unspecified','Maladies infectieuses et parasitaires','A04.9'),
('Foodborne staphylococcal intoxication','Foodborne staphylococcal intoxication','Maladies infectieuses et parasitaires','A05.0'),
('Botulism food poisoning','Botulism food poisoning','Maladies infectieuses et parasitaires','A05.1'),
('Foodborne Clostridium perfringens [Clostridium welchii] intoxication','Foodborne Clostridium perfringens [Clostridium welchii] intoxication','Maladies infectieuses et parasitaires','A05.2'),
('Foodborne Vibrio parahaemolyticus intoxication','Foodborne Vibrio parahaemolyticus intoxication','Maladies infectieuses et parasitaires','A05.3'),
('Foodborne Bacillus cereus intoxication','Foodborne Bacillus cereus intoxication','Maladies infectieuses et parasitaires','A05.4'),
('Foodborne Vibrio vulnificus intoxication','Foodborne Vibrio vulnificus intoxication','Maladies infectieuses et parasitaires','A05.5'),
('autre specified bacterial foodborne intoxications','Other specified bacterial foodborne intoxications','Maladies infectieuses et parasitaires','A05.8'),
('Bacterial foodborne intoxication, non spécifié','Bacterial foodborne intoxication, unspecified','Maladies infectieuses et parasitaires','A05.9'),
('aigu amebic dysentery','Acute amebic dysentery','Maladies infectieuses et parasitaires','A06.0'),
('chronique intestinal amebiasis','Chronic intestinal amebiasis','Maladies infectieuses et parasitaires','A06.1'),
('Amebic nondysenteric colitis','Amebic nondysenteric colitis','Maladies infectieuses et parasitaires','A06.2'),
('Ameboma of intestine','Ameboma of intestine','Maladies infectieuses et parasitaires','A06.3'),
('Amebic liver abscess','Amebic liver abscess','Maladies infectieuses et parasitaires','A06.4'),
('Amebic lung abscess','Amebic lung abscess','Maladies infectieuses et parasitaires','A06.5'),
('Amebic brain abscess','Amebic brain abscess','Maladies infectieuses et parasitaires','A06.6'),
('Cutaneous amebiasis','Cutaneous amebiasis','Maladies infectieuses et parasitaires','A06.7'),
('Amebic cystitis','Amebic cystitis','Maladies infectieuses et parasitaires','A06.81'),
('autre amebic genitourinary infections','Other amebic genitourinary infections','Maladies infectieuses et parasitaires','A06.82'),
('autre amebic infections','Other amebic infections','Maladies infectieuses et parasitaires','A06.89'),
('Amebiasis, non spécifié','Amebiasis, unspecified','Maladies infectieuses et parasitaires','A06.9'),
('Balantidiasis','Balantidiasis','Maladies infectieuses et parasitaires','A07.0'),
('Giardiasis [lambliasis]','Giardiasis [lambliasis]','Maladies infectieuses et parasitaires','A07.1'),
('Cryptosporidiosis','Cryptosporidiosis','Maladies infectieuses et parasitaires','A07.2'),
('Isosporiasis','Isosporiasis','Maladies infectieuses et parasitaires','A07.3'),
('Cyclosporiasis','Cyclosporiasis','Maladies infectieuses et parasitaires','A07.4'),
('autre specified protozoal intestinal diseases','Other specified protozoal intestinal diseases','Maladies infectieuses et parasitaires','A07.8'),
('Protozoal intestinal maladie, non spécifié','Protozoal intestinal disease, unspecified','Maladies infectieuses et parasitaires','A07.9'),
('Rotaviral enteritis','Rotaviral enteritis','Maladies infectieuses et parasitaires','A08.0'),
('aigu gastroenteropathy due to Norwalk agent','Acute gastroenteropathy due to Norwalk agent','Maladies infectieuses et parasitaires','A08.11'),
('aigu gastroenteropathy due to autre small round viruses','Acute gastroenteropathy due to other small round viruses','Maladies infectieuses et parasitaires','A08.19'),
('Adenoviral enteritis','Adenoviral enteritis','Maladies infectieuses et parasitaires','A08.2'),
('Calicivirus enteritis','Calicivirus enteritis','Maladies infectieuses et parasitaires','A08.31'),
('Astrovirus enteritis','Astrovirus enteritis','Maladies infectieuses et parasitaires','A08.32'),
('autre viral enteritis','Other viral enteritis','Maladies infectieuses et parasitaires','A08.39'),
('Viral intestinal infection, non spécifié','Viral intestinal infection, unspecified','Maladies infectieuses et parasitaires','A08.4'),
('autre specified intestinal infections','Other specified intestinal infections','Maladies infectieuses et parasitaires','A08.8'),
('Infectious gastroenteritis and colitis, non spécifié','Infectious gastroenteritis and colitis, unspecified','Maladies infectieuses et parasitaires','A09'),
('CACNA1A-related neurodevelopmental trouble','CACNA1A-related neurodevelopmental disorder','Malformations congénitales et anomalies chromosomiques','QA0.0102')
ON CONFLICT (nom_fr) DO NOTHING;
