-- icd10v2_batch_063.sql (80 rows)
INSERT INTO pathologies (nom_fr, nom_en, categorie, icd10_code)
VALUES
('Bipolar II trouble','Bipolar II disorder','Troubles mentaux et du comportement','F31.81'),
('autre bipolar trouble','Other bipolar disorder','Troubles mentaux et du comportement','F31.89'),
('Trouble bipolaire, unspecified','Bipolar disorder, unspecified','Troubles mentaux et du comportement','F31.9'),
('Trouble dépressif majeur, single episode, mild','Major depressive disorder, single episode, mild','Troubles mentaux et du comportement','F32.0'),
('Trouble dépressif majeur, single episode, moderate','Major depressive disorder, single episode, moderate','Troubles mentaux et du comportement','F32.1'),
('Trouble dépressif majeur, single episode, severe without psychotic features','Major depressive disorder, single episode, severe without psychotic features','Troubles mentaux et du comportement','F32.2'),
('Trouble dépressif majeur, single episode, severe with psychotic features','Major depressive disorder, single episode, severe with psychotic features','Troubles mentaux et du comportement','F32.3'),
('Trouble dépressif majeur, single episode, in partial remission','Major depressive disorder, single episode, in partial remission','Troubles mentaux et du comportement','F32.4'),
('Trouble dépressif majeur, single episode, in full remission','Major depressive disorder, single episode, in full remission','Troubles mentaux et du comportement','F32.5'),
('Premenstrual dysphoric trouble','Premenstrual dysphoric disorder','Troubles mentaux et du comportement','F32.81'),
('autre specified depressive episodes','Other specified depressive episodes','Troubles mentaux et du comportement','F32.89'),
('Trouble dépressif majeur, single episode, unspecified','Major depressive disorder, single episode, unspecified','Troubles mentaux et du comportement','F32.9'),
('Depression, non spécifié','Depression, unspecified','Troubles mentaux et du comportement','F32.A'),
('Trouble dépressif majeur, recurrent, mild','Major depressive disorder, recurrent, mild','Troubles mentaux et du comportement','F33.0'),
('Trouble dépressif majeur, recurrent, moderate','Major depressive disorder, recurrent, moderate','Troubles mentaux et du comportement','F33.1'),
('Trouble dépressif majeur, recurrent severe without psychotic features','Major depressive disorder, recurrent severe without psychotic features','Troubles mentaux et du comportement','F33.2'),
('Trouble dépressif majeur, recurrent, severe with psychotic symptoms','Major depressive disorder, recurrent, severe with psychotic symptoms','Troubles mentaux et du comportement','F33.3'),
('Trouble dépressif majeur, recurrent, in remission, unspecified','Major depressive disorder, recurrent, in remission, unspecified','Troubles mentaux et du comportement','F33.40'),
('Trouble dépressif majeur, recurrent, in partial remission','Major depressive disorder, recurrent, in partial remission','Troubles mentaux et du comportement','F33.41'),
('Trouble dépressif majeur, recurrent, in full remission','Major depressive disorder, recurrent, in full remission','Troubles mentaux et du comportement','F33.42'),
('autre recurrent depressive disorders','Other recurrent depressive disorders','Troubles mentaux et du comportement','F33.8'),
('Trouble dépressif majeur, recurrent, unspecified','Major depressive disorder, recurrent, unspecified','Troubles mentaux et du comportement','F33.9'),
('Cyclothymic trouble','Cyclothymic disorder','Troubles mentaux et du comportement','F34.0'),
('Dysthymic trouble','Dysthymic disorder','Troubles mentaux et du comportement','F34.1'),
('Disruptive mood dysregulation trouble','Disruptive mood dysregulation disorder','Troubles mentaux et du comportement','F34.81'),
('autre specified persistent mood disorders','Other specified persistent mood disorders','Troubles mentaux et du comportement','F34.89'),
('Persistent mood [affective] trouble, non spécifié','Persistent mood [affective] disorder, unspecified','Troubles mentaux et du comportement','F34.9'),
('non spécifié mood [affective] trouble','Unspecified mood [affective] disorder','Troubles mentaux et du comportement','F39'),
('Agoraphobia, non spécifié','Agoraphobia, unspecified','Troubles mentaux et du comportement','F40.00'),
('Agoraphobia with panic trouble','Agoraphobia with panic disorder','Troubles mentaux et du comportement','F40.01'),
('Agoraphobia without panic trouble','Agoraphobia without panic disorder','Troubles mentaux et du comportement','F40.02'),
('Social phobia, non spécifié','Social phobia, unspecified','Troubles mentaux et du comportement','F40.10'),
('Social phobia, generalized','Social phobia, generalized','Troubles mentaux et du comportement','F40.11'),
('Arachnophobia','Arachnophobia','Troubles mentaux et du comportement','F40.210'),
('autre animal type phobia','Other animal type phobia','Troubles mentaux et du comportement','F40.218'),
('Fear of thunderstorms','Fear of thunderstorms','Troubles mentaux et du comportement','F40.220'),
('autre natural environment type phobia','Other natural environment type phobia','Troubles mentaux et du comportement','F40.228'),
('Fear of blood','Fear of blood','Troubles mentaux et du comportement','F40.230'),
('Fear of injections and transfusions','Fear of injections and transfusions','Troubles mentaux et du comportement','F40.231'),
('Fear of autre medical care','Fear of other medical care','Troubles mentaux et du comportement','F40.232'),
('Fear of injury','Fear of injury','Troubles mentaux et du comportement','F40.233'),
('Claustrophobia','Claustrophobia','Troubles mentaux et du comportement','F40.240'),
('Acrophobia','Acrophobia','Troubles mentaux et du comportement','F40.241'),
('Fear of bridges','Fear of bridges','Troubles mentaux et du comportement','F40.242'),
('Fear of flying','Fear of flying','Troubles mentaux et du comportement','F40.243'),
('autre situational type phobia','Other situational type phobia','Troubles mentaux et du comportement','F40.248'),
('Androphobia','Androphobia','Troubles mentaux et du comportement','F40.290'),
('Gynephobia','Gynephobia','Troubles mentaux et du comportement','F40.291'),
('autre specified phobia','Other specified phobia','Troubles mentaux et du comportement','F40.298'),
('autre phobic anxiety disorders','Other phobic anxiety disorders','Troubles mentaux et du comportement','F40.8'),
('Phobic anxiety trouble, non spécifié','Phobic anxiety disorder, unspecified','Troubles mentaux et du comportement','F40.9'),
('Panic trouble [episodic paroxysmal anxiety]','Panic disorder [episodic paroxysmal anxiety]','Troubles mentaux et du comportement','F41.0'),
('Generalized anxiety trouble','Generalized anxiety disorder','Troubles mentaux et du comportement','F41.1'),
('autre mixed anxiety disorders','Other mixed anxiety disorders','Troubles mentaux et du comportement','F41.3'),
('autre specified anxiety disorders','Other specified anxiety disorders','Troubles mentaux et du comportement','F41.8'),
('Anxiety trouble, non spécifié','Anxiety disorder, unspecified','Troubles mentaux et du comportement','F41.9'),
('Mixed obsessional thoughts and acts','Mixed obsessional thoughts and acts','Troubles mentaux et du comportement','F42.2'),
('Hoarding trouble','Hoarding disorder','Troubles mentaux et du comportement','F42.3'),
('Excoriation (skin-picking) trouble','Excoriation (skin-picking) disorder','Troubles mentaux et du comportement','F42.4'),
('autre obsessive-compulsive trouble','Other obsessive-compulsive disorder','Troubles mentaux et du comportement','F42.8'),
('Obsessive-compulsive trouble, non spécifié','Obsessive-compulsive disorder, unspecified','Troubles mentaux et du comportement','F42.9'),
('aigu stress reaction','Acute stress reaction','Troubles mentaux et du comportement','F43.0'),
('Post-traumatic stress trouble, non spécifié','Post-traumatic stress disorder, unspecified','Troubles mentaux et du comportement','F43.10'),
('Post-traumatic stress trouble, aigu','Post-traumatic stress disorder, acute','Troubles mentaux et du comportement','F43.11'),
('Post-traumatic stress trouble, chronique','Post-traumatic stress disorder, chronic','Troubles mentaux et du comportement','F43.12'),
('Adjustment trouble, non spécifié','Adjustment disorder, unspecified','Troubles mentaux et du comportement','F43.20'),
('Adjustment trouble with depressed mood','Adjustment disorder with depressed mood','Troubles mentaux et du comportement','F43.21'),
('Adjustment trouble with anxiety','Adjustment disorder with anxiety','Troubles mentaux et du comportement','F43.22'),
('Adjustment trouble with mixed anxiety and depressed mood','Adjustment disorder with mixed anxiety and depressed mood','Troubles mentaux et du comportement','F43.23'),
('Adjustment trouble with disturbance of conduct','Adjustment disorder with disturbance of conduct','Troubles mentaux et du comportement','F43.24'),
('Adjustment trouble with mixed disturbance of emotions and conduct','Adjustment disorder with mixed disturbance of emotions and conduct','Troubles mentaux et du comportement','F43.25'),
('Adjustment trouble with autre symptoms','Adjustment disorder with other symptoms','Troubles mentaux et du comportement','F43.29'),
('Prolonged grief trouble','Prolonged grief disorder','Troubles mentaux et du comportement','F43.81'),
('autre reactions to severe stress','Other reactions to severe stress','Troubles mentaux et du comportement','F43.89'),
('Reaction to severe stress, non spécifié','Reaction to severe stress, unspecified','Troubles mentaux et du comportement','F43.9'),
('Dissociative amnesia','Dissociative amnesia','Troubles mentaux et du comportement','F44.0'),
('Dissociative fugue','Dissociative fugue','Troubles mentaux et du comportement','F44.1'),
('Dissociative stupor','Dissociative stupor','Troubles mentaux et du comportement','F44.2'),
('Conversion trouble with motor symptom or deficit','Conversion disorder with motor symptom or deficit','Troubles mentaux et du comportement','F44.4'),
('Conversion trouble with seizures or convulsions','Conversion disorder with seizures or convulsions','Troubles mentaux et du comportement','F44.5')
ON CONFLICT (nom_fr) DO NOTHING;
