-- icd10v2_batch_156.sql (80 rows)
INSERT INTO pathologies (nom_fr, nom_en, categorie, icd10_code)
VALUES
('Pressure ulcer of right hip, stage 3','Pressure ulcer of right hip, stage 3','Maladies de la peau et du tissu cellulaire sous-cutané','L89.213'),
('Pressure ulcer of right hip, stage 4','Pressure ulcer of right hip, stage 4','Maladies de la peau et du tissu cellulaire sous-cutané','L89.214'),
('Pressure-induced deep tissue damage of right hip','Pressure-induced deep tissue damage of right hip','Maladies de la peau et du tissu cellulaire sous-cutané','L89.216'),
('Pressure ulcer of right hip, non spécifié stage','Pressure ulcer of right hip, unspecified stage','Maladies de la peau et du tissu cellulaire sous-cutané','L89.219'),
('Pressure ulcer of left hip, unstageable','Pressure ulcer of left hip, unstageable','Maladies de la peau et du tissu cellulaire sous-cutané','L89.220'),
('Pressure ulcer of left hip, stage 1','Pressure ulcer of left hip, stage 1','Maladies de la peau et du tissu cellulaire sous-cutané','L89.221'),
('Pressure ulcer of left hip, stage 2','Pressure ulcer of left hip, stage 2','Maladies de la peau et du tissu cellulaire sous-cutané','L89.222'),
('Pressure ulcer of left hip, stage 3','Pressure ulcer of left hip, stage 3','Maladies de la peau et du tissu cellulaire sous-cutané','L89.223'),
('Pressure ulcer of left hip, stage 4','Pressure ulcer of left hip, stage 4','Maladies de la peau et du tissu cellulaire sous-cutané','L89.224'),
('Pressure-induced deep tissue damage of left hip','Pressure-induced deep tissue damage of left hip','Maladies de la peau et du tissu cellulaire sous-cutané','L89.226'),
('Pressure ulcer of left hip, non spécifié stage','Pressure ulcer of left hip, unspecified stage','Maladies de la peau et du tissu cellulaire sous-cutané','L89.229'),
('Pressure ulcer of non spécifié buttock, unstageable','Pressure ulcer of unspecified buttock, unstageable','Maladies de la peau et du tissu cellulaire sous-cutané','L89.300'),
('Pressure ulcer of non spécifié buttock, stage 1','Pressure ulcer of unspecified buttock, stage 1','Maladies de la peau et du tissu cellulaire sous-cutané','L89.301'),
('Pressure ulcer of non spécifié buttock, stage 2','Pressure ulcer of unspecified buttock, stage 2','Maladies de la peau et du tissu cellulaire sous-cutané','L89.302'),
('Pressure ulcer of non spécifié buttock, stage 3','Pressure ulcer of unspecified buttock, stage 3','Maladies de la peau et du tissu cellulaire sous-cutané','L89.303'),
('Pressure ulcer of non spécifié buttock, stage 4','Pressure ulcer of unspecified buttock, stage 4','Maladies de la peau et du tissu cellulaire sous-cutané','L89.304'),
('Pressure-induced deep tissue damage of non spécifié buttock','Pressure-induced deep tissue damage of unspecified buttock','Maladies de la peau et du tissu cellulaire sous-cutané','L89.306'),
('Pressure ulcer of non spécifié buttock, non spécifié stage','Pressure ulcer of unspecified buttock, unspecified stage','Maladies de la peau et du tissu cellulaire sous-cutané','L89.309'),
('Pressure ulcer of right buttock, unstageable','Pressure ulcer of right buttock, unstageable','Maladies de la peau et du tissu cellulaire sous-cutané','L89.310'),
('Pressure ulcer of right buttock, stage 1','Pressure ulcer of right buttock, stage 1','Maladies de la peau et du tissu cellulaire sous-cutané','L89.311'),
('Pressure ulcer of right buttock, stage 2','Pressure ulcer of right buttock, stage 2','Maladies de la peau et du tissu cellulaire sous-cutané','L89.312'),
('Pressure ulcer of right buttock, stage 3','Pressure ulcer of right buttock, stage 3','Maladies de la peau et du tissu cellulaire sous-cutané','L89.313'),
('Pressure ulcer of right buttock, stage 4','Pressure ulcer of right buttock, stage 4','Maladies de la peau et du tissu cellulaire sous-cutané','L89.314'),
('Pressure-induced deep tissue damage of right buttock','Pressure-induced deep tissue damage of right buttock','Maladies de la peau et du tissu cellulaire sous-cutané','L89.316'),
('Pressure ulcer of right buttock, non spécifié stage','Pressure ulcer of right buttock, unspecified stage','Maladies de la peau et du tissu cellulaire sous-cutané','L89.319'),
('Pressure ulcer of left buttock, unstageable','Pressure ulcer of left buttock, unstageable','Maladies de la peau et du tissu cellulaire sous-cutané','L89.320'),
('Pressure ulcer of left buttock, stage 1','Pressure ulcer of left buttock, stage 1','Maladies de la peau et du tissu cellulaire sous-cutané','L89.321'),
('Pressure ulcer of left buttock, stage 2','Pressure ulcer of left buttock, stage 2','Maladies de la peau et du tissu cellulaire sous-cutané','L89.322'),
('Pressure ulcer of left buttock, stage 3','Pressure ulcer of left buttock, stage 3','Maladies de la peau et du tissu cellulaire sous-cutané','L89.323'),
('Pressure ulcer of left buttock, stage 4','Pressure ulcer of left buttock, stage 4','Maladies de la peau et du tissu cellulaire sous-cutané','L89.324'),
('Pressure-induced deep tissue damage of left buttock','Pressure-induced deep tissue damage of left buttock','Maladies de la peau et du tissu cellulaire sous-cutané','L89.326'),
('Pressure ulcer of left buttock, non spécifié stage','Pressure ulcer of left buttock, unspecified stage','Maladies de la peau et du tissu cellulaire sous-cutané','L89.329'),
('Pressure ulcer of contiguous site of back, buttock and hip, non spécifié stage','Pressure ulcer of contiguous site of back, buttock and hip, unspecified stage','Maladies de la peau et du tissu cellulaire sous-cutané','L89.40'),
('Pressure ulcer of contiguous site of back, buttock and hip, stage 1','Pressure ulcer of contiguous site of back, buttock and hip, stage 1','Maladies de la peau et du tissu cellulaire sous-cutané','L89.41'),
('Pressure ulcer of contiguous site of back, buttock and hip, stage 2','Pressure ulcer of contiguous site of back, buttock and hip, stage 2','Maladies de la peau et du tissu cellulaire sous-cutané','L89.42'),
('Pressure ulcer of contiguous site of back, buttock and hip, stage 3','Pressure ulcer of contiguous site of back, buttock and hip, stage 3','Maladies de la peau et du tissu cellulaire sous-cutané','L89.43'),
('Pressure ulcer of contiguous site of back, buttock and hip, stage 4','Pressure ulcer of contiguous site of back, buttock and hip, stage 4','Maladies de la peau et du tissu cellulaire sous-cutané','L89.44'),
('Pressure ulcer of contiguous site of back, buttock and hip, unstageable','Pressure ulcer of contiguous site of back, buttock and hip, unstageable','Maladies de la peau et du tissu cellulaire sous-cutané','L89.45'),
('Pressure-induced deep tissue damage of contiguous site of back, buttock and hip','Pressure-induced deep tissue damage of contiguous site of back, buttock and hip','Maladies de la peau et du tissu cellulaire sous-cutané','L89.46'),
('Pressure ulcer of non spécifié ankle, unstageable','Pressure ulcer of unspecified ankle, unstageable','Maladies de la peau et du tissu cellulaire sous-cutané','L89.500'),
('Pressure ulcer of non spécifié ankle, stage 1','Pressure ulcer of unspecified ankle, stage 1','Maladies de la peau et du tissu cellulaire sous-cutané','L89.501'),
('Pressure ulcer of non spécifié ankle, stage 2','Pressure ulcer of unspecified ankle, stage 2','Maladies de la peau et du tissu cellulaire sous-cutané','L89.502'),
('Pressure ulcer of non spécifié ankle, stage 3','Pressure ulcer of unspecified ankle, stage 3','Maladies de la peau et du tissu cellulaire sous-cutané','L89.503'),
('Pressure ulcer of non spécifié ankle, stage 4','Pressure ulcer of unspecified ankle, stage 4','Maladies de la peau et du tissu cellulaire sous-cutané','L89.504'),
('Pressure-induced deep tissue damage of non spécifié ankle','Pressure-induced deep tissue damage of unspecified ankle','Maladies de la peau et du tissu cellulaire sous-cutané','L89.506'),
('Pressure ulcer of non spécifié ankle, non spécifié stage','Pressure ulcer of unspecified ankle, unspecified stage','Maladies de la peau et du tissu cellulaire sous-cutané','L89.509'),
('Pressure ulcer of right ankle, unstageable','Pressure ulcer of right ankle, unstageable','Maladies de la peau et du tissu cellulaire sous-cutané','L89.510'),
('Pressure ulcer of right ankle, stage 1','Pressure ulcer of right ankle, stage 1','Maladies de la peau et du tissu cellulaire sous-cutané','L89.511'),
('Pressure ulcer of right ankle, stage 2','Pressure ulcer of right ankle, stage 2','Maladies de la peau et du tissu cellulaire sous-cutané','L89.512'),
('Pressure ulcer of right ankle, stage 3','Pressure ulcer of right ankle, stage 3','Maladies de la peau et du tissu cellulaire sous-cutané','L89.513'),
('Pressure ulcer of right ankle, stage 4','Pressure ulcer of right ankle, stage 4','Maladies de la peau et du tissu cellulaire sous-cutané','L89.514'),
('Pressure-induced deep tissue damage of right ankle','Pressure-induced deep tissue damage of right ankle','Maladies de la peau et du tissu cellulaire sous-cutané','L89.516'),
('Pressure ulcer of right ankle, non spécifié stage','Pressure ulcer of right ankle, unspecified stage','Maladies de la peau et du tissu cellulaire sous-cutané','L89.519'),
('Pressure ulcer of left ankle, unstageable','Pressure ulcer of left ankle, unstageable','Maladies de la peau et du tissu cellulaire sous-cutané','L89.520'),
('Pressure ulcer of left ankle, stage 1','Pressure ulcer of left ankle, stage 1','Maladies de la peau et du tissu cellulaire sous-cutané','L89.521'),
('Pressure ulcer of left ankle, stage 2','Pressure ulcer of left ankle, stage 2','Maladies de la peau et du tissu cellulaire sous-cutané','L89.522'),
('Pressure ulcer of left ankle, stage 3','Pressure ulcer of left ankle, stage 3','Maladies de la peau et du tissu cellulaire sous-cutané','L89.523'),
('Pressure ulcer of left ankle, stage 4','Pressure ulcer of left ankle, stage 4','Maladies de la peau et du tissu cellulaire sous-cutané','L89.524'),
('Pressure-induced deep tissue damage of left ankle','Pressure-induced deep tissue damage of left ankle','Maladies de la peau et du tissu cellulaire sous-cutané','L89.526'),
('Pressure ulcer of left ankle, non spécifié stage','Pressure ulcer of left ankle, unspecified stage','Maladies de la peau et du tissu cellulaire sous-cutané','L89.529'),
('Pressure ulcer of non spécifié heel, unstageable','Pressure ulcer of unspecified heel, unstageable','Maladies de la peau et du tissu cellulaire sous-cutané','L89.600'),
('Pressure ulcer of non spécifié heel, stage 1','Pressure ulcer of unspecified heel, stage 1','Maladies de la peau et du tissu cellulaire sous-cutané','L89.601'),
('Pressure ulcer of non spécifié heel, stage 2','Pressure ulcer of unspecified heel, stage 2','Maladies de la peau et du tissu cellulaire sous-cutané','L89.602'),
('Pressure ulcer of non spécifié heel, stage 3','Pressure ulcer of unspecified heel, stage 3','Maladies de la peau et du tissu cellulaire sous-cutané','L89.603'),
('Pressure ulcer of non spécifié heel, stage 4','Pressure ulcer of unspecified heel, stage 4','Maladies de la peau et du tissu cellulaire sous-cutané','L89.604'),
('Pressure-induced deep tissue damage of non spécifié heel','Pressure-induced deep tissue damage of unspecified heel','Maladies de la peau et du tissu cellulaire sous-cutané','L89.606'),
('Pressure ulcer of non spécifié heel, non spécifié stage','Pressure ulcer of unspecified heel, unspecified stage','Maladies de la peau et du tissu cellulaire sous-cutané','L89.609'),
('Pressure ulcer of right heel, unstageable','Pressure ulcer of right heel, unstageable','Maladies de la peau et du tissu cellulaire sous-cutané','L89.610'),
('Pressure ulcer of right heel, stage 1','Pressure ulcer of right heel, stage 1','Maladies de la peau et du tissu cellulaire sous-cutané','L89.611'),
('Pressure ulcer of right heel, stage 2','Pressure ulcer of right heel, stage 2','Maladies de la peau et du tissu cellulaire sous-cutané','L89.612'),
('Pressure ulcer of right heel, stage 3','Pressure ulcer of right heel, stage 3','Maladies de la peau et du tissu cellulaire sous-cutané','L89.613'),
('Pressure ulcer of right heel, stage 4','Pressure ulcer of right heel, stage 4','Maladies de la peau et du tissu cellulaire sous-cutané','L89.614'),
('Pressure-induced deep tissue damage of right heel','Pressure-induced deep tissue damage of right heel','Maladies de la peau et du tissu cellulaire sous-cutané','L89.616'),
('Pressure ulcer of right heel, non spécifié stage','Pressure ulcer of right heel, unspecified stage','Maladies de la peau et du tissu cellulaire sous-cutané','L89.619'),
('Pressure ulcer of left heel, unstageable','Pressure ulcer of left heel, unstageable','Maladies de la peau et du tissu cellulaire sous-cutané','L89.620'),
('Pressure ulcer of left heel, stage 1','Pressure ulcer of left heel, stage 1','Maladies de la peau et du tissu cellulaire sous-cutané','L89.621'),
('Pressure ulcer of left heel, stage 2','Pressure ulcer of left heel, stage 2','Maladies de la peau et du tissu cellulaire sous-cutané','L89.622'),
('Pressure ulcer of left heel, stage 3','Pressure ulcer of left heel, stage 3','Maladies de la peau et du tissu cellulaire sous-cutané','L89.623'),
('Pressure ulcer of left heel, stage 4','Pressure ulcer of left heel, stage 4','Maladies de la peau et du tissu cellulaire sous-cutané','L89.624'),
('Pressure-induced deep tissue damage of left heel','Pressure-induced deep tissue damage of left heel','Maladies de la peau et du tissu cellulaire sous-cutané','L89.626')
ON CONFLICT (nom_fr) DO NOTHING;
