-- icd10v2_batch_246.sql (80 rows)
INSERT INTO pathologies (nom_fr, nom_en, categorie, icd10_code)
VALUES
('Newborn affected by maternal complication of pregnancy, non spécifié','Newborn affected by maternal complication of pregnancy, unspecified','Affections dont l''origine se situe dans la période périnatale','P01.9'),
('Newborn affected by placenta previa','Newborn affected by placenta previa','Affections dont l''origine se situe dans la période périnatale','P02.0'),
('Newborn affected by autre forms of placental separation and hémorragie','Newborn affected by other forms of placental separation and hemorrhage','Affections dont l''origine se situe dans la période périnatale','P02.1'),
('Newborn affected by non spécifié morphological and functional abnormalities of placenta','Newborn affected by unspecified morphological and functional abnormalities of placenta','Affections dont l''origine se situe dans la période périnatale','P02.20'),
('Newborn affected by autre morphological and functional abnormalities of placenta','Newborn affected by other morphological and functional abnormalities of placenta','Affections dont l''origine se situe dans la période périnatale','P02.29'),
('Newborn affected by placental transfusion syndromes','Newborn affected by placental transfusion syndromes','Affections dont l''origine se situe dans la période périnatale','P02.3'),
('Newborn affected by prolapsed cord','Newborn affected by prolapsed cord','Affections dont l''origine se situe dans la période périnatale','P02.4'),
('Newborn affected by autre compression of umbilical cord','Newborn affected by other compression of umbilical cord','Affections dont l''origine se situe dans la période périnatale','P02.5'),
('Newborn affected by non spécifié conditions of umbilical cord','Newborn affected by unspecified conditions of umbilical cord','Affections dont l''origine se situe dans la période périnatale','P02.60'),
('Newborn affected by autre conditions of umbilical cord','Newborn affected by other conditions of umbilical cord','Affections dont l''origine se situe dans la période périnatale','P02.69'),
('Newborn affected by fetal inflammatory response syndrome','Newborn affected by fetal inflammatory response syndrome','Affections dont l''origine se situe dans la période périnatale','P02.70'),
('Newborn affected by autre conditions from chorioamnionitis','Newborn affected by other conditions from chorioamnionitis','Affections dont l''origine se situe dans la période périnatale','P02.78'),
('Newborn affected by autre abnormalities of membranes','Newborn affected by other abnormalities of membranes','Affections dont l''origine se situe dans la période périnatale','P02.8'),
('Newborn affected by abnormality of membranes, non spécifié','Newborn affected by abnormality of membranes, unspecified','Affections dont l''origine se situe dans la période périnatale','P02.9'),
('Newborn affected by breech delivery and extraction','Newborn affected by breech delivery and extraction','Affections dont l''origine se situe dans la période périnatale','P03.0'),
('Newborn affected by autre malpresentation, malposition and disproportion during labor and delivery','Newborn affected by other malpresentation, malposition and disproportion during labor and delivery','Affections dont l''origine se situe dans la période périnatale','P03.1'),
('Newborn affected by forceps delivery','Newborn affected by forceps delivery','Affections dont l''origine se situe dans la période périnatale','P03.2'),
('Newborn affected by delivery by vacuum extractor [ventouse]','Newborn affected by delivery by vacuum extractor [ventouse]','Affections dont l''origine se situe dans la période périnatale','P03.3'),
('Newborn affected by Cesarean delivery','Newborn affected by Cesarean delivery','Affections dont l''origine se situe dans la période périnatale','P03.4'),
('Newborn affected by precipitate delivery','Newborn affected by precipitate delivery','Affections dont l''origine se situe dans la période périnatale','P03.5'),
('Newborn affected by abnormal uterine contractions','Newborn affected by abnormal uterine contractions','Affections dont l''origine se situe dans la période périnatale','P03.6'),
('Newborn affected by abnormality in fetal (intrauterine) heart rate or rhythm before the onset of labor','Newborn affected by abnormality in fetal (intrauterine) heart rate or rhythm before the onset of labor','Affections dont l''origine se situe dans la période périnatale','P03.810'),
('Newborn affected by abnormality in fetal (intrauterine) heart rate or rhythm during labor','Newborn affected by abnormality in fetal (intrauterine) heart rate or rhythm during labor','Affections dont l''origine se situe dans la période périnatale','P03.811'),
('Newborn affected by abnormality in fetal (intrauterine) heart rate or rhythm, non spécifié as to time of onset','Newborn affected by abnormality in fetal (intrauterine) heart rate or rhythm, unspecified as to time of onset','Affections dont l''origine se situe dans la période périnatale','P03.819'),
('Meconium passage during delivery','Meconium passage during delivery','Affections dont l''origine se situe dans la période périnatale','P03.82'),
('Newborn affected by autre specified complications of labor and delivery','Newborn affected by other specified complications of labor and delivery','Affections dont l''origine se situe dans la période périnatale','P03.89'),
('Newborn affected by complication of labor and delivery, non spécifié','Newborn affected by complication of labor and delivery, unspecified','Affections dont l''origine se situe dans la période périnatale','P03.9'),
('Newborn affected by maternal anesthesia and analgesia in pregnancy, labor and delivery','Newborn affected by maternal anesthesia and analgesia in pregnancy, labor and delivery','Affections dont l''origine se situe dans la période périnatale','P04.0'),
('Newborn affected by maternal antineoplastic chemotherapy','Newborn affected by maternal antineoplastic chemotherapy','Affections dont l''origine se situe dans la période périnatale','P04.11'),
('Newborn affected by maternal cytotoxic drugs','Newborn affected by maternal cytotoxic drugs','Affections dont l''origine se situe dans la période périnatale','P04.12'),
('Newborn affected by maternal use of anticonvulsants','Newborn affected by maternal use of anticonvulsants','Affections dont l''origine se situe dans la période périnatale','P04.13'),
('Newborn affected by maternal use of opiates','Newborn affected by maternal use of opiates','Affections dont l''origine se situe dans la période périnatale','P04.14'),
('Newborn affected by maternal use of antidepressants','Newborn affected by maternal use of antidepressants','Affections dont l''origine se situe dans la période périnatale','P04.15'),
('Newborn affected by maternal use of amphetamines','Newborn affected by maternal use of amphetamines','Affections dont l''origine se situe dans la période périnatale','P04.16'),
('Newborn affected by maternal use of sedative-hypnotics','Newborn affected by maternal use of sedative-hypnotics','Affections dont l''origine se situe dans la période périnatale','P04.17'),
('Newborn affected by maternal use of anxiolytics','Newborn affected by maternal use of anxiolytics','Affections dont l''origine se situe dans la période périnatale','P04.1A'),
('Newborn affected by autre maternal medication','Newborn affected by other maternal medication','Affections dont l''origine se situe dans la période périnatale','P04.18'),
('Newborn affected by maternal use of non spécifié medication','Newborn affected by maternal use of unspecified medication','Affections dont l''origine se situe dans la période périnatale','P04.19'),
('Newborn affected by maternal use of tobacco','Newborn affected by maternal use of tobacco','Affections dont l''origine se situe dans la période périnatale','P04.2'),
('Newborn affected by maternal use of alcohol','Newborn affected by maternal use of alcohol','Affections dont l''origine se situe dans la période périnatale','P04.3'),
('Newborn affected by maternal use of non spécifié drugs of addiction','Newborn affected by maternal use of unspecified drugs of addiction','Affections dont l''origine se situe dans la période périnatale','P04.40'),
('Newborn affected by maternal use of cocaine','Newborn affected by maternal use of cocaine','Affections dont l''origine se situe dans la période périnatale','P04.41'),
('Newborn affected by maternal use of hallucinogens','Newborn affected by maternal use of hallucinogens','Affections dont l''origine se situe dans la période périnatale','P04.42'),
('Newborn affected by maternal use of autre drugs of addiction','Newborn affected by maternal use of other drugs of addiction','Affections dont l''origine se situe dans la période périnatale','P04.49'),
('Newborn affected by maternal use of nutritional chemical substances','Newborn affected by maternal use of nutritional chemical substances','Affections dont l''origine se situe dans la période périnatale','P04.5'),
('Newborn affected by maternal exposure to environmental chemical substances','Newborn affected by maternal exposure to environmental chemical substances','Affections dont l''origine se situe dans la période périnatale','P04.6'),
('Newborn affected by maternal use of cannabis','Newborn affected by maternal use of cannabis','Affections dont l''origine se situe dans la période périnatale','P04.81'),
('Newborn affected by autre maternal noxious substances','Newborn affected by other maternal noxious substances','Affections dont l''origine se situe dans la période périnatale','P04.89'),
('Newborn affected by maternal noxious substance, non spécifié','Newborn affected by maternal noxious substance, unspecified','Affections dont l''origine se situe dans la période périnatale','P04.9'),
('Newborn light for gestational age, non spécifié weight','Newborn light for gestational age, unspecified weight','Affections dont l''origine se situe dans la période périnatale','P05.00'),
('Newborn light for gestational age, less than 500 grams','Newborn light for gestational age, less than 500 grams','Affections dont l''origine se situe dans la période périnatale','P05.01'),
('Newborn light for gestational age, 500-749 grams','Newborn light for gestational age, 500-749 grams','Affections dont l''origine se situe dans la période périnatale','P05.02'),
('Newborn light for gestational age, 750-999 grams','Newborn light for gestational age, 750-999 grams','Affections dont l''origine se situe dans la période périnatale','P05.03'),
('Newborn light for gestational age, 1000-1249 grams','Newborn light for gestational age, 1000-1249 grams','Affections dont l''origine se situe dans la période périnatale','P05.04'),
('Newborn light for gestational age, 1250-1499 grams','Newborn light for gestational age, 1250-1499 grams','Affections dont l''origine se situe dans la période périnatale','P05.05'),
('Newborn light for gestational age, 1500-1749 grams','Newborn light for gestational age, 1500-1749 grams','Affections dont l''origine se situe dans la période périnatale','P05.06'),
('Newborn light for gestational age, 1750-1999 grams','Newborn light for gestational age, 1750-1999 grams','Affections dont l''origine se situe dans la période périnatale','P05.07'),
('Newborn light for gestational age, 2000-2499 grams','Newborn light for gestational age, 2000-2499 grams','Affections dont l''origine se situe dans la période périnatale','P05.08'),
('Newborn light for gestational age, 2500 grams and over','Newborn light for gestational age, 2500 grams and over','Affections dont l''origine se situe dans la période périnatale','P05.09'),
('Newborn small for gestational age, non spécifié weight','Newborn small for gestational age, unspecified weight','Affections dont l''origine se situe dans la période périnatale','P05.10'),
('Newborn small for gestational age, less than 500 grams','Newborn small for gestational age, less than 500 grams','Affections dont l''origine se situe dans la période périnatale','P05.11'),
('Newborn small for gestational age, 500-749 grams','Newborn small for gestational age, 500-749 grams','Affections dont l''origine se situe dans la période périnatale','P05.12'),
('Newborn small for gestational age, 750-999 grams','Newborn small for gestational age, 750-999 grams','Affections dont l''origine se situe dans la période périnatale','P05.13'),
('Newborn small for gestational age, 1000-1249 grams','Newborn small for gestational age, 1000-1249 grams','Affections dont l''origine se situe dans la période périnatale','P05.14'),
('Newborn small for gestational age, 1250-1499 grams','Newborn small for gestational age, 1250-1499 grams','Affections dont l''origine se situe dans la période périnatale','P05.15'),
('Newborn small for gestational age, 1500-1749 grams','Newborn small for gestational age, 1500-1749 grams','Affections dont l''origine se situe dans la période périnatale','P05.16'),
('Newborn small for gestational age, 1750-1999 grams','Newborn small for gestational age, 1750-1999 grams','Affections dont l''origine se situe dans la période périnatale','P05.17'),
('Newborn small for gestational age, 2000-2499 grams','Newborn small for gestational age, 2000-2499 grams','Affections dont l''origine se situe dans la période périnatale','P05.18'),
('Newborn small for gestational age, autre','Newborn small for gestational age, other','Affections dont l''origine se situe dans la période périnatale','P05.19'),
('Newborn affected by fetal (intrauterine) malnutrition not light or small for gestational age','Newborn affected by fetal (intrauterine) malnutrition not light or small for gestational age','Affections dont l''origine se situe dans la période périnatale','P05.2'),
('Newborn affected by slow intrauterine growth, non spécifié','Newborn affected by slow intrauterine growth, unspecified','Affections dont l''origine se situe dans la période périnatale','P05.9'),
('Extremely low birth weight newborn, non spécifié weight','Extremely low birth weight newborn, unspecified weight','Affections dont l''origine se situe dans la période périnatale','P07.00'),
('Extremely low birth weight newborn, less than 500 grams','Extremely low birth weight newborn, less than 500 grams','Affections dont l''origine se situe dans la période périnatale','P07.01'),
('Extremely low birth weight newborn, 500-749 grams','Extremely low birth weight newborn, 500-749 grams','Affections dont l''origine se situe dans la période périnatale','P07.02'),
('Extremely low birth weight newborn, 750-999 grams','Extremely low birth weight newborn, 750-999 grams','Affections dont l''origine se situe dans la période périnatale','P07.03'),
('autre low birth weight newborn, non spécifié weight','Other low birth weight newborn, unspecified weight','Affections dont l''origine se situe dans la période périnatale','P07.10'),
('autre low birth weight newborn, 1000-1249 grams','Other low birth weight newborn, 1000-1249 grams','Affections dont l''origine se situe dans la période périnatale','P07.14'),
('autre low birth weight newborn, 1250-1499 grams','Other low birth weight newborn, 1250-1499 grams','Affections dont l''origine se situe dans la période périnatale','P07.15'),
('autre low birth weight newborn, 1500-1749 grams','Other low birth weight newborn, 1500-1749 grams','Affections dont l''origine se situe dans la période périnatale','P07.16'),
('autre low birth weight newborn, 1750-1999 grams','Other low birth weight newborn, 1750-1999 grams','Affections dont l''origine se situe dans la période périnatale','P07.17')
ON CONFLICT (nom_fr) DO NOTHING;
