-- icd10v2_batch_111.sql (80 rows)
INSERT INTO pathologies (nom_fr, nom_en, categorie, icd10_code)
VALUES
('Diffuse cholesteatosis, left ear','Diffuse cholesteatosis, left ear','Maladies de l''oreille et de l''apophyse mastoïde','H71.32'),
('Diffuse cholesteatosis, bilateral','Diffuse cholesteatosis, bilateral','Maladies de l''oreille et de l''apophyse mastoïde','H71.33'),
('non spécifié cholesteatoma, non spécifié ear','Unspecified cholesteatoma, unspecified ear','Maladies de l''oreille et de l''apophyse mastoïde','H71.90'),
('non spécifié cholesteatoma, right ear','Unspecified cholesteatoma, right ear','Maladies de l''oreille et de l''apophyse mastoïde','H71.91'),
('non spécifié cholesteatoma, left ear','Unspecified cholesteatoma, left ear','Maladies de l''oreille et de l''apophyse mastoïde','H71.92'),
('non spécifié cholesteatoma, bilateral','Unspecified cholesteatoma, bilateral','Maladies de l''oreille et de l''apophyse mastoïde','H71.93'),
('Central perforation of tympanic membrane, non spécifié ear','Central perforation of tympanic membrane, unspecified ear','Maladies de l''oreille et de l''apophyse mastoïde','H72.00'),
('Central perforation of tympanic membrane, right ear','Central perforation of tympanic membrane, right ear','Maladies de l''oreille et de l''apophyse mastoïde','H72.01'),
('Central perforation of tympanic membrane, left ear','Central perforation of tympanic membrane, left ear','Maladies de l''oreille et de l''apophyse mastoïde','H72.02'),
('Central perforation of tympanic membrane, bilateral','Central perforation of tympanic membrane, bilateral','Maladies de l''oreille et de l''apophyse mastoïde','H72.03'),
('Attic perforation of tympanic membrane, non spécifié ear','Attic perforation of tympanic membrane, unspecified ear','Maladies de l''oreille et de l''apophyse mastoïde','H72.10'),
('Attic perforation of tympanic membrane, right ear','Attic perforation of tympanic membrane, right ear','Maladies de l''oreille et de l''apophyse mastoïde','H72.11'),
('Attic perforation of tympanic membrane, left ear','Attic perforation of tympanic membrane, left ear','Maladies de l''oreille et de l''apophyse mastoïde','H72.12'),
('Attic perforation of tympanic membrane, bilateral','Attic perforation of tympanic membrane, bilateral','Maladies de l''oreille et de l''apophyse mastoïde','H72.13'),
('autre marginal perforations of tympanic membrane, right ear','Other marginal perforations of tympanic membrane, right ear','Maladies de l''oreille et de l''apophyse mastoïde','H72.2X1'),
('autre marginal perforations of tympanic membrane, left ear','Other marginal perforations of tympanic membrane, left ear','Maladies de l''oreille et de l''apophyse mastoïde','H72.2X2'),
('autre marginal perforations of tympanic membrane, bilateral','Other marginal perforations of tympanic membrane, bilateral','Maladies de l''oreille et de l''apophyse mastoïde','H72.2X3'),
('autre marginal perforations of tympanic membrane, non spécifié ear','Other marginal perforations of tympanic membrane, unspecified ear','Maladies de l''oreille et de l''apophyse mastoïde','H72.2X9'),
('Multiple perforations of tympanic membrane, right ear','Multiple perforations of tympanic membrane, right ear','Maladies de l''oreille et de l''apophyse mastoïde','H72.811'),
('Multiple perforations of tympanic membrane, left ear','Multiple perforations of tympanic membrane, left ear','Maladies de l''oreille et de l''apophyse mastoïde','H72.812'),
('Multiple perforations of tympanic membrane, bilateral','Multiple perforations of tympanic membrane, bilateral','Maladies de l''oreille et de l''apophyse mastoïde','H72.813'),
('Multiple perforations of tympanic membrane, non spécifié ear','Multiple perforations of tympanic membrane, unspecified ear','Maladies de l''oreille et de l''apophyse mastoïde','H72.819'),
('Total perforations of tympanic membrane, right ear','Total perforations of tympanic membrane, right ear','Maladies de l''oreille et de l''apophyse mastoïde','H72.821'),
('Total perforations of tympanic membrane, left ear','Total perforations of tympanic membrane, left ear','Maladies de l''oreille et de l''apophyse mastoïde','H72.822'),
('Total perforations of tympanic membrane, bilateral','Total perforations of tympanic membrane, bilateral','Maladies de l''oreille et de l''apophyse mastoïde','H72.823'),
('Total perforations of tympanic membrane, non spécifié ear','Total perforations of tympanic membrane, unspecified ear','Maladies de l''oreille et de l''apophyse mastoïde','H72.829'),
('non spécifié perforation of tympanic membrane, non spécifié ear','Unspecified perforation of tympanic membrane, unspecified ear','Maladies de l''oreille et de l''apophyse mastoïde','H72.90'),
('non spécifié perforation of tympanic membrane, right ear','Unspecified perforation of tympanic membrane, right ear','Maladies de l''oreille et de l''apophyse mastoïde','H72.91'),
('non spécifié perforation of tympanic membrane, left ear','Unspecified perforation of tympanic membrane, left ear','Maladies de l''oreille et de l''apophyse mastoïde','H72.92'),
('non spécifié perforation of tympanic membrane, bilateral','Unspecified perforation of tympanic membrane, bilateral','Maladies de l''oreille et de l''apophyse mastoïde','H72.93'),
('aigu myringitis, right ear','Acute myringitis, right ear','Maladies de l''oreille et de l''apophyse mastoïde','H73.001'),
('aigu myringitis, left ear','Acute myringitis, left ear','Maladies de l''oreille et de l''apophyse mastoïde','H73.002'),
('aigu myringitis, bilateral','Acute myringitis, bilateral','Maladies de l''oreille et de l''apophyse mastoïde','H73.003'),
('aigu myringitis, non spécifié ear','Acute myringitis, unspecified ear','Maladies de l''oreille et de l''apophyse mastoïde','H73.009'),
('Bullous myringitis, right ear','Bullous myringitis, right ear','Maladies de l''oreille et de l''apophyse mastoïde','H73.011'),
('Bullous myringitis, left ear','Bullous myringitis, left ear','Maladies de l''oreille et de l''apophyse mastoïde','H73.012'),
('Bullous myringitis, bilateral','Bullous myringitis, bilateral','Maladies de l''oreille et de l''apophyse mastoïde','H73.013'),
('Bullous myringitis, non spécifié ear','Bullous myringitis, unspecified ear','Maladies de l''oreille et de l''apophyse mastoïde','H73.019'),
('autre aigu myringitis, right ear','Other acute myringitis, right ear','Maladies de l''oreille et de l''apophyse mastoïde','H73.091'),
('autre aigu myringitis, left ear','Other acute myringitis, left ear','Maladies de l''oreille et de l''apophyse mastoïde','H73.092'),
('autre aigu myringitis, bilateral','Other acute myringitis, bilateral','Maladies de l''oreille et de l''apophyse mastoïde','H73.093'),
('autre aigu myringitis, non spécifié ear','Other acute myringitis, unspecified ear','Maladies de l''oreille et de l''apophyse mastoïde','H73.099'),
('chronique myringitis, non spécifié ear','Chronic myringitis, unspecified ear','Maladies de l''oreille et de l''apophyse mastoïde','H73.10'),
('chronique myringitis, right ear','Chronic myringitis, right ear','Maladies de l''oreille et de l''apophyse mastoïde','H73.11'),
('chronique myringitis, left ear','Chronic myringitis, left ear','Maladies de l''oreille et de l''apophyse mastoïde','H73.12'),
('chronique myringitis, bilateral','Chronic myringitis, bilateral','Maladies de l''oreille et de l''apophyse mastoïde','H73.13'),
('non spécifié myringitis, non spécifié ear','Unspecified myringitis, unspecified ear','Maladies de l''oreille et de l''apophyse mastoïde','H73.20'),
('non spécifié myringitis, right ear','Unspecified myringitis, right ear','Maladies de l''oreille et de l''apophyse mastoïde','H73.21'),
('non spécifié myringitis, left ear','Unspecified myringitis, left ear','Maladies de l''oreille et de l''apophyse mastoïde','H73.22'),
('non spécifié myringitis, bilateral','Unspecified myringitis, bilateral','Maladies de l''oreille et de l''apophyse mastoïde','H73.23'),
('Atrophic flaccid tympanic membrane, right ear','Atrophic flaccid tympanic membrane, right ear','Maladies de l''oreille et de l''apophyse mastoïde','H73.811'),
('Atrophic flaccid tympanic membrane, left ear','Atrophic flaccid tympanic membrane, left ear','Maladies de l''oreille et de l''apophyse mastoïde','H73.812'),
('Atrophic flaccid tympanic membrane, bilateral','Atrophic flaccid tympanic membrane, bilateral','Maladies de l''oreille et de l''apophyse mastoïde','H73.813'),
('Atrophic flaccid tympanic membrane, non spécifié ear','Atrophic flaccid tympanic membrane, unspecified ear','Maladies de l''oreille et de l''apophyse mastoïde','H73.819'),
('Atrophic nonflaccid tympanic membrane, right ear','Atrophic nonflaccid tympanic membrane, right ear','Maladies de l''oreille et de l''apophyse mastoïde','H73.821'),
('Atrophic nonflaccid tympanic membrane, left ear','Atrophic nonflaccid tympanic membrane, left ear','Maladies de l''oreille et de l''apophyse mastoïde','H73.822'),
('Atrophic nonflaccid tympanic membrane, bilateral','Atrophic nonflaccid tympanic membrane, bilateral','Maladies de l''oreille et de l''apophyse mastoïde','H73.823'),
('Atrophic nonflaccid tympanic membrane, non spécifié ear','Atrophic nonflaccid tympanic membrane, unspecified ear','Maladies de l''oreille et de l''apophyse mastoïde','H73.829'),
('autre specified disorders of tympanic membrane, right ear','Other specified disorders of tympanic membrane, right ear','Maladies de l''oreille et de l''apophyse mastoïde','H73.891'),
('autre specified disorders of tympanic membrane, left ear','Other specified disorders of tympanic membrane, left ear','Maladies de l''oreille et de l''apophyse mastoïde','H73.892'),
('autre specified disorders of tympanic membrane, bilateral','Other specified disorders of tympanic membrane, bilateral','Maladies de l''oreille et de l''apophyse mastoïde','H73.893'),
('autre specified disorders of tympanic membrane, non spécifié ear','Other specified disorders of tympanic membrane, unspecified ear','Maladies de l''oreille et de l''apophyse mastoïde','H73.899'),
('non spécifié trouble of tympanic membrane, non spécifié ear','Unspecified disorder of tympanic membrane, unspecified ear','Maladies de l''oreille et de l''apophyse mastoïde','H73.90'),
('non spécifié trouble of tympanic membrane, right ear','Unspecified disorder of tympanic membrane, right ear','Maladies de l''oreille et de l''apophyse mastoïde','H73.91'),
('non spécifié trouble of tympanic membrane, left ear','Unspecified disorder of tympanic membrane, left ear','Maladies de l''oreille et de l''apophyse mastoïde','H73.92'),
('non spécifié trouble of tympanic membrane, bilateral','Unspecified disorder of tympanic membrane, bilateral','Maladies de l''oreille et de l''apophyse mastoïde','H73.93'),
('Tympanosclerosis, right ear','Tympanosclerosis, right ear','Maladies de l''oreille et de l''apophyse mastoïde','H74.01'),
('Tympanosclerosis, left ear','Tympanosclerosis, left ear','Maladies de l''oreille et de l''apophyse mastoïde','H74.02'),
('Tympanosclerosis, bilateral','Tympanosclerosis, bilateral','Maladies de l''oreille et de l''apophyse mastoïde','H74.03'),
('Tympanosclerosis, non spécifié ear','Tympanosclerosis, unspecified ear','Maladies de l''oreille et de l''apophyse mastoïde','H74.09'),
('Adhesive right middle ear maladie','Adhesive right middle ear disease','Maladies de l''oreille et de l''apophyse mastoïde','H74.11'),
('Adhesive left middle ear maladie','Adhesive left middle ear disease','Maladies de l''oreille et de l''apophyse mastoïde','H74.12'),
('Adhesive middle ear maladie, bilateral','Adhesive middle ear disease, bilateral','Maladies de l''oreille et de l''apophyse mastoïde','H74.13'),
('Adhesive middle ear maladie, non spécifié ear','Adhesive middle ear disease, unspecified ear','Maladies de l''oreille et de l''apophyse mastoïde','H74.19'),
('Discontinuity and dislocation of ear ossicles, non spécifié ear','Discontinuity and dislocation of ear ossicles, unspecified ear','Maladies de l''oreille et de l''apophyse mastoïde','H74.20'),
('Discontinuity and dislocation of right ear ossicles','Discontinuity and dislocation of right ear ossicles','Maladies de l''oreille et de l''apophyse mastoïde','H74.21'),
('Discontinuity and dislocation of left ear ossicles','Discontinuity and dislocation of left ear ossicles','Maladies de l''oreille et de l''apophyse mastoïde','H74.22'),
('Discontinuity and dislocation of ear ossicles, bilateral','Discontinuity and dislocation of ear ossicles, bilateral','Maladies de l''oreille et de l''apophyse mastoïde','H74.23'),
('Ankylosis of ear ossicles, right ear','Ankylosis of ear ossicles, right ear','Maladies de l''oreille et de l''apophyse mastoïde','H74.311'),
('Ankylosis of ear ossicles, left ear','Ankylosis of ear ossicles, left ear','Maladies de l''oreille et de l''apophyse mastoïde','H74.312')
ON CONFLICT (nom_fr) DO NOTHING;
