-- icd10_batch_009.sql (80 rows)
INSERT INTO pathologies (nom_fr, nom_en, categorie, icd10_code)
VALUES
('Vascular dementia, severe, with psychotic disturbance','Vascular dementia, severe, with psychotic disturbance','Troubles mentaux et du comportement','F01.C2'),
('Vascular dementia, severe, with mood disturbance','Vascular dementia, severe, with mood disturbance','Troubles mentaux et du comportement','F01.C3'),
('Vascular dementia, severe, with anxiety','Vascular dementia, severe, with anxiety','Troubles mentaux et du comportement','F01.C4'),
('Dementia in autre diseases classified elsewhere, non spécifié severity, without behavioral disturbance, psychotic disturbance, mood disturbance, and anxiety','Dementia in other diseases classified elsewhere, unspecified severity, without behavioral disturbance, psychotic disturbance, mood disturbance, and anxiety','Troubles mentaux et du comportement','F02.80'),
('Dementia in autre diseases classified elsewhere, non spécifié severity, with agitation','Dementia in other diseases classified elsewhere, unspecified severity, with agitation','Troubles mentaux et du comportement','F02.811'),
('Dementia in autre diseases classified elsewhere, non spécifié severity, with autre behavioral disturbance','Dementia in other diseases classified elsewhere, unspecified severity, with other behavioral disturbance','Troubles mentaux et du comportement','F02.818'),
('Dementia in autre diseases classified elsewhere, non spécifié severity, with psychotic disturbance','Dementia in other diseases classified elsewhere, unspecified severity, with psychotic disturbance','Troubles mentaux et du comportement','F02.82'),
('Dementia in autre diseases classified elsewhere, non spécifié severity, with mood disturbance','Dementia in other diseases classified elsewhere, unspecified severity, with mood disturbance','Troubles mentaux et du comportement','F02.83'),
('Dementia in autre diseases classified elsewhere, non spécifié severity, with anxiety','Dementia in other diseases classified elsewhere, unspecified severity, with anxiety','Troubles mentaux et du comportement','F02.84'),
('Dementia in autre diseases classified elsewhere, mild, without behavioral disturbance, psychotic disturbance, mood disturbance, and anxiety','Dementia in other diseases classified elsewhere, mild, without behavioral disturbance, psychotic disturbance, mood disturbance, and anxiety','Troubles mentaux et du comportement','F02.A0'),
('Dementia in autre diseases classified elsewhere, mild, with agitation','Dementia in other diseases classified elsewhere, mild, with agitation','Troubles mentaux et du comportement','F02.A11'),
('Dementia in autre diseases classified elsewhere, mild, with autre behavioral disturbance','Dementia in other diseases classified elsewhere, mild, with other behavioral disturbance','Troubles mentaux et du comportement','F02.A18'),
('Dementia in autre diseases classified elsewhere, mild, with psychotic disturbance','Dementia in other diseases classified elsewhere, mild, with psychotic disturbance','Troubles mentaux et du comportement','F02.A2'),
('Dementia in autre diseases classified elsewhere, mild, with mood disturbance','Dementia in other diseases classified elsewhere, mild, with mood disturbance','Troubles mentaux et du comportement','F02.A3'),
('Dementia in autre diseases classified elsewhere, mild, with anxiety','Dementia in other diseases classified elsewhere, mild, with anxiety','Troubles mentaux et du comportement','F02.A4'),
('Dementia in autre diseases classified elsewhere, moderate, without behavioral disturbance, psychotic disturbance, mood disturbance, and anxiety','Dementia in other diseases classified elsewhere, moderate, without behavioral disturbance, psychotic disturbance, mood disturbance, and anxiety','Troubles mentaux et du comportement','F02.B0'),
('Dementia in autre diseases classified elsewhere, moderate, with agitation','Dementia in other diseases classified elsewhere, moderate, with agitation','Troubles mentaux et du comportement','F02.B11'),
('Dementia in autre diseases classified elsewhere, moderate, with autre behavioral disturbance','Dementia in other diseases classified elsewhere, moderate, with other behavioral disturbance','Troubles mentaux et du comportement','F02.B18'),
('Dementia in autre diseases classified elsewhere, moderate, with psychotic disturbance','Dementia in other diseases classified elsewhere, moderate, with psychotic disturbance','Troubles mentaux et du comportement','F02.B2'),
('Dementia in autre diseases classified elsewhere, moderate, with mood disturbance','Dementia in other diseases classified elsewhere, moderate, with mood disturbance','Troubles mentaux et du comportement','F02.B3'),
('Dementia in autre diseases classified elsewhere, moderate, with anxiety','Dementia in other diseases classified elsewhere, moderate, with anxiety','Troubles mentaux et du comportement','F02.B4'),
('Dementia in autre diseases classified elsewhere, severe, without behavioral disturbance, psychotic disturbance, mood disturbance, and anxiety','Dementia in other diseases classified elsewhere, severe, without behavioral disturbance, psychotic disturbance, mood disturbance, and anxiety','Troubles mentaux et du comportement','F02.C0'),
('Dementia in autre diseases classified elsewhere, severe, with agitation','Dementia in other diseases classified elsewhere, severe, with agitation','Troubles mentaux et du comportement','F02.C11'),
('Dementia in autre diseases classified elsewhere, severe, with autre behavioral disturbance','Dementia in other diseases classified elsewhere, severe, with other behavioral disturbance','Troubles mentaux et du comportement','F02.C18'),
('Dementia in autre diseases classified elsewhere, severe, with psychotic disturbance','Dementia in other diseases classified elsewhere, severe, with psychotic disturbance','Troubles mentaux et du comportement','F02.C2'),
('Dementia in autre diseases classified elsewhere, severe, with mood disturbance','Dementia in other diseases classified elsewhere, severe, with mood disturbance','Troubles mentaux et du comportement','F02.C3'),
('Dementia in autre diseases classified elsewhere, severe, with anxiety','Dementia in other diseases classified elsewhere, severe, with anxiety','Troubles mentaux et du comportement','F02.C4'),
('non spécifié dementia, non spécifié severity, without behavioral disturbance, psychotic disturbance, mood disturbance, and anxiety','Unspecified dementia, unspecified severity, without behavioral disturbance, psychotic disturbance, mood disturbance, and anxiety','Troubles mentaux et du comportement','F03.90'),
('non spécifié dementia, non spécifié severity, with agitation','Unspecified dementia, unspecified severity, with agitation','Troubles mentaux et du comportement','F03.911'),
('non spécifié dementia, non spécifié severity, with autre behavioral disturbance','Unspecified dementia, unspecified severity, with other behavioral disturbance','Troubles mentaux et du comportement','F03.918'),
('non spécifié dementia, non spécifié severity, with psychotic disturbance','Unspecified dementia, unspecified severity, with psychotic disturbance','Troubles mentaux et du comportement','F03.92'),
('non spécifié dementia, non spécifié severity, with mood disturbance','Unspecified dementia, unspecified severity, with mood disturbance','Troubles mentaux et du comportement','F03.93'),
('non spécifié dementia, non spécifié severity, with anxiety','Unspecified dementia, unspecified severity, with anxiety','Troubles mentaux et du comportement','F03.94'),
('non spécifié dementia, mild, without behavioral disturbance, psychotic disturbance, mood disturbance, and anxiety','Unspecified dementia, mild, without behavioral disturbance, psychotic disturbance, mood disturbance, and anxiety','Troubles mentaux et du comportement','F03.A0'),
('non spécifié dementia, mild, with agitation','Unspecified dementia, mild, with agitation','Troubles mentaux et du comportement','F03.A11'),
('non spécifié dementia, mild, with autre behavioral disturbance','Unspecified dementia, mild, with other behavioral disturbance','Troubles mentaux et du comportement','F03.A18'),
('non spécifié dementia, mild, with psychotic disturbance','Unspecified dementia, mild, with psychotic disturbance','Troubles mentaux et du comportement','F03.A2'),
('non spécifié dementia, mild, with mood disturbance','Unspecified dementia, mild, with mood disturbance','Troubles mentaux et du comportement','F03.A3'),
('non spécifié dementia, mild, with anxiety','Unspecified dementia, mild, with anxiety','Troubles mentaux et du comportement','F03.A4'),
('non spécifié dementia, moderate, without behavioral disturbance, psychotic disturbance, mood disturbance, and anxiety','Unspecified dementia, moderate, without behavioral disturbance, psychotic disturbance, mood disturbance, and anxiety','Troubles mentaux et du comportement','F03.B0'),
('non spécifié dementia, moderate, with agitation','Unspecified dementia, moderate, with agitation','Troubles mentaux et du comportement','F03.B11'),
('non spécifié dementia, moderate, with autre behavioral disturbance','Unspecified dementia, moderate, with other behavioral disturbance','Troubles mentaux et du comportement','F03.B18'),
('non spécifié dementia, moderate, with psychotic disturbance','Unspecified dementia, moderate, with psychotic disturbance','Troubles mentaux et du comportement','F03.B2'),
('non spécifié dementia, moderate, with mood disturbance','Unspecified dementia, moderate, with mood disturbance','Troubles mentaux et du comportement','F03.B3'),
('non spécifié dementia, moderate, with anxiety','Unspecified dementia, moderate, with anxiety','Troubles mentaux et du comportement','F03.B4'),
('non spécifié dementia, severe, without behavioral disturbance, psychotic disturbance, mood disturbance, and anxiety','Unspecified dementia, severe, without behavioral disturbance, psychotic disturbance, mood disturbance, and anxiety','Troubles mentaux et du comportement','F03.C0'),
('non spécifié dementia, severe, with agitation','Unspecified dementia, severe, with agitation','Troubles mentaux et du comportement','F03.C11'),
('non spécifié dementia, severe, with autre behavioral disturbance','Unspecified dementia, severe, with other behavioral disturbance','Troubles mentaux et du comportement','F03.C18'),
('Schizoaffective trouble, depressive type','Schizoaffective disorder, depressive type','Troubles mentaux et du comportement','F25.1'),
('autre schizoaffective disorders','Other schizoaffective disorders','Troubles mentaux et du comportement','F25.8'),
('Schizoaffective trouble, non spécifié','Schizoaffective disorder, unspecified','Troubles mentaux et du comportement','F25.9'),
('autre psychotic trouble not due to a substance or known physiological condition','Other psychotic disorder not due to a substance or known physiological condition','Troubles mentaux et du comportement','F28'),
('non spécifié psychosis not due to a substance or known physiological condition','Unspecified psychosis not due to a substance or known physiological condition','Troubles mentaux et du comportement','F29'),
('Manic episode without psychotic symptoms, non spécifié','Manic episode without psychotic symptoms, unspecified','Troubles mentaux et du comportement','F30.10'),
('Manic episode without psychotic symptoms, mild','Manic episode without psychotic symptoms, mild','Troubles mentaux et du comportement','F30.11'),
('Hemophilus meningitis','Hemophilus meningitis','Maladies du système nerveux','G00.0'),
('Pneumococcal meningitis','Pneumococcal meningitis','Maladies du système nerveux','G00.1'),
('Streptococcal meningitis','Streptococcal meningitis','Maladies du système nerveux','G00.2'),
('Staphylococcal meningitis','Staphylococcal meningitis','Maladies du système nerveux','G00.3'),
('autre bacterial meningitis','Other bacterial meningitis','Maladies du système nerveux','G00.8'),
('Bacterial meningitis, non spécifié','Bacterial meningitis, unspecified','Maladies du système nerveux','G00.9'),
('Meningitis in bacterial diseases classified elsewhere','Meningitis in bacterial diseases classified elsewhere','Maladies du système nerveux','G01'),
('Meningitis in autre infectious and parasitic diseases classified elsewhere','Meningitis in other infectious and parasitic diseases classified elsewhere','Maladies du système nerveux','G02'),
('Nonpyogenic meningitis','Nonpyogenic meningitis','Maladies du système nerveux','G03.0'),
('chronique meningitis','Chronic meningitis','Maladies du système nerveux','G03.1'),
('bénin recurrent meningitis [Mollaret]','Benign recurrent meningitis [Mollaret]','Maladies du système nerveux','G03.2'),
('Meningitis due to autre specified causes','Meningitis due to other specified causes','Maladies du système nerveux','G03.8'),
('Meningitis, non spécifié','Meningitis, unspecified','Maladies du système nerveux','G03.9'),
('aigu disseminated encephalitis and encephalomyelitis, non spécifié','Acute disseminated encephalitis and encephalomyelitis, unspecified','Maladies du système nerveux','G04.00'),
('Postinfectious aigu disseminated encephalitis and encephalomyelitis (postinfectious ADEM)','Postinfectious acute disseminated encephalitis and encephalomyelitis (postinfectious ADEM)','Maladies du système nerveux','G04.01'),
('Postimmunization aigu disseminated encephalitis, myelitis and encephalomyelitis','Postimmunization acute disseminated encephalitis, myelitis and encephalomyelitis','Maladies du système nerveux','G04.02'),
('Tropical spastic paraplegia','Tropical spastic paraplegia','Maladies du système nerveux','G04.1'),
('Bacterial meningoencephalitis and meningomyelitis, not elsewhere classified','Bacterial meningoencephalitis and meningomyelitis, not elsewhere classified','Maladies du système nerveux','G04.2'),
('aigu necrotizing hemorrhagic encephalopathy, non spécifié','Acute necrotizing hemorrhagic encephalopathy, unspecified','Maladies du système nerveux','G04.30'),
('Postinfectious aigu necrotizing hemorrhagic encephalopathy','Postinfectious acute necrotizing hemorrhagic encephalopathy','Maladies du système nerveux','G04.31'),
('Postimmunization aigu necrotizing hemorrhagic encephalopathy','Postimmunization acute necrotizing hemorrhagic encephalopathy','Maladies du système nerveux','G04.32'),
('autre aigu necrotizing hemorrhagic encephalopathy','Other acute necrotizing hemorrhagic encephalopathy','Maladies du système nerveux','G04.39'),
('autre encephalitis and encephalomyelitis','Other encephalitis and encephalomyelitis','Maladies du système nerveux','G04.81'),
('aigu flaccid myelitis','Acute flaccid myelitis','Maladies du système nerveux','G04.82'),
('autre myelitis','Other myelitis','Maladies du système nerveux','G04.89')
ON CONFLICT (nom_fr) DO NOTHING;
