-- icd10v2_batch_017.sql (80 rows)
INSERT INTO pathologies (nom_fr, nom_en, categorie, icd10_code)
VALUES
('Tumeur maligne de biliary tract, unspecified','Malignant neoplasm of biliary tract, unspecified','Tumeurs malignes','C24.9'),
('Tumeur maligne de head of pancreas','Malignant neoplasm of head of pancreas','Tumeurs malignes','C25.0'),
('Tumeur maligne de body of pancreas','Malignant neoplasm of body of pancreas','Tumeurs malignes','C25.1'),
('Tumeur maligne de tail of pancreas','Malignant neoplasm of tail of pancreas','Tumeurs malignes','C25.2'),
('Tumeur maligne de pancreatic duct','Malignant neoplasm of pancreatic duct','Tumeurs malignes','C25.3'),
('Tumeur maligne de endocrine pancreas','Malignant neoplasm of endocrine pancreas','Tumeurs malignes','C25.4'),
('Tumeur maligne de other parts of pancreas','Malignant neoplasm of other parts of pancreas','Tumeurs malignes','C25.7'),
('Tumeur maligne de overlapping sites of pancreas','Malignant neoplasm of overlapping sites of pancreas','Tumeurs malignes','C25.8'),
('Tumeur maligne de pancreas, unspecified','Malignant neoplasm of pancreas, unspecified','Tumeurs malignes','C25.9'),
('Tumeur maligne de intestinal tract, part unspecified','Malignant neoplasm of intestinal tract, part unspecified','Tumeurs malignes','C26.0'),
('Tumeur maligne de spleen','Malignant neoplasm of spleen','Tumeurs malignes','C26.1'),
('Tumeur maligne de ill-defined sites within the digestive system','Malignant neoplasm of ill-defined sites within the digestive system','Tumeurs malignes','C26.9'),
('Nephrotic syndrome with C3 glomerulonephritis','Nephrotic syndrome with C3 glomerulonephritis','Maladies de l''appareil génito-urinaire','N04.A'),
('Isolated proteinuria with C3 glomerulonephritis','Isolated proteinuria with C3 glomerulonephritis','Maladies de l''appareil génito-urinaire','N06.A'),
('aigu nephritic syndrome with C3 glomerulonephritis','Acute nephritic syndrome with C3 glomerulonephritis','Maladies de l''appareil génito-urinaire','N00.A'),
('chronique nephritic syndrome with C3 glomerulonephritis','Chronic nephritic syndrome with C3 glomerulonephritis','Maladies de l''appareil génito-urinaire','N03.A'),
('non spécifié nephritic syndrome with C3 glomerulonephritis','Unspecified nephritic syndrome with C3 glomerulonephritis','Maladies de l''appareil génito-urinaire','N05.A'),
('Rapidly progressive nephritic syndrome with C3 glomerulonephritis','Rapidly progressive nephritic syndrome with C3 glomerulonephritis','Maladies de l''appareil génito-urinaire','N01.A'),
('Recurrent and persistent hematuria with C3 glomerulonephritis','Recurrent and persistent hematuria with C3 glomerulonephritis','Maladies de l''appareil génito-urinaire','N02.A'),
('Hereditary nephropathy, not elsewhere classified with C3 glomerulonephritis','Hereditary nephropathy, not elsewhere classified with C3 glomerulonephritis','Maladies de l''appareil génito-urinaire','N07.A'),
('Subluxation of C3/C4 cervical vertebrae, sequela','Subluxation of C3/C4 cervical vertebrae, sequela','Traumatismes, empoisonnements et autres causes externes','S13.140S'),
('Luxation de C3/C4 cervical vertebrae, sequela','Dislocation of C3/C4 cervical vertebrae, sequela','Traumatismes, empoisonnements et autres causes externes','S13.141S'),
('Subluxation of C3/C4 cervical vertebrae, initial encounter','Subluxation of C3/C4 cervical vertebrae, initial encounter','Traumatismes, empoisonnements et autres causes externes','S13.140A'),
('Subluxation of C3/C4 cervical vertebrae, subsequent encounter','Subluxation of C3/C4 cervical vertebrae, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S13.140D'),
('Luxation de C3/C4 cervical vertebrae, initial encounter','Dislocation of C3/C4 cervical vertebrae, initial encounter','Traumatismes, empoisonnements et autres causes externes','S13.141A'),
('Luxation de C3/C4 cervical vertebrae, subsequent encounter','Dislocation of C3/C4 cervical vertebrae, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S13.141D'),
('non spécifié injury at C3 level of cervical spinal cord, sequela','Unspecified injury at C3 level of cervical spinal cord, sequela','Traumatismes, empoisonnements et autres causes externes','S14.103S'),
('Complete lesion at C3 level of cervical spinal cord, sequela','Complete lesion at C3 level of cervical spinal cord, sequela','Traumatismes, empoisonnements et autres causes externes','S14.113S'),
('non spécifié injury at C3 level of cervical spinal cord, initial encounter','Unspecified injury at C3 level of cervical spinal cord, initial encounter','Traumatismes, empoisonnements et autres causes externes','S14.103A'),
('non spécifié injury at C3 level of cervical spinal cord, subsequent encounter','Unspecified injury at C3 level of cervical spinal cord, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S14.103D'),
('Complete lesion at C3 level of cervical spinal cord, initial encounter','Complete lesion at C3 level of cervical spinal cord, initial encounter','Traumatismes, empoisonnements et autres causes externes','S14.113A'),
('Complete lesion at C3 level of cervical spinal cord, subsequent encounter','Complete lesion at C3 level of cervical spinal cord, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S14.113D'),
('Central cord syndrome at C3 level of cervical spinal cord, sequela','Central cord syndrome at C3 level of cervical spinal cord, sequela','Traumatismes, empoisonnements et autres causes externes','S14.123S'),
('Anterior cord syndrome at C3 level of cervical spinal cord, sequela','Anterior cord syndrome at C3 level of cervical spinal cord, sequela','Traumatismes, empoisonnements et autres causes externes','S14.133S'),
('Brown-Sequard syndrome at C3 level of cervical spinal cord, sequela','Brown-Sequard syndrome at C3 level of cervical spinal cord, sequela','Traumatismes, empoisonnements et autres causes externes','S14.143S'),
('autre incomplete lesion at C3 level of cervical spinal cord, sequela','Other incomplete lesion at C3 level of cervical spinal cord, sequela','Traumatismes, empoisonnements et autres causes externes','S14.153S'),
('Central cord syndrome at C3 level of cervical spinal cord, initial encounter','Central cord syndrome at C3 level of cervical spinal cord, initial encounter','Traumatismes, empoisonnements et autres causes externes','S14.123A'),
('Central cord syndrome at C3 level of cervical spinal cord, subsequent encounter','Central cord syndrome at C3 level of cervical spinal cord, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S14.123D'),
('Anterior cord syndrome at C3 level of cervical spinal cord, initial encounter','Anterior cord syndrome at C3 level of cervical spinal cord, initial encounter','Traumatismes, empoisonnements et autres causes externes','S14.133A'),
('Anterior cord syndrome at C3 level of cervical spinal cord, subsequent encounter','Anterior cord syndrome at C3 level of cervical spinal cord, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S14.133D'),
('Brown-Sequard syndrome at C3 level of cervical spinal cord, initial encounter','Brown-Sequard syndrome at C3 level of cervical spinal cord, initial encounter','Traumatismes, empoisonnements et autres causes externes','S14.143A'),
('Brown-Sequard syndrome at C3 level of cervical spinal cord, subsequent encounter','Brown-Sequard syndrome at C3 level of cervical spinal cord, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S14.143D'),
('autre incomplete lesion at C3 level of cervical spinal cord, initial encounter','Other incomplete lesion at C3 level of cervical spinal cord, initial encounter','Traumatismes, empoisonnements et autres causes externes','S14.153A'),
('autre incomplete lesion at C3 level of cervical spinal cord, subsequent encounter','Other incomplete lesion at C3 level of cervical spinal cord, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S14.153D'),
('Tumeur maligne de nasal cavity','Malignant neoplasm of nasal cavity','Tumeurs malignes','C30.0'),
('Tumeur maligne de middle ear','Malignant neoplasm of middle ear','Tumeurs malignes','C30.1'),
('Tumeur maligne de maxillary sinus','Malignant neoplasm of maxillary sinus','Tumeurs malignes','C31.0'),
('Tumeur maligne de ethmoidal sinus','Malignant neoplasm of ethmoidal sinus','Tumeurs malignes','C31.1'),
('Tumeur maligne de frontal sinus','Malignant neoplasm of frontal sinus','Tumeurs malignes','C31.2'),
('Tumeur maligne de sphenoid sinus','Malignant neoplasm of sphenoid sinus','Tumeurs malignes','C31.3'),
('Tumeur maligne de overlapping sites of accessory sinuses','Malignant neoplasm of overlapping sites of accessory sinuses','Tumeurs malignes','C31.8'),
('Tumeur maligne de accessory sinus, unspecified','Malignant neoplasm of accessory sinus, unspecified','Tumeurs malignes','C31.9'),
('Tumeur maligne de glottis','Malignant neoplasm of glottis','Tumeurs malignes','C32.0'),
('Tumeur maligne de supraglottis','Malignant neoplasm of supraglottis','Tumeurs malignes','C32.1'),
('Tumeur maligne de subglottis','Malignant neoplasm of subglottis','Tumeurs malignes','C32.2'),
('Tumeur maligne de laryngeal cartilage','Malignant neoplasm of laryngeal cartilage','Tumeurs malignes','C32.3'),
('Tumeur maligne de overlapping sites of larynx','Malignant neoplasm of overlapping sites of larynx','Tumeurs malignes','C32.8'),
('Tumeur maligne de larynx, unspecified','Malignant neoplasm of larynx, unspecified','Tumeurs malignes','C32.9'),
('Tumeur maligne de trachea','Malignant neoplasm of trachea','Tumeurs malignes','C33'),
('Tumeur maligne de unspecified main bronchus','Malignant neoplasm of unspecified main bronchus','Tumeurs malignes','C34.00'),
('Tumeur maligne de right main bronchus','Malignant neoplasm of right main bronchus','Tumeurs malignes','C34.01'),
('Tumeur maligne de left main bronchus','Malignant neoplasm of left main bronchus','Tumeurs malignes','C34.02'),
('Tumeur maligne de upper lobe, unspecified bronchus or lung','Malignant neoplasm of upper lobe, unspecified bronchus or lung','Tumeurs malignes','C34.10'),
('Tumeur maligne de upper lobe, right bronchus or lung','Malignant neoplasm of upper lobe, right bronchus or lung','Tumeurs malignes','C34.11'),
('Tumeur maligne de upper lobe, left bronchus or lung','Malignant neoplasm of upper lobe, left bronchus or lung','Tumeurs malignes','C34.12'),
('Tumeur maligne de middle lobe, bronchus or lung','Malignant neoplasm of middle lobe, bronchus or lung','Tumeurs malignes','C34.2'),
('Tumeur maligne de lower lobe, unspecified bronchus or lung','Malignant neoplasm of lower lobe, unspecified bronchus or lung','Tumeurs malignes','C34.30'),
('Tumeur maligne de lower lobe, right bronchus or lung','Malignant neoplasm of lower lobe, right bronchus or lung','Tumeurs malignes','C34.31'),
('Tumeur maligne de lower lobe, left bronchus or lung','Malignant neoplasm of lower lobe, left bronchus or lung','Tumeurs malignes','C34.32'),
('Tumeur maligne de overlapping sites of unspecified bronchus and lung','Malignant neoplasm of overlapping sites of unspecified bronchus and lung','Tumeurs malignes','C34.80'),
('Tumeur maligne de overlapping sites of right bronchus and lung','Malignant neoplasm of overlapping sites of right bronchus and lung','Tumeurs malignes','C34.81'),
('Tumeur maligne de overlapping sites of left bronchus and lung','Malignant neoplasm of overlapping sites of left bronchus and lung','Tumeurs malignes','C34.82'),
('Tumeur maligne de unspecified part of unspecified bronchus or lung','Malignant neoplasm of unspecified part of unspecified bronchus or lung','Tumeurs malignes','C34.90'),
('Tumeur maligne de unspecified part of right bronchus or lung','Malignant neoplasm of unspecified part of right bronchus or lung','Tumeurs malignes','C34.91'),
('Tumeur maligne de unspecified part of left bronchus or lung','Malignant neoplasm of unspecified part of left bronchus or lung','Tumeurs malignes','C34.92'),
('Tumeur maligne de thymus','Malignant neoplasm of thymus','Tumeurs malignes','C37'),
('Tumeur maligne de heart','Malignant neoplasm of heart','Tumeurs malignes','C38.0'),
('Tumeur maligne de anterior mediastinum','Malignant neoplasm of anterior mediastinum','Tumeurs malignes','C38.1'),
('Tumeur maligne de posterior mediastinum','Malignant neoplasm of posterior mediastinum','Tumeurs malignes','C38.2'),
('Tumeur maligne de mediastinum, part unspecified','Malignant neoplasm of mediastinum, part unspecified','Tumeurs malignes','C38.3')
ON CONFLICT (nom_fr) DO NOTHING;
