-- icd10v2_batch_332.sql (80 rows)
INSERT INTO pathologies (nom_fr, nom_en, categorie, icd10_code)
VALUES
('Abrasion, left foot, sequela','Abrasion, left foot, sequela','Traumatismes, empoisonnements et autres causes externes','S90.812S'),
('Abrasion, non spécifié foot, initial encounter','Abrasion, unspecified foot, initial encounter','Traumatismes, empoisonnements et autres causes externes','S90.819A'),
('Abrasion, non spécifié foot, subsequent encounter','Abrasion, unspecified foot, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S90.819D'),
('Abrasion, non spécifié foot, sequela','Abrasion, unspecified foot, sequela','Traumatismes, empoisonnements et autres causes externes','S90.819S'),
('Blister (nonthermal), right foot, initial encounter','Blister (nonthermal), right foot, initial encounter','Traumatismes, empoisonnements et autres causes externes','S90.821A'),
('Blister (nonthermal), right foot, subsequent encounter','Blister (nonthermal), right foot, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S90.821D'),
('Blister (nonthermal), right foot, sequela','Blister (nonthermal), right foot, sequela','Traumatismes, empoisonnements et autres causes externes','S90.821S'),
('Blister (nonthermal), left foot, initial encounter','Blister (nonthermal), left foot, initial encounter','Traumatismes, empoisonnements et autres causes externes','S90.822A'),
('Blister (nonthermal), left foot, subsequent encounter','Blister (nonthermal), left foot, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S90.822D'),
('Blister (nonthermal), left foot, sequela','Blister (nonthermal), left foot, sequela','Traumatismes, empoisonnements et autres causes externes','S90.822S'),
('Blister (nonthermal), non spécifié foot, initial encounter','Blister (nonthermal), unspecified foot, initial encounter','Traumatismes, empoisonnements et autres causes externes','S90.829A'),
('Blister (nonthermal), non spécifié foot, subsequent encounter','Blister (nonthermal), unspecified foot, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S90.829D'),
('Blister (nonthermal), non spécifié foot, sequela','Blister (nonthermal), unspecified foot, sequela','Traumatismes, empoisonnements et autres causes externes','S90.829S'),
('External constriction, right foot, initial encounter','External constriction, right foot, initial encounter','Traumatismes, empoisonnements et autres causes externes','S90.841A'),
('External constriction, right foot, subsequent encounter','External constriction, right foot, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S90.841D'),
('External constriction, right foot, sequela','External constriction, right foot, sequela','Traumatismes, empoisonnements et autres causes externes','S90.841S'),
('External constriction, left foot, initial encounter','External constriction, left foot, initial encounter','Traumatismes, empoisonnements et autres causes externes','S90.842A'),
('External constriction, left foot, subsequent encounter','External constriction, left foot, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S90.842D'),
('External constriction, left foot, sequela','External constriction, left foot, sequela','Traumatismes, empoisonnements et autres causes externes','S90.842S'),
('External constriction, non spécifié foot, initial encounter','External constriction, unspecified foot, initial encounter','Traumatismes, empoisonnements et autres causes externes','S90.849A'),
('External constriction, non spécifié foot, subsequent encounter','External constriction, unspecified foot, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S90.849D'),
('External constriction, non spécifié foot, sequela','External constriction, unspecified foot, sequela','Traumatismes, empoisonnements et autres causes externes','S90.849S'),
('Superficial foreign body, right foot, initial encounter','Superficial foreign body, right foot, initial encounter','Traumatismes, empoisonnements et autres causes externes','S90.851A'),
('Superficial foreign body, right foot, subsequent encounter','Superficial foreign body, right foot, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S90.851D'),
('Superficial foreign body, right foot, sequela','Superficial foreign body, right foot, sequela','Traumatismes, empoisonnements et autres causes externes','S90.851S'),
('Superficial foreign body, left foot, initial encounter','Superficial foreign body, left foot, initial encounter','Traumatismes, empoisonnements et autres causes externes','S90.852A'),
('Superficial foreign body, left foot, subsequent encounter','Superficial foreign body, left foot, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S90.852D'),
('Superficial foreign body, left foot, sequela','Superficial foreign body, left foot, sequela','Traumatismes, empoisonnements et autres causes externes','S90.852S'),
('Superficial foreign body, non spécifié foot, initial encounter','Superficial foreign body, unspecified foot, initial encounter','Traumatismes, empoisonnements et autres causes externes','S90.859A'),
('Superficial foreign body, non spécifié foot, subsequent encounter','Superficial foreign body, unspecified foot, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S90.859D'),
('Superficial foreign body, non spécifié foot, sequela','Superficial foreign body, unspecified foot, sequela','Traumatismes, empoisonnements et autres causes externes','S90.859S'),
('Insect bite (nonvenomous), right foot, initial encounter','Insect bite (nonvenomous), right foot, initial encounter','Traumatismes, empoisonnements et autres causes externes','S90.861A'),
('Insect bite (nonvenomous), right foot, subsequent encounter','Insect bite (nonvenomous), right foot, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S90.861D'),
('Insect bite (nonvenomous), right foot, sequela','Insect bite (nonvenomous), right foot, sequela','Traumatismes, empoisonnements et autres causes externes','S90.861S'),
('Insect bite (nonvenomous), left foot, initial encounter','Insect bite (nonvenomous), left foot, initial encounter','Traumatismes, empoisonnements et autres causes externes','S90.862A'),
('Insect bite (nonvenomous), left foot, subsequent encounter','Insect bite (nonvenomous), left foot, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S90.862D'),
('Insect bite (nonvenomous), left foot, sequela','Insect bite (nonvenomous), left foot, sequela','Traumatismes, empoisonnements et autres causes externes','S90.862S'),
('Insect bite (nonvenomous), non spécifié foot, initial encounter','Insect bite (nonvenomous), unspecified foot, initial encounter','Traumatismes, empoisonnements et autres causes externes','S90.869A'),
('Insect bite (nonvenomous), non spécifié foot, subsequent encounter','Insect bite (nonvenomous), unspecified foot, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S90.869D'),
('Insect bite (nonvenomous), non spécifié foot, sequela','Insect bite (nonvenomous), unspecified foot, sequela','Traumatismes, empoisonnements et autres causes externes','S90.869S'),
('autre superficial bite of right foot, initial encounter','Other superficial bite of right foot, initial encounter','Traumatismes, empoisonnements et autres causes externes','S90.871A'),
('autre superficial bite of right foot, subsequent encounter','Other superficial bite of right foot, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S90.871D'),
('autre superficial bite of right foot, sequela','Other superficial bite of right foot, sequela','Traumatismes, empoisonnements et autres causes externes','S90.871S'),
('autre superficial bite of left foot, initial encounter','Other superficial bite of left foot, initial encounter','Traumatismes, empoisonnements et autres causes externes','S90.872A'),
('autre superficial bite of left foot, subsequent encounter','Other superficial bite of left foot, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S90.872D'),
('autre superficial bite of left foot, sequela','Other superficial bite of left foot, sequela','Traumatismes, empoisonnements et autres causes externes','S90.872S'),
('autre superficial bite of non spécifié foot, initial encounter','Other superficial bite of unspecified foot, initial encounter','Traumatismes, empoisonnements et autres causes externes','S90.879A'),
('autre superficial bite of non spécifié foot, subsequent encounter','Other superficial bite of unspecified foot, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S90.879D'),
('autre superficial bite of non spécifié foot, sequela','Other superficial bite of unspecified foot, sequela','Traumatismes, empoisonnements et autres causes externes','S90.879S'),
('non spécifié superficial injury of right ankle, initial encounter','Unspecified superficial injury of right ankle, initial encounter','Traumatismes, empoisonnements et autres causes externes','S90.911A'),
('non spécifié superficial injury of right ankle, subsequent encounter','Unspecified superficial injury of right ankle, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S90.911D'),
('non spécifié superficial injury of right ankle, sequela','Unspecified superficial injury of right ankle, sequela','Traumatismes, empoisonnements et autres causes externes','S90.911S'),
('non spécifié superficial injury of left ankle, initial encounter','Unspecified superficial injury of left ankle, initial encounter','Traumatismes, empoisonnements et autres causes externes','S90.912A'),
('non spécifié superficial injury of left ankle, subsequent encounter','Unspecified superficial injury of left ankle, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S90.912D'),
('non spécifié superficial injury of left ankle, sequela','Unspecified superficial injury of left ankle, sequela','Traumatismes, empoisonnements et autres causes externes','S90.912S'),
('non spécifié superficial injury of non spécifié ankle, initial encounter','Unspecified superficial injury of unspecified ankle, initial encounter','Traumatismes, empoisonnements et autres causes externes','S90.919A'),
('non spécifié superficial injury of non spécifié ankle, subsequent encounter','Unspecified superficial injury of unspecified ankle, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S90.919D'),
('non spécifié superficial injury of non spécifié ankle, sequela','Unspecified superficial injury of unspecified ankle, sequela','Traumatismes, empoisonnements et autres causes externes','S90.919S'),
('non spécifié superficial injury of right foot, initial encounter','Unspecified superficial injury of right foot, initial encounter','Traumatismes, empoisonnements et autres causes externes','S90.921A'),
('non spécifié superficial injury of right foot, subsequent encounter','Unspecified superficial injury of right foot, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S90.921D'),
('non spécifié superficial injury of right foot, sequela','Unspecified superficial injury of right foot, sequela','Traumatismes, empoisonnements et autres causes externes','S90.921S'),
('non spécifié superficial injury of left foot, initial encounter','Unspecified superficial injury of left foot, initial encounter','Traumatismes, empoisonnements et autres causes externes','S90.922A'),
('non spécifié superficial injury of left foot, subsequent encounter','Unspecified superficial injury of left foot, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S90.922D'),
('non spécifié superficial injury of left foot, sequela','Unspecified superficial injury of left foot, sequela','Traumatismes, empoisonnements et autres causes externes','S90.922S'),
('non spécifié superficial injury of non spécifié foot, initial encounter','Unspecified superficial injury of unspecified foot, initial encounter','Traumatismes, empoisonnements et autres causes externes','S90.929A'),
('non spécifié superficial injury of non spécifié foot, subsequent encounter','Unspecified superficial injury of unspecified foot, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S90.929D'),
('non spécifié superficial injury of non spécifié foot, sequela','Unspecified superficial injury of unspecified foot, sequela','Traumatismes, empoisonnements et autres causes externes','S90.929S'),
('non spécifié superficial injury of right great toe, initial encounter','Unspecified superficial injury of right great toe, initial encounter','Traumatismes, empoisonnements et autres causes externes','S90.931A'),
('non spécifié superficial injury of right great toe, subsequent encounter','Unspecified superficial injury of right great toe, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S90.931D'),
('non spécifié superficial injury of right great toe, sequela','Unspecified superficial injury of right great toe, sequela','Traumatismes, empoisonnements et autres causes externes','S90.931S'),
('non spécifié superficial injury of left great toe, initial encounter','Unspecified superficial injury of left great toe, initial encounter','Traumatismes, empoisonnements et autres causes externes','S90.932A'),
('non spécifié superficial injury of left great toe, subsequent encounter','Unspecified superficial injury of left great toe, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S90.932D'),
('non spécifié superficial injury of left great toe, sequela','Unspecified superficial injury of left great toe, sequela','Traumatismes, empoisonnements et autres causes externes','S90.932S'),
('non spécifié superficial injury of non spécifié great toe, initial encounter','Unspecified superficial injury of unspecified great toe, initial encounter','Traumatismes, empoisonnements et autres causes externes','S90.933A'),
('non spécifié superficial injury of non spécifié great toe, subsequent encounter','Unspecified superficial injury of unspecified great toe, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S90.933D'),
('non spécifié superficial injury of non spécifié great toe, sequela','Unspecified superficial injury of unspecified great toe, sequela','Traumatismes, empoisonnements et autres causes externes','S90.933S'),
('non spécifié superficial injury of right lesser toe(s), initial encounter','Unspecified superficial injury of right lesser toe(s), initial encounter','Traumatismes, empoisonnements et autres causes externes','S90.934A'),
('non spécifié superficial injury of right lesser toe(s), subsequent encounter','Unspecified superficial injury of right lesser toe(s), subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S90.934D'),
('non spécifié superficial injury of right lesser toe(s), sequela','Unspecified superficial injury of right lesser toe(s), sequela','Traumatismes, empoisonnements et autres causes externes','S90.934S'),
('non spécifié superficial injury of left lesser toe(s), initial encounter','Unspecified superficial injury of left lesser toe(s), initial encounter','Traumatismes, empoisonnements et autres causes externes','S90.935A')
ON CONFLICT (nom_fr) DO NOTHING;
