-- icd10v2_batch_481.sql (80 rows)
INSERT INTO pathologies (nom_fr, nom_en, categorie, icd10_code)
VALUES
('Allergy status to autre antibiotic agents','Allergy status to other antibiotic agents','Facteurs influant sur l''état de santé','Z88.1'),
('Allergy status to sulfonamides','Allergy status to sulfonamides','Facteurs influant sur l''état de santé','Z88.2'),
('Allergy status to autre anti-infective agents','Allergy status to other anti-infective agents','Facteurs influant sur l''état de santé','Z88.3'),
('Allergy status to anesthetic agent','Allergy status to anesthetic agent','Facteurs influant sur l''état de santé','Z88.4'),
('Allergy status to narcotic agent','Allergy status to narcotic agent','Facteurs influant sur l''état de santé','Z88.5'),
('Allergy status to analgesic agent','Allergy status to analgesic agent','Facteurs influant sur l''état de santé','Z88.6'),
('Allergy status to serum and vaccine','Allergy status to serum and vaccine','Facteurs influant sur l''état de santé','Z88.7'),
('Allergy status to autre drugs, medicaments and biological substances','Allergy status to other drugs, medicaments and biological substances','Facteurs influant sur l''état de santé','Z88.8'),
('Allergy status to non spécifié drugs, medicaments and biological substances','Allergy status to unspecified drugs, medicaments and biological substances','Facteurs influant sur l''état de santé','Z88.9'),
('Acquired absence of right thumb','Acquired absence of right thumb','Facteurs influant sur l''état de santé','Z89.011'),
('Acquired absence of left thumb','Acquired absence of left thumb','Facteurs influant sur l''état de santé','Z89.012'),
('Acquired absence of non spécifié thumb','Acquired absence of unspecified thumb','Facteurs influant sur l''état de santé','Z89.019'),
('Acquired absence of right finger(s)','Acquired absence of right finger(s)','Facteurs influant sur l''état de santé','Z89.021'),
('Acquired absence of left finger(s)','Acquired absence of left finger(s)','Facteurs influant sur l''état de santé','Z89.022'),
('Acquired absence of non spécifié finger(s)','Acquired absence of unspecified finger(s)','Facteurs influant sur l''état de santé','Z89.029'),
('Acquired absence of right hand','Acquired absence of right hand','Facteurs influant sur l''état de santé','Z89.111'),
('Acquired absence of left hand','Acquired absence of left hand','Facteurs influant sur l''état de santé','Z89.112'),
('Acquired absence of non spécifié hand','Acquired absence of unspecified hand','Facteurs influant sur l''état de santé','Z89.119'),
('Acquired absence of right wrist','Acquired absence of right wrist','Facteurs influant sur l''état de santé','Z89.121'),
('Acquired absence of left wrist','Acquired absence of left wrist','Facteurs influant sur l''état de santé','Z89.122'),
('Acquired absence of non spécifié wrist','Acquired absence of unspecified wrist','Facteurs influant sur l''état de santé','Z89.129'),
('Acquired absence of right upper limb, non spécifié level','Acquired absence of right upper limb, unspecified level','Facteurs influant sur l''état de santé','Z89.201'),
('Acquired absence of left upper limb, non spécifié level','Acquired absence of left upper limb, unspecified level','Facteurs influant sur l''état de santé','Z89.202'),
('Acquired absence of non spécifié upper limb, non spécifié level','Acquired absence of unspecified upper limb, unspecified level','Facteurs influant sur l''état de santé','Z89.209'),
('Acquired absence of right upper limb below elbow','Acquired absence of right upper limb below elbow','Facteurs influant sur l''état de santé','Z89.211'),
('Acquired absence of left upper limb below elbow','Acquired absence of left upper limb below elbow','Facteurs influant sur l''état de santé','Z89.212'),
('Acquired absence of non spécifié upper limb below elbow','Acquired absence of unspecified upper limb below elbow','Facteurs influant sur l''état de santé','Z89.219'),
('Acquired absence of right upper limb above elbow','Acquired absence of right upper limb above elbow','Facteurs influant sur l''état de santé','Z89.221'),
('Acquired absence of left upper limb above elbow','Acquired absence of left upper limb above elbow','Facteurs influant sur l''état de santé','Z89.222'),
('Acquired absence of non spécifié upper limb above elbow','Acquired absence of unspecified upper limb above elbow','Facteurs influant sur l''état de santé','Z89.229'),
('Acquired absence of right shoulder','Acquired absence of right shoulder','Facteurs influant sur l''état de santé','Z89.231'),
('Acquired absence of left shoulder','Acquired absence of left shoulder','Facteurs influant sur l''état de santé','Z89.232'),
('Acquired absence of non spécifié shoulder','Acquired absence of unspecified shoulder','Facteurs influant sur l''état de santé','Z89.239'),
('Acquired absence of right great toe','Acquired absence of right great toe','Facteurs influant sur l''état de santé','Z89.411'),
('Acquired absence of left great toe','Acquired absence of left great toe','Facteurs influant sur l''état de santé','Z89.412'),
('Acquired absence of non spécifié great toe','Acquired absence of unspecified great toe','Facteurs influant sur l''état de santé','Z89.419'),
('Acquired absence of autre right toe(s)','Acquired absence of other right toe(s)','Facteurs influant sur l''état de santé','Z89.421'),
('Acquired absence of autre left toe(s)','Acquired absence of other left toe(s)','Facteurs influant sur l''état de santé','Z89.422'),
('Acquired absence of autre toe(s), non spécifié side','Acquired absence of other toe(s), unspecified side','Facteurs influant sur l''état de santé','Z89.429'),
('Acquired absence of right foot','Acquired absence of right foot','Facteurs influant sur l''état de santé','Z89.431'),
('Acquired absence of left foot','Acquired absence of left foot','Facteurs influant sur l''état de santé','Z89.432'),
('Acquired absence of non spécifié foot','Acquired absence of unspecified foot','Facteurs influant sur l''état de santé','Z89.439'),
('Acquired absence of right ankle','Acquired absence of right ankle','Facteurs influant sur l''état de santé','Z89.441'),
('Acquired absence of left ankle','Acquired absence of left ankle','Facteurs influant sur l''état de santé','Z89.442'),
('Acquired absence of non spécifié ankle','Acquired absence of unspecified ankle','Facteurs influant sur l''état de santé','Z89.449'),
('Acquired absence of right leg below knee','Acquired absence of right leg below knee','Facteurs influant sur l''état de santé','Z89.511'),
('Acquired absence of left leg below knee','Acquired absence of left leg below knee','Facteurs influant sur l''état de santé','Z89.512'),
('Acquired absence of non spécifié leg below knee','Acquired absence of unspecified leg below knee','Facteurs influant sur l''état de santé','Z89.519'),
('Acquired absence of right knee','Acquired absence of right knee','Facteurs influant sur l''état de santé','Z89.521'),
('Acquired absence of left knee','Acquired absence of left knee','Facteurs influant sur l''état de santé','Z89.522'),
('Acquired absence of non spécifié knee','Acquired absence of unspecified knee','Facteurs influant sur l''état de santé','Z89.529'),
('Acquired absence of right leg above knee','Acquired absence of right leg above knee','Facteurs influant sur l''état de santé','Z89.611'),
('Acquired absence of left leg above knee','Acquired absence of left leg above knee','Facteurs influant sur l''état de santé','Z89.612'),
('Acquired absence of non spécifié leg above knee','Acquired absence of unspecified leg above knee','Facteurs influant sur l''état de santé','Z89.619'),
('Acquired absence of right hip joint','Acquired absence of right hip joint','Facteurs influant sur l''état de santé','Z89.621'),
('Acquired absence of left hip joint','Acquired absence of left hip joint','Facteurs influant sur l''état de santé','Z89.622'),
('Acquired absence of non spécifié hip joint','Acquired absence of unspecified hip joint','Facteurs influant sur l''état de santé','Z89.629'),
('Acquired absence of limb, non spécifié','Acquired absence of limb, unspecified','Facteurs influant sur l''état de santé','Z89.9'),
('Acquired absence of eye','Acquired absence of eye','Facteurs influant sur l''état de santé','Z90.01'),
('Acquired absence of larynx','Acquired absence of larynx','Facteurs influant sur l''état de santé','Z90.02'),
('Acquired absence of autre part of head and neck','Acquired absence of other part of head and neck','Facteurs influant sur l''état de santé','Z90.09'),
('Acquired absence of non spécifié breast and nipple','Acquired absence of unspecified breast and nipple','Facteurs influant sur l''état de santé','Z90.10'),
('Acquired absence of right breast and nipple','Acquired absence of right breast and nipple','Facteurs influant sur l''état de santé','Z90.11'),
('Acquired absence of left breast and nipple','Acquired absence of left breast and nipple','Facteurs influant sur l''état de santé','Z90.12'),
('Acquired absence of bilateral breasts and nipples','Acquired absence of bilateral breasts and nipples','Facteurs influant sur l''état de santé','Z90.13'),
('Acquired absence of lung [part of]','Acquired absence of lung [part of]','Facteurs influant sur l''état de santé','Z90.2'),
('Acquired absence of stomach [part of]','Acquired absence of stomach [part of]','Facteurs influant sur l''état de santé','Z90.3'),
('Acquired total absence of pancreas','Acquired total absence of pancreas','Facteurs influant sur l''état de santé','Z90.410'),
('Acquired partial absence of pancreas','Acquired partial absence of pancreas','Facteurs influant sur l''état de santé','Z90.411'),
('Acquired absence of autre specified parts of digestive tract','Acquired absence of other specified parts of digestive tract','Facteurs influant sur l''état de santé','Z90.49'),
('Acquired absence of kidney','Acquired absence of kidney','Facteurs influant sur l''état de santé','Z90.5'),
('Acquired absence of autre parts of urinary tract','Acquired absence of other parts of urinary tract','Facteurs influant sur l''état de santé','Z90.6'),
('Acquired absence of both cervix and uterus','Acquired absence of both cervix and uterus','Facteurs influant sur l''état de santé','Z90.710'),
('Acquired absence of uterus with remaining cervical stump','Acquired absence of uterus with remaining cervical stump','Facteurs influant sur l''état de santé','Z90.711'),
('Acquired absence of cervix with remaining uterus','Acquired absence of cervix with remaining uterus','Facteurs influant sur l''état de santé','Z90.712'),
('Acquired absence of ovaries, unilateral','Acquired absence of ovaries, unilateral','Facteurs influant sur l''état de santé','Z90.721'),
('Acquired absence of ovaries, bilateral','Acquired absence of ovaries, bilateral','Facteurs influant sur l''état de santé','Z90.722'),
('Acquired absence of autre genital organ(s)','Acquired absence of other genital organ(s)','Facteurs influant sur l''état de santé','Z90.79'),
('Acquired absence of spleen','Acquired absence of spleen','Facteurs influant sur l''état de santé','Z90.81'),
('Acquired absence of autre organs','Acquired absence of other organs','Facteurs influant sur l''état de santé','Z90.89')
ON CONFLICT (nom_fr) DO NOTHING;
