-- icd10v2_batch_061.sql (80 rows)
INSERT INTO pathologies (nom_fr, nom_en, categorie, icd10_code)
VALUES
('Nicotine dependence, chewing tobacco, with non spécifié nicotine-induced disorders','Nicotine dependence, chewing tobacco, with unspecified nicotine-induced disorders','Troubles mentaux et du comportement','F17.229'),
('Nicotine dependence, autre tobacco product, uncomplicated','Nicotine dependence, other tobacco product, uncomplicated','Troubles mentaux et du comportement','F17.290'),
('Nicotine dependence, autre tobacco product, in remission','Nicotine dependence, other tobacco product, in remission','Troubles mentaux et du comportement','F17.291'),
('Nicotine dependence, autre tobacco product, with withdrawal','Nicotine dependence, other tobacco product, with withdrawal','Troubles mentaux et du comportement','F17.293'),
('Nicotine dependence, autre tobacco product, with autre nicotine-induced disorders','Nicotine dependence, other tobacco product, with other nicotine-induced disorders','Troubles mentaux et du comportement','F17.298'),
('Nicotine dependence, autre tobacco product, with non spécifié nicotine-induced disorders','Nicotine dependence, other tobacco product, with unspecified nicotine-induced disorders','Troubles mentaux et du comportement','F17.299'),
('Inhalant abuse, uncomplicated','Inhalant abuse, uncomplicated','Troubles mentaux et du comportement','F18.10'),
('Inhalant abuse, in remission','Inhalant abuse, in remission','Troubles mentaux et du comportement','F18.11'),
('Inhalant abuse with intoxication, uncomplicated','Inhalant abuse with intoxication, uncomplicated','Troubles mentaux et du comportement','F18.120'),
('Inhalant abuse with intoxication delirium','Inhalant abuse with intoxication delirium','Troubles mentaux et du comportement','F18.121'),
('Inhalant abuse with intoxication, non spécifié','Inhalant abuse with intoxication, unspecified','Troubles mentaux et du comportement','F18.129'),
('Inhalant abuse with inhalant-induced mood trouble','Inhalant abuse with inhalant-induced mood disorder','Troubles mentaux et du comportement','F18.14'),
('Inhalant abuse with inhalant-induced psychotic trouble with delusions','Inhalant abuse with inhalant-induced psychotic disorder with delusions','Troubles mentaux et du comportement','F18.150'),
('Inhalant abuse with inhalant-induced psychotic trouble with hallucinations','Inhalant abuse with inhalant-induced psychotic disorder with hallucinations','Troubles mentaux et du comportement','F18.151'),
('Inhalant abuse with inhalant-induced psychotic trouble, non spécifié','Inhalant abuse with inhalant-induced psychotic disorder, unspecified','Troubles mentaux et du comportement','F18.159'),
('Inhalant abuse with inhalant-induced dementia','Inhalant abuse with inhalant-induced dementia','Troubles mentaux et du comportement','F18.17'),
('Inhalant abuse with inhalant-induced anxiety trouble','Inhalant abuse with inhalant-induced anxiety disorder','Troubles mentaux et du comportement','F18.180'),
('Inhalant abuse with autre inhalant-induced trouble','Inhalant abuse with other inhalant-induced disorder','Troubles mentaux et du comportement','F18.188'),
('Inhalant abuse with non spécifié inhalant-induced trouble','Inhalant abuse with unspecified inhalant-induced disorder','Troubles mentaux et du comportement','F18.19'),
('Inhalant dependence, uncomplicated','Inhalant dependence, uncomplicated','Troubles mentaux et du comportement','F18.20'),
('Inhalant dependence, in remission','Inhalant dependence, in remission','Troubles mentaux et du comportement','F18.21'),
('Inhalant dependence with intoxication, uncomplicated','Inhalant dependence with intoxication, uncomplicated','Troubles mentaux et du comportement','F18.220'),
('Inhalant dependence with intoxication delirium','Inhalant dependence with intoxication delirium','Troubles mentaux et du comportement','F18.221'),
('Inhalant dependence with intoxication, non spécifié','Inhalant dependence with intoxication, unspecified','Troubles mentaux et du comportement','F18.229'),
('Inhalant dependence with inhalant-induced mood trouble','Inhalant dependence with inhalant-induced mood disorder','Troubles mentaux et du comportement','F18.24'),
('Inhalant dependence with inhalant-induced psychotic trouble with delusions','Inhalant dependence with inhalant-induced psychotic disorder with delusions','Troubles mentaux et du comportement','F18.250'),
('Inhalant dependence with inhalant-induced psychotic trouble with hallucinations','Inhalant dependence with inhalant-induced psychotic disorder with hallucinations','Troubles mentaux et du comportement','F18.251'),
('Inhalant dependence with inhalant-induced psychotic trouble, non spécifié','Inhalant dependence with inhalant-induced psychotic disorder, unspecified','Troubles mentaux et du comportement','F18.259'),
('Inhalant dependence with inhalant-induced dementia','Inhalant dependence with inhalant-induced dementia','Troubles mentaux et du comportement','F18.27'),
('Inhalant dependence with inhalant-induced anxiety trouble','Inhalant dependence with inhalant-induced anxiety disorder','Troubles mentaux et du comportement','F18.280'),
('Inhalant dependence with autre inhalant-induced trouble','Inhalant dependence with other inhalant-induced disorder','Troubles mentaux et du comportement','F18.288'),
('Inhalant dependence with non spécifié inhalant-induced trouble','Inhalant dependence with unspecified inhalant-induced disorder','Troubles mentaux et du comportement','F18.29'),
('Inhalant use, non spécifié, uncomplicated','Inhalant use, unspecified, uncomplicated','Troubles mentaux et du comportement','F18.90'),
('Inhalant use, non spécifié, in remission','Inhalant use, unspecified, in remission','Troubles mentaux et du comportement','F18.91'),
('Inhalant use, non spécifié with intoxication, uncomplicated','Inhalant use, unspecified with intoxication, uncomplicated','Troubles mentaux et du comportement','F18.920'),
('Inhalant use, non spécifié with intoxication with delirium','Inhalant use, unspecified with intoxication with delirium','Troubles mentaux et du comportement','F18.921'),
('Inhalant use, non spécifié with intoxication, non spécifié','Inhalant use, unspecified with intoxication, unspecified','Troubles mentaux et du comportement','F18.929'),
('Inhalant use, non spécifié with inhalant-induced mood trouble','Inhalant use, unspecified with inhalant-induced mood disorder','Troubles mentaux et du comportement','F18.94'),
('Inhalant use, non spécifié with inhalant-induced psychotic trouble with delusions','Inhalant use, unspecified with inhalant-induced psychotic disorder with delusions','Troubles mentaux et du comportement','F18.950'),
('Inhalant use, non spécifié with inhalant-induced psychotic trouble with hallucinations','Inhalant use, unspecified with inhalant-induced psychotic disorder with hallucinations','Troubles mentaux et du comportement','F18.951'),
('Inhalant use, non spécifié with inhalant-induced psychotic trouble, non spécifié','Inhalant use, unspecified with inhalant-induced psychotic disorder, unspecified','Troubles mentaux et du comportement','F18.959'),
('Inhalant use, non spécifié with inhalant-induced persisting dementia','Inhalant use, unspecified with inhalant-induced persisting dementia','Troubles mentaux et du comportement','F18.97'),
('Inhalant use, non spécifié with inhalant-induced anxiety trouble','Inhalant use, unspecified with inhalant-induced anxiety disorder','Troubles mentaux et du comportement','F18.980'),
('Inhalant use, non spécifié with autre inhalant-induced trouble','Inhalant use, unspecified with other inhalant-induced disorder','Troubles mentaux et du comportement','F18.988'),
('Inhalant use, non spécifié with non spécifié inhalant-induced trouble','Inhalant use, unspecified with unspecified inhalant-induced disorder','Troubles mentaux et du comportement','F18.99'),
('autre psychoactive substance abuse, uncomplicated','Other psychoactive substance abuse, uncomplicated','Troubles mentaux et du comportement','F19.10'),
('autre psychoactive substance abuse, in remission','Other psychoactive substance abuse, in remission','Troubles mentaux et du comportement','F19.11'),
('autre psychoactive substance abuse with intoxication, uncomplicated','Other psychoactive substance abuse with intoxication, uncomplicated','Troubles mentaux et du comportement','F19.120'),
('autre psychoactive substance abuse with intoxication delirium','Other psychoactive substance abuse with intoxication delirium','Troubles mentaux et du comportement','F19.121'),
('autre psychoactive substance abuse with intoxication with perceptual disturbances','Other psychoactive substance abuse with intoxication with perceptual disturbances','Troubles mentaux et du comportement','F19.122'),
('autre psychoactive substance abuse with intoxication, non spécifié','Other psychoactive substance abuse with intoxication, unspecified','Troubles mentaux et du comportement','F19.129'),
('autre psychoactive substance abuse with withdrawal, uncomplicated','Other psychoactive substance abuse with withdrawal, uncomplicated','Troubles mentaux et du comportement','F19.130'),
('autre psychoactive substance abuse with withdrawal delirium','Other psychoactive substance abuse with withdrawal delirium','Troubles mentaux et du comportement','F19.131'),
('autre psychoactive substance abuse with withdrawal with perceptual disturbance','Other psychoactive substance abuse with withdrawal with perceptual disturbance','Troubles mentaux et du comportement','F19.132'),
('autre psychoactive substance abuse with withdrawal, non spécifié','Other psychoactive substance abuse with withdrawal, unspecified','Troubles mentaux et du comportement','F19.139'),
('autre psychoactive substance abuse with psychoactive substance-induced mood trouble','Other psychoactive substance abuse with psychoactive substance-induced mood disorder','Troubles mentaux et du comportement','F19.14'),
('autre psychoactive substance abuse with psychoactive substance-induced psychotic trouble with delusions','Other psychoactive substance abuse with psychoactive substance-induced psychotic disorder with delusions','Troubles mentaux et du comportement','F19.150'),
('autre psychoactive substance abuse with psychoactive substance-induced psychotic trouble with hallucinations','Other psychoactive substance abuse with psychoactive substance-induced psychotic disorder with hallucinations','Troubles mentaux et du comportement','F19.151'),
('autre psychoactive substance abuse with psychoactive substance-induced psychotic trouble, non spécifié','Other psychoactive substance abuse with psychoactive substance-induced psychotic disorder, unspecified','Troubles mentaux et du comportement','F19.159'),
('autre psychoactive substance abuse with psychoactive substance-induced persisting amnestic trouble','Other psychoactive substance abuse with psychoactive substance-induced persisting amnestic disorder','Troubles mentaux et du comportement','F19.16'),
('autre psychoactive substance abuse with psychoactive substance-induced persisting dementia','Other psychoactive substance abuse with psychoactive substance-induced persisting dementia','Troubles mentaux et du comportement','F19.17'),
('autre psychoactive substance abuse with psychoactive substance-induced anxiety trouble','Other psychoactive substance abuse with psychoactive substance-induced anxiety disorder','Troubles mentaux et du comportement','F19.180'),
('autre psychoactive substance abuse with psychoactive substance-induced sexual dysfunction','Other psychoactive substance abuse with psychoactive substance-induced sexual dysfunction','Troubles mentaux et du comportement','F19.181'),
('autre psychoactive substance abuse with psychoactive substance-induced sleep trouble','Other psychoactive substance abuse with psychoactive substance-induced sleep disorder','Troubles mentaux et du comportement','F19.182'),
('autre psychoactive substance abuse with autre psychoactive substance-induced trouble','Other psychoactive substance abuse with other psychoactive substance-induced disorder','Troubles mentaux et du comportement','F19.188'),
('autre psychoactive substance abuse with non spécifié psychoactive substance-induced trouble','Other psychoactive substance abuse with unspecified psychoactive substance-induced disorder','Troubles mentaux et du comportement','F19.19'),
('autre psychoactive substance dependence, uncomplicated','Other psychoactive substance dependence, uncomplicated','Troubles mentaux et du comportement','F19.20'),
('autre psychoactive substance dependence, in remission','Other psychoactive substance dependence, in remission','Troubles mentaux et du comportement','F19.21'),
('autre psychoactive substance dependence with intoxication, uncomplicated','Other psychoactive substance dependence with intoxication, uncomplicated','Troubles mentaux et du comportement','F19.220'),
('autre psychoactive substance dependence with intoxication delirium','Other psychoactive substance dependence with intoxication delirium','Troubles mentaux et du comportement','F19.221'),
('autre psychoactive substance dependence with intoxication with perceptual disturbance','Other psychoactive substance dependence with intoxication with perceptual disturbance','Troubles mentaux et du comportement','F19.222'),
('autre psychoactive substance dependence with intoxication, non spécifié','Other psychoactive substance dependence with intoxication, unspecified','Troubles mentaux et du comportement','F19.229'),
('autre psychoactive substance dependence with withdrawal, uncomplicated','Other psychoactive substance dependence with withdrawal, uncomplicated','Troubles mentaux et du comportement','F19.230'),
('autre psychoactive substance dependence with withdrawal delirium','Other psychoactive substance dependence with withdrawal delirium','Troubles mentaux et du comportement','F19.231'),
('autre psychoactive substance dependence with withdrawal with perceptual disturbance','Other psychoactive substance dependence with withdrawal with perceptual disturbance','Troubles mentaux et du comportement','F19.232'),
('autre psychoactive substance dependence with withdrawal, non spécifié','Other psychoactive substance dependence with withdrawal, unspecified','Troubles mentaux et du comportement','F19.239'),
('autre psychoactive substance dependence with psychoactive substance-induced mood trouble','Other psychoactive substance dependence with psychoactive substance-induced mood disorder','Troubles mentaux et du comportement','F19.24'),
('autre psychoactive substance dependence with psychoactive substance-induced psychotic trouble with delusions','Other psychoactive substance dependence with psychoactive substance-induced psychotic disorder with delusions','Troubles mentaux et du comportement','F19.250'),
('autre psychoactive substance dependence with psychoactive substance-induced psychotic trouble with hallucinations','Other psychoactive substance dependence with psychoactive substance-induced psychotic disorder with hallucinations','Troubles mentaux et du comportement','F19.251'),
('autre psychoactive substance dependence with psychoactive substance-induced psychotic trouble, non spécifié','Other psychoactive substance dependence with psychoactive substance-induced psychotic disorder, unspecified','Troubles mentaux et du comportement','F19.259')
ON CONFLICT (nom_fr) DO NOTHING;
