-- icd10v2_batch_435.sql (80 rows)
INSERT INTO pathologies (nom_fr, nom_en, categorie, icd10_code)
VALUES
('Struck by autre bat, racquet or club, initial encounter','Struck by other bat, racquet or club, initial encounter','Causes externes de morbidité et de mortalité','W21.19XA'),
('Struck by autre bat, racquet or club, subsequent encounter','Struck by other bat, racquet or club, subsequent encounter','Causes externes de morbidité et de mortalité','W21.19XD'),
('Struck by autre bat, racquet or club, sequela','Struck by other bat, racquet or club, sequela','Causes externes de morbidité et de mortalité','W21.19XS'),
('Struck by ice hockey stick, initial encounter','Struck by ice hockey stick, initial encounter','Causes externes de morbidité et de mortalité','W21.210A'),
('Struck by ice hockey stick, subsequent encounter','Struck by ice hockey stick, subsequent encounter','Causes externes de morbidité et de mortalité','W21.210D'),
('Struck by ice hockey stick, sequela','Struck by ice hockey stick, sequela','Causes externes de morbidité et de mortalité','W21.210S'),
('Struck by field hockey stick, initial encounter','Struck by field hockey stick, initial encounter','Causes externes de morbidité et de mortalité','W21.211A'),
('Struck by field hockey stick, subsequent encounter','Struck by field hockey stick, subsequent encounter','Causes externes de morbidité et de mortalité','W21.211D'),
('Struck by field hockey stick, sequela','Struck by field hockey stick, sequela','Causes externes de morbidité et de mortalité','W21.211S'),
('Struck by ice hockey puck, initial encounter','Struck by ice hockey puck, initial encounter','Causes externes de morbidité et de mortalité','W21.220A'),
('Struck by ice hockey puck, subsequent encounter','Struck by ice hockey puck, subsequent encounter','Causes externes de morbidité et de mortalité','W21.220D'),
('Struck by ice hockey puck, sequela','Struck by ice hockey puck, sequela','Causes externes de morbidité et de mortalité','W21.220S'),
('Struck by field hockey puck, initial encounter','Struck by field hockey puck, initial encounter','Causes externes de morbidité et de mortalité','W21.221A'),
('Struck by field hockey puck, subsequent encounter','Struck by field hockey puck, subsequent encounter','Causes externes de morbidité et de mortalité','W21.221D'),
('Struck by field hockey puck, sequela','Struck by field hockey puck, sequela','Causes externes de morbidité et de mortalité','W21.221S'),
('Struck by shoe cleats, initial encounter','Struck by shoe cleats, initial encounter','Causes externes de morbidité et de mortalité','W21.31XA'),
('Struck by shoe cleats, subsequent encounter','Struck by shoe cleats, subsequent encounter','Causes externes de morbidité et de mortalité','W21.31XD'),
('Struck by shoe cleats, sequela','Struck by shoe cleats, sequela','Causes externes de morbidité et de mortalité','W21.31XS'),
('Struck by skate blades, initial encounter','Struck by skate blades, initial encounter','Causes externes de morbidité et de mortalité','W21.32XA'),
('Struck by skate blades, subsequent encounter','Struck by skate blades, subsequent encounter','Causes externes de morbidité et de mortalité','W21.32XD'),
('Struck by skate blades, sequela','Struck by skate blades, sequela','Causes externes de morbidité et de mortalité','W21.32XS'),
('Struck by autre sports foot wear, initial encounter','Struck by other sports foot wear, initial encounter','Causes externes de morbidité et de mortalité','W21.39XA'),
('Struck by autre sports foot wear, subsequent encounter','Struck by other sports foot wear, subsequent encounter','Causes externes de morbidité et de mortalité','W21.39XD'),
('Struck by autre sports foot wear, sequela','Struck by other sports foot wear, sequela','Causes externes de morbidité et de mortalité','W21.39XS'),
('Striking against diving board, initial encounter','Striking against diving board, initial encounter','Causes externes de morbidité et de mortalité','W21.4XXA'),
('Striking against diving board, subsequent encounter','Striking against diving board, subsequent encounter','Causes externes de morbidité et de mortalité','W21.4XXD'),
('Striking against diving board, sequela','Striking against diving board, sequela','Causes externes de morbidité et de mortalité','W21.4XXS'),
('Striking against or struck by football helmet, initial encounter','Striking against or struck by football helmet, initial encounter','Causes externes de morbidité et de mortalité','W21.81XA'),
('Striking against or struck by football helmet, subsequent encounter','Striking against or struck by football helmet, subsequent encounter','Causes externes de morbidité et de mortalité','W21.81XD'),
('Striking against or struck by football helmet, sequela','Striking against or struck by football helmet, sequela','Causes externes de morbidité et de mortalité','W21.81XS'),
('Striking against or struck by autre sports equipment, initial encounter','Striking against or struck by other sports equipment, initial encounter','Causes externes de morbidité et de mortalité','W21.89XA'),
('Striking against or struck by autre sports equipment, subsequent encounter','Striking against or struck by other sports equipment, subsequent encounter','Causes externes de morbidité et de mortalité','W21.89XD'),
('Striking against or struck by autre sports equipment, sequela','Striking against or struck by other sports equipment, sequela','Causes externes de morbidité et de mortalité','W21.89XS'),
('Striking against or struck by non spécifié sports equipment, initial encounter','Striking against or struck by unspecified sports equipment, initial encounter','Causes externes de morbidité et de mortalité','W21.9XXA'),
('Striking against or struck by non spécifié sports equipment, subsequent encounter','Striking against or struck by unspecified sports equipment, subsequent encounter','Causes externes de morbidité et de mortalité','W21.9XXD'),
('Striking against or struck by non spécifié sports equipment, sequela','Striking against or struck by unspecified sports equipment, sequela','Causes externes de morbidité et de mortalité','W21.9XXS'),
('Walked into wall, initial encounter','Walked into wall, initial encounter','Causes externes de morbidité et de mortalité','W22.01XA'),
('Walked into wall, subsequent encounter','Walked into wall, subsequent encounter','Causes externes de morbidité et de mortalité','W22.01XD'),
('Walked into wall, sequela','Walked into wall, sequela','Causes externes de morbidité et de mortalité','W22.01XS'),
('Walked into lamppost, initial encounter','Walked into lamppost, initial encounter','Causes externes de morbidité et de mortalité','W22.02XA'),
('Walked into lamppost, subsequent encounter','Walked into lamppost, subsequent encounter','Causes externes de morbidité et de mortalité','W22.02XD'),
('Walked into lamppost, sequela','Walked into lamppost, sequela','Causes externes de morbidité et de mortalité','W22.02XS'),
('Walked into furniture, initial encounter','Walked into furniture, initial encounter','Causes externes de morbidité et de mortalité','W22.03XA'),
('Walked into furniture, subsequent encounter','Walked into furniture, subsequent encounter','Causes externes de morbidité et de mortalité','W22.03XD'),
('Walked into furniture, sequela','Walked into furniture, sequela','Causes externes de morbidité et de mortalité','W22.03XS'),
('Striking against wall of swimming pool causing drowning and submersion, initial encounter','Striking against wall of swimming pool causing drowning and submersion, initial encounter','Causes externes de morbidité et de mortalité','W22.041A'),
('Striking against wall of swimming pool causing drowning and submersion, subsequent encounter','Striking against wall of swimming pool causing drowning and submersion, subsequent encounter','Causes externes de morbidité et de mortalité','W22.041D'),
('Striking against wall of swimming pool causing drowning and submersion, sequela','Striking against wall of swimming pool causing drowning and submersion, sequela','Causes externes de morbidité et de mortalité','W22.041S'),
('Striking against wall of swimming pool causing autre injury, initial encounter','Striking against wall of swimming pool causing other injury, initial encounter','Causes externes de morbidité et de mortalité','W22.042A'),
('Striking against wall of swimming pool causing autre injury, subsequent encounter','Striking against wall of swimming pool causing other injury, subsequent encounter','Causes externes de morbidité et de mortalité','W22.042D'),
('Striking against wall of swimming pool causing autre injury, sequela','Striking against wall of swimming pool causing other injury, sequela','Causes externes de morbidité et de mortalité','W22.042S'),
('Striking against autre stationary object, initial encounter','Striking against other stationary object, initial encounter','Causes externes de morbidité et de mortalité','W22.09XA'),
('Striking against autre stationary object, subsequent encounter','Striking against other stationary object, subsequent encounter','Causes externes de morbidité et de mortalité','W22.09XD'),
('Striking against autre stationary object, sequela','Striking against other stationary object, sequela','Causes externes de morbidité et de mortalité','W22.09XS'),
('Striking against or struck by non spécifié automobile airbag, initial encounter','Striking against or struck by unspecified automobile airbag, initial encounter','Causes externes de morbidité et de mortalité','W22.10XA'),
('Striking against or struck by non spécifié automobile airbag, subsequent encounter','Striking against or struck by unspecified automobile airbag, subsequent encounter','Causes externes de morbidité et de mortalité','W22.10XD'),
('Striking against or struck by non spécifié automobile airbag, sequela','Striking against or struck by unspecified automobile airbag, sequela','Causes externes de morbidité et de mortalité','W22.10XS'),
('Striking against or struck by driver side automobile airbag, initial encounter','Striking against or struck by driver side automobile airbag, initial encounter','Causes externes de morbidité et de mortalité','W22.11XA'),
('Striking against or struck by driver side automobile airbag, subsequent encounter','Striking against or struck by driver side automobile airbag, subsequent encounter','Causes externes de morbidité et de mortalité','W22.11XD'),
('Striking against or struck by driver side automobile airbag, sequela','Striking against or struck by driver side automobile airbag, sequela','Causes externes de morbidité et de mortalité','W22.11XS'),
('Striking against or struck by front passenger side automobile airbag, initial encounter','Striking against or struck by front passenger side automobile airbag, initial encounter','Causes externes de morbidité et de mortalité','W22.12XA'),
('Striking against or struck by front passenger side automobile airbag, subsequent encounter','Striking against or struck by front passenger side automobile airbag, subsequent encounter','Causes externes de morbidité et de mortalité','W22.12XD'),
('Striking against or struck by front passenger side automobile airbag, sequela','Striking against or struck by front passenger side automobile airbag, sequela','Causes externes de morbidité et de mortalité','W22.12XS'),
('Striking against or struck by autre automobile airbag, initial encounter','Striking against or struck by other automobile airbag, initial encounter','Causes externes de morbidité et de mortalité','W22.19XA'),
('Striking against or struck by autre automobile airbag, subsequent encounter','Striking against or struck by other automobile airbag, subsequent encounter','Causes externes de morbidité et de mortalité','W22.19XD'),
('Striking against or struck by autre automobile airbag, sequela','Striking against or struck by other automobile airbag, sequela','Causes externes de morbidité et de mortalité','W22.19XS'),
('Striking against or struck by autre objects, initial encounter','Striking against or struck by other objects, initial encounter','Causes externes de morbidité et de mortalité','W22.8XXA'),
('Striking against or struck by autre objects, subsequent encounter','Striking against or struck by other objects, subsequent encounter','Causes externes de morbidité et de mortalité','W22.8XXD'),
('Striking against or struck by autre objects, sequela','Striking against or struck by other objects, sequela','Causes externes de morbidité et de mortalité','W22.8XXS'),
('Caught, crushed, jammed, or pinched between moving objects, initial encounter','Caught, crushed, jammed, or pinched between moving objects, initial encounter','Causes externes de morbidité et de mortalité','W23.0XXA'),
('Caught, crushed, jammed, or pinched between moving objects, subsequent encounter','Caught, crushed, jammed, or pinched between moving objects, subsequent encounter','Causes externes de morbidité et de mortalité','W23.0XXD'),
('Caught, crushed, jammed, or pinched between moving objects, sequela','Caught, crushed, jammed, or pinched between moving objects, sequela','Causes externes de morbidité et de mortalité','W23.0XXS'),
('Caught, crushed, jammed, or pinched between stationary objects, initial encounter','Caught, crushed, jammed, or pinched between stationary objects, initial encounter','Causes externes de morbidité et de mortalité','W23.1XXA'),
('Caught, crushed, jammed, or pinched between stationary objects, subsequent encounter','Caught, crushed, jammed, or pinched between stationary objects, subsequent encounter','Causes externes de morbidité et de mortalité','W23.1XXD'),
('Caught, crushed, jammed, or pinched between stationary objects, sequela','Caught, crushed, jammed, or pinched between stationary objects, sequela','Causes externes de morbidité et de mortalité','W23.1XXS'),
('Caught, crushed, jammed or pinched between a moving and stationary object, initial encounter','Caught, crushed, jammed or pinched between a moving and stationary object, initial encounter','Causes externes de morbidité et de mortalité','W23.2XXA'),
('Caught, crushed, jammed or pinched between a moving and stationary object, subsequent encounter','Caught, crushed, jammed or pinched between a moving and stationary object, subsequent encounter','Causes externes de morbidité et de mortalité','W23.2XXD'),
('Caught, crushed, jammed or pinched between a moving and stationary object, sequela','Caught, crushed, jammed or pinched between a moving and stationary object, sequela','Causes externes de morbidité et de mortalité','W23.2XXS'),
('Contact with lifting devices, not elsewhere classified, initial encounter','Contact with lifting devices, not elsewhere classified, initial encounter','Causes externes de morbidité et de mortalité','W24.0XXA'),
('Contact with lifting devices, not elsewhere classified, subsequent encounter','Contact with lifting devices, not elsewhere classified, subsequent encounter','Causes externes de morbidité et de mortalité','W24.0XXD')
ON CONFLICT (nom_fr) DO NOTHING;
