-- icd10v2_batch_339.sql (80 rows)
INSERT INTO pathologies (nom_fr, nom_en, categorie, icd10_code)
VALUES
('Food in respiratory tract, part non spécifié causing asphyxiation, initial encounter','Food in respiratory tract, part unspecified causing asphyxiation, initial encounter','Traumatismes, empoisonnements et autres causes externes','T17.920A'),
('Food in respiratory tract, part non spécifié causing asphyxiation, subsequent encounter','Food in respiratory tract, part unspecified causing asphyxiation, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T17.920D'),
('Food in respiratory tract, part non spécifié causing asphyxiation, sequela','Food in respiratory tract, part unspecified causing asphyxiation, sequela','Traumatismes, empoisonnements et autres causes externes','T17.920S'),
('Food in respiratory tract, part non spécifié causing autre injury, initial encounter','Food in respiratory tract, part unspecified causing other injury, initial encounter','Traumatismes, empoisonnements et autres causes externes','T17.928A'),
('Food in respiratory tract, part non spécifié causing autre injury, subsequent encounter','Food in respiratory tract, part unspecified causing other injury, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T17.928D'),
('Food in respiratory tract, part non spécifié causing autre injury, sequela','Food in respiratory tract, part unspecified causing other injury, sequela','Traumatismes, empoisonnements et autres causes externes','T17.928S'),
('autre foreign object in respiratory tract, part non spécifié in causing asphyxiation, initial encounter','Other foreign object in respiratory tract, part unspecified in causing asphyxiation, initial encounter','Traumatismes, empoisonnements et autres causes externes','T17.990A'),
('autre foreign object in respiratory tract, part non spécifié in causing asphyxiation, subsequent encounter','Other foreign object in respiratory tract, part unspecified in causing asphyxiation, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T17.990D'),
('autre foreign object in respiratory tract, part non spécifié in causing asphyxiation, sequela','Other foreign object in respiratory tract, part unspecified in causing asphyxiation, sequela','Traumatismes, empoisonnements et autres causes externes','T17.990S'),
('autre foreign object in respiratory tract, part non spécifié causing autre injury, initial encounter','Other foreign object in respiratory tract, part unspecified causing other injury, initial encounter','Traumatismes, empoisonnements et autres causes externes','T17.998A'),
('autre foreign object in respiratory tract, part non spécifié causing autre injury, subsequent encounter','Other foreign object in respiratory tract, part unspecified causing other injury, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T17.998D'),
('autre foreign object in respiratory tract, part non spécifié causing autre injury, sequela','Other foreign object in respiratory tract, part unspecified causing other injury, sequela','Traumatismes, empoisonnements et autres causes externes','T17.998S'),
('Foreign body in mouth, initial encounter','Foreign body in mouth, initial encounter','Traumatismes, empoisonnements et autres causes externes','T18.0XXA'),
('Foreign body in mouth, subsequent encounter','Foreign body in mouth, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T18.0XXD'),
('Foreign body in mouth, sequela','Foreign body in mouth, sequela','Traumatismes, empoisonnements et autres causes externes','T18.0XXS'),
('non spécifié foreign body in esophagus causing compression of trachea, initial encounter','Unspecified foreign body in esophagus causing compression of trachea, initial encounter','Traumatismes, empoisonnements et autres causes externes','T18.100A'),
('non spécifié foreign body in esophagus causing compression of trachea, subsequent encounter','Unspecified foreign body in esophagus causing compression of trachea, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T18.100D'),
('non spécifié foreign body in esophagus causing compression of trachea, sequela','Unspecified foreign body in esophagus causing compression of trachea, sequela','Traumatismes, empoisonnements et autres causes externes','T18.100S'),
('non spécifié foreign body in esophagus causing autre injury, initial encounter','Unspecified foreign body in esophagus causing other injury, initial encounter','Traumatismes, empoisonnements et autres causes externes','T18.108A'),
('non spécifié foreign body in esophagus causing autre injury, subsequent encounter','Unspecified foreign body in esophagus causing other injury, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T18.108D'),
('non spécifié foreign body in esophagus causing autre injury, sequela','Unspecified foreign body in esophagus causing other injury, sequela','Traumatismes, empoisonnements et autres causes externes','T18.108S'),
('Gastric contents in esophagus causing compression of trachea, initial encounter','Gastric contents in esophagus causing compression of trachea, initial encounter','Traumatismes, empoisonnements et autres causes externes','T18.110A'),
('Gastric contents in esophagus causing compression of trachea, subsequent encounter','Gastric contents in esophagus causing compression of trachea, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T18.110D'),
('Gastric contents in esophagus causing compression of trachea, sequela','Gastric contents in esophagus causing compression of trachea, sequela','Traumatismes, empoisonnements et autres causes externes','T18.110S'),
('Gastric contents in esophagus causing autre injury, initial encounter','Gastric contents in esophagus causing other injury, initial encounter','Traumatismes, empoisonnements et autres causes externes','T18.118A'),
('Gastric contents in esophagus causing autre injury, subsequent encounter','Gastric contents in esophagus causing other injury, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T18.118D'),
('Gastric contents in esophagus causing autre injury, sequela','Gastric contents in esophagus causing other injury, sequela','Traumatismes, empoisonnements et autres causes externes','T18.118S'),
('Food in esophagus causing compression of trachea, initial encounter','Food in esophagus causing compression of trachea, initial encounter','Traumatismes, empoisonnements et autres causes externes','T18.120A'),
('Food in esophagus causing compression of trachea, subsequent encounter','Food in esophagus causing compression of trachea, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T18.120D'),
('Food in esophagus causing compression of trachea, sequela','Food in esophagus causing compression of trachea, sequela','Traumatismes, empoisonnements et autres causes externes','T18.120S'),
('Food in esophagus causing autre injury, initial encounter','Food in esophagus causing other injury, initial encounter','Traumatismes, empoisonnements et autres causes externes','T18.128A'),
('Food in esophagus causing autre injury, subsequent encounter','Food in esophagus causing other injury, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T18.128D'),
('Food in esophagus causing autre injury, sequela','Food in esophagus causing other injury, sequela','Traumatismes, empoisonnements et autres causes externes','T18.128S'),
('autre foreign object in esophagus causing compression of trachea, initial encounter','Other foreign object in esophagus causing compression of trachea, initial encounter','Traumatismes, empoisonnements et autres causes externes','T18.190A'),
('autre foreign object in esophagus causing compression of trachea, subsequent encounter','Other foreign object in esophagus causing compression of trachea, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T18.190D'),
('autre foreign object in esophagus causing compression of trachea, sequela','Other foreign object in esophagus causing compression of trachea, sequela','Traumatismes, empoisonnements et autres causes externes','T18.190S'),
('autre foreign object in esophagus causing autre injury, initial encounter','Other foreign object in esophagus causing other injury, initial encounter','Traumatismes, empoisonnements et autres causes externes','T18.198A'),
('autre foreign object in esophagus causing autre injury, subsequent encounter','Other foreign object in esophagus causing other injury, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T18.198D'),
('autre foreign object in esophagus causing autre injury, sequela','Other foreign object in esophagus causing other injury, sequela','Traumatismes, empoisonnements et autres causes externes','T18.198S'),
('Foreign body in stomach, initial encounter','Foreign body in stomach, initial encounter','Traumatismes, empoisonnements et autres causes externes','T18.2XXA'),
('Foreign body in stomach, subsequent encounter','Foreign body in stomach, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T18.2XXD'),
('Foreign body in stomach, sequela','Foreign body in stomach, sequela','Traumatismes, empoisonnements et autres causes externes','T18.2XXS'),
('Foreign body in small intestine, initial encounter','Foreign body in small intestine, initial encounter','Traumatismes, empoisonnements et autres causes externes','T18.3XXA'),
('Foreign body in small intestine, subsequent encounter','Foreign body in small intestine, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T18.3XXD'),
('Foreign body in small intestine, sequela','Foreign body in small intestine, sequela','Traumatismes, empoisonnements et autres causes externes','T18.3XXS'),
('Foreign body in colon, initial encounter','Foreign body in colon, initial encounter','Traumatismes, empoisonnements et autres causes externes','T18.4XXA'),
('Foreign body in colon, subsequent encounter','Foreign body in colon, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T18.4XXD'),
('Foreign body in colon, sequela','Foreign body in colon, sequela','Traumatismes, empoisonnements et autres causes externes','T18.4XXS'),
('Foreign body in anus and rectum, initial encounter','Foreign body in anus and rectum, initial encounter','Traumatismes, empoisonnements et autres causes externes','T18.5XXA'),
('Foreign body in anus and rectum, subsequent encounter','Foreign body in anus and rectum, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T18.5XXD'),
('Foreign body in anus and rectum, sequela','Foreign body in anus and rectum, sequela','Traumatismes, empoisonnements et autres causes externes','T18.5XXS'),
('Foreign body in autre parts of alimentary tract, initial encounter','Foreign body in other parts of alimentary tract, initial encounter','Traumatismes, empoisonnements et autres causes externes','T18.8XXA'),
('Foreign body in autre parts of alimentary tract, subsequent encounter','Foreign body in other parts of alimentary tract, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T18.8XXD'),
('Foreign body in autre parts of alimentary tract, sequela','Foreign body in other parts of alimentary tract, sequela','Traumatismes, empoisonnements et autres causes externes','T18.8XXS'),
('Foreign body of alimentary tract, part non spécifié, initial encounter','Foreign body of alimentary tract, part unspecified, initial encounter','Traumatismes, empoisonnements et autres causes externes','T18.9XXA'),
('Foreign body of alimentary tract, part non spécifié, subsequent encounter','Foreign body of alimentary tract, part unspecified, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T18.9XXD'),
('Foreign body of alimentary tract, part non spécifié, sequela','Foreign body of alimentary tract, part unspecified, sequela','Traumatismes, empoisonnements et autres causes externes','T18.9XXS'),
('Foreign body in urethra, initial encounter','Foreign body in urethra, initial encounter','Traumatismes, empoisonnements et autres causes externes','T19.0XXA'),
('Foreign body in urethra, subsequent encounter','Foreign body in urethra, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T19.0XXD'),
('Foreign body in urethra, sequela','Foreign body in urethra, sequela','Traumatismes, empoisonnements et autres causes externes','T19.0XXS'),
('Foreign body in bladder, initial encounter','Foreign body in bladder, initial encounter','Traumatismes, empoisonnements et autres causes externes','T19.1XXA'),
('Foreign body in bladder, subsequent encounter','Foreign body in bladder, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T19.1XXD'),
('Foreign body in bladder, sequela','Foreign body in bladder, sequela','Traumatismes, empoisonnements et autres causes externes','T19.1XXS'),
('Foreign body in vulva and vagina, initial encounter','Foreign body in vulva and vagina, initial encounter','Traumatismes, empoisonnements et autres causes externes','T19.2XXA'),
('Foreign body in vulva and vagina, subsequent encounter','Foreign body in vulva and vagina, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T19.2XXD'),
('Foreign body in vulva and vagina, sequela','Foreign body in vulva and vagina, sequela','Traumatismes, empoisonnements et autres causes externes','T19.2XXS'),
('Foreign body in uterus, initial encounter','Foreign body in uterus, initial encounter','Traumatismes, empoisonnements et autres causes externes','T19.3XXA'),
('Foreign body in uterus, subsequent encounter','Foreign body in uterus, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T19.3XXD'),
('Foreign body in uterus, sequela','Foreign body in uterus, sequela','Traumatismes, empoisonnements et autres causes externes','T19.3XXS'),
('Foreign body in penis, initial encounter','Foreign body in penis, initial encounter','Traumatismes, empoisonnements et autres causes externes','T19.4XXA'),
('Foreign body in penis, subsequent encounter','Foreign body in penis, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T19.4XXD'),
('Foreign body in penis, sequela','Foreign body in penis, sequela','Traumatismes, empoisonnements et autres causes externes','T19.4XXS'),
('Foreign body in autre parts of genitourinary tract, initial encounter','Foreign body in other parts of genitourinary tract, initial encounter','Traumatismes, empoisonnements et autres causes externes','T19.8XXA'),
('Foreign body in autre parts of genitourinary tract, subsequent encounter','Foreign body in other parts of genitourinary tract, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T19.8XXD'),
('Foreign body in autre parts of genitourinary tract, sequela','Foreign body in other parts of genitourinary tract, sequela','Traumatismes, empoisonnements et autres causes externes','T19.8XXS'),
('Foreign body in genitourinary tract, part non spécifié, initial encounter','Foreign body in genitourinary tract, part unspecified, initial encounter','Traumatismes, empoisonnements et autres causes externes','T19.9XXA'),
('Foreign body in genitourinary tract, part non spécifié, subsequent encounter','Foreign body in genitourinary tract, part unspecified, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T19.9XXD'),
('Foreign body in genitourinary tract, part non spécifié, sequela','Foreign body in genitourinary tract, part unspecified, sequela','Traumatismes, empoisonnements et autres causes externes','T19.9XXS'),
('Subluxation of T2/T3 thoracic vertebra, sequela','Subluxation of T2/T3 thoracic vertebra, sequela','Traumatismes, empoisonnements et autres causes externes','S23.120S'),
('Luxation de T2/T3 thoracic vertebra, sequela','Dislocation of T2/T3 thoracic vertebra, sequela','Traumatismes, empoisonnements et autres causes externes','S23.121S')
ON CONFLICT (nom_fr) DO NOTHING;
