-- icd10v2_batch_056.sql (80 rows)
INSERT INTO pathologies (nom_fr, nom_en, categorie, icd10_code)
VALUES
('Dementia in autre diseases classified elsewhere, moderate, with anxiety','Dementia in other diseases classified elsewhere, moderate, with anxiety','Troubles mentaux et du comportement','F02.B4'),
('Dementia in autre diseases classified elsewhere, severe, without behavioral disturbance, psychotic disturbance, mood disturbance, and anxiety','Dementia in other diseases classified elsewhere, severe, without behavioral disturbance, psychotic disturbance, mood disturbance, and anxiety','Troubles mentaux et du comportement','F02.C0'),
('Dementia in autre diseases classified elsewhere, severe, with agitation','Dementia in other diseases classified elsewhere, severe, with agitation','Troubles mentaux et du comportement','F02.C11'),
('Dementia in autre diseases classified elsewhere, severe, with autre behavioral disturbance','Dementia in other diseases classified elsewhere, severe, with other behavioral disturbance','Troubles mentaux et du comportement','F02.C18'),
('Dementia in autre diseases classified elsewhere, severe, with psychotic disturbance','Dementia in other diseases classified elsewhere, severe, with psychotic disturbance','Troubles mentaux et du comportement','F02.C2'),
('Dementia in autre diseases classified elsewhere, severe, with mood disturbance','Dementia in other diseases classified elsewhere, severe, with mood disturbance','Troubles mentaux et du comportement','F02.C3'),
('Dementia in autre diseases classified elsewhere, severe, with anxiety','Dementia in other diseases classified elsewhere, severe, with anxiety','Troubles mentaux et du comportement','F02.C4'),
('non spécifié dementia, non spécifié severity, without behavioral disturbance, psychotic disturbance, mood disturbance, and anxiety','Unspecified dementia, unspecified severity, without behavioral disturbance, psychotic disturbance, mood disturbance, and anxiety','Troubles mentaux et du comportement','F03.90'),
('non spécifié dementia, non spécifié severity, with agitation','Unspecified dementia, unspecified severity, with agitation','Troubles mentaux et du comportement','F03.911'),
('non spécifié dementia, non spécifié severity, with autre behavioral disturbance','Unspecified dementia, unspecified severity, with other behavioral disturbance','Troubles mentaux et du comportement','F03.918'),
('non spécifié dementia, non spécifié severity, with psychotic disturbance','Unspecified dementia, unspecified severity, with psychotic disturbance','Troubles mentaux et du comportement','F03.92'),
('non spécifié dementia, non spécifié severity, with mood disturbance','Unspecified dementia, unspecified severity, with mood disturbance','Troubles mentaux et du comportement','F03.93'),
('non spécifié dementia, non spécifié severity, with anxiety','Unspecified dementia, unspecified severity, with anxiety','Troubles mentaux et du comportement','F03.94'),
('non spécifié dementia, mild, without behavioral disturbance, psychotic disturbance, mood disturbance, and anxiety','Unspecified dementia, mild, without behavioral disturbance, psychotic disturbance, mood disturbance, and anxiety','Troubles mentaux et du comportement','F03.A0'),
('non spécifié dementia, mild, with agitation','Unspecified dementia, mild, with agitation','Troubles mentaux et du comportement','F03.A11'),
('non spécifié dementia, mild, with autre behavioral disturbance','Unspecified dementia, mild, with other behavioral disturbance','Troubles mentaux et du comportement','F03.A18'),
('non spécifié dementia, mild, with psychotic disturbance','Unspecified dementia, mild, with psychotic disturbance','Troubles mentaux et du comportement','F03.A2'),
('non spécifié dementia, mild, with mood disturbance','Unspecified dementia, mild, with mood disturbance','Troubles mentaux et du comportement','F03.A3'),
('non spécifié dementia, mild, with anxiety','Unspecified dementia, mild, with anxiety','Troubles mentaux et du comportement','F03.A4'),
('non spécifié dementia, moderate, without behavioral disturbance, psychotic disturbance, mood disturbance, and anxiety','Unspecified dementia, moderate, without behavioral disturbance, psychotic disturbance, mood disturbance, and anxiety','Troubles mentaux et du comportement','F03.B0'),
('non spécifié dementia, moderate, with agitation','Unspecified dementia, moderate, with agitation','Troubles mentaux et du comportement','F03.B11'),
('non spécifié dementia, moderate, with autre behavioral disturbance','Unspecified dementia, moderate, with other behavioral disturbance','Troubles mentaux et du comportement','F03.B18'),
('non spécifié dementia, moderate, with psychotic disturbance','Unspecified dementia, moderate, with psychotic disturbance','Troubles mentaux et du comportement','F03.B2'),
('non spécifié dementia, moderate, with mood disturbance','Unspecified dementia, moderate, with mood disturbance','Troubles mentaux et du comportement','F03.B3'),
('non spécifié dementia, moderate, with anxiety','Unspecified dementia, moderate, with anxiety','Troubles mentaux et du comportement','F03.B4'),
('non spécifié dementia, severe, without behavioral disturbance, psychotic disturbance, mood disturbance, and anxiety','Unspecified dementia, severe, without behavioral disturbance, psychotic disturbance, mood disturbance, and anxiety','Troubles mentaux et du comportement','F03.C0'),
('non spécifié dementia, severe, with agitation','Unspecified dementia, severe, with agitation','Troubles mentaux et du comportement','F03.C11'),
('non spécifié dementia, severe, with autre behavioral disturbance','Unspecified dementia, severe, with other behavioral disturbance','Troubles mentaux et du comportement','F03.C18'),
('non spécifié dementia, severe, with psychotic disturbance','Unspecified dementia, severe, with psychotic disturbance','Troubles mentaux et du comportement','F03.C2'),
('non spécifié dementia, severe, with mood disturbance','Unspecified dementia, severe, with mood disturbance','Troubles mentaux et du comportement','F03.C3'),
('non spécifié dementia, severe, with anxiety','Unspecified dementia, severe, with anxiety','Troubles mentaux et du comportement','F03.C4'),
('Amnestic trouble due to known physiological condition','Amnestic disorder due to known physiological condition','Troubles mentaux et du comportement','F04'),
('Delirium due to known physiological condition','Delirium due to known physiological condition','Troubles mentaux et du comportement','F05'),
('Psychotic trouble with hallucinations due to known physiological condition','Psychotic disorder with hallucinations due to known physiological condition','Troubles mentaux et du comportement','F06.0'),
('Catatonic trouble due to known physiological condition','Catatonic disorder due to known physiological condition','Troubles mentaux et du comportement','F06.1'),
('Psychotic trouble with delusions due to known physiological condition','Psychotic disorder with delusions due to known physiological condition','Troubles mentaux et du comportement','F06.2'),
('Mood trouble due to known physiological condition, non spécifié','Mood disorder due to known physiological condition, unspecified','Troubles mentaux et du comportement','F06.30'),
('Mood trouble due to known physiological condition with depressive features','Mood disorder due to known physiological condition with depressive features','Troubles mentaux et du comportement','F06.31'),
('Mood trouble due to known physiological condition with major depressive-like episode','Mood disorder due to known physiological condition with major depressive-like episode','Troubles mentaux et du comportement','F06.32'),
('Mood trouble due to known physiological condition with manic features','Mood disorder due to known physiological condition with manic features','Troubles mentaux et du comportement','F06.33'),
('Mood trouble due to known physiological condition with mixed features','Mood disorder due to known physiological condition with mixed features','Troubles mentaux et du comportement','F06.34'),
('Anxiety trouble due to known physiological condition','Anxiety disorder due to known physiological condition','Troubles mentaux et du comportement','F06.4'),
('Mild neurocognitive trouble due to known physiological condition without behavioral disturbance','Mild neurocognitive disorder due to known physiological condition without behavioral disturbance','Troubles mentaux et du comportement','F06.70'),
('Mild neurocognitive trouble due to known physiological condition with behavioral disturbance','Mild neurocognitive disorder due to known physiological condition with behavioral disturbance','Troubles mentaux et du comportement','F06.71'),
('autre specified mental disorders due to known physiological condition','Other specified mental disorders due to known physiological condition','Troubles mentaux et du comportement','F06.8'),
('Personality change due to known physiological condition','Personality change due to known physiological condition','Troubles mentaux et du comportement','F07.0'),
('Postconcussional syndrome','Postconcussional syndrome','Troubles mentaux et du comportement','F07.81'),
('autre personality and behavioral disorders due to known physiological condition','Other personality and behavioral disorders due to known physiological condition','Troubles mentaux et du comportement','F07.89'),
('non spécifié personality and behavioral trouble due to known physiological condition','Unspecified personality and behavioral disorder due to known physiological condition','Troubles mentaux et du comportement','F07.9'),
('non spécifié mental trouble due to known physiological condition','Unspecified mental disorder due to known physiological condition','Troubles mentaux et du comportement','F09'),
('Alcohol abuse, uncomplicated','Alcohol abuse, uncomplicated','Troubles mentaux et du comportement','F10.10'),
('Alcohol abuse, in remission','Alcohol abuse, in remission','Troubles mentaux et du comportement','F10.11'),
('Alcohol abuse with intoxication, uncomplicated','Alcohol abuse with intoxication, uncomplicated','Troubles mentaux et du comportement','F10.120'),
('Alcohol abuse with intoxication delirium','Alcohol abuse with intoxication delirium','Troubles mentaux et du comportement','F10.121'),
('Alcohol abuse with intoxication, non spécifié','Alcohol abuse with intoxication, unspecified','Troubles mentaux et du comportement','F10.129'),
('Alcohol abuse with withdrawal, uncomplicated','Alcohol abuse with withdrawal, uncomplicated','Troubles mentaux et du comportement','F10.130'),
('Alcohol abuse with withdrawal delirium','Alcohol abuse with withdrawal delirium','Troubles mentaux et du comportement','F10.131'),
('Alcohol abuse with withdrawal with perceptual disturbance','Alcohol abuse with withdrawal with perceptual disturbance','Troubles mentaux et du comportement','F10.132'),
('Alcohol abuse with withdrawal, non spécifié','Alcohol abuse with withdrawal, unspecified','Troubles mentaux et du comportement','F10.139'),
('Alcohol abuse with alcohol-induced mood trouble','Alcohol abuse with alcohol-induced mood disorder','Troubles mentaux et du comportement','F10.14'),
('Alcohol abuse with alcohol-induced psychotic trouble with delusions','Alcohol abuse with alcohol-induced psychotic disorder with delusions','Troubles mentaux et du comportement','F10.150'),
('Alcohol abuse with alcohol-induced psychotic trouble with hallucinations','Alcohol abuse with alcohol-induced psychotic disorder with hallucinations','Troubles mentaux et du comportement','F10.151'),
('Alcohol abuse with alcohol-induced psychotic trouble, non spécifié','Alcohol abuse with alcohol-induced psychotic disorder, unspecified','Troubles mentaux et du comportement','F10.159'),
('Alcohol abuse with alcohol-induced anxiety trouble','Alcohol abuse with alcohol-induced anxiety disorder','Troubles mentaux et du comportement','F10.180'),
('Alcohol abuse with alcohol-induced sexual dysfunction','Alcohol abuse with alcohol-induced sexual dysfunction','Troubles mentaux et du comportement','F10.181'),
('Alcohol abuse with alcohol-induced sleep trouble','Alcohol abuse with alcohol-induced sleep disorder','Troubles mentaux et du comportement','F10.182'),
('Alcohol abuse with autre alcohol-induced trouble','Alcohol abuse with other alcohol-induced disorder','Troubles mentaux et du comportement','F10.188'),
('Alcohol abuse with non spécifié alcohol-induced trouble','Alcohol abuse with unspecified alcohol-induced disorder','Troubles mentaux et du comportement','F10.19'),
('Alcohol dependence, uncomplicated','Alcohol dependence, uncomplicated','Troubles mentaux et du comportement','F10.20'),
('Alcohol dependence, in remission','Alcohol dependence, in remission','Troubles mentaux et du comportement','F10.21'),
('Alcohol dependence with intoxication, uncomplicated','Alcohol dependence with intoxication, uncomplicated','Troubles mentaux et du comportement','F10.220'),
('Alcohol dependence with intoxication delirium','Alcohol dependence with intoxication delirium','Troubles mentaux et du comportement','F10.221'),
('Alcohol dependence with intoxication, non spécifié','Alcohol dependence with intoxication, unspecified','Troubles mentaux et du comportement','F10.229'),
('Alcohol dependence with withdrawal, uncomplicated','Alcohol dependence with withdrawal, uncomplicated','Troubles mentaux et du comportement','F10.230'),
('Alcohol dependence with withdrawal delirium','Alcohol dependence with withdrawal delirium','Troubles mentaux et du comportement','F10.231'),
('Alcohol dependence with withdrawal with perceptual disturbance','Alcohol dependence with withdrawal with perceptual disturbance','Troubles mentaux et du comportement','F10.232'),
('Alcohol dependence with withdrawal, non spécifié','Alcohol dependence with withdrawal, unspecified','Troubles mentaux et du comportement','F10.239'),
('Alcohol dependence with alcohol-induced mood trouble','Alcohol dependence with alcohol-induced mood disorder','Troubles mentaux et du comportement','F10.24'),
('Alcohol dependence with alcohol-induced psychotic trouble with delusions','Alcohol dependence with alcohol-induced psychotic disorder with delusions','Troubles mentaux et du comportement','F10.250'),
('Alcohol dependence with alcohol-induced psychotic trouble with hallucinations','Alcohol dependence with alcohol-induced psychotic disorder with hallucinations','Troubles mentaux et du comportement','F10.251')
ON CONFLICT (nom_fr) DO NOTHING;
