-- icd10v2_batch_108.sql (80 rows)
INSERT INTO pathologies (nom_fr, nom_en, categorie, icd10_code)
VALUES
('chronique perichondritis of external ear, bilateral','Chronic perichondritis of external ear, bilateral','Maladies de l''oreille et de l''apophyse mastoïde','H61.023'),
('chronique perichondritis of external ear, non spécifié ear','Chronic perichondritis of external ear, unspecified ear','Maladies de l''oreille et de l''apophyse mastoïde','H61.029'),
('Chondritis of right external ear','Chondritis of right external ear','Maladies de l''oreille et de l''apophyse mastoïde','H61.031'),
('Chondritis of left external ear','Chondritis of left external ear','Maladies de l''oreille et de l''apophyse mastoïde','H61.032'),
('Chondritis of external ear, bilateral','Chondritis of external ear, bilateral','Maladies de l''oreille et de l''apophyse mastoïde','H61.033'),
('Chondritis of external ear, non spécifié ear','Chondritis of external ear, unspecified ear','Maladies de l''oreille et de l''apophyse mastoïde','H61.039'),
('non spécifié noninfective disorders of pinna, right ear','Unspecified noninfective disorders of pinna, right ear','Maladies de l''oreille et de l''apophyse mastoïde','H61.101'),
('non spécifié noninfective disorders of pinna, left ear','Unspecified noninfective disorders of pinna, left ear','Maladies de l''oreille et de l''apophyse mastoïde','H61.102'),
('non spécifié noninfective disorders of pinna, bilateral','Unspecified noninfective disorders of pinna, bilateral','Maladies de l''oreille et de l''apophyse mastoïde','H61.103'),
('non spécifié noninfective disorders of pinna, non spécifié ear','Unspecified noninfective disorders of pinna, unspecified ear','Maladies de l''oreille et de l''apophyse mastoïde','H61.109'),
('Acquired deformity of pinna, right ear','Acquired deformity of pinna, right ear','Maladies de l''oreille et de l''apophyse mastoïde','H61.111'),
('Acquired deformity of pinna, left ear','Acquired deformity of pinna, left ear','Maladies de l''oreille et de l''apophyse mastoïde','H61.112'),
('Acquired deformity of pinna, bilateral','Acquired deformity of pinna, bilateral','Maladies de l''oreille et de l''apophyse mastoïde','H61.113'),
('Acquired deformity of pinna, non spécifié ear','Acquired deformity of pinna, unspecified ear','Maladies de l''oreille et de l''apophyse mastoïde','H61.119'),
('Hematoma of pinna, right ear','Hematoma of pinna, right ear','Maladies de l''oreille et de l''apophyse mastoïde','H61.121'),
('Hematoma of pinna, left ear','Hematoma of pinna, left ear','Maladies de l''oreille et de l''apophyse mastoïde','H61.122'),
('Hematoma of pinna, bilateral','Hematoma of pinna, bilateral','Maladies de l''oreille et de l''apophyse mastoïde','H61.123'),
('Hematoma of pinna, non spécifié ear','Hematoma of pinna, unspecified ear','Maladies de l''oreille et de l''apophyse mastoïde','H61.129'),
('Noninfective disorders of pinna, right ear','Noninfective disorders of pinna, right ear','Maladies de l''oreille et de l''apophyse mastoïde','H61.191'),
('Noninfective disorders of pinna, left ear','Noninfective disorders of pinna, left ear','Maladies de l''oreille et de l''apophyse mastoïde','H61.192'),
('Noninfective disorders of pinna, bilateral','Noninfective disorders of pinna, bilateral','Maladies de l''oreille et de l''apophyse mastoïde','H61.193'),
('Noninfective disorders of pinna, non spécifié ear','Noninfective disorders of pinna, unspecified ear','Maladies de l''oreille et de l''apophyse mastoïde','H61.199'),
('Impacted cerumen, non spécifié ear','Impacted cerumen, unspecified ear','Maladies de l''oreille et de l''apophyse mastoïde','H61.20'),
('Impacted cerumen, right ear','Impacted cerumen, right ear','Maladies de l''oreille et de l''apophyse mastoïde','H61.21'),
('Impacted cerumen, left ear','Impacted cerumen, left ear','Maladies de l''oreille et de l''apophyse mastoïde','H61.22'),
('Impacted cerumen, bilateral','Impacted cerumen, bilateral','Maladies de l''oreille et de l''apophyse mastoïde','H61.23'),
('Acquired sténose of right external ear canal, non spécifié','Acquired stenosis of right external ear canal, unspecified','Maladies de l''oreille et de l''apophyse mastoïde','H61.301'),
('Acquired sténose of left external ear canal, non spécifié','Acquired stenosis of left external ear canal, unspecified','Maladies de l''oreille et de l''apophyse mastoïde','H61.302'),
('Acquired sténose of external ear canal, non spécifié, bilateral','Acquired stenosis of external ear canal, unspecified, bilateral','Maladies de l''oreille et de l''apophyse mastoïde','H61.303'),
('Acquired sténose of external ear canal, non spécifié, non spécifié ear','Acquired stenosis of external ear canal, unspecified, unspecified ear','Maladies de l''oreille et de l''apophyse mastoïde','H61.309'),
('Acquired sténose of right external ear canal secondaire to trauma','Acquired stenosis of right external ear canal secondary to trauma','Maladies de l''oreille et de l''apophyse mastoïde','H61.311'),
('Acquired sténose of left external ear canal secondaire to trauma','Acquired stenosis of left external ear canal secondary to trauma','Maladies de l''oreille et de l''apophyse mastoïde','H61.312'),
('Acquired sténose of external ear canal secondaire to trauma, bilateral','Acquired stenosis of external ear canal secondary to trauma, bilateral','Maladies de l''oreille et de l''apophyse mastoïde','H61.313'),
('Acquired sténose of external ear canal secondaire to trauma, non spécifié ear','Acquired stenosis of external ear canal secondary to trauma, unspecified ear','Maladies de l''oreille et de l''apophyse mastoïde','H61.319'),
('Acquired sténose of right external ear canal secondaire to inflammation and infection','Acquired stenosis of right external ear canal secondary to inflammation and infection','Maladies de l''oreille et de l''apophyse mastoïde','H61.321'),
('Acquired sténose of left external ear canal secondaire to inflammation and infection','Acquired stenosis of left external ear canal secondary to inflammation and infection','Maladies de l''oreille et de l''apophyse mastoïde','H61.322'),
('Acquired sténose of external ear canal secondaire to inflammation and infection, bilateral','Acquired stenosis of external ear canal secondary to inflammation and infection, bilateral','Maladies de l''oreille et de l''apophyse mastoïde','H61.323'),
('Acquired sténose of external ear canal secondaire to inflammation and infection, non spécifié ear','Acquired stenosis of external ear canal secondary to inflammation and infection, unspecified ear','Maladies de l''oreille et de l''apophyse mastoïde','H61.329'),
('autre acquired sténose of right external ear canal','Other acquired stenosis of right external ear canal','Maladies de l''oreille et de l''apophyse mastoïde','H61.391'),
('autre acquired sténose of left external ear canal','Other acquired stenosis of left external ear canal','Maladies de l''oreille et de l''apophyse mastoïde','H61.392'),
('autre acquired sténose of external ear canal, bilateral','Other acquired stenosis of external ear canal, bilateral','Maladies de l''oreille et de l''apophyse mastoïde','H61.393'),
('autre acquired sténose of external ear canal, non spécifié ear','Other acquired stenosis of external ear canal, unspecified ear','Maladies de l''oreille et de l''apophyse mastoïde','H61.399'),
('Exostosis of right external canal','Exostosis of right external canal','Maladies de l''oreille et de l''apophyse mastoïde','H61.811'),
('Exostosis of left external canal','Exostosis of left external canal','Maladies de l''oreille et de l''apophyse mastoïde','H61.812'),
('Exostosis of external canal, bilateral','Exostosis of external canal, bilateral','Maladies de l''oreille et de l''apophyse mastoïde','H61.813'),
('Exostosis of external canal, non spécifié ear','Exostosis of external canal, unspecified ear','Maladies de l''oreille et de l''apophyse mastoïde','H61.819'),
('autre specified disorders of right external ear','Other specified disorders of right external ear','Maladies de l''oreille et de l''apophyse mastoïde','H61.891'),
('autre specified disorders of left external ear','Other specified disorders of left external ear','Maladies de l''oreille et de l''apophyse mastoïde','H61.892'),
('autre specified disorders of external ear, bilateral','Other specified disorders of external ear, bilateral','Maladies de l''oreille et de l''apophyse mastoïde','H61.893'),
('autre specified disorders of external ear, non spécifié ear','Other specified disorders of external ear, unspecified ear','Maladies de l''oreille et de l''apophyse mastoïde','H61.899'),
('trouble of external ear, non spécifié, non spécifié ear','Disorder of external ear, unspecified, unspecified ear','Maladies de l''oreille et de l''apophyse mastoïde','H61.90'),
('trouble of right external ear, non spécifié','Disorder of right external ear, unspecified','Maladies de l''oreille et de l''apophyse mastoïde','H61.91'),
('trouble of left external ear, non spécifié','Disorder of left external ear, unspecified','Maladies de l''oreille et de l''apophyse mastoïde','H61.92'),
('trouble of external ear, non spécifié, bilateral','Disorder of external ear, unspecified, bilateral','Maladies de l''oreille et de l''apophyse mastoïde','H61.93'),
('Otitis externa in autre diseases classified elsewhere, non spécifié ear','Otitis externa in other diseases classified elsewhere, unspecified ear','Maladies de l''oreille et de l''apophyse mastoïde','H62.40'),
('Otitis externa in autre diseases classified elsewhere, right ear','Otitis externa in other diseases classified elsewhere, right ear','Maladies de l''oreille et de l''apophyse mastoïde','H62.41'),
('Otitis externa in autre diseases classified elsewhere, left ear','Otitis externa in other diseases classified elsewhere, left ear','Maladies de l''oreille et de l''apophyse mastoïde','H62.42'),
('Otitis externa in autre diseases classified elsewhere, bilateral','Otitis externa in other diseases classified elsewhere, bilateral','Maladies de l''oreille et de l''apophyse mastoïde','H62.43'),
('autre disorders of right external ear in diseases classified elsewhere','Other disorders of right external ear in diseases classified elsewhere','Maladies de l''oreille et de l''apophyse mastoïde','H62.8X1'),
('autre disorders of left external ear in diseases classified elsewhere','Other disorders of left external ear in diseases classified elsewhere','Maladies de l''oreille et de l''apophyse mastoïde','H62.8X2'),
('autre disorders of external ear in diseases classified elsewhere, bilateral','Other disorders of external ear in diseases classified elsewhere, bilateral','Maladies de l''oreille et de l''apophyse mastoïde','H62.8X3'),
('autre disorders of external ear in diseases classified elsewhere, non spécifié ear','Other disorders of external ear in diseases classified elsewhere, unspecified ear','Maladies de l''oreille et de l''apophyse mastoïde','H62.8X9'),
('aigu serous otitis media, non spécifié ear','Acute serous otitis media, unspecified ear','Maladies de l''oreille et de l''apophyse mastoïde','H65.00'),
('aigu serous otitis media, right ear','Acute serous otitis media, right ear','Maladies de l''oreille et de l''apophyse mastoïde','H65.01'),
('aigu serous otitis media, left ear','Acute serous otitis media, left ear','Maladies de l''oreille et de l''apophyse mastoïde','H65.02'),
('aigu serous otitis media, bilateral','Acute serous otitis media, bilateral','Maladies de l''oreille et de l''apophyse mastoïde','H65.03'),
('aigu serous otitis media, recurrent, right ear','Acute serous otitis media, recurrent, right ear','Maladies de l''oreille et de l''apophyse mastoïde','H65.04'),
('aigu serous otitis media, recurrent, left ear','Acute serous otitis media, recurrent, left ear','Maladies de l''oreille et de l''apophyse mastoïde','H65.05'),
('aigu serous otitis media, recurrent, bilateral','Acute serous otitis media, recurrent, bilateral','Maladies de l''oreille et de l''apophyse mastoïde','H65.06'),
('aigu serous otitis media, recurrent, non spécifié ear','Acute serous otitis media, recurrent, unspecified ear','Maladies de l''oreille et de l''apophyse mastoïde','H65.07'),
('aigu and subacute allergic otitis media (mucoid) (sanguinous) (serous), right ear','Acute and subacute allergic otitis media (mucoid) (sanguinous) (serous), right ear','Maladies de l''oreille et de l''apophyse mastoïde','H65.111'),
('aigu and subacute allergic otitis media (mucoid) (sanguinous) (serous), left ear','Acute and subacute allergic otitis media (mucoid) (sanguinous) (serous), left ear','Maladies de l''oreille et de l''apophyse mastoïde','H65.112'),
('aigu and subacute allergic otitis media (mucoid) (sanguinous) (serous), bilateral','Acute and subacute allergic otitis media (mucoid) (sanguinous) (serous), bilateral','Maladies de l''oreille et de l''apophyse mastoïde','H65.113'),
('aigu and subacute allergic otitis media (mucoid) (sanguinous) (serous), recurrent, right ear','Acute and subacute allergic otitis media (mucoid) (sanguinous) (serous), recurrent, right ear','Maladies de l''oreille et de l''apophyse mastoïde','H65.114'),
('aigu and subacute allergic otitis media (mucoid) (sanguinous) (serous), recurrent, left ear','Acute and subacute allergic otitis media (mucoid) (sanguinous) (serous), recurrent, left ear','Maladies de l''oreille et de l''apophyse mastoïde','H65.115'),
('aigu and subacute allergic otitis media (mucoid) (sanguinous) (serous), recurrent, bilateral','Acute and subacute allergic otitis media (mucoid) (sanguinous) (serous), recurrent, bilateral','Maladies de l''oreille et de l''apophyse mastoïde','H65.116'),
('aigu and subacute allergic otitis media (mucoid) (sanguinous) (serous), recurrent, non spécifié ear','Acute and subacute allergic otitis media (mucoid) (sanguinous) (serous), recurrent, unspecified ear','Maladies de l''oreille et de l''apophyse mastoïde','H65.117'),
('aigu and subacute allergic otitis media (mucoid) (sanguinous) (serous), non spécifié ear','Acute and subacute allergic otitis media (mucoid) (sanguinous) (serous), unspecified ear','Maladies de l''oreille et de l''apophyse mastoïde','H65.119'),
('autre aigu nonsuppurative otitis media, right ear','Other acute nonsuppurative otitis media, right ear','Maladies de l''oreille et de l''apophyse mastoïde','H65.191'),
('autre aigu nonsuppurative otitis media, left ear','Other acute nonsuppurative otitis media, left ear','Maladies de l''oreille et de l''apophyse mastoïde','H65.192')
ON CONFLICT (nom_fr) DO NOTHING;
