-- icd10v2_batch_445.sql (80 rows)
INSERT INTO pathologies (nom_fr, nom_en, categorie, icd10_code)
VALUES
('Exposure to autre animate mechanical forces, sequela','Exposure to other animate mechanical forces, sequela','Causes externes de morbidité et de mortalité','W64.XXXS'),
('Accidental drowning and submersion while in bath-tub, initial encounter','Accidental drowning and submersion while in bath-tub, initial encounter','Causes externes de morbidité et de mortalité','W65.XXXA'),
('Accidental drowning and submersion while in bath-tub, subsequent encounter','Accidental drowning and submersion while in bath-tub, subsequent encounter','Causes externes de morbidité et de mortalité','W65.XXXD'),
('Accidental drowning and submersion while in bath-tub, sequela','Accidental drowning and submersion while in bath-tub, sequela','Causes externes de morbidité et de mortalité','W65.XXXS'),
('Accidental drowning and submersion while in swimming-pool, initial encounter','Accidental drowning and submersion while in swimming-pool, initial encounter','Causes externes de morbidité et de mortalité','W67.XXXA'),
('Accidental drowning and submersion while in swimming-pool, subsequent encounter','Accidental drowning and submersion while in swimming-pool, subsequent encounter','Causes externes de morbidité et de mortalité','W67.XXXD'),
('Accidental drowning and submersion while in swimming-pool, sequela','Accidental drowning and submersion while in swimming-pool, sequela','Causes externes de morbidité et de mortalité','W67.XXXS'),
('Accidental drowning and submersion while in natural water, initial encounter','Accidental drowning and submersion while in natural water, initial encounter','Causes externes de morbidité et de mortalité','W69.XXXA'),
('Accidental drowning and submersion while in natural water, subsequent encounter','Accidental drowning and submersion while in natural water, subsequent encounter','Causes externes de morbidité et de mortalité','W69.XXXD'),
('Accidental drowning and submersion while in natural water, sequela','Accidental drowning and submersion while in natural water, sequela','Causes externes de morbidité et de mortalité','W69.XXXS'),
('autre specified cause of accidental non-transport drowning and submersion, initial encounter','Other specified cause of accidental non-transport drowning and submersion, initial encounter','Causes externes de morbidité et de mortalité','W73.XXXA'),
('autre specified cause of accidental non-transport drowning and submersion, subsequent encounter','Other specified cause of accidental non-transport drowning and submersion, subsequent encounter','Causes externes de morbidité et de mortalité','W73.XXXD'),
('autre specified cause of accidental non-transport drowning and submersion, sequela','Other specified cause of accidental non-transport drowning and submersion, sequela','Causes externes de morbidité et de mortalité','W73.XXXS'),
('non spécifié cause of accidental drowning and submersion, initial encounter','Unspecified cause of accidental drowning and submersion, initial encounter','Causes externes de morbidité et de mortalité','W74.XXXA'),
('non spécifié cause of accidental drowning and submersion, subsequent encounter','Unspecified cause of accidental drowning and submersion, subsequent encounter','Causes externes de morbidité et de mortalité','W74.XXXD'),
('non spécifié cause of accidental drowning and submersion, sequela','Unspecified cause of accidental drowning and submersion, sequela','Causes externes de morbidité et de mortalité','W74.XXXS'),
('Exposure to electric transmission lines, initial encounter','Exposure to electric transmission lines, initial encounter','Causes externes de morbidité et de mortalité','W85.XXXA'),
('Exposure to electric transmission lines, subsequent encounter','Exposure to electric transmission lines, subsequent encounter','Causes externes de morbidité et de mortalité','W85.XXXD'),
('Exposure to electric transmission lines, sequela','Exposure to electric transmission lines, sequela','Causes externes de morbidité et de mortalité','W85.XXXS'),
('Exposure to domestic wiring and appliances, initial encounter','Exposure to domestic wiring and appliances, initial encounter','Causes externes de morbidité et de mortalité','W86.0XXA'),
('Exposure to domestic wiring and appliances, subsequent encounter','Exposure to domestic wiring and appliances, subsequent encounter','Causes externes de morbidité et de mortalité','W86.0XXD'),
('Exposure to domestic wiring and appliances, sequela','Exposure to domestic wiring and appliances, sequela','Causes externes de morbidité et de mortalité','W86.0XXS'),
('Exposure to industrial wiring, appliances and electrical machinery, initial encounter','Exposure to industrial wiring, appliances and electrical machinery, initial encounter','Causes externes de morbidité et de mortalité','W86.1XXA'),
('Exposure to industrial wiring, appliances and electrical machinery, subsequent encounter','Exposure to industrial wiring, appliances and electrical machinery, subsequent encounter','Causes externes de morbidité et de mortalité','W86.1XXD'),
('Exposure to industrial wiring, appliances and electrical machinery, sequela','Exposure to industrial wiring, appliances and electrical machinery, sequela','Causes externes de morbidité et de mortalité','W86.1XXS'),
('Exposure to autre electric current, initial encounter','Exposure to other electric current, initial encounter','Causes externes de morbidité et de mortalité','W86.8XXA'),
('Exposure to autre electric current, subsequent encounter','Exposure to other electric current, subsequent encounter','Causes externes de morbidité et de mortalité','W86.8XXD'),
('Exposure to autre electric current, sequela','Exposure to other electric current, sequela','Causes externes de morbidité et de mortalité','W86.8XXS'),
('Exposure to X-rays, initial encounter','Exposure to X-rays, initial encounter','Causes externes de morbidité et de mortalité','W88.0XXA'),
('Exposure to X-rays, subsequent encounter','Exposure to X-rays, subsequent encounter','Causes externes de morbidité et de mortalité','W88.0XXD'),
('Exposure to X-rays, sequela','Exposure to X-rays, sequela','Causes externes de morbidité et de mortalité','W88.0XXS'),
('Exposure to radioactive isotopes, initial encounter','Exposure to radioactive isotopes, initial encounter','Causes externes de morbidité et de mortalité','W88.1XXA'),
('Exposure to radioactive isotopes, subsequent encounter','Exposure to radioactive isotopes, subsequent encounter','Causes externes de morbidité et de mortalité','W88.1XXD'),
('Exposure to radioactive isotopes, sequela','Exposure to radioactive isotopes, sequela','Causes externes de morbidité et de mortalité','W88.1XXS'),
('Exposure to autre ionizing radiation, initial encounter','Exposure to other ionizing radiation, initial encounter','Causes externes de morbidité et de mortalité','W88.8XXA'),
('Exposure to autre ionizing radiation, subsequent encounter','Exposure to other ionizing radiation, subsequent encounter','Causes externes de morbidité et de mortalité','W88.8XXD'),
('Exposure to autre ionizing radiation, sequela','Exposure to other ionizing radiation, sequela','Causes externes de morbidité et de mortalité','W88.8XXS'),
('Exposure to welding light (arc), initial encounter','Exposure to welding light (arc), initial encounter','Causes externes de morbidité et de mortalité','W89.0XXA'),
('Exposure to welding light (arc), subsequent encounter','Exposure to welding light (arc), subsequent encounter','Causes externes de morbidité et de mortalité','W89.0XXD'),
('Exposure to welding light (arc), sequela','Exposure to welding light (arc), sequela','Causes externes de morbidité et de mortalité','W89.0XXS'),
('Exposure to tanning bed, initial encounter','Exposure to tanning bed, initial encounter','Causes externes de morbidité et de mortalité','W89.1XXA'),
('Exposure to tanning bed, subsequent encounter','Exposure to tanning bed, subsequent encounter','Causes externes de morbidité et de mortalité','W89.1XXD'),
('Exposure to tanning bed, sequela','Exposure to tanning bed, sequela','Causes externes de morbidité et de mortalité','W89.1XXS'),
('Exposure to autre man-made visible and ultraviolet light, initial encounter','Exposure to other man-made visible and ultraviolet light, initial encounter','Causes externes de morbidité et de mortalité','W89.8XXA'),
('Exposure to autre man-made visible and ultraviolet light, subsequent encounter','Exposure to other man-made visible and ultraviolet light, subsequent encounter','Causes externes de morbidité et de mortalité','W89.8XXD'),
('Exposure to autre man-made visible and ultraviolet light, sequela','Exposure to other man-made visible and ultraviolet light, sequela','Causes externes de morbidité et de mortalité','W89.8XXS'),
('Exposure to non spécifié man-made visible and ultraviolet light, initial encounter','Exposure to unspecified man-made visible and ultraviolet light, initial encounter','Causes externes de morbidité et de mortalité','W89.9XXA'),
('Exposure to non spécifié man-made visible and ultraviolet light, subsequent encounter','Exposure to unspecified man-made visible and ultraviolet light, subsequent encounter','Causes externes de morbidité et de mortalité','W89.9XXD'),
('Exposure to non spécifié man-made visible and ultraviolet light, sequela','Exposure to unspecified man-made visible and ultraviolet light, sequela','Causes externes de morbidité et de mortalité','W89.9XXS'),
('Exposure to radiofrequency, initial encounter','Exposure to radiofrequency, initial encounter','Causes externes de morbidité et de mortalité','W90.0XXA'),
('Exposure to radiofrequency, subsequent encounter','Exposure to radiofrequency, subsequent encounter','Causes externes de morbidité et de mortalité','W90.0XXD'),
('Exposure to radiofrequency, sequela','Exposure to radiofrequency, sequela','Causes externes de morbidité et de mortalité','W90.0XXS'),
('Exposure to infrared radiation, initial encounter','Exposure to infrared radiation, initial encounter','Causes externes de morbidité et de mortalité','W90.1XXA'),
('Exposure to infrared radiation, subsequent encounter','Exposure to infrared radiation, subsequent encounter','Causes externes de morbidité et de mortalité','W90.1XXD'),
('Exposure to infrared radiation, sequela','Exposure to infrared radiation, sequela','Causes externes de morbidité et de mortalité','W90.1XXS'),
('Exposure to laser radiation, initial encounter','Exposure to laser radiation, initial encounter','Causes externes de morbidité et de mortalité','W90.2XXA'),
('Exposure to laser radiation, subsequent encounter','Exposure to laser radiation, subsequent encounter','Causes externes de morbidité et de mortalité','W90.2XXD'),
('Exposure to laser radiation, sequela','Exposure to laser radiation, sequela','Causes externes de morbidité et de mortalité','W90.2XXS'),
('Exposure to autre nonionizing radiation, initial encounter','Exposure to other nonionizing radiation, initial encounter','Causes externes de morbidité et de mortalité','W90.8XXA'),
('Exposure to autre nonionizing radiation, subsequent encounter','Exposure to other nonionizing radiation, subsequent encounter','Causes externes de morbidité et de mortalité','W90.8XXD'),
('Exposure to autre nonionizing radiation, sequela','Exposure to other nonionizing radiation, sequela','Causes externes de morbidité et de mortalité','W90.8XXS'),
('Exposure to excessive heat of man-made origin, initial encounter','Exposure to excessive heat of man-made origin, initial encounter','Causes externes de morbidité et de mortalité','W92.XXXA'),
('Exposure to excessive heat of man-made origin, subsequent encounter','Exposure to excessive heat of man-made origin, subsequent encounter','Causes externes de morbidité et de mortalité','W92.XXXD'),
('Exposure to excessive heat of man-made origin, sequela','Exposure to excessive heat of man-made origin, sequela','Causes externes de morbidité et de mortalité','W92.XXXS'),
('Contact with dry ice, initial encounter','Contact with dry ice, initial encounter','Causes externes de morbidité et de mortalité','W93.01XA'),
('Contact with dry ice, subsequent encounter','Contact with dry ice, subsequent encounter','Causes externes de morbidité et de mortalité','W93.01XD'),
('Contact with dry ice, sequela','Contact with dry ice, sequela','Causes externes de morbidité et de mortalité','W93.01XS'),
('Inhalation of dry ice, initial encounter','Inhalation of dry ice, initial encounter','Causes externes de morbidité et de mortalité','W93.02XA'),
('Inhalation of dry ice, subsequent encounter','Inhalation of dry ice, subsequent encounter','Causes externes de morbidité et de mortalité','W93.02XD'),
('Inhalation of dry ice, sequela','Inhalation of dry ice, sequela','Causes externes de morbidité et de mortalité','W93.02XS'),
('Contact with liquid air, initial encounter','Contact with liquid air, initial encounter','Causes externes de morbidité et de mortalité','W93.11XA'),
('Contact with liquid air, subsequent encounter','Contact with liquid air, subsequent encounter','Causes externes de morbidité et de mortalité','W93.11XD'),
('Contact with liquid air, sequela','Contact with liquid air, sequela','Causes externes de morbidité et de mortalité','W93.11XS'),
('Inhalation of liquid air, initial encounter','Inhalation of liquid air, initial encounter','Causes externes de morbidité et de mortalité','W93.12XA'),
('Inhalation of liquid air, subsequent encounter','Inhalation of liquid air, subsequent encounter','Causes externes de morbidité et de mortalité','W93.12XD'),
('Inhalation of liquid air, sequela','Inhalation of liquid air, sequela','Causes externes de morbidité et de mortalité','W93.12XS'),
('Prolonged exposure in deep freeze unit or refrigerator, initial encounter','Prolonged exposure in deep freeze unit or refrigerator, initial encounter','Causes externes de morbidité et de mortalité','W93.2XXA'),
('Prolonged exposure in deep freeze unit or refrigerator, subsequent encounter','Prolonged exposure in deep freeze unit or refrigerator, subsequent encounter','Causes externes de morbidité et de mortalité','W93.2XXD'),
('Prolonged exposure in deep freeze unit or refrigerator, sequela','Prolonged exposure in deep freeze unit or refrigerator, sequela','Causes externes de morbidité et de mortalité','W93.2XXS'),
('Exposure to autre excessive cold of man-made origin, initial encounter','Exposure to other excessive cold of man-made origin, initial encounter','Causes externes de morbidité et de mortalité','W93.8XXA')
ON CONFLICT (nom_fr) DO NOTHING;
