-- icd10_batch_047.sql (80 rows)
INSERT INTO pathologies (nom_fr, nom_en, categorie, icd10_code)
VALUES
('Encounter for autre specified prophylactic measures','Encounter for other specified prophylactic measures','Facteurs influant sur l''état de santé','Z29.89'),
('Encounter for prophylactic measures, non spécifié','Encounter for prophylactic measures, unspecified','Facteurs influant sur l''état de santé','Z29.9'),
('Encounter for initial prescription of contraceptive pills','Encounter for initial prescription of contraceptive pills','Facteurs influant sur l''état de santé','Z30.011'),
('Encounter for prescription of emergency contraception','Encounter for prescription of emergency contraception','Facteurs influant sur l''état de santé','Z30.012'),
('Encounter for initial prescription of injectable contraceptive','Encounter for initial prescription of injectable contraceptive','Facteurs influant sur l''état de santé','Z30.013'),
('Encounter for initial prescription of intrauterine contraceptive device','Encounter for initial prescription of intrauterine contraceptive device','Facteurs influant sur l''état de santé','Z30.014'),
('Encounter for initial prescription of vaginal ring hormonal contraceptive','Encounter for initial prescription of vaginal ring hormonal contraceptive','Facteurs influant sur l''état de santé','Z30.015'),
('Encounter for initial prescription of transdermal patch hormonal contraceptive device','Encounter for initial prescription of transdermal patch hormonal contraceptive device','Facteurs influant sur l''état de santé','Z30.016'),
('Encounter for initial prescription of implantable subdermal contraceptive','Encounter for initial prescription of implantable subdermal contraceptive','Facteurs influant sur l''état de santé','Z30.017'),
('Encounter for initial prescription of autre contraceptives','Encounter for initial prescription of other contraceptives','Facteurs influant sur l''état de santé','Z30.018'),
('Encounter for initial prescription of contraceptives, non spécifié','Encounter for initial prescription of contraceptives, unspecified','Facteurs influant sur l''état de santé','Z30.019'),
('Counseling and instruction in natural family planning to avoid pregnancy','Counseling and instruction in natural family planning to avoid pregnancy','Facteurs influant sur l''état de santé','Z30.02'),
('Encounter for autre general counseling and advice on contraception','Encounter for other general counseling and advice on contraception','Facteurs influant sur l''état de santé','Z30.09'),
('Encounter for sterilization','Encounter for sterilization','Facteurs influant sur l''état de santé','Z30.2'),
('Encounter for surveillance of contraceptives, non spécifié','Encounter for surveillance of contraceptives, unspecified','Facteurs influant sur l''état de santé','Z30.40'),
('Encounter for surveillance of contraceptive pills','Encounter for surveillance of contraceptive pills','Facteurs influant sur l''état de santé','Z30.41'),
('Encounter for surveillance of injectable contraceptive','Encounter for surveillance of injectable contraceptive','Facteurs influant sur l''état de santé','Z30.42'),
('Encounter for insertion of intrauterine contraceptive device','Encounter for insertion of intrauterine contraceptive device','Facteurs influant sur l''état de santé','Z30.430'),
('Encounter for routine checking of intrauterine contraceptive device','Encounter for routine checking of intrauterine contraceptive device','Facteurs influant sur l''état de santé','Z30.431'),
('Encounter for removal of intrauterine contraceptive device','Encounter for removal of intrauterine contraceptive device','Facteurs influant sur l''état de santé','Z30.432'),
('Encounter for removal and reinsertion of intrauterine contraceptive device','Encounter for removal and reinsertion of intrauterine contraceptive device','Facteurs influant sur l''état de santé','Z30.433'),
('Encounter for surveillance of vaginal ring hormonal contraceptive device','Encounter for surveillance of vaginal ring hormonal contraceptive device','Facteurs influant sur l''état de santé','Z30.44'),
('Encounter for surveillance of transdermal patch hormonal contraceptive device','Encounter for surveillance of transdermal patch hormonal contraceptive device','Facteurs influant sur l''état de santé','Z30.45'),
('Encounter for surveillance of implantable subdermal contraceptive','Encounter for surveillance of implantable subdermal contraceptive','Facteurs influant sur l''état de santé','Z30.46'),
('Encounter for surveillance of autre contraceptives','Encounter for surveillance of other contraceptives','Facteurs influant sur l''état de santé','Z30.49'),
('Encounter for autre contraceptive management','Encounter for other contraceptive management','Facteurs influant sur l''état de santé','Z30.8'),
('Encounter for contraceptive management, non spécifié','Encounter for contraceptive management, unspecified','Facteurs influant sur l''état de santé','Z30.9'),
('Encounter for reversal of previous sterilization','Encounter for reversal of previous sterilization','Facteurs influant sur l''état de santé','Z31.0'),
('Encounter for fertility testing','Encounter for fertility testing','Facteurs influant sur l''état de santé','Z31.41'),
('Aftercare following sterilization reversal','Aftercare following sterilization reversal','Facteurs influant sur l''état de santé','Z31.42'),
('Encounter of female for testing for genetic maladie carrier status for procreative management','Encounter of female for testing for genetic disease carrier status for procreative management','Facteurs influant sur l''état de santé','Z31.430'),
('Encounter for autre genetic testing of female for procreative management','Encounter for other genetic testing of female for procreative management','Facteurs influant sur l''état de santé','Z31.438'),
('Encounter of male for testing for genetic maladie carrier status for procreative management','Encounter of male for testing for genetic disease carrier status for procreative management','Facteurs influant sur l''état de santé','Z31.440'),
('Encounter for testing of male partner of patient with recurrent pregnancy loss','Encounter for testing of male partner of patient with recurrent pregnancy loss','Facteurs influant sur l''état de santé','Z31.441'),
('Encounter for autre genetic testing of male for procreative management','Encounter for other genetic testing of male for procreative management','Facteurs influant sur l''état de santé','Z31.448'),
('Encounter for autre procreative investigation and testing','Encounter for other procreative investigation and testing','Facteurs influant sur l''état de santé','Z31.49'),
('Encounter for procreative genetic counseling','Encounter for procreative genetic counseling','Facteurs influant sur l''état de santé','Z31.5'),
('Procreative counseling and advice using natural family planning','Procreative counseling and advice using natural family planning','Facteurs influant sur l''état de santé','Z31.61'),
('Encounter for fertility preservation counseling','Encounter for fertility preservation counseling','Facteurs influant sur l''état de santé','Z31.62'),
('Encounter for autre general counseling and advice on procreation','Encounter for other general counseling and advice on procreation','Facteurs influant sur l''état de santé','Z31.69'),
('Encounter for procreative management and counseling for gestational carrier','Encounter for procreative management and counseling for gestational carrier','Facteurs influant sur l''état de santé','Z31.7'),
('Encounter for male factor infertility in female patient','Encounter for male factor infertility in female patient','Facteurs influant sur l''état de santé','Z31.81'),
('Encounter for Rh incompatibility status','Encounter for Rh incompatibility status','Facteurs influant sur l''état de santé','Z31.82'),
('Encounter for assisted reproductive fertility procedure cycle','Encounter for assisted reproductive fertility procedure cycle','Facteurs influant sur l''état de santé','Z31.83'),
('Encounter for fertility preservation procedure','Encounter for fertility preservation procedure','Facteurs influant sur l''état de santé','Z31.84'),
('Encounter for autre procreative management','Encounter for other procreative management','Facteurs influant sur l''état de santé','Z31.89'),
('Encounter for procreative management, non spécifié','Encounter for procreative management, unspecified','Facteurs influant sur l''état de santé','Z31.9'),
('Encounter for pregnancy test, result unknown','Encounter for pregnancy test, result unknown','Facteurs influant sur l''état de santé','Z32.00'),
('Encounter for pregnancy test, result positive','Encounter for pregnancy test, result positive','Facteurs influant sur l''état de santé','Z32.01'),
('Encounter for pregnancy test, result negative','Encounter for pregnancy test, result negative','Facteurs influant sur l''état de santé','Z32.02'),
('Encounter for childbirth instruction','Encounter for childbirth instruction','Facteurs influant sur l''état de santé','Z32.2'),
('Encounter for childcare instruction','Encounter for childcare instruction','Facteurs influant sur l''état de santé','Z32.3'),
('Pregnant state, incidental','Pregnant state, incidental','Facteurs influant sur l''état de santé','Z33.1'),
('Encounter for elective termination of pregnancy','Encounter for elective termination of pregnancy','Facteurs influant sur l''état de santé','Z33.2'),
('Pregnant state, gestational carrier','Pregnant state, gestational carrier','Facteurs influant sur l''état de santé','Z33.3'),
('Encounter for supervision of normal first pregnancy, non spécifié trimester','Encounter for supervision of normal first pregnancy, unspecified trimester','Facteurs influant sur l''état de santé','Z34.00'),
('Encounter for supervision of normal first pregnancy, first trimester','Encounter for supervision of normal first pregnancy, first trimester','Facteurs influant sur l''état de santé','Z34.01'),
('Encounter for supervision of normal first pregnancy, second trimester','Encounter for supervision of normal first pregnancy, second trimester','Facteurs influant sur l''état de santé','Z34.02'),
('Encounter for supervision of normal first pregnancy, third trimester','Encounter for supervision of normal first pregnancy, third trimester','Facteurs influant sur l''état de santé','Z34.03'),
('Encounter for supervision of autre normal pregnancy, non spécifié trimester','Encounter for supervision of other normal pregnancy, unspecified trimester','Facteurs influant sur l''état de santé','Z34.80'),
('Encounter for supervision of autre normal pregnancy, first trimester','Encounter for supervision of other normal pregnancy, first trimester','Facteurs influant sur l''état de santé','Z34.81'),
('Encounter for supervision of autre normal pregnancy, second trimester','Encounter for supervision of other normal pregnancy, second trimester','Facteurs influant sur l''état de santé','Z34.82'),
('Encounter for supervision of autre normal pregnancy, third trimester','Encounter for supervision of other normal pregnancy, third trimester','Facteurs influant sur l''état de santé','Z34.83'),
('Encounter for supervision of normal pregnancy, non spécifié, non spécifié trimester','Encounter for supervision of normal pregnancy, unspecified, unspecified trimester','Facteurs influant sur l''état de santé','Z34.90'),
('Encounter for supervision of normal pregnancy, non spécifié, first trimester','Encounter for supervision of normal pregnancy, unspecified, first trimester','Facteurs influant sur l''état de santé','Z34.91'),
('Encounter for supervision of normal pregnancy, non spécifié, second trimester','Encounter for supervision of normal pregnancy, unspecified, second trimester','Facteurs influant sur l''état de santé','Z34.92'),
('Encounter for supervision of normal pregnancy, non spécifié, third trimester','Encounter for supervision of normal pregnancy, unspecified, third trimester','Facteurs influant sur l''état de santé','Z34.93'),
('Encounter for antenatal screening for chromosomal anomalies','Encounter for antenatal screening for chromosomal anomalies','Facteurs influant sur l''état de santé','Z36.0'),
('Encounter for antenatal screening for raised alphafetoprotein level','Encounter for antenatal screening for raised alphafetoprotein level','Facteurs influant sur l''état de santé','Z36.1'),
('Encounter for autre antenatal screening follow-up','Encounter for other antenatal screening follow-up','Facteurs influant sur l''état de santé','Z36.2'),
('Encounter for antenatal screening for malformations','Encounter for antenatal screening for malformations','Facteurs influant sur l''état de santé','Z36.3'),
('Encounter for antenatal screening for fetal growth retardation','Encounter for antenatal screening for fetal growth retardation','Facteurs influant sur l''état de santé','Z36.4'),
('Encounter for antenatal screening for isoimmunization','Encounter for antenatal screening for isoimmunization','Facteurs influant sur l''état de santé','Z36.5'),
('Encounter for antenatal screening for hydrops fetalis','Encounter for antenatal screening for hydrops fetalis','Facteurs influant sur l''état de santé','Z36.81'),
('Encounter for antenatal screening for nuchal translucency','Encounter for antenatal screening for nuchal translucency','Facteurs influant sur l''état de santé','Z36.82'),
('Encounter for fetal screening for congénital cardiac abnormalities','Encounter for fetal screening for congenital cardiac abnormalities','Facteurs influant sur l''état de santé','Z36.83'),
('Encounter for antenatal screening for fetal lung maturity','Encounter for antenatal screening for fetal lung maturity','Facteurs influant sur l''état de santé','Z36.84'),
('Encounter for antenatal screening for Streptococcus B','Encounter for antenatal screening for Streptococcus B','Facteurs influant sur l''état de santé','Z36.85'),
('Encounter for antenatal screening for cervical length','Encounter for antenatal screening for cervical length','Facteurs influant sur l''état de santé','Z36.86'),
('Encounter for antenatal screening for uncertain dates','Encounter for antenatal screening for uncertain dates','Facteurs influant sur l''état de santé','Z36.87')
ON CONFLICT (nom_fr) DO NOTHING;
