-- icd10v2_batch_743.sql (80 rows)
INSERT INTO pathologies (nom_fr, nom_en, categorie, icd10_code)
VALUES
('non spécifié complication of internal prosthetic device, implant and graft, initial encounter','Unspecified complication of internal prosthetic device, implant and graft, initial encounter','Traumatismes, empoisonnements et autres causes externes','T85.9XXA'),
('non spécifié complication of internal prosthetic device, implant and graft, subsequent encounter','Unspecified complication of internal prosthetic device, implant and graft, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T85.9XXD'),
('non spécifié complication of internal prosthetic device, implant and graft, sequela','Unspecified complication of internal prosthetic device, implant and graft, sequela','Traumatismes, empoisonnements et autres causes externes','T85.9XXS'),
('non spécifié complication of bone marrow transplant','Unspecified complication of bone marrow transplant','Traumatismes, empoisonnements et autres causes externes','T86.00'),
('Bone marrow transplant rejection','Bone marrow transplant rejection','Traumatismes, empoisonnements et autres causes externes','T86.01'),
('Bone marrow transplant insuffisance','Bone marrow transplant failure','Traumatismes, empoisonnements et autres causes externes','T86.02'),
('Bone marrow transplant infection','Bone marrow transplant infection','Traumatismes, empoisonnements et autres causes externes','T86.03'),
('autre complications of bone marrow transplant','Other complications of bone marrow transplant','Traumatismes, empoisonnements et autres causes externes','T86.09'),
('non spécifié complication of kidney transplant','Unspecified complication of kidney transplant','Traumatismes, empoisonnements et autres causes externes','T86.10'),
('Kidney transplant rejection','Kidney transplant rejection','Traumatismes, empoisonnements et autres causes externes','T86.11'),
('Kidney transplant insuffisance','Kidney transplant failure','Traumatismes, empoisonnements et autres causes externes','T86.12'),
('Kidney transplant infection','Kidney transplant infection','Traumatismes, empoisonnements et autres causes externes','T86.13'),
('autre complication of kidney transplant','Other complication of kidney transplant','Traumatismes, empoisonnements et autres causes externes','T86.19'),
('non spécifié complication of heart transplant','Unspecified complication of heart transplant','Traumatismes, empoisonnements et autres causes externes','T86.20'),
('Heart transplant rejection','Heart transplant rejection','Traumatismes, empoisonnements et autres causes externes','T86.21'),
('Heart transplant insuffisance','Heart transplant failure','Traumatismes, empoisonnements et autres causes externes','T86.22'),
('Heart transplant infection','Heart transplant infection','Traumatismes, empoisonnements et autres causes externes','T86.23'),
('Cardiac allograft vasculopathy','Cardiac allograft vasculopathy','Traumatismes, empoisonnements et autres causes externes','T86.290'),
('autre complications of heart transplant','Other complications of heart transplant','Traumatismes, empoisonnements et autres causes externes','T86.298'),
('non spécifié complication of heart-lung transplant','Unspecified complication of heart-lung transplant','Traumatismes, empoisonnements et autres causes externes','T86.30'),
('Heart-lung transplant rejection','Heart-lung transplant rejection','Traumatismes, empoisonnements et autres causes externes','T86.31'),
('Heart-lung transplant insuffisance','Heart-lung transplant failure','Traumatismes, empoisonnements et autres causes externes','T86.32'),
('Heart-lung transplant infection','Heart-lung transplant infection','Traumatismes, empoisonnements et autres causes externes','T86.33'),
('autre complications of heart-lung transplant','Other complications of heart-lung transplant','Traumatismes, empoisonnements et autres causes externes','T86.39'),
('non spécifié complication of liver transplant','Unspecified complication of liver transplant','Traumatismes, empoisonnements et autres causes externes','T86.40'),
('Liver transplant rejection','Liver transplant rejection','Traumatismes, empoisonnements et autres causes externes','T86.41'),
('Liver transplant insuffisance','Liver transplant failure','Traumatismes, empoisonnements et autres causes externes','T86.42'),
('Liver transplant infection','Liver transplant infection','Traumatismes, empoisonnements et autres causes externes','T86.43'),
('autre complications of liver transplant','Other complications of liver transplant','Traumatismes, empoisonnements et autres causes externes','T86.49'),
('Complications of stem cell transplant','Complications of stem cell transplant','Traumatismes, empoisonnements et autres causes externes','T86.5'),
('Lung transplant rejection','Lung transplant rejection','Traumatismes, empoisonnements et autres causes externes','T86.810'),
('Lung transplant insuffisance','Lung transplant failure','Traumatismes, empoisonnements et autres causes externes','T86.811'),
('Lung transplant infection','Lung transplant infection','Traumatismes, empoisonnements et autres causes externes','T86.812'),
('autre complications of lung transplant','Other complications of lung transplant','Traumatismes, empoisonnements et autres causes externes','T86.818'),
('non spécifié complication of lung transplant','Unspecified complication of lung transplant','Traumatismes, empoisonnements et autres causes externes','T86.819'),
('Skin graft (allograft) rejection','Skin graft (allograft) rejection','Traumatismes, empoisonnements et autres causes externes','T86.820'),
('Skin graft (allograft) (autograft) insuffisance','Skin graft (allograft) (autograft) failure','Traumatismes, empoisonnements et autres causes externes','T86.821'),
('Skin graft (allograft) (autograft) infection','Skin graft (allograft) (autograft) infection','Traumatismes, empoisonnements et autres causes externes','T86.822'),
('autre complications of skin graft (allograft) (autograft)','Other complications of skin graft (allograft) (autograft)','Traumatismes, empoisonnements et autres causes externes','T86.828'),
('non spécifié complication of skin graft (allograft) (autograft)','Unspecified complication of skin graft (allograft) (autograft)','Traumatismes, empoisonnements et autres causes externes','T86.829'),
('Bone graft rejection','Bone graft rejection','Traumatismes, empoisonnements et autres causes externes','T86.830'),
('Bone graft insuffisance','Bone graft failure','Traumatismes, empoisonnements et autres causes externes','T86.831'),
('Bone graft infection','Bone graft infection','Traumatismes, empoisonnements et autres causes externes','T86.832'),
('autre complications of bone graft','Other complications of bone graft','Traumatismes, empoisonnements et autres causes externes','T86.838'),
('non spécifié complication of bone graft','Unspecified complication of bone graft','Traumatismes, empoisonnements et autres causes externes','T86.839'),
('Corneal transplant rejection, right eye','Corneal transplant rejection, right eye','Traumatismes, empoisonnements et autres causes externes','T86.8401'),
('Corneal transplant rejection, left eye','Corneal transplant rejection, left eye','Traumatismes, empoisonnements et autres causes externes','T86.8402'),
('Corneal transplant rejection, bilateral','Corneal transplant rejection, bilateral','Traumatismes, empoisonnements et autres causes externes','T86.8403'),
('Corneal transplant rejection, non spécifié eye','Corneal transplant rejection, unspecified eye','Traumatismes, empoisonnements et autres causes externes','T86.8409'),
('Corneal transplant insuffisance, right eye','Corneal transplant failure, right eye','Traumatismes, empoisonnements et autres causes externes','T86.8411'),
('Corneal transplant insuffisance, left eye','Corneal transplant failure, left eye','Traumatismes, empoisonnements et autres causes externes','T86.8412'),
('Corneal transplant insuffisance, bilateral','Corneal transplant failure, bilateral','Traumatismes, empoisonnements et autres causes externes','T86.8413'),
('Corneal transplant insuffisance, non spécifié eye','Corneal transplant failure, unspecified eye','Traumatismes, empoisonnements et autres causes externes','T86.8419'),
('Corneal transplant infection, right eye','Corneal transplant infection, right eye','Traumatismes, empoisonnements et autres causes externes','T86.8421'),
('Corneal transplant infection, left eye','Corneal transplant infection, left eye','Traumatismes, empoisonnements et autres causes externes','T86.8422'),
('Corneal transplant infection, bilateral','Corneal transplant infection, bilateral','Traumatismes, empoisonnements et autres causes externes','T86.8423'),
('Corneal transplant infection, non spécifié eye','Corneal transplant infection, unspecified eye','Traumatismes, empoisonnements et autres causes externes','T86.8429'),
('autre complications of corneal transplant, right eye','Other complications of corneal transplant, right eye','Traumatismes, empoisonnements et autres causes externes','T86.8481'),
('autre complications of corneal transplant, left eye','Other complications of corneal transplant, left eye','Traumatismes, empoisonnements et autres causes externes','T86.8482'),
('autre complications of corneal transplant, bilateral','Other complications of corneal transplant, bilateral','Traumatismes, empoisonnements et autres causes externes','T86.8483'),
('autre complications of corneal transplant, non spécifié eye','Other complications of corneal transplant, unspecified eye','Traumatismes, empoisonnements et autres causes externes','T86.8489'),
('non spécifié complication of corneal transplant, right eye','Unspecified complication of corneal transplant, right eye','Traumatismes, empoisonnements et autres causes externes','T86.8491'),
('non spécifié complication of corneal transplant, left eye','Unspecified complication of corneal transplant, left eye','Traumatismes, empoisonnements et autres causes externes','T86.8492'),
('non spécifié complication of corneal transplant, bilateral','Unspecified complication of corneal transplant, bilateral','Traumatismes, empoisonnements et autres causes externes','T86.8493'),
('non spécifié complication of corneal transplant, non spécifié eye','Unspecified complication of corneal transplant, unspecified eye','Traumatismes, empoisonnements et autres causes externes','T86.8499'),
('Intestine transplant rejection','Intestine transplant rejection','Traumatismes, empoisonnements et autres causes externes','T86.850'),
('Intestine transplant insuffisance','Intestine transplant failure','Traumatismes, empoisonnements et autres causes externes','T86.851'),
('Intestine transplant infection','Intestine transplant infection','Traumatismes, empoisonnements et autres causes externes','T86.852'),
('autre complications of intestine transplant','Other complications of intestine transplant','Traumatismes, empoisonnements et autres causes externes','T86.858'),
('non spécifié complication of intestine transplant','Unspecified complication of intestine transplant','Traumatismes, empoisonnements et autres causes externes','T86.859'),
('autre transplanted tissue rejection','Other transplanted tissue rejection','Traumatismes, empoisonnements et autres causes externes','T86.890'),
('autre transplanted tissue insuffisance','Other transplanted tissue failure','Traumatismes, empoisonnements et autres causes externes','T86.891'),
('autre transplanted tissue infection','Other transplanted tissue infection','Traumatismes, empoisonnements et autres causes externes','T86.892'),
('autre complications of autre transplanted tissue','Other complications of other transplanted tissue','Traumatismes, empoisonnements et autres causes externes','T86.898'),
('non spécifié complication of autre transplanted tissue','Unspecified complication of other transplanted tissue','Traumatismes, empoisonnements et autres causes externes','T86.899'),
('non spécifié complication of non spécifié transplanted organ and tissue','Unspecified complication of unspecified transplanted organ and tissue','Traumatismes, empoisonnements et autres causes externes','T86.90'),
('non spécifié transplanted organ and tissue rejection','Unspecified transplanted organ and tissue rejection','Traumatismes, empoisonnements et autres causes externes','T86.91'),
('non spécifié transplanted organ and tissue insuffisance','Unspecified transplanted organ and tissue failure','Traumatismes, empoisonnements et autres causes externes','T86.92'),
('non spécifié transplanted organ and tissue infection','Unspecified transplanted organ and tissue infection','Traumatismes, empoisonnements et autres causes externes','T86.93'),
('autre complications of non spécifié transplanted organ and tissue','Other complications of unspecified transplanted organ and tissue','Traumatismes, empoisonnements et autres causes externes','T86.99')
ON CONFLICT (nom_fr) DO NOTHING;
