-- icd10v2_batch_473.sql (80 rows)
INSERT INTO pathologies (nom_fr, nom_en, categorie, icd10_code)
VALUES
('Encounter for fitting and adjustment of artificial eye, non spécifié','Encounter for fitting and adjustment of artificial eye, unspecified','Facteurs influant sur l''état de santé','Z44.20'),
('Encounter for fitting and adjustment of artificial right eye','Encounter for fitting and adjustment of artificial right eye','Facteurs influant sur l''état de santé','Z44.21'),
('Encounter for fitting and adjustment of artificial left eye','Encounter for fitting and adjustment of artificial left eye','Facteurs influant sur l''état de santé','Z44.22'),
('Encounter for fitting and adjustment of external breast prosthesis, non spécifié breast','Encounter for fitting and adjustment of external breast prosthesis, unspecified breast','Facteurs influant sur l''état de santé','Z44.30'),
('Encounter for fitting and adjustment of external right breast prosthesis','Encounter for fitting and adjustment of external right breast prosthesis','Facteurs influant sur l''état de santé','Z44.31'),
('Encounter for fitting and adjustment of external left breast prosthesis','Encounter for fitting and adjustment of external left breast prosthesis','Facteurs influant sur l''état de santé','Z44.32'),
('Encounter for fitting and adjustment of autre external prosthetic devices','Encounter for fitting and adjustment of other external prosthetic devices','Facteurs influant sur l''état de santé','Z44.8'),
('Encounter for fitting and adjustment of non spécifié external prosthetic device','Encounter for fitting and adjustment of unspecified external prosthetic device','Facteurs influant sur l''état de santé','Z44.9'),
('Encounter for checking and testing of cardiac pacemaker pulse generator [battery]','Encounter for checking and testing of cardiac pacemaker pulse generator [battery]','Facteurs influant sur l''état de santé','Z45.010'),
('Encounter for adjustment and management of autre part of cardiac pacemaker','Encounter for adjustment and management of other part of cardiac pacemaker','Facteurs influant sur l''état de santé','Z45.018'),
('Encounter for adjustment and management of automatic implantable cardiac defibrillator','Encounter for adjustment and management of automatic implantable cardiac defibrillator','Facteurs influant sur l''état de santé','Z45.02'),
('Encounter for adjustment and management of autre cardiac device','Encounter for adjustment and management of other cardiac device','Facteurs influant sur l''état de santé','Z45.09'),
('Encounter for adjustment and management of infusion pump','Encounter for adjustment and management of infusion pump','Facteurs influant sur l''état de santé','Z45.1'),
('Encounter for adjustment and management of vascular access device','Encounter for adjustment and management of vascular access device','Facteurs influant sur l''état de santé','Z45.2'),
('Encounter for adjustment and management of implanted visual substitution device','Encounter for adjustment and management of implanted visual substitution device','Facteurs influant sur l''état de santé','Z45.31'),
('Encounter for adjustment and management of bone conduction device','Encounter for adjustment and management of bone conduction device','Facteurs influant sur l''état de santé','Z45.320'),
('Encounter for adjustment and management of cochlear device','Encounter for adjustment and management of cochlear device','Facteurs influant sur l''état de santé','Z45.321'),
('Encounter for adjustment and management of autre implanted hearing device','Encounter for adjustment and management of other implanted hearing device','Facteurs influant sur l''état de santé','Z45.328'),
('Encounter for adjustment and management of cerebrospinal fluid drainage device','Encounter for adjustment and management of cerebrospinal fluid drainage device','Facteurs influant sur l''état de santé','Z45.41'),
('Encounter for adjustment and management of neurostimulator','Encounter for adjustment and management of neurostimulator','Facteurs influant sur l''état de santé','Z45.42'),
('Encounter for adjustment and management of autre implanted nervous system device','Encounter for adjustment and management of other implanted nervous system device','Facteurs influant sur l''état de santé','Z45.49'),
('Encounter for adjustment or removal of right breast implant','Encounter for adjustment or removal of right breast implant','Facteurs influant sur l''état de santé','Z45.811'),
('Encounter for adjustment or removal of left breast implant','Encounter for adjustment or removal of left breast implant','Facteurs influant sur l''état de santé','Z45.812'),
('Encounter for adjustment or removal of non spécifié breast implant','Encounter for adjustment or removal of unspecified breast implant','Facteurs influant sur l''état de santé','Z45.819'),
('Encounter for adjustment or removal of myringotomy device (stent) (tube)','Encounter for adjustment or removal of myringotomy device (stent) (tube)','Facteurs influant sur l''état de santé','Z45.82'),
('Encounter for adjustment and management of autre implanted devices','Encounter for adjustment and management of other implanted devices','Facteurs influant sur l''état de santé','Z45.89'),
('Encounter for adjustment and management of non spécifié implanted device','Encounter for adjustment and management of unspecified implanted device','Facteurs influant sur l''état de santé','Z45.9'),
('Encounter for fitting and adjustment of spectacles and contact lenses','Encounter for fitting and adjustment of spectacles and contact lenses','Facteurs influant sur l''état de santé','Z46.0'),
('Encounter for fitting and adjustment of hearing aid','Encounter for fitting and adjustment of hearing aid','Facteurs influant sur l''état de santé','Z46.1'),
('Encounter for fitting and adjustment of autre devices related to nervous system and special senses','Encounter for fitting and adjustment of other devices related to nervous system and special senses','Facteurs influant sur l''état de santé','Z46.2'),
('Encounter for fitting and adjustment of dental prosthetic device','Encounter for fitting and adjustment of dental prosthetic device','Facteurs influant sur l''état de santé','Z46.3'),
('Encounter for fitting and adjustment of orthodontic device','Encounter for fitting and adjustment of orthodontic device','Facteurs influant sur l''état de santé','Z46.4'),
('Encounter for fitting and adjustment of gastric lap band','Encounter for fitting and adjustment of gastric lap band','Facteurs influant sur l''état de santé','Z46.51'),
('Encounter for fitting and adjustment of autre gastrointestinal appliance and device','Encounter for fitting and adjustment of other gastrointestinal appliance and device','Facteurs influant sur l''état de santé','Z46.59'),
('Encounter for fitting and adjustment of urinary device','Encounter for fitting and adjustment of urinary device','Facteurs influant sur l''état de santé','Z46.6'),
('Encounter for fitting and adjustment of insulin pump','Encounter for fitting and adjustment of insulin pump','Facteurs influant sur l''état de santé','Z46.81'),
('Encounter for fitting and adjustment of non-vascular catheter','Encounter for fitting and adjustment of non-vascular catheter','Facteurs influant sur l''état de santé','Z46.82'),
('Encounter for fitting and adjustment of autre specified devices','Encounter for fitting and adjustment of other specified devices','Facteurs influant sur l''état de santé','Z46.89'),
('Encounter for fitting and adjustment of non spécifié device','Encounter for fitting and adjustment of unspecified device','Facteurs influant sur l''état de santé','Z46.9'),
('Aftercare following joint replacement surgery','Aftercare following joint replacement surgery','Facteurs influant sur l''état de santé','Z47.1'),
('Encounter for removal of internal fixation device','Encounter for removal of internal fixation device','Facteurs influant sur l''état de santé','Z47.2'),
('Aftercare following explantation of shoulder joint prosthesis','Aftercare following explantation of shoulder joint prosthesis','Facteurs influant sur l''état de santé','Z47.31'),
('Aftercare following explantation of hip joint prosthesis','Aftercare following explantation of hip joint prosthesis','Facteurs influant sur l''état de santé','Z47.32'),
('Aftercare following explantation of knee joint prosthesis','Aftercare following explantation of knee joint prosthesis','Facteurs influant sur l''état de santé','Z47.33'),
('Encounter for orthopedic aftercare following surgical amputation','Encounter for orthopedic aftercare following surgical amputation','Facteurs influant sur l''état de santé','Z47.81'),
('Encounter for orthopedic aftercare following scoliosis surgery','Encounter for orthopedic aftercare following scoliosis surgery','Facteurs influant sur l''état de santé','Z47.82'),
('Encounter for autre orthopedic aftercare','Encounter for other orthopedic aftercare','Facteurs influant sur l''état de santé','Z47.89'),
('Encounter for change or removal of nonsurgical wound dressing','Encounter for change or removal of nonsurgical wound dressing','Facteurs influant sur l''état de santé','Z48.00'),
('Encounter for change or removal of surgical wound dressing','Encounter for change or removal of surgical wound dressing','Facteurs influant sur l''état de santé','Z48.01'),
('Encounter for removal of sutures','Encounter for removal of sutures','Facteurs influant sur l''état de santé','Z48.02'),
('Encounter for change or removal of drains','Encounter for change or removal of drains','Facteurs influant sur l''état de santé','Z48.03'),
('Encounter for planned postprocedural wound closure','Encounter for planned postprocedural wound closure','Facteurs influant sur l''état de santé','Z48.1'),
('Encounter for aftercare following heart transplant','Encounter for aftercare following heart transplant','Facteurs influant sur l''état de santé','Z48.21'),
('Encounter for aftercare following kidney transplant','Encounter for aftercare following kidney transplant','Facteurs influant sur l''état de santé','Z48.22'),
('Encounter for aftercare following liver transplant','Encounter for aftercare following liver transplant','Facteurs influant sur l''état de santé','Z48.23'),
('Encounter for aftercare following lung transplant','Encounter for aftercare following lung transplant','Facteurs influant sur l''état de santé','Z48.24'),
('Encounter for aftercare following heart-lung transplant','Encounter for aftercare following heart-lung transplant','Facteurs influant sur l''état de santé','Z48.280'),
('Encounter for aftercare following multiple organ transplant','Encounter for aftercare following multiple organ transplant','Facteurs influant sur l''état de santé','Z48.288'),
('Encounter for aftercare following bone marrow transplant','Encounter for aftercare following bone marrow transplant','Facteurs influant sur l''état de santé','Z48.290'),
('Encounter for aftercare following autre organ transplant','Encounter for aftercare following other organ transplant','Facteurs influant sur l''état de santé','Z48.298'),
('Aftercare following surgery for néoplasme','Aftercare following surgery for neoplasm','Facteurs influant sur l''état de santé','Z48.3'),
('Encounter for surgical aftercare following surgery on the sense organs','Encounter for surgical aftercare following surgery on the sense organs','Facteurs influant sur l''état de santé','Z48.810'),
('Encounter for surgical aftercare following surgery on the nervous system','Encounter for surgical aftercare following surgery on the nervous system','Facteurs influant sur l''état de santé','Z48.811'),
('Encounter for surgical aftercare following surgery on the circulatory system','Encounter for surgical aftercare following surgery on the circulatory system','Facteurs influant sur l''état de santé','Z48.812'),
('Encounter for surgical aftercare following surgery on the respiratory system','Encounter for surgical aftercare following surgery on the respiratory system','Facteurs influant sur l''état de santé','Z48.813'),
('Encounter for surgical aftercare following surgery on the teeth or oral cavity','Encounter for surgical aftercare following surgery on the teeth or oral cavity','Facteurs influant sur l''état de santé','Z48.814'),
('Encounter for surgical aftercare following surgery on the digestive system','Encounter for surgical aftercare following surgery on the digestive system','Facteurs influant sur l''état de santé','Z48.815'),
('Encounter for surgical aftercare following surgery on the genitourinary system','Encounter for surgical aftercare following surgery on the genitourinary system','Facteurs influant sur l''état de santé','Z48.816'),
('Encounter for surgical aftercare following surgery on the skin and subcutaneous tissue','Encounter for surgical aftercare following surgery on the skin and subcutaneous tissue','Facteurs influant sur l''état de santé','Z48.817'),
('Encounter for autre specified surgical aftercare','Encounter for other specified surgical aftercare','Facteurs influant sur l''état de santé','Z48.89'),
('Encounter for fitting and adjustment of extracorporeal dialysis catheter','Encounter for fitting and adjustment of extracorporeal dialysis catheter','Facteurs influant sur l''état de santé','Z49.01'),
('Encounter for fitting and adjustment of peritoneal dialysis catheter','Encounter for fitting and adjustment of peritoneal dialysis catheter','Facteurs influant sur l''état de santé','Z49.02'),
('Encounter for adequacy testing for hemodialysis','Encounter for adequacy testing for hemodialysis','Facteurs influant sur l''état de santé','Z49.31'),
('Encounter for adequacy testing for peritoneal dialysis','Encounter for adequacy testing for peritoneal dialysis','Facteurs influant sur l''état de santé','Z49.32'),
('Encounter for antineoplastic radiation therapy','Encounter for antineoplastic radiation therapy','Facteurs influant sur l''état de santé','Z51.0'),
('Encounter for antineoplastic chemotherapy','Encounter for antineoplastic chemotherapy','Facteurs influant sur l''état de santé','Z51.11'),
('Encounter for antineoplastic immunotherapy','Encounter for antineoplastic immunotherapy','Facteurs influant sur l''état de santé','Z51.12'),
('Encounter for palliative care','Encounter for palliative care','Facteurs influant sur l''état de santé','Z51.5'),
('Encounter for desensitization to allergens','Encounter for desensitization to allergens','Facteurs influant sur l''état de santé','Z51.6'),
('Encounter for therapeutic drug level monitoring','Encounter for therapeutic drug level monitoring','Facteurs influant sur l''état de santé','Z51.81')
ON CONFLICT (nom_fr) DO NOTHING;
