-- icd10v2_batch_239.sql (80 rows)
INSERT INTO pathologies (nom_fr, nom_en, categorie, icd10_code)
VALUES
('Term delivery with preterm labor, non spécifié trimester, fetus 2','Term delivery with preterm labor, unspecified trimester, fetus 2','Grossesse, accouchement et puerpéralité','O60.20X2'),
('Term delivery with preterm labor, non spécifié trimester, fetus 3','Term delivery with preterm labor, unspecified trimester, fetus 3','Grossesse, accouchement et puerpéralité','O60.20X3'),
('Term delivery with preterm labor, non spécifié trimester, fetus 4','Term delivery with preterm labor, unspecified trimester, fetus 4','Grossesse, accouchement et puerpéralité','O60.20X4'),
('Term delivery with preterm labor, non spécifié trimester, fetus 5','Term delivery with preterm labor, unspecified trimester, fetus 5','Grossesse, accouchement et puerpéralité','O60.20X5'),
('Term delivery with preterm labor, non spécifié trimester, autre fetus','Term delivery with preterm labor, unspecified trimester, other fetus','Grossesse, accouchement et puerpéralité','O60.20X9'),
('Term delivery with preterm labor, second trimester, not applicable or non spécifié','Term delivery with preterm labor, second trimester, not applicable or unspecified','Grossesse, accouchement et puerpéralité','O60.22X0'),
('Term delivery with preterm labor, second trimester, fetus 1','Term delivery with preterm labor, second trimester, fetus 1','Grossesse, accouchement et puerpéralité','O60.22X1'),
('Term delivery with preterm labor, second trimester, fetus 2','Term delivery with preterm labor, second trimester, fetus 2','Grossesse, accouchement et puerpéralité','O60.22X2'),
('Term delivery with preterm labor, second trimester, fetus 3','Term delivery with preterm labor, second trimester, fetus 3','Grossesse, accouchement et puerpéralité','O60.22X3'),
('Term delivery with preterm labor, second trimester, fetus 4','Term delivery with preterm labor, second trimester, fetus 4','Grossesse, accouchement et puerpéralité','O60.22X4'),
('Term delivery with preterm labor, second trimester, fetus 5','Term delivery with preterm labor, second trimester, fetus 5','Grossesse, accouchement et puerpéralité','O60.22X5'),
('Term delivery with preterm labor, second trimester, autre fetus','Term delivery with preterm labor, second trimester, other fetus','Grossesse, accouchement et puerpéralité','O60.22X9'),
('Term delivery with preterm labor, third trimester, not applicable or non spécifié','Term delivery with preterm labor, third trimester, not applicable or unspecified','Grossesse, accouchement et puerpéralité','O60.23X0'),
('Term delivery with preterm labor, third trimester, fetus 1','Term delivery with preterm labor, third trimester, fetus 1','Grossesse, accouchement et puerpéralité','O60.23X1'),
('Term delivery with preterm labor, third trimester, fetus 2','Term delivery with preterm labor, third trimester, fetus 2','Grossesse, accouchement et puerpéralité','O60.23X2'),
('Term delivery with preterm labor, third trimester, fetus 3','Term delivery with preterm labor, third trimester, fetus 3','Grossesse, accouchement et puerpéralité','O60.23X3'),
('Term delivery with preterm labor, third trimester, fetus 4','Term delivery with preterm labor, third trimester, fetus 4','Grossesse, accouchement et puerpéralité','O60.23X4'),
('Term delivery with preterm labor, third trimester, fetus 5','Term delivery with preterm labor, third trimester, fetus 5','Grossesse, accouchement et puerpéralité','O60.23X5'),
('Term delivery with preterm labor, third trimester, autre fetus','Term delivery with preterm labor, third trimester, other fetus','Grossesse, accouchement et puerpéralité','O60.23X9'),
('Failed medical induction of labor','Failed medical induction of labor','Grossesse, accouchement et puerpéralité','O61.0'),
('Failed instrumental induction of labor','Failed instrumental induction of labor','Grossesse, accouchement et puerpéralité','O61.1'),
('autre failed induction of labor','Other failed induction of labor','Grossesse, accouchement et puerpéralité','O61.8'),
('Failed induction of labor, non spécifié','Failed induction of labor, unspecified','Grossesse, accouchement et puerpéralité','O61.9'),
('primitif inadequate contractions','Primary inadequate contractions','Grossesse, accouchement et puerpéralité','O62.0'),
('secondaire uterine inertia','Secondary uterine inertia','Grossesse, accouchement et puerpéralité','O62.1'),
('autre uterine inertia','Other uterine inertia','Grossesse, accouchement et puerpéralité','O62.2'),
('Precipitate labor','Precipitate labor','Grossesse, accouchement et puerpéralité','O62.3'),
('Hypertonic, incoordinate, and prolonged uterine contractions','Hypertonic, incoordinate, and prolonged uterine contractions','Grossesse, accouchement et puerpéralité','O62.4'),
('autre abnormalities of forces of labor','Other abnormalities of forces of labor','Grossesse, accouchement et puerpéralité','O62.8'),
('Abnormality of forces of labor, non spécifié','Abnormality of forces of labor, unspecified','Grossesse, accouchement et puerpéralité','O62.9'),
('Prolonged first stage (of labor)','Prolonged first stage (of labor)','Grossesse, accouchement et puerpéralité','O63.0'),
('Prolonged second stage (of labor)','Prolonged second stage (of labor)','Grossesse, accouchement et puerpéralité','O63.1'),
('Delayed delivery of second twin, triplet, etc.','Delayed delivery of second twin, triplet, etc.','Grossesse, accouchement et puerpéralité','O63.2'),
('Long labor, non spécifié','Long labor, unspecified','Grossesse, accouchement et puerpéralité','O63.9'),
('Obstructed labor due to incomplete rotation of fetal head, not applicable or non spécifié','Obstructed labor due to incomplete rotation of fetal head, not applicable or unspecified','Grossesse, accouchement et puerpéralité','O64.0XX0'),
('Obstructed labor due to incomplete rotation of fetal head, fetus 1','Obstructed labor due to incomplete rotation of fetal head, fetus 1','Grossesse, accouchement et puerpéralité','O64.0XX1'),
('Obstructed labor due to incomplete rotation of fetal head, fetus 2','Obstructed labor due to incomplete rotation of fetal head, fetus 2','Grossesse, accouchement et puerpéralité','O64.0XX2'),
('Obstructed labor due to incomplete rotation of fetal head, fetus 3','Obstructed labor due to incomplete rotation of fetal head, fetus 3','Grossesse, accouchement et puerpéralité','O64.0XX3'),
('Obstructed labor due to incomplete rotation of fetal head, fetus 4','Obstructed labor due to incomplete rotation of fetal head, fetus 4','Grossesse, accouchement et puerpéralité','O64.0XX4'),
('Obstructed labor due to incomplete rotation of fetal head, fetus 5','Obstructed labor due to incomplete rotation of fetal head, fetus 5','Grossesse, accouchement et puerpéralité','O64.0XX5'),
('Obstructed labor due to incomplete rotation of fetal head, autre fetus','Obstructed labor due to incomplete rotation of fetal head, other fetus','Grossesse, accouchement et puerpéralité','O64.0XX9'),
('Obstructed labor due to breech presentation, not applicable or non spécifié','Obstructed labor due to breech presentation, not applicable or unspecified','Grossesse, accouchement et puerpéralité','O64.1XX0'),
('Obstructed labor due to breech presentation, fetus 1','Obstructed labor due to breech presentation, fetus 1','Grossesse, accouchement et puerpéralité','O64.1XX1'),
('Obstructed labor due to breech presentation, fetus 2','Obstructed labor due to breech presentation, fetus 2','Grossesse, accouchement et puerpéralité','O64.1XX2'),
('Obstructed labor due to breech presentation, fetus 3','Obstructed labor due to breech presentation, fetus 3','Grossesse, accouchement et puerpéralité','O64.1XX3'),
('Obstructed labor due to breech presentation, fetus 4','Obstructed labor due to breech presentation, fetus 4','Grossesse, accouchement et puerpéralité','O64.1XX4'),
('Obstructed labor due to breech presentation, fetus 5','Obstructed labor due to breech presentation, fetus 5','Grossesse, accouchement et puerpéralité','O64.1XX5'),
('Obstructed labor due to breech presentation, autre fetus','Obstructed labor due to breech presentation, other fetus','Grossesse, accouchement et puerpéralité','O64.1XX9'),
('Obstructed labor due to face presentation, not applicable or non spécifié','Obstructed labor due to face presentation, not applicable or unspecified','Grossesse, accouchement et puerpéralité','O64.2XX0'),
('Obstructed labor due to face presentation, fetus 1','Obstructed labor due to face presentation, fetus 1','Grossesse, accouchement et puerpéralité','O64.2XX1'),
('Obstructed labor due to face presentation, fetus 2','Obstructed labor due to face presentation, fetus 2','Grossesse, accouchement et puerpéralité','O64.2XX2'),
('Obstructed labor due to face presentation, fetus 3','Obstructed labor due to face presentation, fetus 3','Grossesse, accouchement et puerpéralité','O64.2XX3'),
('Obstructed labor due to face presentation, fetus 4','Obstructed labor due to face presentation, fetus 4','Grossesse, accouchement et puerpéralité','O64.2XX4'),
('Obstructed labor due to face presentation, fetus 5','Obstructed labor due to face presentation, fetus 5','Grossesse, accouchement et puerpéralité','O64.2XX5'),
('Obstructed labor due to face presentation, autre fetus','Obstructed labor due to face presentation, other fetus','Grossesse, accouchement et puerpéralité','O64.2XX9'),
('Obstructed labor due to brow presentation, not applicable or non spécifié','Obstructed labor due to brow presentation, not applicable or unspecified','Grossesse, accouchement et puerpéralité','O64.3XX0'),
('Obstructed labor due to brow presentation, fetus 1','Obstructed labor due to brow presentation, fetus 1','Grossesse, accouchement et puerpéralité','O64.3XX1'),
('Obstructed labor due to brow presentation, fetus 2','Obstructed labor due to brow presentation, fetus 2','Grossesse, accouchement et puerpéralité','O64.3XX2'),
('Obstructed labor due to brow presentation, fetus 3','Obstructed labor due to brow presentation, fetus 3','Grossesse, accouchement et puerpéralité','O64.3XX3'),
('Obstructed labor due to brow presentation, fetus 4','Obstructed labor due to brow presentation, fetus 4','Grossesse, accouchement et puerpéralité','O64.3XX4'),
('Obstructed labor due to brow presentation, fetus 5','Obstructed labor due to brow presentation, fetus 5','Grossesse, accouchement et puerpéralité','O64.3XX5'),
('Obstructed labor due to brow presentation, autre fetus','Obstructed labor due to brow presentation, other fetus','Grossesse, accouchement et puerpéralité','O64.3XX9'),
('Obstructed labor due to shoulder presentation, not applicable or non spécifié','Obstructed labor due to shoulder presentation, not applicable or unspecified','Grossesse, accouchement et puerpéralité','O64.4XX0'),
('Obstructed labor due to shoulder presentation, fetus 1','Obstructed labor due to shoulder presentation, fetus 1','Grossesse, accouchement et puerpéralité','O64.4XX1'),
('Obstructed labor due to shoulder presentation, fetus 2','Obstructed labor due to shoulder presentation, fetus 2','Grossesse, accouchement et puerpéralité','O64.4XX2'),
('Obstructed labor due to shoulder presentation, fetus 3','Obstructed labor due to shoulder presentation, fetus 3','Grossesse, accouchement et puerpéralité','O64.4XX3'),
('Obstructed labor due to shoulder presentation, fetus 4','Obstructed labor due to shoulder presentation, fetus 4','Grossesse, accouchement et puerpéralité','O64.4XX4'),
('Obstructed labor due to shoulder presentation, fetus 5','Obstructed labor due to shoulder presentation, fetus 5','Grossesse, accouchement et puerpéralité','O64.4XX5'),
('Obstructed labor due to shoulder presentation, autre fetus','Obstructed labor due to shoulder presentation, other fetus','Grossesse, accouchement et puerpéralité','O64.4XX9'),
('Obstructed labor due to compound presentation, not applicable or non spécifié','Obstructed labor due to compound presentation, not applicable or unspecified','Grossesse, accouchement et puerpéralité','O64.5XX0'),
('Obstructed labor due to compound presentation, fetus 1','Obstructed labor due to compound presentation, fetus 1','Grossesse, accouchement et puerpéralité','O64.5XX1'),
('Obstructed labor due to compound presentation, fetus 2','Obstructed labor due to compound presentation, fetus 2','Grossesse, accouchement et puerpéralité','O64.5XX2'),
('Obstructed labor due to compound presentation, fetus 3','Obstructed labor due to compound presentation, fetus 3','Grossesse, accouchement et puerpéralité','O64.5XX3'),
('Obstructed labor due to compound presentation, fetus 4','Obstructed labor due to compound presentation, fetus 4','Grossesse, accouchement et puerpéralité','O64.5XX4'),
('Obstructed labor due to compound presentation, fetus 5','Obstructed labor due to compound presentation, fetus 5','Grossesse, accouchement et puerpéralité','O64.5XX5'),
('Obstructed labor due to compound presentation, autre fetus','Obstructed labor due to compound presentation, other fetus','Grossesse, accouchement et puerpéralité','O64.5XX9'),
('Obstructed labor due to autre malposition and malpresentation, not applicable or non spécifié','Obstructed labor due to other malposition and malpresentation, not applicable or unspecified','Grossesse, accouchement et puerpéralité','O64.8XX0'),
('Obstructed labor due to autre malposition and malpresentation, fetus 1','Obstructed labor due to other malposition and malpresentation, fetus 1','Grossesse, accouchement et puerpéralité','O64.8XX1'),
('Obstructed labor due to autre malposition and malpresentation, fetus 2','Obstructed labor due to other malposition and malpresentation, fetus 2','Grossesse, accouchement et puerpéralité','O64.8XX2'),
('Obstructed labor due to autre malposition and malpresentation, fetus 3','Obstructed labor due to other malposition and malpresentation, fetus 3','Grossesse, accouchement et puerpéralité','O64.8XX3')
ON CONFLICT (nom_fr) DO NOTHING;
