-- icd10v2_batch_178.sql (80 rows)
INSERT INTO pathologies (nom_fr, nom_en, categorie, icd10_code)
VALUES
('Loose body in right wrist','Loose body in right wrist','Maladies de l''appareil locomoteur','M24.031'),
('Loose body in left wrist','Loose body in left wrist','Maladies de l''appareil locomoteur','M24.032'),
('Loose body in non spécifié wrist','Loose body in unspecified wrist','Maladies de l''appareil locomoteur','M24.039'),
('Loose body in right finger joint(s)','Loose body in right finger joint(s)','Maladies de l''appareil locomoteur','M24.041'),
('Loose body in left finger joint(s)','Loose body in left finger joint(s)','Maladies de l''appareil locomoteur','M24.042'),
('Loose body in non spécifié finger joint(s)','Loose body in unspecified finger joint(s)','Maladies de l''appareil locomoteur','M24.049'),
('Loose body in right hip','Loose body in right hip','Maladies de l''appareil locomoteur','M24.051'),
('Loose body in left hip','Loose body in left hip','Maladies de l''appareil locomoteur','M24.052'),
('Loose body in non spécifié hip','Loose body in unspecified hip','Maladies de l''appareil locomoteur','M24.059'),
('Loose body in right ankle','Loose body in right ankle','Maladies de l''appareil locomoteur','M24.071'),
('Loose body in left ankle','Loose body in left ankle','Maladies de l''appareil locomoteur','M24.072'),
('Loose body in non spécifié ankle','Loose body in unspecified ankle','Maladies de l''appareil locomoteur','M24.073'),
('Loose body in right toe joint(s)','Loose body in right toe joint(s)','Maladies de l''appareil locomoteur','M24.074'),
('Loose body in left toe joint(s)','Loose body in left toe joint(s)','Maladies de l''appareil locomoteur','M24.075'),
('Loose body in non spécifié toe joint(s)','Loose body in unspecified toe joint(s)','Maladies de l''appareil locomoteur','M24.076'),
('Loose body, autre site','Loose body, other site','Maladies de l''appareil locomoteur','M24.08'),
('autre articular cartilage disorders, non spécifié site','Other articular cartilage disorders, unspecified site','Maladies de l''appareil locomoteur','M24.10'),
('autre articular cartilage disorders, right shoulder','Other articular cartilage disorders, right shoulder','Maladies de l''appareil locomoteur','M24.111'),
('autre articular cartilage disorders, left shoulder','Other articular cartilage disorders, left shoulder','Maladies de l''appareil locomoteur','M24.112'),
('autre articular cartilage disorders, non spécifié shoulder','Other articular cartilage disorders, unspecified shoulder','Maladies de l''appareil locomoteur','M24.119'),
('autre articular cartilage disorders, right elbow','Other articular cartilage disorders, right elbow','Maladies de l''appareil locomoteur','M24.121'),
('autre articular cartilage disorders, left elbow','Other articular cartilage disorders, left elbow','Maladies de l''appareil locomoteur','M24.122'),
('autre articular cartilage disorders, non spécifié elbow','Other articular cartilage disorders, unspecified elbow','Maladies de l''appareil locomoteur','M24.129'),
('autre articular cartilage disorders, right wrist','Other articular cartilage disorders, right wrist','Maladies de l''appareil locomoteur','M24.131'),
('autre articular cartilage disorders, left wrist','Other articular cartilage disorders, left wrist','Maladies de l''appareil locomoteur','M24.132'),
('autre articular cartilage disorders, non spécifié wrist','Other articular cartilage disorders, unspecified wrist','Maladies de l''appareil locomoteur','M24.139'),
('autre articular cartilage disorders, right hand','Other articular cartilage disorders, right hand','Maladies de l''appareil locomoteur','M24.141'),
('autre articular cartilage disorders, left hand','Other articular cartilage disorders, left hand','Maladies de l''appareil locomoteur','M24.142'),
('autre articular cartilage disorders, non spécifié hand','Other articular cartilage disorders, unspecified hand','Maladies de l''appareil locomoteur','M24.149'),
('autre articular cartilage disorders, right hip','Other articular cartilage disorders, right hip','Maladies de l''appareil locomoteur','M24.151'),
('autre articular cartilage disorders, left hip','Other articular cartilage disorders, left hip','Maladies de l''appareil locomoteur','M24.152'),
('autre articular cartilage disorders, non spécifié hip','Other articular cartilage disorders, unspecified hip','Maladies de l''appareil locomoteur','M24.159'),
('autre articular cartilage disorders, right ankle','Other articular cartilage disorders, right ankle','Maladies de l''appareil locomoteur','M24.171'),
('autre articular cartilage disorders, left ankle','Other articular cartilage disorders, left ankle','Maladies de l''appareil locomoteur','M24.172'),
('autre articular cartilage disorders, non spécifié ankle','Other articular cartilage disorders, unspecified ankle','Maladies de l''appareil locomoteur','M24.173'),
('autre articular cartilage disorders, right foot','Other articular cartilage disorders, right foot','Maladies de l''appareil locomoteur','M24.174'),
('autre articular cartilage disorders, left foot','Other articular cartilage disorders, left foot','Maladies de l''appareil locomoteur','M24.175'),
('autre articular cartilage disorders, non spécifié foot','Other articular cartilage disorders, unspecified foot','Maladies de l''appareil locomoteur','M24.176'),
('autre articular cartilage disorders, autre specified site','Other articular cartilage disorders, other specified site','Maladies de l''appareil locomoteur','M24.19'),
('trouble of ligament, non spécifié site','Disorder of ligament, unspecified site','Maladies de l''appareil locomoteur','M24.20'),
('trouble of ligament, right shoulder','Disorder of ligament, right shoulder','Maladies de l''appareil locomoteur','M24.211'),
('trouble of ligament, left shoulder','Disorder of ligament, left shoulder','Maladies de l''appareil locomoteur','M24.212'),
('trouble of ligament, non spécifié shoulder','Disorder of ligament, unspecified shoulder','Maladies de l''appareil locomoteur','M24.219'),
('trouble of ligament, right elbow','Disorder of ligament, right elbow','Maladies de l''appareil locomoteur','M24.221'),
('trouble of ligament, left elbow','Disorder of ligament, left elbow','Maladies de l''appareil locomoteur','M24.222'),
('trouble of ligament, non spécifié elbow','Disorder of ligament, unspecified elbow','Maladies de l''appareil locomoteur','M24.229'),
('trouble of ligament, right wrist','Disorder of ligament, right wrist','Maladies de l''appareil locomoteur','M24.231'),
('trouble of ligament, left wrist','Disorder of ligament, left wrist','Maladies de l''appareil locomoteur','M24.232'),
('trouble of ligament, non spécifié wrist','Disorder of ligament, unspecified wrist','Maladies de l''appareil locomoteur','M24.239'),
('trouble of ligament, right hand','Disorder of ligament, right hand','Maladies de l''appareil locomoteur','M24.241'),
('trouble of ligament, left hand','Disorder of ligament, left hand','Maladies de l''appareil locomoteur','M24.242'),
('trouble of ligament, non spécifié hand','Disorder of ligament, unspecified hand','Maladies de l''appareil locomoteur','M24.249'),
('trouble of ligament, right hip','Disorder of ligament, right hip','Maladies de l''appareil locomoteur','M24.251'),
('trouble of ligament, left hip','Disorder of ligament, left hip','Maladies de l''appareil locomoteur','M24.252'),
('trouble of ligament, non spécifié hip','Disorder of ligament, unspecified hip','Maladies de l''appareil locomoteur','M24.259'),
('trouble of ligament, right ankle','Disorder of ligament, right ankle','Maladies de l''appareil locomoteur','M24.271'),
('trouble of ligament, left ankle','Disorder of ligament, left ankle','Maladies de l''appareil locomoteur','M24.272'),
('trouble of ligament, non spécifié ankle','Disorder of ligament, unspecified ankle','Maladies de l''appareil locomoteur','M24.273'),
('trouble of ligament, right foot','Disorder of ligament, right foot','Maladies de l''appareil locomoteur','M24.274'),
('trouble of ligament, left foot','Disorder of ligament, left foot','Maladies de l''appareil locomoteur','M24.275'),
('trouble of ligament, non spécifié foot','Disorder of ligament, unspecified foot','Maladies de l''appareil locomoteur','M24.276'),
('trouble of ligament, vertebrae','Disorder of ligament, vertebrae','Maladies de l''appareil locomoteur','M24.28'),
('trouble of ligament, autre specified site','Disorder of ligament, other specified site','Maladies de l''appareil locomoteur','M24.29'),
('Pathological dislocation of non spécifié joint, not elsewhere classified','Pathological dislocation of unspecified joint, not elsewhere classified','Maladies de l''appareil locomoteur','M24.30'),
('Pathological dislocation of right shoulder, not elsewhere classified','Pathological dislocation of right shoulder, not elsewhere classified','Maladies de l''appareil locomoteur','M24.311'),
('Pathological dislocation of left shoulder, not elsewhere classified','Pathological dislocation of left shoulder, not elsewhere classified','Maladies de l''appareil locomoteur','M24.312'),
('Pathological dislocation of non spécifié shoulder, not elsewhere classified','Pathological dislocation of unspecified shoulder, not elsewhere classified','Maladies de l''appareil locomoteur','M24.319'),
('Pathological dislocation of right elbow, not elsewhere classified','Pathological dislocation of right elbow, not elsewhere classified','Maladies de l''appareil locomoteur','M24.321'),
('Pathological dislocation of left elbow, not elsewhere classified','Pathological dislocation of left elbow, not elsewhere classified','Maladies de l''appareil locomoteur','M24.322'),
('Pathological dislocation of non spécifié elbow, not elsewhere classified','Pathological dislocation of unspecified elbow, not elsewhere classified','Maladies de l''appareil locomoteur','M24.329'),
('Pathological dislocation of right wrist, not elsewhere classified','Pathological dislocation of right wrist, not elsewhere classified','Maladies de l''appareil locomoteur','M24.331'),
('Pathological dislocation of left wrist, not elsewhere classified','Pathological dislocation of left wrist, not elsewhere classified','Maladies de l''appareil locomoteur','M24.332'),
('Pathological dislocation of non spécifié wrist, not elsewhere classified','Pathological dislocation of unspecified wrist, not elsewhere classified','Maladies de l''appareil locomoteur','M24.339'),
('Pathological dislocation of right hand, not elsewhere classified','Pathological dislocation of right hand, not elsewhere classified','Maladies de l''appareil locomoteur','M24.341'),
('Pathological dislocation of left hand, not elsewhere classified','Pathological dislocation of left hand, not elsewhere classified','Maladies de l''appareil locomoteur','M24.342'),
('Pathological dislocation of non spécifié hand, not elsewhere classified','Pathological dislocation of unspecified hand, not elsewhere classified','Maladies de l''appareil locomoteur','M24.349'),
('Pathological dislocation of right hip, not elsewhere classified','Pathological dislocation of right hip, not elsewhere classified','Maladies de l''appareil locomoteur','M24.351'),
('Pathological dislocation of left hip, not elsewhere classified','Pathological dislocation of left hip, not elsewhere classified','Maladies de l''appareil locomoteur','M24.352'),
('Pathological dislocation of non spécifié hip, not elsewhere classified','Pathological dislocation of unspecified hip, not elsewhere classified','Maladies de l''appareil locomoteur','M24.359'),
('Pathological dislocation of right knee, not elsewhere classified','Pathological dislocation of right knee, not elsewhere classified','Maladies de l''appareil locomoteur','M24.361')
ON CONFLICT (nom_fr) DO NOTHING;
