-- icd10v2_batch_313.sql (80 rows)
INSERT INTO pathologies (nom_fr, nom_en, categorie, icd10_code)
VALUES
('Blister (nonthermal) of left ring finger, initial encounter','Blister (nonthermal) of left ring finger, initial encounter','Traumatismes, empoisonnements et autres causes externes','S60.425A'),
('Blister (nonthermal) of left ring finger, subsequent encounter','Blister (nonthermal) of left ring finger, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S60.425D'),
('Blister (nonthermal) of left ring finger, sequela','Blister (nonthermal) of left ring finger, sequela','Traumatismes, empoisonnements et autres causes externes','S60.425S'),
('Blister (nonthermal) of right little finger, initial encounter','Blister (nonthermal) of right little finger, initial encounter','Traumatismes, empoisonnements et autres causes externes','S60.426A'),
('Blister (nonthermal) of right little finger, subsequent encounter','Blister (nonthermal) of right little finger, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S60.426D'),
('Blister (nonthermal) of right little finger, sequela','Blister (nonthermal) of right little finger, sequela','Traumatismes, empoisonnements et autres causes externes','S60.426S'),
('Blister (nonthermal) of left little finger, initial encounter','Blister (nonthermal) of left little finger, initial encounter','Traumatismes, empoisonnements et autres causes externes','S60.427A'),
('Blister (nonthermal) of left little finger, subsequent encounter','Blister (nonthermal) of left little finger, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S60.427D'),
('Blister (nonthermal) of left little finger, sequela','Blister (nonthermal) of left little finger, sequela','Traumatismes, empoisonnements et autres causes externes','S60.427S'),
('Blister (nonthermal) of autre finger, initial encounter','Blister (nonthermal) of other finger, initial encounter','Traumatismes, empoisonnements et autres causes externes','S60.428A'),
('Blister (nonthermal) of autre finger, subsequent encounter','Blister (nonthermal) of other finger, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S60.428D'),
('Blister (nonthermal) of autre finger, sequela','Blister (nonthermal) of other finger, sequela','Traumatismes, empoisonnements et autres causes externes','S60.428S'),
('Blister (nonthermal) of non spécifié finger, initial encounter','Blister (nonthermal) of unspecified finger, initial encounter','Traumatismes, empoisonnements et autres causes externes','S60.429A'),
('Blister (nonthermal) of non spécifié finger, subsequent encounter','Blister (nonthermal) of unspecified finger, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S60.429D'),
('Blister (nonthermal) of non spécifié finger, sequela','Blister (nonthermal) of unspecified finger, sequela','Traumatismes, empoisonnements et autres causes externes','S60.429S'),
('External constriction of right index finger, initial encounter','External constriction of right index finger, initial encounter','Traumatismes, empoisonnements et autres causes externes','S60.440A'),
('External constriction of right index finger, subsequent encounter','External constriction of right index finger, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S60.440D'),
('External constriction of right index finger, sequela','External constriction of right index finger, sequela','Traumatismes, empoisonnements et autres causes externes','S60.440S'),
('External constriction of left index finger, initial encounter','External constriction of left index finger, initial encounter','Traumatismes, empoisonnements et autres causes externes','S60.441A'),
('External constriction of left index finger, subsequent encounter','External constriction of left index finger, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S60.441D'),
('External constriction of left index finger, sequela','External constriction of left index finger, sequela','Traumatismes, empoisonnements et autres causes externes','S60.441S'),
('External constriction of right middle finger, initial encounter','External constriction of right middle finger, initial encounter','Traumatismes, empoisonnements et autres causes externes','S60.442A'),
('External constriction of right middle finger, subsequent encounter','External constriction of right middle finger, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S60.442D'),
('External constriction of right middle finger, sequela','External constriction of right middle finger, sequela','Traumatismes, empoisonnements et autres causes externes','S60.442S'),
('External constriction of left middle finger, initial encounter','External constriction of left middle finger, initial encounter','Traumatismes, empoisonnements et autres causes externes','S60.443A'),
('External constriction of left middle finger, subsequent encounter','External constriction of left middle finger, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S60.443D'),
('External constriction of left middle finger, sequela','External constriction of left middle finger, sequela','Traumatismes, empoisonnements et autres causes externes','S60.443S'),
('External constriction of right ring finger, initial encounter','External constriction of right ring finger, initial encounter','Traumatismes, empoisonnements et autres causes externes','S60.444A'),
('External constriction of right ring finger, subsequent encounter','External constriction of right ring finger, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S60.444D'),
('External constriction of right ring finger, sequela','External constriction of right ring finger, sequela','Traumatismes, empoisonnements et autres causes externes','S60.444S'),
('External constriction of left ring finger, initial encounter','External constriction of left ring finger, initial encounter','Traumatismes, empoisonnements et autres causes externes','S60.445A'),
('External constriction of left ring finger, subsequent encounter','External constriction of left ring finger, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S60.445D'),
('External constriction of left ring finger, sequela','External constriction of left ring finger, sequela','Traumatismes, empoisonnements et autres causes externes','S60.445S'),
('External constriction of right little finger, initial encounter','External constriction of right little finger, initial encounter','Traumatismes, empoisonnements et autres causes externes','S60.446A'),
('External constriction of right little finger, subsequent encounter','External constriction of right little finger, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S60.446D'),
('External constriction of right little finger, sequela','External constriction of right little finger, sequela','Traumatismes, empoisonnements et autres causes externes','S60.446S'),
('External constriction of left little finger, initial encounter','External constriction of left little finger, initial encounter','Traumatismes, empoisonnements et autres causes externes','S60.447A'),
('External constriction of left little finger, subsequent encounter','External constriction of left little finger, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S60.447D'),
('External constriction of left little finger, sequela','External constriction of left little finger, sequela','Traumatismes, empoisonnements et autres causes externes','S60.447S'),
('External constriction of autre finger, initial encounter','External constriction of other finger, initial encounter','Traumatismes, empoisonnements et autres causes externes','S60.448A'),
('External constriction of autre finger, subsequent encounter','External constriction of other finger, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S60.448D'),
('External constriction of autre finger, sequela','External constriction of other finger, sequela','Traumatismes, empoisonnements et autres causes externes','S60.448S'),
('External constriction of non spécifié finger, initial encounter','External constriction of unspecified finger, initial encounter','Traumatismes, empoisonnements et autres causes externes','S60.449A'),
('External constriction of non spécifié finger, subsequent encounter','External constriction of unspecified finger, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S60.449D'),
('External constriction of non spécifié finger, sequela','External constriction of unspecified finger, sequela','Traumatismes, empoisonnements et autres causes externes','S60.449S'),
('Superficial foreign body of right index finger, initial encounter','Superficial foreign body of right index finger, initial encounter','Traumatismes, empoisonnements et autres causes externes','S60.450A'),
('Superficial foreign body of right index finger, subsequent encounter','Superficial foreign body of right index finger, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S60.450D'),
('Superficial foreign body of right index finger, sequela','Superficial foreign body of right index finger, sequela','Traumatismes, empoisonnements et autres causes externes','S60.450S'),
('Superficial foreign body of left index finger, initial encounter','Superficial foreign body of left index finger, initial encounter','Traumatismes, empoisonnements et autres causes externes','S60.451A'),
('Superficial foreign body of left index finger, subsequent encounter','Superficial foreign body of left index finger, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S60.451D'),
('Superficial foreign body of left index finger, sequela','Superficial foreign body of left index finger, sequela','Traumatismes, empoisonnements et autres causes externes','S60.451S'),
('Superficial foreign body of right middle finger, initial encounter','Superficial foreign body of right middle finger, initial encounter','Traumatismes, empoisonnements et autres causes externes','S60.452A'),
('Superficial foreign body of right middle finger, subsequent encounter','Superficial foreign body of right middle finger, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S60.452D'),
('Superficial foreign body of right middle finger, sequela','Superficial foreign body of right middle finger, sequela','Traumatismes, empoisonnements et autres causes externes','S60.452S'),
('Superficial foreign body of left middle finger, initial encounter','Superficial foreign body of left middle finger, initial encounter','Traumatismes, empoisonnements et autres causes externes','S60.453A'),
('Superficial foreign body of left middle finger, subsequent encounter','Superficial foreign body of left middle finger, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S60.453D'),
('Superficial foreign body of left middle finger, sequela','Superficial foreign body of left middle finger, sequela','Traumatismes, empoisonnements et autres causes externes','S60.453S'),
('Superficial foreign body of right ring finger, initial encounter','Superficial foreign body of right ring finger, initial encounter','Traumatismes, empoisonnements et autres causes externes','S60.454A'),
('Superficial foreign body of right ring finger, subsequent encounter','Superficial foreign body of right ring finger, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S60.454D'),
('Superficial foreign body of right ring finger, sequela','Superficial foreign body of right ring finger, sequela','Traumatismes, empoisonnements et autres causes externes','S60.454S'),
('Superficial foreign body of left ring finger, initial encounter','Superficial foreign body of left ring finger, initial encounter','Traumatismes, empoisonnements et autres causes externes','S60.455A'),
('Superficial foreign body of left ring finger, subsequent encounter','Superficial foreign body of left ring finger, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S60.455D'),
('Superficial foreign body of left ring finger, sequela','Superficial foreign body of left ring finger, sequela','Traumatismes, empoisonnements et autres causes externes','S60.455S'),
('Superficial foreign body of right little finger, initial encounter','Superficial foreign body of right little finger, initial encounter','Traumatismes, empoisonnements et autres causes externes','S60.456A'),
('Superficial foreign body of right little finger, subsequent encounter','Superficial foreign body of right little finger, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S60.456D'),
('Superficial foreign body of right little finger, sequela','Superficial foreign body of right little finger, sequela','Traumatismes, empoisonnements et autres causes externes','S60.456S'),
('Superficial foreign body of left little finger, initial encounter','Superficial foreign body of left little finger, initial encounter','Traumatismes, empoisonnements et autres causes externes','S60.457A'),
('Superficial foreign body of left little finger, subsequent encounter','Superficial foreign body of left little finger, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S60.457D'),
('Superficial foreign body of left little finger, sequela','Superficial foreign body of left little finger, sequela','Traumatismes, empoisonnements et autres causes externes','S60.457S'),
('Superficial foreign body of autre finger, initial encounter','Superficial foreign body of other finger, initial encounter','Traumatismes, empoisonnements et autres causes externes','S60.458A'),
('Superficial foreign body of autre finger, subsequent encounter','Superficial foreign body of other finger, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S60.458D'),
('Superficial foreign body of autre finger, sequela','Superficial foreign body of other finger, sequela','Traumatismes, empoisonnements et autres causes externes','S60.458S'),
('Superficial foreign body of non spécifié finger, initial encounter','Superficial foreign body of unspecified finger, initial encounter','Traumatismes, empoisonnements et autres causes externes','S60.459A'),
('Superficial foreign body of non spécifié finger, subsequent encounter','Superficial foreign body of unspecified finger, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S60.459D'),
('Superficial foreign body of non spécifié finger, sequela','Superficial foreign body of unspecified finger, sequela','Traumatismes, empoisonnements et autres causes externes','S60.459S'),
('Insect bite (nonvenomous) of right index finger, initial encounter','Insect bite (nonvenomous) of right index finger, initial encounter','Traumatismes, empoisonnements et autres causes externes','S60.460A'),
('Insect bite (nonvenomous) of right index finger, subsequent encounter','Insect bite (nonvenomous) of right index finger, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S60.460D'),
('Insect bite (nonvenomous) of right index finger, sequela','Insect bite (nonvenomous) of right index finger, sequela','Traumatismes, empoisonnements et autres causes externes','S60.460S'),
('Insect bite (nonvenomous) of left index finger, initial encounter','Insect bite (nonvenomous) of left index finger, initial encounter','Traumatismes, empoisonnements et autres causes externes','S60.461A'),
('Insect bite (nonvenomous) of left index finger, subsequent encounter','Insect bite (nonvenomous) of left index finger, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S60.461D')
ON CONFLICT (nom_fr) DO NOTHING;
