-- icd10v2_batch_216.sql (80 rows)
INSERT INTO pathologies (nom_fr, nom_en, categorie, icd10_code)
VALUES
('autre male sexual dysfunction','Other male sexual dysfunction','Maladies de l''appareil génito-urinaire','N53.8'),
('non spécifié male sexual dysfunction','Unspecified male sexual dysfunction','Maladies de l''appareil génito-urinaire','N53.9'),
('Solitary cyst of right breast','Solitary cyst of right breast','Maladies de l''appareil génito-urinaire','N60.01'),
('Solitary cyst of left breast','Solitary cyst of left breast','Maladies de l''appareil génito-urinaire','N60.02'),
('Solitary cyst of non spécifié breast','Solitary cyst of unspecified breast','Maladies de l''appareil génito-urinaire','N60.09'),
('Diffuse cystic mastopathy of right breast','Diffuse cystic mastopathy of right breast','Maladies de l''appareil génito-urinaire','N60.11'),
('Diffuse cystic mastopathy of left breast','Diffuse cystic mastopathy of left breast','Maladies de l''appareil génito-urinaire','N60.12'),
('Diffuse cystic mastopathy of non spécifié breast','Diffuse cystic mastopathy of unspecified breast','Maladies de l''appareil génito-urinaire','N60.19'),
('Fibroadenosis of right breast','Fibroadenosis of right breast','Maladies de l''appareil génito-urinaire','N60.21'),
('Fibroadenosis of left breast','Fibroadenosis of left breast','Maladies de l''appareil génito-urinaire','N60.22'),
('Fibroadenosis of non spécifié breast','Fibroadenosis of unspecified breast','Maladies de l''appareil génito-urinaire','N60.29'),
('Fibrosclerosis of right breast','Fibrosclerosis of right breast','Maladies de l''appareil génito-urinaire','N60.31'),
('Fibrosclerosis of left breast','Fibrosclerosis of left breast','Maladies de l''appareil génito-urinaire','N60.32'),
('Fibrosclerosis of non spécifié breast','Fibrosclerosis of unspecified breast','Maladies de l''appareil génito-urinaire','N60.39'),
('Mammary duct ectasia of right breast','Mammary duct ectasia of right breast','Maladies de l''appareil génito-urinaire','N60.41'),
('Mammary duct ectasia of left breast','Mammary duct ectasia of left breast','Maladies de l''appareil génito-urinaire','N60.42'),
('Mammary duct ectasia of non spécifié breast','Mammary duct ectasia of unspecified breast','Maladies de l''appareil génito-urinaire','N60.49'),
('autre bénin mammary dysplasias of right breast','Other benign mammary dysplasias of right breast','Maladies de l''appareil génito-urinaire','N60.81'),
('autre bénin mammary dysplasias of left breast','Other benign mammary dysplasias of left breast','Maladies de l''appareil génito-urinaire','N60.82'),
('autre bénin mammary dysplasias of non spécifié breast','Other benign mammary dysplasias of unspecified breast','Maladies de l''appareil génito-urinaire','N60.89'),
('non spécifié bénin mammary dysplasia of right breast','Unspecified benign mammary dysplasia of right breast','Maladies de l''appareil génito-urinaire','N60.91'),
('non spécifié bénin mammary dysplasia of left breast','Unspecified benign mammary dysplasia of left breast','Maladies de l''appareil génito-urinaire','N60.92'),
('non spécifié bénin mammary dysplasia of non spécifié breast','Unspecified benign mammary dysplasia of unspecified breast','Maladies de l''appareil génito-urinaire','N60.99'),
('Mastitis without abscess','Mastitis without abscess','Maladies de l''appareil génito-urinaire','N61.0'),
('Abscess of the breast and nipple','Abscess of the breast and nipple','Maladies de l''appareil génito-urinaire','N61.1'),
('Granulomatous mastitis, non spécifié breast','Granulomatous mastitis, unspecified breast','Maladies de l''appareil génito-urinaire','N61.20'),
('Granulomatous mastitis, right breast','Granulomatous mastitis, right breast','Maladies de l''appareil génito-urinaire','N61.21'),
('Granulomatous mastitis, left breast','Granulomatous mastitis, left breast','Maladies de l''appareil génito-urinaire','N61.22'),
('Granulomatous mastitis, bilateral breast','Granulomatous mastitis, bilateral breast','Maladies de l''appareil génito-urinaire','N61.23'),
('Hypertrophy of breast','Hypertrophy of breast','Maladies de l''appareil génito-urinaire','N62'),
('non spécifié lump in non spécifié breast','Unspecified lump in unspecified breast','Maladies de l''appareil génito-urinaire','N63.0'),
('non spécifié lump in the right breast, non spécifié quadrant','Unspecified lump in the right breast, unspecified quadrant','Maladies de l''appareil génito-urinaire','N63.10'),
('non spécifié lump in the right breast, upper outer quadrant','Unspecified lump in the right breast, upper outer quadrant','Maladies de l''appareil génito-urinaire','N63.11'),
('non spécifié lump in the right breast, upper inner quadrant','Unspecified lump in the right breast, upper inner quadrant','Maladies de l''appareil génito-urinaire','N63.12'),
('non spécifié lump in the right breast, lower outer quadrant','Unspecified lump in the right breast, lower outer quadrant','Maladies de l''appareil génito-urinaire','N63.13'),
('non spécifié lump in the right breast, lower inner quadrant','Unspecified lump in the right breast, lower inner quadrant','Maladies de l''appareil génito-urinaire','N63.14'),
('non spécifié lump in the right breast, overlapping quadrants','Unspecified lump in the right breast, overlapping quadrants','Maladies de l''appareil génito-urinaire','N63.15'),
('non spécifié lump in the left breast, non spécifié quadrant','Unspecified lump in the left breast, unspecified quadrant','Maladies de l''appareil génito-urinaire','N63.20'),
('non spécifié lump in the left breast, upper outer quadrant','Unspecified lump in the left breast, upper outer quadrant','Maladies de l''appareil génito-urinaire','N63.21'),
('non spécifié lump in the left breast, upper inner quadrant','Unspecified lump in the left breast, upper inner quadrant','Maladies de l''appareil génito-urinaire','N63.22'),
('non spécifié lump in the left breast, lower outer quadrant','Unspecified lump in the left breast, lower outer quadrant','Maladies de l''appareil génito-urinaire','N63.23'),
('non spécifié lump in the left breast, lower inner quadrant','Unspecified lump in the left breast, lower inner quadrant','Maladies de l''appareil génito-urinaire','N63.24'),
('non spécifié lump in the left breast, overlapping quadrants','Unspecified lump in the left breast, overlapping quadrants','Maladies de l''appareil génito-urinaire','N63.25'),
('non spécifié lump in axillary tail of the right breast','Unspecified lump in axillary tail of the right breast','Maladies de l''appareil génito-urinaire','N63.31'),
('non spécifié lump in axillary tail of the left breast','Unspecified lump in axillary tail of the left breast','Maladies de l''appareil génito-urinaire','N63.32'),
('non spécifié lump in right breast, subareolar','Unspecified lump in right breast, subareolar','Maladies de l''appareil génito-urinaire','N63.41'),
('non spécifié lump in left breast, subareolar','Unspecified lump in left breast, subareolar','Maladies de l''appareil génito-urinaire','N63.42'),
('Fissure and fistula of nipple','Fissure and fistula of nipple','Maladies de l''appareil génito-urinaire','N64.0'),
('Fat necrosis of breast','Fat necrosis of breast','Maladies de l''appareil génito-urinaire','N64.1'),
('Atrophy of breast','Atrophy of breast','Maladies de l''appareil génito-urinaire','N64.2'),
('Galactorrhea not associated with childbirth','Galactorrhea not associated with childbirth','Maladies de l''appareil génito-urinaire','N64.3'),
('Mastodynia','Mastodynia','Maladies de l''appareil génito-urinaire','N64.4'),
('Induration of breast','Induration of breast','Maladies de l''appareil génito-urinaire','N64.51'),
('Nipple discharge','Nipple discharge','Maladies de l''appareil génito-urinaire','N64.52'),
('Retraction of nipple','Retraction of nipple','Maladies de l''appareil génito-urinaire','N64.53'),
('autre signs and symptoms in breast','Other signs and symptoms in breast','Maladies de l''appareil génito-urinaire','N64.59'),
('Ptosis of breast','Ptosis of breast','Maladies de l''appareil génito-urinaire','N64.81'),
('Hypoplasia of breast','Hypoplasia of breast','Maladies de l''appareil génito-urinaire','N64.82'),
('autre specified disorders of breast','Other specified disorders of breast','Maladies de l''appareil génito-urinaire','N64.89'),
('trouble of breast, non spécifié','Disorder of breast, unspecified','Maladies de l''appareil génito-urinaire','N64.9'),
('Deformity of reconstructed breast','Deformity of reconstructed breast','Maladies de l''appareil génito-urinaire','N65.0'),
('Disproportion of reconstructed breast','Disproportion of reconstructed breast','Maladies de l''appareil génito-urinaire','N65.1'),
('aigu salpingitis','Acute salpingitis','Maladies de l''appareil génito-urinaire','N70.01'),
('aigu oophoritis','Acute oophoritis','Maladies de l''appareil génito-urinaire','N70.02'),
('aigu salpingitis and oophoritis','Acute salpingitis and oophoritis','Maladies de l''appareil génito-urinaire','N70.03'),
('chronique salpingitis','Chronic salpingitis','Maladies de l''appareil génito-urinaire','N70.11'),
('chronique oophoritis','Chronic oophoritis','Maladies de l''appareil génito-urinaire','N70.12'),
('chronique salpingitis and oophoritis','Chronic salpingitis and oophoritis','Maladies de l''appareil génito-urinaire','N70.13'),
('Salpingitis, non spécifié','Salpingitis, unspecified','Maladies de l''appareil génito-urinaire','N70.91'),
('Oophoritis, non spécifié','Oophoritis, unspecified','Maladies de l''appareil génito-urinaire','N70.92'),
('Salpingitis and oophoritis, non spécifié','Salpingitis and oophoritis, unspecified','Maladies de l''appareil génito-urinaire','N70.93'),
('aigu inflammatory maladie of uterus','Acute inflammatory disease of uterus','Maladies de l''appareil génito-urinaire','N71.0'),
('chronique inflammatory maladie of uterus','Chronic inflammatory disease of uterus','Maladies de l''appareil génito-urinaire','N71.1'),
('Inflammatory maladie of uterus, non spécifié','Inflammatory disease of uterus, unspecified','Maladies de l''appareil génito-urinaire','N71.9'),
('Inflammatory maladie of cervix uteri','Inflammatory disease of cervix uteri','Maladies de l''appareil génito-urinaire','N72'),
('aigu parametritis and pelvic cellulitis','Acute parametritis and pelvic cellulitis','Maladies de l''appareil génito-urinaire','N73.0'),
('chronique parametritis and pelvic cellulitis','Chronic parametritis and pelvic cellulitis','Maladies de l''appareil génito-urinaire','N73.1'),
('non spécifié parametritis and pelvic cellulitis','Unspecified parametritis and pelvic cellulitis','Maladies de l''appareil génito-urinaire','N73.2'),
('Female aigu pelvic peritonitis','Female acute pelvic peritonitis','Maladies de l''appareil génito-urinaire','N73.3'),
('Female chronique pelvic peritonitis','Female chronic pelvic peritonitis','Maladies de l''appareil génito-urinaire','N73.4')
ON CONFLICT (nom_fr) DO NOTHING;
