-- icd10_batch_044.sql (80 rows)
INSERT INTO pathologies (nom_fr, nom_en, categorie, icd10_code)
VALUES
('Encounter for examination for insurance purposes','Encounter for examination for insurance purposes','Facteurs influant sur l''état de santé','Z02.6'),
('Encounter for disability determination','Encounter for disability determination','Facteurs influant sur l''état de santé','Z02.71'),
('Encounter for issue of autre medical certificate','Encounter for issue of other medical certificate','Facteurs influant sur l''état de santé','Z02.79'),
('Encounter for paternity testing','Encounter for paternity testing','Facteurs influant sur l''état de santé','Z02.81'),
('Encounter for adoption services','Encounter for adoption services','Facteurs influant sur l''état de santé','Z02.82'),
('Encounter for blood-alcohol and blood-drug test','Encounter for blood-alcohol and blood-drug test','Facteurs influant sur l''état de santé','Z02.83'),
('Encounter for child welfare exam','Encounter for child welfare exam','Facteurs influant sur l''état de santé','Z02.84'),
('Encounter for autre administrative examinations','Encounter for other administrative examinations','Facteurs influant sur l''état de santé','Z02.89'),
('Encounter for administrative examinations, non spécifié','Encounter for administrative examinations, unspecified','Facteurs influant sur l''état de santé','Z02.9'),
('Encounter for observation for suspected toxic effect from ingested substance ruled out','Encounter for observation for suspected toxic effect from ingested substance ruled out','Facteurs influant sur l''état de santé','Z03.6'),
('Encounter for suspected problem with amniotic cavity and membrane ruled out','Encounter for suspected problem with amniotic cavity and membrane ruled out','Facteurs influant sur l''état de santé','Z03.71'),
('Encounter for suspected placental problem ruled out','Encounter for suspected placental problem ruled out','Facteurs influant sur l''état de santé','Z03.72'),
('Encounter for suspected fetal anomaly ruled out','Encounter for suspected fetal anomaly ruled out','Facteurs influant sur l''état de santé','Z03.73'),
('Encounter for suspected problem with fetal growth ruled out','Encounter for suspected problem with fetal growth ruled out','Facteurs influant sur l''état de santé','Z03.74'),
('Encounter for suspected cervical shortening ruled out','Encounter for suspected cervical shortening ruled out','Facteurs influant sur l''état de santé','Z03.75'),
('Encounter for autre suspected maternal and fetal conditions ruled out','Encounter for other suspected maternal and fetal conditions ruled out','Facteurs influant sur l''état de santé','Z03.79'),
('Encounter for observation for suspected exposure to anthrax ruled out','Encounter for observation for suspected exposure to anthrax ruled out','Facteurs influant sur l''état de santé','Z03.810'),
('Encounter for observation for suspected exposure to autre biological agents ruled out','Encounter for observation for suspected exposure to other biological agents ruled out','Facteurs influant sur l''état de santé','Z03.818'),
('Encounter for observation for suspected ingested foreign body ruled out','Encounter for observation for suspected ingested foreign body ruled out','Facteurs influant sur l''état de santé','Z03.821'),
('Encounter for observation for suspected aspirated (inhaled) foreign body ruled out','Encounter for observation for suspected aspirated (inhaled) foreign body ruled out','Facteurs influant sur l''état de santé','Z03.822'),
('Encounter for observation for suspected inserted (injected) foreign body ruled out','Encounter for observation for suspected inserted (injected) foreign body ruled out','Facteurs influant sur l''état de santé','Z03.823'),
('Encounter for observation for suspected conditions related to home physiologic monitoring device ruled out','Encounter for observation for suspected conditions related to home physiologic monitoring device ruled out','Facteurs influant sur l''état de santé','Z03.83'),
('Encounter for observation for autre suspected diseases and conditions ruled out','Encounter for observation for other suspected diseases and conditions ruled out','Facteurs influant sur l''état de santé','Z03.89'),
('Encounter for examination and observation following transport accident','Encounter for examination and observation following transport accident','Facteurs influant sur l''état de santé','Z04.1'),
('Encounter for examination and observation following work accident','Encounter for examination and observation following work accident','Facteurs influant sur l''état de santé','Z04.2'),
('Encounter for examination and observation following autre accident','Encounter for examination and observation following other accident','Facteurs influant sur l''état de santé','Z04.3'),
('Encounter for examination and observation following alleged adult rape','Encounter for examination and observation following alleged adult rape','Facteurs influant sur l''état de santé','Z04.41'),
('Encounter for examination and observation following alleged child rape','Encounter for examination and observation following alleged child rape','Facteurs influant sur l''état de santé','Z04.42'),
('Encounter for general psychiatric examination, requested by authority','Encounter for general psychiatric examination, requested by authority','Facteurs influant sur l''état de santé','Z04.6'),
('Encounter for examination and observation following alleged adult physical abuse','Encounter for examination and observation following alleged adult physical abuse','Facteurs influant sur l''état de santé','Z04.71'),
('Encounter for examination and observation following alleged child physical abuse','Encounter for examination and observation following alleged child physical abuse','Facteurs influant sur l''état de santé','Z04.72'),
('Encounter for examination and observation of victim following forced sexual exploitation','Encounter for examination and observation of victim following forced sexual exploitation','Facteurs influant sur l''état de santé','Z04.81'),
('Encounter for examination and observation of victim following forced labor exploitation','Encounter for examination and observation of victim following forced labor exploitation','Facteurs influant sur l''état de santé','Z04.82'),
('Encounter for examination and observation for autre specified reasons','Encounter for examination and observation for other specified reasons','Facteurs influant sur l''état de santé','Z04.89'),
('Encounter for examination and observation for non spécifié reason','Encounter for examination and observation for unspecified reason','Facteurs influant sur l''état de santé','Z04.9'),
('Observation and evaluation of newborn for suspected cardiac condition ruled out','Observation and evaluation of newborn for suspected cardiac condition ruled out','Facteurs influant sur l''état de santé','Z05.0'),
('Observation and evaluation of newborn for suspected infectious condition ruled out','Observation and evaluation of newborn for suspected infectious condition ruled out','Facteurs influant sur l''état de santé','Z05.1'),
('Observation and evaluation of newborn for suspected neurological condition ruled out','Observation and evaluation of newborn for suspected neurological condition ruled out','Facteurs influant sur l''état de santé','Z05.2'),
('Observation and evaluation of newborn for suspected respiratory condition ruled out','Observation and evaluation of newborn for suspected respiratory condition ruled out','Facteurs influant sur l''état de santé','Z05.3'),
('Observation and evaluation of newborn for suspected genetic condition ruled out','Observation and evaluation of newborn for suspected genetic condition ruled out','Facteurs influant sur l''état de santé','Z05.41'),
('Observation and evaluation of newborn for suspected metabolic condition ruled out','Observation and evaluation of newborn for suspected metabolic condition ruled out','Facteurs influant sur l''état de santé','Z05.42'),
('Observation and evaluation of newborn for suspected immunologic condition ruled out','Observation and evaluation of newborn for suspected immunologic condition ruled out','Facteurs influant sur l''état de santé','Z05.43'),
('Observation and evaluation of newborn for suspected gastrointestinal condition ruled out','Observation and evaluation of newborn for suspected gastrointestinal condition ruled out','Facteurs influant sur l''état de santé','Z05.5'),
('Observation and evaluation of newborn for suspected genitourinary condition ruled out','Observation and evaluation of newborn for suspected genitourinary condition ruled out','Facteurs influant sur l''état de santé','Z05.6'),
('Observation and evaluation of newborn for suspected skin and subcutaneous tissue condition ruled out','Observation and evaluation of newborn for suspected skin and subcutaneous tissue condition ruled out','Facteurs influant sur l''état de santé','Z05.71'),
('Observation and evaluation of newborn for suspected musculoskeletal condition ruled out','Observation and evaluation of newborn for suspected musculoskeletal condition ruled out','Facteurs influant sur l''état de santé','Z05.72'),
('Observation and evaluation of newborn for suspected connective tissue condition ruled out','Observation and evaluation of newborn for suspected connective tissue condition ruled out','Facteurs influant sur l''état de santé','Z05.73'),
('Observation and evaluation of newborn for suspected condition related to home physiologic monitoring device ruled out','Observation and evaluation of newborn for suspected condition related to home physiologic monitoring device ruled out','Facteurs influant sur l''état de santé','Z05.81'),
('Observation and evaluation of newborn for autre specified suspected condition ruled out','Observation and evaluation of newborn for other specified suspected condition ruled out','Facteurs influant sur l''état de santé','Z05.89'),
('Observation and evaluation of newborn for non spécifié suspected condition ruled out','Observation and evaluation of newborn for unspecified suspected condition ruled out','Facteurs influant sur l''état de santé','Z05.9'),
('Encounter for follow-up examination after completed treatment for malin néoplasme','Encounter for follow-up examination after completed treatment for malignant neoplasm','Facteurs influant sur l''état de santé','Z08'),
('Encounter for follow-up examination after completed treatment for conditions autre than malin néoplasme','Encounter for follow-up examination after completed treatment for conditions other than malignant neoplasm','Facteurs influant sur l''état de santé','Z09'),
('Encounter for screening for intestinal infectious diseases','Encounter for screening for intestinal infectious diseases','Facteurs influant sur l''état de santé','Z11.0'),
('Encounter for screening for respiratory tuberculosis','Encounter for screening for respiratory tuberculosis','Facteurs influant sur l''état de santé','Z11.1'),
('Encounter for screening for autre bacterial diseases','Encounter for screening for other bacterial diseases','Facteurs influant sur l''état de santé','Z11.2'),
('Encounter for screening for infections with a predominantly sexual mode of transmission','Encounter for screening for infections with a predominantly sexual mode of transmission','Facteurs influant sur l''état de santé','Z11.3'),
('Encounter for screening for human immunodeficiency virus [HIV]','Encounter for screening for human immunodeficiency virus [HIV]','Facteurs influant sur l''état de santé','Z11.4'),
('Encounter for screening for human papillomavirus (HPV)','Encounter for screening for human papillomavirus (HPV)','Facteurs influant sur l''état de santé','Z11.51'),
('Encounter for screening for COVID-19','Encounter for screening for COVID-19','Facteurs influant sur l''état de santé','Z11.52'),
('Encounter for screening for autre viral diseases','Encounter for screening for other viral diseases','Facteurs influant sur l''état de santé','Z11.59'),
('Encounter for screening for autre protozoal diseases and helminthiases','Encounter for screening for other protozoal diseases and helminthiases','Facteurs influant sur l''état de santé','Z11.6'),
('Encounter for testing for latent tuberculosis infection','Encounter for testing for latent tuberculosis infection','Facteurs influant sur l''état de santé','Z11.7'),
('Encounter for screening for autre infectious and parasitic diseases','Encounter for screening for other infectious and parasitic diseases','Facteurs influant sur l''état de santé','Z11.8'),
('Encounter for screening for infectious and parasitic diseases, non spécifié','Encounter for screening for infectious and parasitic diseases, unspecified','Facteurs influant sur l''état de santé','Z11.9'),
('Encounter for screening for malin néoplasme of stomach','Encounter for screening for malignant neoplasm of stomach','Facteurs influant sur l''état de santé','Z12.0'),
('Encounter for screening for malin néoplasme of intestinal tract, non spécifié','Encounter for screening for malignant neoplasm of intestinal tract, unspecified','Facteurs influant sur l''état de santé','Z12.10'),
('Encounter for screening for malin néoplasme of colon','Encounter for screening for malignant neoplasm of colon','Facteurs influant sur l''état de santé','Z12.11'),
('Encounter for screening for malin néoplasme of rectum','Encounter for screening for malignant neoplasm of rectum','Facteurs influant sur l''état de santé','Z12.12'),
('Encounter for screening for malin néoplasme of small intestine','Encounter for screening for malignant neoplasm of small intestine','Facteurs influant sur l''état de santé','Z12.13'),
('Encounter for screening for malin néoplasme of respiratory organs','Encounter for screening for malignant neoplasm of respiratory organs','Facteurs influant sur l''état de santé','Z12.2'),
('Encounter for screening mammogram for malin néoplasme of breast','Encounter for screening mammogram for malignant neoplasm of breast','Facteurs influant sur l''état de santé','Z12.31'),
('Encounter for autre screening for malin néoplasme of breast','Encounter for other screening for malignant neoplasm of breast','Facteurs influant sur l''état de santé','Z12.39'),
('Encounter for screening for malin néoplasme of cervix','Encounter for screening for malignant neoplasm of cervix','Facteurs influant sur l''état de santé','Z12.4'),
('Encounter for screening for malin néoplasme of prostate','Encounter for screening for malignant neoplasm of prostate','Facteurs influant sur l''état de santé','Z12.5'),
('Encounter for screening for malin néoplasme of bladder','Encounter for screening for malignant neoplasm of bladder','Facteurs influant sur l''état de santé','Z12.6'),
('Encounter for screening for malin néoplasme of testis','Encounter for screening for malignant neoplasm of testis','Facteurs influant sur l''état de santé','Z12.71'),
('Encounter for screening for malin néoplasme of vagina','Encounter for screening for malignant neoplasm of vagina','Facteurs influant sur l''état de santé','Z12.72'),
('Encounter for screening for malin néoplasme of ovary','Encounter for screening for malignant neoplasm of ovary','Facteurs influant sur l''état de santé','Z12.73'),
('Encounter for screening for malin néoplasme of autre genitourinary organs','Encounter for screening for malignant neoplasm of other genitourinary organs','Facteurs influant sur l''état de santé','Z12.79'),
('Encounter for screening for malin néoplasme of oral cavity','Encounter for screening for malignant neoplasm of oral cavity','Facteurs influant sur l''état de santé','Z12.81')
ON CONFLICT (nom_fr) DO NOTHING;
