-- icd10_batch_035.sql (80 rows)
INSERT INTO pathologies (nom_fr, nom_en, categorie, icd10_code)
VALUES
('Overexertion from repetitive movements, subsequent encounter','Overexertion from repetitive movements, subsequent encounter','Causes externes de morbidité et de mortalité','X50.3XXD'),
('Overexertion from repetitive movements, sequela','Overexertion from repetitive movements, sequela','Causes externes de morbidité et de mortalité','X50.3XXS'),
('autre and non spécifié overexertion or strenuous movements or postures, initial encounter','Other and unspecified overexertion or strenuous movements or postures, initial encounter','Causes externes de morbidité et de mortalité','X50.9XXA'),
('autre and non spécifié overexertion or strenuous movements or postures, subsequent encounter','Other and unspecified overexertion or strenuous movements or postures, subsequent encounter','Causes externes de morbidité et de mortalité','X50.9XXD'),
('autre and non spécifié overexertion or strenuous movements or postures, sequela','Other and unspecified overexertion or strenuous movements or postures, sequela','Causes externes de morbidité et de mortalité','X50.9XXS'),
('Prolonged stay in weightless environment, initial encounter','Prolonged stay in weightless environment, initial encounter','Causes externes de morbidité et de mortalité','X52.XXXA'),
('Prolonged stay in weightless environment, subsequent encounter','Prolonged stay in weightless environment, subsequent encounter','Causes externes de morbidité et de mortalité','X52.XXXD'),
('Prolonged stay in weightless environment, sequela','Prolonged stay in weightless environment, sequela','Causes externes de morbidité et de mortalité','X52.XXXS'),
('Exposure to autre specified factors, initial encounter','Exposure to other specified factors, initial encounter','Causes externes de morbidité et de mortalité','X58.XXXA'),
('Exposure to autre specified factors, subsequent encounter','Exposure to other specified factors, subsequent encounter','Causes externes de morbidité et de mortalité','X58.XXXD'),
('Exposure to autre specified factors, sequela','Exposure to other specified factors, sequela','Causes externes de morbidité et de mortalité','X58.XXXS'),
('Intentional self-harm by drowning and submersion while in bathtub, initial encounter','Intentional self-harm by drowning and submersion while in bathtub, initial encounter','Causes externes de morbidité et de mortalité','X71.0XXA'),
('Intentional self-harm by drowning and submersion while in bathtub, subsequent encounter','Intentional self-harm by drowning and submersion while in bathtub, subsequent encounter','Causes externes de morbidité et de mortalité','X71.0XXD'),
('Intentional self-harm by drowning and submersion while in bathtub, sequela','Intentional self-harm by drowning and submersion while in bathtub, sequela','Causes externes de morbidité et de mortalité','X71.0XXS'),
('Intentional self-harm by drowning and submersion while in swimming pool, initial encounter','Intentional self-harm by drowning and submersion while in swimming pool, initial encounter','Causes externes de morbidité et de mortalité','X71.1XXA'),
('Intentional self-harm by drowning and submersion while in swimming pool, subsequent encounter','Intentional self-harm by drowning and submersion while in swimming pool, subsequent encounter','Causes externes de morbidité et de mortalité','X71.1XXD'),
('Intentional self-harm by drowning and submersion while in swimming pool, sequela','Intentional self-harm by drowning and submersion while in swimming pool, sequela','Causes externes de morbidité et de mortalité','X71.1XXS'),
('Intentional self-harm by drowning and submersion after jump into swimming pool, initial encounter','Intentional self-harm by drowning and submersion after jump into swimming pool, initial encounter','Causes externes de morbidité et de mortalité','X71.2XXA'),
('Intentional self-harm by drowning and submersion after jump into swimming pool, subsequent encounter','Intentional self-harm by drowning and submersion after jump into swimming pool, subsequent encounter','Causes externes de morbidité et de mortalité','X71.2XXD'),
('Intentional self-harm by drowning and submersion after jump into swimming pool, sequela','Intentional self-harm by drowning and submersion after jump into swimming pool, sequela','Causes externes de morbidité et de mortalité','X71.2XXS'),
('Intentional self-harm by drowning and submersion in natural water, initial encounter','Intentional self-harm by drowning and submersion in natural water, initial encounter','Causes externes de morbidité et de mortalité','X71.3XXA'),
('Intentional self-harm by drowning and submersion in natural water, subsequent encounter','Intentional self-harm by drowning and submersion in natural water, subsequent encounter','Causes externes de morbidité et de mortalité','X71.3XXD'),
('Intentional self-harm by drowning and submersion in natural water, sequela','Intentional self-harm by drowning and submersion in natural water, sequela','Causes externes de morbidité et de mortalité','X71.3XXS'),
('autre intentional self-harm by drowning and submersion, initial encounter','Other intentional self-harm by drowning and submersion, initial encounter','Causes externes de morbidité et de mortalité','X71.8XXA'),
('autre intentional self-harm by drowning and submersion, subsequent encounter','Other intentional self-harm by drowning and submersion, subsequent encounter','Causes externes de morbidité et de mortalité','X71.8XXD'),
('autre intentional self-harm by drowning and submersion, sequela','Other intentional self-harm by drowning and submersion, sequela','Causes externes de morbidité et de mortalité','X71.8XXS'),
('Intentional self-harm by drowning and submersion, non spécifié, initial encounter','Intentional self-harm by drowning and submersion, unspecified, initial encounter','Causes externes de morbidité et de mortalité','X71.9XXA'),
('Intentional self-harm by drowning and submersion, non spécifié, subsequent encounter','Intentional self-harm by drowning and submersion, unspecified, subsequent encounter','Causes externes de morbidité et de mortalité','X71.9XXD'),
('Intentional self-harm by drowning and submersion, non spécifié, sequela','Intentional self-harm by drowning and submersion, unspecified, sequela','Causes externes de morbidité et de mortalité','X71.9XXS'),
('Intentional self-harm by handgun discharge, initial encounter','Intentional self-harm by handgun discharge, initial encounter','Causes externes de morbidité et de mortalité','X72.XXXA'),
('Intentional self-harm by handgun discharge, subsequent encounter','Intentional self-harm by handgun discharge, subsequent encounter','Causes externes de morbidité et de mortalité','X72.XXXD'),
('Intentional self-harm by handgun discharge, sequela','Intentional self-harm by handgun discharge, sequela','Causes externes de morbidité et de mortalité','X72.XXXS'),
('Intentional self-harm by shotgun discharge, initial encounter','Intentional self-harm by shotgun discharge, initial encounter','Causes externes de morbidité et de mortalité','X73.0XXA'),
('Intentional self-harm by shotgun discharge, subsequent encounter','Intentional self-harm by shotgun discharge, subsequent encounter','Causes externes de morbidité et de mortalité','X73.0XXD'),
('Intentional self-harm by shotgun discharge, sequela','Intentional self-harm by shotgun discharge, sequela','Causes externes de morbidité et de mortalité','X73.0XXS'),
('Intentional self-harm by hunting rifle discharge, initial encounter','Intentional self-harm by hunting rifle discharge, initial encounter','Causes externes de morbidité et de mortalité','X73.1XXA'),
('Intentional self-harm by hunting rifle discharge, subsequent encounter','Intentional self-harm by hunting rifle discharge, subsequent encounter','Causes externes de morbidité et de mortalité','X73.1XXD'),
('Intentional self-harm by hunting rifle discharge, sequela','Intentional self-harm by hunting rifle discharge, sequela','Causes externes de morbidité et de mortalité','X73.1XXS'),
('Intentional self-harm by machine gun discharge, initial encounter','Intentional self-harm by machine gun discharge, initial encounter','Causes externes de morbidité et de mortalité','X73.2XXA'),
('Intentional self-harm by machine gun discharge, subsequent encounter','Intentional self-harm by machine gun discharge, subsequent encounter','Causes externes de morbidité et de mortalité','X73.2XXD'),
('Intentional self-harm by machine gun discharge, sequela','Intentional self-harm by machine gun discharge, sequela','Causes externes de morbidité et de mortalité','X73.2XXS'),
('Intentional self-harm by autre larger firearm discharge, initial encounter','Intentional self-harm by other larger firearm discharge, initial encounter','Causes externes de morbidité et de mortalité','X73.8XXA'),
('Intentional self-harm by autre larger firearm discharge, subsequent encounter','Intentional self-harm by other larger firearm discharge, subsequent encounter','Causes externes de morbidité et de mortalité','X73.8XXD'),
('Intentional self-harm by autre larger firearm discharge, sequela','Intentional self-harm by other larger firearm discharge, sequela','Causes externes de morbidité et de mortalité','X73.8XXS'),
('Intentional self-harm by non spécifié larger firearm discharge, initial encounter','Intentional self-harm by unspecified larger firearm discharge, initial encounter','Causes externes de morbidité et de mortalité','X73.9XXA'),
('Intentional self-harm by non spécifié larger firearm discharge, subsequent encounter','Intentional self-harm by unspecified larger firearm discharge, subsequent encounter','Causes externes de morbidité et de mortalité','X73.9XXD'),
('Intentional self-harm by non spécifié larger firearm discharge, sequela','Intentional self-harm by unspecified larger firearm discharge, sequela','Causes externes de morbidité et de mortalité','X73.9XXS'),
('Intentional self-harm by airgun, initial encounter','Intentional self-harm by airgun, initial encounter','Causes externes de morbidité et de mortalité','X74.01XA'),
('Intentional self-harm by airgun, subsequent encounter','Intentional self-harm by airgun, subsequent encounter','Causes externes de morbidité et de mortalité','X74.01XD'),
('Intentional self-harm by airgun, sequela','Intentional self-harm by airgun, sequela','Causes externes de morbidité et de mortalité','X74.01XS'),
('Intentional self-harm by paintball gun, initial encounter','Intentional self-harm by paintball gun, initial encounter','Causes externes de morbidité et de mortalité','X74.02XA'),
('Intentional self-harm by paintball gun, subsequent encounter','Intentional self-harm by paintball gun, subsequent encounter','Causes externes de morbidité et de mortalité','X74.02XD'),
('Intentional self-harm by paintball gun, sequela','Intentional self-harm by paintball gun, sequela','Causes externes de morbidité et de mortalité','X74.02XS'),
('Intentional self-harm by autre gas, air or spring-operated gun, initial encounter','Intentional self-harm by other gas, air or spring-operated gun, initial encounter','Causes externes de morbidité et de mortalité','X74.09XA'),
('Intentional self-harm by autre gas, air or spring-operated gun, subsequent encounter','Intentional self-harm by other gas, air or spring-operated gun, subsequent encounter','Causes externes de morbidité et de mortalité','X74.09XD'),
('Intentional self-harm by autre gas, air or spring-operated gun, sequela','Intentional self-harm by other gas, air or spring-operated gun, sequela','Causes externes de morbidité et de mortalité','X74.09XS'),
('Intentional self-harm by autre firearm discharge, initial encounter','Intentional self-harm by other firearm discharge, initial encounter','Causes externes de morbidité et de mortalité','X74.8XXA'),
('Intentional self-harm by autre firearm discharge, subsequent encounter','Intentional self-harm by other firearm discharge, subsequent encounter','Causes externes de morbidité et de mortalité','X74.8XXD'),
('Intentional self-harm by autre firearm discharge, sequela','Intentional self-harm by other firearm discharge, sequela','Causes externes de morbidité et de mortalité','X74.8XXS'),
('Intentional self-harm by non spécifié firearm discharge, initial encounter','Intentional self-harm by unspecified firearm discharge, initial encounter','Causes externes de morbidité et de mortalité','X74.9XXA'),
('Intentional self-harm by non spécifié firearm discharge, subsequent encounter','Intentional self-harm by unspecified firearm discharge, subsequent encounter','Causes externes de morbidité et de mortalité','X74.9XXD'),
('Intentional self-harm by non spécifié firearm discharge, sequela','Intentional self-harm by unspecified firearm discharge, sequela','Causes externes de morbidité et de mortalité','X74.9XXS'),
('Intentional self-harm by explosive material, initial encounter','Intentional self-harm by explosive material, initial encounter','Causes externes de morbidité et de mortalité','X75.XXXA'),
('Intentional self-harm by explosive material, subsequent encounter','Intentional self-harm by explosive material, subsequent encounter','Causes externes de morbidité et de mortalité','X75.XXXD'),
('Intentional self-harm by explosive material, sequela','Intentional self-harm by explosive material, sequela','Causes externes de morbidité et de mortalité','X75.XXXS'),
('Intentional self-harm by smoke, fire and flames, initial encounter','Intentional self-harm by smoke, fire and flames, initial encounter','Causes externes de morbidité et de mortalité','X76.XXXA'),
('Intentional self-harm by smoke, fire and flames, subsequent encounter','Intentional self-harm by smoke, fire and flames, subsequent encounter','Causes externes de morbidité et de mortalité','X76.XXXD'),
('Intentional self-harm by smoke, fire and flames, sequela','Intentional self-harm by smoke, fire and flames, sequela','Causes externes de morbidité et de mortalité','X76.XXXS'),
('Intentional self-harm by steam or hot vapors, initial encounter','Intentional self-harm by steam or hot vapors, initial encounter','Causes externes de morbidité et de mortalité','X77.0XXA'),
('Intentional self-harm by steam or hot vapors, subsequent encounter','Intentional self-harm by steam or hot vapors, subsequent encounter','Causes externes de morbidité et de mortalité','X77.0XXD'),
('Intentional self-harm by steam or hot vapors, sequela','Intentional self-harm by steam or hot vapors, sequela','Causes externes de morbidité et de mortalité','X77.0XXS'),
('Intentional self-harm by hot tap water, initial encounter','Intentional self-harm by hot tap water, initial encounter','Causes externes de morbidité et de mortalité','X77.1XXA'),
('Intentional self-harm by hot tap water, subsequent encounter','Intentional self-harm by hot tap water, subsequent encounter','Causes externes de morbidité et de mortalité','X77.1XXD'),
('Intentional self-harm by hot tap water, sequela','Intentional self-harm by hot tap water, sequela','Causes externes de morbidité et de mortalité','X77.1XXS'),
('Intentional self-harm by autre hot fluids, initial encounter','Intentional self-harm by other hot fluids, initial encounter','Causes externes de morbidité et de mortalité','X77.2XXA'),
('Intentional self-harm by autre hot fluids, subsequent encounter','Intentional self-harm by other hot fluids, subsequent encounter','Causes externes de morbidité et de mortalité','X77.2XXD'),
('Intentional self-harm by autre hot fluids, sequela','Intentional self-harm by other hot fluids, sequela','Causes externes de morbidité et de mortalité','X77.2XXS'),
('Intentional self-harm by hot household appliances, initial encounter','Intentional self-harm by hot household appliances, initial encounter','Causes externes de morbidité et de mortalité','X77.3XXA'),
('Intentional self-harm by hot household appliances, subsequent encounter','Intentional self-harm by hot household appliances, subsequent encounter','Causes externes de morbidité et de mortalité','X77.3XXD'),
('Intentional self-harm by hot household appliances, sequela','Intentional self-harm by hot household appliances, sequela','Causes externes de morbidité et de mortalité','X77.3XXS')
ON CONFLICT (nom_fr) DO NOTHING;
