-- icd10v2_batch_113.sql (80 rows)
INSERT INTO pathologies (nom_fr, nom_en, categorie, icd10_code)
VALUES
('Vertiginous syndromes in diseases classified elsewhere, left ear','Vertiginous syndromes in diseases classified elsewhere, left ear','Maladies de l''oreille et de l''apophyse mastoïde','H82.2'),
('Vertiginous syndromes in diseases classified elsewhere, bilateral','Vertiginous syndromes in diseases classified elsewhere, bilateral','Maladies de l''oreille et de l''apophyse mastoïde','H82.3'),
('Vertiginous syndromes in diseases classified elsewhere, non spécifié ear','Vertiginous syndromes in diseases classified elsewhere, unspecified ear','Maladies de l''oreille et de l''apophyse mastoïde','H82.9'),
('Labyrinthitis, right ear','Labyrinthitis, right ear','Maladies de l''oreille et de l''apophyse mastoïde','H83.01'),
('Labyrinthitis, left ear','Labyrinthitis, left ear','Maladies de l''oreille et de l''apophyse mastoïde','H83.02'),
('Labyrinthitis, bilateral','Labyrinthitis, bilateral','Maladies de l''oreille et de l''apophyse mastoïde','H83.03'),
('Labyrinthitis, non spécifié ear','Labyrinthitis, unspecified ear','Maladies de l''oreille et de l''apophyse mastoïde','H83.09'),
('Labyrinthine fistula, right ear','Labyrinthine fistula, right ear','Maladies de l''oreille et de l''apophyse mastoïde','H83.11'),
('Labyrinthine fistula, left ear','Labyrinthine fistula, left ear','Maladies de l''oreille et de l''apophyse mastoïde','H83.12'),
('Labyrinthine fistula, bilateral','Labyrinthine fistula, bilateral','Maladies de l''oreille et de l''apophyse mastoïde','H83.13'),
('Labyrinthine fistula, non spécifié ear','Labyrinthine fistula, unspecified ear','Maladies de l''oreille et de l''apophyse mastoïde','H83.19'),
('Labyrinthine dysfunction, right ear','Labyrinthine dysfunction, right ear','Maladies de l''oreille et de l''apophyse mastoïde','H83.2X1'),
('Labyrinthine dysfunction, left ear','Labyrinthine dysfunction, left ear','Maladies de l''oreille et de l''apophyse mastoïde','H83.2X2'),
('Labyrinthine dysfunction, bilateral','Labyrinthine dysfunction, bilateral','Maladies de l''oreille et de l''apophyse mastoïde','H83.2X3'),
('Labyrinthine dysfunction, non spécifié ear','Labyrinthine dysfunction, unspecified ear','Maladies de l''oreille et de l''apophyse mastoïde','H83.2X9'),
('Noise effects on right inner ear','Noise effects on right inner ear','Maladies de l''oreille et de l''apophyse mastoïde','H83.3X1'),
('Noise effects on left inner ear','Noise effects on left inner ear','Maladies de l''oreille et de l''apophyse mastoïde','H83.3X2'),
('Noise effects on inner ear, bilateral','Noise effects on inner ear, bilateral','Maladies de l''oreille et de l''apophyse mastoïde','H83.3X3'),
('Noise effects on inner ear, non spécifié ear','Noise effects on inner ear, unspecified ear','Maladies de l''oreille et de l''apophyse mastoïde','H83.3X9'),
('autre specified diseases of right inner ear','Other specified diseases of right inner ear','Maladies de l''oreille et de l''apophyse mastoïde','H83.8X1'),
('autre specified diseases of left inner ear','Other specified diseases of left inner ear','Maladies de l''oreille et de l''apophyse mastoïde','H83.8X2'),
('autre specified diseases of inner ear, bilateral','Other specified diseases of inner ear, bilateral','Maladies de l''oreille et de l''apophyse mastoïde','H83.8X3'),
('autre specified diseases of inner ear, non spécifié ear','Other specified diseases of inner ear, unspecified ear','Maladies de l''oreille et de l''apophyse mastoïde','H83.8X9'),
('non spécifié maladie of inner ear, non spécifié ear','Unspecified disease of inner ear, unspecified ear','Maladies de l''oreille et de l''apophyse mastoïde','H83.90'),
('non spécifié maladie of right inner ear','Unspecified disease of right inner ear','Maladies de l''oreille et de l''apophyse mastoïde','H83.91'),
('non spécifié maladie of left inner ear','Unspecified disease of left inner ear','Maladies de l''oreille et de l''apophyse mastoïde','H83.92'),
('non spécifié maladie of inner ear, bilateral','Unspecified disease of inner ear, bilateral','Maladies de l''oreille et de l''apophyse mastoïde','H83.93'),
('Conductive hearing loss, bilateral','Conductive hearing loss, bilateral','Maladies de l''oreille et de l''apophyse mastoïde','H90.0'),
('Conductive hearing loss, unilateral, right ear, with unrestricted hearing on the contralateral side','Conductive hearing loss, unilateral, right ear, with unrestricted hearing on the contralateral side','Maladies de l''oreille et de l''apophyse mastoïde','H90.11'),
('Conductive hearing loss, unilateral, left ear, with unrestricted hearing on the contralateral side','Conductive hearing loss, unilateral, left ear, with unrestricted hearing on the contralateral side','Maladies de l''oreille et de l''apophyse mastoïde','H90.12'),
('Conductive hearing loss, non spécifié','Conductive hearing loss, unspecified','Maladies de l''oreille et de l''apophyse mastoïde','H90.2'),
('Sensorineural hearing loss, bilateral','Sensorineural hearing loss, bilateral','Maladies de l''oreille et de l''apophyse mastoïde','H90.3'),
('Sensorineural hearing loss, unilateral, right ear, with unrestricted hearing on the contralateral side','Sensorineural hearing loss, unilateral, right ear, with unrestricted hearing on the contralateral side','Maladies de l''oreille et de l''apophyse mastoïde','H90.41'),
('Sensorineural hearing loss, unilateral, left ear, with unrestricted hearing on the contralateral side','Sensorineural hearing loss, unilateral, left ear, with unrestricted hearing on the contralateral side','Maladies de l''oreille et de l''apophyse mastoïde','H90.42'),
('non spécifié sensorineural hearing loss','Unspecified sensorineural hearing loss','Maladies de l''oreille et de l''apophyse mastoïde','H90.5'),
('Mixed conductive and sensorineural hearing loss, bilateral','Mixed conductive and sensorineural hearing loss, bilateral','Maladies de l''oreille et de l''apophyse mastoïde','H90.6'),
('Mixed conductive and sensorineural hearing loss, unilateral, right ear, with unrestricted hearing on the contralateral side','Mixed conductive and sensorineural hearing loss, unilateral, right ear, with unrestricted hearing on the contralateral side','Maladies de l''oreille et de l''apophyse mastoïde','H90.71'),
('Mixed conductive and sensorineural hearing loss, unilateral, left ear, with unrestricted hearing on the contralateral side','Mixed conductive and sensorineural hearing loss, unilateral, left ear, with unrestricted hearing on the contralateral side','Maladies de l''oreille et de l''apophyse mastoïde','H90.72'),
('Mixed conductive and sensorineural hearing loss, non spécifié','Mixed conductive and sensorineural hearing loss, unspecified','Maladies de l''oreille et de l''apophyse mastoïde','H90.8'),
('Conductive hearing loss, unilateral, right ear with restricted hearing on the contralateral side','Conductive hearing loss, unilateral, right ear with restricted hearing on the contralateral side','Maladies de l''oreille et de l''apophyse mastoïde','H90.A11'),
('Conductive hearing loss, unilateral, left ear with restricted hearing on the contralateral side','Conductive hearing loss, unilateral, left ear with restricted hearing on the contralateral side','Maladies de l''oreille et de l''apophyse mastoïde','H90.A12'),
('Sensorineural hearing loss, unilateral, right ear, with restricted hearing on the contralateral side','Sensorineural hearing loss, unilateral, right ear, with restricted hearing on the contralateral side','Maladies de l''oreille et de l''apophyse mastoïde','H90.A21'),
('Sensorineural hearing loss, unilateral, left ear, with restricted hearing on the contralateral side','Sensorineural hearing loss, unilateral, left ear, with restricted hearing on the contralateral side','Maladies de l''oreille et de l''apophyse mastoïde','H90.A22'),
('Mixed conductive and sensorineural hearing loss, unilateral, right ear with restricted hearing on the contralateral side','Mixed conductive and sensorineural hearing loss, unilateral, right ear with restricted hearing on the contralateral side','Maladies de l''oreille et de l''apophyse mastoïde','H90.A31'),
('Mixed conductive and sensorineural hearing loss, unilateral, left ear with restricted hearing on the contralateral side','Mixed conductive and sensorineural hearing loss, unilateral, left ear with restricted hearing on the contralateral side','Maladies de l''oreille et de l''apophyse mastoïde','H90.A32'),
('Ototoxic hearing loss, right ear','Ototoxic hearing loss, right ear','Maladies de l''oreille et de l''apophyse mastoïde','H91.01'),
('Ototoxic hearing loss, left ear','Ototoxic hearing loss, left ear','Maladies de l''oreille et de l''apophyse mastoïde','H91.02'),
('Ototoxic hearing loss, bilateral','Ototoxic hearing loss, bilateral','Maladies de l''oreille et de l''apophyse mastoïde','H91.03'),
('Ototoxic hearing loss, non spécifié ear','Ototoxic hearing loss, unspecified ear','Maladies de l''oreille et de l''apophyse mastoïde','H91.09'),
('Presbycusis, non spécifié ear','Presbycusis, unspecified ear','Maladies de l''oreille et de l''apophyse mastoïde','H91.10'),
('Presbycusis, right ear','Presbycusis, right ear','Maladies de l''oreille et de l''apophyse mastoïde','H91.11'),
('Presbycusis, left ear','Presbycusis, left ear','Maladies de l''oreille et de l''apophyse mastoïde','H91.12'),
('Presbycusis, bilateral','Presbycusis, bilateral','Maladies de l''oreille et de l''apophyse mastoïde','H91.13'),
('Sudden idiopathic hearing loss, non spécifié ear','Sudden idiopathic hearing loss, unspecified ear','Maladies de l''oreille et de l''apophyse mastoïde','H91.20'),
('Sudden idiopathic hearing loss, right ear','Sudden idiopathic hearing loss, right ear','Maladies de l''oreille et de l''apophyse mastoïde','H91.21'),
('Sudden idiopathic hearing loss, left ear','Sudden idiopathic hearing loss, left ear','Maladies de l''oreille et de l''apophyse mastoïde','H91.22'),
('Sudden idiopathic hearing loss, bilateral','Sudden idiopathic hearing loss, bilateral','Maladies de l''oreille et de l''apophyse mastoïde','H91.23'),
('Deaf nonspeaking, not elsewhere classified','Deaf nonspeaking, not elsewhere classified','Maladies de l''oreille et de l''apophyse mastoïde','H91.3'),
('autre specified hearing loss, right ear','Other specified hearing loss, right ear','Maladies de l''oreille et de l''apophyse mastoïde','H91.8X1'),
('autre specified hearing loss, left ear','Other specified hearing loss, left ear','Maladies de l''oreille et de l''apophyse mastoïde','H91.8X2'),
('autre specified hearing loss, bilateral','Other specified hearing loss, bilateral','Maladies de l''oreille et de l''apophyse mastoïde','H91.8X3'),
('autre specified hearing loss, non spécifié ear','Other specified hearing loss, unspecified ear','Maladies de l''oreille et de l''apophyse mastoïde','H91.8X9'),
('non spécifié hearing loss, non spécifié ear','Unspecified hearing loss, unspecified ear','Maladies de l''oreille et de l''apophyse mastoïde','H91.90'),
('non spécifié hearing loss, right ear','Unspecified hearing loss, right ear','Maladies de l''oreille et de l''apophyse mastoïde','H91.91'),
('non spécifié hearing loss, left ear','Unspecified hearing loss, left ear','Maladies de l''oreille et de l''apophyse mastoïde','H91.92'),
('non spécifié hearing loss, bilateral','Unspecified hearing loss, bilateral','Maladies de l''oreille et de l''apophyse mastoïde','H91.93'),
('Otalgia, right ear','Otalgia, right ear','Maladies de l''oreille et de l''apophyse mastoïde','H92.01'),
('Otalgia, left ear','Otalgia, left ear','Maladies de l''oreille et de l''apophyse mastoïde','H92.02'),
('Otalgia, bilateral','Otalgia, bilateral','Maladies de l''oreille et de l''apophyse mastoïde','H92.03'),
('Otalgia, non spécifié ear','Otalgia, unspecified ear','Maladies de l''oreille et de l''apophyse mastoïde','H92.09'),
('Otorrhea, non spécifié ear','Otorrhea, unspecified ear','Maladies de l''oreille et de l''apophyse mastoïde','H92.10'),
('Otorrhea, right ear','Otorrhea, right ear','Maladies de l''oreille et de l''apophyse mastoïde','H92.11'),
('Otorrhea, left ear','Otorrhea, left ear','Maladies de l''oreille et de l''apophyse mastoïde','H92.12'),
('Otorrhea, bilateral','Otorrhea, bilateral','Maladies de l''oreille et de l''apophyse mastoïde','H92.13'),
('Otorrhagia, non spécifié ear','Otorrhagia, unspecified ear','Maladies de l''oreille et de l''apophyse mastoïde','H92.20'),
('Otorrhagia, right ear','Otorrhagia, right ear','Maladies de l''oreille et de l''apophyse mastoïde','H92.21'),
('Otorrhagia, left ear','Otorrhagia, left ear','Maladies de l''oreille et de l''apophyse mastoïde','H92.22'),
('Otorrhagia, bilateral','Otorrhagia, bilateral','Maladies de l''oreille et de l''apophyse mastoïde','H92.23'),
('Transient ischemic deafness, right ear','Transient ischemic deafness, right ear','Maladies de l''oreille et de l''apophyse mastoïde','H93.011'),
('Transient ischemic deafness, left ear','Transient ischemic deafness, left ear','Maladies de l''oreille et de l''apophyse mastoïde','H93.012')
ON CONFLICT (nom_fr) DO NOTHING;
