-- icd10v2_batch_263.sql (80 rows)
INSERT INTO pathologies (nom_fr, nom_en, categorie, icd10_code)
VALUES
('autre abnormalities of breathing','Other abnormalities of breathing','Symptômes, signes et résultats anormaux','R06.89'),
('non spécifié abnormalities of breathing','Unspecified abnormalities of breathing','Symptômes, signes et résultats anormaux','R06.9'),
('Pain in throat','Pain in throat','Symptômes, signes et résultats anormaux','R07.0'),
('Chest pain on breathing','Chest pain on breathing','Symptômes, signes et résultats anormaux','R07.1'),
('Precordial pain','Precordial pain','Symptômes, signes et résultats anormaux','R07.2'),
('Pleurodynia','Pleurodynia','Symptômes, signes et résultats anormaux','R07.81'),
('Intercostal pain','Intercostal pain','Symptômes, signes et résultats anormaux','R07.82'),
('autre chest pain','Other chest pain','Symptômes, signes et résultats anormaux','R07.89'),
('Chest pain, non spécifié','Chest pain, unspecified','Symptômes, signes et résultats anormaux','R07.9'),
('Asphyxia','Asphyxia','Symptômes, signes et résultats anormaux','R09.01'),
('Hypoxemia','Hypoxemia','Symptômes, signes et résultats anormaux','R09.02'),
('Pleurisy','Pleurisy','Symptômes, signes et résultats anormaux','R09.1'),
('Respiratory arrest','Respiratory arrest','Symptômes, signes et résultats anormaux','R09.2'),
('Abnormal sputum','Abnormal sputum','Symptômes, signes et résultats anormaux','R09.3'),
('Nasal congestion','Nasal congestion','Symptômes, signes et résultats anormaux','R09.81'),
('Postnasal drip','Postnasal drip','Symptômes, signes et résultats anormaux','R09.82'),
('autre specified symptoms and signs involving the circulatory and respiratory systems','Other specified symptoms and signs involving the circulatory and respiratory systems','Symptômes, signes et résultats anormaux','R09.89'),
('Foreign body sensation, non spécifié','Foreign body sensation, unspecified','Symptômes, signes et résultats anormaux','R09.A0'),
('Foreign body sensation, nose','Foreign body sensation, nose','Symptômes, signes et résultats anormaux','R09.A1'),
('Foreign body sensation, throat','Foreign body sensation, throat','Symptômes, signes et résultats anormaux','R09.A2'),
('Foreign body sensation, autre site','Foreign body sensation, other site','Symptômes, signes et résultats anormaux','R09.A9'),
('aigu abdomen','Acute abdomen','Symptômes, signes et résultats anormaux','R10.0'),
('Upper abdominal pain, non spécifié','Upper abdominal pain, unspecified','Symptômes, signes et résultats anormaux','R10.10'),
('Right upper quadrant pain','Right upper quadrant pain','Symptômes, signes et résultats anormaux','R10.11'),
('Left upper quadrant pain','Left upper quadrant pain','Symptômes, signes et résultats anormaux','R10.12'),
('Epigastric pain','Epigastric pain','Symptômes, signes et résultats anormaux','R10.13'),
('Pelvic and perineal pain non spécifié side','Pelvic and perineal pain unspecified side','Symptômes, signes et résultats anormaux','R10.20'),
('Pelvic and perineal pain right side','Pelvic and perineal pain right side','Symptômes, signes et résultats anormaux','R10.21'),
('Pelvic and perineal pain left side','Pelvic and perineal pain left side','Symptômes, signes et résultats anormaux','R10.22'),
('Pelvic and perineal pain bilateral','Pelvic and perineal pain bilateral','Symptômes, signes et résultats anormaux','R10.23'),
('Suprapubic pain','Suprapubic pain','Symptômes, signes et résultats anormaux','R10.24'),
('Lower abdominal pain, non spécifié','Lower abdominal pain, unspecified','Symptômes, signes et résultats anormaux','R10.30'),
('Right lower quadrant pain','Right lower quadrant pain','Symptômes, signes et résultats anormaux','R10.31'),
('Left lower quadrant pain','Left lower quadrant pain','Symptômes, signes et résultats anormaux','R10.32'),
('Periumbilical pain','Periumbilical pain','Symptômes, signes et résultats anormaux','R10.33'),
('Right upper quadrant abdominal tenderness','Right upper quadrant abdominal tenderness','Symptômes, signes et résultats anormaux','R10.811'),
('Left upper quadrant abdominal tenderness','Left upper quadrant abdominal tenderness','Symptômes, signes et résultats anormaux','R10.812'),
('Right lower quadrant abdominal tenderness','Right lower quadrant abdominal tenderness','Symptômes, signes et résultats anormaux','R10.813'),
('Left lower quadrant abdominal tenderness','Left lower quadrant abdominal tenderness','Symptômes, signes et résultats anormaux','R10.814'),
('Periumbilic abdominal tenderness','Periumbilic abdominal tenderness','Symptômes, signes et résultats anormaux','R10.815'),
('Epigastric abdominal tenderness','Epigastric abdominal tenderness','Symptômes, signes et résultats anormaux','R10.816'),
('Generalized abdominal tenderness','Generalized abdominal tenderness','Symptômes, signes et résultats anormaux','R10.817'),
('Abdominal tenderness, non spécifié site','Abdominal tenderness, unspecified site','Symptômes, signes et résultats anormaux','R10.819'),
('Right upper quadrant rebound abdominal tenderness','Right upper quadrant rebound abdominal tenderness','Symptômes, signes et résultats anormaux','R10.821'),
('Left upper quadrant rebound abdominal tenderness','Left upper quadrant rebound abdominal tenderness','Symptômes, signes et résultats anormaux','R10.822'),
('Right lower quadrant rebound abdominal tenderness','Right lower quadrant rebound abdominal tenderness','Symptômes, signes et résultats anormaux','R10.823'),
('Left lower quadrant rebound abdominal tenderness','Left lower quadrant rebound abdominal tenderness','Symptômes, signes et résultats anormaux','R10.824'),
('Periumbilic rebound abdominal tenderness','Periumbilic rebound abdominal tenderness','Symptômes, signes et résultats anormaux','R10.825'),
('Epigastric rebound abdominal tenderness','Epigastric rebound abdominal tenderness','Symptômes, signes et résultats anormaux','R10.826'),
('Generalized rebound abdominal tenderness','Generalized rebound abdominal tenderness','Symptômes, signes et résultats anormaux','R10.827'),
('Rebound abdominal tenderness, non spécifié site','Rebound abdominal tenderness, unspecified site','Symptômes, signes et résultats anormaux','R10.829'),
('Colic','Colic','Symptômes, signes et résultats anormaux','R10.83'),
('Generalized abdominal pain','Generalized abdominal pain','Symptômes, signes et résultats anormaux','R10.84'),
('Abdominal pain of multiple sites','Abdominal pain of multiple sites','Symptômes, signes et résultats anormaux','R10.85'),
('Right flank tenderness','Right flank tenderness','Symptômes, signes et résultats anormaux','R10.8A1'),
('Left flank tenderness','Left flank tenderness','Symptômes, signes et résultats anormaux','R10.8A2'),
('Suprapubic tenderness','Suprapubic tenderness','Symptômes, signes et résultats anormaux','R10.8A3'),
('Flank tenderness, non spécifié','Flank tenderness, unspecified','Symptômes, signes et résultats anormaux','R10.8A9'),
('non spécifié abdominal pain','Unspecified abdominal pain','Symptômes, signes et résultats anormaux','R10.9'),
('Flank pain, non spécifié side','Flank pain, unspecified side','Symptômes, signes et résultats anormaux','R10.A0'),
('Flank pain, right side','Flank pain, right side','Symptômes, signes et résultats anormaux','R10.A1'),
('Flank pain, left side','Flank pain, left side','Symptômes, signes et résultats anormaux','R10.A2'),
('Flank pain, bilateral','Flank pain, bilateral','Symptômes, signes et résultats anormaux','R10.A3'),
('Nausea','Nausea','Symptômes, signes et résultats anormaux','R11.0'),
('Vomiting, non spécifié','Vomiting, unspecified','Symptômes, signes et résultats anormaux','R11.10'),
('Vomiting without nausea','Vomiting without nausea','Symptômes, signes et résultats anormaux','R11.11'),
('Projectile vomiting','Projectile vomiting','Symptômes, signes et résultats anormaux','R11.12'),
('Vomiting of fecal matter','Vomiting of fecal matter','Symptômes, signes et résultats anormaux','R11.13'),
('Bilious vomiting','Bilious vomiting','Symptômes, signes et résultats anormaux','R11.14'),
('Cyclical vomiting syndrome unrelated to migraine','Cyclical vomiting syndrome unrelated to migraine','Symptômes, signes et résultats anormaux','R11.15'),
('Cannabis hyperemesis syndrome','Cannabis hyperemesis syndrome','Symptômes, signes et résultats anormaux','R11.16'),
('Nausea with vomiting, non spécifié','Nausea with vomiting, unspecified','Symptômes, signes et résultats anormaux','R11.2'),
('Heartburn','Heartburn','Symptômes, signes et résultats anormaux','R12'),
('Aphagia','Aphagia','Symptômes, signes et résultats anormaux','R13.0'),
('Dysphagia, non spécifié','Dysphagia, unspecified','Symptômes, signes et résultats anormaux','R13.10'),
('Dysphagia, oral phase','Dysphagia, oral phase','Symptômes, signes et résultats anormaux','R13.11'),
('Dysphagia, oropharyngeal phase','Dysphagia, oropharyngeal phase','Symptômes, signes et résultats anormaux','R13.12'),
('Dysphagia, pharyngeal phase','Dysphagia, pharyngeal phase','Symptômes, signes et résultats anormaux','R13.13'),
('Dysphagia, pharyngoesophageal phase','Dysphagia, pharyngoesophageal phase','Symptômes, signes et résultats anormaux','R13.14'),
('autre dysphagia','Other dysphagia','Symptômes, signes et résultats anormaux','R13.19')
ON CONFLICT (nom_fr) DO NOTHING;
