-- icd10v2_batch_106.sql (80 rows)
INSERT INTO pathologies (nom_fr, nom_en, categorie, icd10_code)
VALUES
('Ocular pain, left eye','Ocular pain, left eye','Maladies de l''œil et de ses annexes','H57.12'),
('Ocular pain, bilateral','Ocular pain, bilateral','Maladies de l''œil et de ses annexes','H57.13'),
('Brow ptosis, right','Brow ptosis, right','Maladies de l''œil et de ses annexes','H57.811'),
('Brow ptosis, left','Brow ptosis, left','Maladies de l''œil et de ses annexes','H57.812'),
('Brow ptosis, bilateral','Brow ptosis, bilateral','Maladies de l''œil et de ses annexes','H57.813'),
('Brow ptosis, non spécifié','Brow ptosis, unspecified','Maladies de l''œil et de ses annexes','H57.819'),
('autre specified disorders of eye and adnexa','Other specified disorders of eye and adnexa','Maladies de l''œil et de ses annexes','H57.89'),
('Foreign body sensation, right eye','Foreign body sensation, right eye','Maladies de l''œil et de ses annexes','H57.8A1'),
('Foreign body sensation, left eye','Foreign body sensation, left eye','Maladies de l''œil et de ses annexes','H57.8A2'),
('Foreign body sensation, bilateral eyes','Foreign body sensation, bilateral eyes','Maladies de l''œil et de ses annexes','H57.8A3'),
('Foreign body sensation, non spécifié eye','Foreign body sensation, unspecified eye','Maladies de l''œil et de ses annexes','H57.8A9'),
('non spécifié trouble of eye and adnexa','Unspecified disorder of eye and adnexa','Maladies de l''œil et de ses annexes','H57.9'),
('Keratopathy (bullous aphakic) following cataract surgery, right eye','Keratopathy (bullous aphakic) following cataract surgery, right eye','Maladies de l''œil et de ses annexes','H59.011'),
('Keratopathy (bullous aphakic) following cataract surgery, left eye','Keratopathy (bullous aphakic) following cataract surgery, left eye','Maladies de l''œil et de ses annexes','H59.012'),
('Keratopathy (bullous aphakic) following cataract surgery, bilateral','Keratopathy (bullous aphakic) following cataract surgery, bilateral','Maladies de l''œil et de ses annexes','H59.013'),
('Keratopathy (bullous aphakic) following cataract surgery, non spécifié eye','Keratopathy (bullous aphakic) following cataract surgery, unspecified eye','Maladies de l''œil et de ses annexes','H59.019'),
('Cataract (lens) fragments in eye following cataract surgery, right eye','Cataract (lens) fragments in eye following cataract surgery, right eye','Maladies de l''œil et de ses annexes','H59.021'),
('Cataract (lens) fragments in eye following cataract surgery, left eye','Cataract (lens) fragments in eye following cataract surgery, left eye','Maladies de l''œil et de ses annexes','H59.022'),
('Cataract (lens) fragments in eye following cataract surgery, bilateral','Cataract (lens) fragments in eye following cataract surgery, bilateral','Maladies de l''œil et de ses annexes','H59.023'),
('Cataract (lens) fragments in eye following cataract surgery, non spécifié eye','Cataract (lens) fragments in eye following cataract surgery, unspecified eye','Maladies de l''œil et de ses annexes','H59.029'),
('Cystoid macular edema following cataract surgery, right eye','Cystoid macular edema following cataract surgery, right eye','Maladies de l''œil et de ses annexes','H59.031'),
('Cystoid macular edema following cataract surgery, left eye','Cystoid macular edema following cataract surgery, left eye','Maladies de l''œil et de ses annexes','H59.032'),
('Cystoid macular edema following cataract surgery, bilateral','Cystoid macular edema following cataract surgery, bilateral','Maladies de l''œil et de ses annexes','H59.033'),
('Cystoid macular edema following cataract surgery, non spécifié eye','Cystoid macular edema following cataract surgery, unspecified eye','Maladies de l''œil et de ses annexes','H59.039'),
('autre disorders of the right eye following cataract surgery','Other disorders of the right eye following cataract surgery','Maladies de l''œil et de ses annexes','H59.091'),
('autre disorders of the left eye following cataract surgery','Other disorders of the left eye following cataract surgery','Maladies de l''œil et de ses annexes','H59.092'),
('autre disorders of the eye following cataract surgery, bilateral','Other disorders of the eye following cataract surgery, bilateral','Maladies de l''œil et de ses annexes','H59.093'),
('autre disorders of non spécifié eye following cataract surgery','Other disorders of unspecified eye following cataract surgery','Maladies de l''œil et de ses annexes','H59.099'),
('Intraoperative hémorragie and hematoma of right eye and adnexa complicating an ophthalmic procedure','Intraoperative hemorrhage and hematoma of right eye and adnexa complicating an ophthalmic procedure','Maladies de l''œil et de ses annexes','H59.111'),
('Intraoperative hémorragie and hematoma of left eye and adnexa complicating an ophthalmic procedure','Intraoperative hemorrhage and hematoma of left eye and adnexa complicating an ophthalmic procedure','Maladies de l''œil et de ses annexes','H59.112'),
('Intraoperative hémorragie and hematoma of eye and adnexa complicating an ophthalmic procedure, bilateral','Intraoperative hemorrhage and hematoma of eye and adnexa complicating an ophthalmic procedure, bilateral','Maladies de l''œil et de ses annexes','H59.113'),
('Intraoperative hémorragie and hematoma of non spécifié eye and adnexa complicating an ophthalmic procedure','Intraoperative hemorrhage and hematoma of unspecified eye and adnexa complicating an ophthalmic procedure','Maladies de l''œil et de ses annexes','H59.119'),
('Intraoperative hémorragie and hematoma of right eye and adnexa complicating autre procedure','Intraoperative hemorrhage and hematoma of right eye and adnexa complicating other procedure','Maladies de l''œil et de ses annexes','H59.121'),
('Intraoperative hémorragie and hematoma of left eye and adnexa complicating autre procedure','Intraoperative hemorrhage and hematoma of left eye and adnexa complicating other procedure','Maladies de l''œil et de ses annexes','H59.122'),
('Intraoperative hémorragie and hematoma of eye and adnexa complicating autre procedure, bilateral','Intraoperative hemorrhage and hematoma of eye and adnexa complicating other procedure, bilateral','Maladies de l''œil et de ses annexes','H59.123'),
('Intraoperative hémorragie and hematoma of non spécifié eye and adnexa complicating autre procedure','Intraoperative hemorrhage and hematoma of unspecified eye and adnexa complicating other procedure','Maladies de l''œil et de ses annexes','H59.129'),
('Accidental puncture and laceration of right eye and adnexa during an ophthalmic procedure','Accidental puncture and laceration of right eye and adnexa during an ophthalmic procedure','Maladies de l''œil et de ses annexes','H59.211'),
('Accidental puncture and laceration of left eye and adnexa during an ophthalmic procedure','Accidental puncture and laceration of left eye and adnexa during an ophthalmic procedure','Maladies de l''œil et de ses annexes','H59.212'),
('Accidental puncture and laceration of eye and adnexa during an ophthalmic procedure, bilateral','Accidental puncture and laceration of eye and adnexa during an ophthalmic procedure, bilateral','Maladies de l''œil et de ses annexes','H59.213'),
('Accidental puncture and laceration of non spécifié eye and adnexa during an ophthalmic procedure','Accidental puncture and laceration of unspecified eye and adnexa during an ophthalmic procedure','Maladies de l''œil et de ses annexes','H59.219'),
('Accidental puncture and laceration of right eye and adnexa during autre procedure','Accidental puncture and laceration of right eye and adnexa during other procedure','Maladies de l''œil et de ses annexes','H59.221'),
('Accidental puncture and laceration of left eye and adnexa during autre procedure','Accidental puncture and laceration of left eye and adnexa during other procedure','Maladies de l''œil et de ses annexes','H59.222'),
('Accidental puncture and laceration of eye and adnexa during autre procedure, bilateral','Accidental puncture and laceration of eye and adnexa during other procedure, bilateral','Maladies de l''œil et de ses annexes','H59.223'),
('Accidental puncture and laceration of non spécifié eye and adnexa during autre procedure','Accidental puncture and laceration of unspecified eye and adnexa during other procedure','Maladies de l''œil et de ses annexes','H59.229'),
('Postprocedural hémorragie of right eye and adnexa following an ophthalmic procedure','Postprocedural hemorrhage of right eye and adnexa following an ophthalmic procedure','Maladies de l''œil et de ses annexes','H59.311'),
('Postprocedural hémorragie of left eye and adnexa following an ophthalmic procedure','Postprocedural hemorrhage of left eye and adnexa following an ophthalmic procedure','Maladies de l''œil et de ses annexes','H59.312'),
('Postprocedural hémorragie of eye and adnexa following an ophthalmic procedure, bilateral','Postprocedural hemorrhage of eye and adnexa following an ophthalmic procedure, bilateral','Maladies de l''œil et de ses annexes','H59.313'),
('Postprocedural hémorragie of non spécifié eye and adnexa following an ophthalmic procedure','Postprocedural hemorrhage of unspecified eye and adnexa following an ophthalmic procedure','Maladies de l''œil et de ses annexes','H59.319'),
('Postprocedural hémorragie of right eye and adnexa following autre procedure','Postprocedural hemorrhage of right eye and adnexa following other procedure','Maladies de l''œil et de ses annexes','H59.321'),
('Postprocedural hémorragie of left eye and adnexa following autre procedure','Postprocedural hemorrhage of left eye and adnexa following other procedure','Maladies de l''œil et de ses annexes','H59.322'),
('Postprocedural hémorragie of eye and adnexa following autre procedure, bilateral','Postprocedural hemorrhage of eye and adnexa following other procedure, bilateral','Maladies de l''œil et de ses annexes','H59.323'),
('Postprocedural hémorragie of non spécifié eye and adnexa following autre procedure','Postprocedural hemorrhage of unspecified eye and adnexa following other procedure','Maladies de l''œil et de ses annexes','H59.329'),
('Postprocedural hematoma of right eye and adnexa following an ophthalmic procedure','Postprocedural hematoma of right eye and adnexa following an ophthalmic procedure','Maladies de l''œil et de ses annexes','H59.331'),
('Postprocedural hematoma of left eye and adnexa following an ophthalmic procedure','Postprocedural hematoma of left eye and adnexa following an ophthalmic procedure','Maladies de l''œil et de ses annexes','H59.332'),
('Postprocedural hematoma of eye and adnexa following an ophthalmic procedure, bilateral','Postprocedural hematoma of eye and adnexa following an ophthalmic procedure, bilateral','Maladies de l''œil et de ses annexes','H59.333'),
('Postprocedural hematoma of non spécifié eye and adnexa following an ophthalmic procedure','Postprocedural hematoma of unspecified eye and adnexa following an ophthalmic procedure','Maladies de l''œil et de ses annexes','H59.339'),
('Postprocedural hematoma of right eye and adnexa following autre procedure','Postprocedural hematoma of right eye and adnexa following other procedure','Maladies de l''œil et de ses annexes','H59.341'),
('Postprocedural hematoma of left eye and adnexa following autre procedure','Postprocedural hematoma of left eye and adnexa following other procedure','Maladies de l''œil et de ses annexes','H59.342'),
('Postprocedural hematoma of eye and adnexa following autre procedure, bilateral','Postprocedural hematoma of eye and adnexa following other procedure, bilateral','Maladies de l''œil et de ses annexes','H59.343'),
('Postprocedural hematoma of non spécifié eye and adnexa following autre procedure','Postprocedural hematoma of unspecified eye and adnexa following other procedure','Maladies de l''œil et de ses annexes','H59.349'),
('Postprocedural seroma of right eye and adnexa following an ophthalmic procedure','Postprocedural seroma of right eye and adnexa following an ophthalmic procedure','Maladies de l''œil et de ses annexes','H59.351'),
('Postprocedural seroma of left eye and adnexa following an ophthalmic procedure','Postprocedural seroma of left eye and adnexa following an ophthalmic procedure','Maladies de l''œil et de ses annexes','H59.352'),
('Postprocedural seroma of eye and adnexa following an ophthalmic procedure, bilateral','Postprocedural seroma of eye and adnexa following an ophthalmic procedure, bilateral','Maladies de l''œil et de ses annexes','H59.353'),
('Postprocedural seroma of non spécifié eye and adnexa following an ophthalmic procedure','Postprocedural seroma of unspecified eye and adnexa following an ophthalmic procedure','Maladies de l''œil et de ses annexes','H59.359'),
('Postprocedural seroma of right eye and adnexa following autre procedure','Postprocedural seroma of right eye and adnexa following other procedure','Maladies de l''œil et de ses annexes','H59.361'),
('Postprocedural seroma of left eye and adnexa following autre procedure','Postprocedural seroma of left eye and adnexa following other procedure','Maladies de l''œil et de ses annexes','H59.362'),
('Postprocedural seroma of eye and adnexa following autre procedure, bilateral','Postprocedural seroma of eye and adnexa following other procedure, bilateral','Maladies de l''œil et de ses annexes','H59.363'),
('Postprocedural seroma of non spécifié eye and adnexa following autre procedure','Postprocedural seroma of unspecified eye and adnexa following other procedure','Maladies de l''œil et de ses annexes','H59.369'),
('inflammation (infection) of postprocedural bleb, non spécifié','Inflammation (infection) of postprocedural bleb, unspecified','Maladies de l''œil et de ses annexes','H59.40'),
('inflammation (infection) of postprocedural bleb, stage 1','Inflammation (infection) of postprocedural bleb, stage 1','Maladies de l''œil et de ses annexes','H59.41'),
('inflammation (infection) of postprocedural bleb, stage 2','Inflammation (infection) of postprocedural bleb, stage 2','Maladies de l''œil et de ses annexes','H59.42'),
('inflammation (infection) of postprocedural bleb, stage 3','Inflammation (infection) of postprocedural bleb, stage 3','Maladies de l''œil et de ses annexes','H59.43'),
('Chorioretinal scars after surgery for detachment, right eye','Chorioretinal scars after surgery for detachment, right eye','Maladies de l''œil et de ses annexes','H59.811'),
('Chorioretinal scars after surgery for detachment, left eye','Chorioretinal scars after surgery for detachment, left eye','Maladies de l''œil et de ses annexes','H59.812'),
('Chorioretinal scars after surgery for detachment, bilateral','Chorioretinal scars after surgery for detachment, bilateral','Maladies de l''œil et de ses annexes','H59.813'),
('Chorioretinal scars after surgery for detachment, non spécifié eye','Chorioretinal scars after surgery for detachment, unspecified eye','Maladies de l''œil et de ses annexes','H59.819'),
('autre intraoperative complications of eye and adnexa, not elsewhere classified','Other intraoperative complications of eye and adnexa, not elsewhere classified','Maladies de l''œil et de ses annexes','H59.88'),
('autre postprocedural complications and disorders of eye and adnexa, not elsewhere classified','Other postprocedural complications and disorders of eye and adnexa, not elsewhere classified','Maladies de l''œil et de ses annexes','H59.89'),
('Abscess of external ear, non spécifié ear','Abscess of external ear, unspecified ear','Maladies de l''oreille et de l''apophyse mastoïde','H60.00'),
('Abscess of right external ear','Abscess of right external ear','Maladies de l''oreille et de l''apophyse mastoïde','H60.01')
ON CONFLICT (nom_fr) DO NOTHING;
