-- icd10v2_batch_351.sql (80 rows)
INSERT INTO pathologies (nom_fr, nom_en, categorie, icd10_code)
VALUES
('Intoxication par chloramphenicol group, intentional self-harm, sequela','Poisoning by chloramphenicol group, intentional self-harm, sequela','Traumatismes, empoisonnements et autres causes externes','T36.2X2S'),
('Intoxication par chloramphenicol group, assault, initial encounter','Poisoning by chloramphenicol group, assault, initial encounter','Traumatismes, empoisonnements et autres causes externes','T36.2X3A'),
('Intoxication par chloramphenicol group, assault, subsequent encounter','Poisoning by chloramphenicol group, assault, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T36.2X3D'),
('Intoxication par chloramphenicol group, assault, sequela','Poisoning by chloramphenicol group, assault, sequela','Traumatismes, empoisonnements et autres causes externes','T36.2X3S'),
('Intoxication par chloramphenicol group, undetermined, initial encounter','Poisoning by chloramphenicol group, undetermined, initial encounter','Traumatismes, empoisonnements et autres causes externes','T36.2X4A'),
('Intoxication par chloramphenicol group, undetermined, subsequent encounter','Poisoning by chloramphenicol group, undetermined, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T36.2X4D'),
('Intoxication par chloramphenicol group, undetermined, sequela','Poisoning by chloramphenicol group, undetermined, sequela','Traumatismes, empoisonnements et autres causes externes','T36.2X4S'),
('Effet indésirable de chloramphenicol group, initial encounter','Adverse effect of chloramphenicol group, initial encounter','Traumatismes, empoisonnements et autres causes externes','T36.2X5A'),
('Effet indésirable de chloramphenicol group, subsequent encounter','Adverse effect of chloramphenicol group, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T36.2X5D'),
('Effet indésirable de chloramphenicol group, sequela','Adverse effect of chloramphenicol group, sequela','Traumatismes, empoisonnements et autres causes externes','T36.2X5S'),
('Underdosing of chloramphenicol group, initial encounter','Underdosing of chloramphenicol group, initial encounter','Traumatismes, empoisonnements et autres causes externes','T36.2X6A'),
('Underdosing of chloramphenicol group, subsequent encounter','Underdosing of chloramphenicol group, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T36.2X6D'),
('Underdosing of chloramphenicol group, sequela','Underdosing of chloramphenicol group, sequela','Traumatismes, empoisonnements et autres causes externes','T36.2X6S'),
('Intoxication par macrolides, accidental (unintentional), initial encounter','Poisoning by macrolides, accidental (unintentional), initial encounter','Traumatismes, empoisonnements et autres causes externes','T36.3X1A'),
('Intoxication par macrolides, accidental (unintentional), subsequent encounter','Poisoning by macrolides, accidental (unintentional), subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T36.3X1D'),
('Intoxication par macrolides, accidental (unintentional), sequela','Poisoning by macrolides, accidental (unintentional), sequela','Traumatismes, empoisonnements et autres causes externes','T36.3X1S'),
('Intoxication par macrolides, intentional self-harm, initial encounter','Poisoning by macrolides, intentional self-harm, initial encounter','Traumatismes, empoisonnements et autres causes externes','T36.3X2A'),
('Intoxication par macrolides, intentional self-harm, subsequent encounter','Poisoning by macrolides, intentional self-harm, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T36.3X2D'),
('Intoxication par macrolides, intentional self-harm, sequela','Poisoning by macrolides, intentional self-harm, sequela','Traumatismes, empoisonnements et autres causes externes','T36.3X2S'),
('Intoxication par macrolides, assault, initial encounter','Poisoning by macrolides, assault, initial encounter','Traumatismes, empoisonnements et autres causes externes','T36.3X3A'),
('Intoxication par macrolides, assault, subsequent encounter','Poisoning by macrolides, assault, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T36.3X3D'),
('Intoxication par macrolides, assault, sequela','Poisoning by macrolides, assault, sequela','Traumatismes, empoisonnements et autres causes externes','T36.3X3S'),
('Intoxication par macrolides, undetermined, initial encounter','Poisoning by macrolides, undetermined, initial encounter','Traumatismes, empoisonnements et autres causes externes','T36.3X4A'),
('Intoxication par macrolides, undetermined, subsequent encounter','Poisoning by macrolides, undetermined, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T36.3X4D'),
('Intoxication par macrolides, undetermined, sequela','Poisoning by macrolides, undetermined, sequela','Traumatismes, empoisonnements et autres causes externes','T36.3X4S'),
('Effet indésirable de macrolides, initial encounter','Adverse effect of macrolides, initial encounter','Traumatismes, empoisonnements et autres causes externes','T36.3X5A'),
('Effet indésirable de macrolides, subsequent encounter','Adverse effect of macrolides, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T36.3X5D'),
('Effet indésirable de macrolides, sequela','Adverse effect of macrolides, sequela','Traumatismes, empoisonnements et autres causes externes','T36.3X5S'),
('Underdosing of macrolides, initial encounter','Underdosing of macrolides, initial encounter','Traumatismes, empoisonnements et autres causes externes','T36.3X6A'),
('Underdosing of macrolides, subsequent encounter','Underdosing of macrolides, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T36.3X6D'),
('Underdosing of macrolides, sequela','Underdosing of macrolides, sequela','Traumatismes, empoisonnements et autres causes externes','T36.3X6S'),
('Intoxication par tetracyclines, accidental (unintentional), initial encounter','Poisoning by tetracyclines, accidental (unintentional), initial encounter','Traumatismes, empoisonnements et autres causes externes','T36.4X1A'),
('Intoxication par tetracyclines, accidental (unintentional), subsequent encounter','Poisoning by tetracyclines, accidental (unintentional), subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T36.4X1D'),
('Intoxication par tetracyclines, accidental (unintentional), sequela','Poisoning by tetracyclines, accidental (unintentional), sequela','Traumatismes, empoisonnements et autres causes externes','T36.4X1S'),
('Intoxication par tetracyclines, intentional self-harm, initial encounter','Poisoning by tetracyclines, intentional self-harm, initial encounter','Traumatismes, empoisonnements et autres causes externes','T36.4X2A'),
('Intoxication par tetracyclines, intentional self-harm, subsequent encounter','Poisoning by tetracyclines, intentional self-harm, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T36.4X2D'),
('Intoxication par tetracyclines, intentional self-harm, sequela','Poisoning by tetracyclines, intentional self-harm, sequela','Traumatismes, empoisonnements et autres causes externes','T36.4X2S'),
('Intoxication par tetracyclines, assault, initial encounter','Poisoning by tetracyclines, assault, initial encounter','Traumatismes, empoisonnements et autres causes externes','T36.4X3A'),
('Intoxication par tetracyclines, assault, subsequent encounter','Poisoning by tetracyclines, assault, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T36.4X3D'),
('Intoxication par tetracyclines, assault, sequela','Poisoning by tetracyclines, assault, sequela','Traumatismes, empoisonnements et autres causes externes','T36.4X3S'),
('Intoxication par tetracyclines, undetermined, initial encounter','Poisoning by tetracyclines, undetermined, initial encounter','Traumatismes, empoisonnements et autres causes externes','T36.4X4A'),
('Intoxication par tetracyclines, undetermined, subsequent encounter','Poisoning by tetracyclines, undetermined, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T36.4X4D'),
('Intoxication par tetracyclines, undetermined, sequela','Poisoning by tetracyclines, undetermined, sequela','Traumatismes, empoisonnements et autres causes externes','T36.4X4S'),
('Effet indésirable de tetracyclines, initial encounter','Adverse effect of tetracyclines, initial encounter','Traumatismes, empoisonnements et autres causes externes','T36.4X5A'),
('Effet indésirable de tetracyclines, subsequent encounter','Adverse effect of tetracyclines, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T36.4X5D'),
('Effet indésirable de tetracyclines, sequela','Adverse effect of tetracyclines, sequela','Traumatismes, empoisonnements et autres causes externes','T36.4X5S'),
('Underdosing of tetracyclines, initial encounter','Underdosing of tetracyclines, initial encounter','Traumatismes, empoisonnements et autres causes externes','T36.4X6A'),
('Underdosing of tetracyclines, subsequent encounter','Underdosing of tetracyclines, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T36.4X6D'),
('Underdosing of tetracyclines, sequela','Underdosing of tetracyclines, sequela','Traumatismes, empoisonnements et autres causes externes','T36.4X6S'),
('Intoxication par aminoglycosides, accidental (unintentional), initial encounter','Poisoning by aminoglycosides, accidental (unintentional), initial encounter','Traumatismes, empoisonnements et autres causes externes','T36.5X1A'),
('Intoxication par aminoglycosides, accidental (unintentional), subsequent encounter','Poisoning by aminoglycosides, accidental (unintentional), subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T36.5X1D'),
('Intoxication par aminoglycosides, accidental (unintentional), sequela','Poisoning by aminoglycosides, accidental (unintentional), sequela','Traumatismes, empoisonnements et autres causes externes','T36.5X1S'),
('Intoxication par aminoglycosides, intentional self-harm, initial encounter','Poisoning by aminoglycosides, intentional self-harm, initial encounter','Traumatismes, empoisonnements et autres causes externes','T36.5X2A'),
('Intoxication par aminoglycosides, intentional self-harm, subsequent encounter','Poisoning by aminoglycosides, intentional self-harm, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T36.5X2D'),
('Intoxication par aminoglycosides, intentional self-harm, sequela','Poisoning by aminoglycosides, intentional self-harm, sequela','Traumatismes, empoisonnements et autres causes externes','T36.5X2S'),
('Intoxication par aminoglycosides, assault, initial encounter','Poisoning by aminoglycosides, assault, initial encounter','Traumatismes, empoisonnements et autres causes externes','T36.5X3A'),
('Intoxication par aminoglycosides, assault, subsequent encounter','Poisoning by aminoglycosides, assault, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T36.5X3D'),
('Intoxication par aminoglycosides, assault, sequela','Poisoning by aminoglycosides, assault, sequela','Traumatismes, empoisonnements et autres causes externes','T36.5X3S'),
('Intoxication par aminoglycosides, undetermined, initial encounter','Poisoning by aminoglycosides, undetermined, initial encounter','Traumatismes, empoisonnements et autres causes externes','T36.5X4A'),
('Intoxication par aminoglycosides, undetermined, subsequent encounter','Poisoning by aminoglycosides, undetermined, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T36.5X4D'),
('Intoxication par aminoglycosides, undetermined, sequela','Poisoning by aminoglycosides, undetermined, sequela','Traumatismes, empoisonnements et autres causes externes','T36.5X4S'),
('Effet indésirable de aminoglycosides, initial encounter','Adverse effect of aminoglycosides, initial encounter','Traumatismes, empoisonnements et autres causes externes','T36.5X5A'),
('Effet indésirable de aminoglycosides, subsequent encounter','Adverse effect of aminoglycosides, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T36.5X5D'),
('Effet indésirable de aminoglycosides, sequela','Adverse effect of aminoglycosides, sequela','Traumatismes, empoisonnements et autres causes externes','T36.5X5S'),
('Underdosing of aminoglycosides, initial encounter','Underdosing of aminoglycosides, initial encounter','Traumatismes, empoisonnements et autres causes externes','T36.5X6A'),
('Underdosing of aminoglycosides, subsequent encounter','Underdosing of aminoglycosides, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T36.5X6D'),
('Underdosing of aminoglycosides, sequela','Underdosing of aminoglycosides, sequela','Traumatismes, empoisonnements et autres causes externes','T36.5X6S'),
('Intoxication par rifampicins, accidental (unintentional), initial encounter','Poisoning by rifampicins, accidental (unintentional), initial encounter','Traumatismes, empoisonnements et autres causes externes','T36.6X1A'),
('Intoxication par rifampicins, accidental (unintentional), subsequent encounter','Poisoning by rifampicins, accidental (unintentional), subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T36.6X1D'),
('Intoxication par rifampicins, accidental (unintentional), sequela','Poisoning by rifampicins, accidental (unintentional), sequela','Traumatismes, empoisonnements et autres causes externes','T36.6X1S'),
('Intoxication par rifampicins, intentional self-harm, initial encounter','Poisoning by rifampicins, intentional self-harm, initial encounter','Traumatismes, empoisonnements et autres causes externes','T36.6X2A'),
('Intoxication par rifampicins, intentional self-harm, subsequent encounter','Poisoning by rifampicins, intentional self-harm, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T36.6X2D'),
('Intoxication par rifampicins, intentional self-harm, sequela','Poisoning by rifampicins, intentional self-harm, sequela','Traumatismes, empoisonnements et autres causes externes','T36.6X2S'),
('Intoxication par rifampicins, assault, initial encounter','Poisoning by rifampicins, assault, initial encounter','Traumatismes, empoisonnements et autres causes externes','T36.6X3A'),
('Intoxication par rifampicins, assault, subsequent encounter','Poisoning by rifampicins, assault, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T36.6X3D'),
('Intoxication par rifampicins, assault, sequela','Poisoning by rifampicins, assault, sequela','Traumatismes, empoisonnements et autres causes externes','T36.6X3S'),
('Intoxication par rifampicins, undetermined, initial encounter','Poisoning by rifampicins, undetermined, initial encounter','Traumatismes, empoisonnements et autres causes externes','T36.6X4A'),
('Intoxication par rifampicins, undetermined, subsequent encounter','Poisoning by rifampicins, undetermined, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T36.6X4D'),
('Intoxication par rifampicins, undetermined, sequela','Poisoning by rifampicins, undetermined, sequela','Traumatismes, empoisonnements et autres causes externes','T36.6X4S'),
('Effet indésirable de rifampicins, initial encounter','Adverse effect of rifampicins, initial encounter','Traumatismes, empoisonnements et autres causes externes','T36.6X5A')
ON CONFLICT (nom_fr) DO NOTHING;
