-- icd10v2_batch_076.sql (80 rows)
INSERT INTO pathologies (nom_fr, nom_en, categorie, icd10_code)
VALUES
('Eczematous dermatitis of left eye, non spécifié eyelid','Eczematous dermatitis of left eye, unspecified eyelid','Maladies de l''œil et de ses annexes','H01.136'),
('Eczematous dermatitis of non spécifié eye, non spécifié eyelid','Eczematous dermatitis of unspecified eye, unspecified eyelid','Maladies de l''œil et de ses annexes','H01.139'),
('Xeroderma of right upper eyelid','Xeroderma of right upper eyelid','Maladies de l''œil et de ses annexes','H01.141'),
('Xeroderma of right lower eyelid','Xeroderma of right lower eyelid','Maladies de l''œil et de ses annexes','H01.142'),
('Xeroderma of right eye, non spécifié eyelid','Xeroderma of right eye, unspecified eyelid','Maladies de l''œil et de ses annexes','H01.143'),
('Xeroderma of left upper eyelid','Xeroderma of left upper eyelid','Maladies de l''œil et de ses annexes','H01.144'),
('Xeroderma of left lower eyelid','Xeroderma of left lower eyelid','Maladies de l''œil et de ses annexes','H01.145'),
('Xeroderma of left eye, non spécifié eyelid','Xeroderma of left eye, unspecified eyelid','Maladies de l''œil et de ses annexes','H01.146'),
('Xeroderma of non spécifié eye, non spécifié eyelid','Xeroderma of unspecified eye, unspecified eyelid','Maladies de l''œil et de ses annexes','H01.149'),
('autre specified inflammation of right upper eyelid','Other specified inflammation of right upper eyelid','Maladies de l''œil et de ses annexes','H01.81'),
('autre specified inflammation of right lower eyelid','Other specified inflammation of right lower eyelid','Maladies de l''œil et de ses annexes','H01.82'),
('autre specified inflammation of right eye, non spécifié eyelid','Other specified inflammation of right eye, unspecified eyelid','Maladies de l''œil et de ses annexes','H01.83'),
('autre specified inflammation of left upper eyelid','Other specified inflammation of left upper eyelid','Maladies de l''œil et de ses annexes','H01.84'),
('autre specified inflammation of left lower eyelid','Other specified inflammation of left lower eyelid','Maladies de l''œil et de ses annexes','H01.85'),
('autre specified inflammation of left eye, non spécifié eyelid','Other specified inflammation of left eye, unspecified eyelid','Maladies de l''œil et de ses annexes','H01.86'),
('autre specified inflammation of non spécifié eye, non spécifié eyelid','Other specified inflammation of unspecified eye, unspecified eyelid','Maladies de l''œil et de ses annexes','H01.89'),
('autre specified inflammation of right eye, upper and lower eyelids','Other specified inflammation of right eye, upper and lower eyelids','Maladies de l''œil et de ses annexes','H01.8A'),
('autre specified inflammation of left eye, upper and lower eyelids','Other specified inflammation of left eye, upper and lower eyelids','Maladies de l''œil et de ses annexes','H01.8B'),
('non spécifié inflammation of eyelid','Unspecified inflammation of eyelid','Maladies de l''œil et de ses annexes','H01.9'),
('non spécifié entropion of right upper eyelid','Unspecified entropion of right upper eyelid','Maladies de l''œil et de ses annexes','H02.001'),
('non spécifié entropion of right lower eyelid','Unspecified entropion of right lower eyelid','Maladies de l''œil et de ses annexes','H02.002'),
('non spécifié entropion of right eye, non spécifié eyelid','Unspecified entropion of right eye, unspecified eyelid','Maladies de l''œil et de ses annexes','H02.003'),
('non spécifié entropion of left upper eyelid','Unspecified entropion of left upper eyelid','Maladies de l''œil et de ses annexes','H02.004'),
('non spécifié entropion of left lower eyelid','Unspecified entropion of left lower eyelid','Maladies de l''œil et de ses annexes','H02.005'),
('non spécifié entropion of left eye, non spécifié eyelid','Unspecified entropion of left eye, unspecified eyelid','Maladies de l''œil et de ses annexes','H02.006'),
('non spécifié entropion of non spécifié eye, non spécifié eyelid','Unspecified entropion of unspecified eye, unspecified eyelid','Maladies de l''œil et de ses annexes','H02.009'),
('Cicatricial entropion of right upper eyelid','Cicatricial entropion of right upper eyelid','Maladies de l''œil et de ses annexes','H02.011'),
('Cicatricial entropion of right lower eyelid','Cicatricial entropion of right lower eyelid','Maladies de l''œil et de ses annexes','H02.012'),
('Cicatricial entropion of right eye, non spécifié eyelid','Cicatricial entropion of right eye, unspecified eyelid','Maladies de l''œil et de ses annexes','H02.013'),
('Cicatricial entropion of left upper eyelid','Cicatricial entropion of left upper eyelid','Maladies de l''œil et de ses annexes','H02.014'),
('Cicatricial entropion of left lower eyelid','Cicatricial entropion of left lower eyelid','Maladies de l''œil et de ses annexes','H02.015'),
('Cicatricial entropion of left eye, non spécifié eyelid','Cicatricial entropion of left eye, unspecified eyelid','Maladies de l''œil et de ses annexes','H02.016'),
('Cicatricial entropion of non spécifié eye, non spécifié eyelid','Cicatricial entropion of unspecified eye, unspecified eyelid','Maladies de l''œil et de ses annexes','H02.019'),
('Mechanical entropion of right upper eyelid','Mechanical entropion of right upper eyelid','Maladies de l''œil et de ses annexes','H02.021'),
('Mechanical entropion of right lower eyelid','Mechanical entropion of right lower eyelid','Maladies de l''œil et de ses annexes','H02.022'),
('Mechanical entropion of right eye, non spécifié eyelid','Mechanical entropion of right eye, unspecified eyelid','Maladies de l''œil et de ses annexes','H02.023'),
('Mechanical entropion of left upper eyelid','Mechanical entropion of left upper eyelid','Maladies de l''œil et de ses annexes','H02.024'),
('Mechanical entropion of left lower eyelid','Mechanical entropion of left lower eyelid','Maladies de l''œil et de ses annexes','H02.025'),
('Mechanical entropion of left eye, non spécifié eyelid','Mechanical entropion of left eye, unspecified eyelid','Maladies de l''œil et de ses annexes','H02.026'),
('Mechanical entropion of non spécifié eye, non spécifié eyelid','Mechanical entropion of unspecified eye, unspecified eyelid','Maladies de l''œil et de ses annexes','H02.029'),
('Senile entropion of right upper eyelid','Senile entropion of right upper eyelid','Maladies de l''œil et de ses annexes','H02.031'),
('Senile entropion of right lower eyelid','Senile entropion of right lower eyelid','Maladies de l''œil et de ses annexes','H02.032'),
('Senile entropion of right eye, non spécifié eyelid','Senile entropion of right eye, unspecified eyelid','Maladies de l''œil et de ses annexes','H02.033'),
('Senile entropion of left upper eyelid','Senile entropion of left upper eyelid','Maladies de l''œil et de ses annexes','H02.034'),
('Senile entropion of left lower eyelid','Senile entropion of left lower eyelid','Maladies de l''œil et de ses annexes','H02.035'),
('Senile entropion of left eye, non spécifié eyelid','Senile entropion of left eye, unspecified eyelid','Maladies de l''œil et de ses annexes','H02.036'),
('Senile entropion of non spécifié eye, non spécifié eyelid','Senile entropion of unspecified eye, unspecified eyelid','Maladies de l''œil et de ses annexes','H02.039'),
('Spastic entropion of right upper eyelid','Spastic entropion of right upper eyelid','Maladies de l''œil et de ses annexes','H02.041'),
('Spastic entropion of right lower eyelid','Spastic entropion of right lower eyelid','Maladies de l''œil et de ses annexes','H02.042'),
('Spastic entropion of right eye, non spécifié eyelid','Spastic entropion of right eye, unspecified eyelid','Maladies de l''œil et de ses annexes','H02.043'),
('Spastic entropion of left upper eyelid','Spastic entropion of left upper eyelid','Maladies de l''œil et de ses annexes','H02.044'),
('Spastic entropion of left lower eyelid','Spastic entropion of left lower eyelid','Maladies de l''œil et de ses annexes','H02.045'),
('Spastic entropion of left eye, non spécifié eyelid','Spastic entropion of left eye, unspecified eyelid','Maladies de l''œil et de ses annexes','H02.046'),
('Spastic entropion of non spécifié eye, non spécifié eyelid','Spastic entropion of unspecified eye, unspecified eyelid','Maladies de l''œil et de ses annexes','H02.049'),
('Trichiasis without entropion right upper eyelid','Trichiasis without entropion right upper eyelid','Maladies de l''œil et de ses annexes','H02.051'),
('Trichiasis without entropion right lower eyelid','Trichiasis without entropion right lower eyelid','Maladies de l''œil et de ses annexes','H02.052'),
('Trichiasis without entropion right eye, non spécifié eyelid','Trichiasis without entropion right eye, unspecified eyelid','Maladies de l''œil et de ses annexes','H02.053'),
('Trichiasis without entropion left upper eyelid','Trichiasis without entropion left upper eyelid','Maladies de l''œil et de ses annexes','H02.054'),
('Trichiasis without entropion left lower eyelid','Trichiasis without entropion left lower eyelid','Maladies de l''œil et de ses annexes','H02.055'),
('Trichiasis without entropion left eye, non spécifié eyelid','Trichiasis without entropion left eye, unspecified eyelid','Maladies de l''œil et de ses annexes','H02.056'),
('Trichiasis without entropion non spécifié eye, non spécifié eyelid','Trichiasis without entropion unspecified eye, unspecified eyelid','Maladies de l''œil et de ses annexes','H02.059'),
('non spécifié ectropion of right upper eyelid','Unspecified ectropion of right upper eyelid','Maladies de l''œil et de ses annexes','H02.101'),
('non spécifié ectropion of right lower eyelid','Unspecified ectropion of right lower eyelid','Maladies de l''œil et de ses annexes','H02.102'),
('non spécifié ectropion of right eye, non spécifié eyelid','Unspecified ectropion of right eye, unspecified eyelid','Maladies de l''œil et de ses annexes','H02.103'),
('non spécifié ectropion of left upper eyelid','Unspecified ectropion of left upper eyelid','Maladies de l''œil et de ses annexes','H02.104'),
('non spécifié ectropion of left lower eyelid','Unspecified ectropion of left lower eyelid','Maladies de l''œil et de ses annexes','H02.105'),
('non spécifié ectropion of left eye, non spécifié eyelid','Unspecified ectropion of left eye, unspecified eyelid','Maladies de l''œil et de ses annexes','H02.106'),
('non spécifié ectropion of non spécifié eye, non spécifié eyelid','Unspecified ectropion of unspecified eye, unspecified eyelid','Maladies de l''œil et de ses annexes','H02.109'),
('Cicatricial ectropion of right upper eyelid','Cicatricial ectropion of right upper eyelid','Maladies de l''œil et de ses annexes','H02.111'),
('Cicatricial ectropion of right lower eyelid','Cicatricial ectropion of right lower eyelid','Maladies de l''œil et de ses annexes','H02.112'),
('Cicatricial ectropion of right eye, non spécifié eyelid','Cicatricial ectropion of right eye, unspecified eyelid','Maladies de l''œil et de ses annexes','H02.113'),
('Cicatricial ectropion of left upper eyelid','Cicatricial ectropion of left upper eyelid','Maladies de l''œil et de ses annexes','H02.114'),
('Cicatricial ectropion of left lower eyelid','Cicatricial ectropion of left lower eyelid','Maladies de l''œil et de ses annexes','H02.115'),
('Cicatricial ectropion of left eye, non spécifié eyelid','Cicatricial ectropion of left eye, unspecified eyelid','Maladies de l''œil et de ses annexes','H02.116'),
('Cicatricial ectropion of non spécifié eye, non spécifié eyelid','Cicatricial ectropion of unspecified eye, unspecified eyelid','Maladies de l''œil et de ses annexes','H02.119'),
('Mechanical ectropion of right upper eyelid','Mechanical ectropion of right upper eyelid','Maladies de l''œil et de ses annexes','H02.121'),
('Mechanical ectropion of right lower eyelid','Mechanical ectropion of right lower eyelid','Maladies de l''œil et de ses annexes','H02.122'),
('Mechanical ectropion of right eye, non spécifié eyelid','Mechanical ectropion of right eye, unspecified eyelid','Maladies de l''œil et de ses annexes','H02.123'),
('Mechanical ectropion of left upper eyelid','Mechanical ectropion of left upper eyelid','Maladies de l''œil et de ses annexes','H02.124'),
('Mechanical ectropion of left lower eyelid','Mechanical ectropion of left lower eyelid','Maladies de l''œil et de ses annexes','H02.125')
ON CONFLICT (nom_fr) DO NOTHING;
