-- icd10_batch_007.sql (80 rows)
INSERT INTO pathologies (nom_fr, nom_en, categorie, icd10_code)
VALUES
('Carcinome, in situ of unspecified eye','Carcinoma in situ of unspecified eye','Tumeurs bénignes et in situ','D09.20'),
('Carcinome, in situ of right eye','Carcinoma in situ of right eye','Tumeurs bénignes et in situ','D09.21'),
('Carcinome, in situ of left eye','Carcinoma in situ of left eye','Tumeurs bénignes et in situ','D09.22'),
('Carcinome, in situ of thyroid and other endocrine glands','Carcinoma in situ of thyroid and other endocrine glands','Tumeurs bénignes et in situ','D09.3'),
('Carcinome, in situ of other specified sites','Carcinoma in situ of other specified sites','Tumeurs bénignes et in situ','D09.8'),
('Carcinome, in situ, unspecified','Carcinoma in situ, unspecified','Tumeurs bénignes et in situ','D09.9'),
('Tumeur bénigne, of lip','Benign neoplasm of lip','Tumeurs bénignes et in situ','D10.0'),
('Tumeur bénigne, of tongue','Benign neoplasm of tongue','Tumeurs bénignes et in situ','D10.1'),
('Tumeur bénigne, of floor of mouth','Benign neoplasm of floor of mouth','Tumeurs bénignes et in situ','D10.2'),
('Tumeur bénigne, of unspecified part of mouth','Benign neoplasm of unspecified part of mouth','Tumeurs bénignes et in situ','D10.30'),
('Tumeur bénigne, of other parts of mouth','Benign neoplasm of other parts of mouth','Tumeurs bénignes et in situ','D10.39'),
('Tumeur bénigne, of tonsil','Benign neoplasm of tonsil','Tumeurs bénignes et in situ','D10.4'),
('Tumeur bénigne, of other parts of oropharynx','Benign neoplasm of other parts of oropharynx','Tumeurs bénignes et in situ','D10.5'),
('Tumeur bénigne, of nasopharynx','Benign neoplasm of nasopharynx','Tumeurs bénignes et in situ','D10.6'),
('Tumeur bénigne, of hypopharynx','Benign neoplasm of hypopharynx','Tumeurs bénignes et in situ','D10.7'),
('Tumeur bénigne, of pharynx, unspecified','Benign neoplasm of pharynx, unspecified','Tumeurs bénignes et in situ','D10.9'),
('Tumeur bénigne, of parotid gland','Benign neoplasm of parotid gland','Tumeurs bénignes et in situ','D11.0'),
('Tumeur bénigne, of other major salivary glands','Benign neoplasm of other major salivary glands','Tumeurs bénignes et in situ','D11.7'),
('Tumeur bénigne, of major salivary gland, unspecified','Benign neoplasm of major salivary gland, unspecified','Tumeurs bénignes et in situ','D11.9'),
('Tumeur bénigne, of cecum','Benign neoplasm of cecum','Tumeurs bénignes et in situ','D12.0'),
('Tumeur bénigne, of appendix','Benign neoplasm of appendix','Tumeurs bénignes et in situ','D12.1'),
('Tumeur bénigne, of ascending colon','Benign neoplasm of ascending colon','Tumeurs bénignes et in situ','D12.2'),
('Tumeur bénigne, of transverse colon','Benign neoplasm of transverse colon','Tumeurs bénignes et in situ','D12.3'),
('Tumeur bénigne, of descending colon','Benign neoplasm of descending colon','Tumeurs bénignes et in situ','D12.4'),
('Tumeur bénigne, of sigmoid colon','Benign neoplasm of sigmoid colon','Tumeurs bénignes et in situ','D12.5'),
('Tumeur bénigne, of colon, unspecified','Benign neoplasm of colon, unspecified','Tumeurs bénignes et in situ','D12.6'),
('Tumeur bénigne, of rectosigmoid junction','Benign neoplasm of rectosigmoid junction','Tumeurs bénignes et in situ','D12.7'),
('Tumeur bénigne, of rectum','Benign neoplasm of rectum','Tumeurs bénignes et in situ','D12.8'),
('Tumeur bénigne, of anus and anal canal','Benign neoplasm of anus and anal canal','Tumeurs bénignes et in situ','D12.9'),
('Tumeur bénigne, of esophagus','Benign neoplasm of esophagus','Tumeurs bénignes et in situ','D13.0'),
('Tumeur bénigne, of stomach','Benign neoplasm of stomach','Tumeurs bénignes et in situ','D13.1'),
('Tumeur bénigne, of duodenum','Benign neoplasm of duodenum','Tumeurs bénignes et in situ','D13.2'),
('Tumeur bénigne, of unspecified part of small intestine','Benign neoplasm of unspecified part of small intestine','Tumeurs bénignes et in situ','D13.30'),
('Tumeur bénigne, of other parts of small intestine','Benign neoplasm of other parts of small intestine','Tumeurs bénignes et in situ','D13.39'),
('Tumeur bénigne, of liver','Benign neoplasm of liver','Tumeurs bénignes et in situ','D13.4'),
('Tumeur bénigne, of extrahepatic bile ducts','Benign neoplasm of extrahepatic bile ducts','Tumeurs bénignes et in situ','D13.5'),
('Tumeur bénigne, of pancreas','Benign neoplasm of pancreas','Tumeurs bénignes et in situ','D13.6'),
('Tumeur bénigne, of endocrine pancreas','Benign neoplasm of endocrine pancreas','Tumeurs bénignes et in situ','D13.7'),
('Familial adenomatous polyposis','Familial adenomatous polyposis','Tumeurs bénignes et in situ','D13.91'),
('Tumeur bénigne, of ill-defined sites within the digestive system','Benign neoplasm of ill-defined sites within the digestive system','Tumeurs bénignes et in situ','D13.99'),
('Tumeur bénigne, of middle ear, nasal cavity and accessory sinuses','Benign neoplasm of middle ear, nasal cavity and accessory sinuses','Tumeurs bénignes et in situ','D14.0'),
('Von Willebrand maladie, type 2B','Von Willebrand disease, type 2B','Maladies du sang et troubles immunitaires','D68.021'),
('Von Willebrand maladie, type 2M','Von Willebrand disease, type 2M','Maladies du sang et troubles immunitaires','D68.022'),
('Von Willebrand maladie, type 2N','Von Willebrand disease, type 2N','Maladies du sang et troubles immunitaires','D68.023'),
('Von Willebrand maladie, type 2, non spécifié','Von Willebrand disease, type 2, unspecified','Maladies du sang et troubles immunitaires','D68.029'),
('Von Willebrand maladie, type 3','Von Willebrand disease, type 3','Maladies du sang et troubles immunitaires','D68.03'),
('Acquired von Willebrand maladie','Acquired von Willebrand disease','Maladies du sang et troubles immunitaires','D68.04'),
('autre von Willebrand maladie','Other von Willebrand disease','Maladies du sang et troubles immunitaires','D68.09'),
('carence of vitamin E','Deficiency of vitamin E','Maladies endocriniennes, nutritionnelles et métaboliques','E56.0'),
('congénital iodine-carence syndrome, neurological type','Congenital iodine-deficiency syndrome, neurological type','Maladies endocriniennes, nutritionnelles et métaboliques','E00.0'),
('congénital iodine-carence syndrome, myxedematous type','Congenital iodine-deficiency syndrome, myxedematous type','Maladies endocriniennes, nutritionnelles et métaboliques','E00.1'),
('congénital iodine-carence syndrome, mixed type','Congenital iodine-deficiency syndrome, mixed type','Maladies endocriniennes, nutritionnelles et métaboliques','E00.2'),
('congénital iodine-carence syndrome, non spécifié','Congenital iodine-deficiency syndrome, unspecified','Maladies endocriniennes, nutritionnelles et métaboliques','E00.9'),
('Iodine-carence related diffuse (endemic) goiter','Iodine-deficiency related diffuse (endemic) goiter','Maladies endocriniennes, nutritionnelles et métaboliques','E01.0'),
('Iodine-carence related multinodular (endemic) goiter','Iodine-deficiency related multinodular (endemic) goiter','Maladies endocriniennes, nutritionnelles et métaboliques','E01.1'),
('Iodine-carence related (endemic) goiter, non spécifié','Iodine-deficiency related (endemic) goiter, unspecified','Maladies endocriniennes, nutritionnelles et métaboliques','E01.2'),
('autre iodine-carence related thyroid disorders and allied conditions','Other iodine-deficiency related thyroid disorders and allied conditions','Maladies endocriniennes, nutritionnelles et métaboliques','E01.8'),
('Subclinical iodine-carence hypothyroidism','Subclinical iodine-deficiency hypothyroidism','Maladies endocriniennes, nutritionnelles et métaboliques','E02'),
('congénital hypothyroidism with diffuse goiter','Congenital hypothyroidism with diffuse goiter','Maladies endocriniennes, nutritionnelles et métaboliques','E03.0'),
('congénital hypothyroidism without goiter','Congenital hypothyroidism without goiter','Maladies endocriniennes, nutritionnelles et métaboliques','E03.1'),
('Hypothyroïdie, due to medicaments and other exogenous substances','Hypothyroidism due to medicaments and other exogenous substances','Maladies endocriniennes, nutritionnelles et métaboliques','E03.2'),
('Postinfectious hypothyroidism','Postinfectious hypothyroidism','Maladies endocriniennes, nutritionnelles et métaboliques','E03.3'),
('Atrophy of thyroid (acquired)','Atrophy of thyroid (acquired)','Maladies endocriniennes, nutritionnelles et métaboliques','E03.4'),
('Myxedema coma','Myxedema coma','Maladies endocriniennes, nutritionnelles et métaboliques','E03.5'),
('autre specified hypothyroidism','Other specified hypothyroidism','Maladies endocriniennes, nutritionnelles et métaboliques','E03.8'),
('Hypothyroïdie, , unspecified','Hypothyroidism, unspecified','Maladies endocriniennes, nutritionnelles et métaboliques','E03.9'),
('Nontoxic diffuse goiter','Nontoxic diffuse goiter','Maladies endocriniennes, nutritionnelles et métaboliques','E04.0'),
('Nontoxic single thyroid nodule','Nontoxic single thyroid nodule','Maladies endocriniennes, nutritionnelles et métaboliques','E04.1'),
('Nontoxic multinodular goiter','Nontoxic multinodular goiter','Maladies endocriniennes, nutritionnelles et métaboliques','E04.2'),
('autre specified nontoxic goiter','Other specified nontoxic goiter','Maladies endocriniennes, nutritionnelles et métaboliques','E04.8'),
('Nontoxic goiter, non spécifié','Nontoxic goiter, unspecified','Maladies endocriniennes, nutritionnelles et métaboliques','E04.9'),
('Thyrotoxicosis with diffuse goiter without thyrotoxic crisis or storm','Thyrotoxicosis with diffuse goiter without thyrotoxic crisis or storm','Maladies endocriniennes, nutritionnelles et métaboliques','E05.00'),
('Thyrotoxicosis with diffuse goiter with thyrotoxic crisis or storm','Thyrotoxicosis with diffuse goiter with thyrotoxic crisis or storm','Maladies endocriniennes, nutritionnelles et métaboliques','E05.01'),
('Thyrotoxicosis with toxic single thyroid nodule without thyrotoxic crisis or storm','Thyrotoxicosis with toxic single thyroid nodule without thyrotoxic crisis or storm','Maladies endocriniennes, nutritionnelles et métaboliques','E05.10'),
('Thyrotoxicosis with toxic single thyroid nodule with thyrotoxic crisis or storm','Thyrotoxicosis with toxic single thyroid nodule with thyrotoxic crisis or storm','Maladies endocriniennes, nutritionnelles et métaboliques','E05.11'),
('Thyrotoxicosis with toxic multinodular goiter without thyrotoxic crisis or storm','Thyrotoxicosis with toxic multinodular goiter without thyrotoxic crisis or storm','Maladies endocriniennes, nutritionnelles et métaboliques','E05.20'),
('Thyrotoxicosis with toxic multinodular goiter with thyrotoxic crisis or storm','Thyrotoxicosis with toxic multinodular goiter with thyrotoxic crisis or storm','Maladies endocriniennes, nutritionnelles et métaboliques','E05.21'),
('Thyrotoxicosis from ectopic thyroid tissue without thyrotoxic crisis or storm','Thyrotoxicosis from ectopic thyroid tissue without thyrotoxic crisis or storm','Maladies endocriniennes, nutritionnelles et métaboliques','E05.30'),
('Thyrotoxicosis from ectopic thyroid tissue with thyrotoxic crisis or storm','Thyrotoxicosis from ectopic thyroid tissue with thyrotoxic crisis or storm','Maladies endocriniennes, nutritionnelles et métaboliques','E05.31'),
('Thyrotoxicosis factitia without thyrotoxic crisis or storm','Thyrotoxicosis factitia without thyrotoxic crisis or storm','Maladies endocriniennes, nutritionnelles et métaboliques','E05.40')
ON CONFLICT (nom_fr) DO NOTHING;
