-- icd10v2_batch_192.sql (80 rows)
INSERT INTO pathologies (nom_fr, nom_en, categorie, icd10_code)
VALUES
('autre rupture of muscle (nontraumatic), left shoulder','Other rupture of muscle (nontraumatic), left shoulder','Maladies de l''appareil locomoteur','M62.112'),
('autre rupture of muscle (nontraumatic), non spécifié shoulder','Other rupture of muscle (nontraumatic), unspecified shoulder','Maladies de l''appareil locomoteur','M62.119'),
('autre rupture of muscle (nontraumatic), right upper arm','Other rupture of muscle (nontraumatic), right upper arm','Maladies de l''appareil locomoteur','M62.121'),
('autre rupture of muscle (nontraumatic), left upper arm','Other rupture of muscle (nontraumatic), left upper arm','Maladies de l''appareil locomoteur','M62.122'),
('autre rupture of muscle (nontraumatic), non spécifié upper arm','Other rupture of muscle (nontraumatic), unspecified upper arm','Maladies de l''appareil locomoteur','M62.129'),
('autre rupture of muscle (nontraumatic), right forearm','Other rupture of muscle (nontraumatic), right forearm','Maladies de l''appareil locomoteur','M62.131'),
('autre rupture of muscle (nontraumatic), left forearm','Other rupture of muscle (nontraumatic), left forearm','Maladies de l''appareil locomoteur','M62.132'),
('autre rupture of muscle (nontraumatic), non spécifié forearm','Other rupture of muscle (nontraumatic), unspecified forearm','Maladies de l''appareil locomoteur','M62.139'),
('autre rupture of muscle (nontraumatic), right hand','Other rupture of muscle (nontraumatic), right hand','Maladies de l''appareil locomoteur','M62.141'),
('autre rupture of muscle (nontraumatic), left hand','Other rupture of muscle (nontraumatic), left hand','Maladies de l''appareil locomoteur','M62.142'),
('autre rupture of muscle (nontraumatic), non spécifié hand','Other rupture of muscle (nontraumatic), unspecified hand','Maladies de l''appareil locomoteur','M62.149'),
('autre rupture of muscle (nontraumatic), right thigh','Other rupture of muscle (nontraumatic), right thigh','Maladies de l''appareil locomoteur','M62.151'),
('autre rupture of muscle (nontraumatic), left thigh','Other rupture of muscle (nontraumatic), left thigh','Maladies de l''appareil locomoteur','M62.152'),
('autre rupture of muscle (nontraumatic), non spécifié thigh','Other rupture of muscle (nontraumatic), unspecified thigh','Maladies de l''appareil locomoteur','M62.159'),
('autre rupture of muscle (nontraumatic), right lower leg','Other rupture of muscle (nontraumatic), right lower leg','Maladies de l''appareil locomoteur','M62.161'),
('autre rupture of muscle (nontraumatic), left lower leg','Other rupture of muscle (nontraumatic), left lower leg','Maladies de l''appareil locomoteur','M62.162'),
('autre rupture of muscle (nontraumatic), non spécifié lower leg','Other rupture of muscle (nontraumatic), unspecified lower leg','Maladies de l''appareil locomoteur','M62.169'),
('autre rupture of muscle (nontraumatic), right ankle and foot','Other rupture of muscle (nontraumatic), right ankle and foot','Maladies de l''appareil locomoteur','M62.171'),
('autre rupture of muscle (nontraumatic), left ankle and foot','Other rupture of muscle (nontraumatic), left ankle and foot','Maladies de l''appareil locomoteur','M62.172'),
('autre rupture of muscle (nontraumatic), non spécifié ankle and foot','Other rupture of muscle (nontraumatic), unspecified ankle and foot','Maladies de l''appareil locomoteur','M62.179'),
('autre rupture of muscle (nontraumatic), autre site','Other rupture of muscle (nontraumatic), other site','Maladies de l''appareil locomoteur','M62.18'),
('Nontraumatic ischemic infarction of muscle, non spécifié site','Nontraumatic ischemic infarction of muscle, unspecified site','Maladies de l''appareil locomoteur','M62.20'),
('Nontraumatic ischemic infarction of muscle, right shoulder','Nontraumatic ischemic infarction of muscle, right shoulder','Maladies de l''appareil locomoteur','M62.211'),
('Nontraumatic ischemic infarction of muscle, left shoulder','Nontraumatic ischemic infarction of muscle, left shoulder','Maladies de l''appareil locomoteur','M62.212'),
('Nontraumatic ischemic infarction of muscle, non spécifié shoulder','Nontraumatic ischemic infarction of muscle, unspecified shoulder','Maladies de l''appareil locomoteur','M62.219'),
('Nontraumatic ischemic infarction of muscle, right upper arm','Nontraumatic ischemic infarction of muscle, right upper arm','Maladies de l''appareil locomoteur','M62.221'),
('Nontraumatic ischemic infarction of muscle, left upper arm','Nontraumatic ischemic infarction of muscle, left upper arm','Maladies de l''appareil locomoteur','M62.222'),
('Nontraumatic ischemic infarction of muscle, non spécifié upper arm','Nontraumatic ischemic infarction of muscle, unspecified upper arm','Maladies de l''appareil locomoteur','M62.229'),
('Nontraumatic ischemic infarction of muscle, right forearm','Nontraumatic ischemic infarction of muscle, right forearm','Maladies de l''appareil locomoteur','M62.231'),
('Nontraumatic ischemic infarction of muscle, left forearm','Nontraumatic ischemic infarction of muscle, left forearm','Maladies de l''appareil locomoteur','M62.232'),
('Nontraumatic ischemic infarction of muscle, non spécifié forearm','Nontraumatic ischemic infarction of muscle, unspecified forearm','Maladies de l''appareil locomoteur','M62.239'),
('Nontraumatic ischemic infarction of muscle, right hand','Nontraumatic ischemic infarction of muscle, right hand','Maladies de l''appareil locomoteur','M62.241'),
('Nontraumatic ischemic infarction of muscle, left hand','Nontraumatic ischemic infarction of muscle, left hand','Maladies de l''appareil locomoteur','M62.242'),
('Nontraumatic ischemic infarction of muscle, non spécifié hand','Nontraumatic ischemic infarction of muscle, unspecified hand','Maladies de l''appareil locomoteur','M62.249'),
('Nontraumatic ischemic infarction of muscle, right thigh','Nontraumatic ischemic infarction of muscle, right thigh','Maladies de l''appareil locomoteur','M62.251'),
('Nontraumatic ischemic infarction of muscle, left thigh','Nontraumatic ischemic infarction of muscle, left thigh','Maladies de l''appareil locomoteur','M62.252'),
('Nontraumatic ischemic infarction of muscle, non spécifié thigh','Nontraumatic ischemic infarction of muscle, unspecified thigh','Maladies de l''appareil locomoteur','M62.259'),
('Nontraumatic ischemic infarction of muscle, right lower leg','Nontraumatic ischemic infarction of muscle, right lower leg','Maladies de l''appareil locomoteur','M62.261'),
('Nontraumatic ischemic infarction of muscle, left lower leg','Nontraumatic ischemic infarction of muscle, left lower leg','Maladies de l''appareil locomoteur','M62.262'),
('Nontraumatic ischemic infarction of muscle, non spécifié lower leg','Nontraumatic ischemic infarction of muscle, unspecified lower leg','Maladies de l''appareil locomoteur','M62.269'),
('Nontraumatic ischemic infarction of muscle, right ankle and foot','Nontraumatic ischemic infarction of muscle, right ankle and foot','Maladies de l''appareil locomoteur','M62.271'),
('Nontraumatic ischemic infarction of muscle, left ankle and foot','Nontraumatic ischemic infarction of muscle, left ankle and foot','Maladies de l''appareil locomoteur','M62.272'),
('Nontraumatic ischemic infarction of muscle, non spécifié ankle and foot','Nontraumatic ischemic infarction of muscle, unspecified ankle and foot','Maladies de l''appareil locomoteur','M62.279'),
('Nontraumatic ischemic infarction of muscle, autre site','Nontraumatic ischemic infarction of muscle, other site','Maladies de l''appareil locomoteur','M62.28'),
('Immobility syndrome (paraplegic)','Immobility syndrome (paraplegic)','Maladies de l''appareil locomoteur','M62.3'),
('Contracture of muscle, non spécifié site','Contracture of muscle, unspecified site','Maladies de l''appareil locomoteur','M62.40'),
('Contracture of muscle, right shoulder','Contracture of muscle, right shoulder','Maladies de l''appareil locomoteur','M62.411'),
('Contracture of muscle, left shoulder','Contracture of muscle, left shoulder','Maladies de l''appareil locomoteur','M62.412'),
('Contracture of muscle, non spécifié shoulder','Contracture of muscle, unspecified shoulder','Maladies de l''appareil locomoteur','M62.419'),
('Contracture of muscle, right upper arm','Contracture of muscle, right upper arm','Maladies de l''appareil locomoteur','M62.421'),
('Contracture of muscle, left upper arm','Contracture of muscle, left upper arm','Maladies de l''appareil locomoteur','M62.422'),
('Contracture of muscle, non spécifié upper arm','Contracture of muscle, unspecified upper arm','Maladies de l''appareil locomoteur','M62.429'),
('Contracture of muscle, right forearm','Contracture of muscle, right forearm','Maladies de l''appareil locomoteur','M62.431'),
('Contracture of muscle, left forearm','Contracture of muscle, left forearm','Maladies de l''appareil locomoteur','M62.432'),
('Contracture of muscle, non spécifié forearm','Contracture of muscle, unspecified forearm','Maladies de l''appareil locomoteur','M62.439'),
('Contracture of muscle, right hand','Contracture of muscle, right hand','Maladies de l''appareil locomoteur','M62.441'),
('Contracture of muscle, left hand','Contracture of muscle, left hand','Maladies de l''appareil locomoteur','M62.442'),
('Contracture of muscle, non spécifié hand','Contracture of muscle, unspecified hand','Maladies de l''appareil locomoteur','M62.449'),
('Contracture of muscle, right thigh','Contracture of muscle, right thigh','Maladies de l''appareil locomoteur','M62.451'),
('Contracture of muscle, left thigh','Contracture of muscle, left thigh','Maladies de l''appareil locomoteur','M62.452'),
('Contracture of muscle, non spécifié thigh','Contracture of muscle, unspecified thigh','Maladies de l''appareil locomoteur','M62.459'),
('Contracture of muscle, right lower leg','Contracture of muscle, right lower leg','Maladies de l''appareil locomoteur','M62.461'),
('Contracture of muscle, left lower leg','Contracture of muscle, left lower leg','Maladies de l''appareil locomoteur','M62.462'),
('Contracture of muscle, non spécifié lower leg','Contracture of muscle, unspecified lower leg','Maladies de l''appareil locomoteur','M62.469'),
('Contracture of muscle, right ankle and foot','Contracture of muscle, right ankle and foot','Maladies de l''appareil locomoteur','M62.471'),
('Contracture of muscle, left ankle and foot','Contracture of muscle, left ankle and foot','Maladies de l''appareil locomoteur','M62.472'),
('Contracture of muscle, non spécifié ankle and foot','Contracture of muscle, unspecified ankle and foot','Maladies de l''appareil locomoteur','M62.479'),
('Contracture of muscle, autre site','Contracture of muscle, other site','Maladies de l''appareil locomoteur','M62.48'),
('Contracture of muscle, multiple sites','Contracture of muscle, multiple sites','Maladies de l''appareil locomoteur','M62.49'),
('Muscle wasting and atrophy, not elsewhere classified, non spécifié site','Muscle wasting and atrophy, not elsewhere classified, unspecified site','Maladies de l''appareil locomoteur','M62.50'),
('Muscle wasting and atrophy, not elsewhere classified, right shoulder','Muscle wasting and atrophy, not elsewhere classified, right shoulder','Maladies de l''appareil locomoteur','M62.511'),
('Muscle wasting and atrophy, not elsewhere classified, left shoulder','Muscle wasting and atrophy, not elsewhere classified, left shoulder','Maladies de l''appareil locomoteur','M62.512'),
('Muscle wasting and atrophy, not elsewhere classified, non spécifié shoulder','Muscle wasting and atrophy, not elsewhere classified, unspecified shoulder','Maladies de l''appareil locomoteur','M62.519'),
('Muscle wasting and atrophy, not elsewhere classified, right upper arm','Muscle wasting and atrophy, not elsewhere classified, right upper arm','Maladies de l''appareil locomoteur','M62.521'),
('Muscle wasting and atrophy, not elsewhere classified, left upper arm','Muscle wasting and atrophy, not elsewhere classified, left upper arm','Maladies de l''appareil locomoteur','M62.522'),
('Muscle wasting and atrophy, not elsewhere classified, non spécifié upper arm','Muscle wasting and atrophy, not elsewhere classified, unspecified upper arm','Maladies de l''appareil locomoteur','M62.529'),
('Muscle wasting and atrophy, not elsewhere classified, right forearm','Muscle wasting and atrophy, not elsewhere classified, right forearm','Maladies de l''appareil locomoteur','M62.531'),
('Muscle wasting and atrophy, not elsewhere classified, left forearm','Muscle wasting and atrophy, not elsewhere classified, left forearm','Maladies de l''appareil locomoteur','M62.532'),
('Muscle wasting and atrophy, not elsewhere classified, non spécifié forearm','Muscle wasting and atrophy, not elsewhere classified, unspecified forearm','Maladies de l''appareil locomoteur','M62.539'),
('Muscle wasting and atrophy, not elsewhere classified, right hand','Muscle wasting and atrophy, not elsewhere classified, right hand','Maladies de l''appareil locomoteur','M62.541')
ON CONFLICT (nom_fr) DO NOTHING;
