-- icd10v2_batch_039.sql (80 rows)
INSERT INTO pathologies (nom_fr, nom_en, categorie, icd10_code)
VALUES
('Desmoid tumeur of abdominal wall','Desmoid tumor of abdominal wall','Tumeurs bénignes et in situ','D48.113'),
('Desmoid tumeur, intraabdominal','Desmoid tumor, intraabdominal','Tumeurs bénignes et in situ','D48.114'),
('Desmoid tumeur of upper extremity and shoulder girdle','Desmoid tumor of upper extremity and shoulder girdle','Tumeurs bénignes et in situ','D48.115'),
('Desmoid tumeur of lower extremity and pelvic girdle','Desmoid tumor of lower extremity and pelvic girdle','Tumeurs bénignes et in situ','D48.116'),
('Desmoid tumeur of back','Desmoid tumor of back','Tumeurs bénignes et in situ','D48.117'),
('Desmoid tumeur of autre site','Desmoid tumor of other site','Tumeurs bénignes et in situ','D48.118'),
('Desmoid tumeur of non spécifié site','Desmoid tumor of unspecified site','Tumeurs bénignes et in situ','D48.119'),
('autre specified néoplasme of uncertain behavior of connective and autre soft tissue','Other specified neoplasm of uncertain behavior of connective and other soft tissue','Tumeurs bénignes et in situ','D48.19'),
('néoplasme of uncertain behavior of peripheral nerves and autonomic nervous system','Neoplasm of uncertain behavior of peripheral nerves and autonomic nervous system','Tumeurs bénignes et in situ','D48.2'),
('néoplasme of uncertain behavior of retroperitoneum','Neoplasm of uncertain behavior of retroperitoneum','Tumeurs bénignes et in situ','D48.3'),
('néoplasme of uncertain behavior of peritoneum','Neoplasm of uncertain behavior of peritoneum','Tumeurs bénignes et in situ','D48.4'),
('néoplasme of uncertain behavior of skin','Neoplasm of uncertain behavior of skin','Tumeurs bénignes et in situ','D48.5'),
('néoplasme of uncertain behavior of non spécifié breast','Neoplasm of uncertain behavior of unspecified breast','Tumeurs bénignes et in situ','D48.60'),
('néoplasme of uncertain behavior of right breast','Neoplasm of uncertain behavior of right breast','Tumeurs bénignes et in situ','D48.61'),
('néoplasme of uncertain behavior of left breast','Neoplasm of uncertain behavior of left breast','Tumeurs bénignes et in situ','D48.62'),
('néoplasme of uncertain behavior of autre specified sites','Neoplasm of uncertain behavior of other specified sites','Tumeurs bénignes et in situ','D48.7'),
('néoplasme of uncertain behavior, non spécifié','Neoplasm of uncertain behavior, unspecified','Tumeurs bénignes et in situ','D48.9'),
('néoplasme of non spécifié behavior of digestive system','Neoplasm of unspecified behavior of digestive system','Tumeurs bénignes et in situ','D49.0'),
('néoplasme of non spécifié behavior of respiratory system','Neoplasm of unspecified behavior of respiratory system','Tumeurs bénignes et in situ','D49.1'),
('néoplasme of non spécifié behavior of bone, soft tissue, and skin','Neoplasm of unspecified behavior of bone, soft tissue, and skin','Tumeurs bénignes et in situ','D49.2'),
('néoplasme of non spécifié behavior of breast','Neoplasm of unspecified behavior of breast','Tumeurs bénignes et in situ','D49.3'),
('néoplasme of non spécifié behavior of bladder','Neoplasm of unspecified behavior of bladder','Tumeurs bénignes et in situ','D49.4'),
('néoplasme of non spécifié behavior of right kidney','Neoplasm of unspecified behavior of right kidney','Tumeurs bénignes et in situ','D49.511'),
('néoplasme of non spécifié behavior of left kidney','Neoplasm of unspecified behavior of left kidney','Tumeurs bénignes et in situ','D49.512'),
('néoplasme of non spécifié behavior of non spécifié kidney','Neoplasm of unspecified behavior of unspecified kidney','Tumeurs bénignes et in situ','D49.519'),
('néoplasme of non spécifié behavior of autre genitourinary organ','Neoplasm of unspecified behavior of other genitourinary organ','Tumeurs bénignes et in situ','D49.59'),
('néoplasme of non spécifié behavior of brain','Neoplasm of unspecified behavior of brain','Tumeurs bénignes et in situ','D49.6'),
('néoplasme of non spécifié behavior of endocrine glands and autre parts of nervous system','Neoplasm of unspecified behavior of endocrine glands and other parts of nervous system','Tumeurs bénignes et in situ','D49.7'),
('néoplasme of non spécifié behavior of retina and choroid','Neoplasm of unspecified behavior of retina and choroid','Tumeurs bénignes et in situ','D49.81'),
('néoplasme of non spécifié behavior of autre specified sites','Neoplasm of unspecified behavior of other specified sites','Tumeurs bénignes et in situ','D49.89'),
('néoplasme of non spécifié behavior of non spécifié site','Neoplasm of unspecified behavior of unspecified site','Tumeurs bénignes et in situ','D49.9'),
('Maternal care for anti-D [Rh] antibodies, first trimester, fetus 5','Maternal care for anti-D [Rh] antibodies, first trimester, fetus 5','Grossesse, accouchement et puerpéralité','O36.0115'),
('Maternal care for anti-D [Rh] antibodies, second trimester, fetus 5','Maternal care for anti-D [Rh] antibodies, second trimester, fetus 5','Grossesse, accouchement et puerpéralité','O36.0125'),
('Maternal care for anti-D [Rh] antibodies, third trimester, fetus 5','Maternal care for anti-D [Rh] antibodies, third trimester, fetus 5','Grossesse, accouchement et puerpéralité','O36.0135'),
('Maternal care for anti-D [Rh] antibodies, non spécifié trimester, fetus 5','Maternal care for anti-D [Rh] antibodies, unspecified trimester, fetus 5','Grossesse, accouchement et puerpéralité','O36.0195'),
('Iron carence anemia secondaire to blood loss (chronique)','Iron deficiency anemia secondary to blood loss (chronic)','Maladies du sang et troubles immunitaires','D50.0'),
('Sideropenic dysphagia','Sideropenic dysphagia','Maladies du sang et troubles immunitaires','D50.1'),
('autre iron carence anemias','Other iron deficiency anemias','Maladies du sang et troubles immunitaires','D50.8'),
('Iron carence anemia, non spécifié','Iron deficiency anemia, unspecified','Maladies du sang et troubles immunitaires','D50.9'),
('Transcobalamin II carence','Transcobalamin II deficiency','Maladies du sang et troubles immunitaires','D51.2'),
('Dietary folate carence anemia','Dietary folate deficiency anemia','Maladies du sang et troubles immunitaires','D52.0'),
('Drug-induced folate carence anemia','Drug-induced folate deficiency anemia','Maladies du sang et troubles immunitaires','D52.1'),
('autre folate carence anemias','Other folate deficiency anemias','Maladies du sang et troubles immunitaires','D52.8'),
('Folate carence anemia, non spécifié','Folate deficiency anemia, unspecified','Maladies du sang et troubles immunitaires','D52.9'),
('Protein carence anemia','Protein deficiency anemia','Maladies du sang et troubles immunitaires','D53.0'),
('autre megaloblastic anemias, not elsewhere classified','Other megaloblastic anemias, not elsewhere classified','Maladies du sang et troubles immunitaires','D53.1'),
('Scorbutic anemia','Scorbutic anemia','Maladies du sang et troubles immunitaires','D53.2'),
('autre specified nutritional anemias','Other specified nutritional anemias','Maladies du sang et troubles immunitaires','D53.8'),
('Nutritional anemia, non spécifié','Nutritional anemia, unspecified','Maladies du sang et troubles immunitaires','D53.9'),
('Anémie due to glucose-6-phosphate dehydrogenase [G6PD] deficiency','Anemia due to glucose-6-phosphate dehydrogenase [G6PD] deficiency','Maladies du sang et troubles immunitaires','D55.0'),
('Anémie due to other disorders of glutathione metabolism','Anemia due to other disorders of glutathione metabolism','Maladies du sang et troubles immunitaires','D55.1'),
('Anémie due to pyruvate kinase deficiency','Anemia due to pyruvate kinase deficiency','Maladies du sang et troubles immunitaires','D55.21'),
('Anémie due to other disorders of glycolytic enzymes','Anemia due to other disorders of glycolytic enzymes','Maladies du sang et troubles immunitaires','D55.29'),
('Anémie due to disorders of nucleotide metabolism','Anemia due to disorders of nucleotide metabolism','Maladies du sang et troubles immunitaires','D55.3'),
('autre anemias due to enzyme disorders','Other anemias due to enzyme disorders','Maladies du sang et troubles immunitaires','D55.8'),
('Anémie due to enzyme disorder, unspecified','Anemia due to enzyme disorder, unspecified','Maladies du sang et troubles immunitaires','D55.9'),
('Alpha thalassemia','Alpha thalassemia','Maladies du sang et troubles immunitaires','D56.0'),
('Beta thalassemia','Beta thalassemia','Maladies du sang et troubles immunitaires','D56.1'),
('Delta-beta thalassemia','Delta-beta thalassemia','Maladies du sang et troubles immunitaires','D56.2'),
('Thalassemia minor','Thalassemia minor','Maladies du sang et troubles immunitaires','D56.3'),
('Hereditary persistence of fetal hemoglobin [HPFH]','Hereditary persistence of fetal hemoglobin [HPFH]','Maladies du sang et troubles immunitaires','D56.4'),
('Hemoglobin E-beta thalassemia','Hemoglobin E-beta thalassemia','Maladies du sang et troubles immunitaires','D56.5'),
('autre thalassemias','Other thalassemias','Maladies du sang et troubles immunitaires','D56.8'),
('Thalassemia, non spécifié','Thalassemia, unspecified','Maladies du sang et troubles immunitaires','D56.9'),
('Hb-SS maladie with crisis, non spécifié','Hb-SS disease with crisis, unspecified','Maladies du sang et troubles immunitaires','D57.00'),
('Hb-SS maladie with aigu chest syndrome','Hb-SS disease with acute chest syndrome','Maladies du sang et troubles immunitaires','D57.01'),
('Hb-SS maladie with splenic sequestration','Hb-SS disease with splenic sequestration','Maladies du sang et troubles immunitaires','D57.02'),
('Hb-SS maladie with cerebral vascular involvement','Hb-SS disease with cerebral vascular involvement','Maladies du sang et troubles immunitaires','D57.03'),
('Hb-SS maladie with dactylitis','Hb-SS disease with dactylitis','Maladies du sang et troubles immunitaires','D57.04'),
('Hb-SS maladie with crisis with autre specified complication','Hb-SS disease with crisis with other specified complication','Maladies du sang et troubles immunitaires','D57.09'),
('Sickle-cell maladie without crisis','Sickle-cell disease without crisis','Maladies du sang et troubles immunitaires','D57.1'),
('Sickle-cell/Hb-C maladie without crisis','Sickle-cell/Hb-C disease without crisis','Maladies du sang et troubles immunitaires','D57.20'),
('Sickle-cell/Hb-C maladie with aigu chest syndrome','Sickle-cell/Hb-C disease with acute chest syndrome','Maladies du sang et troubles immunitaires','D57.211'),
('Sickle-cell/Hb-C maladie with splenic sequestration','Sickle-cell/Hb-C disease with splenic sequestration','Maladies du sang et troubles immunitaires','D57.212'),
('Sickle-cell/Hb-C maladie with cerebral vascular involvement','Sickle-cell/Hb-C disease with cerebral vascular involvement','Maladies du sang et troubles immunitaires','D57.213'),
('Sickle-cell/Hb-C maladie with dactylitis','Sickle-cell/Hb-C disease with dactylitis','Maladies du sang et troubles immunitaires','D57.214'),
('Sickle-cell/Hb-C maladie with crisis with autre specified complication','Sickle-cell/Hb-C disease with crisis with other specified complication','Maladies du sang et troubles immunitaires','D57.218'),
('Sickle-cell/Hb-C maladie with crisis, non spécifié','Sickle-cell/Hb-C disease with crisis, unspecified','Maladies du sang et troubles immunitaires','D57.219'),
('Sickle-cell trait','Sickle-cell trait','Maladies du sang et troubles immunitaires','D57.3'),
('Sickle-cell thalassemia without crisis','Sickle-cell thalassemia without crisis','Maladies du sang et troubles immunitaires','D57.40')
ON CONFLICT (nom_fr) DO NOTHING;
