-- icd10v2_batch_298.sql (80 rows)
INSERT INTO pathologies (nom_fr, nom_en, categorie, icd10_code)
VALUES
('External constriction of right shoulder, initial encounter','External constriction of right shoulder, initial encounter','Traumatismes, empoisonnements et autres causes externes','S40.241A'),
('External constriction of right shoulder, subsequent encounter','External constriction of right shoulder, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S40.241D'),
('External constriction of right shoulder, sequela','External constriction of right shoulder, sequela','Traumatismes, empoisonnements et autres causes externes','S40.241S'),
('External constriction of left shoulder, initial encounter','External constriction of left shoulder, initial encounter','Traumatismes, empoisonnements et autres causes externes','S40.242A'),
('External constriction of left shoulder, subsequent encounter','External constriction of left shoulder, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S40.242D'),
('External constriction of left shoulder, sequela','External constriction of left shoulder, sequela','Traumatismes, empoisonnements et autres causes externes','S40.242S'),
('External constriction of non spécifié shoulder, initial encounter','External constriction of unspecified shoulder, initial encounter','Traumatismes, empoisonnements et autres causes externes','S40.249A'),
('External constriction of non spécifié shoulder, subsequent encounter','External constriction of unspecified shoulder, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S40.249D'),
('External constriction of non spécifié shoulder, sequela','External constriction of unspecified shoulder, sequela','Traumatismes, empoisonnements et autres causes externes','S40.249S'),
('Superficial foreign body of right shoulder, initial encounter','Superficial foreign body of right shoulder, initial encounter','Traumatismes, empoisonnements et autres causes externes','S40.251A'),
('Superficial foreign body of right shoulder, subsequent encounter','Superficial foreign body of right shoulder, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S40.251D'),
('Superficial foreign body of right shoulder, sequela','Superficial foreign body of right shoulder, sequela','Traumatismes, empoisonnements et autres causes externes','S40.251S'),
('Superficial foreign body of left shoulder, initial encounter','Superficial foreign body of left shoulder, initial encounter','Traumatismes, empoisonnements et autres causes externes','S40.252A'),
('Superficial foreign body of left shoulder, subsequent encounter','Superficial foreign body of left shoulder, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S40.252D'),
('Superficial foreign body of left shoulder, sequela','Superficial foreign body of left shoulder, sequela','Traumatismes, empoisonnements et autres causes externes','S40.252S'),
('Superficial foreign body of non spécifié shoulder, initial encounter','Superficial foreign body of unspecified shoulder, initial encounter','Traumatismes, empoisonnements et autres causes externes','S40.259A'),
('Superficial foreign body of non spécifié shoulder, subsequent encounter','Superficial foreign body of unspecified shoulder, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S40.259D'),
('Superficial foreign body of non spécifié shoulder, sequela','Superficial foreign body of unspecified shoulder, sequela','Traumatismes, empoisonnements et autres causes externes','S40.259S'),
('Insect bite (nonvenomous) of right shoulder, initial encounter','Insect bite (nonvenomous) of right shoulder, initial encounter','Traumatismes, empoisonnements et autres causes externes','S40.261A'),
('Insect bite (nonvenomous) of right shoulder, subsequent encounter','Insect bite (nonvenomous) of right shoulder, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S40.261D'),
('Insect bite (nonvenomous) of right shoulder, sequela','Insect bite (nonvenomous) of right shoulder, sequela','Traumatismes, empoisonnements et autres causes externes','S40.261S'),
('Insect bite (nonvenomous) of left shoulder, initial encounter','Insect bite (nonvenomous) of left shoulder, initial encounter','Traumatismes, empoisonnements et autres causes externes','S40.262A'),
('Insect bite (nonvenomous) of left shoulder, subsequent encounter','Insect bite (nonvenomous) of left shoulder, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S40.262D'),
('Insect bite (nonvenomous) of left shoulder, sequela','Insect bite (nonvenomous) of left shoulder, sequela','Traumatismes, empoisonnements et autres causes externes','S40.262S'),
('Insect bite (nonvenomous) of non spécifié shoulder, initial encounter','Insect bite (nonvenomous) of unspecified shoulder, initial encounter','Traumatismes, empoisonnements et autres causes externes','S40.269A'),
('Insect bite (nonvenomous) of non spécifié shoulder, subsequent encounter','Insect bite (nonvenomous) of unspecified shoulder, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S40.269D'),
('Insect bite (nonvenomous) of non spécifié shoulder, sequela','Insect bite (nonvenomous) of unspecified shoulder, sequela','Traumatismes, empoisonnements et autres causes externes','S40.269S'),
('autre superficial bite of right shoulder, initial encounter','Other superficial bite of right shoulder, initial encounter','Traumatismes, empoisonnements et autres causes externes','S40.271A'),
('autre superficial bite of right shoulder, subsequent encounter','Other superficial bite of right shoulder, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S40.271D'),
('autre superficial bite of right shoulder, sequela','Other superficial bite of right shoulder, sequela','Traumatismes, empoisonnements et autres causes externes','S40.271S'),
('autre superficial bite of left shoulder, initial encounter','Other superficial bite of left shoulder, initial encounter','Traumatismes, empoisonnements et autres causes externes','S40.272A'),
('autre superficial bite of left shoulder, subsequent encounter','Other superficial bite of left shoulder, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S40.272D'),
('autre superficial bite of left shoulder, sequela','Other superficial bite of left shoulder, sequela','Traumatismes, empoisonnements et autres causes externes','S40.272S'),
('autre superficial bite of non spécifié shoulder, initial encounter','Other superficial bite of unspecified shoulder, initial encounter','Traumatismes, empoisonnements et autres causes externes','S40.279A'),
('autre superficial bite of non spécifié shoulder, subsequent encounter','Other superficial bite of unspecified shoulder, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S40.279D'),
('autre superficial bite of non spécifié shoulder, sequela','Other superficial bite of unspecified shoulder, sequela','Traumatismes, empoisonnements et autres causes externes','S40.279S'),
('Abrasion of right upper arm, initial encounter','Abrasion of right upper arm, initial encounter','Traumatismes, empoisonnements et autres causes externes','S40.811A'),
('Abrasion of right upper arm, subsequent encounter','Abrasion of right upper arm, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S40.811D'),
('Abrasion of right upper arm, sequela','Abrasion of right upper arm, sequela','Traumatismes, empoisonnements et autres causes externes','S40.811S'),
('Abrasion of left upper arm, initial encounter','Abrasion of left upper arm, initial encounter','Traumatismes, empoisonnements et autres causes externes','S40.812A'),
('Abrasion of left upper arm, subsequent encounter','Abrasion of left upper arm, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S40.812D'),
('Abrasion of left upper arm, sequela','Abrasion of left upper arm, sequela','Traumatismes, empoisonnements et autres causes externes','S40.812S'),
('Abrasion of non spécifié upper arm, initial encounter','Abrasion of unspecified upper arm, initial encounter','Traumatismes, empoisonnements et autres causes externes','S40.819A'),
('Abrasion of non spécifié upper arm, subsequent encounter','Abrasion of unspecified upper arm, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S40.819D'),
('Abrasion of non spécifié upper arm, sequela','Abrasion of unspecified upper arm, sequela','Traumatismes, empoisonnements et autres causes externes','S40.819S'),
('Blister (nonthermal) of right upper arm, initial encounter','Blister (nonthermal) of right upper arm, initial encounter','Traumatismes, empoisonnements et autres causes externes','S40.821A'),
('Blister (nonthermal) of right upper arm, subsequent encounter','Blister (nonthermal) of right upper arm, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S40.821D'),
('Blister (nonthermal) of right upper arm, sequela','Blister (nonthermal) of right upper arm, sequela','Traumatismes, empoisonnements et autres causes externes','S40.821S'),
('Blister (nonthermal) of left upper arm, initial encounter','Blister (nonthermal) of left upper arm, initial encounter','Traumatismes, empoisonnements et autres causes externes','S40.822A'),
('Blister (nonthermal) of left upper arm, subsequent encounter','Blister (nonthermal) of left upper arm, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S40.822D'),
('Blister (nonthermal) of left upper arm, sequela','Blister (nonthermal) of left upper arm, sequela','Traumatismes, empoisonnements et autres causes externes','S40.822S'),
('Blister (nonthermal) of non spécifié upper arm, initial encounter','Blister (nonthermal) of unspecified upper arm, initial encounter','Traumatismes, empoisonnements et autres causes externes','S40.829A'),
('Blister (nonthermal) of non spécifié upper arm, subsequent encounter','Blister (nonthermal) of unspecified upper arm, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S40.829D'),
('Blister (nonthermal) of non spécifié upper arm, sequela','Blister (nonthermal) of unspecified upper arm, sequela','Traumatismes, empoisonnements et autres causes externes','S40.829S'),
('External constriction of right upper arm, initial encounter','External constriction of right upper arm, initial encounter','Traumatismes, empoisonnements et autres causes externes','S40.841A'),
('External constriction of right upper arm, subsequent encounter','External constriction of right upper arm, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S40.841D'),
('External constriction of right upper arm, sequela','External constriction of right upper arm, sequela','Traumatismes, empoisonnements et autres causes externes','S40.841S'),
('External constriction of left upper arm, initial encounter','External constriction of left upper arm, initial encounter','Traumatismes, empoisonnements et autres causes externes','S40.842A'),
('External constriction of left upper arm, subsequent encounter','External constriction of left upper arm, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S40.842D'),
('External constriction of left upper arm, sequela','External constriction of left upper arm, sequela','Traumatismes, empoisonnements et autres causes externes','S40.842S'),
('External constriction of non spécifié upper arm, initial encounter','External constriction of unspecified upper arm, initial encounter','Traumatismes, empoisonnements et autres causes externes','S40.849A'),
('External constriction of non spécifié upper arm, subsequent encounter','External constriction of unspecified upper arm, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S40.849D'),
('External constriction of non spécifié upper arm, sequela','External constriction of unspecified upper arm, sequela','Traumatismes, empoisonnements et autres causes externes','S40.849S'),
('Superficial foreign body of right upper arm, initial encounter','Superficial foreign body of right upper arm, initial encounter','Traumatismes, empoisonnements et autres causes externes','S40.851A'),
('Superficial foreign body of right upper arm, subsequent encounter','Superficial foreign body of right upper arm, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S40.851D'),
('Superficial foreign body of right upper arm, sequela','Superficial foreign body of right upper arm, sequela','Traumatismes, empoisonnements et autres causes externes','S40.851S'),
('Superficial foreign body of left upper arm, initial encounter','Superficial foreign body of left upper arm, initial encounter','Traumatismes, empoisonnements et autres causes externes','S40.852A'),
('Superficial foreign body of left upper arm, subsequent encounter','Superficial foreign body of left upper arm, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S40.852D'),
('Superficial foreign body of left upper arm, sequela','Superficial foreign body of left upper arm, sequela','Traumatismes, empoisonnements et autres causes externes','S40.852S'),
('Superficial foreign body of non spécifié upper arm, initial encounter','Superficial foreign body of unspecified upper arm, initial encounter','Traumatismes, empoisonnements et autres causes externes','S40.859A'),
('Superficial foreign body of non spécifié upper arm, subsequent encounter','Superficial foreign body of unspecified upper arm, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S40.859D'),
('Superficial foreign body of non spécifié upper arm, sequela','Superficial foreign body of unspecified upper arm, sequela','Traumatismes, empoisonnements et autres causes externes','S40.859S'),
('Insect bite (nonvenomous) of right upper arm, initial encounter','Insect bite (nonvenomous) of right upper arm, initial encounter','Traumatismes, empoisonnements et autres causes externes','S40.861A'),
('Insect bite (nonvenomous) of right upper arm, subsequent encounter','Insect bite (nonvenomous) of right upper arm, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S40.861D'),
('Insect bite (nonvenomous) of right upper arm, sequela','Insect bite (nonvenomous) of right upper arm, sequela','Traumatismes, empoisonnements et autres causes externes','S40.861S'),
('Insect bite (nonvenomous) of left upper arm, initial encounter','Insect bite (nonvenomous) of left upper arm, initial encounter','Traumatismes, empoisonnements et autres causes externes','S40.862A'),
('Insect bite (nonvenomous) of left upper arm, subsequent encounter','Insect bite (nonvenomous) of left upper arm, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S40.862D'),
('Insect bite (nonvenomous) of left upper arm, sequela','Insect bite (nonvenomous) of left upper arm, sequela','Traumatismes, empoisonnements et autres causes externes','S40.862S'),
('Insect bite (nonvenomous) of non spécifié upper arm, initial encounter','Insect bite (nonvenomous) of unspecified upper arm, initial encounter','Traumatismes, empoisonnements et autres causes externes','S40.869A'),
('Insect bite (nonvenomous) of non spécifié upper arm, subsequent encounter','Insect bite (nonvenomous) of unspecified upper arm, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S40.869D')
ON CONFLICT (nom_fr) DO NOTHING;
