-- icd10_batch_004.sql (80 rows)
INSERT INTO pathologies (nom_fr, nom_en, categorie, icd10_code)
VALUES
('Lymphocutaneous sporotrichosis','Lymphocutaneous sporotrichosis','Maladies infectieuses et parasitaires','B42.1'),
('Disseminated sporotrichosis','Disseminated sporotrichosis','Maladies infectieuses et parasitaires','B42.7'),
('Cerebral sporotrichosis','Cerebral sporotrichosis','Maladies infectieuses et parasitaires','B42.81'),
('Sporotrichosis arthritis','Sporotrichosis arthritis','Maladies infectieuses et parasitaires','B42.82'),
('autre forms of sporotrichosis','Other forms of sporotrichosis','Maladies infectieuses et parasitaires','B42.89'),
('Sporotrichosis, non spécifié','Sporotrichosis, unspecified','Maladies infectieuses et parasitaires','B42.9'),
('Cutaneous chromomycosis','Cutaneous chromomycosis','Maladies infectieuses et parasitaires','B43.0'),
('Pheomycotic brain abscess','Pheomycotic brain abscess','Maladies infectieuses et parasitaires','B43.1'),
('Subcutaneous pheomycotic abscess and cyst','Subcutaneous pheomycotic abscess and cyst','Maladies infectieuses et parasitaires','B43.2'),
('autre forms of chromomycosis','Other forms of chromomycosis','Maladies infectieuses et parasitaires','B43.8'),
('Chromomycosis, non spécifié','Chromomycosis, unspecified','Maladies infectieuses et parasitaires','B43.9'),
('Invasive pulmonary aspergillosis','Invasive pulmonary aspergillosis','Maladies infectieuses et parasitaires','B44.0'),
('autre pulmonary aspergillosis','Other pulmonary aspergillosis','Maladies infectieuses et parasitaires','B44.1'),
('Tonsillar aspergillosis','Tonsillar aspergillosis','Maladies infectieuses et parasitaires','B44.2'),
('Disseminated aspergillosis','Disseminated aspergillosis','Maladies infectieuses et parasitaires','B44.7'),
('Allergic bronchopulmonary aspergillosis','Allergic bronchopulmonary aspergillosis','Maladies infectieuses et parasitaires','B44.81'),
('autre forms of aspergillosis','Other forms of aspergillosis','Maladies infectieuses et parasitaires','B44.89'),
('Aspergillosis, non spécifié','Aspergillosis, unspecified','Maladies infectieuses et parasitaires','B44.9'),
('Pulmonary cryptococcosis','Pulmonary cryptococcosis','Maladies infectieuses et parasitaires','B45.0'),
('Cerebral cryptococcosis','Cerebral cryptococcosis','Maladies infectieuses et parasitaires','B45.1'),
('Cutaneous cryptococcosis','Cutaneous cryptococcosis','Maladies infectieuses et parasitaires','B45.2'),
('Osseous cryptococcosis','Osseous cryptococcosis','Maladies infectieuses et parasitaires','B45.3'),
('Disseminated cryptococcosis','Disseminated cryptococcosis','Maladies infectieuses et parasitaires','B45.7'),
('autre forms of cryptococcosis','Other forms of cryptococcosis','Maladies infectieuses et parasitaires','B45.8'),
('Cryptococcosis, non spécifié','Cryptococcosis, unspecified','Maladies infectieuses et parasitaires','B45.9'),
('Pulmonary mucormycosis','Pulmonary mucormycosis','Maladies infectieuses et parasitaires','B46.0'),
('Rhinocerebral mucormycosis','Rhinocerebral mucormycosis','Maladies infectieuses et parasitaires','B46.1'),
('Gastrointestinal mucormycosis','Gastrointestinal mucormycosis','Maladies infectieuses et parasitaires','B46.2'),
('Cutaneous mucormycosis','Cutaneous mucormycosis','Maladies infectieuses et parasitaires','B46.3'),
('Disseminated mucormycosis','Disseminated mucormycosis','Maladies infectieuses et parasitaires','B46.4'),
('Mucormycosis, non spécifié','Mucormycosis, unspecified','Maladies infectieuses et parasitaires','B46.5'),
('autre zygomycoses','Other zygomycoses','Maladies infectieuses et parasitaires','B46.8'),
('Zygomycosis, non spécifié','Zygomycosis, unspecified','Maladies infectieuses et parasitaires','B46.9'),
('Eumycetoma','Eumycetoma','Maladies infectieuses et parasitaires','B47.0'),
('Actinomycetoma','Actinomycetoma','Maladies infectieuses et parasitaires','B47.1'),
('Mycetoma, non spécifié','Mycetoma, unspecified','Maladies infectieuses et parasitaires','B47.9'),
('Lobomycosis','Lobomycosis','Maladies infectieuses et parasitaires','B48.0'),
('Rhinosporidiosis','Rhinosporidiosis','Maladies infectieuses et parasitaires','B48.1'),
('Allescheriasis','Allescheriasis','Maladies infectieuses et parasitaires','B48.2'),
('Geotrichosis','Geotrichosis','Maladies infectieuses et parasitaires','B48.3'),
('Penicillosis','Penicillosis','Maladies infectieuses et parasitaires','B48.4'),
('autre specified mycoses','Other specified mycoses','Maladies infectieuses et parasitaires','B48.8'),
('non spécifié mycosis','Unspecified mycosis','Maladies infectieuses et parasitaires','B49'),
('Plasmodium falciparum malaria with cerebral complications','Plasmodium falciparum malaria with cerebral complications','Maladies infectieuses et parasitaires','B50.0'),
('autre severe and complicated Plasmodium falciparum malaria','Other severe and complicated Plasmodium falciparum malaria','Maladies infectieuses et parasitaires','B50.8'),
('Plasmodium falciparum malaria, non spécifié','Plasmodium falciparum malaria, unspecified','Maladies infectieuses et parasitaires','B50.9'),
('Plasmodium vivax malaria with rupture of spleen','Plasmodium vivax malaria with rupture of spleen','Maladies infectieuses et parasitaires','B51.0'),
('Plasmodium vivax malaria with autre complications','Plasmodium vivax malaria with other complications','Maladies infectieuses et parasitaires','B51.8'),
('Plasmodium vivax malaria without complication','Plasmodium vivax malaria without complication','Maladies infectieuses et parasitaires','B51.9'),
('Plasmodium malariae malaria with nephropathy','Plasmodium malariae malaria with nephropathy','Maladies infectieuses et parasitaires','B52.0'),
('Plasmodium malariae malaria with autre complications','Plasmodium malariae malaria with other complications','Maladies infectieuses et parasitaires','B52.8'),
('Plasmodium malariae malaria without complication','Plasmodium malariae malaria without complication','Maladies infectieuses et parasitaires','B52.9'),
('Plasmodium ovale malaria','Plasmodium ovale malaria','Maladies infectieuses et parasitaires','B53.0'),
('Paludisme, due to simian plasmodia','Malaria due to simian plasmodia','Maladies infectieuses et parasitaires','B53.1'),
('autre malaria, not elsewhere classified','Other malaria, not elsewhere classified','Maladies infectieuses et parasitaires','B53.8'),
('non spécifié malaria','Unspecified malaria','Maladies infectieuses et parasitaires','B54'),
('Visceral leishmaniasis','Visceral leishmaniasis','Maladies infectieuses et parasitaires','B55.0'),
('Cutaneous leishmaniasis','Cutaneous leishmaniasis','Maladies infectieuses et parasitaires','B55.1'),
('Mucocutaneous leishmaniasis','Mucocutaneous leishmaniasis','Maladies infectieuses et parasitaires','B55.2'),
('Leishmaniasis, non spécifié','Leishmaniasis, unspecified','Maladies infectieuses et parasitaires','B55.9'),
('Gambiense trypanosomiasis','Gambiense trypanosomiasis','Maladies infectieuses et parasitaires','B56.0'),
('Rhodesiense trypanosomiasis','Rhodesiense trypanosomiasis','Maladies infectieuses et parasitaires','B56.1'),
('African trypanosomiasis, non spécifié','African trypanosomiasis, unspecified','Maladies infectieuses et parasitaires','B56.9'),
('aigu Chagas'' maladie with heart involvement','Acute Chagas'' disease with heart involvement','Maladies infectieuses et parasitaires','B57.0'),
('aigu Chagas'' maladie without heart involvement','Acute Chagas'' disease without heart involvement','Maladies infectieuses et parasitaires','B57.1'),
('Chagas'' maladie (chronique) with heart involvement','Chagas'' disease (chronic) with heart involvement','Maladies infectieuses et parasitaires','B57.2'),
('Chagas'' maladie with digestive system involvement, non spécifié','Chagas'' disease with digestive system involvement, unspecified','Maladies infectieuses et parasitaires','B57.30'),
('Megaesophagus in Chagas'' maladie','Megaesophagus in Chagas'' disease','Maladies infectieuses et parasitaires','B57.31'),
('Megacolon in Chagas'' maladie','Megacolon in Chagas'' disease','Maladies infectieuses et parasitaires','B57.32'),
('autre digestive system involvement in Chagas'' maladie','Other digestive system involvement in Chagas'' disease','Maladies infectieuses et parasitaires','B57.39'),
('Chagas'' maladie with nervous system involvement, non spécifié','Chagas'' disease with nervous system involvement, unspecified','Maladies infectieuses et parasitaires','B57.40'),
('Meningitis in Chagas'' maladie','Meningitis in Chagas'' disease','Maladies infectieuses et parasitaires','B57.41'),
('Meningoencephalitis in Chagas'' maladie','Meningoencephalitis in Chagas'' disease','Maladies infectieuses et parasitaires','B57.42'),
('autre nervous system involvement in Chagas'' maladie','Other nervous system involvement in Chagas'' disease','Maladies infectieuses et parasitaires','B57.49'),
('Chagas'' maladie (chronique) with autre organ involvement','Chagas'' disease (chronic) with other organ involvement','Maladies infectieuses et parasitaires','B57.5'),
('Toxoplasma oculopathy, non spécifié','Toxoplasma oculopathy, unspecified','Maladies infectieuses et parasitaires','B58.00'),
('Toxoplasma chorioretinitis','Toxoplasma chorioretinitis','Maladies infectieuses et parasitaires','B58.01'),
('autre toxoplasma oculopathy','Other toxoplasma oculopathy','Maladies infectieuses et parasitaires','B58.09'),
('Toxoplasma hepatitis','Toxoplasma hepatitis','Maladies infectieuses et parasitaires','B58.1'),
('Toxoplasma meningoencephalitis','Toxoplasma meningoencephalitis','Maladies infectieuses et parasitaires','B58.2')
ON CONFLICT (nom_fr) DO NOTHING;
