-- icd10v2_batch_003.sql (80 rows)
INSERT INTO pathologies (nom_fr, nom_en, categorie, icd10_code)
VALUES
('autre forms of anthrax','Other forms of anthrax','Maladies infectieuses et parasitaires','A22.8'),
('Anthrax, non spécifié','Anthrax, unspecified','Maladies infectieuses et parasitaires','A22.9'),
('Brucellosis due to Brucella melitensis','Brucellosis due to Brucella melitensis','Maladies infectieuses et parasitaires','A23.0'),
('Brucellosis due to Brucella abortus','Brucellosis due to Brucella abortus','Maladies infectieuses et parasitaires','A23.1'),
('Brucellosis due to Brucella suis','Brucellosis due to Brucella suis','Maladies infectieuses et parasitaires','A23.2'),
('Brucellosis due to Brucella canis','Brucellosis due to Brucella canis','Maladies infectieuses et parasitaires','A23.3'),
('autre brucellosis','Other brucellosis','Maladies infectieuses et parasitaires','A23.8'),
('Brucellosis, non spécifié','Brucellosis, unspecified','Maladies infectieuses et parasitaires','A23.9'),
('Glanders','Glanders','Maladies infectieuses et parasitaires','A24.0'),
('aigu and fulminating melioidosis','Acute and fulminating melioidosis','Maladies infectieuses et parasitaires','A24.1'),
('Subacute and chronique melioidosis','Subacute and chronic melioidosis','Maladies infectieuses et parasitaires','A24.2'),
('autre melioidosis','Other melioidosis','Maladies infectieuses et parasitaires','A24.3'),
('Melioidosis, non spécifié','Melioidosis, unspecified','Maladies infectieuses et parasitaires','A24.9'),
('Spirillosis','Spirillosis','Maladies infectieuses et parasitaires','A25.0'),
('Streptobacillosis','Streptobacillosis','Maladies infectieuses et parasitaires','A25.1'),
('Rat-bite fever, non spécifié','Rat-bite fever, unspecified','Maladies infectieuses et parasitaires','A25.9'),
('Cutaneous erysipeloid','Cutaneous erysipeloid','Maladies infectieuses et parasitaires','A26.0'),
('Erysipelothrix sepsis','Erysipelothrix sepsis','Maladies infectieuses et parasitaires','A26.7'),
('autre forms of erysipeloid','Other forms of erysipeloid','Maladies infectieuses et parasitaires','A26.8'),
('Erysipeloid, non spécifié','Erysipeloid, unspecified','Maladies infectieuses et parasitaires','A26.9'),
('Leptospirosis icterohemorrhagica','Leptospirosis icterohemorrhagica','Maladies infectieuses et parasitaires','A27.0'),
('Aseptic meningitis in leptospirosis','Aseptic meningitis in leptospirosis','Maladies infectieuses et parasitaires','A27.81'),
('autre forms of leptospirosis','Other forms of leptospirosis','Maladies infectieuses et parasitaires','A27.89'),
('Leptospirosis, non spécifié','Leptospirosis, unspecified','Maladies infectieuses et parasitaires','A27.9'),
('Pasteurellosis','Pasteurellosis','Maladies infectieuses et parasitaires','A28.0'),
('Cat-scratch maladie','Cat-scratch disease','Maladies infectieuses et parasitaires','A28.1'),
('Extraintestinal yersiniosis','Extraintestinal yersiniosis','Maladies infectieuses et parasitaires','A28.2'),
('autre specified zoonotic bacterial diseases, not elsewhere classified','Other specified zoonotic bacterial diseases, not elsewhere classified','Maladies infectieuses et parasitaires','A28.8'),
('Zoonotic bacterial maladie, non spécifié','Zoonotic bacterial disease, unspecified','Maladies infectieuses et parasitaires','A28.9'),
('Maladie rénale chronique, stage 3a','Chronic kidney disease, stage 3a','Maladies de l''appareil génito-urinaire','N18.31'),
('Maternal care for Anti-A sensitization, first trimester, fetus 3','Maternal care for Anti-A sensitization, first trimester, fetus 3','Grossesse, accouchement et puerpéralité','O36.1113'),
('Maternal care for Anti-A sensitization, second trimester, fetus 3','Maternal care for Anti-A sensitization, second trimester, fetus 3','Grossesse, accouchement et puerpéralité','O36.1123'),
('Maternal care for Anti-A sensitization, third trimester, fetus 3','Maternal care for Anti-A sensitization, third trimester, fetus 3','Grossesse, accouchement et puerpéralité','O36.1133'),
('Maternal care for Anti-A sensitization, non spécifié trimester, fetus 3','Maternal care for Anti-A sensitization, unspecified trimester, fetus 3','Grossesse, accouchement et puerpéralité','O36.1193'),
('Person injured while boarding or alighting from a 3- or 4- wheeled all-terrain vehicle (ATV), sequela','Person injured while boarding or alighting from a 3- or 4- wheeled all-terrain vehicle (ATV), sequela','Causes externes de morbidité et de mortalité','V86.45XS'),
('Person injured while boarding or alighting from a 3- or 4- wheeled all-terrain vehicle (ATV), initial encounter','Person injured while boarding or alighting from a 3- or 4- wheeled all-terrain vehicle (ATV), initial encounter','Causes externes de morbidité et de mortalité','V86.45XA'),
('Person injured while boarding or alighting from a 3- or 4- wheeled all-terrain vehicle (ATV), subsequent encounter','Person injured while boarding or alighting from a 3- or 4- wheeled all-terrain vehicle (ATV), subsequent encounter','Causes externes de morbidité et de mortalité','V86.45XD'),
('Indeterminate leprosy','Indeterminate leprosy','Maladies infectieuses et parasitaires','A30.0'),
('Tuberculoid leprosy','Tuberculoid leprosy','Maladies infectieuses et parasitaires','A30.1'),
('Borderline tuberculoid leprosy','Borderline tuberculoid leprosy','Maladies infectieuses et parasitaires','A30.2'),
('Borderline leprosy','Borderline leprosy','Maladies infectieuses et parasitaires','A30.3'),
('Borderline lepromatous leprosy','Borderline lepromatous leprosy','Maladies infectieuses et parasitaires','A30.4'),
('Lepromatous leprosy','Lepromatous leprosy','Maladies infectieuses et parasitaires','A30.5'),
('autre forms of leprosy','Other forms of leprosy','Maladies infectieuses et parasitaires','A30.8'),
('Leprosy, non spécifié','Leprosy, unspecified','Maladies infectieuses et parasitaires','A30.9'),
('Pulmonary mycobacterial infection','Pulmonary mycobacterial infection','Maladies infectieuses et parasitaires','A31.0'),
('Cutaneous mycobacterial infection','Cutaneous mycobacterial infection','Maladies infectieuses et parasitaires','A31.1'),
('Disseminated mycobacterium avium-intracellulare complex (DMAC)','Disseminated mycobacterium avium-intracellulare complex (DMAC)','Maladies infectieuses et parasitaires','A31.2'),
('autre mycobacterial infections','Other mycobacterial infections','Maladies infectieuses et parasitaires','A31.8'),
('Mycobacterial infection, non spécifié','Mycobacterial infection, unspecified','Maladies infectieuses et parasitaires','A31.9'),
('Cutaneous listeriosis','Cutaneous listeriosis','Maladies infectieuses et parasitaires','A32.0'),
('Listerial meningitis','Listerial meningitis','Maladies infectieuses et parasitaires','A32.11'),
('Listerial meningoencephalitis','Listerial meningoencephalitis','Maladies infectieuses et parasitaires','A32.12'),
('Listerial sepsis','Listerial sepsis','Maladies infectieuses et parasitaires','A32.7'),
('Oculoglandular listeriosis','Oculoglandular listeriosis','Maladies infectieuses et parasitaires','A32.81'),
('Listerial endocarditis','Listerial endocarditis','Maladies infectieuses et parasitaires','A32.82'),
('autre forms of listeriosis','Other forms of listeriosis','Maladies infectieuses et parasitaires','A32.89'),
('Listeriosis, non spécifié','Listeriosis, unspecified','Maladies infectieuses et parasitaires','A32.9'),
('Tetanus neonatorum','Tetanus neonatorum','Maladies infectieuses et parasitaires','A33'),
('Obstetrical tetanus','Obstetrical tetanus','Maladies infectieuses et parasitaires','A34'),
('autre tetanus','Other tetanus','Maladies infectieuses et parasitaires','A35'),
('Pharyngeal diphtheria','Pharyngeal diphtheria','Maladies infectieuses et parasitaires','A36.0'),
('Nasopharyngeal diphtheria','Nasopharyngeal diphtheria','Maladies infectieuses et parasitaires','A36.1'),
('Laryngeal diphtheria','Laryngeal diphtheria','Maladies infectieuses et parasitaires','A36.2'),
('Cutaneous diphtheria','Cutaneous diphtheria','Maladies infectieuses et parasitaires','A36.3'),
('Diphtheritic cardiomyopathy','Diphtheritic cardiomyopathy','Maladies infectieuses et parasitaires','A36.81'),
('Diphtheritic radiculomyelitis','Diphtheritic radiculomyelitis','Maladies infectieuses et parasitaires','A36.82'),
('Diphtheritic polyneuritis','Diphtheritic polyneuritis','Maladies infectieuses et parasitaires','A36.83'),
('Diphtheritic tubulo-interstitial nephropathy','Diphtheritic tubulo-interstitial nephropathy','Maladies infectieuses et parasitaires','A36.84'),
('Diphtheritic cystitis','Diphtheritic cystitis','Maladies infectieuses et parasitaires','A36.85'),
('Diphtheritic conjunctivitis','Diphtheritic conjunctivitis','Maladies infectieuses et parasitaires','A36.86'),
('autre diphtheritic complications','Other diphtheritic complications','Maladies infectieuses et parasitaires','A36.89'),
('Diphtheria, non spécifié','Diphtheria, unspecified','Maladies infectieuses et parasitaires','A36.9'),
('Whooping cough due to Bordetella pertussis without pneumonia','Whooping cough due to Bordetella pertussis without pneumonia','Maladies infectieuses et parasitaires','A37.00'),
('Whooping cough due to Bordetella pertussis with pneumonia','Whooping cough due to Bordetella pertussis with pneumonia','Maladies infectieuses et parasitaires','A37.01'),
('Whooping cough due to Bordetella parapertussis without pneumonia','Whooping cough due to Bordetella parapertussis without pneumonia','Maladies infectieuses et parasitaires','A37.10'),
('Whooping cough due to Bordetella parapertussis with pneumonia','Whooping cough due to Bordetella parapertussis with pneumonia','Maladies infectieuses et parasitaires','A37.11'),
('Whooping cough due to autre Bordetella species without pneumonia','Whooping cough due to other Bordetella species without pneumonia','Maladies infectieuses et parasitaires','A37.80'),
('Whooping cough due to autre Bordetella species with pneumonia','Whooping cough due to other Bordetella species with pneumonia','Maladies infectieuses et parasitaires','A37.81'),
('Whooping cough, non spécifié species without pneumonia','Whooping cough, unspecified species without pneumonia','Maladies infectieuses et parasitaires','A37.90')
ON CONFLICT (nom_fr) DO NOTHING;
