-- icd10v2_batch_006.sql (80 rows)
INSERT INTO pathologies (nom_fr, nom_en, categorie, icd10_code)
VALUES
('Syphilis, non spécifié','Syphilis, unspecified','Maladies infectieuses et parasitaires','A53.9'),
('Gonococcal infection of lower genitourinary tract, non spécifié','Gonococcal infection of lower genitourinary tract, unspecified','Maladies infectieuses et parasitaires','A54.00'),
('Gonococcal cystitis and urethritis, non spécifié','Gonococcal cystitis and urethritis, unspecified','Maladies infectieuses et parasitaires','A54.01'),
('Gonococcal vulvovaginitis, non spécifié','Gonococcal vulvovaginitis, unspecified','Maladies infectieuses et parasitaires','A54.02'),
('Gonococcal cervicitis, non spécifié','Gonococcal cervicitis, unspecified','Maladies infectieuses et parasitaires','A54.03'),
('autre gonococcal infection of lower genitourinary tract','Other gonococcal infection of lower genitourinary tract','Maladies infectieuses et parasitaires','A54.09'),
('Gonococcal infection of lower genitourinary tract with periurethral and accessory gland abscess','Gonococcal infection of lower genitourinary tract with periurethral and accessory gland abscess','Maladies infectieuses et parasitaires','A54.1'),
('Gonococcal infection of kidney and ureter','Gonococcal infection of kidney and ureter','Maladies infectieuses et parasitaires','A54.21'),
('Gonococcal prostatitis','Gonococcal prostatitis','Maladies infectieuses et parasitaires','A54.22'),
('Gonococcal infection of autre male genital organs','Gonococcal infection of other male genital organs','Maladies infectieuses et parasitaires','A54.23'),
('Gonococcal female pelvic inflammatory maladie','Gonococcal female pelvic inflammatory disease','Maladies infectieuses et parasitaires','A54.24'),
('autre gonococcal genitourinary infections','Other gonococcal genitourinary infections','Maladies infectieuses et parasitaires','A54.29'),
('Gonococcal infection of eye, non spécifié','Gonococcal infection of eye, unspecified','Maladies infectieuses et parasitaires','A54.30'),
('Gonococcal conjunctivitis','Gonococcal conjunctivitis','Maladies infectieuses et parasitaires','A54.31'),
('Gonococcal iridocyclitis','Gonococcal iridocyclitis','Maladies infectieuses et parasitaires','A54.32'),
('Gonococcal keratitis','Gonococcal keratitis','Maladies infectieuses et parasitaires','A54.33'),
('autre gonococcal eye infection','Other gonococcal eye infection','Maladies infectieuses et parasitaires','A54.39'),
('Gonococcal infection of musculoskeletal system, non spécifié','Gonococcal infection of musculoskeletal system, unspecified','Maladies infectieuses et parasitaires','A54.40'),
('Gonococcal spondylopathy','Gonococcal spondylopathy','Maladies infectieuses et parasitaires','A54.41'),
('Gonococcal arthritis','Gonococcal arthritis','Maladies infectieuses et parasitaires','A54.42'),
('Gonococcal osteomyelitis','Gonococcal osteomyelitis','Maladies infectieuses et parasitaires','A54.43'),
('Gonococcal infection of autre musculoskeletal tissue','Gonococcal infection of other musculoskeletal tissue','Maladies infectieuses et parasitaires','A54.49'),
('Gonococcal pharyngitis','Gonococcal pharyngitis','Maladies infectieuses et parasitaires','A54.5'),
('Gonococcal infection of anus and rectum','Gonococcal infection of anus and rectum','Maladies infectieuses et parasitaires','A54.6'),
('Gonococcal meningitis','Gonococcal meningitis','Maladies infectieuses et parasitaires','A54.81'),
('Gonococcal brain abscess','Gonococcal brain abscess','Maladies infectieuses et parasitaires','A54.82'),
('Gonococcal heart infection','Gonococcal heart infection','Maladies infectieuses et parasitaires','A54.83'),
('Gonococcal pneumonia','Gonococcal pneumonia','Maladies infectieuses et parasitaires','A54.84'),
('Gonococcal peritonitis','Gonococcal peritonitis','Maladies infectieuses et parasitaires','A54.85'),
('Gonococcal sepsis','Gonococcal sepsis','Maladies infectieuses et parasitaires','A54.86'),
('autre gonococcal infections','Other gonococcal infections','Maladies infectieuses et parasitaires','A54.89'),
('Gonococcal infection, non spécifié','Gonococcal infection, unspecified','Maladies infectieuses et parasitaires','A54.9'),
('Chlamydial lymphogranuloma (venereum)','Chlamydial lymphogranuloma (venereum)','Maladies infectieuses et parasitaires','A55'),
('Chlamydial infection of lower genitourinary tract, non spécifié','Chlamydial infection of lower genitourinary tract, unspecified','Maladies infectieuses et parasitaires','A56.00'),
('Chlamydial cystitis and urethritis','Chlamydial cystitis and urethritis','Maladies infectieuses et parasitaires','A56.01'),
('Chlamydial vulvovaginitis','Chlamydial vulvovaginitis','Maladies infectieuses et parasitaires','A56.02'),
('autre chlamydial infection of lower genitourinary tract','Other chlamydial infection of lower genitourinary tract','Maladies infectieuses et parasitaires','A56.09'),
('Chlamydial female pelvic inflammatory maladie','Chlamydial female pelvic inflammatory disease','Maladies infectieuses et parasitaires','A56.11'),
('autre chlamydial genitourinary infection','Other chlamydial genitourinary infection','Maladies infectieuses et parasitaires','A56.19'),
('Chlamydial infection of genitourinary tract, non spécifié','Chlamydial infection of genitourinary tract, unspecified','Maladies infectieuses et parasitaires','A56.2'),
('Chlamydial infection of anus and rectum','Chlamydial infection of anus and rectum','Maladies infectieuses et parasitaires','A56.3'),
('Chlamydial infection of pharynx','Chlamydial infection of pharynx','Maladies infectieuses et parasitaires','A56.4'),
('Sexually transmitted chlamydial infection of autre sites','Sexually transmitted chlamydial infection of other sites','Maladies infectieuses et parasitaires','A56.8'),
('Chancroid','Chancroid','Maladies infectieuses et parasitaires','A57'),
('Granuloma inguinale','Granuloma inguinale','Maladies infectieuses et parasitaires','A58'),
('Urogenital trichomoniasis, non spécifié','Urogenital trichomoniasis, unspecified','Maladies infectieuses et parasitaires','A59.00'),
('Trichomonal vulvovaginitis','Trichomonal vulvovaginitis','Maladies infectieuses et parasitaires','A59.01'),
('Trichomonal prostatitis','Trichomonal prostatitis','Maladies infectieuses et parasitaires','A59.02'),
('Trichomonal cystitis and urethritis','Trichomonal cystitis and urethritis','Maladies infectieuses et parasitaires','A59.03'),
('autre urogenital trichomoniasis','Other urogenital trichomoniasis','Maladies infectieuses et parasitaires','A59.09'),
('Trichomoniasis of autre sites','Trichomoniasis of other sites','Maladies infectieuses et parasitaires','A59.8'),
('Trichomoniasis, non spécifié','Trichomoniasis, unspecified','Maladies infectieuses et parasitaires','A59.9'),
('Herpesviral infection of urogenital system, non spécifié','Herpesviral infection of urogenital system, unspecified','Maladies infectieuses et parasitaires','A60.00'),
('Herpesviral infection of penis','Herpesviral infection of penis','Maladies infectieuses et parasitaires','A60.01'),
('Herpesviral infection of autre male genital organs','Herpesviral infection of other male genital organs','Maladies infectieuses et parasitaires','A60.02'),
('Herpesviral cervicitis','Herpesviral cervicitis','Maladies infectieuses et parasitaires','A60.03'),
('Herpesviral vulvovaginitis','Herpesviral vulvovaginitis','Maladies infectieuses et parasitaires','A60.04'),
('Herpesviral infection of autre urogenital tract','Herpesviral infection of other urogenital tract','Maladies infectieuses et parasitaires','A60.09'),
('Herpesviral infection of perianal skin and rectum','Herpesviral infection of perianal skin and rectum','Maladies infectieuses et parasitaires','A60.1'),
('Anogenital herpesviral infection, non spécifié','Anogenital herpesviral infection, unspecified','Maladies infectieuses et parasitaires','A60.9'),
('Anogenital (venereal) warts','Anogenital (venereal) warts','Maladies infectieuses et parasitaires','A63.0'),
('autre specified predominantly sexually transmitted diseases','Other specified predominantly sexually transmitted diseases','Maladies infectieuses et parasitaires','A63.8'),
('non spécifié sexually transmitted maladie','Unspecified sexually transmitted disease','Maladies infectieuses et parasitaires','A64'),
('Nonvenereal syphilis','Nonvenereal syphilis','Maladies infectieuses et parasitaires','A65'),
('Initial lesions of yaws','Initial lesions of yaws','Maladies infectieuses et parasitaires','A66.0'),
('Multiple papillomata and wet crab yaws','Multiple papillomata and wet crab yaws','Maladies infectieuses et parasitaires','A66.1'),
('autre early skin lesions of yaws','Other early skin lesions of yaws','Maladies infectieuses et parasitaires','A66.2'),
('Hyperkeratosis of yaws','Hyperkeratosis of yaws','Maladies infectieuses et parasitaires','A66.3'),
('Gummata and ulcers of yaws','Gummata and ulcers of yaws','Maladies infectieuses et parasitaires','A66.4'),
('Gangosa','Gangosa','Maladies infectieuses et parasitaires','A66.5'),
('Bone and joint lesions of yaws','Bone and joint lesions of yaws','Maladies infectieuses et parasitaires','A66.6'),
('autre manifestations of yaws','Other manifestations of yaws','Maladies infectieuses et parasitaires','A66.7'),
('Latent yaws','Latent yaws','Maladies infectieuses et parasitaires','A66.8'),
('Yaws, non spécifié','Yaws, unspecified','Maladies infectieuses et parasitaires','A66.9'),
('primitif lesions of pinta','Primary lesions of pinta','Maladies infectieuses et parasitaires','A67.0'),
('Intermediate lesions of pinta','Intermediate lesions of pinta','Maladies infectieuses et parasitaires','A67.1'),
('Late lesions of pinta','Late lesions of pinta','Maladies infectieuses et parasitaires','A67.2'),
('Mixed lesions of pinta','Mixed lesions of pinta','Maladies infectieuses et parasitaires','A67.3'),
('Pinta, non spécifié','Pinta, unspecified','Maladies infectieuses et parasitaires','A67.9'),
('Louse-borne relapsing fever','Louse-borne relapsing fever','Maladies infectieuses et parasitaires','A68.0')
ON CONFLICT (nom_fr) DO NOTHING;
