-- icd10v2_batch_195.sql (80 rows)
INSERT INTO pathologies (nom_fr, nom_en, categorie, icd10_code)
VALUES
('Trochanteric bursitis, left hip','Trochanteric bursitis, left hip','Maladies de l''appareil locomoteur','M70.62'),
('autre bursitis of hip, non spécifié hip','Other bursitis of hip, unspecified hip','Maladies de l''appareil locomoteur','M70.70'),
('autre bursitis of hip, right hip','Other bursitis of hip, right hip','Maladies de l''appareil locomoteur','M70.71'),
('autre bursitis of hip, left hip','Other bursitis of hip, left hip','Maladies de l''appareil locomoteur','M70.72'),
('autre soft tissue disorders related to use, overuse and pressure of non spécifié site','Other soft tissue disorders related to use, overuse and pressure of unspecified site','Maladies de l''appareil locomoteur','M70.80'),
('autre soft tissue disorders related to use, overuse and pressure, right shoulder','Other soft tissue disorders related to use, overuse and pressure, right shoulder','Maladies de l''appareil locomoteur','M70.811'),
('autre soft tissue disorders related to use, overuse and pressure, left shoulder','Other soft tissue disorders related to use, overuse and pressure, left shoulder','Maladies de l''appareil locomoteur','M70.812'),
('autre soft tissue disorders related to use, overuse and pressure, non spécifié shoulder','Other soft tissue disorders related to use, overuse and pressure, unspecified shoulder','Maladies de l''appareil locomoteur','M70.819'),
('autre soft tissue disorders related to use, overuse and pressure, right upper arm','Other soft tissue disorders related to use, overuse and pressure, right upper arm','Maladies de l''appareil locomoteur','M70.821'),
('autre soft tissue disorders related to use, overuse and pressure, left upper arm','Other soft tissue disorders related to use, overuse and pressure, left upper arm','Maladies de l''appareil locomoteur','M70.822'),
('autre soft tissue disorders related to use, overuse and pressure, non spécifié upper arms','Other soft tissue disorders related to use, overuse and pressure, unspecified upper arms','Maladies de l''appareil locomoteur','M70.829'),
('autre soft tissue disorders related to use, overuse and pressure, right forearm','Other soft tissue disorders related to use, overuse and pressure, right forearm','Maladies de l''appareil locomoteur','M70.831'),
('autre soft tissue disorders related to use, overuse and pressure, left forearm','Other soft tissue disorders related to use, overuse and pressure, left forearm','Maladies de l''appareil locomoteur','M70.832'),
('autre soft tissue disorders related to use, overuse and pressure, non spécifié forearm','Other soft tissue disorders related to use, overuse and pressure, unspecified forearm','Maladies de l''appareil locomoteur','M70.839'),
('autre soft tissue disorders related to use, overuse and pressure, right hand','Other soft tissue disorders related to use, overuse and pressure, right hand','Maladies de l''appareil locomoteur','M70.841'),
('autre soft tissue disorders related to use, overuse and pressure, left hand','Other soft tissue disorders related to use, overuse and pressure, left hand','Maladies de l''appareil locomoteur','M70.842'),
('autre soft tissue disorders related to use, overuse and pressure, non spécifié hand','Other soft tissue disorders related to use, overuse and pressure, unspecified hand','Maladies de l''appareil locomoteur','M70.849'),
('autre soft tissue disorders related to use, overuse and pressure, right thigh','Other soft tissue disorders related to use, overuse and pressure, right thigh','Maladies de l''appareil locomoteur','M70.851'),
('autre soft tissue disorders related to use, overuse and pressure, left thigh','Other soft tissue disorders related to use, overuse and pressure, left thigh','Maladies de l''appareil locomoteur','M70.852'),
('autre soft tissue disorders related to use, overuse and pressure, non spécifié thigh','Other soft tissue disorders related to use, overuse and pressure, unspecified thigh','Maladies de l''appareil locomoteur','M70.859'),
('autre soft tissue disorders related to use, overuse and pressure, right lower leg','Other soft tissue disorders related to use, overuse and pressure, right lower leg','Maladies de l''appareil locomoteur','M70.861'),
('autre soft tissue disorders related to use, overuse and pressure, left lower leg','Other soft tissue disorders related to use, overuse and pressure, left lower leg','Maladies de l''appareil locomoteur','M70.862'),
('autre soft tissue disorders related to use, overuse and pressure, non spécifié leg','Other soft tissue disorders related to use, overuse and pressure, unspecified leg','Maladies de l''appareil locomoteur','M70.869'),
('autre soft tissue disorders related to use, overuse and pressure, right ankle and foot','Other soft tissue disorders related to use, overuse and pressure, right ankle and foot','Maladies de l''appareil locomoteur','M70.871'),
('autre soft tissue disorders related to use, overuse and pressure, left ankle and foot','Other soft tissue disorders related to use, overuse and pressure, left ankle and foot','Maladies de l''appareil locomoteur','M70.872'),
('autre soft tissue disorders related to use, overuse and pressure, non spécifié ankle and foot','Other soft tissue disorders related to use, overuse and pressure, unspecified ankle and foot','Maladies de l''appareil locomoteur','M70.879'),
('autre soft tissue disorders related to use, overuse and pressure autre site','Other soft tissue disorders related to use, overuse and pressure other site','Maladies de l''appareil locomoteur','M70.88'),
('autre soft tissue disorders related to use, overuse and pressure multiple sites','Other soft tissue disorders related to use, overuse and pressure multiple sites','Maladies de l''appareil locomoteur','M70.89'),
('non spécifié soft tissue trouble related to use, overuse and pressure of non spécifié site','Unspecified soft tissue disorder related to use, overuse and pressure of unspecified site','Maladies de l''appareil locomoteur','M70.90'),
('non spécifié soft tissue trouble related to use, overuse and pressure, right shoulder','Unspecified soft tissue disorder related to use, overuse and pressure, right shoulder','Maladies de l''appareil locomoteur','M70.911'),
('non spécifié soft tissue trouble related to use, overuse and pressure, left shoulder','Unspecified soft tissue disorder related to use, overuse and pressure, left shoulder','Maladies de l''appareil locomoteur','M70.912'),
('non spécifié soft tissue trouble related to use, overuse and pressure, non spécifié shoulder','Unspecified soft tissue disorder related to use, overuse and pressure, unspecified shoulder','Maladies de l''appareil locomoteur','M70.919'),
('non spécifié soft tissue trouble related to use, overuse and pressure, right upper arm','Unspecified soft tissue disorder related to use, overuse and pressure, right upper arm','Maladies de l''appareil locomoteur','M70.921'),
('non spécifié soft tissue trouble related to use, overuse and pressure, left upper arm','Unspecified soft tissue disorder related to use, overuse and pressure, left upper arm','Maladies de l''appareil locomoteur','M70.922'),
('non spécifié soft tissue trouble related to use, overuse and pressure, non spécifié upper arm','Unspecified soft tissue disorder related to use, overuse and pressure, unspecified upper arm','Maladies de l''appareil locomoteur','M70.929'),
('non spécifié soft tissue trouble related to use, overuse and pressure, right forearm','Unspecified soft tissue disorder related to use, overuse and pressure, right forearm','Maladies de l''appareil locomoteur','M70.931'),
('non spécifié soft tissue trouble related to use, overuse and pressure, left forearm','Unspecified soft tissue disorder related to use, overuse and pressure, left forearm','Maladies de l''appareil locomoteur','M70.932'),
('non spécifié soft tissue trouble related to use, overuse and pressure, non spécifié forearm','Unspecified soft tissue disorder related to use, overuse and pressure, unspecified forearm','Maladies de l''appareil locomoteur','M70.939'),
('non spécifié soft tissue trouble related to use, overuse and pressure, right hand','Unspecified soft tissue disorder related to use, overuse and pressure, right hand','Maladies de l''appareil locomoteur','M70.941'),
('non spécifié soft tissue trouble related to use, overuse and pressure, left hand','Unspecified soft tissue disorder related to use, overuse and pressure, left hand','Maladies de l''appareil locomoteur','M70.942'),
('non spécifié soft tissue trouble related to use, overuse and pressure, non spécifié hand','Unspecified soft tissue disorder related to use, overuse and pressure, unspecified hand','Maladies de l''appareil locomoteur','M70.949'),
('non spécifié soft tissue trouble related to use, overuse and pressure, right thigh','Unspecified soft tissue disorder related to use, overuse and pressure, right thigh','Maladies de l''appareil locomoteur','M70.951'),
('non spécifié soft tissue trouble related to use, overuse and pressure, left thigh','Unspecified soft tissue disorder related to use, overuse and pressure, left thigh','Maladies de l''appareil locomoteur','M70.952'),
('non spécifié soft tissue trouble related to use, overuse and pressure, non spécifié thigh','Unspecified soft tissue disorder related to use, overuse and pressure, unspecified thigh','Maladies de l''appareil locomoteur','M70.959'),
('non spécifié soft tissue trouble related to use, overuse and pressure, right lower leg','Unspecified soft tissue disorder related to use, overuse and pressure, right lower leg','Maladies de l''appareil locomoteur','M70.961'),
('non spécifié soft tissue trouble related to use, overuse and pressure, left lower leg','Unspecified soft tissue disorder related to use, overuse and pressure, left lower leg','Maladies de l''appareil locomoteur','M70.962'),
('non spécifié soft tissue trouble related to use, overuse and pressure, non spécifié lower leg','Unspecified soft tissue disorder related to use, overuse and pressure, unspecified lower leg','Maladies de l''appareil locomoteur','M70.969'),
('non spécifié soft tissue trouble related to use, overuse and pressure, right ankle and foot','Unspecified soft tissue disorder related to use, overuse and pressure, right ankle and foot','Maladies de l''appareil locomoteur','M70.971'),
('non spécifié soft tissue trouble related to use, overuse and pressure, left ankle and foot','Unspecified soft tissue disorder related to use, overuse and pressure, left ankle and foot','Maladies de l''appareil locomoteur','M70.972'),
('non spécifié soft tissue trouble related to use, overuse and pressure, non spécifié ankle and foot','Unspecified soft tissue disorder related to use, overuse and pressure, unspecified ankle and foot','Maladies de l''appareil locomoteur','M70.979'),
('non spécifié soft tissue trouble related to use, overuse and pressure autre','Unspecified soft tissue disorder related to use, overuse and pressure other','Maladies de l''appareil locomoteur','M70.98'),
('non spécifié soft tissue trouble related to use, overuse and pressure multiple sites','Unspecified soft tissue disorder related to use, overuse and pressure multiple sites','Maladies de l''appareil locomoteur','M70.99'),
('Abscess of bursa, non spécifié site','Abscess of bursa, unspecified site','Maladies de l''appareil locomoteur','M71.00'),
('Abscess of bursa, right shoulder','Abscess of bursa, right shoulder','Maladies de l''appareil locomoteur','M71.011'),
('Abscess of bursa, left shoulder','Abscess of bursa, left shoulder','Maladies de l''appareil locomoteur','M71.012'),
('Abscess of bursa, non spécifié shoulder','Abscess of bursa, unspecified shoulder','Maladies de l''appareil locomoteur','M71.019'),
('Abscess of bursa, right elbow','Abscess of bursa, right elbow','Maladies de l''appareil locomoteur','M71.021'),
('Abscess of bursa, left elbow','Abscess of bursa, left elbow','Maladies de l''appareil locomoteur','M71.022'),
('Abscess of bursa, non spécifié elbow','Abscess of bursa, unspecified elbow','Maladies de l''appareil locomoteur','M71.029'),
('Abscess of bursa, right wrist','Abscess of bursa, right wrist','Maladies de l''appareil locomoteur','M71.031'),
('Abscess of bursa, left wrist','Abscess of bursa, left wrist','Maladies de l''appareil locomoteur','M71.032'),
('Abscess of bursa, non spécifié wrist','Abscess of bursa, unspecified wrist','Maladies de l''appareil locomoteur','M71.039'),
('Abscess of bursa, right hand','Abscess of bursa, right hand','Maladies de l''appareil locomoteur','M71.041'),
('Abscess of bursa, left hand','Abscess of bursa, left hand','Maladies de l''appareil locomoteur','M71.042'),
('Abscess of bursa, non spécifié hand','Abscess of bursa, unspecified hand','Maladies de l''appareil locomoteur','M71.049'),
('Abscess of bursa, right hip','Abscess of bursa, right hip','Maladies de l''appareil locomoteur','M71.051'),
('Abscess of bursa, left hip','Abscess of bursa, left hip','Maladies de l''appareil locomoteur','M71.052'),
('Abscess of bursa, non spécifié hip','Abscess of bursa, unspecified hip','Maladies de l''appareil locomoteur','M71.059'),
('Abscess of bursa, right knee','Abscess of bursa, right knee','Maladies de l''appareil locomoteur','M71.061'),
('Abscess of bursa, left knee','Abscess of bursa, left knee','Maladies de l''appareil locomoteur','M71.062'),
('Abscess of bursa, non spécifié knee','Abscess of bursa, unspecified knee','Maladies de l''appareil locomoteur','M71.069'),
('Abscess of bursa, right ankle and foot','Abscess of bursa, right ankle and foot','Maladies de l''appareil locomoteur','M71.071'),
('Abscess of bursa, left ankle and foot','Abscess of bursa, left ankle and foot','Maladies de l''appareil locomoteur','M71.072'),
('Abscess of bursa, non spécifié ankle and foot','Abscess of bursa, unspecified ankle and foot','Maladies de l''appareil locomoteur','M71.079'),
('Abscess of bursa, autre site','Abscess of bursa, other site','Maladies de l''appareil locomoteur','M71.08'),
('Abscess of bursa, multiple sites','Abscess of bursa, multiple sites','Maladies de l''appareil locomoteur','M71.09'),
('autre infective bursitis, non spécifié site','Other infective bursitis, unspecified site','Maladies de l''appareil locomoteur','M71.10'),
('autre infective bursitis, right shoulder','Other infective bursitis, right shoulder','Maladies de l''appareil locomoteur','M71.111'),
('autre infective bursitis, left shoulder','Other infective bursitis, left shoulder','Maladies de l''appareil locomoteur','M71.112'),
('autre infective bursitis, non spécifié shoulder','Other infective bursitis, unspecified shoulder','Maladies de l''appareil locomoteur','M71.119')
ON CONFLICT (nom_fr) DO NOTHING;
