-- icd10v2_batch_323.sql (80 rows)
INSERT INTO pathologies (nom_fr, nom_en, categorie, icd10_code)
VALUES
('Contusion of left knee, sequela','Contusion of left knee, sequela','Traumatismes, empoisonnements et autres causes externes','S80.02XS'),
('Contusion of non spécifié lower leg, initial encounter','Contusion of unspecified lower leg, initial encounter','Traumatismes, empoisonnements et autres causes externes','S80.10XA'),
('Contusion of non spécifié lower leg, subsequent encounter','Contusion of unspecified lower leg, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S80.10XD'),
('Contusion of non spécifié lower leg, sequela','Contusion of unspecified lower leg, sequela','Traumatismes, empoisonnements et autres causes externes','S80.10XS'),
('Contusion of right lower leg, initial encounter','Contusion of right lower leg, initial encounter','Traumatismes, empoisonnements et autres causes externes','S80.11XA'),
('Contusion of right lower leg, subsequent encounter','Contusion of right lower leg, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S80.11XD'),
('Contusion of right lower leg, sequela','Contusion of right lower leg, sequela','Traumatismes, empoisonnements et autres causes externes','S80.11XS'),
('Contusion of left lower leg, initial encounter','Contusion of left lower leg, initial encounter','Traumatismes, empoisonnements et autres causes externes','S80.12XA'),
('Contusion of left lower leg, subsequent encounter','Contusion of left lower leg, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S80.12XD'),
('Contusion of left lower leg, sequela','Contusion of left lower leg, sequela','Traumatismes, empoisonnements et autres causes externes','S80.12XS'),
('Abrasion, right knee, initial encounter','Abrasion, right knee, initial encounter','Traumatismes, empoisonnements et autres causes externes','S80.211A'),
('Abrasion, right knee, subsequent encounter','Abrasion, right knee, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S80.211D'),
('Abrasion, right knee, sequela','Abrasion, right knee, sequela','Traumatismes, empoisonnements et autres causes externes','S80.211S'),
('Abrasion, left knee, initial encounter','Abrasion, left knee, initial encounter','Traumatismes, empoisonnements et autres causes externes','S80.212A'),
('Abrasion, left knee, subsequent encounter','Abrasion, left knee, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S80.212D'),
('Abrasion, left knee, sequela','Abrasion, left knee, sequela','Traumatismes, empoisonnements et autres causes externes','S80.212S'),
('Abrasion, non spécifié knee, initial encounter','Abrasion, unspecified knee, initial encounter','Traumatismes, empoisonnements et autres causes externes','S80.219A'),
('Abrasion, non spécifié knee, subsequent encounter','Abrasion, unspecified knee, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S80.219D'),
('Abrasion, non spécifié knee, sequela','Abrasion, unspecified knee, sequela','Traumatismes, empoisonnements et autres causes externes','S80.219S'),
('Blister (nonthermal), right knee, initial encounter','Blister (nonthermal), right knee, initial encounter','Traumatismes, empoisonnements et autres causes externes','S80.221A'),
('Blister (nonthermal), right knee, subsequent encounter','Blister (nonthermal), right knee, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S80.221D'),
('Blister (nonthermal), right knee, sequela','Blister (nonthermal), right knee, sequela','Traumatismes, empoisonnements et autres causes externes','S80.221S'),
('Blister (nonthermal), left knee, initial encounter','Blister (nonthermal), left knee, initial encounter','Traumatismes, empoisonnements et autres causes externes','S80.222A'),
('Blister (nonthermal), left knee, subsequent encounter','Blister (nonthermal), left knee, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S80.222D'),
('Blister (nonthermal), left knee, sequela','Blister (nonthermal), left knee, sequela','Traumatismes, empoisonnements et autres causes externes','S80.222S'),
('Blister (nonthermal), non spécifié knee, initial encounter','Blister (nonthermal), unspecified knee, initial encounter','Traumatismes, empoisonnements et autres causes externes','S80.229A'),
('Blister (nonthermal), non spécifié knee, subsequent encounter','Blister (nonthermal), unspecified knee, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S80.229D'),
('Blister (nonthermal), non spécifié knee, sequela','Blister (nonthermal), unspecified knee, sequela','Traumatismes, empoisonnements et autres causes externes','S80.229S'),
('External constriction, right knee, initial encounter','External constriction, right knee, initial encounter','Traumatismes, empoisonnements et autres causes externes','S80.241A'),
('External constriction, right knee, subsequent encounter','External constriction, right knee, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S80.241D'),
('External constriction, right knee, sequela','External constriction, right knee, sequela','Traumatismes, empoisonnements et autres causes externes','S80.241S'),
('External constriction, left knee, initial encounter','External constriction, left knee, initial encounter','Traumatismes, empoisonnements et autres causes externes','S80.242A'),
('External constriction, left knee, subsequent encounter','External constriction, left knee, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S80.242D'),
('External constriction, left knee, sequela','External constriction, left knee, sequela','Traumatismes, empoisonnements et autres causes externes','S80.242S'),
('External constriction, non spécifié knee, initial encounter','External constriction, unspecified knee, initial encounter','Traumatismes, empoisonnements et autres causes externes','S80.249A'),
('External constriction, non spécifié knee, subsequent encounter','External constriction, unspecified knee, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S80.249D'),
('External constriction, non spécifié knee, sequela','External constriction, unspecified knee, sequela','Traumatismes, empoisonnements et autres causes externes','S80.249S'),
('Superficial foreign body, right knee, initial encounter','Superficial foreign body, right knee, initial encounter','Traumatismes, empoisonnements et autres causes externes','S80.251A'),
('Superficial foreign body, right knee, subsequent encounter','Superficial foreign body, right knee, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S80.251D'),
('Superficial foreign body, right knee, sequela','Superficial foreign body, right knee, sequela','Traumatismes, empoisonnements et autres causes externes','S80.251S'),
('Superficial foreign body, left knee, initial encounter','Superficial foreign body, left knee, initial encounter','Traumatismes, empoisonnements et autres causes externes','S80.252A'),
('Superficial foreign body, left knee, subsequent encounter','Superficial foreign body, left knee, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S80.252D'),
('Superficial foreign body, left knee, sequela','Superficial foreign body, left knee, sequela','Traumatismes, empoisonnements et autres causes externes','S80.252S'),
('Superficial foreign body, non spécifié knee, initial encounter','Superficial foreign body, unspecified knee, initial encounter','Traumatismes, empoisonnements et autres causes externes','S80.259A'),
('Superficial foreign body, non spécifié knee, subsequent encounter','Superficial foreign body, unspecified knee, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S80.259D'),
('Superficial foreign body, non spécifié knee, sequela','Superficial foreign body, unspecified knee, sequela','Traumatismes, empoisonnements et autres causes externes','S80.259S'),
('Insect bite (nonvenomous), right knee, initial encounter','Insect bite (nonvenomous), right knee, initial encounter','Traumatismes, empoisonnements et autres causes externes','S80.261A'),
('Insect bite (nonvenomous), right knee, subsequent encounter','Insect bite (nonvenomous), right knee, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S80.261D'),
('Insect bite (nonvenomous), right knee, sequela','Insect bite (nonvenomous), right knee, sequela','Traumatismes, empoisonnements et autres causes externes','S80.261S'),
('Insect bite (nonvenomous), left knee, initial encounter','Insect bite (nonvenomous), left knee, initial encounter','Traumatismes, empoisonnements et autres causes externes','S80.262A'),
('Insect bite (nonvenomous), left knee, subsequent encounter','Insect bite (nonvenomous), left knee, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S80.262D'),
('Insect bite (nonvenomous), left knee, sequela','Insect bite (nonvenomous), left knee, sequela','Traumatismes, empoisonnements et autres causes externes','S80.262S'),
('Insect bite (nonvenomous), non spécifié knee, initial encounter','Insect bite (nonvenomous), unspecified knee, initial encounter','Traumatismes, empoisonnements et autres causes externes','S80.269A'),
('Insect bite (nonvenomous), non spécifié knee, subsequent encounter','Insect bite (nonvenomous), unspecified knee, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S80.269D'),
('Insect bite (nonvenomous), non spécifié knee, sequela','Insect bite (nonvenomous), unspecified knee, sequela','Traumatismes, empoisonnements et autres causes externes','S80.269S'),
('autre superficial bite of right knee, initial encounter','Other superficial bite of right knee, initial encounter','Traumatismes, empoisonnements et autres causes externes','S80.271A'),
('autre superficial bite of right knee, subsequent encounter','Other superficial bite of right knee, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S80.271D'),
('autre superficial bite of right knee, sequela','Other superficial bite of right knee, sequela','Traumatismes, empoisonnements et autres causes externes','S80.271S'),
('autre superficial bite of left knee, initial encounter','Other superficial bite of left knee, initial encounter','Traumatismes, empoisonnements et autres causes externes','S80.272A'),
('autre superficial bite of left knee, subsequent encounter','Other superficial bite of left knee, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S80.272D'),
('autre superficial bite of left knee, sequela','Other superficial bite of left knee, sequela','Traumatismes, empoisonnements et autres causes externes','S80.272S'),
('autre superficial bite of non spécifié knee, initial encounter','Other superficial bite of unspecified knee, initial encounter','Traumatismes, empoisonnements et autres causes externes','S80.279A'),
('autre superficial bite of non spécifié knee, subsequent encounter','Other superficial bite of unspecified knee, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S80.279D'),
('autre superficial bite of non spécifié knee, sequela','Other superficial bite of unspecified knee, sequela','Traumatismes, empoisonnements et autres causes externes','S80.279S'),
('Abrasion, right lower leg, initial encounter','Abrasion, right lower leg, initial encounter','Traumatismes, empoisonnements et autres causes externes','S80.811A'),
('Abrasion, right lower leg, subsequent encounter','Abrasion, right lower leg, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S80.811D'),
('Abrasion, right lower leg, sequela','Abrasion, right lower leg, sequela','Traumatismes, empoisonnements et autres causes externes','S80.811S'),
('Abrasion, left lower leg, initial encounter','Abrasion, left lower leg, initial encounter','Traumatismes, empoisonnements et autres causes externes','S80.812A'),
('Abrasion, left lower leg, subsequent encounter','Abrasion, left lower leg, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S80.812D'),
('Abrasion, left lower leg, sequela','Abrasion, left lower leg, sequela','Traumatismes, empoisonnements et autres causes externes','S80.812S'),
('Abrasion, non spécifié lower leg, initial encounter','Abrasion, unspecified lower leg, initial encounter','Traumatismes, empoisonnements et autres causes externes','S80.819A'),
('Abrasion, non spécifié lower leg, subsequent encounter','Abrasion, unspecified lower leg, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S80.819D'),
('Abrasion, non spécifié lower leg, sequela','Abrasion, unspecified lower leg, sequela','Traumatismes, empoisonnements et autres causes externes','S80.819S'),
('Blister (nonthermal), right lower leg, initial encounter','Blister (nonthermal), right lower leg, initial encounter','Traumatismes, empoisonnements et autres causes externes','S80.821A'),
('Blister (nonthermal), right lower leg, subsequent encounter','Blister (nonthermal), right lower leg, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S80.821D'),
('Blister (nonthermal), right lower leg, sequela','Blister (nonthermal), right lower leg, sequela','Traumatismes, empoisonnements et autres causes externes','S80.821S'),
('Blister (nonthermal), left lower leg, initial encounter','Blister (nonthermal), left lower leg, initial encounter','Traumatismes, empoisonnements et autres causes externes','S80.822A'),
('Blister (nonthermal), left lower leg, subsequent encounter','Blister (nonthermal), left lower leg, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S80.822D'),
('Blister (nonthermal), left lower leg, sequela','Blister (nonthermal), left lower leg, sequela','Traumatismes, empoisonnements et autres causes externes','S80.822S'),
('Blister (nonthermal), non spécifié lower leg, initial encounter','Blister (nonthermal), unspecified lower leg, initial encounter','Traumatismes, empoisonnements et autres causes externes','S80.829A')
ON CONFLICT (nom_fr) DO NOTHING;
