-- icd10v2_batch_483.sql (80 rows)
INSERT INTO pathologies (nom_fr, nom_en, categorie, icd10_code)
VALUES
('Personal history of autre medical treatment','Personal history of other medical treatment','Facteurs influant sur l''état de santé','Z92.89'),
('Tracheostomy status','Tracheostomy status','Facteurs influant sur l''état de santé','Z93.0'),
('Gastrostomy status','Gastrostomy status','Facteurs influant sur l''état de santé','Z93.1'),
('Ileostomy status','Ileostomy status','Facteurs influant sur l''état de santé','Z93.2'),
('Colostomy status','Colostomy status','Facteurs influant sur l''état de santé','Z93.3'),
('autre artificial openings of gastrointestinal tract status','Other artificial openings of gastrointestinal tract status','Facteurs influant sur l''état de santé','Z93.4'),
('non spécifié cystostomy status','Unspecified cystostomy status','Facteurs influant sur l''état de santé','Z93.50'),
('Cutaneous-vesicostomy status','Cutaneous-vesicostomy status','Facteurs influant sur l''état de santé','Z93.51'),
('Appendico-vesicostomy status','Appendico-vesicostomy status','Facteurs influant sur l''état de santé','Z93.52'),
('autre cystostomy status','Other cystostomy status','Facteurs influant sur l''état de santé','Z93.59'),
('autre artificial openings of urinary tract status','Other artificial openings of urinary tract status','Facteurs influant sur l''état de santé','Z93.6'),
('autre artificial opening status','Other artificial opening status','Facteurs influant sur l''état de santé','Z93.8'),
('Artificial opening status, non spécifié','Artificial opening status, unspecified','Facteurs influant sur l''état de santé','Z93.9'),
('Kidney transplant status','Kidney transplant status','Facteurs influant sur l''état de santé','Z94.0'),
('Heart transplant status','Heart transplant status','Facteurs influant sur l''état de santé','Z94.1'),
('Lung transplant status','Lung transplant status','Facteurs influant sur l''état de santé','Z94.2'),
('Heart and lungs transplant status','Heart and lungs transplant status','Facteurs influant sur l''état de santé','Z94.3'),
('Liver transplant status','Liver transplant status','Facteurs influant sur l''état de santé','Z94.4'),
('Skin transplant status','Skin transplant status','Facteurs influant sur l''état de santé','Z94.5'),
('Bone transplant status','Bone transplant status','Facteurs influant sur l''état de santé','Z94.6'),
('Corneal transplant status','Corneal transplant status','Facteurs influant sur l''état de santé','Z94.7'),
('Bone marrow transplant status','Bone marrow transplant status','Facteurs influant sur l''état de santé','Z94.81'),
('Intestine transplant status','Intestine transplant status','Facteurs influant sur l''état de santé','Z94.82'),
('Pancreas transplant status','Pancreas transplant status','Facteurs influant sur l''état de santé','Z94.83'),
('Stem cells transplant status','Stem cells transplant status','Facteurs influant sur l''état de santé','Z94.84'),
('autre transplanted organ and tissue status','Other transplanted organ and tissue status','Facteurs influant sur l''état de santé','Z94.89'),
('Transplanted organ and tissue status, non spécifié','Transplanted organ and tissue status, unspecified','Facteurs influant sur l''état de santé','Z94.9'),
('Presence of cardiac pacemaker','Presence of cardiac pacemaker','Facteurs influant sur l''état de santé','Z95.0'),
('Presence of aortocoronary bypass graft','Presence of aortocoronary bypass graft','Facteurs influant sur l''état de santé','Z95.1'),
('Presence of prosthetic heart valve','Presence of prosthetic heart valve','Facteurs influant sur l''état de santé','Z95.2'),
('Presence of xenogenic heart valve','Presence of xenogenic heart valve','Facteurs influant sur l''état de santé','Z95.3'),
('Presence of autre heart-valve replacement','Presence of other heart-valve replacement','Facteurs influant sur l''état de santé','Z95.4'),
('Presence of coronary angioplasty implant and graft','Presence of coronary angioplasty implant and graft','Facteurs influant sur l''état de santé','Z95.5'),
('Presence of automatic (implantable) cardiac defibrillator','Presence of automatic (implantable) cardiac defibrillator','Facteurs influant sur l''état de santé','Z95.810'),
('Presence of heart assist device','Presence of heart assist device','Facteurs influant sur l''état de santé','Z95.811'),
('Presence of fully implantable artificial heart','Presence of fully implantable artificial heart','Facteurs influant sur l''état de santé','Z95.812'),
('Presence of autre cardiac implants and grafts','Presence of other cardiac implants and grafts','Facteurs influant sur l''état de santé','Z95.818'),
('Peripheral vascular angioplasty status with implants and grafts','Peripheral vascular angioplasty status with implants and grafts','Facteurs influant sur l''état de santé','Z95.820'),
('Presence of autre vascular implants and grafts','Presence of other vascular implants and grafts','Facteurs influant sur l''état de santé','Z95.828'),
('Presence of cardiac and vascular implant and graft, non spécifié','Presence of cardiac and vascular implant and graft, unspecified','Facteurs influant sur l''état de santé','Z95.9'),
('Presence of urogenital implants','Presence of urogenital implants','Facteurs influant sur l''état de santé','Z96.0'),
('Presence of intraocular lens','Presence of intraocular lens','Facteurs influant sur l''état de santé','Z96.1'),
('Presence of otological and audiological implant, non spécifié','Presence of otological and audiological implant, unspecified','Facteurs influant sur l''état de santé','Z96.20'),
('Cochlear implant status','Cochlear implant status','Facteurs influant sur l''état de santé','Z96.21'),
('Myringotomy tube(s) status','Myringotomy tube(s) status','Facteurs influant sur l''état de santé','Z96.22'),
('Presence of autre otological and audiological implants','Presence of other otological and audiological implants','Facteurs influant sur l''état de santé','Z96.29'),
('Presence of artificial larynx','Presence of artificial larynx','Facteurs influant sur l''état de santé','Z96.3'),
('Presence of insulin pump (external) (internal)','Presence of insulin pump (external) (internal)','Facteurs influant sur l''état de santé','Z96.41'),
('Presence of autre endocrine implants','Presence of other endocrine implants','Facteurs influant sur l''état de santé','Z96.49'),
('Presence of tooth-root and mandibular implants','Presence of tooth-root and mandibular implants','Facteurs influant sur l''état de santé','Z96.5'),
('Presence of non spécifié orthopedic joint implant','Presence of unspecified orthopedic joint implant','Facteurs influant sur l''état de santé','Z96.60'),
('Presence of right artificial shoulder joint','Presence of right artificial shoulder joint','Facteurs influant sur l''état de santé','Z96.611'),
('Presence of left artificial shoulder joint','Presence of left artificial shoulder joint','Facteurs influant sur l''état de santé','Z96.612'),
('Presence of non spécifié artificial shoulder joint','Presence of unspecified artificial shoulder joint','Facteurs influant sur l''état de santé','Z96.619'),
('Presence of right artificial elbow joint','Presence of right artificial elbow joint','Facteurs influant sur l''état de santé','Z96.621'),
('Presence of left artificial elbow joint','Presence of left artificial elbow joint','Facteurs influant sur l''état de santé','Z96.622'),
('Presence of non spécifié artificial elbow joint','Presence of unspecified artificial elbow joint','Facteurs influant sur l''état de santé','Z96.629'),
('Presence of right artificial wrist joint','Presence of right artificial wrist joint','Facteurs influant sur l''état de santé','Z96.631'),
('Presence of left artificial wrist joint','Presence of left artificial wrist joint','Facteurs influant sur l''état de santé','Z96.632'),
('Presence of non spécifié artificial wrist joint','Presence of unspecified artificial wrist joint','Facteurs influant sur l''état de santé','Z96.639'),
('Presence of right artificial hip joint','Presence of right artificial hip joint','Facteurs influant sur l''état de santé','Z96.641'),
('Presence of left artificial hip joint','Presence of left artificial hip joint','Facteurs influant sur l''état de santé','Z96.642'),
('Presence of artificial hip joint, bilateral','Presence of artificial hip joint, bilateral','Facteurs influant sur l''état de santé','Z96.643'),
('Presence of non spécifié artificial hip joint','Presence of unspecified artificial hip joint','Facteurs influant sur l''état de santé','Z96.649'),
('Presence of right artificial knee joint','Presence of right artificial knee joint','Facteurs influant sur l''état de santé','Z96.651'),
('Presence of left artificial knee joint','Presence of left artificial knee joint','Facteurs influant sur l''état de santé','Z96.652'),
('Presence of artificial knee joint, bilateral','Presence of artificial knee joint, bilateral','Facteurs influant sur l''état de santé','Z96.653'),
('Presence of non spécifié artificial knee joint','Presence of unspecified artificial knee joint','Facteurs influant sur l''état de santé','Z96.659'),
('Presence of right artificial ankle joint','Presence of right artificial ankle joint','Facteurs influant sur l''état de santé','Z96.661'),
('Presence of left artificial ankle joint','Presence of left artificial ankle joint','Facteurs influant sur l''état de santé','Z96.662'),
('Presence of non spécifié artificial ankle joint','Presence of unspecified artificial ankle joint','Facteurs influant sur l''état de santé','Z96.669'),
('Finger-joint replacement of right hand','Finger-joint replacement of right hand','Facteurs influant sur l''état de santé','Z96.691'),
('Finger-joint replacement of left hand','Finger-joint replacement of left hand','Facteurs influant sur l''état de santé','Z96.692'),
('Finger-joint replacement, bilateral','Finger-joint replacement, bilateral','Facteurs influant sur l''état de santé','Z96.693'),
('Presence of autre orthopedic joint implants','Presence of other orthopedic joint implants','Facteurs influant sur l''état de santé','Z96.698'),
('Presence of autre bone and tendon implants','Presence of other bone and tendon implants','Facteurs influant sur l''état de santé','Z96.7'),
('Presence of artificial skin','Presence of artificial skin','Facteurs influant sur l''état de santé','Z96.81'),
('Presence of neurostimulator','Presence of neurostimulator','Facteurs influant sur l''état de santé','Z96.82'),
('Presence of autre specified functional implants','Presence of other specified functional implants','Facteurs influant sur l''état de santé','Z96.89'),
('Presence of functional implant, non spécifié','Presence of functional implant, unspecified','Facteurs influant sur l''état de santé','Z96.9')
ON CONFLICT (nom_fr) DO NOTHING;
