-- icd10v2_batch_087.sql (80 rows)
INSERT INTO pathologies (nom_fr, nom_en, categorie, icd10_code)
VALUES
('Nodular corneal degeneration, bilateral','Nodular corneal degeneration, bilateral','Maladies de l''œil et de ses annexes','H18.453'),
('Nodular corneal degeneration, non spécifié eye','Nodular corneal degeneration, unspecified eye','Maladies de l''œil et de ses annexes','H18.459'),
('Peripheral corneal degeneration, right eye','Peripheral corneal degeneration, right eye','Maladies de l''œil et de ses annexes','H18.461'),
('Peripheral corneal degeneration, left eye','Peripheral corneal degeneration, left eye','Maladies de l''œil et de ses annexes','H18.462'),
('Peripheral corneal degeneration, bilateral','Peripheral corneal degeneration, bilateral','Maladies de l''œil et de ses annexes','H18.463'),
('Peripheral corneal degeneration, non spécifié eye','Peripheral corneal degeneration, unspecified eye','Maladies de l''œil et de ses annexes','H18.469'),
('autre corneal degeneration','Other corneal degeneration','Maladies de l''œil et de ses annexes','H18.49'),
('non spécifié hereditary corneal dystrophies, right eye','Unspecified hereditary corneal dystrophies, right eye','Maladies de l''œil et de ses annexes','H18.501'),
('non spécifié hereditary corneal dystrophies, left eye','Unspecified hereditary corneal dystrophies, left eye','Maladies de l''œil et de ses annexes','H18.502'),
('non spécifié hereditary corneal dystrophies, bilateral','Unspecified hereditary corneal dystrophies, bilateral','Maladies de l''œil et de ses annexes','H18.503'),
('non spécifié hereditary corneal dystrophies, non spécifié eye','Unspecified hereditary corneal dystrophies, unspecified eye','Maladies de l''œil et de ses annexes','H18.509'),
('Endothelial corneal dystrophy, right eye','Endothelial corneal dystrophy, right eye','Maladies de l''œil et de ses annexes','H18.511'),
('Endothelial corneal dystrophy, left eye','Endothelial corneal dystrophy, left eye','Maladies de l''œil et de ses annexes','H18.512'),
('Endothelial corneal dystrophy, bilateral','Endothelial corneal dystrophy, bilateral','Maladies de l''œil et de ses annexes','H18.513'),
('Endothelial corneal dystrophy, non spécifié eye','Endothelial corneal dystrophy, unspecified eye','Maladies de l''œil et de ses annexes','H18.519'),
('Epithelial (juvenile) corneal dystrophy, right eye','Epithelial (juvenile) corneal dystrophy, right eye','Maladies de l''œil et de ses annexes','H18.521'),
('Epithelial (juvenile) corneal dystrophy, left eye','Epithelial (juvenile) corneal dystrophy, left eye','Maladies de l''œil et de ses annexes','H18.522'),
('Epithelial (juvenile) corneal dystrophy, bilateral','Epithelial (juvenile) corneal dystrophy, bilateral','Maladies de l''œil et de ses annexes','H18.523'),
('Epithelial (juvenile) corneal dystrophy, non spécifié eye','Epithelial (juvenile) corneal dystrophy, unspecified eye','Maladies de l''œil et de ses annexes','H18.529'),
('Granular corneal dystrophy, right eye','Granular corneal dystrophy, right eye','Maladies de l''œil et de ses annexes','H18.531'),
('Granular corneal dystrophy, left eye','Granular corneal dystrophy, left eye','Maladies de l''œil et de ses annexes','H18.532'),
('Granular corneal dystrophy, bilateral','Granular corneal dystrophy, bilateral','Maladies de l''œil et de ses annexes','H18.533'),
('Granular corneal dystrophy, non spécifié eye','Granular corneal dystrophy, unspecified eye','Maladies de l''œil et de ses annexes','H18.539'),
('Lattice corneal dystrophy, right eye','Lattice corneal dystrophy, right eye','Maladies de l''œil et de ses annexes','H18.541'),
('Lattice corneal dystrophy, left eye','Lattice corneal dystrophy, left eye','Maladies de l''œil et de ses annexes','H18.542'),
('Lattice corneal dystrophy, bilateral','Lattice corneal dystrophy, bilateral','Maladies de l''œil et de ses annexes','H18.543'),
('Lattice corneal dystrophy, non spécifié eye','Lattice corneal dystrophy, unspecified eye','Maladies de l''œil et de ses annexes','H18.549'),
('Macular corneal dystrophy, right eye','Macular corneal dystrophy, right eye','Maladies de l''œil et de ses annexes','H18.551'),
('Macular corneal dystrophy, left eye','Macular corneal dystrophy, left eye','Maladies de l''œil et de ses annexes','H18.552'),
('Macular corneal dystrophy, bilateral','Macular corneal dystrophy, bilateral','Maladies de l''œil et de ses annexes','H18.553'),
('Macular corneal dystrophy, non spécifié eye','Macular corneal dystrophy, unspecified eye','Maladies de l''œil et de ses annexes','H18.559'),
('autre hereditary corneal dystrophies, right eye','Other hereditary corneal dystrophies, right eye','Maladies de l''œil et de ses annexes','H18.591'),
('autre hereditary corneal dystrophies, left eye','Other hereditary corneal dystrophies, left eye','Maladies de l''œil et de ses annexes','H18.592'),
('autre hereditary corneal dystrophies, bilateral','Other hereditary corneal dystrophies, bilateral','Maladies de l''œil et de ses annexes','H18.593'),
('autre hereditary corneal dystrophies, non spécifié eye','Other hereditary corneal dystrophies, unspecified eye','Maladies de l''œil et de ses annexes','H18.599'),
('Keratoconus, non spécifié, right eye','Keratoconus, unspecified, right eye','Maladies de l''œil et de ses annexes','H18.601'),
('Keratoconus, non spécifié, left eye','Keratoconus, unspecified, left eye','Maladies de l''œil et de ses annexes','H18.602'),
('Keratoconus, non spécifié, bilateral','Keratoconus, unspecified, bilateral','Maladies de l''œil et de ses annexes','H18.603'),
('Keratoconus, non spécifié, non spécifié eye','Keratoconus, unspecified, unspecified eye','Maladies de l''œil et de ses annexes','H18.609'),
('Keratoconus, stable, right eye','Keratoconus, stable, right eye','Maladies de l''œil et de ses annexes','H18.611'),
('Keratoconus, stable, left eye','Keratoconus, stable, left eye','Maladies de l''œil et de ses annexes','H18.612'),
('Keratoconus, stable, bilateral','Keratoconus, stable, bilateral','Maladies de l''œil et de ses annexes','H18.613'),
('Keratoconus, stable, non spécifié eye','Keratoconus, stable, unspecified eye','Maladies de l''œil et de ses annexes','H18.619'),
('Keratoconus, unstable, right eye','Keratoconus, unstable, right eye','Maladies de l''œil et de ses annexes','H18.621'),
('Keratoconus, unstable, left eye','Keratoconus, unstable, left eye','Maladies de l''œil et de ses annexes','H18.622'),
('Keratoconus, unstable, bilateral','Keratoconus, unstable, bilateral','Maladies de l''œil et de ses annexes','H18.623'),
('Keratoconus, unstable, non spécifié eye','Keratoconus, unstable, unspecified eye','Maladies de l''œil et de ses annexes','H18.629'),
('non spécifié corneal deformity','Unspecified corneal deformity','Maladies de l''œil et de ses annexes','H18.70'),
('Corneal ectasia, right eye','Corneal ectasia, right eye','Maladies de l''œil et de ses annexes','H18.711'),
('Corneal ectasia, left eye','Corneal ectasia, left eye','Maladies de l''œil et de ses annexes','H18.712'),
('Corneal ectasia, bilateral','Corneal ectasia, bilateral','Maladies de l''œil et de ses annexes','H18.713'),
('Corneal ectasia, non spécifié eye','Corneal ectasia, unspecified eye','Maladies de l''œil et de ses annexes','H18.719'),
('Corneal staphyloma, right eye','Corneal staphyloma, right eye','Maladies de l''œil et de ses annexes','H18.721'),
('Corneal staphyloma, left eye','Corneal staphyloma, left eye','Maladies de l''œil et de ses annexes','H18.722'),
('Corneal staphyloma, bilateral','Corneal staphyloma, bilateral','Maladies de l''œil et de ses annexes','H18.723'),
('Corneal staphyloma, non spécifié eye','Corneal staphyloma, unspecified eye','Maladies de l''œil et de ses annexes','H18.729'),
('Descemetocele, right eye','Descemetocele, right eye','Maladies de l''œil et de ses annexes','H18.731'),
('Descemetocele, left eye','Descemetocele, left eye','Maladies de l''œil et de ses annexes','H18.732'),
('Descemetocele, bilateral','Descemetocele, bilateral','Maladies de l''œil et de ses annexes','H18.733'),
('Descemetocele, non spécifié eye','Descemetocele, unspecified eye','Maladies de l''œil et de ses annexes','H18.739'),
('Underdosing of histamine H2-receptor blockers, sequela','Underdosing of histamine H2-receptor blockers, sequela','Traumatismes, empoisonnements et autres causes externes','T47.0X6S'),
('Intoxication par histamine H2-receptor blockers, assault, sequela','Poisoning by histamine H2-receptor blockers, assault, sequela','Traumatismes, empoisonnements et autres causes externes','T47.0X3S'),
('Intoxication par histamine H2-receptor blockers, undetermined, sequela','Poisoning by histamine H2-receptor blockers, undetermined, sequela','Traumatismes, empoisonnements et autres causes externes','T47.0X4S'),
('Effet indésirable de histamine H2-receptor blockers, sequela','Adverse effect of histamine H2-receptor blockers, sequela','Traumatismes, empoisonnements et autres causes externes','T47.0X5S'),
('Underdosing of histamine H2-receptor blockers, initial encounter','Underdosing of histamine H2-receptor blockers, initial encounter','Traumatismes, empoisonnements et autres causes externes','T47.0X6A'),
('Underdosing of histamine H2-receptor blockers, subsequent encounter','Underdosing of histamine H2-receptor blockers, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T47.0X6D'),
('Intoxication par histamine H2-receptor blockers, accidental (unintentional), sequela','Poisoning by histamine H2-receptor blockers, accidental (unintentional), sequela','Traumatismes, empoisonnements et autres causes externes','T47.0X1S'),
('Intoxication par histamine H2-receptor blockers, assault, initial encounter','Poisoning by histamine H2-receptor blockers, assault, initial encounter','Traumatismes, empoisonnements et autres causes externes','T47.0X3A'),
('Intoxication par histamine H2-receptor blockers, assault, subsequent encounter','Poisoning by histamine H2-receptor blockers, assault, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T47.0X3D'),
('Intoxication par histamine H2-receptor blockers, undetermined, initial encounter','Poisoning by histamine H2-receptor blockers, undetermined, initial encounter','Traumatismes, empoisonnements et autres causes externes','T47.0X4A'),
('Intoxication par histamine H2-receptor blockers, undetermined, subsequent encounter','Poisoning by histamine H2-receptor blockers, undetermined, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T47.0X4D'),
('Effet indésirable de histamine H2-receptor blockers, initial encounter','Adverse effect of histamine H2-receptor blockers, initial encounter','Traumatismes, empoisonnements et autres causes externes','T47.0X5A'),
('Effet indésirable de histamine H2-receptor blockers, subsequent encounter','Adverse effect of histamine H2-receptor blockers, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T47.0X5D'),
('Intoxication par histamine H2-receptor blockers, accidental (unintentional), initial encounter','Poisoning by histamine H2-receptor blockers, accidental (unintentional), initial encounter','Traumatismes, empoisonnements et autres causes externes','T47.0X1A'),
('Intoxication par histamine H2-receptor blockers, accidental (unintentional), subsequent encounter','Poisoning by histamine H2-receptor blockers, accidental (unintentional), subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T47.0X1D'),
('Intoxication par histamine H2-receptor blockers, intentional self-harm, sequela','Poisoning by histamine H2-receptor blockers, intentional self-harm, sequela','Traumatismes, empoisonnements et autres causes externes','T47.0X2S'),
('Intoxication par histamine H2-receptor blockers, intentional self-harm, initial encounter','Poisoning by histamine H2-receptor blockers, intentional self-harm, initial encounter','Traumatismes, empoisonnements et autres causes externes','T47.0X2A'),
('Intoxication par histamine H2-receptor blockers, intentional self-harm, subsequent encounter','Poisoning by histamine H2-receptor blockers, intentional self-harm, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T47.0X2D'),
('non spécifié aigu and subacute iridocyclitis','Unspecified acute and subacute iridocyclitis','Maladies de l''œil et de ses annexes','H20.00'),
('primitif iridocyclitis, right eye','Primary iridocyclitis, right eye','Maladies de l''œil et de ses annexes','H20.011')
ON CONFLICT (nom_fr) DO NOTHING;
