-- icd10v2_batch_315.sql (80 rows)
INSERT INTO pathologies (nom_fr, nom_en, categorie, icd10_code)
VALUES
('External constriction of non spécifié hand, subsequent encounter','External constriction of unspecified hand, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S60.549D'),
('External constriction of non spécifié hand, sequela','External constriction of unspecified hand, sequela','Traumatismes, empoisonnements et autres causes externes','S60.549S'),
('Superficial foreign body of right hand, initial encounter','Superficial foreign body of right hand, initial encounter','Traumatismes, empoisonnements et autres causes externes','S60.551A'),
('Superficial foreign body of right hand, subsequent encounter','Superficial foreign body of right hand, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S60.551D'),
('Superficial foreign body of right hand, sequela','Superficial foreign body of right hand, sequela','Traumatismes, empoisonnements et autres causes externes','S60.551S'),
('Superficial foreign body of left hand, initial encounter','Superficial foreign body of left hand, initial encounter','Traumatismes, empoisonnements et autres causes externes','S60.552A'),
('Superficial foreign body of left hand, subsequent encounter','Superficial foreign body of left hand, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S60.552D'),
('Superficial foreign body of left hand, sequela','Superficial foreign body of left hand, sequela','Traumatismes, empoisonnements et autres causes externes','S60.552S'),
('Superficial foreign body of non spécifié hand, initial encounter','Superficial foreign body of unspecified hand, initial encounter','Traumatismes, empoisonnements et autres causes externes','S60.559A'),
('Superficial foreign body of non spécifié hand, subsequent encounter','Superficial foreign body of unspecified hand, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S60.559D'),
('Superficial foreign body of non spécifié hand, sequela','Superficial foreign body of unspecified hand, sequela','Traumatismes, empoisonnements et autres causes externes','S60.559S'),
('Insect bite (nonvenomous) of right hand, initial encounter','Insect bite (nonvenomous) of right hand, initial encounter','Traumatismes, empoisonnements et autres causes externes','S60.561A'),
('Insect bite (nonvenomous) of right hand, subsequent encounter','Insect bite (nonvenomous) of right hand, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S60.561D'),
('Insect bite (nonvenomous) of right hand, sequela','Insect bite (nonvenomous) of right hand, sequela','Traumatismes, empoisonnements et autres causes externes','S60.561S'),
('Insect bite (nonvenomous) of left hand, initial encounter','Insect bite (nonvenomous) of left hand, initial encounter','Traumatismes, empoisonnements et autres causes externes','S60.562A'),
('Insect bite (nonvenomous) of left hand, subsequent encounter','Insect bite (nonvenomous) of left hand, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S60.562D'),
('Insect bite (nonvenomous) of left hand, sequela','Insect bite (nonvenomous) of left hand, sequela','Traumatismes, empoisonnements et autres causes externes','S60.562S'),
('Insect bite (nonvenomous) of non spécifié hand, initial encounter','Insect bite (nonvenomous) of unspecified hand, initial encounter','Traumatismes, empoisonnements et autres causes externes','S60.569A'),
('Insect bite (nonvenomous) of non spécifié hand, subsequent encounter','Insect bite (nonvenomous) of unspecified hand, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S60.569D'),
('Insect bite (nonvenomous) of non spécifié hand, sequela','Insect bite (nonvenomous) of unspecified hand, sequela','Traumatismes, empoisonnements et autres causes externes','S60.569S'),
('autre superficial bite of hand of right hand, initial encounter','Other superficial bite of hand of right hand, initial encounter','Traumatismes, empoisonnements et autres causes externes','S60.571A'),
('autre superficial bite of hand of right hand, subsequent encounter','Other superficial bite of hand of right hand, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S60.571D'),
('autre superficial bite of hand of right hand, sequela','Other superficial bite of hand of right hand, sequela','Traumatismes, empoisonnements et autres causes externes','S60.571S'),
('autre superficial bite of hand of left hand, initial encounter','Other superficial bite of hand of left hand, initial encounter','Traumatismes, empoisonnements et autres causes externes','S60.572A'),
('autre superficial bite of hand of left hand, subsequent encounter','Other superficial bite of hand of left hand, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S60.572D'),
('autre superficial bite of hand of left hand, sequela','Other superficial bite of hand of left hand, sequela','Traumatismes, empoisonnements et autres causes externes','S60.572S'),
('autre superficial bite of hand of non spécifié hand, initial encounter','Other superficial bite of hand of unspecified hand, initial encounter','Traumatismes, empoisonnements et autres causes externes','S60.579A'),
('autre superficial bite of hand of non spécifié hand, subsequent encounter','Other superficial bite of hand of unspecified hand, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S60.579D'),
('autre superficial bite of hand of non spécifié hand, sequela','Other superficial bite of hand of unspecified hand, sequela','Traumatismes, empoisonnements et autres causes externes','S60.579S'),
('Abrasion of right wrist, initial encounter','Abrasion of right wrist, initial encounter','Traumatismes, empoisonnements et autres causes externes','S60.811A'),
('Abrasion of right wrist, subsequent encounter','Abrasion of right wrist, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S60.811D'),
('Abrasion of right wrist, sequela','Abrasion of right wrist, sequela','Traumatismes, empoisonnements et autres causes externes','S60.811S'),
('Abrasion of left wrist, initial encounter','Abrasion of left wrist, initial encounter','Traumatismes, empoisonnements et autres causes externes','S60.812A'),
('Abrasion of left wrist, subsequent encounter','Abrasion of left wrist, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S60.812D'),
('Abrasion of left wrist, sequela','Abrasion of left wrist, sequela','Traumatismes, empoisonnements et autres causes externes','S60.812S'),
('Abrasion of non spécifié wrist, initial encounter','Abrasion of unspecified wrist, initial encounter','Traumatismes, empoisonnements et autres causes externes','S60.819A'),
('Abrasion of non spécifié wrist, subsequent encounter','Abrasion of unspecified wrist, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S60.819D'),
('Abrasion of non spécifié wrist, sequela','Abrasion of unspecified wrist, sequela','Traumatismes, empoisonnements et autres causes externes','S60.819S'),
('Blister (nonthermal) of right wrist, initial encounter','Blister (nonthermal) of right wrist, initial encounter','Traumatismes, empoisonnements et autres causes externes','S60.821A'),
('Blister (nonthermal) of right wrist, subsequent encounter','Blister (nonthermal) of right wrist, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S60.821D'),
('Blister (nonthermal) of right wrist, sequela','Blister (nonthermal) of right wrist, sequela','Traumatismes, empoisonnements et autres causes externes','S60.821S'),
('Blister (nonthermal) of left wrist, initial encounter','Blister (nonthermal) of left wrist, initial encounter','Traumatismes, empoisonnements et autres causes externes','S60.822A'),
('Blister (nonthermal) of left wrist, subsequent encounter','Blister (nonthermal) of left wrist, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S60.822D'),
('Blister (nonthermal) of left wrist, sequela','Blister (nonthermal) of left wrist, sequela','Traumatismes, empoisonnements et autres causes externes','S60.822S'),
('Blister (nonthermal) of non spécifié wrist, initial encounter','Blister (nonthermal) of unspecified wrist, initial encounter','Traumatismes, empoisonnements et autres causes externes','S60.829A'),
('Blister (nonthermal) of non spécifié wrist, subsequent encounter','Blister (nonthermal) of unspecified wrist, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S60.829D'),
('Blister (nonthermal) of non spécifié wrist, sequela','Blister (nonthermal) of unspecified wrist, sequela','Traumatismes, empoisonnements et autres causes externes','S60.829S'),
('External constriction of right wrist, initial encounter','External constriction of right wrist, initial encounter','Traumatismes, empoisonnements et autres causes externes','S60.841A'),
('External constriction of right wrist, subsequent encounter','External constriction of right wrist, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S60.841D'),
('External constriction of right wrist, sequela','External constriction of right wrist, sequela','Traumatismes, empoisonnements et autres causes externes','S60.841S'),
('External constriction of left wrist, initial encounter','External constriction of left wrist, initial encounter','Traumatismes, empoisonnements et autres causes externes','S60.842A'),
('External constriction of left wrist, subsequent encounter','External constriction of left wrist, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S60.842D'),
('External constriction of left wrist, sequela','External constriction of left wrist, sequela','Traumatismes, empoisonnements et autres causes externes','S60.842S'),
('External constriction of non spécifié wrist, initial encounter','External constriction of unspecified wrist, initial encounter','Traumatismes, empoisonnements et autres causes externes','S60.849A'),
('External constriction of non spécifié wrist, subsequent encounter','External constriction of unspecified wrist, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S60.849D'),
('External constriction of non spécifié wrist, sequela','External constriction of unspecified wrist, sequela','Traumatismes, empoisonnements et autres causes externes','S60.849S'),
('Superficial foreign body of right wrist, initial encounter','Superficial foreign body of right wrist, initial encounter','Traumatismes, empoisonnements et autres causes externes','S60.851A'),
('Superficial foreign body of right wrist, subsequent encounter','Superficial foreign body of right wrist, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S60.851D'),
('Superficial foreign body of right wrist, sequela','Superficial foreign body of right wrist, sequela','Traumatismes, empoisonnements et autres causes externes','S60.851S'),
('Superficial foreign body of left wrist, initial encounter','Superficial foreign body of left wrist, initial encounter','Traumatismes, empoisonnements et autres causes externes','S60.852A'),
('Superficial foreign body of left wrist, subsequent encounter','Superficial foreign body of left wrist, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S60.852D'),
('Superficial foreign body of left wrist, sequela','Superficial foreign body of left wrist, sequela','Traumatismes, empoisonnements et autres causes externes','S60.852S'),
('Superficial foreign body of non spécifié wrist, initial encounter','Superficial foreign body of unspecified wrist, initial encounter','Traumatismes, empoisonnements et autres causes externes','S60.859A'),
('Superficial foreign body of non spécifié wrist, subsequent encounter','Superficial foreign body of unspecified wrist, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S60.859D'),
('Superficial foreign body of non spécifié wrist, sequela','Superficial foreign body of unspecified wrist, sequela','Traumatismes, empoisonnements et autres causes externes','S60.859S'),
('Insect bite (nonvenomous) of right wrist, initial encounter','Insect bite (nonvenomous) of right wrist, initial encounter','Traumatismes, empoisonnements et autres causes externes','S60.861A'),
('Insect bite (nonvenomous) of right wrist, subsequent encounter','Insect bite (nonvenomous) of right wrist, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S60.861D'),
('Insect bite (nonvenomous) of right wrist, sequela','Insect bite (nonvenomous) of right wrist, sequela','Traumatismes, empoisonnements et autres causes externes','S60.861S'),
('Insect bite (nonvenomous) of left wrist, initial encounter','Insect bite (nonvenomous) of left wrist, initial encounter','Traumatismes, empoisonnements et autres causes externes','S60.862A'),
('Insect bite (nonvenomous) of left wrist, subsequent encounter','Insect bite (nonvenomous) of left wrist, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S60.862D'),
('Insect bite (nonvenomous) of left wrist, sequela','Insect bite (nonvenomous) of left wrist, sequela','Traumatismes, empoisonnements et autres causes externes','S60.862S'),
('Insect bite (nonvenomous) of non spécifié wrist, initial encounter','Insect bite (nonvenomous) of unspecified wrist, initial encounter','Traumatismes, empoisonnements et autres causes externes','S60.869A'),
('Insect bite (nonvenomous) of non spécifié wrist, subsequent encounter','Insect bite (nonvenomous) of unspecified wrist, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S60.869D'),
('Insect bite (nonvenomous) of non spécifié wrist, sequela','Insect bite (nonvenomous) of unspecified wrist, sequela','Traumatismes, empoisonnements et autres causes externes','S60.869S'),
('autre superficial bite of right wrist, initial encounter','Other superficial bite of right wrist, initial encounter','Traumatismes, empoisonnements et autres causes externes','S60.871A'),
('autre superficial bite of right wrist, subsequent encounter','Other superficial bite of right wrist, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S60.871D'),
('autre superficial bite of right wrist, sequela','Other superficial bite of right wrist, sequela','Traumatismes, empoisonnements et autres causes externes','S60.871S'),
('autre superficial bite of left wrist, initial encounter','Other superficial bite of left wrist, initial encounter','Traumatismes, empoisonnements et autres causes externes','S60.872A'),
('autre superficial bite of left wrist, subsequent encounter','Other superficial bite of left wrist, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S60.872D'),
('autre superficial bite of left wrist, sequela','Other superficial bite of left wrist, sequela','Traumatismes, empoisonnements et autres causes externes','S60.872S')
ON CONFLICT (nom_fr) DO NOTHING;
