-- icd10_batch_011.sql (80 rows)
INSERT INTO pathologies (nom_fr, nom_en, categorie, icd10_code)
VALUES
('bénin shuddering attacks','Benign shuddering attacks','Maladies du système nerveux','G25.83'),
('autre specified extrapyramidal and movement disorders','Other specified extrapyramidal and movement disorders','Maladies du système nerveux','G25.89'),
('Extrapyramidal and movement trouble, non spécifié','Extrapyramidal and movement disorder, unspecified','Maladies du système nerveux','G25.9'),
('Extrapyramidal and movement disorders in diseases classified elsewhere','Extrapyramidal and movement disorders in diseases classified elsewhere','Maladies du système nerveux','G26'),
('Maladie d''Alzheimer, with early onset','Alzheimer''s disease with early onset','Maladies du système nerveux','G30.0'),
('Maladie d''Alzheimer, with late onset','Alzheimer''s disease with late onset','Maladies du système nerveux','G30.1'),
('autre Alzheimer''s maladie','Other Alzheimer''s disease','Maladies du système nerveux','G30.8'),
('Maladie d''Alzheimer, , unspecified','Alzheimer''s disease, unspecified','Maladies du système nerveux','G30.9'),
('Pick''s maladie','Pick''s disease','Maladies du système nerveux','G31.01'),
('autre frontotemporal neurocognitive trouble','Other frontotemporal neurocognitive disorder','Maladies du système nerveux','G31.09'),
('Senile dégénérescence of brain, not elsewhere classified','Senile degeneration of brain, not elsewhere classified','Maladies du système nerveux','G31.1'),
('dégénérescence of nervous system due to alcohol','Degeneration of nervous system due to alcohol','Maladies du système nerveux','G31.2'),
('Leukodystrophy, non spécifié','Leukodystrophy, unspecified','Maladies du système nerveux','G31.80'),
('Alpers maladie','Alpers disease','Maladies du système nerveux','G31.81'),
('Leigh''s maladie','Leigh''s disease','Maladies du système nerveux','G31.82'),
('Neurocognitive trouble with Lewy bodies','Neurocognitive disorder with Lewy bodies','Maladies du système nerveux','G31.83'),
('Mild cognitive impairment of uncertain or unknown etiology','Mild cognitive impairment of uncertain or unknown etiology','Maladies du système nerveux','G31.84'),
('Corticobasal dégénérescence','Corticobasal degeneration','Maladies du système nerveux','G31.85'),
('Alexander maladie','Alexander disease','Maladies du système nerveux','G31.86'),
('primitif progressive apraxia of speech','Primary progressive apraxia of speech','Maladies du système nerveux','G31.87'),
('autre specified degenerative diseases of nervous system','Other specified degenerative diseases of nervous system','Maladies du système nerveux','G31.89'),
('Degenerative maladie of nervous system, non spécifié','Degenerative disease of nervous system, unspecified','Maladies du système nerveux','G31.9'),
('Subacute combined dégénérescence of spinal cord in diseases classified elsewhere','Subacute combined degeneration of spinal cord in diseases classified elsewhere','Maladies du système nerveux','G32.0'),
('Cerebellar ataxia in diseases classified elsewhere','Cerebellar ataxia in diseases classified elsewhere','Maladies du système nerveux','G32.81'),
('autre specified degenerative disorders of nervous system in diseases classified elsewhere','Other specified degenerative disorders of nervous system in diseases classified elsewhere','Maladies du système nerveux','G32.89'),
('Relapsing-remitting multiple sclerosis','Relapsing-remitting multiple sclerosis','Maladies du système nerveux','G35.A'),
('primitif progressive multiple sclerosis, non spécifié','Primary progressive multiple sclerosis, unspecified','Maladies du système nerveux','G35.B0'),
('Active primitif progressive multiple sclerosis','Active primary progressive multiple sclerosis','Maladies du système nerveux','G35.B1'),
('Non-active primitif progressive multiple sclerosis','Non-active primary progressive multiple sclerosis','Maladies du système nerveux','G35.B2'),
('secondaire progressive multiple sclerosis, non spécifié','Secondary progressive multiple sclerosis, unspecified','Maladies du système nerveux','G35.C0'),
('Active secondaire progressive multiple sclerosis','Active secondary progressive multiple sclerosis','Maladies du système nerveux','G35.C1'),
('Non-active secondaire progressive multiple sclerosis','Non-active secondary progressive multiple sclerosis','Maladies du système nerveux','G35.C2'),
('Sclérose en plaques, , unspecified','Multiple sclerosis, unspecified','Maladies du système nerveux','G35.D'),
('Neuromyelitis optica [Devic]','Neuromyelitis optica [Devic]','Maladies du système nerveux','G36.0'),
('aigu and subacute hemorrhagic leukoencephalitis [Hurst]','Acute and subacute hemorrhagic leukoencephalitis [Hurst]','Maladies du système nerveux','G36.1'),
('autre specified aigu disseminated demyelination','Other specified acute disseminated demyelination','Maladies du système nerveux','G36.8'),
('aigu disseminated demyelination, non spécifié','Acute disseminated demyelination, unspecified','Maladies du système nerveux','G36.9'),
('Diffuse sclerosis of central nervous system','Diffuse sclerosis of central nervous system','Maladies du système nerveux','G37.0'),
('Central demyelination of corpus callosum','Central demyelination of corpus callosum','Maladies du système nerveux','G37.1'),
('Central pontine myelinolysis','Central pontine myelinolysis','Maladies du système nerveux','G37.2'),
('aigu transverse myelitis in demyelinating maladie of central nervous system','Acute transverse myelitis in demyelinating disease of central nervous system','Maladies du système nerveux','G37.3'),
('Subacute necrotizing myelitis of central nervous system','Subacute necrotizing myelitis of central nervous system','Maladies du système nerveux','G37.4'),
('Concentric sclerosis [Balo] of central nervous system','Concentric sclerosis [Balo] of central nervous system','Maladies du système nerveux','G37.5'),
('Myelin oligodendrocyte glycoprotein antibody maladie','Myelin oligodendrocyte glycoprotein antibody disease','Maladies du système nerveux','G37.81'),
('autre specified demyelinating diseases of central nervous system','Other specified demyelinating diseases of central nervous system','Maladies du système nerveux','G37.89'),
('Demyelinating maladie of central nervous system, non spécifié','Demyelinating disease of central nervous system, unspecified','Maladies du système nerveux','G37.9'),
('Localization-related (focal) (partial) idiopathic epilepsy and epileptic syndromes with seizures of localized onset, not intractable, with status epilepticus','Localization-related (focal) (partial) idiopathic epilepsy and epileptic syndromes with seizures of localized onset, not intractable, with status epilepticus','Maladies du système nerveux','G40.001'),
('Localization-related (focal) (partial) idiopathic epilepsy and epileptic syndromes with seizures of localized onset, not intractable, without status epilepticus','Localization-related (focal) (partial) idiopathic epilepsy and epileptic syndromes with seizures of localized onset, not intractable, without status epilepticus','Maladies du système nerveux','G40.009'),
('Localization-related (focal) (partial) idiopathic epilepsy and epileptic syndromes with seizures of localized onset, intractable, with status epilepticus','Localization-related (focal) (partial) idiopathic epilepsy and epileptic syndromes with seizures of localized onset, intractable, with status epilepticus','Maladies du système nerveux','G40.011'),
('Localization-related (focal) (partial) idiopathic epilepsy and epileptic syndromes with seizures of localized onset, intractable, without status epilepticus','Localization-related (focal) (partial) idiopathic epilepsy and epileptic syndromes with seizures of localized onset, intractable, without status epilepticus','Maladies du système nerveux','G40.019'),
('Localization-related (focal) (partial) symptomatic epilepsy and epileptic syndromes with simple partial seizures, not intractable, with status epilepticus','Localization-related (focal) (partial) symptomatic epilepsy and epileptic syndromes with simple partial seizures, not intractable, with status epilepticus','Maladies du système nerveux','G40.101'),
('Localization-related (focal) (partial) symptomatic epilepsy and epileptic syndromes with simple partial seizures, not intractable, without status epilepticus','Localization-related (focal) (partial) symptomatic epilepsy and epileptic syndromes with simple partial seizures, not intractable, without status epilepticus','Maladies du système nerveux','G40.109'),
('Localization-related (focal) (partial) symptomatic epilepsy and epileptic syndromes with simple partial seizures, intractable, with status epilepticus','Localization-related (focal) (partial) symptomatic epilepsy and epileptic syndromes with simple partial seizures, intractable, with status epilepticus','Maladies du système nerveux','G40.111'),
('Localization-related (focal) (partial) symptomatic epilepsy and epileptic syndromes with simple partial seizures, intractable, without status epilepticus','Localization-related (focal) (partial) symptomatic epilepsy and epileptic syndromes with simple partial seizures, intractable, without status epilepticus','Maladies du système nerveux','G40.119'),
('Localization-related (focal) (partial) symptomatic epilepsy and epileptic syndromes with complex partial seizures, not intractable, with status epilepticus','Localization-related (focal) (partial) symptomatic epilepsy and epileptic syndromes with complex partial seizures, not intractable, with status epilepticus','Maladies du système nerveux','G40.201'),
('Localization-related (focal) (partial) symptomatic epilepsy and epileptic syndromes with complex partial seizures, not intractable, without status epilepticus','Localization-related (focal) (partial) symptomatic epilepsy and epileptic syndromes with complex partial seizures, not intractable, without status epilepticus','Maladies du système nerveux','G40.209'),
('Localization-related (focal) (partial) symptomatic epilepsy and epileptic syndromes with complex partial seizures, intractable, with status epilepticus','Localization-related (focal) (partial) symptomatic epilepsy and epileptic syndromes with complex partial seizures, intractable, with status epilepticus','Maladies du système nerveux','G40.211'),
('Localization-related (focal) (partial) symptomatic epilepsy and epileptic syndromes with complex partial seizures, intractable, without status epilepticus','Localization-related (focal) (partial) symptomatic epilepsy and epileptic syndromes with complex partial seizures, intractable, without status epilepticus','Maladies du système nerveux','G40.219'),
('Generalized idiopathic epilepsy and epileptic syndromes, not intractable, with status epilepticus','Generalized idiopathic epilepsy and epileptic syndromes, not intractable, with status epilepticus','Maladies du système nerveux','G40.301'),
('Generalized idiopathic epilepsy and epileptic syndromes, not intractable, without status epilepticus','Generalized idiopathic epilepsy and epileptic syndromes, not intractable, without status epilepticus','Maladies du système nerveux','G40.309'),
('non spécifié cord compression','Unspecified cord compression','Maladies du système nerveux','G95.20'),
('autre cord compression','Other cord compression','Maladies du système nerveux','G95.29'),
('Conus medullaris syndrome','Conus medullaris syndrome','Maladies du système nerveux','G95.81'),
('autre specified diseases of spinal cord','Other specified diseases of spinal cord','Maladies du système nerveux','G95.89'),
('maladie of spinal cord, non spécifié','Disease of spinal cord, unspecified','Maladies du système nerveux','G95.9'),
('Cerebrospinal fluid leak, non spécifié','Cerebrospinal fluid leak, unspecified','Maladies du système nerveux','G96.00'),
('Cranial cerebrospinal fluid leak, spontaneous','Cranial cerebrospinal fluid leak, spontaneous','Maladies du système nerveux','G96.01'),
('Trichiasis without entropion left lower eyelid','Trichiasis without entropion left lower eyelid','Maladies de l''œil et de ses annexes','H02.055'),
('Trichiasis without entropion left eye, non spécifié eyelid','Trichiasis without entropion left eye, unspecified eyelid','Maladies de l''œil et de ses annexes','H02.056'),
('Trichiasis without entropion non spécifié eye, non spécifié eyelid','Trichiasis without entropion unspecified eye, unspecified eyelid','Maladies de l''œil et de ses annexes','H02.059'),
('non spécifié ectropion of right upper eyelid','Unspecified ectropion of right upper eyelid','Maladies de l''œil et de ses annexes','H02.101'),
('non spécifié ectropion of right lower eyelid','Unspecified ectropion of right lower eyelid','Maladies de l''œil et de ses annexes','H02.102'),
('non spécifié ectropion of right eye, non spécifié eyelid','Unspecified ectropion of right eye, unspecified eyelid','Maladies de l''œil et de ses annexes','H02.103'),
('non spécifié ectropion of left upper eyelid','Unspecified ectropion of left upper eyelid','Maladies de l''œil et de ses annexes','H02.104'),
('Contact blepharoconjunctivitis, right eye','Contact blepharoconjunctivitis, right eye','Maladies de l''œil et de ses annexes','H10.531'),
('Contact blepharoconjunctivitis, left eye','Contact blepharoconjunctivitis, left eye','Maladies de l''œil et de ses annexes','H10.532'),
('Contact blepharoconjunctivitis, bilateral','Contact blepharoconjunctivitis, bilateral','Maladies de l''œil et de ses annexes','H10.533'),
('Contact blepharoconjunctivitis, non spécifié eye','Contact blepharoconjunctivitis, unspecified eye','Maladies de l''œil et de ses annexes','H10.539'),
('Pingueculitis, right eye','Pingueculitis, right eye','Maladies de l''œil et de ses annexes','H10.811'),
('Pingueculitis, left eye','Pingueculitis, left eye','Maladies de l''œil et de ses annexes','H10.812')
ON CONFLICT (nom_fr) DO NOTHING;
