-- icd10v2_batch_064.sql (80 rows)
INSERT INTO pathologies (nom_fr, nom_en, categorie, icd10_code)
VALUES
('Conversion trouble with sensory symptom or deficit','Conversion disorder with sensory symptom or deficit','Troubles mentaux et du comportement','F44.6'),
('Conversion trouble with mixed symptom presentation','Conversion disorder with mixed symptom presentation','Troubles mentaux et du comportement','F44.7'),
('Dissociative identity trouble','Dissociative identity disorder','Troubles mentaux et du comportement','F44.81'),
('autre dissociative and conversion disorders','Other dissociative and conversion disorders','Troubles mentaux et du comportement','F44.89'),
('Dissociative and conversion trouble, non spécifié','Dissociative and conversion disorder, unspecified','Troubles mentaux et du comportement','F44.9'),
('Somatization trouble','Somatization disorder','Troubles mentaux et du comportement','F45.0'),
('Undifferentiated somatoform trouble','Undifferentiated somatoform disorder','Troubles mentaux et du comportement','F45.1'),
('Hypochondriacal trouble, non spécifié','Hypochondriacal disorder, unspecified','Troubles mentaux et du comportement','F45.20'),
('Hypochondriasis','Hypochondriasis','Troubles mentaux et du comportement','F45.21'),
('Body dysmorphic trouble','Body dysmorphic disorder','Troubles mentaux et du comportement','F45.22'),
('autre hypochondriacal disorders','Other hypochondriacal disorders','Troubles mentaux et du comportement','F45.29'),
('Pain trouble exclusively related to psychological factors','Pain disorder exclusively related to psychological factors','Troubles mentaux et du comportement','F45.41'),
('Pain trouble with related psychological factors','Pain disorder with related psychological factors','Troubles mentaux et du comportement','F45.42'),
('autre somatoform disorders','Other somatoform disorders','Troubles mentaux et du comportement','F45.8'),
('Somatoform trouble, non spécifié','Somatoform disorder, unspecified','Troubles mentaux et du comportement','F45.9'),
('Depersonalization-derealization syndrome','Depersonalization-derealization syndrome','Troubles mentaux et du comportement','F48.1'),
('Pseudobulbar affect','Pseudobulbar affect','Troubles mentaux et du comportement','F48.2'),
('autre specified nonpsychotic mental disorders','Other specified nonpsychotic mental disorders','Troubles mentaux et du comportement','F48.8'),
('Nonpsychotic mental trouble, non spécifié','Nonpsychotic mental disorder, unspecified','Troubles mentaux et du comportement','F48.9'),
('Anorexia nervosa, non spécifié','Anorexia nervosa, unspecified','Troubles mentaux et du comportement','F50.00'),
('Anorexia nervosa, restricting type, mild','Anorexia nervosa, restricting type, mild','Troubles mentaux et du comportement','F50.010'),
('Anorexia nervosa, restricting type, moderate','Anorexia nervosa, restricting type, moderate','Troubles mentaux et du comportement','F50.011'),
('Anorexia nervosa, restricting type, severe','Anorexia nervosa, restricting type, severe','Troubles mentaux et du comportement','F50.012'),
('Anorexia nervosa, restricting type, extreme','Anorexia nervosa, restricting type, extreme','Troubles mentaux et du comportement','F50.013'),
('Anorexia nervosa, restricting type, in remission','Anorexia nervosa, restricting type, in remission','Troubles mentaux et du comportement','F50.014'),
('Anorexia nervosa, restricting type, non spécifié','Anorexia nervosa, restricting type, unspecified','Troubles mentaux et du comportement','F50.019'),
('Anorexia nervosa, binge eating/purging type, mild','Anorexia nervosa, binge eating/purging type, mild','Troubles mentaux et du comportement','F50.020'),
('Anorexia nervosa, binge eating/purging type, moderate','Anorexia nervosa, binge eating/purging type, moderate','Troubles mentaux et du comportement','F50.021'),
('Anorexia nervosa, binge eating/purging type, severe','Anorexia nervosa, binge eating/purging type, severe','Troubles mentaux et du comportement','F50.022'),
('Anorexia nervosa, binge eating/purging type, extreme','Anorexia nervosa, binge eating/purging type, extreme','Troubles mentaux et du comportement','F50.023'),
('Anorexia nervosa, binge eating/purging type, in remission','Anorexia nervosa, binge eating/purging type, in remission','Troubles mentaux et du comportement','F50.024'),
('Anorexia nervosa, binge eating/purging type, non spécifié','Anorexia nervosa, binge eating/purging type, unspecified','Troubles mentaux et du comportement','F50.029'),
('Bulimia nervosa, non spécifié','Bulimia nervosa, unspecified','Troubles mentaux et du comportement','F50.20'),
('Bulimia nervosa, mild','Bulimia nervosa, mild','Troubles mentaux et du comportement','F50.21'),
('Bulimia nervosa, moderate','Bulimia nervosa, moderate','Troubles mentaux et du comportement','F50.22'),
('Bulimia nervosa, severe','Bulimia nervosa, severe','Troubles mentaux et du comportement','F50.23'),
('Bulimia nervosa, extreme','Bulimia nervosa, extreme','Troubles mentaux et du comportement','F50.24'),
('Bulimia nervosa, in remission','Bulimia nervosa, in remission','Troubles mentaux et du comportement','F50.25'),
('Binge eating trouble, mild','Binge eating disorder, mild','Troubles mentaux et du comportement','F50.810'),
('Binge eating trouble, moderate','Binge eating disorder, moderate','Troubles mentaux et du comportement','F50.811'),
('Binge eating trouble, severe','Binge eating disorder, severe','Troubles mentaux et du comportement','F50.812'),
('Binge eating trouble, extreme','Binge eating disorder, extreme','Troubles mentaux et du comportement','F50.813'),
('Binge eating trouble, in remission','Binge eating disorder, in remission','Troubles mentaux et du comportement','F50.814'),
('Binge eating trouble, non spécifié','Binge eating disorder, unspecified','Troubles mentaux et du comportement','F50.819'),
('Avoidant/restrictive food intake trouble','Avoidant/restrictive food intake disorder','Troubles mentaux et du comportement','F50.82'),
('Pica in adults','Pica in adults','Troubles mentaux et du comportement','F50.83'),
('Rumination trouble in adults','Rumination disorder in adults','Troubles mentaux et du comportement','F50.84'),
('autre specified eating trouble','Other specified eating disorder','Troubles mentaux et du comportement','F50.89'),
('Eating trouble, non spécifié','Eating disorder, unspecified','Troubles mentaux et du comportement','F50.9'),
('primitif insomnia','Primary insomnia','Troubles mentaux et du comportement','F51.01'),
('Adjustment insomnia','Adjustment insomnia','Troubles mentaux et du comportement','F51.02'),
('Paradoxical insomnia','Paradoxical insomnia','Troubles mentaux et du comportement','F51.03'),
('Psychophysiologic insomnia','Psychophysiologic insomnia','Troubles mentaux et du comportement','F51.04'),
('Insomnia due to autre mental trouble','Insomnia due to other mental disorder','Troubles mentaux et du comportement','F51.05'),
('autre insomnia not due to a substance or known physiological condition','Other insomnia not due to a substance or known physiological condition','Troubles mentaux et du comportement','F51.09'),
('primitif hypersomnia','Primary hypersomnia','Troubles mentaux et du comportement','F51.11'),
('Insufficient sleep syndrome','Insufficient sleep syndrome','Troubles mentaux et du comportement','F51.12'),
('Hypersomnia due to autre mental trouble','Hypersomnia due to other mental disorder','Troubles mentaux et du comportement','F51.13'),
('autre hypersomnia not due to a substance or known physiological condition','Other hypersomnia not due to a substance or known physiological condition','Troubles mentaux et du comportement','F51.19'),
('Sleepwalking [somnambulism]','Sleepwalking [somnambulism]','Troubles mentaux et du comportement','F51.3'),
('Sleep terrors [night terrors]','Sleep terrors [night terrors]','Troubles mentaux et du comportement','F51.4'),
('Nightmare trouble','Nightmare disorder','Troubles mentaux et du comportement','F51.5'),
('autre sleep disorders not due to a substance or known physiological condition','Other sleep disorders not due to a substance or known physiological condition','Troubles mentaux et du comportement','F51.8'),
('Sleep trouble not due to a substance or known physiological condition, non spécifié','Sleep disorder not due to a substance or known physiological condition, unspecified','Troubles mentaux et du comportement','F51.9'),
('Hypoactive sexual desire trouble','Hypoactive sexual desire disorder','Troubles mentaux et du comportement','F52.0'),
('Sexual aversion trouble','Sexual aversion disorder','Troubles mentaux et du comportement','F52.1'),
('Male erectile trouble','Male erectile disorder','Troubles mentaux et du comportement','F52.21'),
('Female sexual arousal trouble','Female sexual arousal disorder','Troubles mentaux et du comportement','F52.22'),
('Female orgasmic trouble','Female orgasmic disorder','Troubles mentaux et du comportement','F52.31'),
('Male orgasmic trouble','Male orgasmic disorder','Troubles mentaux et du comportement','F52.32'),
('Premature ejaculation','Premature ejaculation','Troubles mentaux et du comportement','F52.4'),
('Vaginismus not due to a substance or known physiological condition','Vaginismus not due to a substance or known physiological condition','Troubles mentaux et du comportement','F52.5'),
('Dyspareunia not due to a substance or known physiological condition','Dyspareunia not due to a substance or known physiological condition','Troubles mentaux et du comportement','F52.6'),
('autre sexual dysfunction not due to a substance or known physiological condition','Other sexual dysfunction not due to a substance or known physiological condition','Troubles mentaux et du comportement','F52.8'),
('non spécifié sexual dysfunction not due to a substance or known physiological condition','Unspecified sexual dysfunction not due to a substance or known physiological condition','Troubles mentaux et du comportement','F52.9'),
('Postpartum depression','Postpartum depression','Troubles mentaux et du comportement','F53.0'),
('Puerperal psychosis','Puerperal psychosis','Troubles mentaux et du comportement','F53.1'),
('Psychological and behavioral factors associated with disorders or diseases classified elsewhere','Psychological and behavioral factors associated with disorders or diseases classified elsewhere','Troubles mentaux et du comportement','F54'),
('Abuse of antacids','Abuse of antacids','Troubles mentaux et du comportement','F55.0'),
('Abuse of herbal or folk remedies','Abuse of herbal or folk remedies','Troubles mentaux et du comportement','F55.1')
ON CONFLICT (nom_fr) DO NOTHING;
