-- icd10v2_batch_258.sql (80 rows)
INSERT INTO pathologies (nom_fr, nom_en, categorie, icd10_code)
VALUES
('congénital facial asymmetry','Congenital facial asymmetry','Malformations congénitales et anomalies chromosomiques','Q67.0'),
('congénital compression facies','Congenital compression facies','Malformations congénitales et anomalies chromosomiques','Q67.1'),
('Dolichocephaly','Dolichocephaly','Malformations congénitales et anomalies chromosomiques','Q67.2'),
('Plagiocephaly','Plagiocephaly','Malformations congénitales et anomalies chromosomiques','Q67.3'),
('autre congénital deformities of skull, face and jaw','Other congenital deformities of skull, face and jaw','Malformations congénitales et anomalies chromosomiques','Q67.4'),
('congénital deformity of spine','Congenital deformity of spine','Malformations congénitales et anomalies chromosomiques','Q67.5'),
('Pectus excavatum','Pectus excavatum','Malformations congénitales et anomalies chromosomiques','Q67.6'),
('Pectus carinatum','Pectus carinatum','Malformations congénitales et anomalies chromosomiques','Q67.7'),
('autre congénital deformities of chest','Other congenital deformities of chest','Malformations congénitales et anomalies chromosomiques','Q67.8'),
('congénital deformity of sternocleidomastoid muscle','Congenital deformity of sternocleidomastoid muscle','Malformations congénitales et anomalies chromosomiques','Q68.0'),
('congénital deformity of finger(s) and hand','Congenital deformity of finger(s) and hand','Malformations congénitales et anomalies chromosomiques','Q68.1'),
('congénital deformity of knee','Congenital deformity of knee','Malformations congénitales et anomalies chromosomiques','Q68.2'),
('congénital bowing of femur','Congenital bowing of femur','Malformations congénitales et anomalies chromosomiques','Q68.3'),
('congénital bowing of tibia and fibula','Congenital bowing of tibia and fibula','Malformations congénitales et anomalies chromosomiques','Q68.4'),
('congénital bowing of long bones of leg, non spécifié','Congenital bowing of long bones of leg, unspecified','Malformations congénitales et anomalies chromosomiques','Q68.5'),
('Discoid meniscus','Discoid meniscus','Malformations congénitales et anomalies chromosomiques','Q68.6'),
('autre specified congénital musculoskeletal deformities','Other specified congenital musculoskeletal deformities','Malformations congénitales et anomalies chromosomiques','Q68.8'),
('Accessory finger(s)','Accessory finger(s)','Malformations congénitales et anomalies chromosomiques','Q69.0'),
('Accessory thumb(s)','Accessory thumb(s)','Malformations congénitales et anomalies chromosomiques','Q69.1'),
('Accessory toe(s)','Accessory toe(s)','Malformations congénitales et anomalies chromosomiques','Q69.2'),
('Polydactyly, non spécifié','Polydactyly, unspecified','Malformations congénitales et anomalies chromosomiques','Q69.9'),
('Fused fingers, non spécifié hand','Fused fingers, unspecified hand','Malformations congénitales et anomalies chromosomiques','Q70.00'),
('Fused fingers, right hand','Fused fingers, right hand','Malformations congénitales et anomalies chromosomiques','Q70.01'),
('Fused fingers, left hand','Fused fingers, left hand','Malformations congénitales et anomalies chromosomiques','Q70.02'),
('Fused fingers, bilateral','Fused fingers, bilateral','Malformations congénitales et anomalies chromosomiques','Q70.03'),
('Webbed fingers, non spécifié hand','Webbed fingers, unspecified hand','Malformations congénitales et anomalies chromosomiques','Q70.10'),
('Webbed fingers, right hand','Webbed fingers, right hand','Malformations congénitales et anomalies chromosomiques','Q70.11'),
('Webbed fingers, left hand','Webbed fingers, left hand','Malformations congénitales et anomalies chromosomiques','Q70.12'),
('Webbed fingers, bilateral','Webbed fingers, bilateral','Malformations congénitales et anomalies chromosomiques','Q70.13'),
('Fused toes, non spécifié foot','Fused toes, unspecified foot','Malformations congénitales et anomalies chromosomiques','Q70.20'),
('Fused toes, right foot','Fused toes, right foot','Malformations congénitales et anomalies chromosomiques','Q70.21'),
('Fused toes, left foot','Fused toes, left foot','Malformations congénitales et anomalies chromosomiques','Q70.22'),
('Fused toes, bilateral','Fused toes, bilateral','Malformations congénitales et anomalies chromosomiques','Q70.23'),
('Webbed toes, non spécifié foot','Webbed toes, unspecified foot','Malformations congénitales et anomalies chromosomiques','Q70.30'),
('Webbed toes, right foot','Webbed toes, right foot','Malformations congénitales et anomalies chromosomiques','Q70.31'),
('Webbed toes, left foot','Webbed toes, left foot','Malformations congénitales et anomalies chromosomiques','Q70.32'),
('Webbed toes, bilateral','Webbed toes, bilateral','Malformations congénitales et anomalies chromosomiques','Q70.33'),
('Polysyndactyly, non spécifié','Polysyndactyly, unspecified','Malformations congénitales et anomalies chromosomiques','Q70.4'),
('Syndactyly, non spécifié','Syndactyly, unspecified','Malformations congénitales et anomalies chromosomiques','Q70.9'),
('congénital complete absence of non spécifié upper limb','Congenital complete absence of unspecified upper limb','Malformations congénitales et anomalies chromosomiques','Q71.00'),
('congénital complete absence of right upper limb','Congenital complete absence of right upper limb','Malformations congénitales et anomalies chromosomiques','Q71.01'),
('congénital complete absence of left upper limb','Congenital complete absence of left upper limb','Malformations congénitales et anomalies chromosomiques','Q71.02'),
('congénital complete absence of upper limb, bilateral','Congenital complete absence of upper limb, bilateral','Malformations congénitales et anomalies chromosomiques','Q71.03'),
('congénital absence of non spécifié upper arm and forearm with hand present','Congenital absence of unspecified upper arm and forearm with hand present','Malformations congénitales et anomalies chromosomiques','Q71.10'),
('congénital absence of right upper arm and forearm with hand present','Congenital absence of right upper arm and forearm with hand present','Malformations congénitales et anomalies chromosomiques','Q71.11'),
('congénital absence of left upper arm and forearm with hand present','Congenital absence of left upper arm and forearm with hand present','Malformations congénitales et anomalies chromosomiques','Q71.12'),
('congénital absence of upper arm and forearm with hand present, bilateral','Congenital absence of upper arm and forearm with hand present, bilateral','Malformations congénitales et anomalies chromosomiques','Q71.13'),
('congénital absence of both forearm and hand, non spécifié upper limb','Congenital absence of both forearm and hand, unspecified upper limb','Malformations congénitales et anomalies chromosomiques','Q71.20'),
('congénital absence of both forearm and hand, right upper limb','Congenital absence of both forearm and hand, right upper limb','Malformations congénitales et anomalies chromosomiques','Q71.21'),
('congénital absence of both forearm and hand, left upper limb','Congenital absence of both forearm and hand, left upper limb','Malformations congénitales et anomalies chromosomiques','Q71.22'),
('congénital absence of both forearm and hand, bilateral','Congenital absence of both forearm and hand, bilateral','Malformations congénitales et anomalies chromosomiques','Q71.23'),
('congénital absence of non spécifié hand and finger','Congenital absence of unspecified hand and finger','Malformations congénitales et anomalies chromosomiques','Q71.30'),
('congénital absence of right hand and finger','Congenital absence of right hand and finger','Malformations congénitales et anomalies chromosomiques','Q71.31'),
('congénital absence of left hand and finger','Congenital absence of left hand and finger','Malformations congénitales et anomalies chromosomiques','Q71.32'),
('congénital absence of hand and finger, bilateral','Congenital absence of hand and finger, bilateral','Malformations congénitales et anomalies chromosomiques','Q71.33'),
('Longitudinal reduction defect of non spécifié radius','Longitudinal reduction defect of unspecified radius','Malformations congénitales et anomalies chromosomiques','Q71.40'),
('Longitudinal reduction defect of right radius','Longitudinal reduction defect of right radius','Malformations congénitales et anomalies chromosomiques','Q71.41'),
('Longitudinal reduction defect of left radius','Longitudinal reduction defect of left radius','Malformations congénitales et anomalies chromosomiques','Q71.42'),
('Longitudinal reduction defect of radius, bilateral','Longitudinal reduction defect of radius, bilateral','Malformations congénitales et anomalies chromosomiques','Q71.43'),
('Longitudinal reduction defect of non spécifié ulna','Longitudinal reduction defect of unspecified ulna','Malformations congénitales et anomalies chromosomiques','Q71.50'),
('Longitudinal reduction defect of right ulna','Longitudinal reduction defect of right ulna','Malformations congénitales et anomalies chromosomiques','Q71.51'),
('Longitudinal reduction defect of left ulna','Longitudinal reduction defect of left ulna','Malformations congénitales et anomalies chromosomiques','Q71.52'),
('Longitudinal reduction defect of ulna, bilateral','Longitudinal reduction defect of ulna, bilateral','Malformations congénitales et anomalies chromosomiques','Q71.53'),
('Lobster-claw hand, non spécifié hand','Lobster-claw hand, unspecified hand','Malformations congénitales et anomalies chromosomiques','Q71.60'),
('Lobster-claw right hand','Lobster-claw right hand','Malformations congénitales et anomalies chromosomiques','Q71.61'),
('Lobster-claw left hand','Lobster-claw left hand','Malformations congénitales et anomalies chromosomiques','Q71.62'),
('Lobster-claw hand, bilateral','Lobster-claw hand, bilateral','Malformations congénitales et anomalies chromosomiques','Q71.63'),
('congénital shortening of right upper limb','Congenital shortening of right upper limb','Malformations congénitales et anomalies chromosomiques','Q71.811'),
('congénital shortening of left upper limb','Congenital shortening of left upper limb','Malformations congénitales et anomalies chromosomiques','Q71.812'),
('congénital shortening of upper limb, bilateral','Congenital shortening of upper limb, bilateral','Malformations congénitales et anomalies chromosomiques','Q71.813'),
('congénital shortening of non spécifié upper limb','Congenital shortening of unspecified upper limb','Malformations congénitales et anomalies chromosomiques','Q71.819'),
('autre reduction defects of right upper limb','Other reduction defects of right upper limb','Malformations congénitales et anomalies chromosomiques','Q71.891'),
('autre reduction defects of left upper limb','Other reduction defects of left upper limb','Malformations congénitales et anomalies chromosomiques','Q71.892'),
('autre reduction defects of upper limb, bilateral','Other reduction defects of upper limb, bilateral','Malformations congénitales et anomalies chromosomiques','Q71.893'),
('autre reduction defects of non spécifié upper limb','Other reduction defects of unspecified upper limb','Malformations congénitales et anomalies chromosomiques','Q71.899'),
('non spécifié reduction defect of non spécifié upper limb','Unspecified reduction defect of unspecified upper limb','Malformations congénitales et anomalies chromosomiques','Q71.90'),
('non spécifié reduction defect of right upper limb','Unspecified reduction defect of right upper limb','Malformations congénitales et anomalies chromosomiques','Q71.91'),
('non spécifié reduction defect of left upper limb','Unspecified reduction defect of left upper limb','Malformations congénitales et anomalies chromosomiques','Q71.92'),
('non spécifié reduction defect of upper limb, bilateral','Unspecified reduction defect of upper limb, bilateral','Malformations congénitales et anomalies chromosomiques','Q71.93'),
('congénital complete absence of non spécifié lower limb','Congenital complete absence of unspecified lower limb','Malformations congénitales et anomalies chromosomiques','Q72.00')
ON CONFLICT (nom_fr) DO NOTHING;
