-- icd10v2_batch_492.sql (80 rows)
INSERT INTO pathologies (nom_fr, nom_en, categorie, icd10_code)
VALUES
('Injury of trigeminal nerve, left side, initial encounter','Injury of trigeminal nerve, left side, initial encounter','Traumatismes, empoisonnements et autres causes externes','S04.32XA'),
('Injury of trigeminal nerve, left side, subsequent encounter','Injury of trigeminal nerve, left side, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S04.32XD'),
('Injury of trigeminal nerve, left side, sequela','Injury of trigeminal nerve, left side, sequela','Traumatismes, empoisonnements et autres causes externes','S04.32XS'),
('Injury of abducent nerve, non spécifié side, initial encounter','Injury of abducent nerve, unspecified side, initial encounter','Traumatismes, empoisonnements et autres causes externes','S04.40XA'),
('Injury of abducent nerve, non spécifié side, subsequent encounter','Injury of abducent nerve, unspecified side, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S04.40XD'),
('Injury of abducent nerve, non spécifié side, sequela','Injury of abducent nerve, unspecified side, sequela','Traumatismes, empoisonnements et autres causes externes','S04.40XS'),
('Injury of abducent nerve, right side, initial encounter','Injury of abducent nerve, right side, initial encounter','Traumatismes, empoisonnements et autres causes externes','S04.41XA'),
('Injury of abducent nerve, right side, subsequent encounter','Injury of abducent nerve, right side, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S04.41XD'),
('Injury of abducent nerve, right side, sequela','Injury of abducent nerve, right side, sequela','Traumatismes, empoisonnements et autres causes externes','S04.41XS'),
('Injury of abducent nerve, left side, initial encounter','Injury of abducent nerve, left side, initial encounter','Traumatismes, empoisonnements et autres causes externes','S04.42XA'),
('Injury of abducent nerve, left side, subsequent encounter','Injury of abducent nerve, left side, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S04.42XD'),
('Injury of abducent nerve, left side, sequela','Injury of abducent nerve, left side, sequela','Traumatismes, empoisonnements et autres causes externes','S04.42XS'),
('Injury of facial nerve, non spécifié side, initial encounter','Injury of facial nerve, unspecified side, initial encounter','Traumatismes, empoisonnements et autres causes externes','S04.50XA'),
('Injury of facial nerve, non spécifié side, subsequent encounter','Injury of facial nerve, unspecified side, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S04.50XD'),
('Injury of facial nerve, non spécifié side, sequela','Injury of facial nerve, unspecified side, sequela','Traumatismes, empoisonnements et autres causes externes','S04.50XS'),
('Injury of facial nerve, right side, initial encounter','Injury of facial nerve, right side, initial encounter','Traumatismes, empoisonnements et autres causes externes','S04.51XA'),
('Injury of facial nerve, right side, subsequent encounter','Injury of facial nerve, right side, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S04.51XD'),
('Injury of facial nerve, right side, sequela','Injury of facial nerve, right side, sequela','Traumatismes, empoisonnements et autres causes externes','S04.51XS'),
('Injury of facial nerve, left side, initial encounter','Injury of facial nerve, left side, initial encounter','Traumatismes, empoisonnements et autres causes externes','S04.52XA'),
('Injury of facial nerve, left side, subsequent encounter','Injury of facial nerve, left side, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S04.52XD'),
('Injury of facial nerve, left side, sequela','Injury of facial nerve, left side, sequela','Traumatismes, empoisonnements et autres causes externes','S04.52XS'),
('Injury of acoustic nerve, non spécifié side, initial encounter','Injury of acoustic nerve, unspecified side, initial encounter','Traumatismes, empoisonnements et autres causes externes','S04.60XA'),
('Injury of acoustic nerve, non spécifié side, subsequent encounter','Injury of acoustic nerve, unspecified side, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S04.60XD'),
('Injury of acoustic nerve, non spécifié side, sequela','Injury of acoustic nerve, unspecified side, sequela','Traumatismes, empoisonnements et autres causes externes','S04.60XS'),
('Injury of acoustic nerve, right side, initial encounter','Injury of acoustic nerve, right side, initial encounter','Traumatismes, empoisonnements et autres causes externes','S04.61XA'),
('Injury of acoustic nerve, right side, subsequent encounter','Injury of acoustic nerve, right side, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S04.61XD'),
('Injury of acoustic nerve, right side, sequela','Injury of acoustic nerve, right side, sequela','Traumatismes, empoisonnements et autres causes externes','S04.61XS'),
('Injury of acoustic nerve, left side, initial encounter','Injury of acoustic nerve, left side, initial encounter','Traumatismes, empoisonnements et autres causes externes','S04.62XA'),
('Injury of acoustic nerve, left side, subsequent encounter','Injury of acoustic nerve, left side, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S04.62XD'),
('Injury of acoustic nerve, left side, sequela','Injury of acoustic nerve, left side, sequela','Traumatismes, empoisonnements et autres causes externes','S04.62XS'),
('Injury of accessory nerve, non spécifié side, initial encounter','Injury of accessory nerve, unspecified side, initial encounter','Traumatismes, empoisonnements et autres causes externes','S04.70XA'),
('Injury of accessory nerve, non spécifié side, subsequent encounter','Injury of accessory nerve, unspecified side, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S04.70XD'),
('Injury of accessory nerve, non spécifié side, sequela','Injury of accessory nerve, unspecified side, sequela','Traumatismes, empoisonnements et autres causes externes','S04.70XS'),
('Injury of accessory nerve, right side, initial encounter','Injury of accessory nerve, right side, initial encounter','Traumatismes, empoisonnements et autres causes externes','S04.71XA'),
('Injury of accessory nerve, right side, subsequent encounter','Injury of accessory nerve, right side, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S04.71XD'),
('Injury of accessory nerve, right side, sequela','Injury of accessory nerve, right side, sequela','Traumatismes, empoisonnements et autres causes externes','S04.71XS'),
('Injury of accessory nerve, left side, initial encounter','Injury of accessory nerve, left side, initial encounter','Traumatismes, empoisonnements et autres causes externes','S04.72XA'),
('Injury of accessory nerve, left side, subsequent encounter','Injury of accessory nerve, left side, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S04.72XD'),
('Injury of accessory nerve, left side, sequela','Injury of accessory nerve, left side, sequela','Traumatismes, empoisonnements et autres causes externes','S04.72XS'),
('Injury of olfactory [1st ] nerve, right side, initial encounter','Injury of olfactory [1st ] nerve, right side, initial encounter','Traumatismes, empoisonnements et autres causes externes','S04.811A'),
('Injury of olfactory [1st ] nerve, right side, subsequent encounter','Injury of olfactory [1st ] nerve, right side, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S04.811D'),
('Injury of olfactory [1st ] nerve, right side, sequela','Injury of olfactory [1st ] nerve, right side, sequela','Traumatismes, empoisonnements et autres causes externes','S04.811S'),
('Injury of olfactory [1st ] nerve, left side, initial encounter','Injury of olfactory [1st ] nerve, left side, initial encounter','Traumatismes, empoisonnements et autres causes externes','S04.812A'),
('Injury of olfactory [1st ] nerve, left side, subsequent encounter','Injury of olfactory [1st ] nerve, left side, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S04.812D'),
('Injury of olfactory [1st ] nerve, left side, sequela','Injury of olfactory [1st ] nerve, left side, sequela','Traumatismes, empoisonnements et autres causes externes','S04.812S'),
('Injury of olfactory [1st ] nerve, non spécifié side, initial encounter','Injury of olfactory [1st ] nerve, unspecified side, initial encounter','Traumatismes, empoisonnements et autres causes externes','S04.819A'),
('Injury of olfactory [1st ] nerve, non spécifié side, subsequent encounter','Injury of olfactory [1st ] nerve, unspecified side, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S04.819D'),
('Injury of olfactory [1st ] nerve, non spécifié side, sequela','Injury of olfactory [1st ] nerve, unspecified side, sequela','Traumatismes, empoisonnements et autres causes externes','S04.819S'),
('Injury of autre cranial nerves, right side, initial encounter','Injury of other cranial nerves, right side, initial encounter','Traumatismes, empoisonnements et autres causes externes','S04.891A'),
('Injury of autre cranial nerves, right side, subsequent encounter','Injury of other cranial nerves, right side, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S04.891D'),
('Injury of autre cranial nerves, right side, sequela','Injury of other cranial nerves, right side, sequela','Traumatismes, empoisonnements et autres causes externes','S04.891S'),
('Injury of autre cranial nerves, left side, initial encounter','Injury of other cranial nerves, left side, initial encounter','Traumatismes, empoisonnements et autres causes externes','S04.892A'),
('Injury of autre cranial nerves, left side, subsequent encounter','Injury of other cranial nerves, left side, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S04.892D'),
('Injury of autre cranial nerves, left side, sequela','Injury of other cranial nerves, left side, sequela','Traumatismes, empoisonnements et autres causes externes','S04.892S'),
('Injury of autre cranial nerves, non spécifié side, initial encounter','Injury of other cranial nerves, unspecified side, initial encounter','Traumatismes, empoisonnements et autres causes externes','S04.899A'),
('Injury of autre cranial nerves, non spécifié side, subsequent encounter','Injury of other cranial nerves, unspecified side, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S04.899D'),
('Injury of autre cranial nerves, non spécifié side, sequela','Injury of other cranial nerves, unspecified side, sequela','Traumatismes, empoisonnements et autres causes externes','S04.899S'),
('Injury of non spécifié cranial nerve, initial encounter','Injury of unspecified cranial nerve, initial encounter','Traumatismes, empoisonnements et autres causes externes','S04.9XXA'),
('Injury of non spécifié cranial nerve, subsequent encounter','Injury of unspecified cranial nerve, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S04.9XXD'),
('Injury of non spécifié cranial nerve, sequela','Injury of unspecified cranial nerve, sequela','Traumatismes, empoisonnements et autres causes externes','S04.9XXS'),
('Injury of conjunctiva and corneal abrasion without foreign body, non spécifié eye, initial encounter','Injury of conjunctiva and corneal abrasion without foreign body, unspecified eye, initial encounter','Traumatismes, empoisonnements et autres causes externes','S05.00XA'),
('Injury of conjunctiva and corneal abrasion without foreign body, non spécifié eye, subsequent encounter','Injury of conjunctiva and corneal abrasion without foreign body, unspecified eye, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S05.00XD'),
('Injury of conjunctiva and corneal abrasion without foreign body, non spécifié eye, sequela','Injury of conjunctiva and corneal abrasion without foreign body, unspecified eye, sequela','Traumatismes, empoisonnements et autres causes externes','S05.00XS'),
('Injury of conjunctiva and corneal abrasion without foreign body, right eye, initial encounter','Injury of conjunctiva and corneal abrasion without foreign body, right eye, initial encounter','Traumatismes, empoisonnements et autres causes externes','S05.01XA'),
('Injury of conjunctiva and corneal abrasion without foreign body, right eye, subsequent encounter','Injury of conjunctiva and corneal abrasion without foreign body, right eye, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S05.01XD'),
('Injury of conjunctiva and corneal abrasion without foreign body, right eye, sequela','Injury of conjunctiva and corneal abrasion without foreign body, right eye, sequela','Traumatismes, empoisonnements et autres causes externes','S05.01XS'),
('Injury of conjunctiva and corneal abrasion without foreign body, left eye, initial encounter','Injury of conjunctiva and corneal abrasion without foreign body, left eye, initial encounter','Traumatismes, empoisonnements et autres causes externes','S05.02XA'),
('Injury of conjunctiva and corneal abrasion without foreign body, left eye, subsequent encounter','Injury of conjunctiva and corneal abrasion without foreign body, left eye, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S05.02XD'),
('Injury of conjunctiva and corneal abrasion without foreign body, left eye, sequela','Injury of conjunctiva and corneal abrasion without foreign body, left eye, sequela','Traumatismes, empoisonnements et autres causes externes','S05.02XS'),
('Contusion of eyeball and orbital tissues, non spécifié eye, initial encounter','Contusion of eyeball and orbital tissues, unspecified eye, initial encounter','Traumatismes, empoisonnements et autres causes externes','S05.10XA'),
('Contusion of eyeball and orbital tissues, non spécifié eye, subsequent encounter','Contusion of eyeball and orbital tissues, unspecified eye, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S05.10XD'),
('Contusion of eyeball and orbital tissues, non spécifié eye, sequela','Contusion of eyeball and orbital tissues, unspecified eye, sequela','Traumatismes, empoisonnements et autres causes externes','S05.10XS'),
('Contusion of eyeball and orbital tissues, right eye, initial encounter','Contusion of eyeball and orbital tissues, right eye, initial encounter','Traumatismes, empoisonnements et autres causes externes','S05.11XA'),
('Contusion of eyeball and orbital tissues, right eye, subsequent encounter','Contusion of eyeball and orbital tissues, right eye, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S05.11XD'),
('Contusion of eyeball and orbital tissues, right eye, sequela','Contusion of eyeball and orbital tissues, right eye, sequela','Traumatismes, empoisonnements et autres causes externes','S05.11XS'),
('Contusion of eyeball and orbital tissues, left eye, initial encounter','Contusion of eyeball and orbital tissues, left eye, initial encounter','Traumatismes, empoisonnements et autres causes externes','S05.12XA'),
('Contusion of eyeball and orbital tissues, left eye, subsequent encounter','Contusion of eyeball and orbital tissues, left eye, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S05.12XD'),
('Contusion of eyeball and orbital tissues, left eye, sequela','Contusion of eyeball and orbital tissues, left eye, sequela','Traumatismes, empoisonnements et autres causes externes','S05.12XS'),
('Ocular laceration and rupture with prolapse or loss of intraocular tissue, non spécifié eye, initial encounter','Ocular laceration and rupture with prolapse or loss of intraocular tissue, unspecified eye, initial encounter','Traumatismes, empoisonnements et autres causes externes','S05.20XA'),
('Ocular laceration and rupture with prolapse or loss of intraocular tissue, non spécifié eye, subsequent encounter','Ocular laceration and rupture with prolapse or loss of intraocular tissue, unspecified eye, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S05.20XD')
ON CONFLICT (nom_fr) DO NOTHING;
