-- icd10_batch_023.sql (80 rows)
INSERT INTO pathologies (nom_fr, nom_en, categorie, icd10_code)
VALUES
('Webbing of neck','Webbing of neck','Malformations congénitales et anomalies chromosomiques','Q18.3'),
('Macrostomia','Macrostomia','Malformations congénitales et anomalies chromosomiques','Q18.4'),
('Microstomia','Microstomia','Malformations congénitales et anomalies chromosomiques','Q18.5'),
('Macrocheilia','Macrocheilia','Malformations congénitales et anomalies chromosomiques','Q18.6'),
('Microcheilia','Microcheilia','Malformations congénitales et anomalies chromosomiques','Q18.7'),
('autre specified congénital malformations of face and neck','Other specified congenital malformations of face and neck','Malformations congénitales et anomalies chromosomiques','Q18.8'),
('congénital malformation of face and neck, non spécifié','Congenital malformation of face and neck, unspecified','Malformations congénitales et anomalies chromosomiques','Q18.9'),
('Common arterial trunk','Common arterial trunk','Malformations congénitales et anomalies chromosomiques','Q20.0'),
('Double outlet right ventricle','Double outlet right ventricle','Malformations congénitales et anomalies chromosomiques','Q20.1'),
('Double outlet left ventricle','Double outlet left ventricle','Malformations congénitales et anomalies chromosomiques','Q20.2'),
('Discordant ventriculoarterial connection','Discordant ventriculoarterial connection','Malformations congénitales et anomalies chromosomiques','Q20.3'),
('Double inlet ventricle','Double inlet ventricle','Malformations congénitales et anomalies chromosomiques','Q20.4'),
('Discordant atrioventricular connection','Discordant atrioventricular connection','Malformations congénitales et anomalies chromosomiques','Q20.5'),
('Isomerism of atrial appendages','Isomerism of atrial appendages','Malformations congénitales et anomalies chromosomiques','Q20.6'),
('autre congénital malformations of cardiac chambers and connections','Other congenital malformations of cardiac chambers and connections','Malformations congénitales et anomalies chromosomiques','Q20.8'),
('congénital malformation of cardiac chambers and connections, non spécifié','Congenital malformation of cardiac chambers and connections, unspecified','Malformations congénitales et anomalies chromosomiques','Q20.9'),
('Ventricular septal defect','Ventricular septal defect','Malformations congénitales et anomalies chromosomiques','Q21.0'),
('Atrial septal defect, non spécifié','Atrial septal defect, unspecified','Malformations congénitales et anomalies chromosomiques','Q21.10'),
('Secundum atrial septal defect','Secundum atrial septal defect','Malformations congénitales et anomalies chromosomiques','Q21.11'),
('Patent foramen ovale','Patent foramen ovale','Malformations congénitales et anomalies chromosomiques','Q21.12'),
('Coronary sinus atrial septal defect','Coronary sinus atrial septal defect','Malformations congénitales et anomalies chromosomiques','Q21.13'),
('Superior sinus venosus atrial septal defect','Superior sinus venosus atrial septal defect','Malformations congénitales et anomalies chromosomiques','Q21.14'),
('Inferior sinus venosus atrial septal defect','Inferior sinus venosus atrial septal defect','Malformations congénitales et anomalies chromosomiques','Q21.15'),
('Sinus venosus atrial septal defect, non spécifié','Sinus venosus atrial septal defect, unspecified','Malformations congénitales et anomalies chromosomiques','Q21.16'),
('autre specified atrial septal defect','Other specified atrial septal defect','Malformations congénitales et anomalies chromosomiques','Q21.19'),
('Atrioventricular septal defect, non spécifié as to partial or complete','Atrioventricular septal defect, unspecified as to partial or complete','Malformations congénitales et anomalies chromosomiques','Q21.20'),
('Partial atrioventricular septal defect','Partial atrioventricular septal defect','Malformations congénitales et anomalies chromosomiques','Q21.21'),
('Transitional atrioventricular septal defect','Transitional atrioventricular septal defect','Malformations congénitales et anomalies chromosomiques','Q21.22'),
('Complete atrioventricular septal defect','Complete atrioventricular septal defect','Malformations congénitales et anomalies chromosomiques','Q21.23'),
('Tetralogy of Fallot','Tetralogy of Fallot','Malformations congénitales et anomalies chromosomiques','Q21.3'),
('Aortopulmonary septal defect','Aortopulmonary septal defect','Malformations congénitales et anomalies chromosomiques','Q21.4'),
('autre congénital malformations of cardiac septa','Other congenital malformations of cardiac septa','Malformations congénitales et anomalies chromosomiques','Q21.8'),
('congénital malformation of cardiac septum, non spécifié','Congenital malformation of cardiac septum, unspecified','Malformations congénitales et anomalies chromosomiques','Q21.9'),
('Pulmonary valve atresia','Pulmonary valve atresia','Malformations congénitales et anomalies chromosomiques','Q22.0'),
('congénital pulmonary valve sténose','Congenital pulmonary valve stenosis','Malformations congénitales et anomalies chromosomiques','Q22.1'),
('congénital pulmonary valve insufficiency','Congenital pulmonary valve insufficiency','Malformations congénitales et anomalies chromosomiques','Q22.2'),
('autre congénital malformations of pulmonary valve','Other congenital malformations of pulmonary valve','Malformations congénitales et anomalies chromosomiques','Q22.3'),
('congénital tricuspid sténose','Congenital tricuspid stenosis','Malformations congénitales et anomalies chromosomiques','Q22.4'),
('Ebstein''s anomaly','Ebstein''s anomaly','Malformations congénitales et anomalies chromosomiques','Q22.5'),
('Hypoplastic right heart syndrome','Hypoplastic right heart syndrome','Malformations congénitales et anomalies chromosomiques','Q22.6'),
('autre congénital malformations of tricuspid valve','Other congenital malformations of tricuspid valve','Malformations congénitales et anomalies chromosomiques','Q22.8'),
('congénital malformation of tricuspid valve, non spécifié','Congenital malformation of tricuspid valve, unspecified','Malformations congénitales et anomalies chromosomiques','Q22.9'),
('congénital sténose of aortic valve','Congenital stenosis of aortic valve','Malformations congénitales et anomalies chromosomiques','Q23.0'),
('congénital insufficiency of aortic valve','Congenital insufficiency of aortic valve','Malformations congénitales et anomalies chromosomiques','Q23.1'),
('congénital mitral sténose','Congenital mitral stenosis','Malformations congénitales et anomalies chromosomiques','Q23.2'),
('congénital mitral insufficiency','Congenital mitral insufficiency','Malformations congénitales et anomalies chromosomiques','Q23.3'),
('Hypoplastic left heart syndrome','Hypoplastic left heart syndrome','Malformations congénitales et anomalies chromosomiques','Q23.4'),
('Bicuspid aortic valve','Bicuspid aortic valve','Malformations congénitales et anomalies chromosomiques','Q23.81'),
('congénital mitral valve cleft leaflet','Congenital mitral valve cleft leaflet','Malformations congénitales et anomalies chromosomiques','Q23.82'),
('autre congénital malformations of aortic and mitral valves','Other congenital malformations of aortic and mitral valves','Malformations congénitales et anomalies chromosomiques','Q23.88'),
('congénital malformation of aortic and mitral valves, non spécifié','Congenital malformation of aortic and mitral valves, unspecified','Malformations congénitales et anomalies chromosomiques','Q23.9'),
('Dextrocardia','Dextrocardia','Malformations congénitales et anomalies chromosomiques','Q24.0'),
('Levocardia','Levocardia','Malformations congénitales et anomalies chromosomiques','Q24.1'),
('Cor triatriatum','Cor triatriatum','Malformations congénitales et anomalies chromosomiques','Q24.2'),
('Pulmonary infundibular sténose','Pulmonary infundibular stenosis','Malformations congénitales et anomalies chromosomiques','Q24.3'),
('congénital subaortic sténose','Congenital subaortic stenosis','Malformations congénitales et anomalies chromosomiques','Q24.4'),
('Malformation of coronary vessels','Malformation of coronary vessels','Malformations congénitales et anomalies chromosomiques','Q24.5'),
('congénital heart block','Congenital heart block','Malformations congénitales et anomalies chromosomiques','Q24.6'),
('autre specified congénital malformations of heart','Other specified congenital malformations of heart','Malformations congénitales et anomalies chromosomiques','Q24.8'),
('congénital malformation of heart, non spécifié','Congenital malformation of heart, unspecified','Malformations congénitales et anomalies chromosomiques','Q24.9'),
('Patent ductus arteriosus','Patent ductus arteriosus','Malformations congénitales et anomalies chromosomiques','Q25.0'),
('Coarctation of aorta','Coarctation of aorta','Malformations congénitales et anomalies chromosomiques','Q25.1'),
('Interruption of aortic arch','Interruption of aortic arch','Malformations congénitales et anomalies chromosomiques','Q25.21'),
('autre atresia of aorta','Other atresia of aorta','Malformations congénitales et anomalies chromosomiques','Q25.29'),
('Supravalvular aortic sténose','Supravalvular aortic stenosis','Malformations congénitales et anomalies chromosomiques','Q25.3'),
('congénital malformation of aorta non spécifié','Congenital malformation of aorta unspecified','Malformations congénitales et anomalies chromosomiques','Q25.40'),
('absence and aplasia of aorta','Absence and aplasia of aorta','Malformations congénitales et anomalies chromosomiques','Q25.41'),
('Hypoplasia of aorta','Hypoplasia of aorta','Malformations congénitales et anomalies chromosomiques','Q25.42'),
('congénital aneurysm of aorta','Congenital aneurysm of aorta','Malformations congénitales et anomalies chromosomiques','Q25.43'),
('congénital dilation of aorta','Congenital dilation of aorta','Malformations congénitales et anomalies chromosomiques','Q25.44'),
('Double aortic arch','Double aortic arch','Malformations congénitales et anomalies chromosomiques','Q25.45'),
('Tortuous aortic arch','Tortuous aortic arch','Malformations congénitales et anomalies chromosomiques','Q25.46'),
('Right aortic arch','Right aortic arch','Malformations congénitales et anomalies chromosomiques','Q25.47'),
('Anomalous origin of subclavian artery','Anomalous origin of subclavian artery','Malformations congénitales et anomalies chromosomiques','Q25.48'),
('autre congénital malformations of aorta','Other congenital malformations of aorta','Malformations congénitales et anomalies chromosomiques','Q25.49'),
('Atresia of pulmonary artery','Atresia of pulmonary artery','Malformations congénitales et anomalies chromosomiques','Q25.5'),
('sténose of pulmonary artery','Stenosis of pulmonary artery','Malformations congénitales et anomalies chromosomiques','Q25.6'),
('Coarctation of pulmonary artery','Coarctation of pulmonary artery','Malformations congénitales et anomalies chromosomiques','Q25.71'),
('congénital pulmonary arteriovenous malformation','Congenital pulmonary arteriovenous malformation','Malformations congénitales et anomalies chromosomiques','Q25.72'),
('autre congénital malformations of pulmonary artery','Other congenital malformations of pulmonary artery','Malformations congénitales et anomalies chromosomiques','Q25.79')
ON CONFLICT (nom_fr) DO NOTHING;
