-- icd10v2_batch_154.sql (80 rows)
INSERT INTO pathologies (nom_fr, nom_en, categorie, icd10_code)
VALUES
('Acquired hypertrichosis lanuginosa','Acquired hypertrichosis lanuginosa','Maladies de la peau et du tissu cellulaire sous-cutané','L68.1'),
('Localized hypertrichosis','Localized hypertrichosis','Maladies de la peau et du tissu cellulaire sous-cutané','L68.2'),
('Polytrichia','Polytrichia','Maladies de la peau et du tissu cellulaire sous-cutané','L68.3'),
('autre hypertrichosis','Other hypertrichosis','Maladies de la peau et du tissu cellulaire sous-cutané','L68.8'),
('Hypertrichosis, non spécifié','Hypertrichosis, unspecified','Maladies de la peau et du tissu cellulaire sous-cutané','L68.9'),
('Acne vulgaris','Acne vulgaris','Maladies de la peau et du tissu cellulaire sous-cutané','L70.0'),
('Acne conglobata','Acne conglobata','Maladies de la peau et du tissu cellulaire sous-cutané','L70.1'),
('Acne varioliformis','Acne varioliformis','Maladies de la peau et du tissu cellulaire sous-cutané','L70.2'),
('Acne tropica','Acne tropica','Maladies de la peau et du tissu cellulaire sous-cutané','L70.3'),
('Infantile acne','Infantile acne','Maladies de la peau et du tissu cellulaire sous-cutané','L70.4'),
('Acne excoriee','Acne excoriee','Maladies de la peau et du tissu cellulaire sous-cutané','L70.5'),
('autre acne','Other acne','Maladies de la peau et du tissu cellulaire sous-cutané','L70.8'),
('Acne, non spécifié','Acne, unspecified','Maladies de la peau et du tissu cellulaire sous-cutané','L70.9'),
('Perioral dermatitis','Perioral dermatitis','Maladies de la peau et du tissu cellulaire sous-cutané','L71.0'),
('Rhinophyma','Rhinophyma','Maladies de la peau et du tissu cellulaire sous-cutané','L71.1'),
('autre rosacea','Other rosacea','Maladies de la peau et du tissu cellulaire sous-cutané','L71.8'),
('Rosacea, non spécifié','Rosacea, unspecified','Maladies de la peau et du tissu cellulaire sous-cutané','L71.9'),
('Epidermal cyst','Epidermal cyst','Maladies de la peau et du tissu cellulaire sous-cutané','L72.0'),
('Pilar cyst','Pilar cyst','Maladies de la peau et du tissu cellulaire sous-cutané','L72.11'),
('Trichodermal cyst','Trichodermal cyst','Maladies de la peau et du tissu cellulaire sous-cutané','L72.12'),
('Steatocystoma multiplex','Steatocystoma multiplex','Maladies de la peau et du tissu cellulaire sous-cutané','L72.2'),
('Sebaceous cyst','Sebaceous cyst','Maladies de la peau et du tissu cellulaire sous-cutané','L72.3'),
('autre follicular cysts of the skin and subcutaneous tissue','Other follicular cysts of the skin and subcutaneous tissue','Maladies de la peau et du tissu cellulaire sous-cutané','L72.8'),
('Follicular cyst of the skin and subcutaneous tissue, non spécifié','Follicular cyst of the skin and subcutaneous tissue, unspecified','Maladies de la peau et du tissu cellulaire sous-cutané','L72.9'),
('Acne keloid','Acne keloid','Maladies de la peau et du tissu cellulaire sous-cutané','L73.0'),
('Pseudofolliculitis barbae','Pseudofolliculitis barbae','Maladies de la peau et du tissu cellulaire sous-cutané','L73.1'),
('Hidradenitis suppurativa','Hidradenitis suppurativa','Maladies de la peau et du tissu cellulaire sous-cutané','L73.2'),
('autre specified follicular disorders','Other specified follicular disorders','Maladies de la peau et du tissu cellulaire sous-cutané','L73.8'),
('Follicular trouble, non spécifié','Follicular disorder, unspecified','Maladies de la peau et du tissu cellulaire sous-cutané','L73.9'),
('Miliaria rubra','Miliaria rubra','Maladies de la peau et du tissu cellulaire sous-cutané','L74.0'),
('Miliaria crystallina','Miliaria crystallina','Maladies de la peau et du tissu cellulaire sous-cutané','L74.1'),
('Miliaria profunda','Miliaria profunda','Maladies de la peau et du tissu cellulaire sous-cutané','L74.2'),
('Miliaria, non spécifié','Miliaria, unspecified','Maladies de la peau et du tissu cellulaire sous-cutané','L74.3'),
('Anhidrosis','Anhidrosis','Maladies de la peau et du tissu cellulaire sous-cutané','L74.4'),
('primitif focal hyperhidrosis, axilla','Primary focal hyperhidrosis, axilla','Maladies de la peau et du tissu cellulaire sous-cutané','L74.510'),
('primitif focal hyperhidrosis, face','Primary focal hyperhidrosis, face','Maladies de la peau et du tissu cellulaire sous-cutané','L74.511'),
('primitif focal hyperhidrosis, palms','Primary focal hyperhidrosis, palms','Maladies de la peau et du tissu cellulaire sous-cutané','L74.512'),
('primitif focal hyperhidrosis, soles','Primary focal hyperhidrosis, soles','Maladies de la peau et du tissu cellulaire sous-cutané','L74.513'),
('primitif focal hyperhidrosis, non spécifié','Primary focal hyperhidrosis, unspecified','Maladies de la peau et du tissu cellulaire sous-cutané','L74.519'),
('secondaire focal hyperhidrosis','Secondary focal hyperhidrosis','Maladies de la peau et du tissu cellulaire sous-cutané','L74.52'),
('autre eccrine sweat disorders','Other eccrine sweat disorders','Maladies de la peau et du tissu cellulaire sous-cutané','L74.8'),
('Eccrine sweat trouble, non spécifié','Eccrine sweat disorder, unspecified','Maladies de la peau et du tissu cellulaire sous-cutané','L74.9'),
('Bromhidrosis','Bromhidrosis','Maladies de la peau et du tissu cellulaire sous-cutané','L75.0'),
('Chromhidrosis','Chromhidrosis','Maladies de la peau et du tissu cellulaire sous-cutané','L75.1'),
('Apocrine miliaria','Apocrine miliaria','Maladies de la peau et du tissu cellulaire sous-cutané','L75.2'),
('autre apocrine sweat disorders','Other apocrine sweat disorders','Maladies de la peau et du tissu cellulaire sous-cutané','L75.8'),
('Apocrine sweat trouble, non spécifié','Apocrine sweat disorder, unspecified','Maladies de la peau et du tissu cellulaire sous-cutané','L75.9'),
('Intraoperative hémorragie and hematoma of skin and subcutaneous tissue complicating a dermatologic procedure','Intraoperative hemorrhage and hematoma of skin and subcutaneous tissue complicating a dermatologic procedure','Maladies de la peau et du tissu cellulaire sous-cutané','L76.01'),
('Intraoperative hémorragie and hematoma of skin and subcutaneous tissue complicating autre procedure','Intraoperative hemorrhage and hematoma of skin and subcutaneous tissue complicating other procedure','Maladies de la peau et du tissu cellulaire sous-cutané','L76.02'),
('Accidental puncture and laceration of skin and subcutaneous tissue during a dermatologic procedure','Accidental puncture and laceration of skin and subcutaneous tissue during a dermatologic procedure','Maladies de la peau et du tissu cellulaire sous-cutané','L76.11'),
('Accidental puncture and laceration of skin and subcutaneous tissue during autre procedure','Accidental puncture and laceration of skin and subcutaneous tissue during other procedure','Maladies de la peau et du tissu cellulaire sous-cutané','L76.12'),
('Postprocedural hémorragie of skin and subcutaneous tissue following a dermatologic procedure','Postprocedural hemorrhage of skin and subcutaneous tissue following a dermatologic procedure','Maladies de la peau et du tissu cellulaire sous-cutané','L76.21'),
('Postprocedural hémorragie of skin and subcutaneous tissue following autre procedure','Postprocedural hemorrhage of skin and subcutaneous tissue following other procedure','Maladies de la peau et du tissu cellulaire sous-cutané','L76.22'),
('Postprocedural hematoma of skin and subcutaneous tissue following a dermatologic procedure','Postprocedural hematoma of skin and subcutaneous tissue following a dermatologic procedure','Maladies de la peau et du tissu cellulaire sous-cutané','L76.31'),
('Postprocedural hematoma of skin and subcutaneous tissue following autre procedure','Postprocedural hematoma of skin and subcutaneous tissue following other procedure','Maladies de la peau et du tissu cellulaire sous-cutané','L76.32'),
('Postprocedural seroma of skin and subcutaneous tissue following a dermatologic procedure','Postprocedural seroma of skin and subcutaneous tissue following a dermatologic procedure','Maladies de la peau et du tissu cellulaire sous-cutané','L76.33'),
('Postprocedural seroma of skin and subcutaneous tissue following autre procedure','Postprocedural seroma of skin and subcutaneous tissue following other procedure','Maladies de la peau et du tissu cellulaire sous-cutané','L76.34'),
('autre intraoperative complications of skin and subcutaneous tissue','Other intraoperative complications of skin and subcutaneous tissue','Maladies de la peau et du tissu cellulaire sous-cutané','L76.81'),
('autre postprocedural complications of skin and subcutaneous tissue','Other postprocedural complications of skin and subcutaneous tissue','Maladies de la peau et du tissu cellulaire sous-cutané','L76.82'),
('Vitiligo','Vitiligo','Maladies de la peau et du tissu cellulaire sous-cutané','L80'),
('Postinflammatory hyperpigmentation','Postinflammatory hyperpigmentation','Maladies de la peau et du tissu cellulaire sous-cutané','L81.0'),
('Chloasma','Chloasma','Maladies de la peau et du tissu cellulaire sous-cutané','L81.1'),
('Freckles','Freckles','Maladies de la peau et du tissu cellulaire sous-cutané','L81.2'),
('Cafe au lait spots','Cafe au lait spots','Maladies de la peau et du tissu cellulaire sous-cutané','L81.3'),
('autre melanin hyperpigmentation','Other melanin hyperpigmentation','Maladies de la peau et du tissu cellulaire sous-cutané','L81.4'),
('Leukoderma, not elsewhere classified','Leukoderma, not elsewhere classified','Maladies de la peau et du tissu cellulaire sous-cutané','L81.5'),
('autre disorders of diminished melanin formation','Other disorders of diminished melanin formation','Maladies de la peau et du tissu cellulaire sous-cutané','L81.6'),
('Pigmented purpuric dermatosis','Pigmented purpuric dermatosis','Maladies de la peau et du tissu cellulaire sous-cutané','L81.7'),
('autre specified disorders of pigmentation','Other specified disorders of pigmentation','Maladies de la peau et du tissu cellulaire sous-cutané','L81.8'),
('trouble of pigmentation, non spécifié','Disorder of pigmentation, unspecified','Maladies de la peau et du tissu cellulaire sous-cutané','L81.9'),
('Inflamed seborrheic keratosis','Inflamed seborrheic keratosis','Maladies de la peau et du tissu cellulaire sous-cutané','L82.0'),
('autre seborrheic keratosis','Other seborrheic keratosis','Maladies de la peau et du tissu cellulaire sous-cutané','L82.1'),
('Acanthosis nigricans','Acanthosis nigricans','Maladies de la peau et du tissu cellulaire sous-cutané','L83'),
('Corns and callosities','Corns and callosities','Maladies de la peau et du tissu cellulaire sous-cutané','L84'),
('Acquired ichthyosis','Acquired ichthyosis','Maladies de la peau et du tissu cellulaire sous-cutané','L85.0'),
('Acquired keratosis [keratoderma] palmaris et plantaris','Acquired keratosis [keratoderma] palmaris et plantaris','Maladies de la peau et du tissu cellulaire sous-cutané','L85.1'),
('Keratosis punctata (palmaris et plantaris)','Keratosis punctata (palmaris et plantaris)','Maladies de la peau et du tissu cellulaire sous-cutané','L85.2'),
('Xerosis cutis','Xerosis cutis','Maladies de la peau et du tissu cellulaire sous-cutané','L85.3'),
('autre specified epidermal thickening','Other specified epidermal thickening','Maladies de la peau et du tissu cellulaire sous-cutané','L85.8'),
('Epidermal thickening, non spécifié','Epidermal thickening, unspecified','Maladies de la peau et du tissu cellulaire sous-cutané','L85.9')
ON CONFLICT (nom_fr) DO NOTHING;
