-- icd10_batch_033.sql (80 rows)
INSERT INTO pathologies (nom_fr, nom_en, categorie, icd10_code)
VALUES
('Exposure to melting of autre clothing and apparel, initial encounter','Exposure to melting of other clothing and apparel, initial encounter','Causes externes de morbidité et de mortalité','X06.3XXA'),
('Exposure to melting of autre clothing and apparel, subsequent encounter','Exposure to melting of other clothing and apparel, subsequent encounter','Causes externes de morbidité et de mortalité','X06.3XXD'),
('Exposure to melting of autre clothing and apparel, sequela','Exposure to melting of other clothing and apparel, sequela','Causes externes de morbidité et de mortalité','X06.3XXS'),
('Exposure to bed fire due to non spécifié burning material, initial encounter','Exposure to bed fire due to unspecified burning material, initial encounter','Causes externes de morbidité et de mortalité','X08.00XA'),
('Exposure to bed fire due to non spécifié burning material, subsequent encounter','Exposure to bed fire due to unspecified burning material, subsequent encounter','Causes externes de morbidité et de mortalité','X08.00XD'),
('Exposure to bed fire due to non spécifié burning material, sequela','Exposure to bed fire due to unspecified burning material, sequela','Causes externes de morbidité et de mortalité','X08.00XS'),
('Exposure to bed fire due to burning cigarette, initial encounter','Exposure to bed fire due to burning cigarette, initial encounter','Causes externes de morbidité et de mortalité','X08.01XA'),
('Exposure to bed fire due to burning cigarette, subsequent encounter','Exposure to bed fire due to burning cigarette, subsequent encounter','Causes externes de morbidité et de mortalité','X08.01XD'),
('Exposure to bed fire due to burning cigarette, sequela','Exposure to bed fire due to burning cigarette, sequela','Causes externes de morbidité et de mortalité','X08.01XS'),
('Exposure to bed fire due to autre burning material, initial encounter','Exposure to bed fire due to other burning material, initial encounter','Causes externes de morbidité et de mortalité','X08.09XA'),
('Exposure to bed fire due to autre burning material, subsequent encounter','Exposure to bed fire due to other burning material, subsequent encounter','Causes externes de morbidité et de mortalité','X08.09XD'),
('Exposure to bed fire due to autre burning material, sequela','Exposure to bed fire due to other burning material, sequela','Causes externes de morbidité et de mortalité','X08.09XS'),
('Exposure to sofa fire due to non spécifié burning material, initial encounter','Exposure to sofa fire due to unspecified burning material, initial encounter','Causes externes de morbidité et de mortalité','X08.10XA'),
('Exposure to sofa fire due to non spécifié burning material, subsequent encounter','Exposure to sofa fire due to unspecified burning material, subsequent encounter','Causes externes de morbidité et de mortalité','X08.10XD'),
('Exposure to sofa fire due to non spécifié burning material, sequela','Exposure to sofa fire due to unspecified burning material, sequela','Causes externes de morbidité et de mortalité','X08.10XS'),
('Exposure to sofa fire due to burning cigarette, initial encounter','Exposure to sofa fire due to burning cigarette, initial encounter','Causes externes de morbidité et de mortalité','X08.11XA'),
('Exposure to sofa fire due to burning cigarette, subsequent encounter','Exposure to sofa fire due to burning cigarette, subsequent encounter','Causes externes de morbidité et de mortalité','X08.11XD'),
('Exposure to sofa fire due to burning cigarette, sequela','Exposure to sofa fire due to burning cigarette, sequela','Causes externes de morbidité et de mortalité','X08.11XS'),
('Exposure to sofa fire due to autre burning material, initial encounter','Exposure to sofa fire due to other burning material, initial encounter','Causes externes de morbidité et de mortalité','X08.19XA'),
('Exposure to sofa fire due to autre burning material, subsequent encounter','Exposure to sofa fire due to other burning material, subsequent encounter','Causes externes de morbidité et de mortalité','X08.19XD'),
('Exposure to sofa fire due to autre burning material, sequela','Exposure to sofa fire due to other burning material, sequela','Causes externes de morbidité et de mortalité','X08.19XS'),
('Exposure to autre furniture fire due to non spécifié burning material, initial encounter','Exposure to other furniture fire due to unspecified burning material, initial encounter','Causes externes de morbidité et de mortalité','X08.20XA'),
('Exposure to autre furniture fire due to non spécifié burning material, subsequent encounter','Exposure to other furniture fire due to unspecified burning material, subsequent encounter','Causes externes de morbidité et de mortalité','X08.20XD'),
('Exposure to autre furniture fire due to non spécifié burning material, sequela','Exposure to other furniture fire due to unspecified burning material, sequela','Causes externes de morbidité et de mortalité','X08.20XS'),
('Exposure to autre furniture fire due to burning cigarette, initial encounter','Exposure to other furniture fire due to burning cigarette, initial encounter','Causes externes de morbidité et de mortalité','X08.21XA'),
('Exposure to autre furniture fire due to burning cigarette, subsequent encounter','Exposure to other furniture fire due to burning cigarette, subsequent encounter','Causes externes de morbidité et de mortalité','X08.21XD'),
('Exposure to autre furniture fire due to burning cigarette, sequela','Exposure to other furniture fire due to burning cigarette, sequela','Causes externes de morbidité et de mortalité','X08.21XS'),
('Exposure to autre furniture fire due to autre burning material, initial encounter','Exposure to other furniture fire due to other burning material, initial encounter','Causes externes de morbidité et de mortalité','X08.29XA'),
('Exposure to autre furniture fire due to autre burning material, subsequent encounter','Exposure to other furniture fire due to other burning material, subsequent encounter','Causes externes de morbidité et de mortalité','X08.29XD'),
('Exposure to autre furniture fire due to autre burning material, sequela','Exposure to other furniture fire due to other burning material, sequela','Causes externes de morbidité et de mortalité','X08.29XS'),
('Exposure to autre specified smoke, fire and flames, initial encounter','Exposure to other specified smoke, fire and flames, initial encounter','Causes externes de morbidité et de mortalité','X08.8XXA'),
('Exposure to autre specified smoke, fire and flames, subsequent encounter','Exposure to other specified smoke, fire and flames, subsequent encounter','Causes externes de morbidité et de mortalité','X08.8XXD'),
('Exposure to autre specified smoke, fire and flames, sequela','Exposure to other specified smoke, fire and flames, sequela','Causes externes de morbidité et de mortalité','X08.8XXS'),
('Contact with hot drinks, initial encounter','Contact with hot drinks, initial encounter','Causes externes de morbidité et de mortalité','X10.0XXA'),
('Contact with hot drinks, subsequent encounter','Contact with hot drinks, subsequent encounter','Causes externes de morbidité et de mortalité','X10.0XXD'),
('Contact with hot drinks, sequela','Contact with hot drinks, sequela','Causes externes de morbidité et de mortalité','X10.0XXS'),
('Contact with hot food, initial encounter','Contact with hot food, initial encounter','Causes externes de morbidité et de mortalité','X10.1XXA'),
('Contact with hot food, subsequent encounter','Contact with hot food, subsequent encounter','Causes externes de morbidité et de mortalité','X10.1XXD'),
('Contact with hot food, sequela','Contact with hot food, sequela','Causes externes de morbidité et de mortalité','X10.1XXS'),
('Contact with fats and cooking oils, initial encounter','Contact with fats and cooking oils, initial encounter','Causes externes de morbidité et de mortalité','X10.2XXA'),
('Contact with fats and cooking oils, subsequent encounter','Contact with fats and cooking oils, subsequent encounter','Causes externes de morbidité et de mortalité','X10.2XXD'),
('Contact with fats and cooking oils, sequela','Contact with fats and cooking oils, sequela','Causes externes de morbidité et de mortalité','X10.2XXS'),
('Contact with hot water in bath or tub, initial encounter','Contact with hot water in bath or tub, initial encounter','Causes externes de morbidité et de mortalité','X11.0XXA'),
('Contact with hot water in bath or tub, subsequent encounter','Contact with hot water in bath or tub, subsequent encounter','Causes externes de morbidité et de mortalité','X11.0XXD'),
('Contact with hot water in bath or tub, sequela','Contact with hot water in bath or tub, sequela','Causes externes de morbidité et de mortalité','X11.0XXS'),
('Contact with running hot water, initial encounter','Contact with running hot water, initial encounter','Causes externes de morbidité et de mortalité','X11.1XXA'),
('Contact with running hot water, subsequent encounter','Contact with running hot water, subsequent encounter','Causes externes de morbidité et de mortalité','X11.1XXD'),
('Contact with running hot water, sequela','Contact with running hot water, sequela','Causes externes de morbidité et de mortalité','X11.1XXS'),
('Contact with autre hot tap-water, initial encounter','Contact with other hot tap-water, initial encounter','Causes externes de morbidité et de mortalité','X11.8XXA'),
('Contact with autre hot tap-water, subsequent encounter','Contact with other hot tap-water, subsequent encounter','Causes externes de morbidité et de mortalité','X11.8XXD'),
('Contact with autre hot tap-water, sequela','Contact with other hot tap-water, sequela','Causes externes de morbidité et de mortalité','X11.8XXS'),
('Contact with autre hot fluids, initial encounter','Contact with other hot fluids, initial encounter','Causes externes de morbidité et de mortalité','X12.XXXA'),
('Contact with autre hot fluids, subsequent encounter','Contact with other hot fluids, subsequent encounter','Causes externes de morbidité et de mortalité','X12.XXXD'),
('Contact with autre hot fluids, sequela','Contact with other hot fluids, sequela','Causes externes de morbidité et de mortalité','X12.XXXS'),
('Inhalation of steam and autre hot vapors, initial encounter','Inhalation of steam and other hot vapors, initial encounter','Causes externes de morbidité et de mortalité','X13.0XXA'),
('Inhalation of steam and autre hot vapors, subsequent encounter','Inhalation of steam and other hot vapors, subsequent encounter','Causes externes de morbidité et de mortalité','X13.0XXD'),
('Inhalation of steam and autre hot vapors, sequela','Inhalation of steam and other hot vapors, sequela','Causes externes de morbidité et de mortalité','X13.0XXS'),
('autre contact with steam and autre hot vapors, initial encounter','Other contact with steam and other hot vapors, initial encounter','Causes externes de morbidité et de mortalité','X13.1XXA'),
('autre contact with steam and autre hot vapors, subsequent encounter','Other contact with steam and other hot vapors, subsequent encounter','Causes externes de morbidité et de mortalité','X13.1XXD'),
('autre contact with steam and autre hot vapors, sequela','Other contact with steam and other hot vapors, sequela','Causes externes de morbidité et de mortalité','X13.1XXS'),
('Inhalation of hot air and gases, initial encounter','Inhalation of hot air and gases, initial encounter','Causes externes de morbidité et de mortalité','X14.0XXA'),
('Inhalation of hot air and gases, subsequent encounter','Inhalation of hot air and gases, subsequent encounter','Causes externes de morbidité et de mortalité','X14.0XXD'),
('Inhalation of hot air and gases, sequela','Inhalation of hot air and gases, sequela','Causes externes de morbidité et de mortalité','X14.0XXS'),
('autre contact with hot air and autre hot gases, initial encounter','Other contact with hot air and other hot gases, initial encounter','Causes externes de morbidité et de mortalité','X14.1XXA'),
('autre contact with hot air and autre hot gases, subsequent encounter','Other contact with hot air and other hot gases, subsequent encounter','Causes externes de morbidité et de mortalité','X14.1XXD'),
('autre contact with hot air and autre hot gases, sequela','Other contact with hot air and other hot gases, sequela','Causes externes de morbidité et de mortalité','X14.1XXS'),
('Contact with hot stove (kitchen), initial encounter','Contact with hot stove (kitchen), initial encounter','Causes externes de morbidité et de mortalité','X15.0XXA'),
('Contact with hot stove (kitchen), subsequent encounter','Contact with hot stove (kitchen), subsequent encounter','Causes externes de morbidité et de mortalité','X15.0XXD'),
('Contact with hot stove (kitchen), sequela','Contact with hot stove (kitchen), sequela','Causes externes de morbidité et de mortalité','X15.0XXS'),
('Contact with hot toaster, initial encounter','Contact with hot toaster, initial encounter','Causes externes de morbidité et de mortalité','X15.1XXA'),
('Contact with hot toaster, subsequent encounter','Contact with hot toaster, subsequent encounter','Causes externes de morbidité et de mortalité','X15.1XXD'),
('Contact with hot toaster, sequela','Contact with hot toaster, sequela','Causes externes de morbidité et de mortalité','X15.1XXS'),
('Contact with hotplate, initial encounter','Contact with hotplate, initial encounter','Causes externes de morbidité et de mortalité','X15.2XXA'),
('Contact with hotplate, subsequent encounter','Contact with hotplate, subsequent encounter','Causes externes de morbidité et de mortalité','X15.2XXD'),
('Contact with hotplate, sequela','Contact with hotplate, sequela','Causes externes de morbidité et de mortalité','X15.2XXS'),
('Contact with hot saucepan or skillet, initial encounter','Contact with hot saucepan or skillet, initial encounter','Causes externes de morbidité et de mortalité','X15.3XXA'),
('Contact with hot saucepan or skillet, subsequent encounter','Contact with hot saucepan or skillet, subsequent encounter','Causes externes de morbidité et de mortalité','X15.3XXD'),
('Contact with hot saucepan or skillet, sequela','Contact with hot saucepan or skillet, sequela','Causes externes de morbidité et de mortalité','X15.3XXS'),
('Contact with autre hot household appliances, initial encounter','Contact with other hot household appliances, initial encounter','Causes externes de morbidité et de mortalité','X15.8XXA'),
('Contact with autre hot household appliances, subsequent encounter','Contact with other hot household appliances, subsequent encounter','Causes externes de morbidité et de mortalité','X15.8XXD')
ON CONFLICT (nom_fr) DO NOTHING;
