-- icd10v2_batch_235.sql (80 rows)
INSERT INTO pathologies (nom_fr, nom_en, categorie, icd10_code)
VALUES
('Oligohydramnios, third trimester, fetus 5','Oligohydramnios, third trimester, fetus 5','Grossesse, accouchement et puerpéralité','O41.03X5'),
('Oligohydramnios, third trimester, autre fetus','Oligohydramnios, third trimester, other fetus','Grossesse, accouchement et puerpéralité','O41.03X9'),
('infection of amniotic sac and membranes, non spécifié, first trimester, not applicable or non spécifié','Infection of amniotic sac and membranes, unspecified, first trimester, not applicable or unspecified','Grossesse, accouchement et puerpéralité','O41.1010'),
('infection of amniotic sac and membranes, non spécifié, first trimester, fetus 1','Infection of amniotic sac and membranes, unspecified, first trimester, fetus 1','Grossesse, accouchement et puerpéralité','O41.1011'),
('infection of amniotic sac and membranes, non spécifié, first trimester, fetus 2','Infection of amniotic sac and membranes, unspecified, first trimester, fetus 2','Grossesse, accouchement et puerpéralité','O41.1012'),
('infection of amniotic sac and membranes, non spécifié, first trimester, fetus 3','Infection of amniotic sac and membranes, unspecified, first trimester, fetus 3','Grossesse, accouchement et puerpéralité','O41.1013'),
('infection of amniotic sac and membranes, non spécifié, first trimester, fetus 4','Infection of amniotic sac and membranes, unspecified, first trimester, fetus 4','Grossesse, accouchement et puerpéralité','O41.1014'),
('infection of amniotic sac and membranes, non spécifié, first trimester, fetus 5','Infection of amniotic sac and membranes, unspecified, first trimester, fetus 5','Grossesse, accouchement et puerpéralité','O41.1015'),
('infection of amniotic sac and membranes, non spécifié, first trimester, autre fetus','Infection of amniotic sac and membranes, unspecified, first trimester, other fetus','Grossesse, accouchement et puerpéralité','O41.1019'),
('infection of amniotic sac and membranes, non spécifié, second trimester, not applicable or non spécifié','Infection of amniotic sac and membranes, unspecified, second trimester, not applicable or unspecified','Grossesse, accouchement et puerpéralité','O41.1020'),
('infection of amniotic sac and membranes, non spécifié, second trimester, fetus 1','Infection of amniotic sac and membranes, unspecified, second trimester, fetus 1','Grossesse, accouchement et puerpéralité','O41.1021'),
('infection of amniotic sac and membranes, non spécifié, second trimester, fetus 2','Infection of amniotic sac and membranes, unspecified, second trimester, fetus 2','Grossesse, accouchement et puerpéralité','O41.1022'),
('infection of amniotic sac and membranes, non spécifié, second trimester, fetus 3','Infection of amniotic sac and membranes, unspecified, second trimester, fetus 3','Grossesse, accouchement et puerpéralité','O41.1023'),
('infection of amniotic sac and membranes, non spécifié, second trimester, fetus 4','Infection of amniotic sac and membranes, unspecified, second trimester, fetus 4','Grossesse, accouchement et puerpéralité','O41.1024'),
('infection of amniotic sac and membranes, non spécifié, second trimester, fetus 5','Infection of amniotic sac and membranes, unspecified, second trimester, fetus 5','Grossesse, accouchement et puerpéralité','O41.1025'),
('infection of amniotic sac and membranes, non spécifié, second trimester, autre fetus','Infection of amniotic sac and membranes, unspecified, second trimester, other fetus','Grossesse, accouchement et puerpéralité','O41.1029'),
('infection of amniotic sac and membranes, non spécifié, third trimester, not applicable or non spécifié','Infection of amniotic sac and membranes, unspecified, third trimester, not applicable or unspecified','Grossesse, accouchement et puerpéralité','O41.1030'),
('infection of amniotic sac and membranes, non spécifié, third trimester, fetus 1','Infection of amniotic sac and membranes, unspecified, third trimester, fetus 1','Grossesse, accouchement et puerpéralité','O41.1031'),
('infection of amniotic sac and membranes, non spécifié, third trimester, fetus 2','Infection of amniotic sac and membranes, unspecified, third trimester, fetus 2','Grossesse, accouchement et puerpéralité','O41.1032'),
('infection of amniotic sac and membranes, non spécifié, third trimester, fetus 3','Infection of amniotic sac and membranes, unspecified, third trimester, fetus 3','Grossesse, accouchement et puerpéralité','O41.1033'),
('infection of amniotic sac and membranes, non spécifié, third trimester, fetus 4','Infection of amniotic sac and membranes, unspecified, third trimester, fetus 4','Grossesse, accouchement et puerpéralité','O41.1034'),
('infection of amniotic sac and membranes, non spécifié, third trimester, fetus 5','Infection of amniotic sac and membranes, unspecified, third trimester, fetus 5','Grossesse, accouchement et puerpéralité','O41.1035'),
('infection of amniotic sac and membranes, non spécifié, third trimester, autre fetus','Infection of amniotic sac and membranes, unspecified, third trimester, other fetus','Grossesse, accouchement et puerpéralité','O41.1039'),
('infection of amniotic sac and membranes, non spécifié, non spécifié trimester, not applicable or non spécifié','Infection of amniotic sac and membranes, unspecified, unspecified trimester, not applicable or unspecified','Grossesse, accouchement et puerpéralité','O41.1090'),
('infection of amniotic sac and membranes, non spécifié, non spécifié trimester, fetus 1','Infection of amniotic sac and membranes, unspecified, unspecified trimester, fetus 1','Grossesse, accouchement et puerpéralité','O41.1091'),
('infection of amniotic sac and membranes, non spécifié, non spécifié trimester, fetus 2','Infection of amniotic sac and membranes, unspecified, unspecified trimester, fetus 2','Grossesse, accouchement et puerpéralité','O41.1092'),
('infection of amniotic sac and membranes, non spécifié, non spécifié trimester, fetus 3','Infection of amniotic sac and membranes, unspecified, unspecified trimester, fetus 3','Grossesse, accouchement et puerpéralité','O41.1093'),
('infection of amniotic sac and membranes, non spécifié, non spécifié trimester, fetus 4','Infection of amniotic sac and membranes, unspecified, unspecified trimester, fetus 4','Grossesse, accouchement et puerpéralité','O41.1094'),
('infection of amniotic sac and membranes, non spécifié, non spécifié trimester, fetus 5','Infection of amniotic sac and membranes, unspecified, unspecified trimester, fetus 5','Grossesse, accouchement et puerpéralité','O41.1095'),
('infection of amniotic sac and membranes, non spécifié, non spécifié trimester, autre fetus','Infection of amniotic sac and membranes, unspecified, unspecified trimester, other fetus','Grossesse, accouchement et puerpéralité','O41.1099'),
('Chorioamnionitis, first trimester, not applicable or non spécifié','Chorioamnionitis, first trimester, not applicable or unspecified','Grossesse, accouchement et puerpéralité','O41.1210'),
('Chorioamnionitis, first trimester, fetus 1','Chorioamnionitis, first trimester, fetus 1','Grossesse, accouchement et puerpéralité','O41.1211'),
('Chorioamnionitis, first trimester, fetus 2','Chorioamnionitis, first trimester, fetus 2','Grossesse, accouchement et puerpéralité','O41.1212'),
('Chorioamnionitis, first trimester, fetus 3','Chorioamnionitis, first trimester, fetus 3','Grossesse, accouchement et puerpéralité','O41.1213'),
('Chorioamnionitis, first trimester, fetus 4','Chorioamnionitis, first trimester, fetus 4','Grossesse, accouchement et puerpéralité','O41.1214'),
('Chorioamnionitis, first trimester, fetus 5','Chorioamnionitis, first trimester, fetus 5','Grossesse, accouchement et puerpéralité','O41.1215'),
('Chorioamnionitis, first trimester, autre fetus','Chorioamnionitis, first trimester, other fetus','Grossesse, accouchement et puerpéralité','O41.1219'),
('Chorioamnionitis, second trimester, not applicable or non spécifié','Chorioamnionitis, second trimester, not applicable or unspecified','Grossesse, accouchement et puerpéralité','O41.1220'),
('Chorioamnionitis, second trimester, fetus 1','Chorioamnionitis, second trimester, fetus 1','Grossesse, accouchement et puerpéralité','O41.1221'),
('Chorioamnionitis, second trimester, fetus 2','Chorioamnionitis, second trimester, fetus 2','Grossesse, accouchement et puerpéralité','O41.1222'),
('Chorioamnionitis, second trimester, fetus 3','Chorioamnionitis, second trimester, fetus 3','Grossesse, accouchement et puerpéralité','O41.1223'),
('Chorioamnionitis, second trimester, fetus 4','Chorioamnionitis, second trimester, fetus 4','Grossesse, accouchement et puerpéralité','O41.1224'),
('Chorioamnionitis, second trimester, fetus 5','Chorioamnionitis, second trimester, fetus 5','Grossesse, accouchement et puerpéralité','O41.1225'),
('Chorioamnionitis, second trimester, autre fetus','Chorioamnionitis, second trimester, other fetus','Grossesse, accouchement et puerpéralité','O41.1229'),
('Chorioamnionitis, third trimester, not applicable or non spécifié','Chorioamnionitis, third trimester, not applicable or unspecified','Grossesse, accouchement et puerpéralité','O41.1230'),
('Chorioamnionitis, third trimester, fetus 1','Chorioamnionitis, third trimester, fetus 1','Grossesse, accouchement et puerpéralité','O41.1231'),
('Chorioamnionitis, third trimester, fetus 2','Chorioamnionitis, third trimester, fetus 2','Grossesse, accouchement et puerpéralité','O41.1232'),
('Chorioamnionitis, third trimester, fetus 3','Chorioamnionitis, third trimester, fetus 3','Grossesse, accouchement et puerpéralité','O41.1233'),
('Chorioamnionitis, third trimester, fetus 4','Chorioamnionitis, third trimester, fetus 4','Grossesse, accouchement et puerpéralité','O41.1234'),
('Chorioamnionitis, third trimester, fetus 5','Chorioamnionitis, third trimester, fetus 5','Grossesse, accouchement et puerpéralité','O41.1235'),
('Chorioamnionitis, third trimester, autre fetus','Chorioamnionitis, third trimester, other fetus','Grossesse, accouchement et puerpéralité','O41.1239'),
('Chorioamnionitis, non spécifié trimester, not applicable or non spécifié','Chorioamnionitis, unspecified trimester, not applicable or unspecified','Grossesse, accouchement et puerpéralité','O41.1290'),
('Chorioamnionitis, non spécifié trimester, fetus 1','Chorioamnionitis, unspecified trimester, fetus 1','Grossesse, accouchement et puerpéralité','O41.1291'),
('Chorioamnionitis, non spécifié trimester, fetus 2','Chorioamnionitis, unspecified trimester, fetus 2','Grossesse, accouchement et puerpéralité','O41.1292'),
('Chorioamnionitis, non spécifié trimester, fetus 3','Chorioamnionitis, unspecified trimester, fetus 3','Grossesse, accouchement et puerpéralité','O41.1293'),
('Chorioamnionitis, non spécifié trimester, fetus 4','Chorioamnionitis, unspecified trimester, fetus 4','Grossesse, accouchement et puerpéralité','O41.1294'),
('Chorioamnionitis, non spécifié trimester, fetus 5','Chorioamnionitis, unspecified trimester, fetus 5','Grossesse, accouchement et puerpéralité','O41.1295'),
('Chorioamnionitis, non spécifié trimester, autre fetus','Chorioamnionitis, unspecified trimester, other fetus','Grossesse, accouchement et puerpéralité','O41.1299'),
('Placentitis, first trimester, not applicable or non spécifié','Placentitis, first trimester, not applicable or unspecified','Grossesse, accouchement et puerpéralité','O41.1410'),
('Placentitis, first trimester, fetus 1','Placentitis, first trimester, fetus 1','Grossesse, accouchement et puerpéralité','O41.1411'),
('Placentitis, first trimester, fetus 2','Placentitis, first trimester, fetus 2','Grossesse, accouchement et puerpéralité','O41.1412'),
('Placentitis, first trimester, fetus 3','Placentitis, first trimester, fetus 3','Grossesse, accouchement et puerpéralité','O41.1413'),
('Placentitis, first trimester, fetus 4','Placentitis, first trimester, fetus 4','Grossesse, accouchement et puerpéralité','O41.1414'),
('Placentitis, first trimester, fetus 5','Placentitis, first trimester, fetus 5','Grossesse, accouchement et puerpéralité','O41.1415'),
('Placentitis, first trimester, autre fetus','Placentitis, first trimester, other fetus','Grossesse, accouchement et puerpéralité','O41.1419'),
('Placentitis, second trimester, not applicable or non spécifié','Placentitis, second trimester, not applicable or unspecified','Grossesse, accouchement et puerpéralité','O41.1420'),
('Placentitis, second trimester, fetus 1','Placentitis, second trimester, fetus 1','Grossesse, accouchement et puerpéralité','O41.1421'),
('Placentitis, second trimester, fetus 2','Placentitis, second trimester, fetus 2','Grossesse, accouchement et puerpéralité','O41.1422'),
('Placentitis, second trimester, fetus 3','Placentitis, second trimester, fetus 3','Grossesse, accouchement et puerpéralité','O41.1423'),
('Placentitis, second trimester, fetus 4','Placentitis, second trimester, fetus 4','Grossesse, accouchement et puerpéralité','O41.1424'),
('Placentitis, second trimester, fetus 5','Placentitis, second trimester, fetus 5','Grossesse, accouchement et puerpéralité','O41.1425'),
('Placentitis, second trimester, autre fetus','Placentitis, second trimester, other fetus','Grossesse, accouchement et puerpéralité','O41.1429'),
('Placentitis, third trimester, not applicable or non spécifié','Placentitis, third trimester, not applicable or unspecified','Grossesse, accouchement et puerpéralité','O41.1430'),
('Placentitis, third trimester, fetus 1','Placentitis, third trimester, fetus 1','Grossesse, accouchement et puerpéralité','O41.1431'),
('Placentitis, third trimester, fetus 2','Placentitis, third trimester, fetus 2','Grossesse, accouchement et puerpéralité','O41.1432'),
('Placentitis, third trimester, fetus 3','Placentitis, third trimester, fetus 3','Grossesse, accouchement et puerpéralité','O41.1433'),
('Placentitis, third trimester, fetus 4','Placentitis, third trimester, fetus 4','Grossesse, accouchement et puerpéralité','O41.1434'),
('Placentitis, third trimester, fetus 5','Placentitis, third trimester, fetus 5','Grossesse, accouchement et puerpéralité','O41.1435'),
('Placentitis, third trimester, autre fetus','Placentitis, third trimester, other fetus','Grossesse, accouchement et puerpéralité','O41.1439'),
('Placentitis, non spécifié trimester, not applicable or non spécifié','Placentitis, unspecified trimester, not applicable or unspecified','Grossesse, accouchement et puerpéralité','O41.1490')
ON CONFLICT (nom_fr) DO NOTHING;
