-- icd10v2_batch_527.sql (80 rows)
INSERT INTO pathologies (nom_fr, nom_en, categorie, icd10_code)
VALUES
('Major laceration of abdominal aorta, subsequent encounter','Major laceration of abdominal aorta, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S35.02XD'),
('Major laceration of abdominal aorta, sequela','Major laceration of abdominal aorta, sequela','Traumatismes, empoisonnements et autres causes externes','S35.02XS'),
('autre injury of abdominal aorta, initial encounter','Other injury of abdominal aorta, initial encounter','Traumatismes, empoisonnements et autres causes externes','S35.09XA'),
('autre injury of abdominal aorta, subsequent encounter','Other injury of abdominal aorta, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S35.09XD'),
('autre injury of abdominal aorta, sequela','Other injury of abdominal aorta, sequela','Traumatismes, empoisonnements et autres causes externes','S35.09XS'),
('non spécifié injury of inferior vena cava, initial encounter','Unspecified injury of inferior vena cava, initial encounter','Traumatismes, empoisonnements et autres causes externes','S35.10XA'),
('non spécifié injury of inferior vena cava, subsequent encounter','Unspecified injury of inferior vena cava, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S35.10XD'),
('non spécifié injury of inferior vena cava, sequela','Unspecified injury of inferior vena cava, sequela','Traumatismes, empoisonnements et autres causes externes','S35.10XS'),
('Minor laceration of inferior vena cava, initial encounter','Minor laceration of inferior vena cava, initial encounter','Traumatismes, empoisonnements et autres causes externes','S35.11XA'),
('Minor laceration of inferior vena cava, subsequent encounter','Minor laceration of inferior vena cava, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S35.11XD'),
('Minor laceration of inferior vena cava, sequela','Minor laceration of inferior vena cava, sequela','Traumatismes, empoisonnements et autres causes externes','S35.11XS'),
('Major laceration of inferior vena cava, initial encounter','Major laceration of inferior vena cava, initial encounter','Traumatismes, empoisonnements et autres causes externes','S35.12XA'),
('Major laceration of inferior vena cava, subsequent encounter','Major laceration of inferior vena cava, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S35.12XD'),
('Major laceration of inferior vena cava, sequela','Major laceration of inferior vena cava, sequela','Traumatismes, empoisonnements et autres causes externes','S35.12XS'),
('autre injury of inferior vena cava, initial encounter','Other injury of inferior vena cava, initial encounter','Traumatismes, empoisonnements et autres causes externes','S35.19XA'),
('autre injury of inferior vena cava, subsequent encounter','Other injury of inferior vena cava, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S35.19XD'),
('autre injury of inferior vena cava, sequela','Other injury of inferior vena cava, sequela','Traumatismes, empoisonnements et autres causes externes','S35.19XS'),
('Minor laceration of celiac artery, initial encounter','Minor laceration of celiac artery, initial encounter','Traumatismes, empoisonnements et autres causes externes','S35.211A'),
('Minor laceration of celiac artery, subsequent encounter','Minor laceration of celiac artery, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S35.211D'),
('Minor laceration of celiac artery, sequela','Minor laceration of celiac artery, sequela','Traumatismes, empoisonnements et autres causes externes','S35.211S'),
('Major laceration of celiac artery, initial encounter','Major laceration of celiac artery, initial encounter','Traumatismes, empoisonnements et autres causes externes','S35.212A'),
('Major laceration of celiac artery, subsequent encounter','Major laceration of celiac artery, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S35.212D'),
('Major laceration of celiac artery, sequela','Major laceration of celiac artery, sequela','Traumatismes, empoisonnements et autres causes externes','S35.212S'),
('autre injury of celiac artery, initial encounter','Other injury of celiac artery, initial encounter','Traumatismes, empoisonnements et autres causes externes','S35.218A'),
('autre injury of celiac artery, subsequent encounter','Other injury of celiac artery, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S35.218D'),
('autre injury of celiac artery, sequela','Other injury of celiac artery, sequela','Traumatismes, empoisonnements et autres causes externes','S35.218S'),
('non spécifié injury of celiac artery, initial encounter','Unspecified injury of celiac artery, initial encounter','Traumatismes, empoisonnements et autres causes externes','S35.219A'),
('non spécifié injury of celiac artery, subsequent encounter','Unspecified injury of celiac artery, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S35.219D'),
('non spécifié injury of celiac artery, sequela','Unspecified injury of celiac artery, sequela','Traumatismes, empoisonnements et autres causes externes','S35.219S'),
('Minor laceration of superior mesenteric artery, initial encounter','Minor laceration of superior mesenteric artery, initial encounter','Traumatismes, empoisonnements et autres causes externes','S35.221A'),
('Minor laceration of superior mesenteric artery, subsequent encounter','Minor laceration of superior mesenteric artery, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S35.221D'),
('Minor laceration of superior mesenteric artery, sequela','Minor laceration of superior mesenteric artery, sequela','Traumatismes, empoisonnements et autres causes externes','S35.221S'),
('Major laceration of superior mesenteric artery, initial encounter','Major laceration of superior mesenteric artery, initial encounter','Traumatismes, empoisonnements et autres causes externes','S35.222A'),
('Major laceration of superior mesenteric artery, subsequent encounter','Major laceration of superior mesenteric artery, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S35.222D'),
('Major laceration of superior mesenteric artery, sequela','Major laceration of superior mesenteric artery, sequela','Traumatismes, empoisonnements et autres causes externes','S35.222S'),
('autre injury of superior mesenteric artery, initial encounter','Other injury of superior mesenteric artery, initial encounter','Traumatismes, empoisonnements et autres causes externes','S35.228A'),
('autre injury of superior mesenteric artery, subsequent encounter','Other injury of superior mesenteric artery, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S35.228D'),
('autre injury of superior mesenteric artery, sequela','Other injury of superior mesenteric artery, sequela','Traumatismes, empoisonnements et autres causes externes','S35.228S'),
('non spécifié injury of superior mesenteric artery, initial encounter','Unspecified injury of superior mesenteric artery, initial encounter','Traumatismes, empoisonnements et autres causes externes','S35.229A'),
('non spécifié injury of superior mesenteric artery, subsequent encounter','Unspecified injury of superior mesenteric artery, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S35.229D'),
('non spécifié injury of superior mesenteric artery, sequela','Unspecified injury of superior mesenteric artery, sequela','Traumatismes, empoisonnements et autres causes externes','S35.229S'),
('Minor laceration of inferior mesenteric artery, initial encounter','Minor laceration of inferior mesenteric artery, initial encounter','Traumatismes, empoisonnements et autres causes externes','S35.231A'),
('Minor laceration of inferior mesenteric artery, subsequent encounter','Minor laceration of inferior mesenteric artery, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S35.231D'),
('Minor laceration of inferior mesenteric artery, sequela','Minor laceration of inferior mesenteric artery, sequela','Traumatismes, empoisonnements et autres causes externes','S35.231S'),
('Major laceration of inferior mesenteric artery, initial encounter','Major laceration of inferior mesenteric artery, initial encounter','Traumatismes, empoisonnements et autres causes externes','S35.232A'),
('Major laceration of inferior mesenteric artery, subsequent encounter','Major laceration of inferior mesenteric artery, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S35.232D'),
('Major laceration of inferior mesenteric artery, sequela','Major laceration of inferior mesenteric artery, sequela','Traumatismes, empoisonnements et autres causes externes','S35.232S'),
('autre injury of inferior mesenteric artery, initial encounter','Other injury of inferior mesenteric artery, initial encounter','Traumatismes, empoisonnements et autres causes externes','S35.238A'),
('autre injury of inferior mesenteric artery, subsequent encounter','Other injury of inferior mesenteric artery, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S35.238D'),
('autre injury of inferior mesenteric artery, sequela','Other injury of inferior mesenteric artery, sequela','Traumatismes, empoisonnements et autres causes externes','S35.238S'),
('non spécifié injury of inferior mesenteric artery, initial encounter','Unspecified injury of inferior mesenteric artery, initial encounter','Traumatismes, empoisonnements et autres causes externes','S35.239A'),
('non spécifié injury of inferior mesenteric artery, subsequent encounter','Unspecified injury of inferior mesenteric artery, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S35.239D'),
('non spécifié injury of inferior mesenteric artery, sequela','Unspecified injury of inferior mesenteric artery, sequela','Traumatismes, empoisonnements et autres causes externes','S35.239S'),
('Minor laceration of branches of celiac and mesenteric artery, initial encounter','Minor laceration of branches of celiac and mesenteric artery, initial encounter','Traumatismes, empoisonnements et autres causes externes','S35.291A'),
('Minor laceration of branches of celiac and mesenteric artery, subsequent encounter','Minor laceration of branches of celiac and mesenteric artery, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S35.291D'),
('Minor laceration of branches of celiac and mesenteric artery, sequela','Minor laceration of branches of celiac and mesenteric artery, sequela','Traumatismes, empoisonnements et autres causes externes','S35.291S'),
('Major laceration of branches of celiac and mesenteric artery, initial encounter','Major laceration of branches of celiac and mesenteric artery, initial encounter','Traumatismes, empoisonnements et autres causes externes','S35.292A'),
('Major laceration of branches of celiac and mesenteric artery, subsequent encounter','Major laceration of branches of celiac and mesenteric artery, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S35.292D'),
('Major laceration of branches of celiac and mesenteric artery, sequela','Major laceration of branches of celiac and mesenteric artery, sequela','Traumatismes, empoisonnements et autres causes externes','S35.292S'),
('autre injury of branches of celiac and mesenteric artery, initial encounter','Other injury of branches of celiac and mesenteric artery, initial encounter','Traumatismes, empoisonnements et autres causes externes','S35.298A'),
('autre injury of branches of celiac and mesenteric artery, subsequent encounter','Other injury of branches of celiac and mesenteric artery, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S35.298D'),
('autre injury of branches of celiac and mesenteric artery, sequela','Other injury of branches of celiac and mesenteric artery, sequela','Traumatismes, empoisonnements et autres causes externes','S35.298S'),
('non spécifié injury of branches of celiac and mesenteric artery, initial encounter','Unspecified injury of branches of celiac and mesenteric artery, initial encounter','Traumatismes, empoisonnements et autres causes externes','S35.299A'),
('non spécifié injury of branches of celiac and mesenteric artery, subsequent encounter','Unspecified injury of branches of celiac and mesenteric artery, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S35.299D'),
('non spécifié injury of branches of celiac and mesenteric artery, sequela','Unspecified injury of branches of celiac and mesenteric artery, sequela','Traumatismes, empoisonnements et autres causes externes','S35.299S'),
('Laceration of portal vein, initial encounter','Laceration of portal vein, initial encounter','Traumatismes, empoisonnements et autres causes externes','S35.311A'),
('Laceration of portal vein, subsequent encounter','Laceration of portal vein, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S35.311D'),
('Laceration of portal vein, sequela','Laceration of portal vein, sequela','Traumatismes, empoisonnements et autres causes externes','S35.311S'),
('autre specified injury of portal vein, initial encounter','Other specified injury of portal vein, initial encounter','Traumatismes, empoisonnements et autres causes externes','S35.318A'),
('autre specified injury of portal vein, subsequent encounter','Other specified injury of portal vein, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S35.318D'),
('autre specified injury of portal vein, sequela','Other specified injury of portal vein, sequela','Traumatismes, empoisonnements et autres causes externes','S35.318S'),
('non spécifié injury of portal vein, initial encounter','Unspecified injury of portal vein, initial encounter','Traumatismes, empoisonnements et autres causes externes','S35.319A'),
('non spécifié injury of portal vein, subsequent encounter','Unspecified injury of portal vein, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S35.319D'),
('non spécifié injury of portal vein, sequela','Unspecified injury of portal vein, sequela','Traumatismes, empoisonnements et autres causes externes','S35.319S'),
('Laceration of splenic vein, initial encounter','Laceration of splenic vein, initial encounter','Traumatismes, empoisonnements et autres causes externes','S35.321A'),
('Laceration of splenic vein, subsequent encounter','Laceration of splenic vein, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S35.321D'),
('Laceration of splenic vein, sequela','Laceration of splenic vein, sequela','Traumatismes, empoisonnements et autres causes externes','S35.321S'),
('autre specified injury of splenic vein, initial encounter','Other specified injury of splenic vein, initial encounter','Traumatismes, empoisonnements et autres causes externes','S35.328A'),
('autre specified injury of splenic vein, subsequent encounter','Other specified injury of splenic vein, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S35.328D'),
('autre specified injury of splenic vein, sequela','Other specified injury of splenic vein, sequela','Traumatismes, empoisonnements et autres causes externes','S35.328S')
ON CONFLICT (nom_fr) DO NOTHING;
