-- icd10v2_batch_015.sql (80 rows)
INSERT INTO pathologies (nom_fr, nom_en, categorie, icd10_code)
VALUES
('Tumeur maligne de base of tongue','Malignant neoplasm of base of tongue','Tumeurs malignes','C01'),
('Tumeur maligne de dorsal surface of tongue','Malignant neoplasm of dorsal surface of tongue','Tumeurs malignes','C02.0'),
('Tumeur maligne de border of tongue','Malignant neoplasm of border of tongue','Tumeurs malignes','C02.1'),
('Tumeur maligne de ventral surface of tongue','Malignant neoplasm of ventral surface of tongue','Tumeurs malignes','C02.2'),
('Tumeur maligne de anterior two-thirds of tongue, part unspecified','Malignant neoplasm of anterior two-thirds of tongue, part unspecified','Tumeurs malignes','C02.3'),
('Tumeur maligne de lingual tonsil','Malignant neoplasm of lingual tonsil','Tumeurs malignes','C02.4'),
('Tumeur maligne de overlapping sites of tongue','Malignant neoplasm of overlapping sites of tongue','Tumeurs malignes','C02.8'),
('Tumeur maligne de tongue, unspecified','Malignant neoplasm of tongue, unspecified','Tumeurs malignes','C02.9'),
('Tumeur maligne de upper gum','Malignant neoplasm of upper gum','Tumeurs malignes','C03.0'),
('Tumeur maligne de lower gum','Malignant neoplasm of lower gum','Tumeurs malignes','C03.1'),
('Tumeur maligne de gum, unspecified','Malignant neoplasm of gum, unspecified','Tumeurs malignes','C03.9'),
('Tumeur maligne de anterior floor of mouth','Malignant neoplasm of anterior floor of mouth','Tumeurs malignes','C04.0'),
('Tumeur maligne de lateral floor of mouth','Malignant neoplasm of lateral floor of mouth','Tumeurs malignes','C04.1'),
('Tumeur maligne de overlapping sites of floor of mouth','Malignant neoplasm of overlapping sites of floor of mouth','Tumeurs malignes','C04.8'),
('Tumeur maligne de floor of mouth, unspecified','Malignant neoplasm of floor of mouth, unspecified','Tumeurs malignes','C04.9'),
('Tumeur maligne de hard palate','Malignant neoplasm of hard palate','Tumeurs malignes','C05.0'),
('Tumeur maligne de soft palate','Malignant neoplasm of soft palate','Tumeurs malignes','C05.1'),
('Tumeur maligne de uvula','Malignant neoplasm of uvula','Tumeurs malignes','C05.2'),
('Tumeur maligne de overlapping sites of palate','Malignant neoplasm of overlapping sites of palate','Tumeurs malignes','C05.8'),
('Tumeur maligne de palate, unspecified','Malignant neoplasm of palate, unspecified','Tumeurs malignes','C05.9'),
('Tumeur maligne de cheek mucosa','Malignant neoplasm of cheek mucosa','Tumeurs malignes','C06.0'),
('Tumeur maligne de vestibule of mouth','Malignant neoplasm of vestibule of mouth','Tumeurs malignes','C06.1'),
('Tumeur maligne de retromolar area','Malignant neoplasm of retromolar area','Tumeurs malignes','C06.2'),
('Tumeur maligne de overlapping sites of unspecified parts of mouth','Malignant neoplasm of overlapping sites of unspecified parts of mouth','Tumeurs malignes','C06.80'),
('Tumeur maligne de overlapping sites of other parts of mouth','Malignant neoplasm of overlapping sites of other parts of mouth','Tumeurs malignes','C06.89'),
('Tumeur maligne de mouth, unspecified','Malignant neoplasm of mouth, unspecified','Tumeurs malignes','C06.9'),
('Tumeur maligne de parotid gland','Malignant neoplasm of parotid gland','Tumeurs malignes','C07'),
('Tumeur maligne de submandibular gland','Malignant neoplasm of submandibular gland','Tumeurs malignes','C08.0'),
('Tumeur maligne de sublingual gland','Malignant neoplasm of sublingual gland','Tumeurs malignes','C08.1'),
('Tumeur maligne de major salivary gland, unspecified','Malignant neoplasm of major salivary gland, unspecified','Tumeurs malignes','C08.9'),
('Tumeur maligne de tonsillar fossa','Malignant neoplasm of tonsillar fossa','Tumeurs malignes','C09.0'),
('Tumeur maligne de tonsillar pillar (anterior) (posterior)','Malignant neoplasm of tonsillar pillar (anterior) (posterior)','Tumeurs malignes','C09.1'),
('Tumeur maligne de overlapping sites of tonsil','Malignant neoplasm of overlapping sites of tonsil','Tumeurs malignes','C09.8'),
('Tumeur maligne de tonsil, unspecified','Malignant neoplasm of tonsil, unspecified','Tumeurs malignes','C09.9'),
('Quadriplegia, C1-C4 complete','Quadriplegia, C1-C4 complete','Maladies du système nerveux','G82.51'),
('Quadriplegia, C1-C4 incomplete','Quadriplegia, C1-C4 incomplete','Maladies du système nerveux','G82.52'),
('Subluxation of C1/C2 cervical vertebrae, sequela','Subluxation of C1/C2 cervical vertebrae, sequela','Traumatismes, empoisonnements et autres causes externes','S13.120S'),
('Luxation de C1/C2 cervical vertebrae, sequela','Dislocation of C1/C2 cervical vertebrae, sequela','Traumatismes, empoisonnements et autres causes externes','S13.121S'),
('Subluxation of C1/C2 cervical vertebrae, initial encounter','Subluxation of C1/C2 cervical vertebrae, initial encounter','Traumatismes, empoisonnements et autres causes externes','S13.120A'),
('Subluxation of C1/C2 cervical vertebrae, subsequent encounter','Subluxation of C1/C2 cervical vertebrae, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S13.120D'),
('Luxation de C1/C2 cervical vertebrae, initial encounter','Dislocation of C1/C2 cervical vertebrae, initial encounter','Traumatismes, empoisonnements et autres causes externes','S13.121A'),
('Luxation de C1/C2 cervical vertebrae, subsequent encounter','Dislocation of C1/C2 cervical vertebrae, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S13.121D'),
('non spécifié injury at C1 level of cervical spinal cord, sequela','Unspecified injury at C1 level of cervical spinal cord, sequela','Traumatismes, empoisonnements et autres causes externes','S14.101S'),
('Complete lesion at C1 level of cervical spinal cord, sequela','Complete lesion at C1 level of cervical spinal cord, sequela','Traumatismes, empoisonnements et autres causes externes','S14.111S'),
('non spécifié injury at C1 level of cervical spinal cord, initial encounter','Unspecified injury at C1 level of cervical spinal cord, initial encounter','Traumatismes, empoisonnements et autres causes externes','S14.101A'),
('non spécifié injury at C1 level of cervical spinal cord, subsequent encounter','Unspecified injury at C1 level of cervical spinal cord, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S14.101D'),
('Complete lesion at C1 level of cervical spinal cord, initial encounter','Complete lesion at C1 level of cervical spinal cord, initial encounter','Traumatismes, empoisonnements et autres causes externes','S14.111A'),
('Complete lesion at C1 level of cervical spinal cord, subsequent encounter','Complete lesion at C1 level of cervical spinal cord, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S14.111D'),
('Central cord syndrome at C1 level of cervical spinal cord, sequela','Central cord syndrome at C1 level of cervical spinal cord, sequela','Traumatismes, empoisonnements et autres causes externes','S14.121S'),
('Anterior cord syndrome at C1 level of cervical spinal cord, sequela','Anterior cord syndrome at C1 level of cervical spinal cord, sequela','Traumatismes, empoisonnements et autres causes externes','S14.131S'),
('Brown-Sequard syndrome at C1 level of cervical spinal cord, sequela','Brown-Sequard syndrome at C1 level of cervical spinal cord, sequela','Traumatismes, empoisonnements et autres causes externes','S14.141S'),
('autre incomplete lesion at C1 level of cervical spinal cord, sequela','Other incomplete lesion at C1 level of cervical spinal cord, sequela','Traumatismes, empoisonnements et autres causes externes','S14.151S'),
('Central cord syndrome at C1 level of cervical spinal cord, initial encounter','Central cord syndrome at C1 level of cervical spinal cord, initial encounter','Traumatismes, empoisonnements et autres causes externes','S14.121A'),
('Central cord syndrome at C1 level of cervical spinal cord, subsequent encounter','Central cord syndrome at C1 level of cervical spinal cord, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S14.121D'),
('Anterior cord syndrome at C1 level of cervical spinal cord, initial encounter','Anterior cord syndrome at C1 level of cervical spinal cord, initial encounter','Traumatismes, empoisonnements et autres causes externes','S14.131A'),
('Anterior cord syndrome at C1 level of cervical spinal cord, subsequent encounter','Anterior cord syndrome at C1 level of cervical spinal cord, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S14.131D'),
('Brown-Sequard syndrome at C1 level of cervical spinal cord, initial encounter','Brown-Sequard syndrome at C1 level of cervical spinal cord, initial encounter','Traumatismes, empoisonnements et autres causes externes','S14.141A'),
('Brown-Sequard syndrome at C1 level of cervical spinal cord, subsequent encounter','Brown-Sequard syndrome at C1 level of cervical spinal cord, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S14.141D'),
('autre incomplete lesion at C1 level of cervical spinal cord, initial encounter','Other incomplete lesion at C1 level of cervical spinal cord, initial encounter','Traumatismes, empoisonnements et autres causes externes','S14.151A'),
('autre incomplete lesion at C1 level of cervical spinal cord, subsequent encounter','Other incomplete lesion at C1 level of cervical spinal cord, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S14.151D'),
('Subluxation of C7/T1 cervical vertebrae, sequela','Subluxation of C7/T1 cervical vertebrae, sequela','Traumatismes, empoisonnements et autres causes externes','S13.180S'),
('Luxation de C7/T1 cervical vertebrae, sequela','Dislocation of C7/T1 cervical vertebrae, sequela','Traumatismes, empoisonnements et autres causes externes','S13.181S'),
('Subluxation of C7/T1 cervical vertebrae, initial encounter','Subluxation of C7/T1 cervical vertebrae, initial encounter','Traumatismes, empoisonnements et autres causes externes','S13.180A'),
('Subluxation of C7/T1 cervical vertebrae, subsequent encounter','Subluxation of C7/T1 cervical vertebrae, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S13.180D'),
('Luxation de C7/T1 cervical vertebrae, initial encounter','Dislocation of C7/T1 cervical vertebrae, initial encounter','Traumatismes, empoisonnements et autres causes externes','S13.181A'),
('Luxation de C7/T1 cervical vertebrae, subsequent encounter','Dislocation of C7/T1 cervical vertebrae, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S13.181D'),
('Tumeur maligne de vallecula','Malignant neoplasm of vallecula','Tumeurs malignes','C10.0'),
('Tumeur maligne de anterior surface of epiglottis','Malignant neoplasm of anterior surface of epiglottis','Tumeurs malignes','C10.1'),
('Tumeur maligne de lateral wall of oropharynx','Malignant neoplasm of lateral wall of oropharynx','Tumeurs malignes','C10.2'),
('Tumeur maligne de posterior wall of oropharynx','Malignant neoplasm of posterior wall of oropharynx','Tumeurs malignes','C10.3'),
('Tumeur maligne de branchial cleft','Malignant neoplasm of branchial cleft','Tumeurs malignes','C10.4'),
('Tumeur maligne de overlapping sites of oropharynx','Malignant neoplasm of overlapping sites of oropharynx','Tumeurs malignes','C10.8'),
('Tumeur maligne de oropharynx, unspecified','Malignant neoplasm of oropharynx, unspecified','Tumeurs malignes','C10.9'),
('Tumeur maligne de superior wall of nasopharynx','Malignant neoplasm of superior wall of nasopharynx','Tumeurs malignes','C11.0'),
('Tumeur maligne de posterior wall of nasopharynx','Malignant neoplasm of posterior wall of nasopharynx','Tumeurs malignes','C11.1'),
('Tumeur maligne de lateral wall of nasopharynx','Malignant neoplasm of lateral wall of nasopharynx','Tumeurs malignes','C11.2'),
('Tumeur maligne de anterior wall of nasopharynx','Malignant neoplasm of anterior wall of nasopharynx','Tumeurs malignes','C11.3'),
('Tumeur maligne de overlapping sites of nasopharynx','Malignant neoplasm of overlapping sites of nasopharynx','Tumeurs malignes','C11.8'),
('Tumeur maligne de nasopharynx, unspecified','Malignant neoplasm of nasopharynx, unspecified','Tumeurs malignes','C11.9'),
('Tumeur maligne de pyriform sinus','Malignant neoplasm of pyriform sinus','Tumeurs malignes','C12')
ON CONFLICT (nom_fr) DO NOTHING;
