-- icd10v2_batch_346.sql (80 rows)
INSERT INTO pathologies (nom_fr, nom_en, categorie, icd10_code)
VALUES
('Corrosion of third degree of abdominal wall, sequela','Corrosion of third degree of abdominal wall, sequela','Traumatismes, empoisonnements et autres causes externes','T21.72XS'),
('Corrosion of third degree of upper back, initial encounter','Corrosion of third degree of upper back, initial encounter','Traumatismes, empoisonnements et autres causes externes','T21.73XA'),
('Corrosion of third degree of upper back, subsequent encounter','Corrosion of third degree of upper back, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T21.73XD'),
('Corrosion of third degree of upper back, sequela','Corrosion of third degree of upper back, sequela','Traumatismes, empoisonnements et autres causes externes','T21.73XS'),
('Corrosion of third degree of lower back, initial encounter','Corrosion of third degree of lower back, initial encounter','Traumatismes, empoisonnements et autres causes externes','T21.74XA'),
('Corrosion of third degree of lower back, subsequent encounter','Corrosion of third degree of lower back, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T21.74XD'),
('Corrosion of third degree of lower back, sequela','Corrosion of third degree of lower back, sequela','Traumatismes, empoisonnements et autres causes externes','T21.74XS'),
('Corrosion of third degree of buttock, initial encounter','Corrosion of third degree of buttock, initial encounter','Traumatismes, empoisonnements et autres causes externes','T21.75XA'),
('Corrosion of third degree of buttock, subsequent encounter','Corrosion of third degree of buttock, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T21.75XD'),
('Corrosion of third degree of buttock, sequela','Corrosion of third degree of buttock, sequela','Traumatismes, empoisonnements et autres causes externes','T21.75XS'),
('Corrosion of third degree of male genital region, initial encounter','Corrosion of third degree of male genital region, initial encounter','Traumatismes, empoisonnements et autres causes externes','T21.76XA'),
('Corrosion of third degree of male genital region, subsequent encounter','Corrosion of third degree of male genital region, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T21.76XD'),
('Corrosion of third degree of male genital region, sequela','Corrosion of third degree of male genital region, sequela','Traumatismes, empoisonnements et autres causes externes','T21.76XS'),
('Corrosion of third degree of female genital region, initial encounter','Corrosion of third degree of female genital region, initial encounter','Traumatismes, empoisonnements et autres causes externes','T21.77XA'),
('Corrosion of third degree of female genital region, subsequent encounter','Corrosion of third degree of female genital region, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T21.77XD'),
('Corrosion of third degree of female genital region, sequela','Corrosion of third degree of female genital region, sequela','Traumatismes, empoisonnements et autres causes externes','T21.77XS'),
('Corrosion of third degree of autre site of trunk, initial encounter','Corrosion of third degree of other site of trunk, initial encounter','Traumatismes, empoisonnements et autres causes externes','T21.79XA'),
('Corrosion of third degree of autre site of trunk, subsequent encounter','Corrosion of third degree of other site of trunk, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T21.79XD'),
('Corrosion of third degree of autre site of trunk, sequela','Corrosion of third degree of other site of trunk, sequela','Traumatismes, empoisonnements et autres causes externes','T21.79XS'),
('Subluxation of T3/T4 thoracic vertebra, sequela','Subluxation of T3/T4 thoracic vertebra, sequela','Traumatismes, empoisonnements et autres causes externes','S23.122S'),
('Luxation de T3/T4 thoracic vertebra, sequela','Dislocation of T3/T4 thoracic vertebra, sequela','Traumatismes, empoisonnements et autres causes externes','S23.123S'),
('Subluxation of T3/T4 thoracic vertebra, initial encounter','Subluxation of T3/T4 thoracic vertebra, initial encounter','Traumatismes, empoisonnements et autres causes externes','S23.122A'),
('Subluxation of T3/T4 thoracic vertebra, subsequent encounter','Subluxation of T3/T4 thoracic vertebra, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S23.122D'),
('Luxation de T3/T4 thoracic vertebra, initial encounter','Dislocation of T3/T4 thoracic vertebra, initial encounter','Traumatismes, empoisonnements et autres causes externes','S23.123A'),
('Luxation de T3/T4 thoracic vertebra, subsequent encounter','Dislocation of T3/T4 thoracic vertebra, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S23.123D'),
('Burn of non spécifié body region, non spécifié degree','Burn of unspecified body region, unspecified degree','Traumatismes, empoisonnements et autres causes externes','T30.0'),
('Corrosion of non spécifié body region, non spécifié degree','Corrosion of unspecified body region, unspecified degree','Traumatismes, empoisonnements et autres causes externes','T30.4'),
('Burns involving less than 10% of body surface','Burns involving less than 10% of body surface','Traumatismes, empoisonnements et autres causes externes','T31.0'),
('Burns involving 10-19% of body surface with 0% to 9% third degree burns','Burns involving 10-19% of body surface with 0% to 9% third degree burns','Traumatismes, empoisonnements et autres causes externes','T31.10'),
('Burns involving 10-19% of body surface with 10-19% third degree burns','Burns involving 10-19% of body surface with 10-19% third degree burns','Traumatismes, empoisonnements et autres causes externes','T31.11'),
('Burns involving 20-29% of body surface with 0% to 9% third degree burns','Burns involving 20-29% of body surface with 0% to 9% third degree burns','Traumatismes, empoisonnements et autres causes externes','T31.20'),
('Burns involving 20-29% of body surface with 10-19% third degree burns','Burns involving 20-29% of body surface with 10-19% third degree burns','Traumatismes, empoisonnements et autres causes externes','T31.21'),
('Burns involving 20-29% of body surface with 20-29% third degree burns','Burns involving 20-29% of body surface with 20-29% third degree burns','Traumatismes, empoisonnements et autres causes externes','T31.22'),
('Burns involving 30-39% of body surface with 0% to 9% third degree burns','Burns involving 30-39% of body surface with 0% to 9% third degree burns','Traumatismes, empoisonnements et autres causes externes','T31.30'),
('Burns involving 30-39% of body surface with 10-19% third degree burns','Burns involving 30-39% of body surface with 10-19% third degree burns','Traumatismes, empoisonnements et autres causes externes','T31.31'),
('Burns involving 30-39% of body surface with 20-29% third degree burns','Burns involving 30-39% of body surface with 20-29% third degree burns','Traumatismes, empoisonnements et autres causes externes','T31.32'),
('Burns involving 30-39% of body surface with 30-39% third degree burns','Burns involving 30-39% of body surface with 30-39% third degree burns','Traumatismes, empoisonnements et autres causes externes','T31.33'),
('Burns involving 40-49% of body surface with 0% to 9% third degree burns','Burns involving 40-49% of body surface with 0% to 9% third degree burns','Traumatismes, empoisonnements et autres causes externes','T31.40'),
('Burns involving 40-49% of body surface with 10-19% third degree burns','Burns involving 40-49% of body surface with 10-19% third degree burns','Traumatismes, empoisonnements et autres causes externes','T31.41'),
('Burns involving 40-49% of body surface with 20-29% third degree burns','Burns involving 40-49% of body surface with 20-29% third degree burns','Traumatismes, empoisonnements et autres causes externes','T31.42'),
('Burns involving 40-49% of body surface with 30-39% third degree burns','Burns involving 40-49% of body surface with 30-39% third degree burns','Traumatismes, empoisonnements et autres causes externes','T31.43'),
('Burns involving 40-49% of body surface with 40-49% third degree burns','Burns involving 40-49% of body surface with 40-49% third degree burns','Traumatismes, empoisonnements et autres causes externes','T31.44'),
('Burns involving 50-59% of body surface with 0% to 9% third degree burns','Burns involving 50-59% of body surface with 0% to 9% third degree burns','Traumatismes, empoisonnements et autres causes externes','T31.50'),
('Burns involving 50-59% of body surface with 10-19% third degree burns','Burns involving 50-59% of body surface with 10-19% third degree burns','Traumatismes, empoisonnements et autres causes externes','T31.51'),
('Burns involving 50-59% of body surface with 20-29% third degree burns','Burns involving 50-59% of body surface with 20-29% third degree burns','Traumatismes, empoisonnements et autres causes externes','T31.52'),
('Burns involving 50-59% of body surface with 30-39% third degree burns','Burns involving 50-59% of body surface with 30-39% third degree burns','Traumatismes, empoisonnements et autres causes externes','T31.53'),
('Burns involving 50-59% of body surface with 40-49% third degree burns','Burns involving 50-59% of body surface with 40-49% third degree burns','Traumatismes, empoisonnements et autres causes externes','T31.54'),
('Burns involving 50-59% of body surface with 50-59% third degree burns','Burns involving 50-59% of body surface with 50-59% third degree burns','Traumatismes, empoisonnements et autres causes externes','T31.55'),
('Burns involving 60-69% of body surface with 0% to 9% third degree burns','Burns involving 60-69% of body surface with 0% to 9% third degree burns','Traumatismes, empoisonnements et autres causes externes','T31.60'),
('Burns involving 60-69% of body surface with 10-19% third degree burns','Burns involving 60-69% of body surface with 10-19% third degree burns','Traumatismes, empoisonnements et autres causes externes','T31.61'),
('Burns involving 60-69% of body surface with 20-29% third degree burns','Burns involving 60-69% of body surface with 20-29% third degree burns','Traumatismes, empoisonnements et autres causes externes','T31.62'),
('Burns involving 60-69% of body surface with 30-39% third degree burns','Burns involving 60-69% of body surface with 30-39% third degree burns','Traumatismes, empoisonnements et autres causes externes','T31.63'),
('Burns involving 60-69% of body surface with 40-49% third degree burns','Burns involving 60-69% of body surface with 40-49% third degree burns','Traumatismes, empoisonnements et autres causes externes','T31.64'),
('Burns involving 60-69% of body surface with 50-59% third degree burns','Burns involving 60-69% of body surface with 50-59% third degree burns','Traumatismes, empoisonnements et autres causes externes','T31.65'),
('Burns involving 60-69% of body surface with 60-69% third degree burns','Burns involving 60-69% of body surface with 60-69% third degree burns','Traumatismes, empoisonnements et autres causes externes','T31.66'),
('Burns involving 70-79% of body surface with 0% to 9% third degree burns','Burns involving 70-79% of body surface with 0% to 9% third degree burns','Traumatismes, empoisonnements et autres causes externes','T31.70'),
('Burns involving 70-79% of body surface with 10-19% third degree burns','Burns involving 70-79% of body surface with 10-19% third degree burns','Traumatismes, empoisonnements et autres causes externes','T31.71'),
('Burns involving 70-79% of body surface with 20-29% third degree burns','Burns involving 70-79% of body surface with 20-29% third degree burns','Traumatismes, empoisonnements et autres causes externes','T31.72'),
('Burns involving 70-79% of body surface with 30-39% third degree burns','Burns involving 70-79% of body surface with 30-39% third degree burns','Traumatismes, empoisonnements et autres causes externes','T31.73'),
('Burns involving 70-79% of body surface with 40-49% third degree burns','Burns involving 70-79% of body surface with 40-49% third degree burns','Traumatismes, empoisonnements et autres causes externes','T31.74'),
('Burns involving 70-79% of body surface with 50-59% third degree burns','Burns involving 70-79% of body surface with 50-59% third degree burns','Traumatismes, empoisonnements et autres causes externes','T31.75'),
('Burns involving 70-79% of body surface with 60-69% third degree burns','Burns involving 70-79% of body surface with 60-69% third degree burns','Traumatismes, empoisonnements et autres causes externes','T31.76'),
('Burns involving 70-79% of body surface with 70-79% third degree burns','Burns involving 70-79% of body surface with 70-79% third degree burns','Traumatismes, empoisonnements et autres causes externes','T31.77'),
('Burns involving 80-89% of body surface with 0% to 9% third degree burns','Burns involving 80-89% of body surface with 0% to 9% third degree burns','Traumatismes, empoisonnements et autres causes externes','T31.80'),
('Burns involving 80-89% of body surface with 10-19% third degree burns','Burns involving 80-89% of body surface with 10-19% third degree burns','Traumatismes, empoisonnements et autres causes externes','T31.81'),
('Burns involving 80-89% of body surface with 20-29% third degree burns','Burns involving 80-89% of body surface with 20-29% third degree burns','Traumatismes, empoisonnements et autres causes externes','T31.82'),
('Burns involving 80-89% of body surface with 30-39% third degree burns','Burns involving 80-89% of body surface with 30-39% third degree burns','Traumatismes, empoisonnements et autres causes externes','T31.83'),
('Burns involving 80-89% of body surface with 40-49% third degree burns','Burns involving 80-89% of body surface with 40-49% third degree burns','Traumatismes, empoisonnements et autres causes externes','T31.84'),
('Burns involving 80-89% of body surface with 50-59% third degree burns','Burns involving 80-89% of body surface with 50-59% third degree burns','Traumatismes, empoisonnements et autres causes externes','T31.85'),
('Burns involving 80-89% of body surface with 60-69% third degree burns','Burns involving 80-89% of body surface with 60-69% third degree burns','Traumatismes, empoisonnements et autres causes externes','T31.86'),
('Burns involving 80-89% of body surface with 70-79% third degree burns','Burns involving 80-89% of body surface with 70-79% third degree burns','Traumatismes, empoisonnements et autres causes externes','T31.87'),
('Burns involving 80-89% of body surface with 80-89% third degree burns','Burns involving 80-89% of body surface with 80-89% third degree burns','Traumatismes, empoisonnements et autres causes externes','T31.88'),
('Burns involving 90% or more of body surface with 0% to 9% third degree burns','Burns involving 90% or more of body surface with 0% to 9% third degree burns','Traumatismes, empoisonnements et autres causes externes','T31.90'),
('Burns involving 90% or more of body surface with 10-19% third degree burns','Burns involving 90% or more of body surface with 10-19% third degree burns','Traumatismes, empoisonnements et autres causes externes','T31.91'),
('Burns involving 90% or more of body surface with 20-29% third degree burns','Burns involving 90% or more of body surface with 20-29% third degree burns','Traumatismes, empoisonnements et autres causes externes','T31.92'),
('Burns involving 90% or more of body surface with 30-39% third degree burns','Burns involving 90% or more of body surface with 30-39% third degree burns','Traumatismes, empoisonnements et autres causes externes','T31.93'),
('Burns involving 90% or more of body surface with 40-49% third degree burns','Burns involving 90% or more of body surface with 40-49% third degree burns','Traumatismes, empoisonnements et autres causes externes','T31.94'),
('Burns involving 90% or more of body surface with 50-59% third degree burns','Burns involving 90% or more of body surface with 50-59% third degree burns','Traumatismes, empoisonnements et autres causes externes','T31.95'),
('Burns involving 90% or more of body surface with 60-69% third degree burns','Burns involving 90% or more of body surface with 60-69% third degree burns','Traumatismes, empoisonnements et autres causes externes','T31.96'),
('Burns involving 90% or more of body surface with 70-79% third degree burns','Burns involving 90% or more of body surface with 70-79% third degree burns','Traumatismes, empoisonnements et autres causes externes','T31.97')
ON CONFLICT (nom_fr) DO NOTHING;
