-- icd10v2_batch_240.sql (80 rows)
INSERT INTO pathologies (nom_fr, nom_en, categorie, icd10_code)
VALUES
('Obstructed labor due to autre malposition and malpresentation, fetus 4','Obstructed labor due to other malposition and malpresentation, fetus 4','Grossesse, accouchement et puerpéralité','O64.8XX4'),
('Obstructed labor due to autre malposition and malpresentation, fetus 5','Obstructed labor due to other malposition and malpresentation, fetus 5','Grossesse, accouchement et puerpéralité','O64.8XX5'),
('Obstructed labor due to autre malposition and malpresentation, autre fetus','Obstructed labor due to other malposition and malpresentation, other fetus','Grossesse, accouchement et puerpéralité','O64.8XX9'),
('Obstructed labor due to malposition and malpresentation, non spécifié, not applicable or non spécifié','Obstructed labor due to malposition and malpresentation, unspecified, not applicable or unspecified','Grossesse, accouchement et puerpéralité','O64.9XX0'),
('Obstructed labor due to malposition and malpresentation, non spécifié, fetus 1','Obstructed labor due to malposition and malpresentation, unspecified, fetus 1','Grossesse, accouchement et puerpéralité','O64.9XX1'),
('Obstructed labor due to malposition and malpresentation, non spécifié, fetus 2','Obstructed labor due to malposition and malpresentation, unspecified, fetus 2','Grossesse, accouchement et puerpéralité','O64.9XX2'),
('Obstructed labor due to malposition and malpresentation, non spécifié, fetus 3','Obstructed labor due to malposition and malpresentation, unspecified, fetus 3','Grossesse, accouchement et puerpéralité','O64.9XX3'),
('Obstructed labor due to malposition and malpresentation, non spécifié, fetus 4','Obstructed labor due to malposition and malpresentation, unspecified, fetus 4','Grossesse, accouchement et puerpéralité','O64.9XX4'),
('Obstructed labor due to malposition and malpresentation, non spécifié, fetus 5','Obstructed labor due to malposition and malpresentation, unspecified, fetus 5','Grossesse, accouchement et puerpéralité','O64.9XX5'),
('Obstructed labor due to malposition and malpresentation, non spécifié, autre fetus','Obstructed labor due to malposition and malpresentation, unspecified, other fetus','Grossesse, accouchement et puerpéralité','O64.9XX9'),
('Obstructed labor due to deformed pelvis','Obstructed labor due to deformed pelvis','Grossesse, accouchement et puerpéralité','O65.0'),
('Obstructed labor due to generally contracted pelvis','Obstructed labor due to generally contracted pelvis','Grossesse, accouchement et puerpéralité','O65.1'),
('Obstructed labor due to pelvic inlet contraction','Obstructed labor due to pelvic inlet contraction','Grossesse, accouchement et puerpéralité','O65.2'),
('Obstructed labor due to pelvic outlet and mid-cavity contraction','Obstructed labor due to pelvic outlet and mid-cavity contraction','Grossesse, accouchement et puerpéralité','O65.3'),
('Obstructed labor due to fetopelvic disproportion, non spécifié','Obstructed labor due to fetopelvic disproportion, unspecified','Grossesse, accouchement et puerpéralité','O65.4'),
('Obstructed labor due to abnormality of maternal pelvic organs','Obstructed labor due to abnormality of maternal pelvic organs','Grossesse, accouchement et puerpéralité','O65.5'),
('Obstructed labor due to autre maternal pelvic abnormalities','Obstructed labor due to other maternal pelvic abnormalities','Grossesse, accouchement et puerpéralité','O65.8'),
('Obstructed labor due to maternal pelvic abnormality, non spécifié','Obstructed labor due to maternal pelvic abnormality, unspecified','Grossesse, accouchement et puerpéralité','O65.9'),
('Obstructed labor due to shoulder dystocia','Obstructed labor due to shoulder dystocia','Grossesse, accouchement et puerpéralité','O66.0'),
('Obstructed labor due to locked twins','Obstructed labor due to locked twins','Grossesse, accouchement et puerpéralité','O66.1'),
('Obstructed labor due to unusually large fetus','Obstructed labor due to unusually large fetus','Grossesse, accouchement et puerpéralité','O66.2'),
('Obstructed labor due to autre abnormalities of fetus','Obstructed labor due to other abnormalities of fetus','Grossesse, accouchement et puerpéralité','O66.3'),
('Failed trial of labor, non spécifié','Failed trial of labor, unspecified','Grossesse, accouchement et puerpéralité','O66.40'),
('Failed attempted vaginal birth after previous cesarean delivery','Failed attempted vaginal birth after previous cesarean delivery','Grossesse, accouchement et puerpéralité','O66.41'),
('Attempted application of vacuum extractor and forceps','Attempted application of vacuum extractor and forceps','Grossesse, accouchement et puerpéralité','O66.5'),
('Obstructed labor due to autre multiple fetuses','Obstructed labor due to other multiple fetuses','Grossesse, accouchement et puerpéralité','O66.6'),
('autre specified obstructed labor','Other specified obstructed labor','Grossesse, accouchement et puerpéralité','O66.8'),
('Obstructed labor, non spécifié','Obstructed labor, unspecified','Grossesse, accouchement et puerpéralité','O66.9'),
('Intrapartum hémorragie with coagulation defect','Intrapartum hemorrhage with coagulation defect','Grossesse, accouchement et puerpéralité','O67.0'),
('autre intrapartum hémorragie','Other intrapartum hemorrhage','Grossesse, accouchement et puerpéralité','O67.8'),
('Intrapartum hémorragie, non spécifié','Intrapartum hemorrhage, unspecified','Grossesse, accouchement et puerpéralité','O67.9'),
('Labor and delivery complicated by abnormality of fetal acid-base balance','Labor and delivery complicated by abnormality of fetal acid-base balance','Grossesse, accouchement et puerpéralité','O68'),
('Labor and delivery complicated by prolapse of cord, not applicable or non spécifié','Labor and delivery complicated by prolapse of cord, not applicable or unspecified','Grossesse, accouchement et puerpéralité','O69.0XX0'),
('Labor and delivery complicated by prolapse of cord, fetus 1','Labor and delivery complicated by prolapse of cord, fetus 1','Grossesse, accouchement et puerpéralité','O69.0XX1'),
('Labor and delivery complicated by prolapse of cord, fetus 2','Labor and delivery complicated by prolapse of cord, fetus 2','Grossesse, accouchement et puerpéralité','O69.0XX2'),
('Labor and delivery complicated by prolapse of cord, fetus 3','Labor and delivery complicated by prolapse of cord, fetus 3','Grossesse, accouchement et puerpéralité','O69.0XX3'),
('Labor and delivery complicated by prolapse of cord, fetus 4','Labor and delivery complicated by prolapse of cord, fetus 4','Grossesse, accouchement et puerpéralité','O69.0XX4'),
('Labor and delivery complicated by prolapse of cord, fetus 5','Labor and delivery complicated by prolapse of cord, fetus 5','Grossesse, accouchement et puerpéralité','O69.0XX5'),
('Labor and delivery complicated by prolapse of cord, autre fetus','Labor and delivery complicated by prolapse of cord, other fetus','Grossesse, accouchement et puerpéralité','O69.0XX9'),
('Labor and delivery complicated by cord around neck, with compression, not applicable or non spécifié','Labor and delivery complicated by cord around neck, with compression, not applicable or unspecified','Grossesse, accouchement et puerpéralité','O69.1XX0'),
('Labor and delivery complicated by cord around neck, with compression, fetus 1','Labor and delivery complicated by cord around neck, with compression, fetus 1','Grossesse, accouchement et puerpéralité','O69.1XX1'),
('Labor and delivery complicated by cord around neck, with compression, fetus 2','Labor and delivery complicated by cord around neck, with compression, fetus 2','Grossesse, accouchement et puerpéralité','O69.1XX2'),
('Labor and delivery complicated by cord around neck, with compression, fetus 3','Labor and delivery complicated by cord around neck, with compression, fetus 3','Grossesse, accouchement et puerpéralité','O69.1XX3'),
('Labor and delivery complicated by cord around neck, with compression, fetus 4','Labor and delivery complicated by cord around neck, with compression, fetus 4','Grossesse, accouchement et puerpéralité','O69.1XX4'),
('Labor and delivery complicated by cord around neck, with compression, fetus 5','Labor and delivery complicated by cord around neck, with compression, fetus 5','Grossesse, accouchement et puerpéralité','O69.1XX5'),
('Labor and delivery complicated by cord around neck, with compression, autre fetus','Labor and delivery complicated by cord around neck, with compression, other fetus','Grossesse, accouchement et puerpéralité','O69.1XX9'),
('Labor and delivery complicated by autre cord entanglement, with compression, not applicable or non spécifié','Labor and delivery complicated by other cord entanglement, with compression, not applicable or unspecified','Grossesse, accouchement et puerpéralité','O69.2XX0'),
('Labor and delivery complicated by autre cord entanglement, with compression, fetus 1','Labor and delivery complicated by other cord entanglement, with compression, fetus 1','Grossesse, accouchement et puerpéralité','O69.2XX1'),
('Labor and delivery complicated by autre cord entanglement, with compression, fetus 2','Labor and delivery complicated by other cord entanglement, with compression, fetus 2','Grossesse, accouchement et puerpéralité','O69.2XX2'),
('Labor and delivery complicated by autre cord entanglement, with compression, fetus 3','Labor and delivery complicated by other cord entanglement, with compression, fetus 3','Grossesse, accouchement et puerpéralité','O69.2XX3'),
('Labor and delivery complicated by autre cord entanglement, with compression, fetus 4','Labor and delivery complicated by other cord entanglement, with compression, fetus 4','Grossesse, accouchement et puerpéralité','O69.2XX4'),
('Labor and delivery complicated by autre cord entanglement, with compression, fetus 5','Labor and delivery complicated by other cord entanglement, with compression, fetus 5','Grossesse, accouchement et puerpéralité','O69.2XX5'),
('Labor and delivery complicated by autre cord entanglement, with compression, autre fetus','Labor and delivery complicated by other cord entanglement, with compression, other fetus','Grossesse, accouchement et puerpéralité','O69.2XX9'),
('Labor and delivery complicated by short cord, not applicable or non spécifié','Labor and delivery complicated by short cord, not applicable or unspecified','Grossesse, accouchement et puerpéralité','O69.3XX0'),
('Labor and delivery complicated by short cord, fetus 1','Labor and delivery complicated by short cord, fetus 1','Grossesse, accouchement et puerpéralité','O69.3XX1'),
('Labor and delivery complicated by short cord, fetus 2','Labor and delivery complicated by short cord, fetus 2','Grossesse, accouchement et puerpéralité','O69.3XX2'),
('Labor and delivery complicated by short cord, fetus 3','Labor and delivery complicated by short cord, fetus 3','Grossesse, accouchement et puerpéralité','O69.3XX3'),
('Labor and delivery complicated by short cord, fetus 4','Labor and delivery complicated by short cord, fetus 4','Grossesse, accouchement et puerpéralité','O69.3XX4'),
('Labor and delivery complicated by short cord, fetus 5','Labor and delivery complicated by short cord, fetus 5','Grossesse, accouchement et puerpéralité','O69.3XX5'),
('Labor and delivery complicated by short cord, autre fetus','Labor and delivery complicated by short cord, other fetus','Grossesse, accouchement et puerpéralité','O69.3XX9'),
('Labor and delivery complicated by vasa previa, not applicable or non spécifié','Labor and delivery complicated by vasa previa, not applicable or unspecified','Grossesse, accouchement et puerpéralité','O69.4XX0'),
('Labor and delivery complicated by vasa previa, fetus 1','Labor and delivery complicated by vasa previa, fetus 1','Grossesse, accouchement et puerpéralité','O69.4XX1'),
('Labor and delivery complicated by vasa previa, fetus 2','Labor and delivery complicated by vasa previa, fetus 2','Grossesse, accouchement et puerpéralité','O69.4XX2'),
('Labor and delivery complicated by vasa previa, fetus 3','Labor and delivery complicated by vasa previa, fetus 3','Grossesse, accouchement et puerpéralité','O69.4XX3'),
('Labor and delivery complicated by vasa previa, fetus 4','Labor and delivery complicated by vasa previa, fetus 4','Grossesse, accouchement et puerpéralité','O69.4XX4'),
('Labor and delivery complicated by vasa previa, fetus 5','Labor and delivery complicated by vasa previa, fetus 5','Grossesse, accouchement et puerpéralité','O69.4XX5'),
('Labor and delivery complicated by vasa previa, autre fetus','Labor and delivery complicated by vasa previa, other fetus','Grossesse, accouchement et puerpéralité','O69.4XX9'),
('Labor and delivery complicated by vascular lesion of cord, not applicable or non spécifié','Labor and delivery complicated by vascular lesion of cord, not applicable or unspecified','Grossesse, accouchement et puerpéralité','O69.5XX0'),
('Labor and delivery complicated by vascular lesion of cord, fetus 1','Labor and delivery complicated by vascular lesion of cord, fetus 1','Grossesse, accouchement et puerpéralité','O69.5XX1'),
('Labor and delivery complicated by vascular lesion of cord, fetus 2','Labor and delivery complicated by vascular lesion of cord, fetus 2','Grossesse, accouchement et puerpéralité','O69.5XX2'),
('Labor and delivery complicated by vascular lesion of cord, fetus 3','Labor and delivery complicated by vascular lesion of cord, fetus 3','Grossesse, accouchement et puerpéralité','O69.5XX3'),
('Labor and delivery complicated by vascular lesion of cord, fetus 4','Labor and delivery complicated by vascular lesion of cord, fetus 4','Grossesse, accouchement et puerpéralité','O69.5XX4'),
('Labor and delivery complicated by vascular lesion of cord, fetus 5','Labor and delivery complicated by vascular lesion of cord, fetus 5','Grossesse, accouchement et puerpéralité','O69.5XX5'),
('Labor and delivery complicated by vascular lesion of cord, autre fetus','Labor and delivery complicated by vascular lesion of cord, other fetus','Grossesse, accouchement et puerpéralité','O69.5XX9'),
('Labor and delivery complicated by cord around neck, without compression, not applicable or non spécifié','Labor and delivery complicated by cord around neck, without compression, not applicable or unspecified','Grossesse, accouchement et puerpéralité','O69.81X0'),
('Labor and delivery complicated by cord around neck, without compression, fetus 1','Labor and delivery complicated by cord around neck, without compression, fetus 1','Grossesse, accouchement et puerpéralité','O69.81X1'),
('Labor and delivery complicated by cord around neck, without compression, fetus 2','Labor and delivery complicated by cord around neck, without compression, fetus 2','Grossesse, accouchement et puerpéralité','O69.81X2'),
('Labor and delivery complicated by cord around neck, without compression, fetus 3','Labor and delivery complicated by cord around neck, without compression, fetus 3','Grossesse, accouchement et puerpéralité','O69.81X3'),
('Labor and delivery complicated by cord around neck, without compression, fetus 4','Labor and delivery complicated by cord around neck, without compression, fetus 4','Grossesse, accouchement et puerpéralité','O69.81X4'),
('Labor and delivery complicated by cord around neck, without compression, fetus 5','Labor and delivery complicated by cord around neck, without compression, fetus 5','Grossesse, accouchement et puerpéralité','O69.81X5')
ON CONFLICT (nom_fr) DO NOTHING;
