-- icd10v2_batch_693.sql (80 rows)
INSERT INTO pathologies (nom_fr, nom_en, categorie, icd10_code)
VALUES
('Intoxication par other hormones and synthetic substitutes, undetermined, sequela','Poisoning by other hormones and synthetic substitutes, undetermined, sequela','Traumatismes, empoisonnements et autres causes externes','T38.894S'),
('Effet indésirable de other hormones and synthetic substitutes, initial encounter','Adverse effect of other hormones and synthetic substitutes, initial encounter','Traumatismes, empoisonnements et autres causes externes','T38.895A'),
('Effet indésirable de other hormones and synthetic substitutes, subsequent encounter','Adverse effect of other hormones and synthetic substitutes, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T38.895D'),
('Effet indésirable de other hormones and synthetic substitutes, sequela','Adverse effect of other hormones and synthetic substitutes, sequela','Traumatismes, empoisonnements et autres causes externes','T38.895S'),
('Underdosing of autre hormones and synthetic substitutes, initial encounter','Underdosing of other hormones and synthetic substitutes, initial encounter','Traumatismes, empoisonnements et autres causes externes','T38.896A'),
('Underdosing of autre hormones and synthetic substitutes, subsequent encounter','Underdosing of other hormones and synthetic substitutes, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T38.896D'),
('Underdosing of autre hormones and synthetic substitutes, sequela','Underdosing of other hormones and synthetic substitutes, sequela','Traumatismes, empoisonnements et autres causes externes','T38.896S'),
('Intoxication par unspecified hormone antagonists, accidental (unintentional), initial encounter','Poisoning by unspecified hormone antagonists, accidental (unintentional), initial encounter','Traumatismes, empoisonnements et autres causes externes','T38.901A'),
('Intoxication par unspecified hormone antagonists, accidental (unintentional), subsequent encounter','Poisoning by unspecified hormone antagonists, accidental (unintentional), subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T38.901D'),
('Intoxication par unspecified hormone antagonists, accidental (unintentional), sequela','Poisoning by unspecified hormone antagonists, accidental (unintentional), sequela','Traumatismes, empoisonnements et autres causes externes','T38.901S'),
('Intoxication par unspecified hormone antagonists, intentional self-harm, initial encounter','Poisoning by unspecified hormone antagonists, intentional self-harm, initial encounter','Traumatismes, empoisonnements et autres causes externes','T38.902A'),
('Intoxication par unspecified hormone antagonists, intentional self-harm, subsequent encounter','Poisoning by unspecified hormone antagonists, intentional self-harm, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T38.902D'),
('Intoxication par unspecified hormone antagonists, intentional self-harm, sequela','Poisoning by unspecified hormone antagonists, intentional self-harm, sequela','Traumatismes, empoisonnements et autres causes externes','T38.902S'),
('Intoxication par unspecified hormone antagonists, assault, initial encounter','Poisoning by unspecified hormone antagonists, assault, initial encounter','Traumatismes, empoisonnements et autres causes externes','T38.903A'),
('Intoxication par unspecified hormone antagonists, assault, subsequent encounter','Poisoning by unspecified hormone antagonists, assault, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T38.903D'),
('Intoxication par unspecified hormone antagonists, assault, sequela','Poisoning by unspecified hormone antagonists, assault, sequela','Traumatismes, empoisonnements et autres causes externes','T38.903S'),
('Intoxication par unspecified hormone antagonists, undetermined, initial encounter','Poisoning by unspecified hormone antagonists, undetermined, initial encounter','Traumatismes, empoisonnements et autres causes externes','T38.904A'),
('Intoxication par unspecified hormone antagonists, undetermined, subsequent encounter','Poisoning by unspecified hormone antagonists, undetermined, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T38.904D'),
('Intoxication par unspecified hormone antagonists, undetermined, sequela','Poisoning by unspecified hormone antagonists, undetermined, sequela','Traumatismes, empoisonnements et autres causes externes','T38.904S'),
('Effet indésirable de unspecified hormone antagonists, initial encounter','Adverse effect of unspecified hormone antagonists, initial encounter','Traumatismes, empoisonnements et autres causes externes','T38.905A'),
('Effet indésirable de unspecified hormone antagonists, subsequent encounter','Adverse effect of unspecified hormone antagonists, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T38.905D'),
('Effet indésirable de unspecified hormone antagonists, sequela','Adverse effect of unspecified hormone antagonists, sequela','Traumatismes, empoisonnements et autres causes externes','T38.905S'),
('Underdosing of non spécifié hormone antagonists, initial encounter','Underdosing of unspecified hormone antagonists, initial encounter','Traumatismes, empoisonnements et autres causes externes','T38.906A'),
('Underdosing of non spécifié hormone antagonists, subsequent encounter','Underdosing of unspecified hormone antagonists, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T38.906D'),
('Underdosing of non spécifié hormone antagonists, sequela','Underdosing of unspecified hormone antagonists, sequela','Traumatismes, empoisonnements et autres causes externes','T38.906S'),
('Intoxication par other hormone antagonists, accidental (unintentional), initial encounter','Poisoning by other hormone antagonists, accidental (unintentional), initial encounter','Traumatismes, empoisonnements et autres causes externes','T38.991A'),
('Intoxication par other hormone antagonists, accidental (unintentional), subsequent encounter','Poisoning by other hormone antagonists, accidental (unintentional), subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T38.991D'),
('Intoxication par other hormone antagonists, accidental (unintentional), sequela','Poisoning by other hormone antagonists, accidental (unintentional), sequela','Traumatismes, empoisonnements et autres causes externes','T38.991S'),
('Intoxication par other hormone antagonists, intentional self-harm, initial encounter','Poisoning by other hormone antagonists, intentional self-harm, initial encounter','Traumatismes, empoisonnements et autres causes externes','T38.992A'),
('Intoxication par other hormone antagonists, intentional self-harm, subsequent encounter','Poisoning by other hormone antagonists, intentional self-harm, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T38.992D'),
('Intoxication par other hormone antagonists, intentional self-harm, sequela','Poisoning by other hormone antagonists, intentional self-harm, sequela','Traumatismes, empoisonnements et autres causes externes','T38.992S'),
('Intoxication par other hormone antagonists, assault, initial encounter','Poisoning by other hormone antagonists, assault, initial encounter','Traumatismes, empoisonnements et autres causes externes','T38.993A'),
('Intoxication par other hormone antagonists, assault, subsequent encounter','Poisoning by other hormone antagonists, assault, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T38.993D'),
('Intoxication par other hormone antagonists, assault, sequela','Poisoning by other hormone antagonists, assault, sequela','Traumatismes, empoisonnements et autres causes externes','T38.993S'),
('Intoxication par other hormone antagonists, undetermined, initial encounter','Poisoning by other hormone antagonists, undetermined, initial encounter','Traumatismes, empoisonnements et autres causes externes','T38.994A'),
('Intoxication par other hormone antagonists, undetermined, subsequent encounter','Poisoning by other hormone antagonists, undetermined, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T38.994D'),
('Intoxication par other hormone antagonists, undetermined, sequela','Poisoning by other hormone antagonists, undetermined, sequela','Traumatismes, empoisonnements et autres causes externes','T38.994S'),
('Effet indésirable de other hormone antagonists, initial encounter','Adverse effect of other hormone antagonists, initial encounter','Traumatismes, empoisonnements et autres causes externes','T38.995A'),
('Effet indésirable de other hormone antagonists, subsequent encounter','Adverse effect of other hormone antagonists, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T38.995D'),
('Effet indésirable de other hormone antagonists, sequela','Adverse effect of other hormone antagonists, sequela','Traumatismes, empoisonnements et autres causes externes','T38.995S'),
('Underdosing of autre hormone antagonists, initial encounter','Underdosing of other hormone antagonists, initial encounter','Traumatismes, empoisonnements et autres causes externes','T38.996A'),
('Underdosing of autre hormone antagonists, subsequent encounter','Underdosing of other hormone antagonists, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T38.996D'),
('Underdosing of autre hormone antagonists, sequela','Underdosing of other hormone antagonists, sequela','Traumatismes, empoisonnements et autres causes externes','T38.996S'),
('Intoxication par aspirin, accidental (unintentional), initial encounter','Poisoning by aspirin, accidental (unintentional), initial encounter','Traumatismes, empoisonnements et autres causes externes','T39.011A'),
('Intoxication par aspirin, accidental (unintentional), subsequent encounter','Poisoning by aspirin, accidental (unintentional), subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T39.011D'),
('Intoxication par aspirin, accidental (unintentional), sequela','Poisoning by aspirin, accidental (unintentional), sequela','Traumatismes, empoisonnements et autres causes externes','T39.011S'),
('Intoxication par aspirin, intentional self-harm, initial encounter','Poisoning by aspirin, intentional self-harm, initial encounter','Traumatismes, empoisonnements et autres causes externes','T39.012A'),
('Intoxication par aspirin, intentional self-harm, subsequent encounter','Poisoning by aspirin, intentional self-harm, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T39.012D'),
('Intoxication par aspirin, intentional self-harm, sequela','Poisoning by aspirin, intentional self-harm, sequela','Traumatismes, empoisonnements et autres causes externes','T39.012S'),
('Intoxication par aspirin, assault, initial encounter','Poisoning by aspirin, assault, initial encounter','Traumatismes, empoisonnements et autres causes externes','T39.013A'),
('Intoxication par aspirin, assault, subsequent encounter','Poisoning by aspirin, assault, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T39.013D'),
('Intoxication par aspirin, assault, sequela','Poisoning by aspirin, assault, sequela','Traumatismes, empoisonnements et autres causes externes','T39.013S'),
('Intoxication par aspirin, undetermined, initial encounter','Poisoning by aspirin, undetermined, initial encounter','Traumatismes, empoisonnements et autres causes externes','T39.014A'),
('Intoxication par aspirin, undetermined, subsequent encounter','Poisoning by aspirin, undetermined, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T39.014D'),
('Intoxication par aspirin, undetermined, sequela','Poisoning by aspirin, undetermined, sequela','Traumatismes, empoisonnements et autres causes externes','T39.014S'),
('Effet indésirable de aspirin, initial encounter','Adverse effect of aspirin, initial encounter','Traumatismes, empoisonnements et autres causes externes','T39.015A'),
('Effet indésirable de aspirin, subsequent encounter','Adverse effect of aspirin, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T39.015D'),
('Effet indésirable de aspirin, sequela','Adverse effect of aspirin, sequela','Traumatismes, empoisonnements et autres causes externes','T39.015S'),
('Underdosing of aspirin, initial encounter','Underdosing of aspirin, initial encounter','Traumatismes, empoisonnements et autres causes externes','T39.016A'),
('Underdosing of aspirin, subsequent encounter','Underdosing of aspirin, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T39.016D'),
('Underdosing of aspirin, sequela','Underdosing of aspirin, sequela','Traumatismes, empoisonnements et autres causes externes','T39.016S'),
('Intoxication par salicylates, accidental (unintentional), initial encounter','Poisoning by salicylates, accidental (unintentional), initial encounter','Traumatismes, empoisonnements et autres causes externes','T39.091A'),
('Intoxication par salicylates, accidental (unintentional), subsequent encounter','Poisoning by salicylates, accidental (unintentional), subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T39.091D'),
('Intoxication par salicylates, accidental (unintentional), sequela','Poisoning by salicylates, accidental (unintentional), sequela','Traumatismes, empoisonnements et autres causes externes','T39.091S'),
('Intoxication par salicylates, intentional self-harm, initial encounter','Poisoning by salicylates, intentional self-harm, initial encounter','Traumatismes, empoisonnements et autres causes externes','T39.092A'),
('Intoxication par salicylates, intentional self-harm, subsequent encounter','Poisoning by salicylates, intentional self-harm, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T39.092D'),
('Intoxication par salicylates, intentional self-harm, sequela','Poisoning by salicylates, intentional self-harm, sequela','Traumatismes, empoisonnements et autres causes externes','T39.092S'),
('Intoxication par salicylates, assault, initial encounter','Poisoning by salicylates, assault, initial encounter','Traumatismes, empoisonnements et autres causes externes','T39.093A'),
('Intoxication par salicylates, assault, subsequent encounter','Poisoning by salicylates, assault, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T39.093D'),
('Intoxication par salicylates, assault, sequela','Poisoning by salicylates, assault, sequela','Traumatismes, empoisonnements et autres causes externes','T39.093S'),
('Intoxication par salicylates, undetermined, initial encounter','Poisoning by salicylates, undetermined, initial encounter','Traumatismes, empoisonnements et autres causes externes','T39.094A'),
('Intoxication par salicylates, undetermined, subsequent encounter','Poisoning by salicylates, undetermined, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T39.094D'),
('Intoxication par salicylates, undetermined, sequela','Poisoning by salicylates, undetermined, sequela','Traumatismes, empoisonnements et autres causes externes','T39.094S'),
('Effet indésirable de salicylates, initial encounter','Adverse effect of salicylates, initial encounter','Traumatismes, empoisonnements et autres causes externes','T39.095A'),
('Effet indésirable de salicylates, subsequent encounter','Adverse effect of salicylates, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T39.095D'),
('Effet indésirable de salicylates, sequela','Adverse effect of salicylates, sequela','Traumatismes, empoisonnements et autres causes externes','T39.095S'),
('Underdosing of salicylates, initial encounter','Underdosing of salicylates, initial encounter','Traumatismes, empoisonnements et autres causes externes','T39.096A'),
('Underdosing of salicylates, subsequent encounter','Underdosing of salicylates, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','T39.096D'),
('Underdosing of salicylates, sequela','Underdosing of salicylates, sequela','Traumatismes, empoisonnements et autres causes externes','T39.096S'),
('Intoxication par 4-Aminophenol derivatives, accidental (unintentional), initial encounter','Poisoning by 4-Aminophenol derivatives, accidental (unintentional), initial encounter','Traumatismes, empoisonnements et autres causes externes','T39.1X1A')
ON CONFLICT (nom_fr) DO NOTHING;
