-- icd10v2_batch_034.sql (80 rows)
INSERT INTO pathologies (nom_fr, nom_en, categorie, icd10_code)
VALUES
('Carcinome in situ of endometrium','Carcinoma in situ of endometrium','Tumeurs bénignes et in situ','D07.0'),
('Carcinome in situ of vulva','Carcinoma in situ of vulva','Tumeurs bénignes et in situ','D07.1'),
('Carcinome in situ of vagina','Carcinoma in situ of vagina','Tumeurs bénignes et in situ','D07.2'),
('Carcinome in situ of unspecified female genital organs','Carcinoma in situ of unspecified female genital organs','Tumeurs bénignes et in situ','D07.30'),
('Carcinome in situ of other female genital organs','Carcinoma in situ of other female genital organs','Tumeurs bénignes et in situ','D07.39'),
('Carcinome in situ of penis','Carcinoma in situ of penis','Tumeurs bénignes et in situ','D07.4'),
('Carcinome in situ of prostate','Carcinoma in situ of prostate','Tumeurs bénignes et in situ','D07.5'),
('Carcinome in situ of unspecified male genital organs','Carcinoma in situ of unspecified male genital organs','Tumeurs bénignes et in situ','D07.60'),
('Carcinome in situ of scrotum','Carcinoma in situ of scrotum','Tumeurs bénignes et in situ','D07.61'),
('Carcinome in situ of other male genital organs','Carcinoma in situ of other male genital organs','Tumeurs bénignes et in situ','D07.69'),
('Carcinome in situ of bladder','Carcinoma in situ of bladder','Tumeurs bénignes et in situ','D09.0'),
('Carcinome in situ of unspecified urinary organ','Carcinoma in situ of unspecified urinary organ','Tumeurs bénignes et in situ','D09.10'),
('Carcinome in situ of other urinary organs','Carcinoma in situ of other urinary organs','Tumeurs bénignes et in situ','D09.19'),
('Carcinome in situ of unspecified eye','Carcinoma in situ of unspecified eye','Tumeurs bénignes et in situ','D09.20'),
('Carcinome in situ of right eye','Carcinoma in situ of right eye','Tumeurs bénignes et in situ','D09.21'),
('Carcinome in situ of left eye','Carcinoma in situ of left eye','Tumeurs bénignes et in situ','D09.22'),
('Carcinome in situ of thyroid and other endocrine glands','Carcinoma in situ of thyroid and other endocrine glands','Tumeurs bénignes et in situ','D09.3'),
('Carcinome in situ of other specified sites','Carcinoma in situ of other specified sites','Tumeurs bénignes et in situ','D09.8'),
('Carcinome in situ, unspecified','Carcinoma in situ, unspecified','Tumeurs bénignes et in situ','D09.9'),
('Hereditary vitamin D-dependent rickets (type 1) (type 2)','Hereditary vitamin D-dependent rickets (type 1) (type 2)','Maladies endocriniennes, nutritionnelles et métaboliques','E83.32'),
('Maternal care for anti-D [Rh] antibodies, first trimester, fetus 1','Maternal care for anti-D [Rh] antibodies, first trimester, fetus 1','Grossesse, accouchement et puerpéralité','O36.0111'),
('Maternal care for anti-D [Rh] antibodies, second trimester, fetus 1','Maternal care for anti-D [Rh] antibodies, second trimester, fetus 1','Grossesse, accouchement et puerpéralité','O36.0121'),
('Maternal care for anti-D [Rh] antibodies, third trimester, fetus 1','Maternal care for anti-D [Rh] antibodies, third trimester, fetus 1','Grossesse, accouchement et puerpéralité','O36.0131'),
('Maternal care for anti-D [Rh] antibodies, non spécifié trimester, fetus 1','Maternal care for anti-D [Rh] antibodies, unspecified trimester, fetus 1','Grossesse, accouchement et puerpéralité','O36.0191'),
('Tumeur bénigne de lip','Benign neoplasm of lip','Tumeurs bénignes et in situ','D10.0'),
('Tumeur bénigne de tongue','Benign neoplasm of tongue','Tumeurs bénignes et in situ','D10.1'),
('Tumeur bénigne de floor of mouth','Benign neoplasm of floor of mouth','Tumeurs bénignes et in situ','D10.2'),
('Tumeur bénigne de unspecified part of mouth','Benign neoplasm of unspecified part of mouth','Tumeurs bénignes et in situ','D10.30'),
('Tumeur bénigne de other parts of mouth','Benign neoplasm of other parts of mouth','Tumeurs bénignes et in situ','D10.39'),
('Tumeur bénigne de tonsil','Benign neoplasm of tonsil','Tumeurs bénignes et in situ','D10.4'),
('Tumeur bénigne de other parts of oropharynx','Benign neoplasm of other parts of oropharynx','Tumeurs bénignes et in situ','D10.5'),
('Tumeur bénigne de nasopharynx','Benign neoplasm of nasopharynx','Tumeurs bénignes et in situ','D10.6'),
('Tumeur bénigne de hypopharynx','Benign neoplasm of hypopharynx','Tumeurs bénignes et in situ','D10.7'),
('Tumeur bénigne de pharynx, unspecified','Benign neoplasm of pharynx, unspecified','Tumeurs bénignes et in situ','D10.9'),
('Tumeur bénigne de parotid gland','Benign neoplasm of parotid gland','Tumeurs bénignes et in situ','D11.0'),
('Tumeur bénigne de other major salivary glands','Benign neoplasm of other major salivary glands','Tumeurs bénignes et in situ','D11.7'),
('Tumeur bénigne de major salivary gland, unspecified','Benign neoplasm of major salivary gland, unspecified','Tumeurs bénignes et in situ','D11.9'),
('Tumeur bénigne de cecum','Benign neoplasm of cecum','Tumeurs bénignes et in situ','D12.0'),
('Tumeur bénigne de appendix','Benign neoplasm of appendix','Tumeurs bénignes et in situ','D12.1'),
('Tumeur bénigne de ascending colon','Benign neoplasm of ascending colon','Tumeurs bénignes et in situ','D12.2'),
('Tumeur bénigne de transverse colon','Benign neoplasm of transverse colon','Tumeurs bénignes et in situ','D12.3'),
('Tumeur bénigne de descending colon','Benign neoplasm of descending colon','Tumeurs bénignes et in situ','D12.4'),
('Tumeur bénigne de sigmoid colon','Benign neoplasm of sigmoid colon','Tumeurs bénignes et in situ','D12.5'),
('Tumeur bénigne de colon, unspecified','Benign neoplasm of colon, unspecified','Tumeurs bénignes et in situ','D12.6'),
('Tumeur bénigne de rectosigmoid junction','Benign neoplasm of rectosigmoid junction','Tumeurs bénignes et in situ','D12.7'),
('Tumeur bénigne de rectum','Benign neoplasm of rectum','Tumeurs bénignes et in situ','D12.8'),
('Tumeur bénigne de anus and anal canal','Benign neoplasm of anus and anal canal','Tumeurs bénignes et in situ','D12.9'),
('Tumeur bénigne de esophagus','Benign neoplasm of esophagus','Tumeurs bénignes et in situ','D13.0'),
('Tumeur bénigne de stomach','Benign neoplasm of stomach','Tumeurs bénignes et in situ','D13.1'),
('Tumeur bénigne de duodenum','Benign neoplasm of duodenum','Tumeurs bénignes et in situ','D13.2'),
('Tumeur bénigne de unspecified part of small intestine','Benign neoplasm of unspecified part of small intestine','Tumeurs bénignes et in situ','D13.30'),
('Tumeur bénigne de other parts of small intestine','Benign neoplasm of other parts of small intestine','Tumeurs bénignes et in situ','D13.39'),
('Tumeur bénigne de liver','Benign neoplasm of liver','Tumeurs bénignes et in situ','D13.4'),
('Tumeur bénigne de extrahepatic bile ducts','Benign neoplasm of extrahepatic bile ducts','Tumeurs bénignes et in situ','D13.5'),
('Tumeur bénigne de pancreas','Benign neoplasm of pancreas','Tumeurs bénignes et in situ','D13.6'),
('Tumeur bénigne de endocrine pancreas','Benign neoplasm of endocrine pancreas','Tumeurs bénignes et in situ','D13.7'),
('Familial adenomatous polyposis','Familial adenomatous polyposis','Tumeurs bénignes et in situ','D13.91'),
('Tumeur bénigne de ill-defined sites within the digestive system','Benign neoplasm of ill-defined sites within the digestive system','Tumeurs bénignes et in situ','D13.99'),
('Tumeur bénigne de middle ear, nasal cavity and accessory sinuses','Benign neoplasm of middle ear, nasal cavity and accessory sinuses','Tumeurs bénignes et in situ','D14.0'),
('Tumeur bénigne de larynx','Benign neoplasm of larynx','Tumeurs bénignes et in situ','D14.1'),
('Tumeur bénigne de trachea','Benign neoplasm of trachea','Tumeurs bénignes et in situ','D14.2'),
('Tumeur bénigne de unspecified bronchus and lung','Benign neoplasm of unspecified bronchus and lung','Tumeurs bénignes et in situ','D14.30'),
('Tumeur bénigne de right bronchus and lung','Benign neoplasm of right bronchus and lung','Tumeurs bénignes et in situ','D14.31'),
('Tumeur bénigne de left bronchus and lung','Benign neoplasm of left bronchus and lung','Tumeurs bénignes et in situ','D14.32'),
('Tumeur bénigne de respiratory system, unspecified','Benign neoplasm of respiratory system, unspecified','Tumeurs bénignes et in situ','D14.4'),
('Tumeur bénigne de thymus','Benign neoplasm of thymus','Tumeurs bénignes et in situ','D15.0'),
('Tumeur bénigne de heart','Benign neoplasm of heart','Tumeurs bénignes et in situ','D15.1'),
('Tumeur bénigne de mediastinum','Benign neoplasm of mediastinum','Tumeurs bénignes et in situ','D15.2'),
('Tumeur bénigne de other specified intrathoracic organs','Benign neoplasm of other specified intrathoracic organs','Tumeurs bénignes et in situ','D15.7'),
('Tumeur bénigne de intrathoracic organ, unspecified','Benign neoplasm of intrathoracic organ, unspecified','Tumeurs bénignes et in situ','D15.9'),
('Tumeur bénigne de scapula and long bones of unspecified upper limb','Benign neoplasm of scapula and long bones of unspecified upper limb','Tumeurs bénignes et in situ','D16.00'),
('Tumeur bénigne de scapula and long bones of right upper limb','Benign neoplasm of scapula and long bones of right upper limb','Tumeurs bénignes et in situ','D16.01'),
('Tumeur bénigne de scapula and long bones of left upper limb','Benign neoplasm of scapula and long bones of left upper limb','Tumeurs bénignes et in situ','D16.02'),
('Tumeur bénigne de short bones of unspecified upper limb','Benign neoplasm of short bones of unspecified upper limb','Tumeurs bénignes et in situ','D16.10'),
('Tumeur bénigne de short bones of right upper limb','Benign neoplasm of short bones of right upper limb','Tumeurs bénignes et in situ','D16.11'),
('Tumeur bénigne de short bones of left upper limb','Benign neoplasm of short bones of left upper limb','Tumeurs bénignes et in situ','D16.12'),
('Tumeur bénigne de long bones of unspecified lower limb','Benign neoplasm of long bones of unspecified lower limb','Tumeurs bénignes et in situ','D16.20'),
('Tumeur bénigne de long bones of right lower limb','Benign neoplasm of long bones of right lower limb','Tumeurs bénignes et in situ','D16.21'),
('Tumeur bénigne de long bones of left lower limb','Benign neoplasm of long bones of left lower limb','Tumeurs bénignes et in situ','D16.22'),
('Tumeur bénigne de short bones of unspecified lower limb','Benign neoplasm of short bones of unspecified lower limb','Tumeurs bénignes et in situ','D16.30')
ON CONFLICT (nom_fr) DO NOTHING;
