-- icd10v2_batch_535.sql (80 rows)
INSERT INTO pathologies (nom_fr, nom_en, categorie, icd10_code)
VALUES
('Contusion of bladder, sequela','Contusion of bladder, sequela','Traumatismes, empoisonnements et autres causes externes','S37.22XS'),
('Laceration of bladder, initial encounter','Laceration of bladder, initial encounter','Traumatismes, empoisonnements et autres causes externes','S37.23XA'),
('Laceration of bladder, subsequent encounter','Laceration of bladder, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S37.23XD'),
('Laceration of bladder, sequela','Laceration of bladder, sequela','Traumatismes, empoisonnements et autres causes externes','S37.23XS'),
('autre injury of bladder, initial encounter','Other injury of bladder, initial encounter','Traumatismes, empoisonnements et autres causes externes','S37.29XA'),
('autre injury of bladder, subsequent encounter','Other injury of bladder, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S37.29XD'),
('autre injury of bladder, sequela','Other injury of bladder, sequela','Traumatismes, empoisonnements et autres causes externes','S37.29XS'),
('non spécifié injury of urethra, initial encounter','Unspecified injury of urethra, initial encounter','Traumatismes, empoisonnements et autres causes externes','S37.30XA'),
('non spécifié injury of urethra, subsequent encounter','Unspecified injury of urethra, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S37.30XD'),
('non spécifié injury of urethra, sequela','Unspecified injury of urethra, sequela','Traumatismes, empoisonnements et autres causes externes','S37.30XS'),
('Contusion of urethra, initial encounter','Contusion of urethra, initial encounter','Traumatismes, empoisonnements et autres causes externes','S37.32XA'),
('Contusion of urethra, subsequent encounter','Contusion of urethra, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S37.32XD'),
('Contusion of urethra, sequela','Contusion of urethra, sequela','Traumatismes, empoisonnements et autres causes externes','S37.32XS'),
('Laceration of urethra, initial encounter','Laceration of urethra, initial encounter','Traumatismes, empoisonnements et autres causes externes','S37.33XA'),
('Laceration of urethra, subsequent encounter','Laceration of urethra, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S37.33XD'),
('Laceration of urethra, sequela','Laceration of urethra, sequela','Traumatismes, empoisonnements et autres causes externes','S37.33XS'),
('autre injury of urethra, initial encounter','Other injury of urethra, initial encounter','Traumatismes, empoisonnements et autres causes externes','S37.39XA'),
('autre injury of urethra, subsequent encounter','Other injury of urethra, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S37.39XD'),
('autre injury of urethra, sequela','Other injury of urethra, sequela','Traumatismes, empoisonnements et autres causes externes','S37.39XS'),
('non spécifié injury of ovary, unilateral, initial encounter','Unspecified injury of ovary, unilateral, initial encounter','Traumatismes, empoisonnements et autres causes externes','S37.401A'),
('non spécifié injury of ovary, unilateral, subsequent encounter','Unspecified injury of ovary, unilateral, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S37.401D'),
('non spécifié injury of ovary, unilateral, sequela','Unspecified injury of ovary, unilateral, sequela','Traumatismes, empoisonnements et autres causes externes','S37.401S'),
('non spécifié injury of ovary, bilateral, initial encounter','Unspecified injury of ovary, bilateral, initial encounter','Traumatismes, empoisonnements et autres causes externes','S37.402A'),
('non spécifié injury of ovary, bilateral, subsequent encounter','Unspecified injury of ovary, bilateral, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S37.402D'),
('non spécifié injury of ovary, bilateral, sequela','Unspecified injury of ovary, bilateral, sequela','Traumatismes, empoisonnements et autres causes externes','S37.402S'),
('non spécifié injury of ovary, non spécifié, initial encounter','Unspecified injury of ovary, unspecified, initial encounter','Traumatismes, empoisonnements et autres causes externes','S37.409A'),
('non spécifié injury of ovary, non spécifié, subsequent encounter','Unspecified injury of ovary, unspecified, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S37.409D'),
('non spécifié injury of ovary, non spécifié, sequela','Unspecified injury of ovary, unspecified, sequela','Traumatismes, empoisonnements et autres causes externes','S37.409S'),
('Contusion of ovary, unilateral, initial encounter','Contusion of ovary, unilateral, initial encounter','Traumatismes, empoisonnements et autres causes externes','S37.421A'),
('Contusion of ovary, unilateral, subsequent encounter','Contusion of ovary, unilateral, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S37.421D'),
('Contusion of ovary, unilateral, sequela','Contusion of ovary, unilateral, sequela','Traumatismes, empoisonnements et autres causes externes','S37.421S'),
('Contusion of ovary, bilateral, initial encounter','Contusion of ovary, bilateral, initial encounter','Traumatismes, empoisonnements et autres causes externes','S37.422A'),
('Contusion of ovary, bilateral, subsequent encounter','Contusion of ovary, bilateral, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S37.422D'),
('Contusion of ovary, bilateral, sequela','Contusion of ovary, bilateral, sequela','Traumatismes, empoisonnements et autres causes externes','S37.422S'),
('Contusion of ovary, non spécifié, initial encounter','Contusion of ovary, unspecified, initial encounter','Traumatismes, empoisonnements et autres causes externes','S37.429A'),
('Contusion of ovary, non spécifié, subsequent encounter','Contusion of ovary, unspecified, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S37.429D'),
('Contusion of ovary, non spécifié, sequela','Contusion of ovary, unspecified, sequela','Traumatismes, empoisonnements et autres causes externes','S37.429S'),
('Laceration of ovary, unilateral, initial encounter','Laceration of ovary, unilateral, initial encounter','Traumatismes, empoisonnements et autres causes externes','S37.431A'),
('Laceration of ovary, unilateral, subsequent encounter','Laceration of ovary, unilateral, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S37.431D'),
('Laceration of ovary, unilateral, sequela','Laceration of ovary, unilateral, sequela','Traumatismes, empoisonnements et autres causes externes','S37.431S'),
('Laceration of ovary, bilateral, initial encounter','Laceration of ovary, bilateral, initial encounter','Traumatismes, empoisonnements et autres causes externes','S37.432A'),
('Laceration of ovary, bilateral, subsequent encounter','Laceration of ovary, bilateral, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S37.432D'),
('Laceration of ovary, bilateral, sequela','Laceration of ovary, bilateral, sequela','Traumatismes, empoisonnements et autres causes externes','S37.432S'),
('Laceration of ovary, non spécifié, initial encounter','Laceration of ovary, unspecified, initial encounter','Traumatismes, empoisonnements et autres causes externes','S37.439A'),
('Laceration of ovary, non spécifié, subsequent encounter','Laceration of ovary, unspecified, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S37.439D'),
('Laceration of ovary, non spécifié, sequela','Laceration of ovary, unspecified, sequela','Traumatismes, empoisonnements et autres causes externes','S37.439S'),
('autre injury of ovary, unilateral, initial encounter','Other injury of ovary, unilateral, initial encounter','Traumatismes, empoisonnements et autres causes externes','S37.491A'),
('autre injury of ovary, unilateral, subsequent encounter','Other injury of ovary, unilateral, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S37.491D'),
('autre injury of ovary, unilateral, sequela','Other injury of ovary, unilateral, sequela','Traumatismes, empoisonnements et autres causes externes','S37.491S'),
('autre injury of ovary, bilateral, initial encounter','Other injury of ovary, bilateral, initial encounter','Traumatismes, empoisonnements et autres causes externes','S37.492A'),
('autre injury of ovary, bilateral, subsequent encounter','Other injury of ovary, bilateral, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S37.492D'),
('autre injury of ovary, bilateral, sequela','Other injury of ovary, bilateral, sequela','Traumatismes, empoisonnements et autres causes externes','S37.492S'),
('autre injury of ovary, non spécifié, initial encounter','Other injury of ovary, unspecified, initial encounter','Traumatismes, empoisonnements et autres causes externes','S37.499A'),
('autre injury of ovary, non spécifié, subsequent encounter','Other injury of ovary, unspecified, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S37.499D'),
('autre injury of ovary, non spécifié, sequela','Other injury of ovary, unspecified, sequela','Traumatismes, empoisonnements et autres causes externes','S37.499S'),
('non spécifié injury of fallopian tube, unilateral, initial encounter','Unspecified injury of fallopian tube, unilateral, initial encounter','Traumatismes, empoisonnements et autres causes externes','S37.501A'),
('non spécifié injury of fallopian tube, unilateral, subsequent encounter','Unspecified injury of fallopian tube, unilateral, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S37.501D'),
('non spécifié injury of fallopian tube, unilateral, sequela','Unspecified injury of fallopian tube, unilateral, sequela','Traumatismes, empoisonnements et autres causes externes','S37.501S'),
('non spécifié injury of fallopian tube, bilateral, initial encounter','Unspecified injury of fallopian tube, bilateral, initial encounter','Traumatismes, empoisonnements et autres causes externes','S37.502A'),
('non spécifié injury of fallopian tube, bilateral, subsequent encounter','Unspecified injury of fallopian tube, bilateral, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S37.502D'),
('non spécifié injury of fallopian tube, bilateral, sequela','Unspecified injury of fallopian tube, bilateral, sequela','Traumatismes, empoisonnements et autres causes externes','S37.502S'),
('non spécifié injury of fallopian tube, non spécifié, initial encounter','Unspecified injury of fallopian tube, unspecified, initial encounter','Traumatismes, empoisonnements et autres causes externes','S37.509A'),
('non spécifié injury of fallopian tube, non spécifié, subsequent encounter','Unspecified injury of fallopian tube, unspecified, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S37.509D'),
('non spécifié injury of fallopian tube, non spécifié, sequela','Unspecified injury of fallopian tube, unspecified, sequela','Traumatismes, empoisonnements et autres causes externes','S37.509S'),
('primitif blast injury of fallopian tube, unilateral, initial encounter','Primary blast injury of fallopian tube, unilateral, initial encounter','Traumatismes, empoisonnements et autres causes externes','S37.511A'),
('primitif blast injury of fallopian tube, unilateral, subsequent encounter','Primary blast injury of fallopian tube, unilateral, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S37.511D'),
('primitif blast injury of fallopian tube, unilateral, sequela','Primary blast injury of fallopian tube, unilateral, sequela','Traumatismes, empoisonnements et autres causes externes','S37.511S'),
('primitif blast injury of fallopian tube, bilateral, initial encounter','Primary blast injury of fallopian tube, bilateral, initial encounter','Traumatismes, empoisonnements et autres causes externes','S37.512A'),
('primitif blast injury of fallopian tube, bilateral, subsequent encounter','Primary blast injury of fallopian tube, bilateral, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S37.512D'),
('primitif blast injury of fallopian tube, bilateral, sequela','Primary blast injury of fallopian tube, bilateral, sequela','Traumatismes, empoisonnements et autres causes externes','S37.512S'),
('primitif blast injury of fallopian tube, non spécifié, initial encounter','Primary blast injury of fallopian tube, unspecified, initial encounter','Traumatismes, empoisonnements et autres causes externes','S37.519A'),
('primitif blast injury of fallopian tube, non spécifié, subsequent encounter','Primary blast injury of fallopian tube, unspecified, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S37.519D'),
('primitif blast injury of fallopian tube, non spécifié, sequela','Primary blast injury of fallopian tube, unspecified, sequela','Traumatismes, empoisonnements et autres causes externes','S37.519S'),
('Contusion of fallopian tube, unilateral, initial encounter','Contusion of fallopian tube, unilateral, initial encounter','Traumatismes, empoisonnements et autres causes externes','S37.521A'),
('Contusion of fallopian tube, unilateral, subsequent encounter','Contusion of fallopian tube, unilateral, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S37.521D'),
('Contusion of fallopian tube, unilateral, sequela','Contusion of fallopian tube, unilateral, sequela','Traumatismes, empoisonnements et autres causes externes','S37.521S'),
('Contusion of fallopian tube, bilateral, initial encounter','Contusion of fallopian tube, bilateral, initial encounter','Traumatismes, empoisonnements et autres causes externes','S37.522A'),
('Contusion of fallopian tube, bilateral, subsequent encounter','Contusion of fallopian tube, bilateral, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S37.522D'),
('Contusion of fallopian tube, bilateral, sequela','Contusion of fallopian tube, bilateral, sequela','Traumatismes, empoisonnements et autres causes externes','S37.522S'),
('Contusion of fallopian tube, non spécifié, initial encounter','Contusion of fallopian tube, unspecified, initial encounter','Traumatismes, empoisonnements et autres causes externes','S37.529A')
ON CONFLICT (nom_fr) DO NOTHING;
