-- icd10v2_batch_454.sql (80 rows)
INSERT INTO pathologies (nom_fr, nom_en, categorie, icd10_code)
VALUES
('autre drowning and submersion, undetermined intent, subsequent encounter','Other drowning and submersion, undetermined intent, subsequent encounter','Causes externes de morbidité et de mortalité','Y21.8XXD'),
('autre drowning and submersion, undetermined intent, sequela','Other drowning and submersion, undetermined intent, sequela','Causes externes de morbidité et de mortalité','Y21.8XXS'),
('non spécifié drowning and submersion, undetermined intent, initial encounter','Unspecified drowning and submersion, undetermined intent, initial encounter','Causes externes de morbidité et de mortalité','Y21.9XXA'),
('non spécifié drowning and submersion, undetermined intent, subsequent encounter','Unspecified drowning and submersion, undetermined intent, subsequent encounter','Causes externes de morbidité et de mortalité','Y21.9XXD'),
('non spécifié drowning and submersion, undetermined intent, sequela','Unspecified drowning and submersion, undetermined intent, sequela','Causes externes de morbidité et de mortalité','Y21.9XXS'),
('Handgun discharge, undetermined intent, initial encounter','Handgun discharge, undetermined intent, initial encounter','Causes externes de morbidité et de mortalité','Y22.XXXA'),
('Handgun discharge, undetermined intent, subsequent encounter','Handgun discharge, undetermined intent, subsequent encounter','Causes externes de morbidité et de mortalité','Y22.XXXD'),
('Handgun discharge, undetermined intent, sequela','Handgun discharge, undetermined intent, sequela','Causes externes de morbidité et de mortalité','Y22.XXXS'),
('Shotgun discharge, undetermined intent, initial encounter','Shotgun discharge, undetermined intent, initial encounter','Causes externes de morbidité et de mortalité','Y23.0XXA'),
('Shotgun discharge, undetermined intent, subsequent encounter','Shotgun discharge, undetermined intent, subsequent encounter','Causes externes de morbidité et de mortalité','Y23.0XXD'),
('Shotgun discharge, undetermined intent, sequela','Shotgun discharge, undetermined intent, sequela','Causes externes de morbidité et de mortalité','Y23.0XXS'),
('Hunting rifle discharge, undetermined intent, initial encounter','Hunting rifle discharge, undetermined intent, initial encounter','Causes externes de morbidité et de mortalité','Y23.1XXA'),
('Hunting rifle discharge, undetermined intent, subsequent encounter','Hunting rifle discharge, undetermined intent, subsequent encounter','Causes externes de morbidité et de mortalité','Y23.1XXD'),
('Hunting rifle discharge, undetermined intent, sequela','Hunting rifle discharge, undetermined intent, sequela','Causes externes de morbidité et de mortalité','Y23.1XXS'),
('Military firearm discharge, undetermined intent, initial encounter','Military firearm discharge, undetermined intent, initial encounter','Causes externes de morbidité et de mortalité','Y23.2XXA'),
('Military firearm discharge, undetermined intent, subsequent encounter','Military firearm discharge, undetermined intent, subsequent encounter','Causes externes de morbidité et de mortalité','Y23.2XXD'),
('Military firearm discharge, undetermined intent, sequela','Military firearm discharge, undetermined intent, sequela','Causes externes de morbidité et de mortalité','Y23.2XXS'),
('Machine gun discharge, undetermined intent, initial encounter','Machine gun discharge, undetermined intent, initial encounter','Causes externes de morbidité et de mortalité','Y23.3XXA'),
('Machine gun discharge, undetermined intent, subsequent encounter','Machine gun discharge, undetermined intent, subsequent encounter','Causes externes de morbidité et de mortalité','Y23.3XXD'),
('Machine gun discharge, undetermined intent, sequela','Machine gun discharge, undetermined intent, sequela','Causes externes de morbidité et de mortalité','Y23.3XXS'),
('autre larger firearm discharge, undetermined intent, initial encounter','Other larger firearm discharge, undetermined intent, initial encounter','Causes externes de morbidité et de mortalité','Y23.8XXA'),
('autre larger firearm discharge, undetermined intent, subsequent encounter','Other larger firearm discharge, undetermined intent, subsequent encounter','Causes externes de morbidité et de mortalité','Y23.8XXD'),
('autre larger firearm discharge, undetermined intent, sequela','Other larger firearm discharge, undetermined intent, sequela','Causes externes de morbidité et de mortalité','Y23.8XXS'),
('non spécifié larger firearm discharge, undetermined intent, initial encounter','Unspecified larger firearm discharge, undetermined intent, initial encounter','Causes externes de morbidité et de mortalité','Y23.9XXA'),
('non spécifié larger firearm discharge, undetermined intent, subsequent encounter','Unspecified larger firearm discharge, undetermined intent, subsequent encounter','Causes externes de morbidité et de mortalité','Y23.9XXD'),
('non spécifié larger firearm discharge, undetermined intent, sequela','Unspecified larger firearm discharge, undetermined intent, sequela','Causes externes de morbidité et de mortalité','Y23.9XXS'),
('Airgun discharge, undetermined intent, initial encounter','Airgun discharge, undetermined intent, initial encounter','Causes externes de morbidité et de mortalité','Y24.0XXA'),
('Airgun discharge, undetermined intent, subsequent encounter','Airgun discharge, undetermined intent, subsequent encounter','Causes externes de morbidité et de mortalité','Y24.0XXD'),
('Airgun discharge, undetermined intent, sequela','Airgun discharge, undetermined intent, sequela','Causes externes de morbidité et de mortalité','Y24.0XXS'),
('autre firearm discharge, undetermined intent, initial encounter','Other firearm discharge, undetermined intent, initial encounter','Causes externes de morbidité et de mortalité','Y24.8XXA'),
('autre firearm discharge, undetermined intent, subsequent encounter','Other firearm discharge, undetermined intent, subsequent encounter','Causes externes de morbidité et de mortalité','Y24.8XXD'),
('autre firearm discharge, undetermined intent, sequela','Other firearm discharge, undetermined intent, sequela','Causes externes de morbidité et de mortalité','Y24.8XXS'),
('non spécifié firearm discharge, undetermined intent, initial encounter','Unspecified firearm discharge, undetermined intent, initial encounter','Causes externes de morbidité et de mortalité','Y24.9XXA'),
('non spécifié firearm discharge, undetermined intent, subsequent encounter','Unspecified firearm discharge, undetermined intent, subsequent encounter','Causes externes de morbidité et de mortalité','Y24.9XXD'),
('non spécifié firearm discharge, undetermined intent, sequela','Unspecified firearm discharge, undetermined intent, sequela','Causes externes de morbidité et de mortalité','Y24.9XXS'),
('Contact with explosive material, undetermined intent, initial encounter','Contact with explosive material, undetermined intent, initial encounter','Causes externes de morbidité et de mortalité','Y25.XXXA'),
('Contact with explosive material, undetermined intent, subsequent encounter','Contact with explosive material, undetermined intent, subsequent encounter','Causes externes de morbidité et de mortalité','Y25.XXXD'),
('Contact with explosive material, undetermined intent, sequela','Contact with explosive material, undetermined intent, sequela','Causes externes de morbidité et de mortalité','Y25.XXXS'),
('Exposure to smoke, fire and flames, undetermined intent, initial encounter','Exposure to smoke, fire and flames, undetermined intent, initial encounter','Causes externes de morbidité et de mortalité','Y26.XXXA'),
('Exposure to smoke, fire and flames, undetermined intent, subsequent encounter','Exposure to smoke, fire and flames, undetermined intent, subsequent encounter','Causes externes de morbidité et de mortalité','Y26.XXXD'),
('Exposure to smoke, fire and flames, undetermined intent, sequela','Exposure to smoke, fire and flames, undetermined intent, sequela','Causes externes de morbidité et de mortalité','Y26.XXXS'),
('Contact with steam and hot vapors, undetermined intent, initial encounter','Contact with steam and hot vapors, undetermined intent, initial encounter','Causes externes de morbidité et de mortalité','Y27.0XXA'),
('Contact with steam and hot vapors, undetermined intent, subsequent encounter','Contact with steam and hot vapors, undetermined intent, subsequent encounter','Causes externes de morbidité et de mortalité','Y27.0XXD'),
('Contact with steam and hot vapors, undetermined intent, sequela','Contact with steam and hot vapors, undetermined intent, sequela','Causes externes de morbidité et de mortalité','Y27.0XXS'),
('Contact with hot tap water, undetermined intent, initial encounter','Contact with hot tap water, undetermined intent, initial encounter','Causes externes de morbidité et de mortalité','Y27.1XXA'),
('Contact with hot tap water, undetermined intent, subsequent encounter','Contact with hot tap water, undetermined intent, subsequent encounter','Causes externes de morbidité et de mortalité','Y27.1XXD'),
('Contact with hot tap water, undetermined intent, sequela','Contact with hot tap water, undetermined intent, sequela','Causes externes de morbidité et de mortalité','Y27.1XXS'),
('Contact with hot fluids, undetermined intent, initial encounter','Contact with hot fluids, undetermined intent, initial encounter','Causes externes de morbidité et de mortalité','Y27.2XXA'),
('Contact with hot fluids, undetermined intent, subsequent encounter','Contact with hot fluids, undetermined intent, subsequent encounter','Causes externes de morbidité et de mortalité','Y27.2XXD'),
('Contact with hot fluids, undetermined intent, sequela','Contact with hot fluids, undetermined intent, sequela','Causes externes de morbidité et de mortalité','Y27.2XXS'),
('Contact with hot household appliance, undetermined intent, initial encounter','Contact with hot household appliance, undetermined intent, initial encounter','Causes externes de morbidité et de mortalité','Y27.3XXA'),
('Contact with hot household appliance, undetermined intent, subsequent encounter','Contact with hot household appliance, undetermined intent, subsequent encounter','Causes externes de morbidité et de mortalité','Y27.3XXD'),
('Contact with hot household appliance, undetermined intent, sequela','Contact with hot household appliance, undetermined intent, sequela','Causes externes de morbidité et de mortalité','Y27.3XXS'),
('Contact with autre hot objects, undetermined intent, initial encounter','Contact with other hot objects, undetermined intent, initial encounter','Causes externes de morbidité et de mortalité','Y27.8XXA'),
('Contact with autre hot objects, undetermined intent, subsequent encounter','Contact with other hot objects, undetermined intent, subsequent encounter','Causes externes de morbidité et de mortalité','Y27.8XXD'),
('Contact with autre hot objects, undetermined intent, sequela','Contact with other hot objects, undetermined intent, sequela','Causes externes de morbidité et de mortalité','Y27.8XXS'),
('Contact with non spécifié hot objects, undetermined intent, initial encounter','Contact with unspecified hot objects, undetermined intent, initial encounter','Causes externes de morbidité et de mortalité','Y27.9XXA'),
('Contact with non spécifié hot objects, undetermined intent, subsequent encounter','Contact with unspecified hot objects, undetermined intent, subsequent encounter','Causes externes de morbidité et de mortalité','Y27.9XXD'),
('Contact with non spécifié hot objects, undetermined intent, sequela','Contact with unspecified hot objects, undetermined intent, sequela','Causes externes de morbidité et de mortalité','Y27.9XXS'),
('Contact with sharp glass, undetermined intent, initial encounter','Contact with sharp glass, undetermined intent, initial encounter','Causes externes de morbidité et de mortalité','Y28.0XXA'),
('Contact with sharp glass, undetermined intent, subsequent encounter','Contact with sharp glass, undetermined intent, subsequent encounter','Causes externes de morbidité et de mortalité','Y28.0XXD'),
('Contact with sharp glass, undetermined intent, sequela','Contact with sharp glass, undetermined intent, sequela','Causes externes de morbidité et de mortalité','Y28.0XXS'),
('Contact with knife, undetermined intent, initial encounter','Contact with knife, undetermined intent, initial encounter','Causes externes de morbidité et de mortalité','Y28.1XXA'),
('Contact with knife, undetermined intent, subsequent encounter','Contact with knife, undetermined intent, subsequent encounter','Causes externes de morbidité et de mortalité','Y28.1XXD'),
('Contact with knife, undetermined intent, sequela','Contact with knife, undetermined intent, sequela','Causes externes de morbidité et de mortalité','Y28.1XXS'),
('Contact with sword or dagger, undetermined intent, initial encounter','Contact with sword or dagger, undetermined intent, initial encounter','Causes externes de morbidité et de mortalité','Y28.2XXA'),
('Contact with sword or dagger, undetermined intent, subsequent encounter','Contact with sword or dagger, undetermined intent, subsequent encounter','Causes externes de morbidité et de mortalité','Y28.2XXD'),
('Contact with sword or dagger, undetermined intent, sequela','Contact with sword or dagger, undetermined intent, sequela','Causes externes de morbidité et de mortalité','Y28.2XXS'),
('Contact with autre sharp object, undetermined intent, initial encounter','Contact with other sharp object, undetermined intent, initial encounter','Causes externes de morbidité et de mortalité','Y28.8XXA'),
('Contact with autre sharp object, undetermined intent, subsequent encounter','Contact with other sharp object, undetermined intent, subsequent encounter','Causes externes de morbidité et de mortalité','Y28.8XXD'),
('Contact with autre sharp object, undetermined intent, sequela','Contact with other sharp object, undetermined intent, sequela','Causes externes de morbidité et de mortalité','Y28.8XXS'),
('Contact with non spécifié sharp object, undetermined intent, initial encounter','Contact with unspecified sharp object, undetermined intent, initial encounter','Causes externes de morbidité et de mortalité','Y28.9XXA'),
('Contact with non spécifié sharp object, undetermined intent, subsequent encounter','Contact with unspecified sharp object, undetermined intent, subsequent encounter','Causes externes de morbidité et de mortalité','Y28.9XXD'),
('Contact with non spécifié sharp object, undetermined intent, sequela','Contact with unspecified sharp object, undetermined intent, sequela','Causes externes de morbidité et de mortalité','Y28.9XXS'),
('Contact with blunt object, undetermined intent, initial encounter','Contact with blunt object, undetermined intent, initial encounter','Causes externes de morbidité et de mortalité','Y29.XXXA'),
('Contact with blunt object, undetermined intent, subsequent encounter','Contact with blunt object, undetermined intent, subsequent encounter','Causes externes de morbidité et de mortalité','Y29.XXXD'),
('Contact with blunt object, undetermined intent, sequela','Contact with blunt object, undetermined intent, sequela','Causes externes de morbidité et de mortalité','Y29.XXXS'),
('Falling, jumping or pushed from a high place, undetermined intent, initial encounter','Falling, jumping or pushed from a high place, undetermined intent, initial encounter','Causes externes de morbidité et de mortalité','Y30.XXXA'),
('Falling, jumping or pushed from a high place, undetermined intent, subsequent encounter','Falling, jumping or pushed from a high place, undetermined intent, subsequent encounter','Causes externes de morbidité et de mortalité','Y30.XXXD'),
('Falling, jumping or pushed from a high place, undetermined intent, sequela','Falling, jumping or pushed from a high place, undetermined intent, sequela','Causes externes de morbidité et de mortalité','Y30.XXXS')
ON CONFLICT (nom_fr) DO NOTHING;
