-- icd10v2_batch_104.sql (80 rows)
INSERT INTO pathologies (nom_fr, nom_en, categorie, icd10_code)
VALUES
('Internal ophthalmoplegia (complete) (total), non spécifié eye','Internal ophthalmoplegia (complete) (total), unspecified eye','Maladies de l''œil et de ses annexes','H52.519'),
('Paresis of accommodation, right eye','Paresis of accommodation, right eye','Maladies de l''œil et de ses annexes','H52.521'),
('Paresis of accommodation, left eye','Paresis of accommodation, left eye','Maladies de l''œil et de ses annexes','H52.522'),
('Paresis of accommodation, bilateral','Paresis of accommodation, bilateral','Maladies de l''œil et de ses annexes','H52.523'),
('Paresis of accommodation, non spécifié eye','Paresis of accommodation, unspecified eye','Maladies de l''œil et de ses annexes','H52.529'),
('Spasm of accommodation, right eye','Spasm of accommodation, right eye','Maladies de l''œil et de ses annexes','H52.531'),
('Spasm of accommodation, left eye','Spasm of accommodation, left eye','Maladies de l''œil et de ses annexes','H52.532'),
('Spasm of accommodation, bilateral','Spasm of accommodation, bilateral','Maladies de l''œil et de ses annexes','H52.533'),
('Spasm of accommodation, non spécifié eye','Spasm of accommodation, unspecified eye','Maladies de l''œil et de ses annexes','H52.539'),
('autre disorders of refraction','Other disorders of refraction','Maladies de l''œil et de ses annexes','H52.6'),
('non spécifié trouble of refraction','Unspecified disorder of refraction','Maladies de l''œil et de ses annexes','H52.7'),
('non spécifié amblyopia, right eye','Unspecified amblyopia, right eye','Maladies de l''œil et de ses annexes','H53.001'),
('non spécifié amblyopia, left eye','Unspecified amblyopia, left eye','Maladies de l''œil et de ses annexes','H53.002'),
('non spécifié amblyopia, bilateral','Unspecified amblyopia, bilateral','Maladies de l''œil et de ses annexes','H53.003'),
('non spécifié amblyopia, non spécifié eye','Unspecified amblyopia, unspecified eye','Maladies de l''œil et de ses annexes','H53.009'),
('Deprivation amblyopia, right eye','Deprivation amblyopia, right eye','Maladies de l''œil et de ses annexes','H53.011'),
('Deprivation amblyopia, left eye','Deprivation amblyopia, left eye','Maladies de l''œil et de ses annexes','H53.012'),
('Deprivation amblyopia, bilateral','Deprivation amblyopia, bilateral','Maladies de l''œil et de ses annexes','H53.013'),
('Deprivation amblyopia, non spécifié eye','Deprivation amblyopia, unspecified eye','Maladies de l''œil et de ses annexes','H53.019'),
('Refractive amblyopia, right eye','Refractive amblyopia, right eye','Maladies de l''œil et de ses annexes','H53.021'),
('Refractive amblyopia, left eye','Refractive amblyopia, left eye','Maladies de l''œil et de ses annexes','H53.022'),
('Refractive amblyopia, bilateral','Refractive amblyopia, bilateral','Maladies de l''œil et de ses annexes','H53.023'),
('Refractive amblyopia, non spécifié eye','Refractive amblyopia, unspecified eye','Maladies de l''œil et de ses annexes','H53.029'),
('Strabismic amblyopia, right eye','Strabismic amblyopia, right eye','Maladies de l''œil et de ses annexes','H53.031'),
('Strabismic amblyopia, left eye','Strabismic amblyopia, left eye','Maladies de l''œil et de ses annexes','H53.032'),
('Strabismic amblyopia, bilateral','Strabismic amblyopia, bilateral','Maladies de l''œil et de ses annexes','H53.033'),
('Strabismic amblyopia, non spécifié eye','Strabismic amblyopia, unspecified eye','Maladies de l''œil et de ses annexes','H53.039'),
('Amblyopia suspect, right eye','Amblyopia suspect, right eye','Maladies de l''œil et de ses annexes','H53.041'),
('Amblyopia suspect, left eye','Amblyopia suspect, left eye','Maladies de l''œil et de ses annexes','H53.042'),
('Amblyopia suspect, bilateral','Amblyopia suspect, bilateral','Maladies de l''œil et de ses annexes','H53.043'),
('Amblyopia suspect, non spécifié eye','Amblyopia suspect, unspecified eye','Maladies de l''œil et de ses annexes','H53.049'),
('non spécifié subjective visual disturbances','Unspecified subjective visual disturbances','Maladies de l''œil et de ses annexes','H53.10'),
('Day blindness','Day blindness','Maladies de l''œil et de ses annexes','H53.11'),
('Transient visual loss, right eye','Transient visual loss, right eye','Maladies de l''œil et de ses annexes','H53.121'),
('Transient visual loss, left eye','Transient visual loss, left eye','Maladies de l''œil et de ses annexes','H53.122'),
('Transient visual loss, bilateral','Transient visual loss, bilateral','Maladies de l''œil et de ses annexes','H53.123'),
('Transient visual loss, non spécifié eye','Transient visual loss, unspecified eye','Maladies de l''œil et de ses annexes','H53.129'),
('Sudden visual loss, right eye','Sudden visual loss, right eye','Maladies de l''œil et de ses annexes','H53.131'),
('Sudden visual loss, left eye','Sudden visual loss, left eye','Maladies de l''œil et de ses annexes','H53.132'),
('Sudden visual loss, bilateral','Sudden visual loss, bilateral','Maladies de l''œil et de ses annexes','H53.133'),
('Sudden visual loss, non spécifié eye','Sudden visual loss, unspecified eye','Maladies de l''œil et de ses annexes','H53.139'),
('Visual discomfort, right eye','Visual discomfort, right eye','Maladies de l''œil et de ses annexes','H53.141'),
('Visual discomfort, left eye','Visual discomfort, left eye','Maladies de l''œil et de ses annexes','H53.142'),
('Visual discomfort, bilateral','Visual discomfort, bilateral','Maladies de l''œil et de ses annexes','H53.143'),
('Visual discomfort, non spécifié','Visual discomfort, unspecified','Maladies de l''œil et de ses annexes','H53.149'),
('Visual distortions of shape and size','Visual distortions of shape and size','Maladies de l''œil et de ses annexes','H53.15'),
('Psychophysical visual disturbances','Psychophysical visual disturbances','Maladies de l''œil et de ses annexes','H53.16'),
('autre subjective visual disturbances','Other subjective visual disturbances','Maladies de l''œil et de ses annexes','H53.19'),
('Diplopia','Diplopia','Maladies de l''œil et de ses annexes','H53.2'),
('non spécifié trouble of binocular vision','Unspecified disorder of binocular vision','Maladies de l''œil et de ses annexes','H53.30'),
('Abnormal retinal correspondence','Abnormal retinal correspondence','Maladies de l''œil et de ses annexes','H53.31'),
('Fusion with defective stereopsis','Fusion with defective stereopsis','Maladies de l''œil et de ses annexes','H53.32'),
('Simultaneous visual perception without fusion','Simultaneous visual perception without fusion','Maladies de l''œil et de ses annexes','H53.33'),
('Suppression of binocular vision','Suppression of binocular vision','Maladies de l''œil et de ses annexes','H53.34'),
('non spécifié visual field defects','Unspecified visual field defects','Maladies de l''œil et de ses annexes','H53.40'),
('Scotoma involving central area, right eye','Scotoma involving central area, right eye','Maladies de l''œil et de ses annexes','H53.411'),
('Scotoma involving central area, left eye','Scotoma involving central area, left eye','Maladies de l''œil et de ses annexes','H53.412'),
('Scotoma involving central area, bilateral','Scotoma involving central area, bilateral','Maladies de l''œil et de ses annexes','H53.413'),
('Scotoma involving central area, non spécifié eye','Scotoma involving central area, unspecified eye','Maladies de l''œil et de ses annexes','H53.419'),
('Scotoma of blind spot area, right eye','Scotoma of blind spot area, right eye','Maladies de l''œil et de ses annexes','H53.421'),
('Scotoma of blind spot area, left eye','Scotoma of blind spot area, left eye','Maladies de l''œil et de ses annexes','H53.422'),
('Scotoma of blind spot area, bilateral','Scotoma of blind spot area, bilateral','Maladies de l''œil et de ses annexes','H53.423'),
('Scotoma of blind spot area, non spécifié eye','Scotoma of blind spot area, unspecified eye','Maladies de l''œil et de ses annexes','H53.429'),
('Sector or arcuate defects, right eye','Sector or arcuate defects, right eye','Maladies de l''œil et de ses annexes','H53.431'),
('Sector or arcuate defects, left eye','Sector or arcuate defects, left eye','Maladies de l''œil et de ses annexes','H53.432'),
('Sector or arcuate defects, bilateral','Sector or arcuate defects, bilateral','Maladies de l''œil et de ses annexes','H53.433'),
('Sector or arcuate defects, non spécifié eye','Sector or arcuate defects, unspecified eye','Maladies de l''œil et de ses annexes','H53.439'),
('autre localized visual field defect, right eye','Other localized visual field defect, right eye','Maladies de l''œil et de ses annexes','H53.451'),
('autre localized visual field defect, left eye','Other localized visual field defect, left eye','Maladies de l''œil et de ses annexes','H53.452'),
('autre localized visual field defect, bilateral','Other localized visual field defect, bilateral','Maladies de l''œil et de ses annexes','H53.453'),
('autre localized visual field defect, non spécifié eye','Other localized visual field defect, unspecified eye','Maladies de l''œil et de ses annexes','H53.459'),
('Homonymous bilateral field defects, right side','Homonymous bilateral field defects, right side','Maladies de l''œil et de ses annexes','H53.461'),
('Homonymous bilateral field defects, left side','Homonymous bilateral field defects, left side','Maladies de l''œil et de ses annexes','H53.462'),
('Homonymous bilateral field defects, non spécifié side','Homonymous bilateral field defects, unspecified side','Maladies de l''œil et de ses annexes','H53.469'),
('Heteronymous bilateral field defects','Heteronymous bilateral field defects','Maladies de l''œil et de ses annexes','H53.47'),
('Generalized contraction of visual field, right eye','Generalized contraction of visual field, right eye','Maladies de l''œil et de ses annexes','H53.481'),
('Generalized contraction of visual field, left eye','Generalized contraction of visual field, left eye','Maladies de l''œil et de ses annexes','H53.482'),
('Generalized contraction of visual field, bilateral','Generalized contraction of visual field, bilateral','Maladies de l''œil et de ses annexes','H53.483'),
('Generalized contraction of visual field, non spécifié eye','Generalized contraction of visual field, unspecified eye','Maladies de l''œil et de ses annexes','H53.489'),
('non spécifié color vision deficiencies','Unspecified color vision deficiencies','Maladies de l''œil et de ses annexes','H53.50')
ON CONFLICT (nom_fr) DO NOTHING;
