-- icd10v2_batch_188.sql (80 rows)
INSERT INTO pathologies (nom_fr, nom_en, categorie, icd10_code)
VALUES
('Panniculitis affecting regions of neck and back, cervicothoracic region','Panniculitis affecting regions of neck and back, cervicothoracic region','Maladies de l''appareil locomoteur','M54.03'),
('Panniculitis affecting regions of neck and back, thoracic region','Panniculitis affecting regions of neck and back, thoracic region','Maladies de l''appareil locomoteur','M54.04'),
('Panniculitis affecting regions of neck and back, thoracolumbar region','Panniculitis affecting regions of neck and back, thoracolumbar region','Maladies de l''appareil locomoteur','M54.05'),
('Panniculitis affecting regions of neck and back, lumbar region','Panniculitis affecting regions of neck and back, lumbar region','Maladies de l''appareil locomoteur','M54.06'),
('Panniculitis affecting regions of neck and back, lumbosacral region','Panniculitis affecting regions of neck and back, lumbosacral region','Maladies de l''appareil locomoteur','M54.07'),
('Panniculitis affecting regions of neck and back, sacral and sacrococcygeal region','Panniculitis affecting regions of neck and back, sacral and sacrococcygeal region','Maladies de l''appareil locomoteur','M54.08'),
('Panniculitis affecting regions, neck and back, multiple sites in spine','Panniculitis affecting regions, neck and back, multiple sites in spine','Maladies de l''appareil locomoteur','M54.09'),
('Radiculopathy, site non spécifié','Radiculopathy, site unspecified','Maladies de l''appareil locomoteur','M54.10'),
('Radiculopathy, occipito-atlanto-axial region','Radiculopathy, occipito-atlanto-axial region','Maladies de l''appareil locomoteur','M54.11'),
('Radiculopathy, cervical region','Radiculopathy, cervical region','Maladies de l''appareil locomoteur','M54.12'),
('Radiculopathy, cervicothoracic region','Radiculopathy, cervicothoracic region','Maladies de l''appareil locomoteur','M54.13'),
('Radiculopathy, thoracic region','Radiculopathy, thoracic region','Maladies de l''appareil locomoteur','M54.14'),
('Radiculopathy, thoracolumbar region','Radiculopathy, thoracolumbar region','Maladies de l''appareil locomoteur','M54.15'),
('Radiculopathy, lumbar region','Radiculopathy, lumbar region','Maladies de l''appareil locomoteur','M54.16'),
('Radiculopathy, lumbosacral region','Radiculopathy, lumbosacral region','Maladies de l''appareil locomoteur','M54.17'),
('Radiculopathy, sacral and sacrococcygeal region','Radiculopathy, sacral and sacrococcygeal region','Maladies de l''appareil locomoteur','M54.18'),
('Cervicalgia','Cervicalgia','Maladies de l''appareil locomoteur','M54.2'),
('Sciatica, non spécifié side','Sciatica, unspecified side','Maladies de l''appareil locomoteur','M54.30'),
('Sciatica, right side','Sciatica, right side','Maladies de l''appareil locomoteur','M54.31'),
('Sciatica, left side','Sciatica, left side','Maladies de l''appareil locomoteur','M54.32'),
('Lumbago with sciatica, non spécifié side','Lumbago with sciatica, unspecified side','Maladies de l''appareil locomoteur','M54.40'),
('Lumbago with sciatica, right side','Lumbago with sciatica, right side','Maladies de l''appareil locomoteur','M54.41'),
('Lumbago with sciatica, left side','Lumbago with sciatica, left side','Maladies de l''appareil locomoteur','M54.42'),
('Low back pain, non spécifié','Low back pain, unspecified','Maladies de l''appareil locomoteur','M54.50'),
('Vertebrogenic low back pain','Vertebrogenic low back pain','Maladies de l''appareil locomoteur','M54.51'),
('autre low back pain','Other low back pain','Maladies de l''appareil locomoteur','M54.59'),
('Pain in thoracic spine','Pain in thoracic spine','Maladies de l''appareil locomoteur','M54.6'),
('Occipital neuralgia','Occipital neuralgia','Maladies de l''appareil locomoteur','M54.81'),
('autre dorsalgia','Other dorsalgia','Maladies de l''appareil locomoteur','M54.89'),
('Dorsalgia, non spécifié','Dorsalgia, unspecified','Maladies de l''appareil locomoteur','M54.9'),
('Infective myositis, non spécifié right arm','Infective myositis, unspecified right arm','Maladies de l''appareil locomoteur','M60.000'),
('Infective myositis, non spécifié left arm','Infective myositis, unspecified left arm','Maladies de l''appareil locomoteur','M60.001'),
('Infective myositis, non spécifié arm','Infective myositis, unspecified arm','Maladies de l''appareil locomoteur','M60.002'),
('Infective myositis, non spécifié right leg','Infective myositis, unspecified right leg','Maladies de l''appareil locomoteur','M60.003'),
('Infective myositis, non spécifié left leg','Infective myositis, unspecified left leg','Maladies de l''appareil locomoteur','M60.004'),
('Infective myositis, non spécifié leg','Infective myositis, unspecified leg','Maladies de l''appareil locomoteur','M60.005'),
('Infective myositis, non spécifié site','Infective myositis, unspecified site','Maladies de l''appareil locomoteur','M60.009'),
('Infective myositis, right shoulder','Infective myositis, right shoulder','Maladies de l''appareil locomoteur','M60.011'),
('Infective myositis, left shoulder','Infective myositis, left shoulder','Maladies de l''appareil locomoteur','M60.012'),
('Infective myositis, non spécifié shoulder','Infective myositis, unspecified shoulder','Maladies de l''appareil locomoteur','M60.019'),
('Infective myositis, right upper arm','Infective myositis, right upper arm','Maladies de l''appareil locomoteur','M60.021'),
('Infective myositis, left upper arm','Infective myositis, left upper arm','Maladies de l''appareil locomoteur','M60.022'),
('Infective myositis, non spécifié upper arm','Infective myositis, unspecified upper arm','Maladies de l''appareil locomoteur','M60.029'),
('Infective myositis, right forearm','Infective myositis, right forearm','Maladies de l''appareil locomoteur','M60.031'),
('Infective myositis, left forearm','Infective myositis, left forearm','Maladies de l''appareil locomoteur','M60.032'),
('Infective myositis, non spécifié forearm','Infective myositis, unspecified forearm','Maladies de l''appareil locomoteur','M60.039'),
('Infective myositis, right hand','Infective myositis, right hand','Maladies de l''appareil locomoteur','M60.041'),
('Infective myositis, left hand','Infective myositis, left hand','Maladies de l''appareil locomoteur','M60.042'),
('Infective myositis, non spécifié hand','Infective myositis, unspecified hand','Maladies de l''appareil locomoteur','M60.043'),
('Infective myositis, right finger(s)','Infective myositis, right finger(s)','Maladies de l''appareil locomoteur','M60.044'),
('Infective myositis, left finger(s)','Infective myositis, left finger(s)','Maladies de l''appareil locomoteur','M60.045'),
('Infective myositis, non spécifié finger(s)','Infective myositis, unspecified finger(s)','Maladies de l''appareil locomoteur','M60.046'),
('Infective myositis, right thigh','Infective myositis, right thigh','Maladies de l''appareil locomoteur','M60.051'),
('Infective myositis, left thigh','Infective myositis, left thigh','Maladies de l''appareil locomoteur','M60.052'),
('Infective myositis, non spécifié thigh','Infective myositis, unspecified thigh','Maladies de l''appareil locomoteur','M60.059'),
('Infective myositis, right lower leg','Infective myositis, right lower leg','Maladies de l''appareil locomoteur','M60.061'),
('Infective myositis, left lower leg','Infective myositis, left lower leg','Maladies de l''appareil locomoteur','M60.062'),
('Infective myositis, non spécifié lower leg','Infective myositis, unspecified lower leg','Maladies de l''appareil locomoteur','M60.069'),
('Infective myositis, right ankle','Infective myositis, right ankle','Maladies de l''appareil locomoteur','M60.070'),
('Infective myositis, left ankle','Infective myositis, left ankle','Maladies de l''appareil locomoteur','M60.071'),
('Infective myositis, non spécifié ankle','Infective myositis, unspecified ankle','Maladies de l''appareil locomoteur','M60.072'),
('Infective myositis, right foot','Infective myositis, right foot','Maladies de l''appareil locomoteur','M60.073'),
('Infective myositis, left foot','Infective myositis, left foot','Maladies de l''appareil locomoteur','M60.074'),
('Infective myositis, non spécifié foot','Infective myositis, unspecified foot','Maladies de l''appareil locomoteur','M60.075'),
('Infective myositis, right toe(s)','Infective myositis, right toe(s)','Maladies de l''appareil locomoteur','M60.076'),
('Infective myositis, left toe(s)','Infective myositis, left toe(s)','Maladies de l''appareil locomoteur','M60.077'),
('Infective myositis, non spécifié toe(s)','Infective myositis, unspecified toe(s)','Maladies de l''appareil locomoteur','M60.078'),
('Infective myositis, autre site','Infective myositis, other site','Maladies de l''appareil locomoteur','M60.08'),
('Infective myositis, multiple sites','Infective myositis, multiple sites','Maladies de l''appareil locomoteur','M60.09'),
('Interstitial myositis of non spécifié site','Interstitial myositis of unspecified site','Maladies de l''appareil locomoteur','M60.10'),
('Interstitial myositis, right shoulder','Interstitial myositis, right shoulder','Maladies de l''appareil locomoteur','M60.111'),
('Interstitial myositis, left shoulder','Interstitial myositis, left shoulder','Maladies de l''appareil locomoteur','M60.112'),
('Interstitial myositis, non spécifié shoulder','Interstitial myositis, unspecified shoulder','Maladies de l''appareil locomoteur','M60.119'),
('Interstitial myositis, right upper arm','Interstitial myositis, right upper arm','Maladies de l''appareil locomoteur','M60.121'),
('Interstitial myositis, left upper arm','Interstitial myositis, left upper arm','Maladies de l''appareil locomoteur','M60.122'),
('Interstitial myositis, non spécifié upper arm','Interstitial myositis, unspecified upper arm','Maladies de l''appareil locomoteur','M60.129'),
('Interstitial myositis, right forearm','Interstitial myositis, right forearm','Maladies de l''appareil locomoteur','M60.131'),
('Interstitial myositis, left forearm','Interstitial myositis, left forearm','Maladies de l''appareil locomoteur','M60.132'),
('Interstitial myositis, non spécifié forearm','Interstitial myositis, unspecified forearm','Maladies de l''appareil locomoteur','M60.139'),
('Interstitial myositis, right hand','Interstitial myositis, right hand','Maladies de l''appareil locomoteur','M60.141')
ON CONFLICT (nom_fr) DO NOTHING;
