-- icd10v2_batch_221.sql (80 rows)
INSERT INTO pathologies (nom_fr, nom_en, categorie, icd10_code)
VALUES
('Complication associated with artificial fertilization, non spécifié','Complication associated with artificial fertilization, unspecified','Maladies de l''appareil génito-urinaire','N98.9'),
('Postprocedural (aigu) (chronique) kidney insuffisance','Postprocedural (acute) (chronic) kidney failure','Maladies de l''appareil génito-urinaire','N99.0'),
('Postprocedural urethral stricture, male, meatal','Postprocedural urethral stricture, male, meatal','Maladies de l''appareil génito-urinaire','N99.110'),
('Postprocedural bulbous urethral stricture, male','Postprocedural bulbous urethral stricture, male','Maladies de l''appareil génito-urinaire','N99.111'),
('Postprocedural membranous urethral stricture, male','Postprocedural membranous urethral stricture, male','Maladies de l''appareil génito-urinaire','N99.112'),
('Postprocedural anterior bulbous urethral stricture, male','Postprocedural anterior bulbous urethral stricture, male','Maladies de l''appareil génito-urinaire','N99.113'),
('Postprocedural urethral stricture, male, non spécifié','Postprocedural urethral stricture, male, unspecified','Maladies de l''appareil génito-urinaire','N99.114'),
('Postprocedural fossa navicularis urethral stricture','Postprocedural fossa navicularis urethral stricture','Maladies de l''appareil génito-urinaire','N99.115'),
('Postprocedural urethral stricture, male, overlapping sites','Postprocedural urethral stricture, male, overlapping sites','Maladies de l''appareil génito-urinaire','N99.116'),
('Postprocedural urethral stricture, female','Postprocedural urethral stricture, female','Maladies de l''appareil génito-urinaire','N99.12'),
('Postprocedural adhesions of vagina','Postprocedural adhesions of vagina','Maladies de l''appareil génito-urinaire','N99.2'),
('Prolapse of vaginal vault after hysterectomy','Prolapse of vaginal vault after hysterectomy','Maladies de l''appareil génito-urinaire','N99.3'),
('Postprocedural pelvic peritoneal adhesions','Postprocedural pelvic peritoneal adhesions','Maladies de l''appareil génito-urinaire','N99.4'),
('Cystostomy hémorragie','Cystostomy hemorrhage','Maladies de l''appareil génito-urinaire','N99.510'),
('Cystostomy infection','Cystostomy infection','Maladies de l''appareil génito-urinaire','N99.511'),
('Cystostomy malfunction','Cystostomy malfunction','Maladies de l''appareil génito-urinaire','N99.512'),
('autre cystostomy complication','Other cystostomy complication','Maladies de l''appareil génito-urinaire','N99.518'),
('hémorragie of incontinent external stoma of urinary tract','Hemorrhage of incontinent external stoma of urinary tract','Maladies de l''appareil génito-urinaire','N99.520'),
('infection of incontinent external stoma of urinary tract','Infection of incontinent external stoma of urinary tract','Maladies de l''appareil génito-urinaire','N99.521'),
('Malfunction of incontinent external stoma of urinary tract','Malfunction of incontinent external stoma of urinary tract','Maladies de l''appareil génito-urinaire','N99.522'),
('Herniation of incontinent stoma of urinary tract','Herniation of incontinent stoma of urinary tract','Maladies de l''appareil génito-urinaire','N99.523'),
('sténose of incontinent stoma of urinary tract','Stenosis of incontinent stoma of urinary tract','Maladies de l''appareil génito-urinaire','N99.524'),
('autre complication of incontinent external stoma of urinary tract','Other complication of incontinent external stoma of urinary tract','Maladies de l''appareil génito-urinaire','N99.528'),
('hémorragie of continent stoma of urinary tract','Hemorrhage of continent stoma of urinary tract','Maladies de l''appareil génito-urinaire','N99.530'),
('infection of continent stoma of urinary tract','Infection of continent stoma of urinary tract','Maladies de l''appareil génito-urinaire','N99.531'),
('Malfunction of continent stoma of urinary tract','Malfunction of continent stoma of urinary tract','Maladies de l''appareil génito-urinaire','N99.532'),
('Herniation of continent stoma of urinary tract','Herniation of continent stoma of urinary tract','Maladies de l''appareil génito-urinaire','N99.533'),
('sténose of continent stoma of urinary tract','Stenosis of continent stoma of urinary tract','Maladies de l''appareil génito-urinaire','N99.534'),
('autre complication of continent stoma of urinary tract','Other complication of continent stoma of urinary tract','Maladies de l''appareil génito-urinaire','N99.538'),
('Intraoperative hémorragie and hematoma of a genitourinary system organ or structure complicating a genitourinary system procedure','Intraoperative hemorrhage and hematoma of a genitourinary system organ or structure complicating a genitourinary system procedure','Maladies de l''appareil génito-urinaire','N99.61'),
('Intraoperative hémorragie and hematoma of a genitourinary system organ or structure complicating autre procedure','Intraoperative hemorrhage and hematoma of a genitourinary system organ or structure complicating other procedure','Maladies de l''appareil génito-urinaire','N99.62'),
('Accidental puncture and laceration of a genitourinary system organ or structure during a genitourinary system procedure','Accidental puncture and laceration of a genitourinary system organ or structure during a genitourinary system procedure','Maladies de l''appareil génito-urinaire','N99.71'),
('Accidental puncture and laceration of a genitourinary system organ or structure during autre procedure','Accidental puncture and laceration of a genitourinary system organ or structure during other procedure','Maladies de l''appareil génito-urinaire','N99.72'),
('autre intraoperative complications of genitourinary system','Other intraoperative complications of genitourinary system','Maladies de l''appareil génito-urinaire','N99.81'),
('Postprocedural hémorragie of a genitourinary system organ or structure following a genitourinary system procedure','Postprocedural hemorrhage of a genitourinary system organ or structure following a genitourinary system procedure','Maladies de l''appareil génito-urinaire','N99.820'),
('Postprocedural hémorragie of a genitourinary system organ or structure following autre procedure','Postprocedural hemorrhage of a genitourinary system organ or structure following other procedure','Maladies de l''appareil génito-urinaire','N99.821'),
('Residual ovary syndrome','Residual ovary syndrome','Maladies de l''appareil génito-urinaire','N99.83'),
('Postprocedural hematoma of a genitourinary system organ or structure following a genitourinary system procedure','Postprocedural hematoma of a genitourinary system organ or structure following a genitourinary system procedure','Maladies de l''appareil génito-urinaire','N99.840'),
('Postprocedural hematoma of a genitourinary system organ or structure following autre procedure','Postprocedural hematoma of a genitourinary system organ or structure following other procedure','Maladies de l''appareil génito-urinaire','N99.841'),
('Postprocedural seroma of a genitourinary system organ or structure following a genitourinary system procedure','Postprocedural seroma of a genitourinary system organ or structure following a genitourinary system procedure','Maladies de l''appareil génito-urinaire','N99.842'),
('Postprocedural seroma of a genitourinary system organ or structure following autre procedure','Postprocedural seroma of a genitourinary system organ or structure following other procedure','Maladies de l''appareil génito-urinaire','N99.843'),
('Post endometrial ablation syndrome','Post endometrial ablation syndrome','Maladies de l''appareil génito-urinaire','N99.85'),
('autre postprocedural complications and disorders of genitourinary system','Other postprocedural complications and disorders of genitourinary system','Maladies de l''appareil génito-urinaire','N99.89'),
('Abdominal pregnancy without intrauterine pregnancy','Abdominal pregnancy without intrauterine pregnancy','Grossesse, accouchement et puerpéralité','O00.00'),
('Abdominal pregnancy with intrauterine pregnancy','Abdominal pregnancy with intrauterine pregnancy','Grossesse, accouchement et puerpéralité','O00.01'),
('Right tubal pregnancy without intrauterine pregnancy','Right tubal pregnancy without intrauterine pregnancy','Grossesse, accouchement et puerpéralité','O00.101'),
('Left tubal pregnancy without intrauterine pregnancy','Left tubal pregnancy without intrauterine pregnancy','Grossesse, accouchement et puerpéralité','O00.102'),
('non spécifié tubal pregnancy without intrauterine pregnancy','Unspecified tubal pregnancy without intrauterine pregnancy','Grossesse, accouchement et puerpéralité','O00.109'),
('Right tubal pregnancy with intrauterine pregnancy','Right tubal pregnancy with intrauterine pregnancy','Grossesse, accouchement et puerpéralité','O00.111'),
('Left tubal pregnancy with intrauterine pregnancy','Left tubal pregnancy with intrauterine pregnancy','Grossesse, accouchement et puerpéralité','O00.112'),
('non spécifié tubal pregnancy with intrauterine pregnancy','Unspecified tubal pregnancy with intrauterine pregnancy','Grossesse, accouchement et puerpéralité','O00.119'),
('Right ovarian pregnancy without intrauterine pregnancy','Right ovarian pregnancy without intrauterine pregnancy','Grossesse, accouchement et puerpéralité','O00.201'),
('Left ovarian pregnancy without intrauterine pregnancy','Left ovarian pregnancy without intrauterine pregnancy','Grossesse, accouchement et puerpéralité','O00.202'),
('non spécifié ovarian pregnancy without intrauterine pregnancy','Unspecified ovarian pregnancy without intrauterine pregnancy','Grossesse, accouchement et puerpéralité','O00.209'),
('Right ovarian pregnancy with intrauterine pregnancy','Right ovarian pregnancy with intrauterine pregnancy','Grossesse, accouchement et puerpéralité','O00.211'),
('Left ovarian pregnancy with intrauterine pregnancy','Left ovarian pregnancy with intrauterine pregnancy','Grossesse, accouchement et puerpéralité','O00.212'),
('non spécifié ovarian pregnancy with intrauterine pregnancy','Unspecified ovarian pregnancy with intrauterine pregnancy','Grossesse, accouchement et puerpéralité','O00.219'),
('autre ectopic pregnancy without intrauterine pregnancy','Other ectopic pregnancy without intrauterine pregnancy','Grossesse, accouchement et puerpéralité','O00.80'),
('autre ectopic pregnancy with intrauterine pregnancy','Other ectopic pregnancy with intrauterine pregnancy','Grossesse, accouchement et puerpéralité','O00.81'),
('non spécifié ectopic pregnancy without intrauterine pregnancy','Unspecified ectopic pregnancy without intrauterine pregnancy','Grossesse, accouchement et puerpéralité','O00.90'),
('non spécifié ectopic pregnancy with intrauterine pregnancy','Unspecified ectopic pregnancy with intrauterine pregnancy','Grossesse, accouchement et puerpéralité','O00.91'),
('Classical hydatidiform mole','Classical hydatidiform mole','Grossesse, accouchement et puerpéralité','O01.0'),
('Incomplete and partial hydatidiform mole','Incomplete and partial hydatidiform mole','Grossesse, accouchement et puerpéralité','O01.1'),
('Hydatidiform mole, non spécifié','Hydatidiform mole, unspecified','Grossesse, accouchement et puerpéralité','O01.9'),
('Blighted ovum and nonhydatidiform mole','Blighted ovum and nonhydatidiform mole','Grossesse, accouchement et puerpéralité','O02.0'),
('Missed abortion','Missed abortion','Grossesse, accouchement et puerpéralité','O02.1'),
('Inappropriate change in quantitative human chorionic gonadotropin (hCG) in early pregnancy','Inappropriate change in quantitative human chorionic gonadotropin (hCG) in early pregnancy','Grossesse, accouchement et puerpéralité','O02.81'),
('autre abnormal products of conception','Other abnormal products of conception','Grossesse, accouchement et puerpéralité','O02.89'),
('Abnormal product of conception, non spécifié','Abnormal product of conception, unspecified','Grossesse, accouchement et puerpéralité','O02.9'),
('Genital tract and pelvic infection following incomplete spontaneous abortion','Genital tract and pelvic infection following incomplete spontaneous abortion','Grossesse, accouchement et puerpéralité','O03.0'),
('Delayed or excessive hémorragie following incomplete spontaneous abortion','Delayed or excessive hemorrhage following incomplete spontaneous abortion','Grossesse, accouchement et puerpéralité','O03.1'),
('Embolism following incomplete spontaneous abortion','Embolism following incomplete spontaneous abortion','Grossesse, accouchement et puerpéralité','O03.2'),
('non spécifié complication following incomplete spontaneous abortion','Unspecified complication following incomplete spontaneous abortion','Grossesse, accouchement et puerpéralité','O03.30'),
('Shock following incomplete spontaneous abortion','Shock following incomplete spontaneous abortion','Grossesse, accouchement et puerpéralité','O03.31'),
('Renal insuffisance following incomplete spontaneous abortion','Renal failure following incomplete spontaneous abortion','Grossesse, accouchement et puerpéralité','O03.32'),
('Metabolic trouble following incomplete spontaneous abortion','Metabolic disorder following incomplete spontaneous abortion','Grossesse, accouchement et puerpéralité','O03.33'),
('Damage to pelvic organs following incomplete spontaneous abortion','Damage to pelvic organs following incomplete spontaneous abortion','Grossesse, accouchement et puerpéralité','O03.34'),
('autre venous complications following incomplete spontaneous abortion','Other venous complications following incomplete spontaneous abortion','Grossesse, accouchement et puerpéralité','O03.35'),
('Cardiac arrest following incomplete spontaneous abortion','Cardiac arrest following incomplete spontaneous abortion','Grossesse, accouchement et puerpéralité','O03.36'),
('Sepsis following incomplete spontaneous abortion','Sepsis following incomplete spontaneous abortion','Grossesse, accouchement et puerpéralité','O03.37')
ON CONFLICT (nom_fr) DO NOTHING;
