-- icd10v2_batch_218.sql (80 rows)
INSERT INTO pathologies (nom_fr, nom_en, categorie, icd10_code)
VALUES
('Superficial endometriosis of the right uterosacral ligament','Superficial endometriosis of the right uterosacral ligament','Maladies de l''appareil génito-urinaire','N80.3A1'),
('Superficial endometriosis of the left uterosacral ligament','Superficial endometriosis of the left uterosacral ligament','Maladies de l''appareil génito-urinaire','N80.3A2'),
('Superficial endometriosis of the bilateral uterosacral ligament(s)','Superficial endometriosis of the bilateral uterosacral ligament(s)','Maladies de l''appareil génito-urinaire','N80.3A3'),
('Superficial endometriosis of the uterosacral ligament(s), non spécifié side','Superficial endometriosis of the uterosacral ligament(s), unspecified side','Maladies de l''appareil génito-urinaire','N80.3A9'),
('Deep endometriosis of the right uterosacral ligament','Deep endometriosis of the right uterosacral ligament','Maladies de l''appareil génito-urinaire','N80.3B1'),
('Deep endometriosis of the left uterosacral ligament','Deep endometriosis of the left uterosacral ligament','Maladies de l''appareil génito-urinaire','N80.3B2'),
('Deep endometriosis of bilateral uterosacral ligament(s)','Deep endometriosis of bilateral uterosacral ligament(s)','Maladies de l''appareil génito-urinaire','N80.3B3'),
('Deep endometriosis of the uterosacral ligament(s), non spécifié side','Deep endometriosis of the uterosacral ligament(s), unspecified side','Maladies de l''appareil génito-urinaire','N80.3B9'),
('Endometriosis of the right uterosacral ligament, non spécifié depth','Endometriosis of the right uterosacral ligament, unspecified depth','Maladies de l''appareil génito-urinaire','N80.3C1'),
('Endometriosis of the left uterosacral ligament, non spécifié depth','Endometriosis of the left uterosacral ligament, unspecified depth','Maladies de l''appareil génito-urinaire','N80.3C2'),
('Endometriosis of bilateral uterosacral ligament(s), non spécifié depth','Endometriosis of bilateral uterosacral ligament(s), unspecified depth','Maladies de l''appareil génito-urinaire','N80.3C3'),
('Endometriosis of the uterosacral ligament(s), non spécifié side, non spécifié depth','Endometriosis of the uterosacral ligament(s), unspecified side, unspecified depth','Maladies de l''appareil génito-urinaire','N80.3C9'),
('Superficial endometriosis of the pelvic peritoneum, autre specified sites','Superficial endometriosis of the pelvic peritoneum, other specified sites','Maladies de l''appareil génito-urinaire','N80.391'),
('Deep endometriosis of the pelvic peritoneum, autre specified sites','Deep endometriosis of the pelvic peritoneum, other specified sites','Maladies de l''appareil génito-urinaire','N80.392'),
('Endometriosis of the pelvic peritoneum, autre specified sites, non spécifié depth','Endometriosis of the pelvic peritoneum, other specified sites, unspecified depth','Maladies de l''appareil génito-urinaire','N80.399'),
('Endometriosis of rectovaginal septum, non spécifié involvement of vagina','Endometriosis of rectovaginal septum, unspecified involvement of vagina','Maladies de l''appareil génito-urinaire','N80.40'),
('Endometriosis of rectovaginal septum without involvement of vagina','Endometriosis of rectovaginal septum without involvement of vagina','Maladies de l''appareil génito-urinaire','N80.41'),
('Endometriosis of rectovaginal septum with involvement of vagina','Endometriosis of rectovaginal septum with involvement of vagina','Maladies de l''appareil génito-urinaire','N80.42'),
('Endometriosis of intestine, non spécifié','Endometriosis of intestine, unspecified','Maladies de l''appareil génito-urinaire','N80.50'),
('Superficial endometriosis of the rectum','Superficial endometriosis of the rectum','Maladies de l''appareil génito-urinaire','N80.511'),
('Deep endometriosis of the rectum','Deep endometriosis of the rectum','Maladies de l''appareil génito-urinaire','N80.512'),
('Endometriosis of the rectum, non spécifié depth','Endometriosis of the rectum, unspecified depth','Maladies de l''appareil génito-urinaire','N80.519'),
('Superficial endometriosis of the sigmoid colon','Superficial endometriosis of the sigmoid colon','Maladies de l''appareil génito-urinaire','N80.521'),
('Deep endometriosis of the sigmoid colon','Deep endometriosis of the sigmoid colon','Maladies de l''appareil génito-urinaire','N80.522'),
('Endometriosis of the sigmoid colon, non spécifié depth','Endometriosis of the sigmoid colon, unspecified depth','Maladies de l''appareil génito-urinaire','N80.529'),
('Superficial endometriosis of the cecum','Superficial endometriosis of the cecum','Maladies de l''appareil génito-urinaire','N80.531'),
('Deep endometriosis of the cecum','Deep endometriosis of the cecum','Maladies de l''appareil génito-urinaire','N80.532'),
('Endometriosis of the cecum, non spécifié depth','Endometriosis of the cecum, unspecified depth','Maladies de l''appareil génito-urinaire','N80.539'),
('Superficial endometriosis of the appendix','Superficial endometriosis of the appendix','Maladies de l''appareil génito-urinaire','N80.541'),
('Deep endometriosis of the appendix','Deep endometriosis of the appendix','Maladies de l''appareil génito-urinaire','N80.542'),
('Endometriosis of the appendix, non spécifié depth','Endometriosis of the appendix, unspecified depth','Maladies de l''appareil génito-urinaire','N80.549'),
('Superficial endometriosis of autre parts of the colon','Superficial endometriosis of other parts of the colon','Maladies de l''appareil génito-urinaire','N80.551'),
('Deep endometriosis of autre parts of the colon','Deep endometriosis of other parts of the colon','Maladies de l''appareil génito-urinaire','N80.552'),
('Endometriosis of autre parts of the colon, non spécifié depth','Endometriosis of other parts of the colon, unspecified depth','Maladies de l''appareil génito-urinaire','N80.559'),
('Superficial endometriosis of the small intestine','Superficial endometriosis of the small intestine','Maladies de l''appareil génito-urinaire','N80.561'),
('Deep endometriosis of the small intestine','Deep endometriosis of the small intestine','Maladies de l''appareil génito-urinaire','N80.562'),
('Endometriosis of the small intestine, non spécifié depth','Endometriosis of the small intestine, unspecified depth','Maladies de l''appareil génito-urinaire','N80.569'),
('Endometriosis in cutaneous scar','Endometriosis in cutaneous scar','Maladies de l''appareil génito-urinaire','N80.6'),
('Endometriosis of bladder, non spécifié depth','Endometriosis of bladder, unspecified depth','Maladies de l''appareil génito-urinaire','N80.A0'),
('Superficial endometriosis of bladder','Superficial endometriosis of bladder','Maladies de l''appareil génito-urinaire','N80.A1'),
('Deep endometriosis of bladder','Deep endometriosis of bladder','Maladies de l''appareil génito-urinaire','N80.A2'),
('Superficial endometriosis of right ureter','Superficial endometriosis of right ureter','Maladies de l''appareil génito-urinaire','N80.A41'),
('Superficial endometriosis of left ureter','Superficial endometriosis of left ureter','Maladies de l''appareil génito-urinaire','N80.A42'),
('Superficial endometriosis of bilateral ureters','Superficial endometriosis of bilateral ureters','Maladies de l''appareil génito-urinaire','N80.A43'),
('Superficial endometriosis of non spécifié ureter','Superficial endometriosis of unspecified ureter','Maladies de l''appareil génito-urinaire','N80.A49'),
('Deep endometriosis of right ureter','Deep endometriosis of right ureter','Maladies de l''appareil génito-urinaire','N80.A51'),
('Deep endometriosis of left ureter','Deep endometriosis of left ureter','Maladies de l''appareil génito-urinaire','N80.A52'),
('Deep endometriosis of bilateral ureters','Deep endometriosis of bilateral ureters','Maladies de l''appareil génito-urinaire','N80.A53'),
('Deep endometriosis of non spécifié ureter','Deep endometriosis of unspecified ureter','Maladies de l''appareil génito-urinaire','N80.A59'),
('Endometriosis of right ureter, non spécifié depth','Endometriosis of right ureter, unspecified depth','Maladies de l''appareil génito-urinaire','N80.A61'),
('Endometriosis of left ureter, non spécifié depth','Endometriosis of left ureter, unspecified depth','Maladies de l''appareil génito-urinaire','N80.A62'),
('Endometriosis of bilateral ureters, non spécifié depth','Endometriosis of bilateral ureters, unspecified depth','Maladies de l''appareil génito-urinaire','N80.A63'),
('Endometriosis of non spécifié ureter, non spécifié depth','Endometriosis of unspecified ureter, unspecified depth','Maladies de l''appareil génito-urinaire','N80.A69'),
('Endometriosis of pleura','Endometriosis of pleura','Maladies de l''appareil génito-urinaire','N80.B1'),
('Endometriosis of lung','Endometriosis of lung','Maladies de l''appareil génito-urinaire','N80.B2'),
('Superficial endometriosis of diaphragm','Superficial endometriosis of diaphragm','Maladies de l''appareil génito-urinaire','N80.B31'),
('Deep endometriosis of diaphragm','Deep endometriosis of diaphragm','Maladies de l''appareil génito-urinaire','N80.B32'),
('Endometriosis of diaphragm, non spécifié depth','Endometriosis of diaphragm, unspecified depth','Maladies de l''appareil génito-urinaire','N80.B39'),
('Endometriosis of the pericardial space','Endometriosis of the pericardial space','Maladies de l''appareil génito-urinaire','N80.B4'),
('Endometriosis of the mediastinal space','Endometriosis of the mediastinal space','Maladies de l''appareil génito-urinaire','N80.B5'),
('Endometriosis of cardiothoracic space','Endometriosis of cardiothoracic space','Maladies de l''appareil génito-urinaire','N80.B6'),
('Endometriosis of the abdomen, non spécifié','Endometriosis of the abdomen, unspecified','Maladies de l''appareil génito-urinaire','N80.C0'),
('Endometriosis of the anterior abdominal wall, subcutaneous tissue','Endometriosis of the anterior abdominal wall, subcutaneous tissue','Maladies de l''appareil génito-urinaire','N80.C10'),
('Endometriosis of the anterior abdominal wall, fascia and muscular layers','Endometriosis of the anterior abdominal wall, fascia and muscular layers','Maladies de l''appareil génito-urinaire','N80.C11'),
('Endometriosis of the anterior abdominal wall, non spécifié depth','Endometriosis of the anterior abdominal wall, unspecified depth','Maladies de l''appareil génito-urinaire','N80.C19'),
('Endometriosis of the umbilicus','Endometriosis of the umbilicus','Maladies de l''appareil génito-urinaire','N80.C2'),
('Endometriosis of the inguinal canal','Endometriosis of the inguinal canal','Maladies de l''appareil génito-urinaire','N80.C3'),
('Endometriosis of extra-pelvic abdominal peritoneum','Endometriosis of extra-pelvic abdominal peritoneum','Maladies de l''appareil génito-urinaire','N80.C4'),
('Endometriosis of autre site of abdomen','Endometriosis of other site of abdomen','Maladies de l''appareil génito-urinaire','N80.C9'),
('Endometriosis of the pelvic nerves, non spécifié','Endometriosis of the pelvic nerves, unspecified','Maladies de l''appareil génito-urinaire','N80.D0'),
('Endometriosis of the sacral splanchnic nerves','Endometriosis of the sacral splanchnic nerves','Maladies de l''appareil génito-urinaire','N80.D1'),
('Endometriosis of the sacral nerve roots','Endometriosis of the sacral nerve roots','Maladies de l''appareil génito-urinaire','N80.D2'),
('Endometriosis of the obturator nerve','Endometriosis of the obturator nerve','Maladies de l''appareil génito-urinaire','N80.D3'),
('Endometriosis of the sciatic nerve','Endometriosis of the sciatic nerve','Maladies de l''appareil génito-urinaire','N80.D4'),
('Endometriosis of the pudendal nerve','Endometriosis of the pudendal nerve','Maladies de l''appareil génito-urinaire','N80.D5'),
('Endometriosis of the femoral nerve','Endometriosis of the femoral nerve','Maladies de l''appareil génito-urinaire','N80.D6'),
('Endometriosis of autre pelvic nerve','Endometriosis of other pelvic nerve','Maladies de l''appareil génito-urinaire','N80.D9'),
('autre endometriosis','Other endometriosis','Maladies de l''appareil génito-urinaire','N80.8'),
('Endometriosis, non spécifié','Endometriosis, unspecified','Maladies de l''appareil génito-urinaire','N80.9'),
('Urethrocele','Urethrocele','Maladies de l''appareil génito-urinaire','N81.0')
ON CONFLICT (nom_fr) DO NOTHING;
