-- icd10v2_batch_100.sql (80 rows)
INSERT INTO pathologies (nom_fr, nom_en, categorie, icd10_code)
VALUES
('Panuveitis, bilateral','Panuveitis, bilateral','Maladies de l''œil et de ses annexes','H44.113'),
('Panuveitis, non spécifié eye','Panuveitis, unspecified eye','Maladies de l''œil et de ses annexes','H44.119'),
('Parasitic endophthalmitis, non spécifié, right eye','Parasitic endophthalmitis, unspecified, right eye','Maladies de l''œil et de ses annexes','H44.121'),
('Parasitic endophthalmitis, non spécifié, left eye','Parasitic endophthalmitis, unspecified, left eye','Maladies de l''œil et de ses annexes','H44.122'),
('Parasitic endophthalmitis, non spécifié, bilateral','Parasitic endophthalmitis, unspecified, bilateral','Maladies de l''œil et de ses annexes','H44.123'),
('Parasitic endophthalmitis, non spécifié, non spécifié eye','Parasitic endophthalmitis, unspecified, unspecified eye','Maladies de l''œil et de ses annexes','H44.129'),
('Sympathetic uveitis, right eye','Sympathetic uveitis, right eye','Maladies de l''œil et de ses annexes','H44.131'),
('Sympathetic uveitis, left eye','Sympathetic uveitis, left eye','Maladies de l''œil et de ses annexes','H44.132'),
('Sympathetic uveitis, bilateral','Sympathetic uveitis, bilateral','Maladies de l''œil et de ses annexes','H44.133'),
('Sympathetic uveitis, non spécifié eye','Sympathetic uveitis, unspecified eye','Maladies de l''œil et de ses annexes','H44.139'),
('autre endophthalmitis','Other endophthalmitis','Maladies de l''œil et de ses annexes','H44.19'),
('Degenerative myopia, non spécifié eye','Degenerative myopia, unspecified eye','Maladies de l''œil et de ses annexes','H44.20'),
('Degenerative myopia, right eye','Degenerative myopia, right eye','Maladies de l''œil et de ses annexes','H44.21'),
('Degenerative myopia, left eye','Degenerative myopia, left eye','Maladies de l''œil et de ses annexes','H44.22'),
('Degenerative myopia, bilateral','Degenerative myopia, bilateral','Maladies de l''œil et de ses annexes','H44.23'),
('Degenerative myopia with choroidal neovascularization, right eye','Degenerative myopia with choroidal neovascularization, right eye','Maladies de l''œil et de ses annexes','H44.2A1'),
('Degenerative myopia with choroidal neovascularization, left eye','Degenerative myopia with choroidal neovascularization, left eye','Maladies de l''œil et de ses annexes','H44.2A2'),
('Degenerative myopia with choroidal neovascularization, bilateral','Degenerative myopia with choroidal neovascularization, bilateral','Maladies de l''œil et de ses annexes','H44.2A3'),
('Degenerative myopia with choroidal neovascularization, non spécifié eye','Degenerative myopia with choroidal neovascularization, unspecified eye','Maladies de l''œil et de ses annexes','H44.2A9'),
('Degenerative myopia with macular hole, right eye','Degenerative myopia with macular hole, right eye','Maladies de l''œil et de ses annexes','H44.2B1'),
('Degenerative myopia with macular hole, left eye','Degenerative myopia with macular hole, left eye','Maladies de l''œil et de ses annexes','H44.2B2'),
('Degenerative myopia with macular hole, bilateral','Degenerative myopia with macular hole, bilateral','Maladies de l''œil et de ses annexes','H44.2B3'),
('Degenerative myopia with macular hole, non spécifié eye','Degenerative myopia with macular hole, unspecified eye','Maladies de l''œil et de ses annexes','H44.2B9'),
('Degenerative myopia with retinal detachment, right eye','Degenerative myopia with retinal detachment, right eye','Maladies de l''œil et de ses annexes','H44.2C1'),
('Degenerative myopia with retinal detachment, left eye','Degenerative myopia with retinal detachment, left eye','Maladies de l''œil et de ses annexes','H44.2C2'),
('Degenerative myopia with retinal detachment, bilateral','Degenerative myopia with retinal detachment, bilateral','Maladies de l''œil et de ses annexes','H44.2C3'),
('Degenerative myopia with retinal detachment, non spécifié eye','Degenerative myopia with retinal detachment, unspecified eye','Maladies de l''œil et de ses annexes','H44.2C9'),
('Degenerative myopia with foveoschisis, right eye','Degenerative myopia with foveoschisis, right eye','Maladies de l''œil et de ses annexes','H44.2D1'),
('Degenerative myopia with foveoschisis, left eye','Degenerative myopia with foveoschisis, left eye','Maladies de l''œil et de ses annexes','H44.2D2'),
('Degenerative myopia with foveoschisis, bilateral','Degenerative myopia with foveoschisis, bilateral','Maladies de l''œil et de ses annexes','H44.2D3'),
('Degenerative myopia with foveoschisis, non spécifié eye','Degenerative myopia with foveoschisis, unspecified eye','Maladies de l''œil et de ses annexes','H44.2D9'),
('Degenerative myopia with autre maculopathy, right eye','Degenerative myopia with other maculopathy, right eye','Maladies de l''œil et de ses annexes','H44.2E1'),
('Degenerative myopia with autre maculopathy, left eye','Degenerative myopia with other maculopathy, left eye','Maladies de l''œil et de ses annexes','H44.2E2'),
('Degenerative myopia with autre maculopathy, bilateral','Degenerative myopia with other maculopathy, bilateral','Maladies de l''œil et de ses annexes','H44.2E3'),
('Degenerative myopia with autre maculopathy, non spécifié eye','Degenerative myopia with other maculopathy, unspecified eye','Maladies de l''œil et de ses annexes','H44.2E9'),
('non spécifié degenerative trouble of globe','Unspecified degenerative disorder of globe','Maladies de l''œil et de ses annexes','H44.30'),
('Chalcosis, right eye','Chalcosis, right eye','Maladies de l''œil et de ses annexes','H44.311'),
('Chalcosis, left eye','Chalcosis, left eye','Maladies de l''œil et de ses annexes','H44.312'),
('Chalcosis, bilateral','Chalcosis, bilateral','Maladies de l''œil et de ses annexes','H44.313'),
('Chalcosis, non spécifié eye','Chalcosis, unspecified eye','Maladies de l''œil et de ses annexes','H44.319'),
('Siderosis of eye, right eye','Siderosis of eye, right eye','Maladies de l''œil et de ses annexes','H44.321'),
('Siderosis of eye, left eye','Siderosis of eye, left eye','Maladies de l''œil et de ses annexes','H44.322'),
('Siderosis of eye, bilateral','Siderosis of eye, bilateral','Maladies de l''œil et de ses annexes','H44.323'),
('Siderosis of eye, non spécifié eye','Siderosis of eye, unspecified eye','Maladies de l''œil et de ses annexes','H44.329'),
('autre degenerative disorders of globe, right eye','Other degenerative disorders of globe, right eye','Maladies de l''œil et de ses annexes','H44.391'),
('autre degenerative disorders of globe, left eye','Other degenerative disorders of globe, left eye','Maladies de l''œil et de ses annexes','H44.392'),
('autre degenerative disorders of globe, bilateral','Other degenerative disorders of globe, bilateral','Maladies de l''œil et de ses annexes','H44.393'),
('autre degenerative disorders of globe, non spécifié eye','Other degenerative disorders of globe, unspecified eye','Maladies de l''œil et de ses annexes','H44.399'),
('non spécifié hypotony of eye','Unspecified hypotony of eye','Maladies de l''œil et de ses annexes','H44.40'),
('Flat anterior chamber hypotony of right eye','Flat anterior chamber hypotony of right eye','Maladies de l''œil et de ses annexes','H44.411'),
('Flat anterior chamber hypotony of left eye','Flat anterior chamber hypotony of left eye','Maladies de l''œil et de ses annexes','H44.412'),
('Flat anterior chamber hypotony of eye, bilateral','Flat anterior chamber hypotony of eye, bilateral','Maladies de l''œil et de ses annexes','H44.413'),
('Flat anterior chamber hypotony of non spécifié eye','Flat anterior chamber hypotony of unspecified eye','Maladies de l''œil et de ses annexes','H44.419'),
('Hypotony of right eye due to ocular fistula','Hypotony of right eye due to ocular fistula','Maladies de l''œil et de ses annexes','H44.421'),
('Hypotony of left eye due to ocular fistula','Hypotony of left eye due to ocular fistula','Maladies de l''œil et de ses annexes','H44.422'),
('Hypotony of eye due to ocular fistula, bilateral','Hypotony of eye due to ocular fistula, bilateral','Maladies de l''œil et de ses annexes','H44.423'),
('Hypotony of non spécifié eye due to ocular fistula','Hypotony of unspecified eye due to ocular fistula','Maladies de l''œil et de ses annexes','H44.429'),
('Hypotony of eye due to autre ocular disorders, right eye','Hypotony of eye due to other ocular disorders, right eye','Maladies de l''œil et de ses annexes','H44.431'),
('Hypotony of eye due to autre ocular disorders, left eye','Hypotony of eye due to other ocular disorders, left eye','Maladies de l''œil et de ses annexes','H44.432'),
('Hypotony of eye due to autre ocular disorders, bilateral','Hypotony of eye due to other ocular disorders, bilateral','Maladies de l''œil et de ses annexes','H44.433'),
('Hypotony of eye due to autre ocular disorders, non spécifié eye','Hypotony of eye due to other ocular disorders, unspecified eye','Maladies de l''œil et de ses annexes','H44.439'),
('primitif hypotony of right eye','Primary hypotony of right eye','Maladies de l''œil et de ses annexes','H44.441'),
('primitif hypotony of left eye','Primary hypotony of left eye','Maladies de l''œil et de ses annexes','H44.442'),
('primitif hypotony of eye, bilateral','Primary hypotony of eye, bilateral','Maladies de l''œil et de ses annexes','H44.443'),
('primitif hypotony of non spécifié eye','Primary hypotony of unspecified eye','Maladies de l''œil et de ses annexes','H44.449'),
('non spécifié degenerated conditions of globe','Unspecified degenerated conditions of globe','Maladies de l''œil et de ses annexes','H44.50'),
('Absolute glaucoma, right eye','Absolute glaucoma, right eye','Maladies de l''œil et de ses annexes','H44.511'),
('Absolute glaucoma, left eye','Absolute glaucoma, left eye','Maladies de l''œil et de ses annexes','H44.512'),
('Absolute glaucoma, bilateral','Absolute glaucoma, bilateral','Maladies de l''œil et de ses annexes','H44.513'),
('Absolute glaucoma, non spécifié eye','Absolute glaucoma, unspecified eye','Maladies de l''œil et de ses annexes','H44.519'),
('Atrophy of globe, right eye','Atrophy of globe, right eye','Maladies de l''œil et de ses annexes','H44.521'),
('Atrophy of globe, left eye','Atrophy of globe, left eye','Maladies de l''œil et de ses annexes','H44.522'),
('Atrophy of globe, bilateral','Atrophy of globe, bilateral','Maladies de l''œil et de ses annexes','H44.523'),
('Atrophy of globe, non spécifié eye','Atrophy of globe, unspecified eye','Maladies de l''œil et de ses annexes','H44.529'),
('Leucocoria, right eye','Leucocoria, right eye','Maladies de l''œil et de ses annexes','H44.531'),
('Leucocoria, left eye','Leucocoria, left eye','Maladies de l''œil et de ses annexes','H44.532'),
('Leucocoria, bilateral','Leucocoria, bilateral','Maladies de l''œil et de ses annexes','H44.533'),
('Leucocoria, non spécifié eye','Leucocoria, unspecified eye','Maladies de l''œil et de ses annexes','H44.539'),
('non spécifié retained (old) intraocular foreign body, magnetic, right eye','Unspecified retained (old) intraocular foreign body, magnetic, right eye','Maladies de l''œil et de ses annexes','H44.601'),
('non spécifié retained (old) intraocular foreign body, magnetic, left eye','Unspecified retained (old) intraocular foreign body, magnetic, left eye','Maladies de l''œil et de ses annexes','H44.602')
ON CONFLICT (nom_fr) DO NOTHING;
