-- icd10v2_batch_299.sql (80 rows)
INSERT INTO pathologies (nom_fr, nom_en, categorie, icd10_code)
VALUES
('Insect bite (nonvenomous) of non spécifié upper arm, sequela','Insect bite (nonvenomous) of unspecified upper arm, sequela','Traumatismes, empoisonnements et autres causes externes','S40.869S'),
('autre superficial bite of right upper arm, initial encounter','Other superficial bite of right upper arm, initial encounter','Traumatismes, empoisonnements et autres causes externes','S40.871A'),
('autre superficial bite of right upper arm, subsequent encounter','Other superficial bite of right upper arm, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S40.871D'),
('autre superficial bite of right upper arm, sequela','Other superficial bite of right upper arm, sequela','Traumatismes, empoisonnements et autres causes externes','S40.871S'),
('autre superficial bite of left upper arm, initial encounter','Other superficial bite of left upper arm, initial encounter','Traumatismes, empoisonnements et autres causes externes','S40.872A'),
('autre superficial bite of left upper arm, subsequent encounter','Other superficial bite of left upper arm, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S40.872D'),
('autre superficial bite of left upper arm, sequela','Other superficial bite of left upper arm, sequela','Traumatismes, empoisonnements et autres causes externes','S40.872S'),
('autre superficial bite of non spécifié upper arm, initial encounter','Other superficial bite of unspecified upper arm, initial encounter','Traumatismes, empoisonnements et autres causes externes','S40.879A'),
('autre superficial bite of non spécifié upper arm, subsequent encounter','Other superficial bite of unspecified upper arm, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S40.879D'),
('autre superficial bite of non spécifié upper arm, sequela','Other superficial bite of unspecified upper arm, sequela','Traumatismes, empoisonnements et autres causes externes','S40.879S'),
('non spécifié superficial injury of right shoulder, initial encounter','Unspecified superficial injury of right shoulder, initial encounter','Traumatismes, empoisonnements et autres causes externes','S40.911A'),
('non spécifié superficial injury of right shoulder, subsequent encounter','Unspecified superficial injury of right shoulder, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S40.911D'),
('non spécifié superficial injury of right shoulder, sequela','Unspecified superficial injury of right shoulder, sequela','Traumatismes, empoisonnements et autres causes externes','S40.911S'),
('non spécifié superficial injury of left shoulder, initial encounter','Unspecified superficial injury of left shoulder, initial encounter','Traumatismes, empoisonnements et autres causes externes','S40.912A'),
('non spécifié superficial injury of left shoulder, subsequent encounter','Unspecified superficial injury of left shoulder, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S40.912D'),
('non spécifié superficial injury of left shoulder, sequela','Unspecified superficial injury of left shoulder, sequela','Traumatismes, empoisonnements et autres causes externes','S40.912S'),
('non spécifié superficial injury of non spécifié shoulder, initial encounter','Unspecified superficial injury of unspecified shoulder, initial encounter','Traumatismes, empoisonnements et autres causes externes','S40.919A'),
('non spécifié superficial injury of non spécifié shoulder, subsequent encounter','Unspecified superficial injury of unspecified shoulder, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S40.919D'),
('non spécifié superficial injury of non spécifié shoulder, sequela','Unspecified superficial injury of unspecified shoulder, sequela','Traumatismes, empoisonnements et autres causes externes','S40.919S'),
('non spécifié superficial injury of right upper arm, initial encounter','Unspecified superficial injury of right upper arm, initial encounter','Traumatismes, empoisonnements et autres causes externes','S40.921A'),
('non spécifié superficial injury of right upper arm, subsequent encounter','Unspecified superficial injury of right upper arm, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S40.921D'),
('non spécifié superficial injury of right upper arm, sequela','Unspecified superficial injury of right upper arm, sequela','Traumatismes, empoisonnements et autres causes externes','S40.921S'),
('non spécifié superficial injury of left upper arm, initial encounter','Unspecified superficial injury of left upper arm, initial encounter','Traumatismes, empoisonnements et autres causes externes','S40.922A'),
('non spécifié superficial injury of left upper arm, subsequent encounter','Unspecified superficial injury of left upper arm, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S40.922D'),
('non spécifié superficial injury of left upper arm, sequela','Unspecified superficial injury of left upper arm, sequela','Traumatismes, empoisonnements et autres causes externes','S40.922S'),
('non spécifié superficial injury of non spécifié upper arm, initial encounter','Unspecified superficial injury of unspecified upper arm, initial encounter','Traumatismes, empoisonnements et autres causes externes','S40.929A'),
('non spécifié superficial injury of non spécifié upper arm, subsequent encounter','Unspecified superficial injury of unspecified upper arm, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S40.929D'),
('non spécifié superficial injury of non spécifié upper arm, sequela','Unspecified superficial injury of unspecified upper arm, sequela','Traumatismes, empoisonnements et autres causes externes','S40.929S'),
('non spécifié open wound of right shoulder, initial encounter','Unspecified open wound of right shoulder, initial encounter','Traumatismes, empoisonnements et autres causes externes','S41.001A'),
('non spécifié open wound of right shoulder, subsequent encounter','Unspecified open wound of right shoulder, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S41.001D'),
('non spécifié open wound of right shoulder, sequela','Unspecified open wound of right shoulder, sequela','Traumatismes, empoisonnements et autres causes externes','S41.001S'),
('non spécifié open wound of left shoulder, initial encounter','Unspecified open wound of left shoulder, initial encounter','Traumatismes, empoisonnements et autres causes externes','S41.002A'),
('non spécifié open wound of left shoulder, subsequent encounter','Unspecified open wound of left shoulder, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S41.002D'),
('non spécifié open wound of left shoulder, sequela','Unspecified open wound of left shoulder, sequela','Traumatismes, empoisonnements et autres causes externes','S41.002S'),
('non spécifié open wound of non spécifié shoulder, initial encounter','Unspecified open wound of unspecified shoulder, initial encounter','Traumatismes, empoisonnements et autres causes externes','S41.009A'),
('non spécifié open wound of non spécifié shoulder, subsequent encounter','Unspecified open wound of unspecified shoulder, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S41.009D'),
('non spécifié open wound of non spécifié shoulder, sequela','Unspecified open wound of unspecified shoulder, sequela','Traumatismes, empoisonnements et autres causes externes','S41.009S'),
('Laceration without foreign body of right shoulder, initial encounter','Laceration without foreign body of right shoulder, initial encounter','Traumatismes, empoisonnements et autres causes externes','S41.011A'),
('Laceration without foreign body of right shoulder, subsequent encounter','Laceration without foreign body of right shoulder, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S41.011D'),
('Laceration without foreign body of right shoulder, sequela','Laceration without foreign body of right shoulder, sequela','Traumatismes, empoisonnements et autres causes externes','S41.011S'),
('Laceration without foreign body of left shoulder, initial encounter','Laceration without foreign body of left shoulder, initial encounter','Traumatismes, empoisonnements et autres causes externes','S41.012A'),
('Laceration without foreign body of left shoulder, subsequent encounter','Laceration without foreign body of left shoulder, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S41.012D'),
('Laceration without foreign body of left shoulder, sequela','Laceration without foreign body of left shoulder, sequela','Traumatismes, empoisonnements et autres causes externes','S41.012S'),
('Laceration without foreign body of non spécifié shoulder, initial encounter','Laceration without foreign body of unspecified shoulder, initial encounter','Traumatismes, empoisonnements et autres causes externes','S41.019A'),
('Laceration without foreign body of non spécifié shoulder, subsequent encounter','Laceration without foreign body of unspecified shoulder, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S41.019D'),
('Laceration without foreign body of non spécifié shoulder, sequela','Laceration without foreign body of unspecified shoulder, sequela','Traumatismes, empoisonnements et autres causes externes','S41.019S'),
('Laceration with foreign body of right shoulder, initial encounter','Laceration with foreign body of right shoulder, initial encounter','Traumatismes, empoisonnements et autres causes externes','S41.021A'),
('Laceration with foreign body of right shoulder, subsequent encounter','Laceration with foreign body of right shoulder, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S41.021D'),
('Laceration with foreign body of right shoulder, sequela','Laceration with foreign body of right shoulder, sequela','Traumatismes, empoisonnements et autres causes externes','S41.021S'),
('Laceration with foreign body of left shoulder, initial encounter','Laceration with foreign body of left shoulder, initial encounter','Traumatismes, empoisonnements et autres causes externes','S41.022A'),
('Laceration with foreign body of left shoulder, subsequent encounter','Laceration with foreign body of left shoulder, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S41.022D'),
('Laceration with foreign body of left shoulder, sequela','Laceration with foreign body of left shoulder, sequela','Traumatismes, empoisonnements et autres causes externes','S41.022S'),
('Laceration with foreign body of non spécifié shoulder, initial encounter','Laceration with foreign body of unspecified shoulder, initial encounter','Traumatismes, empoisonnements et autres causes externes','S41.029A'),
('Laceration with foreign body of non spécifié shoulder, subsequent encounter','Laceration with foreign body of unspecified shoulder, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S41.029D'),
('Laceration with foreign body of non spécifié shoulder, sequela','Laceration with foreign body of unspecified shoulder, sequela','Traumatismes, empoisonnements et autres causes externes','S41.029S'),
('Puncture wound without foreign body of right shoulder, initial encounter','Puncture wound without foreign body of right shoulder, initial encounter','Traumatismes, empoisonnements et autres causes externes','S41.031A'),
('Puncture wound without foreign body of right shoulder, subsequent encounter','Puncture wound without foreign body of right shoulder, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S41.031D'),
('Puncture wound without foreign body of right shoulder, sequela','Puncture wound without foreign body of right shoulder, sequela','Traumatismes, empoisonnements et autres causes externes','S41.031S'),
('Puncture wound without foreign body of left shoulder, initial encounter','Puncture wound without foreign body of left shoulder, initial encounter','Traumatismes, empoisonnements et autres causes externes','S41.032A'),
('Puncture wound without foreign body of left shoulder, subsequent encounter','Puncture wound without foreign body of left shoulder, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S41.032D'),
('Puncture wound without foreign body of left shoulder, sequela','Puncture wound without foreign body of left shoulder, sequela','Traumatismes, empoisonnements et autres causes externes','S41.032S'),
('Puncture wound without foreign body of non spécifié shoulder, initial encounter','Puncture wound without foreign body of unspecified shoulder, initial encounter','Traumatismes, empoisonnements et autres causes externes','S41.039A'),
('Puncture wound without foreign body of non spécifié shoulder, subsequent encounter','Puncture wound without foreign body of unspecified shoulder, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S41.039D'),
('Puncture wound without foreign body of non spécifié shoulder, sequela','Puncture wound without foreign body of unspecified shoulder, sequela','Traumatismes, empoisonnements et autres causes externes','S41.039S'),
('Puncture wound with foreign body of right shoulder, initial encounter','Puncture wound with foreign body of right shoulder, initial encounter','Traumatismes, empoisonnements et autres causes externes','S41.041A'),
('Puncture wound with foreign body of right shoulder, subsequent encounter','Puncture wound with foreign body of right shoulder, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S41.041D'),
('Puncture wound with foreign body of right shoulder, sequela','Puncture wound with foreign body of right shoulder, sequela','Traumatismes, empoisonnements et autres causes externes','S41.041S'),
('Puncture wound with foreign body of left shoulder, initial encounter','Puncture wound with foreign body of left shoulder, initial encounter','Traumatismes, empoisonnements et autres causes externes','S41.042A'),
('Puncture wound with foreign body of left shoulder, subsequent encounter','Puncture wound with foreign body of left shoulder, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S41.042D'),
('Puncture wound with foreign body of left shoulder, sequela','Puncture wound with foreign body of left shoulder, sequela','Traumatismes, empoisonnements et autres causes externes','S41.042S'),
('Puncture wound with foreign body of non spécifié shoulder, initial encounter','Puncture wound with foreign body of unspecified shoulder, initial encounter','Traumatismes, empoisonnements et autres causes externes','S41.049A'),
('Puncture wound with foreign body of non spécifié shoulder, subsequent encounter','Puncture wound with foreign body of unspecified shoulder, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S41.049D'),
('Puncture wound with foreign body of non spécifié shoulder, sequela','Puncture wound with foreign body of unspecified shoulder, sequela','Traumatismes, empoisonnements et autres causes externes','S41.049S'),
('Open bite of right shoulder, initial encounter','Open bite of right shoulder, initial encounter','Traumatismes, empoisonnements et autres causes externes','S41.051A'),
('Open bite of right shoulder, subsequent encounter','Open bite of right shoulder, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S41.051D'),
('Open bite of right shoulder, sequela','Open bite of right shoulder, sequela','Traumatismes, empoisonnements et autres causes externes','S41.051S'),
('Open bite of left shoulder, initial encounter','Open bite of left shoulder, initial encounter','Traumatismes, empoisonnements et autres causes externes','S41.052A'),
('Open bite of left shoulder, subsequent encounter','Open bite of left shoulder, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S41.052D'),
('Open bite of left shoulder, sequela','Open bite of left shoulder, sequela','Traumatismes, empoisonnements et autres causes externes','S41.052S'),
('Open bite of non spécifié shoulder, initial encounter','Open bite of unspecified shoulder, initial encounter','Traumatismes, empoisonnements et autres causes externes','S41.059A')
ON CONFLICT (nom_fr) DO NOTHING;
