-- icd10v2_batch_219.sql (80 rows)
INSERT INTO pathologies (nom_fr, nom_en, categorie, icd10_code)
VALUES
('Cystocele, non spécifié','Cystocele, unspecified','Maladies de l''appareil génito-urinaire','N81.10'),
('Cystocele, midline','Cystocele, midline','Maladies de l''appareil génito-urinaire','N81.11'),
('Cystocele, lateral','Cystocele, lateral','Maladies de l''appareil génito-urinaire','N81.12'),
('Incomplete uterovaginal prolapse','Incomplete uterovaginal prolapse','Maladies de l''appareil génito-urinaire','N81.2'),
('Complete uterovaginal prolapse','Complete uterovaginal prolapse','Maladies de l''appareil génito-urinaire','N81.3'),
('Uterovaginal prolapse, non spécifié','Uterovaginal prolapse, unspecified','Maladies de l''appareil génito-urinaire','N81.4'),
('Vaginal enterocele','Vaginal enterocele','Maladies de l''appareil génito-urinaire','N81.5'),
('Rectocele','Rectocele','Maladies de l''appareil génito-urinaire','N81.6'),
('Perineocele','Perineocele','Maladies de l''appareil génito-urinaire','N81.81'),
('Incompetence or weakening of pubocervical tissue','Incompetence or weakening of pubocervical tissue','Maladies de l''appareil génito-urinaire','N81.82'),
('Incompetence or weakening of rectovaginal tissue','Incompetence or weakening of rectovaginal tissue','Maladies de l''appareil génito-urinaire','N81.83'),
('Pelvic muscle wasting','Pelvic muscle wasting','Maladies de l''appareil génito-urinaire','N81.84'),
('Cervical stump prolapse','Cervical stump prolapse','Maladies de l''appareil génito-urinaire','N81.85'),
('autre female genital prolapse','Other female genital prolapse','Maladies de l''appareil génito-urinaire','N81.89'),
('Female genital prolapse, non spécifié','Female genital prolapse, unspecified','Maladies de l''appareil génito-urinaire','N81.9'),
('Vesicovaginal fistula','Vesicovaginal fistula','Maladies de l''appareil génito-urinaire','N82.0'),
('autre female urinary-genital tract fistulae','Other female urinary-genital tract fistulae','Maladies de l''appareil génito-urinaire','N82.1'),
('Fistula of vagina to small intestine','Fistula of vagina to small intestine','Maladies de l''appareil génito-urinaire','N82.2'),
('Fistula of vagina to large intestine','Fistula of vagina to large intestine','Maladies de l''appareil génito-urinaire','N82.3'),
('autre female intestinal-genital tract fistulae','Other female intestinal-genital tract fistulae','Maladies de l''appareil génito-urinaire','N82.4'),
('Female genital tract-skin fistulae','Female genital tract-skin fistulae','Maladies de l''appareil génito-urinaire','N82.5'),
('autre female genital tract fistulae','Other female genital tract fistulae','Maladies de l''appareil génito-urinaire','N82.8'),
('Female genital tract fistula, non spécifié','Female genital tract fistula, unspecified','Maladies de l''appareil génito-urinaire','N82.9'),
('Follicular cyst of ovary, non spécifié side','Follicular cyst of ovary, unspecified side','Maladies de l''appareil génito-urinaire','N83.00'),
('Follicular cyst of right ovary','Follicular cyst of right ovary','Maladies de l''appareil génito-urinaire','N83.01'),
('Follicular cyst of left ovary','Follicular cyst of left ovary','Maladies de l''appareil génito-urinaire','N83.02'),
('Corpus luteum cyst of ovary, non spécifié side','Corpus luteum cyst of ovary, unspecified side','Maladies de l''appareil génito-urinaire','N83.10'),
('Corpus luteum cyst of right ovary','Corpus luteum cyst of right ovary','Maladies de l''appareil génito-urinaire','N83.11'),
('Corpus luteum cyst of left ovary','Corpus luteum cyst of left ovary','Maladies de l''appareil génito-urinaire','N83.12'),
('non spécifié ovarian cyst, right side','Unspecified ovarian cyst, right side','Maladies de l''appareil génito-urinaire','N83.201'),
('non spécifié ovarian cyst, left side','Unspecified ovarian cyst, left side','Maladies de l''appareil génito-urinaire','N83.202'),
('non spécifié ovarian cyst, non spécifié side','Unspecified ovarian cyst, unspecified side','Maladies de l''appareil génito-urinaire','N83.209'),
('autre ovarian cyst, right side','Other ovarian cyst, right side','Maladies de l''appareil génito-urinaire','N83.291'),
('autre ovarian cyst, left side','Other ovarian cyst, left side','Maladies de l''appareil génito-urinaire','N83.292'),
('autre ovarian cyst, non spécifié side','Other ovarian cyst, unspecified side','Maladies de l''appareil génito-urinaire','N83.299'),
('Acquired atrophy of right ovary','Acquired atrophy of right ovary','Maladies de l''appareil génito-urinaire','N83.311'),
('Acquired atrophy of left ovary','Acquired atrophy of left ovary','Maladies de l''appareil génito-urinaire','N83.312'),
('Acquired atrophy of ovary, non spécifié side','Acquired atrophy of ovary, unspecified side','Maladies de l''appareil génito-urinaire','N83.319'),
('Acquired atrophy of right fallopian tube','Acquired atrophy of right fallopian tube','Maladies de l''appareil génito-urinaire','N83.321'),
('Acquired atrophy of left fallopian tube','Acquired atrophy of left fallopian tube','Maladies de l''appareil génito-urinaire','N83.322'),
('Acquired atrophy of fallopian tube, non spécifié side','Acquired atrophy of fallopian tube, unspecified side','Maladies de l''appareil génito-urinaire','N83.329'),
('Acquired atrophy of right ovary and fallopian tube','Acquired atrophy of right ovary and fallopian tube','Maladies de l''appareil génito-urinaire','N83.331'),
('Acquired atrophy of left ovary and fallopian tube','Acquired atrophy of left ovary and fallopian tube','Maladies de l''appareil génito-urinaire','N83.332'),
('Acquired atrophy of ovary and fallopian tube, non spécifié side','Acquired atrophy of ovary and fallopian tube, unspecified side','Maladies de l''appareil génito-urinaire','N83.339'),
('Prolapse and hernia of ovary and fallopian tube, non spécifié side','Prolapse and hernia of ovary and fallopian tube, unspecified side','Maladies de l''appareil génito-urinaire','N83.40'),
('Prolapse and hernia of right ovary and fallopian tube','Prolapse and hernia of right ovary and fallopian tube','Maladies de l''appareil génito-urinaire','N83.41'),
('Prolapse and hernia of left ovary and fallopian tube','Prolapse and hernia of left ovary and fallopian tube','Maladies de l''appareil génito-urinaire','N83.42'),
('Torsion of right ovary and ovarian pedicle','Torsion of right ovary and ovarian pedicle','Maladies de l''appareil génito-urinaire','N83.511'),
('Torsion of left ovary and ovarian pedicle','Torsion of left ovary and ovarian pedicle','Maladies de l''appareil génito-urinaire','N83.512'),
('Torsion of ovary and ovarian pedicle, non spécifié side','Torsion of ovary and ovarian pedicle, unspecified side','Maladies de l''appareil génito-urinaire','N83.519'),
('Torsion of right fallopian tube','Torsion of right fallopian tube','Maladies de l''appareil génito-urinaire','N83.521'),
('Torsion of left fallopian tube','Torsion of left fallopian tube','Maladies de l''appareil génito-urinaire','N83.522'),
('Torsion of fallopian tube, non spécifié side','Torsion of fallopian tube, unspecified side','Maladies de l''appareil génito-urinaire','N83.529'),
('Torsion of ovary, ovarian pedicle and fallopian tube','Torsion of ovary, ovarian pedicle and fallopian tube','Maladies de l''appareil génito-urinaire','N83.53'),
('Hematosalpinx','Hematosalpinx','Maladies de l''appareil génito-urinaire','N83.6'),
('Hematoma of broad ligament','Hematoma of broad ligament','Maladies de l''appareil génito-urinaire','N83.7'),
('autre noninflammatory disorders of ovary, fallopian tube and broad ligament','Other noninflammatory disorders of ovary, fallopian tube and broad ligament','Maladies de l''appareil génito-urinaire','N83.8'),
('Noninflammatory trouble of ovary, fallopian tube and broad ligament, non spécifié','Noninflammatory disorder of ovary, fallopian tube and broad ligament, unspecified','Maladies de l''appareil génito-urinaire','N83.9'),
('Polyp of corpus uteri','Polyp of corpus uteri','Maladies de l''appareil génito-urinaire','N84.0'),
('Polyp of cervix uteri','Polyp of cervix uteri','Maladies de l''appareil génito-urinaire','N84.1'),
('Polyp of vagina','Polyp of vagina','Maladies de l''appareil génito-urinaire','N84.2'),
('Polyp of vulva','Polyp of vulva','Maladies de l''appareil génito-urinaire','N84.3'),
('Polyp of autre parts of female genital tract','Polyp of other parts of female genital tract','Maladies de l''appareil génito-urinaire','N84.8'),
('Polyp of female genital tract, non spécifié','Polyp of female genital tract, unspecified','Maladies de l''appareil génito-urinaire','N84.9'),
('Endometrial hyperplasia, non spécifié','Endometrial hyperplasia, unspecified','Maladies de l''appareil génito-urinaire','N85.00'),
('bénin endometrial hyperplasia','Benign endometrial hyperplasia','Maladies de l''appareil génito-urinaire','N85.01'),
('Endometrial intraepithelial neoplasia [EIN]','Endometrial intraepithelial neoplasia [EIN]','Maladies de l''appareil génito-urinaire','N85.02'),
('Hypertrophy of uterus','Hypertrophy of uterus','Maladies de l''appareil génito-urinaire','N85.2'),
('Subinvolution of uterus','Subinvolution of uterus','Maladies de l''appareil génito-urinaire','N85.3'),
('Malposition of uterus','Malposition of uterus','Maladies de l''appareil génito-urinaire','N85.4'),
('Inversion of uterus','Inversion of uterus','Maladies de l''appareil génito-urinaire','N85.5'),
('Intrauterine synechiae','Intrauterine synechiae','Maladies de l''appareil génito-urinaire','N85.6'),
('Hematometra','Hematometra','Maladies de l''appareil génito-urinaire','N85.7'),
('autre specified noninflammatory disorders of uterus','Other specified noninflammatory disorders of uterus','Maladies de l''appareil génito-urinaire','N85.8'),
('Noninflammatory trouble of uterus, non spécifié','Noninflammatory disorder of uterus, unspecified','Maladies de l''appareil génito-urinaire','N85.9'),
('Isthmocele','Isthmocele','Maladies de l''appareil génito-urinaire','N85.A'),
('Erosion and ectropion of cervix uteri','Erosion and ectropion of cervix uteri','Maladies de l''appareil génito-urinaire','N86'),
('Mild cervical dysplasia','Mild cervical dysplasia','Maladies de l''appareil génito-urinaire','N87.0'),
('Moderate cervical dysplasia','Moderate cervical dysplasia','Maladies de l''appareil génito-urinaire','N87.1'),
('Dysplasia of cervix uteri, non spécifié','Dysplasia of cervix uteri, unspecified','Maladies de l''appareil génito-urinaire','N87.9')
ON CONFLICT (nom_fr) DO NOTHING;
