-- icd10v2_batch_089.sql (80 rows)
INSERT INTO pathologies (nom_fr, nom_en, categorie, icd10_code)
VALUES
('Exudative cysts of iris or anterior chamber, non spécifié eye','Exudative cysts of iris or anterior chamber, unspecified eye','Maladies de l''œil et de ses annexes','H21.319'),
('Implantation cysts of iris, ciliary body or anterior chamber, right eye','Implantation cysts of iris, ciliary body or anterior chamber, right eye','Maladies de l''œil et de ses annexes','H21.321'),
('Implantation cysts of iris, ciliary body or anterior chamber, left eye','Implantation cysts of iris, ciliary body or anterior chamber, left eye','Maladies de l''œil et de ses annexes','H21.322'),
('Implantation cysts of iris, ciliary body or anterior chamber, bilateral','Implantation cysts of iris, ciliary body or anterior chamber, bilateral','Maladies de l''œil et de ses annexes','H21.323'),
('Implantation cysts of iris, ciliary body or anterior chamber, non spécifié eye','Implantation cysts of iris, ciliary body or anterior chamber, unspecified eye','Maladies de l''œil et de ses annexes','H21.329'),
('Parasitic cyst of iris, ciliary body or anterior chamber, right eye','Parasitic cyst of iris, ciliary body or anterior chamber, right eye','Maladies de l''œil et de ses annexes','H21.331'),
('Parasitic cyst of iris, ciliary body or anterior chamber, left eye','Parasitic cyst of iris, ciliary body or anterior chamber, left eye','Maladies de l''œil et de ses annexes','H21.332'),
('Parasitic cyst of iris, ciliary body or anterior chamber, bilateral','Parasitic cyst of iris, ciliary body or anterior chamber, bilateral','Maladies de l''œil et de ses annexes','H21.333'),
('Parasitic cyst of iris, ciliary body or anterior chamber, non spécifié eye','Parasitic cyst of iris, ciliary body or anterior chamber, unspecified eye','Maladies de l''œil et de ses annexes','H21.339'),
('primitif cyst of pars plana, right eye','Primary cyst of pars plana, right eye','Maladies de l''œil et de ses annexes','H21.341'),
('primitif cyst of pars plana, left eye','Primary cyst of pars plana, left eye','Maladies de l''œil et de ses annexes','H21.342'),
('primitif cyst of pars plana, bilateral','Primary cyst of pars plana, bilateral','Maladies de l''œil et de ses annexes','H21.343'),
('primitif cyst of pars plana, non spécifié eye','Primary cyst of pars plana, unspecified eye','Maladies de l''œil et de ses annexes','H21.349'),
('Exudative cyst of pars plana, right eye','Exudative cyst of pars plana, right eye','Maladies de l''œil et de ses annexes','H21.351'),
('Exudative cyst of pars plana, left eye','Exudative cyst of pars plana, left eye','Maladies de l''œil et de ses annexes','H21.352'),
('Exudative cyst of pars plana, bilateral','Exudative cyst of pars plana, bilateral','Maladies de l''œil et de ses annexes','H21.353'),
('Exudative cyst of pars plana, non spécifié eye','Exudative cyst of pars plana, unspecified eye','Maladies de l''œil et de ses annexes','H21.359'),
('Pupillary membranes, non spécifié eye','Pupillary membranes, unspecified eye','Maladies de l''œil et de ses annexes','H21.40'),
('Pupillary membranes, right eye','Pupillary membranes, right eye','Maladies de l''œil et de ses annexes','H21.41'),
('Pupillary membranes, left eye','Pupillary membranes, left eye','Maladies de l''œil et de ses annexes','H21.42'),
('Pupillary membranes, bilateral','Pupillary membranes, bilateral','Maladies de l''œil et de ses annexes','H21.43'),
('non spécifié adhesions of iris, right eye','Unspecified adhesions of iris, right eye','Maladies de l''œil et de ses annexes','H21.501'),
('non spécifié adhesions of iris, left eye','Unspecified adhesions of iris, left eye','Maladies de l''œil et de ses annexes','H21.502'),
('non spécifié adhesions of iris, bilateral','Unspecified adhesions of iris, bilateral','Maladies de l''œil et de ses annexes','H21.503'),
('non spécifié adhesions of iris and ciliary body, non spécifié eye','Unspecified adhesions of iris and ciliary body, unspecified eye','Maladies de l''œil et de ses annexes','H21.509'),
('Anterior synechiae (iris), right eye','Anterior synechiae (iris), right eye','Maladies de l''œil et de ses annexes','H21.511'),
('Anterior synechiae (iris), left eye','Anterior synechiae (iris), left eye','Maladies de l''œil et de ses annexes','H21.512'),
('Anterior synechiae (iris), bilateral','Anterior synechiae (iris), bilateral','Maladies de l''œil et de ses annexes','H21.513'),
('Anterior synechiae (iris), non spécifié eye','Anterior synechiae (iris), unspecified eye','Maladies de l''œil et de ses annexes','H21.519'),
('Goniosynechiae, right eye','Goniosynechiae, right eye','Maladies de l''œil et de ses annexes','H21.521'),
('Goniosynechiae, left eye','Goniosynechiae, left eye','Maladies de l''œil et de ses annexes','H21.522'),
('Goniosynechiae, bilateral','Goniosynechiae, bilateral','Maladies de l''œil et de ses annexes','H21.523'),
('Goniosynechiae, non spécifié eye','Goniosynechiae, unspecified eye','Maladies de l''œil et de ses annexes','H21.529'),
('Iridodialysis, right eye','Iridodialysis, right eye','Maladies de l''œil et de ses annexes','H21.531'),
('Iridodialysis, left eye','Iridodialysis, left eye','Maladies de l''œil et de ses annexes','H21.532'),
('Iridodialysis, bilateral','Iridodialysis, bilateral','Maladies de l''œil et de ses annexes','H21.533'),
('Iridodialysis, non spécifié eye','Iridodialysis, unspecified eye','Maladies de l''œil et de ses annexes','H21.539'),
('Posterior synechiae (iris), right eye','Posterior synechiae (iris), right eye','Maladies de l''œil et de ses annexes','H21.541'),
('Posterior synechiae (iris), left eye','Posterior synechiae (iris), left eye','Maladies de l''œil et de ses annexes','H21.542'),
('Posterior synechiae (iris), bilateral','Posterior synechiae (iris), bilateral','Maladies de l''œil et de ses annexes','H21.543'),
('Posterior synechiae (iris), non spécifié eye','Posterior synechiae (iris), unspecified eye','Maladies de l''œil et de ses annexes','H21.549'),
('Recession of chamber angle, right eye','Recession of chamber angle, right eye','Maladies de l''œil et de ses annexes','H21.551'),
('Recession of chamber angle, left eye','Recession of chamber angle, left eye','Maladies de l''œil et de ses annexes','H21.552'),
('Recession of chamber angle, bilateral','Recession of chamber angle, bilateral','Maladies de l''œil et de ses annexes','H21.553'),
('Recession of chamber angle, non spécifié eye','Recession of chamber angle, unspecified eye','Maladies de l''œil et de ses annexes','H21.559'),
('Pupillary abnormality, right eye','Pupillary abnormality, right eye','Maladies de l''œil et de ses annexes','H21.561'),
('Pupillary abnormality, left eye','Pupillary abnormality, left eye','Maladies de l''œil et de ses annexes','H21.562'),
('Pupillary abnormality, bilateral','Pupillary abnormality, bilateral','Maladies de l''œil et de ses annexes','H21.563'),
('Pupillary abnormality, non spécifié eye','Pupillary abnormality, unspecified eye','Maladies de l''œil et de ses annexes','H21.569'),
('Floppy iris syndrome','Floppy iris syndrome','Maladies de l''œil et de ses annexes','H21.81'),
('Plateau iris syndrome (post-iridectomy) (postprocedural)','Plateau iris syndrome (post-iridectomy) (postprocedural)','Maladies de l''œil et de ses annexes','H21.82'),
('autre specified disorders of iris and ciliary body','Other specified disorders of iris and ciliary body','Maladies de l''œil et de ses annexes','H21.89'),
('non spécifié trouble of iris and ciliary body','Unspecified disorder of iris and ciliary body','Maladies de l''œil et de ses annexes','H21.9'),
('Disorders of iris and ciliary body in diseases classified elsewhere','Disorders of iris and ciliary body in diseases classified elsewhere','Maladies de l''œil et de ses annexes','H22'),
('Cortical age-related cataract, right eye','Cortical age-related cataract, right eye','Maladies de l''œil et de ses annexes','H25.011'),
('Cortical age-related cataract, left eye','Cortical age-related cataract, left eye','Maladies de l''œil et de ses annexes','H25.012'),
('Cortical age-related cataract, bilateral','Cortical age-related cataract, bilateral','Maladies de l''œil et de ses annexes','H25.013'),
('Cortical age-related cataract, non spécifié eye','Cortical age-related cataract, unspecified eye','Maladies de l''œil et de ses annexes','H25.019'),
('Anterior subcapsular polar age-related cataract, right eye','Anterior subcapsular polar age-related cataract, right eye','Maladies de l''œil et de ses annexes','H25.031'),
('Anterior subcapsular polar age-related cataract, left eye','Anterior subcapsular polar age-related cataract, left eye','Maladies de l''œil et de ses annexes','H25.032'),
('Anterior subcapsular polar age-related cataract, bilateral','Anterior subcapsular polar age-related cataract, bilateral','Maladies de l''œil et de ses annexes','H25.033'),
('Anterior subcapsular polar age-related cataract, non spécifié eye','Anterior subcapsular polar age-related cataract, unspecified eye','Maladies de l''œil et de ses annexes','H25.039'),
('Posterior subcapsular polar age-related cataract, right eye','Posterior subcapsular polar age-related cataract, right eye','Maladies de l''œil et de ses annexes','H25.041'),
('Posterior subcapsular polar age-related cataract, left eye','Posterior subcapsular polar age-related cataract, left eye','Maladies de l''œil et de ses annexes','H25.042'),
('Posterior subcapsular polar age-related cataract, bilateral','Posterior subcapsular polar age-related cataract, bilateral','Maladies de l''œil et de ses annexes','H25.043'),
('Posterior subcapsular polar age-related cataract, non spécifié eye','Posterior subcapsular polar age-related cataract, unspecified eye','Maladies de l''œil et de ses annexes','H25.049'),
('autre age-related incipient cataract, right eye','Other age-related incipient cataract, right eye','Maladies de l''œil et de ses annexes','H25.091'),
('autre age-related incipient cataract, left eye','Other age-related incipient cataract, left eye','Maladies de l''œil et de ses annexes','H25.092'),
('autre age-related incipient cataract, bilateral','Other age-related incipient cataract, bilateral','Maladies de l''œil et de ses annexes','H25.093'),
('autre age-related incipient cataract, non spécifié eye','Other age-related incipient cataract, unspecified eye','Maladies de l''œil et de ses annexes','H25.099'),
('Age-related nuclear cataract, non spécifié eye','Age-related nuclear cataract, unspecified eye','Maladies de l''œil et de ses annexes','H25.10'),
('Age-related nuclear cataract, right eye','Age-related nuclear cataract, right eye','Maladies de l''œil et de ses annexes','H25.11'),
('Age-related nuclear cataract, left eye','Age-related nuclear cataract, left eye','Maladies de l''œil et de ses annexes','H25.12'),
('Age-related nuclear cataract, bilateral','Age-related nuclear cataract, bilateral','Maladies de l''œil et de ses annexes','H25.13'),
('Age-related cataract, morgagnian type, non spécifié eye','Age-related cataract, morgagnian type, unspecified eye','Maladies de l''œil et de ses annexes','H25.20'),
('Age-related cataract, morgagnian type, right eye','Age-related cataract, morgagnian type, right eye','Maladies de l''œil et de ses annexes','H25.21'),
('Age-related cataract, morgagnian type, left eye','Age-related cataract, morgagnian type, left eye','Maladies de l''œil et de ses annexes','H25.22'),
('Age-related cataract, morgagnian type, bilateral','Age-related cataract, morgagnian type, bilateral','Maladies de l''œil et de ses annexes','H25.23'),
('Combined forms of age-related cataract, right eye','Combined forms of age-related cataract, right eye','Maladies de l''œil et de ses annexes','H25.811'),
('Combined forms of age-related cataract, left eye','Combined forms of age-related cataract, left eye','Maladies de l''œil et de ses annexes','H25.812')
ON CONFLICT (nom_fr) DO NOTHING;
