-- icd10v2_batch_441.sql (80 rows)
INSERT INTO pathologies (nom_fr, nom_en, categorie, icd10_code)
VALUES
('Accidental striking against or bumped into by another person, initial encounter','Accidental striking against or bumped into by another person, initial encounter','Causes externes de morbidité et de mortalité','W51.XXXA'),
('Accidental striking against or bumped into by another person, subsequent encounter','Accidental striking against or bumped into by another person, subsequent encounter','Causes externes de morbidité et de mortalité','W51.XXXD'),
('Accidental striking against or bumped into by another person, sequela','Accidental striking against or bumped into by another person, sequela','Causes externes de morbidité et de mortalité','W51.XXXS'),
('Crushed, pushed or stepped on by crowd or human stampede, initial encounter','Crushed, pushed or stepped on by crowd or human stampede, initial encounter','Causes externes de morbidité et de mortalité','W52.XXXA'),
('Crushed, pushed or stepped on by crowd or human stampede, subsequent encounter','Crushed, pushed or stepped on by crowd or human stampede, subsequent encounter','Causes externes de morbidité et de mortalité','W52.XXXD'),
('Crushed, pushed or stepped on by crowd or human stampede, sequela','Crushed, pushed or stepped on by crowd or human stampede, sequela','Causes externes de morbidité et de mortalité','W52.XXXS'),
('Bitten by mouse, initial encounter','Bitten by mouse, initial encounter','Causes externes de morbidité et de mortalité','W53.01XA'),
('Bitten by mouse, subsequent encounter','Bitten by mouse, subsequent encounter','Causes externes de morbidité et de mortalité','W53.01XD'),
('Bitten by mouse, sequela','Bitten by mouse, sequela','Causes externes de morbidité et de mortalité','W53.01XS'),
('autre contact with mouse, initial encounter','Other contact with mouse, initial encounter','Causes externes de morbidité et de mortalité','W53.09XA'),
('autre contact with mouse, subsequent encounter','Other contact with mouse, subsequent encounter','Causes externes de morbidité et de mortalité','W53.09XD'),
('autre contact with mouse, sequela','Other contact with mouse, sequela','Causes externes de morbidité et de mortalité','W53.09XS'),
('Bitten by rat, initial encounter','Bitten by rat, initial encounter','Causes externes de morbidité et de mortalité','W53.11XA'),
('Bitten by rat, subsequent encounter','Bitten by rat, subsequent encounter','Causes externes de morbidité et de mortalité','W53.11XD'),
('Bitten by rat, sequela','Bitten by rat, sequela','Causes externes de morbidité et de mortalité','W53.11XS'),
('autre contact with rat, initial encounter','Other contact with rat, initial encounter','Causes externes de morbidité et de mortalité','W53.19XA'),
('autre contact with rat, subsequent encounter','Other contact with rat, subsequent encounter','Causes externes de morbidité et de mortalité','W53.19XD'),
('autre contact with rat, sequela','Other contact with rat, sequela','Causes externes de morbidité et de mortalité','W53.19XS'),
('Bitten by squirrel, initial encounter','Bitten by squirrel, initial encounter','Causes externes de morbidité et de mortalité','W53.21XA'),
('Bitten by squirrel, subsequent encounter','Bitten by squirrel, subsequent encounter','Causes externes de morbidité et de mortalité','W53.21XD'),
('Bitten by squirrel, sequela','Bitten by squirrel, sequela','Causes externes de morbidité et de mortalité','W53.21XS'),
('autre contact with squirrel, initial encounter','Other contact with squirrel, initial encounter','Causes externes de morbidité et de mortalité','W53.29XA'),
('autre contact with squirrel, subsequent encounter','Other contact with squirrel, subsequent encounter','Causes externes de morbidité et de mortalité','W53.29XD'),
('autre contact with squirrel, sequela','Other contact with squirrel, sequela','Causes externes de morbidité et de mortalité','W53.29XS'),
('Bitten by autre rodent, initial encounter','Bitten by other rodent, initial encounter','Causes externes de morbidité et de mortalité','W53.81XA'),
('Bitten by autre rodent, subsequent encounter','Bitten by other rodent, subsequent encounter','Causes externes de morbidité et de mortalité','W53.81XD'),
('Bitten by autre rodent, sequela','Bitten by other rodent, sequela','Causes externes de morbidité et de mortalité','W53.81XS'),
('autre contact with autre rodent, initial encounter','Other contact with other rodent, initial encounter','Causes externes de morbidité et de mortalité','W53.89XA'),
('autre contact with autre rodent, subsequent encounter','Other contact with other rodent, subsequent encounter','Causes externes de morbidité et de mortalité','W53.89XD'),
('autre contact with autre rodent, sequela','Other contact with other rodent, sequela','Causes externes de morbidité et de mortalité','W53.89XS'),
('Bitten by dog, initial encounter','Bitten by dog, initial encounter','Causes externes de morbidité et de mortalité','W54.0XXA'),
('Bitten by dog, subsequent encounter','Bitten by dog, subsequent encounter','Causes externes de morbidité et de mortalité','W54.0XXD'),
('Bitten by dog, sequela','Bitten by dog, sequela','Causes externes de morbidité et de mortalité','W54.0XXS'),
('Struck by dog, initial encounter','Struck by dog, initial encounter','Causes externes de morbidité et de mortalité','W54.1XXA'),
('Struck by dog, subsequent encounter','Struck by dog, subsequent encounter','Causes externes de morbidité et de mortalité','W54.1XXD'),
('Struck by dog, sequela','Struck by dog, sequela','Causes externes de morbidité et de mortalité','W54.1XXS'),
('autre contact with dog, initial encounter','Other contact with dog, initial encounter','Causes externes de morbidité et de mortalité','W54.8XXA'),
('autre contact with dog, subsequent encounter','Other contact with dog, subsequent encounter','Causes externes de morbidité et de mortalité','W54.8XXD'),
('autre contact with dog, sequela','Other contact with dog, sequela','Causes externes de morbidité et de mortalité','W54.8XXS'),
('Bitten by cat, initial encounter','Bitten by cat, initial encounter','Causes externes de morbidité et de mortalité','W55.01XA'),
('Bitten by cat, subsequent encounter','Bitten by cat, subsequent encounter','Causes externes de morbidité et de mortalité','W55.01XD'),
('Bitten by cat, sequela','Bitten by cat, sequela','Causes externes de morbidité et de mortalité','W55.01XS'),
('Scratched by cat, initial encounter','Scratched by cat, initial encounter','Causes externes de morbidité et de mortalité','W55.03XA'),
('Scratched by cat, subsequent encounter','Scratched by cat, subsequent encounter','Causes externes de morbidité et de mortalité','W55.03XD'),
('Scratched by cat, sequela','Scratched by cat, sequela','Causes externes de morbidité et de mortalité','W55.03XS'),
('autre contact with cat, initial encounter','Other contact with cat, initial encounter','Causes externes de morbidité et de mortalité','W55.09XA'),
('autre contact with cat, subsequent encounter','Other contact with cat, subsequent encounter','Causes externes de morbidité et de mortalité','W55.09XD'),
('autre contact with cat, sequela','Other contact with cat, sequela','Causes externes de morbidité et de mortalité','W55.09XS'),
('Bitten by horse, initial encounter','Bitten by horse, initial encounter','Causes externes de morbidité et de mortalité','W55.11XA'),
('Bitten by horse, subsequent encounter','Bitten by horse, subsequent encounter','Causes externes de morbidité et de mortalité','W55.11XD'),
('Bitten by horse, sequela','Bitten by horse, sequela','Causes externes de morbidité et de mortalité','W55.11XS'),
('Struck by horse, initial encounter','Struck by horse, initial encounter','Causes externes de morbidité et de mortalité','W55.12XA'),
('Struck by horse, subsequent encounter','Struck by horse, subsequent encounter','Causes externes de morbidité et de mortalité','W55.12XD'),
('Struck by horse, sequela','Struck by horse, sequela','Causes externes de morbidité et de mortalité','W55.12XS'),
('autre contact with horse, initial encounter','Other contact with horse, initial encounter','Causes externes de morbidité et de mortalité','W55.19XA'),
('autre contact with horse, subsequent encounter','Other contact with horse, subsequent encounter','Causes externes de morbidité et de mortalité','W55.19XD'),
('autre contact with horse, sequela','Other contact with horse, sequela','Causes externes de morbidité et de mortalité','W55.19XS'),
('Bitten by cow, initial encounter','Bitten by cow, initial encounter','Causes externes de morbidité et de mortalité','W55.21XA'),
('Bitten by cow, subsequent encounter','Bitten by cow, subsequent encounter','Causes externes de morbidité et de mortalité','W55.21XD'),
('Bitten by cow, sequela','Bitten by cow, sequela','Causes externes de morbidité et de mortalité','W55.21XS'),
('Struck by cow, initial encounter','Struck by cow, initial encounter','Causes externes de morbidité et de mortalité','W55.22XA'),
('Struck by cow, subsequent encounter','Struck by cow, subsequent encounter','Causes externes de morbidité et de mortalité','W55.22XD'),
('Struck by cow, sequela','Struck by cow, sequela','Causes externes de morbidité et de mortalité','W55.22XS'),
('autre contact with cow, initial encounter','Other contact with cow, initial encounter','Causes externes de morbidité et de mortalité','W55.29XA'),
('autre contact with cow, subsequent encounter','Other contact with cow, subsequent encounter','Causes externes de morbidité et de mortalité','W55.29XD'),
('autre contact with cow, sequela','Other contact with cow, sequela','Causes externes de morbidité et de mortalité','W55.29XS'),
('Bitten by autre hoof stock, initial encounter','Bitten by other hoof stock, initial encounter','Causes externes de morbidité et de mortalité','W55.31XA'),
('Bitten by autre hoof stock, subsequent encounter','Bitten by other hoof stock, subsequent encounter','Causes externes de morbidité et de mortalité','W55.31XD'),
('Bitten by autre hoof stock, sequela','Bitten by other hoof stock, sequela','Causes externes de morbidité et de mortalité','W55.31XS'),
('Struck by autre hoof stock, initial encounter','Struck by other hoof stock, initial encounter','Causes externes de morbidité et de mortalité','W55.32XA'),
('Struck by autre hoof stock, subsequent encounter','Struck by other hoof stock, subsequent encounter','Causes externes de morbidité et de mortalité','W55.32XD'),
('Struck by autre hoof stock, sequela','Struck by other hoof stock, sequela','Causes externes de morbidité et de mortalité','W55.32XS'),
('autre contact with autre hoof stock, initial encounter','Other contact with other hoof stock, initial encounter','Causes externes de morbidité et de mortalité','W55.39XA'),
('autre contact with autre hoof stock, subsequent encounter','Other contact with other hoof stock, subsequent encounter','Causes externes de morbidité et de mortalité','W55.39XD'),
('autre contact with autre hoof stock, sequela','Other contact with other hoof stock, sequela','Causes externes de morbidité et de mortalité','W55.39XS'),
('Bitten by pig, initial encounter','Bitten by pig, initial encounter','Causes externes de morbidité et de mortalité','W55.41XA'),
('Bitten by pig, subsequent encounter','Bitten by pig, subsequent encounter','Causes externes de morbidité et de mortalité','W55.41XD'),
('Bitten by pig, sequela','Bitten by pig, sequela','Causes externes de morbidité et de mortalité','W55.41XS'),
('Struck by pig, initial encounter','Struck by pig, initial encounter','Causes externes de morbidité et de mortalité','W55.42XA'),
('Struck by pig, subsequent encounter','Struck by pig, subsequent encounter','Causes externes de morbidité et de mortalité','W55.42XD')
ON CONFLICT (nom_fr) DO NOTHING;
