-- icd10v2_batch_278.sql (80 rows)
INSERT INTO pathologies (nom_fr, nom_en, categorie, icd10_code)
VALUES
('Puncture wound without foreign body of left cheek and temporomandibular area, sequela','Puncture wound without foreign body of left cheek and temporomandibular area, sequela','Traumatismes, empoisonnements et autres causes externes','S01.432S'),
('Puncture wound without foreign body of non spécifié cheek and temporomandibular area, initial encounter','Puncture wound without foreign body of unspecified cheek and temporomandibular area, initial encounter','Traumatismes, empoisonnements et autres causes externes','S01.439A'),
('Puncture wound without foreign body of non spécifié cheek and temporomandibular area, subsequent encounter','Puncture wound without foreign body of unspecified cheek and temporomandibular area, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S01.439D'),
('Puncture wound without foreign body of non spécifié cheek and temporomandibular area, sequela','Puncture wound without foreign body of unspecified cheek and temporomandibular area, sequela','Traumatismes, empoisonnements et autres causes externes','S01.439S'),
('Puncture wound with foreign body of right cheek and temporomandibular area, initial encounter','Puncture wound with foreign body of right cheek and temporomandibular area, initial encounter','Traumatismes, empoisonnements et autres causes externes','S01.441A'),
('Puncture wound with foreign body of right cheek and temporomandibular area, subsequent encounter','Puncture wound with foreign body of right cheek and temporomandibular area, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S01.441D'),
('Puncture wound with foreign body of right cheek and temporomandibular area, sequela','Puncture wound with foreign body of right cheek and temporomandibular area, sequela','Traumatismes, empoisonnements et autres causes externes','S01.441S'),
('Puncture wound with foreign body of left cheek and temporomandibular area, initial encounter','Puncture wound with foreign body of left cheek and temporomandibular area, initial encounter','Traumatismes, empoisonnements et autres causes externes','S01.442A'),
('Puncture wound with foreign body of left cheek and temporomandibular area, subsequent encounter','Puncture wound with foreign body of left cheek and temporomandibular area, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S01.442D'),
('Puncture wound with foreign body of left cheek and temporomandibular area, sequela','Puncture wound with foreign body of left cheek and temporomandibular area, sequela','Traumatismes, empoisonnements et autres causes externes','S01.442S'),
('Puncture wound with foreign body of non spécifié cheek and temporomandibular area, initial encounter','Puncture wound with foreign body of unspecified cheek and temporomandibular area, initial encounter','Traumatismes, empoisonnements et autres causes externes','S01.449A'),
('Puncture wound with foreign body of non spécifié cheek and temporomandibular area, subsequent encounter','Puncture wound with foreign body of unspecified cheek and temporomandibular area, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S01.449D'),
('Puncture wound with foreign body of non spécifié cheek and temporomandibular area, sequela','Puncture wound with foreign body of unspecified cheek and temporomandibular area, sequela','Traumatismes, empoisonnements et autres causes externes','S01.449S'),
('Open bite of right cheek and temporomandibular area, initial encounter','Open bite of right cheek and temporomandibular area, initial encounter','Traumatismes, empoisonnements et autres causes externes','S01.451A'),
('Open bite of right cheek and temporomandibular area, subsequent encounter','Open bite of right cheek and temporomandibular area, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S01.451D'),
('Open bite of right cheek and temporomandibular area, sequela','Open bite of right cheek and temporomandibular area, sequela','Traumatismes, empoisonnements et autres causes externes','S01.451S'),
('Open bite of left cheek and temporomandibular area, initial encounter','Open bite of left cheek and temporomandibular area, initial encounter','Traumatismes, empoisonnements et autres causes externes','S01.452A'),
('Open bite of left cheek and temporomandibular area, subsequent encounter','Open bite of left cheek and temporomandibular area, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S01.452D'),
('Open bite of left cheek and temporomandibular area, sequela','Open bite of left cheek and temporomandibular area, sequela','Traumatismes, empoisonnements et autres causes externes','S01.452S'),
('Open bite of non spécifié cheek and temporomandibular area, initial encounter','Open bite of unspecified cheek and temporomandibular area, initial encounter','Traumatismes, empoisonnements et autres causes externes','S01.459A'),
('Open bite of non spécifié cheek and temporomandibular area, subsequent encounter','Open bite of unspecified cheek and temporomandibular area, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S01.459D'),
('Open bite of non spécifié cheek and temporomandibular area, sequela','Open bite of unspecified cheek and temporomandibular area, sequela','Traumatismes, empoisonnements et autres causes externes','S01.459S'),
('non spécifié open wound of lip, initial encounter','Unspecified open wound of lip, initial encounter','Traumatismes, empoisonnements et autres causes externes','S01.501A'),
('non spécifié open wound of lip, subsequent encounter','Unspecified open wound of lip, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S01.501D'),
('non spécifié open wound of lip, sequela','Unspecified open wound of lip, sequela','Traumatismes, empoisonnements et autres causes externes','S01.501S'),
('non spécifié open wound of oral cavity, initial encounter','Unspecified open wound of oral cavity, initial encounter','Traumatismes, empoisonnements et autres causes externes','S01.502A'),
('non spécifié open wound of oral cavity, subsequent encounter','Unspecified open wound of oral cavity, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S01.502D'),
('non spécifié open wound of oral cavity, sequela','Unspecified open wound of oral cavity, sequela','Traumatismes, empoisonnements et autres causes externes','S01.502S'),
('Laceration without foreign body of lip, initial encounter','Laceration without foreign body of lip, initial encounter','Traumatismes, empoisonnements et autres causes externes','S01.511A'),
('Laceration without foreign body of lip, subsequent encounter','Laceration without foreign body of lip, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S01.511D'),
('Laceration without foreign body of lip, sequela','Laceration without foreign body of lip, sequela','Traumatismes, empoisonnements et autres causes externes','S01.511S'),
('Laceration without foreign body of oral cavity, initial encounter','Laceration without foreign body of oral cavity, initial encounter','Traumatismes, empoisonnements et autres causes externes','S01.512A'),
('Laceration without foreign body of oral cavity, subsequent encounter','Laceration without foreign body of oral cavity, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S01.512D'),
('Laceration without foreign body of oral cavity, sequela','Laceration without foreign body of oral cavity, sequela','Traumatismes, empoisonnements et autres causes externes','S01.512S'),
('Laceration with foreign body of lip, initial encounter','Laceration with foreign body of lip, initial encounter','Traumatismes, empoisonnements et autres causes externes','S01.521A'),
('Laceration with foreign body of lip, subsequent encounter','Laceration with foreign body of lip, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S01.521D'),
('Laceration with foreign body of lip, sequela','Laceration with foreign body of lip, sequela','Traumatismes, empoisonnements et autres causes externes','S01.521S'),
('Laceration with foreign body of oral cavity, initial encounter','Laceration with foreign body of oral cavity, initial encounter','Traumatismes, empoisonnements et autres causes externes','S01.522A'),
('Laceration with foreign body of oral cavity, subsequent encounter','Laceration with foreign body of oral cavity, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S01.522D'),
('Laceration with foreign body of oral cavity, sequela','Laceration with foreign body of oral cavity, sequela','Traumatismes, empoisonnements et autres causes externes','S01.522S'),
('Puncture wound without foreign body of lip, initial encounter','Puncture wound without foreign body of lip, initial encounter','Traumatismes, empoisonnements et autres causes externes','S01.531A'),
('Puncture wound without foreign body of lip, subsequent encounter','Puncture wound without foreign body of lip, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S01.531D'),
('Puncture wound without foreign body of lip, sequela','Puncture wound without foreign body of lip, sequela','Traumatismes, empoisonnements et autres causes externes','S01.531S'),
('Contusion of throat, initial encounter','Contusion of throat, initial encounter','Traumatismes, empoisonnements et autres causes externes','S10.0XXA'),
('Contusion of throat, subsequent encounter','Contusion of throat, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S10.0XXD'),
('Contusion of throat, sequela','Contusion of throat, sequela','Traumatismes, empoisonnements et autres causes externes','S10.0XXS'),
('non spécifié superficial injuries of throat, initial encounter','Unspecified superficial injuries of throat, initial encounter','Traumatismes, empoisonnements et autres causes externes','S10.10XA'),
('non spécifié superficial injuries of throat, subsequent encounter','Unspecified superficial injuries of throat, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S10.10XD'),
('non spécifié superficial injuries of throat, sequela','Unspecified superficial injuries of throat, sequela','Traumatismes, empoisonnements et autres causes externes','S10.10XS'),
('Abrasion of throat, initial encounter','Abrasion of throat, initial encounter','Traumatismes, empoisonnements et autres causes externes','S10.11XA'),
('Abrasion of throat, subsequent encounter','Abrasion of throat, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S10.11XD'),
('Abrasion of throat, sequela','Abrasion of throat, sequela','Traumatismes, empoisonnements et autres causes externes','S10.11XS'),
('Blister (nonthermal) of throat, initial encounter','Blister (nonthermal) of throat, initial encounter','Traumatismes, empoisonnements et autres causes externes','S10.12XA'),
('Blister (nonthermal) of throat, subsequent encounter','Blister (nonthermal) of throat, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S10.12XD'),
('Blister (nonthermal) of throat, sequela','Blister (nonthermal) of throat, sequela','Traumatismes, empoisonnements et autres causes externes','S10.12XS'),
('External constriction of part of throat, initial encounter','External constriction of part of throat, initial encounter','Traumatismes, empoisonnements et autres causes externes','S10.14XA'),
('External constriction of part of throat, subsequent encounter','External constriction of part of throat, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S10.14XD'),
('External constriction of part of throat, sequela','External constriction of part of throat, sequela','Traumatismes, empoisonnements et autres causes externes','S10.14XS'),
('Superficial foreign body of throat, initial encounter','Superficial foreign body of throat, initial encounter','Traumatismes, empoisonnements et autres causes externes','S10.15XA'),
('Superficial foreign body of throat, subsequent encounter','Superficial foreign body of throat, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S10.15XD'),
('Superficial foreign body of throat, sequela','Superficial foreign body of throat, sequela','Traumatismes, empoisonnements et autres causes externes','S10.15XS'),
('Insect bite (nonvenomous) of throat, initial encounter','Insect bite (nonvenomous) of throat, initial encounter','Traumatismes, empoisonnements et autres causes externes','S10.16XA'),
('Insect bite (nonvenomous) of throat, subsequent encounter','Insect bite (nonvenomous) of throat, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S10.16XD'),
('Insect bite (nonvenomous) of throat, sequela','Insect bite (nonvenomous) of throat, sequela','Traumatismes, empoisonnements et autres causes externes','S10.16XS'),
('autre superficial bite of throat, initial encounter','Other superficial bite of throat, initial encounter','Traumatismes, empoisonnements et autres causes externes','S10.17XA'),
('autre superficial bite of throat, subsequent encounter','Other superficial bite of throat, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S10.17XD'),
('autre superficial bite of throat, sequela','Other superficial bite of throat, sequela','Traumatismes, empoisonnements et autres causes externes','S10.17XS'),
('non spécifié superficial injury of autre specified part of neck, initial encounter','Unspecified superficial injury of other specified part of neck, initial encounter','Traumatismes, empoisonnements et autres causes externes','S10.80XA'),
('non spécifié superficial injury of autre specified part of neck, subsequent encounter','Unspecified superficial injury of other specified part of neck, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S10.80XD'),
('non spécifié superficial injury of autre specified part of neck, sequela','Unspecified superficial injury of other specified part of neck, sequela','Traumatismes, empoisonnements et autres causes externes','S10.80XS'),
('Abrasion of autre specified part of neck, initial encounter','Abrasion of other specified part of neck, initial encounter','Traumatismes, empoisonnements et autres causes externes','S10.81XA'),
('Abrasion of autre specified part of neck, subsequent encounter','Abrasion of other specified part of neck, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S10.81XD'),
('Abrasion of autre specified part of neck, sequela','Abrasion of other specified part of neck, sequela','Traumatismes, empoisonnements et autres causes externes','S10.81XS'),
('Blister (nonthermal) of autre specified part of neck, initial encounter','Blister (nonthermal) of other specified part of neck, initial encounter','Traumatismes, empoisonnements et autres causes externes','S10.82XA'),
('Blister (nonthermal) of autre specified part of neck, subsequent encounter','Blister (nonthermal) of other specified part of neck, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S10.82XD'),
('Blister (nonthermal) of autre specified part of neck, sequela','Blister (nonthermal) of other specified part of neck, sequela','Traumatismes, empoisonnements et autres causes externes','S10.82XS'),
('Contusion of autre specified part of neck, initial encounter','Contusion of other specified part of neck, initial encounter','Traumatismes, empoisonnements et autres causes externes','S10.83XA'),
('Contusion of autre specified part of neck, subsequent encounter','Contusion of other specified part of neck, subsequent encounter','Traumatismes, empoisonnements et autres causes externes','S10.83XD'),
('Contusion of autre specified part of neck, sequela','Contusion of other specified part of neck, sequela','Traumatismes, empoisonnements et autres causes externes','S10.83XS'),
('External constriction of autre specified part of neck, initial encounter','External constriction of other specified part of neck, initial encounter','Traumatismes, empoisonnements et autres causes externes','S10.84XA')
ON CONFLICT (nom_fr) DO NOTHING;
