-- icd10_batch_019.sql (80 rows)
INSERT INTO pathologies (nom_fr, nom_en, categorie, icd10_code)
VALUES
('Unrepairable overhanging of dental restorative materials','Unrepairable overhanging of dental restorative materials','Maladies de l''appareil digestif','K08.52'),
('Fractured dental restorative material without loss of material','Fractured dental restorative material without loss of material','Maladies de l''appareil digestif','K08.530'),
('Fractured dental restorative material with loss of material','Fractured dental restorative material with loss of material','Maladies de l''appareil digestif','K08.531'),
('Fractured dental restorative material, non spécifié','Fractured dental restorative material, unspecified','Maladies de l''appareil digestif','K08.539'),
('Contour of existing restoration of tooth biologically incompatible with oral health','Contour of existing restoration of tooth biologically incompatible with oral health','Maladies de l''appareil digestif','K08.54'),
('Allergy to existing dental restorative material','Allergy to existing dental restorative material','Maladies de l''appareil digestif','K08.55'),
('Poor aesthetic of existing restoration of tooth','Poor aesthetic of existing restoration of tooth','Maladies de l''appareil digestif','K08.56'),
('autre unsatisfactory restoration of tooth','Other unsatisfactory restoration of tooth','Maladies de l''appareil digestif','K08.59'),
('primitif occlusal trauma','Primary occlusal trauma','Maladies de l''appareil digestif','K08.81'),
('secondaire occlusal trauma','Secondary occlusal trauma','Maladies de l''appareil digestif','K08.82'),
('autre specified disorders of teeth and supporting structures','Other specified disorders of teeth and supporting structures','Maladies de l''appareil digestif','K08.89'),
('trouble of teeth and supporting structures, non spécifié','Disorder of teeth and supporting structures, unspecified','Maladies de l''appareil digestif','K08.9'),
('Developmental odontogenic cysts','Developmental odontogenic cysts','Maladies de l''appareil digestif','K09.0'),
('Developmental (nonodontogenic) cysts of oral region','Developmental (nonodontogenic) cysts of oral region','Maladies de l''appareil digestif','K09.1'),
('autre cysts of oral region, not elsewhere classified','Other cysts of oral region, not elsewhere classified','Maladies de l''appareil digestif','K09.8'),
('Cyst of oral region, non spécifié','Cyst of oral region, unspecified','Maladies de l''appareil digestif','K09.9'),
('Atrophy of salivary gland','Atrophy of salivary gland','Maladies de l''appareil digestif','K11.0'),
('Hypertrophy of salivary gland','Hypertrophy of salivary gland','Maladies de l''appareil digestif','K11.1'),
('Sialoadenitis, non spécifié','Sialoadenitis, unspecified','Maladies de l''appareil digestif','K11.20'),
('aigu sialoadenitis','Acute sialoadenitis','Maladies de l''appareil digestif','K11.21'),
('aigu recurrent sialoadenitis','Acute recurrent sialoadenitis','Maladies de l''appareil digestif','K11.22'),
('chronique sialoadenitis','Chronic sialoadenitis','Maladies de l''appareil digestif','K11.23'),
('Abscess of salivary gland','Abscess of salivary gland','Maladies de l''appareil digestif','K11.3'),
('Fistula of salivary gland','Fistula of salivary gland','Maladies de l''appareil digestif','K11.4'),
('Sialolithiasis','Sialolithiasis','Maladies de l''appareil digestif','K11.5'),
('Mucocele of salivary gland','Mucocele of salivary gland','Maladies de l''appareil digestif','K11.6'),
('Disturbances of salivary secretion','Disturbances of salivary secretion','Maladies de l''appareil digestif','K11.7'),
('autre diseases of salivary glands','Other diseases of salivary glands','Maladies de l''appareil digestif','K11.8'),
('maladie of salivary gland, non spécifié','Disease of salivary gland, unspecified','Maladies de l''appareil digestif','K11.9'),
('Recurrent oral aphthae','Recurrent oral aphthae','Maladies de l''appareil digestif','K12.0'),
('autre forms of stomatitis','Other forms of stomatitis','Maladies de l''appareil digestif','K12.1'),
('Cellulite infectieuse, and abscess of mouth','Cellulitis and abscess of mouth','Maladies de l''appareil digestif','K12.2'),
('Oral mucositis (ulcerative), non spécifié','Oral mucositis (ulcerative), unspecified','Maladies de l''appareil digestif','K12.30'),
('Oral mucositis (ulcerative) due to antineoplastic therapy','Oral mucositis (ulcerative) due to antineoplastic therapy','Maladies de l''appareil digestif','K12.31'),
('Oral mucositis (ulcerative) due to autre drugs','Oral mucositis (ulcerative) due to other drugs','Maladies de l''appareil digestif','K12.32'),
('Oral mucositis (ulcerative) due to radiation','Oral mucositis (ulcerative) due to radiation','Maladies de l''appareil digestif','K12.33'),
('autre oral mucositis (ulcerative)','Other oral mucositis (ulcerative)','Maladies de l''appareil digestif','K12.39'),
('Diseases of lips','Diseases of lips','Maladies de l''appareil digestif','K13.0'),
('Cheek and lip biting','Cheek and lip biting','Maladies de l''appareil digestif','K13.1'),
('Leukoplakia of oral mucosa, including tongue','Leukoplakia of oral mucosa, including tongue','Maladies de l''appareil digestif','K13.21'),
('Minimal keratinized residual ridge mucosa','Minimal keratinized residual ridge mucosa','Maladies de l''appareil digestif','K13.22'),
('Excessive keratinized residual ridge mucosa','Excessive keratinized residual ridge mucosa','Maladies de l''appareil digestif','K13.23'),
('Leukokeratosis nicotina palati','Leukokeratosis nicotina palati','Maladies de l''appareil digestif','K13.24'),
('autre disturbances of oral epithelium, including tongue','Other disturbances of oral epithelium, including tongue','Maladies de l''appareil digestif','K13.29'),
('Hairy leukoplakia','Hairy leukoplakia','Maladies de l''appareil digestif','K13.3'),
('Granuloma and granuloma-like lesions of oral mucosa','Granuloma and granuloma-like lesions of oral mucosa','Maladies de l''appareil digestif','K13.4'),
('Oral submucous fibrosis','Oral submucous fibrosis','Maladies de l''appareil digestif','K13.5'),
('Irritative hyperplasia of oral mucosa','Irritative hyperplasia of oral mucosa','Maladies de l''appareil digestif','K13.6'),
('non spécifié lesions of oral mucosa','Unspecified lesions of oral mucosa','Maladies de l''appareil digestif','K13.70'),
('autre lesions of oral mucosa','Other lesions of oral mucosa','Maladies de l''appareil digestif','K13.79'),
('Glossitis','Glossitis','Maladies de l''appareil digestif','K14.0'),
('Geographic tongue','Geographic tongue','Maladies de l''appareil digestif','K14.1'),
('Median rhomboid glossitis','Median rhomboid glossitis','Maladies de l''appareil digestif','K14.2'),
('Hypertrophy of tongue papillae','Hypertrophy of tongue papillae','Maladies de l''appareil digestif','K14.3'),
('Atrophy of tongue papillae','Atrophy of tongue papillae','Maladies de l''appareil digestif','K14.4'),
('Plicated tongue','Plicated tongue','Maladies de l''appareil digestif','K14.5'),
('Glossodynia','Glossodynia','Maladies de l''appareil digestif','K14.6'),
('autre diseases of tongue','Other diseases of tongue','Maladies de l''appareil digestif','K14.8'),
('maladie of tongue, non spécifié','Disease of tongue, unspecified','Maladies de l''appareil digestif','K14.9'),
('Eosinophilic esophagitis','Eosinophilic esophagitis','Maladies de l''appareil digestif','K20.0'),
('autre esophagitis without bleeding','Other esophagitis without bleeding','Maladies de l''appareil digestif','K20.80'),
('autre esophagitis with bleeding','Other esophagitis with bleeding','Maladies de l''appareil digestif','K20.81'),
('Esophagitis, non spécifié without bleeding','Esophagitis, unspecified without bleeding','Maladies de l''appareil digestif','K20.90'),
('Esophagitis, non spécifié with bleeding','Esophagitis, unspecified with bleeding','Maladies de l''appareil digestif','K20.91'),
('Gastro-esophageal reflux maladie with esophagitis, without bleeding','Gastro-esophageal reflux disease with esophagitis, without bleeding','Maladies de l''appareil digestif','K21.00'),
('Gastro-esophageal reflux maladie with esophagitis, with bleeding','Gastro-esophageal reflux disease with esophagitis, with bleeding','Maladies de l''appareil digestif','K21.01'),
('Gastro-esophageal reflux maladie without esophagitis','Gastro-esophageal reflux disease without esophagitis','Maladies de l''appareil digestif','K21.9'),
('Achalasia of cardia','Achalasia of cardia','Maladies de l''appareil digestif','K22.0'),
('Ulcer of esophagus without bleeding','Ulcer of esophagus without bleeding','Maladies de l''appareil digestif','K22.10'),
('Ulcer of esophagus with bleeding','Ulcer of esophagus with bleeding','Maladies de l''appareil digestif','K22.11'),
('Esophageal obstruction','Esophageal obstruction','Maladies de l''appareil digestif','K22.2'),
('Perforation of esophagus','Perforation of esophagus','Maladies de l''appareil digestif','K22.3'),
('Dyskinesia of esophagus','Dyskinesia of esophagus','Maladies de l''appareil digestif','K22.4'),
('Diverticulum of esophagus, acquired','Diverticulum of esophagus, acquired','Maladies de l''appareil digestif','K22.5'),
('Gastro-esophageal laceration-hémorragie syndrome','Gastro-esophageal laceration-hemorrhage syndrome','Maladies de l''appareil digestif','K22.6'),
('Barrett''s esophagus without dysplasia','Barrett''s esophagus without dysplasia','Maladies de l''appareil digestif','K22.70'),
('Barrett''s esophagus with low grade dysplasia','Barrett''s esophagus with low grade dysplasia','Maladies de l''appareil digestif','K22.710'),
('Barrett''s esophagus with high grade dysplasia','Barrett''s esophagus with high grade dysplasia','Maladies de l''appareil digestif','K22.711'),
('Barrett''s esophagus with dysplasia, non spécifié','Barrett''s esophagus with dysplasia, unspecified','Maladies de l''appareil digestif','K22.719'),
('Esophageal polyp','Esophageal polyp','Maladies de l''appareil digestif','K22.81')
ON CONFLICT (nom_fr) DO NOTHING;
