-- ndc_batch_031.sql (80 rows)
INSERT INTO medicaments (nom, dci, forme, dosage, voie_administration, laboratoire, pays, classe_therapeutique, nom_commercial)
SELECT v.nom, v.dci, v.forme, v.dosage, v.voie, v.labo, v.pays, v.classe, v.nomcom
FROM (VALUES
('MAGNESIUM CHLORIDE','magnesium chloride','CRYSTAL','MAGNESIUM CHLORIDE 1 kg/kg',NULL,'Macco Organiques, S.r.o.','INT',NULL,NULL),
('Halog','halcinonide cream','Crème','HALCINONIDE 1 mg/g','Topique','Sun Pharmaceutical Industries, Inc.','US','Corticosteroid','Halog'),
('Magnesium Monoethylfumarate','magnesium monoethylfumarate','Poudre','MAGNESIUM MONOETHYLFUMARATE 1 kg/kg',NULL,'Laboratorium Ofichem BV','INT',NULL,NULL),
('Progesterone wettable','progesterone wettable','Poudre','PROGESTERONE 1 g/g',NULL,'LETCO MEDICAL, LLC','INT',NULL,NULL),
('fosamprenavir calcium','fosamprenavir calcium','Comprimé','FOSAMPRENAVIR CALCIUM 700 mg/1',NULL,'Glaxo Operations UK Ltd','INT',NULL,NULL),
('Diazoxide Choline','diazoxide choline','Poudre','DIAZOXIDE CHOLINE 1 kg/kg',NULL,'Siegfried Grafton, Inc.','INT',NULL,NULL),
('SULFADOXINE','sulfadoxine','Poudre','SULFADOXINE 1 kg/kg',NULL,'ANUH PHARMA LIMITED','INT',NULL,NULL),
('Aminophylline (hydrous)','aminophylline (hydrous)','Poudre','AMINOPHYLLINE 1 kg/kg',NULL,'Siegfried PharmaChemikalien Minden GmbH','INT',NULL,NULL),
('Dolutegravir Sodium','dolutegravir sodium','Poudre','DOLUTEGRAVIR SODIUM 50 kg/50kg',NULL,'Aurobindo Pharma Limited','INT',NULL,NULL),
('Copper Peptide','copper peptide','Poudre','PREZATIDE COPPER 1 kg/kg',NULL,'CHENGDU INNOVATION PHARMACEUTICAL CO.,LTD','INT',NULL,NULL),
('Acetaminophen and Diphenhydramine Hydrochloride','acetaminophen and diphenhydramine hydrochloride','Gélule','ACETAMINOPHEN 500 mg/1',NULL,'APL HEALTHCARE LIMITED','INT',NULL,NULL),
('Toltrazuril','toltrazuril','Poudre','TOLTRAZURIL 1 kg/kg',NULL,'NGL FINE-CHEM LIMITED','INT',NULL,NULL),
('Procarbazine HCl','procarbazine hcl','Poudre','PROCARBAZINE HYDROCHLORIDE 5 g/5g',NULL,'DARMERICA, LLC','INT',NULL,NULL),
('DSIP Acetate','dsip acetate','Poudre','EMIDELTIDE 1 g/g',NULL,'El-Peptido (Shanghai) Biopharmaceutical Co., Ltd','INT',NULL,NULL),
('Disulfiram','disulfiram','Poudre','DISULFIRAM 1 kg/kg',NULL,'Solara Active Pharma Sciences Limited','INT',NULL,NULL),
('Choline Chloride','choline chloride','Poudre','CHOLINE CHLORIDE 1 g/g',NULL,'Qingdao Biopeptek Co., Ltd.','INT',NULL,NULL),
('Safinamide Mesylate','safinamide mesylate','Poudre','SAFINAMIDE MESYLATE 20 kg/20kg',NULL,'Biophore India Pharmaceuticals Private Limited','INT',NULL,NULL),
('Ranolazine','ranolazine','Poudre','RANOLAZINE 50 kg/50kg',NULL,'SIONC PHARMACEUTICALS PVT LTD','INT',NULL,NULL),
('CJC1295 with DAC','cjc1295 with dac','Poudre','CJC-1295 1 g/g',NULL,'Nanjing Chengong Pharmaceutical Co., Ltd.','INT',NULL,NULL),
('Acetaminophen gelcaps','acetaminophen','Comprimé','ACETAMINOPHEN 500 mg/1','Orale','TARGET CORPORATION','INT',NULL,'Acetaminophen gelcaps'),
('childrens ibuprofen','ibuprofen','Comprimé','IBUPROFEN 100 mg/1','Orale','Rite Aid Corporation','US','Nonsteroidal Anti-inflammatory Drug','childrens ibuprofen'),
('OCUFLOX','ofloxacin','Solution','OFLOXACIN 3 mg/mL','Ophtalmique','Allergan, Inc.','US','Quinolone Antimicrobial','OCUFLOX'),
('GUNA-IL 4','binetrakin','Solution','BINETRAKIN 4 [hp_C]/30mL','Orale','Guna spa','INT',NULL,'GUNA-IL 4'),
('Hyosyne','hyoscyamine sulfate','ELIXIR','HYOSCYAMINE SULFATE .125 mg/5mL','Orale','ATLANTIC BIOLOGICALS CORP.','INT',NULL,'Hyosyne'),
('Cooling Gel','pain relief cooling gel','Gel','PHENYLEPHRINE HYDROCHLORIDE 2.5 mg/g','Topique','Neilmed Pharmaceuticals Inc.','INT','alpha-1 Adrenergic Agonist','Cooling Gel'),
('LBEL FOREVER HYDRA LONGWEAR AND HYDRATING FOUNDATION 90H SPF 15 LATTE 180F','octinoxate, zinc oxide','EMULSION','OCTINOXATE 50 mg/g','Topique','BEL STAR S.A.','INT','Médicaments topiques','LBEL FOREVER HYDRA LONGWEAR AND HYDRATING FOUNDATION 90H SPF 15 LATTE 180F'),
('AESCULUS HIPPOCASTANUM','aesculus hippocastanum','PELLET','HORSE CHESTNUT 2 [hp_X]/1','Orale','Rxhomeo Private Limited d.b.a. Rxhomeo, Inc','INT',NULL,'AESCULUS HIPPOCASTANUM'),
('Sun Defense Minerals (Light)','zinc oxide, titanium dioxide','Poudre','TITANIUM DIOXIDE 218 mg/g','Topique','Eminence Organic Skin Care','INT','Médicaments topiques','Sun Defense Minerals (Light)'),
('Senna S','docusate sodium, sennosides','Comprimé','DOCUSATE SODIUM 50 mg/1','Orale','Safeway, Inc.','INT',NULL,'Senna S'),
('Slender Ragweed','ambrosia confertiflora','Solution','AMBROSIA CONFERTIFLORA POLLEN .1 g/mL','INTRADERMAL','Greer Laboratories, Inc.','US','Non-Standardized Pollen Allergenic Extract','Slender Ragweed'),
('White Mulberry Pollen','morus alba','Solution','MORUS ALBA POLLEN .05 g/mL','INTRADERMAL','Greer Laboratories, Inc.','US','Non-Standardized Pollen Allergenic Extract','White Mulberry Pollen'),
('Summit 367 Antibacterial Foam','benzalkonium chloride','Solution','BENZALKONIUM CHLORIDE 1 mg/mL','Topique','R.L. Williams Company','INT','Médicaments topiques','Summit 367 Antibacterial Foam'),
('ampicillin','ampicillin','Solution','AMPICILLIN SODIUM 1 g/1','Intramusculaire','Sagent Pharmaceuticals','US','Penicillin-class Antibacterial','ampicillin'),
('Sinus Plus Headache','acetaminophen, phenylephrine hcl','Comprimé','ACETAMINOPHEN 325 mg/1','Orale','Kroger Company','INT','alpha-1 Adrenergic Agonist','Sinus Plus Headache'),
('Altra Antimicrobial Foaming Hand Wash with 0.3% PCMX','chloroxylenol','Solution','CHLOROXYLENOL .3 g/100mL','Topique','Buckeye International, Inc.','INT','Médicaments topiques','Altra Antimicrobial Foaming Hand Wash with 0.3% PCMX'),
('esomeprazole','esomeprazole','Gélule','ESOMEPRAZOLE 20 mg/1','Orale','Macleods Pharmaceuticals Limited','US','Proton Pump Inhibitor','esomeprazole'),
('SoftSoap Antibacterial with moisturizers White Tea and Berry Fusion','benzalkonium chloride','LIQUID','BENZALKONIUM CHLORIDE 1.33 mg/mL','Topique','COLGATE PALMOLIVE COMPANY','INT','Médicaments topiques','SoftSoap Antibacterial with moisturizers White Tea and Berry Fusion'),
('topcare Lansoprazole','lansoprazole','Comprimé','LANSOPRAZOLE 15 mg/1','Orale','Topco Associates LLC','US','Proton Pump Inhibitor','topcare Lansoprazole'),
('TopCare Health Original Eye Drops','tetrahydrozoline hcl','Solution','TETRAHYDROZOLINE HYDROCHLORIDE .05 g/100mL','Ophtalmique','Topco Associates LLC','INT','Ophtalmologie','TopCare Health Original Eye Drops'),
('KEYTRUDA','pembrolizumab','Solution','PEMBROLIZUMAB 25 mg/mL','Intraveineuse','Merck Sharp & Dohme LLC','US','Programmed Death Receptor-1 Blocking Antibody','KEYTRUDA'),
('Kali Bichromicum','kali bichromicum','PELLET','POTASSIUM DICHROMATE 6 [hp_C]/1','Orale','Hahnemann Laboratories, INC.','INT',NULL,'Kali Bichromicum'),
('Ignatia Amara','ignatia amara','PELLET','STRYCHNOS IGNATII SEED 6 [hp_C]/1','Orale','Hahnemann Laboratories, INC.','INT',NULL,'Ignatia Amara'),
('Alumina','alumina','PELLET','ALUMINUM OXIDE 6 [hp_C]/1','Orale','Hahnemann Laboratories, INC.','INT',NULL,'Alumina'),
('HEB Lubricant Eye Drops','carboxymethylcellulose sodium','Solution','CARBOXYMETHYLCELLULOSE SODIUM .5 g/100mL','Ophtalmique','HEB','INT','Ophtalmologie','HEB Lubricant Eye Drops'),
('Capzasin HP Arthritis Pain Relief','capsaicin','Crème','CAPSAICIN .001 g/g','Topique','Chattem, Inc.','INT','Médicaments topiques','Capzasin HP Arthritis Pain Relief'),
('Meijer Maximum Strength Severe Congestion and Cough','dextromethorphan hydrobromide, guaifenesin, and phenylephrine hydrochloride','LIQUID','DEXTROMETHORPHAN HYDROBROMIDE 20 mg/20mL','Orale','MEIJER, INC.','INT','Expectorant','Meijer Maximum Strength Severe Congestion and Cough'),
('WINREVAIR','sotatercept-csrk','Kit',NULL,NULL,'Merck Sharp & Dohme LLC','US',NULL,'WINREVAIR'),
('Allopurinol sodium','allopurinol sodium','Solution','ALLOPURINOL SODIUM 500 mg/25mL','Intraveineuse','Hikma Pharmaceuticals USA Inc.','US','Xanthine Oxidase Inhibitor','Allopurinol sodium'),
('HYDROXYCHLOROQUINE SULFATE','hydroxychloroquine sulfate','Comprimé','HYDROXYCHLOROQUINE SULFATE 200 mg/1','Orale','Laurus Labs Limited','US','Antimalarial','HYDROXYCHLOROQUINE SULFATE'),
('Herz Homo','herpes zoster nosode','LIQUID','HUMAN HERPESVIRUS 3 17 [hp_X]/mL','Orale','Deseret Biologicals, Inc.','INT',NULL,'Herz Homo'),
('Bio Gentian','gentianella amarella, flos','LIQUID','GENTIANELLA AMARELLA FLOWER 6 [hp_X]/mL','Orale','BioActive Nutritional Inc .','INT',NULL,'Bio Gentian'),
('Acetylcholine Chloride Phenolic','acetylcholine chloride,','LIQUID','ACETYLCHOLINE CHLORIDE 6 [hp_X]/mL','Orale','Energique, Inc.','INT','Cholinergic Receptor Agonist','Acetylcholine Chloride Phenolic'),
('Ibuprofen PM','ibuprofen and diphenhydramine hcl','Gélule','DIPHENHYDRAMINE HYDROCHLORIDE 25 mg/1','Orale','Whole Foods Market, INC.','US','Histamine-1 Receptor Antagonist','Ibuprofen PM'),
('ZO Skin Health Broad-Spectrum Sunscreen SPF 50','titanium dioxide, zinc oxide','Crème','TITANIUM DIOXIDE 7.552 mg/118g','Topique','ZO Skin Health, Inc.','INT','Médicaments topiques','ZO Skin Health Broad-Spectrum Sunscreen SPF 50'),
('Vermasode','artemisia vulgaris, chelidonium majus, granatum, spigelia anthelmia, ratanhia, arsenicum album, ferrum metallicum, calcarea carbonica, cina, gaertner bacillus, graphites, mercurius dulcis, natrum muriaticum, natrum phosphoricum, vermin nosode','LIQUID','ARSENIC TRIOXIDE 6 [hp_X]/mL','Orale','Natural Creations, Inc','INT',NULL,'Vermasode'),
('Guaifenesin 1200 mg','guaifenesin','Comprimé','GUAIFENESIN 1200 mg/1','Orale','Dr. Reddy''s Laboratories Inc.','US','Expectorant','Guaifenesin 1200 mg'),
('GABA','gaba','LIQUID','.GAMMA.-AMINOBUTYRIC ACID 8 [hp_X]/mL','Orale','Deseret Biologicals, Inc.','INT',NULL,'GABA'),
('SENNA TIME S','docusate sodium-sennosides','Comprimé','DOCUSATE SODIUM 50 mg/1','Orale','TIME CAP LABORATORIES, INC','INT',NULL,'SENNA TIME S'),
('Epicoccum','epicoccum nigrum','Solution injectable','EPICOCCUM NIGRUM .1 g/mL','CUTANEOUS','Allermed Laboratories, Inc.','US','Non-Standardized Fungal Allergenic Extract','Epicoccum'),
('Maybelline New York Master Prime By Face Studio Primer Broad Spectrum SPF 30 Sunscreen','octinoxate','Lotion','OCTINOXATE 75 mg/mL','Topique','LOreal USA Products Inc','INT','Médicaments topiques','Maybelline New York Master Prime By Face Studio Primer Broad Spectrum SPF 30 Sunscreen'),
('GI Clear P','arsenicum album, baptisia tinctoria, lachesis mutus, pulsatilla (pratensis), rhus tox','LIQUID','ARSENIC TRIOXIDE 10 [hp_X]/mL','Orale','Energique, Inc.','INT',NULL,'GI Clear P'),
('Aethusa cynapium','aethusa cynapium','PELLET','AETHUSA CYNAPIUM 200 [kp_C]/200[kp_C]','Orale','Boiron','INT',NULL,'Aethusa cynapium'),
('Alfalfa','alfalfa','PELLET','ALFALFA 6 [hp_C]/6[hp_C]','Orale','Boiron','INT',NULL,'Alfalfa'),
('Hepar sulfuris 8X','hepar sulfuris 8x','LIQUID','CALCIUM SULFIDE 8 [hp_X]/mL','Orale','Uriel Pharmacy, Inc','INT',NULL,'Hepar sulfuris 8X'),
('Stomach Relief','bismuth subsalicylate','Comprimé','BISMUTH SUBSALICYLATE 262 mg/1','Orale','Wal-Mart Stores Inc','INT',NULL,'Stomach Relief'),
('Chininum sulphuricum','quinine sulfate','PELLET','QUININE SULFATE 12 [hp_C]/12[hp_C]','Orale','Boiron','INT','Antimalarial','Chininum sulphuricum'),
('Sooth-a-Sting','benzocaine, isopropyl alcohol','SWAB','BENZOCAINE .06 g/g','Topique','HART Health','INT','Standardized Chemical Allergen','Sooth-a-Sting'),
('Cobaltum metallicum','cobalt','PELLET','COBALT 30 [hp_C]/30[hp_C]','Orale','Boiron','INT','Standardized Chemical Allergen','Cobaltum metallicum'),
('Asepxia Baking Soda Acne Bar','salicylic acid','SOAP','SALICYLIC ACID 18 mg/g','Topique','Genomma Lab USA','INT','Médicaments topiques','Asepxia Baking Soda Acne Bar'),
('TRI-LO-MARZIA','norgestimate and ethinyl estradiol','Kit',NULL,NULL,'A-S Medication Solutions','US',NULL,'TRI-LO-MARZIA'),
('NORETHINDRONE','norethindrone','Comprimé','NORETHINDRONE .35 mg/1','Orale','A-S Medication Solutions','US','Progestin','NORETHINDRONE'),
('purity made simple','salicylic acid','Crème','SALICYLIC ACID .5 ug/mL','Topique','Philosophy, Inc.','INT','Médicaments topiques','purity made simple'),
('CAREALL Ibuprofen','ibuprofen','Comprimé','IBUPROFEN 200 mg/1','Orale','New World Imports','US','Nonsteroidal Anti-inflammatory Drug','CAREALL Ibuprofen'),
('ANTIFUNGAL FOOT','tolnaftate','Spray','TOLNAFTATE 1 g/100g','Topique','Universal Distribution Center LLC','INT','Médicaments topiques','ANTIFUNGAL FOOT'),
('Novita Pure Petrolatum Jelly','petrolatum','JELLY','PETROLATUM 100 g/100g','Topique','Shield Line LLC','INT','Médicaments topiques','Novita Pure Petrolatum Jelly'),
('Collinsonia canadensis','collinsonia canadensis root','PELLET','COLLINSONIA CANADENSIS ROOT 8 [hp_X]/8[hp_X]','Orale','Boiron','INT',NULL,'Collinsonia canadensis'),
('Cortisone aceticum','cortisone acetate','PELLET','CORTISONE ACETATE 12 [hp_C]/12[hp_C]','Orale','Boiron','INT','Corticosteroid','Cortisone aceticum'),
('EXCAUGH','guaifenesin','Comprimé','GUAIFENESIN 100 mg/1','Orale','FORTUNE PHARMACAL COMPANY, LIMITED','INT','Expectorant','EXCAUGH'),
('CVS Enamel Guard','fluoride','PASTE, DENTIFRICE','POTASSIUM NITRATE 5 g/100g','DENTAL','CVS Pharmacy','INT',NULL,'CVS Enamel Guard'),
('CVS ADULT COUGH PLUS CHEST CONGESTION DM','dextromethorphan hydrobromide and guaifenesin','Solution','DEXTROMETHORPHAN HYDROBROMIDE 20 mg/20mL','Orale','CVS PHARMACY','INT','Expectorant','CVS ADULT COUGH PLUS CHEST CONGESTION DM')
) AS v(nom, dci, forme, dosage, voie, labo, pays, classe, nomcom)
WHERE NOT EXISTS (
  SELECT 1 FROM medicaments m WHERE UPPER(m.nom) = UPPER(v.nom)
);
