-- ndc_batch_098.sql (80 rows)
INSERT INTO medicaments (nom, dci, forme, dosage, voie_administration, laboratoire, pays, classe_therapeutique, nom_commercial)
SELECT v.nom, v.dci, v.forme, v.dosage, v.voie, v.labo, v.pays, v.classe, v.nomcom
FROM (VALUES
('Doctors Kline and Green Board Certified Dermatologist Hand Sanitizer','alcohol','Gel','ALCOHOL 77 mL/100mL','Topique','Formulated Solutions, LLC','INT','Médicaments topiques','Doctors Kline and Green Board Certified Dermatologist Hand Sanitizer'),
('X3 Clean','benzalkonium chloride','AEROSOL, FOAM','BENZALKONIUM CHLORIDE 1.3 mg/mL','Topique','X3 Labs Inc.','INT','Médicaments topiques','X3 Clean'),
('Piperacillin, Tazobactam','piperacillin sodium, tazobactam sodium','Solution','PIPERACILLIN SODIUM 36 g/152mL','Intraveineuse','Sagent Pharmaceuticals','US','Penicillin-class Antibacterial','Piperacillin, Tazobactam'),
('Colgate Total SF Advanced Whitening','stannous fluoride','PASTE, DENTIFRICE','STANNOUS FLUORIDE 1.1 mg/g','DENTAL','Colgate-Palmolive Company','INT',NULL,'Colgate Total SF Advanced Whitening'),
('EMEND','aprepitant','Gélule','APREPITANT 80 mg/1','Orale','Merck Sharp & Dohme LLC','US','Substance P/Neurokinin-1 Receptor Antagonist','EMEND'),
('Cold Plus Head Congestion Daytime','acetaminophen, dextromethorphan hydrobromide, and phenylephrine hydrochloride','Comprimé','ACETAMINOPHEN 325 mg/1','Orale','TopCo Associates LLC','INT','Sigma-1 Agonist','Cold Plus Head Congestion Daytime'),
('Kali Telluricosum','kali telluricosum','PELLET','POTASSIUM TELLURITE 6 [hp_C]/1','Orale','Hahnemann Laboratories, INC.','INT','Osmotic Laxative','Kali Telluricosum'),
('Effervescent Orange Cold Relief','aspirin, chlorpheniramine maleate, phenylephrine bitartrate','Comprimé','ASPIRIN 325 mg/1','Orale','H. E. Butt Grocery Company','INT','Histamine-1 Receptor Antagonist','Effervescent Orange Cold Relief'),
('VERQUVO','vericiguat','Comprimé','VERICIGUAT 2.5 mg/1','Orale','Merck Sharp & Dohme LLC','US','Soluble Guanylate Cyclase Stimulator','VERQUVO'),
('meijer fiber therapy','psyllium husk','Poudre','PSYLLIUM HUSK 3.4 g/5.79g','Orale','MEIJER DISTRIBUTION INC','INT',NULL,'meijer fiber therapy'),
('Publix Calamine Medicated','zinc acetate and pramoxine hydrochloride','Lotion','PRAMOXINE HYDROCHLORIDE 10 mg/mL','Topique','Publix','INT','Copper Absorption Inhibitor','Publix Calamine Medicated'),
('Colic','beta vulgaris, carduus marianus, lappa major, aluminium metallicum, arsenicum album, chelidonium majus, hydrastis canadensis, lycopodium clavatum, natrum sulphuricum, nux vomica, phsophorus','LIQUID','ALUMINUM 12 [hp_X]/mL','Orale','BioActive Nutritional, Inc.','INT','Non-Standardized Plant Allergenic Extract','Colic'),
('Gonal-f RFF Redi-ject','follitropin','Solution','FOLLITROPIN 300 [iU]/.5mL','Sous-cutanée','EMD Serono, Inc.','US','Gonadotropin','Gonal-f RFF Redi-ject'),
('ZO Skin Health Sheer Fluid Tint Broad-Spectrum Sunscreen SPF 45 Medium-Tan','zinc oxide','LIQUID','ZINC OXIDE 160 mg/mL','Topique','ZO Skin Health, Inc.','INT','Médicaments topiques','ZO Skin Health Sheer Fluid Tint Broad-Spectrum Sunscreen SPF 45 Medium-Tan'),
('SULWHASOO PERFECTING CUSHION NO. 15','octinoxate, titanium dioxide, and zinc oxide','Lotion','OCTINOXATE 2.1 g/30g','Topique','Amorepacific Corporation','INT','Médicaments topiques','SULWHASOO PERFECTING CUSHION NO. 15'),
('GaviLyte-H and Bisacodyl','polyethylene glycol 3350, sodium chloride, sodium bicarbonate, potassium chloride and bisacodyl delayed-release tablet','Kit',NULL,'Orale','Lupin Pharmaceuticals, Inc.','US',NULL,'GaviLyte-H and Bisacodyl'),
('Grief','cimicifuga racemosa, natrum sulphuricum, phosphoricum acidum, sepia, cerebrum suis, ignatia amara, natrum muriaticum, ambra grisea, dna, aurum metallicum, cocculus indicus, digitalis purpurea, helleborus niger, lycopodium clavatum, staphysagria','LIQUID','AMBERGRIS 9 [hp_X]/mL','Orale','Deseret Biologicals, Inc.','INT','Standardized Chemical Allergen','Grief'),
('Comfort-Time','acetaminophen, caffeine, and pyrilamine maleate','Comprimé','ACETAMINOPHEN 500 mg/1','Orale','Time Cap Labs, Inc','INT','Central Nervous System Stimulant','Comfort-Time'),
('Stemphylium solani','stemphylium solani','LIQUID','STEMPHYLIUM SOLANI .1 g/mL','PERCUTANEOUS','Allermed Laboratories, Inc.','US','Non-Standardized Fungal Allergenic Extract','Stemphylium solani'),
('Daily Meds','salicylic acid','Lotion','SALICYLIC ACID 20 mg/mL','Topique','Bioelements, Inc.','INT','Médicaments topiques','Daily Meds'),
('Garnier green labs Replumping HyaluMelon Broad Spectrum SPF 30 Sunscreen','avobenzone, homosalate, octisalate and octocrylene','Crème','AVOBENZONE 30 mg/mL','Topique','LOreal USA Products Inc','INT','Médicaments topiques','Garnier green labs Replumping HyaluMelon Broad Spectrum SPF 30 Sunscreen'),
('Scarstat','calendula officinalis, graphites, hypericum perforatum, silicea, staphysagria, thiosinaminum','LIQUID','ALLYLTHIOUREA 10 [hp_X]/mL','Orale','Energique, Inc.','INT',NULL,'Scarstat'),
('LYMPHDRAINEX','geranium robertianum, nasturtium aquaticum, teucrium scorodonia, apis mellifica, equisetum hyemale, fumaria officinalis, natrum sulphuricum, phytolacca decandra, pinus sylvestris, veronica officinalis, gentiana lutea, sarsaparilla (smilax regelii), baryta carbonica, hepar sulphuris calcareum, mercurius cyanatus, scrophularia nodosa, aloe, ferrum iodatum, myosotis arvensis, aranea diadema, calcarea phosphorica, juglans regia, parathyroid gland (bovine), thymus (suis), thyroidinum (suis)','LIQUID','ALOE 8 [hp_X]/mL','Orale','Energique, Inc.','INT','Blood Coagulation Factor','LYMPHDRAINEX'),
('Cesamet','nabilone','Gélule','NABILONE 1 mg/1','Orale','Bausch Health US LLC','US','Cannabinoid','Cesamet'),
('Librax','chlordiazepoxide hydrochloride and clidinium bromide','Gélule','CHLORDIAZEPOXIDE HYDROCHLORIDE 5 mg/1','Orale','Bausch Health US, LLC','US','Anticholinergic','Librax'),
('Aplenzin','bupropion hydrobromide','Comprimé','BUPROPION HYDROBROMIDE 174 mg/1','Orale','Bausch Health US, LLC','US','Aminoketone','Aplenzin'),
('Oxalis 1X','oxalis 1x','Pommade','OXALIS STRICTA WHOLE 1 [hp_X]/g','Topique','Uriel Pharmacy, Inc','INT','Médicaments topiques','Oxalis 1X'),
('ZELBORAF','vemurafenib','Comprimé','VEMURAFENIB 240 mg/1','Orale','Genentech, Inc.','US','Kinase Inhibitor','ZELBORAF'),
('THERASTAT, CHERRY','cherry cough drops','Pastille','MENTHOL 7.6 mg/1','Orale','HART Health','INT',NULL,'THERASTAT, CHERRY'),
('Capsaicin 0.035 Percent','capsaicin','Crème','CAPSAICIN .035 g/100g','Topique','Alexso, Inc','INT','Médicaments topiques','Capsaicin 0.035 Percent'),
('MedPRIDE with Wintergreen Oil','isopropyl alcohol','LIQUID','ISOPROPYL ALCOHOL 70 mL/100mL','Topique','Shield Line LLC','INT','Médicaments topiques','MedPRIDE with Wintergreen Oil'),
('Tom Whole Care Spearmint SLS Free fights cavities whitening fresh breath helps fight tartar','sodium monofluorophosphate','PASTE, DENTIFRICE','SODIUM MONOFLUOROPHOSPHATE 1.4 mg/g','DENTAL','Tom''s of Maine, Inc.','INT',NULL,'Tom Whole Care Spearmint SLS Free fights cavities whitening fresh breath helps fight tartar'),
('Sheer Tint Mineral Sunscreen Broad Spectrum SPF 50 - Medium/Deep Shade','spf 50 sunscreen broad spectrum - medium/deep shade','Lotion','TITANIUM DIOXIDE 2.37 g/100g','Topique','Autumn Harp','INT','Médicaments topiques','Sheer Tint Mineral Sunscreen Broad Spectrum SPF 50 - Medium/Deep Shade'),
('CVS Health Sensitive Enamel Repair','sodium fluoride','PASTE, DENTIFRICE','POTASSIUM NITRATE 5 g/100g','Orale','CVS','INT',NULL,'CVS Health Sensitive Enamel Repair'),
('Maximum Strength Gas Relief Softgel','simethicone','Gélule','DIMETHICONE, UNSPECIFIED 250 mg/1','Orale','CVS PHARMACY, INC','INT','Skin Barrier Activity','Maximum Strength Gas Relief Softgel'),
('LAUROCERASUS','prunus laurocerasus leaf','PELLET','PRUNUS LAUROCERASUS LEAF 200 [kp_C]/200[kp_C]','Orale','Boiron','INT',NULL,'LAUROCERASUS'),
('Naproxen Sodium (NSAID) Fever Reducer/ Pain Reliever','naproxen sodium','Comprimé','NAPROXEN SODIUM 220 mg/1','Orale','Amneal Pharmaceuticals of New York LLC','US','Nonsteroidal Anti-inflammatory Drug','Naproxen Sodium (NSAID) Fever Reducer/ Pain Reliever'),
('CounterAct Cough Drops Honey Lemon','menthol','Pastille','MENTHOL 7 mg/1','Orale','Melaleuca, Inc.','INT',NULL,'CounterAct Cough Drops Honey Lemon'),
('Scar Treatment Balm','allantoin','SALVE','ALLANTOIN, (R)- .5 g/100g','Topique','Better Planet Brands LLC','INT','Médicaments topiques','Scar Treatment Balm'),
('Llorens Care Children Acetaminophen','acetaminophen','Suspension','ACETAMINOPHEN 160 mg/5mL','Orale','Llorens Pharmaceutical International Division, Inc.','INT',NULL,'Llorens Care Children Acetaminophen'),
('Rompe Pecho DM','dextromethorphan hbr, guaifenesin','LIQUID','DEXTROMETHORPHAN HYDROBROMIDE 10 mg/5mL','Orale','Efficient Laboratories Inc','INT','Expectorant','Rompe Pecho DM'),
('Xyliderm','lidocaine, isopropyl alcohol','Kit',NULL,NULL,'PureTek Corporation','INT',NULL,'Xyliderm'),
('Candid-Y','adrenalinum, candida albicans, thyroidinum, torula cerevisiae, triticum, ustilago maidis, antimon. crud, arsenicum alb., baptisia, berber. aqui., bryonia, calc. phos., cinchona, helonias dioica, hydrastis, iodium, iris versicolor, kali carb., lachesis, lycopodium, merc. viv., nat.carb., nat. phos, nitricum ac., phosphorus, podoph. pelt, pulsatilla, sepia, echinacea, ginkgo, juglans regia, lappa, thuja occ.','LIQUID','ANEMONE PULSATILLA 20 [hp_X]/mL','Orale','Newton Laboratories, Inc.','INT','Catecholamine','Candid-Y'),
('DG Health Nasal Allergy','triamcinolone acetonide','Spray','TRIAMCINOLONE ACETONIDE 55 ug/1','Nasale','Dolgencorp, LLC','US','Corticosteroid','DG Health Nasal Allergy'),
('Proctozone-B','bisacodyl','Suppositoire','BISACODYL 10 mg/1','Rectale','Rising Pharma Holdings, Inc.','INT','Stimulant Laxative','Proctozone-B'),
('AVEDA OUTER PEACE ACNE RELIEF PADS','salicylic acid','Solution','SALICYLIC ACID 15 mg/g','Topique','Aveda Corporation','INT','Médicaments topiques','AVEDA OUTER PEACE ACNE RELIEF PADS'),
('Priorix','measels, mumps, and rubella vaccine, live','Kit',NULL,NULL,'GlaxoSmithKline Biologicals SA','US',NULL,'Priorix'),
('Elitek','rasburicase','Kit',NULL,NULL,'Sanofi-Aventis U.S. LLC','US',NULL,'Elitek'),
('safeHands Hand Sanitizer Fragrance Free','benzalkonium chloride','LIQUID','BENZALKONIUM CHLORIDE .13 g/100mL','Topique','Safehands Distribution Ne, LLC','INT','Médicaments topiques','safeHands Hand Sanitizer Fragrance Free'),
('H-Joint and Muscle Formula','arnica montana, bellis perennis, chamomilla','OIL','ARNICA MONTANA 12 [hp_C]/11mL','Topique','Healing Natural Oils LLC','INT','Médicaments topiques','H-Joint and Muscle Formula'),
('PLANTSCRIPTION SPF 25 POWER ANTI AGING BROAD SPECTRUM 25','avobenzone, homosalate, octislate, and octocrylene','Crème','AVOBENZONE 30 mg/mL','Topique','ORIGINS NATURAL RESOURCES INC.','INT','Médicaments topiques','PLANTSCRIPTION SPF 25 POWER ANTI AGING BROAD SPECTRUM 25'),
('Medicated Wipes Hemorrhoidal Wipes with Witch Hazel','witch hazel','CLOTH','WITCH HAZEL .5 g/g','Topique','CVS Pharmacy','INT','Médicaments topiques','Medicated Wipes Hemorrhoidal Wipes with Witch Hazel'),
('No-Shift-Lag','arnica montana, bellis perennis, ipecac, phytolacca americana root, and zinc','Comprimé','ARNICA MONTANA 30 [hp_C]/1','Orale','Miers Laboratories','INT',NULL,'No-Shift-Lag'),
('Everyday Sheer Coverage Light Tint SPF 20','zinc oxide','Crème','ZINC OXIDE 177 mg/mL','Topique','Allure Labs Inc','INT','Copper Absorption Inhibitor','Everyday Sheer Coverage Light Tint SPF 20'),
('Nu Skin 180 Degree UV Defense Hydrator SPF 18','octinoxate and zinc oxide','Lotion','OCTINOXATE 75 mg/mL','Topique','NSE Products, Inc','INT','Médicaments topiques','Nu Skin 180 Degree UV Defense Hydrator SPF 18'),
('Flex Drops 2024','flex drops','LIQUID','ANGELICA ARCHANGELICA ROOT 2 [hp_X]/59mL','Orale','Professional Complementary Health Formulas','INT','Calculi Dissolution Agent','Flex Drops 2024'),
('Pancreas/Stomach Drops 5021','pancreas/stomach drops','LIQUID','BOS TAURUS PANCREAS 6 [hp_X]/59mL','Orale','Professional Complementary Health Formulas','INT','Non-Standardized Food Allergenic Extract','Pancreas/Stomach Drops 5021'),
('Obagi Medical Back to Basics (Including Obagi Medical Professional-C Serum 20)','homosalate, octisalate, and zinc oxide','Kit',NULL,NULL,'Obagi Cosmeceuticals LLC','INT',NULL,'Obagi Medical Back to Basics (Including Obagi Medical Professional-C Serum 20)'),
('ATTITUDE Oceanly Phyto-Sun Tinted Cream SPF 30','zinc oxide','STICK','ZINC OXIDE 24 g/100g','Topique','9055-7588 Quebec Inc. DBA Attitude','INT','Médicaments topiques','ATTITUDE Oceanly Phyto-Sun Tinted Cream SPF 30'),
('Kovaltry','antihemophilic factor (recombinant)','Kit',NULL,NULL,'Bayer HealthCare LLC','US',NULL,'Kovaltry'),
('CEFTRIAXONE AND DEXTROSE','ceftriaxone','Solution','CEFTRIAXONE SODIUM 1 g/50mL','Intraveineuse','B. Braun Medical Inc.','US','Cephalosporin Antibacterial','CEFTRIAXONE AND DEXTROSE'),
('Aero Care Handy Quat Antiseptic Handwash','benzalkonium chloride','SOAP','BENZALKONIUM CHLORIDE 25 mg/mL','Topique','ABC Compounding Co., Inc.','INT','Médicaments topiques','Aero Care Handy Quat Antiseptic Handwash'),
('Anti Bacterial Hand Gel Pineapple Mango','alcohol','Gel','ALCOHOL 71 mL/100mL','Topique','Bath & Body Works, Inc.','INT','Médicaments topiques','Anti Bacterial Hand Gel Pineapple Mango'),
('Parasite Nosode Combination 9405','parasite nosode combination','LIQUID','ARSENIC TRIOXIDE 6 [hp_X]/29.5mL','Orale','Professional Complementary Health Formulas','INT',NULL,'Parasite Nosode Combination 9405'),
('R11 NEUTROVIR','adenosine triphosphate, antimonium crudum, crotalus horridus, elaps corallinus, lycopodium clavatum, naja tripudians, viscum album fruiting top','Solution','ADENOSINE TRIPHOSPHATE 5 [hp_X]/mL','Sublinguale','Apex Energetics Inc.','INT',NULL,'R11 NEUTROVIR'),
('CoreTex Sun X SPF 30 Thin','avobenzone, homosalate, octinoxate, octisalate, oxybenzone','LIQUID','AVOBENZONE 1 g/100mL','Topique','CoreTex Products Inc','INT','Médicaments topiques','CoreTex Sun X SPF 30 Thin'),
('Antiseptic Hand Sanitizer','alcohol','Gel','ALCOHOL .7 mL/mL','Topique','Laboratorios Zeyco, S.A. de C.V.','INT','Médicaments topiques','Antiseptic Hand Sanitizer'),
('Severe Cold Head Congestion','acetaminophen, guaifenesin, and phenylephrine hydrochloride','Comprimé','ACETAMINOPHEN 325 mg/1','Orale','Chain Drug Marketing Association','INT','Expectorant','Severe Cold Head Congestion'),
('MALE-PROS','prostrate booster','LIQUID','ACTAEA SPICATA ROOT 10 [hp_X]/mL','Orale','Vitality Works, Inc.','INT','Copper Absorption Inhibitor','MALE-PROS'),
('Shea','vitamin c and niacinamide even tone 48h antiperspirant deodorant','STICK','ALUMINUM SESQUICHLOROHYDRATE 12.2 g/100g','Topique','Conopco Inc. d/b/a/ Unilever','INT','Médicaments topiques','Shea'),
('Molds, Rusts and Smuts, Cephalosporium acremonium','cephalosporium acremonium','Solution','SAROCLADIUM STRICTUM .1 g/mL','PERCUTANEOUS','Jubilant HollisterStier LLC','US','Non-Standardized Fungal Allergenic Extract','Molds, Rusts and Smuts, Cephalosporium acremonium'),
('Premier Value Antibacterial Plus Urinary Pain Relief','methenamine, sodium salicylate','Comprimé','METHENAMINE 162 mg/1','Orale','Chain Drug Consortium, LLC','INT',NULL,'Premier Value Antibacterial Plus Urinary Pain Relief'),
('Chavita 7','aur met, calc sulf, cerebrum, hypericum perforatum, lachesis mutus, millefolium, valeriana','LIQUID','ACHILLEA MILLEFOLIUM WHOLE 21 [hp_X]/60mL','Orale','RUBIMED AG','INT','Blood Coagulation Factor','Chavita 7'),
('Pepto-Bismol Chewable, CVP HEALTH','bismuth subsalicylate','Comprimé','BISMUTH SUBSALICYLATE 262 mg/1','Orale','Lil'' Drug Store Products, Inc.','INT',NULL,'Pepto-Bismol Chewable, CVP HEALTH'),
('Mucus Relief DM Expectorant and Cough Suppressant','guaifenesin and dextromethorphan hbr','Comprimé','DEXTROMETHORPHAN HYDROBROMIDE 30 mg/1','Orale','Winco Foods, LLC.','US','Expectorant','Mucus Relief DM Expectorant and Cough Suppressant'),
('AGE20S SIGNATURE ESSENCE PACT INTENSE COVER MINI 41N','octinoxate, octocrylene, titanium dioxide','Crème','OCTINOXATE .26 g/4g','Topique','Aekyung Industrial Co., Ltd.','INT','Médicaments topiques','AGE20S SIGNATURE ESSENCE PACT INTENSE COVER MINI 41N'),
('McKesson Benzalkonium Chloride Towelette','benzalkonium chloride','SWAB','BENZALKONIUM CHLORIDE .13 g/100g','Topique','McKesson Medical-Surgical','INT','Médicaments topiques','McKesson Benzalkonium Chloride Towelette'),
('Weightless Protection SPF 45','sunscreen broad spectrum','Lotion','OCTISALATE 5 g/100mL','Topique','CP Skin Health Group, Inc.','INT','Médicaments topiques','Weightless Protection SPF 45'),
('My Way','levonorgestrel','Comprimé','LEVONORGESTREL 1.5 mg/1','Orale','NuCare Pharmaceuticals,Inc.','US','Progestin','My Way'),
('Extra Strength Natural Antacid','calcium carbonate','Comprimé','CALCIUM CARBONATE 750 mg/1','Orale','Raritan Pharmaceuticals Inc','INT','Blood Coagulation Factor','Extra Strength Natural Antacid')
) AS v(nom, dci, forme, dosage, voie, labo, pays, classe, nomcom)
WHERE NOT EXISTS (
  SELECT 1 FROM medicaments m WHERE UPPER(m.nom) = UPPER(v.nom)
);
