-- ndc_batch_131.sql (80 rows)
INSERT INTO medicaments (nom, dci, forme, dosage, voie_administration, laboratoire, pays, classe_therapeutique, nom_commercial)
SELECT v.nom, v.dci, v.forme, v.dosage, v.voie, v.labo, v.pays, v.classe, v.nomcom
FROM (VALUES
('Opicapone','opicapone','Gélule','OPICAPONE 50 mg/1',NULL,'Catalent Pharma Solutions, LLC','INT',NULL,NULL),
('NILOTINIB TARTRATE','nilotinib tartrate','Poudre','NILOTINIB TARTRATE 1 kg/kg',NULL,'TAPI Croatia Industries Ltd.','INT',NULL,NULL),
('Mylanta All-Family Multi Symptom Stomach Remedy','calcium carbonate, simethicone','LIQUID','CALCIUM CARBONATE 800 mg/10mL','Orale','Sportpharm LLC','INT','Blood Coagulation Factor','Mylanta All-Family Multi Symptom Stomach Remedy'),
('BM Calc Sulph','calcarea sulphurica','Comprimé','CALCIUM SULFATE ANHYDROUS 6 [hp_X]/60mg','Orale','BM Private Limited','INT','Blood Coagulation Factor','BM Calc Sulph'),
('Carbidopa, Levodopa, and Entacapone','carbidopa, levodopa, and entacapone','Comprimé','CARBIDOPA 12.5 mg/1','Orale','Sandoz Inc','US','Aromatic Amino Acid','Carbidopa, Levodopa, and Entacapone'),
('Genital Warts Remover Cream','salicylic acid','Crème','CHLORHEXIDINE DIACETATE .02 g/g','Topique','Guangxi Keyun E-commerce Co., Ltd.','INT','Decreased Cell Wall Integrity','Genital Warts Remover Cream'),
('Pacto Refreshing Sunscreen Broad Spectrum SPF 50','avobenzone, octisalate, octocrylene','Gel','AVOBENZONE 30 mg/mL','Topique','Mynd LLC','INT','Médicaments topiques','Pacto Refreshing Sunscreen Broad Spectrum SPF 50'),
('bareMinerals Complexion Rescue Tinted Hydrating Broad Spectrum SPF 30 Cinnamon 10.5','titanium dioxide','Gel','TITANIUM DIOXIDE 62 mg/mL','Topique','Orveon Global US LLC','INT','Médicaments topiques','bareMinerals Complexion Rescue Tinted Hydrating Broad Spectrum SPF 30 Cinnamon 10.5'),
('Aspirin, Dextromethorphan hydrobromide, and Phenylephrine bitartrate','aspirin, dextromethorphan hydrobromide, and phenylephrine bitartrate','Comprimé','ASPIRIN 325 mg/1',NULL,'Bayer HealthCare LLC.','INT',NULL,NULL),
('Ivacaftor spary dried dispersion','ivacaftor spary dried dispersion','Poudre','IVACAFTOR 1 kg/kg',NULL,'HOVIONE LIMITED','INT',NULL,NULL),
('EBM-N-3 Intermediate','ebm-n-3 intermediate','Poudre','ERIBULIN 15 kg/15kg',NULL,'Emcure Pharmaceuticals Limited','INT',NULL,NULL),
('Phenelzine sulfate','phenelzine sulfate','Poudre','PHENELZINE SULFATE 1 kg/kg',NULL,'Siegfried Evionnaz SA','INT',NULL,NULL),
('TIBOLONE','tibolone','Poudre','TIBOLONE 1 kg/kg',NULL,'NEWCHEM SPA','INT',NULL,NULL),
('Epinastine Hydrochloride','epinastine hydrochloride','Poudre','EPINASTINE 1 g/g',NULL,'Chongqing Biocare Pharmaceutical Ltd.','INT',NULL,NULL),
('Streptomycin Sulfate','streptomycin sulfate','Poudre','STREPTOMYCIN SULFATE 50 kg/50kg',NULL,'Sichuan Long March Pharmaceutical Co. Ltd.','INT',NULL,NULL),
('BUPIVACAINE HYDROCHLORIDE MONOHYDRATE','bupivacaine hydrochloride monohydrate','Poudre','BUPIVACAINE HYDROCHLORIDE 1 kg/kg',NULL,'Professional Compounding Centers of America','INT',NULL,NULL),
('CLOBETASONE BUTYRATE','clobetasone butyrate','Poudre','CLOBETASONE BUTYRATE 1 kg/kg',NULL,'SYMBIOTICA SPECIALITY INGREDIENTS SDN.BHD','INT',NULL,NULL),
('Bendroflumethiazide','bendroflumethiazide','Poudre','BENDROFLUMETHIAZIDE 1 kg/kg',NULL,'Unichem Laboratories Limited, India','INT',NULL,NULL),
('TERAZOSIN HYDROCHLORIDE ANHYDROUS','terazosin hydrochloride anhydrous','Poudre','TERAZOSIN HYDROCHLORIDE ANHYDROUS 1 kg/kg',NULL,'CU Chemie Uetikon GmbH','INT',NULL,NULL),
('Indoximod','indoximod','Poudre','INDOXIMOD 1 kg/kg',NULL,'MSN Laboratories Private Limited','INT',NULL,NULL),
('EBGLYSS','lebrikizumab-lbkz','Solution','LEBRIKIZUMAB 250 mg/2mL','Sous-cutanée','Eli Lilly and Company','US','Interleukin-13 Antagonist','EBGLYSS'),
('pegvisomant','pegvisomant','Solution','PEGVISOMANT 30 mg/mL',NULL,'Pfizer Manufacturing Belgium NV','INT',NULL,NULL),
('PEG-3350 and Electrolytes','polyethylene glycol 3350, sodium sulfate anhydrous, sodium bicarbonate, sodium chloride, potassium chloride','Solution','POLYETHYLENE GLYCOL 3350 236 g/4L','Orale','Affordable Pharmaceuticals, LLC','US','Osmotic Laxative','PEG-3350 and Electrolytes'),
('Amcinonide','amcinonide','Poudre','AMCINONIDE 100 kg/100kg',NULL,'Sicor de Mexico S.A. de C.V','INT',NULL,NULL),
('Theophylline Anhydrous','theophylline anhydrous','Poudre','THEOPHYLLINE ANHYDROUS 1 g/g',NULL,'LETCO MEDICAL, LLC','INT',NULL,NULL),
('Paroxetine Mesylate','paroxetine mesylate','Poudre','PAROXETINE MESYLATE 1 kg/kg',NULL,'Zhejiang Huahai Pharmaceutical Co., Ltd.','INT',NULL,NULL),
('Sacubitril','sacubitril','Poudre','SACUBITRIL 1 kg/kg',NULL,'Biocon Limited','INT',NULL,NULL),
('Perampanel Hemisesquihydrate','perampanel hemisesquihydrate','Poudre','PERAMPANEL HYDRATE (4:3) 50 kg/50kg',NULL,'Aurobindo Pharma Limited','INT',NULL,NULL),
('diphenhydramine hcl tablet, coated','diphenhydramine hcl tablet, coated','Comprimé','DIPHENHYDRAMINE HYDROCHLORIDE 25 mg/1',NULL,'Globela Pharma Pvt Ltd','INT',NULL,NULL),
('PVP Iodine 30/60','pvp iodine 30/60','Poudre','POVIDONE-IODINE 1 kg/kg',NULL,'BASF Corporation','INT',NULL,NULL),
('Assorted Fruit Antacid Chews','calcium carbonate','Comprimé','CALCIUM CARBONATE 750 mg/1','Orale','Target Corporation','INT','Blood Coagulation Factor','Assorted Fruit Antacid Chews'),
('Ceftobiprole Medocaril Sodium for Injection','ceftobiprole medocaril sodium for injection','Solution','CEFTOBIPROLE MEDOCARIL SODIUM 500 mg/mL',NULL,'Nipro Pharma Corporation','INT',NULL,NULL),
('Calcium Sennosides','calcium sennosides','Poudre','SENNOSIDES 1 kg/kg',NULL,'K. Patel Phyto Extractions Private Limited','INT',NULL,NULL),
('Nabilone','nabilone','Poudre','NABILONE 1 kg/kg',NULL,'Purisys LLC','INT',NULL,NULL),
('tislelizumab','tislelizumab','LIQUID','TISLELIZUMAB 10 mg/10mg',NULL,'Boehringer Ingelheim Biopharmaceuticals (China) Ltd.','INT',NULL,NULL),
('Watermelon Wonder Hand Sanitizer','alcohol','Gel','ALCOHOL 620 mg/g','Topique','Target Corporation','INT','Médicaments topiques','Watermelon Wonder Hand Sanitizer'),
('Oral Care Antiseptic','eucalyptol, menthol, methyl salicylate, thymol','MOUTHWASH','EUCALYPTOL .92 mg/mL','Orale','Rite Aid Corporation','INT',NULL,'Oral Care Antiseptic'),
('Glovers Therapeutic Care','salicylic acid','LIQUID','SALICYLIC ACID 20 mg/mL','Topique','J. Strickland and Co.','INT','Médicaments topiques','Glovers Therapeutic Care'),
('Disopyramide Phosphate','disopyramide phosphate','Gélule','DISOPYRAMIDE PHOSPHATE 100 mg/1','Orale','Teva Pharmaceuticals USA, Inc.','US','Antiarrhythmic','Disopyramide Phosphate'),
('NARS PURE RADIANT TINTED MOISTURIZER Santiago','octinoxate, titanium dioxide','Crème','OCTINOXATE 4.044 g/50mL','Topique','NARS Cosmetics','INT','Médicaments topiques','NARS PURE RADIANT TINTED MOISTURIZER Santiago'),
('Radiant Defense Perfecting Liquid Broad Spectrum SPF 30 - Almond','titanium dioxide, zinc oxide','Lotion','TITANIUM DIOXIDE 3.44 g/100mL','Topique','Rodan & Fields','INT','Médicaments topiques','Radiant Defense Perfecting Liquid Broad Spectrum SPF 30 - Almond'),
('Acticlate CAP','doxycycline hyclate','Gélule','DOXYCYCLINE HYCLATE 75 mg/1','Orale','Aqua Pharmaceuticals','US','Tetracycline-class Drug','Acticlate CAP'),
('7 Standardized Grass Pollen Mix','poa pratensis, festuca elatior, dactylis glomerata, lolium perenne, agrositis alba, anthoxanthum odoratum, and phleum pratense','Solution','AGROSTIS GIGANTEA POLLEN 1428.5714 [BAU]/mL','INTRADERMAL','Greer Laboratories, Inc.','US','Non-Standardized Pollen Allergenic Extract','7 Standardized Grass Pollen Mix'),
('Dandelion','taraxacum officinale','Solution','TARAXACUM OFFICINALE POLLEN .05 g/mL','INTRADERMAL','Greer Laboratories, Inc.','US','Non-Standardized Pollen Allergenic Extract','Dandelion'),
('2 Maple Pollen Mix','acer rubrum and acer saccharum','Solution','ACER RUBRUM POLLEN .0005 g/mL','INTRADERMAL','Greer Laboratories, Inc.','US','Non-Standardized Pollen Allergenic Extract','2 Maple Pollen Mix'),
('Good Neighbor Pharmacy Bacitracin Zinc','bacitracin zinc','Pommade','BACITRACIN ZINC 500 [iU]/g','Topique','AmerisourceBergen','INT','Decreased Cell Wall Synthesis & Repair','Good Neighbor Pharmacy Bacitracin Zinc'),
('terrasil Diabetics Ulcer and Bed Sore Relief','allantoin','Kit',NULL,NULL,'Aidance Scientific, Inc., DBA Aidance Skincare & Topical Solutions','INT',NULL,'terrasil Diabetics Ulcer and Bed Sore Relief'),
('CliniClean','chlorhexidine gluconate 4%','Solution','CHLORHEXIDINE GLUCONATE 4 g/100mL','Topique','Xttrium Laboratories, Inc.','US','Decreased Cell Wall Integrity','CliniClean'),
('Clematis Erecta','clematis erecta','PELLET','CLEMATIS RECTA FLOWERING TOP 100 [hp_C]/1','Orale','Hahnemann Laboratories, INC.','INT',NULL,'Clematis Erecta'),
('Cuprum Aceticum','cuprum aceticum','PELLET','CUPRIC ACETATE 6 [hp_C]/1','Orale','Hahnemann Laboratories, INC.','INT',NULL,'Cuprum Aceticum'),
('Digitalis Purpurea','digitalis purpurea','PELLET','DIGITALIS 6 [hp_C]/1','Orale','Hahnemann Laboratories, INC.','INT',NULL,'Digitalis Purpurea'),
('Zincum Oxydatum','zincum oxydatum','PELLET','ZINC OXIDE 6 [hp_C]/1','Orale','Hahnemann Laboratories, INC.','INT',NULL,'Zincum Oxydatum'),
('Zirconium Oxydatum','zirconium oxydatum','PELLET','ZIRCONIUM OXIDE 6 [hp_C]/1','Orale','Hahnemann Laboratories, INC.','INT',NULL,'Zirconium Oxydatum'),
('Pain and Fever','acetaminophen','Suspension','ACETAMINOPHEN 160 mg/5mL','Orale','H E B','INT',NULL,'Pain and Fever'),
('Acidum Sulphuricum','acidum sulphuricum','PELLET','SULFURIC ACID 6 [hp_C]/1','Orale','Hahnemann Laboratories, INC.','INT',NULL,'Acidum Sulphuricum'),
('MediChoice Povidone-Iodine','povidone-iodine','Pommade','POVIDONE-IODINE 100 mg/g','Topique','O&M HALYARD, INC.','INT','Médicaments topiques','MediChoice Povidone-Iodine'),
('Sodium Ferric Gluconate Complex in Sucrose','sodium ferric gluconate complex in sucrose','Solution injectable','SODIUM FERRIC GLUCONATE COMPLEX 12.5 mg/mL','Intraveineuse','Hikma Pharmaceuticals USA Inc.','US','Parenteral Iron Replacement','Sodium Ferric Gluconate Complex in Sucrose'),
('Sodium Sulfacetamide 10 Sulfur 2 cream','sulfacetamide sodium and sulfur','Crème','SULFACETAMIDE SODIUM 100 mg/g','Topique','Acella Pharmaceuticals, LLC','INT','Sulfonamide Antibacterial','Sodium Sulfacetamide 10 Sulfur 2 cream'),
('STRE HOMO','dna, enterococcus faecalis, streptococcus agalactiae, streptococcus bovis , streptococcus dysgalactiae, streptococcus mutans, streptococcus oralis, streptococcus pneumoniae, streptococcus uberis, streptococcus viridans','LIQUID','ENTEROCOCCUS FAECALIS 15 [hp_X]/mL','Orale','Deseret Biologicals, Inc.','INT',NULL,'STRE HOMO'),
('FNG II','echinacea (angustifolia), lomatium dissectum, nasturtium aquaticum, tabebuia impetiginosa, hydrastis canadensis, iodium, adrenalinum, argentum metallicum, thymus (suis), thyroidinum (suis), phosphoricum acidum, candida albicans, lycopodium clavatum, pulsatilla (vulgaris), sepia','LIQUID','CANDIDA ALBICANS 12 [hp_X]/mL','Orale','BioActive Nutritional, Inc.','INT','Catecholamine','FNG II'),
('Scopolamine','scopolamine','Patch transdermique','SCOPOLAMINE 1 mg/3d','Transdermique','Rhodes Pharmaceuticals L.P.','US','Anticholinergic','Scopolamine'),
('LANEIGE HYDRO UV DEFENSE EX BROAD SPECTRUM SPF 50','octocrylene, homosalate, octisalate, avobenzone','Crème','AVOBENZONE 1.25 g/50mL','Topique','AMOREPACIFIC CORPORATION','INT','Médicaments topiques','LANEIGE HYDRO UV DEFENSE EX BROAD SPECTRUM SPF 50'),
('Ileocecal Valve Support','iodium, hypophysis suis, thyroidinum, (suis), glandula suprarenalis suis, fel tauri, taraxacum officinale, bryonia (alba), carbo vegetabilis, colocynthis, indolum, lycopodium clavatum, mercurius corrosivus, nux vomica, phosphorus, pulsatilla (pratensis)','LIQUID','ACTIVATED CHARCOAL 30 [hp_C]/mL','Orale','Deseret Biologicals, Inc.','INT','Non-Standardized Plant Allergenic Extract','Ileocecal Valve Support'),
('Redroot Pigweed Pollen','amaranthus retroflexus','Solution injectable','AMARANTHUS RETROFLEXUS POLLEN .05 g/mL','CUTANEOUS','Allermed Laboratories, Inc.','US','Non-Standardized Pollen Allergenic Extract','Redroot Pigweed Pollen'),
('La Roche Posay Laboratoire Dermatologique Anthelios Dermo Kids Gentle Face and Body Broad Spectrum SPF 60 Sunscreen Water Resistant 80 Minutes','avobenzone, homosalate, octisalate and octocrylene','Lotion','AVOBENZONE 30 mg/mL','Topique','L''Oreal USA Products Inc','INT','Médicaments topiques','La Roche Posay Laboratoire Dermatologique Anthelios Dermo Kids Gentle Face and Body Broad Spectrum SPF 60 Sunscreen Water Resistant 80 Minutes'),
('CARCINOSIN CORD','carcinosin','LIQUID','HUMAN BREAST TUMOR CELL 12 [hp_X]/mL','Orale','Energique, Inc.','INT',NULL,'CARCINOSIN CORD'),
('Organdrainex','allium cepa, allium sativum, ambrosia artemisiaefolia, berberis vulgaris, chelidonium majus, collinsonia canadensis, cynara scolymus, petroselinum sativum, trifolium pratense, methylcobalamin, aloe, alpha-lipoicum acidum, palladium metallicum','LIQUID','ALOE 7 [hp_X]/mL','Orale','Energique, Inc.','INT','Non-Standardized Food Allergenic Extract','Organdrainex'),
('Good Neighbor Pharmacy Gentle Laxative','bisacodyl','Suppositoire','BISACODYL 10 mg/2000mg','Rectale','AmerisourceBergen Drug Corp','INT','Stimulant Laxative','Good Neighbor Pharmacy Gentle Laxative'),
('EcoCare 250','triclosan','Solution','TRICLOSAN 3 mg/mL','Topique','Ecolab Inc.','INT','Médicaments topiques','EcoCare 250'),
('Medique at Home Aspirin','aspirin','Comprimé','ASPIRIN 325 mg/1','Orale','Unifirst First Aid Corporation','INT','Nonsteroidal Anti-inflammatory Drug','Medique at Home Aspirin'),
('Pulmo Ferrum','pulmo ferrum','LIQUID','IRON 8 [hp_X]/mL','Orale','Uriel Pharmacy Inc.','INT',NULL,'Pulmo Ferrum'),
('Artifical Tears','glycerin and propylene glycol','Solution','GLYCERIN 3 mg/mL','Ophtalmique','Wal-Mart Stores Inc','INT','Non-Standardized Chemical Allergen','Artifical Tears'),
('Velphoro','sucroferric oxyhydroxide','Comprimé','FERRIC OXYHYDROXIDE 500 mg/1','Orale','Fresenius Medical Care Renal Therapies Group, LLC','US','Phosphate Binder','Velphoro'),
('Actemra','tocilizumab','Solution','TOCILIZUMAB 162 mg/.9mL','Sous-cutanée','Genentech, Inc.','US','Interleukin-6 Receptor Antagonist','Actemra'),
('ARTISTRY YOUTH XTEND Lifting Smoothing Foundation Broad Spectrum SPF 20 Sunscreen','octinoxate, oxybenzone','Crème','OCTINOXATE 75 mg/mL','Topique','Amway Corp','INT','Médicaments topiques','ARTISTRY YOUTH XTEND Lifting Smoothing Foundation Broad Spectrum SPF 20 Sunscreen'),
('CREST CAVITY PROTECTION COOL MINT','sodium fluoride','Gel','SODIUM FLUORIDE 1.5 mg/g','DENTAL','A-S Medication Solutions','INT',NULL,'CREST CAVITY PROTECTION COOL MINT'),
('Nextstellis','drospirenone and estetrol','Kit',NULL,NULL,'Mayne Pharma','US',NULL,'Nextstellis'),
('Myco Nail A Antifungal Solution','undecylenic acid','LIQUID','UNDECYLENIC ACID 250 mg/mL','Topique','Kramer Novis','INT','Médicaments topiques','Myco Nail A Antifungal Solution'),
('Fire Out','benzocaine and menthol','Solution','BENZOCAINE 200 mg/mL','Topique','Randob Ltd.','INT','Standardized Chemical Allergen','Fire Out'),
('Antibiotic','bacitracin zinc, neomycin sulfate, polymyxin b sulfate','Kit',NULL,NULL,'GFA Production (Xiamen) Co., Ltd.','INT',NULL,'Antibiotic')
) AS v(nom, dci, forme, dosage, voie, labo, pays, classe, nomcom)
WHERE NOT EXISTS (
  SELECT 1 FROM medicaments m WHERE UPPER(m.nom) = UPPER(v.nom)
);
