-- ndc_batch_015.sql (80 rows)
INSERT INTO medicaments (nom, dci, forme, dosage, voie_administration, laboratoire, pays, classe_therapeutique, nom_commercial)
SELECT v.nom, v.dci, v.forme, v.dosage, v.voie, v.labo, v.pays, v.classe, v.nomcom
FROM (VALUES
('2 in 1 Dandruff','pyrithione zinc','SHAMPOO','PYRITHIONE ZINC 10 mg/mL','Topique','Retail Business Services, LLC','INT','Médicaments topiques','2 in 1 Dandruff'),
('Oral Antivavity','sodium fluoride','MOUTHWASH','SODIUM FLUORIDE .1 mg/mL','Orale','Amazon.com Services LLC','INT',NULL,'Oral Antivavity'),
('Dexmedetomidine hydrochloride','dexmedetomidine hydrochloride','Solution','DEXMEDETOMIDINE HYDROCHLORIDE 100 ug/mL','Intraveineuse','Medical Purchasing Solutions, LLC','US','Central alpha-2 Adrenergic Agonist','Dexmedetomidine hydrochloride'),
('Elta MD Skincare UV Stick Broad Spectrum SPF50','zinc oxide','STICK','ZINC OXIDE 22 g/100g','Topique','CP Skin Health Group, Inc','INT','Copper Absorption Inhibitor','Elta MD Skincare UV Stick Broad Spectrum SPF50'),
('METHYLERGONOVINE MALEATE','methylergonovine maleate','Solution injectable','METHYLERGONOVINE MALEATE .2 mg/mL','Intraveineuse','Bryant Ranch Prepack','US','Ergot Derivative','METHYLERGONOVINE MALEATE'),
('Daily Moisturizing','dimethicone','Lotion','DIMETHICONE 12 mg/g','Topique','Old East Main Co.','INT','Skin Barrier Activity','Daily Moisturizing'),
('Clean Simple Hand Sanitizer','alcohol','LIQUID','ALCOHOL 75 mL/100mL','Topique','KINGKEY MBC LIFE TECHNOLOGY GROUP CO., LTD','INT','Médicaments topiques','Clean Simple Hand Sanitizer'),
('Germ-Away','anti-microbial','CLOTH','BENZALKONIUM CHLORIDE 1.3 mg/g','Topique','Unico International Trading Corp','INT','Médicaments topiques','Germ-Away'),
('Betamethasone Sodium Phosphate and Betamethasone Acetate','betamethasone sodium phosphate and betamethasone acetate','Suspension','BETAMETHASONE ACETATE 3 mg/mL','INTRA-ARTICULAR','American Regent, Inc.','US','Corticosteroid','Betamethasone Sodium Phosphate and Betamethasone Acetate'),
('Trionex','calcipotriene cream, 0.005% and transparent dressing','Kit',NULL,NULL,'V2 Pharma, LLC','INT',NULL,'Trionex'),
('Optimel Manuka Forte Eye Gel','glycerin','Gel','GLYCERIN 2 mg/mL','Ophtalmique','Melcare Biomedical Pty Ltd','INT','Non-Standardized Chemical Allergen','Optimel Manuka Forte Eye Gel'),
('AZX Wellness Hand Sanitizer','alcohol','Gel','ALCOHOL 70 mL/100mL','Topique','ASC Marketing LTD','INT','Médicaments topiques','AZX Wellness Hand Sanitizer'),
('ABOVE INTIMATE LIQUIDSOAP','above intimate','LIQUID','ALOE .01 mg/250g','Topique','BASTON INDUSTRIA DE AEROSSOIS LTDA','INT','Médicaments topiques','ABOVE INTIMATE LIQUIDSOAP'),
('Plantar Wart Removers','salicylic acid','DISC','SALICYLIC ACID .4 g/g','Topique','Scholls Wellness Company LLC','INT','Médicaments topiques','Plantar Wart Removers'),
('COSELA','trilaciclib','Solution','TRILACICLIB DIHYDROCHLORIDE 300 mg/20mL','Intraveineuse','Pharmacosmos Therapeutics Inc.','US','Kinase Inhibitor','COSELA'),
('Recens Foam','alcohol','LIQUID','ALCOHOL .7 mL/mL','Topique','Certus Medical, Inc.','INT','Médicaments topiques','Recens Foam'),
('TOPCO Childrens Cough Relief','dextromethorphan hbr and guaifenesin','LIQUID','DEXTROMETHORPHAN HYDROBROMIDE 5 mg/5mL','Orale','Topco Associates, LLC','INT','Expectorant','TOPCO Childrens Cough Relief'),
('Acne Fighting Putty Primer','salicylic acid','Crème','SALICYLIC ACID 18 mg/g','Topique','e.l.f. Cosmetics, Inc','INT','Médicaments topiques','Acne Fighting Putty Primer'),
('Dyural 80 Kit','methylprednisolone acetate, lidocaine hydrochloride, bupivacaine hydrochloride, povidine iodine, sodium chloride, isopropyl alcohol','Kit',NULL,'Épidurale','Asclemed USA, Inc.','INT',NULL,'Dyural 80 Kit'),
('Vacation Shimmer Oil','avobenzone homosalate octisalate octocrylene','OIL','AVOBENZONE 2.9 g/100mL','Topique','Vacation Inc','INT','Médicaments topiques','Vacation Shimmer Oil'),
('TRANEXAMIC ACID IN SODIUM CHLORIDE','tranexamic acid','Solution','TRANEXAMIC ACID 10 mg/mL','Intraveineuse','Amneal Pharmaceuticals Private Limited','US','Antifibrinolytic Agent','TRANEXAMIC ACID IN SODIUM CHLORIDE'),
('Brut Classic Antiperspirant and Deodorant','aluminum chlorohydrate','Spray','ALUMINUM CHLOROHYDRATE 20.9 g/100g','Topique','Sodalis USA LLC','INT','Médicaments topiques','Brut Classic Antiperspirant and Deodorant'),
('Flawless Brightening Sunscreen','titanium dioxide, zinc oxide','Crème','TITANIUM DIOXIDE 80 mg/g','Topique','Flawless Skin Care LLC','INT','Médicaments topiques','Flawless Brightening Sunscreen'),
('Drop20','fucus vesiculosus, chelidonium majus, kali phosphoricum, lycopodium clavatum, natrum muriaticum, quercus glandium spiritus, quercus robur, nux vomica, phytolacca decandra, ornithogalum umbellatum, agnus castus, berberis aquifolium, berberis vulgaris, saccharum officinale, solidago virgaurea, calcarea carbonica, carbo vegetabilis, magnesia phosphorica, natrum phosphoricum, sinapis arvensis, flos, ubidecarenonum, graphites, hypophysis suis, placenta totalis suis, hypothalamus (bovine)','LIQUID','ACTIVATED CHARCOAL 12 [hp_X]/mL','Orale','Pick Enterprises Corp','INT','Calculi Dissolution Agent','Drop20'),
('Skin Protectant','petrolatum','Pommade','PETROLATUM 410 mg/g','Topique','Walmart Inc.','INT','Médicaments topiques','Skin Protectant'),
('Immunies','homeopathic immunomodulator','Gélule','PANAX GINSENG WHOLE 1 [hp_X]/1','Orale','HCBIOPHARM LLC','INT',NULL,'Immunies'),
('Sumatriptan','sumatriptan','Comprimé','SUMATRIPTAN SUCCINATE 100 mg/1','Orale','Advanced Rx Pharmacy of Tennessee, LLC','US','Serotonin-1b and Serotonin-1d Receptor Agonist','Sumatriptan'),
('MGC Health Cough Drops Original Herb','menthol','Pastille','MENTHOL 4.8 mg/1','Orale','Medical Group Care LLC','INT',NULL,'MGC Health Cough Drops Original Herb'),
('QUALITY CHOICE Maximum Strength Nighttime Cold and Flu','acetaminophen, dextromethorphan hydrobromide, doxylamine succinate, phenylephrine hydrochloride','Gélule','ACETAMINOPHEN 325 mg/1','Orale','Chain Drug Marketing Association, Inc.','INT','Antihistamine','QUALITY CHOICE Maximum Strength Nighttime Cold and Flu'),
('Dermoia Manuka Honey Eczema','oatmeal','Crème','OATMEAL 20 mg/mL','Topique','TREASUREWISE LLC','INT','Non-Standardized Food Allergenic Extract','Dermoia Manuka Honey Eczema'),
('Alcohol wet wipes','alcohol wet wipes','DRESSING','ALCOHOL 75 mL/100mL','Topique','Shandong Aishule Hygiene Products Co., Ltd','INT','Médicaments topiques','Alcohol wet wipes'),
('up and up Medicated Anti-dandruff Anti-dandruff, anti-seborrheic dermatitis, anti-psoriasis','selenium sulfide','SHAMPOO','SELENIUM SULFIDE 10 mg/mL','Topique','TARGET CORPORATION','INT','Médicaments topiques','up and up Medicated Anti-dandruff Anti-dandruff, anti-seborrheic dermatitis, anti-psoriasis'),
('PRIDEFUL SPF 15 LIP BALM-citrus','homosalate, octisalate, octocrylene, avobenzone','STICK','AVOBENZONE 20 mg/g','Topique','PRIDEFUL LLC','INT','Médicaments topiques','PRIDEFUL SPF 15 LIP BALM-citrus'),
('BadaBOOM Sunscreen','sunscreen','Crème','TITANIUM DIOXIDE 23.9 g/100g','Topique','Aopline Health Industry Technology (Guangzhou) Co., Ltd.','INT','Médicaments topiques','BadaBOOM Sunscreen'),
('natural lip balm SPF15( blueberry) 01','avobenzone,homosalate,octocrylene,octisalate','LIPSTICK','AVOBENZONE 2 g/100g','Topique','Cosmuses Cosmetics (Ningbo) Co., Ltd.','INT','Médicaments topiques','natural lip balm SPF15( blueberry) 01'),
('Bestmade Natural Products BM134','arsenic album, hydrastis, myristica, nitric acid, paeonia, rhus tox, silicea','LIQUID','ARSENIC TRIOXIDE 30 [hp_C]/30[hp_C]','Orale','Bestmade Natural Products','INT',NULL,'Bestmade Natural Products BM134'),
('Bestmade Natural Products Stramonium','stramonium','Comprimé','DATURA STRAMONIUM 30 [hp_C]/30[hp_C]','Orale','Bestmade Natural Products','INT',NULL,'Bestmade Natural Products Stramonium'),
('ANTIBACTERIAL FRUITY ZEST','glycerin','SOAP','GLYCERIN 1 g/g','Transdermique','Quimicas Handal de Centroamerica SA de CV','INT','Non-Standardized Chemical Allergen','ANTIBACTERIAL FRUITY ZEST'),
('Flobow SMELLING SALTS','ammonia 15% smelling salts','INHALANT','AMMONIA 15 g/100g','Inhalation','Jiangxi Yudexi Pharmaceutical Co., LTD','INT',NULL,'Flobow SMELLING SALTS'),
('Matte Invisible Mineral Sunscreen','zinc oxide','Crème','ZINC OXIDE 160 mg/g','Topique','INTEGRATIVE AESTHETICS BOSTON, LLC','INT','Médicaments topiques','Matte Invisible Mineral Sunscreen'),
('Tinted Mineral 40','titanium dioxide, zinc oxide','Crème','TITANIUM DIOXIDE 80 mg/g','Topique','2301 PLASTIC SURGERY, PLLC','INT','Médicaments topiques','Tinted Mineral 40'),
('Latin Beauty LLC. Powder Sunscreen SPF 50 Kiss the Sun','latin beauty llc. powder sunscreen spf 50 kiss the sun','Poudre','TITANIUM DIOXIDE .9 g/6g','CUTANEOUS','Guangzhou Yueyou Biological Technology Co., Ltd.','INT',NULL,'Latin Beauty LLC. Powder Sunscreen SPF 50 Kiss the Sun'),
('TULA SKINCARE BREAKOUT BREAKTHROUGH ACNE TONER PADS','salicylic acid','DISC','SALICYLIC ACID 2 g/1001','Topique','The Procter & Gamble Manufacturing Company','INT','Médicaments topiques','TULA SKINCARE BREAKOUT BREAKTHROUGH ACNE TONER PADS'),
('ADI Medical PVP-I Pouch, Foil','povidone-iodine','Solution','POVIDONE-IODINE 10 g/100g','Topique','Asia Dynamics Inc., d/b/a ADI Medical','INT','Médicaments topiques','ADI Medical PVP-I Pouch, Foil'),
('Extra Strength Acetaminophen','acetaminophen','Comprimé','ACETAMINOPHEN 500 mg/1','Orale','TIME CAP LABORATORIES, INC.','INT',NULL,'Extra Strength Acetaminophen'),
('Dentalclean Blue Diamond Alcohol Free Mouthwash','sodium fluoride 0.05%','RINSE','SODIUM FLUORIDE .2 mg/mL','DENTAL','Rabbit Indstria e Comrcio de Produtos de Higiene Pessoal Ltda','INT',NULL,'Dentalclean Blue Diamond Alcohol Free Mouthwash'),
('Sun Juice Body Mist Sunscreen SPF30 - Watermelon Sugar PARADISO','avobenzone, homosalate, octisalate','Spray','AVOBENZONE 30 mg/mL','Topique','Koco Life LLC','INT','Médicaments topiques','Sun Juice Body Mist Sunscreen SPF30 - Watermelon Sugar PARADISO'),
('SUMMER GELEE SPF-4','homosalate, octisalate','Gel','HOMOSALATE 20 mg/mL','Topique','SUMMER GELEE LLC','INT','Médicaments topiques','SUMMER GELEE SPF-4'),
('Bitchstix Eucalyptus Mint SPF 30 Sunscreen Lip Balm SPF 30','avobenzone, octinoxate, octisalate, oxybenzone','STICK','AVOBENZONE 3 g/100g','Topique','Bitchstix, LLC','INT','Médicaments topiques','Bitchstix Eucalyptus Mint SPF 30 Sunscreen Lip Balm SPF 30'),
('MICONAZOLE 3 COMBINATION PACK (miconazole nitrate) kit','miconazole nitrate','Kit',NULL,NULL,'Cosette Pharmaceuticals, Inc.','US',NULL,'MICONAZOLE 3 COMBINATION PACK (miconazole nitrate) kit'),
('HYDROCORTISONE VALERATE','hydrocortisone valerate','Crème','HYDROCORTISONE VALERATE 2 mg/g','Topique','Cosette Pharmaceuticals, Inc.','US','Corticosteroid','HYDROCORTISONE VALERATE'),
('JAYSUING Silicone Scar Gel','glycerin','Gel','CENTELLA ASIATICA ROOT .006 mg/30mg','Topique','Shantou Jaysuing Cleaning and Environmental Protection Technology Co., Ltd.','INT','Médicaments topiques','JAYSUING Silicone Scar Gel'),
('St. Moriz Suncare 30 Face Sunscreen','sunscreen','Lotion','OCTISALATE 50 mg/mL','Topique','Hothouse Beauty Inc','INT','Médicaments topiques','St. Moriz Suncare 30 Face Sunscreen'),
('SUTENT','sunitinib malate','Gélule','SUNITINIB MALATE 50 mg/1','Orale','Pfizer Laboratories Div Pfizer Inc','US','Kinase Inhibitor','SUTENT'),
('Ziprasidone','ziprasidone','Gélule','ZIPRASIDONE HYDROCHLORIDE 60 mg/1','Orale','Major Pharmaceuticals','US','Atypical Antipsychotic','Ziprasidone'),
('SYBORG SALTS Smelling Salt','ammonium carbonate and sodium carbonate','GRANULE','AMMONIUM CARBONATE 15 g/100g','Inhalation','Direct Outlet Supplier LLC','INT',NULL,'SYBORG SALTS Smelling Salt'),
('SilkTears','glycerin ophthalmic solution','Solution','GLYCERIN 2 mg/1000mL','Ophtalmique','SilkTears','INT','Non-Standardized Chemical Allergen','SilkTears'),
('Gentle Mineral SPF 40 Tinted','zinc oxide','Crème','ZINC OXIDE 200 mg/g','Topique','ELIZA ARAKELIAN','INT','Médicaments topiques','Gentle Mineral SPF 40 Tinted'),
('LipBOMB','titanium dioxide, zinc oxide','STICK','TITANIUM DIOXIDE 40 mg/g','Topique','FLEUR DE VIE LLC','INT','Médicaments topiques','LipBOMB'),
('Mineral Sunscreen Non-Tinted','titanium dioxide, zinc oxide','Crème','TITANIUM DIOXIDE 80 mg/g','Topique','YUMA ACNE CLINIC, L.L.C.','INT','Médicaments topiques','Mineral Sunscreen Non-Tinted'),
('FENBENDAZOLE Oral Dewormer','fenbendazole','PASTE','FENBENDAZOLE 100 mg/g','Orale','Shenzhen Zhenshangzekai Technology Co., Ltd.','INT',NULL,'FENBENDAZOLE Oral Dewormer'),
('TIRTIR SUN BOUNCY GLOW LIP BALM SPF30 - 04 BURNT MAPLE','zinc oxide','Crème','ZINC OXIDE 135 mg/mL','Topique','TIRTIR USA Inc.','INT','Médicaments topiques','TIRTIR SUN BOUNCY GLOW LIP BALM SPF30 - 04 BURNT MAPLE'),
('bareMinerals Blemish Rescue Skin-Clearing Loose Foundation Warm Deep 5.5N','salicylic acid','Poudre','SALICYLIC ACID 30 mg/6g','Topique','Orveon Global US LLC','INT','Médicaments topiques','bareMinerals Blemish Rescue Skin-Clearing Loose Foundation Warm Deep 5.5N'),
('Venetoclax','venetoclax','Poudre','VENETOCLAX .25 kg/kg',NULL,'AbbVie Inc.','INT',NULL,NULL),
('Alka Seltzer Plus Free Cold and Flu Day Liqui-Gels','alka seltzer plus free cold and flu day liqui-gels','Gélule','ACETAMINOPHEN 325 mg/1',NULL,'Bayer HealthCare LLC.','INT',NULL,NULL),
('Trulicity','dulaglutide','Solution','DULAGLUTIDE 1.5 mg/.5mL','Sous-cutanée','Eli Lilly and Company','US','GLP-1 Receptor Agonist','Trulicity'),
('Phendimetrazine Tartrate','phendimetrazine tartrate','Poudre','PHENDIMETRAZINE TARTRATE 1 kg/kg',NULL,'Olon SpA','INT',NULL,NULL),
('Dexamethasone Sodium Phosphate','dexamethasone sodium phosphate','Poudre','DEXAMETHASONE SODIUM PHOSPHATE 1 kg/kg',NULL,'NEWCHEM SPA','INT',NULL,NULL),
('Phytonadione','phytonadione','Poudre','PHYTONADIONE 1 kg/kg',NULL,'Chongqing Biocare Pharmaceutical Ltd.','INT',NULL,NULL),
('Bepotastine','bepotastine','Poudre','BEPOTASTINE BESILATE 1 kg/kg',NULL,'UBE Corporation','INT',NULL,NULL),
('Cytomegalovirus Nosode','cytomegalovirus nosode','LIQUID','HUMAN HERPESVIRUS 5 1000 [hp_X]/mL',NULL,'Deseret Biologicals, Inc.','INT',NULL,NULL),
('Diclofenac','diclofenac','Poudre','DICLOFENAC 1 kg/kg',NULL,'Unique Chemicals','INT',NULL,NULL),
('Phenoxybenzamine Hydrochloride','phenoxybenzamine hydrochloride','Poudre','PHENOXYBENZAMINE HYDROCHLORIDE 50 kg/50kg',NULL,'Aurobindo Pharma Limited','INT',NULL,NULL),
('FLUNIXIN MEGLUMINE','flunixin meglumine','Poudre','FLUNIXIN MEGLUMINE 1 g/g',NULL,'Kalchem International inc','INT',NULL,NULL),
('Ertugliflozin','ertugliflozin','Poudre','ERTUGLIFLOZIN 1 kg/kg',NULL,'Upjohn Manufacturing Ireland Unlimited Company','INT',NULL,NULL),
('Naloxone Hydrochloride Dihydrate','naloxone hydrochloride dihydrate','Poudre','NALOXONE HYDROCHLORIDE DIHYDRATE 1 kg/kg',NULL,'Noramco, LLC','INT',NULL,NULL),
('Physicians Care Eyewash','eyewash','Solution','WATER 465 mL/473mL','Ophtalmique','Acme United Corporation','INT','Ophtalmologie','Physicians Care Eyewash'),
('First Aid Only Sting Relief','benzocaine','SWAB','BENZOCAINE .12 g/.6mL','Topique','Acme United Corporation','INT','Standardized Chemical Allergen','First Aid Only Sting Relief'),
('DIANEAL PD-2 with Dextrose','sodium chloride, sodium lactate, calcium chloride, magnesium chloride and dextrose','Solution','CALCIUM CHLORIDE 25.7 mg/100mL','INTRAPERITONEAL','Vantive US Healthcare LLC','US','Blood Coagulation Factor','DIANEAL PD-2 with Dextrose'),
('Formoterol Fumarate','formoterol fumarate','Poudre','FORMOTEROL FUMARATE 25 kg/25kg',NULL,'Cipla Ltd.','INT',NULL,NULL)
) AS v(nom, dci, forme, dosage, voie, labo, pays, classe, nomcom)
WHERE NOT EXISTS (
  SELECT 1 FROM medicaments m WHERE UPPER(m.nom) = UPPER(v.nom)
);
