-- ndc_batch_085.sql (80 rows)
INSERT INTO medicaments (nom, dci, forme, dosage, voie_administration, laboratoire, pays, classe_therapeutique, nom_commercial)
SELECT v.nom, v.dci, v.forme, v.dosage, v.voie, v.labo, v.pays, v.classe, v.nomcom
FROM (VALUES
('Eplerenone','eplerenone','Poudre','EPLERENONE 1 kg/kg',NULL,'Pharmacia & Upjohn Company LLC','INT',NULL,NULL),
('anhydrous citric acid, aspirin, sodium bicarbonate','anhydrous citric acid, aspirin, sodium bicarbonate','Comprimé','ANHYDROUS CITRIC ACID 1000 mg/1',NULL,'Bayer HealthCare LLC.','INT',NULL,NULL),
('Roflumilast','roflumilast','Comprimé','ROFLUMILAST 500 ug/1','Orale','Major Pharmaceuticals','US','Phosphodiesterase 4 Inhibitor','Roflumilast'),
('Mycophenolate Mofetile','mycophenolate mofetile','Poudre','MYCOPHENOLATE MOFETIL 1 kg/kg',NULL,'Hisun Pharmaceutical (Hangzhou) Co., Ltd.','INT',NULL,NULL),
('Acitretin','acitretin','Poudre','ACITRETIN 1 kg/kg',NULL,'Olon SpA','INT',NULL,NULL),
('Sulfadiazine Sodium','sulfadiazine sodium','Poudre','SULFADIAZINE SODIUM 1 g/g',NULL,'Medisca Inc.','INT',NULL,NULL),
('Helicobacter Pylori,Helicobacter Pylori DNA','helicobacter pylori,helicobacter pylori dna','LIQUID','HELICOBACTER PYLORI 15 [hp_X]/mL',NULL,'Deseret Biologicals','INT',NULL,NULL),
('Omadacycline tosylate','omadacycline tosylate','Poudre','OMADACYCLINE TOSYLATE 1 kg/kg',NULL,'Dynamit Nobel GmbH Explosivstoff- und Systemtechnik','INT',NULL,NULL),
('CYCLOBENZAPRINE HCL','cyclobenzaprine hcl','Poudre','CYCLOBENZAPRINE HYDROCHLORIDE 1 g/g',NULL,'Kalchem International inc','INT',NULL,NULL),
('Cupric Sulfate Anhydrous','cupric sulfate anhydrous','Poudre','CUPRIC SULFATE ANHYDROUS 1 kg/kg',NULL,'Jost Chemical Co.','INT',NULL,NULL),
('Fingolimod Hydrochloride (Form-I)','fingolimod hydrochloride (form-i)','Poudre','FINGOLIMOD HYDROCHLORIDE 1 kg/kg',NULL,'MSN Laboratories Private Limited','INT',NULL,NULL),
('Zeranol','zeranol','Poudre','ZERANOL 1 kg/kg',NULL,'Zhejiang Hisun Pharmaceutical Co., Ltd.','INT',NULL,NULL),
('ALXN2040','alxn2040','Poudre','DANICOPAN 1 kg/kg',NULL,'Cambrex Charles City, Inc.','INT',NULL,NULL),
('Atomoxetine Hydrochloride','atomoxetine hydrochloride','Poudre','ATOMOXETINE HYDROCHLORIDE 1 kg/kg',NULL,'Honour Lab Limited','INT',NULL,NULL),
('BENZOIN','benzoin','LIQUID','BENZOIN RESIN 100 g/1000mL',NULL,'NATARA GLOBAL LIMITED','INT',NULL,NULL),
('Rilpivirine Hydrochloride','rilpivirine hydrochloride','Poudre','RILPIVIRINE HYDROCHLORIDE 1 kg/kg',NULL,'SMS Pharmaceuticals Limited','INT',NULL,NULL),
('Rezafungin','rezafungin','Solution','REZAFUNGIN 200 mg/1',NULL,'Patheon Italia S.p.A.','INT',NULL,NULL),
('plerixafor','plerixafor','Solution','PLERIXAFOR 24 mg/1.2mL',NULL,'Patheon Manufacturing Services LLC','INT',NULL,NULL),
('S,S-Reboxetine Succinate','s,s-reboxetine succinate','Poudre','ESREBOXETINE SUCCINATE 1 kg/kg',NULL,'Laboratorium Ofichem BV','INT',NULL,NULL),
('Zopiclone','zopiclone','Poudre','ZOPICLONE 1 kg/kg',NULL,'Industriale Chimica s.r.l.','INT',NULL,NULL),
('Blistex Foille Medicated First Aid','benzocaine and chloroxylenol','Pommade','BENZOCAINE 5 g/100g','Topique','Blistex Inc.','INT','Standardized Chemical Allergen','Blistex Foille Medicated First Aid'),
('BORAGO OFFICINALIS FLOWER','borago officinalis flower','LIQUID','BORAGO OFFICINALIS FLOWER 1 [hp_X]/mL',NULL,'Herbamed AG','INT',NULL,NULL),
('Quinapril Hydrochloride/Hydrochlorothiazide','quinapril hydrochloride/hydrochlorothiazide','Comprimé','HYDROCHLOROTHIAZIDE 12.5 mg/1',NULL,'Aurobindo Pharma Limited','INT',NULL,NULL),
('TESAMORELIN','tesamorelin','Poudre','TESAMORELIN 1 g/g',NULL,'Shenzhen Alvantis Pharma Co., Ltd.','INT',NULL,NULL),
('BPC-157','bpc-157','Poudre','BPC-157 100 g/100g',NULL,'Hangzhou Yiqi Biotechnology Co., Ltd','INT',NULL,NULL),
('somatropin','somatropin','LIQUID','SOMATROPIN 60 g/60g',NULL,'Hefei Xinzhu Biological Technology Co., Ltd.','INT',NULL,NULL),
('ponazuril','ponazuril','Poudre','PONAZURIL 1 kg/kg',NULL,'Jiangsu Willing Bio-Tech Co., Ltd','INT',NULL,NULL),
('Hydroxy Progesterone Caproate','hydroxy progesterone caproate','Poudre','HYDROXYPROGESTERONE CAPROATE 100 g/100g',NULL,'Brichem Sciences Private Limited','INT',NULL,NULL),
('Ultane','sevoflurane','LIQUID','SEVOFLURANE 250 mL/250mL','Inhalation','AbbVie Inc.','US','General Anesthetic','Ultane'),
('Rohto Dry-Aid','povidone, propylene glycol','LIQUID','POVIDONE, UNSPECIFIED 6.8 mg/mL','Ophtalmique','The Mentholatum Company','INT','Ophtalmologie','Rohto Dry-Aid'),
('NICOTINAMIDE RIBOSIDE CHLORIDE','nicotinamide riboside chloride','Poudre','NADIDE 1 g/g',NULL,'Qingdao Biopeptek Co., Ltd.','INT',NULL,NULL),
('Leuprorelin Acetate','leuprorelin acetate','Poudre','LEUPROLIDE ACETATE 1 g/g',NULL,'Hubei JXBio Pharmaceutical Co.,Ltd','INT',NULL,NULL),
('LIOTHYRONINE','liothyronine','Poudre','LIOTHYRONINE SODIUM 1 kg/kg',NULL,'VALARY LAB PRIVATE LIMITED','INT',NULL,NULL),
('Estradiol (Hemihydrate)','estradiol (hemihydrate)','Poudre','ESTRADIOL HEMIHYDRATE 1 kg/kg',NULL,'Pharma Source Direct, Inc.','INT',NULL,NULL),
('Acetaminophen, Caffeine, Pyrilamine Maleate','acetaminophen, caffeine, pyrilamine maleate','Comprimé','ACETAMINOPHEN 500 mg/1',NULL,'Shield Pharmaceuticals Corp','INT',NULL,NULL),
('up and up extra strength smooth dissolving antacid Assorted Fruit','calcium carbonate','Comprimé','CALCIUM CARBONATE 750 mg/1','Orale','Target corporation','INT','Blood Coagulation Factor','up and up extra strength smooth dissolving antacid Assorted Fruit'),
('Rite Aid Fiber Caplets','calcium polycarbophil','Comprimé','CALCIUM POLYCARBOPHIL 625 mg/1','Orale','RITE AID CORPORATION','INT',NULL,'Rite Aid Fiber Caplets'),
('Glovers Dandruff Control Med., Floral','sulfur','Suspension','SULFUR 25 mg/mL','Topique','J. Strickland & Co.','INT','Médicaments topiques','Glovers Dandruff Control Med., Floral'),
('GUNA-ORAL','achillea millefolium - aconitum napellus - arnica montana - atropa belladonna - calcium sulfide - comfrey root - echinacea angustifolia - echinacea purpurea - hypericum perforatum - sus scrofa tooth - witch hazel -','Spray','ACHILLEA MILLEFOLIUM 3 [hp_X]/30mL','Orale','Guna spa','INT',NULL,'GUNA-ORAL'),
('MISSHA ALL AROUND ESSENCE SUNSCREEN','homosalate, octocrylene, octisalate, avobenzone','Crème','AVOBENZONE 2.7 g/100mL','Topique','Able C&C Co., Ltd.','INT','Médicaments topiques','MISSHA ALL AROUND ESSENCE SUNSCREEN'),
('CYZONE NITRO AIR DESODORANTE ANTITRANSPIRANTE ROLL ON','aluminum sesquichlorohydrate','EMULSION','ALUMINUM SESQUICHLOROHYDRATE 132.8 mg/g','Topique','BEL STAR SA','INT','Médicaments topiques','CYZONE NITRO AIR DESODORANTE ANTITRANSPIRANTE ROLL ON'),
('Aurovisc OE','hypromellose ophthalmic solution 2% w/v','Solution','HYPROMELLOSE 2208 (15000 MPA.S) 20 mg/mL','Ophtalmique','Aurolab','INT','Ophtalmologie','Aurovisc OE'),
('Signature Select Pain Relieving','lidocaine hcl, benzalkonium chloride','Spray','BENZALKONIUM CHLORIDE .13 g/100mL','Topique','Safeway/Albartsons','INT','Amide Local Anesthetic','Signature Select Pain Relieving'),
('Standardized Cat Hair Allergenic Extract','felis catus','Solution','FELIS CATUS DANDER 5000 [BAU]/mL','INTRADERMAL','Greer Laboratories, Inc.','US','Standardized Animal Skin Allergenic Extract','Standardized Cat Hair Allergenic Extract'),
('White Alder Pollen','alnus rhombifolia','Solution','ALNUS RHOMBIFOLIA POLLEN .001 g/mL','INTRADERMAL','Greer Laboratories, Inc.','US','Non-Standardized Pollen Allergenic Extract','White Alder Pollen'),
('Virginia Scrub Pine Pollen','pinus virginiana','Solution','PINUS VIRGINIANA POLLEN .05 g/mL','INTRADERMAL','Greer Laboratories, Inc.','US','Non-Standardized Pollen Allergenic Extract','Virginia Scrub Pine Pollen'),
('DHS Body Wash','zinc pyrithione','LIQUID','ZINC PYRITHIONE 50 mg/mL','Topique','Person and Covey','INT','Médicaments topiques','DHS Body Wash'),
('NAS Toner','salicylic acid','LIQUID','SALICYLIC ACID 1 g/1001','Topique','BURT''S BEES, INC.','INT','Médicaments topiques','NAS Toner'),
('Zap Neutral','sodium fluoride','Gel','SODIUM FLUORIDE 4.086 g/454g','DENTAL','Crosstex International Inc.','INT',NULL,'Zap Neutral'),
('Kroger Digestive Relief','bismuth subsalicylate','Comprimé','BISMUTH SUBSALICYLATE 262 mg/1','Orale','KROGER COMPANY','INT',NULL,'Kroger Digestive Relief'),
('DAILY SUNSCREEN BROAD SPECTRUM SPF 30','zinc oxide','Crème','ZINC OXIDE 155 mg/mL','Topique','S+','INT','Copper Absorption Inhibitor','DAILY SUNSCREEN BROAD SPECTRUM SPF 30'),
('Colgate Total SF Advanced Deep Clean','stannous fluoride','PASTE, DENTIFRICE','STANNOUS FLUORIDE 1.1 mg/g','DENTAL','Colgate-Palmolive Company','INT',NULL,'Colgate Total SF Advanced Deep Clean'),
('Juglans Cinerea','juglans cinerea','PELLET','JUGLANS CINEREA BRANCH BARK/ROOT BARK 6 [hp_C]/1','Orale','Hahnemann Laboratories, INC.','INT',NULL,'Juglans Cinerea'),
('Coriandrum Sativum (Coriander)','coriandrum sativum (coriander)','PELLET','CORIANDER 6 [hp_C]/1','Orale','Hahnemann Laboratories, INC.','INT',NULL,'Coriandrum Sativum (Coriander)'),
('RECARBRIO','imipenem anhydrous, cilastatin, and relebactam anhydrous','Solution','CILASTATIN 500 mg/100mL','Intraveineuse','Merck Sharp & Dohme LLC','US','Penem Antibacterial','RECARBRIO'),
('GAVISCON','aluminum hydroxide and magnesium carbonate','LIQUID','ALUMINUM HYDROXIDE 95 mg/15mL','Orale','Haleon US Holdings LLC','INT',NULL,'GAVISCON'),
('Mercurius Cyanatus','mercurius cyanatus','PELLET','MERCURIC CYANIDE 6 [hp_C]/1','Orale','Hahnemann Laboratories, INC.','INT',NULL,'Mercurius Cyanatus'),
('Zirconium Carbonicum','zirconium carbonicum','PELLET','ZIRCONIUM CARBONATE 6 [hp_C]/1','Orale','Hahnemann Laboratories, INC.','INT',NULL,'Zirconium Carbonicum'),
('HEB','acetaminophen','Comprimé','ACETAMINOPHEN 650 mg/1','Orale','HEB','US',NULL,'HEB'),
('Dehydrated Alcohol','alcohol','Solution','ALCOHOL 1 mL/mL','PERCUTANEOUS','XGen Pharmaceuticals DJB, Inc.','US',NULL,'Dehydrated Alcohol'),
('Meijer Anti Nausea','dextrose(glucose),levulose(fructose),phosphoric acid','LIQUID','DEXTROSE, UNSPECIFIED FORM 1.87 g/5mL','Orale','MEIJER DISTRIBUTION, INC.','INT',NULL,'Meijer Anti Nausea'),
('PUBLIX Sore Throat Menthol Flavor','phenol','Spray','PHENOL 1.4 g/100mL','Orale','PUBLIX SUPER MARKETS, INC','INT',NULL,'PUBLIX Sore Throat Menthol Flavor'),
('Olanzapine and Fluoxetine','olanzapine and fluoxetine','Gélule','FLUOXETINE HYDROCHLORIDE 25 mg/1','Orale','AvKARE','US','Atypical Antipsychotic','Olanzapine and Fluoxetine'),
('COMETRIQ','cabozantinib','Kit',NULL,NULL,'Exelixis, Inc.','US',NULL,'COMETRIQ'),
('Herz Plus','arsenicum album, cistus canadensis, clematis erecta, comocladia dentata, croton tiglium, dolichos pruriens, graphites, iris versicolor, kali bichromicum, kalmia latifolia, lachesis mutus, mercurius solubilis, mezereum, prunus spinosa, ranunculus bulbosus, rhus tox, zincum phosphoratum','LIQUID','ARSENIC TRIOXIDE 12 [hp_X]/mL','Orale','Deseret Biologicals, Inc.','INT',NULL,'Herz Plus'),
('Osteoforce','medulla ossis suis, calcarea carbonica, calcarea fluorica, causticum, cocculus indicus, ledum palustre, phosphoricum acidum, rhus tox','LIQUID','ANAMIRTA COCCULUS SEED 12 [hp_X]/mL','Orale','BioActive Nutritional, Inc.','INT',NULL,'Osteoforce'),
('Cort Sym','apis mellifica, belladonna, calcarea carbonica, mezereum, rhus tox, astacus fluviatilis, gelsemium sempervirens','Gel','APIS MELLIFERA 12 [hp_X]/g','Topique','Energique, Inc.','INT','Standardized Insect Venom Allergenic Extract','Cort Sym'),
('ZO Skin Health Daily Mineral Sunshade Broad-Spectrum Sunscreen SPF 45 (Tan)','titanium dioxide, zinc oxide','Lotion','TITANIUM DIOXIDE 54 mg/mL','Topique','ZO Skin Health Inc.','INT','Médicaments topiques','ZO Skin Health Daily Mineral Sunshade Broad-Spectrum Sunscreen SPF 45 (Tan)'),
('Swim-EAR','swim-ear','Solution','ISOPROPYL ALCOHOL 950 mg/mL','AURICULAR (OTIC)','Fougera Pharmaceuticals, LLC','INT',NULL,'Swim-EAR'),
('HA2CG Evolution','asclepias vincetoxicum, echinacea (angustifolia), hypothalamus (suis), cerebrum suis, hepar suis, kidney (suis), methylcobalamin, pancreas suis, stomach (suis), aacg-a, aacg-b, calcarea carbonica, gelsemium sempervirens, graphites, nux vomica, phytolacca decandra, gambogia, 7-oxo-dehydroepiandrosterone 3-acetate, adenosinum triphosphoricum dinatrum, insulinum (suis), sarcolacticum acidum, proteus (vulgaris)','LIQUID','7-OXODEHYDROEPIANDROSTERONE 3-ACETATE 30 [hp_X]/mL','Orale','Deseret Biologicals, Inc.','INT','Non-Standardized Plant Allergenic Extract','HA2CG Evolution'),
('Saccharomyces cerevisiae','saccharomyces cerevisiae','LIQUID','SACCHAROMYCES CEREVISIAE .1 g/mL','PERCUTANEOUS','Allermed Laboratories, Inc.','US','Non-Standardized Food Allergenic Extract','Saccharomyces cerevisiae'),
('Maybelline New York Dream Fresh BB Beauty Balm Skin Perfector Broad Spectrum SPF 30 Sunscreen','titanium dioxide','Crème','TITANIUM DIOXIDE 11.5 mg/mL','Topique','L''Oreal USA Products Inc','INT','Médicaments topiques','Maybelline New York Dream Fresh BB Beauty Balm Skin Perfector Broad Spectrum SPF 30 Sunscreen'),
('Vaccistat','baptisia tinctoria, echinacea (angustifolia), hydrastis canadensis, alumina, antimonium tartaricum, mezereum, natrum muriaticum, mercurius solubilis, silicea, thuja occidentalis, malandrinum, variolinum','LIQUID','ALUMINUM OXIDE 12 [hp_X]/mL','Orale','Energique, Inc.','INT','Live Vaccinia Virus Vaccine','Vaccistat'),
('good neighbor pharmacy loperamide hydrochloride','loperamide hcl','Solution','LOPERAMIDE HYDROCHLORIDE 1 mg/7.5mL','Orale','Amerisource Bergen','US','Opioid Agonist','good neighbor pharmacy loperamide hydrochloride'),
('Mercurialis Calendula','mercurialis calendula','Pommade','CALENDULA OFFICINALIS FLOWERING TOP 1 [hp_X]/g','Topique','Uriel Pharmacy Inc.','INT','Non-Standardized Food Allergenic Extract','Mercurialis Calendula'),
('Equate Cough DM','dextromethorphan polistirex','Suspension','DEXTROMETHORPHAN HYDROBROMIDE 30 mg/5mL','Orale','Wal-Mart Stores Inc','US','Sigma-1 Agonist','Equate Cough DM'),
('Methyl Salicylate 25 Percent','methyl salicylate','Crème','METHYL SALICYLATE 250 mg/mL','Topique','Alexso, Inc','INT','Médicaments topiques','Methyl Salicylate 25 Percent'),
('Levonest','levonorgestrel and ethinyl estradiol','Kit',NULL,NULL,'A-S Medication Solutions','US',NULL,'Levonest'),
('CareALL Arthritis and Muscle','capsaicin','Crème','CAPSAICIN .025 g/g','Topique','New World Imports, Inc','INT','Médicaments topiques','CareALL Arthritis and Muscle'),
('4% MENTHOL COLD THERAPY','menthol','Gel','MENTHOL, UNSPECIFIED FORM 4 g/100g','Topique','Universal Distribution Center LLC','INT','Médicaments topiques','4% MENTHOL COLD THERAPY')
) AS v(nom, dci, forme, dosage, voie, labo, pays, classe, nomcom)
WHERE NOT EXISTS (
  SELECT 1 FROM medicaments m WHERE UPPER(m.nom) = UPPER(v.nom)
);
