-- ndc_batch_028.sql (80 rows)
INSERT INTO medicaments (nom, dci, forme, dosage, voie_administration, laboratoire, pays, classe_therapeutique, nom_commercial)
SELECT v.nom, v.dci, v.forme, v.dosage, v.voie, v.labo, v.pays, v.classe, v.nomcom
FROM (VALUES
('Petroleum Jelly','baby petroleum jelly','JELLY','WHITE PETROLATUM 100 g/100g','Topique','NeilMed Pharmaceuticals Inc.','INT','Médicaments topiques','Petroleum Jelly'),
('LBEL FOREVER HYDRA LONGWEAR AND HYDRATING FOUNDATION 90H SPF 15 CHAMPAGNE 170N','octinoxate, zinc oxide','EMULSION','OCTINOXATE 50 mg/g','Topique','BEL STAR S.A.','INT','Médicaments topiques','LBEL FOREVER HYDRA LONGWEAR AND HYDRATING FOUNDATION 90H SPF 15 CHAMPAGNE 170N'),
('ACONITUM NAPELLUS','aconitum napellus','PELLET','ACONITUM NAPELLUS 3 [hp_X]/1','Orale','Rxhomeo Private Limited d.b.a. Rxhomeo, Inc','INT',NULL,'ACONITUM NAPELLUS'),
('POTASSIUM CITRATE','potassium citrate','Comprimé','POTASSIUM CITRATE 540 mg/1','Orale','Rising Pharma Holdings, Inc.','US','Anti-coagulant','POTASSIUM CITRATE'),
('Adenosine','adenosine','Solution','ADENOSINE 3 mg/mL','Intraveineuse','NorthStar Rx LLC','US','Adenosine Receptor Agonist','Adenosine'),
('Signature Select Effervescent Pain Relief','aspirin','Comprimé','ASPIRIN 325 mg/1','Orale','Safeway Inc.','INT','Nonsteroidal Anti-inflammatory Drug','Signature Select Effervescent Pain Relief'),
('YERVOY','ipilimumab','Solution injectable','IPILIMUMAB 5 mg/mL','Intraveineuse','E.R. Squibb & Sons, L.L.C.','US','CTLA-4-directed Blocking Antibody','YERVOY'),
('Red Mulberry Pollen','morus rubra','Solution','MORUS RUBRA POLLEN .05 g/mL','INTRADERMAL','Greer Laboratories, Inc.','US','Non-Standardized Pollen Allergenic Extract','Red Mulberry Pollen'),
('Plantain Sorrel Mix','plantago lanceolata and rumex acetosella','Solution','PLANTAGO LANCEOLATA POLLEN .05 g/mL','INTRADERMAL','Greer Laboratories, Inc.','US','Non-Standardized Pollen Allergenic Extract','Plantain Sorrel Mix'),
('DANZITEN','nilotinib','Comprimé','NILOTINIB 71 mg/1','Orale','Azurity Pharmaceuticals, Inc.','US','Kinase Inhibitor','DANZITEN'),
('Ultomiris','ravulizumab','Solution','RAVULIZUMAB 300 mg/30mL','Intraveineuse','Alexion Pharmaceuticals Inc.','US','Complement Inhibitor','Ultomiris'),
('NightTime','acetaminophen, dextromethorphan hbr, doxylamine succinate','Solution','ACETAMINOPHEN 650 mg/30mL','Orale','Kroger Company','INT','Antihistamine','NightTime'),
('Altra Non-Alcohol Foaming Hand Sanitizer with Allantoin and Aloe','benzalkonium chloride','Solution','BENZALKONIUM CHLORIDE .12 g/100mL','Topique','Buckeye International, Inc.','INT','Médicaments topiques','Altra Non-Alcohol Foaming Hand Sanitizer with Allantoin and Aloe'),
('Protex Complete Antibacterial Bar','chloroxylenol','SOAP','CHLOROXYLENOL 3 mg/g','Topique','Colgate-Palmolive Company','INT','Médicaments topiques','Protex Complete Antibacterial Bar'),
('Vapor Inhaler levmetamfetamine nasal decongestant, TopCare health','levmetamfetamine','INHALANT','LEVMETAMFETAMINE 50 mg/1','Nasale','Topco Associates LLC','INT',NULL,'Vapor Inhaler levmetamfetamine nasal decongestant, TopCare health'),
('TopCare Health Advanced Moisturizing Plus Redness Relief','dextran 70, polyethylene glycol 400, povidone, tetrahydrozoline hcl','Solution','DEXTRAN 70 .1 g/100mL','Ophtalmique','Topco Associates LLC','INT','Plasma Volume Expander','TopCare Health Advanced Moisturizing Plus Redness Relief'),
('Calcarea Fluorica','calcarea fluorica','PELLET','CALCIUM FLUORIDE 6 [hp_C]/1','Orale','Hahnemann Laboratories, INC.','INT',NULL,'Calcarea Fluorica'),
('Cobaltum Oxydatum','cobaltum oxydatum','PELLET','COBALT OXIDE 6 [hp_C]/1','Orale','Hahnemann Laboratories, INC.','INT',NULL,'Cobaltum Oxydatum'),
('Gallium Fluoratum','gallium fluoratum','PELLET','GALLIUM TRIFLUORIDE 6 [hp_C]/1','Orale','Hahnemann Laboratories, INC.','INT',NULL,'Gallium Fluoratum'),
('REGULAR STRENGTH ANTACID MINT','aluminum hydroxide, magnesium hydroxide, dimethicone','Suspension','ALUMINUM HYDROXIDE 400 mg/10mL','Orale','H E B','INT','Calculi Dissolution Agent','REGULAR STRENGTH ANTACID MINT'),
('Amphotericin B','amphotericin b','Solution','AMPHOTERICIN B 50 mg/10mL','Intraveineuse','XGen Pharmaceuticals DJB, Inc.','US','Lipid-based Polyene Antifungal','Amphotericin B'),
('Hand Wash','benzalkonium chloride','LIQUID','BENZALKONIUM CHLORIDE 1.3 mg/mL','Topique','United Natural Foods, Inc. dba UNFI','INT','Médicaments topiques','Hand Wash'),
('ICY Hot Pro No Mess Two Pack','camphor, menthol','Crème','CAMPHOR (SYNTHETIC) 11 g/100g','Topique','Chattem, Inc.','INT','Médicaments topiques','ICY Hot Pro No Mess Two Pack'),
('Meijer Senna Laxative Regular Strength','sennosides','Comprimé','SENNOSIDES 8.6 mg/1','Orale','MEIJER, INC.','INT',NULL,'Meijer Senna Laxative Regular Strength'),
('Publix antibiotic plus Pain Relief','neomycin sulfate, polymyxin b sulfate, and pramoxine hydrochloride','Crème','NEOMYCIN SULFATE 3.5 mg/g','Topique','Publix Super Markets Inc','INT','Aminoglycoside Antibacterial','Publix antibiotic plus Pain Relief'),
('Vasostrict','vasopressin','Solution injectable','VASOPRESSIN, UNSPECIFIED .4 [USP''U]/mL','Intraveineuse','Par Health USA, LLC','US','Médicaments IV / Hospitaliers','Vasostrict'),
('Intimate','anacardium orientale, aurum muriaticum natronatum, camphora, dna (human), germanium metallicum, helleborus niger, hydrogen, lac caninum, lac materna humanum, lithium carbonicum, magnesia oxydata, natrum carbonicum, neon, oxytocin, placenta totalis suis, rhus glabra, saccharum officinale, stramonium, thuja occidentalis','LIQUID','CAMPHOR (NATURAL) 12 [hp_X]/mL','Orale','Deseret Biologicals, Inc.','INT','Calculi Dissolution Agent','Intimate'),
('CANDIDA ALB','candida albicans','LIQUID','CANDIDA ALBICANS 60 [hp_X]/mL','Orale','BioActive Nutritional, Inc.','INT','Non-Standardized Fungal Allergenic Extract','CANDIDA ALB'),
('MIGLUSTAT','miglustat','Gélule','MIGLUSTAT 100 mg/1','Orale','ANI Pharmaceuticals, Inc.','US','Enzyme Stabilizer','MIGLUSTAT'),
('Multi Flower','aesculus carnea, flos, aesculus hippocastanum, flos, agrimonia eupatoria, flos, bromus ramosus, flos, calluna vulgaris, flos, carpinus betulus , flos, castanea sativa, flos, centaurium umbellatum, flos, ceratostigma willmottianum, flos, cichorium intybus, flos, clematis vitalba, flos, clematis vitalba, flos, fagus sylvatica, flos, gentianella amarella, flos, helianthemum nummularium, flos, ilex aquifolium, flos, impatiens glandulifera, flos, larix decidua, flos, lonicera caprifolium, flos','LIQUID','AESCULUS CARNEA FLOWER 30 [hp_C]/mL','Orale','Energique, Inc.','INT',NULL,'Multi Flower'),
('365 Whole Foods Market Epsom Salt','magnesium sulfate','Solution','MAGNESIUM SULFATE HEPTAHYDRATE 1 g/g','Orale','Whole Foods Market, Inc.','INT','Calculi Dissolution Agent','365 Whole Foods Market Epsom Salt'),
('Digestion','gentiana lut, sambucus nig, arsenicum alb, bismuth sub, carbo veg, kali bic, lycopodium, nux vom, phosphorus, pulsatilla','LIQUID','ACTIVATED CHARCOAL 12 [hp_X]/mL','Orale','Natural Creations, Inc','INT','Bismuth','Digestion'),
('Alfuzosin hydrochloride','alfuzosin hydrochloride','Comprimé','ALFUZOSIN HYDROCHLORIDE 10 mg/1','Orale','Aphena Pharma Solutions - Tennessee, LLC','US','alpha-Adrenergic Blocker','Alfuzosin hydrochloride'),
('PMS Relief','agnus castus, cimicifuga racemosa, kali carbonicum, lycopodium clavatum, saccharum officinale, thyroidinum (bovine), hypothalamus suis, aristolochia clematitis, folliculinum, aurum sulphuratum, candida albicans, cocculus indicus, conium maculatum, cyclamen europaeum, elaps corallinus, lac caninum, lachesis mutus, magnesia carbonica, pulsatilla (pratensis), stannum metallicum','LIQUID','ANAMIRTA COCCULUS SEED 12 [hp_X]/mL','Orale','Deseret Biologicals, Inc.','INT','Non-Standardized Fungal Allergenic Extract','PMS Relief'),
('SENNA TIME','sennosides','Comprimé','SENNOSIDES A AND B 8.6 mg/1','Orale','TIME CAP LABORATORIES, INC','INT',NULL,'SENNA TIME'),
('Curvularia','curvularia lunata','Solution injectable','COCHLIOBOLUS LUNATUS .1 g/mL','CUTANEOUS','Allermed Laboratories, Inc.','US','Non-Standardized Fungal Allergenic Extract','Curvularia'),
('Lancome Paris Visionnaire Broad Spectrum SPF 20 Sunscreen Advanced Multi Correcting All Skin Types','avobenzone, octisalate and octocrylene','Crème','AVOBENZONE 30 mg/g','Topique','L''Oreal USA Products Inc','INT','Médicaments topiques','Lancome Paris Visionnaire Broad Spectrum SPF 20 Sunscreen Advanced Multi Correcting All Skin Types'),
('Vermiclear','granatum, rhamnus purshiana, juglans regia, filix mas, absinthium, aesculus hippocastanum, arsenicum album, baptisia tinctoria, cina, cuprum metallicum, ipecacuanha, lycopodium clavatum, mercurius vivus, nux vomica, pulsatilla (vulgaris), ratanhia, rhus tox, sabadilla, santoninum, silicea, spigelia anthelmia, terebinthina, teucrium marum','LIQUID','ARSENIC TRIOXIDE 15 [hp_X]/mL','Orale','Energique, Inc.','INT','Copper-containing Intrauterine Device','Vermiclear'),
('Imiquimod','imiquimod','Crème','IMIQUIMOD 12.5 mg/.25g','Topique','Padagis Israel Pharmaceuticals Ltd','US','Increased Cytokine Activity','Imiquimod'),
('Nicotine Polacrilex coated ice mint','nicotine polacrilex','GUM, CHEWING','NICOTINE 2 mg/1','Buccale','AmerisourceBergen (Good Neighbor Pharmacy) 46122','US','Cholinergic Nicotinic Agonist','Nicotine Polacrilex coated ice mint'),
('Medique Extra Strength Apap','acetaminophen','Comprimé','ACETAMINOPHEN 500 mg/1','Orale','Unifirst First Aid Corporation','INT',NULL,'Medique Extra Strength Apap'),
('Anacardium orientale','semecarpus anacardium juice','PELLET','SEMECARPUS ANACARDIUM JUICE 200 [kp_C]/200[kp_C]','Orale','Boiron','INT',NULL,'Anacardium orientale'),
('Antimonium crudum','antimony trisulfide','PELLET','ANTIMONY TRISULFIDE 5 [hp_C]/5[hp_C]','Orale','Boiron','INT',NULL,'Antimonium crudum'),
('Diaper Rash','zinc oxide','PASTE','ZINC OXIDE 400 mg/g','Topique','Walmart Inc.','INT','Médicaments topiques','Diaper Rash'),
('MG FoamSan','benzalkonium chloride','LIQUID','BENZALKONIUM CHLORIDE .1 g/100g','Topique','Morgan Gallacher Inc. DBA Custom Chemical Formulators Inc.','INT','Médicaments topiques','MG FoamSan'),
('PVP Iodine','povidone-iodine','SWAB','POVIDONE-IODINE .1 g/g','Topique','HART Health','INT','Médicaments topiques','PVP Iodine'),
('Asepxia Softening Acne Bar','salicylic acid','SOAP','SALICYLIC ACID 2 g/100g','Topique','Genomma Lab USA','INT','Médicaments topiques','Asepxia Softening Acne Bar'),
('Olmesartan Medoxomil and Hydrochlorothiazide','olmesartan medoxomil and hydrochlorothiazide','Comprimé','HYDROCHLOROTHIAZIDE 12.5 mg/1','Orale','A-S Medication Solutions','US','Angiotensin 2 Receptor Blocker','Olmesartan Medoxomil and Hydrochlorothiazide'),
('clear days ahead fast-acting salicylic acid acne spot treatment','salicylic acid','Gel','SALICYLIC ACID .3 g/15mL','Topique','Philosophy','INT','Médicaments topiques','clear days ahead fast-acting salicylic acid acne spot treatment'),
('CLOMIPRAMINE HYDROCHLORIDE','clomipramine hydrochloride','Gélule','CLOMIPRAMINE HYDROCHLORIDE 25 mg/1','Orale','Sun Pharmaceutical Industries, Inc.','US','Tricyclic Antidepressant','CLOMIPRAMINE HYDROCHLORIDE'),
('CAREALL Clotrimazole','clotrimazole','Crème','CLOTRIMAZOLE 10 g/g','Topique','New World Imports, Inc','INT','Azole Antifungal','CAREALL Clotrimazole'),
('Dimethicone 1 Skin Protectant','dimethicone','Lotion','DIMETHICONE, UNSPECIFIED 1 g/100mL','Topique','Universal Distribution Center LLC','INT','Skin Barrier Activity','Dimethicone 1 Skin Protectant'),
('Baby Petrolatum Jelly','petrolatum','JELLY','PETROLATUM 99.9 g/100g','Topique','SHIELD LINE LLC','INT','Médicaments topiques','Baby Petrolatum Jelly'),
('MILK OF MAGNESIA ORIGINAL','magnesium hydroxide','Suspension','MAGNESIUM HYDROXIDE 1200 mg/15mL','Orale','GOODSENSE','INT','Calculi Dissolution Agent','MILK OF MAGNESIA ORIGINAL'),
('Cuprum metallicum','copper','PELLET','COPPER 7 [hp_C]/7[hp_C]','Orale','Boiron','INT','Copper-containing Intrauterine Device','Cuprum metallicum'),
('Dolichos pruriens','mucuna pruriens fruit trichome','PELLET','MUCUNA PRURIENS FRUIT TRICHOME 30 [hp_C]/30[hp_C]','Orale','Boiron','INT',NULL,'Dolichos pruriens'),
('COLTALIN-ND','acetaminophen, phenylephrine hydrochloride','Comprimé','ACETAMINOPHEN 325 mg/1','Orale','FORTUNE PHARMACAL COMPANY LIMITED','INT','alpha-1 Adrenergic Agonist','COLTALIN-ND'),
('CVS Stomach Relief','bismuth subsalicylate','Comprimé','BISMUTH SUBSALICYLATE 262 mg/1','Orale','CVS','INT','Bismuth','CVS Stomach Relief'),
('CVS Adult Mucus chest congestion','guaifenesin','Sirop','GUAIFENESIN 200 mg/10mL','Orale','CVS PHARMACY','INT','Expectorant','CVS Adult Mucus chest congestion'),
('PHENYLEPHRINE HCI','phenylephrine hci','Solution injectable','PHENYLEPHRINE HYDROCHLORIDE 10 mg/mL','Intraveineuse','HF Acquisition Co LLC, DBA HealthFirst','US','alpha-1 Adrenergic Agonist','PHENYLEPHRINE HCI'),
('3 Hydrogen Peroxide','hydrogen peroxide','LIQUID','HYDROGEN PEROXIDE 30 mg/mL','Topique','Midwood Brands LLC','INT','Médicaments topiques','3 Hydrogen Peroxide'),
('Medline','petrolatum','Pommade','WHITE PETROLATUM 934 mg/g','Topique','Medline Industries, LP','INT','Médicaments topiques','Medline'),
('Aurum Metallicum 18X','aurum metallicum 18x','LIQUID','GOLD 18 [hp_X]/30mL','Orale','True Botanica, LLC','INT','Standardized Chemical Allergen','Aurum Metallicum 18X'),
('Adult Low Strength Aspirin','aspirin','Comprimé','ASPIRIN 81 mg/1','Orale','DISCOUNT DRUG MART','INT','Nonsteroidal Anti-inflammatory Drug','Adult Low Strength Aspirin'),
('Tinted Face Cream SPF 15','octocrylene, octisalate','Crème','OCTISALATE 2 g/100mL','Topique','Bentley Laboratories, LLC','INT','Médicaments topiques','Tinted Face Cream SPF 15'),
('Melissa officinalis','melissa officinalis','PELLET','MELISSA OFFICINALIS 30 [hp_C]/30[hp_C]','Orale','Boiron','INT',NULL,'Melissa officinalis'),
('Mercurius solubilis','mercurius solubilis','PELLET','MERCURIUS SOLUBILIS 9 [hp_C]/9[hp_C]','Orale','Boiron','INT',NULL,'Mercurius solubilis'),
('Mezereum','daphne mezereum bark','PELLET','DAPHNE MEZEREUM BARK 1 [hp_M]/[hp_M]','Orale','Boiron','INT',NULL,'Mezereum'),
('cle de peau BEAUTE THE FOUNDATION N O80 DEEP OCHER','octinoxate and titanium dioxide','EMULSION','OCTINOXATE 1092 mg/28mL','Topique','SHISEIDO AMERICAS CORPORATION','INT','Médicaments topiques','cle de peau BEAUTE THE FOUNDATION N O80 DEEP OCHER'),
('Giltuss TR','guaifenesin,dextromethorphan hbr,phenylephrine hcl','Comprimé','DEXTROMETHORPHAN HYDROBROMIDE 29 mg/1','Orale','Gil Pharmaceutical Corp','INT','Expectorant','Giltuss TR'),
('ESTERIFIED ESTROGENS AND METHYLTESTOSTERONE FULL STRENGTH','esterified estrogens, methyltestosterone','Comprimé','ESTROGENS, ESTERIFIED 1.25 mg/1','Orale','Method Pharmaceuticals, LLC','INT','Androgen','ESTERIFIED ESTROGENS AND METHYLTESTOSTERONE FULL STRENGTH'),
('Double Antibiotic','bacitracin zinc and polymyxin b sulfate','Pommade','BACITRACIN ZINC 500 [USP''U]/g','Topique','STRATUS PHARMACEUTICALS INC','INT','Polymyxin-class Antibacterial','Double Antibiotic'),
('PharmapureRx Lidocaine HCl 4.12%','lidocaine hydrochloride','Crème','LIDOCAINE HYDROCHLORIDE 41.2 mg/g','Topique','PureTek Corporation','INT','Amide Local Anesthetic','PharmapureRx Lidocaine HCl 4.12%'),
('Gas-Indigestion','chamomilla, echinacea, iris versicolor, ruta graveolens, taraxacum officinale, antimonium crudum, arsenicum album, baptisia tinctoria, bryonia, carbo vegetabilis, chelidonium majus, cinchona officinalis, colchicum autumnale, daphne indica, ipecacuanha, iris versicolor, kali carbonicum, kreosotum, lachesis mutus, lycopodium clavatum, magnesia carbonica, mercurius vivus, nux vomica, phosphorus, pulsatilla, spigelia anthelmia, sulphur, pyrogenium','LIQUID','ACTIVATED CHARCOAL 15 [hp_X]/mL','Orale','Newton Laboratories, Inc.','INT','Non-Standardized Plant Allergenic Extract','Gas-Indigestion'),
('DG Health Triple Antibiotic','bacitracin zinc, neomycin, polymyxin b','Pommade','BACITRACIN ZINC 400 [USP''U]/g','Topique','Dolgencorp, LLC','INT','Aminoglycoside Antibacterial','DG Health Triple Antibiotic'),
('dg health 8 hr arthritis pain relief','acetaminophen','Comprimé','ACETAMINOPHEN 650 mg/1','Orale','Dolgencorp Inc','US',NULL,'dg health 8 hr arthritis pain relief'),
('3.5OZ MP DRY ACTIVE SPORT','aluminum chlorohydrate','Spray','ALUMINUM CHLOROHYDRATE 24.5 g/100g','Topique','Rejoice International Corp.','INT','Médicaments topiques','3.5OZ MP DRY ACTIVE SPORT'),
('Xanax','alprazolam','Comprimé','ALPRAZOLAM .25 mg/1','Orale','Viatris Specialty LLC','US','Benzodiazepine','Xanax'),
('N-2','selenicereus grandiflorus whole, crataegus laevigata whole, dibasic potassium phosphate, arnica montana, valeriana officinalis whole, spigelia anthelmia, and beef heart','Solution','ARNICA MONTANA 6 [hp_X]/mL','Sublinguale','DNA Labs, Inc.','INT',NULL,'N-2'),
('BeneFIX','coagulation factor ix (recombinant)','Kit',NULL,NULL,'Wyeth BioPharma Division of Wyeth Pharmaceuticals LLC','US',NULL,'BeneFIX')
) AS v(nom, dci, forme, dosage, voie, labo, pays, classe, nomcom)
WHERE NOT EXISTS (
  SELECT 1 FROM medicaments m WHERE UPPER(m.nom) = UPPER(v.nom)
);
