-- ndc_batch_130.sql (80 rows)
INSERT INTO medicaments (nom, dci, forme, dosage, voie_administration, laboratoire, pays, classe_therapeutique, nom_commercial)
SELECT v.nom, v.dci, v.forme, v.dosage, v.voie, v.labo, v.pays, v.classe, v.nomcom
FROM (VALUES
('Fluocinolone Acetonide Oil','fluocinolone acetonide','OIL','FLUOCINOLONE ACETONIDE .11 mg/mL','AURICULAR (OTIC)','Rising Pharma Holdings, Inc.','US','Corticosteroid','Fluocinolone Acetonide Oil'),
('Pollens - Trees, Elm, American Ulmus americana','elm, american ulmus americana','Solution','ULMUS AMERICANA POLLEN .05 g/mL','PERCUTANEOUS','Jubilant HollisterStier LLC','US','Non-Standardized Pollen Allergenic Extract','Pollens - Trees, Elm, American Ulmus americana'),
('Molds, Penicillium Mix','molds, penicillium mix','Solution','CLONOSTACHYS ROSEA F. ROSEA .1 g/mL','PERCUTANEOUS','Jubilant HollisterStier LLC','US','Non-Standardized Fungal Allergenic Extract','Molds, Penicillium Mix'),
('Premier Value Zinc Cold Therapy Citrus Flavor','zinc gluconate','Comprimé','ZINC GLUCONATE 1 [hp_X]/1','Orale','PHARMACY VALUE ALLIANCE, LLC','INT','Copper Absorption Inhibitor','Premier Value Zinc Cold Therapy Citrus Flavor'),
('VFEND','voriconazole','Solution','VORICONAZOLE 10 mg/mL','Intraveineuse','Roerig','US','Azole Antifungal','VFEND'),
('Eucerin Advanced Hydration Sunscreen SPF 50','avobenzone, homosalate, octisalate, octocrylene','Spray','AVOBENZONE 3 g/100g','Topique','Beiersdorf Inc','INT','Médicaments topiques','Eucerin Advanced Hydration Sunscreen SPF 50'),
('Atovaquone and Proguanil HCl','atovaquone and proguanil hydrochloride','Comprimé','ATOVAQUONE 250 mg/1','Orale','Prasco Laboratories','US','Antimalarial','Atovaquone and Proguanil HCl'),
('Acne Treatment','benzoyl peroxide','Lotion','BENZOYL PEROXIDE 50 mg/mL','Topique','Vivier Pharma, Inc.','INT','Médicaments topiques','Acne Treatment'),
('Degasa Hand Sanitizer Lemon Lime Scent','alcohol','Gel','ALCOHOL .7 mL/mL','Topique','Degasa, S.A. de C.V.','INT','Médicaments topiques','Degasa Hand Sanitizer Lemon Lime Scent'),
('Colace','docusate sodium - sennosides','Comprimé','DOCUSATE SODIUM 50 mg/1','Orale','Atlantis Consumer Healthcare, Inc.','INT',NULL,'Colace'),
('Walgreens Scar Cream w/SPF 30','avobenzone3%,octocrylene10%,oxybenone 6%','Crème','AVOBENZONE 30 mg/g','Topique','Walgreens','INT','Médicaments topiques','Walgreens Scar Cream w/SPF 30'),
('YUTIQ','fluocinolone acetonide','Implant','FLUOCINOLONE ACETONIDE .18 mg/1','INTRAVITREAL','ANI Pharmaceuticals, Inc.','US','Corticosteroid','YUTIQ'),
('CopperFixx','copper and arnica montana','Pommade','ARNICA MONTANA 4 [hp_X]/57g','Topique','Quest Products, Inc.','INT','Copper-containing Intrauterine Device','CopperFixx'),
('Sorbutuss NR','sorbutuss','LIQUID','DEXTROMETHORPHAN HYDROBROMIDE 10 mg/5mL','Orale','Dextrum Laboratories Inc.','INT','Expectorant','Sorbutuss NR'),
('Daytrana','methylphenidate','Patch transdermique','METHYLPHENIDATE 15 mg/9h','Transdermique','Noven Therapeutics, LLC','US','Central Nervous System Stimulant','Daytrana'),
('Sun Bum Sunscreen Oil 50 5 OZ','avobenzone, homosalate, octisalate, octocrylene','OIL','AVOBENZONE 30 mg/mL','Topique','Sun Bum, LLC','INT','Médicaments topiques','Sun Bum Sunscreen Oil 50 5 OZ'),
('Allergy DyeFree','allergy dyefree','Gélule','DIPHENHYDRAMINE HYDROCHLORIDE 25 mg/1','Orale','Allegiant Health','INT','Histamine-1 Receptor Antagonist','Allergy DyeFree'),
('Bye Bye Foundation Full Coverage Moisturizer SPF 50 Neutral Tan','titanium dioxide and zinc oxide','Crème','TITANIUM DIOXIDE 9 g/100mL','Topique','IT COSMETICS, LLC','INT','Médicaments topiques','Bye Bye Foundation Full Coverage Moisturizer SPF 50 Neutral Tan'),
('Guaifenesin Syrup and Dextromethorphan','guaifenesin syrup and dextromethorphan','Sirop','DEXTROMETHORPHAN HYDROBROMIDE 10 mg/5mL','Orale','Natco Pharma USA LLC','INT','Expectorant','Guaifenesin Syrup and Dextromethorphan'),
('First Aid Beauty FAB Broad Spectrum Sunscreen SPF 30','octinoxate, octocrylene, and zinc oxide','Crème','OCTINOXATE 5.6 g/100mL','Topique','The Procter & Gamble Manufacturing Company','INT','Médicaments topiques','First Aid Beauty FAB Broad Spectrum Sunscreen SPF 30'),
('Vicks DayQuil and Nyquil VapoCOOL Severe COLD and FLU plus CONGESTION','acetaminophen, phenylephrine hydrochloride, and doxylamine succinate','Kit',NULL,'Orale','The Procter & Gamble Manufacturing Company','INT',NULL,'Vicks DayQuil and Nyquil VapoCOOL Severe COLD and FLU plus CONGESTION'),
('Umbra Tinte Mineral Cream SPF 30','zinc oxide','Crème','ZINC OXIDE 12 g/60mL','Topique','Drunk Elephant, LLC','INT','Médicaments topiques','Umbra Tinte Mineral Cream SPF 30'),
('Absorbine Jr Neck and Shoulder','absorbine jr neck and shoulder','Patch transdermique','MENTHOL 7500 mg/h','Topique','Clarion Brands LLC','INT','Médicaments topiques','Absorbine Jr Neck and Shoulder'),
('Akin Cough Formula DM','dextromethorphan, guaifenesin','LIQUID','DEXTROMETHORPHAN HYDROBROMIDE 10 mg/5mL','Orale','Southern Sales & Service, Inc.','INT','Expectorant','Akin Cough Formula DM'),
('Lidocaine Dry','lidocaine','Spray','LIDOCAINE 4 g/100mL','Topique','CVS','INT','Amide Local Anesthetic','Lidocaine Dry'),
('Ephedrine Hydrochloride','ephedrine hydrochloride','Comprimé','EPHEDRINE HYDROCHLORIDE 12.5 mg/1','Orale','Walgreen Company','INT','Norepinephrine Releasing Agent','Ephedrine Hydrochloride'),
('Benadryl Extra Strength Itch Stopping','diphenhydramine hydrochloride and zinc acetate','Crème','DIPHENHYDRAMINE HYDROCHLORIDE 20 mg/g','Topique','Kenvue Brands LLC','INT','Copper Absorption Inhibitor','Benadryl Extra Strength Itch Stopping'),
('Lip Clear Lysine Plus','menthol, unspecified form','Pommade','MENTHOL, UNSPECIFIED FORM 1 mg/g','Topique','Quantum, Inc.','INT','Médicaments topiques','Lip Clear Lysine Plus'),
('Zanaflex','tizanidine hydrochloride','Gélule','TIZANIDINE HYDROCHLORIDE 6 mg/1','Orale','Covis Pharma US, Inc','US','Central alpha-2 Adrenergic Agonist','Zanaflex'),
('Centellian24 Madeca Derma Shield Vital Dewy Sunscreen','avobenzone, homosalate, octisalate, octrocrylene','Crème','AVOBENZONE 2.8 g/100mL','Topique','70541','INT','Médicaments topiques','Centellian24 Madeca Derma Shield Vital Dewy Sunscreen'),
('foster and thrive acid reducer antacid','famotidine, calcium carbonate and magnesium hydroxide','Comprimé','CALCIUM CARBONATE 800 mg/1','Orale','Strategic Sourcing Services LLC','US','Calculi Dissolution Agent','foster and thrive acid reducer antacid'),
('Rocklatan','netarsudil and latanoprost ophthalmic solution, 0.02%/0.005%','Solution','LATANOPROST .05 mg/mL','Ophtalmique','Alcon Laboratories, Inc.','US','Rho Kinase Inhibitor','Rocklatan'),
('Doctor Butlers Hemorrhoid and Fissure External Pain Formula','lidocaine 5%','Crème','LIDOCAINE 5 g/100g','Topique','Beyond Health, P.A.','INT','Amide Local Anesthetic','Doctor Butlers Hemorrhoid and Fissure External Pain Formula'),
('Charm Tex FLUORIDE','sodium monofluorophosphate','PASTE, DENTIFRICE','SODIUM MONOFLUOROPHOSPHATE .1 g/100g','Topique','Yangzhou Hongshengding Chemical Co.,Ltd.','INT','Médicaments topiques','Charm Tex FLUORIDE'),
('Mucus Relief Cough and Congestion DM','guaifenesin and dextromethorphan hbr','Comprimé','DEXTROMETHORPHAN HYDROBROMIDE 20 mg/1','Orale','Bryant Ranch Prepack','INT','Expectorant','Mucus Relief Cough and Congestion DM'),
('PredniSONE Tablets, USP, 10 mg','prednisone','Comprimé','PREDNISONE 10 mg/1','Orale','Bryant Ranch Prepack','US','Corticosteroid','PredniSONE Tablets, USP, 10 mg'),
('Viabecline','tetracycline hydrochloride','Pommade','TETRACYCLINE HYDROCHLORIDE 30 mg/mL','Topique','Accuria, LLC','INT','Tetracycline-class Antimicrobial','Viabecline'),
('Virus Defense ANNAKARE','aconitum napellus root, arsenic trioxide, baptisia tinctoria whole, bryonia alba root, echinacea angustifolia whole, eupatorium perfoliatum whole, gelsemium sempervirens whole, glycyrrhiza glabra, hydrastis canadensis whole, toxicodendron pubescens leaf','Spray','ACONITUM NAPELLUS ROOT 12 [hp_X]/30mL','Orale','Ratis, LLC','INT','Non-Standardized Food Allergenic Extract','Virus Defense ANNAKARE'),
('basic care daytime severe cold and flu nighttime severe cold and flu','acetaminophen, dextromethorphan hbr, doxylamine succinate, guaifenesin, phenylephrine hcl','Kit',NULL,NULL,'Amazon.com Services LLC','INT',NULL,'basic care daytime severe cold and flu nighttime severe cold and flu'),
('Perfect Glow BB Cream Sunscreen SPF 30 - Medium Tan','octinoxate, titanium dioxide, zinc oxide','Crème','OCTINOXATE 6.5 g/100mL','Topique','Pur-lisse Beauty, LLC','INT','Médicaments topiques','Perfect Glow BB Cream Sunscreen SPF 30 - Medium Tan'),
('Curist Lidocaine Numbing Relief','lidocaine','Crème','LIDOCAINE 5 g/100g','Topique','Little Pharma, Inc.','INT','Amide Local Anesthetic','Curist Lidocaine Numbing Relief'),
('American Safety First Aid Antispetic','hydrogen peroxide','Spray','HYDROGEN PEROXIDE 30 mL/1000mL','Topique','Orazen Inc','INT','Médicaments topiques','American Safety First Aid Antispetic'),
('EltaMD UV SPF 30 Plus','zinc oxide and octinoxate sunscreen','Lotion','OCTINOXATE 75 g/1000g','Topique','CP Skin Health Group, Inc.','INT','Copper Absorption Inhibitor','EltaMD UV SPF 30 Plus'),
('Dakins Full','sodium hypochlorite','Solution','SODIUM HYPOCHLORITE 5 mg/mL','Topique','Century Pharmaceuticals, Inc.','INT','Médicaments topiques','Dakins Full'),
('Hydroxyzine HCL','hydroxyzine hcl','Comprimé','HYDROXYZINE DIHYDROCHLORIDE 50 mg/1','Orale','Direct_rx','US','Antihistamine','Hydroxyzine HCL'),
('Sinus Congestion and Pain Maximum Strength','acetaminophen, phenylephrine hcl','Comprimé','ACETAMINOPHEN 325 mg/1','Orale','Rugby Laboratories','INT','alpha-1 Adrenergic Agonist','Sinus Congestion and Pain Maximum Strength'),
('STIMUFEND','pegflilgrastim-fpgk','Solution','PEGFILGRASTIM 6 mg/.6mL','Sous-cutanée','NORTHSTAR RX LLC','US','Leukocyte Growth Factor','STIMUFEND'),
('DCH Calaspray Itch Relief','pramoxine hcl 1%, zinc acetate 0.1%','Spray','PRAMOXINE HYDROCHLORIDE 1 g/100g','Topique','Derma Care Research Labs, LLC','INT','Copper Absorption Inhibitor','DCH Calaspray Itch Relief'),
('Systane Ultra Preservative Free','polyethylene glycol 400 and propylene glycol','Solution','POLYETHYLENE GLYCOL 400 4 mg/mL','Ophtalmique','Alcon Laboratories, Inc.','INT','Ophtalmologie','Systane Ultra Preservative Free'),
('DANYELZA','naxitamab','Solution injectable','NAXITAMAB 40 mg/10mL','Intraveineuse','Y-mAbs Therapeutics, Inc.','US','Glycolipid Disialoganglioside-directed Antibody','DANYELZA'),
('XPHOZAH 30 mg','tenapanor','Comprimé','TENAPANOR HYDROCHLORIDE 30 mg/1','Orale','Ardelyx, Inc.','US','Sodium-Hydrogen Exchanger 3 Inhibitor','XPHOZAH 30 mg'),
('ABOVE NBA MEN SPORT PLUS ANTIPERSPIRANT DEODORANT 72H','above nba men sport plus antiperspirant deodorant 72h','Spray','ALUMINUM SESQUICHLOROHYDRATE 19.2 mg/100g','Topique','BASTON INUSTRIA DE AEROSSOIS LTDA','INT','Médicaments topiques','ABOVE NBA MEN SPORT PLUS ANTIPERSPIRANT DEODORANT 72H'),
('Clindamycin Phosphate and Tretinoin','clindamycin phosphate and tretinoin','Gel','CLINDAMYCIN PHOSPHATE 10 mg/g','Topique','Solaris Pharma Corporation','US','Lincosamide Antibacterial','Clindamycin Phosphate and Tretinoin'),
('TOPCARE Childrens Cold and Cough and Runny Nose','acetaminophen, chlorpheniramine maleate, and dextromethorphan hydrobromide','Suspension','ACETAMINOPHEN 160 mg/5mL','Orale','Topco Associates, LLC','INT','Histamine-1 Receptor Antagonist','TOPCARE Childrens Cold and Cough and Runny Nose'),
('e.l.f Skin Acne-Treating Body Mist','salicylic acid','LIQUID','SALICYLIC ACID 20 mg/mL','Topique','e.l.f. Cosmetics, Inc','INT','Médicaments topiques','e.l.f Skin Acne-Treating Body Mist'),
('Purifi Hand Sanitizer','benzalkonium chloride','Solution','BENZALKONIUM CHLORIDE .13 g/100mL','Topique','Purifi LLC','INT','Médicaments topiques','Purifi Hand Sanitizer'),
('Sure Invisible Solid Fresh and Cool','aluminum zirconium trichlorohydrex gly','STICK','ALUMINUM ZIRCONIUM TRICHLOROHYDREX GLY 19 g/100g','Topique','Sodalis USA LLC','INT','Médicaments topiques','Sure Invisible Solid Fresh and Cool'),
('SULFACETAMIDE SODIUM, SULFUR','sulfacetamide sodium, sulfur','Solution','SULFACETAMIDE SODIUM 100 mg/mL','Topique','Bantry Pharma, LLC','INT','Sulfonamide Antibacterial','SULFACETAMIDE SODIUM, SULFUR'),
('FOASU Pink Y s MOISTURIZING MIST','niacinamide, adenosine','LIQUID','ADENOSINE .04 g/100mL','Topique','HANSCOS Co.,Ltd.','INT','Adenosine Receptor Agonist','FOASU Pink Y s MOISTURIZING MIST'),
('JuniperCleanDishSoap Juniper','dishwashing detergent juniper forest','LIQUID','CHLOROXYLENOL .2 g/100g','CUTANEOUS','KYNC DESIGN LLC','INT',NULL,'JuniperCleanDishSoap Juniper'),
('Doxylamine succinate and pyridoxine hydrochloride','doxylamine succinate and pyridoxine hydrochloride','Comprimé','DOXYLAMINE SUCCINATE 10 mg/1','Orale','Actavis Pharma, Inc.','US','Antihistamine','Doxylamine succinate and pyridoxine hydrochloride'),
('URICOZEN','gout recovery, joint pain and inflammation relief, and gout crystal dissolution','Gélule','LONICERA JAPONICA FLOWER 1 [hp_X]/1','Orale','HCBIOPHARM','INT',NULL,'URICOZEN'),
('KOVR Military grade sunscreen for Men','zinc oxide','Lotion','ZINC OXIDE 14.6 g/100g','Topique','ACTIVE LIFE INC','INT','Copper Absorption Inhibitor','KOVR Military grade sunscreen for Men'),
('DERLADIE WITCH HAZEL PERFECT VITAMIN GELCREAM','niacinamide, adenosine','Crème','ADENOSINE .04 g/100mL','Topique','LAON COMMERCE co ltd','INT','Adenosine Receptor Agonist','DERLADIE WITCH HAZEL PERFECT VITAMIN GELCREAM'),
('St Moriz suncare body sunscreen spf50','suncare body sunscreen spf50','Lotion','AVOBENZONE 5.4 mg/180mL','Topique','Aopline Health Industry Technology (Guangzhou) Co., Ltd.','INT','Médicaments topiques','St Moriz suncare body sunscreen spf50'),
('natural lip balm SPF15( Passion Fruit) 01','avobenzone,homosalate,octocrylene,octisalate','LIPSTICK','AVOBENZONE 2 g/100g','Topique','Cosmuses Cosmetics (Ningbo) Co., Ltd.','INT','Médicaments topiques','natural lip balm SPF15( Passion Fruit) 01'),
('Bestmade Natural Products BM140','berb vulg, calc phos, causticum, dulcamara, nux vomica, rhus tox','LIQUID','BERBERIS VULGARIS ROOT BARK 30 [hp_C]/30[hp_C]','Orale','Bestmade Natural Products','INT','Blood Coagulation Factor','Bestmade Natural Products BM140'),
('Bestmade Natural Products Wyethia He','wyethia helenioides','Comprimé','WYETHIA HELENIOIDES ROOT 30 [hp_C]/30[hp_C]','Orale','Bestmade Natural Products','INT',NULL,'Bestmade Natural Products Wyethia He'),
('SERYNTH ECZEMA RELIEF','hydrocortisone 1% eczema relief','Crème','HYDROCORTISONE 1 g/100g','Topique','Jiangxi Yudexi Pharmaceutical Co., LTD','INT','Corticosteroid','SERYNTH ECZEMA RELIEF'),
('Sheer Mineral Sunscreen','titanium dioxide, zinc oxide','Crème','TITANIUM DIOXIDE 80 mg/g','Topique','The Maui Medical Group, Inc','INT','Médicaments topiques','Sheer Mineral Sunscreen'),
('RestoraScalp Anti Dandruff Dry Dark Roots','anti dandruff dry shampoo','Poudre','SALICYLIC ACID 2 g/100g','Topique','Raven Innovations LLC','INT','Médicaments topiques','RestoraScalp Anti Dandruff Dry Dark Roots'),
('Native Mineral Suncare Daily Face Broad Spectrum SPF 30 Unscented','zinc oxide','Lotion','ZINC OXIDE 20 g/100mL','Topique','The Procter & Gamble Manufacturing Company','INT','Médicaments topiques','Native Mineral Suncare Daily Face Broad Spectrum SPF 30 Unscented'),
('Vecamyl','mecamylamine hydrochloride','Comprimé','MECAMYLAMINE HYDROCHLORIDE 2.5 mg/1','Orale','TILDE Sciences LLC','US','Autonomic Ganglionic Blocker','Vecamyl'),
('Glow This Way','octisalate, octocrylene, zinc oxide, avobenzone, homosalate','Kit',NULL,'Topique','Koco Life LLC','INT','Médicaments topiques','Glow This Way'),
('Wart Remover Ointmen t','salicylic acid, chlorhexidine','Pommade','CHLORHEXIDINE 1 g/100g','Topique','Dongkou County Hecheng Network Technology Co., Ltd.','INT','Decreased Cell Wall Integrity','Wart Remover Ointmen t'),
('Bitchstix Pink Lemon SPF 30 Sunscreen Lip Balm SPF 30','avobenzone, octinoxate, octisalate, oxybenzone','STICK','AVOBENZONE 3 g/100g','Topique','Bitchstix, LLC','INT','Médicaments topiques','Bitchstix Pink Lemon SPF 30 Sunscreen Lip Balm SPF 30'),
('Gold Bond Medicated Maximum Strength Foot','menthol','Poudre','MENTHOL 1 g/100g','Topique','Gold Bond Co LLC','INT','Médicaments topiques','Gold Bond Medicated Maximum Strength Foot'),
('Herb Analgesic','herb analgesic paste','PASTE','ANGELICA SEED 2 g/100g','Topique','Changsha Maocheng Trading Co., Ltd','INT','Médicaments topiques','Herb Analgesic'),
('JAYSUING Hyaluronic Acid Moisturizing Sunscreen','titanium dioxide','LIQUID','CENTELLA ASIATICA LEAF .006 mg/30mg','Topique','Shantou Jaysuing Cleaning and Environmental Protection Technology Co., Ltd.','INT','Médicaments topiques','JAYSUING Hyaluronic Acid Moisturizing Sunscreen'),
('Sugargirl Hot Body Screen Shimmer Sunscreen SPF 30','homosalate, octocrylene, octinoxate, avobenzone, octisalate','Lotion','AVOBENZONE 30 mg/mL','Topique','I World LLC','INT','Médicaments topiques','Sugargirl Hot Body Screen Shimmer Sunscreen SPF 30')
) AS v(nom, dci, forme, dosage, voie, labo, pays, classe, nomcom)
WHERE NOT EXISTS (
  SELECT 1 FROM medicaments m WHERE UPPER(m.nom) = UPPER(v.nom)
);
