-- ndc_batch_038.sql (80 rows)
INSERT INTO medicaments (nom, dci, forme, dosage, voie_administration, laboratoire, pays, classe_therapeutique, nom_commercial)
SELECT v.nom, v.dci, v.forme, v.dosage, v.voie, v.labo, v.pays, v.classe, v.nomcom
FROM (VALUES
('Male Balance','avena sativa, hepar suis, orchitinum (suis), testosterone, agnus castus, damiana, ginkgo biloba, hypothalamus (suis), lycopodium clabatum, human growth hormone, epimedium grandiflorum, serotonin (hydrochloride)','LIQUID','AVENA SATIVA FLOWERING TOP 6 [hp_X]/mL','Orale','Energique,Inc.','INT','Androgen','Male Balance'),
('Zovirax','acyclovir','Pommade','ACYCLOVIR 50 mg/g','Topique','Bausch Health US, LLC','US','Herpes Simplex Virus Nucleoside Analog DNA Polymerase Inhibitor','Zovirax'),
('ANCOBON','flucytosine','Gélule','FLUCYTOSINE 250 mg/1','Orale','Bausch Health US LLC','US','Nucleoside Analog Antifungal','ANCOBON'),
('Targretin','bexarotene','Gélule','BEXAROTENE 75 mg/1','Orale','Bausch Health US, LLC','US','Retinoid','Targretin'),
('Medi-First Plus Extra Strength Non-Aspirin','acetaminophen','Comprimé','ACETAMINOPHEN 500 mg/1','Orale','Unifirst First Aid Corporation','INT',NULL,'Medi-First Plus Extra Strength Non-Aspirin'),
('Hypericum 3X','hypericum 3x','LIQUID','ST. JOHN''S WORT 3 [hp_X]/mL','Orale','Uriel Pharmacy, Inc','INT',NULL,'Hypericum 3X'),
('Chocolate Laxative Regular strength, Sennosides Stimulant Laxative, equate','sennosides','Comprimé','SENNOSIDES 15 mg/1','Orale','Wal-Mart Stores Inc','INT',NULL,'Chocolate Laxative Regular strength, Sennosides Stimulant Laxative, equate'),
('equate childrens pain and fever','acetaminophen','Suspension','ACETAMINOPHEN 160 mg/5mL','Orale','Wal-Mart Stores Inc','INT',NULL,'equate childrens pain and fever'),
('TNKase','tenecteplase','Kit',NULL,NULL,'Genentech, Inc.','US',NULL,'TNKase'),
('Cimifuga racemosa','black cohosh','PELLET','BLACK COHOSH 9 [hp_C]/9[hp_C]','Orale','Boiron','INT',NULL,'Cimifuga racemosa'),
('Camphora','camphor (natural)','PELLET','CAMPHOR (NATURAL) 200 [kp_C]/200[kp_C]','Orale','Boiron','INT',NULL,'Camphora'),
('Zyvox','linezolid','Solution','LINEZOLID 600 mg/300mL','Intraveineuse','Pharmacia & Upjohn Company LLC','US','Oxazolidinone Antibacterial','Zyvox'),
('Causticum','causticum','PELLET','CAUSTICUM 5 [hp_C]/5[hp_C]','Orale','Boiron','INT',NULL,'Causticum'),
('Bromo Seltzer','aspirin, sodium bicarbonate, citric acid','Comprimé','ANHYDROUS CITRIC ACID 1000 mg/1','Orale','Tower Laboratories Ltd','INT','Anti-coagulant','Bromo Seltzer'),
('NATURAL Epsom Salt','magnesium sulfate','GRANULE','MAGNESIUM SULFATE, UNSPECIFIED FORM 100 g/100g','Orale','Universal Distribution Center LLC','INT','Calculi Dissolution Agent','NATURAL Epsom Salt'),
('Novita Petrolatum Jelly Pink','petrolatum','JELLY','PETROLATUM 99.9 g/100g','Topique','Shield Line LLC','INT','Médicaments topiques','Novita Petrolatum Jelly Pink'),
('Sinus Severe','acetaminophen, guaifenesin, and phenylephrine hydrochloride','Comprimé','ACETAMINOPHEN 325 mg/1','Orale','GoodSense','INT','Expectorant','Sinus Severe'),
('COLTALIN','acetaminophen, chlorpheniramine maleate, phenylephrine hydrochloride','Comprimé','ACETAMINOPHEN 325 mg/1','Orale','FORTUNE PHARMACAL COMPANY LIMITED','INT','Histamine-1 Receptor Antagonist','COLTALIN'),
('Acetaminophen and Ibuprofen','acetaminophen and ibuprofen','Comprimé','ACETAMINOPHEN 250 mg/1','Orale','CVS','US','Nonsteroidal Anti-inflammatory Drug','Acetaminophen and Ibuprofen'),
('CVS Nighttime Childrens Cold and Cough Multi-Symptom Relief','chlorpheniramine maleate and dextromethorphan hydrobromide','Solution','CHLORPHENIRAMINE MALEATE 2 mg/15mL','Orale','CVS PHARMACY','INT','Histamine-1 Receptor Antagonist','CVS Nighttime Childrens Cold and Cough Multi-Symptom Relief'),
('Sodium Polystyrene Sulfonate','sodium polystyrene sulfonate','Suspension','SODIUM POLYSTYRENE SULFONATE 15 g/60mL','Orale','Cardinal Health 107, LLC','US',NULL,'Sodium Polystyrene Sulfonate'),
('exchange select Ultra Strength Antacid Assorted Fruit','calcium carbonate','Comprimé','CALCIUM CARBONATE 1000 mg/1','Orale','ARMY AND AIR FORCE EXCHANGE SERVICE','INT',NULL,'exchange select Ultra Strength Antacid Assorted Fruit'),
('FAMILY WELLNESS DRY SCALP 2 IN 1 DANDRUFF PLUS CONDITIONER Anti-Dandruff','pyrithione zinc','SHAMPOO','PYRITHIONE ZINC 10 mg/mL','Topique','FAMILY DOLLAR SERVICES INC','INT','Médicaments topiques','FAMILY WELLNESS DRY SCALP 2 IN 1 DANDRUFF PLUS CONDITIONER Anti-Dandruff'),
('Evenity','romosozumab-aqqg','Solution','ROMOSOZUMAB 105 mg/1.17mL','Sous-cutanée','Amgen, Inc','US',NULL,'Evenity'),
('Kali muriaticum','potassium chloride','PELLET','POTASSIUM CHLORIDE 6 [hp_C]/6[hp_C]','Orale','Boiron','INT','Osmotic Laxative','Kali muriaticum'),
('Kali sulphuricum','potassium sulfate','PELLET','POTASSIUM SULFATE 200 [kp_C]/200[kp_C]','Orale','Boiron','INT','Osmotic Laxative','Kali sulphuricum'),
('Dermatone Sport SPF 50','avobenzone 3%, homosalate 10%, octocrylene 6%','Lotion','AVOBENZONE 3 g/100mL','Topique','Dermatone Labs LLC','INT','Médicaments topiques','Dermatone Sport SPF 50'),
('DISCOUNT DRUG MART','cough drops honey lemon','Pastille','MENTHOL 7.5 mg/1','Orale','DISCOUNT DRUG MART','INT',NULL,'DISCOUNT DRUG MART'),
('Performance Face Sunscreen Broad Spectrum SPF 30','zinc oxide, octocrylene, octisalate','Crème','OCTISALATE 2 g/100mL','Topique','Bentley Laboratories, LLC','INT','Copper Absorption Inhibitor','Performance Face Sunscreen Broad Spectrum SPF 30'),
('Tusnel Cough Suppressant Expectorant','dextromethorphan hbr, guaifenesin','LIQUID','DEXTROMETHORPHAN HYDROBROMIDE 10 mg/5mL','Orale','Llorens Pharmaceutical International Division, Inc.','INT','Expectorant','Tusnel Cough Suppressant Expectorant'),
('CALC FLUOR 6X','calcium fluoride','Comprimé','CALCIUM FLUORIDE 6 [hp_X]/1','Orale','Hyland''s Inc.','INT',NULL,'CALC FLUOR 6X'),
('Sirolimus','sirolimus','Comprimé','SIROLIMUS 1 mg/1','Orale','Dr. Reddy''s Laboratories Limited','US','Kinase Inhibitor','Sirolimus'),
('Stramonium','datura stramonium','PELLET','DATURA STRAMONIUM 6 [hp_C]/1','Orale','Boiron','INT',NULL,'Stramonium'),
('PHENAGIL','chlorpheniramine maleate, dextromethorphan hbr and phenylephrine hcl','Comprimé','CHLORPHENIRAMINE MALEATE 3.5 mg/1','Orale','Gil Pharmaceutical Corp.','INT','Histamine-1 Receptor Antagonist','PHENAGIL'),
('Uro-MP','methenamine, sodium phosphate, monobasic, anhydrous, phenyl salicylate, methylene blue and hyoscyamine sulfate','Gélule','HYOSCYAMINE SULFATE .12 mg/1','Orale','Method Pharmaceuticals, LLC','INT','Osmotic Laxative','Uro-MP'),
('Stratuscare Glycerin Laxative Pediatric','glycerin','Suppositoire','GLYCERIN 1 g/1','Rectale','Stratus Pharmaceuticals','INT','Non-Standardized Chemical Allergen','Stratuscare Glycerin Laxative Pediatric'),
('Dimopair','dimethicone','Crème','DIMETHICONE 50 mg/mL','Topique','PureTek Corporation','INT','Skin Barrier Activity','Dimopair'),
('Edema','elaps corallinus, apis mel., arsenicum alb., cantharis, cinchona, colchicum, convallaria, crotalus horridus, digitalis, juniperus com., lachesis, merc. viv., naja, nat. carb., nat.sulphuricum, rhus toxicodendron, sambucus nig., strophanthus hispidus, thuja occ., vipera berus, echinacea, lappa, solidago, taraxacum, urtica ur.','LIQUID','APIS MELLIFERA 20 [hp_X]/mL','Orale','Newton Laboratories, Inc.','INT','Non-Standardized Food Allergenic Extract','Edema'),
('dg health omeprazole','omeprazole','Comprimé','OMEPRAZOLE 20 mg/1','Orale','Dolgencorp Inc','US','Proton Pump Inhibitor','dg health omeprazole'),
('Mineral Oil','mineral oil','LIQUID','MINERAL OIL 999 mg/mL','Orale','Old East Main Co.','INT',NULL,'Mineral Oil'),
('SPA HAND SANITIZER SUMMER LEMON','ethyl alcohol','Gel','ALCOHOL 70 mL/100mL','Topique','Rejoice International Corp.','INT','Médicaments topiques','SPA HAND SANITIZER SUMMER LEMON'),
('profen IB childrens','ibuprofen','Suspension','IBUPROFEN 100 mg/5mL','Orale','Publix Super Markets Inc','US','Nonsteroidal Anti-inflammatory Drug','profen IB childrens'),
('Bisacodyl','bisacodyl','Suppositoire','BISACODYL 10 mg/1','Rectale','GERI-CARE PHARMACEUTICAL CORP','INT','Stimulant Laxative','Bisacodyl'),
('Sepia','sepia officinalis juice','PELLET','SEPIA OFFICINALIS JUICE 6 [hp_C]/6[hp_C]','Orale','Boiron','INT',NULL,'Sepia'),
('SINAPIS NIGRA','black mustard seed','PELLET','BLACK MUSTARD SEED 200 [kp_C]/200[kp_C]','Orale','Boiron','INT',NULL,'SINAPIS NIGRA'),
('ZOMIG','zolmitriptan','Comprimé','ZOLMITRIPTAN 2.5 mg/1','Orale','Amneal Pharmaceuticals LLC','US','Serotonin-1b and Serotonin-1d Receptor Agonist','ZOMIG'),
('H-Athletes Foot Formula','calendula officinalis, lycopodium clavatum, thuja occidentalis','OIL','CALENDULA OFFICINALIS FLOWERING TOP 12 [hp_C]/11mL','Topique','Healing Natural Oils LLC','INT','Médicaments topiques','H-Athletes Foot Formula'),
('Oralair 100 IR','anthoxanthum odoratum pollen, dactylis glomerata pollen, lolium perenne pollen, phleum pratense pollen, and poa pratensis pollen','Comprimé','ANTHOXANTHUM ODORATUM POLLEN 100 [IR]/1','Sublinguale','Stallergenes','US','Standardized Pollen Allergenic Extract','Oralair 100 IR'),
('CVS Antifungal Ringworm','clotrimazole','Crème','CLOTRIMAZOLE 1 g/100g','Topique','CVS Pharmacy','INT','Azole Antifungal','CVS Antifungal Ringworm'),
('EMJ ANTIPERSPIRANT MOUNTAIN AIR 2.6 OZ (73 g)','aluminum zirconium trichlorohydrex gly 20%','STICK','ALUMINUM ZIRCONIUM TRICHLOROHYDREX GLY .2 g/g','Topique','RNA PHARMA LLC','INT','Médicaments topiques','EMJ ANTIPERSPIRANT MOUNTAIN AIR 2.6 OZ (73 g)'),
('SheerZinc SPF 30 Tinted - Tan','zinc oxide','Crème','ZINC OXIDE 186 mg/g','Topique','Allure Labs Inc','INT','Copper Absorption Inhibitor','SheerZinc SPF 30 Tinted - Tan'),
('Anti-Hives Drops 2004','anti-hives drops','LIQUID','APIS MELLIFERA 6 [hp_X]/59mL','Orale','Professional Complementary Health Formulas','INT','Calculi Dissolution Agent','Anti-Hives Drops 2004'),
('Adrenal Drops 5001','adrenal drops','LIQUID','ATROPINE SULFATE 6 [hp_X]/59mL','Orale','Professional Complementary Health Formulas','INT','Anticholinergic','Adrenal Drops 5001'),
('NU-DERM HEALTHY SKIN PROTECTION SPF 35','octinoxate and zinc oxide','Crème','OCTINOXATE 75 mg/mL','Topique','Obagi Cosmeceuticals LLC','INT','Médicaments topiques','NU-DERM HEALTHY SKIN PROTECTION SPF 35'),
('Water','aconitum nap, arsenicum alb, borax, calc phos, gelsenium, lycopodium, phosphoricum ac, picricum ac, plumb met, solidago','LIQUID','ACONITUM NAPELLUS 12 [hp_X]/59mL','Orale','NET Remedies','INT','Blood Coagulation Factor','Water'),
('Xeomin','incobotulinumtoxina','Solution','BOTULINUM TOXIN TYPE A 200 [USP''U]/1','Intramusculaire','Merz Pharmaceuticals, LLC','US','Acetylcholine Release Inhibitor','Xeomin'),
('Cefoxitin and Dextrose','cefoxitin sodium','Solution','CEFOXITIN SODIUM 1 g/50mL','Intraveineuse','B. Braun Medical Inc.','US','Cephalosporin Antibacterial','Cefoxitin and Dextrose'),
('Candesartan cilexetil','candesartan cilexetil','Comprimé','CANDESARTAN CILEXETIL 4 mg/1','Orale','ANI Pharmaceuticals, Inc.','US','Angiotensin 2 Receptor Blocker','Candesartan cilexetil'),
('Anti-BacterialHandSpray White T Shirt','alcohol','Spray','ALCOHOL 72 mL/100mL','Topique','Bath & Body Works, Inc.','INT','Médicaments topiques','Anti-BacterialHandSpray White T Shirt'),
('Organic Acid Combination 9305','organic acid combination','LIQUID','ADIPIC ACID 12 [hp_X]/29.5mL','Orale','Professional Complementary Health Formulas','INT','Non-Standardized Plant Allergenic Extract','Organic Acid Combination 9305'),
('G11 PINEAL-MET','adenosine triphosphate, ammonium chloride, gold, saffron, ferrosoferric phosphate, pulsatilla vulgaris whole','Solution','ADENOSINE TRIPHOSPHATE 5 [hp_X]/mL','Sublinguale','Apex Energetics Inc.','INT','Standardized Chemical Allergen','G11 PINEAL-MET'),
('Armadillidium Vulgare','armadillidium vulgare','PELLET','ARMADILLIDIUM VULGARE WHOLE 6 [hp_C]/1','Orale','Hahnemann Laboratories, Inc.','INT',NULL,'Armadillidium Vulgare'),
('IOMERVU','iomeprol injection','Solution','IOMEPROL 816 mg/mL','INTRA-ARTERIAL','BRACCO DIAGNOSTICS INC','US','Radiographic Contrast Agent','IOMERVU'),
('TYENNE','tocilizumab-aazg','Solution','TOCILIZUMAB 162 mg/.9mL','Sous-cutanée','Fresenius Kabi USA, LLC','US','Interleukin-6 Receptor Antagonist','TYENNE'),
('Broad Spectrum SPF 15 Sunscreen Iced Pear Lip Balm','broad spectrum spf 15 sunscreen iced pear lip balm','STICK','AVOBENZONE .13 g/4.25g','Topique','Raining Rose','INT','Médicaments topiques','Broad Spectrum SPF 15 Sunscreen Iced Pear Lip Balm'),
('Saniclean','benzalkonium chloride','SOAP','BENZALKONIUM CHLORIDE .13 g/100mL','Topique','Simoniz Saniclean, LLC','INT','Médicaments topiques','Saniclean'),
('Best Choice Eye Drops Advanced Relief','dextran 70, polyethylene glycol 400, povidone, tetrahydrozoline hydrochloride','Solution','DEXTRAN 70 .1 g/100mL','Ophtalmique','Valu Merchandisers, Co.','INT','Plasma Volume Expander','Best Choice Eye Drops Advanced Relief'),
('DUAL ACTION GLACIER MINT COUGH SUPPRESSANT ORAL ANESTHETIC','menthol','Pastille','MENTHOL 8.3 mg/1','Orale','Ricola USA Inc.','INT',NULL,'DUAL ACTION GLACIER MINT COUGH SUPPRESSANT ORAL ANESTHETIC'),
('Slenderiix','weight management formula','LIQUID','AMMONIUM BROMIDE 12 [hp_X]/mL','Orale','Vitality Works','INT','Non-Standardized Plant Allergenic Extract','Slenderiix'),
('Degree 5 In 1 Clinical Protection Antiperspirant and Deodorant','aluminum zirconium tetrachlorohydrex gly','STICK','ALUMINUM ZIRCONIUM TETRACHLOROHYDREX GLY 20 g/100g','Topique','Conopco Inc. d/b/a Unilever','INT','Médicaments topiques','Degree 5 In 1 Clinical Protection Antiperspirant and Deodorant'),
('Animal Allergens, UF Dog Hair-Dander Canis spp','animal allergens, dog dander canis spp','Solution','CANIS LUPUS FAMILIARIS DANDER .0008 g/mL','PERCUTANEOUS','Jubilant HollisterStier LLC','US','Non-Standardized Animal Dander Allergenic Extract','Animal Allergens, UF Dog Hair-Dander Canis spp'),
('Cardura','doxazosin','Comprimé','DOXAZOSIN MESYLATE 8 mg/1','Orale','ROERIG','US','alpha-Adrenergic Blocker','Cardura'),
('Dopamine Hydrochloride and Dextrose','dopamine hydrochloride','Solution','DOPAMINE HYDROCHLORIDE 80 mg/100mL','Intraveineuse','Baxter Healthcare Corporation','US','Catecholamine','Dopamine Hydrochloride and Dextrose'),
('ZzzQuil ULTRA, Travel BASIX','doxylamine succinate','Comprimé','DOXYLAMINE SUCCINATE 25 mg/1','Orale','Lil'' Drug Store Products, Inc.','INT','Antihistamine','ZzzQuil ULTRA, Travel BASIX'),
('TIGER Balm PAIN RELIEVING HYDROGEL','camphor (synthetic), levomenthol, and capsicum','Patch transdermique','CAMPHOR (SYNTHETIC) 160 mg/1','Topique','Haw Par Healthcare Ltd.','INT','Non-Standardized Food Allergenic Extract','TIGER Balm PAIN RELIEVING HYDROGEL'),
('WinCo Original Strength Triple Antibiotic','bacitracin zinc, neomycin sulfate, and polymyxin b sulfate','Pommade','BACITRACIN ZINC 400 [iU]/g','Topique','WinCo Foods, LLC','INT','Aminoglycoside Antibacterial','WinCo Original Strength Triple Antibiotic'),
('AGE20S SIGNATURE ESSENCE PACT INTENSE COVER 35N','octinoxate, octocrylene, titanium dioxide','Crème','OCTINOXATE .91 g/14g','Topique','Aekyung Industrial Co., Ltd.','INT','Médicaments topiques','AGE20S SIGNATURE ESSENCE PACT INTENSE COVER 35N'),
('Dr Lift Mineral SPF 50','titanium dioxide, zinc oxide','Spray','TITANIUM DIOXIDE 72 mg/100mL','Topique','Spa de Soleil','INT','Médicaments topiques','Dr Lift Mineral SPF 50'),
('Clearing Skin Wash','salicylic acid','LIQUID','SALICYLIC ACID .501 mg/100mL','Topique','Dermalogica, LLC.','INT','Médicaments topiques','Clearing Skin Wash'),
('Stomach Saver','abies nig, antimon crud, arg nit, arsenicum alb, carbo veg, cinchona, lycopodium, nat phos, nux mosch, nux vom, podoph pelt, robinia','Comprimé','ACTIVATED CHARCOAL 6 [hp_C]/1','Orale','Silver Star Brands','INT','Non-Standardized Food Allergenic Extract','Stomach Saver')
) AS v(nom, dci, forme, dosage, voie, labo, pays, classe, nomcom)
WHERE NOT EXISTS (
  SELECT 1 FROM medicaments m WHERE UPPER(m.nom) = UPPER(v.nom)
);
