-- ndc_batch_120.sql (80 rows)
INSERT INTO medicaments (nom, dci, forme, dosage, voie_administration, laboratoire, pays, classe_therapeutique, nom_commercial)
SELECT v.nom, v.dci, v.forme, v.dosage, v.voie, v.labo, v.pays, v.classe, v.nomcom
FROM (VALUES
('Piasky','crovalimab','Solution','CROVALIMAB 340 mg/2mL','Sous-cutanée','Genentech, Inc.','US','Complement C5 Inhibitor','Piasky'),
('SYMBICORT','budesonide and formoterol fumarate dihydrate','AEROSOL','BUDESONIDE 160 ug/1','Inhalation','A-S Medication Solutions','US','Corticosteroid','SYMBICORT'),
('Sambucol Cold and Flu Relief','bryonia, gelsemium sempervirens, sabucus nigra, sulphur, zincum gluconicum','Comprimé','BRYONIA ALBA ROOT 6 [hp_X]/mg','Orale','PharmaCare US, Inc.','INT','Copper Absorption Inhibitor','Sambucol Cold and Flu Relief'),
('AmeriDerm PeriShield','zinc oxide','Pommade','ZINC OXIDE 3.8 g/100g','Topique','Shield Line LLC','INT','Médicaments topiques','AmeriDerm PeriShield'),
('Burts Bees SPF 30 Untinted Lip Balm Tropic Like Its Hot','burts bees spf 30 untinted lip balm tropic like its hot','STICK','ZINC OXIDE 11.99 g/100g','Topique','Autumn Harp','INT','Médicaments topiques','Burts Bees SPF 30 Untinted Lip Balm Tropic Like Its Hot'),
('allergy nasal','fluticasone propionate','Spray','FLUTICASONE PROPIONATE 50 ug/1','Nasale','CVS WOONSOCKET PRESCRIPTION CENTER, INCORPORATED','US','Corticosteroid','allergy nasal'),
('CVS Health Stomach Relief SOFTGEL','bismuth subsalicylate','Gélule','BISMUTH SUBSALICYLATE 262 mg/1','Orale','CVS Pharmacy, Inc.','INT',NULL,'CVS Health Stomach Relief SOFTGEL'),
('INFANT 4.2% SODIUM BICARBONATE','infant 4.2% sodium bicarbonate','Solution','SODIUM BICARBONATE 42 mg/mL','Intraveineuse','HF Acquisition Co LLC, DBA HealthFirst','INT','Alkalinizing Activity','INFANT 4.2% SODIUM BICARBONATE'),
('NALOXONE HCl','naloxone hcl','Spray','NALOXONE HYDROCHLORIDE 4 mg/.1mL','Nasale','HF Acquisition Co LLC, DBA HealthFirst','US','Opioid Antagonist','NALOXONE HCl'),
('Family Wellness Ear Relief Ear Drops','matricaria chamomilla, mercurius solubilis, sulfur','Solution','MATRICARIA CHAMOMILLA 10 [hp_X]/mL','AURICULAR (OTIC)','Family Dollar Services Inc','INT',NULL,'Family Wellness Ear Relief Ear Drops'),
('North Woods Derma Gel Clear','alcohol','Gel','ALCOHOL .7 mL/mL','Topique','Superior Chemical Corporation','INT','Médicaments topiques','North Woods Derma Gel Clear'),
('Sun Logic Lait Solaire Corps SPF 20','avobenzone, homosalate, octocrylene','Lotion','AVOBENZONE 29 mg/mL','Topique','Guinot','INT','Médicaments topiques','Sun Logic Lait Solaire Corps SPF 20'),
('Mephitis mephitica','mephitis mephitis anal gland fluid','PELLET','MEPHITIS MEPHITIS ANAL GLAND FLUID 6 [hp_C]/6[hp_C]','Orale','Boiron','INT',NULL,'Mephitis mephitica'),
('SHISEIDO REVITALESSENCE SKIN GLOW FOUNDATION 430','octinoxate','EMULSION','OCTINOXATE 2.30805 g/30mL','Topique','SHISEIDO AMERICAS CORPORATION','INT','Médicaments topiques','SHISEIDO REVITALESSENCE SKIN GLOW FOUNDATION 430'),
('Finafta MultiOral','benzocaine','Spray','BENZOCAINE 7.5 mg/100mL','Orale','Efficient Laboratories Inc.','INT','Standardized Chemical Allergen','Finafta MultiOral'),
('ZALTRAP','ziv-aflibercept','Solution','AFLIBERCEPT 100 mg/4mL','Intraveineuse','sanofi-aventis U.S. LLC','US','Vascular Endothelial Growth Factor Inhibitor','ZALTRAP'),
('Post - Vaccination','influenzinum, morbillinum, pertussinum, aconitum nap., alumina, antimon. tart., arsenicum alb., baptisia, belladonna, bryonia, cinchona, crotalus horridus, gelsemium, kali bic., lachesis, ledum, merc. viv., mezereum, nux vom., phosphorus, pulsatilla, rhus toxicodendron, silicea, sulphur, thuja occ., vaccinium, apis mel., echinacea, hypericum','LIQUID','ACONITUM NAPELLUS 15 [hp_X]/mL','Orale','Newton Laboratories, Inc.','INT','Non-Standardized Plant Allergenic Extract','Post - Vaccination'),
('Allergy Childrens Allergy','diphenhydramine hydrochloride','LIQUID','DIPHENHYDRAMINE HYDROCHLORIDE 12.5 mg/5mL','Orale','Dolgencorp, Inc. (DOLLAR GENERAL & REXALL)','INT','Histamine-1 Receptor Antagonist','Allergy Childrens Allergy'),
('Allergy Multi Symptom','acetaminophen, chlorpheniramine maleate, and phenylephrine hydrochloride','Comprimé','ACETAMINOPHEN 325 mg/1','Orale','AAA PHARMACEUTICAL, INC.','INT','Histamine-1 Receptor Antagonist','Allergy Multi Symptom'),
('Premier Solutions Liquid Bandage','benzethonium chloride dyclonine hydrochloride','LIQUID','BENZETHONIUM CHLORIDE .2 mg/10mL','Topique','Premier Brands of America, Inc.','INT','Médicaments topiques','Premier Solutions Liquid Bandage'),
('Coolexa','camphor, menthol, methyl salicylate','Crème','CAMPHOR (SYNTHETIC) 40 mg/g','Topique','Rising Pharma Holdings, Inc.','INT','Médicaments topiques','Coolexa'),
('Bach Original Flower Remedies Chicory','cichorium intybus','Solution','CICHORIUM INTYBUS FLOWER 5 [hp_X]/.095mL','Orale','Nelson Bach USA Limited','INT',NULL,'Bach Original Flower Remedies Chicory'),
('Geri-Dryl allergy relief','diphenhydramine hcl','Comprimé','DIPHENHYDRAMINE HYDROCHLORIDE 25 mg/1','Orale','Geri-Care Pharmaceutical Corp','INT','Histamine-1 Receptor Antagonist','Geri-Dryl allergy relief'),
('FLUARIX 2025/2026','influenza virus vaccine','Suspension','INFLUENZA A VIRUS A/THAILAND/8/2022 IVR-237 (H3N2) ANTIGEN (FORMALDEHYDE INACTIVATED) 15 ug/.5mL','Intramusculaire','GlaxoSmithKline Biologicals SA','US',NULL,'FLUARIX 2025/2026'),
('T-7','aesculus hippocastanum whole','Solution','AESCULUS HIPPOCASTANUM WHOLE 30 [hp_X]/mL','Sublinguale','DNA Labs, Inc.','INT',NULL,'T-7'),
('SHISEIDO UV PROTECTIVE COMPACT (REFILL) FAIR IVORY','octinoxate, octocrylene, and titanium dioxide','Poudre','OCTINOXATE 888 mg/12g','Topique','SHISEIDO AMERICAS CORPORATION','INT','Médicaments topiques','SHISEIDO UV PROTECTIVE COMPACT (REFILL) FAIR IVORY'),
('Hair and Nail Tonic','avena, dna, elaeis, glandula suprarenalis suis, hamamelis, hepar suis, kali sulph, nat mur, nicotinamidum, phosphoricum ac, pituitarum posterium, riboflavinum, thiaminum hydrochloricum, thuja occ, thyroidinum, urtica ur.','LIQUID','AVENA SATIVA FLOWERING TOP 4 [hp_X]/41mL','Orale','Eight and Company L.L.C','INT','Osmotic Laxative','Hair and Nail Tonic'),
('Alyglo','human immunoglobulin g','LIQUID','HUMAN IMMUNOGLOBULIN G 100 mg/mL','Intraveineuse','GC Biopharma Corp.','US','Human Immunoglobulin G','Alyglo'),
('EDURANT PED','rilpivirine hydrochloride','Comprimé','RILPIVIRINE HYDROCHLORIDE 2.5 mg/1','Orale','Janssen Products, LP','US','Human Immunodeficiency Virus 1 Non-Nucleoside Analog Reverse Transcriptase Inhib','EDURANT PED'),
('CBD Pain Relief Cream','trolamine salicylate','Crème','TROLAMINE SALICYLATE 100 mg/g','Topique','Allure Labs','INT','Médicaments topiques','CBD Pain Relief Cream'),
('Sunright Lip Balm','octinoxate, avobenzone, and octocrylene','STICK','AVOBENZONE 30 mg/g','Topique','NSE Products, Inc.','INT','Médicaments topiques','Sunright Lip Balm'),
('Glucose Drops 2031','glucose drops','LIQUID','BOS TAURUS PANCREAS 6 [hp_X]/59mL','Orale','Professional Complementary Health Formulas','INT','Paramagnetic Contrast Agent','Glucose Drops 2031'),
('Tonsil/Adenoid/Appendix Drops 5030','tonsil/adenoid/appendix drops','LIQUID','BERBERIS AQUIFOLIUM ROOT BARK 3 [hp_X]/59mL','Orale','Professional Complementary Health Formulas','INT',NULL,'Tonsil/Adenoid/Appendix Drops 5030'),
('Obagi Nu-Derm System Normal-Dry Skin Transformation Kit','hydroquinone, homosalate, octisalate, zinc oxide','Kit',NULL,NULL,'Obagi Cosmeceuticals LLC','INT',NULL,'Obagi Nu-Derm System Normal-Dry Skin Transformation Kit'),
('ATTITUDE Sunly Tinted Mineral Sunscreen Face Stick Unscented SPF 30','zinc oxide','STICK','ZINC OXIDE 20 g/100g','Topique','9055-7588 Quebec Inc. DBA Attitude','INT','Médicaments topiques','ATTITUDE Sunly Tinted Mineral Sunscreen Face Stick Unscented SPF 30'),
('Dior Forever Skin Wear Flawless Skin True Foundation SPF 20 3C Cool','octisalate, titanium dioxide','EMULSION','OCTISALATE 35 mg/mL','Topique','Parfums Christian Dior','INT','Médicaments topiques','Dior Forever Skin Wear Flawless Skin True Foundation SPF 20 3C Cool'),
('Chlorhexidine Gluconate 0.12% Oral Rinse','chlorhexidine gluconate 0.12% oral rinse','Solution','CHLORHEXIDINE GLUCONATE 1.2 mg/mL','Orale','Chartwell RX, LLC','US','Decreased Cell Wall Integrity','Chlorhexidine Gluconate 0.12% Oral Rinse'),
('CENTER-AL - QUERCUS ALBA POLLEN','quercus alba pollen','Suspension','QUERCUS ALBA POLLEN 10000 [PNU]/mL','Sous-cutanée','ALK-Abello, Inc.','US','Non-Standardized Pollen Allergenic Extract','CENTER-AL - QUERCUS ALBA POLLEN'),
('Anti Bacterial Hand Gel Sweet Orange and Agave','alcohol','Gel','ALCOHOL 71 mL/100mL','Topique','Bath & Body Works, Inc.','INT','Médicaments topiques','Anti Bacterial Hand Gel Sweet Orange and Agave'),
('Livestock Nosode Combination 9413','livestock nosode combination','LIQUID','BACILLUS ANTHRACIS IMMUNOSERUM RABBIT 12 [hp_X]/29.5mL','Orale','Professional Complementary Health Formulas','INT',NULL,'Livestock Nosode Combination 9413'),
('R32 IMMUNO-CLR','betula pendula, folia, bos taurus thymus, castanea vesca, poplar bud, ribes nigrum flower bud, rna, viscum album stem','Solution','BETULA PENDULA LEAF 2 [hp_X]/mL','Sublinguale','Apex Energetics Inc.','INT',NULL,'R32 IMMUNO-CLR'),
('TECHNETIUM Tc 99m MERTIATIDE','technetium tc 99m mertiatide','Solution','BETIATIDE 1 mg/1','Intraveineuse','Jubilant DraxImage Inc., dba Jubilant Radiopharma','US','Médicaments IV / Hospitaliers','TECHNETIUM Tc 99m MERTIATIDE'),
('Diprivan','propofol','Solution injectable','PROPOFOL 10 mg/mL','Intraveineuse','Fresenius Kabi USA, LLC','US','General Anesthetic','Diprivan'),
('Alka-Seltzer Plus Maximum Strength Night Cold and Flu','acetaminophen, dextromethorphan hydrobromide, doxylamine succinate, phenylephrine hydrochloride','Gélule','ACETAMINOPHEN 325 mg/1','Orale','Bayer HealthCare LLC.','INT','Antihistamine','Alka-Seltzer Plus Maximum Strength Night Cold and Flu'),
('MONISTAT 3','miconazole nitrate','Kit',NULL,NULL,'Insight Pharmaceuticals LLC','US',NULL,'MONISTAT 3'),
('TLB-Matrix','joint booster','LIQUID','ATROPA BELLADONNA 15 [hp_X]/mL','Orale','Vitality Works, Inc.','INT','Copper Absorption Inhibitor','TLB-Matrix'),
('Pollens - Trees, Cottonwood, Common Populus deltoides','cottonwood, common populus deltoides','Solution','POPULUS DELTOIDES POLLEN .05 g/mL','PERCUTANEOUS','Jubilant HollisterStier LLC','US','Non-Standardized Pollen Allergenic Extract','Pollens - Trees, Cottonwood, Common Populus deltoides'),
('Molds, Rusts and Smuts, Fusarium vasinfectum','fusarium vasinfectum','Solution','FUSARIUM OXYSPORUM VASINFECTUM .1 g/mL','PERCUTANEOUS','Jubilant HollisterStier LLC','US','Non-Standardized Fungal Allergenic Extract','Molds, Rusts and Smuts, Fusarium vasinfectum'),
('Cefprozil','cefprozil','Comprimé','CEFPROZIL 500 mg/1','Orale','Ascend Laboratories, LLC','US',NULL,'Cefprozil'),
('Enalapril Maleate Oral Solution','enalapril maleate oral solution','Solution','ENALAPRIL MALEATE 1 mg/mL','Orale','Ascend Laboratories, LLC','US','Angiotensin Converting Enzyme Inhibitor','Enalapril Maleate Oral Solution'),
('Emvita 10','agnus castus, arum triph, hepar sulph calc, lachesis, pancreas, petroleum','LIQUID','ARISAEMA TRIPHYLLUM ROOT 18 [hp_M]/60mL','Orale','RUBIMED AG','INT',NULL,'Emvita 10'),
('Omeprazole, 24/7 Life by 7-Eleven','omeprazole tablet, delayed release','Comprimé','OMEPRAZOLE MAGNESIUM 20.6 mg/1','Orale','Lil'' Drug Store Products, Inc.','INT','Proton Pump Inhibitor','Omeprazole, 24/7 Life by 7-Eleven'),
('WinCo Foods Saline Nasal Relief','sodium chloride','Spray','SODIUM CHLORIDE .65 g/100mL','Nasale','WinCo Foods, LLC','INT',NULL,'WinCo Foods Saline Nasal Relief'),
('AGE20S SIGNATURE ESSENCE PACT INTENSE COVER MINI 25N','octinoxate, octocrylene, titanium dioxide','Crème','OCTINOXATE .26 g/4g','Topique','Aekyung Industrial Co., Ltd.','INT','Médicaments topiques','AGE20S SIGNATURE ESSENCE PACT INTENSE COVER MINI 25N'),
('Ibuprofen Oral','ibuprofen oral','Suspension','IBUPROFEN 100 mg/5mL','Orale','NuCare Pharmaceuticals,Inc.','US','Nonsteroidal Anti-inflammatory Drug','Ibuprofen Oral'),
('Walgreens Lidocaine Back','lidocaine','Patch transdermique','LIDOCAINE 40 mg/g','Topique','Walgreen Co.','INT','Amide Local Anesthetic','Walgreens Lidocaine Back'),
('Alocane Emergency Burn','lidocaine hydrochloride','Gel','LIDOCAINE HYDROCHLORIDE 4 g/100mL','Topique','Quest Products, LLC.','INT','Amide Local Anesthetic','Alocane Emergency Burn'),
('Sun Bum Mineral 30 Sunscreen 3 OZ New','zinc oxide','Lotion','ZINC OXIDE 147 mg/mL','Topique','Sun Bum, LLC','INT','Médicaments topiques','Sun Bum Mineral 30 Sunscreen 3 OZ New'),
('First Aid Beauty FAB Ultra Repair Intense Hydration Skin Protectant Vanilla','colloidal oatmeal','Crème','OATMEAL .5 g/100g','Topique','The Procter & Gamble Manufacturing Company','INT','Non-Standardized Food Allergenic Extract','First Aid Beauty FAB Ultra Repair Intense Hydration Skin Protectant Vanilla'),
('Vicks NyQuil HIGH BLOOD PRESSURE Cold and Flu','acetaminophen, dextromethorphan hydrobromide, and doxylamine succinate','LIQUID','ACETAMINOPHEN 650 mg/30mL','Orale','The Procter & Gamble Manufacturing Company','INT','Antihistamine','Vicks NyQuil HIGH BLOOD PRESSURE Cold and Flu'),
('A Health Itch Relief Gel','itch relief gel','Gel','DIPHENHYDRAMINE HYDROCHLORIDE 2 mg/100mL','Topique','Bionpharma, Inc.','INT','Histamine-1 Receptor Antagonist','A Health Itch Relief Gel'),
('CVS Health SPF 50 Beach Guard','avobenzone, homosalate, octisalate, octocrylene','STICK','AVOBENZONE 30 mg/g','Topique','CVS Pharmacy','INT','Médicaments topiques','CVS Health SPF 50 Beach Guard'),
('KT Pain Relief Cream Magnesium with Arnica and 4% Lidocaine','kt pain relief cream magnesium with arnica and 4% lidocaine rollon','LIQUID','LIDOCAINE 4 g/100mL','Topique','Clarion Brands LLC','INT','Amide Local Anesthetic','KT Pain Relief Cream Magnesium with Arnica and 4% Lidocaine'),
('CVS Itch Relief','diphenhydramine hcl, zinc acetate','Spray','DIPHENHYDRAMINE HYDROCHLORIDE 2 g/100mL','Topique','CVS','INT','Copper Absorption Inhibitor','CVS Itch Relief'),
('Clean and Clear Advantage Acne Spot Treatment','salicylic acid','Lotion','SALICYLIC ACID 20 mg/mL','Topique','Kenvue Brands LLC','INT','Médicaments topiques','Clean and Clear Advantage Acne Spot Treatment'),
('Neutrogena Healthy Skin Radiant Tinted Moisturizer Sunscreen Broad Spectrum SPF 25, Sheer Tan 30','titanium dioxide, zinc oxide','Lotion','TITANIUM DIOXIDE 60 mg/mL','Topique','Kenvue Brands LLC','INT','Médicaments topiques','Neutrogena Healthy Skin Radiant Tinted Moisturizer Sunscreen Broad Spectrum SPF 25, Sheer Tan 30'),
('LOQTORZI','toripalimab-tpzi','Solution injectable','TORIPALIMAB 240 mg/6mL','Intraveineuse','Coherus Oncology, Inc.','US','Programmed Death Receptor-1 Blocking Antibody','LOQTORZI'),
('DermaNumb Analgesic','lidocaine hcl','Gel','LIDOCAINE HYDROCHLORIDE 40 mg/g','Topique','A.T.S. Laboratories, LLC','INT','Amide Local Anesthetic','DermaNumb Analgesic'),
('Lice Ladies Prevent','sabadilla','Spray','SCHOENOCAULON OFFICINALE SEED 6 [hp_X]/mL','Topique','Lice Ladies Atlanta, LLC','INT','Médicaments topiques','Lice Ladies Prevent'),
('Tudorza Pressair','aclidinium bromide','Poudre','ACLIDINIUM BROMIDE 400 ug/1','Inhalation','Covis Pharma US, Inc','US','Anticholinergic','Tudorza Pressair'),
('Foster and Thrive Ready to Use Mineral oil Laxative','mineral oil','Lavement','MINERAL OIL 1000 g/118mL','Rectale','Strategic Sourcing Services LLC','INT',NULL,'Foster and Thrive Ready to Use Mineral oil Laxative'),
('Right Remedies Maximum Strength Gas Relief Softgel','simethicone','Gélule','DIMETHICONE 250 mg/1','Orale','Strive Pharmaceuticals Inc.','INT','Skin Barrier Activity','Right Remedies Maximum Strength Gas Relief Softgel'),
('Touchpoint Biodegradable Sanitizing Wipes','benzalkonium chloride','CLOTH','BENZALKONIUM CHLORIDE 1.3 mg/1','CUTANEOUS','Innocore Sales & Marketing Inc','INT',NULL,'Touchpoint Biodegradable Sanitizing Wipes'),
('Sodium Fluoride Chewable','sodium fluoride','Comprimé','SODIUM FLUORIDE 1 mg/1','Orale','Bryant Ranch Prepack','INT',NULL,'Sodium Fluoride Chewable'),
('SCENTUAL AROMA BEAUTY SUN VEIL SPF30','titanium dioxide, zinc oxide','Crème','TITANIUM DIOXIDE 2 g/100g','Topique','LABORATOIRES DRUIDE INC','INT','Médicaments topiques','SCENTUAL AROMA BEAUTY SUN VEIL SPF30'),
('Glucose Control T015','syzygium jambolanum, glandula suprarenalis suis, hydrastis canadensis, hypophysis suis, pancreas suis, phaseolus, aceticum acidum, lacticum acidum, phosphoricum acidum, phosphorus, uranium nitricum','LIQUID','ACETIC ACID 12 [hp_X]/mL','Orale','Guangzhou Renuma Medical Systems Co., Ltd','INT','Non-Standardized Food Allergenic Extract','Glucose Control T015'),
('Aromalief Pain Relief Cream Orange Ginger','menthol','Lotion','MENTHOL 1 g/100g','Topique','Marketites LLC','INT','Médicaments topiques','Aromalief Pain Relief Cream Orange Ginger'),
('Petrolatum','white petrolatum','JELLY','PETROLATUM 1 g/g','Topique','Retail Business Services, LLC','INT','Médicaments topiques','Petrolatum'),
('AcuPlus Advanced Therapy for Pain and Recovery','menthol','Solution','MENTHOL 35 mg/mL','Topique','INNOVATIONS FOR WELLNESS, LLC','INT','Médicaments topiques','AcuPlus Advanced Therapy for Pain and Recovery'),
('Bystolic','nebivolol hydrochloride','Comprimé','NEBIVOLOL HYDROCHLORIDE 2.5 mg/1','Orale','Allergan, Inc.','US','beta-Adrenergic Blocker','Bystolic')
) AS v(nom, dci, forme, dosage, voie, labo, pays, classe, nomcom)
WHERE NOT EXISTS (
  SELECT 1 FROM medicaments m WHERE UPPER(m.nom) = UPPER(v.nom)
);
