-- ndc_batch_033.sql (80 rows)
INSERT INTO medicaments (nom, dci, forme, dosage, voie_administration, laboratoire, pays, classe_therapeutique, nom_commercial)
SELECT v.nom, v.dci, v.forme, v.dosage, v.voie, v.labo, v.pays, v.classe, v.nomcom
FROM (VALUES
('H2OCEAN NOTHING','benzalkonium cl, lidocaine hcl','LIQUID','BENZALKONIUM CHLORIDE .13 g/100mL','Topique','H2Ocean, LLC','INT','Amide Local Anesthetic','H2OCEAN NOTHING'),
('Neuracin Topical Gel','neuracin topical analgesic gel','Gel','CAMPHOR (SYNTHETIC) 40 mg/g','Topique','SOLA Pharmaceuticals','INT','Médicaments topiques','Neuracin Topical Gel'),
('Dofetilide','dofetilide','Gélule','DOFETILIDE .25 mg/1','Orale','REMEDYREPACK INC.','US','Antiarrhythmic','Dofetilide'),
('Foster and Thrive Chest Congestion Relief PE PE','guaifenesin/phenylephrine','Comprimé','GUAIFENESIN 400 mg/1','Orale','Strategic Sourcing Services LLC','INT','Expectorant','Foster and Thrive Chest Congestion Relief PE PE'),
('Raw Elements Eco Formula SPF30 Sample Packs','zinc oxide','Lotion','ZINC OXIDE 230 mg/g','Topique','Raw Elements LLC','INT','Copper Absorption Inhibitor','Raw Elements Eco Formula SPF30 Sample Packs'),
('Sevelamer Hydrochloride','sevelamer hydrochloride','Comprimé','SEVELAMER HYDROCHLORIDE 800 mg/1','Orale','Zydus Pharmaceuticals USA Inc.','US','Phosphate Binder','Sevelamer Hydrochloride'),
('Free to Breathe','calendula, eucalyptus,peppermint','SALVE','CALENDULA OFFICINALIS FLOWER 1 [hp_X]/100g','Topique','Spry Life LLC','INT','Médicaments topiques','Free to Breathe'),
('TheraCare Hemorrhoidal','mineral oil, petrolatum, phenylephrine hcl','Pommade','MINERAL OIL 14 g/100g','Rectale','Veridian Healthcare','INT','alpha-1 Adrenergic Agonist','TheraCare Hemorrhoidal'),
('Haloperidol Lactate','haloperidol','Solution','HALOPERIDOL LACTATE 5 mg/mL','Intramusculaire','Henry Schein, Inc.','US','Typical Antipsychotic','Haloperidol Lactate'),
('Eltrombopag','eltrombopag olamine','Comprimé','ELTROMBOPAG OLAMINE 25 mg/1','Orale','Hikma Pharmaceuticals USA Inc.','US','Thrombopoietin Receptor Agonist','Eltrombopag'),
('Honey Lemon Cough Drops','menthol','Pastille','MENTHOL 6 mg/1','Orale','Trader Joe''s Company','INT',NULL,'Honey Lemon Cough Drops'),
('CU Pain Away Pain Relief','menthol','Crème','MENTHOL 12.5 mg/g','Topique','Canadian Unique Health Ltd.','INT','Médicaments topiques','CU Pain Away Pain Relief'),
('Regular Strength Assorted Flavors','antacid calcium carbonate','Comprimé','CALCIUM CARBONATE 500 mg/1','Orale','AKRON PHARMA INC','INT','Blood Coagulation Factor','Regular Strength Assorted Flavors'),
('FIRSTAR BZK Antiseptic Towelette','benzalkonium chloride','SWAB','BENZALKONIUM CHLORIDE .13 g/100g','Topique','JIANGMEN SHUIZIRUN SANITARY ARTICLES CO., LTD.','INT','Médicaments topiques','FIRSTAR BZK Antiseptic Towelette'),
('Arthritis Pain Reliever','diclofenac sodium','Gel','DICLOFENAC SODIUM 10 mg/g','Topique','Care One (Retail Business Services, LLC.)','US','Nonsteroidal Anti-inflammatory Drug','Arthritis Pain Reliever'),
('NuValu Epsom Salt','magnesium sulfate (heptahydrate)','GRANULE','MAGNESIUM SULFATE HEPTAHYDRATE 100 g/100g','Orale','J C SALES','INT','Calculi Dissolution Agent','NuValu Epsom Salt'),
('Head Congestion plus Flu Severe PE','acetaminophen, dextromethorphan hydrobromide, guaifenesin, and phenylephrine hydrochloride','Comprimé','ACETAMINOPHEN 325 mg/1','Orale','HARRIS TEETER','INT','Expectorant','Head Congestion plus Flu Severe PE'),
('Namzaric','memantine hydrochloride and donepezil hydrochloride','Gélule','DONEPEZIL HYDROCHLORIDE 10 mg/1','Orale','Allergan, Inc.','US','Cholinesterase Inhibitor','Namzaric'),
('SAPHRIS','asenapine maleate','Comprimé','ASENAPINE MALEATE 10 mg/1','Sublinguale','Allergan, Inc.','US','Atypical Antipsychotic','SAPHRIS'),
('Myrbetriq','mirabegron','Comprimé','MIRABEGRON 50 mg/1','Orale','Astellas Pharma US, Inc.','US','beta3-Adrenergic Agonist','Myrbetriq'),
('Amantadine HCL','amantadine hcl','Comprimé','AMANTADINE HYDROCHLORIDE 100 mg/1','Orale','Direct_Rx','US','Influenza A M2 Protein Inhibitor','Amantadine HCL'),
('DEYO','disinfecting wet wipes','CLOTH','ALCOHOL .75 mL/1','Topique','Henan Yeesain Health Technology Co., Ltd.','INT','Médicaments topiques','DEYO'),
('Rugby Cetirizine Hydrochloride and Pseudoephedrine Hydrochloride','cetirizine hydrochloride, pseudoephedrine hydrochloride','Comprimé','CETIRIZINE HYDROCHLORIDE 5 mg/1','Orale','Rugby Laboratories','US','Histamine-1 Receptor Antagonist','Rugby Cetirizine Hydrochloride and Pseudoephedrine Hydrochloride'),
('Rugby Zinc Oxide 20%','rugby zinc oxide 20%','Pommade','ZINC OXIDE 20 g/100g','Topique','Rugby Laboratories','INT','Médicaments topiques','Rugby Zinc Oxide 20%'),
('CLINDAMYCIN PHOSPHATE AND BENZOYL PEROXIDE CLINDAMYCIN PHOSPHATE AND BENZOYL PEROXIDE','clindamycin phosphate and benzoyl peroxide','Gel','BENZOYL PEROXIDE 50 mg/g','Topique','Northstar Rx LLC','US','Lincosamide Antibacterial','CLINDAMYCIN PHOSPHATE AND BENZOYL PEROXIDE CLINDAMYCIN PHOSPHATE AND BENZOYL PEROXIDE'),
('Pindolol','pindolol','Comprimé','PINDOLOL 10 mg/1','Orale','PD-Rx Pharmaceuticals, Inc.','US','beta-Adrenergic Blocker','Pindolol'),
('Doxepin','doxepin','Comprimé','DOXEPIN HYDROCHLORIDE 3 mg/1','Orale','Archis Pharma LLC','US','Tricyclic Antidepressant','Doxepin'),
('MADECASSOL','centella asiatica','Gel','CENTELLA ASIATICA 10 mg/g','Topique','Lydia Co., Ltd.','INT','Médicaments topiques','MADECASSOL'),
('CBD Clinic Pain Relief - Level 5','menthol, camphor','Pommade','CAMPHOR (NATURAL) 11 g/100g','Topique','ABACUS HEALTH PRODUCTS, INC.','INT','Médicaments topiques','CBD Clinic Pain Relief - Level 5'),
('Antiperspirant Above Sport Energy Men','antiperspirant above sport energy men aerosol','Spray','ALUMINUM SESQUICHLOROHYDRATE 24 g/100g','Topique','Baston Industria de Aerossis Ltda','INT','Médicaments topiques','Antiperspirant Above Sport Energy Men'),
('Ambi Even and Clean Skin Tone Kit','salicylic acid','Kit',NULL,NULL,'Ambi Enterprise LLC','INT',NULL,'Ambi Even and Clean Skin Tone Kit'),
('THE SKIN HOUSE Wrinkle Snail SystemCream','adenosine','Crème','ADENOSINE .04 g/100mL','Topique','NOKSIBCHO cosmetic Co., Ltd.','INT','Adenosine Receptor Agonist','THE SKIN HOUSE Wrinkle Snail SystemCream'),
('PLAY Sunscreen SPF 50','homosalate, octocrylene, octisalate, avobenzone','STICK','AVOBENZONE 3 g/100g','Topique','Supergoop LLC','INT','Médicaments topiques','PLAY Sunscreen SPF 50'),
('Topcare 70 Isopropyl Alcohol Wipes','isopropyl alcohol','CLOTH','ISOPROPYL ALCOHOL .7 mL/mL','Topique','Topco Associates LLC','INT','Médicaments topiques','Topcare 70 Isopropyl Alcohol Wipes'),
('e.l.f. Hydrating Camo CC Cream SPF30 Rich 610 N','homosalate, octisalate, octocrylene, zinc oxide','Crème','HOMOSALATE 50 mg/g','Topique','e.l.f. Cosmetics, Inc.','INT','Médicaments topiques','e.l.f. Hydrating Camo CC Cream SPF30 Rich 610 N'),
('Gallium Ga-68 PSMA-11','gallium ga-68 gozetotide','Solution','GALLIUM GA-68 GOZETOTIDE 5 mCi/mL','Intraveineuse','UCLA Biomedical Cyclotron','US','Radioactive Diagnostic Agent','Gallium Ga-68 PSMA-11'),
('KRAZATI','adagrasib','Comprimé','ADAGRASIB 200 mg/1','Orale','Mirati Therapeutics, Inc','US',NULL,'KRAZATI'),
('The INKEY List Beta Hydroxy Acid Serum','salicylic acid','Gel','SALICYLIC ACID 20 mg/mL','Topique','Brand Evangelists for Beauty Ltd','INT','Médicaments topiques','The INKEY List Beta Hydroxy Acid Serum'),
('Acne Dots','salicylic acid','Patch transdermique','SALICYLIC ACID 5 mg/1000mg','Transdermique','Hangzhou Caring Cleaning Commodity Co., Ltd','INT',NULL,'Acne Dots'),
('Diclofenac Sodium and Misoprostol','diclofenac sodium and misoprostol','Comprimé','DICLOFENAC SODIUM 75 mg/1','Orale','Actavis Pharma, Inc.','US','Nonsteroidal Anti-inflammatory Drug','Diclofenac Sodium and Misoprostol'),
('CALCAREA SULPHURICA 6X','calcarea sulphurica','PELLET','CALCIUM SULFATE ANHYDROUS 6 [hp_X]/1','Sublinguale','SEVENE USA','INT','Blood Coagulation Factor','CALCAREA SULPHURICA 6X'),
('MIAMI MD SUN SHIELD Broad Spectrum SPF 40','avobenzone, homosalate, octisalate, octocrylene','Crème','AVOBENZONE 30 mg/mL','Topique','BRAND BOLT LLC','INT','Médicaments topiques','MIAMI MD SUN SHIELD Broad Spectrum SPF 40'),
('Unscented NasalGuard Antiseptic Topical','benzalkonium chloride','Gel','BENZALKONIUM CHLORIDE 1.3 mg/1000mg','Topique','TRUTEK CORP.','INT','Médicaments topiques','Unscented NasalGuard Antiseptic Topical'),
('Sotalol Hydrochloride','sotalol hydrochloride','Comprimé','SOTALOL HYDROCHLORIDE 80 mg/1','Orale','Proficient Rx LP','US','Antiarrhythmic','Sotalol Hydrochloride'),
('SYNC ICE','sync relief ice','Gel','MENTHOL 4 g/1','Topique','iON Pharma, LLC','INT','Médicaments topiques','SYNC ICE'),
('Bestmade Natural Products BM98','sepia, sanguinaria, acid sulph, lachesis, amyl nitrosum, aquilegia, cimicifuga','LIQUID','AMYL NITRITE 30 [hp_C]/30[hp_C]','Orale','Bestmade Natural Products','INT',NULL,'Bestmade Natural Products BM98'),
('Bestmade Natural Products Iodium','iodium','Comprimé','IODINE 30 [hp_C]/30[hp_C]','Orale','Bestmade Natural Products','INT',NULL,'Bestmade Natural Products Iodium'),
('Aging Eye Formula','cineraria maritima, eye (suis), calcarea fluorica, causticum, phosphorus, silicea, zincum metallicum, germanium metallicum, natrum muriaticum','Spray','CALCIUM FLUORIDE 12 [hp_X]/mL','Orale','Nutritional Specialties, Inc.','INT',NULL,'Aging Eye Formula'),
('HEALMUSZ WART REMOVER','salicylic acid 5% wart remover','LIQUID','SALICYLIC ACID 5 g/100mL','Topique','Jiangxi Yudexi Pharmaceutical Co., LTD','INT','Médicaments topiques','HEALMUSZ WART REMOVER'),
('FRNOIP 5% Minoxidil Hair Growth Sprays Serum','minoxidil 5%','LIQUID','BIOTIN .5 g/100mL','Topique','Guangzhou Borderless Technology Co., Ltd.','INT','Arteriolar Vasodilator','FRNOIP 5% Minoxidil Hair Growth Sprays Serum'),
('Deconimo','hand sanitizing wipes','CLOTH','ALCOHOL 75 mL/100mL','Topique','IMAGINE AMAZON LLC','INT','Médicaments topiques','Deconimo'),
('Porphose','colloidal oatmeal topical spray','Spray','OATMEAL .15 g/100g','Topique','Porphose','INT','Non-Standardized Food Allergenic Extract','Porphose'),
('Secret Weightless Dry Variety Pack','aluminum chlorohydrate','Kit',NULL,NULL,'The Procter & Gamble Manufacturing Company','INT',NULL,'Secret Weightless Dry Variety Pack'),
('Super Chocolate Fluoride Mouthwash','anticavity mouthwash','LIQUID','SODIUM FLUORIDE .002 mg/10mL','DENTAL','SuperMouth, LLC.','INT',NULL,'Super Chocolate Fluoride Mouthwash'),
('VYKAT XR','diazoxide choline','Comprimé','DIAZOXIDE CHOLINE 25 mg/1','Orale','Soleno Therapeutics, Inc.','US',NULL,'VYKAT XR'),
('Moisturize Cream','moisturize cream','Crème','GLYCERIN 3 mg/70mL','CUTANEOUS','Guangzhou Yanxi Biotechnology Co., Ltd','INT','Non-Standardized Chemical Allergen','Moisturize Cream'),
('Crest Clean Breath Spearmint','stannous fluoride','PASTE, DENTIFRICE','STANNOUS FLUORIDE 1.5 mg/g','DENTAL','The Procter & Gamble Manufacturing Company','INT',NULL,'Crest Clean Breath Spearmint'),
('Cancer Council Daily Body Moisturizer SPF50 Plus','avobenzone, homosalate, octisalate, octocrylene','Lotion','AVOBENZONE 30 mg/mL','Topique','Vitality US Co.','INT','Médicaments topiques','Cancer Council Daily Body Moisturizer SPF50 Plus'),
('COLLAGECREAM','collagecream','Crème','TOCOPHEROL .05 g/50g','CUTANEOUS','Guangzhou Kadiya Biotechnology Co., Ltd.','INT',NULL,'COLLAGECREAM'),
('Sunplus Mist Sunscreen SPF 30','avobenzone, octisalate, octocrylene','LIQUID','AVOBENZONE 30 mg/mL','Topique','SUNPLUS SKIN CARE LLC','INT','Médicaments topiques','Sunplus Mist Sunscreen SPF 30'),
('Omlonti','omidenepag isopropyl','Solution','OMIDENEPAG ISOPROPYL .02 mg/mL','Ophtalmique','Ocuvex Therapeutics, Inc.','US','Prostaglandin E2 Receptor Agonist','Omlonti'),
('Sungboon Editor Hydro Booster Moisture Sunscreen','homosalate, octisalate, octocrylene, avobenzone','Crème','AVOBENZONE 28 mg/mL','Topique','Olive International Inc.','INT','Médicaments topiques','Sungboon Editor Hydro Booster Moisture Sunscreen'),
('AMERFRESH FLUORIDE','sodium fluoride','PASTE, DENTIFRICE','SODIUM FLUORIDE .1 g/100g','Topique','Yangzhou ONE & ONLY Personal Care Products Co., LTD','INT','Médicaments topiques','AMERFRESH FLUORIDE'),
('duvelisib','duvelisib','Gélule','DUVELISIB 15 mg/1',NULL,'Catalent Pharma Solutions, LLC','INT',NULL,NULL),
('FLUVASTATIN SODIUM milled','fluvastatin sodium milled','Poudre','FLUVASTATIN SODIUM 1 kg/kg',NULL,'DELMAR CHEMICALS INC','INT',NULL,NULL),
('Dr Simi Extra Strength Acetaminophen 250 mg, Aspirin 250 mg, and Caffeine 65 mg','acetaminophen 250 mg, aspirin 250 mg, and caffeine 65 mg','Comprimé','ACETAMINOPHEN 250 mg/1','Orale','Farmacias De Similares TX LLC','INT','Central Nervous System Stimulant','Dr Simi Extra Strength Acetaminophen 250 mg, Aspirin 250 mg, and Caffeine 65 mg'),
('COCO AND EVE SUNNY HONEY PROTECT TAN BOOSTING ANTI-AGING SPF 45','sunscreen oil','OIL','AVOBENZONE 3 mg/100mg','Topique','Soleil Collective LLC','INT','Médicaments topiques','COCO AND EVE SUNNY HONEY PROTECT TAN BOOSTING ANTI-AGING SPF 45'),
('oopsie First Aid','bacitracin zinc neomycin sulfate polymyxin b sulfate','Pommade','BACITRACIN ZINC 400 [USP''U]/g','Topique','4 Visions LLC','INT','Aminoglycoside Antibacterial','oopsie First Aid'),
('Panama Jack SPF 45 Dreamsicle Lip Balm','avobenzone, homosalate, octinoxate, octisalate, petrolatum','STICK','AVOBENZONE 30 mg/g','Topique','Panama Jack','INT','Médicaments topiques','Panama Jack SPF 45 Dreamsicle Lip Balm'),
('bareMinerals BAREPRO Performance Wear Liquid Foundation Broad Spectrum SPF 20 Aspen 04','titanium dioxide','LIQUID','TITANIUM DIOXIDE 33.2 mg/mL','Topique','Orveon Global US LLC','INT','Médicaments topiques','bareMinerals BAREPRO Performance Wear Liquid Foundation Broad Spectrum SPF 20 Aspen 04'),
('Indapamide','indapamide','Comprimé','INDAPAMIDE 2.5 mg/1',NULL,'Actavis Pharma, Inc.','INT',NULL,NULL),
('Tobramycin Sulfate','tobramycin sulfate','Poudre','TOBRAMYCIN SULFATE 1 g/g',NULL,'Spectrum Laboratory Products, Inc.','INT',NULL,NULL),
('MYCOPHENOLATE SODIUM','mycophenolate sodium','Poudre','MYCOPHENOLATE SODIUM 1 kg/kg',NULL,'Apotex Inc.','INT',NULL,NULL),
('Finerenone','finerenone','Comprimé','FINERENONE 40 mg/1',NULL,'Bayer HealthCare Pharmaceuticals Inc.','INT',NULL,NULL),
('Sofosbuver','sofosbuver','Poudre','SOFOSBUVIR 100 kg/100kg',NULL,'Teva API India Private Ltd','INT',NULL,NULL),
('darunavir ethanolate and cobicistat','darunavir ethanolate and cobicistat','Comprimé','COBICISTAT 150 mg/1',NULL,'Janssen Ortho LLC','INT',NULL,NULL),
('Tigilanol Tiglate','tigilanol tiglate','Poudre','TIGILANOL TIGLATE 1 g/g',NULL,'Indena SpA','INT',NULL,NULL),
('bivalirudin','bivalirudin','Poudre','BIVALIRUDIN 1 kg/kg',NULL,'Ambiopharm, Inc.','INT',NULL,NULL),
('Moxidectin','moxidectin','Poudre','MOXIDECTIN 1 kg/kg',NULL,'Livzon Group Fuzhou Fuxing Pharmaceutical Co., Ltd.','INT',NULL,NULL),
('VALBENAZINE DITOSYLATE','valbenazine ditosylate','Poudre','VALBENAZINE DITOSYLATE 1 kg/kg',NULL,'F.I.S. FABBRICA ITALIANA SINTETICI S.P.A.','INT',NULL,NULL)
) AS v(nom, dci, forme, dosage, voie, labo, pays, classe, nomcom)
WHERE NOT EXISTS (
  SELECT 1 FROM medicaments m WHERE UPPER(m.nom) = UPPER(v.nom)
);
