-- ndc_batch_054.sql (80 rows)
INSERT INTO medicaments (nom, dci, forme, dosage, voie_administration, laboratoire, pays, classe_therapeutique, nom_commercial)
SELECT v.nom, v.dci, v.forme, v.dosage, v.voie, v.labo, v.pays, v.classe, v.nomcom
FROM (VALUES
('Relief Pain Relieving Cream','menthol','Crème','MENTHOL 2.5 g/100g','Topique','Corganics, LP','INT','Médicaments topiques','Relief Pain Relieving Cream'),
('Sodium Sulfacetamide 9% and Sulfur 4% Cleanser','sulfacetamide sodium, sulfur','LIQUID','SULFACETAMIDE SODIUM 90 mg/mL','Topique','Method Pharmaceuticals','INT','Sulfonamide Antibacterial','Sodium Sulfacetamide 9% and Sulfur 4% Cleanser'),
('Azolen','miconazole nitrate','TINCTURE','MICONAZOLE NITRATE 20 mg/mL','Topique','Stratus Pharmaceuticals, Inc.','INT','Azole Antifungal','Azolen'),
('Dexatran','multivitamin','Gélule','CALCIUM PANTOTHENATE 10 mg/1','CUTANEOUS','PureTek Corporation','INT','Calculi Dissolution Agent','Dexatran'),
('Intestia','echinacea, iris versicolor, urtica urens, arsenicum album, baptisia tinctoria, bryonia, cinchona officinalis, collinsonia canadensis, dioscorea villosa, i odium, iris versicolor, lachesis mutus, lycopodium clavatum, natrum carbonicum, natrum muriaticum, nux vomica, phosphorus, podophyllum peltatum, pulsatilla, rhus toxicodendron, pyrogenium','LIQUID','ANEMONE PULSATILLA 15 [hp_X]/mL','Orale','Newton Laboratories, Inc.','INT','Non-Standardized Plant Allergenic Extract','Intestia'),
('Alert','caffeine','Comprimé','CAFFEINE 200 mg/1','Orale','DOLGENCORP, LLC','INT','Central Nervous System Stimulant','Alert'),
('GeriCare Senna Syrup','sennosides','LIQUID','SENNOSIDES 8.8 mg/5mL','Orale','Geri-Care Pharmaceutical Corp.','INT',NULL,'GeriCare Senna Syrup'),
('N-9','phosphorus, citrullus colocynthis fruit pulp, iris versicolor whole, lycopodium clavatum whole, momordica balsamina whole, and bos taurus pancreas','Solution','BOS TAURUS PANCREAS 200 [hp_X]/mL','Sublinguale','DNA Labs, Inc.','INT',NULL,'N-9'),
('ENBREL','etanercept','Solution','ETANERCEPT 25 mg/.5mL','Sous-cutanée','Immunex Corporation','US','Tumor Necrosis Factor Blocker','ENBREL'),
('NIZATIDINE','nizatidine','Solution','NIZATIDINE 15 mg/mL','Orale','Amneal Pharmaceuticals LLC','US','Histamine-2 Receptor Antagonist','NIZATIDINE'),
('H-Fissures Formula','calendula officinalis, chamomilla','OIL','CALENDULA OFFICINALIS FLOWERING TOP 12 [hp_C]/11mL','Topique','Healing Natural Oils LLC','INT','Médicaments topiques','H-Fissures Formula'),
('Seasonal Allergy Formula','hydrastis canadensis, kali muriaticum, gelsemium sempervirens, kali bichromicum, sabadilla, histaminum, house dust, grass mix, trees mix, weeds mix','LIQUID','ACER NEGUNDO POLLEN 6 [hp_X]/mL','Orale','Integrative Healing Institute, LLC','INT','Allergens','Seasonal Allergy Formula'),
('Streptococcinum','streptococcus pyogenes','PELLET','STREPTOCOCCUS PYOGENES 30 [hp_C]/30[hp_C]','Orale','Boiron','INT',NULL,'Streptococcinum'),
('Coldcalm','onion, apis mellifera, atropa belladonna, eupatorium perfoliatum flowering top, gelsemium sempervirens root, strychnos nux-vomica seed, phytolacca americana root, pulsatilla vulgaris, dichromate ion','Comprimé','APIS MELLIFERA 6 [hp_C]/1','Orale','Laboratoires Boiron','INT','Non-Standardized Food Allergenic Extract','Coldcalm'),
('CALENDULA','calendula','Pommade','CALENDULA OFFICINALIS FLOWERING TOP 1 [hp_X]/g','Topique','Boiron','INT','Médicaments topiques','CALENDULA'),
('EMJ ANTIPERSPIRANT JOHN DEERE IRON HORIZON 2.6 OZ','aluminum zirconium trichlorohydrex gly 20%','STICK','ALUMINUM ZIRCONIUM TRICHLOROHYDREX GLY .2 g/g','Topique','RNA PHARMA LLC','INT','Médicaments topiques','EMJ ANTIPERSPIRANT JOHN DEERE IRON HORIZON 2.6 OZ'),
('Tinted Clear Zinc Solar Protection SPF 30','zinc oxide','Crème','ZINC OXIDE 176.7 mg/g','Topique','Allure Labs, Inc','INT','Copper Absorption Inhibitor','Tinted Clear Zinc Solar Protection SPF 30'),
('ASPARAGUS','asparagus officinalis','Solution','ASPARAGUS .1 g/mL','PERCUTANEOUS','ALK-Abello, Inc.','US','Non-Standardized Food Allergenic Extract','ASPARAGUS'),
('Flora Plus','aloe, alumina, antimon crud, arg nit, chelidonium maj, gambogia, graphites, hydrastis, lycopodium, silicea','LIQUID','ALOE VERA LEAF 12 [hp_X]/59.1mL','Orale','NET Remedies','INT',NULL,'Flora Plus'),
('Dior Forever Skin Glow Flawless Radiant Skin True Foundation SPF 25 10N Neutral','octisalate, titanium dioxide','EMULSION','OCTISALATE 45 mg/mL','Topique','Parfums Christian Dior','INT','Médicaments topiques','Dior Forever Skin Glow Flawless Radiant Skin True Foundation SPF 25 10N Neutral'),
('Fruit of the Earth LUV THAT SUN Sport Sunscreen Continuous SPF 70','avobenzone, homosalate, octisalate, octocrylene, oxybenzone','Spray','AVOBENZONE 30 mg/g','Topique','Fruit Of The Earth, Inc.','INT','Médicaments topiques','Fruit of the Earth LUV THAT SUN Sport Sunscreen Continuous SPF 70'),
('Anti-BacterialHandSpray Cactus Blossom','alcohol','Spray','ALCOHOL 72 mL/100mL','Topique','Bath & Body Works, Inc.','INT','Médicaments topiques','Anti-BacterialHandSpray Cactus Blossom'),
('ALTAVERA','levonorgestrel and ethinyl estradiol','Kit',NULL,NULL,'Bryant Ranch Prepack','US',NULL,'ALTAVERA'),
('Brompheniramine Maleate, Pseudoephedrine Hydrochloride and Dextromethorphan Hydrobromide','brompheniramine maleate, pseudoephedrine hydrochloride and dextromethorphan hydrobromide','Sirop','BROMPHENIRAMINE MALEATE 2 mg/5mL','Orale','Bryant Ranch Prepack','US','Sigma-1 Agonist','Brompheniramine Maleate, Pseudoephedrine Hydrochloride and Dextromethorphan Hydrobromide'),
('Organophosphate Combination 9309','organophosphate combination','LIQUID','BLACK COHOSH 3 [hp_X]/29.5mL','Orale','Professional Complementary Health Formulas','INT',NULL,'Organophosphate Combination 9309'),
('OYSTER','crassostrea virginica','Solution','EASTERN OYSTER .1 g/mL','PERCUTANEOUS','ALK-Abello, Inc.','US',NULL,'OYSTER'),
('SWEET CORN','zea mays','Solution','CORN .1 g/mL','PERCUTANEOUS','ALK-Abello, Inc.','US','Non-Standardized Food Allergenic Extract','SWEET CORN'),
('BANANA BOAT KIDS FREE 50','banana boat kids free 50','Spray','AVOBENZONE 3 g/100g','Topique','Edgewell Personal Care Brands, LLC','INT','Médicaments topiques','BANANA BOAT KIDS FREE 50'),
('M12 BRAIN','argentum metallicum, artemisia vulgaris, cicuta virosa, cobaltum metallicum, cocculus indicus, conium maculatum, ginkgo biloba, kali bromatum, lathyrus sativus, mercurius solubilis, nux vomica, plumbum metallicum, salix alba, scopolaminum hydrobromidum, sequoiadendron giganteum, sus scrofa cerebrum','Solution','ANAMIRTA COCCULUS SEED 4 [hp_X]/mL','Sublinguale','Apex Energetics Inc','INT','Anticholinergic','M12 BRAIN'),
('Broad Spectrum SPF 15 Sunscreen Vanilla Mint Lip Balm','broad spectrum spf 15 sunscreen vanilla mint lip balm','STICK','AVOBENZONE .13 g/4.25g','Topique','Raining Rose','INT','Médicaments topiques','Broad Spectrum SPF 15 Sunscreen Vanilla Mint Lip Balm'),
('Stopain Extra Strength Continuous','menthol','Spray','MENTHOL 80 mg/mL','Topique','Troy Manufacturing, Inc.','INT','Médicaments topiques','Stopain Extra Strength Continuous'),
('Sunscreen for Kids SPF 50','avobenzone, homosalate, octisalate','Spray','AVOBENZONE 30 mg/g','Topique','Valu Merchandisers Company','INT','Médicaments topiques','Sunscreen for Kids SPF 50'),
('Daytime Cold and Flu Non Drowsy','acetaminophen, dextromethorphan hydrobromide, phenylephrine hydrochloride','LIQUID','ACETAMINOPHEN 325 mg/15mL','Orale','QUALITY CHOICE (Chain Drug Marketing Association)','INT','Sigma-1 Agonist','Daytime Cold and Flu Non Drowsy'),
('Category II','immune system booster','LIQUID','ARALIA RACEMOSA ROOT 6 [hp_X]/mL','Orale','Vitality Works, Inc','INT',NULL,'Category II'),
('Dove Advanced Care Invisible Clear Finish 48h Antiperspirant','aluminum zirconium tetrachlorohydrex gly','STICK','ALUMINUM ZIRCONIUM TETRACHLOROHYDREX GLY 11.4 g/100g','Topique','Conopco Inc. d/b/a/ Unilever','INT','Médicaments topiques','Dove Advanced Care Invisible Clear Finish 48h Antiperspirant'),
('Crestor','rosuvastatin','Comprimé','ROSUVASTATIN CALCIUM 40 mg/1','Orale','AstraZeneca Pharmaceuticals LP','US','HMG-CoA Reductase Inhibitor','Crestor'),
('Almay Clear Complexion Makeup Neutral','salicylic acid','LIQUID','SALICYLIC ACID 2 mg/2mL','Topique','Almay','INT','Médicaments topiques','Almay Clear Complexion Makeup Neutral'),
('Pollens - Trees, Bottlebrush, Callistemon spp.','bottlebrush, callistemon citrinus','Solution','MELALEUCA CITRINA POLLEN .05 g/mL','PERCUTANEOUS','Jubilant HollisterStier LLC','US','Non-Standardized Pollen Allergenic Extract','Pollens - Trees, Bottlebrush, Callistemon spp.'),
('Molds - Mold Mix 4','molds - mold mix 4','Solution','ALTERNARIA ALTERNATA .1 g/mL','PERCUTANEOUS','Jubilant HollisterStier LLC','US','Non-Standardized Fungal Allergenic Extract','Molds - Mold Mix 4'),
('Acetaminophen and Codeine','acetaminophen and codeine','Comprimé','ACETAMINOPHEN 300 mg/1','Orale','Amneal Pharmaceuticals LLC','US','Opioid Agonist','Acetaminophen and Codeine'),
('Reyvow','lasmiditan','Comprimé','LASMIDITAN 50 mg/1','Orale','Eli Lilly and Company','US',NULL,'Reyvow'),
('Aralia Racemosa MT','aralia racemosa','LIQUID','ARALIA RACEMOSA ROOT .25 1/.25L','Orale','OHM PHARMA INC.','INT',NULL,'Aralia Racemosa MT'),
('Oraqix','lidocaine and prilocaine','Gel','LIDOCAINE 25 mg/g','PERIODONTAL','Dentsply Pharmaceutical','US','Amide Local Anesthetic','Oraqix'),
('Advil','ibuprofen','Comprimé','IBUPROFEN 200 mg/1','Orale','Lil'' Drug Store Products, Inc.','US','Nonsteroidal Anti-inflammatory Drug','Advil'),
('Isoflurane','isoflurane','LIQUID','ISOFLURANE 1 mL/mL','Inhalation','Piramal Critical Care, Inc.','US','General Anesthetic','Isoflurane'),
('BencoCaine Topical Anesthetic','benzocaine','Gel','BENZOCAINE 200 mg/g','DENTAL','Benco Dental','INT','Standardized Chemical Allergen','BencoCaine Topical Anesthetic'),
('Winco Irritation Relief Eye','tetrahydrozoline hcl, zinc sulfate','Solution','TETRAHYDROZOLINE HYDROCHLORIDE 50 mg/100mL','Ophtalmique','WinCo Foods, LLC','INT','Copper Absorption Inhibitor','Winco Irritation Relief Eye'),
('AGE20S SIGNATURE ESSENCE PACT INTENSE COVER 27W','octinoxate, octocrylene, titanium dioxide','Crème','OCTINOXATE .91 g/14g','Topique','Aekyung Industrial Co., Ltd.','INT','Médicaments topiques','AGE20S SIGNATURE ESSENCE PACT INTENSE COVER 27W'),
('Studio 35 External Analgesic Medicated Body','menthol and zinc oxide','Poudre','MENTHOL 1.5 mg/g','Topique','Walgreen Co','INT','Copper Absorption Inhibitor','Studio 35 External Analgesic Medicated Body'),
('Premium Hand Sanitizer','ethanol','Gel','ALCOHOL 70 g/100g','Topique','MCKESSON MEDICAL-SURGICAL INC.','INT','Médicaments topiques','Premium Hand Sanitizer'),
('NativeRemedies Kidney Stone Clear','belladonna,berberis vulgaris, calc carb, cantharis, lycopodium','LIQUID','ATROPA BELLADONNA 6 [hp_C]/59mL','Orale','Silver Star Brands','INT',NULL,'NativeRemedies Kidney Stone Clear'),
('PACLITAXEL PACLITAXEL','paclitaxel','Solution','PACLITAXEL 6 mg/mL','Intraveineuse','Gland Pharma Limited','US','Microtubule Inhibitor','PACLITAXEL PACLITAXEL'),
('Morphine Sulfate Extended Release','morphine sulfate','Comprimé','MORPHINE SULFATE 15 mg/1','Orale','American Health Packaging','US','Opioid Agonist','Morphine Sulfate Extended Release'),
('VOXZOGO 1.2mg','vosoritide','Kit',NULL,NULL,'BioMarin Pharmaceutical Inc.','US',NULL,'VOXZOGO 1.2mg'),
('Always Liquid Foundation Makeup Sunscreen Broad Spectrum SPF 15 - Natural Tan','homosalate, octisalate, zinc oxide','LIQUID','HOMOSALATE 4.25 g/100mL','Topique','Distribuidora Comercial Jafra, S.A. de C.V','INT','Médicaments topiques','Always Liquid Foundation Makeup Sunscreen Broad Spectrum SPF 15 - Natural Tan'),
('Sun Bum 15 Premium Moisturizing Sunscreen 8 OZ','avobenzone, homosalate, octisalate, octocrylene','Lotion','AVOBENZONE 20 mg/mL','Topique','Sun Bum, LLC','INT','Médicaments topiques','Sun Bum 15 Premium Moisturizing Sunscreen 8 OZ'),
('Sinus Headache PEMaximum Strength Non-Drowsy Maximum Strength Non-Drowsy','acetaminophen and phenylephrine hcl','Comprimé','ACETAMINOPHEN 325 mg/1','Orale','Allegiant Health','INT','alpha-1 Adrenergic Agonist','Sinus Headache PEMaximum Strength Non-Drowsy Maximum Strength Non-Drowsy'),
('Infants Pain and Fever','acetaminophen','Suspension','ACETAMINOPHEN 160 mg/5mL','Orale','WALGREENS','INT',NULL,'Infants Pain and Fever'),
('Harris Teeter Calamine','zinc oxide','LIQUID','ZINC OXIDE 160 mg/mL','Topique','Harris Teeter, LLC.','INT','Copper Absorption Inhibitor','Harris Teeter Calamine'),
('Pyrilamine Maleate and Dextromethorphan Hydrobromide','pyrilamine maleate and dextromethorphan hydrobromide','LIQUID','DEXTROMETHORPHAN HYDROBROMIDE 7.5 mg/5mL','Orale','Westminster Pharmaceuticals, LLC','INT','Sigma-1 Agonist','Pyrilamine Maleate and Dextromethorphan Hydrobromide'),
('Old Spice Canyon','aluminum zirconium tetrachlorohydrex gly','STICK','ALUMINUM ZIRCONIUM TETRACHLOROHYDREX GLY 15 g/100g','Topique','The Procter & Gamble Manufacturing Company','INT','Médicaments topiques','Old Spice Canyon'),
('Crest Premium Plus Breath Bacteria Blast','stannous fluoride','PASTE, DENTIFRICE','STANNOUS FLUORIDE 1.4 mg/g','DENTAL','The Procter & Gamble Manufacturing Company','INT',NULL,'Crest Premium Plus Breath Bacteria Blast'),
('FifthPulse Bacitracin Zinc 1oz','bacitracin zinc','Pommade','BACITRACIN ZINC 500 [iU]/g','Topique','Front Pharmaceutical PLC','INT','Decreased Cell Wall Synthesis & Repair','FifthPulse Bacitracin Zinc 1oz'),
('Fear Less','aspen, cal carb, elm, kali phos, mag phos, mimulus, star of bethlehem, walnut','Spray','JUGLANS REGIA FLOWERING TOP 5 [hp_X]/29.6mL','Orale','Siddha Flower Essences LLC','INT','Calculi Dissolution Agent','Fear Less'),
('Mens rogaine Minoxidil Unscented Formula','minoxidil','AEROSOL, FOAM','MINOXIDIL 50 mg/g','Topique','Kenvue Brands LLC','US','Arteriolar Vasodilator','Mens rogaine Minoxidil Unscented Formula'),
('Neosporin Plus Pain Relief Clubtray','bacitracin zinc, neomycin sulfate, polymyxin b sulfate, and pramoxine hydrochloride','Kit',NULL,NULL,'Kenvue Brands LLC','INT',NULL,'Neosporin Plus Pain Relief Clubtray'),
('Leader Chest Congestion Relief DM','dextromethorphan hydrobromide / guaifenesin','Comprimé','DEXTROMETHORPHAN HYDROBROMIDE 20 mg/1','Orale','Cardinal Health','INT','Expectorant','Leader Chest Congestion Relief DM'),
('leader anti diarrheal','loperamide hcl','Comprimé','LOPERAMIDE HYDROCHLORIDE 2 mg/1','Orale','Cardinal Health 110, LLC. dba Leader','US','Opioid Agonist','leader anti diarrheal'),
('Smart Care TROPICAL MANGO HAND SANITIZER','ethyl alcohol','Spray','ALCOHOL 70 mL/100mL','Topique','Ashtel Studios, Inc.','INT','Médicaments topiques','Smart Care TROPICAL MANGO HAND SANITIZER'),
('Neomycin Sulfate','neomycin sulfate','Comprimé','NEOMYCIN SULFATE 500 mg/1','Orale','REMEDYREPACK INC.','US','Aminoglycoside Antibacterial','Neomycin Sulfate'),
('MAXIMUM STRENGTH ANTACID ANTIGAS','aluminum hydroxide, magnesium hydroxide, dimethicone','Suspension','ALUMINUM HYDROXIDE 400 mg/5mL','Orale','STRATEGIC SOURCING SERVICES LLC','INT','Calculi Dissolution Agent','MAXIMUM STRENGTH ANTACID ANTIGAS'),
('GOOD REMEDIES Nighttime Sleep Aid Caplets','diphenhydramine hydrochloride','Comprimé','DIPHENHYDRAMINE HYDROCHLORIDE 25 mg/1','Orale','Strive Pharmaceuticals Inc.','INT','Histamine-1 Receptor Antagonist','GOOD REMEDIES Nighttime Sleep Aid Caplets'),
('telmisartan and hydrochlorothiazide','telmisartan and hydrochlorothiazide','Comprimé','HYDROCHLOROTHIAZIDE 12.5 mg/1','Orale','Lifestar Pharma LLC','US','Angiotensin 2 Receptor Blocker','telmisartan and hydrochlorothiazide'),
('BORTEZOMIB','bortezomib','Solution','BORTEZOMIB 1 mg/mL','Intraveineuse','Zydus Lifesciences Limited','US','Proteasome Inhibitor','BORTEZOMIB'),
('Hydrating Face Wash','calendula','OIL','CALENDULA OFFICINALIS FLOWER 1 [hp_X]/133mL','Topique','Spry Life LLC','INT','Médicaments topiques','Hydrating Face Wash'),
('HealthWise Cold Therapy Pain Relief Patch','menthol','Patch transdermique','MENTHOL 5 g/100g','Topique','Veridian Healthcare','INT','Médicaments topiques','HealthWise Cold Therapy Pain Relief Patch'),
('In Transit Skin Defence','avobenzone, octinoxate, octocrylene, oxybenzone','Crème','AVOBENZONE 30 mg/mL','Topique','THIS WORKS PRODUCTS LIMITED','INT','Médicaments topiques','In Transit Skin Defence'),
('EVR Alcohol Prep Pads','isopropyl alcohol','Patch transdermique','ISOPROPYL ALCOHOL 70 g/100g','Topique','Taizhou Kangping Medical Science And Technology Co., Ltd.','INT','Médicaments topiques','EVR Alcohol Prep Pads'),
('Freeman Packaging Hand Sanitizer','alcohol','LIQUID','ALCOHOL 62 mL/100mL','Topique','JIANGMEN SHUIZIRUN SANITARY ARTICLES CO., LTD.','INT','Médicaments topiques','Freeman Packaging Hand Sanitizer'),
('Eyeleve MGD','mineral oil','EMULSION','LIGHT MINERAL OIL 2 mg/.4mL','Ophtalmique','Bruder Healthcare','INT','Ophtalmologie','Eyeleve MGD')
) AS v(nom, dci, forme, dosage, voie, labo, pays, classe, nomcom)
WHERE NOT EXISTS (
  SELECT 1 FROM medicaments m WHERE UPPER(m.nom) = UPPER(v.nom)
);
