-- ndc_batch_113.sql (80 rows)
INSERT INTO medicaments (nom, dci, forme, dosage, voie_administration, laboratoire, pays, classe_therapeutique, nom_commercial)
SELECT v.nom, v.dci, v.forme, v.dosage, v.voie, v.labo, v.pays, v.classe, v.nomcom
FROM (VALUES
('tussin','dextromethorphan hydrobromide, guaifenesin','Solution','DEXTROMETHORPHAN HYDROBROMIDE 20 mg/20mL','Orale','H E B','INT','Expectorant','tussin'),
('Crataegus oxyacantha','hawthorn leaf with flower','PELLET','HAWTHORN LEAF WITH FLOWER 200 [kp_C]/200[kp_C]','Orale','Boiron','INT',NULL,'Crataegus oxyacantha'),
('fluorometholone ophthalmic suspension','fluorometholone','Suspension','FLUOROMETHOLONE 1 mg/mL','Ophtalmique','Amneal Pharmaceuticals NY LLC','US','Corticosteroid','fluorometholone ophthalmic suspension'),
('Arnicare Procedure Recovery','arnica montana','Kit',NULL,'Orale','Laboratoires Boiron','INT',NULL,'Arnicare Procedure Recovery'),
('DermaClear BHA Spot Treatment','salicylic acid','Gel','SALICYLIC ACID 2 mg/g','Topique','Allure Labs','INT','Médicaments topiques','DermaClear BHA Spot Treatment'),
('LIGUSTRUM VULGARE POLLEN','privet','Solution','LIGUSTRUM VULGARE POLLEN .1 g/mL','Sous-cutanée','ALK-Abello, Inc.','US','Non-Standardized Pollen Allergenic Extract','LIGUSTRUM VULGARE POLLEN'),
('Thymus Drops 5027','thymus drops','LIQUID','AMARYLLIS BELLADONNA WHOLE 6 [hp_X]/59mL','Orale','Professional Complementary Health Formulas','INT','Blood Coagulation Factor','Thymus Drops 5027'),
('ATTITUDE Sunly Mineral Sunscreen Stick Orange Blossom SPF 30','zinc oxide','STICK','ZINC OXIDE 20 g/100g','Topique','9055-7588 Quebec Inc. DBA Attitude','INT','Médicaments topiques','ATTITUDE Sunly Mineral Sunscreen Stick Orange Blossom SPF 30'),
('Dior Forever Skin Wear Flawless Skin True Foundation SPF 20 2WO Warm Olive','octisalate, titanium dioxide','EMULSION','OCTISALATE 35 mg/mL','Topique','Parfums Christian Dior','INT','Médicaments topiques','Dior Forever Skin Wear Flawless Skin True Foundation SPF 20 2WO Warm Olive'),
('Doxycycline Monohydrate','doxycycline monohydrate','Gélule','DOXYCYCLINE 50 mg/1','Orale','Chartwell RX, LLC.','US','Tetracycline-class Drug','Doxycycline Monohydrate'),
('Sani-Spritz','alcohol','LIQUID','ALCOHOL .7 mL/mL','Topique','ABC Compounding Co., Inc.','INT','Médicaments topiques','Sani-Spritz'),
('Anti Bacterial Hand Gel Raspberries and Whipped Vanilla','alcohol','Gel','ALCOHOL 71 mL/100mL','Topique','Bath & Body Works, Inc.','INT','Médicaments topiques','Anti Bacterial Hand Gel Raspberries and Whipped Vanilla'),
('Opium Tincture Deodorized','morphine tincture','Solution','MORPHINE 10 g/1000mL','Orale','Bryant Ranch Prepack','INT','Opioid Agonist','Opium Tincture Deodorized'),
('Urinary Nosode Combination 9410','urinary nosode combination','LIQUID','BERBERIS VULGARIS ROOT BARK 10 [hp_X]/29.5mL','Orale','Professional Complementary Health Formulas','INT',NULL,'Urinary Nosode Combination 9410'),
('Fludarabine','fludarabine phosphate','Solution','FLUDARABINE PHOSPHATE 25 mg/mL','Intraveineuse','Fresenius Kabi USA, LLC','US','Nucleoside Metabolic Inhibitor','Fludarabine'),
('Banana Boat Sport Ultra Sunscreen Broad Spectrum SPF 65','avobenzone,homosalate,octisalate,octocrylene','Lotion','AVOBENZONE 2.7 g/100g','Topique','Edgewell Personal Care Brands LLC','INT','Médicaments topiques','Banana Boat Sport Ultra Sunscreen Broad Spectrum SPF 65'),
('R20 TESTOGEN','adenosine triphosphate, arsenicum album, levothyroxine, natrum sulphuricum, phosphorus, ruta graveolens','Solution','ADENOSINE TRIPHOSPHATE 5 [hp_X]/mL','Sublinguale','Apex Energetics Inc.','INT','Osmotic Laxative','R20 TESTOGEN'),
('RUBY-FILL','rubidium rb 82','Solution','RUBIDIUM CHLORIDE RB-82 100 mCi/1','Intraveineuse','Jubilant DraxImage Inc., dba Jubilant Radiopharma','US','Radioactive Diagnostic Agent','RUBY-FILL'),
('StingX','benzocaine','SWAB','BENZOCAINE 6 g/100mL','Topique','CoreTex Products Inc','INT','Standardized Chemical Allergen','StingX'),
('HARMON DAILY MOISTURZIER','dimethicone','Lotion','DIMETHICONE 13 mg/mL','Topique','HARMON STORES, INC.','INT','Skin Barrier Activity','HARMON DAILY MOISTURZIER'),
('kirkland signature minoxidil','minoxidil','Solution','MINOXIDIL 5 g/100mL','Topique','Costco Wholesale Company','US','Arteriolar Vasodilator','kirkland signature minoxidil'),
('Monistat 1 Combination Pack','miconazole nitrate','Kit',NULL,NULL,'Insight Pharmaceuticals LLC','US',NULL,'Monistat 1 Combination Pack'),
('QC Burn Relief Aloe','lidocaine hcl','Gel','LIDOCAINE HYDROCHLORIDE .5 g/100g','Topique','Chain Drug Marketing Association Inc','INT','Amide Local Anesthetic','QC Burn Relief Aloe'),
('Sweep','detoxifying','LIQUID','ACTIVATED CHARCOAL 10 [hp_X]/mL','Orale','Vitality Works, Inc.','INT',NULL,'Sweep'),
('Kalliga','desogestrel and ethinyl estradiol','Kit',NULL,NULL,'Aurobindo Pharma Limited','US',NULL,'Kalliga'),
('Emvita 7','anacard occ, glandula sup, lachesis mutus, lycopodium, phosphorus','LIQUID','ANACARDIUM OCCIDENTALE FRUIT 18 [hp_M]/60mL','Orale','RUBIMED AG','INT',NULL,'Emvita 7'),
('Nighttime Sleep Aid, 24-7 Life BY 7-ELEVEN, 6oz','diphenhydramine hcl solution','Solution','DIPHENHYDRAMINE HYDROCHLORIDE 50 mg/30mL','Orale','Lil'' Drug Store Products, Inc.','INT','Histamine-1 Receptor Antagonist','Nighttime Sleep Aid, 24-7 Life BY 7-ELEVEN, 6oz'),
('Severe Congestion Nasal Anti-Drip Nasal Decongestant','oxymetazoline hydrochloride','Spray','OXYMETAZOLINE HYDROCHLORIDE .05 g/100mL','Nasale','WinCo FOODS, LLC','INT','Vasoconstrictor','Severe Congestion Nasal Anti-Drip Nasal Decongestant'),
('AGE20S SIGNATURE ESSENCE PACT INTENSE COVER MINI 27W','octinoxate, octocrylene, titanium dioxide','Crème','OCTINOXATE .26 g/4g','Topique','Aekyung Industrial Co., Ltd.','INT','Médicaments topiques','AGE20S SIGNATURE ESSENCE PACT INTENSE COVER MINI 27W'),
('Dr Sheffield Muscle Rub Cream','muscle rub cream','Crème','MENTHOL 100 mg/g','Topique','NuCare Pharmaceuticals,Inc.','INT','Médicaments topiques','Dr Sheffield Muscle Rub Cream'),
('ALYACEN 7/7/7','norethindrone and ethinyl estradiol','Kit',NULL,NULL,'Glenmark Pharmaceuticals Inc., USA','US',NULL,'ALYACEN 7/7/7'),
('McKesson Ibuprofen 200 mg','ibuprofen','Comprimé','IBUPROFEN 200 mg/1','Orale','McKesson Medical-Surgical','US','Nonsteroidal Anti-inflammatory Drug','McKesson Ibuprofen 200 mg'),
('PCA Gel','salicylic acid','Gel','SALICYLIC ACID 2 g/100mL','Topique','CP Skin Health Group, Inc','INT','Médicaments topiques','PCA Gel'),
('DRx Choice Sore Throat Menthol Flavor','phenol','Spray','PHENOL 1.4 g/100mL','Orale','RARITAN PHARMACEUTICALS INC','INT',NULL,'DRx Choice Sore Throat Menthol Flavor'),
('NuLev','hyoscyamine sulfate','Comprimé','HYOSCYAMINE SULFATE .125 mg/1','Orale','Viatris Specialty LLC','INT',NULL,'NuLev'),
('good sense pain relief','acetaminophen','Comprimé','ACETAMINOPHEN 325 mg/1','Orale','Preferred Pharmaceuticals Inc.','INT',NULL,'good sense pain relief'),
('Walgreens Daily Acne Cleanser- Sensitive Skin Formula','benzoyl peroxide','Lotion','BENZOYL PEROXIDE 50 mg/mL','Topique','Walgreen Company','INT','Médicaments topiques','Walgreens Daily Acne Cleanser- Sensitive Skin Formula'),
('WALGREENS NIGHTTIME ALLERGY RELIEF','doxylamine succinate','LIQUID','DOXYLAMINE SUCCINATE 6.25 mg/15mL','Orale','WALGREENS CO.','INT','Antihistamine','WALGREENS NIGHTTIME ALLERGY RELIEF'),
('ETHACRYNATE SODIUM','ethacrynate sodium','Solution','ETHACRYNATE SODIUM 50 mg/50mL','Intraveineuse','Leading Pharma, LLC','US','Loop Diuretic','ETHACRYNATE SODIUM'),
('First Aid Beauty FAB Ultra Repair Skin Protectant','colloidal oatmeal','Crème','OATMEAL .5 g/100g','Topique','The Procter & Gamble Manufacturing Company','INT','Non-Standardized Food Allergenic Extract','First Aid Beauty FAB Ultra Repair Skin Protectant'),
('Pepto Bismol Ultra','bismuth subsalicylate','Suspension','BISMUTH SUBSALICYLATE 525 mg/15mL','Orale','The Procter & Gamble Manufacturing Company','INT',NULL,'Pepto Bismol Ultra'),
('mild iodine tincture','iodine and sodium iodide and alcohol','LIQUID','ALCOHOL 470 mg/mL','Topique','BIONPHARMA INC.','INT','Médicaments topiques','mild iodine tincture'),
('adult tussin dm','dextromethorphan hydrobromide, guaifenesin','Solution','DEXTROMETHORPHAN HYDROBROMIDE 20 mg/20mL','Orale','CVS Pharmacy','INT','Expectorant','adult tussin dm'),
('Thermacare Heat Therapy Max Strength Lidocaine Pain Relief Rollon','thermacare heat therapy max strength lidocaine pain relief rollon','LIQUID','BENZYL ALCOHOL 10 g/100mL','Topique','Clarion Brands LLC','INT','Amide Local Anesthetic','Thermacare Heat Therapy Max Strength Lidocaine Pain Relief Rollon'),
('ASCENIV','human immunoglobulin g','LIQUID','HUMAN IMMUNOGLOBULIN G 5 g/50mL','Intraveineuse','ADMA Biologics, Inc.','US','Human Immunoglobulin G','ASCENIV'),
('CVS Severe Tussin CF Max','acetaminophen, dextromethorphan hbr','Solution','ACETAMINOPHEN 650 mg/20mL','Orale','CVS PHARMACY','INT','Sigma-1 Agonist','CVS Severe Tussin CF Max'),
('Neutrogena All in 1 Acne Control Daily Scrub','salicylic acid','LIQUID','SALICYLIC ACID 20 mg/mL','Topique','Kenvue Brands LLC','INT','Médicaments topiques','Neutrogena All in 1 Acne Control Daily Scrub'),
('Neutrogena Ultra Sheer Face Serum Sunscreen Broad Spectrum SPF 60','avobenzone, homosalate, octisalate, and octocrylene','Lotion','AVOBENZONE 30 mg/mL','Topique','Kenvue Brands LLC','INT','Médicaments topiques','Neutrogena Ultra Sheer Face Serum Sunscreen Broad Spectrum SPF 60'),
('YUSIMRY','adalimumab-aqvh','Solution','ADALIMUMAB 40 mg/.8mL','Sous-cutanée','Coherus BioSciences Inc','US','Tumor Necrosis Factor Blocker','YUSIMRY'),
('CHARLOTTE TILBURY Broad Spectrum SPF 50 Sunscreen Invisible UV Flawless Poreless Primer','avobenzone, octinoxate, octisalate and octocrylene','Crème','AVOBENZONE .918 g/30mL','Topique','Charlotte Tilbury Beauty Ltd.','INT','Médicaments topiques','CHARLOTTE TILBURY Broad Spectrum SPF 50 Sunscreen Invisible UV Flawless Poreless Primer'),
('Lice Ladies Defend Conditioner','sabadilla','LIQUID','SCHOENOCAULON OFFICINALE SEED 6 [hp_X]/mL','Topique','Lice Ladies Atlanta, LLC','INT','Médicaments topiques','Lice Ladies Defend Conditioner'),
('Motion Sickness','dimenhydrinate','Comprimé','DIMENHYDRINATE 50 mg/1','Orale','Strategic Sourcing Services LLC','INT','Histamine-1 Receptor Antagonist','Motion Sickness'),
('RIGHT REMEDIES OVERNIGHT Laxative','bisacodyl','Comprimé','BISACODYL 5 mg/1','Orale','Strive Pharmaceuticals Inc.','INT','Stimulant Laxative','RIGHT REMEDIES OVERNIGHT Laxative'),
('ZOLADEX','goserelin','Implant','GOSERELIN ACETATE 3.6 mg/1','Sous-cutanée','TerSera Therapeutics LLC','US','Gonadotropin Releasing Hormone Receptor Agonist','ZOLADEX'),
('Touchpoint Wipes Sanitizing Wipes','benzalkonium chloride','CLOTH','BENZALKONIUM CHLORIDE 1.3 mg/1','CUTANEOUS','Innocore Sales & Marketing Inc','INT',NULL,'Touchpoint Wipes Sanitizing Wipes'),
('FRUDIA Blueberry Hydrating Air Fit Sunscreen','octocrylene, homosalate, octisalate, avobenzone','Crème','AVOBENZONE 27 mg/g','Topique','WELCOS CO.,LTD.','INT','Médicaments topiques','FRUDIA Blueberry Hydrating Air Fit Sunscreen'),
('Mommys Bliss Childrens Pain and Fever','acetaminophen','Suspension','ACETAMINOPHEN 160 mg/5mL','Orale','Mom Enterprises, LLC.','INT',NULL,'Mommys Bliss Childrens Pain and Fever'),
('Female Vitality T010','cimicifuga racemosa, fucus vesiculosus, oophorinum (suis), hypophysis suis, thyroidinum (suis), graphites, lachesis mutus, natrum muriaticum, pulsatilla (pratensis), sepia','LIQUID','ANEMONE PRATENSIS 12 [hp_X]/mL','Orale','Guangzhou Renuma Medical Systems Co., Ltd','INT',NULL,'Female Vitality T010'),
('Indium In 111 Oxyquinoline','indium in-111 oxyquinoline','LIQUID','INDIUM IN-111 OXYQUINOLINE 1 mCi/mL','Intraveineuse','BWXT Medical Ltd.','US','Médicaments IV / Hospitaliers','Indium In 111 Oxyquinoline'),
('Salsalate','salsalate','Comprimé','SALSALATE 750 mg/1','Orale','Bryant Ranch Prepack','INT',NULL,'Salsalate'),
('Cough Drops Dollar General Assorted Flavors 80ct','menthol','Pastille','MENTHOL 2.8 mg/1','Orale','Dollar General','INT',NULL,'Cough Drops Dollar General Assorted Flavors 80ct'),
('LMR Plus','lidocaine','Kit',NULL,NULL,'V2 Pharma, LLC','INT',NULL,'LMR Plus'),
('ANTIPERSPIRANT ABOVE DERMACLINICAL MEN','antiperspirant above dermaclinical men','Spray','ALUMINUM SESQUICHLOROHYDRATE 16 g/100g','Topique','BASTON INDUSTRIA DE AEROSSOIS LTDA','INT','Médicaments topiques','ANTIPERSPIRANT ABOVE DERMACLINICAL MEN'),
('Tolnaftate Antifungal Powder','tolnaftate','Poudre','TOLNAFTATE 1 g/100g','Topique','SCHOLL''S WELLNESS COMPANY LLC','INT','Médicaments topiques','Tolnaftate Antifungal Powder'),
('THE SKINHOUSE BLACK SNAIL WRINKLE','adenosine','Crème','ADENOSINE .02 g/50mL','Topique','NOKSIBCHO cosmetic Co., Ltd.','INT','Adenosine Receptor Agonist','THE SKINHOUSE BLACK SNAIL WRINKLE'),
('PROCYSBI','cysteamine bitartrate','Gélule','CYSTEAMINE BITARTRATE 25 mg/1','Orale','Horizon Therapeutics USA, Inc.','US','Cystine Depleting Agent','PROCYSBI'),
('topcare sleep aid','doxylamine succinate','Comprimé','DOXYLAMINE SUCCINATE 25 mg/1','Orale','Topco Associates LLC','US','Antihistamine','topcare sleep aid'),
('Inveltys','loteprednol etabonate','Suspension','LOTEPREDNOL ETABONATE 10 mg/mL','Ophtalmique','Alcon Laboratories, Inc.','US','Corticosteroid','Inveltys'),
('e.l.f. Camo CC Cream SPF 30 Deep 500 W','homosalate, octisalate, octocrylene, zinc oxide','Crème','HOMOSALATE 50 mg/g','Topique','e.l.f. Cosmetics, Inc.','INT','Médicaments topiques','e.l.f. Camo CC Cream SPF 30 Deep 500 W'),
('MLK F4 Kit','triamcinolone acetonide, lidocaine hydrochloride, bupivacaine hydrochloride, povidine iodine','Kit',NULL,'Épidurale','Asclemed USA, Inc.','INT',NULL,'MLK F4 Kit'),
('Vacation Lip Trips Desserts Bananas Foster','avobenzone, homosalate, octisalate, and octocrylene','STICK','AVOBENZONE .03 g/g','Topique','Vacation Inc.','INT','Médicaments topiques','Vacation Lip Trips Desserts Bananas Foster'),
('Spiriva Respimat','tiotropium bromide inhalation spray','Spray','TIOTROPIUM BROMIDE ANHYDROUS 1.562 ug/1','Inhalation','Boehringer Ingelheim Pharmaceuticals, Inc.','US','Anticholinergic','Spiriva Respimat'),
('Caring mill Lidocaine Aloe Gel Burn and Pain Relief','lidocaine hydrochloride','LIQUID','LIDOCAINE HYDROCHLORIDE 5 mg/mL','Topique','FSA Store Inc.','INT','Amide Local Anesthetic','Caring mill Lidocaine Aloe Gel Burn and Pain Relief'),
('OPS INSTANT HAND SANITIZER','benzalkonium chloride','Gel','BENZALKONIUM CHLORIDE .1 g/100mL','Topique','Archer Manufacturing, Inc.','INT','Médicaments topiques','OPS INSTANT HAND SANITIZER'),
('Equate Olopatadine Hydrochloride Ophthalmic Solution','olopatadine hydrochloride ophthalmic solution','Solution','OLOPATADINE HYDROCHLORIDE 1 mg/mL','Ophtalmique','WAL-MART STORES, INC.,','US','Histamine-1 Receptor Antagonist','Equate Olopatadine Hydrochloride Ophthalmic Solution'),
('Hand Sanitizer gel','alcohol','Gel','ALCOHOL 70 mL/100mL','Topique','EverywhereAire LLC','INT','Médicaments topiques','Hand Sanitizer gel'),
('Ketorocaine LM Kit','ketorolac tromethamine, lidocaine hydrochloride, bupivacaine hydrochloride, povidine iodine','Kit',NULL,'Épidurale','Advanced Rx Pharmacy of Tennessee, LLC','INT',NULL,'Ketorocaine LM Kit'),
('La Roche Posay Laboratoire Dermatologique ANTHELIOS UVPRO SPORT INVISIBLE SUNSCREEN BROAD SPECTRUM SPF 45','avobenzone, homosalate, octisalate, and octocrylene','Spray','AVOBENZONE 30 mg/g','Topique','L''Oreal USA, Inc.','INT','Médicaments topiques','La Roche Posay Laboratoire Dermatologique ANTHELIOS UVPRO SPORT INVISIBLE SUNSCREEN BROAD SPECTRUM SPF 45'),
('Attruby','acoramidis hydrochloride','Comprimé','ACORAMIDIS HYDROCHLORIDE 356 mg/1','Orale','BridgeBio Pharma, Inc.','US','Transthyretin Stabilizer','Attruby'),
('up and up nicotine','nicotine polacrilex','GUM, CHEWING','NICOTINE 2 mg/1','Orale','Target Corporation','US','Cholinergic Nicotinic Agonist','up and up nicotine')
) AS v(nom, dci, forme, dosage, voie, labo, pays, classe, nomcom)
WHERE NOT EXISTS (
  SELECT 1 FROM medicaments m WHERE UPPER(m.nom) = UPPER(v.nom)
);
