-- ndc_batch_051.sql (80 rows)
INSERT INTO medicaments (nom, dci, forme, dosage, voie_administration, laboratoire, pays, classe_therapeutique, nom_commercial)
SELECT v.nom, v.dci, v.forme, v.dosage, v.voie, v.labo, v.pays, v.classe, v.nomcom
FROM (VALUES
('Stomach Relief Ultra','bismuth subsalicylate','LIQUID','BISMUTH SUBSALICYLATE 525 mg/15mL','Orale','Dolgencorp, Inc. (DOLLAR GENERAL & REXALL)','INT','Bismuth','Stomach Relief Ultra'),
('N-8','silicon dioxide, atropa belladonna, citrullus colocynthis fruit pulp, black cohosh, anemone pulsatilla, sepia officinalis juice, palladium, apis mellifera, and bos taurus ovary','Solution','ANEMONE PULSATILLA 6 [hp_X]/mL','Sublinguale','DNA Labs, Inc.','INT','Standardized Insect Venom Allergenic Extract','N-8'),
('H-Arthritis Formula','apium graveolens, arnica montana','OIL','ARNICA MONTANA 12 [hp_C]/11mL','Topique','Healing Natural Oils LLC','INT','Médicaments topiques','H-Arthritis Formula'),
('Etyqa','estradiol and norethindrone acetate','Comprimé','ESTRADIOL 1 mg/1','Orale','Aurobindo Pharma Limited','US','Estrogen','Etyqa'),
('CVS Motion Sickness Fast Melting','meclizine hydrochloride','Comprimé','MECLIZINE HYDROCHLORIDE 25 mg/1','Orale','CVS Pharmacy, Inc.','INT','Antiemetic','CVS Motion Sickness Fast Melting'),
('HemCalm','horse chestnut, hamamelis virginiana root bark/stem bark, paeonia officinalis root, krameria lappacea root','Suppositoire','HAMAMELIS VIRGINIANA ROOT BARK/STEM BARK 2 [hp_X]/1','Rectale','Boiron','INT',NULL,'HemCalm'),
('Light Tint Clear Zinc Solar Protection SPF 30','zinc oxide','Crème','ZINC OXIDE 170 mg/g','Topique','Allure Labs, Inc','INT','Copper Absorption Inhibitor','Light Tint Clear Zinc Solar Protection SPF 30'),
('T-Relief','achillea millefolium, hypericum perforatum, hamamelis virginiana root bark/stem bark, echinacea, unspecified, matricaria recutita, atropa belladonna,comfrey root, aconitum napellus, bellis perennis,arnica montana, and ruta graveolens flowering top','Pommade','ACHILLEA MILLEFOLIUM 2 [hp_X]/g','Topique','MediNatura Inc','INT','Médicaments topiques','T-Relief'),
('Anti-Smoking II Drops 2008','anti-smoking ii drops','LIQUID','BEEF KIDNEY 6 [hp_X]/59mL','Orale','Professional Complementary Health Formulas','INT','Cholinergic Nicotinic Agonist','Anti-Smoking II Drops 2008'),
('Female Endocrine Axis Drops 5005','female endocrine axis drops','LIQUID','ALETRIS FARINOSA ROOT 4 [hp_X]/59mL','Orale','Professional Complementary Health Formulas','INT',NULL,'Female Endocrine Axis Drops 5005'),
('Para Solve','calc carb, chenopodium anth, cina, croton, filix mas, gambocia, granatum, lycopodium, merc corros, nat phos, santoninum, senna, spigelia anth, stannum met, tanacetum, teuricum mar, zingiber','LIQUID','ARTEMISIA CINA PRE-FLOWERING TOP 12 [hp_X]/59.1mL','Orale','NET Remedies','INT','Non-Standardized Food Allergenic Extract','Para Solve'),
('NITROFURANTOIN MONOHYDRATE MACROCRYSTALLINE','nitrofurantoin monohydrate','Gélule','NITROFURANTOIN 25 mg/1','Orale','Direct_Rx','US','Nitrofuran Antibacterial','NITROFURANTOIN MONOHYDRATE MACROCRYSTALLINE'),
('Dior Forever Skin Glow Flawless Radiant Skin True Foundation SPF 25 9N Neutral','octisalate, titanium dioxide','EMULSION','OCTISALATE 45 mg/mL','Topique','Parfums Christian Dior','INT','Médicaments topiques','Dior Forever Skin Glow Flawless Radiant Skin True Foundation SPF 25 9N Neutral'),
('Fruit of the Earth LUV THAT SUN Sport Sunscreen Continuous SPF 50','avobenzone, homosalate, octisalate, octocrylene','Spray','AVOBENZONE 30 mg/g','Topique','FRUIT OF THE EARTH, INC.','INT','Médicaments topiques','Fruit of the Earth LUV THAT SUN Sport Sunscreen Continuous SPF 50'),
('Anti-BacterialHandSpray Sun Washed Citrus','alcohol','Spray','ALCOHOL 72 mL/100mL','Topique','Bath & Body Works, Inc.','INT','Médicaments topiques','Anti-BacterialHandSpray Sun Washed Citrus'),
('Bisoprolol Fumarate','bisoprolol fumarate','Comprimé','BISOPROLOL FUMARATE 5 mg/1','Orale','Bryant Ranch Prepack','US','beta-Adrenergic Blocker','Bisoprolol Fumarate'),
('MORELLA CERIFERA POLLEN','bayberry wax myrtle','Solution','MORELLA CERIFERA POLLEN .05 g/mL','PERCUTANEOUS','ALK-Abello, Inc.','US','Non-Standardized Pollen Allergenic Extract','MORELLA CERIFERA POLLEN'),
('CRAB','paralithodes camtschaticus','Solution','RED KING CRAB .1 g/mL','PERCUTANEOUS','ALK-Abello, Inc.','US',NULL,'CRAB'),
('Robitussin Sugar-Free Dye-Free Cough Plus Chest Congestion DM','dextromethorphan hydrobromide, guaifenesin','Solution','DEXTROMETHORPHAN HYDROBROMIDE 20 mg/20mL','Orale','Haleon US Holdings LLC','INT','Expectorant','Robitussin Sugar-Free Dye-Free Cough Plus Chest Congestion DM'),
('Floxuridine','floxuridine','Solution','FLOXURIDINE 500 mg/5mL','INTRA-ARTERIAL','Fresenius Kabi USA, LLC','US','Antimetabolite','Floxuridine'),
('G16 ELECTRO-MET','adenosine triphosphate, antimony potassium tartrate, cinchona officinalis bark, strychnos nux-vomica seed, phosphoric acid, sulfur','Solution','ADENOSINE TRIPHOSPHATE 6 [hp_X]/mL','Sublinguale','Apex Energetics Inc.','INT','Non-Standardized Plant Allergenic Extract','G16 ELECTRO-MET'),
('Baryta Muriatica','baryta muriatica','PELLET','BARIUM CHLORIDE DIHYDRATE 6 [hp_C]/1','Orale','Hahnemann Laboratories, INC','INT',NULL,'Baryta Muriatica'),
('Broad Spectrum SPF 15 Sunscreen Unflavored Lip Balm','broad spectrum spf 15 sunscreen unflavored lip balm','STICK','AVOBENZONE .13 g/4.25g','Topique','Raining Rose','INT','Médicaments topiques','Broad Spectrum SPF 15 Sunscreen Unflavored Lip Balm'),
('Stopain Clinical','menthol, unspecified form','Gel','MENTHOL, UNSPECIFIED FORM 100 mg/g','Topique','Troy Manufacturing, Inc.','INT','Médicaments topiques','Stopain Clinical'),
('Category I','immune system booster','LIQUID','ACTAEA SPICATA ROOT 6 [hp_X]/mL','Orale','Vitality Works, Inc','INT','Non-Standardized Fungal Allergenic Extract','Category I'),
('Dove Clinical Protection Cool Essentials Antiperspirant and Deodorant','aluminum zirconium tetrachlorohydrex gly','STICK','ALUMINUM ZIRCONIUM TETRACHLOROHYDREX GLY 20 g/100g','Topique','Conopco Inc. d/b/a Unilever','INT','Médicaments topiques','Dove Clinical Protection Cool Essentials Antiperspirant and Deodorant'),
('bhs beautiful hair and scalp','vibrant color with rose essence anti-dandruff conditioner','LIQUID','SALICYLIC ACID 2 g/100mL','Topique','Conopco, Inc. d/b/a/ Unilever','INT','Médicaments topiques','bhs beautiful hair and scalp'),
('UNASYN','ampicillin sodium and sulbactam sodium','Solution','AMPICILLIN SODIUM 2 g/1','Intramusculaire','Roerig','US','Penicillin-class Antibacterial','UNASYN'),
('ALMAY SMART SHADE ANTI-AGING SKINTONE MATCHING MAKEUP SPF 20 Light','titanium dioxide, zinc oxide','LIQUID','TITANIUM DIOXIDE 5.5 mg/mL','Topique','Almay, Inc.','INT','Copper Absorption Inhibitor','ALMAY SMART SHADE ANTI-AGING SKINTONE MATCHING MAKEUP SPF 20 Light'),
('PanOxyl','adapalene','Gel','ADAPALENE 1 mg/g','Topique','CROWN LABORATORIES','US','Retinoid','PanOxyl'),
('Psychotria Ipecacuanha MT','psychotria ipecacuanha','TINCTURE','CARAPICHEA IPECACUANHA WHOLE 1 [hp_X]/.25L','Orale','OHM PHARMA INC.','INT',NULL,'Psychotria Ipecacuanha MT'),
('Zantac 360, Travel BASIX','famotidine tablet, film-coated','Comprimé','FAMOTIDINE 20 mg/1','Orale','Lil'' Drug Store Products, Inc','US','Histamine-2 Receptor Antagonist','Zantac 360, Travel BASIX'),
('Sevoflurane','sevoflurane','LIQUID','SEVOFLURANE 1 mL/mL','Inhalation','Piramal Critical Care Inc','US','General Anesthetic','Sevoflurane'),
('Natural Extensions Antibacterial Foaming Hand','benzalkonium chloride','SOAP','BENZALKONIUM CHLORIDE 1 mg/mL','Topique','Benco Dental','INT','Médicaments topiques','Natural Extensions Antibacterial Foaming Hand'),
('Winco Advanced Relief Eye Drops','dextran 70, polyethylene glycol 400, povidone, tetrahydrozoline hcl','Solution','DEXTRAN 70 100 mg/100mL','Ophtalmique','WinCo Foods, LLC','INT','Plasma Volume Expander','Winco Advanced Relief Eye Drops'),
('AGE20S SIGNATURE ESSENCE PACT INTENSE COVER 31N','octinoxate, octocrylene, titanium dioxide','Crème','OCTINOXATE .91 g/14g','Topique','Aekyung Industrial Co., Ltd.','INT','Médicaments topiques','AGE20S SIGNATURE ESSENCE PACT INTENSE COVER 31N'),
('BUPRENORPHINE HYDROCHLORIDE and NALOXONE HYDROCHLORIDE DIHYDRATE','buprenorphine hydrochloride and naloxone hydrochloride dihydrate','Comprimé','BUPRENORPHINE HYDROCHLORIDE 8 mg/1','Sublinguale','Redpharm Drug','US','Opioid Antagonist','BUPRENORPHINE HYDROCHLORIDE and NALOXONE HYDROCHLORIDE DIHYDRATE'),
('Resinol','petrolatum and resorcinol','Pommade','PETROLATUM 55 g/100g','Topique','ResiCal, Inc.','INT','Médicaments topiques','Resinol'),
('Cough and Cold Nighttime','acetaminophen diphenhydramine hci phenylephrine hci','LIQUID','ACETAMINOPHEN 650 mg/20mL','Orale','Walgreens','INT','Histamine-1 Receptor Antagonist','Cough and Cold Nighttime'),
('Maximum Strength Hydrocortisone Cream with Aloe','hydrocortisone cream','Crème','HYDROCORTISONE 1 g/100g','Topique','Walgreens','INT','Corticosteroid','Maximum Strength Hydrocortisone Cream with Aloe'),
('Aspirin 325','aspirin','Comprimé','ASPIRIN 325 mg/1','Orale','Walgreen Company','INT','Nonsteroidal Anti-inflammatory Drug','Aspirin 325'),
('Tru Skin Rituals SPF 25','titanium dioxide, zinc oxide','Spray','TITANIUM DIOXIDE 8.16 mg/170mL','Topique','Spa de Soleil','INT','Médicaments topiques','Tru Skin Rituals SPF 25'),
('Profilnine','factor ix complex','Kit',NULL,'Intraveineuse','GRIFOLS USA, LLC','US','Médicaments IV / Hospitaliers','Profilnine'),
('McKesson Loradatine','loratainde','Comprimé','LORATADINE 10 mg/1','Orale','McKesson Medical Surgical','US',NULL,'McKesson Loradatine'),
('Triple Complex Sleep Tonic','calc phos, clac sulph, mag phos','LIQUID','CALCIUM PHOSPHATE 8 [hp_X]/59mL','Orale','Silver Star Brands','INT','Blood Coagulation Factor','Triple Complex Sleep Tonic'),
('VOXZOGO 0.56mg','vosoritide','Kit',NULL,NULL,'BioMarin Pharmaceutical Inc.','US',NULL,'VOXZOGO 0.56mg'),
('Polymyxin B Sulfate and Trimethoprim','polymyxin b sulfate and trimethoprim sulfate','Solution','POLYMYXIN B SULFATE 10000 [USP''U]/mL','Ophtalmique','Preferred Pharmaceuticals Inc.','US','Dihydrofolate Reductase Inhibitor Antibacterial','Polymyxin B Sulfate and Trimethoprim'),
('Always Liquid Foundation Makeup Sunscreen Broad Spectrum SPF 15 - Soft Ivory','homosalate, octisalate, zinc oxide','LIQUID','HOMOSALATE 4.25 g/100mL','Topique','Distribuidora Comercial Jafra, S.A. de C.V','INT','Médicaments topiques','Always Liquid Foundation Makeup Sunscreen Broad Spectrum SPF 15 - Soft Ivory'),
('Sun Bum 50 Premium Moisturizing Sunscreen','avobenzone, homosalate, octisalate, octocrylene','Lotion','AVOBENZONE 30 mg/mL','Topique','Sun Bum, LLC','INT','Médicaments topiques','Sun Bum 50 Premium Moisturizing Sunscreen'),
('Walgreen Daytimel Kids Cold Cough plus Mucus','guaifenesin, phenylephrine hydrochloride and dextromethorphan hydrobromide','LIQUID','DEXTROMETHORPHAN HYDROBROMIDE 10 mg/15mL','Orale','WALGREENS CO.','INT','Expectorant','Walgreen Daytimel Kids Cold Cough plus Mucus'),
('WalgreenChildrens Pain Fever','acetaminophen','Suspension','ACETAMINOPHEN 160 mg/5mL','Orale','WALGREENS CO.','INT',NULL,'WalgreenChildrens Pain Fever'),
('Lidocaine Hydrochloride and Hydrocortisone Acetate','lidocaine hydrochloride and hydrocortisone acetate','Crème','HYDROCORTISONE ACETATE 5 mg/g','Topique','Westminster Pharmaceuticals, LLC','INT','Amide Local Anesthetic','Lidocaine Hydrochloride and Hydrocortisone Acetate'),
('Old Spice Nightpanther','aluminum zirconium tetrachlorohydrex gly','STICK','ALUMINUM ZIRCONIUM TETRACHLOROHYDREX GLY 15 g/100g','Topique','The Procter & Gamble Manufacturing Company','INT','Médicaments topiques','Old Spice Nightpanther'),
('Crest Complete plus Whitening Deep Clean','sodium fluoride','PASTE, DENTIFRICE','SODIUM FLUORIDE 1.5 mg/g','DENTAL','The Procter & Gamble Manufacturing Company','INT',NULL,'Crest Complete plus Whitening Deep Clean'),
('FifthPulse Bacitracin Zinc 4oz','bacitracin zinc','Pommade','BACITRACIN ZINC 500 [iU]/g','Topique','Front Pharmaceutical PLC','INT','Decreased Cell Wall Synthesis & Repair','FifthPulse Bacitracin Zinc 4oz'),
('CVS Health Sterile Saline Mist','sodium chloride','Spray','SODIUM CHLORIDE .9 g/100g','Nasale','CVS Pharmacy','INT',NULL,'CVS Health Sterile Saline Mist'),
('energy and motivation','calc sulph, gentiana amarella flos, kali phos, nat mur, nat phos, nat sulph, olea europea flos, phos acid, ulex europaeus flos','Spray','CALCIUM SULFATE ANHYDROUS 6 [hp_X]/29.6mL','Orale','Siddha Flower Essences LLC','INT','Blood Coagulation Factor','energy and motivation'),
('Womens Rogaine Unscented','minoxidil','AEROSOL, FOAM','MINOXIDIL 50 mg/g','Topique','Kenvue Brands LLC','US','Arteriolar Vasodilator','Womens Rogaine Unscented'),
('Aveeno Favorites','avobenzone, homosalate, octisalate, octocrylene','Kit',NULL,NULL,'Kenvue Brands LLC','INT',NULL,'Aveeno Favorites'),
('Leader Chest Congestion Relief G450','guaifenesin','Comprimé','GUAIFENESIN 400 mg/1','Orale','Cardinal Health','INT','Expectorant','Leader Chest Congestion Relief G450'),
('12HR Allergy Relief','fexofenadine hydrochloride','Comprimé','FEXOFENADINE HYDROCHLORIDE 60 mg/1','Orale','CARDINAL HEALTH','US','Histamine-1 Receptor Antagonist','12HR Allergy Relief'),
('Smart Care SEA BREEZE HAND SANITIZER','ethyl alcohol','Spray','ALCOHOL 70 mL/100mL','Topique','Ashtel Studios, Inc.','INT','Médicaments topiques','Smart Care SEA BREEZE HAND SANITIZER'),
('Bromocriptine Mesylate','bromocriptine mesylate','Gélule','BROMOCRIPTINE MESYLATE 5 mg/1','Orale','Mylan Pharmaceuticals Inc.','US','Ergot Derivative','Bromocriptine Mesylate'),
('REGULAR STRENGTH ANTACID AND ANTIGAS','aluminum hydroxide, magnesium hydroxide, dimethicone','Suspension','ALUMINUM HYDROXIDE 200 mg/5mL','Orale','STRATEGIC SOURCING SERVICES LLC','INT','Calculi Dissolution Agent','REGULAR STRENGTH ANTACID AND ANTIGAS'),
('Methenamine Hippurate','methenamine hippurate','Comprimé','METHENAMINE HIPPURATE 1 g/1','Orale','Esjay Pharma LLC','US',NULL,'Methenamine Hippurate'),
('BEIZRAY','docetaxel','Kit',NULL,NULL,'Zydus Pharmaceuticals USA Inc.','US',NULL,'BEIZRAY'),
('Animal Pain Relief','arnica, ginger, rosemary','SALVE','ARNICA MONTANA FLOWER 1 [hp_X]/17g','Topique','Spry Life LLC','INT','Médicaments topiques','Animal Pain Relief'),
('HealthWise Menstrual Pain Relief Patch','menthol','Patch transdermique','MENTHOL, UNSPECIFIED FORM 10 g/100g','Topique','Veridian Healthcare','INT','Médicaments topiques','HealthWise Menstrual Pain Relief Patch'),
('Pharbetol','acetaminophen','Comprimé','ACETAMINOPHEN 500 mg/1','Orale','Proficient Rx LP','INT',NULL,'Pharbetol'),
('Perfect Legs Skin Protector SPF 30','avobenzone, octinoxate, octocrylene','Crème','AVOBENZONE 16 mg/mL','Topique','THIS WORKS PRODUCTS LIMITED','INT','Médicaments topiques','Perfect Legs Skin Protector SPF 30'),
('Nalbuphine Hydrochloride','nalbuphine hydrochloride','Solution','NALBUPHINE HYDROCHLORIDE 10 mg/mL','Intramusculaire','Hospira, Inc.','US','Opioid Agonist/Antagonist','Nalbuphine Hydrochloride'),
('COLD and FLU RELIEF','cold and flu relief','PELLET','ACONITUM NAPELLUS 14 [hp_X]/1','Orale','Clineva Management Services, LLC','INT',NULL,'COLD and FLU RELIEF'),
('Novex Anti-Bacterial Hand Sanitizer Wipe','benzalkonium chloride','SWAB','BENZALKONIUM CHLORIDE .05 g/100g','Topique','JIANGMEN SHUIZIRUN SANITARY ARTICLES CO., LTD.','INT','Médicaments topiques','Novex Anti-Bacterial Hand Sanitizer Wipe'),
('AY BENDITO - CBD','camphor, menthol','Gel','CAMPHOR (SYNTHETIC) 6 g/100g','Topique','AY BENDITO INTERNATIONAL, INC','INT','Médicaments topiques','AY BENDITO - CBD'),
('Alkindi Sprinkle','hydrocortisone','GRANULE','HYDROCORTISONE .5 mg/1','Orale','Eton Pharmaceuticals, Inc.','US','Corticosteroid','Alkindi Sprinkle'),
('Antiseptic Mouth Rinse','eucalyptol, menthol, methyl salicylate, thymol','MOUTHWASH','EUCALYPTOL .92 mg/mL','Orale','Harris Teeter','INT',NULL,'Antiseptic Mouth Rinse'),
('Trubrexa Patch ER','trubrexa patch er','Patch transdermique','CAPSAICIN .00025 g/g','Transdermique','Direct_Rx','INT','Amide Local Anesthetic','Trubrexa Patch ER'),
('Doctor Hoys Pain Relief Gel Roll-On','menthol, camphor (synthetic)','Gel','CAMPHOR (SYNTHETIC) 50 mg/mL','Topique','Dynamic Blending Specialists, Inc.','INT','Médicaments topiques','Doctor Hoys Pain Relief Gel Roll-On'),
('Noshinku Bergamot Hand Sanitizer','alcohol','Solution','ALCOHOL 62.5 mL/100mL','Topique','Noshinku','INT','Médicaments topiques','Noshinku Bergamot Hand Sanitizer'),
('70 Alcohol Hand Sanitizer','alcohol','LIQUID','ALCOHOL 70 mL/100mL','Topique','Iron Lab SA de CV','INT','Médicaments topiques','70 Alcohol Hand Sanitizer')
) AS v(nom, dci, forme, dosage, voie, labo, pays, classe, nomcom)
WHERE NOT EXISTS (
  SELECT 1 FROM medicaments m WHERE UPPER(m.nom) = UPPER(v.nom)
);
