-- ndc_batch_072.sql (80 rows)
INSERT INTO medicaments (nom, dci, forme, dosage, voie_administration, laboratoire, pays, classe_therapeutique, nom_commercial)
SELECT v.nom, v.dci, v.forme, v.dosage, v.voie, v.labo, v.pays, v.classe, v.nomcom
FROM (VALUES
('Black gold','black gold','Poudre','SELENIUM 16 mg/1','INTRAGASTRIC','Zhongbaokang Biotechnology Co., Ltd','INT',NULL,'Black gold'),
('Tea Tree Oil Antifungal Soaps','tolnaftate','SOAP','TOLNAFTATE .7 g/70g','Topique','Nanjing Jitaxing Technology Co., LTD','INT','Médicaments topiques','Tea Tree Oil Antifungal Soaps'),
('TATTOO NUMBX NUMBING PAIN RELIEVING','lidocaine hydrochloride','Crème','LIDOCAINE HYDROCHLORIDE 40 mg/mL','Topique','Scyberco Ltd','INT','Amide Local Anesthetic','TATTOO NUMBX NUMBING PAIN RELIEVING'),
('bareMinerals BAREPRO Performance Wear Liquid Foundation Broad Spectrum SPF 20 Sandstone 16','titanium dioxide','LIQUID','TITANIUM DIOXIDE 33.2 mg/mL','Topique','Orveon Global US LLC','INT','Médicaments topiques','bareMinerals BAREPRO Performance Wear Liquid Foundation Broad Spectrum SPF 20 Sandstone 16'),
('Zinc Sulfate, Heptahydrate','zinc sulfate, heptahydrate','CRYSTAL','ZINC SULFATE HEPTAHYDRATE 1 kg/kg',NULL,'Spectrum Laboratory Products, Inc.','INT',NULL,NULL),
('Benzoyl Peroxide Powder Water Wet','benzoyl peroxide powder water wet','Poudre','BENZOYL PEROXIDE 1 kg/kg',NULL,'Corden Pharma Bergamo S.p.A.','INT',NULL,NULL),
('Doravirine and Islatravir Monohydrate','doravirine and islatravir monohydrate','Comprimé','DORAVIRINE 100 mg/1',NULL,'MSD International GmbH','INT',NULL,NULL),
('Pemetrexed Disodium Hemipentahydrate','pemetrexed disodium hemipentahydrate','Poudre','PEMETREXED DISODIUM HEMIPENTAHYDRATE 5 kg/5kg',NULL,'Emcure Pharmaceuticals Limited','INT',NULL,NULL),
('N-Acetyl-DL-Tryptophan','n-acetyl-dl-tryptophan','Poudre','N-ACETYL-DL-TRYPTOPHAN 1 kg/kg',NULL,'Ajinomoto Co., Inc.','INT',NULL,NULL),
('Major Bacitracin','bacitracin zinc','Pommade','BACITRACIN ZINC 500 [USP''U]/g','Topique','Major Pharmaceuticals','INT','Decreased Cell Wall Synthesis & Repair','Major Bacitracin'),
('Adagrasib','adagrasib','Comprimé','ADAGRASIB 200 mg/1',NULL,'PATHEON FRANCE S.A.S','INT',NULL,NULL),
('OCTENIDINE HYDROCHLORIDE','octenidine hydrochloride','Poudre','OCTENIDINE HYDROCHLORIDE 1 kg/kg',NULL,'DISHMAN CARBOGEN AMCIS LIMITED','INT',NULL,NULL),
('Ziprasidone Mesilate Trihydrate','ziprasidone mesilate trihydrate','Poudre','ZIPRASIDONE MESYLATE 1 kg/kg',NULL,'Chromo Laboratories India Private Limited','INT',NULL,NULL),
('Normosol-R','sodium chloride, sodium acetate anhydrous, sodium gluconate, potassium chloride, and magnesium chloride','Solution','MAGNESIUM CHLORIDE 30 mg/100mL','Intraveineuse','ICU Medical Inc.','US','Calculi Dissolution Agent','Normosol-R'),
('Abemaciclib','abemaciclib','Poudre','ABEMACICLIB 1 kg/kg',NULL,'SciAnda(Changshu) Pharmaceuticals, Ltd.','INT',NULL,NULL),
('Erlotinib Hydrochloride (Form-B)','erlotinib hydrochloride (form-b)','Poudre','ERLOTINIB HYDROCHLORIDE 1 kg/kg',NULL,'MSN Laboratories Private Limited','INT',NULL,NULL),
('Pitolisant Hydrochloride SD','pitolisant hydrochloride sd','Poudre','PITOLISANT HYDROCHLORIDE 35 kg/35kg',NULL,'NURAY CHEMICALS PRIVATE LIMITED','INT',NULL,NULL),
('Camphor (Synthetic) and Menthol','camphor (synthetic) and menthol','Pommade','CAMPHOR (SYNTHETIC) 110 mg/g',NULL,'Haw Par Healthcare Ltd.','INT',NULL,NULL),
('RISANKIZUMAB','risankizumab','Solution','RISANKIZUMAB 60 mg/mL',NULL,'Patheon Italia S.p.A.','INT',NULL,NULL),
('Tenofovir Alafenamide Hemifumarate','tenofovir alafenamide hemifumarate','Poudre','TENOFOVIR ALAFENAMIDE FUMARATE 1 kg/kg',NULL,'Hetero Labs Limited','INT',NULL,NULL),
('Magnesium Monoethylfumarate Micronized','magnesium monoethylfumarate micronized','Poudre','MAGNESIUM MONOETHYLFUMARATE 1 kg/kg',NULL,'Laboratorium Ofichem BV','INT',NULL,NULL),
('Prednisolone Sodium Phosphate','prednisolone sodium phosphate','Poudre','PREDNISOLONE SODIUM PHOSPHATE 1 g/g',NULL,'LETCO MEDICAL, LLC','INT',NULL,NULL),
('umeclidinium bromide','umeclidinium bromide','Poudre','UMECLIDINIUM BROMIDE 1 kg/kg',NULL,'Glaxo Operations UK Ltd','INT',NULL,NULL),
('CEANOTHUS AMERICANUS LEAF','ceanothus americanus leaf','LIQUID','CEANOTHUS AMERICANUS LEAF 1 [hp_X]/.001L',NULL,'Herbamed AG','INT',NULL,NULL),
('Fluvastatin Sodium','fluvastatin sodium','Poudre','FLUVASTATIN SODIUM 1 kg/kg',NULL,'Biocon Limited','INT',NULL,NULL),
('Aquaphor Original','petrolatum','Pommade','PETROLATUM 41 g/100g','Topique','Beiersdorf Inc','INT','Médicaments topiques','Aquaphor Original'),
('Esomeprazole Potassium','esomeprazole potassium','Poudre','ESOMEPRAZOLE POTASSIUM 1 kg/kg',NULL,'Alivus Life Sciences Limited','INT',NULL,NULL),
('Depakote','divalproex sodium','Comprimé','DIVALPROEX SODIUM 500 mg/1','Orale','AbbVie Inc.','US','Anti-epileptic Agent','Depakote'),
('Eluxadoline','eluxadoline','Poudre','ELUXADOLINE 1 kg/kg',NULL,'MSN Life Sciences Private Limited','INT',NULL,NULL),
('L-Threonine','l-threonine','Poudre','THREONINE 1 kg/kg',NULL,'Shanghai Ajinomoto Amino Acid Co.,Ltd.','INT',NULL,NULL),
('Dexibuprofen','dexibuprofen','Poudre','DEXIBUPROFEN 1 kg/kg',NULL,'Solara Active Pharma Sciences Limited','INT',NULL,NULL),
('ACE-031','ace-031','Poudre','RAMATERCEPT 1 g/g',NULL,'Qingdao Biopeptek Co., Ltd.','INT',NULL,NULL),
('Dehydroepiandrosterone (Micronized) (DHEA)','dehydroepiandrosterone (micronized) (dhea)','Poudre','PRASTERONE 1 kg/kg',NULL,'Pharma Source Direct, Inc.','INT',NULL,NULL),
('Physostigmine Salicylate','physostigmine salicylate','Poudre','PHYSOSTIGMINE SALICYLATE 100 g/100g',NULL,'Osauhing TBD Pharmatech','INT',NULL,NULL),
('up and up chewable aspirin','aspirin','Comprimé','ASPIRIN 81 mg/1','Orale','Target Corporation','INT','Nonsteroidal Anti-inflammatory Drug','up and up chewable aspirin'),
('Simplify White Tea LHS','benzalkonium chloride','LIQUID','BENZALKONIUM CHLORIDE 130 mg/100mL','Topique','RITE AID CORPORATION','INT','Médicaments topiques','Simplify White Tea LHS'),
('GUNA-ALLERGY T','ammonium carbonate - apis mellifera - arsenic trioxide - blatta orientalis - cupric acetate - drimia maritima bulb - epinephrine - galphimia glauca flowering top - histamine dihydrochloride - luffa operculata - manganese gluconate - onion - schoenocaulon officinale seed - sodium chloride - sus scrofa adrenal gland - sus scrofa bronchus - sus scrofa nasal mucosa -','Solution','AMMONIUM CARBONATE 30 [hp_X]/30mL','Orale','Guna spa','INT','Catecholamine','GUNA-ALLERGY T'),
('MISSHA M Perfect Cover BB SPF42 No21','octinoxate, zinc oxide, titanium dioxide','Crème','OCTINOXATE .075 g/g','Topique','Able C&C Co., Ltd.','INT','Médicaments topiques','MISSHA M Perfect Cover BB SPF42 No21'),
('CYZONE TRAX DESODORANTE ANTITRANSPIRANTE ROLL ON','aluminum sesquichlorohydrate','EMULSION','ALUMINUM SESQUICHLOROHYDRATE 132.8 mg/g','Topique','BEL STAR SA','INT','Médicaments topiques','CYZONE TRAX DESODORANTE ANTITRANSPIRANTE ROLL ON'),
('Hypromellose Eye Drops 0.7%','hypromellose eye drops 0.7%','Solution','HYPROMELLOSE 2910 (4000 MPA.S) 7 mg/mL','Topique','Aurolab','INT','Médicaments topiques','Hypromellose Eye Drops 0.7%'),
('Signature Care Sensitive Maximum Strength','potassium nitrate, sodium fluoride','PASTE, DENTIFRICE','POTASSIUM NITRATE 5 g/100g','DENTAL','Safeway','INT',NULL,'Signature Care Sensitive Maximum Strength'),
('signature care childrens ibuprofen','ibuprofen','Suspension','IBUPROFEN 100 mg/5mL','Orale','Safeway','US','Nonsteroidal Anti-inflammatory Drug','signature care childrens ibuprofen'),
('Standardized Mite Dermatophagoides pteronyssinus','dermatophagoides pteronyssinus','CONCENTRATE','DERMATOPHAGOIDES PTERONYSSINUS 5000 [AU]/mL','INTRADERMAL','Greer Laboratories, Inc.','US','Standardized Insect Allergenic Extract','Standardized Mite Dermatophagoides pteronyssinus'),
('Privet Pollen','ligustrum vulgare','Solution','LIGUSTRUM VULGARE POLLEN .05 g/mL','INTRADERMAL','Greer Laboratories, Inc.','US','Non-Standardized Pollen Allergenic Extract','Privet Pollen'),
('Pecan Pollen','carya illinoinensis','Solution','CARYA ILLINOINENSIS POLLEN .05 g/mL','INTRADERMAL','Greer Laboratories, Inc.','US','Non-Standardized Pollen Allergenic Extract','Pecan Pollen'),
('BB Broad Spectrum SPF 15 Medium','zinc oxide titanium dioxide','Crème','TITANIUM DIOXIDE 4.7 g/100g','Topique','Burt''s Bees','INT','Médicaments topiques','BB Broad Spectrum SPF 15 Medium'),
('Kroger Jock Itch','clotrimazole','Crème','CLOTRIMAZOLE 10 mg/g','Topique','Kroger Company','INT','Azole Antifungal','Kroger Jock Itch'),
('Hand Guard Foaming Alcohol Instant Hand Sanitizer','alcohol','Solution','ALCOHOL 620 mL/L','Topique','Wechem, Inc.','INT','Médicaments topiques','Hand Guard Foaming Alcohol Instant Hand Sanitizer'),
('JANUMET XR','sitagliptin and metformin hydrochloride','Comprimé','METFORMIN HYDROCHLORIDE 1000 mg/1','Orale','Merck Sharp & Dohme LLC','US','Biguanide','JANUMET XR'),
('Ultramicrosize Griseofulvin','ultramicrosize griseofulvin tablets','Comprimé','GRISEOFULVIN 125 mg/1','Orale','Amneal Pharmaceuticals of New York LLC','US','Tubulin Inhibiting Agent','Ultramicrosize Griseofulvin'),
('Original Antiseptic','eucalyptol, menthol, methyl salicylate, thymol','MOUTHWASH','EUCALYPTOL .92 mg/mL','Orale','Topco Associates LLC','INT',NULL,'Original Antiseptic'),
('EMGALITY','galcanezumab-gnlm','Solution','GALCANEZUMAB 120 mg/mL','Sous-cutanée','Eli Lilly and Company','US',NULL,'EMGALITY'),
('Chloroprocaine Hydrochloride','chloroprocaine hydrochloride','Solution','CHLOROPROCAINE HYDROCHLORIDE 20 mg/mL','Épidurale','Hikma Pharmaceuticals USA Inc.','US','Ester Local Anesthetic','Chloroprocaine Hydrochloride'),
('Chewable Stomach Relief','bismuth subsalicylate','Comprimé','BISMUTH SUBSALICYLATE 262 mg/1','Orale','PUBLIX SUPER MARKETS INC,','INT','Bismuth','Chewable Stomach Relief'),
('PREVDUO','neostigmine methylsulfate and glycopyrrolate','Solution injectable','GLYCOPYRROLATE .2 mg/mL','Intraveineuse','Endo USA','US','Anticholinergic','PREVDUO'),
('Oxybutynin Chloride Extended Release','oxybutynin chloride','Comprimé','OXYBUTYNIN CHLORIDE 5 mg/1','Orale','AvKARE','US','Cholinergic Muscarinic Antagonist','Oxybutynin Chloride Extended Release'),
('Dairy Allergen Mix','adenosinum triphosphoricum dinatrum, benzoicum acidum, calcarea carbonica, calcarea fluorica, calcarea phosphorica, calcium citrate, calcium gluconate, carbo vegetabilis, chamomilla, cholinum, cinnamic acid, coumarinum, eugenol, folic acid, folliculinum, formalinum, gaba (gamma-aminobutyric acid), gaertner bacillus (bach), histaminum hydrochloricum, ileum (suis), jejunum (suis), l-asparagine (monohydrate), lac caninum, lac defloratum, lac felinum, lac humanum, lac vaccinum, menadione,','LIQUID','.GAMMA.-AMINOBUTYRIC ACID 8 [hp_X]/mL','Orale','Deseret Biologicals, Inc.','INT','Blood Coagulation Factor','Dairy Allergen Mix'),
('VARICO HP','calcarea fluorica, carbo vegetabilis, hamamelis virginiana, lachesis mutus, lycopodium clavatum, pulsatilla (vulgaris), secale cornutum, staphysagria, zincum metallicum','LIQUID','ACTIVATED CHARCOAL 30 [hp_X]/mL','Orale','BioActive Nutritional, Inc.','INT',NULL,'VARICO HP'),
('URIBEL TABS','methenamine, benzoic acid, phenyl salicylate, methylene blue, and hyoscyamine sulfate','Comprimé','BENZOIC ACID 9 mg/1','Orale','Mission Pharmacal Company','INT','Nitrogen Binding Agent','URIBEL TABS'),
('365 Everyday Value','sport lotion mineral sunscreen spf 30','Lotion','ZINC OXIDE 8.25 g/44mL','Topique','Whole Foods Market, Inc.','INT','Médicaments topiques','365 Everyday Value'),
('ZO Skin Health Pigment Control Program Plus Hydroquinone','hydroquinone','Kit',NULL,NULL,'ZO Skin Health, Inc.','INT',NULL,'ZO Skin Health Pigment Control Program Plus Hydroquinone'),
('Fever CP','aconitum napellus, bryonia alba, calcarea carbonica, ferrum phosphoricum, lycopodium clavatum, phosphorus, pulsatilla, pyrogenium, sulphur','LIQUID','ACONITUM NAPELLUS WHOLE 30 [hp_X]/mL','Orale','Natural Creations, Inc','INT',NULL,'Fever CP'),
('Detox I','carduus marianus, chelidonium majus, lycopodium clavatum, taraxacum officinale, avena sativa, cynara scolymus, methylcobalamin, menadione, alpha-lipoicum acidum, cinchona officinalis, hepar suis, veratrum album, colon (suis), duodenum (suis), gallbladder (suis), intestine (suis), lymph node (suis), pancreas suis, thymus (suis), acetaldehyde, alpha-ketoglutaricum acidum, cholesterinum, formicum acidum, histaminum hydrochloricum, malic acid, natrum oxalaceticum, sulphur, calcarea carbonica,','LIQUID','.ALPHA.-LIPOIC ACID 8 [hp_X]/mL','Orale','Deseret Biologicals, Inc.','INT',NULL,'Detox I'),
('Stemphylium','stemphylium botryosum','Solution injectable','PLEOSPORA TARDA .1 g/mL','CUTANEOUS','Allermed Laboratories, Inc.','US','Non-Standardized Fungal Allergenic Extract','Stemphylium'),
('PARURE GOLD SKIN MATTE FOUNDATION NO-TRANSFER HIGH PERFECTION 24H CARE AND WEAR INFUSED WITH 24K GOLD AND WHITE PEONY WITH SUNSCREEN BROADSPECTRUM SPF 15 3N','octisalate, titanium dioxide','EMULSION','OCTISALATE 35 mg/mL','Topique','Guerlain','INT','Médicaments topiques','PARURE GOLD SKIN MATTE FOUNDATION NO-TRANSFER HIGH PERFECTION 24H CARE AND WEAR INFUSED WITH 24K GOLD AND WHITE PEONY WITH SUNSCREEN BROADSPECTRUM SPF 15 3N'),
('Lancome Paris Renergie HPN 300 Peptide Broad Spectrum SPF 25 Sunscreen','avobenzone, octisalate and octocrylene','Crème','AVOBENZONE 30 mg/g','Topique','L''Oreal USA Products Inc','INT','Médicaments topiques','Lancome Paris Renergie HPN 300 Peptide Broad Spectrum SPF 25 Sunscreen'),
('Ring HP','ginkgo biloba, chininum sulphuricum, cinchona officinalis, graphites, natrum salicylicum, plumbum metallicum, salicylicum acidum, spigelia anthelmia, thiosinaminum','LIQUID','ALLYLTHIOUREA 30 [hp_X]/mL','Orale','Energique, Inc.','INT','Antimalarial','Ring HP'),
('Ativan','lorazepam','Comprimé','LORAZEPAM .5 mg/1','Orale','Bausch Health US LLC','US','Benzodiazepine','Ativan'),
('Green Guard Derma-Caine Burn','benzalkonium chloride, lidocaine hcl','Crème','BENZALKONIUM CHLORIDE 1.3 mg/g','Topique','Unifirst First Aid Corporation','INT','Amide Local Anesthetic','Green Guard Derma-Caine Burn'),
('Kalium carbonicum 6X','kalium carbonicum 6x','LIQUID','POTASSIUM CARBONATE 6 [hp_X]/mL','Orale','Uriel Pharmacy, Inc','INT',NULL,'Kalium carbonicum 6X'),
('NiteTime Cold/Flu, Multi-Symptom Relief','acetaminophen, dextromethorphan hbr, doxylamine succinate','Gélule','ACETAMINOPHEN 325 mg/1','Orale','Wal-Mart Stores Inc','INT','Antihistamine','NiteTime Cold/Flu, Multi-Symptom Relief'),
('Herceptin Hylecta','trastuzumab and hyaluronidase-oysk','Solution','HYALURONIDASE (HUMAN RECOMBINANT) 10000 U/5mL','Sous-cutanée','Genentech, Inc.','US','Endoglycosidase','Herceptin Hylecta'),
('Exaprin Plus','aspirin, acetaminophen, caffeine','Comprimé','ACETAMINOPHEN 250 mg/1','Orale','HART Health','INT','Central Nervous System Stimulant','Exaprin Plus'),
('Apri 28 Day','desogestrel and ethinyl estradiol','Kit',NULL,NULL,'A-S Medication Solutions','US',NULL,'Apri 28 Day'),
('0.25 % PHENYLEPHRINE HCl HEMORRHOIDAL','mineral oil, petrolatum, phenylephrine hydrochloride','Pommade','MINERAL OIL 14 g/100g','Topique','Universal Distribution Center LLC','INT','alpha-1 Adrenergic Agonist','0.25 % PHENYLEPHRINE HCl HEMORRHOIDAL'),
('70%','isopropyl alcohol','LIQUID','ISOPROPYL ALCOHOL 70 mL/100mL','Topique','Perrigo Direct, Inc','INT','Médicaments topiques','70%'),
('Toms Whole Care Cinnamon Clove FIGHTS CAVITIES WHITENING FRESH BREATH HELPS FIGHT TARTAR','sodium monofluorophosphate','PASTE, DENTIFRICE','SODIUM MONOFLUOROPHOSPHATE 1.4 mg/g','DENTAL','Tom''s of Maine, Inc.','INT',NULL,'Toms Whole Care Cinnamon Clove FIGHTS CAVITIES WHITENING FRESH BREATH HELPS FIGHT TARTAR'),
('CVS PHARMACY DYE FREE Childrens Allergy Chews','diphenhydramine hcl','Comprimé','DIPHENHYDRAMINE HYDROCHLORIDE 12.5 mg/1','Orale','CVS PHARMACY, INC.','INT','Histamine-1 Receptor Antagonist','CVS PHARMACY DYE FREE Childrens Allergy Chews'),
('Nighttime Sleep-Aid Softgel','diphenhydramine hydrochloride','Gélule','DIPHENHYDRAMINE HYDROCHLORIDE 25 mg/1','Orale','CVS PHARMACY, INC','INT','Histamine-1 Receptor Antagonist','Nighttime Sleep-Aid Softgel'),
('Lidocaine 4% Maximum OTC Strength','lidocaine','Patch transdermique','LIDOCAINE 4 g/100g','Topique','Cardinal Health 107, LLC','INT','Amide Local Anesthetic','Lidocaine 4% Maximum OTC Strength')
) AS v(nom, dci, forme, dosage, voie, labo, pays, classe, nomcom)
WHERE NOT EXISTS (
  SELECT 1 FROM medicaments m WHERE UPPER(m.nom) = UPPER(v.nom)
);
