-- ndc_batch_013.sql (80 rows)
INSERT INTO medicaments (nom, dci, forme, dosage, voie_administration, laboratoire, pays, classe_therapeutique, nom_commercial)
SELECT v.nom, v.dci, v.forme, v.dosage, v.voie, v.labo, v.pays, v.classe, v.nomcom
FROM (VALUES
('Dandruff','pyrithione zinc','SHAMPOO','PYRITHIONE ZINC 10 mg/mL','Topique','H E B','INT','Médicaments topiques','Dandruff'),
('Anticavity Rinse','sodium fluoride','MOUTHWASH','SODIUM FLUORIDE .2 mg/mL','Orale','H E B','INT',NULL,'Anticavity Rinse'),
('Witch Hazel','witch hazel','Solution','WITCH HAZEL 860 mg/mL','Topique','United Natural Foods, Inc. dba UNFI','INT','Médicaments topiques','Witch Hazel'),
('DAYTIME-NIGHTTIME SEVERE COLD AND FLU','acetaminophen, dextromethorphan hbr, doxylamine succinate, phenylephrine hcl','Kit',NULL,'Orale','KROGER','INT',NULL,'DAYTIME-NIGHTTIME SEVERE COLD AND FLU'),
('Antacid','calcium carbonate','Comprimé','CALCIUM CARBONATE 750 mg/1','Orale','Meijer Distribution Inc','INT',NULL,'Antacid'),
('Sodium Sulfacetamide 10 Sulfur 5 Cleanser','sulfacetamide sodium and sulfur','RINSE','SULFACETAMIDE SODIUM 10 mg/g','Topique','Acella Pharmaceuticals, LLC','INT','Sulfonamide Antibacterial','Sodium Sulfacetamide 10 Sulfur 5 Cleanser'),
('Phenobarbital Sodium','phenobarbital sodium','Solution injectable','PHENOBARBITAL SODIUM 65 mg/mL','Intramusculaire','Cameron Pharmaceuticals','INT',NULL,'Phenobarbital Sodium'),
('IMITREX','sumatriptan','Comprimé','SUMATRIPTAN SUCCINATE 50 mg/1','Orale','GlaxoSmithKline LLC','US','Serotonin-1b and Serotonin-1d Receptor Agonist','IMITREX'),
('Bio Walnut','juglans regia, flos','LIQUID','JUGLANS REGIA FLOWERING TOP 6 [hp_X]/mL','Orale','BioActive Nutritional, Inc.','INT',NULL,'Bio Walnut'),
('Testosterone','testosterone','Comprimé','TESTOSTERONE 30 [hp_X]/1','Orale','Zoe Processing','INT','Androgen','Testosterone'),
('Amoxicillin','amoxicillin','Gélule','AMOXICILLIN 500 mg/1','Orale','QPharma, Inc.','US','Penicillin-class Antibacterial','Amoxicillin'),
('Oxycodone and Aspirin','oxycodone and aspirin','Comprimé','ASPIRIN 325 mg/1','Orale','Epic Pharma, LLC','US','Nonsteroidal Anti-inflammatory Drug','Oxycodone and Aspirin'),
('IOPE UV DEFENSE SUN PROTECTOR','homosalate, octocrylene, octisalate, avobenzone','Crème','AVOBENZONE 1.25 g/50mL','Topique','AMOREPACIFIC CORPORATION','INT','Médicaments topiques','IOPE UV DEFENSE SUN PROTECTOR'),
('Biorphen','phenylephrine hydrochloride','Solution','PHENYLEPHRINE HYDROCHLORIDE .1 mg/mL','Intraveineuse','Dr. Reddy''s Laboratories Inc.','US','alpha-1 Adrenergic Agonist','Biorphen'),
('ESPEROCT','antihemophilic factor (recombinant), glycopegylated-exei','Kit',NULL,NULL,'Novo Nordisk','US',NULL,'ESPEROCT'),
('LAMICTAL','lamotrigine','Comprimé','LAMOTRIGINE 5 mg/1','Orale','GlaxoSmithKline LLC','US','Anti-epileptic Agent','LAMICTAL'),
('Western Wheatgrass Pollen','agropyron smithii','Solution injectable','PASCOPYRUM SMITHII POLLEN .05 g/mL','CUTANEOUS','Allermed Laboratories, Inc.','US','Non-Standardized Pollen Allergenic Extract','Western Wheatgrass Pollen'),
('Satos Corn and Callus Remover','salicylic acid','LIQUID','SALICYLIC ACID 12 g/100mL','Topique','Sato Pharmaceutical Co., Ltd.','INT','Médicaments topiques','Satos Corn and Callus Remover'),
('La Roche Posay Face Body Anthelios SPF 60 Melt In Milk Fast absorbing, velvety finish for all skin types with Cell-OC Shield XL','avobenzone, homosalate, octisalate and octocrylene','Lotion','AVOBENZONE 30 mg/mL','Topique','L''Oreal USA Products Inc','INT','Médicaments topiques','La Roche Posay Face Body Anthelios SPF 60 Melt In Milk Fast absorbing, velvety finish for all skin types with Cell-OC Shield XL'),
('Acetaldehyde Phenolic','acetaldehyde','LIQUID','ACETALDEHYDE 6 [hp_X]/mL','Orale','Energique, Inc.','INT',NULL,'Acetaldehyde Phenolic'),
('Influenzinum 200C','influenzinum (2021-2022)','LIQUID','INFLUENZA A VIRUS A/TASMANIA/503/2020 IVR-221 (H3N2) ANTIGEN (FORMALDEHYDE INACTIVATED) 200 [hp_C]/m','Orale','Energique, Inc.','INT',NULL,'Influenzinum 200C'),
('Aspirin','aspirin','Comprimé','ASPIRIN 325 mg/1','Orale','Amerisource Bergen','INT','Nonsteroidal Anti-inflammatory Drug','Aspirin'),
('Salonpas LIDOCAINE Pain Relieving','lidocaine','Patch transdermique','LIDOCAINE 560 mg/1','PERCUTANEOUS','Hisamitsu Pharmaceutical Co., Inc.','INT','Amide Local Anesthetic','Salonpas LIDOCAINE Pain Relieving'),
('Endure 300 Cida Rinse Gel Antimicrobial Hand Rinse','antiseptic handwash','Solution','ALCOHOL 70 mL/100mL','Topique','Ecolab Inc.','INT','Médicaments topiques','Endure 300 Cida Rinse Gel Antimicrobial Hand Rinse'),
('Medique Cold Eeze','zinc gluconate','Pastille','ZINC GLUCONATE 2 [hp_X]/1','Orale','Unifirst First Aid Corporation','INT','Copper Absorption Inhibitor','Medique Cold Eeze'),
('Imatinib Mesylate','imatinib','Comprimé','IMATINIB MESYLATE 100 mg/1','Orale','Safecor Health, LLC','US','Kinase Inhibitor','Imatinib Mesylate'),
('Plantago Primula','plantago primula','LIQUID','HYOSCYAMUS NIGER LEAF 3 [hp_X]/mL','Orale','Uriel Pharmacy Inc.','INT',NULL,'Plantago Primula'),
('Headache Relief Extra Strength','acetaminophen, aspirin and caffeine','Comprimé','ACETAMINOPHEN 250 mg/1','Orale','Wal-Mart Stores Inc','INT','Central Nervous System Stimulant','Headache Relief Extra Strength'),
('Artistry Ideal Radiance Illuminating CC SPF 50 Broad Spectrum Sunscreen Medium','ensulizole,octinoxate, oxybenzone, titanium dioxide, zinc oxide','Crème','ENSULIZOLE 20 mg/mL','Topique','Amway Corp','INT','Copper Absorption Inhibitor','Artistry Ideal Radiance Illuminating CC SPF 50 Broad Spectrum Sunscreen Medium'),
('PEARL ANTIMICROBIAL HAND ITEM 1027AB-01','chloroxylenol','SOAP','CHLOROXYLENOL .3 g/100mL','Topique','AMERICAN CHEMICAL AND SANITARY SUPPLY INC','INT','Médicaments topiques','PEARL ANTIMICROBIAL HAND ITEM 1027AB-01'),
('Bismuthum metallicum','bismuth','PELLET','BISMUTH 200 [kp_C]/200[kp_C]','Orale','Boiron','INT',NULL,'Bismuthum metallicum'),
('LIDOCAINE AND PRILOCAINE','lidocaine and prilocaine','Crème','LIDOCAINE 25 mg/g','Topique','A-S Medication Solutions','US','Amide Local Anesthetic','LIDOCAINE AND PRILOCAINE'),
('BUPROPION HYDROCHLORIDE (SR)','bupropion hydrochloride','Comprimé','BUPROPION HYDROCHLORIDE 150 mg/1','Orale','A-S Medication Solutions','US','Aminoketone','BUPROPION HYDROCHLORIDE (SR)'),
('Ezetimibe','ezetimibe','Comprimé','EZETIMIBE 10 mg/1','Orale','A-S Medication Solutions','US','Dietary Cholesterol Absorption Inhibitor','Ezetimibe'),
('Betamethasone Dipropionate','betamethasone dipropionate','Pommade','BETAMETHASONE DIPROPIONATE .5 mg/g','Topique','A-S Medication Solutions','US','Corticosteroid','Betamethasone Dipropionate'),
('Nortriptyline Hydrochloride','nortriptyline hydrochloride','Gélule','NORTRIPTYLINE HYDROCHLORIDE 25 mg/1','Orale','Mayne Pharma Inc.','US','Tricyclic Antidepressant','Nortriptyline Hydrochloride'),
('SUPRESS-PE Pediatric','guiafenesin, phenylephrine hcl','Solution','GUAIFENESIN 50 mg/mL','Orale','Kramer Novis','INT','Expectorant','SUPRESS-PE Pediatric'),
('AMERIDERM','bzk','SHAMPOO','BENZALKONIUM CHLORIDE .1 g/100g','Topique','SHIELD LINE LLC','INT','Médicaments topiques','AMERIDERM'),
('Timolol Maleate','timolol maleate','Solution','TIMOLOL MALEATE 3.4 mg/mL','Ophtalmique','Ingenus Pharmaceuticals, LLC','US','beta-Adrenergic Blocker','Timolol Maleate'),
('Refill 3','benzalkonium chloride, lidocaine hydrochloride','Crème','BENZALKONIUM CHLORIDE .13 g/100g','Topique','GFA Production (Xiamen) Co., Ltd.','INT','Amide Local Anesthetic','Refill 3'),
('Alcohol Prep Pad','alcohol prep pad','LIQUID','ISOPROPYL ALCOHOL 70 mL/100mL','Topique','ASO LLC','INT','Médicaments topiques','Alcohol Prep Pad'),
('Albendazole','albendazole','Comprimé','ALBENDAZOLE 200 mg/1','Orale','Golden State Medical Supply, Inc.','US','Anthelmintic','Albendazole'),
('Zileuton','zileuton','Comprimé','ZILEUTON 600 mg/1','Orale','Golden State Medical Supply, Inc.','US','5-Lipoxygenase Inhibitor','Zileuton'),
('Mary Kay TimeWise Repair Volu-Firm Day Cream Broad Spectrum SPF 30','avobenzone, homosalate, octisalate, octocrylene, oxybenzone','Crème','AVOBENZONE 3 g/100g','Topique','Mary Kay Inc.','INT','Médicaments topiques','Mary Kay TimeWise Repair Volu-Firm Day Cream Broad Spectrum SPF 30'),
('CVS Ibuprofen','ibuprofen','Comprimé','IBUPROFEN 200 mg/1','Orale','CVS Pharmacy','US','Nonsteroidal Anti-inflammatory Drug','CVS Ibuprofen'),
('Dicyclomine Hydrochloride','dicyclomine hydrochloride','Comprimé','DICYCLOMINE HYDROCHLORIDE 20 mg/1','Orale','Northwind Health Company, LLC','US','Anticholinergic','Dicyclomine Hydrochloride'),
('Ergocalciferol Capsules,','ergocalciferol capsules,','Gélule','ERGOCALCIFEROL 1.25 mg/1','Orale','Northwind Health Company, LLC','US','Provitamin D2 Compound','Ergocalciferol Capsules,'),
('Hamamelis virginiana','hamamelis virginiana root bark/stem bark','PELLET','HAMAMELIS VIRGINIANA ROOT BARK/STEM BARK 30 [hp_X]/30[hp_X]','Orale','Boiron','INT',NULL,'Hamamelis virginiana'),
('Histaminum hydrochloricum','histamine dihydrochloride','PELLET','HISTAMINE DIHYDROCHLORIDE 15 [hp_C]/15[hp_C]','Orale','Boiron','INT',NULL,'Histaminum hydrochloricum'),
('PRAVASTATIN SODIUM','pravastatin sodium','Comprimé','PRAVASTATIN SODIUM 40 mg/1','Orale','Cardinal Health 107, LLC','US','HMG-CoA Reductase Inhibitor','PRAVASTATIN SODIUM'),
('Allergy Multi-Symptom','acetaminophen, chlorpheniramine maleate and phenylephrine hcl','Comprimé','ACETAMINOPHEN 325 mg/1','Orale','ARMY AND AIR FORCE EXCHANGE SERVICE','INT','Histamine-1 Receptor Antagonist','Allergy Multi-Symptom'),
('Family Wellness Hot and Cold Pain Relief','hot and cold pain relief','Crème','MENTHOL, UNSPECIFIED FORM 100 mg/g','Topique','FAMILY DOLLAR (Family Wellness)','INT','Médicaments topiques','Family Wellness Hot and Cold Pain Relief'),
('Be Smart Get Prepared Triple Antibiotic','bacitracin zinc, neomycin sulfate, polymyxin b sulfate','Pommade','BACITRACIN ZINC 400 [USP''U]/g','Topique','Total Resources International, Inc','INT','Aminoglycoside Antibacterial','Be Smart Get Prepared Triple Antibiotic'),
('Hielo Ardiente','menthol','Gel','MENTHOL 1 g/100g','Topique','Menper Distributors, Inc.','INT','Médicaments topiques','Hielo Ardiente'),
('Curad Alcohol Sterile, Thick','isopropyl alcohol','SWAB','ISOPROPYL ALCOHOL 70 mL/100mL','Topique','Medline Industries, LP','INT','Médicaments topiques','Curad Alcohol Sterile, Thick'),
('Lobelia Inflata 6X','lobelia inflata','LIQUID','LOBELIA INFLATA 6 [hp_X]/30mL','Orale','True Botanica, LLC','INT',NULL,'Lobelia Inflata 6X'),
('Sei Bella Tinted BB Moisturizing Creme Medium 320 C','titanium dioxide 5% and zinc oxide 5%','Lotion','TITANIUM DIOXIDE 1.5 g/30mL','Topique','Melaleuca Inc.','INT','Médicaments topiques','Sei Bella Tinted BB Moisturizing Creme Medium 320 C'),
('Licensed Hand Sanitizer Barbie 01','alcohol','Spray','ALCOHOL 70 mL/100mL','Topique','Shenzhen Lantern Scicence Co.,Ltd.','INT','Médicaments topiques','Licensed Hand Sanitizer Barbie 01'),
('Helium','helium','GAS','HELIUM 992 mL/L','Inhalation','Matheson Tri-Gas, Inc.','US',NULL,'Helium'),
('SHISEIDO REVITALESSENCE SKIN GLOW FOUNDATION 520','octinoxate','EMULSION','OCTINOXATE 2.30805 g/30mL','Topique','SHISEIDO AMERICAS CORPORATION','INT','Médicaments topiques','SHISEIDO REVITALESSENCE SKIN GLOW FOUNDATION 520'),
('Rompe Pecho EX','guaifenesin','LIQUID','GUAIFENESIN 200 mg/10mL','Orale','Efficient Laboratories Inc','INT','Expectorant','Rompe Pecho EX'),
('Physostigma venenosum','physostigma venenosum seed','PELLET','PHYSOSTIGMA VENENOSUM SEED 6 [hp_C]/6[hp_C]','Orale','Boiron','INT',NULL,'Physostigma venenosum'),
('Plumbum metallicum','lead','PELLET','LEAD 30 [hp_C]/30[hp_C]','Orale','Boiron','INT',NULL,'Plumbum metallicum'),
('Pulsatilla','anemone pulsatilla','PELLET','ANEMONE PULSATILLA 9 [hp_C]/9[hp_C]','Orale','Boiron','INT',NULL,'Pulsatilla'),
('Dry Scalp Care','pyrithione zinc','SHAMPOO','PYRITHIONE ZINC 10 mg/mL','Topique','Old East Main Co.','INT','Médicaments topiques','Dry Scalp Care'),
('Zylast Antiseptic K','benzalkonium chloride','Lotion','BENZALKONIUM CHLORIDE .13 g/100mL','Topique','Innovative Biodefense','INT','Médicaments topiques','Zylast Antiseptic K'),
('Foot Odor Control Powder','tolnaftate','Spray','TOLNAFTATE 1.3 g/113g','Topique','Premier Brands of America Inc.','INT','Médicaments topiques','Foot Odor Control Powder'),
('Bach Original Flower Remedies Gorse','ulex europaeus','Solution','ULEX EUROPAEUS FLOWER 5 [hp_X]/.095mL','Orale','Nelson Bach USA Limited','INT',NULL,'Bach Original Flower Remedies Gorse'),
('T-12','gentianella amarella whole','Solution','GENTIANELLA AMARELLA WHOLE 30 [hp_X]/mL','Sublinguale','DNA Labs, Inc.','INT',NULL,'T-12'),
('SHISEIDO UV PROTECTIVE COMPACT (REFILL) MEDIUM IVORY','octinoxate, octocrylene, and titanium dioxide','Poudre','OCTINOXATE 888 mg/12g','Topique','SHISEIDO AMERICAS CORPORATION','INT','Médicaments topiques','SHISEIDO UV PROTECTIVE COMPACT (REFILL) MEDIUM IVORY'),
('ImmunoBooster','arsenicum alb, baptisia, echinacea, medulla ossis suis, merc corros, sulphur iod, thuja occ','LIQUID','ARSENIC TRIOXIDE 200 [hp_C]/41mL','Orale','Eight and Company L.L.C','INT',NULL,'ImmunoBooster'),
('ALOE UP PRO 50 CONTINUOUS SUNSCREEN','avobenzone, homosalate, octisalate, octocrylene, oxybenzone','Spray','AVOBENZONE 3 g/100mL','Topique','Aloe Care International, LLC','INT','Médicaments topiques','ALOE UP PRO 50 CONTINUOUS SUNSCREEN'),
('Diclolidol Kit','lidocaine hcl, diclofenac sodium','Kit',NULL,NULL,'PureTek Corporation','INT',NULL,'Diclolidol Kit'),
('infants pain fever','acetaminophen','Suspension','ACETAMINOPHEN 160 mg/5mL','Orale','H E B','INT',NULL,'infants pain fever'),
('Guanfacine Extended-Release','guanfacine','Comprimé','GUANFACINE 1 mg/1','Orale','Golden State Medical Supply, Inc.','US','Central alpha-2 Adrenergic Agonist','Guanfacine Extended-Release'),
('Jet Lag Relief','anamirta cocculus seed, arnica montana, strychnos nux-vomica whole','PELLET','ANAMIRTA COCCULUS SEED 6 [hp_C]/1','Orale','Laboratoires Boiron','INT',NULL,'Jet Lag Relief'),
('THROATCALM','echinacea angustifolia whole, plantago major whole','Spray','ECHINACEA ANGUSTIFOLIA WHOLE 1 [hp_X]/mL','Orale','Boiron','INT',NULL,'THROATCALM'),
('Alprazolam','alprazolam','Comprimé','ALPRAZOLAM .25 mg/1','Orale','Actavis Pharma, Inc.','US','Benzodiazepine','Alprazolam'),
('I Conceal Flawless Foundation Broad Spectrum SPF 30 Sunscreen Deep Honey','zinc oxide and titanium dioxide','Crème','TITANIUM DIOXIDE 58 mg/g','Topique','Allure Labs','INT','Médicaments topiques','I Conceal Flawless Foundation Broad Spectrum SPF 30 Sunscreen Deep Honey'),
('Nu Skin ageLOC Radiant Day Broad Spectrum SPF 22','avobenzone, homosalate, octisalate, and octocrylene','Lotion','AVOBENZONE 30 mg/mL','Topique','NSE Products, Inc.','INT','Médicaments topiques','Nu Skin ageLOC Radiant Day Broad Spectrum SPF 22')
) AS v(nom, dci, forme, dosage, voie, labo, pays, classe, nomcom)
WHERE NOT EXISTS (
  SELECT 1 FROM medicaments m WHERE UPPER(m.nom) = UPPER(v.nom)
);
