-- ndc_batch_124.sql (80 rows)
INSERT INTO medicaments (nom, dci, forme, dosage, voie_administration, laboratoire, pays, classe_therapeutique, nom_commercial)
SELECT v.nom, v.dci, v.forme, v.dosage, v.voie, v.labo, v.pays, v.classe, v.nomcom
FROM (VALUES
('Amiloride Hydrochloride and Hydrochlorothiazide','amiloride hydrochloride and hydrochlorothiazide','Comprimé','AMILORIDE HYDROCHLORIDE 5 mg/1',NULL,'Teva Pharmaceuticals USA, Inc.','INT',NULL,NULL),
('Ammonium Aluminum Sulfate','ammonium aluminum sulfate','CRYSTAL','ALUMINUM SULFATE 1 g/g',NULL,'Holland Company, Inc.','INT',NULL,NULL),
('Betamethasone Dipropionate Micronized','betamethasone dipropionate micronized','Poudre','BETAMETHASONE DIPROPIONATE 1 kg/kg',NULL,'NEWCHEM SPA','INT',NULL,NULL),
('Albuterol Salbutamol base','albuterol salbutamol base','Poudre','ALBUTEROL 100 kg/100kg',NULL,'SICOR Societa'' Italiana Corticosteroidi s.r.l.','INT',NULL,NULL),
('Tolbutamide','tolbutamide','Poudre','TOLBUTAMIDE 1 kg/kg',NULL,'Dipharma Francis Srl','INT',NULL,NULL),
('efavirenz, emtricitabine, and tenofovir disoproxil fumarate','efavirenz, emtricitabine, and tenofovir disoproxil fumarate','Comprimé','EFAVIRENZ 600 mg/1',NULL,'Takeda GmbH','INT',NULL,NULL),
('ESTRADIOL HEMIHYDRATE','estradiol hemihydrate','Poudre','ESTRADIOL HEMIHYDRATE 1 g/g',NULL,'Kalchem International inc','INT',NULL,NULL),
('Brompheniramine Maleate','brompheniramine maleate','Poudre','BROMPHENIRAMINE MALEATE 1 kg/kg',NULL,'Supriya Lifescience Limited','INT',NULL,NULL),
('FLUPHENAZINE DECANOATE','fluphenazine decanoate','LIQUID','FLUPHENAZINE DECANOATE 1 kg/kg',NULL,'Professional Compounding Centers of America dba PCCA','INT',NULL,NULL),
('Lurasidone Hydrochloride API','lurasidone hydrochloride api','Poudre','LURASIDONE HYDROCHLORIDE 1 kg/kg',NULL,'Dr.Reddy''s Laboratories Limited','INT',NULL,NULL),
('Normosol-R and Dextrose','dextrose, sodium chloride, sodium acetate anhydrous, sodium gluconate, potassium chloride, and magnesium chloride','Solution','DEXTROSE MONOHYDRATE 5 g/100mL','Intraveineuse','ICU Medical Inc.','US','Calculi Dissolution Agent','Normosol-R and Dextrose'),
('Apalutamide','apalutamide','Poudre','APALUTAMIDE 1 kg/kg',NULL,'Hetero Labs Limited','INT',NULL,NULL),
('NUPHAR LUTEA ROOT','nuphar lutea root','LIQUID','NUPHAR LUTEA ROOT 1 [hp_X]/mL',NULL,'Herbamed AG','INT',NULL,NULL),
('CABOZANTINIB','cabozantinib','Poudre','CABOZANTINIB 1 kg/kg',NULL,'STERLING SPA','INT',NULL,NULL),
('THYMOSIN .BETA.-4','thymosin .beta.-4','Poudre','THYMOSIN .BETA.-4 100 g/100g',NULL,'Hangzhou Yiqi Biotechnology Co., Ltd','INT',NULL,NULL),
('Metyrosine','metyrosine','Poudre','METYROSINE 1 kg/kg',NULL,'R.L.Fine Chem Private Limited','INT',NULL,NULL),
('Acetaminophen,Dextromethorphan HBr,Phenylephrine HCl','acetaminophen,dextromethorphan hbr,phenylephrine hcl','Gélule','ACETAMINOPHEN 325 mg/1',NULL,'Pioneer Life Sciences, LLC','INT',NULL,NULL),
('Rite Aid Stomach Relief Original Flavor','bismuth subsalicylate','Comprimé','BISMUTH SUBSALICYLATE 262 mg/1','Orale','RITE AID CORPORATION','INT',NULL,'Rite Aid Stomach Relief Original Flavor'),
('Sulfur 8 Fresh Anti-Dandruff Oil Moisturizing','pyrithione zinc','Lotion','PYRITHIONE ZINC 1 mg/mL','Topique','J. Strickland & Co.','INT','Médicaments topiques','Sulfur 8 Fresh Anti-Dandruff Oil Moisturizing'),
('NARS PURE RADIANT TINTED MOISTURIZER Groenland','octinoxate, titanium dioxide','Crème','OCTINOXATE 4.044 g/50mL','Topique','NARS Cosmetics','INT','Médicaments topiques','NARS PURE RADIANT TINTED MOISTURIZER Groenland'),
('SPOTLESS REGIMEN FOR ACNE, BLEMISHES AND BREAKOUTS','benzoyl peroxide','Kit',NULL,'Topique','Rodan & Fields','INT','Médicaments topiques','SPOTLESS REGIMEN FOR ACNE, BLEMISHES AND BREAKOUTS'),
('Albertson Lidocaine, Menthol Pain Relief Medicated Patch','lidocaine and menthol','Patch transdermique','LIDOCAINE 4 g/100g','Topique','Safeway','INT','Amide Local Anesthetic','Albertson Lidocaine, Menthol Pain Relief Medicated Patch'),
('Black Willow Pollen','salix nigra','Solution','SALIX NIGRA POLLEN .05 g/mL','INTRADERMAL','Greer Laboratories, Inc.','US','Non-Standardized Pollen Allergenic Extract','Black Willow Pollen'),
('Meijer Jock Itch Relief Antifungal','miconazole nitrate','Spray','MICONAZOLE NITRATE 20 mg/g','Topique','Formulated Solutions, LLC','INT','Azole Antifungal','Meijer Jock Itch Relief Antifungal'),
('Good Neighbor Pharmacy ibuprofen childrens','ibuprofen','Suspension','IBUPROFEN 100 mg/5mL','Orale','Amerisource Bergen','US','Nonsteroidal Anti-inflammatory Drug','Good Neighbor Pharmacy ibuprofen childrens'),
('terrasil Antifungal Cleansing Bar','clotrimazole','SOAP','CLOTRIMAZOLE 1 g/100g','Topique','Aidance Scientific, Inc, DBA Aidance Skincare & Topical Solutions','INT','Azole Antifungal','terrasil Antifungal Cleansing Bar'),
('24 / 7 Life Non-Drowsy Allergy Relief','loratadine tablet','Comprimé','LORATADINE 10 mg/1','Orale','Lil'' Drug Store Products, Inc.','US',NULL,'24 / 7 Life Non-Drowsy Allergy Relief'),
('NUPRO Chlorhexidine Gluconate','chlorhexidine gluconate','RINSE','CHLORHEXIDINE GLUCONATE 1.2 mg/mL','Orale','Xttrium Laboratories, Inc.','US','Decreased Cell Wall Integrity','NUPRO Chlorhexidine Gluconate'),
('TOPCARE EVERYDAY SPORT SPF 70 SUNSCREEN','avobenzone, homosalate, octisalate, octocrylene, oxybenzone','Lotion','AVOBENZONE 30 mg/mL','Topique','TOPCO ASSOCIATES LLC','INT','Médicaments topiques','TOPCARE EVERYDAY SPORT SPF 70 SUNSCREEN'),
('Ranitidine','ranitidine','Sirop','RANITIDINE 15 mg/mL','Orale','Pharmaceutical Associates, Inc.','US','Histamine-2 Receptor Antagonist','Ranitidine'),
('HEB Maximum strength Laxative pills','sennosides','Comprimé','SENNOSIDES 25 mg/1','Orale','H E B','INT',NULL,'HEB Maximum strength Laxative pills'),
('HEB Sore Throat Cherry Flavor','phenol','Spray','PHENOL 1.4 g/100mL','Orale','HEB','INT',NULL,'HEB Sore Throat Cherry Flavor'),
('Dantrolene','dantrolene','Solution','DANTROLENE SODIUM 20 mg/1','Intraveineuse','Hikma Pharmaceuticals USA Inc.','US','Skeletal Muscle Relaxant','Dantrolene'),
('Publix Infants Dye Free Gas Relief','simethicone','EMULSION','DIMETHICONE, UNSPECIFIED 20 mg/.3mL','Orale','PUBLIX SUPER MARKETS, INC','INT','Skin Barrier Activity','Publix Infants Dye Free Gas Relief'),
('Hydration Complex','beta vulgaris, boldo, calcarea fluorica, calcarea phosphorica, carduus benedictus, chelidonium majus, coffea tosta, equisetum arvense, germanium sesquioxide, ginkgo biloba, hypericum perforatum, kali muriaticum, kali phosphoricum, kali sulphuricum, petroselinum sativum, silicea, taraxacum officinale','LIQUID','BETA VULGARIS WHOLE 1 [hp_X]/mL','Orale','Deseret Biologicals, Inc.','INT','Blood Coagulation Factor','Hydration Complex'),
('Injury','arnica montana, calendula officinalis, hypericum perforatum, symphytum officinale, belladonna, bellis perennis, carbo vegetabilis, hamamelis virginiana, millefolium, rhus tox, ruta graveolens, veratrum album','LIQUID','ACHILLEA MILLEFOLIUM 12 [hp_X]/mL','Orale','BioActive Nutritional, Inc.','INT',NULL,'Injury'),
('Sulwhasoo Perfecting Cushion NO.33C1 Walnut','octinoxate, titanium dioxide, and homosalate','Lotion','HOMOSALATE 1.05 g/15g','Topique','Amorepacific Corporation','INT','Médicaments topiques','Sulwhasoo Perfecting Cushion NO.33C1 Walnut'),
('Trauma Remedy','chamomilla, echinacea (angustifolia), hamamelis virginiana, hypericum perforatum, millefolium, calendula officinalis, arnica montana, bellis perennis, rhus tox, bryonia (alba), clematis vitalba, folia, hepar sulphuris calcareum, ornithogalum umbellatum, prunus cerasifera, flos, carbo vegetabilis','LIQUID','ACHILLEA MILLEFOLIUM WHOLE 3 [hp_X]/mL','Orale','Deseret Biologicals, Inc.','INT',NULL,'Trauma Remedy'),
('Extra strength Acetaminophen PM','acetaminophen 500mg/ diphenhydramine hcl 25mg','Comprimé','ACETAMINOPHEN 500 mg/1','Orale','TIME CAP LABS INC','INT','Histamine-1 Receptor Antagonist','Extra strength Acetaminophen PM'),
('Box Elder Maple Pollen','acer negundo','Solution injectable','ACER NEGUNDO POLLEN .05 g/mL','CUTANEOUS','Allermed Laboratories, Inc.','US','Non-Standardized Pollen Allergenic Extract','Box Elder Maple Pollen'),
('Nazal','naphazoline hydrochloride','LIQUID','NAPHAZOLINE HYDROCHLORIDE 50 mg/100mL','Nasale','Sato Pharmaceutical Co., Ltd.','INT',NULL,'Nazal'),
('Lancome Paris Renergie Lift Makeup Broad Spectrum SPF 27 Sunscreen','octinoxate and titanium dioxide','LIQUID','OCTINOXATE 75 mg/mL','Topique','L''Oreal USA Products Inc','INT','Médicaments topiques','Lancome Paris Renergie Lift Makeup Broad Spectrum SPF 27 Sunscreen'),
('Multi-Phenolic','mannose, 5-hydroxytryptophan, acetaldehyde, acetylcholine chloride, ascorbicum acidum, aspartame, butylated hydroxytoluene, caffeic acid, candida albicans, cinnamic acid, coniferyl alcohol, coumarinum, dopamine hydrochloride, estradiol, gaba (gamma-aminobutyric acid), gallicum acidum, histaminum hydrochloricum, hydrocortisone, indolum, l-dopa, l-phenylalanine, melatonin, menadione, norepinephrine (bitartrate), petroselinum crispum, phenyl isothiocyanate, piperine, progesterone, pyrrole, quercetin,','LIQUID','.GAMMA.-AMINOBUTYRIC ACID 12 [hp_X]/mL','Orale','Energique, Inc.','INT','Aromatic Amino Acid','Multi-Phenolic'),
('Pepcid','famotidine','Comprimé','FAMOTIDINE 20 mg/1','Orale','Bausch Health US LLC','US','Histamine-2 Receptor Antagonist','Pepcid'),
('APONVIE','aprepitant','EMULSION','APREPITANT 32 mg/4.4mL','Intraveineuse','Heron Therapeutics, Inc.','US','Substance P/Neurokinin-1 Receptor Antagonist','APONVIE'),
('Medique Decorel Forte','acetaminophen, dextromethorphan hydrobromide, guaifenesin, phenylephrine hydrochloride','Comprimé','ACETAMINOPHEN 325 mg/1','Orale','Unifirst First Aid Corporation','INT','Expectorant','Medique Decorel Forte'),
('Oxalis 5X','oxalis 5x','Pommade','OXALIS STRICTA WHOLE 5 [hp_X]/g','Topique','Uriel Pharmacy, Inc','INT','Médicaments topiques','Oxalis 5X'),
('Equate Effervescent Antacid and Pain Relief','aspirin, citric acid, sodium bicarbonate','Comprimé','ANHYDROUS CITRIC ACID 1000 mg/1','Orale','Walmart','INT','Anti-coagulant','Equate Effervescent Antacid and Pain Relief'),
('Guaifenesin and Codeine Phosphate','guaifenesin and codeine phosphate','Solution','CODEINE PHOSPHATE 10 mg/5mL','Orale','A-S Medication Solutions','INT','Expectorant','Guaifenesin and Codeine Phosphate'),
('Caulophyllum thalictroides','caulophyllum thalictroides root','PELLET','CAULOPHYLLUM THALICTROIDES ROOT 30 [hp_X]/1','Orale','Boiron','INT',NULL,'Caulophyllum thalictroides'),
('CareALL Hand Sanitizer','alcohol','Gel','ALCOHOL .7 mL/mL','Topique','New World Imports, Inc.','INT','Médicaments topiques','CareALL Hand Sanitizer'),
('ACNE FORTE Acne Treatment Cream','benzoyl peroxide','Crème','BENZOYL PEROXIDE 50 mg/mL','Topique','GSCM Ventures Inc. DBA Revitol','INT','Médicaments topiques','ACNE FORTE Acne Treatment Cream'),
('AMERIWASH','parachlorometaxylenol','LIQUID','CHLOROXYLENOL .003 mg/mL','Topique','SHIELD LINE LLC','INT','Médicaments topiques','AMERIWASH'),
('therapeutic tar anti-dandruff Anti-dandruff, anti-seborrheic dermatitis, anti-psoriasis','coal tar','SHAMPOO','COAL TAR 5 mg/mL','Topique','GOODSENSE','INT','Médicaments topiques','therapeutic tar anti-dandruff Anti-dandruff, anti-seborrheic dermatitis, anti-psoriasis'),
('Toms of Maine Whiten Plus Deep Clean Peppermint','sodium fluoride','PASTE, DENTIFRICE','SODIUM FLUORIDE 1.1 mg/g','DENTAL','Tom''s of Maine','INT',NULL,'Toms of Maine Whiten Plus Deep Clean Peppermint'),
('Derma B Everyday Fit Sunscreen SPF 50','avobezone, homosalate, octisalate, octocrylene','Lotion','AVOBENZONE 30 mg/mL','Topique','NeoPharm Co., Ltd.','INT','Médicaments topiques','Derma B Everyday Fit Sunscreen SPF 50'),
('Hyoscyamine ER','hyoscyamine sulfate','Comprimé','HYOSCYAMINE SULFATE .375 mg/1','Orale','Mylan Pharmaceuticals Inc.','INT',NULL,'Hyoscyamine ER'),
('CVS Fexofenadine Hydrochloride','fexofenadine hydrochloride','Comprimé','FEXOFENADINE HYDROCHLORIDE 180 mg/1','Orale','CVS Pharmacy','US','Histamine-1 Receptor Antagonist','CVS Fexofenadine Hydrochloride'),
('Severe Congestion and Pain','acetaminophen, guaifenesin, phenylephrine hcl','Comprimé','ACETAMINOPHEN 325 mg/1','Orale','Family Dollar Services Inc','INT','Expectorant','Severe Congestion and Pain'),
('STERILE ALCOHOL PREP PADS 01','isopropyl alcohol','SWAB','ISOPROPYL ALCOHOL .7 mL/mL','Topique','Total Resources International Inc.','INT','Médicaments topiques','STERILE ALCOHOL PREP PADS 01'),
('Kali arsenicosum','potassium arsenite anhydrous','PELLET','POTASSIUM ARSENITE ANHYDROUS 200 [kp_C]/200[kp_C]','Orale','Boiron','INT',NULL,'Kali arsenicosum'),
('Medline Alcohol Swabstick Triples','isopropyl alcohol','SWAB','ISOPROPYL ALCOHOL 70 mL/100mL','Topique','Medline Industries, LP','INT','Médicaments topiques','Medline Alcohol Swabstick Triples'),
('Sei Bella CC Brightening Creme Medium Tan','octinoxate 7.5%, titanium dioxide 5%, zinc oxide 1%','Lotion','OCTINOXATE 2.475 g/33mL','Topique','Melaleuca Inc.','INT','Médicaments topiques','Sei Bella CC Brightening Creme Medium Tan'),
('Sun Logic Creme Solaire Visage et corps SPF 30','avobenzone, homosalate, octinoxate, octisalate, octocrylene','Lotion','AVOBENZONE 28.5 mg/mL','Topique','Guinot','INT','Médicaments topiques','Sun Logic Creme Solaire Visage et corps SPF 30'),
('Watermelon Hand Sanitizer Spray. 01','alcohol','Spray','ALCOHOL 70 mL/100mL','Topique','Shenzhen Lantern Scicence Co.,Ltd.','INT','Médicaments topiques','Watermelon Hand Sanitizer Spray. 01'),
('Strontium carbonicum','strontium carbonate','PELLET','STRONTIUM CARBONATE 30 [hp_C]/30[hp_C]','Orale','Boiron','INT',NULL,'Strontium carbonicum'),
('Airway Ease','influenzinum, antimon. tart., arsenicum alb., bryonia, chelidonium majus, cinchona, drosera, eucalyptus, histaminum hydrochloricum, hydrastis, kali bic., kali carb., kali iod., myrrha, nat. sulphuricum, nux vom., phosphorus, pulsatilla, rumex crisp., sambucus nig., spongia, tussilago farfara, verbascum, echinacea, lappa.','LIQUID','ANEMONE PULSATILLA 15 [hp_X]/mL','Orale','Newton Laboratories, Inc.','INT','Non-Standardized Plant Allergenic Extract','Airway Ease'),
('Hyperactivity-Mental Focus','adrenalinum, aconitum nap., arg. nit., arsenicum alb., baptisia, chamomilla, cypripedium, digitalis, gelsemium, humulus, ignatia, impatiens glandulifera flos, iodium, lachesis, lycopodium, nat. mur., nux vom., scutellaria lateriflora, staphysag., stramonium, theridion, echinacea, gingko, hypericum, passiflora','LIQUID','ACONITUM NAPELLUS 20 [hp_X]/mL','Orale','Newton Laboratories, Inc.','INT','Catecholamine','Hyperactivity-Mental Focus'),
('Cough Relief Adult','dextromethorphan hbr','LIQUID','DEXTROMETHORPHAN HYDROBROMIDE 15 mg/5mL','Orale','Dolgencorp, Inc. (DOLLAR GENERAL & REXALL)','INT','Sigma-1 Agonist','Cough Relief Adult'),
('Zylast Antiseptic','ethyl alcohol','Gel','ALCOHOL 44.9 mL/59.1mL','Topique','Innovative BioDefense','INT','Médicaments topiques','Zylast Antiseptic'),
('Lidonumb','lidocaine 5%','Crème','LIDOCAINE .05 g/g','Topique','Rising Pharma Holdings, Inc.','INT','Amide Local Anesthetic','Lidonumb'),
('Bach Original Flower Remedies Crab Apple','malus pumila','Solution','MALUS PUMILA FLOWER 5 [hp_X]/.095mL','Orale','Nelson Bach USA Limited','INT',NULL,'Bach Original Flower Remedies Crab Apple'),
('Bexsero','neisseria meningitidis serogroup b nhba fusion protein antigen, neisseria meningitidis serogroup b fhbp fusion protein antigen and neisseria meningitidis serogroup b nada protein antigen','Suspension','NEISSERIA MENINGITIDIS GROUP B FHBP FUSION PROTEIN ANTIGEN 50 ug/.5mL','Intramusculaire','GlaxoSmithKline Biologicals SA','US',NULL,'Bexsero'),
('SHISEIDO UV PROTECTIVE COMPACT (REFILL) LIGHT IVORY','octinoxate, octocrylene, and titanium dioxide','Poudre','OCTINOXATE 888 mg/12g','Topique','SHISEIDO AMERICAS CORPORATION','INT','Médicaments topiques','SHISEIDO UV PROTECTIVE COMPACT (REFILL) LIGHT IVORY'),
('Arnica Power','arnica montana','LIQUID','ARNICA MONTANA WHOLE 3 [hp_X]/41mL','Orale','Eight and Company L.L.C','INT',NULL,'Arnica Power'),
('ALOE ICE SPF 50','avobenzone, homosalate, octisalate, octocrylene, oxybenzone','Spray','AVOBENZONE 3 g/100mL','Topique','Aloe Care International, LLC','INT','Médicaments topiques','ALOE ICE SPF 50'),
('Lextol','diclofenac sodium, capsaicin','Kit',NULL,NULL,'PureTek Corporation','INT',NULL,'Lextol'),
('CVS SPF 30 Sport','avobenzone, homosalate, octocrylene','Spray','AVOBENZONE 2 g/100g','Topique','CVS Pharmacy','INT','Médicaments topiques','CVS SPF 30 Sport'),
('Clear Cell Clarifying Acne','benzoyl peroxide','Lotion','BENZOYL PEROXIDE 50 mg/g','Topique','Allure Labs','INT','Médicaments topiques','Clear Cell Clarifying Acne'),
('Nu Colour Bioadaptive BB Plus Foundation - Light Golden','titanium dioxide','Lotion','TITANIUM DIOXIDE 120 mg/mL','Topique','NSE Products, Inc.','INT','Médicaments topiques','Nu Colour Bioadaptive BB Plus Foundation - Light Golden')
) AS v(nom, dci, forme, dosage, voie, labo, pays, classe, nomcom)
WHERE NOT EXISTS (
  SELECT 1 FROM medicaments m WHERE UPPER(m.nom) = UPPER(v.nom)
);
