-- ndc_batch_017.sql (80 rows)
INSERT INTO medicaments (nom, dci, forme, dosage, voie_administration, laboratoire, pays, classe_therapeutique, nom_commercial)
SELECT v.nom, v.dci, v.forme, v.dosage, v.voie, v.labo, v.pays, v.classe, v.nomcom
FROM (VALUES
('Salonpas Pain Relieving LIDOCAINE 4% FLEX','lidocaine','Patch transdermique','LIDOCAINE 42 mg/1','PERCUTANEOUS','Hisamitsu Pharmaceutical Co., Inc.','INT','Amide Local Anesthetic','Salonpas Pain Relieving LIDOCAINE 4% FLEX'),
('EcoCare 360','benzalkonium','Solution','BENZALKONIUM CHLORIDE .1 mg/100mL','Topique','Ecolab Inc.','INT','Médicaments topiques','EcoCare 360'),
('Medique Medi-Meclizine','meclizine hcl','Comprimé','MECLIZINE HYDROCHLORIDE 25 mg/1','Orale','Unifirst First Aid Corporation','INT','Antiemetic','Medique Medi-Meclizine'),
('Plantago Pyrite','plantago pyrite','LIQUID','ABIES ALBA LEAFY TWIG 6 [hp_X]/mL','Orale','Uriel Pharmacy Inc.','INT','Non-Standardized Food Allergenic Extract','Plantago Pyrite'),
('ALECENSA','alectinib hydrochloride','Gélule','ALECTINIB HYDROCHLORIDE 150 mg/1','Orale','Genentech, Inc.','US','Kinase Inhibitor','ALECENSA'),
('Artistry Exact Fit Longwearing Foundation SPF 15 Broad Spectrum Sunscreen','titanium dioxide','Crème','TITANIUM DIOXIDE 40.25 mg/mL','Topique','Amway Corp','INT','Médicaments topiques','Artistry Exact Fit Longwearing Foundation SPF 15 Broad Spectrum Sunscreen'),
('SOFT TOUCH PLUS ANTIBACTERIAL HAND ITEM 1039','chloroxylenol','SOAP','CHLOROXYLENOL .3 g/100mL','Topique','AMERICAN CHEMICAL AND SANITARY SUPPLY INC','INT','Médicaments topiques','SOFT TOUCH PLUS ANTIBACTERIAL HAND ITEM 1039'),
('Baryta carbonica','barium carbonate','PELLET','BARIUM CARBONATE 1 [hp_M]/[hp_M]','Orale','Boiron','INT',NULL,'Baryta carbonica'),
('Isosorbide Mononitrate','isosorbide mononitrate','Comprimé','ISOSORBIDE MONONITRATE 60 mg/1','Orale','A-S Medication Solutions','US','Nitrate Vasodilator','Isosorbide Mononitrate'),
('Glimepiride','glimepiride','Comprimé','GLIMEPIRIDE 2 mg/1','Orale','A-S Medication Solutions','US','Sulfonylurea','Glimepiride'),
('Diphenhydramine HCL','diphenhydramine hcl','Gélule','DIPHENHYDRAMINE HYDROCHLORIDE 25 mg/1','Orale','A-S Medication Solutions','INT','Histamine-1 Receptor Antagonist','Diphenhydramine HCL'),
('liothyronine sodium','liothyronine sodium','Comprimé','LIOTHYRONINE SODIUM 5 ug/1','Orale','A-S Medication Solutions','US','l-Triiodothyronine','liothyronine sodium'),
('Lutera','levonorgestrel and ethinyl estradiol','Kit',NULL,NULL,'Mayne Pharma Inc.','US',NULL,'Lutera'),
('SUPRESS A','dexbromopheniramine maleate, dextromethorphan hbr, phenylephrine hcl','Sirop','DEXBROMPHENIRAMINE MALEATE 1 mg/mL','Orale','Kramer Novis','INT','Sigma-1 Agonist','SUPRESS A'),
('AmeriDerm Antibacterial Wash','parachlorometaxylenol','LIQUID','CHLOROXYLENOL .003 mg/mL','Topique','SHIELD LINE LLC','INT','Médicaments topiques','AmeriDerm Antibacterial Wash'),
('Refill 4','isopropyl alcohol','CLOTH','ISOPROPYL ALCOHOL 70 g/100g','Topique','GFA Production (Xiamen) Co., Ltd.','INT','Médicaments topiques','Refill 4'),
('Olanzapine','olanzapine','Comprimé','OLANZAPINE 5 mg/1','Orale','Golden State Medical Supply, Inc.','US','Atypical Antipsychotic','Olanzapine'),
('Gallicum acidum','gallic acid monohydrate','PELLET','GALLIC ACID MONOHYDRATE 6 [hp_C]/6[hp_C]','Orale','Boiron','INT',NULL,'Gallicum acidum'),
('Sugar Free Cough Drops','honey lemon','PASTILLE','MENTHOL 7.6 mg/1','Orale','CVS Pharmacy','INT',NULL,'Sugar Free Cough Drops'),
('Glonoinum','nitroglycerin','PELLET','NITROGLYCERIN 5 [hp_C]/5[hp_C]','Orale','Boiron','INT','Nitrate Vasodilator','Glonoinum'),
('Graphites','graphite','PELLET','GRAPHITE 12 [hp_C]/12[hp_C]','Orale','Boiron','INT',NULL,'Graphites'),
('6% HETASTARCH IN 0.9% SODIUM CHLORIDE','6% hetastarch in 0.9% sodium chloride','Solution','HETASTARCH 6 g/100mL','Intraveineuse','HF Acquisition Co LLC, DBA HealthFirst','US','Plasma Volume Expander','6% HETASTARCH IN 0.9% SODIUM CHLORIDE'),
('EPINEPHRINE','epinephrine','Solution injectable','EPINEPHRINE .1 mg/mL','Intraveineuse','HF Acquisition Co LLC, DBA HealthFirst','US','Catecholamine','EPINEPHRINE'),
('Nux vomica','strychnos nux-vomica seed','PELLET','STRYCHNOS NUX-VOMICA SEED 6 [hp_X]/6[hp_X]','Orale','Boiron','INT','Non-Standardized Plant Allergenic Extract','Nux vomica'),
('Family Wellness Anorectal Lidocaine','anorectal lidocaine','Crème','LIDOCAINE 50 mg/g','Topique','FAMILY DOLLAR (Family Wellness)','INT','Amide Local Anesthetic','Family Wellness Anorectal Lidocaine'),
('Phosphoricum acidum','phosphoric acid','PELLET','PHOSPHORIC ACID 6 [hp_C]/6[hp_C]','Orale','Boiron','INT',NULL,'Phosphoricum acidum'),
('Aseptil Rojo','phenol','Spray','PHENOL 1.4 mg/100mL','Topique','Menper Distributors, Inc.','INT','Médicaments topiques','Aseptil Rojo'),
('Curad Alcohol Prep Pads Medium','isopropyl alcohol','SWAB','ISOPROPYL ALCOHOL 70 mL/100mL','Topique','Medline Industries, LP','INT','Médicaments topiques','Curad Alcohol Prep Pads Medium'),
('Formicum Acidum 6X','formicum acidum 6x','LIQUID','FORMIC ACID 6 [hp_X]/30mL','Orale','True Botanica, LLC','INT',NULL,'Formicum Acidum 6X'),
('Sei Bella Tinted BB Moisturizing Creme Medium 440 N','titanium dioxide 5% and zinc oxide 5%','Lotion','TITANIUM DIOXIDE 1.5 g/30mL','Topique','Melaleuca Inc.','INT','Médicaments topiques','Sei Bella Tinted BB Moisturizing Creme Medium 440 N'),
('Licensed Hand Sanitizer Hot Wheels 01','alcohol','Spray','ALCOHOL 70 mL/100mL','Topique','Shenzhen Lantern Scicence Co.,Ltd.','INT','Médicaments topiques','Licensed Hand Sanitizer Hot Wheels 01'),
('Oxygen/Helium 20/80','oxygen/helium 20/80','GAS','OXYGEN 200 mL/L','Inhalation','MATHESON TRI-GAS, INC.','US',NULL,'Oxygen/Helium 20/80'),
('SHISEIDO REVITALESSENCE SKIN GLOW FOUNDATION 530','octinoxate','EMULSION','OCTINOXATE 2.30805 g/30mL','Topique','SHISEIDO AMERICAS CORPORATION','INT','Médicaments topiques','SHISEIDO REVITALESSENCE SKIN GLOW FOUNDATION 530'),
('Rompe Pecho Nighttime','acetaminophen, dextromethorphan hbr, doxylamine succinate, phenylephrine hcl','LIQUID','ACETAMINOPHEN 650 mg/30mL','Orale','EFFICIENT LABORATORIES INC','INT','Antihistamine','Rompe Pecho Nighttime'),
('Bedwetting','echinacea, hydrastis canadensis, passiflora incarnata, valeriana officinalis, belladonna, cantharis, causticum, equisetum hyemale, ferrum metallicum, gelsemium sempervirens, humulus lupulus, kali phosphoricum, lycopodium clavatum, natrum muriaticum, plantago major, pulsatilla, rhus aromatica, sabal serrulata, thyroidinum, verbascum thapsus','PELLET','ANEMONE PULSATILLA 15 [hp_X]/g','Orale','Newton Laboratories, Inc.','INT','Non-Standardized Food Allergenic Extract','Bedwetting'),
('V-Fem Care','agaricus musc., arsenicum alb., aur. met., berber. aqui., caladium seguinum, candida albicans, cantharis, conium, graphites, helonias dioica, hydrastis, kali carb., kreosotum, lycopodium, merc. viv., murex purpurea, nat. mur., nitricum ac., pulsatilla, rhus toxicodendron, sepia, sulphur, tarentula hispana, thuja occ., zinc. met., apis mel., hamamelis','LIQUID','AMANITA MUSCARIA FRUITING BODY 15 [hp_X]/mL','Orale','Newton Laboratories, Inc.','INT','Non-Standardized Fungal Allergenic Extract','V-Fem Care'),
('Mouth Rinse','eucalyptol, menthol, methyl salicylate, thymol','MOUTHWASH','EUCALYPTOL .92 mg/mL','Orale','Old East Main Co.','INT',NULL,'Mouth Rinse'),
('Sleep Aid NightTime','diphenhydramine hcl','LIQUID','DIPHENHYDRAMINE HYDROCHLORIDE 50 mg/30mL','Orale','Dolgencorp, Inc. (DOLLAR GENERAL & REXALL)','INT','Histamine-1 Receptor Antagonist','Sleep Aid NightTime'),
('Antiseptic Wipes','zylast hand wipes','SWAB','ALCOHOL 76 mL/100mL','Topique','Westwood Laboratories','INT','Médicaments topiques','Antiseptic Wipes'),
('Anti- Fungal Miconazole Nitrate','miconazole nitrate','Poudre','MICONAZOLE NITRATE 1.42 g/71g','Topique','Premier Brands of America Inc.','INT','Azole Antifungal','Anti- Fungal Miconazole Nitrate'),
('Bach Original Flower Remedies Heather','calluna vulgaris','Solution','CALLUNA VULGARIS FLOWERING TOP 5 [hp_X]/.095mL','Orale','Nelson Bach USA Limited','INT',NULL,'Bach Original Flower Remedies Heather'),
('GeriCare Sorbitol Solution','sorbitol','LIQUID','SORBITOL 70 mg/100mL','Rectale','GERI-CARE PHARMACEUTICALS, CORP','INT',NULL,'GeriCare Sorbitol Solution'),
('T-13','ulex europaeus whole','Solution','ULEX EUROPAEUS WHOLE 30 [hp_X]/mL','Sublinguale','DNA Labs, Inc.','INT',NULL,'T-13'),
('SHISEIDO UV PROTECTIVE COMPACT (REFILL) MEDIUM OCHRE','octinoxate, octocrylene, and titanium dioxide','Poudre','OCTINOXATE 888 mg/12g','Topique','SHISEIDO AMERICAS CORPORATION','INT','Médicaments topiques','SHISEIDO UV PROTECTIVE COMPACT (REFILL) MEDIUM OCHRE'),
('Body Balance','aralia quin, arnica, avena, carduus mar, elaeis, glandula suprarenalis suis, nat mur, phosphoricum ac, thuja occ','LIQUID','AMERICAN GINSENG 4 [hp_X]/41mL','Orale','Eight and Company L.L.C','INT',NULL,'Body Balance'),
('ALOE UP SPORT SPF-15','avobenzone, homosalate, octisalate, octocrylene','Lotion','AVOBENZONE 2 g/100mL','Topique','Aloe Care International, LLC','INT','Médicaments topiques','ALOE UP SPORT SPF-15'),
('DermacinRx PHN Pak','lidocaine','Kit',NULL,NULL,'PureTek Corporation','INT',NULL,'DermacinRx PHN Pak'),
('ETHYL ALCOHOL','alcohol','Gel','ALCOHOL 70 mL/100mL','Topique','ASP Global LLC','INT','Médicaments topiques','ETHYL ALCOHOL'),
('sugar free menthol cough drops','menthol','Pastille','MENTHOL 5.8 mg/1','Orale','CVS Pharmacy','INT',NULL,'sugar free menthol cough drops'),
('Syphilinum','treponemic skin canker human','PELLET','TREPONEMIC SKIN CANKER HUMAN 30 [hp_C]/30[hp_C]','Orale','Boiron','INT',NULL,'Syphilinum'),
('DIARALIA','arsenic trioxide,cinchona officinalis bark, podophyllum','Comprimé','ARSENIC TRIOXIDE 9 [hp_C]/1','Orale','BOIRON','INT',NULL,'DIARALIA'),
('Voriconazole','voriconazole','Comprimé','VORICONAZOLE 200 mg/1','Orale','American Health Packaging','US','Azole Antifungal','Voriconazole'),
('I Conceal Flawless Foundation Broad Spectrum SPF 30 Sunscreen Mahogany','zinc oxide and titanium dioxide','Crème','TITANIUM DIOXIDE 65 mg/g','Topique','Allure Labs','INT','Médicaments topiques','I Conceal Flawless Foundation Broad Spectrum SPF 30 Sunscreen Mahogany'),
('Nu Colour Bioadaptive BB plus Foundation - Medium Beige','titanium dioxide','Lotion','TITANIUM DIOXIDE 130 mg/mL','Topique','NSE Products, Inc.','INT','Médicaments topiques','Nu Colour Bioadaptive BB plus Foundation - Medium Beige'),
('Kidney Stone Drops 2039','kidney stone drops','LIQUID','BERBERIS VULGARIS ROOT BARK 6 [hp_X]/59mL','Orale','Professional Complementary Health Formulas','INT',NULL,'Kidney Stone Drops 2039'),
('BARLEY','hordeum vulgare','Solution','BARLEY .1 g/mL','PERCUTANEOUS','ALK-Abello, Inc.','US','Non-Standardized Food Allergenic Extract','BARLEY'),
('Obagi-C Fx System Normal-Oily Skin Brightening System with Arbutin','homosalate, octisalate, zinc oxide','Kit',NULL,NULL,'Obagi Cosmeceuticals LLC','INT',NULL,'Obagi-C Fx System Normal-Oily Skin Brightening System with Arbutin'),
('Dior Forever Skin Wear Flawless Skin True Foundation SPF 20 4,5N Neutral','octisalate, titanium dioxide','EMULSION','OCTISALATE 35 mg/mL','Topique','Parfums Christian Dior','INT','Médicaments topiques','Dior Forever Skin Wear Flawless Skin True Foundation SPF 20 4,5N Neutral'),
('Griseofulvin','griseofulvin (microsize)','Suspension','GRISEOFULVIN 125 mg/5mL','Orale','Chartwell RX, LLC.','US','Tubulin Inhibiting Agent','Griseofulvin'),
('Steritalc 2g','talc','Poudre','TALC 2 g/50mL','INTRAPLEURAL','Novatech SA','US',NULL,'Steritalc 2g'),
('Anti Bacterial Hand Gel Sweetest Song','alcohol','Gel','ALCOHOL 71 mL/100mL','Topique','Bath & Body Works, Inc.','INT','Médicaments topiques','Anti Bacterial Hand Gel Sweetest Song'),
('Hyoscyamine Sulfate TAB','hyoscyamine sulfate','Comprimé','HYOSCYAMINE SULFATE .125 mg/1','Orale','Bryant Ranch Prepack','INT',NULL,'Hyoscyamine Sulfate TAB'),
('Animal Pathogens Nosode Combination 9419','animal pathogens nosode combination','LIQUID','BAPTISIA TINCTORIA WHOLE 3 [hp_X]/29.5mL','Orale','Professional Complementary Health Formulas','INT',NULL,'Animal Pathogens Nosode Combination 9419'),
('ROBITUSSIN COUGH PLUS CHEST CONGESTION DM','dextromethorphan hydrobromide and guaifenesin','Solution','DEXTROMETHORPHAN HYDROBROMIDE 20 mg/20mL','Orale','Haleon US Holdings LLC','INT','Expectorant','ROBITUSSIN COUGH PLUS CHEST CONGESTION DM'),
('TURKEY','meleagris gallopavo','Solution','TURKEY .1 g/mL','PERCUTANEOUS','ALK-Abello, Inc.','US','Non-Standardized Food Allergenic Extract','TURKEY'),
('ADRENAL STIM Formula','betula pendula folia bos taurus adrenal gland, castanea vesca, poplar bud, rna','Solution','BETULA PENDULA LEAF 2 [hp_X]/mL','Sublinguale','Apex Energetics Inc.','INT',NULL,'ADRENAL STIM Formula'),
('Arsenicum Iodatum','arsenicum iodatum','PELLET','ARSENIC TRIIODIDE 6 [hp_C]/1','Orale','Hahnemann Laboratories, Inc.','INT',NULL,'Arsenicum Iodatum'),
('Childrens Allergy Relief','fexofenadine hcl','Comprimé','FEXOFENADINE HYDROCHLORIDE 30 mg/1','Orale','PLD Acquisitions LLC DBA Avma Pharma Solutions','US','Histamine-1 Receptor Antagonist','Childrens Allergy Relief'),
('Micatin','miconazole nitrate','Crème','MICONAZOLE NITRATE 20 mg/g','Topique','WellSpring Pharmaceutical Corporation','INT','Azole Antifungal','Micatin'),
('NICARDIPINE HYDROCHLORIDE','nicardipine hydrochloride','Solution injectable','NICARDIPINE HYDROCHLORIDE 25 mg/10mL','Intraveineuse','Fresenius Kabi USA, LLC','US','Dihydropyridine Calcium Channel Blocker','NICARDIPINE HYDROCHLORIDE'),
('Best Choice Assorted Fruit','calcium carbonate','Comprimé','CALCIUM CARBONATE 500 mg/1','Orale','BEST CHOICE (VALU MERCHANDISERS COMPANY)','INT','Blood Coagulation Factor','Best Choice Assorted Fruit'),
('kirkland signature acid controller','famotidine','Comprimé','FAMOTIDINE 20 mg/1','Orale','Costco Wholesale Company','US','Histamine-2 Receptor Antagonist','kirkland signature acid controller'),
('Nix','permethrin','RINSE','PERMETHRIN 1 g/100mL','Topique','Insight Pharmaceuticals LLC','US','Pyrethroid','Nix'),
('QC Regular Strength','antacid','Comprimé','CALCIUM CARBONATE 500 mg/1','Orale','QUALITY CHOICE (CHAIN DRUG MARKETING ASSOCIATION)','INT',NULL,'QC Regular Strength'),
('RadDefense 2','raddefense2','LIQUID','CALIFORNIUM CF-249 30 [hp_C]/.03mL','Orale','Vitality Works, Inc.','INT',NULL,'RadDefense 2'),
('Premphase','conjugated estrogens and medroxyprogesterone acetate','Kit',NULL,NULL,'Wyeth Pharmaceuticals LLC, a subsidiary of Pfizer Inc.','US',NULL,'Premphase'),
('Almay Clear Complexion Makeup Warm Beige','salicylic acid','LIQUID','SALICYLIC ACID 2 mg/2mL','Topique','Almay','INT','Médicaments topiques','Almay Clear Complexion Makeup Warm Beige'),
('Molds - Mold Mix 10','molds - mold mix 10','Solution','ALTERNARIA ALTERNATA .1 g/mL','PERCUTANEOUS','Jubilant HollisterStier LLC','US','Non-Standardized Fungal Allergenic Extract','Molds - Mold Mix 10'),
('Ipratropium Bromide and Albuterol Sulfate','ipratropium bromide and albuterol sulfate','Solution','ALBUTEROL SULFATE 2.5 mg/3mL','Inhalation','Aurobindo Pharma Limited','US','Anticholinergic','Ipratropium Bromide and Albuterol Sulfate'),
('Emvita 16','aconitum napellus, ambra grisea, eschscholtzia, secale, thymus gland, zinc met','LIQUID','ACONITUM NAPELLUS WHOLE 800 [hp_C]/60mL','Orale','RUBIMED AG','INT',NULL,'Emvita 16')
) AS v(nom, dci, forme, dosage, voie, labo, pays, classe, nomcom)
WHERE NOT EXISTS (
  SELECT 1 FROM medicaments m WHERE UPPER(m.nom) = UPPER(v.nom)
);
