-- ndc_batch_078.sql (80 rows)
INSERT INTO medicaments (nom, dci, forme, dosage, voie_administration, laboratoire, pays, classe_therapeutique, nom_commercial)
SELECT v.nom, v.dci, v.forme, v.dosage, v.voie, v.labo, v.pays, v.classe, v.nomcom
FROM (VALUES
('CETAFEN EXTRA','acetaminophen','Comprimé','ACETAMINOPHEN 500 mg/1','Orale','HART Health','INT',NULL,'CETAFEN EXTRA'),
('Laxacin','docusate sodium and sennosides','Comprimé','DOCUSATE SODIUM 50 mg/1','Orale','Alexso, Inc','INT',NULL,'Laxacin'),
('Depo-Medrol','methylprednisolone acetate','Suspension','METHYLPREDNISOLONE ACETATE 40 mg/mL','INTRALESIONAL','Pharmacia & Upjohn Company LLC','US','Corticosteroid','Depo-Medrol'),
('Lidocaine Viscous','lidocaine hydrochloride','Solution','LIDOCAINE HYDROCHLORIDE 20 mg/mL','Orale','A-S Medication Solutions','US','Amide Local Anesthetic','Lidocaine Viscous'),
('TACLONEX','calcipotriene and betamethasone dipropionate','Suspension','BETAMETHASONE DIPROPIONATE .5 mg/g','Topique','LEO Pharma Inc.','US','Corticosteroid','TACLONEX'),
('4% Menthol PAIN RELIEF','menthol','Gel','MENTHOL, UNSPECIFIED FORM 4 g/100mL','Topique','Universal Distribution Center LLC','INT','Médicaments topiques','4% Menthol PAIN RELIEF'),
('Simply White Clean Mint','sodium fluoride','PASTE, DENTIFRICE','SODIUM FLUORIDE .00243 g/g','DENTAL','Tom''s of Maine, Inc.','INT',NULL,'Simply White Clean Mint'),
('Salicylic Acid Wart Remover','salicylic acid','STRIP','SALICYLIC ACID 40 mg/1','Topique','ASO Pharmaceutical Co. Ltd.','INT','Médicaments topiques','Salicylic Acid Wart Remover'),
('CVS PHARMACY Extra Strength Cherry Flavor','aluminum hydroxide and magnesium carbonate','Comprimé','ALUMINUM HYDROXIDE 160 mg/1','Orale','CVS Pharmacy,Inc.','INT',NULL,'CVS PHARMACY Extra Strength Cherry Flavor'),
('CVS Cooling Patch','menthol','Patch transdermique','MENTHOL, UNSPECIFIED FORM .5 g/10g','Topique','CVS Pharmacy','INT','Médicaments topiques','CVS Cooling Patch'),
('VERAPAMIL HCI','verapamil hci','Solution','VERAPAMIL HYDROCHLORIDE 2.5 mg/mL','Intraveineuse','HF Acquisition Co LLC, DBA HealthFirst','US','Calcium Channel Blocker','VERAPAMIL HCI'),
('Frenna AC','aluminum chloride','Solution','ALUMINUM CHLORIDE 8.75 g/35g','DENTAL','Dharma Research, inc.','INT',NULL,'Frenna AC'),
('Apis Mell.','apis mell.','GLOBULE','APIS MELLIFERA VENOM 6 [hp_X]/23g','Orale','True Botanica, LLC','INT',NULL,'Apis Mell.'),
('XYOSTED','testosterone enanthate','Solution injectable','TESTOSTERONE ENANTHATE 100 mg/.5mL','Sous-cutanée','Antares Pharma, Inc.','US','Androgen','XYOSTED'),
('Kids Cold and Cough Combo Pack','onion, chamomile, arabica coffee bean, calcium sulfide, golden seal, sodium chloride, phosphorus, pulsatilla vulgaris top, sulfur','Kit',NULL,'Orale','Hyland''s Consumer Health Inc.','INT',NULL,'Kids Cold and Cough Combo Pack'),
('IBU','ibuprofen','Comprimé','IBUPROFEN 400 mg/1','Orale','Dr. Reddy''s Laboratories Limited','US','Nonsteroidal Anti-inflammatory Drug','IBU'),
('SHISEIDO REVITALESSENCE SKIN GLOW FOUNDATION 150','octinoxate','EMULSION','OCTINOXATE 2.30805 g/30mL','Topique','SHISEIDO AMERICAS CORPORATION','INT','Médicaments topiques','SHISEIDO REVITALESSENCE SKIN GLOW FOUNDATION 150'),
('Rompe Pecho SF Flu SF Flu','brompheniramine maleate, dextromethorphan hbr','LIQUID','BROMPHENIRAMINE MALEATE 4 mg/5mL','Orale','Efficient Laboratories Inc','INT','Sigma-1 Agonist','Rompe Pecho SF Flu SF Flu'),
('Estomaquil Polvo','bismuth subsalicylate','Poudre','BISMUTH SUBSALICYLATE 262 mg/1','Orale','ProMex LLC','INT',NULL,'Estomaquil Polvo'),
('Atrix System 1','salicylic acid','Kit',NULL,NULL,'PureTek Corporation','INT',NULL,'Atrix System 1'),
('Vapor Inhaler levmetamfetamine nasal decongestant, DG health','levmetamfetamine','INHALANT','LEVMETAMFETAMINE 50 mg/1','Nasale','Dolgencorp Inc.','INT',NULL,'Vapor Inhaler levmetamfetamine nasal decongestant, DG health'),
('INFANRIX','diphtheria and tetanus toxoids and acellular pertussis vaccine adsorbed','Suspension','BORDETELLA PERTUSSIS FILAMENTOUS HEMAGGLUTININ ANTIGEN (FORMALDEHYDE INACTIVATED) 25 ug/.5mL','Intramusculaire','GlaxoSmithKline Biologicals SA','US','Inactivated Bordetella Pertussis Vaccine','INFANRIX'),
('N-17','zinc, selenium, bos taurus thymus, sus scrofa spleen, bos taurus lymph, bos taurus adrenal gland, arginine, cystine, echinacea angustifolia, thiamine, pyridoxine hydrochloride, and ascorbic acid','Solution','ARGININE 4 [hp_X]/mL','Sublinguale','DNA Labs, Inc.','INT','Vitamin B6 Analog','N-17'),
('cle de peau BEAUTE THE FOUNDATION N M O40','octinoxate and titanium dioxide','PASTE','OCTINOXATE 1.165 g/28mL','Topique','Shiseido Americas Corporation','INT','Médicaments topiques','cle de peau BEAUTE THE FOUNDATION N M O40'),
('H-Insomnia Formula','apium graveolens, salvia officinalis','OIL','CELERY SEED 6 [hp_C]/11mL','Topique','Healing Natural Oils LLC','INT','Non-Standardized Food Allergenic Extract','H-Insomnia Formula'),
('A PERFECT WORLD SPF 40 AGE DEFENSE BROAD SPECTRUM MOISTURIZER WITH WHITE TEA','avobenzone, homosalate, octinoxate, octisalate, and octocrylene','Crème','AVOBENZONE 30 mg/mL','Topique','ORIGINS NATURAL RESOURCES INC.','INT','Médicaments topiques','A PERFECT WORLD SPF 40 AGE DEFENSE BROAD SPECTRUM MOISTURIZER WITH WHITE TEA'),
('Fetroja','cefiderocol sulfate tosylate','Solution','CEFIDEROCOL SULFATE TOSYLATE 1 g/10mL','Intraveineuse','Shionogi Inc.','US','Cephalosporin Antibacterial','Fetroja'),
('Duke Midnight Swim Antiperspirant','aluminum zirconium trichlorohydrex gly','STICK','ALUMINUM ZIRCONIUM TRICHLOROHYDREX GLY .2 g/1','Topique','RNA PHARMA, LLC','INT','Médicaments topiques','Duke Midnight Swim Antiperspirant'),
('Cover Recover SPF 30 Warm Beige','zinc oxide and titanium dioxide','Crème','TITANIUM DIOXIDE 65 mg/mL','Topique','Allure Labs, Inc','INT','Copper Absorption Inhibitor','Cover Recover SPF 30 Warm Beige'),
('GENUINE JOE Cleaning Supplies Antibacterial Foam So ap Refill','chloroxylenol','LIQUID','CHLOROXYLENOL .003 mg/mL','Topique','S.P. Richards Company','INT','Médicaments topiques','GENUINE JOE Cleaning Supplies Antibacterial Foam So ap Refill'),
('Degex Drops 2017','degex drops','LIQUID','ACTIVATED CHARCOAL 6 [hp_X]/59mL','Orale','Professional Complementary Health Formulas','INT',NULL,'Degex Drops 2017'),
('Lymph/Spleen/Mammary Drops 5014','lymph/spleen/mammary drops','LIQUID','ARSENIC TRIOXIDE 6 [hp_X]/59mL','Orale','Professional Complementary Health Formulas','INT',NULL,'Lymph/Spleen/Mammary Drops 5014'),
('Obagi Medical Physical Defense Broad Spectrum Mineral Sunscreen SPF 50 by SUZANOBAGIMD','titanium dioxide and zinc oxide','Crème','TITANIUM DIOXIDE 58 mg/g','Topique','Obagi Cosmeceuticals LLC','INT','Médicaments topiques','Obagi Medical Physical Defense Broad Spectrum Mineral Sunscreen SPF 50 by SUZANOBAGIMD'),
('Dior Forever Skin Wear Flawless Skin True Foundation SPF 20 0N Neutral','octisalate, titanium dioxide','EMULSION','OCTISALATE 35 mg/mL','Topique','Parfums Christian Dior','INT','Médicaments topiques','Dior Forever Skin Wear Flawless Skin True Foundation SPF 20 0N Neutral'),
('Antiperspirant Deodorant Champagne Toast','aluminum zirconium trichlorohydrex gly','STICK','ALUMINUM ZIRCONIUM TRICHLOROHYDREX GLY 16 g/100g','Topique','Bath and Body Works, Distr.','INT','Médicaments topiques','Antiperspirant Deodorant Champagne Toast'),
('Tri-Lo- Estarylla','norgestimate and ethinyl estradiol','Kit',NULL,NULL,'Bryant Ranch Prepack','US',NULL,'Tri-Lo- Estarylla'),
('Nitro-Thio Combination 9318','nitro-thio combination','LIQUID','ALDICARB 12 [hp_X]/29.5mL','Orale','Professional Complementary Health Formulas','INT','Non-Standardized Plant Allergenic Extract','Nitro-Thio Combination 9318'),
('ACER SACCHARUM POLLEN','sugar maple','Solution','ACER SACCHARUM POLLEN .05 g/mL','PERCUTANEOUS','ALK-Abello, Inc.','US','Non-Standardized Pollen Allergenic Extract','ACER SACCHARUM POLLEN'),
('Robitussin Direct Cough','dextromethorphan hydrobromide','Gélule','DEXTROMETHORPHAN HYDROBROMIDE 15 mg/1','Orale','Haleon US Holdings LLC','INT','Sigma-1 Agonist','Robitussin Direct Cough'),
('HALIBUT','hippoglossus hippoglossus','Solution','ATLANTIC HALIBUT .1 g/mL','PERCUTANEOUS','ALK-Abello, Inc.','US','Non-Standardized Food Allergenic Extract','HALIBUT'),
('R01 LIVER','adenosine triphosphate, matricaria chamomilla, lycopodium clavatum spore, strychnos nux-vomica seed, phosphorus','Solution','ADENOSINE TRIPHOSPHATE 5 [hp_X]/mL','Sublinguale','Apex Energetics Inc.','INT','Non-Standardized Plant Allergenic Extract','R01 LIVER'),
('SUGAR FREE SWISS CHERRY HERB THROAT DROPS','menthol','Pastille','MENTHOL 2.2 mg/1','Orale','Ricola USA Inc.','INT',NULL,'SUGAR FREE SWISS CHERRY HERB THROAT DROPS'),
('Fem Response','female reproductive booster','LIQUID','APOCYNUM CANNABINUM ROOT 7 [hp_X]/mL','Orale','Vitality Works, Inc.','INT',NULL,'Fem Response'),
('Ponds','rejuveness anti-wrinkle daily moisturizer with sunscreen spf 30','Crème','OCTINOXATE 7 g/100g','Topique','CONOPCO Inc. d/b/a Unilever','INT','Médicaments topiques','Ponds'),
('Pollens - Weeds, Careless/Pigweed Mix','careless/pigweed mix','Solution','AMARANTHUS PALMERI POLLEN .05 g/mL','PERCUTANEOUS','Jubilant HollisterStier LLC','US','Non-Standardized Pollen Allergenic Extract','Pollens - Weeds, Careless/Pigweed Mix'),
('Glucotrol XL','glipizide','Comprimé','GLIPIZIDE 5 mg/1','Orale','Roerig','US','Sulfonylurea','Glucotrol XL'),
('OHM-PAN','carbo vegetabilis, ceanothus americanus, gallium aparine, leptandra virginica, mandragora officinarum, momordica balsamina, quassia amara','Spray','ACTIVATED CHARCOAL 12 [hp_X]/30mL','Orale','OHM PHARMA INC.','INT',NULL,'OHM-PAN'),
('Excedrin Extra Strength, CVP HEALTH','acetaminophen, aspirin, and caffeine','Comprimé','ACETAMINOPHEN 250 mg/1','Orale','Lil Drug Store Products, Inc','INT','Central Nervous System Stimulant','Excedrin Extra Strength, CVP HEALTH'),
('Atropine','atropine sulfate','Solution','ATROPINE SULFATE 10 mg/mL','Ophtalmique','Redpharm Drug','US','Anticholinergic','Atropine'),
('Acne Cleanser','salicylic acid','LIQUID','SALICYLIC ACID 1.15 mg/230mL','Topique','Spa de Soleil','INT','Médicaments topiques','Acne Cleanser'),
('Alphanate','antihemophilic factor/von willebrand factor complex (human)','Kit',NULL,'Intraveineuse','GRIFOLS USA, LLC','US','Médicaments IV / Hospitaliers','Alphanate'),
('NativeRemedies Triple Complex BronchoSoothe','kali phos, mag phos, nat sulph','LIQUID','MAGNESIUM PHOSPHATE, DIBASIC TRIHYDRATE 8 [hp_X]/59mL','Orale','Silver Star Brands','INT','Calculi Dissolution Agent','NativeRemedies Triple Complex BronchoSoothe'),
('Azithromycin monohydrate','azithromycin monohydrate','Solution','AZITHROMYCIN MONOHYDRATE 500 mg/10mL','Intraveineuse','Gland Pharma Limited','US','Macrolide Antimicrobial','Azithromycin monohydrate'),
('Fast Acting Heartburn Relief Peppermint Flavor','calcium carbonate','Comprimé','CALCIUM CARBONATE 500 mg/1','Orale','Raritan Pharmaceuticals Inc','INT',NULL,'Fast Acting Heartburn Relief Peppermint Flavor'),
('Always Liquid Foundation Makeup Sunscreen Broad Spectrum SPF 15- Bisque','homosalate, octisalate, zinc oxide','LIQUID','HOMOSALATE 4.25 g/100mL','Topique','Distribuidora Comercial Jafra, S.A. de C.V','INT','Médicaments topiques','Always Liquid Foundation Makeup Sunscreen Broad Spectrum SPF 15- Bisque'),
('Sun Bum Tinted Sunscreen Lip Balm Broad Spectrum SPF 15 - Bonfire','homosalate, octisalate, octocrylene, zinc oxide','STICK','HOMOSALATE 100 mg/g','Topique','Sun Bum, LLC','INT','Médicaments topiques','Sun Bum Tinted Sunscreen Lip Balm Broad Spectrum SPF 15 - Bonfire'),
('Walgreens Grape Flavor','children cough and chest congestion','LIQUID','DEXTROMETHORPHAN HYDROBROMIDE 20 mg/20mL','Orale','WALGREENS','INT','Expectorant','Walgreens Grape Flavor'),
('Severe Congestion and Cough','dextromethorphan hbr, guaifenesin, phenylephrine hcl','Solution','DEXTROMETHORPHAN HYDROBROMIDE 20 mg/20mL','Orale','Walgreen Company','INT','Expectorant','Severe Congestion and Cough'),
('StellaLife VEGA Oral Care Gel','gel','Gel','ARNICA MONTANA 18 [hp_X]/mL','DENTAL','StellaLife, Inc.','INT',NULL,'StellaLife VEGA Oral Care Gel'),
('Crest Complete plus Whitening plus Scope','sodium fluoride','PASTE, DENTIFRICE','SODIUM FLUORIDE 1.5 mg/g','DENTAL','The Procter & Gamble Manufacturing Company','INT',NULL,'Crest Complete plus Whitening plus Scope'),
('NOVUM APR','menthol','Spray','MENTHOL .5 g/100mL','Topique','NOVUM SOLUTIONS INC','INT','Médicaments topiques','NOVUM APR'),
('Cough and Chest Congestion DM Adult','dextromethorphan hbr, guaifenesin','LIQUID','DEXTROMETHORPHAN HYDROBROMIDE 20 mg/20mL','Orale','CVS Pharmacy','INT','Expectorant','Cough and Chest Congestion DM Adult'),
('Neutrogena Oil Free Acne Stress Control Power Clear Scrub','salicylic acid','Gel','SALICYLIC ACID 20 mg/mL','Topique','Kenvue Brands LLC','INT','Médicaments topiques','Neutrogena Oil Free Acne Stress Control Power Clear Scrub'),
('Aveeno Calm Plus Restore Daily Moisturizer Mineral Sunscreen Broad Spectrum SPF 30','titanium dioxide, zinc oxide','Lotion','TITANIUM DIOXIDE 58 mg/mL','Topique','Kenvue Brands LLC','INT','Médicaments topiques','Aveeno Calm Plus Restore Daily Moisturizer Mineral Sunscreen Broad Spectrum SPF 30'),
('Leader Liquid Bandage','benzethonium chloride dyclonine hydrochloride','LIQUID','BENZETHONIUM CHLORIDE .2 mg/10mL','Topique','LEADER/ Cardinal Health 110, Inc.','INT','Médicaments topiques','Leader Liquid Bandage'),
('Brush Buddies SPIDEY and his AMAZING FRIENDS ANTICAVITY FLUORIDE-Spidey Punch','sodium fluoride','MOUTHWASH','SODIUM FLUORIDE .05 g/100mL','Orale','Ashtel Studios Inc.','INT',NULL,'Brush Buddies SPIDEY and his AMAZING FRIENDS ANTICAVITY FLUORIDE-Spidey Punch'),
('Dr Tatty Numbing','lidocaine hcl','Crème','LIDOCAINE HYDROCHLORIDE 4 g/100g','Topique','Prodigy Media Inc','INT','Amide Local Anesthetic','Dr Tatty Numbing'),
('COXANTO','oxaprozin','Gélule','OXAPROZIN 300 mg/1','Orale','SOLA Pharmaceuticals, LLC','US','Nonsteroidal Anti-inflammatory Drug','COXANTO'),
('Nursing Cream','calendula officinalis, chamomilla recutita, althaea officinalis','SALVE','ALTHAEA OFFICINALIS ROOT 1 [hp_X]/51.7g','Topique','Spry Life LLC','INT','Médicaments topiques','Nursing Cream'),
('HealthWise Soothing Lidocaine Pain Relief','lidocaine hci 0.5%','Gel','LIDOCAINE HYDROCHLORIDE ANHYDROUS .5 g/g','Topique','Veridian Healthcare','INT','Amide Local Anesthetic','HealthWise Soothing Lidocaine Pain Relief'),
('Cryomax Cooling','menthol','Gel','MENTHOL, (+)- 9.5 g/100g','Topique','LIFE WEAR TECHNOLOGIES','INT','Médicaments topiques','Cryomax Cooling'),
('Cisatracurium Besylate','cisatracurium besylate','Solution','CISATRACURIUM BESYLATE 2 mg/mL','Intraveineuse','Hospira, Inc.','US','Nondepolarizing Neuromuscular Blocker','Cisatracurium Besylate'),
('Ciprofloxacin in Dextrose','ciprofloxacin','Solution','CIPROFLOXACIN 400 mg/200mL','Intraveineuse','Hospira, Inc.','US','Fluoroquinolone Antibacterial','Ciprofloxacin in Dextrose'),
('Keep Going Sting Relief Pad','benzocaine and isopropyl alcohol','CLOTH','BENZOCAINE 6 g/100g','Topique','JIANGMEN SHUIZIRUN SANITARY ARTICLES CO., LTD.','INT','Standardized Chemical Allergen','Keep Going Sting Relief Pad'),
('PetSilver Wound 2','argentum metalicum','Spray','SILVER .00175 g/59g','Topique','AG Essence','INT','Médicaments topiques','PetSilver Wound 2'),
('Harris Teeter Spring Fresh Body Wash','benzalkonium chloride','LIQUID','BENZALKONIUM CHLORIDE 1.3 mg/mL','Topique','Harris Teeter','INT','Médicaments topiques','Harris Teeter Spring Fresh Body Wash'),
('Cough Drops Dollar General Strawberry 30ct','menthol','Pastille','MENTHOL 2.7 mg/1','Orale','Dollar General Corporation','INT',NULL,'Cough Drops Dollar General Strawberry 30ct'),
('Hand Sanitizer Santal Blanc','alcohol solution','Solution','ALCOHOL 70 mL/100mL','Topique','Noshinku','INT','Médicaments topiques','Hand Sanitizer Santal Blanc'),
('SOME BY MI V10 HYAL AIR FIT SUNSCREEN','sunscreent','Crème','AVOBENZONE 3 g/50mL','Topique','PERENNEBELL','INT','Médicaments topiques','SOME BY MI V10 HYAL AIR FIT SUNSCREEN'),
('Caffeine and Sodium Benzoate','caffeine and sodium benzoate','Solution','CAFFEINE 125 mg/mL','Intramusculaire','American Regent, Inc.','INT','Central Nervous System Stimulant','Caffeine and Sodium Benzoate')
) AS v(nom, dci, forme, dosage, voie, labo, pays, classe, nomcom)
WHERE NOT EXISTS (
  SELECT 1 FROM medicaments m WHERE UPPER(m.nom) = UPPER(v.nom)
);
