-- ndc_batch_001.sql (80 rows)
INSERT INTO medicaments (nom, dci, forme, dosage, voie_administration, laboratoire, pays, classe_therapeutique, nom_commercial)
SELECT v.nom, v.dci, v.forme, v.dosage, v.voie, v.labo, v.pays, v.classe, v.nomcom
FROM (VALUES
('Vacation by Vacation Scent and Shimmer Duo','avobenzone, homosalate, octisalate, and octocrylene','Kit',NULL,NULL,'Vacation Inc.','INT',NULL,'Vacation by Vacation Scent and Shimmer Duo'),
('POTASSIUM PHOSPHATES','potassium phosphate, monobasic potassium phosphate, dibasic injection,','Solution','POTASSIUM PHOSPHATE, DIBASIC 236 mg/mL','Intraveineuse','Amneal Pharmaceuticals Private Limited','US','Osmotic Laxative','POTASSIUM PHOSPHATES'),
('Rorobell WaWa Tooth','sodium monofluorophosphate','PASTE, DENTIFRICE','SODIUM MONOFLUOROPHOSPHATE .72 g/100g','Orale','ROROBELL','INT',NULL,'Rorobell WaWa Tooth'),
('Capsaicin Cream','capsaicin','Crème','CAPSAICIN .1 g/100g','Topique','Noble OTC LLC','INT','Médicaments topiques','Capsaicin Cream'),
('natouch','miconazole','SOAP','MICONAZOLE 1.2 g/120g','Topique','Natouch LLC','INT','Azole Antifungal','natouch'),
('Antigingivitis/Antiplaque','cetylpyridinium chloride','MOUTHWASH','CETYLPYRIDINIUM CHLORIDE .7 mg/mL','Orale','Meijer, Inc.','INT',NULL,'Antigingivitis/Antiplaque'),
('Mirtazapine','mirtazapine','Comprimé','MIRTAZAPINE 45 mg/1','Orale','SQUARE PHARMACEUTICALS LIMITED','US',NULL,'Mirtazapine'),
('VISTA MEIBO TEARS Propylene Glycol 0.6% w/v Advanced Dry Eye Relief Lubricating Drops 10 ml','propylene glycol','LIQUID','PROPYLENE GLYCOL .6 g/100mL','Ophtalmique','Red Wedding LLC','INT','Ophtalmologie','VISTA MEIBO TEARS Propylene Glycol 0.6% w/v Advanced Dry Eye Relief Lubricating Drops 10 ml'),
('Tolnaftate','antifungal liquid spray','Spray','TOLNAFTATE 1.5 g/150g','Topique','Wal-Mart Stores, Inc','INT','Médicaments topiques','Tolnaftate'),
('equate dual back pain reliever','acetaminophen, ibuprofen','Comprimé','ACETAMINOPHEN 250 mg/1','Orale','WALMART INC.','US','Nonsteroidal Anti-inflammatory Drug','equate dual back pain reliever'),
('PlaneAire Hands Lemon Olive Oil Hand Sanitizer','ethanol hand sanitizer','Lotion','ALCOHOL 70 mL/100mL','Topique','EverywhereAire LLC','INT','Médicaments topiques','PlaneAire Hands Lemon Olive Oil Hand Sanitizer'),
('Mupirocin','mupirocin','Pommade','MUPIROCIN 20 mg/g','Topique','Advanced Rx Pharmacy of Tennessee, LLC','US','RNA Synthetase Inhibitor Antibacterial','Mupirocin'),
('tizanidine','tizanidine','Comprimé','TIZANIDINE HYDROCHLORIDE 2 mg/1','Orale','Advanced Rx of Tennessee, LLC','US','Central alpha-2 Adrenergic Agonist','tizanidine'),
('MGC Health','cough drops vanilla honey','Pastille','MENTHOL 2.5 mg/1','Orale','Medical Group Care LLC','INT',NULL,'MGC Health'),
('Ingrown Nail Treatment','jalawef ingrown nail treatment','LIQUID','CLOVE OIL 6 g/100mL','Topique','Consilii LLC','INT','Médicaments topiques','Ingrown Nail Treatment'),
('QUALITY CHOICE Anti-Nausea','dextrose(glucose),levulose(fructose),phosphoric acid','Solution','DEXTROSE, UNSPECIFIED FORM 1.87 g/5mL','Orale','QUALITY CHOICE (CHAIN DRUG MARKETING ASSOCIATION)','INT',NULL,'QUALITY CHOICE Anti-Nausea'),
('Dermachange Scar','allantoin','Gel','ALLANTOIN .5 g/100g','Topique','Private Label Beauty and Wellness','INT','Médicaments topiques','Dermachange Scar'),
('CITRACID-50','desinfectant solution for hemodialysis machine','Solution','CITRIC ACID MONOHYDRATE .5 g/100mL','HEMODIALYSIS','Aqua Medica, S.A. de C.V.','INT','Anti-coagulant','CITRACID-50'),
('Lancome Paris Clarifique BX-Interceptor Topical Acne Clearing Treatment','salicylic acid','LIQUID','SALICYLIC ACID 20 mg/mL','Topique','LOreal USA Products Inc','INT','Médicaments topiques','Lancome Paris Clarifique BX-Interceptor Topical Acne Clearing Treatment'),
('TIGER BABY Baby Sunscreen SPF-50','zinc oxide','Crème','ZINC OXIDE 200 mg/mL','Topique','BRICKELL BRANDS LLC','INT','Copper Absorption Inhibitor','TIGER BABY Baby Sunscreen SPF-50'),
('up and up mint nicotine','nicotine polacrilex','Pastille','NICOTINE 2 mg/1','Orale','Target Corporation','US','Cholinergic Nicotinic Agonist','up and up mint nicotine'),
('diltiazem hydrochloride','diltiazem hydrochloride','Gélule','DILTIAZEM HYDROCHLORIDE 120 mg/1','Orale','NCS HealthCare of KY, LLC dba Vangard Labs','US','Calcium Channel Blocker','diltiazem hydrochloride'),
('Pain Be Gone','menthol','Crème','MENTHOL 9.6 mg/mL','Topique','Back to Earth Inc.','INT','Médicaments topiques','Pain Be Gone'),
('Losartan Potassium and Hydrochlorothiazide','losartan potassium and hydrochlorothiazide','Comprimé','HYDROCHLOROTHIAZIDE 12.5 mg/1','Orale','Proficient Rx LP','US','Angiotensin 2 Receptor Blocker','Losartan Potassium and Hydrochlorothiazide'),
('HALOPERIDOL','haloperidol','Comprimé','HALOPERIDOL 2 mg/1','Orale','Creekwood Pharmaceuticals LLC','US','Typical Antipsychotic','HALOPERIDOL'),
('SPF15 natural lip balm 01','avobenzone,homosalate,octocrylene,octisalate','LIPSTICK','AVOBENZONE 2 g/100g','Topique','Cosmuses Cosmetics (Ningbo) Co., Ltd.','INT','Médicaments topiques','SPF15 natural lip balm 01'),
('SPIRONOLACTONE','spironolactone','Comprimé','SPIRONOLACTONE 25 mg/1','Orale','NCS HealthCare of KY, LLC dba Vangard Labs','US','Aldosterone Antagonist','SPIRONOLACTONE'),
('Bestmade Natural Products Silicea','silicea','Comprimé','SILICA 30 [hp_C]/30[hp_C]','Orale','Bestmade Natural Products','INT',NULL,'Bestmade Natural Products Silicea'),
('Hismile','grape bubblegum flavor sodium fluoride anticavity toothpaste','Gel','SODIUM FLUORIDE 2.4 mg/g','DENTAL','Hismile Pty Ltd','INT',NULL,'Hismile'),
('ANTIBACTERIAL DREAMY FLORALS','glycerin','SOAP','GLYCERIN 1 g/g','Transdermique','Quimicas Handal de Centroamerica SA de CV','INT','Non-Standardized Chemical Allergen','ANTIBACTERIAL DREAMY FLORALS'),
('Flobow WART REMOVER','salicylic acid 17% wart remover','Crème','SALICYLIC ACID 17 g/100g','Topique','Jiangxi Yudexi Pharmaceutical Co., LTD','INT','Médicaments topiques','Flobow WART REMOVER'),
('Tinted Mineral Sunscreen 20% Zinc Oxide','zinc oxide','Crème','ZINC OXIDE 200 mg/g','Topique','INTEGRATIVE AESTHETICS BOSTON, LLC','INT','Médicaments topiques','Tinted Mineral Sunscreen 20% Zinc Oxide'),
('Nourish Non-Tinted Mineral Sunscreen','zinc oxide','Crème','ZINC OXIDE 160 mg/g','Topique','Fern Burg','INT','Médicaments topiques','Nourish Non-Tinted Mineral Sunscreen'),
('Ceftriaxone Sodium','ceftriaxone sodium','Solution','CEFTRIAXONE SODIUM 1 g/1','Intramusculaire','Sandoz Inc','US','Cephalosporin Antibacterial','Ceftriaxone Sodium'),
('Tula Skincare Radiant Skin Brightening Serum Skin Tint Broad Spectrum SPF 30 28 Deep Neutral-Cool','avobenzone, and octisalate','LIQUID','AVOBENZONE 3 g/100mL','Topique','The Procter & Gamble Manufacturing Company','INT','Médicaments topiques','Tula Skincare Radiant Skin Brightening Serum Skin Tint Broad Spectrum SPF 30 28 Deep Neutral-Cool'),
('Me Ga Care Foam TM','ethyl alcohol, isopropyl alcohol','LIQUID','ALCOHOL 55 mL/100mL','Topique','Babikian Healthcare Products CJSC','INT','Médicaments topiques','Me Ga Care Foam TM'),
('Aminocaproic Acid','aminocaproic acid','Solution','AMINOCAPROIC ACID .25 g/mL','Orale','Apozeal Pharmaceuticals Inc.','US','Antifibrinolytic Agent','Aminocaproic Acid'),
('1912 Herb Co Easy Stomach Herb','malt, hawthorn','Poudre','HAWTHORN LEAF WITH FLOWER 20 g/100g','Orale','Agricultural Corporation YUBIMUHUAN CO Ltd','INT',NULL,'1912 Herb Co Easy Stomach Herb'),
('Dentalclean Dental Gel Booster Adult Use','sodium fluoride 0.24%','Gel','SODIUM FLUORIDE 2.4 mg/g','DENTAL','Rabbit Indstria e Comrcio de Produtos de Higiene Pessoal Ltda','INT',NULL,'Dentalclean Dental Gel Booster Adult Use'),
('Sunglaze Body Gel Cream Sunscreen SPF50','avobenzone, homosalate, octisalate, octocrylene','Crème','AVOBENZONE 40 mg/mL','Topique','Koco Life LLC','INT','Médicaments topiques','Sunglaze Body Gel Cream Sunscreen SPF50'),
('Acnil','acnil clindamycin hydrochloride and metronidazole liniment','LINIMENT','CLINDAMYCIN HYDROCHLORIDE 10 mg/30mL','Topique','Jiangsu Chenpai Bond Pharmaceutical Co.,Ltd.','INT','Lincosamide Antibacterial','Acnil'),
('Bitchstix The Original SPF 30 Sunscreen Lip Balm SPF 30','avobenzone, octinoxate, octisalate, oxybenzone','STICK','AVOBENZONE 3 g/100g','Topique','Bitchistix, LLC','INT','Médicaments topiques','Bitchstix The Original SPF 30 Sunscreen Lip Balm SPF 30'),
('Fluorouracil','fluorouracil','Solution','FLUOROURACIL 50 mg/mL','Intraveineuse','ProPharma Distribution','US','Nucleoside Metabolic Inhibitor','Fluorouracil'),
('BARUBT LUMINOUS EYE CORRECTOR SPF 41 01 FAIR','luminous eye corrector spf 41','Crème','CERAMIDE AP .05 g/5g','CUTANEOUS','Guangdong Youbaijia Cosmetic Industry Co., Ltd','INT','Non-Standardized Food Allergenic Extract','BARUBT LUMINOUS EYE CORRECTOR SPF 41 01 FAIR'),
('BUNUSS Phyto-Pro Skin Cream','progesterone','PASTE','PROGESTERONE 16.9 mg/mL','Topique','Jiashen International Trade Limited','INT','Progesterone','BUNUSS Phyto-Pro Skin Cream'),
('JAYSUING Liquid Wart Flat','glycerin','LIQUID','CAMELLIA SINENSIS SEED OIL .0006 mg/3mg','Topique','Shantou Jaysuing Cleaning and Environmental Protection Technology Co., Ltd.','INT','Médicaments topiques','JAYSUING Liquid Wart Flat'),
('St. Moriz Suncare 30 Body Sunscreen','sunscreen','Lotion','AVOBENZONE 30 mg/mL','Topique','Hothouse Beauty Inc','INT','Médicaments topiques','St. Moriz Suncare 30 Body Sunscreen'),
('Tirzepatide','tirzepatide','Poudre','TIRZEPATIDE 1 g/g',NULL,'Hybio Pharmaceutical Co., Ltd.','INT',NULL,NULL),
('Diazepam','diazepam','Spray','DIAZEPAM 10 mg/100uL',NULL,'Catalent Pharma Solutions, LLC','INT',NULL,NULL),
('Crisaborole','crisaborole','Poudre','CRISABOROLE 100 kg/100kg',NULL,'TAPI Croatia Industries Ltd.','INT',NULL,NULL),
('Mesalamine','mesalamine','Poudre','MESALAMINE 1 kg/kg',NULL,'Cambrex Karlskoga AB','INT',NULL,NULL),
('Chlordiazepoxide','chlordiazepoxide','Poudre','CHLORDIAZEPOXIDE 1 kg/kg',NULL,'Cambrex Profarmaco Milano Srl','INT',NULL,NULL),
('PT Elite Premium Pain Relief','capsaicin, menthol','Crème','CAPSAICIN .35 mg/mL','Topique','PT ELITE PRODUCTS LLC','INT','Médicaments topiques','PT Elite Premium Pain Relief'),
('NicDuic Quit Smoking Nicotine Patches 1-3 Step','14mg nicotine patches','Patch transdermique','NICOTINE 14 mg/1001','Topique','Shenzhen Paxi Trading Co., Ltd.','INT','Cholinergic Nicotinic Agonist','NicDuic Quit Smoking Nicotine Patches 1-3 Step'),
('Mattifying Mineral SPF 40 Tinted','titanium dioxide, zinc oxide','Crème','TITANIUM DIOXIDE 80 mg/g','Topique','ELIZA ARAKELIAN','INT','Médicaments topiques','Mattifying Mineral SPF 40 Tinted'),
('Fondaparinux Sodium','fondaparinux sodium','Solution injectable','FONDAPARINUX SODIUM 2.5 mg/.5mL','Sous-cutanée','Sandoz Inc.','US','Factor Xa Inhibitor','Fondaparinux Sodium'),
('Azithromycin Dihydrate','azithromycin dihydrate','Comprimé','AZITHROMYCIN DIHYDRATE 500 mg/1','Orale','Sportpharm LLC','US','Macrolide Antimicrobial','Azithromycin Dihydrate'),
('Alcohol Free Hand Sanitizer','benzalkonium chloride','Gel','BENZALKONIUM CHLORIDE .3 g/100mL','Topique','HAIAN KANGRUI TEXTILE CO., LTD.','INT','Médicaments topiques','Alcohol Free Hand Sanitizer'),
('NEWSKIN Whole Embryonic Layer Anti-Aging Skin Renewal Powde','maritime pine, schisandra chinensis seed, centella asiatica triterpenoids','Poudre','CENTELLA ASIATICA TRITERPENOIDS 30 mg/6g','Orale','Japan Medical Biotechnology Limited','INT',NULL,'NEWSKIN Whole Embryonic Layer Anti-Aging Skin Renewal Powde'),
('Ivermectin','ivermectin','PASTE','IVERMECTIN 1.87 g/100g','Orale','Shenzhen Zhenshangzekai Technology Co, Ltd.','INT','Antiparasitic','Ivermectin'),
('TIRTIR SUN BOUNCY GLOW LIP BALM SPF30 - 01 HAZY MAUVE','zinc oxide','Crème','ZINC OXIDE 135 mg/mL','Topique','TIRTIR USA Inc.','INT','Médicaments topiques','TIRTIR SUN BOUNCY GLOW LIP BALM SPF30 - 01 HAZY MAUVE'),
('bareMinerals Blemish Rescue Skin-Clearing Loose Foundation Neutral Tan 4N','salicylic acid','Poudre','SALICYLIC ACID 30 mg/6g','Topique','Orveon Global US LLC','INT','Médicaments topiques','bareMinerals Blemish Rescue Skin-Clearing Loose Foundation Neutral Tan 4N'),
('prazosin hydrochloride','prazosin hydrochloride','Comprimé','PRAZOSIN HYDROCHLORIDE 2.5 mg/1',NULL,'Pfizer Laboratories Div Pfizer Inc','INT',NULL,NULL),
('Dextromethorphan Hydrobromide, Paracetamol, Phenylephrine Hydrochloride','dextromethorphan hydrobromide, paracetamol, phenylephrine hydrochloride','Gélule','ACETAMINOPHEN 325 mg/1',NULL,'Bayer HealthCare LLC','INT',NULL,NULL),
('Leucovorin Calcium','leucovorin calcium','Comprimé','LEUCOVORIN CALCIUM 25 mg/1',NULL,'Teva Pharmaceuticals USA, Inc.','INT',NULL,NULL),
('Caffeine','caffeine','Comprimé','CAFFEINE 100 mg/1',NULL,'Contract Pharmacal Corp.','INT',NULL,NULL),
('Amantadine Hydrochloride','amantadine hydrochloride','Gélule','AMANTADINE HYDROCHLORIDE 100 mg/1',NULL,'Patheon Softgels Inc.','INT',NULL,NULL),
('Bismuth Subgallate','bismuth subgallate','Poudre','BISMUTH SUBGALLATE 1 kg/kg',NULL,'Spectrum Laboratory Products, Inc.','INT',NULL,NULL),
('SODIUM PHOSPHATE, MONOBASIC, MONOHYDRATE','sodium phosphate, monobasic, monohydrate','Poudre','SODIUM PHOSPHATE, MONOBASIC, MONOHYDRATE 1 kg/kg',NULL,'Hunan Jiudian Pharmaceutical Co.,Ltd.','INT',NULL,NULL),
('Dapiprazole HCl','dapiprazole hcl','Poudre','DAPIPRAZOLE HYDROCHLORIDE 1 kg/kg',NULL,'Angelini Pharma Italia Aziende Chimiche Riunite Angelini Francesco A.C.R.A.F. Spa','INT',NULL,NULL),
('Acetaminophen','acetaminophen','Comprimé','ACETAMINOPHEN 500 mg/1',NULL,'Kenvue Brands LLC','INT',NULL,NULL),
('Aluminum sulfate','aluminum sulfate','Poudre','ALUMINUM SULFATE 1 g/g',NULL,'Holland Company, Inc.','INT',NULL,NULL),
('Isosulfan Blue','isosulfan blue','Poudre','ISOSULFAN BLUE 15 kg/15kg',NULL,'Emcure Pharmaceuticals Limited','INT',NULL,NULL),
('Dabigatran Etexilate Mesylate','dabigatran etexilate mesylate','Poudre','DABIGATRAN ETEXILATE MESYLATE 75 kg/75kg',NULL,'Medichem Manufacturing (Malta) Ltd.','INT',NULL,NULL),
('Memantine Hydrochloride','memantine hydrochloride','Poudre','MEMANTINE HYDROCHLORIDE 1 kg/kg',NULL,'Olon SpA','INT',NULL,NULL),
('Entecavir','entecavir','Poudre','ENTECAVIR 1 kg/kg',NULL,'Siegfried Evionnaz SA','INT',NULL,NULL),
('Pantoprazole Sodium','pantoprazole sodium','Comprimé','PANTOPRAZOLE SODIUM 40 mg/1','Orale','Major Pharmaceuticals','US','Proton Pump Inhibitor','Pantoprazole Sodium'),
('Dexrazoxane','dexrazoxane','Poudre','DEXRAZOXANE 1 kg/kg',NULL,'Chongqing Biocare Pharmaceutical Ltd.','INT',NULL,NULL),
('PREGABALIN','pregabalin','Gélule','PREGABALIN 25 mg/1','Orale','Major Pharmaceuticals','US',NULL,'PREGABALIN'),
('Desmopressin','desmopressin','Poudre','DESMOPRESSIN 250 g/250g',NULL,'Piramal Pharma Limited','INT',NULL,NULL)
) AS v(nom, dci, forme, dosage, voie, labo, pays, classe, nomcom)
WHERE NOT EXISTS (
  SELECT 1 FROM medicaments m WHERE UPPER(m.nom) = UPPER(v.nom)
);
