-- ndc_batch_069.sql (80 rows)
INSERT INTO medicaments (nom, dci, forme, dosage, voie_administration, laboratoire, pays, classe_therapeutique, nom_commercial)
SELECT v.nom, v.dci, v.forme, v.dosage, v.voie, v.labo, v.pays, v.classe, v.nomcom
FROM (VALUES
('SEAWEED BATH CO. SPF 50 SPORT','octocrylene, zinc oxide, octisalate','Lotion','OCTISALATE 50 mg/mL','Topique','The Seaweed Bath Co.','INT','Copper Absorption Inhibitor','SEAWEED BATH CO. SPF 50 SPORT'),
('Chest Congestion Relief','guaifenesin','Comprimé','GUAIFENESIN 400 mg/1','Orale','Meijer, Inc.','INT','Expectorant','Chest Congestion Relief'),
('Healthy Back Institute Rub On Relief','analgesic','Crème','CAMPHOR (SYNTHETIC) .03 g/g','Topique','Eagle Labs Inc.','INT','Médicaments topiques','Healthy Back Institute Rub On Relief'),
('ARNICA MONTANA 30C - 3-PACK','arnica montana','PELLET','ARNICA MONTANA 30 [hp_C]/1','Sublinguale','SEVENE USA','INT',NULL,'ARNICA MONTANA 30C - 3-PACK'),
('Assurance Barrier Cream','dimethicone cream','Gel','DIMETHICONE 100 5 g/251mL','Topique','Walmart Inc','INT','Médicaments topiques','Assurance Barrier Cream'),
('betr remedies ibuprofen','ibuprofen','Comprimé','IBUPROFEN 200 mg/1','Orale','Live Betr LLC','US','Nonsteroidal Anti-inflammatory Drug','betr remedies ibuprofen'),
('Multi-Specialty Kit','depo-medrol, lidocaine, isopropyl alcohol','Kit',NULL,'INFILTRATION','Advanced Rx Pharmacy of Tennessee, LLC','INT',NULL,'Multi-Specialty Kit'),
('Tinted Moisturizer SPF 46 Universal Tint','zinc oxide, octinoxate','Crème','OCTINOXATE 7.5 g/100mL','Topique','Drmtlgy, LLC','INT','Copper Absorption Inhibitor','Tinted Moisturizer SPF 46 Universal Tint'),
('Hammertech Vitamin A and D','white petrolatum','Pommade','PETROLATUM 76 g/100g','Topique','HAMMER TECH LLC','INT','Médicaments topiques','Hammertech Vitamin A and D'),
('3.6oz BiEST 2.5 Estrogen Cream','estriol,estradiol,estrogen cream','Crème','ESTRADIOL .5 mg/102g','Transdermique','SHYNE BRANDS/BIOLabs PRO','INT','Estrogen','3.6oz BiEST 2.5 Estrogen Cream'),
('Zhong Hua Feng Shi Die Da Gao External Analgesic Plaster','menthol, methyl salicylate','Patch transdermique','MENTHOL, UNSPECIFIED FORM .04 g/g','Topique','Big 5 Nutrition LLC','INT','Médicaments topiques','Zhong Hua Feng Shi Die Da Gao External Analgesic Plaster'),
('TARGET UP AND UP GUM CARE','cetylpyridinium chloride 0.05%','MOUTHWASH','CETYLPYRIDINIUM CHLORIDE .05 g/100mL','Orale','Target Corporation','INT',NULL,'TARGET UP AND UP GUM CARE'),
('AKTEN','lidocaine hydrochloride anhydrous','Gel','LIDOCAINE HYDROCHLORIDE ANHYDROUS 35 mg/mL','Ophtalmique','Thea Pharma Inc.','US','Amide Local Anesthetic','AKTEN'),
('GR CC Broad Spectrum SPF 30','octinoxate, oxybenzone','Crème','OCTINOXATE 6 g/100mL','Topique','ERKUL KOZMETIK SANAYI VE TICARET ANONIM SIRKETI','INT','Médicaments topiques','GR CC Broad Spectrum SPF 30'),
('antiseptic hand sanitizer 01','alcohol','LIQUID','ALCOHOL 62 mL/100mL','Topique','Cosmuses Cosmetics (Ningbo) Co., Ltd.','INT','Médicaments topiques','antiseptic hand sanitizer 01'),
('Bestmade Natural Products BM110','sepia, aesculus, cimicifuga, calc fluor, baryta carb, rhus tox, kali carb','LIQUID','BARIUM CARBONATE 30 [hp_C]/30[hp_C]','Orale','Bestmade Natural Products','INT',NULL,'Bestmade Natural Products BM110'),
('Bestmade Natural Products Mezereum','mezereum','Comprimé','DAPHNE MEZEREUM BARK 30 [hp_C]/30[hp_C]','Orale','Bestmade Natural Products','INT',NULL,'Bestmade Natural Products Mezereum'),
('REINREUDE WART REMOVER','salicylic acid 17% wart remover','LIQUID','SALICYLIC ACID 17 g/100mL','Topique','Jiangxi Yudexi Pharmaceutical Co., LTD','INT','Médicaments topiques','REINREUDE WART REMOVER'),
('BEHATMH 17% Salicylic acid Wart Remover Serum Pen','salicylic acid','LIQUID','SALICYLIC ACID 17 g/100mL','Topique','Guangzhou Borderless Technology Co., Ltd.','INT','Médicaments topiques','BEHATMH 17% Salicylic acid Wart Remover Serum Pen'),
('Tagrid Skin Repair Cream','allantoin','Crème','ALLANTOIN 10 mg/g','Topique','TAGRID LLC','INT','Médicaments topiques','Tagrid Skin Repair Cream'),
('Prevention','titanium dioxide, zinc oxide','Crème','TITANIUM DIOXIDE 80 mg/g','Topique','Noble Center for Healthy Aging LLC','INT','Médicaments topiques','Prevention'),
('Wish Hand Sanitizer Coconut Cream White Florals','alcohol hand sanitizer','Spray','ALCOHOL 70 mL/100mL','Topique','PT SUPER HOME PRODUCT INDONESIA','INT','Médicaments topiques','Wish Hand Sanitizer Coconut Cream White Florals'),
('Tula Skincare Radiant Skin Brightening Serum Skin Tint Broad Spectrum SPF 30 08 Light Medium-Cool','avobenzone, and octisalate','LIQUID','AVOBENZONE 3 g/100mL','Topique','The Procter & Gamble Manufacturing Company','INT','Médicaments topiques','Tula Skincare Radiant Skin Brightening Serum Skin Tint Broad Spectrum SPF 30 08 Light Medium-Cool'),
('THE ZOEUN SKIN TOTAL CARE','colloidal oatmeal, sturgeon extract','SHAMPOO','OATMEAL .007 g/100mL','Topique','Sturgeonbio Co.,Ltd.','INT','Non-Standardized Food Allergenic Extract','THE ZOEUN SKIN TOTAL CARE'),
('Dubai Chocolate Fluoride Mouthwash','anticavity mouthwash','LIQUID','SODIUM FLUORIDE .002 mg/10mL','DENTAL','SuperMouth, LLC.','INT',NULL,'Dubai Chocolate Fluoride Mouthwash'),
('Premixed saline packets','sodium chloride, sodium bicarbonate','Solution','SODIUM BICARBONATE 700 mg/3000mg','Nasale','Shenzhen Kerui lntl Trading Co., Ltd','INT','Alkalinizing Activity','Premixed saline packets'),
('Massage essential oil','massage essential oil','LIQUID','HYALURONIC ACID 3 mg/100mL','CUTANEOUS','Guangzhou Yanxi Biotechnology Co., Ltd','INT',NULL,'Massage essential oil'),
('Crest 3D White Ultra Whitening with Stain-Blasting Foam Vivid Mint','sodium fluoride','PASTE, DENTIFRICE','SODIUM FLUORIDE 1.5 mg/g','DENTAL','The Procter & Gamble Manufacturing Company','INT',NULL,'Crest 3D White Ultra Whitening with Stain-Blasting Foam Vivid Mint'),
('Glytone Acne BPO Treatment Gel','benzoyl peroxide gel','Gel','BENZOYL PEROXIDE .05 g/g','Topique','Glytone, LLC','INT','Médicaments topiques','Glytone Acne BPO Treatment Gel'),
('EvennessBrighteningBodyOil','evennessbrighteningbodyoil','EMULSION','ASCORBIC ACID 7.5 mg/250mg','CUTANEOUS','Guangzhou Kadiya Biotechnology Co., Ltd.','INT','Vitamin A','EvennessBrighteningBodyOil'),
('Morning Person Daily Repair Protect Moisturizer','zinc oxide','Lotion','ZINC OXIDE 132 mg/mL','Topique','Morning Person Beauty','INT','Médicaments topiques','Morning Person Daily Repair Protect Moisturizer'),
('OUHOE Protection Sunscreen','titanium dioxide','LIQUID','CENTELLA ASIATICA .15 mg/50mg','Topique','Shantou Ouhoe Technology Co., Ltd.','INT','Médicaments topiques','OUHOE Protection Sunscreen'),
('Lopinavir and Ritonavir','lopinavir and ritonavir','Comprimé','LOPINAVIR 100 mg/1',NULL,'AbbVie Deutschland GmbH & Co Kg','INT',NULL,NULL),
('Aluminum Hydroxide Magnesium Carbonate','aluminum hydroxide magnesium carbonate','Poudre','ALUMINUM HYDROXIDE 64 kg/100kg',NULL,'SPI Pharma Inc.','INT',NULL,NULL),
('Face Love','zinc oxide','Crème','ZINC OXIDE 160 mg/g','Topique','CLARITY SKIN CARE STUDIO, INC.','INT','Médicaments topiques','Face Love'),
('DILUENT','water solution','Solution injectable','WATER 1 mL/mL','Intraveineuse','Sandoz Inc','US','Médicaments IV / Hospitaliers','DILUENT'),
('WowDay Hemorrhoid and Fissure Cream','hemorrhoid and fissure cream','Crème','GLYCERIN 3 g/15g','Rectale','WowDay LLC','INT','Non-Standardized Chemical Allergen','WowDay Hemorrhoid and Fissure Cream'),
('Numb Fast Hemorrhoidal','lidocaine','Crème','LIDOCAINE 50 mg/mL','Topique','Oasis Plus LLC','INT','Amide Local Anesthetic','Numb Fast Hemorrhoidal'),
('bareMinerals BAREPRO Performance Wear Liquid Foundation Broad Spectrum SPF 20 Sandalwood 15','titanium dioxide','LIQUID','TITANIUM DIOXIDE 33.2 mg/mL','Topique','Orveon Global US LLC','INT','Médicaments topiques','bareMinerals BAREPRO Performance Wear Liquid Foundation Broad Spectrum SPF 20 Sandalwood 15'),
('Triazolam','triazolam','Poudre','TRIAZOLAM 1 kg/kg',NULL,'Pharmacia and Upjohn Company LLC','INT',NULL,NULL),
('Methyldopa','methyldopa','Poudre','METHYLDOPA 1 kg/kg',NULL,'Teva API India Limited','INT',NULL,NULL),
('LEVODOPA','levodopa','Poudre','LEVODOPA 1 kg/kg',NULL,'Ajinomoto Co., Inc.','INT',NULL,NULL),
('Amoxicillin Trihydrate','amoxicillin trihydrate','Poudre','AMOXICILLIN 1 kg/kg',NULL,'Inner Mongolia Changsheng Pharmaceutical Co., Ltd.','INT',NULL,NULL),
('ESTRONE','estrone','Poudre','ESTRONE 1 kg/kg',NULL,'Qinhuangdao Zizhu Pharmaceutical Co., Ltd.','INT',NULL,NULL),
('E-6005','e-6005','Poudre','E-6005 1 kg/kg',NULL,'Procos S.p.A.','INT',NULL,NULL),
('levacetylleucine','levacetylleucine','Suspension','LEVACETYLLEUCINE 1000 mg/1',NULL,'Patheon France S.A.S','INT',NULL,NULL),
('lapatinib','lapatinib','Poudre','LAPATINIB 1 kg/kg',NULL,'ThermoFisher Scientific Cork','INT',NULL,NULL),
('INDIGOTINDISULFONATE SODIUM','indigotindisulfonate sodium','Poudre','INDIGOTINDISULFONATE SODIUM 1 kg/kg',NULL,'DISHMAN CARBOGEN AMCIS LIMITED','INT',NULL,NULL),
('Calcium Phosphate Dibasic Anhydrous','calcium phosphate dibasic anhydrous','Poudre','CALCIUM PHOSPHATE, DIBASIC, ANHYDROUS 1 kg/kg',NULL,'Jost Chemical Co.','INT',NULL,NULL),
('Olaparib','olaparib','Poudre','OLAPARIB 1 kg/kg',NULL,'SciAnda(Changshu) Pharmaceuticals, Ltd.','INT',NULL,NULL),
('Abacavir Sulphate','abacavir sulphate','Poudre','ABACAVIR SULFATE 1 kg/kg',NULL,'Dr.Reddy''s Laboratories Limited','INT',NULL,NULL),
('NORMOSOL-M AND DEXTROSE','dextrose monohydrate, sodium chloride, potassium acetate, and magnesium acetate','Solution','DEXTROSE MONOHYDRATE 5 g/100mL','Intraveineuse','ICU Medical Inc.','US','Calculi Dissolution Agent','NORMOSOL-M AND DEXTROSE'),
('Caduet','amlodipine and atorvastatin','Comprimé','AMLODIPINE BESYLATE 5 mg/1','Orale','Pfizer Laboratories Div Pfizer Inc','US','Calcium Channel Blocker','Caduet'),
('Sacubitril Valsartan Sodium Hydrate','sacubitril valsartan sodium hydrate','Poudre','SACUBITRIL VALSARTAN SODIUM HYDRATE 1 kg/kg',NULL,'Honour Lab Limited','INT',NULL,NULL),
('Ethyl eicosapentaenoate','ethyl eicosapentaenoate','OIL','ICOSAPENT ETHYL 1 kg/kg',NULL,'Nisshin Pharma Inc.','INT',NULL,NULL),
('ranibizumab','ranibizumab','Solution','RANIBIZUMAB 10 mg/mL',NULL,'Patheon Italia S.p.A.','INT',NULL,NULL),
('Azacitidine','azacitidine','Poudre','AZACITIDINE 1 kg/kg',NULL,'Hetero Labs Limited','INT',NULL,NULL),
('BUPROPION','bupropion','Poudre','BUPROPION HYDROCHLORIDE 1 kg/kg',NULL,'Granules India Limited','INT',NULL,NULL),
('Calcium Monoethylfumarate Micronized','calcium monoethylfumarate micronized','Poudre','CALCIUM MONOETHYLFUMARATE 1 kg/kg',NULL,'Laboratorium Ofichem BV','INT',NULL,NULL),
('Paroxetine Hydrochloride Hemihydrate','paroxetine hydrochloride hemihydrate','Poudre','PAROXETINE HYDROCHLORIDE HEMIHYDRATE 1 kg/kg',NULL,'ZHEJIANG HUAHAI PHARMACEUTICAL CO., LTD.','INT',NULL,NULL),
('Fumaria Officinalis Flowering Top','fumaria officinalis flowering top','LIQUID','FUMARIA OFFICINALIS FLOWERING TOP 1 [hp_X]/.001L',NULL,'Herbamed AG','INT',NULL,NULL),
('DYDROGESTERONE','dydrogesterone','Poudre','DYDROGESTERONE 1 kg/kg',NULL,'Sterling S.p.A.','INT',NULL,NULL),
('BENZOYL PEROXIDE','benzoyl peroxide','Crème','BENZOYL PEROXIDE 25 mg/kg',NULL,'Pure Source, LLC','INT',NULL,NULL),
('linezolid (form-1)','linezolid (form-1)','Poudre','LINEZOLID 1 kg/kg',NULL,'Jubilant Biosys limited','INT',NULL,NULL),
('E-Z-Disk','barium sulfate','Comprimé','BARIUM SULFATE 700 mg/1','Orale','E-Z-EM, INC.','US','Radiographic Contrast Agent','E-Z-Disk'),
('Apremilast Form-M','apremilast form-m','Poudre','APREMILAST 1 kg/kg',NULL,'MSN Life Sciences Private Limited','INT',NULL,NULL),
('Long R3 IGF-1','long r3 igf-1','Poudre','PEPTIDE B27PD 10 mg/10mg',NULL,'DARMERICA, LLC','INT',NULL,NULL),
('L-Phenylalanine','l-phenylalanine','Poudre','PHENYLALANINE 1 kg/kg',NULL,'Shanghai Ajinomoto Amino Acid Co., Ltd.','INT',NULL,NULL),
('Trehalose','trehalose','Poudre','TREHALOSE 1 g/g',NULL,'Qingdao Biopeptek Co., Ltd.','INT',NULL,NULL),
('cupric sulfate pentahydrate','cupric sulfate pentahydrate','CRYSTAL','CUPRIC SULFATE 25 kg/25kg',NULL,'Biophore india pharmaceutical PVT Ltd','INT',NULL,NULL),
('Pregnenolone','pregnenolone','Poudre','PREGNENOLONE 1 kg/kg',NULL,'Pharma Source Direct, Inc.','INT',NULL,NULL),
('Aflibercept','aflibercept','LIQUID','AFLIBERCEPT 65 mg/mL',NULL,'Boehringer Ingelheim Fremont, Inc.','INT',NULL,NULL),
('extra strength Tropical Fruit','antacid','Comprimé','CALCIUM CARBONATE 750 mg/1','Orale','Target Corporation','INT','Blood Coagulation Factor','extra strength Tropical Fruit'),
('MULTI-SYMPTOM COLD AND FLU RELIEF DAYTIME','acetaminophen 325 mg dextromethorphan hbr 10 mg phenylephrine hci 5 mg','Gélule','ACETAMINOPHEN 325 mg/1','Orale','RITE AID','INT','Sigma-1 Agonist','MULTI-SYMPTOM COLD AND FLU RELIEF DAYTIME'),
('Jinteli','norethindrone acetate and ethinyl estradiol','Comprimé','ETHINYL ESTRADIOL 5 ug/1','Orale','Teva Pharmaceuticals USA, Inc.','US','Estrogen','Jinteli'),
('Lumryz','sodium oxybate','Suspension','SODIUM OXYBATE 4.5 g/1','Orale','Avadel CNS Pharmaceuticals, LLC','US','Central Nervous System Depressant','Lumryz'),
('MISSHA M Perfect Cover BB No 31','zinc oxide, titanium dioxide, octinoxate','Crème','OCTINOXATE .075 g/g','Topique','Able C&C Co., Ltd.','INT','Copper Absorption Inhibitor','MISSHA M Perfect Cover BB No 31'),
('Ultra Balm Moisturizing Protective Balm for lips SPF 20 Nude Caramel','octinoxate, zinc oxide','STICK','OCTINOXATE 7.5 g/100g','Topique','BEL STAR S A','INT','Médicaments topiques','Ultra Balm Moisturizing Protective Balm for lips SPF 20 Nude Caramel'),
('SPRYCEL','dasatinib','Comprimé','DASATINIB 100 mg/1','Orale','E.R. Squibb & Sons, L.L.C.','US','Kinase Inhibitor','SPRYCEL'),
('Signature Care Enamel Guard Sensitive Gentle Whitening','potassium nitrate, sodium fluoride','PASTE, DENTIFRICE','POTASSIUM NITRATE 5 g/100g','DENTAL','Safeway','INT',NULL,'Signature Care Enamel Guard Sensitive Gentle Whitening')
) AS v(nom, dci, forme, dosage, voie, labo, pays, classe, nomcom)
WHERE NOT EXISTS (
  SELECT 1 FROM medicaments m WHERE UPPER(m.nom) = UPPER(v.nom)
);
