-- ndc_batch_096.sql (80 rows)
INSERT INTO medicaments (nom, dci, forme, dosage, voie_administration, laboratoire, pays, classe_therapeutique, nom_commercial)
SELECT v.nom, v.dci, v.forme, v.dosage, v.voie, v.labo, v.pays, v.classe, v.nomcom
FROM (VALUES
('0.5% LIDOCAINE HCl','0.5% lidocaine hcl','Solution','LIDOCAINE HYDROCHLORIDE 5 mg/mL','INFILTRATION','HF Acquisition Co LLC, DBA HealthFirst','US','Amide Local Anesthetic','0.5% LIDOCAINE HCl'),
('DR. SANA COUGH AND CHEST CONGESTION DM','dextromethorphan hydrobromide, guaifenesin','LIQUID','DEXTROMETHORPHAN HYDROBROMIDE 20 mg/30mL','Orale','GADAL Laboratories, Inc','INT','Expectorant','DR. SANA COUGH AND CHEST CONGESTION DM'),
('MediPlast','salicylic acid','PLASTER','SALICYLIC ACID 40 g/100g','Topique','Medline Industries, LP','INT','Médicaments topiques','MediPlast'),
('Phosphorus 6X','phosphorus 6x','LIQUID','PHOSPHORUS 6 [hp_X]/30mL','Orale','True Botanica, LLC','INT',NULL,'Phosphorus 6X'),
('Lacticum acidum','lactic acid, dl-','PELLET','LACTIC ACID, DL- 30 [hp_C]/30[hp_C]','Orale','Boiron','INT',NULL,'Lacticum acidum'),
('DermaCort Anti-itch','hydrocortisone','Crème','HYDROCORTISONE 10 mg/g','Topique','Melaleuca, Inc.','INT','Corticosteroid','DermaCort Anti-itch'),
('4 Kids Cold and Cough Day and Night Grape Flavor','onion,anemone pulsatilla, phosphorus, goldenseal, calcium sulfide, sodium chloride, sulfur, matricaria chamomilla and arabica coffee bean','Kit',NULL,'Orale','Hyland''s Inc.','INT',NULL,'4 Kids Cold and Cough Day and Night Grape Flavor'),
('SHISEIDO REVITALESSENCE SKIN GLOW FOUNDATION 260','octinoxate','EMULSION','OCTINOXATE 2.30805 g/30mL','Topique','SHISEIDO AMERICAS CORPORATION','INT','Médicaments topiques','SHISEIDO REVITALESSENCE SKIN GLOW FOUNDATION 260'),
('Sulphuricum acidum','sulfuric acid','PELLET','SULFURIC ACID 6 [hp_C]/6[hp_C]','Orale','Boiron','INT',NULL,'Sulphuricum acidum'),
('Triasil','triamcinolone acetonide','Kit',NULL,NULL,'PureTek Corporation','INT',NULL,'Triasil'),
('Thyroid-Adrenal','adrenalinum, thyroidinum, aloe, calc. carb., chelidonium majus, conium, graphites, iodium, lachesis, lycopodium, lycopus virginicus, phytolacca, rhus toxicodendron, silicea, spongia, echinacea','LIQUID','ALOE 20 [hp_X]/mL','Orale','Newton Laboratories, Inc.','INT','Catecholamine','Thyroid-Adrenal'),
('rexall hemorrhoidal','cocoa butter, phenylephrine hcl','Suppositoire','COCOA BUTTER 2211 mg/1','Rectale','Dolgencorp Inc','INT','alpha-1 Adrenergic Agonist','rexall hemorrhoidal'),
('8HR Muscle Aches and Pain','acetaminophen','Comprimé','ACETAMINOPHEN 650 mg/1','Orale','AAA Pharmaceutical, Inc.','US',NULL,'8HR Muscle Aches and Pain'),
('DAILY LIGHT GUARD DEFENSE FLUID BROAD SPECTRUM SPF 30','titanium dioxide and zinc oxide','Lotion','TITANIUM DIOXIDE 63 mg/mL','Topique','Aveda Corporation','INT','Médicaments topiques','DAILY LIGHT GUARD DEFENSE FLUID BROAD SPECTRUM SPF 30'),
('MILK OF MAGNESIA CHERRY','magnesium hydroxide','LIQUID','MAGNESIUM HYDROXIDE 1200 mg/15mL','Orale','Geri-Care Pharmaceuticals, Corp','INT','Calculi Dissolution Agent','MILK OF MAGNESIA CHERRY'),
('Shingrix','zoster vaccine recombinant, adjuvanted','Kit',NULL,NULL,'GlaxoSmithKline Biologicals SA','US',NULL,'Shingrix'),
('N-25','serenoa repens whole, agathosma crenulata whole, chimaphila umbellata, elymus repens whole, selenium, and bos taurus prostate gland','Solution','AGATHOSMA CRENULATA WHOLE 2 [hp_X]/mL','Sublinguale','DNA Labs, Inc.','INT',NULL,'N-25'),
('cle de peau BEAUTE THE FOUNDATION N M B40','octinoxate and titanium dioxide','PASTE','OCTINOXATE 1.165 g/28mL','Topique','Shiseido Americas Corporation','INT','Médicaments topiques','cle de peau BEAUTE THE FOUNDATION N M B40'),
('H-Gout Formula','arnica montana, rhododendron','OIL','ARNICA MONTANA 12 [hp_C]/11mL','Topique','Healing Natural Oils LLC','INT','Médicaments topiques','H-Gout Formula'),
('DR ANDREW WEILS FOR ORIGINS MEGA-DEFENSE ADVANCED DAILY UV DEFENDER BROAD SPECTRUM SPF 45','titanium dioxide and zinc oxide','Lotion','TITANIUM DIOXIDE 63 mg/mL','Topique','ORIGINS NATURAL RESOURCES INC.','INT','Médicaments topiques','DR ANDREW WEILS FOR ORIGINS MEGA-DEFENSE ADVANCED DAILY UV DEFENDER BROAD SPECTRUM SPF 45'),
('tussin severe','acetaminophen, dextromethorphan hydrobromide, guaifenesin, phenylephrine hydrochloride','Solution','ACETAMINOPHEN 650 mg/20mL','Orale','H E B','INT','Expectorant','tussin severe'),
('NO-JET-LAG','arnica montana, bellis perennis, matricaria chamomilla, ipecac, and lycopodium clavatum spore','Comprimé','ARNICA MONTANA WHOLE 30 [hp_C]/1','Orale','Miers Laboratories','INT',NULL,'NO-JET-LAG'),
('Tetracycline Hydrochloride','tetracycline hydrochloride','Gélule','TETRACYCLINE HYDROCHLORIDE 250 mg/1','Orale','Amneal Pharmaceuticals NY LLC','US','Tetracycline-class Antimicrobial','Tetracycline Hydrochloride'),
('Alendronate','alendronate sodium','Comprimé','ALENDRONATE SODIUM 70 mg/1','Orale','Hangzhou Minsheng Binjiang Pharmaceutical Co., Ltd.','US','Bisphosphonate','Alendronate'),
('Mineral Sunscreen Broad Spectrum SPF 30','zinc oxide and titanium dioxide','Crème','ZINC OXIDE 50 mg/mL','Topique','Allure Labs, Inc','INT','Copper Absorption Inhibitor','Mineral Sunscreen Broad Spectrum SPF 30'),
('AP-24 Whitening','sodium monofluorophosphate','PASTE','SODIUM MONOFLUOROPHOSPHATE 7.6 mg/g','DENTAL','NSE Products, Inc.','INT',NULL,'AP-24 Whitening'),
('Facial Pain Drops 2023','facial pain drops','LIQUID','ACONITUM NAPELLUS WHOLE 4 [hp_X]/59mL','Orale','Professional Complementary Health Formulas','INT',NULL,'Facial Pain Drops 2023'),
('Pancreas Drops 5020','pancreas drops','LIQUID','ACETIC ACID 4 [hp_X]/59mL','Orale','Professional Complementary Health Formulas','INT','Non-Standardized Food Allergenic Extract','Pancreas Drops 5020'),
('Attitude Oceanly Phyto-Sun Tinted - SPF 15 - Broad Spectrum Sunscreen','zinc oxide','STICK','ZINC OXIDE 10 g/100g','Topique','Attitude DBA 9055-7588 Qubec Inc.','INT','Médicaments topiques','Attitude Oceanly Phyto-Sun Tinted - SPF 15 - Broad Spectrum Sunscreen'),
('Dior Forever Skin Wear Flawless Skin True Foundation SPF 20 1W Warm','octisalate, titanium dioxide','EMULSION','OCTISALATE 35 mg/mL','Topique','Parfums Christian Dior','INT','Médicaments topiques','Dior Forever Skin Wear Flawless Skin True Foundation SPF 20 1W Warm'),
('LIDOCAINE HCl and EPINEPHRINE','lidocaine hcl and epinephrine','Solution injectable','EPINEPHRINE BITARTRATE .005 mg/mL','Épidurale','B. Braun Medical Inc.','US','Amide Local Anesthetic','LIDOCAINE HCl and EPINEPHRINE'),
('Lynx Foamy PCMX Antiseptic Hand and Body Wash 6876','chloroxylenol','SOAP','CHLOROXYLENOL 3 mg/mL','Topique','ABC Compounding Co., Inc.','INT','Médicaments topiques','Lynx Foamy PCMX Antiseptic Hand and Body Wash 6876'),
('Anti Bacterial Hand Gel Warm Vanilla Sugar','alcohol','Gel','ALCOHOL 71 mL/100mL','Topique','Bath & Body Works, Inc.','INT','Médicaments topiques','Anti Bacterial Hand Gel Warm Vanilla Sugar'),
('AleveX','camphor and menthol','Spray','CAMPHOR (SYNTHETIC) 5.5 mg/g','Topique','Bayer HealthCare LLC','INT','Médicaments topiques','AleveX'),
('Alka Seltzer Plus Maximum Strength Cough Chest Congestion PowerFast Fizz','dextromethorphan hydrobromide, guaifenesin','Comprimé','DEXTROMETHORPHAN HYDROBROMIDE 10 mg/1','Orale','Bayer Healthcare LLC.','INT','Expectorant','Alka Seltzer Plus Maximum Strength Cough Chest Congestion PowerFast Fizz'),
('Aspirina Cafeina','aspirin,caffeine','Comprimé','ASPIRIN 500 mg/1','Orale','Bayer HealthCare LLC.','INT','Central Nervous System Stimulant','Aspirina Cafeina'),
('Flurbiprofen Sodium','flurbiprofen sodium','Solution','FLURBIPROFEN SODIUM .3 mg/mL','Ophtalmique','Proficient Rx LP','US','Nonsteroidal Anti-inflammatory Drug','Flurbiprofen Sodium'),
('Nematodes Nosode Combination 9404','nematodes nosode combination','LIQUID','ARSENIC TRIOXIDE 6 [hp_X]/29.5mL','Orale','Professional Complementary Health Formulas','INT',NULL,'Nematodes Nosode Combination 9404'),
('Ofloxacin Otic','ofloxacin','Solution','OFLOXACIN 3 mg/mL','AURICULAR (OTIC)','Proficient Rx LP','US','Quinolone Antimicrobial','Ofloxacin Otic'),
('Pyridoxine Hydrochloride','pyridoxine hydrochloride','Solution','PYRIDOXINE HYDROCHLORIDE 100 mg/mL','Intramusculaire','Fresenius Kabi USA, LLC','US','Vitamin B6 Analog','Pyridoxine Hydrochloride'),
('Banana Boat Sport coolzone Clear Sunscreen Broad Spectrum SPF 30','avobenzone,homosalate,octisalate,octocrylene','Spray','AVOBENZONE 2 g/100g','Topique','Edgewell Personal Care Brands LLC','INT','Médicaments topiques','Banana Boat Sport coolzone Clear Sunscreen Broad Spectrum SPF 30'),
('R09 SPLEEN','adenosine triphosphate, baptisia tinctoria root, ceanothus americanus leaf, fucus vesiculosus, podophyllum resin, sepia officinalis juice, testosterone','Solution','ADENOSINE TRIPHOSPHATE 5 [hp_X]/mL','Sublinguale','Apex Energetics Inc.','INT','Androgen','R09 SPLEEN'),
('Zeyco Hand Sanitizer','alcohol','Gel','ALCOHOL .7 mL/mL','Topique','Laboratorios Zeyco, S.A. de C.V.','INT','Médicaments topiques','Zeyco Hand Sanitizer'),
('Severe Sinus Congestion and Pain','acetaminophen, guaifenesin, and phenylephrine hydrochloride','Comprimé','ACETAMINOPHEN 325 mg/1','Orale','Chain Drug Marketing Association','INT','Expectorant','Severe Sinus Congestion and Pain'),
('LV-FX','liver assit','LIQUID','ANACARDIUM OCCIDENTALE FRUIT 14 [hp_X]/mL','Orale','Vitality Works, Inc','INT',NULL,'LV-FX'),
('Pollens - Trees, Cedar, Red Juniperus virginiana','cedar, red juniperus virginiana','Solution','JUNIPERUS VIRGINIANA POLLEN .05 g/mL','PERCUTANEOUS','Jubilant HollisterStier LLC','US','Non-Standardized Pollen Allergenic Extract','Pollens - Trees, Cedar, Red Juniperus virginiana'),
('Uceris','budesonide','Comprimé','BUDESONIDE 9 mg/1','Orale','Santarus Inc.','US','Corticosteroid','Uceris'),
('Mepivacaine','mepivacaine hydrochloride','Solution','MEPIVACAINE HYDROCHLORIDE 30 mg/mL','SUBMUCOSAL','Benco Dental','US','Amide Local Anesthetic','Mepivacaine'),
('AGE20S SIGNATURE ESSENCE PACT INTENSE COVER MINI 33N','octinoxate, octocrylene, titanium dioxide','Crème','OCTINOXATE .26 g/4g','Topique','Aekyung Industrial Co., Ltd.','INT','Médicaments topiques','AGE20S SIGNATURE ESSENCE PACT INTENSE COVER MINI 33N'),
('Estradiol Vaginal','estradiol','Crème','ESTRADIOL .1 mg/g','Vaginale','NuCare Pharmaceuticals, Inc.','US','Estrogen','Estradiol Vaginal'),
('Ichthammol','ichthammol ointment','Pommade','ICHTHAMMOL 100 mg/g','Topique','Walgreens','INT','Médicaments topiques','Ichthammol'),
('McKesson Obstetrical Antiseptic Towelette','benzalkonium chloride','SWAB','BENZALKONIUM CHLORIDE .13 g/100g','Topique','McKesson Medical-Surgical','INT','Médicaments topiques','McKesson Obstetrical Antiseptic Towelette'),
('PCA SKIN Acne','benzoyl perozide','Crème','BENZOYL PEROXIDE 5 g/100g','Topique','CP Skin Health Group, Inc.','INT','Médicaments topiques','PCA SKIN Acne'),
('Gas Relief Mint Flavor','simethicone','Comprimé','DIMETHICONE, UNSPECIFIED 80 mg/1','Orale','Raritan Pharmaceuticals Inc','INT','Skin Barrier Activity','Gas Relief Mint Flavor'),
('Value Health by Prodose Eye Drops','tetrahydrozoline hydrochloride and polyethylene glycol 400','Solution','POLYETHYLENE GLYCOL 400 10 mg/mL','Ophtalmique','Prodose, Inc.','INT','Ophtalmologie','Value Health by Prodose Eye Drops'),
('Muscle Rub Cream','menthol 10%, methyl salicylate 15%','Crème','MENTHOL, UNSPECIFIED FORM 10 g/100g','Topique','Preferred Pharmaceuticals Inc.','INT','Médicaments topiques','Muscle Rub Cream'),
('Sun Bum Protecting Scalp and Hair Mist SPF 30 sunscreen','avobenzone, homosalate, octisalate, octocrylene','Spray','AVOBENZONE 30 mg/mL','Topique','Sun Bum, LLC','INT','Médicaments topiques','Sun Bum Protecting Scalp and Hair Mist SPF 30 sunscreen'),
('Ibuprofen Fast relief medicine for pain','ibuprofen 200 mg','Comprimé','IBUPROFEN 200 mg/1','Orale','Allegiant Health','US','Nonsteroidal Anti-inflammatory Drug','Ibuprofen Fast relief medicine for pain'),
('Old Spice High Endurance Pure Sport','aluminum zirconium tetrachlorohydrex gly','STICK','ALUMINUM ZIRCONIUM TETRACHLOROHYDREX GLY 17 g/100g','Topique','The Procter & Gamble Manufacturing Company','INT','Médicaments topiques','Old Spice High Endurance Pure Sport'),
('StellaLife VEGA Oral Care Peppermint Pain and Swelling Relief','arnica, calendula, chamomilla, echinacea angustifolia, echinacea purpurea, hepar sulph calc, hypericum, lgnatia, ledum palustre, ruta, silicea, staphysagria','Gel','ARNICA MONTANA 3 [hp_X]/mL','Topique','StellaLife, Inc.','INT','Médicaments topiques','StellaLife VEGA Oral Care Peppermint Pain and Swelling Relief'),
('Crest 3D White Stain Eraser Polishing Mint','sodium fluoride','PASTE, DENTIFRICE','SODIUM FLUORIDE 1.5 mg/g','Orale','The Procter & Gamble Manufacturing Company','INT',NULL,'Crest 3D White Stain Eraser Polishing Mint'),
('Severe Cold Daytime','acetaminophen, dextromethorphan hbr, guaifenesin, phenylephrine hcl','Gélule','ACETAMINOPHEN 325 mg/1','Orale','CVS Pharmacy','INT','Expectorant','Severe Cold Daytime'),
('Uline Antacid','calcium carbonate','Comprimé','CALCIUM CARBONATE 420 mg/1','Orale','Uline','INT','Blood Coagulation Factor','Uline Antacid'),
('Neutrogena Sport Active Defense SPF 70','avobenzone, homosalate, octisalate, octocrylene','Spray','AVOBENZONE 30 mg/g','Topique','Kenvue Brands LLC','INT','Médicaments topiques','Neutrogena Sport Active Defense SPF 70'),
('Tamoxifen Citrate','tamoxifen citrate','Comprimé','TAMOXIFEN CITRATE 10 mg/1','Orale','Mylan Pharmaceuticals Inc.','US','Estrogen Agonist/Antagonist','Tamoxifen Citrate'),
('Leader All Day Sinus and Cold D','naproxen sodium, pseudoephedrine hcl','Comprimé','NAPROXEN SODIUM 220 mg/1','Orale','Cardinal Health 110, LLC. dba Leader','US','Nonsteroidal Anti-inflammatory Drug','Leader All Day Sinus and Cold D'),
('Smart Care WATERMELON WAVE HAND SANITIZER','ethyl alcohol','Spray','ALCOHOL 70 mL/100mL','Topique','Ashtel Studios, Inc.','INT','Médicaments topiques','Smart Care WATERMELON WAVE HAND SANITIZER'),
('Xermelo','telotristat ethyl','Comprimé','TELOTRISTAT ETHYL 250 mg/1','Orale','Lexicon Pharmaceuticals, Inc.','US','Tryptophan Hydroxylase Inhibitor','Xermelo'),
('e.l.f Plz Clarify Facial Oil','e.l.f plz clarify facial oil','LIQUID','SALICYLIC ACID 2 g/100mL','Topique','Zhejiang Ayan Biotech Co., Ltd.','INT','Médicaments topiques','e.l.f Plz Clarify Facial Oil'),
('Metformin','metformin er 500 mg','Comprimé','METFORMIN HYDROCHLORIDE 500 mg/1','Orale','REMEDYREPACK INC.','US','Biguanide','Metformin'),
('Foster and Thrive Stomach Relief','bismuth subsalicylate','Comprimé','BISMUTH SUBSALICYLATE 262 mg/1','Orale','Strategic Sourcing Services LLC','INT',NULL,'Foster and Thrive Stomach Relief'),
('GOOD REMEDIES Maximum Strength Urinary Pain Relief Caplet','phenazopyridine hydrochloride','Comprimé','PHENAZOPYRIDINE HYDROCHLORIDE 99.5 mg/1','Orale','Strive Pharmaceuticals Inc.','INT',NULL,'GOOD REMEDIES Maximum Strength Urinary Pain Relief Caplet'),
('QUZYTTIR','cetirizine hydrochloride','Solution injectable','CETIRIZINE HYDROCHLORIDE 10 mg/mL','Intraveineuse','TerSera Therapeutics LLC','US','Histamine-1 Receptor Antagonist','QUZYTTIR'),
('VERTRA Premium Suncare SPF 30','titanium dioxide, zinc oxide','Spray','TITANIUM DIOXIDE 40 mg/mL','Topique','Eai-Jr286, Inc.','INT','Copper Absorption Inhibitor','VERTRA Premium Suncare SPF 30'),
('Red Scalpfixer Anti Dandruff','pyrinthione zinc','SHAMPOO','ZINC PYRITHIONE 10 mg/100mL','Topique','Orange Lab, Inc','INT','Médicaments topiques','Red Scalpfixer Anti Dandruff'),
('PetSilver Ear Wash 4','argentum metallicum','Spray','SILVER .0035 g/118g','Topique','AG Essence','INT','Médicaments topiques','PetSilver Ear Wash 4'),
('basic care ibuprofen','ibuprofen','Gélule','IBUPROFEN 200 mg/1','Orale','Amazon.com Services LLC','US','Nonsteroidal Anti-inflammatory Drug','basic care ibuprofen'),
('Dakins Quarter','sodium hypochlorite','Solution','SODIUM HYPOCHLORITE 1.25 mg/mL','Topique','Century Pharmaceuticals, Inc.','INT','Médicaments topiques','Dakins Quarter'),
('Celexa','citalopram','Comprimé','CITALOPRAM HYDROBROMIDE 10 mg/1','Orale','Allergan, Inc.','US','Serotonin Reuptake Inhibitor','Celexa'),
('BYLVAY','odevixibat','Gélule','ODEVIXIBAT 200 ug/1','Orale','Albireo Pharma, Inc.','US','Ileal Bile Acid Transporter Inhibitor','BYLVAY')
) AS v(nom, dci, forme, dosage, voie, labo, pays, classe, nomcom)
WHERE NOT EXISTS (
  SELECT 1 FROM medicaments m WHERE UPPER(m.nom) = UPPER(v.nom)
);
