-- ndc_batch_114.sql (80 rows)
INSERT INTO medicaments (nom, dci, forme, dosage, voie_administration, laboratoire, pays, classe_therapeutique, nom_commercial)
SELECT v.nom, v.dci, v.forme, v.dosage, v.voie, v.labo, v.pays, v.classe, v.nomcom
FROM (VALUES
('MIAMI BEACH BUM Save Face SPF-30 Sunscreen','zinc oxide','Crème','ZINC OXIDE 150 mg/mL','Topique','MIAMI BEACH BUM','INT','Copper Absorption Inhibitor','MIAMI BEACH BUM Save Face SPF-30 Sunscreen'),
('GR LIP BUTTER BLUEBERRY SPF 15','avobenzone, octinoxate','LIPSTICK','AVOBENZONE 2.7 g/100g','Topique','ERKUL KOZMETIK SANAYI VE TICARET ANONIM SIRKETI','INT','Médicaments topiques','GR LIP BUTTER BLUEBERRY SPF 15'),
('Microgestin Fe 1.5/30','norethindrone acetate/ethinyl estradiol and ferrous fumarate','Kit',NULL,NULL,'Proficient Rx LP','US',NULL,'Microgestin Fe 1.5/30'),
('THE SOLUTION NUMBING','lidocaine hydrochloride','Gel','LIDOCAINE HYDROCHLORIDE 5 g/100mL','Topique','SCALP TECH INC','INT','Amide Local Anesthetic','THE SOLUTION NUMBING'),
('Bestmade Natural Products BM126','chimaphila, conium, pareira brav, pulsatilla nig, sabal serr, stigmata may, thuja occ','LIQUID','CHIMAPHILA UMBELLATA WHOLE 30 [hp_C]/30[hp_C]','Orale','Bestmade Natural Products','INT',NULL,'Bestmade Natural Products BM126'),
('Bestmade Natural Products Ruta Gr','ruta graveolens','Comprimé','RUTA GRAVEOLENS FLOWERING TOP 30 [hp_C]/30[hp_C]','Orale','Bestmade Natural Products','INT',NULL,'Bestmade Natural Products Ruta Gr'),
('PUVIDA FUNGAL NAIL RENEWAL','undecylenic acid 25% fungal nail renewal','LIQUID','UNDECYLENIC ACID 25 g/100mL','Topique','Jiangxi Yudexi Pharmaceutical Co., LTD','INT','Médicaments topiques','PUVIDA FUNGAL NAIL RENEWAL'),
('TAGOQHIA Minoxidil Hair Thickening Serum','minoxidil','LIQUID','BIOTIN .2 g/100mL','Topique','Guangzhou Borderless Technology Co., Ltd.','INT','Arteriolar Vasodilator','TAGOQHIA Minoxidil Hair Thickening Serum'),
('GHOSTED','zinc oxide','Lotion','ZINC OXIDE 100 mg/mL','Topique','Spooge','INT','Médicaments topiques','GHOSTED'),
('ProtectME Tinted Mineral SPF 40 20%','zinc oxide','Crème','ZINC OXIDE 200 mg/g','Topique','PUREFECTION LA, INC.','INT','Médicaments topiques','ProtectME Tinted Mineral SPF 40 20%'),
('Tula Skincare Radiant Skin Brightening Serum Skin Tint Broad Spectrum SPF 30 23 Tan-Deep Olive','avobenzone, and octisalate','LIQUID','AVOBENZONE 3 g/100mL','Topique','The Procter & Gamble Manufacturing Company','INT','Médicaments topiques','Tula Skincare Radiant Skin Brightening Serum Skin Tint Broad Spectrum SPF 30 23 Tan-Deep Olive'),
('Empower','white petrolatum, zinc oxide','Spray','WHITE PETROLATUM 30 g/100g','Topique','Bemis Manufacturing Company Inc','INT','Médicaments topiques','Empower'),
('Tattoo Numbing Cream','numbing cream','Crème','LIDOCAINE 5 g/100mL','Topique','Changsha Beiliang E-commerce Co., Ltd','INT','Amide Local Anesthetic','Tattoo Numbing Cream'),
('Counter Beauty Dew Skin Tinted Moisturizer No. 4','zinc oxide','Lotion','ZINC OXIDE 14 g/100g','Topique','G2G Ventures, PBC','INT','Médicaments topiques','Counter Beauty Dew Skin Tinted Moisturizer No. 4'),
('Puriya Eczema Cream','colloidal oatmeal','Crème','OATMEAL 1 g/100g','Topique','IPC Republic, Inc.','INT','Non-Standardized Food Allergenic Extract','Puriya Eczema Cream'),
('Zozdal Wart Remover','wart remover salicylic acid','LIQUID','APIS MELLIFERA VENOM 2 g/100mL','Topique','Jiashen International Trade Limited','INT','Médicaments topiques','Zozdal Wart Remover'),
('SimplyGreat Antibacterial wet wipes','benzalkonium chloride','CLOTH','BENZALKONIUM CHLORIDE .13 g/100g','Topique','Simply Great Brands LLC','INT','Médicaments topiques','SimplyGreat Antibacterial wet wipes'),
('HANCHOBIT Matte Sun Stick','titanium dioxide','Crème','ARTEMISIA VULGARIS ROOT .0036 mg/18mg','Topique','HANCHOYEANBIOTEC Co.,Ltd.','INT','Médicaments topiques','HANCHOBIT Matte Sun Stick'),
('Selinexor','selinexor','Comprimé','SELINEXOR 20 mg/1',NULL,'Catalent Pharma Solutions, LLC','INT',NULL,NULL),
('4-Amiinobenzoic acid','4-amiinobenzoic acid','Poudre','AMINOBENZOIC ACID 1 kg/kg',NULL,'Cambrex Karlskoga AB','INT',NULL,NULL),
('Non-Tinted Mineral Sunscreen','zinc oxide','Crème','ZINC OXIDE 200 mg/g','Topique','OLGA KLIMOV INC','INT','Médicaments topiques','Non-Tinted Mineral Sunscreen'),
('Tined Mineral Sunscreen Whipped Mousse','titanium dioxide, zinc oxide','Crème','TITANIUM DIOXIDE 80 mg/g','Topique','ESTILO SALON & SPA LLC','INT','Médicaments topiques','Tined Mineral Sunscreen Whipped Mousse'),
('Solar Shield non-tinted matte mineral SPF 40','titanium dioxide, zinc oxide','Crème','TITANIUM DIOXIDE 80 mg/g','Topique','Joyce Kelly Enterprises','INT','Médicaments topiques','Solar Shield non-tinted matte mineral SPF 40'),
('Irlvixro WART REMOVER FOR COMMON PLANTAR WARTS','wart remover for common plantar warts','LIQUID','SALICYLIC ACID 15 g/100mL','Topique','Shenzhen Xituo Electronics Co., Ltd','INT','Médicaments topiques','Irlvixro WART REMOVER FOR COMMON PLANTAR WARTS'),
('bareMinerals Blemish Rescue Skin-Clearing Loose Foundation Golden Beige 2.5NW','salicylic acid','Poudre','SALICYLIC ACID 30 mg/6g','Topique','Orveon Global US LLC','INT','Médicaments topiques','bareMinerals Blemish Rescue Skin-Clearing Loose Foundation Golden Beige 2.5NW'),
('PENBRAYA','meningococcal groups a, b, c, w, and y vaccine','Kit',NULL,NULL,'Pfizer Laboratories Div Pfizer Inc','US',NULL,'PENBRAYA'),
('Moderna COVID-19 Vaccine','moderna covid-19 vaccine','Suspension','CX-046684 25 ug/.25mL',NULL,'ROVI Pharma Industrial Services S.A.','INT',NULL,NULL),
('METHYLPREDNISOLONE HEMISUCCINATE','methylprednisolone hemisuccinate','Poudre','METHYLPREDNISOLONE HEMISUCCINATE 1 kg/kg',NULL,'NEWCHEM SPA','INT',NULL,NULL),
('Succimer','succimer','Poudre','SUCCIMER 1 g/g',NULL,'Medisca Inc.','INT',NULL,NULL),
('Anagrelide Hydrochloride','anagrelide hydrochloride','Poudre','ANAGRELIDE HYDROCHLORIDE 10 kg/10kg',NULL,'Micro Labs Limited','INT',NULL,NULL),
('Levalbuterol HCl','levalbuterol hcl','Poudre','LEVALBUTEROL HYDROCHLORIDE 100 kg/100kg',NULL,'SICOR Societa'' Italiana Corticosteroidi s.r.l.','INT',NULL,NULL),
('Babesia Microti, Babesia Microti DNA','babesia microti, babesia microti dna','LIQUID','BABESIA MICROTI 10 [hp_M]/mL',NULL,'Deseret Biologicals, Inc.','INT',NULL,NULL),
('Bismuth Subsalicylate SG Fine','bismuth subsalicylate sg fine','Poudre','BISMUTH SUBSALICYLATE 500 kg/500kg',NULL,'5N Plus Lubeck GmbH','INT',NULL,NULL),
('Naloxegol Oxalate Premix','naloxegol oxalate premix','Poudre','NALOXEGOL OXALATE 25 kg/50kg',NULL,'Aurobindo Pharma Limited','INT',NULL,NULL),
('Magnesium Gluconate','magnesium gluconate','Poudre','MAGNESIUM GLUCONATE 1 kg/kg',NULL,'Jost Chemical Co.','INT',NULL,NULL),
('Ibrutinib (Form-C)','ibrutinib (form-c)','Poudre','IBRUTINIB 1 kg/kg',NULL,'MSN Laboratories Private Limited','INT',NULL,NULL),
('Lopinavir','lopinavir','Poudre','LOPINAVIR 1 kg/kg',NULL,'Honour Lab Limited','INT',NULL,NULL),
('ustekinumab-ttwe','ustekinumab-ttwe','Solution','USTEKINUMAB 45 mg/.5mL',NULL,'Patheon Italia S.p.A','INT',NULL,NULL),
('Etravirine Premix','etravirine premix','Poudre','ETRAVIRINE 1 kg/kg',NULL,'Hetero Labs Limited','INT',NULL,NULL),
('Belladonna Extract','belladonna extract','Poudre','ATROPA BELLADONNA 1 kg/kg',NULL,'Inga Pharmaceuticals','INT',NULL,NULL),
('Eplerenone Micronized','eplerenone micronized','Poudre','EPLERENONE 1 kg/kg',NULL,'Industriale Chimica s.r.l.','INT',NULL,NULL),
('STRYCHNOS IGNATII SEED','strychnos ignatii seed','LIQUID','STRYCHNOS IGNATII SEED 1 [hp_X]/mL',NULL,'Herbamed AG','INT',NULL,NULL),
('Dabigatran','dabigatran','Poudre','DABIGATRAN 1 kg/kg',NULL,'Biocon Limited','INT',NULL,NULL),
('Cidofovir Anhydrous','cidofovir anhydrous','Poudre','CIDOFOVIR ANHYDROUS 100 g/100g',NULL,'BILLS BIOTECH PRIVATE LIMITED','INT',NULL,NULL),
('TB500 Fragment','tb500 fragment','Poudre','TB-500 1 g/g',NULL,'Shenzhen Alvantis Pharma Co., Ltd.','INT',NULL,NULL),
('BPC157 Acetate','bpc157 acetate','Poudre','BPC-157 ACETATE 100 g/100g',NULL,'Hangzhou Yiqi Biotechnology Co., Ltd','INT',NULL,NULL),
('Gabapentin Enacarbil','gabapentin enacarbil','Poudre','GABAPENTIN ENACARBIL 1 kg/kg',NULL,'Dasami Lab Private Limited','INT',NULL,NULL),
('pHisoderm CLEAN ANTI-BLEMISH BODY WASH','salicylic acid','Gel','SALICYLIC ACID 20 mg/mL','Topique','The Mentholatum Company','INT','Médicaments topiques','pHisoderm CLEAN ANTI-BLEMISH BODY WASH'),
('Testosterone Phenylpropionate','testosterone phenylpropionate','Poudre','TESTOSTERONE PHENYLPROPIONATE 100 g/100g',NULL,'Brichem Sciences Private Limited','INT',NULL,NULL),
('DAYWEAR ADVANCED MULTI-PROTECTION ANTI-OXIDANT 24H-MOISTURE CREME BROAD SPECTRUM SPF15','avobenzone, homosalate, octisalate','Crème','AVOBENZONE 30 mg/mL','Topique','ESTEE LAUDER INC','INT','Médicaments topiques','DAYWEAR ADVANCED MULTI-PROTECTION ANTI-OXIDANT 24H-MOISTURE CREME BROAD SPECTRUM SPF15'),
('Softlips Cherry, Raspberry, Vanilla','dimethicone','STICK','DIMETHICONE 20 mg/g','Topique','The Mentholatum Company','INT','Skin Barrier Activity','Softlips Cherry, Raspberry, Vanilla'),
('Buspirone Hydrochloride (BPN)','buspirone hydrochloride (bpn)','Poudre','BUSPIRONE HYDROCHLORIDE 1 kg/kg',NULL,'Cohance Lifesciences Limited','INT',NULL,NULL),
('Sufentanil Citrate','sufentanil citrate','Poudre','SUFENTANIL CITRATE 1 g/g',NULL,'Pharma Source Direct, Inc.','INT',NULL,NULL),
('Up and Up maximum Strength fast mucus relief Severe Congestion and Cough','dextromethorphan hydrobromide, guaifenesin, and phenylephrine hydrochloride','LIQUID','DEXTROMETHORPHAN HYDROBROMIDE 20 mg/20mL','Orale','Target Corporation','INT','Expectorant','Up and Up maximum Strength fast mucus relief Severe Congestion and Cough'),
('Cherry Antacid Relief Chew','calcium carbonate','Comprimé','CALCIUM CARBONATE 1177 mg/1','Orale','Rite Aid','INT','Blood Coagulation Factor','Cherry Antacid Relief Chew'),
('aspirin pain relief','aspirin','Comprimé','ASPIRIN 325 mg/1','Orale','Rite Aid Corporation','INT','Nonsteroidal Anti-inflammatory Drug','aspirin pain relief'),
('Sulfur 8 Loc Twist and Braid Scalp','salicylic acid','Solution','SALICYLIC ACID 30 mg/mL','Topique','J. Strickland & Co.','INT','Médicaments topiques','Sulfur 8 Loc Twist and Braid Scalp'),
('GUNA BOWEL PLUS','activated charcoal - aloe - aluminum oxide - bryonia alba root - chelidonium majus - collinsonia - frangula alnus bark - lycopodium clavatum spore - potassium carbonate- rhubarb - strychnos nux vomica seed - silybum marianum seed - skatole - sodium carbonate - sus scrofa pancreas - taraxacum officinale - thiamine -','Solution','ACTIVATED CHARCOAL 6 [hp_X]/30mL','Orale','Guna spa','INT','Non-Standardized Food Allergenic Extract','GUNA BOWEL PLUS'),
('MISSHA M Perfect Cover BB No.45','octinoxate, zinc oxide, titanium dioxide','Crème','OCTINOXATE 7.5 g/100mL','Topique','Able C&C Co., Ltd.','INT','Copper Absorption Inhibitor','MISSHA M Perfect Cover BB No.45'),
('RODAN - FIELDS ESSENTIALS Body Sunscreen BROAD SPECTRUM SPF 30','avobenzone, homosalate, octisalate, octocrylene','Crème','AVOBENZONE 20 mg/mL','Topique','Rodan & Fields','INT','Médicaments topiques','RODAN - FIELDS ESSENTIALS Body Sunscreen BROAD SPECTRUM SPF 30'),
('Etonogestrel and Ethinyl Estradiol Vaginal Ring','etonogestrel and ethinyl estradiol vaginal ring','RING','ETHINYL ESTRADIOL .015 mg/d','Vaginale','Northstar Rx LLC','US','Estrogen','Etonogestrel and Ethinyl Estradiol Vaginal Ring'),
('Adult Cough and Chest Congestion Relief DM Non Drowsy','dextromethorphan hbr, guaifenesin','LIQUID','DEXTROMETHORPHAN HYDROBROMIDE 20 mg/10mL','Orale','Safeway, Inc.','INT','Expectorant','Adult Cough and Chest Congestion Relief DM Non Drowsy'),
('Signature Care Original','oxymetazoline hydrochloride','Spray','OXYMETAZOLINE HYDROCHLORIDE .05 g/100mL','Nasale','SAFEWAY, INC.','INT','Vasoconstrictor','Signature Care Original'),
('Standardized Perennial Ryegrass Pollen','lolium perenne','Solution','LOLIUM PERENNE POLLEN 10000 [BAU]/mL','INTRADERMAL','Greer Laboratories, Inc.','US','Standardized Pollen Allergenic Extract','Standardized Perennial Ryegrass Pollen'),
('White Ash Pollen','fraxinus americana','Solution','FRAXINUS AMERICANA POLLEN .05 g/mL','INTRADERMAL','Greer Laboratories, Inc.','US','Non-Standardized Pollen Allergenic Extract','White Ash Pollen'),
('Iodine Bush','allenrolfea occidentalis','Solution','ALLENROLFEA OCCIDENTALIS POLLEN .1 g/mL','INTRADERMAL','Greer Laboratories, Inc.','US','Non-Standardized Pollen Allergenic Extract','Iodine Bush'),
('Good Neighbor Pharmacy Athletes foot Relief Antifungal','miconazole nitrate','Spray','MICONAZOLE NITRATE 20 mg/g','Topique','Formulated Solutions, LLC','INT','Azole Antifungal','Good Neighbor Pharmacy Athletes foot Relief Antifungal'),
('Anecream 5','lidocaine 5%','Crème','LIDOCAINE 5 g/100g','Topique','Focus Health Group','INT','Amide Local Anesthetic','Anecream 5'),
('terrasil Skin Repair Maximum Strength','allantoin','Pommade','ALLANTOIN .6 g/100g','Topique','Aidance Scientific, Inc, DBA Aidance Skincare & Topical Solutions','INT','Médicaments topiques','terrasil Skin Repair Maximum Strength'),
('Kroger Urinary Pain Relief','phenazopyridine hydrochloride','Comprimé','PHENAZOPYRIDINE HYDROCHLORIDE 95 mg/1','Orale','THE KROGER CO','INT',NULL,'Kroger Urinary Pain Relief'),
('vigabatrin for oral solution','vigabatrin','Solution','VIGABATRIN 50 mg/mL','Orale','Camber Pharmaceuticals, Inc.','US','Anti-epileptic Agent','vigabatrin for oral solution'),
('Colgate Kids Space Jam Mild Bubble Fruit Flavor','sodium fluoride','Gel','SODIUM FLUORIDE 1.1 mg/g','DENTAL','Colgate-Palmolive Company','INT',NULL,'Colgate Kids Space Jam Mild Bubble Fruit Flavor'),
('BUTALBITAL AND ACETAMINOPHEN','butalbital and acetaminophen','Comprimé','ACETAMINOPHEN 300 mg/1','Orale','Burel Pharmaceuticals, LLC','US','Barbiturate','BUTALBITAL AND ACETAMINOPHEN'),
('Intensive Enamel Repair Whitening TP','intensive enamel repair whitening tp','PASTE, DENTIFRICE','POTASSIUM NITRATE 5 g/100g','Orale','Topco Associates LLC','INT',NULL,'Intensive Enamel Repair Whitening TP'),
('Allergy Relief Caplet','diphenhydramine hydrochloride','Comprimé','DIPHENHYDRAMINE HYDROCHLORIDE 25 mg/1','Orale','TOPCO ASSOCIATES LLC','INT','Histamine-1 Receptor Antagonist','Allergy Relief Caplet'),
('Gel-Kam Fruit and Berry','stannous fluoride','Gel','STANNOUS FLUORIDE 1 mg/g','DENTAL','Colgate Oral Pharmaceuticals, Inc.','INT',NULL,'Gel-Kam Fruit and Berry'),
('PHAZYME','simethicone','Gélule','DIMETHICONE 180 mg/1','Orale','C.B. Fleet Company, Inc.','INT','Skin Barrier Activity','PHAZYME'),
('HEB Extra Strength Smooth Antacid Assorted Fruits','calcium carbonate','Comprimé','CALCIUM CARBONATE 750 mg/1','Orale','H E B','INT','Blood Coagulation Factor','HEB Extra Strength Smooth Antacid Assorted Fruits'),
('Allergy Relief-D','loratadine and pseudoephedrine sulfate','Comprimé','LORATADINE 10 mg/1','Orale','HEB','US','alpha-Adrenergic Agonist','Allergy Relief-D'),
('MediChoice Fluoride','sodium monofluorophosphate','PASTE, DENTIFRICE','SODIUM MONOFLUOROPHOSPHATE 7.6 mg/g','DENTAL','O&M HALYARD, INC.','INT',NULL,'MediChoice Fluoride')
) AS v(nom, dci, forme, dosage, voie, labo, pays, classe, nomcom)
WHERE NOT EXISTS (
  SELECT 1 FROM medicaments m WHERE UPPER(m.nom) = UPPER(v.nom)
);
