-- ndc_batch_018.sql (80 rows)
INSERT INTO medicaments (nom, dci, forme, dosage, voie_administration, laboratoire, pays, classe_therapeutique, nom_commercial)
SELECT v.nom, v.dci, v.forme, v.dosage, v.voie, v.labo, v.pays, v.classe, v.nomcom
FROM (VALUES
('DayQuil Severe plus VapoCOOL Cold and Flu, CVP HEALTH','acetaminophen, dextromethorphan hydrobromide, guaifenesin, and phenylephrine hydrochloride','Comprimé','ACETAMINOPHEN 325 mg/1','Orale','Lil'' Drug Store Products, Inc.','INT','Expectorant','DayQuil Severe plus VapoCOOL Cold and Flu, CVP HEALTH'),
('Vertra S Dorian Kona Gold Signature Face Stick SPF 38','titanium dioxide','STICK','TITANIUM DIOXIDE 23 g/100g','Topique','Toshiki Pigment Co., ltd.','INT','Médicaments topiques','Vertra S Dorian Kona Gold Signature Face Stick SPF 38'),
('Mucus Relief DM Maximum Strength','dextromethorphan hbr and guaifenesin','Solution','DEXTROMETHORPHAN HYDROBROMIDE 20 mg/20mL','Orale','WINCO FOODS, LLC','INT','Expectorant','Mucus Relief DM Maximum Strength'),
('AGE20S SIGNATURE ESSENCE PACT INTENSE COVER MINI 15C','octinoxate, octocrylene, titanium dioxide','Crème','OCTINOXATE .26 g/4g','Topique','Aekyung Industrial Co., Ltd.','INT','Médicaments topiques','AGE20S SIGNATURE ESSENCE PACT INTENSE COVER MINI 15C'),
('LEVULAN KERASTICK','aminolevulinic acid hydrochloride','Kit',NULL,NULL,'Sun Pharmaceutical Industries, Inc','US',NULL,'LEVULAN KERASTICK'),
('Maximum Strength Hydrocortisone Cream','hydrocortisone cream','Crème','HYDROCORTISONE 1 g/100g','Topique','Walgreens','INT','Corticosteroid','Maximum Strength Hydrocortisone Cream'),
('Doxycycline Hyclate','doxycycline hyclate','Gélule','DOXYCYCLINE HYCLATE 50 mg/1','Orale','NuCare Pharmaceuticals,Inc.','US','Tetracycline-class Drug','Doxycycline Hyclate'),
('Aspirin enteric coated low dose','aspirin','Comprimé','ASPIRIN 81 mg/1','Orale','Walgreen Company','INT','Nonsteroidal Anti-inflammatory Drug','Aspirin enteric coated low dose'),
('Grandma Els','diaper rash ointment','Pommade','LANOLIN .155 g/g','Topique','ABBE Laboratories, Inc.','INT','Médicaments topiques','Grandma Els'),
('Rylaze','asparaginase erwinia chrysanthemi (recombinant)-rywn','Solution injectable','ASPARAGINASE 20 mg/mL','Intramusculaire','Jazz Pharmaceuticals, Inc.','US','Asparagine-specific Enzyme','Rylaze'),
('Neomycin Polymyxin B Sulfates and Dexamethasone','neomycin sulfate, polymyxin b sulfate and dexamethasone','Suspension','DEXAMETHASONE 1 mg/mL','Ophtalmique','NuCare Pharmaceuticals,Inc.','US','Aminoglycoside Antibacterial','Neomycin Polymyxin B Sulfates and Dexamethasone'),
('levoleucovorin','levoleucovorin','Solution injectable','LEVOLEUCOVORIN CALCIUM 10 mg/mL','Intraveineuse','Gland Pharma Limited','US','Folate Analog','levoleucovorin'),
('Ultra Organic Fiber Sugar Free','psyllium husk','Poudre','PSYLLIUM HUSK 3.4 g/7g','Orale','Raritan Pharmaceuticals Inc','INT',NULL,'Ultra Organic Fiber Sugar Free'),
('DOXYCYCLINE','doxycycline','Gélule','DOXYCYCLINE 50 mg/1','Orale','Lupin Pharmaceuticals, Inc.','US','Tetracycline-class Drug','DOXYCYCLINE'),
('Alocane Max','lidocaine hydrochloride and benzalkonium chloride','Gel','BENZALKONIUM CHLORIDE .13 g/100mL','Topique','Quest Products LLC','INT','Amide Local Anesthetic','Alocane Max'),
('Diacomit','stiripentol','Gélule','STIRIPENTOL 250 mg/1','Orale','BIOCODEX, INC.','US',NULL,'Diacomit'),
('Sun Bum 30 Mineral Sunscreen Face 1.7 OZ','titanium dioxide, zinc oxide','Lotion','TITANIUM DIOXIDE 53 mg/mL','Topique','Sun Bum, LLC','INT','Médicaments topiques','Sun Bum 30 Mineral Sunscreen Face 1.7 OZ'),
('Laxative Enteric Coated','bisacodyl 5mg','Comprimé','BISACODYL 5 mg/1','Orale','Allegiant Health','INT','Stimulant Laxative','Laxative Enteric Coated'),
('Walgreens Cold Therapy Pain Relieving Patch','menthol','Patch transdermique','MENTHOL, UNSPECIFIED FORM 50 mg/g','Topique','Walgreen Co.','INT','Médicaments topiques','Walgreens Cold Therapy Pain Relieving Patch'),
('Harris Teeter Ultra Lubricant Eye Drops','polyethylene glycol 400, propylene glycol','Solution','POLYETHYLENE GLYCOL 400 .4 g/100mL','Ophtalmique','Harris Teeter, LLC.','INT','Ophtalmologie','Harris Teeter Ultra Lubricant Eye Drops'),
('Alpha E3 PRO Hand Sanitizer','alcohol','Spray','ALCOHOL 71 mL/100mL','Topique','Alpha Chemical Services, Inc.','INT','Médicaments topiques','Alpha E3 PRO Hand Sanitizer'),
('Methenamine Mandelate','methenamine mandelate','Comprimé','METHENAMINE MANDELATE 500 mg/1','Orale','Westminster Pharmaceuticals, LLC','INT',NULL,'Methenamine Mandelate'),
('Gillette Clinical Protection Cool Wave Clear','aluminum zirconium octachlorohydrex gly','Gel','ALUMINUM ZIRCONIUM OCTACHLOROHYDREX GLY 20 g/100g','Topique','The Procter & Gamble Manufacturing Company','INT','Médicaments topiques','Gillette Clinical Protection Cool Wave Clear'),
('Vicks childrens Cough Congestion','phenylephrine hcl, dextromethorphan hbr, guaifenesin','LIQUID','DEXTROMETHORPHAN HYDROBROMIDE 10 mg/15mL','Orale','The Procter & Gamble Manufacturing Company','INT','Expectorant','Vicks childrens Cough Congestion'),
('stimulant laxative','bisacodyl','Comprimé','BISACODYL 5 mg/1','Orale','BIONPHARMA INC.','INT','Stimulant Laxative','stimulant laxative'),
('CVS Menthol Cough Drops','menthol','Pastille','MENTHOL 5.4 mg/1','Orale','CVS Pharmacy','INT',NULL,'CVS Menthol Cough Drops'),
('Cystex PM','acetaminophen, diphenhydramine hcl','Comprimé','ACETAMINOPHEN 500 mg/1','Orale','Clarion Brands, LLC','INT','Histamine-1 Receptor Antagonist','Cystex PM'),
('Icequake Coldn Hot medicated patch','menthol','CLOTH','MENTHOL 50 mg/g','Topique','Southern Sales & Service, Inc.','INT','Médicaments topiques','Icequake Coldn Hot medicated patch'),
('Neutrogena Oil Free Acne Moisturizer Pink Grapefruit','salicylic acid','Lotion','SALICYLIC ACID 5 mg/mL','Topique','Kenvue Brands LLC','INT','Médicaments topiques','Neutrogena Oil Free Acne Moisturizer Pink Grapefruit'),
('Neutrogena SkinClearing Mineral Powder Buff 30','salicylic acid','Poudre','SALICYLIC ACID 5 mg/g','Topique','Kenvue Brands LLC','INT','Médicaments topiques','Neutrogena SkinClearing Mineral Powder Buff 30'),
('Leader Ready to Use Saline Laxative','sodium phosphate, dibasic and sodium phosphate, monobasic, unspecified form','Lavement','SODIUM PHOSPHATE, DIBASIC, UNSPECIFIED FORM 7 g/118mL','Rectale','Cardinal Health','INT','Osmotic Laxative','Leader Ready to Use Saline Laxative'),
('Lip Clear Lysine Plus Coldstick','octinoxate and oxybenzone','LIPSTICK','OCTINOXATE 70 mg/g','Topique','Quantum, Inc.','INT','Médicaments topiques','Lip Clear Lysine Plus Coldstick'),
('Methylprednisolone Sodium Succinate','methylprednisolone','Solution','METHYLPREDNISOLONE SODIUM SUCCINATE 40 mg/mL','Intramusculaire','Amneal Pharmaceuticals LLC','US','Corticosteroid','Methylprednisolone Sodium Succinate'),
('Loteprednol Etabonate','loteprednol etabonate','Suspension','LOTEPREDNOL ETABONATE 5 mg/mL','Ophtalmique','Sentiss Pharmaceuticals LLC','US','Corticosteroid','Loteprednol Etabonate'),
('Galantamine','galantamine','Comprimé','GALANTAMINE HYDROBROMIDE 4 mg/1','Orale','Slate Run Pharmaceuticals, LLC','US','Cholinesterase Inhibitor','Galantamine'),
('Harrys Extra Strength Antiperspirant Solstice','aluminum zirconium trichlorohydrex gly','STICK','ALUMINUM ZIRCONIUM TRICHLOROHYDREX GLY 200 mg/g','Topique','Harry''s, Inc.','INT','Médicaments topiques','Harrys Extra Strength Antiperspirant Solstice'),
('Stool Softener Laxative','docusate sodium','Gélule','DOCUSATE SODIUM 100 mg/1','Orale','Strategic Sourcing Services LLC','INT',NULL,'Stool Softener Laxative'),
('RIGHT REMEDIES NIGHTTIME SEVERE COLD AND FLU softgel','acetaminophen, dextromethorphan hydrobromide, doxylamine succinate, phenylephrine hydrochloride','Gélule','ACETAMINOPHEN 325 mg/1','Orale','Strive Pharmaceuticals Inc.','INT','Antihistamine','RIGHT REMEDIES NIGHTTIME SEVERE COLD AND FLU softgel'),
('TIGLUTIK','riluzole','LIQUID','RILUZOLE 50 mg/10mL','Orale','EDW PHARMA, INC','US','Benzothiazole','TIGLUTIK'),
('AVANCE INCONTINENCE CARE','benzethonium chloride','Crème','BENZETHONIUM CHLORIDE .2 g/100g','Topique','SMART CHOICE MEDICAL INC.','INT','Médicaments topiques','AVANCE INCONTINENCE CARE'),
('Antibacterial Aqua Clear 2X Ultra','benzalkonium chloride','LIQUID','BENZALKONIUM CHLORIDE 1.3 mg/mL','Topique','Sante Manufacturing Inc','INT','Médicaments topiques','Antibacterial Aqua Clear 2X Ultra'),
('Oxaliplatin','oxaliplatin','Solution','OXALIPLATIN 5 mg/mL','Intraveineuse','Meitheal Pharmaceuticals Inc.','US','Platinum-based Drug','Oxaliplatin'),
('Oxaprozin','oxaprozin','Comprimé','OXAPROZIN 600 mg/1','Orale','Bryant Ranch Prepack','US','Nonsteroidal Anti-inflammatory Drug','Oxaprozin'),
('Nabumetone','nabumetone','Comprimé','NABUMETONE 750 mg/1','Orale','Bryant Ranch Prepack','US','Nonsteroidal Anti-inflammatory Drug','Nabumetone'),
('Tizanidne hydrochloride','tizanidne hydrochloride','Gélule','TIZANIDINE HYDROCHLORIDE 2 mg/1','Orale','Bryant Ranch Prepack','US','Central alpha-2 Adrenergic Agonist','Tizanidne hydrochloride'),
('Gemcitabine','gemcitabine','Solution','GEMCITABINE HYDROCHLORIDE 38 mg/mL','Intraveineuse','Hospira, Inc.','US','Nucleoside Metabolic Inhibitor','Gemcitabine'),
('Naloxone Hydrochloride','naloxone hydrochloride','Solution','NALOXONE HYDROCHLORIDE .4 mg/mL','Intramusculaire','Hospira, Inc.','US','Opioid Antagonist','Naloxone Hydrochloride'),
('Arakoda','tafenoquine','Comprimé','TAFENOQUINE 100 mg/1','Orale','60 Degrees Pharmaceuticals, INC.','US',NULL,'Arakoda'),
('Phenytoin Sodium','phenytoin sodium','Gélule','PHENYTOIN SODIUM 100 mg/1','Orale','Aphena Pharma Solutions - Tennessee, LLC','US','Anti-epileptic Agent','Phenytoin Sodium'),
('Sanitizing Wipes Alcohol Free Fragrance Free','benzalkonium chloride','CLOTH','BENZALKONIUM CHLORIDE 1.3 mg/1','CUTANEOUS','GoodEarth Distribution Llc','INT',NULL,'Sanitizing Wipes Alcohol Free Fragrance Free'),
('Xarelto','rivaroxaban','Comprimé','RIVAROXABAN 10 mg/1','Orale','Aphena Pharma Solutions - Tennessee, LLC','US','Factor Xa Inhibitor','Xarelto'),
('Perfect Glow BB Cream Sunscreen SPF 30 - Light Medium','octinoxate, titanium dioxide, zinc oxide','Crème','OCTINOXATE 6.5 g/100mL','Topique','Pur-lisse Beauty, LLC','INT','Médicaments topiques','Perfect Glow BB Cream Sunscreen SPF 30 - Light Medium'),
('Isopto Atropine','atropine sulfate','Solution','ATROPINE SULFATE 10 mg/mL','Ophtalmique','Alcon Laboratories, Inc.','US','Anticholinergic','Isopto Atropine'),
('basic care nicotine','nicotine polacrilex','GUM, CHEWING','NICOTINE 4 mg/1','Orale','Amazon.com Services LLC','US','Cholinergic Nicotinic Agonist','basic care nicotine'),
('EltaMD UV Physical Rosy Tint SPF40','titanium dioxide, zinc oxide sunscreen','Lotion','TITANIUM DIOXIDE 70 g/1000g','Topique','CP Skin Health Group, Inc','INT','Copper Absorption Inhibitor','EltaMD UV Physical Rosy Tint SPF40'),
('Felodipine','felodipine','Comprimé','FELODIPINE 2.5 mg/1','Orale','Bryant Ranch Prepack','US','Dihydropyridine Calcium Channel Blocker','Felodipine'),
('OXCARBAZEPINE','oxcarbazepine','Comprimé','OXCARBAZEPINE 300 mg/1','Orale','Bryant Ranch Prepack','US','Anti-epileptic Agent','OXCARBAZEPINE'),
('Dexamethasone','dexamethasone','Comprimé','DEXAMETHASONE 1.5 mg/1','Orale','Direct_rx','US','Corticosteroid','Dexamethasone'),
('Benzalkonium chloride','benzalkonium chloride','LIQUID','BENZALKONIUM CHLORIDE 1.3 mg/mL','Topique','Old East Main Co.','INT','Médicaments topiques','Benzalkonium chloride'),
('Pure care hand sanitizer','alcohol','Gel','ALCOHOL 75 mL/100mL','Topique','KINGKEY MBC LIFE TECHNOLOGY GROUP CO., LTD','INT','Médicaments topiques','Pure care hand sanitizer'),
('RECTICARE','lidocaine and glycerin','CLOTH','GLYCERIN 200 mg/g','Topique','Ferndale Laboratories, Inc.','INT','Amide Local Anesthetic','RECTICARE'),
('Fluticasone Propionate ALLERGY RELIEF','fluticasone propionate','Spray','FLUTICASONE PROPIONATE 50 ug/1','Nasale','GLENMARK THERAPEUTICS INC., USA','US','Corticosteroid','Fluticasone Propionate ALLERGY RELIEF'),
('Balsalazide Disodium','balsalazide disodium','Gélule','BALSALAZIDE DISODIUM 750 mg/1','Orale','PD-Rx Pharmaceuticals, Inc.','US','Aminosalicylate','Balsalazide Disodium'),
('Cipotrex','calcipotriene cream, 0.005% and transparent dressing','Kit',NULL,NULL,'V2 Pharma, LLC','INT',NULL,'Cipotrex'),
('Rhinomel Manuka','sodium chloride','Spray','SODIUM CHLORIDE 9 mg/mL','Nasale','Melcare Biomedical Pty Ltd','INT',NULL,'Rhinomel Manuka'),
('BRIUMVI','ublituximab','Solution','UBLITUXIMAB 150 mg/6mL','Intraveineuse','TG Therapeutics, Inc.','US','CD20-directed Cytolytic Antibody','BRIUMVI'),
('ANTIPERSPIRANT ABOVE EXTREME SUN MEN','antiperspirant above extreme sun men','Spray','ALUMINUM SESQUICHLOROHYDRATE 19 mg/90g','Topique','BASTON INDUSTRIA DE AEROSSOIS LTDA','INT','Médicaments topiques','ANTIPERSPIRANT ABOVE EXTREME SUN MEN'),
('Clear Away Wart Removers','salicylic acid','DISC','SALICYLIC ACID .4 g/g','Topique','Scholls Wellness Company LLC','INT','Médicaments topiques','Clear Away Wart Removers'),
('Monoferric','ferric derisomaltose','Solution','FERRIC DERISOMALTOSE 100 mg/mL','Intraveineuse','Pharmacosmos Therapeutics Inc.','US','Médicaments IV / Hospitaliers','Monoferric'),
('Arth Arrest','methyl nicotinate, capsaicin','Crème','CAPSAICIN .025 g/100g','Topique','Key 2 Health, Inc.','INT','Nicotinic Acid','Arth Arrest'),
('Topcare Stool Softener','docusate sodium','Gélule','DOCUSATE SODIUM 100 mg/1','Orale','TOPCO ASSOCIATES LLC','INT',NULL,'Topcare Stool Softener'),
('LENALIDOMIDE','lenalidomide','Gélule','LENALIDOMIDE 2.5 mg/1','Orale','EXELAN PHARMACEUTICALS INC.','US','Thalidomide Analog','LENALIDOMIDE'),
('Acne Fighting Spot Gel','salicylic acid','Gel','SALICYLIC ACID 10 mg/mL','Topique','e.l.f. Cosmetics, Inc','INT','Médicaments topiques','Acne Fighting Spot Gel'),
('Hydrocortisone','hydrocortisone','Comprimé','HYDROCORTISONE 5 mg/1','Orale','Asclemed USA, Inc.','US','Corticosteroid','Hydrocortisone'),
('Theraflu Severe Cold Relief Daytime Berry Burst','acetaminophen, dextromethorphan hbr','Solution','ACETAMINOPHEN 650 mg/1','Orale','Haleon US Holdings LLC','INT','Sigma-1 Agonist','Theraflu Severe Cold Relief Daytime Berry Burst'),
('CHILDRENS ADVIL','ibuprofen','Suspension','IBUPROFEN 100 mg/5mL','Orale','Haleon US Holdings LLC','US','Nonsteroidal Anti-inflammatory Drug','CHILDRENS ADVIL'),
('Kyzatrex','testosterone undecanoate','Gélule','TESTOSTERONE UNDECANOATE 200 mg/1','Orale','Marius Pharmaceuticals','US','Androgen','Kyzatrex'),
('DROXIA','hydroxyurea','Gélule','HYDROXYUREA 300 mg/1','Orale','Waylis Therapeutics LLC','US','Antimetabolite','DROXIA'),
('Jardiance','empagliflozin','Comprimé','EMPAGLIFLOZIN 25 mg/1','Orale','Boehringer Ingelheim Pharmaceuticals, Inc.','US','Sodium-Glucose Cotransporter 2 Inhibitor','Jardiance'),
('Trijardy XR','empagliflozin, linagliptin, metformin hydrochloride','Comprimé','EMPAGLIFLOZIN 25 mg/1','Orale','Boehringer Ingelheim Pharmaceuticals, Inc.','US','Biguanide','Trijardy XR')
) AS v(nom, dci, forme, dosage, voie, labo, pays, classe, nomcom)
WHERE NOT EXISTS (
  SELECT 1 FROM medicaments m WHERE UPPER(m.nom) = UPPER(v.nom)
);
