-- ndc_batch_060.sql (80 rows)
INSERT INTO medicaments (nom, dci, forme, dosage, voie_administration, laboratoire, pays, classe_therapeutique, nom_commercial)
SELECT v.nom, v.dci, v.forme, v.dosage, v.voie, v.labo, v.pays, v.classe, v.nomcom
FROM (VALUES
('Childrens Wal Tap Elixer Cold and Allergy','brompheniramine maleate, phenylephrine hcl','LIQUID','BROMPHENIRAMINE MALEATE 2 mg/10mL','Orale','Walgreens','INT','alpha-1 Adrenergic Agonist','Childrens Wal Tap Elixer Cold and Allergy'),
('Ibuprofen and Pseudoephedrine Hydrochloride','ibuprofen and pseudoephedrine hydrochloride','Comprimé','IBUPROFEN 200 mg/1','Orale','WALGREEN COMPANY','US','Nonsteroidal Anti-inflammatory Drug','Ibuprofen and Pseudoephedrine Hydrochloride'),
('Iclevia','levonorgestrel and ethinyl estradiol','Kit',NULL,NULL,'Aurobindo Pharma Limited','US',NULL,'Iclevia'),
('OHM-CIR','baryta iodata, cactus grandiflorus, carbo vegetabilis, crataegus oxyacantha, curare, kali carbonicum, kalmia latifolia, melilotus officinale, naja tripudians, secale cornutum, solanum nigrum, spigelia anthelmia','Spray','ACTIVATED CHARCOAL 12 [hp_X]/30mL','Orale','OHM PHARMA INC.','INT',NULL,'OHM-CIR'),
('Laxative Women','bisacodyl','Comprimé','BISACODYL 5 mg/1','Orale','WinCo Foods, LLC','INT','Stimulant Laxative','Laxative Women'),
('Walgreens SPF 50 Sport Continuous Sunscreen','avobenzone, homosalat, octisalate, octocrylene','Spray','AVOBENZONE 30 mg/g','Topique','WALGREEN COMPANY','INT','Médicaments topiques','Walgreens SPF 50 Sport Continuous Sunscreen'),
('Sertraline','sertraline','Comprimé','SERTRALINE HYDROCHLORIDE 100 mg/1','Orale','NuCare Pharmaceuticals,Inc.','US','Serotonin Reuptake Inhibitor','Sertraline'),
('Moisture Sunscreen SPF 50','titanium dioxide, zinc oxide','Lotion','OCTINOXATE 9 mg/120mL','Topique','Spa de Soleil','INT','Médicaments topiques','Moisture Sunscreen SPF 50'),
('AlphaNine SD','coagulation factor ix (human)','Kit',NULL,'Intraveineuse','GRIFOLS USA, LLC','US','Médicaments IV / Hospitaliers','AlphaNine SD'),
('Mckesson Hand Cleanse and Soothe with Aloe','chloroxylenol','Gel','CHLOROXYLENOL .95 g/g','Topique','Mckesson Medical-Surgical Inc.','INT','Médicaments topiques','Mckesson Hand Cleanse and Soothe with Aloe'),
('NativeRemedies InflammaGo','arnica, berberis, bryonia, dulcamara, rhus tox','LIQUID','ARNICA MONTANA 6 [hp_C]/59mL','Orale','Silver Star Brands','INT',NULL,'NativeRemedies InflammaGo'),
('Primidone','primidone','Comprimé','PRIMIDONE 50 mg/1','Orale','American Health Packaging','US','Anti-epileptic Agent','Primidone'),
('Gelato Homecare','stannous fluoride','Gel','STANNOUS FLUORIDE .116 g/120g','DENTAL','Mycone Dental Supply Co., Inc DBA Keystone Industries and Deepak Products Inc.','INT',NULL,'Gelato Homecare'),
('Sinus PE plus Allergy','chlorpheniramine maleate and phenylephrine hcl','Comprimé','CHLORPHENIRAMINE MALEATE 4 mg/1','Orale','Walgreen Company','INT','Histamine-1 Receptor Antagonist','Sinus PE plus Allergy'),
('Walgreens Antibacterial Hand Wipes','benzalkonium chloride','CLOTH','BENZALKONIUM CHLORIDE .11 g/100mL','Topique','Walgreen Co.','INT','Médicaments topiques','Walgreens Antibacterial Hand Wipes'),
('Sun Bum 15 Premium Moisturizing Sunscreen 6 OZ','avobenzone, homosalate, octisalate, octocrylene','Lotion','AVOBENZONE 20 mg/mL','Topique','Sun Bum, LLC','INT','Médicaments topiques','Sun Bum 15 Premium Moisturizing Sunscreen 6 OZ'),
('Nasal Decongestant PE Maximum Strength Non-Drowsy','phenylephrine 10 mg','Comprimé','PHENYLEPHRINE HYDROCHLORIDE 10 mg/1','Orale','Allegiant Health','INT','alpha-1 Adrenergic Agonist','Nasal Decongestant PE Maximum Strength Non-Drowsy'),
('Daytime Nighttime Cold and Flu','acetaminophen dextromethorphan hbr phenylephrine hci doxylaminesucinate','Kit',NULL,NULL,'Harris Teeter, LLC','INT',NULL,'Daytime Nighttime Cold and Flu'),
('Procto-Med HC','hydrocortisone','Crème','HYDROCORTISONE 25 mg/g','Topique','Leading Pharma, LLC','US','Corticosteroid','Procto-Med HC'),
('Old Spice Clinical Sweat Defense Stronger Swagger Soft','aluminum zirconium trichlorohydrex gly','STICK','ALUMINUM ZIRCONIUM TRICHLOROHYDREX GLY 20 g/100g','Topique','The Procter & Gamble Manufacturing Company','INT','Médicaments topiques','Old Spice Clinical Sweat Defense Stronger Swagger Soft'),
('DERMOSCRIBE ICHYBUM','hydrocortisone, clioquinol, zinc oxide','Crème','CLIOQUINOL 1 g/100g','Topique','DERMOSCRIBE PTY LTD','INT','Corticosteroid','DERMOSCRIBE ICHYBUM'),
('Crest Complete Plus Scope Outlast Ultra','sodium fluoride','PASTE, DENTIFRICE','SODIUM FLUORIDE 1.5 mg/g','DENTAL','The Procter & Gamble Manufacturing Company','INT',NULL,'Crest Complete Plus Scope Outlast Ultra'),
('FifthPulse Hydrocortisone 4oz','hydrocortisone','Pommade','HYDROCORTISONE 1 g/100g','Topique','Front Pharmaceutical PLC','INT','Corticosteroid','FifthPulse Hydrocortisone 4oz'),
('Multi-Symptom Cold and Fever Childrens','acetaminophen, dextromethorphan hbr, guaifenesin, phenylephrine hcl','Solution','ACETAMINOPHEN 325 mg/10mL','Orale','CVS PHARMACY','INT','Expectorant','Multi-Symptom Cold and Fever Childrens'),
('ULINE Eyewash','eyewash','Solution','WATER 465 mL/473mL','Ophtalmique','Uline.','US','Ophtalmologie','ULINE Eyewash'),
('Neosporin Kids Plus Pain Relief','neomycin sulfate, polymyxin b sulfate, and pramoxine hydrochloride','Crème','NEOMYCIN SULFATE 3.5 mg/g','Topique','Kenvue Brands LLC','INT','Aminoglycoside Antibacterial','Neosporin Kids Plus Pain Relief'),
('Clean and Clear Essentials Dual Action Moisturizer','salicylic acid','Lotion','SALICYLIC ACID 5 mg/mL','Topique','Kenvue Brands LLC','INT','Médicaments topiques','Clean and Clear Essentials Dual Action Moisturizer'),
('CR-5667753 Leader Daily Moisturizer','cr-5667753 leader daily moisturizer','Pommade','PETROLATUM 41 g/100g','Topique','Cardinal Health','INT','Médicaments topiques','CR-5667753 Leader Daily Moisturizer'),
('CardinalExtra Strength Antacid Wintergreen flavor','calcium carbonate','Comprimé','CALCIUM CARBONATE 750 mg/1','Orale','CARDINAL HEALTH','INT','Blood Coagulation Factor','CardinalExtra Strength Antacid Wintergreen flavor'),
('Smart Care MORNING DEW HAND SANITIZER','ethyl alcohol','Spray','ALCOHOL 70 mL/100mL','Topique','Ashtel Studios, Inc.','INT','Médicaments topiques','Smart Care MORNING DEW HAND SANITIZER'),
('Levetiracetam ER','levetiracetam','Comprimé','LEVETIRACETAM 500 mg/1','Orale','REMEDYREPACK INC.','US','Decreased Central Nervous System Disorganized Electrical Activity','Levetiracetam ER'),
('MYCOPHENOLIC ACID','mycophenolic acid','Comprimé','MYCOPHENOLATE SODIUM 360 mg/1','Orale','REMEDYREPACK INC.','US','Antimetabolite Immunosuppressant','MYCOPHENOLIC ACID'),
('GOOD REMEDIES Allergy Relief SOFTGEL','diphenhydramine hydrochloride','Gélule','DIPHENHYDRAMINE HYDROCHLORIDE 25 mg/1','Orale','Strive Pharmaceuticals Inc.','INT','Histamine-1 Receptor Antagonist','GOOD REMEDIES Allergy Relief SOFTGEL'),
('JAYTHARI Oral Suspension','deflazacort','Suspension','DEFLAZACORT 22.75 mg/mL','Orale','Zydus Pharmaceuticals (USA) Inc.','US','Corticosteroid','JAYTHARI Oral Suspension'),
('Acne Face Wash','calendula, yarrow, chamomile','OIL','ACHILLEA MILLEFOLIUM FLOWER 1 [hp_X]/100mL','Topique','Spry Life LLC','INT','Médicaments topiques','Acne Face Wash'),
('Thera Care Hot and Cold Medicated Patch','menthol','Patch transdermique','MENTHOL 5 g/100g','Topique','Veridian Healthcare','INT','Médicaments topiques','Thera Care Hot and Cold Medicated Patch'),
('ProHeal Alcohol Prep Pad','isopropyl alcohol','Patch transdermique','ISOPROPYL ALCOHOL 70 g/100g','Topique','Taizhou Kangping Medical Science And Technology Co., Ltd.','INT','Médicaments topiques','ProHeal Alcohol Prep Pad'),
('PredniSONE Tablets, USP, 20 mg','prednisone','Comprimé','PREDNISONE 20 mg/1','Orale','Bryant Ranch Prepack','US','Corticosteroid','PredniSONE Tablets, USP, 20 mg'),
('Glossier sun glaze gleaming sunscreen oil broad spectrum SPF 30 Water Resistant 40 Min','glossier sun glaze gleaming sunscreen oil broad spectrum spf 30 water resistant 40 min','Spray','AVOBENZONE 3 g/100g','Topique','Glossier Inc.','INT','Médicaments topiques','Glossier sun glaze gleaming sunscreen oil broad spectrum SPF 30 Water Resistant 40 Min'),
('Valproic','valproic acid','Gélule','VALPROIC ACID 250 mg/1','Orale','Aphena Pharma Solutions - Tennessee, LLC','US','Anti-epileptic Agent','Valproic'),
('Hand Wipes','chlorhexidine digluconate and benzethonium chloride','CLOTH','BENZETHONIUM CHLORIDE .08 g/g','Topique','JIANGMEN SHUIZIRUN SANITARY ARTICLES CO., LTD.','INT','Decreased Cell Wall Integrity','Hand Wipes'),
('Benefit Plus Drops','kidney (suis), abrotanum, anacardium orientale, baryta muriatica, calcarea carbonica, calcarea phosphorica, glandula suprarenalis suis, graphites, helleborus niger, hepar suis, hypothalamus suis, ignatia amara, lycopodium clavatum, secale cornutum, silicea, thymus (suis), thyroidinum (suis)','LIQUID','ARTEMISIA ABROTANUM FLOWERING TOP 8 [hp_X]/mL','Orale','Gulf Coast Wellness Center','INT','Blood Coagulation Factor','Benefit Plus Drops'),
('AY BENDITO THERMOACTIVE','menthol, camphor','Spray','CAMPHOR (SYNTHETIC) 5.3 g/100mL','Topique','AY BENDITO INTERNATIONAL, INC','INT','Médicaments topiques','AY BENDITO THERMOACTIVE'),
('Cryselle','norgestrel and ethinyl estradiol','Kit',NULL,'Orale','Teva Pharmaceuticals, Inc.','US',NULL,'Cryselle'),
('Cough Drops Dollar General Honey Lemon 30ct','menthol','Pastille','MENTHOL 7.5 mg/1','Orale','Dollar General Corporation','INT',NULL,'Cough Drops Dollar General Honey Lemon 30ct'),
('Nourishing Hand Sanitizer Limon','alcohol','Solution','ALCOHOL 70 mL/100mL','Topique','Noshinku','INT','Médicaments topiques','Nourishing Hand Sanitizer Limon'),
('Abbasi co Minoxidil','abbasi co minoxidil shampoo','LIQUID','MINOXIDIL 5 mg/100mg','Topique','Guangzhou Yilong Cosmetics.,Ltd','INT','Arteriolar Vasodilator','Abbasi co Minoxidil'),
('Abacavir','abacavir','Comprimé','ABACAVIR SULFATE 300 mg/1','Orale','XLCare Pharmaceuticals Inc.','US','Human Immunodeficiency Virus Nucleoside Analog Reverse Transcriptase Inhibitor','Abacavir'),
('Prometrium','progesterone','Gélule','PROGESTERONE 100 mg/1','Orale','Acertis Pharmaceuticals, LLC','US','Progesterone','Prometrium'),
('NebuClear MD','saline','LIQUID','SODIUM CHLORIDE 9 mg/9mg','Inhalation','Blue Echo Care LLC','INT',NULL,'NebuClear MD'),
('ANTIPERSPIRANT ABOVE INVISIBLE FEMININO','antiperspirant above invisible feminino aerosol','Spray','ALUMINUM SESQUICHLOROHYDRATE 16 g/100g','Topique','BASTON INDUSTRIA DE AEROSSIS LTDA','INT','Médicaments topiques','ANTIPERSPIRANT ABOVE INVISIBLE FEMININO'),
('Zenibell Snail IntensiveCream','glycerin','Crème','GLYCERIN 2 g/100g','Topique','MISOCOS','INT','Non-Standardized Chemical Allergen','Zenibell Snail IntensiveCream'),
('SFERANGS COLLAGEN SYNERGY AMPOULE','adenosine','LIQUID','ADENOSINE .04 g/100mL','Topique','NOKSIBCHO cosmetic Co., Ltd.','INT','Adenosine Receptor Agonist','SFERANGS COLLAGEN SYNERGY AMPOULE'),
('PLAY Antioxidant Body Mist SPF 50 - Vanilla Orchid','avobenzone, homosalate, octisalate, octocrylene','Spray','AVOBENZONE 3 mg/100mL','Topique','Supergoop LLC','INT','Médicaments topiques','PLAY Antioxidant Body Mist SPF 50 - Vanilla Orchid'),
('Lessina','levonorgestrel and ethinyl estradiol','Kit',NULL,NULL,'Teva Pharmaceuticals USA, Inc.','US',NULL,'Lessina'),
('Hillyard E2 Food Industry Foaming','benzalkonium chloride','LIQUID','BENZALKONIUM CHLORIDE .13 g/100mL','Topique','Hillyard GMP','INT','Médicaments topiques','Hillyard E2 Food Industry Foaming'),
('Bupivilog Kit','marcaine, kenalog, povidone iodine','Kit',NULL,'Épidurale','Asclemed USA, Inc.','INT',NULL,'Bupivilog Kit'),
('VIGAFYDE','vigabatrin','Solution','VIGABATRIN 100 mg/mL','Orale','Upsher-Smith Laboratories, LLC','US','Anti-epileptic Agent','VIGAFYDE'),
('Caring mill Mineral Eye Cream','zinc oxide','LIQUID','ZINC OXIDE 14.4 g/100mL','Topique','FSA STORE INC.','INT','Médicaments topiques','Caring mill Mineral Eye Cream'),
('Club Wipes Sanitizing Wipes Lemon Scent','benzalkonium chloride','CLOTH','BENZALKONIUM CHLORIDE 1.3 mg/g','Topique','Golden Mills LLC','INT','Médicaments topiques','Club Wipes Sanitizing Wipes Lemon Scent'),
('Rezurock','belumosudil','Comprimé','BELUMOSUDIL 200 mg/1','Orale','Kadmon Pharmaceuticals, LLC','US',NULL,'Rezurock'),
('Natrum Sulphuricum 6X','sodium sulfate','PELLET','SODIUM SULFATE 6 [hp_X]/1','Sublinguale','SEVENE USA','INT','Osmotic Laxative','Natrum Sulphuricum 6X'),
('Betr sleep aid','diphenhydramine hydrochloride','Comprimé','DIPHENHYDRAMINE HYDROCHLORIDE 25 mg/1','Orale','Live Betr LLC','INT','Histamine-1 Receptor Antagonist','Betr sleep aid'),
('4 Way Fast Acting','phenylephrine hydrochloride','Spray','PHENYLEPHRINE HYDROCHLORIDE 10 mg/mL','Nasale','Haleon US Holdings LLC','INT','alpha-1 Adrenergic Agonist','4 Way Fast Acting'),
('ELROEL Pang Pang Sun Cushion Plus','zinc oxide, titanium dioxide, octinoxate, octisalate','Crème','OCTINOXATE 7 g/100g','Topique','MONOGLOT HOLDINGS Inc.','INT','Copper Absorption Inhibitor','ELROEL Pang Pang Sun Cushion Plus'),
('24 Hour Acne Serum','benzoyl peroxide','Gel','BENZOYL PEROXIDE 5 g/100g','Topique','Drmtlgy, LLC','INT','Médicaments topiques','24 Hour Acne Serum'),
('Clotrimazole (Topical Solution), 1%','clotrimazole','Solution','CLOTRIMAZOLE 10 mg/mL','Topique','Puro Pharma Inc.','INT','Azole Antifungal','Clotrimazole (Topical Solution), 1%'),
('INTIMALE LIDOCAINE DELAY','lidocaine hydrochloride','Solution','LIDOCAINE HYDROCHLORIDE 10 mg/mL','Topique','SKINS SEXUAL HEALTH LIMITED','INT','Amide Local Anesthetic','INTIMALE LIDOCAINE DELAY'),
('Progest-Oil-2oz-SB','progest-oil-2oz-sb','OIL','PROGESTERONE 12.8 g/60g','Transdermique','Shyne Brands/BIOLabs PRO','INT','Progesterone','Progest-Oil-2oz-SB'),
('VYJUVEK','vyjuvek','Kit',NULL,NULL,'Krystal Biotech, Inc.','US',NULL,'VYJUVEK'),
('Ethanol','alcohol','Gel','ALCOHOL 70 mL/100mL','Topique','TARGET CORPORATION INC.','INT','Médicaments topiques','Ethanol'),
('ZIOPTAN','tafluprost','Solution','TAFLUPROST .015 mg/mL','Ophtalmique','Thea Pharma Inc.','US','Prostaglandin Analog','ZIOPTAN'),
('BlueStop Max','external analgesic','Gel','LIDOCAINE HYDROCHLORIDE 40 mg/g','Topique','Clavel Corporation','INT','Amide Local Anesthetic','BlueStop Max'),
('Bestmade Natural Products BM106','aesculus, beta vulgaris, calc fluor, negundium americana, paeonia off, ratanhia, sedum acre, sulphur','LIQUID','ACER NEGUNDO WHOLE 30 [hp_C]/30[hp_C]','Orale','Bestmade Natural Products','INT',NULL,'Bestmade Natural Products BM106'),
('Bestmade Natural Products Mag Carb','magnesia carbonica','Comprimé','MAGNESIUM CARBONATE 30 [hp_C]/30[hp_C]','Orale','Bestmade Natural Products','INT',NULL,'Bestmade Natural Products Mag Carb'),
('Kidney Liquescence','juniperus communis, uva-ursi, equisetum hyemale, taraxacum officinale, eupatorium purpureum, kidney (bovine), nitricum acidum, cantharis, hepar sulphuris calcareum','LIQUID','ARCTOSTAPHYLOS UVA-URSI LEAF 2 [hp_X]/mL','Orale','Nutritional Specialties, Inc.','INT','Non-Standardized Food Allergenic Extract','Kidney Liquescence'),
('SYLVIRENE MILIA REMOVER','salicylic acid 1% milia remover','LIQUID','SALICYLIC ACID 1 g/100mL','Topique','Jiangxi Yudexi Pharmaceutical Co., LTD','INT','Médicaments topiques','SYLVIRENE MILIA REMOVER'),
('EZBIORT 5% Minoxidil Hair Growth Sprays Serum','minoxidil','LIQUID','BIOTIN .5 g/100mL','Topique','Guangzhou Borderless Technology Co., Ltd.','INT','Arteriolar Vasodilator','EZBIORT 5% Minoxidil Hair Growth Sprays Serum'),
('Folliculitis Treatment Cream','miconazole nitrate','Crème','MICONAZOLE NITRATE 15 mg/g','Topique','TAGRID LLC','INT','Azole Antifungal','Folliculitis Treatment Cream'),
('Tinted Mineral Sunscreen','zinc oxide','Crème','ZINC OXIDE 200 mg/g','Topique','Micro Fibro Blast','INT','Médicaments topiques','Tinted Mineral Sunscreen')
) AS v(nom, dci, forme, dosage, voie, labo, pays, classe, nomcom)
WHERE NOT EXISTS (
  SELECT 1 FROM medicaments m WHERE UPPER(m.nom) = UPPER(v.nom)
);
