-- ndc_batch_050.sql (80 rows)
INSERT INTO medicaments (nom, dci, forme, dosage, voie_administration, laboratoire, pays, classe_therapeutique, nom_commercial)
SELECT v.nom, v.dci, v.forme, v.dosage, v.voie, v.labo, v.pays, v.classe, v.nomcom
FROM (VALUES
('L-ISOLEUCINE','l-isoleucine','Poudre','ISOLEUCINE 1 kg/kg',NULL,'Ajinomoto do Brasil Industria e Comercio de Alimentos Ltda.','INT',NULL,NULL),
('EDARAVONE','edaravone','Poudre','EDARAVONE 1 kg/kg',NULL,'SOLARA ACTIVE PHARMA SCIENCES LIMITED','INT',NULL,NULL),
('SLU-PP-332','slu-pp-332','Poudre','4-HYDROXYBENZOIC ACID 1 g/g',NULL,'Qingdao Biopeptek Co., Ltd.','INT',NULL,NULL),
('Molnupiravir','molnupiravir','Poudre','MOLNUPIRAVIR 20 kg/20kg',NULL,'Biophore India Pharmaceuticals Pvt. Ltd','INT',NULL,NULL),
('Iron sucrose liquid','iron sucrose liquid','LIQUID','IRON SUCROSE 30 kg/30kg',NULL,'SIONC PHARMACEUTICALS PVT LTD','INT',NULL,NULL),
('Preferred Antibacterial Plus Urinary Pain Relief','methenamine, sodium salicylate','Comprimé','METHENAMINE 162 mg/1','Orale','Reese Pharmaceutical Co','INT',NULL,'Preferred Antibacterial Plus Urinary Pain Relief'),
('phenazone','phenazone','Poudre','ANTIPYRINE 1 kg/kg',NULL,'Hebei Jiheng Pharmaceutical Co., Ltd.','INT',NULL,NULL),
('EIGHT HOUR NIGHT','dimethicone','EMULSION','DIMETHICONE 2 mg/g','Topique','REVLON','INT','Skin Barrier Activity','EIGHT HOUR NIGHT'),
('Zenocutuzumab','zenocutuzumab','LIQUID','ZENOCUTUZUMAB 20 mg/20mg',NULL,'Boehringer Ingelheim Fremont, Inc.','INT',NULL,NULL),
('up and up naproxen sodium pm','diphenhydramine hydrochloride, naproxen sodium','Comprimé','DIPHENHYDRAMINE HYDROCHLORIDE 25 mg/1','Orale','Target Corporation','US','Histamine-1 Receptor Antagonist','up and up naproxen sodium pm'),
('HYCAMTIN','topotecan hydrochloride','Solution','TOPOTECAN HYDROCHLORIDE 4 mg/4mL','Intraveineuse','Novartis Pharmaceuticals Corporation','US','Topoisomerase Inhibitor','HYCAMTIN'),
('GUNA-TGF BETA 1','transforming growth factor beta 1','Solution','TRANSFORMING GROWTH FACTOR BETA-1 4 [hp_C]/30mL','Orale','Guna spa','INT',NULL,'GUNA-TGF BETA 1'),
('Levetiracetam Levetiracetam','levetiracetam','Solution','LEVETIRACETAM 100 mg/mL','Orale','Atlantic Biologicals Corp.','US','Decreased Central Nervous System Disorganized Electrical Activity','Levetiracetam Levetiracetam'),
('PROMACTA','eltrombopag olamine','Suspension','ELTROMBOPAG OLAMINE 12.5 mg/1','Orale','Novartis Pharmaceuticals Corporation','US','Thrombopoietin Receptor Agonist','PROMACTA'),
('LBEL FOREVER MATTE LONGWEAR AND CONTROL FOUNDATION 72H SPF 15 CAPUCCINO 310C','octinoxate, zinc oxide','EMULSION','OCTINOXATE 50 mg/g','Topique','BEL STAR S.A.','INT','Médicaments topiques','LBEL FOREVER MATTE LONGWEAR AND CONTROL FOUNDATION 72H SPF 15 CAPUCCINO 310C'),
('Sun Defense Minerals (Deep)','zinc oxide','Poudre','ZINC OXIDE 235 mg/g','Topique','Eminence Organic Skin Care','INT','Médicaments topiques','Sun Defense Minerals (Deep)'),
('Signature Care Honey Lemon Cough Drops','menthol','Pastille','MENTHOL 7.5 mg/1','Orale','Safeway','INT',NULL,'Signature Care Honey Lemon Cough Drops'),
('Nighttime Cold and Flu Relief','acetaminophen, dextromethorphan hbr, doxylamine succinate','Gélule','ACETAMINOPHEN 325 mg/1','Orale','Safeway, Inc.','INT','Antihistamine','Nighttime Cold and Flu Relief'),
('Covergirl plus Olay Simply Ageless Foundation plus Titanium Dioxide Sunscreen Broad Spectrum SPF 28 (All shades)','titanium dioxide','Crème','TITANIUM DIOXIDE 4.9 mg/.1g','Topique','Noxell Corporation','INT','Médicaments topiques','Covergirl plus Olay Simply Ageless Foundation plus Titanium Dioxide Sunscreen Broad Spectrum SPF 28 (All shades)'),
('Post Oak Pollen','quercus stellata','Solution','QUERCUS STELLATA POLLEN .025 g/mL','INTRADERMAL','Greer Laboratories, Inc.','US','Non-Standardized Pollen Allergenic Extract','Post Oak Pollen'),
('SUTAB','sodium sulfate, magnesium sulfate, and potassium chloride','Comprimé','MAGNESIUM SULFATE ANHYDROUS 2.7 g/1','Orale','Azurity Pharmaceuticals, Inc.','US','Calculi Dissolution Agent','SUTAB'),
('good sense migraine formula','acetaminophen, aspirin, caffeine','Comprimé','ACETAMINOPHEN 250 mg/1','Orale','L. Perrigo Company','US','Central Nervous System Stimulant','good sense migraine formula'),
('Famciclovir','famciclovir','Comprimé','FAMCICLOVIR 125 mg/1','Orale','Macleods Pharmaceuticals Limited','US','Herpesvirus Nucleoside Analog DNA Polymerase Inhibitor','Famciclovir'),
('Topcare Nasal','oxymetazoline hydrochloride','Spray','OXYMETAZOLINE HYDROCHLORIDE .05 g/100mL','Nasale','Topco Associates LLC','INT','Vasoconstrictor','Topcare Nasal'),
('parodontax','stannous fluoride','PASTE','STANNOUS FLUORIDE 1.1 mg/g','DENTAL','Haleon US Holdings LLC','INT',NULL,'parodontax'),
('Tums Chewy Bites','calcium carbonate','Comprimé','CALCIUM CARBONATE 750 mg/1','Orale','Haleon US Holdings LLC','INT','Blood Coagulation Factor','Tums Chewy Bites'),
('Sensodyne Pronamel Kids Bubble Twist','sodium fluoride','PASTE','SODIUM FLUORIDE 1.1 mg/g','DENTAL','Haleon US Holdings LLC','INT',NULL,'Sensodyne Pronamel Kids Bubble Twist'),
('HEB Camphor Phenol','camphor 10.8% and phenol 4.7%','LIQUID','CAMPHOR (NATURAL) 108 mg/mL','Topique','H E B','INT','Médicaments topiques','HEB Camphor Phenol'),
('Daytime Severe Cold and Cough','acetaminophen, dextromethorphan hbr, phenylephrine hcl','LIQUID','ACETAMINOPHEN 650 mg/30mL','Orale','H E B','INT','Sigma-1 Agonist','Daytime Severe Cold and Cough'),
('equaline daytime cold and flu relief','acetaminophen, dextromethorphan hbr, phenylephrine hcl','Solution','ACETAMINOPHEN 325 mg/15mL','Orale','United Natural Foods, Inc. dba UNFI','INT','Sigma-1 Agonist','equaline daytime cold and flu relief'),
('24 hour allergy','cetirizine hydrochloride','Comprimé','CETIRIZINE HYDROCHLORIDE 10 mg/1','Orale','Meijer Distribution Inc','US','Histamine-1 Receptor Antagonist','24 hour allergy'),
('Publix Regular Strength Peppermint Flavor','calcium carbonate','Comprimé','CALCIUM CARBONATE 500 mg/1','Orale','PUBLIX SUPER MARKETS, INC','INT',NULL,'Publix Regular Strength Peppermint Flavor'),
('Vir Combination','adenoviren nosode, cytomegalovirus nosode, herpes simplex virus 1 dna, herpes simplex virus 2 dna, epstein-barr virus nosode, hepatitis b nosode, herpes simplex 1 nosode, herpes simplex 2 nosode, human herpesvirus 6a, human herpesvirus 6b, influenzinum (2023-2024)','LIQUID','HEPATITIS B VIRUS 33 [hp_X]/mL','Orale','Deseret Biologicals, Inc.','INT','Live Human Adenovirus Type 4 Vaccine','Vir Combination'),
('Toxodetox','toxoplasma gondii','LIQUID','TOXOPLASMA GONDII 12 [hp_X]/mL','Orale','BioActive Nutritional, Inc.','INT',NULL,'Toxodetox'),
('Progesterone Phenolic','progesterone','LIQUID','PROGESTERONE 6 [hp_X]/mL','Orale','Energique, Inc.','INT','Progesterone','Progesterone Phenolic'),
('Hydrogen Peroxide 3 Percent','hydrogen peroxide','LIQUID','HYDROGEN PEROXIDE 2.65 mL/100mL','Topique','Whole Foods Market','INT','Médicaments topiques','Hydrogen Peroxide 3 Percent'),
('ZO Skin Health Sheer Fluid Broad-Spectrum Sunscreen SPF 50','zinc oxide','Lotion','ZINC OXIDE .225 g/50mL','Topique','ZO Skin Health, Inc.','INT','Médicaments topiques','ZO Skin Health Sheer Fluid Broad-Spectrum Sunscreen SPF 50'),
('CONSTIPATION','magnesia carbonica, magnesia muriatica, aesculus hippocastanum, alumen, alumina, bryonia alba, nux vomica, silicea','LIQUID','ALUMINUM OXIDE 12 [hp_X]/mL','Orale','Natural Creations, Inc.','INT','Calculi Dissolution Agent','CONSTIPATION'),
('Tygacil','tigecycline','Solution','TIGECYCLINE 50 mg/5mL','Intraveineuse','Wyeth Pharmaceuticals LLC, a subsidiary of Pfizer Inc.','US','Tetracycline-class Antibacterial','Tygacil'),
('REBINYN','coagulation factor ix recombinant, glycopegylated','Kit',NULL,NULL,'Novo Nordisk','US',NULL,'REBINYN'),
('Phoma','phoma betae','Solution injectable','PLEOSPORA BETAE .1 g/mL','CUTANEOUS','Allermed Laboratories, Inc.','US','Non-Standardized Fungal Allergenic Extract','Phoma'),
('PARURE GOLD SKIN MATTE FOUNDATION NO-TRANSFER HIGH PERFECTION 24H CARE AND WEAR INFUSED WITH 24K GOLD AND WHITE PEONY WITH SUNSCREEN BROADSPECTRUM SPF 15 0N','octisalate, titanium dioxide','EMULSION','OCTISALATE 35 mg/mL','Topique','Guerlain','INT','Médicaments topiques','PARURE GOLD SKIN MATTE FOUNDATION NO-TRANSFER HIGH PERFECTION 24H CARE AND WEAR INFUSED WITH 24K GOLD AND WHITE PEONY WITH SUNSCREEN BROADSPECTRUM SPF 15 0N'),
('La Roche Posay Anthelios UV Clear Daily Invisible Broad Spectrum SPF 50 Sunscreen','avobenzone, homosalate, octisalate and octocrylene','Lotion','AVOBENZONE 30 mg/mL','Topique','L''Oreal USA Products Inc','INT','Médicaments topiques','La Roche Posay Anthelios UV Clear Daily Invisible Broad Spectrum SPF 50 Sunscreen'),
('Lymph HP','aconitum napellus, arsenicum album, baptisia tinctoria, belladonna, bryonia, causticum, echinacea, eupatorium perfoliatum, ferrum phosphoricum, gelsemium sempervirens, hydrastis canadensis, hypericum perforatum, kali carbonicum, lachesis mutus, lobelia inflata, lomatium dissectum, lung, natrum sulphuricum, phosphorus, phytolacca decandra, pulsatilla, pyrogenium, rhus tox, silicea, sulphur, symphytum officinale','LIQUID','ACONITUM NAPELLUS WHOLE 30 [hp_X]/mL','Orale','Energique, Inc.','INT',NULL,'Lymph HP'),
('Ciclopirox','ciclopirox','SHAMPOO','CICLOPIROX 1 g/100mL','Topique','Padagis Israel Pharmaceuticals Ltd','US','Decreased DNA Replication','Ciclopirox'),
('Alert Aid','caffeine','Comprimé','CAFFEINE 200 mg/1','Orale','Amerisource Bergen','INT','Central Nervous System Stimulant','Alert Aid'),
('Temozolomide','temozolomide','Gélule','TEMOZOLOMIDE 140 mg/1','Orale','Sun Pharmaceutical Industries, Inc.','US','Alkylating Drug','Temozolomide'),
('Green Guard Super Stat Blood Clotting First Aid','benzethonium chloride and lidocaine','Spray','BENZETHONIUM CHLORIDE 170 mg/85g','Topique','Unifirst First Aid Corporation','INT','Amide Local Anesthetic','Green Guard Super Stat Blood Clotting First Aid'),
('Levico Prunus','levico prunus','LIQUID','FERRIC OXIDE RED 6 [hp_X]/mL','Orale','Uriel Pharmacy Inc.','INT',NULL,'Levico Prunus'),
('Equate Flu and Severe Cold and Cough','acetaminophen, diphenhydramine hydrochloride, phenylephrine hydrochloride','Solution','ACETAMINOPHEN 650 mg/1','Orale','Wal-Mart Stores Inc','INT','Histamine-1 Receptor Antagonist','Equate Flu and Severe Cold and Cough'),
('Rituxan','rituximab','Solution','RITUXIMAB 10 mg/mL','Intraveineuse','Genentech, Inc.','US','CD20-directed Cytolytic Antibody','Rituxan'),
('TRIBIOTIC','bacitracin zinc, neomycin sulfate, polymyxin b sulfate','Pommade','BACITRACIN ZINC 400 [iU]/g','Topique','HART Health','INT','Aminoglycoside Antibacterial','TRIBIOTIC'),
('Solu-Cortef','hydrocortisone sodium succinate','Solution','HYDROCORTISONE SODIUM SUCCINATE 100 mg/2mL','Intramusculaire','Pharmacia & Upjohn Company LLC','US','Corticosteroid','Solu-Cortef'),
('ALLEGRA ALLERGY','fexofenadine hydrochloride','Comprimé','FEXOFENADINE HYDROCHLORIDE 180 mg/1','Orale','A-S Medication Solutions','US','Histamine-1 Receptor Antagonist','ALLEGRA ALLERGY'),
('Belladonna','atropa belladonna','PELLET','ATROPA BELLADONNA 15 [hp_C]/15[hp_C]','Orale','Boiron','INT',NULL,'Belladonna'),
('NITROSTAT','nitroglycerin','Comprimé','NITROGLYCERIN .4 mg/1','Sublinguale','A-S Medication Solutions','US','Nitrate Vasodilator','NITROSTAT'),
('Top Value Effervescent Cold Relief - Orange','aspirin, chlorpheniramine maleate, phenylephrine bitartrate','Comprimé','ASPIRIN 325 mg/1','Orale','Tower Laboratories Ltd.','INT','Histamine-1 Receptor Antagonist','Top Value Effervescent Cold Relief - Orange'),
('CareALL Triple Antibiotic plus Pain Relief','bacitracin zinc, neomycin sulfate, polymyxin b sulfate, pramoxine hcl','Pommade','BACITRACIN ZINC 500 [USP''U]/g','Topique','New World Imports, Inc','INT','Aminoglycoside Antibacterial','CareALL Triple Antibiotic plus Pain Relief'),
('W/CLIP PDQ INSTANT HAND SANITIZER','ethyl alcohol','Kit',NULL,NULL,'Universal Distribution Center LLC','INT',NULL,'W/CLIP PDQ INSTANT HAND SANITIZER'),
('Aloe Vera Petrolatum Jelly','petrolatum','JELLY','PETROLATUM 99.35 g/100g','Topique','Shield Line LLC','INT','Médicaments topiques','Aloe Vera Petrolatum Jelly'),
('PRIMAQUINE PHOSPHATE','primaquine phosphate','Comprimé','PRIMAQUINE PHOSPHATE 15 mg/1','Orale','Ingenus Pharmaceuticals, LLC','US','Antimalarial','PRIMAQUINE PHOSPHATE'),
('SPF 30 Sport Sunscreen GoodSense','avobenzone 3%, homosalate 15%, octisalate 5%, octocrylene 8%','Spray','AVOBENZONE 3 g/100g','Topique','Geiss, Destin, & Dunn, Inc','INT','Médicaments topiques','SPF 30 Sport Sunscreen GoodSense'),
('Articaine Hydrochloride and Epinephrine','articaine hydrochloride and epinephrine','Solution','ARTICAINE HYDROCHLORIDE 40 mg/mL','SUBMUCOSAL','Novocol Pharmaceutical of Canada, Inc.','US','Amide Local Anesthetic','Articaine Hydrochloride and Epinephrine'),
('MAGSIL ANTACID (LEMON MINT)','aluminum hydroxide dried gel, magnesium hydroxide, and simethicone','Comprimé','ALUMINUM HYDROXIDE 200 mg/1','Orale','FORTUNE PHARMACAL COMPANY LIMITED','INT','Calculi Dissolution Agent','MAGSIL ANTACID (LEMON MINT)'),
('CVS Original Nasal Mist','oxymetazoline hcl','Spray','OXYMETAZOLINE HYDROCHLORIDE .05 g/100mL','Nasale','CVS PHARMACY, INC','INT','Vasoconstrictor','CVS Original Nasal Mist'),
('HEPARIN SODIUM IN SODIUM CHLORIDE','heparin sodium in sodium chloride','Solution','HEPARIN SODIUM 10000 [USP''U]/100mL','Intraveineuse','HF Acquisition Co LLC, DBA HealthFirst','US','Anti-coagulant','HEPARIN SODIUM IN SODIUM CHLORIDE'),
('Exchange Select Powder Fresh Deodorant','aluminum zirconium pentachlorohydrex gly','STICK','ALUMINUM ZIRCONIUM PENTACHLOROHYDREX GLY 180 mg/g','Topique','Army & Air Force Exchange Service','INT','Médicaments topiques','Exchange Select Powder Fresh Deodorant'),
('Sinus Pressure and Pain','acetaminophen, phenylephrine hcl','Comprimé','ACETAMINOPHEN 325 mg/1','Orale','Family Dollar Services Inc','INT','alpha-1 Adrenergic Agonist','Sinus Pressure and Pain'),
('NEUPOGEN','filgrastim','Solution','FILGRASTIM 300 ug/mL','Intraveineuse','Amgen, Inc','US','Leukocyte Growth Factor','NEUPOGEN'),
('Stannum Metallicum','stannum metallicum','Crème','TIN 6 [hp_X]/50mL','Topique','True Botanica, LLC','INT','Médicaments topiques','Stannum Metallicum'),
('Hydrocodone Bitartrate and Ibuprofen','hydrocodone bitartrate and ibuprofen','Comprimé','HYDROCODONE BITARTRATE 2.5 mg/1','Orale','Amneal Pharmaceuticals of New York LLC','US','Nonsteroidal Anti-inflammatory Drug','Hydrocodone Bitartrate and Ibuprofen'),
('Dermatone SPF 50 Sunscreen Stick','zinc oxide','STICK','ZINC OXIDE 200 mg/g','Topique','Dermatone','INT','Médicaments topiques','Dermatone SPF 50 Sunscreen Stick'),
('NUDESCREEN DEWY ILLUMINATING GLOW SPF 30 - Angel Glow','zinc oxide sunscreen','Lotion','ZINC OXIDE 15 g/100mL','Topique','Bentley Laboratories, LLC','INT','Copper Absorption Inhibitor','NUDESCREEN DEWY ILLUMINATING GLOW SPF 30 - Angel Glow'),
('Tusnel DM','dextromethorphan hbr, guaifenesin, phenylephrine hcl','LIQUID','DEXTROMETHORPHAN HYDROBROMIDE 20 mg/5mL','Orale','Llorens Pharmaceutical International Division, Inc.','INT','Expectorant','Tusnel DM'),
('Kali Sulph 6X','potassium sulfate','Comprimé','POTASSIUM SULFATE 6 [hp_X]/1','Orale','Hyland''s Inc.','INT','Osmotic Laxative','Kali Sulph 6X'),
('cle de peau BEAUTE THE FOUNDATION N B50 TAN BEIGE','octinoxate and titanium dioxide','EMULSION','OCTINOXATE 1092 mg/28mL','Topique','SHISEIDO AMERICAS CORPORATION','INT','Médicaments topiques','cle de peau BEAUTE THE FOUNDATION N B50 TAN BEIGE'),
('Giltuss EX Maximum Strength Expectorant','giltuss ex maximum strength expectorant','Comprimé','GUAIFENESIN 1200 mg/1','Orale','Gil Pharmaceutical Corp','INT','Expectorant','Giltuss EX Maximum Strength Expectorant'),
('Sodium Sulfacetamide and Sulfur','sulfacetamide sodium, sulfur','LIQUID','SULFACETAMIDE SODIUM 100 mg/g','Topique','Method Pharmaceuticals, LLC','INT','Sulfonamide Antibacterial','Sodium Sulfacetamide and Sulfur'),
('ARCTIC RELIEF','menthol, unspecified form','Gel','MENTHOL, UNSPECIFIED FORM 3.969 g/113.4g','Topique','STRATUS PHARMACEUTICALS INC','INT','Médicaments topiques','ARCTIC RELIEF'),
('Phosphorus','phosphorus','PELLET','PHOSPHORUS 15 [hp_C]/15[hp_C]','Orale','Boiron','INT',NULL,'Phosphorus')
) AS v(nom, dci, forme, dosage, voie, labo, pays, classe, nomcom)
WHERE NOT EXISTS (
  SELECT 1 FROM medicaments m WHERE UPPER(m.nom) = UPPER(v.nom)
);
