-- ndc_batch_025.sql (80 rows)
INSERT INTO medicaments (nom, dci, forme, dosage, voie_administration, laboratoire, pays, classe_therapeutique, nom_commercial)
SELECT v.nom, v.dci, v.forme, v.dosage, v.voie, v.labo, v.pays, v.classe, v.nomcom
FROM (VALUES
('Sleepy Time CP','aconitum, arsenicum alb, calc carb, coffea cruda, magnesium met, nux vom, pulsatilla, sepia, sulphur','LIQUID','ACONITUM NAPELLUS WHOLE 30 [hp_X]/mL','Orale','Natural Creations, Inc','INT','Non-Standardized Food Allergenic Extract','Sleepy Time CP'),
('Cefuroxime','cefuroxime','Solution','CEFUROXIME SODIUM 750 mg/8mL','Intraveineuse','Hikma Pharmaceuticals USA Inc.','US','Cephalosporin Antibacterial','Cefuroxime'),
('Trauma Relief','chamomilla, echinacea (angustifolia), hamamelis virginiana, hypericum perforatum, millefolium, calendula officinalis, arnica montana, belladonna, bellis perennis, clematis vitalba, flos, helianthemum nummularium, flos, impatiens glandulifera, flos, ornithogalum umbellatum, flos, prunus cerasifera, flos, symphytum officinale, rhus tox, bryonia (alba), hepar sulphuris calcareum, carbo vegetabilis','LIQUID','ACHILLEA MILLEFOLIUM WHOLE 3 [hp_X]/g','Topique','Deseret Biologicals, Inc.','INT','Médicaments topiques','Trauma Relief'),
('SENNOSIDES','sennosides','Comprimé','SENNOSIDES A AND B 15 mg/1','Orale','TIME CAP LABORATORIES, INC','INT',NULL,'SENNOSIDES'),
('Arsenicum album','arsenic trioxide','PELLET','ARSENIC TRIOXIDE 5 [hp_C]/5[hp_C]','Orale','Boiron','INT',NULL,'Arsenicum album'),
('Dermabon Multi Symptom Psoriasis Control','coal tar','SOAP','COAL TAR 21.3 mg/g','Topique','Dermabon de Chihuahua, S.A. de C.V.','INT','Médicaments topiques','Dermabon Multi Symptom Psoriasis Control'),
('Kiehls Super Fluid Daily UV Defense SPF 50 plus Anti-Pollution Lightweight Formula for All Skin Types','avobenzone, homosalate, octisalate, octocrylene and oxybenzone','Crème','AVOBENZONE 30 mg/mL','Topique','L''Oreal USA Products Inc','INT','Médicaments topiques','Kiehls Super Fluid Daily UV Defense SPF 50 plus Anti-Pollution Lightweight Formula for All Skin Types'),
('Fatigue Stat CM','echinacea (angustifolia), lomatium dissectum, tabebuia impetiginosa, hydrastis canadensis, phytolacca decandra, aranea diadema, ipecacuanha, iridium metallicum, lachesis mutus, muriaticum acidum, rhus tox, cytomegalovirus nosode','LIQUID','ARANEUS DIADEMATUS 6 [hp_X]/mL','Orale','Energique, Inc','INT',NULL,'Fatigue Stat CM'),
('Miconazole Nitrate','anti-fungal powder miconazole nitrate talc free','Poudre','MICONAZOLE NITRATE 1.42 g/71g','Topique','AmerisourceBergen Drug Corporation','INT','Azole Antifungal','Miconazole Nitrate'),
('Medi-First Burn with Lidocaine','benzalkonium chloride, lidocaine','Crème','BENZALKONIUM CHLORIDE 1.3 mg/g','Topique','Unifirst First Aid Corporation','INT','Amide Local Anesthetic','Medi-First Burn with Lidocaine'),
('Hepar Magnesium 8X','hepar magnesium 8x','LIQUID','BEEF LIVER 8 [hp_X]/mL','Orale','Uriel Pharmacy, Inc','INT','Calculi Dissolution Agent','Hepar Magnesium 8X'),
('Miconazole 3 Combination Pack','miconazole nitrate','Kit',NULL,NULL,'EQUATE (Wal-Mart Stores, Inc.) (see also WAL-MART INC)','US',NULL,'Miconazole 3 Combination Pack'),
('Apis mellifica','apis mellifera','PELLET','APIS MELLIFERA 30 [hp_X]/30[hp_X]','Orale','Boiron','INT','Standardized Insect Venom Allergenic Extract','Apis mellifica'),
('MG DermaGel 70','ethyl alcohol','LIQUID','ALCOHOL .7 L/L','Topique','Morgan Gallacher Inc. DBA Custom Chemical Formulators Inc.','INT','Médicaments topiques','MG DermaGel 70'),
('Asepxia Scrub Acne Bar','salicylic acid','SOAP','SALICYLIC ACID 2 g/100g','Topique','Genomma Lab USA','INT','Médicaments topiques','Asepxia Scrub Acne Bar'),
('NARCAN','naloxone hydrochloride','Spray','NALOXONE HYDROCHLORIDE 4 mg/.1mL','Nasale','A-S Medication Solutions','US','Opioid Antagonist','NARCAN'),
('clear days ahead overnight repair salicylic acid acne treatment pads','salicylic acid','CLOTH','SALICYLIC ACID 283.5 mg/56.7g','Topique','Philosophy Inc.','INT','Médicaments topiques','clear days ahead overnight repair salicylic acid acne treatment pads'),
('CareALL Acetaminophen','acetaminophen','Comprimé','ACETAMINOPHEN 325 mg/1','Orale','New World Imports, Inc','INT',NULL,'CareALL Acetaminophen'),
('Pyrithione Zinc 0.5 Dandruff','pyrithione zinc','SHAMPOO','PYRITHIONE ZINC .5 g/100mL','Topique','Universal Distribution Center LLC','INT','Médicaments topiques','Pyrithione Zinc 0.5 Dandruff'),
('Psoriasin Deep Moisturizing','coal tar','Pommade','COAL TAR 20 mg/g','Topique','Kobayashi Healthcare International, Inc.','INT','Médicaments topiques','Psoriasin Deep Moisturizing'),
('MILK OF MAGNESIA','magnesium hydroxide','Suspension','MAGNESIUM HYDROXIDE 1200 mg/15mL','Orale','GOODSENSE','INT','Calculi Dissolution Agent','MILK OF MAGNESIA'),
('GENOTROPIN','somatropin','Kit',NULL,NULL,'Pfizer Laboratories Div Pfizer Inc','US',NULL,'GENOTROPIN'),
('AMLODIPINE, VALSARTAN, HYDROCHLOROTHIAZIDE','amlodipine besylate valsartan hydrochlorothiazide','Comprimé','AMLODIPINE BESYLATE 5 mg/1','Orale','Golden State Medical Supply, Inc.','US','Angiotensin 2 Receptor Blocker','AMLODIPINE, VALSARTAN, HYDROCHLOROTHIAZIDE'),
('COLTALIN-DM','acetaminophen, chlorpheniramine maleate, dextromethorphan hydrobromide, phenylephrine hydrochloride','Comprimé','ACETAMINOPHEN 325 mg/1','Orale','FORTUNE PHARMACAL COMPANY LIMITED','INT','Histamine-1 Receptor Antagonist','COLTALIN-DM'),
('Dulcamara','solanum dulcamara top','PELLET','SOLANUM DULCAMARA TOP 200 [kp_C]/200[kp_C]','Orale','Boiron','INT',NULL,'Dulcamara'),
('CVS Maximum Strength','dextromethorphan hbr, guaifenesin','Solution','DEXTROMETHORPHAN HYDROBROMIDE 20 mg/20mL','Orale','CVS PHARMACY','INT','Expectorant','CVS Maximum Strength'),
('VENOFER (IRON SUCROSE)','venofer (iron sucrose)','Solution','IRON SUCROSE 20 mg/mL','Intraveineuse','HF Acquisition Co LLC, DBA HealthFirst','US','Parenteral Iron Replacement','VENOFER (IRON SUCROSE)'),
('Sleep-Aid','diphenhydramine hcl','Comprimé','DIPHENHYDRAMINE HYDROCHLORIDE 25 mg/1','Orale','ARMY AND AIR FORCE EXCHANGE SERVICE','INT','Histamine-1 Receptor Antagonist','Sleep-Aid'),
('citroma','magnesium citrate','LIQUID','MAGNESIUM CITRATE 1.745 g/29.6mL','Orale','Family Dollar Stores, Inc','INT','Calculi Dissolution Agent','citroma'),
('LUMAKRAS','sotorasib','Comprimé','SOTORASIB 120 mg/1','Orale','Amgen Inc','US',NULL,'LUMAKRAS'),
('Ionite APF Neutral','sodium fluoride','Gel','SODIUM FLUORIDE 4.41 g/490g','DENTAL','Dharma Research, inc.','INT',NULL,'Ionite APF Neutral'),
('Cleanse','benzalkonium chloride','Solution','BENZALKONIUM CHLORIDE .13 g/100mL','Topique','Medline Industries, LP','INT','Médicaments topiques','Cleanse'),
('Aurum Metallicum 9X','aurum metallicum 9x','LIQUID','GOLD 9 [hp_X]/30mL','Orale','True Botanica, LLC','INT','Standardized Chemical Allergen','Aurum Metallicum 9X'),
('ChloraPrep Swabstick','chlorhexidine gluconate and isopropyl alcohol','Solution','CHLORHEXIDINE GLUCONATE 20 mg/mL','Topique','CareFusion 213 LLC','US','Decreased Cell Wall Integrity','ChloraPrep Swabstick'),
('Acne Control Face Wash','salicylic acid','Gel','SALICYLIC ACID 2 g/100mL','Topique','Bentley Laboratories, LLC','INT','Médicaments topiques','Acne Control Face Wash'),
('Tusnel SF','dextromethorphan hbr, guaifenesin','LIQUID','DEXTROMETHORPHAN HYDROBROMIDE 10 mg/5mL','Orale','Llorens Pharmaceutical International Division, Inc.','INT','Expectorant','Tusnel SF'),
('SKIN MEDICA Purifying Foaming Wash','salicylic acid','LIQUID','SALICYLIC ACID 20 mg/mL','Topique','Allergan, Inc.','INT','Médicaments topiques','SKIN MEDICA Purifying Foaming Wash'),
('Natrum carbonicum','sodium carbonate','PELLET','SODIUM CARBONATE 200 [kp_C]/200[kp_C]','Orale','Boiron','INT',NULL,'Natrum carbonicum'),
('cle de peau BEAUTE THE FOUNDATION N O60 DEEP TAN OCHER','octinoxate and titanium dioxide','EMULSION','OCTINOXATE 1092 mg/28mL','Topique','SHISEIDO AMERICAS CORPORATION','INT','Médicaments topiques','cle de peau BEAUTE THE FOUNDATION N O60 DEEP TAN OCHER'),
('Giltuss Allergy Plus','chlophedianol hcl, chlorpheniramine maleate, phenylephrine hcl','Comprimé','CHLOPHEDIANOL HYDROCHLORIDE 24 mg/1','Orale','Gil Pharmaceutical Corp','INT','Histamine-1 Receptor Antagonist','Giltuss Allergy Plus'),
('ESTERIFIED ESTROGENS AND METHYLTESTOSTERONE HALF STRENGTH','esterified estrogens, methyltestosterone','Comprimé','ESTROGENS, ESTERIFIED .625 mg/1','Orale','Method Pharmaceuticals, LLC','INT','Androgen','ESTERIFIED ESTROGENS AND METHYLTESTOSTERONE HALF STRENGTH'),
('BACITRACIN ZINC','bacitracin zinc','Pommade','BACITRACIN ZINC 500 [USP''U]/g','Topique','STRATUS PHARMACEUTICALS INC','INT','Decreased Cell Wall Synthesis & Repair','BACITRACIN ZINC'),
('DermacinRx Skin Moisturizing Ultra SPF 50 Sunscreen','avobenzone, octinoxate, octisalate, titanium dioxide','Lotion','AVOBENZONE 25 mg/mL','Topique','PureTek Corporation','INT','Médicaments topiques','DermacinRx Skin Moisturizing Ultra SPF 50 Sunscreen'),
('Heavy Metal-Amalga Detox','allium sativum, aluminium metallicum, arg. met., aur. met., baryta carb., beryllium metallicum, bismuthum metallicum, cadmium metallicum, calc. fluor., carbo veg., chelidonium majus, cinchona, cobaltum met., cuprum met., glycyrrhiza glabra, hydrofluoricum acidum, iris versicolor, manganum metallicum, merc. viv., niccolum metallicum, osmium metallicum, platinum met., plumb. met., stannum met., strontium carb., thallium metallicum, titanium metallicum, carduus mar., taraxacum','LIQUID','ACTIVATED CHARCOAL 20 [hp_X]/mL','Orale','Newton Laboratories, Inc.','INT','Copper-containing Intrauterine Device','Heavy Metal-Amalga Detox'),
('Senna Laxative','sennosides','Comprimé','SENNOSIDES 8.6 mg/1','Orale','DOLGENCORP, LLC','INT',NULL,'Senna Laxative'),
('Dollar General','nasal phenylephrine hydrochloride','Spray','PHENYLEPHRINE HYDROCHLORIDE 1 g/100mL','Nasale','DOLGENCORP, INC. (DOLLAR GENERAL & REXALL)','INT','alpha-1 Adrenergic Agonist','Dollar General'),
('3.5OZ MP DRY CHIVALRY','aluminum chlorohydrate','Spray','ALUMINUM CHLOROHYDRATE 24.5 g/100g','Topique','Rejoice International Corp.','INT','Médicaments topiques','3.5OZ MP DRY CHIVALRY'),
('Aspirin Enteric Safety Coated','aspirin','Comprimé','ASPIRIN 81 mg/1','Orale','Publix Supermarkets, Inc.','INT','Nonsteroidal Anti-inflammatory Drug','Aspirin Enteric Safety Coated'),
('Senna Syrup','sennosides','LIQUID','SENNOSIDES 8.8 mg/5mL','Orale','Rising Pharma Holdings, Inc.','INT',NULL,'Senna Syrup'),
('GeriCare Docusate Sodium Liquid','docusate sodium','LIQUID','DOCUSATE SODIUM 50 mg/5mL','Orale','GERI-CARE PHARMACEUTICALS, CORP','INT',NULL,'GeriCare Docusate Sodium Liquid'),
('N-1 Adrenal Energizer','berberis vulgaris whole, viscum album whole, solidago virgaurea whole, bos taurus adrenal gland, arnica montana, dibasic potassium phosphate, and sus scrofa spleen','Solution','ARNICA MONTANA 8 [hp_X]/mL','Sublinguale','DNA Labs, Inc.','INT',NULL,'N-1 Adrenal Energizer'),
('Naloxone Hydrochloride Injection, USP, Auto-Injector','naloxone hydrochloride','Solution','NALOXONE HYDROCHLORIDE 10 mg/.4mL','Intramusculaire','Kaleo, Inc.','US','Opioid Antagonist','Naloxone Hydrochloride Injection, USP, Auto-Injector'),
('H-BI Hemorrhoids Formula','calendula officinallis, hamamelis virginiana','OIL','CALENDULA OFFICINALIS FLOWERING TOP 12 [hp_C]/11mL','Topique','Healing Natural Oils LLC','INT','Médicaments topiques','H-BI Hemorrhoids Formula'),
('VERATRUM VIRIDE','veratrum viride root','PELLET','VERATRUM VIRIDE ROOT 200 [kp_C]/200[kp_C]','Orale','Boiron','INT',NULL,'VERATRUM VIRIDE'),
('Fexofenadine HCl and Pseudoephedrine HCI','fexofenadine hcl and pseudoephedrine hci','Comprimé','FEXOFENADINE HYDROCHLORIDE 60 mg/1','Orale','CVS Pharmacy','US','Histamine-1 Receptor Antagonist','Fexofenadine HCl and Pseudoephedrine HCI'),
('Phenytoin','phenytoin','Comprimé','PHENYTOIN 50 mg/1','Orale','American Health Packaging','US','Anti-epileptic Agent','Phenytoin'),
('Chlordiazepoxide Hydrochloride and Clidinium Bromide','chlordiazepoxide hydrochloride and clidinium bromide','Gélule','CHLORDIAZEPOXIDE HYDROCHLORIDE 5 mg/1','Orale','American Health Packaging','US','Anticholinergic','Chlordiazepoxide Hydrochloride and Clidinium Bromide'),
('Les Coja Organic SPF 30','ethylhexyl salicylate, homosalate, butyl methoxydibenzoylmethane','Lotion','BUTYL METHOXYDIBENZOYLMETHANE .03 g/g','Topique','RNA PHARMA, LLC','INT','Médicaments topiques','Les Coja Organic SPF 30'),
('MORUS ALBA POLLEN','mulberry white','Solution','MORUS ALBA POLLEN .05 g/mL','Sous-cutanée','ALK-Abello, Inc.','US','Non-Standardized Pollen Allergenic Extract','MORUS ALBA POLLEN'),
('T-Relief Extra Strength','calendula officinalis flowering top, matricaria recutita, hamamelis virginiana root bark/stem bark, achillea millefolium, ruta graveolens flowering top, comfrey root, aconitum napellus, echinacea, unspecified, baptisia tinctoria root, atropa belladonna, arnica montana, bellis perennis and hypericum perforatum','Solution','ACHILLEA MILLEFOLIUM 2 [hp_X]/50mL','Orale','MediNatura Inc','INT',NULL,'T-Relief Extra Strength'),
('Estradiol 1557','estradiol','LIQUID','ESTRADIOL 9 [hp_X]/29.5mL','Orale','Professional Complementary Health Formulas','INT','Estrogen','Estradiol 1557'),
('Helicobacter Pylori Nosode 4445','helicobacter pylori nosode','LIQUID','HELICOBACTER PYLORI 30 [hp_X]/59mL','Orale','Professional Complementary Health Formulas','INT',NULL,'Helicobacter Pylori Nosode 4445'),
('NU-DERM SUNFADER Skin Lightener with Sunscreen (SPF 15) PABA FREE','hydroquinone, octinoxate, and oxybenzone','Lotion','HYDROQUINONE 40 mg/g','Topique','Obagi Cosmeceuticals LLC','INT','Melanin Synthesis Inhibitor','NU-DERM SUNFADER Skin Lightener with Sunscreen (SPF 15) PABA FREE'),
('Day and Night Vitals','allium sat, aloe, arsenicum alb, berber vulg, calc phos, ceanothus, chelidonium maj, cholesterinum, clematis erecta, condurango, gambogia, hamamelis, kali brom, kali phos, lycopodium, nat carb, passiflora, senna, silicea, solidago, spigelia anth, spongia, veratrum vir','LIQUID','ALOE VERA LEAF 12 [hp_X]/59mL','Orale','NET Remedies','INT','Blood Coagulation Factor','Day and Night Vitals'),
('Dior Forever Skin Glow Flawless Radiant Skin True Foundation SPF 25 6,5W Warm','octisalate, titanium dioxide','EMULSION','OCTISALATE 45 mg/mL','Topique','Parfums Christian Dior','INT','Médicaments topiques','Dior Forever Skin Glow Flawless Radiant Skin True Foundation SPF 25 6,5W Warm'),
('Rivastigmine Tartrate','rivastigmine tartrate','Gélule','RIVASTIGMINE TARTRATE 1.5 mg/1','Orale','Chartwell RX, LLC','US','Cholinesterase Inhibitor','Rivastigmine Tartrate'),
('Cabana Beach Club with Blood Orange and Essential Oils SPF 50 Sunscreen','avobenzone, homosalate, octisalate, octocrylene','Lotion','AVOBENZONE 30 mg/mL','Topique','Fruit of the Earth, Inc.','INT','Médicaments topiques','Cabana Beach Club with Blood Orange and Essential Oils SPF 50 Sunscreen'),
('RUMEX CRISPUS POLLEN','dock yellow','Solution','RUMEX CRISPUS POLLEN .1 g/mL','Sous-cutanée','ALK-Abello, Inc.','US','Non-Standardized Pollen Allergenic Extract','RUMEX CRISPUS POLLEN'),
('Anti-BacterialHandSpray Fresh Rainfall','alcohol','Spray','ALCOHOL 72 mL/100mL','Topique','Bath & Body Works, Inc.','INT','Médicaments topiques','Anti-BacterialHandSpray Fresh Rainfall'),
('Syeda','drospirenone and ethinyl estradiol','Kit',NULL,NULL,'Bryant Ranch Prepack','US',NULL,'Syeda'),
('adapalene and benzoyl peroxide','adapalene and benzoyl peroxide','Gel','ADAPALENE .1 g/100g','Topique','Bryant Ranch Prepack','US','Retinoid','adapalene and benzoyl peroxide'),
('Pollinosis Combination 9261','pollinosis combination','LIQUID','ARSENIC TRIOXIDE 6 [hp_X]/29.5mL','Orale','Professional Complementary Health Formulas','INT',NULL,'Pollinosis Combination 9261'),
('Mitoxantrone','mitoxantrone hydrochloride','Solution','MITOXANTRONE HYDROCHLORIDE 2 mg/mL','Intraveineuse','Fresenius Kabi USA, LLC','US','Topoisomerase Inhibitor','Mitoxantrone'),
('Valproate Sodium','valproate sodium','Solution','VALPROATE SODIUM 100 mg/mL','Intraveineuse','Fresenius Kabi USA, LLC','US','Anti-epileptic Agent','Valproate Sodium'),
('Hawaiian Tropic Everyday Active SPF30','avobenzone,homosalate,octocrylene','Lotion','AVOBENZONE 2.2 g/100g','Topique','Edgewell Personal Care Brands LLC','INT','Médicaments topiques','Hawaiian Tropic Everyday Active SPF30'),
('G05 OXI-MET','adenosine triphosphate, ignatia amara, kali phosphoricum, natrum muriaticum, nux vomica, sulphur','Solution','ADENOSINE TRIPHOSPHATE 5 [hp_X]/mL','Sublinguale','Apex Energetics Inc.','INT','Non-Standardized Plant Allergenic Extract','G05 OXI-MET'),
('Broad Spectrum SPF 30 Sunscreen','broad spectrum spf 30 sunscreen','Lotion','ZINC OXIDE 8.25 g/44mL','Topique','Raining Rose','INT','Médicaments topiques','Broad Spectrum SPF 30 Sunscreen'),
('Quality Choice Mucus Relief','guaifenesin','Comprimé','GUAIFENESIN 400 mg/1','Orale','Chain Drug Marketing Association','INT','Expectorant','Quality Choice Mucus Relief'),
('Cetaphil Sheer Mineral Sunscreen SPF 50','titanium dioxide, zinc oxide','Lotion','TITANIUM DIOXIDE 90 mg/mL','Topique','Galderma Laboratories, L.P.','INT','Médicaments topiques','Cetaphil Sheer Mineral Sunscreen SPF 50'),
('COOL RELIEF ORAL ANESTHETIC','menthol','Pastille','MENTHOL 13.2 mg/1','Orale','Ricola USA Inc.','INT',NULL,'COOL RELIEF ORAL ANESTHETIC')
) AS v(nom, dci, forme, dosage, voie, labo, pays, classe, nomcom)
WHERE NOT EXISTS (
  SELECT 1 FROM medicaments m WHERE UPPER(m.nom) = UPPER(v.nom)
);
