-- ndc_batch_080.sql (80 rows)
INSERT INTO medicaments (nom, dci, forme, dosage, voie_administration, laboratoire, pays, classe_therapeutique, nom_commercial)
SELECT v.nom, v.dci, v.forme, v.dosage, v.voie, v.labo, v.pays, v.classe, v.nomcom
FROM (VALUES
('Rite Aid Extra Strength Assorted Fruit','calcium carbonate','Comprimé','CALCIUM CARBONATE 750 mg/1','Orale','RITE AID CORPORATION','INT',NULL,'Rite Aid Extra Strength Assorted Fruit'),
('Tafinlar','dabrafenib','Gélule','DABRAFENIB MESYLATE 75 mg/1','Orale','Novartis Pharmaceuticals Corporation','US','Kinase Inhibitor','Tafinlar'),
('GUNA-CELL','acetylcarnitine, l-ampc-alpha-lipoic ac-a-tocopherol-ascorbic acid-calc carb-citric ac-cobalamin-colchicum-conium-cupric sulf-herring sperm dna-ferrous fumarate-folic acid-fumaric acid-kali aspartate-mang phos-mang gluconate-mang phos ii-pyruvaldehyde-nat oxalaceticum-sodium pyruvate-niacin-pantothenic acid-ph-podophyllum peltatum-pyridoxine hydrochloride-riboflavin-saccharomyces cerevisiae rna-selenomethionine-succinic acid-sulfur-thiamine hydrochloride-zinc','Solution','.ALPHA.-LIPOIC ACID 3 [hp_X]/30mL','Orale','Guna spa','INT','Anti-coagulant','GUNA-CELL'),
('Cepacol Extra Strength Sore Throat honey lemon','benzocaine and menthol','Pastille','BENZOCAINE 15 mg/1','Orale','ATLANTIC BIOLOGICALS CORP.','INT','Standardized Chemical Allergen','Cepacol Extra Strength Sore Throat honey lemon'),
('MAYZENT','siponimod','Comprimé','SIPONIMOD .25 mg/1','Orale','Novartis Pharmaceuticals Corporation','US','Sphingosine 1-phosphate Receptor Modulator','MAYZENT'),
('CYZONE NITRO DESODORANTE ANTITRANSPIRANTE ROLL ON','aluminum sesquichlorohydrate','EMULSION','ALUMINUM SESQUICHLOROHYDRATE 132.8 mg/g','Topique','BEL STAR SA','INT','Médicaments topiques','CYZONE NITRO DESODORANTE ANTITRANSPIRANTE ROLL ON'),
('Aurovisc','hypromellose ophthalmic solution 2% w/v','Solution','HYPROMELLOSE 2208 (15000 MPA.S) 20 mg/mL','Ophtalmique','Aurolab','INT','Ophtalmologie','Aurovisc'),
('Fluphenazine Hydrochoride','fluphenazine hydrochloride','Comprimé','FLUPHENAZINE HYDROCHLORIDE 1 mg/1','Orale','Rising Pharma Holdings, Inc.','US','Phenothiazine','Fluphenazine Hydrochoride'),
('Signature Care Medicated Cooling','witch hazel','CLOTH','WITCH HAZEL 500 mg/1','Topique','Better Living Brands, LLC','INT','Médicaments topiques','Signature Care Medicated Cooling'),
('Sweetgum Pollen','liquidambar styraciflua','Solution','LIQUIDAMBAR STYRACIFLUA POLLEN .1 g/mL','INTRADERMAL','Greer Laboratories, Inc.','US','Non-Standardized Pollen Allergenic Extract','Sweetgum Pollen'),
('Longleaf Pine Pollen','pinus palustris','Solution','PINUS PALUSTRIS POLLEN .05 g/mL','INTRADERMAL','Greer Laboratories, Inc.','US','Non-Standardized Pollen Allergenic Extract','Longleaf Pine Pollen'),
('Central Western Weed Mix','kochia scoparia, chenopodium album and salsola kali','Solution','BASSIA SCOPARIA POLLEN 6666.6666 [PNU]/mL','INTRADERMAL','Greer Laboratories, Inc.','US','Non-Standardized Pollen Allergenic Extract','Central Western Weed Mix'),
('Dolce and Gabbana Meet Your Flawless Matte Skin Duo','octisalate, octocrylene, titanium dioxide, zinc oxide','Kit',NULL,NULL,'Socoplan','INT',NULL,'Dolce and Gabbana Meet Your Flawless Matte Skin Duo'),
('SOTYLIZE','sotalol hydrochloride','Solution','SOTALOL HYDROCHLORIDE 5 mg/mL','Orale','Azurity Pharmaceuticals, Inc.','US','Antiarrhythmic','SOTYLIZE'),
('NAS Targeted Spot Treatment','salicylic acid','LIQUID','SALICYLIC ACID .75 g/100g','Topique','Burt''s Bees','INT','Médicaments topiques','NAS Targeted Spot Treatment'),
('good sense allergy','diphenhydramine hcl','Solution','DIPHENHYDRAMINE HYDROCHLORIDE 12.5 mg/5mL','Orale','L. Perrigo Company','INT','Histamine-1 Receptor Antagonist','good sense allergy'),
('injoy heartburn relief','famotidine, calcium carbonate and magnesium hydroxide','Comprimé','CALCIUM CARBONATE 800 mg/1','Orale','L. Perrigo Company','US','Calculi Dissolution Agent','injoy heartburn relief'),
('Colgate MaxFresh Citrus Fresh','sodium fluoride','Gel','SODIUM FLUORIDE 1.1 mg/g','DENTAL','Colgate-Palmolive Company','INT',NULL,'Colgate MaxFresh Citrus Fresh'),
('Cinnamomum','cinnamomum','PELLET','CINNAMON 6 [hp_C]/1','Orale','Hahnemann Laboratories, INC.','INT','Non-Standardized Food Allergenic Extract','Cinnamomum'),
('Guaiacum','guaiacum','PELLET','GUAIACUM OFFICINALE RESIN 6 [hp_C]/1','Orale','Hahnemann Laboratories, INC.','INT',NULL,'Guaiacum'),
('SENSODYNE Rapid Relief','stannous fluoride','PASTE','STANNOUS FLUORIDE 1.1 mg/g','Orale','Haleon US Holdings LLC','INT',NULL,'SENSODYNE Rapid Relief'),
('Sensodyne Pronamel Kids Berry Twist','sodium fluoride','PASTE','SODIUM FLUORIDE 1.1 mg/g','DENTAL','Haleon US Holdings LLC','INT',NULL,'Sensodyne Pronamel Kids Berry Twist'),
('HEB SPF 50 Cucumber Water Scented Continuous Sunscreen','avobenzone, homosalate, octisalate, octocrylene','Spray','AVOBENZONE 30 mg/g','Topique','H.E.B','INT','Médicaments topiques','HEB SPF 50 Cucumber Water Scented Continuous Sunscreen'),
('HEB Dry Eye Eye Drops','glycerin, hypromellose, polyethylene glycol 400','Solution','GLYCERIN .2 g/100mL','Ophtalmique','HEB','INT','Non-Standardized Chemical Allergen','HEB Dry Eye Eye Drops'),
('Head Congestion plus Flu Severe','acetaminophen, dextromethorphan hydrobromide, guaifenesin, and phenylephrine hydrochloride','Comprimé','ACETAMINOPHEN 325 mg/1','Orale','United Natural Foods, Inc. dba UNFI','INT','Expectorant','Head Congestion plus Flu Severe'),
('STOOL SOFTENER-STIMULANT LAXATIVE','stool softener-stimulant laxative','Comprimé','DOCUSATE SODIUM 50 mg/1','Orale','Kroger Company','INT',NULL,'STOOL SOFTENER-STIMULANT LAXATIVE'),
('Publix Extra Strength Tropical Fruit','calcium carbonate','Comprimé','CALCIUM CARBONATE 750 mg/1','Orale','PUBLIX SUPER MARKETS, INC','INT',NULL,'Publix Extra Strength Tropical Fruit'),
('WELLBUTRIN SR','bupropion hydrochloride','Comprimé','BUPROPION HYDROCHLORIDE 200 mg/1','Orale','GlaxoSmithKline LLC','US','Aminoketone','WELLBUTRIN SR'),
('ENERGIZER','phosphoricum acidum, cocculus indicus, helonias dioica, ignatia amara, sepia, zincum metallicum','LIQUID','ANAMIRTA COCCULUS SEED 6 [hp_X]/mL','Orale','BioActive Nutritional, Inc.','INT',NULL,'ENERGIZER'),
('reconstituted Air','reconstituted air','GAS','OXYGEN 210 mL/L','Inhalation','AMERICAN WELDING & GAS, INC.','US',NULL,'reconstituted Air'),
('WINTER BLEND','echinacea (angustifolia), uva-ursi, baptisia tinctoria, convallaria majalis, kali muriaticum, pinus sylvestris, thuja occidentalis, bryonia, crotalus horridus, lachesis mutus, selenium metallicum, viscum album','LIQUID','ARCTOSTAPHYLOS UVA-URSI LEAF 1 [hp_X]/mL','Orale','Energique, Inc.','INT','Osmotic Laxative','WINTER BLEND'),
('Acne Care Charcoal Cleanser','acne care charcoal cleanser','LIQUID','SALICYLIC ACID 3.61 g/3.61g','Topique','Whole Foods Market','INT','Médicaments topiques','Acne Care Charcoal Cleanser'),
('ZO Skin Health Daily Mineral Sunshade Broad-Spectrum Sunscreen SPF 45 (Light Medium)','titanium dioxide, zinc oxide','Lotion','TITANIUM DIOXIDE 54 mg/mL','Topique','ZO Skin Health Inc.','INT','Médicaments topiques','ZO Skin Health Daily Mineral Sunshade Broad-Spectrum Sunscreen SPF 45 (Light Medium)'),
('Zincum Metallicum 12X','zincum metallicum','LIQUID','ZINC 12 [hp_X]/mL','Orale','Natural Creations, Inc','INT',NULL,'Zincum Metallicum 12X'),
('FLOLAN','epoprostenol sodium','Solution','EPOPROSTENOL SODIUM 1.5 mg/1','Intraveineuse','GlaxoSmithKline LLC','US','Prostacycline Vasodilator','FLOLAN'),
('Motion-Time Chewable','meclizine hcl','Comprimé','MECLIZINE HYDROCHLORIDE 25 mg/251','Orale','Time-Cap Labs, Inc','INT','Antiemetic','Motion-Time Chewable'),
('Aspergillus niger','aspergillus niger','LIQUID','ASPERGILLUS NIGER VAR. NIGER .1 g/mL','PERCUTANEOUS','Allermed Laboratories, Inc.','US','Non-Standardized Fungal Allergenic Extract','Aspergillus niger'),
('PARURE GOLD SKIN MATTE FOUNDATION NO-TRANSFER HIGH PERFECTION 24H CARE AND WEAR INFUSED WITH 24K GOLD AND WHITE PEONY WITH SUNSCREEN BROADSPECTRUM SPF 15 4W','octisalate, titanium dioxide','EMULSION','OCTISALATE 35 mg/mL','Topique','Guerlain','INT','Médicaments topiques','PARURE GOLD SKIN MATTE FOUNDATION NO-TRANSFER HIGH PERFECTION 24H CARE AND WEAR INFUSED WITH 24K GOLD AND WHITE PEONY WITH SUNSCREEN BROADSPECTRUM SPF 15 4W'),
('CeraVe AM Facial Moisturizing Broad Spectrum SPF 50 Sunscreen','homosalate, octisalate, octocrylene and zinc oxide','Lotion','HOMOSALATE 80 mg/mL','Topique','L''Oreal USA Products Inc','INT','Copper Absorption Inhibitor','CeraVe AM Facial Moisturizing Broad Spectrum SPF 50 Sunscreen'),
('Sinus HP','arsenicum album, hepar sulphuris calcareum, hydrastis canadensis, kali bichromicum, lycopodium clavatum, mercurius solubilis, natrum muriaticum, phosphorus, pulsatilla (pratensis), sepia, thuja occidentalis','LIQUID','ARSENIC TRIOXIDE 30 [hp_X]/mL','Orale','Energique, Inc.','INT',NULL,'Sinus HP'),
('ATORVALIQ','atorvaliq','Suspension','ATORVASTATIN CALCIUM TRIHYDRATE 20 mg/5mL','Orale','CMP Pharma, Inc.','US','HMG-CoA Reductase Inhibitor','ATORVALIQ'),
('Green Guard Burn','lidocaine hcl','Spray','LIDOCAINE HYDROCHLORIDE 20 g/L','Topique','Unifirst First Aid Corporation','INT','Amide Local Anesthetic','Green Guard Burn'),
('Meteoric Iron Prunus','meteoric iron prunus','LIQUID','ECHINACEA, UNSPECIFIED 3 [hp_X]/mL','Orale','Uriel Pharmacy Inc.','INT',NULL,'Meteoric Iron Prunus'),
('LUCENTIS','ranibizumab','Solution','RANIBIZUMAB 10 mg/mL','INTRAVITREAL','Genentech, Inc.','US','Vascular Endothelial Growth Factor Inhibitor','LUCENTIS'),
('HISTAPRIN','diphenhydramine','Comprimé','DIPHENHYDRAMINE HYDROCHLORIDE 25 mg/1','Orale','NorMed','INT','Histamine-1 Receptor Antagonist','HISTAPRIN'),
('Terocin','lidocaine, menthol','Patch transdermique','LIDOCAINE 600 mg/1','Topique','Alexso, Inc','INT','Amide Local Anesthetic','Terocin'),
('Patterson Dental Topical Anesthetic','benzocaine','Gel','BENZOCAINE 200 mg/g','DENTAL','Patterson Dental','INT','Standardized Chemical Allergen','Patterson Dental Topical Anesthetic'),
('CAREALL Anti-Itch','diphenhydramine hydrochloride and zinc acetate cream','Crème','DIPHENHYDRAMINE HYDROCHLORIDE 20 mg/g','Topique','New World Imports, Inc','INT','Copper Absorption Inhibitor','CAREALL Anti-Itch'),
('2.5% Menthol PAIN RELIEF','menthol','Gel','MENTHOL, UNSPECIFIED FORM 25 mg/g','Topique','Universal Distribution Center LLC','INT','Médicaments topiques','2.5% Menthol PAIN RELIEF'),
('MedPride Vitamin A and D','white petrolatum','Pommade','PETROLATUM 76 g/100g','Topique','Shield Line LLC','INT','Médicaments topiques','MedPride Vitamin A and D'),
('Isosorbide dinitrate and hydralazine hydrochloride','isosorbide dinitrate and hydralazine hydrochloride','Comprimé','HYDRALAZINE HYDROCHLORIDE 37.5 mg/1','Orale','Ingenus Pharmaceuticals, LLC','US','Arteriolar Vasodilator','Isosorbide dinitrate and hydralazine hydrochloride'),
('Toms Whole Care Mouthwash Fresh Mint','sodium fluoride','RINSE','SODIUM FLUORIDE 1 mg/10mL','DENTAL','Tom''s of Maine, Inc.','INT',NULL,'Toms Whole Care Mouthwash Fresh Mint'),
('Salicylic Acid 40% / Corn Remover','salicylic acid','PLASTER','SALICYLIC ACID .4 g/g','Topique','ASO Pharmaceutical Co.,ltd.','INT','Médicaments topiques','Salicylic Acid 40% / Corn Remover'),
('CVS DayTime and NightTime Value Pack Cold and Flu','acetaminophen, phenylephrine hydrochloride, and doxylamine succinate','Kit',NULL,NULL,'CVS PHARMACY','INT',NULL,'CVS DayTime and NightTime Value Pack Cold and Flu'),
('Allergy Relief Extra Strength','diphenhydramine hcl','Comprimé','DIPHENHYDRAMINE HYDROCHLORIDE 50 mg/1','Orale','CVS WOONSOCKET PRESCRIPTION CENTER, INCORPORATED','INT','Histamine-1 Receptor Antagonist','Allergy Relief Extra Strength'),
('Childrens Cough and Cold','chlorpheniramine maleate, dextrometrorphan hbr','LIQUID','CHLORPHENIRAMINE MALEATE 2 mg/10mL','Orale','FAMILY DOLLAR SERVICES INC','INT','Histamine-1 Receptor Antagonist','Childrens Cough and Cold'),
('Marinol','dronabinol','Gélule','DRONABINOL 2.5 mg/1','Orale','ThePharmaNetwork, LLC','US','Cannabinoid','Marinol'),
('Apis Mell. 30X','apis mellifera venom','LIQUID','APIS MELLIFERA VENOM 30 [hp_X]/30mL','Orale','True Botanica, LLC','INT',NULL,'Apis Mell. 30X'),
('Radically Rejuvenating SPF Day Cream','zinc oxide','Crème','ZINC OXIDE 20 g/100g','Topique','Better Planet Brands LLC','INT','Médicaments topiques','Radically Rejuvenating SPF Day Cream'),
('Liquid Acetaminophen','acetaminophen','LIQUID','ACETAMINOPHEN 160 mg/5mL','Orale','LLORENS PHARMACEUTICALS INTERNATIONAL DIVISION','INT',NULL,'Liquid Acetaminophen'),
('Kids Cough and Mucus Daytime Grape Flavor','bryonia alba root,calcium sulfide,pulsatilla vulgaris whole,ferrosoferric phosphate,phosphorus,antimony potassium tartrate,ipecac,rumex crispus root','LIQUID','ANTIMONY POTASSIUM TARTRATE 15 [hp_X]/mL','Orale','Hyland''s Consumer Health Inc.','INT',NULL,'Kids Cough and Mucus Daytime Grape Flavor'),
('SHISEIDO REVITALESSENCE SKIN GLOW FOUNDATION 160','octinoxate','EMULSION','OCTINOXATE 2.30805 g/30mL','Topique','SHISEIDO AMERICAS CORPORATION','INT','Médicaments topiques','SHISEIDO REVITALESSENCE SKIN GLOW FOUNDATION 160'),
('Rompe Pecho NT NT','acetaminophen, dextromethorphan hbr, doxylamine succinate','LIQUID','ACETAMINOPHEN 650 mg/30mL','Orale','Efficient Laboratories Inc','INT','Antihistamine','Rompe Pecho NT NT'),
('OIDO SANA','isopropyl alcohol','Solution','ISOPROPYL ALCOHOL .95 g/mL','AURICULAR (OTIC)','ProMex LLC','INT',NULL,'OIDO SANA'),
('Lidocaine HCl 3% and Hydrocortisone Acetate 0.5% Cream','lidocaine hcl and hydrocortisone acetate','Kit',NULL,'Rectale','PureTek Corporation','INT',NULL,'Lidocaine HCl 3% and Hydrocortisone Acetate 0.5% Cream'),
('Dairy-Grain-Nightshade','iris vers., solidago, antimon. crud., arg. nit., arsenicum alb., avena, baptisia, belladonna, bryonia, capsicum, carduus ben., cinchona, dulcamara, fagopyrum, gelsemium, hyoscyamus, ipecac., lac vac., lachesis, lycopodium, nat. mur., phos., podoph. pelt., pulsatilla, rhus tox., sac. lac., secale, sepia, stramonium, tabacum, triticum, ustilago maidis, verbascum, lycopersicum, solanum nig., solanum tub., stigmata, torula cerevisiae.','LIQUID','ANEMONE PULSATILLA 15 [hp_X]/mL','Orale','Newton Laboratories, Inc.','INT','Non-Standardized Food Allergenic Extract','Dairy-Grain-Nightshade'),
('GERI-LANTA MAXIMUM STRENGTH','aluminum hydroxide, magnesium hydroxide, dimethicone','Suspension','ALUMINUM HYDROXIDE 400 mg/5mL','Orale','Geri-Care Pharmaceuticals, Corp','INT','Calculi Dissolution Agent','GERI-LANTA MAXIMUM STRENGTH'),
('PEDIARIX','diphtheria and tetanus toxoids and acellular pertussis adsorbed, hepatitis b (recombinant) and inactivated poliovirus vaccine combined','Suspension','BORDETELLA PERTUSSIS FILAMENTOUS HEMAGGLUTININ ANTIGEN (FORMALDEHYDE INACTIVATED) 25 ug/.5mL','Intramusculaire','GlaxoSmithKline Biologicals SA','US','Inactivated Bordetella Pertussis Vaccine','PEDIARIX'),
('N-18','oyster shell calcium carbonate, crude, sepia officinalis juice, silicon dioxide, nitric acid, and sus scrofa pineal gland','Solution','NITRIC ACID 12 [hp_X]/mL','Sublinguale','DNA Labs, Inc.','INT',NULL,'N-18'),
('cle de peau BEAUTE THE FOUNDATION N M O60','octinoxate and titanium dioxide','PASTE','OCTINOXATE 1.165 g/28mL','Topique','Shiseido Americas Corporation','INT','Médicaments topiques','cle de peau BEAUTE THE FOUNDATION N M O60'),
('Sleep Aid Formula','apium graveolens, salvia officinalis','OIL','CELERY SEED 6 [hp_C]/11mL','Topique','Healing Natural Oils LLC','INT','Non-Standardized Food Allergenic Extract','Sleep Aid Formula'),
('PLANTSCRIPTION SPF 25 POWER ANTI-AGING oil FREE BROAD SPECTRUM','avobenzone, homosalate, octisalate, and octocrylene','Crème','AVOBENZONE 30 mg/mL','Topique','ORIGINS NATURAL RESOURCES INC.','INT','Médicaments topiques','PLANTSCRIPTION SPF 25 POWER ANTI-AGING oil FREE BROAD SPECTRUM'),
('Mulpleta','lusutrombopag','Comprimé','LUSUTROMBOPAG 3 mg/1','Orale','SHIONOGI INC.','US',NULL,'Mulpleta'),
('PAXIL','paroxetine hydrochloride','Comprimé','PAROXETINE HYDROCHLORIDE 10 mg/1','Orale','Apotex Corp','US','Serotonin Reuptake Inhibitor','PAXIL'),
('Cover Recover SPF 30 Sand','zinc oxide and titanium dioxide','Crème','TITANIUM DIOXIDE 65 mg/mL','Topique','Allure Labs, Inc','INT','Copper Absorption Inhibitor','Cover Recover SPF 30 Sand'),
('Digestive Enzyme Drops 2018','digestive enzyme drops','LIQUID','BEEF LIVER 6 [hp_X]/59mL','Orale','Professional Complementary Health Formulas','INT','Non-Standardized Food Allergenic Extract','Digestive Enzyme Drops 2018'),
('Muscle/Ligament/Cartilage Drops 5015','muscle/ligament/cartilage drops','LIQUID','BOS TAURUS LIGAMENT 6 [hp_X]/59mL','Orale','Professional Complementary Health Formulas','INT','Calculi Dissolution Agent','Muscle/Ligament/Cartilage Drops 5015'),
('CLENZIDERM DAILY CARE FOAMING CLEANSER ACNE TREATMENT','salicylic acid','LIQUID','SALICYLIC ACID 20 mg/mL','Topique','Obagi Cosmeceuticals LLC','INT','Médicaments topiques','CLENZIDERM DAILY CARE FOAMING CLEANSER ACNE TREATMENT'),
('Dior Forever Skin Wear Flawless Skin True Foundation SPF 20 0W Warm','octisalate, titanium dioxide','EMULSION','OCTISALATE 35 mg/mL','Topique','Parfums Christian Dior','INT','Médicaments topiques','Dior Forever Skin Wear Flawless Skin True Foundation SPF 20 0W Warm'),
('Lynx san a foam','alcohol','LIQUID','ALCOHOL .7 mL/mL','Topique','ABC Compounding Co., Inc.','INT','Médicaments topiques','Lynx san a foam')
) AS v(nom, dci, forme, dosage, voie, labo, pays, classe, nomcom)
WHERE NOT EXISTS (
  SELECT 1 FROM medicaments m WHERE UPPER(m.nom) = UPPER(v.nom)
);
