-- ndc_batch_012.sql (80 rows)
INSERT INTO medicaments (nom, dci, forme, dosage, voie_administration, laboratoire, pays, classe_therapeutique, nom_commercial)
SELECT v.nom, v.dci, v.forme, v.dosage, v.voie, v.labo, v.pays, v.classe, v.nomcom
FROM (VALUES
('FLUOXETINE HCL','fluoxetine hcl','Poudre','FLUOXETINE 1 g/g',NULL,'KALCHEM INTERNATIONAL INC','INT',NULL,NULL),
('PAPAVERINE HYDROCHLORIDE','papaverine hydrochloride','Poudre','PAPAVERINE HYDROCHLORIDE 1 kg/kg',NULL,'PROFESSIONAL COMPOUNDING CENTERS OF AMERICA','INT',NULL,NULL),
('DIANEAL LOW CALCIUM WITH DEXTROSE','sodium chloride, sodium lactate, calcium chloride, magnesium chloride and dextrose','Solution','CALCIUM CHLORIDE 18.3 mg/100mL','INTRAPERITONEAL','Vantive US Healthcare LLC','INT','Blood Coagulation Factor','DIANEAL LOW CALCIUM WITH DEXTROSE'),
('ADSOL Red Cell Preservation Solution System in Plastic Container (PL 146 Plastic)','anticoagulant citrate phosphate dextrose (cpd) solution and adsol preservation solution','Kit',NULL,NULL,'Fenwal, Inc.','US',NULL,'ADSOL Red Cell Preservation Solution System in Plastic Container (PL 146 Plastic)'),
('Manganese Gluconate Dihydrate','manganese gluconate dihydrate','GRANULE','MANGANESE GLUCONATE DIHYDRATE 1 kg/kg',NULL,'Jost Chemical Co.','INT',NULL,NULL),
('Tipiracil Hydrochloride','tipiracil hydrochloride','Poudre','TIPIRACIL HYDROCHLORIDE 1 kg/kg',NULL,'MSN Laboratories Private Limited','INT',NULL,NULL),
('Mirabegron','mirabegron','Poudre','MIRABEGRON 1 kg/kg',NULL,'Dr.Reddy''s Laboratories Limited','INT',NULL,NULL),
('Trabectedin','trabectedin','Poudre','TRABECTEDIN 1 g/g',NULL,'Jiangsu Hengrui Pharmaceuticals Co., Ltd.','INT',NULL,NULL),
('RISPERDAL','risperdal','Poudre','RISPERIDONE 35 kg/35kg',NULL,'NURAY CHEMICALS PRIVATE LIMITED','INT',NULL,NULL),
('Octreotide Acetate','octreotide acetate','Poudre','OCTREOTIDE ACETATE 6 g/6g',NULL,'PolyPeptide Laboratories, Pvt. Ltd.','INT',NULL,NULL),
('Voxelotor','voxelotor','Comprimé','VOXELOTOR 300 mg/1',NULL,'Patheon Inc.','INT',NULL,NULL),
('rHuPH20','rhuph20','Solution injectable','HYALURONIDASE RECOMBINANT HUMAN 10 mg/10mg',NULL,'Avid Bioservices Inc.','INT',NULL,NULL),
('Ibuprofen Arginine','ibuprofen arginine','Poudre','IBUPROFEN ARGININE 1 kg/kg',NULL,'SMS Pharmaceuticals Limited','INT',NULL,NULL),
('Misoprostol','misoprostol','LIQUID','MISOPROSTOL 1 g/g',NULL,'Chirogate International Inc','INT',NULL,NULL),
('Elagolix Sodium','elagolix sodium','Poudre','ELAGOLIX SODIUM 1 kg/kg',NULL,'HETERO LABS LIMITED','INT',NULL,NULL),
('Felypressin','felypressin','Poudre','FELYPRESSIN .2 g/.2g',NULL,'PolyPeptide Laboratories (Sweden) AB','INT',NULL,NULL),
('Anidulafungin','anidulafungin','Poudre','ANIDULAFUNGIN 1 kg/kg',NULL,'BrightGene Bio-Medical Technology Co., Ltd.','INT',NULL,NULL),
('Cyclosporine A','cyclosporine a','Poudre','CYCLOSPORINE 1 g/g',NULL,'LETCO MEDICAL, LLC','INT',NULL,NULL),
('Etonogestrel','etonogestrel','Poudre','ETONOGESTREL 1 kg/kg',NULL,'Industriale Chimica s.r.l.','INT',NULL,NULL),
('Carmex Daily Care Moisturizing Lip Balm Favorites SPF 15','octinoxate, oxybenzone','Kit',NULL,NULL,'Carma Laboratories, Inc.','INT',NULL,'Carmex Daily Care Moisturizing Lip Balm Favorites SPF 15'),
('Carmex Variety Pack Daily Care Sticks Moisturizing Lip Balm SPF 15','octinoxate, oxybenzone','Kit',NULL,NULL,'Carma Laboratories, Inc.','INT',NULL,'Carmex Variety Pack Daily Care Sticks Moisturizing Lip Balm SPF 15'),
('Hero Cosmetics Pimple Correct Salicylic Acid Acne Treatment','salicylic acid','Gel','SALICYLIC ACID 20 mg/mL','Topique','Church & Dwight Co., Inc.','INT','Médicaments topiques','Hero Cosmetics Pimple Correct Salicylic Acid Acne Treatment'),
('Irinotecan Hydrochloride','irinotecan hydrochloride','Poudre','IRINOTECAN HYDROCHLORIDE 1 kg/kg',NULL,'ScinoPharm Taiwan Ltd.','INT',NULL,NULL),
('Apixaban','apixaban','Poudre','APIXABAN 1 kg/kg',NULL,'Jubilant Biosys limited','INT',NULL,NULL),
('Posaconazole','posaconazole','Poudre','POSACONAZOLE 1 kg/kg',NULL,'Biocon Limited','INT',NULL,NULL),
('Ondansetron Hydrochloride','ondansetron hydrochloride','Comprimé','ONDANSETRON HYDROCHLORIDE 4 mg/1',NULL,'Aurobindo Pharma Limited','INT',NULL,NULL),
('Fosinopril Sodium','fosinopril sodium','Poudre','FOSINOPRIL SODIUM 1 kg/kg',NULL,'Hetero Drugs Limited','INT',NULL,NULL),
('telmisartan','telmisartan','Poudre','TELMISARTAN 1 kg/kg',NULL,'Alivus Life Sciences Limited','INT',NULL,NULL),
('TB 500 Fragment','tb 500 fragment','Poudre','TB-500 100 g/100g',NULL,'Bills Biotech Pvt. Ltd.','INT',NULL,NULL),
('Semaglutide','semaglutide','Poudre','SEMAGLUTIDE 100 g/100g',NULL,'Harbin Jixianglong Biotech Co., Ltd.','INT',NULL,NULL),
('KPV acetate','kpv acetate','Poudre','PEPTIDE B27PD 100 g/100g',NULL,'Hangzhou Yiqi Biotechnology Co., Ltd','INT',NULL,NULL),
('Edoxaban Tosylate (Monohydrate)','edoxaban tosylate (monohydrate)','Poudre','EDOXABAN TOSYLATE MONOHYDRATE 1 kg/kg',NULL,'MSN Life Sciences Private Limited','INT',NULL,NULL),
('Pimavanserin Tartrate','pimavanserin tartrate','Poudre','PIMAVANSERIN TARTRATE 1 kg/kg',NULL,'Dasami Lab Private Limited','INT',NULL,NULL),
('Rifampin','rifampin','Poudre','RIFAMPIN 5000 g/5000g',NULL,'DARMERICA, LLC','INT',NULL,NULL),
('CYCLOBENZAPRINE HYDROCHLORIDE','cyclobenzaprine hydrochloride','Poudre','CYCLOBENZAPRINE HYDROCHLORIDE 1 kg/kg',NULL,'R.L.Fine Chem Private Limited','INT',NULL,NULL),
('Methyl Salicylate','methyl salicylate','LIQUID','METHYL SALICYLATE 1 kg/kg',NULL,'Ganzhou Maoyuan Pharmaceutical Co., Ltd.','INT',NULL,NULL),
('up and up childrens allergy melts','diphenhydramine hcl','Comprimé','DIPHENHYDRAMINE HYDROCHLORIDE 12.5 mg/1','Orale','Target Corporation','INT','Histamine-1 Receptor Antagonist','up and up childrens allergy melts'),
('Docusate Sodium 50 mg and Sennosides 8.6 mg','docusate sodium 50 mg and sennosides 8.6 mg','Gélule','DOCUSATE SODIUM 50 mg/1',NULL,'Pioneer Life Sciences, LLC','INT',NULL,NULL),
('Guaifenesin','guaifenesin','Poudre','GUAIFENESIN 1 kg/kg',NULL,'Zen Chemicals Private Limited','INT',NULL,NULL),
('FELBAMATE','felbamate','Poudre','FELBAMATE 1 kg/kg',NULL,'AKTINOS PHARMA PRIVATE LIMITED','INT',NULL,NULL),
('Titanium Dioxide','titanium dioxide','LIQUID','TITANIUM DIOXIDE 10 kg/20kg',NULL,'Kowon International Korea Co.ltd','INT',NULL,NULL),
('OCTOCRYLENE','octocrylene','LIQUID','OCTOCRYLENE 1 kg/kg',NULL,'SALICYLATES & CHEMICALS PRIVATE LIMITED','INT',NULL,NULL),
('Refenesen Mucus Relief','guaifenesin','Comprimé','GUAIFENESIN 400 mg/1','Orale','Reese Pharmaceutical Co','INT','Expectorant','Refenesen Mucus Relief'),
('Revlon Kiss Balm SPF 20','avobenzone, benzophenone-3, octinoxate','STICK','AVOBENZONE 2 g/mL','Topique','Revlon Consumer Products Corp','INT','Médicaments topiques','Revlon Kiss Balm SPF 20'),
('Mitchum Clinical Soft Solid Pure Fresh','aluminum zirconium tetrachlorohydrex gly 20.0%','STICK','ALUMINUM ZIRCONIUM TETRACHLOROHYDREX GLY .2 g/g','Topique','Revlon Consumer Products Corp.','INT','Médicaments topiques','Mitchum Clinical Soft Solid Pure Fresh'),
('Acetaminophen 325 mg, Diphenhydramine HCL 12.5 mg, Phenylephrine HCl 5 mg','acetaminophen 325 mg, diphenhydramine hcl 12.5 mg, phenylephrine hcl 5 mg','Comprimé','ACETAMINOPHEN 325 mg/1',NULL,'Shield Pharmaceuticals Corp','INT',NULL,NULL),
('choriogonadotropin alfa','choriogonadotropin alfa','Solution','CHORIOGONADOTROPIN ALFA 10000 [USP''U]/10mL',NULL,'Bamboo US Bidco LCC','INT',NULL,NULL),
('Extra Strength Antacid Calcium Carbonate,750 mg','calcium carbonate','Comprimé','CALCIUM CARBONATE 750 mg/1','Orale','TARGET CORPORATION','INT','Blood Coagulation Factor','Extra Strength Antacid Calcium Carbonate,750 mg'),
('Rite Aid Mineral Zinc Oxide Sunscreen Broad Spectrum SPF 50','zinc oxide','STICK','ZINC OXIDE 216 mg/g','Topique','Rite Aid','INT','Médicaments topiques','Rite Aid Mineral Zinc Oxide Sunscreen Broad Spectrum SPF 50'),
('sleep aid','doxylamine succinate','Comprimé','DOXYLAMINE SUCCINATE 25 mg/1','Orale','Rite Aid Corporation','US','Antihistamine','sleep aid'),
('Arranon','nelarabine','Solution injectable','NELARABINE 5 mg/mL','Intraveineuse','Novartis Pharmaceuticals Corporation','US','Nucleoside Metabolic Inhibitor','Arranon'),
('GUNA STOMACH PLUS','antimonium crudum - argentum nitricum - arsenicum album - ipecacuanha - nux vomica - origanum majorana - cuprum metallicum - taraxacum officinale - natrum phosphoricum -','PELLET','ANTIMONY TRISULFIDE 6 [hp_X]/4g','Orale','Guna spa','INT','Copper-containing Intrauterine Device','GUNA STOMACH PLUS'),
('Potassium Chloride Extended-release','potassium chloride extended-release','Comprimé','POTASSIUM CHLORIDE 1500 mg/1','Orale','Atlantic Biologicals Corp.','US','Osmotic Laxative','Potassium Chloride Extended-release'),
('TOBREX','tobramycin','Pommade','TOBRAMYCIN 3 mg/g','Ophtalmique','Novartis Pharmaceuticals Corporation','US','Aminoglycoside Antibacterial','TOBREX'),
('LEQVIO','inclisiran','Solution','INCLISIRAN SODIUM 284 mg/1.5mL','Sous-cutanée','Novartis Pharmaceuticals Corporation','US',NULL,'LEQVIO'),
('SPOTLESS Acne Clearing Treatment','benzoyl peroxide','Lotion','BENZOYL PEROXIDE .025 g/mL','Topique','Rodan & Fields','INT','Médicaments topiques','SPOTLESS Acne Clearing Treatment'),
('CIMICIFUGA RACEMOSA','cimicifuga racemosa','PELLET','BLACK COHOSH 1 [hp_X]/1','Orale','Rxhomeo Private Limited d.b.a. Rxhomeo, Inc','INT',NULL,'CIMICIFUGA RACEMOSA'),
('Zoledronic acid','zoledronic acid','Solution injectable','ZOLEDRONIC ACID 4 mg/5mL','Intraveineuse','Accord Healthcare Inc.','US','Bisphosphonate','Zoledronic acid'),
('Tazorac','tazarotene','Gel','TAZAROTENE 1 mg/g','CUTANEOUS','Almirall, LLC','US','Retinoid','Tazorac'),
('MUCUS RELIEF MAX','guaifenesin','Comprimé','GUAIFENESIN 1200 mg/1','Orale','Better Living Brands, LLC','US','Expectorant','MUCUS RELIEF MAX'),
('K-O-T Standardized Grass Pollen Mix','poa pratensis, dactylis glomerata and phleum pratense','Solution','DACTYLIS GLOMERATA POLLEN 3333.333 [BAU]/mL','INTRADERMAL','Greer Laboratories, Inc.','US','Standardized Pollen Allergenic Extract','K-O-T Standardized Grass Pollen Mix'),
('Wax Myrtle Pollen','morella cerifera','Solution','MORELLA CERIFERA POLLEN .1 g/mL','INTRADERMAL','Greer Laboratories, Inc.','US','Non-Standardized Pollen Allergenic Extract','Wax Myrtle Pollen'),
('Southern Ragweed','ambrosia bidentata','Solution','AMBROSIA BIDENTATA POLLEN .05 g/mL','INTRADERMAL','Greer Laboratories, Inc.','US','Non-Standardized Pollen Allergenic Extract','Southern Ragweed'),
('California Black Walnut Pollen','juglans californica','Solution','JUGLANS CALIFORNICA POLLEN 40000 [PNU]/mL','INTRADERMAL','Greer Laboratories, Inc.','US','Non-Standardized Pollen Allergenic Extract','California Black Walnut Pollen'),
('White Oak Pollen','quercus alba','Solution','QUERCUS ALBA POLLEN .05 g/mL','INTRADERMAL','Greer Laboratories, Inc.','US','Non-Standardized Pollen Allergenic Extract','White Oak Pollen'),
('Signature Care Athletes Foot','miconazole nitrate','Spray','MICONAZOLE NITRATE 20 mg/g','Topique','Formulated Solutions, LLC','INT','Azole Antifungal','Signature Care Athletes Foot'),
('Good Neighbor Pharmacy Aspirin','aspirin','Comprimé','ASPIRIN 81 mg/1','Orale','Amerisource Bergen','INT','Nonsteroidal Anti-inflammatory Drug','Good Neighbor Pharmacy Aspirin'),
('terrasil First Aid Antiseptic Wound and Burn Care','hexylresorcinol','Pommade','HEXYLRESORCINOL .1 g/100g','Topique','Aidance Scientific, Inc, DBA Aidance Skincare & Topical Solutions','INT','Médicaments topiques','terrasil First Aid Antiseptic Wound and Burn Care'),
('good sense nasal','oxymetazoline hcl','Spray','OXYMETAZOLINE HYDROCHLORIDE .05 g/100mL','Nasale','L. Perrigo Company','INT','Vasoconstrictor','good sense nasal'),
('good sense nicotine','nicotine polacrilex','GUM, CHEWING','NICOTINE 2 mg/1','Orale','L. Perrigo Company','US','Cholinergic Nicotinic Agonist','good sense nicotine'),
('anti diarrheal','loperamide hcl','Comprimé','LOPERAMIDE HYDROCHLORIDE 2 mg/1','Orale','L. Perrigo Company','US','Opioid Agonist','anti diarrheal'),
('good sense sleep aid ultra','doxylamine succinate','Comprimé','DOXYLAMINE SUCCINATE 25 mg/1','Orale','L. Perrigo Company','US','Antihistamine','good sense sleep aid ultra'),
('Dimethyl Fumarate','dimethyl fumarate','Gélule','DIMETHYL FUMARATE 120 mg/1','Orale','Macleods Pharmaceuticals Limited','US',NULL,'Dimethyl Fumarate'),
('Speed Stick Power Fresh','aluminum zirconium tetrachlorohydrex gly','STICK','ALUMINUM ZIRCONIUM TETRACHLOROHYDREX GLY 159 mg/g','Topique','COLGATE PALMOLIVE COMPANY','INT','Médicaments topiques','Speed Stick Power Fresh'),
('Oil Free Acne Wash','salicylic acid 2%','Lotion','SALICYLIC ACID 20.6 mg/mL','Topique','Topco Associates LLC','INT','Médicaments topiques','Oil Free Acne Wash'),
('Kali Phosphoricum','kali phosphoricum','PELLET','DIBASIC POTASSIUM PHOSPHATE 6 [hp_C]/1','Orale','Hahnemann Laboratories, INC.','INT','Osmotic Laxative','Kali Phosphoricum'),
('Sensodyne Pronamel Strong and Bright Enamel Extra Fresh','potassium nitrate and sodium fluoride','PASTE','POTASSIUM NITRATE 50 mg/g','Orale','Haleon US Holdings LLC','INT',NULL,'Sensodyne Pronamel Strong and Bright Enamel Extra Fresh'),
('STERILE DILUENT','sterile water','Solution injectable','WATER .7 mL/.7mL','Intramusculaire','Merck Sharp & Dohme LLC','US',NULL,'STERILE DILUENT'),
('Sensodyne Pronamel Clinical Enamel Strength Whitening Action','potassium nitrate, sodium fluoride','PASTE','POTASSIUM NITRATE 50 mg/g','Orale','Haleon US Holdings LLC','INT',NULL,'Sensodyne Pronamel Clinical Enamel Strength Whitening Action'),
('Silicium Metallicum','silicium metallicum','PELLET','SILICON 6 [hp_C]/1','Orale','Hahnemann Laboratories, INC.','INT',NULL,'Silicium Metallicum')
) AS v(nom, dci, forme, dosage, voie, labo, pays, classe, nomcom)
WHERE NOT EXISTS (
  SELECT 1 FROM medicaments m WHERE UPPER(m.nom) = UPPER(v.nom)
);
