-- ndc_batch_002.sql (80 rows)
INSERT INTO medicaments (nom, dci, forme, dosage, voie_administration, laboratoire, pays, classe_therapeutique, nom_commercial)
SELECT v.nom, v.dci, v.forme, v.dosage, v.voie, v.labo, v.pays, v.classe, v.nomcom
FROM (VALUES
('Salcaprozate Sodium','salcaprozate sodium','Poudre','SALCAPROZATE SODIUM 10 kg/10kg',NULL,'Micro Labs Limited','INT',NULL,NULL),
('ATROPINE SULFATE','atropine sulfate','Poudre','ATROPINE SULFATE 1 kg/kg',NULL,'SCL Lifesciences Limited','INT',NULL,NULL),
('Coccidioides Posadasii DNA','coccidioides posadasii dna','LIQUID','COCCIDIOIDES POSADASII DNA 60 [hp_X]/mL',NULL,'Deseret Biologicals, Inc.','INT',NULL,NULL),
('Promethazine Hydrochloride','promethazine hydrochloride','Poudre','PROMETHAZINE HYDROCHLORIDE 1 kg/kg',NULL,'Egis Pharmaceuticals PLC','INT',NULL,NULL),
('Bartonella Bacilliformis DNA, Bartonella Clarridgeiae, Bartonella Clarridgeiae DNA, Bartonella Elizabethae, Bartonella Henselae, Bartonella Henselae DNA, Bartonella Quintana, Bartonella Quintana DNA, Bartonella Vinsonii, Bartonella Vinsonii DNA, Bartonella Washoensis, Bartonella Washoensis DNA, Bartonella Elizabethae DNA','bartonella bacilliformis dna, bartonella clarridgeiae, bartonella clarridgeiae dna, bartonella elizabethae, bartonella henselae, bartonella henselae dna, bartonella quintana, bartonella quintana dna, bartonella vinsonii, bartonella vinsonii dna, bartonella washoensis, bartonella washoensis dna, bartonella elizabethae dna','LIQUID','BARTONELLA BACILLIFORMIS DNA 60 [hp_X]/mL',NULL,'Deseret Biologicals, Inc.','INT',NULL,NULL),
('Bacitracin','bacitracin','Poudre','BACITRACIN 1 kg/kg',NULL,'Xellia (Taizhou) Pharmaceuticals Co., Ltd','INT',NULL,NULL),
('IS5MN 70% Lactose 200 30%','is5mn 70% lactose 200 30%','Poudre','ISOSORBIDE MONONITRATE 1 kg/kg',NULL,'Dipharma Francis Srl','INT',NULL,NULL),
('TENOFOVIR DISOPROXIL FUMARATE','tenofovir disoproxil fumarate','Comprimé','TENOFOVIR DISOPROXIL FUMARATE 300 mg/1',NULL,'Takeda GmbH','INT',NULL,NULL),
('Guaifenesin and Pseudoephedrine HCl','guaifenesin and pseudoephedrine hcl','Comprimé','GUAIFENESIN 1200 mg/1',NULL,'Aurobindo Pharma Limited','INT',NULL,NULL),
('Potassium Chloride','potassium chloride','Poudre','POTASSIUM CHLORIDE .87 kg/kg',NULL,'Adare Pharmaceuticals Inc','INT',NULL,NULL),
('FLUCONAZOLE','fluconazole','Poudre','FLUCONAZOLE 1 g/g',NULL,'Kalchem International inc','INT',NULL,NULL),
('Dexchlorpheniramine Maleate','dexchlorpheniramine maleate','Poudre','DEXCHLORPHENIRAMINE MALEATE 1 kg/kg',NULL,'Supriya Lifescience Limited','INT',NULL,NULL),
('Menthol','menthol','Pastille','MENTHOL, UNSPECIFIED FORM 7 mg/1',NULL,'Pharmaloz Manufacturing Inc','INT',NULL,NULL),
('Buprenorphine','buprenorphine','Poudre','BUPRENORPHINE 1 kg/kg',NULL,'Noramco, LLC','INT',NULL,NULL),
('METHYLCOBALAMIN','methylcobalamin','Poudre','METHYLCOBALAMIN 1 kg/kg',NULL,'Professional Compounding Centers of America','INT',NULL,NULL),
('ACETAZOLAMIDE','acetazolamide','Poudre','ACETAZOLAMIDE 1 kg/kg',NULL,'Professional Compounding Centers of America dba PCCA','INT',NULL,NULL),
('Halobetasol Propionate','halobetasol propionate','Poudre','HALOBETASOL PROPIONATE 1 kg/kg',NULL,'Symbiotica Speciality Ingredients Sdn. Bhd.','INT',NULL,NULL),
('ALCOHOL','alcohol','Spray','ALCOHOL 62 mL/100mL',NULL,'Scribe Opco, Inc.','INT',NULL,NULL),
('Cetirizine Hydrochloride','cetirizine hydrochloride','Poudre','CETIRIZINE HYDROCHLORIDE 25 kg/25kg',NULL,'Cipla Ltd.','INT',NULL,NULL),
('Magnesium Sulfate Heptahydrate','magnesium sulfate heptahydrate','GRANULE','MAGNESIUM SULFATE HEPTAHYDRATE 1 kg/kg',NULL,'Jost Chemical Co.','INT',NULL,NULL),
('LEDERLE LEUCOVORIN','calcium folinate','Comprimé','LEUCOVORIN CALCIUM 5 mg/1','Orale','Pfizer Laboratories Div Pfizer Inc','INT','Folate Analog','LEDERLE LEUCOVORIN'),
('Zolpidem Tartrate','zolpidem tartrate','Comprimé','ZOLPIDEM TARTRATE 12.5 mg/1','Orale','Sanofi-Aventis U.S. LLC','US','gamma-Aminobutyric Acid A Receptor Positive Modulator','Zolpidem Tartrate'),
('VALSARTAN','valsartan','Poudre','VALSARTAN 1 kg/kg',NULL,'Ipca Laboratories Limited','INT',NULL,NULL),
('Ivabradine Monosulfate','ivabradine monosulfate','Poudre','IVABRADINE SULFATE 2.5 kg/2.5kg',NULL,'Jiangsu Hengrui Pharmaceuticals Co., Ltd.','INT',NULL,NULL),
('Selexipag','selexipag','Poudre','SELEXIPAG 35 kg/35kg',NULL,'NURAY CHEMICALS PRIVATE LIMITED','INT',NULL,NULL),
('Theophylline','theophylline','Poudre','THEOPHYLLINE 1 kg/kg',NULL,'Shandong Xinhua Pharmaceutical Company Limited','INT',NULL,NULL),
('Exenatide','exenatide','Poudre','EXENATIDE 250 g/250g',NULL,'PolyPeptide Laboratories Private Limited','INT',NULL,NULL),
('Maraviroc','maraviroc','Poudre','MARAVIROC 1 kg/kg',NULL,'Honour Lab Limited','INT',NULL,NULL),
('DEXTROMETHORPHAN HYDROBROMIDE and BUPROPION HYDROCHLORIDE','dextromethorphan hydrobromide and bupropion hydrochloride','Comprimé','BUPROPION HYDROCHLORIDE 105 mg/1',NULL,'Patheon Inc.','INT',NULL,NULL),
('Calcium Carbonate','calcium carbonate','Poudre','CALCIUM CARBONATE 1 kg/kg',NULL,'Omya Inc.','INT',NULL,NULL),
('Fenoprofen Calcium','fenoprofen calcium','Poudre','FENOPROFEN CALCIUM 1 kg/kg',NULL,'SMS Pharmaceuticals Limited','INT',NULL,NULL),
('terlipressin','terlipressin','Solution','TERLIPRESSIN .85 mg/5mL',NULL,'Patheon Italia S.p.A.','INT',NULL,NULL),
('Naproxen Sodium','naproxen sodium','Poudre','NAPROXEN SODIUM 1 kg/kg',NULL,'Hetero Labs Limited','INT',NULL,NULL),
('DEGARELIX','degarelix','Poudre','DEGARELIX 1 g/g',NULL,'PolyPeptide Laboratories (Sweden) AB','INT',NULL,NULL),
('Micafungin Sodium','micafungin sodium','Poudre','MICAFUNGIN SODIUM 1 kg/kg',NULL,'BrightGene Bio-Medical Technology Co., Ltd.','INT',NULL,NULL),
('Bendamustine hydrochloride','bendamustine hydrochloride','Poudre','BENDAMUSTINE HYDROCHLORIDE 1 kg/kg',NULL,'SUN PHARMACEUTICAL INDUSTRIES, INC.','INT',NULL,NULL),
('Apomorphine Hydrochloride','apomorphine hydrochloride','Poudre','APOMORPHINE HYDROCHLORIDE 1 g/g',NULL,'LETCO MEDICAL, LLC','INT',NULL,NULL),
('Drospirenone','drospirenone','Poudre','DROSPIRENONE 1 kg/kg',NULL,'Industriale Chimica s.r.l.','INT',NULL,NULL),
('Levofloxacin','levofloxacin','Poudre','LEVOFLOXACIN 100 kg/100kg',NULL,'Assia Chemical Industries Ltd - Teva Tech Site','INT',NULL,NULL),
('Ambrisentan','ambrisentan','Poudre','AMBRISENTAN 1 kg/kg',NULL,'Zhejiang Huahai Pharmaceutical Co., Ltd.','INT',NULL,NULL),
('Rhododendron Campylocarpum Whole','rhododendron campylocarpum whole','LIQUID','RHODODENDRON CAMPYLOCARPUM WHOLE 1 [hp_X]/mL',NULL,'Herbamed AG','INT',NULL,NULL),
('NORGESTREL','norgestrel','Poudre','NORGESTREL 1 kg/kg',NULL,'STERLING SPA','INT',NULL,NULL),
('TOPIRAMATE','topiramate','Poudre','TOPIRAMATE 1 kg/kg',NULL,'ScinoPharm Taiwan Ltd.','INT',NULL,NULL),
('Rinvoq','upadacitinib','Comprimé','UPADACITINIB 45 mg/1','Orale','AbbVie Inc.','US','Janus Kinase Inhibitor','Rinvoq'),
('Orajel Paw Patrol','sodium fluoride','PASTE, DENTIFRICE','SODIUM FLUORIDE 1.5 mg/g','DENTAL','Church & Dwight Co., Inc.','INT',NULL,'Orajel Paw Patrol'),
('Orajel Gabbys Dollhouse','sodium fluoride','PASTE, DENTIFRICE','SODIUM FLUORIDE 2.4 mg/g','Orale','Church & Dwight Co., Inc.','INT',NULL,'Orajel Gabbys Dollhouse'),
('Valsartan and Hydrochlorothiazide','valsartan and hydrochlorothiazide','Comprimé','HYDROCHLOROTHIAZIDE 12.5 mg/1',NULL,'Aurobindo Pharma Limited','INT',NULL,NULL),
('Lactulose','lactulose','LIQUID','LACTULOSE 1 kg/kg',NULL,'Lacsa Pty Ltd.','INT',NULL,NULL),
('saxagliptin monohydrate','saxagliptin monohydrate','Poudre','SAXAGLIPTIN 1 kg/kg',NULL,'Alivus Life Sciences Limited','INT',NULL,NULL),
('Semax Acetate','semax acetate','Poudre','SEMAX 100 g/100g',NULL,'Bills Biotech Pvt. Ltd.','INT',NULL,NULL),
('InstantFoam Complete PURE','alcohol','LIQUID','ALCOHOL 80 g/100mL','Topique','SC Johnson Professional USA Inc.','INT','Médicaments topiques','InstantFoam Complete PURE'),
('Castor Oil','castor oil','LIQUID','CASTOR OIL 1 g/mL','Orale','Nice-Pak Products, LLC','INT',NULL,'Castor Oil'),
('Sacubitril and Valsartan','sacubitril and valsartan','Poudre','SACUBITRIL VALSARTAN SODIUM HYDRATE 1 kg/kg',NULL,'MSN Life Sciences Private Limited','INT',NULL,NULL),
('Zinc Oxide','zinc oxide','Poudre','ZINC OXIDE 1 kg/kg',NULL,'Advanced Dispersed Particles SL.','INT',NULL,NULL),
('Trientine Hydrochloride','trientine hydrochloride','Poudre','TRIENTINE HYDROCHLORIDE 1 kg/kg',NULL,'Dasami Lab Private Limited','INT',NULL,NULL),
('Dantrolene Sodium','dantrolene sodium','Poudre','DANTROLENE SODIUM 500 g/500g',NULL,'Darmerica, LLC','INT',NULL,NULL),
('Pyrimethamine','pyrimethamine','Poudre','PYRIMETHAMINE 1 kg/kg',NULL,'R.L.Fine Chem Private Limited','INT',NULL,NULL),
('SERMORELIN ACETATE','sermorelin acetate','Poudre','SERMORELIN 100 g/100g',NULL,'SCH PHARMA PRIVATE LIMITED','INT',NULL,NULL),
('First Aid Antiseptic','povidone-iodine','Solution','POVIDONE-IODINE 10 mg/mL','Topique','Target Corporation','INT','Médicaments topiques','First Aid Antiseptic'),
('Diphenhydramine HCl 25 mg','diphenhydramine hcl 25 mg','Gélule','DIPHENHYDRAMINE HYDROCHLORIDE 25 mg/1',NULL,'Pioneer Life Sciences, LLC','INT',NULL,NULL),
('Clotrimazole','clotrimazole','Poudre','CLOTRIMAZOLE 1 kg/kg',NULL,'Zen Chemicals Private Limited','INT',NULL,NULL),
('Anastrozole','anastrozole','Poudre','ANASTROZOLE 1 g/g',NULL,'Qingdao Biopeptek Co., Ltd.','INT',NULL,NULL),
('SODIUM SALICYLATE','sodium salicylate','Poudre','SODIUM SALICYLATE 1 kg/kg',NULL,'SALICYLATES & CHEMICALS PRIVATE LIMITED','INT',NULL,NULL),
('Deferiprone Milled','deferiprone milled','Poudre','DEFERIPRONE 1 kg/kg',NULL,'Chemo Biosynthesis Srl','INT',NULL,NULL),
('ENCORAFENIB','encorafenib','Poudre','ENCORAFENIB 1 kg/kg',NULL,'VALARY LAB PRIVATE LIMITED','INT',NULL,NULL),
('Baclofen','baclofen','Poudre','BACLOFEN 1 kg/kg',NULL,'Pharma Source Direct, Inc.','INT',NULL,NULL),
('Acetaminophen 500 mg, Caffeine 60 mg, Pyrilamine maleate 15 mg','acetaminophen 500 mg, caffeine 60 mg, pyrilamine maleate 15 mg','Comprimé','ACETAMINOPHEN 500 mg/1',NULL,'Shield Pharmaceuticals Corp','INT',NULL,NULL),
('Helium, Oxygen','helium, oxygen','GAS','HELIUM 600 mL/L','Inhalation','AIRGAS USA, LLC','US',NULL,'Helium, Oxygen'),
('Up and Up Esomeprazole Magnesium','esomeprazole magnesium','Gélule','ESOMEPRAZOLE MAGNESIUM DIHYDRATE 20 mg/1','Orale','Target Corporation','US','Proton Pump Inhibitor','Up and Up Esomeprazole Magnesium'),
('Rite Aid Mineral Sunscreen Broad Spectrum SPF 50','titanium dioxide, zinc oxide','Lotion','TITANIUM DIOXIDE 30 mg/mL','Topique','Rite Aid','INT','Médicaments topiques','Rite Aid Mineral Sunscreen Broad Spectrum SPF 50'),
('Stomach Relief Regular Strength','bismuth subsalicylate','LIQUID','BISMUTH SUBSALICYLATE 525 mg/30mL','Orale','Rite Aid Corporation','INT','Bismuth','Stomach Relief Regular Strength'),
('White Rose Petroleum Jelly','petrolatum','Pommade','PETROLATUM 1000 mg/g','Topique','J. Strickland & Co.','INT','Médicaments topiques','White Rose Petroleum Jelly'),
('GUNA DIGESTION PLUS','pork liver - lycopodium clavatum spore - strychnos nux vomica seed - sus scrofa pancreas - aethusa cynapium -','Solution','AETHUSA CYNAPIUM 3 [hp_X]/30mL','Orale','Guna spa','INT','Non-Standardized Plant Allergenic Extract','GUNA DIGESTION PLUS'),
('OneLAX SENNA','senna','Sirop','SENNOSIDES A AND B 417.12 mg/237mL','Orale','ATLANTIC BIOLOGICALS CORP.','INT',NULL,'OneLAX SENNA'),
('LAMOTRIGINE','lamotrigine','Comprimé','LAMOTRIGINE 25 mg/1','Orale','Torrent Pharmaceuticals Limited','US','Anti-epileptic Agent','LAMOTRIGINE'),
('NARS PURE RADIANT TINTED MOISTURIZER Finland','octinoxate, titanium dioxide','Crème','OCTINOXATE 4.044 g/50mL','Topique','NARS Cosmetics','INT','Médicaments topiques','NARS PURE RADIANT TINTED MOISTURIZER Finland'),
('SPOTLESS Daily Acne Wash','benzoyl peroxide','Crème','BENZOYL PEROXIDE .05 g/mL','Topique','Rodan & Fields','INT','Médicaments topiques','SPOTLESS Daily Acne Wash'),
('Cobenfy','xanomeline and trospium chloride','Gélule','TROSPIUM CHLORIDE 30 mg/1','Orale','E.R. Squibb & Sons, L.L.C.','US','Cholinergic Muscarinic Agonist','Cobenfy'),
('ropinirole','ropinirole','Comprimé','ROPINIROLE HYDROCHLORIDE 5 mg/1','Orale','Accord Healthcare Inc.','US','Nonergot Dopamine Agonist','ropinirole'),
('Atenolol','atenolol','Comprimé','ATENOLOL 50 mg/1','Orale','Teva Pharmaceuticals USA, Inc.','US','beta-Adrenergic Blocker','Atenolol')
) AS v(nom, dci, forme, dosage, voie, labo, pays, classe, nomcom)
WHERE NOT EXISTS (
  SELECT 1 FROM medicaments m WHERE UPPER(m.nom) = UPPER(v.nom)
);
