-- ndc_batch_094.sql (80 rows)
INSERT INTO medicaments (nom, dci, forme, dosage, voie_administration, laboratoire, pays, classe_therapeutique, nom_commercial)
SELECT v.nom, v.dci, v.forme, v.dosage, v.voie, v.labo, v.pays, v.classe, v.nomcom
FROM (VALUES
('CENTER-AL - MORUS RUBRA POLLEN','morus rubra pollen','Suspension','MORUS RUBRA POLLEN 10000 [PNU]/mL','Sous-cutanée','ALK-Abello, Inc.','US','Non-Standardized Pollen Allergenic Extract','CENTER-AL - MORUS RUBRA POLLEN'),
('Lynx Antibacterial','chloroxylenol','SOAP','CHLOROXYLENOL 3 mg/mL','Topique','ABC Compounding Co., Inc.','INT','Médicaments topiques','Lynx Antibacterial'),
('MOSQUITO','culix pipiens','Solution','CULEX PIPIENS .01 g/mL','PERCUTANEOUS','ALK-Abello, Inc.','US',NULL,'MOSQUITO'),
('Purified Cortrophin Gel','repository corticotropin','Solution injectable','CORTICOTROPIN 80 [USP''U]/mL','Intramusculaire','ANI Pharmaceuticals, Inc.','US','Adrenocorticotropic Hormone','Purified Cortrophin Gel'),
('Antiperspirant Deodorant Lavender','aluminum zirconium trichlorohydrex gly','STICK','ALUMINUM ZIRCONIUM TRICHLOROHYDREX GLY 16 g/100g','Topique','Bath and Body Works, Distr.','INT','Médicaments topiques','Antiperspirant Deodorant Lavender'),
('Galantamine Hydrobromide','galantamine hydrobromide','Gélule','GALANTAMINE HYDROBROMIDE 24 mg/1','Orale','Bryant Ranch Prepack','US','Cholinesterase Inhibitor','Galantamine Hydrobromide'),
('Tapeworm Nosode Combination 9403','tapeworm nosode combination','LIQUID','ARSENIC TRIOXIDE 6 [hp_X]/29.5mL','Orale','Professional Complementary Health Formulas','INT',NULL,'Tapeworm Nosode Combination 9403'),
('R08 LYMPHATICS','adenosine triphosphate, ammonium muriaticum, baptisia tinctoria, colchicum autumnale, juniperus communis, levothyroxine, podophyllinum, rhus toxicodendron','Solution','ADENOSINE TRIPHOSPHATE 5 [hp_X]/mL','Sublinguale','Apex Energetics Inc.','INT','Non-Standardized Food Allergenic Extract','R08 LYMPHATICS'),
('Midazolam In Sodium Chloride','midazolam in sodium chloride','Solution','MIDAZOLAM HYDROCHLORIDE 1 mg/mL','Intraveineuse','FRESENIUS KABI USA, LLC','US','Benzodiazepine','Midazolam In Sodium Chloride'),
('STOPAIN CLINICAL Migraine and Headache','menthol, unspecified form, atropa belladonna, iris versicolor root, sanguinaria canadensis root','Gel','ATROPA BELLADONNA 3 [hp_X]/g','Topique','Troy Manufacturing, Inc.','INT','Médicaments topiques','STOPAIN CLINICAL Migraine and Headache'),
('Alka-Seltzer Plus Maximum Strength Day Cold and Flu','acetaminophen, dextromethorphan hydrobromide, phenylephrine hydrochloride','Gélule','ACETAMINOPHEN 325 mg/1','Orale','Bayer HealthCare LLC.','INT','Sigma-1 Agonist','Alka-Seltzer Plus Maximum Strength Day Cold and Flu'),
('Zeyco Antiseptic Hand Sanitizer Gel','alcohol','Gel','ALCOHOL .7 mL/mL','Topique','Laboratorios Zeyco, S.A. de C.V.','INT','Médicaments topiques','Zeyco Antiseptic Hand Sanitizer Gel'),
('HurriCaine Topical Anesthetic','benzocaine','Gel','BENZOCAINE 200 mg/g','DENTAL','Beutlich Pharmaceuticals, LLC','INT','Standardized Chemical Allergen','HurriCaine Topical Anesthetic'),
('Lung-Resp','cough relief','LIQUID','ARSENIC TRIOXIDE 15 [hp_X]/mL','Orale','Vitality Works, Inc','INT',NULL,'Lung-Resp'),
('Chavita 6','cerebrum, plumb met, staphysagria, viscum album','LIQUID','DELPHINIUM STAPHISAGRIA SEED 50 [hp_C]/60mL','Orale','RUBIMED AG','INT',NULL,'Chavita 6'),
('Pepcid Complete, TRAVEL BASIX','famotidine, calcium carbonate, magnesium hydroxide chewable tablet','Comprimé','CALCIUM CARBONATE 800 mg/1','Orale','Lil'' Drug Store Products, Inc.','US','Histamine-2 Receptor Antagonist','Pepcid Complete, TRAVEL BASIX'),
('CYSTEINE HYDROCHLORIDE','cysteine hydrochloride','Solution injectable','CYSTEINE HYDROCHLORIDE 34.5 mg/mL','Intraveineuse','Baxter Healthcare Corporation','US','Médicaments IV / Hospitaliers','CYSTEINE HYDROCHLORIDE'),
('Glucose and Sodium Chloride','dextrose anhydrous and sodium chloride','Solution','DEXTROSE MONOHYDRATE 5.5 g/100mL','Intraveineuse','Baxter Healthcare Corporation','INT','Osmotic Laxative','Glucose and Sodium Chloride'),
('Saline Laxative','sodium phosphate','Lavement','SODIUM PHOSPHATE, DIBASIC, UNSPECIFIED FORM 7 g/118mL','Rectale','Walgreen Company','INT',NULL,'Saline Laxative'),
('Winco Original Formula Eye Drops','tetrahydrozoline hcl','Solution','TETRAHYDROZOLINE HYDROCHLORIDE .05 g/100mL','Ophtalmique','WinCo Foods, LLC','INT','Ophtalmologie','Winco Original Formula Eye Drops'),
('AGE20S SIGNATURE ESSENCE PACT INTENSE COVER MINI 27C','octinoxate, octocrylene, titanium dioxide','Crème','OCTINOXATE .26 g/4g','Topique','Aekyung Industrial Co., Ltd.','INT','Médicaments topiques','AGE20S SIGNATURE ESSENCE PACT INTENSE COVER MINI 27C'),
('EXTRA STRENGTH WAL-DRYL ITCH RELIEF','diphenhydramine, zinc acetate','Spray','DIPHENHYDRAMINE HYDROCHLORIDE 20 mg/mL','Topique','WALGREEN CO','INT','Copper Absorption Inhibitor','EXTRA STRENGTH WAL-DRYL ITCH RELIEF'),
('Etomidate','etomidate injection','Solution','ETOMIDATE 2 mg/mL','Intraveineuse','Gland Pharma Limited','US','General Anesthetic','Etomidate'),
('Extra Strength Antacid Assorted Berries','calcium carbonate','Comprimé','CALCIUM CARBONATE 750 mg/1','Orale','RARITAN PHARMACEUTICALS INC','INT',NULL,'Extra Strength Antacid Assorted Berries'),
('Sun Bum Tinted Sunscreen Lip Balm Broad Spectrum SPF 15 - Sunset Cove Carded','homosalate, octisalate, octocrylene, zinc oxide','STICK','HOMOSALATE 100 mg/g','Topique','Sun Bum, LLC','INT','Médicaments topiques','Sun Bum Tinted Sunscreen Lip Balm Broad Spectrum SPF 15 - Sunset Cove Carded'),
('Old Spice Fiji with Palm Tree','aluminum zirconium tetrachlorohydrex gly','STICK','ALUMINUM ZIRCONIUM TETRACHLOROHYDREX GLY 15 g/100g','Topique','The Procter & Gamble Manufacturing Company','INT','Médicaments topiques','Old Spice Fiji with Palm Tree'),
('Vega Oral Care Recovery Peppermint','kit','Kit',NULL,'Orale','StellaLife, Inc.','INT',NULL,'Vega Oral Care Recovery Peppermint'),
('Crest Pro-Health Bacteria Shield and Gum Deep Clean','stannous fluoride','PASTE, DENTIFRICE','STANNOUS FLUORIDE 1.4 mg/g','DENTAL','The Procter & Gamble Manufacturing Company','INT',NULL,'Crest Pro-Health Bacteria Shield and Gum Deep Clean'),
('Severe Cold and Flu Relief','acetaminophen, dextromethorphan hbr, guaifenesin, phenylephrine hcl','Comprimé','ACETAMINOPHEN 325 mg/1','Orale','CVS PHARMACY','INT','Expectorant','Severe Cold and Flu Relief'),
('Clean and Clear Acne Exfoliating Cleanser','salicylic acid','LIQUID','SALICYLIC ACID 20 mg/mL','Topique','Kenvue Brands LLC','INT','Médicaments topiques','Clean and Clear Acne Exfoliating Cleanser'),
('Perphenazine and Amitriptyline Hydrochloride','perphenazine and amitriptyline hydrochloride','Comprimé','AMITRIPTYLINE HYDROCHLORIDE 10 mg/1','Orale','Mylan Pharmaceuticals Inc.','US','Phenothiazine','Perphenazine and Amitriptyline Hydrochloride'),
('Smart Care FRESH RAIN HAND SANITIZER','ethyl alcohol','Spray','ALCOHOL 70 mL/100mL','Topique','Ashtel Studios, Inc.','INT','Médicaments topiques','Smart Care FRESH RAIN HAND SANITIZER'),
('Bravado Labs Numbing','lidocaine hcl','Spray','LIDOCAINE HYDROCHLORIDE 5 g/100g','Topique','Prodigy Media Inc','INT','Amide Local Anesthetic','Bravado Labs Numbing'),
('SPF15','avobenzone, homosalate, octocrylene, octisalate','LIPSTICK','AVOBENZONE 20 mg/g','Topique','Zhejiang Ayan Biotech Co.,Ltd.','INT','Médicaments topiques','SPF15'),
('Foster and Thrive Extra Strength Sugar Free Antacid Orange','calcium carbonate','Comprimé','CALCIUM CARBONATE 750 mg/1','Orale','Strategic Sourcing Services LLC','INT','Blood Coagulation Factor','Foster and Thrive Extra Strength Sugar Free Antacid Orange'),
('GOOD REMEDIES ibuprofen 200 mg','ibuprofen','Comprimé','IBUPROFEN 200 mg/1','Orale','Strive Pharmaceuticals Inc.','INT','Nonsteroidal Anti-inflammatory Drug','GOOD REMEDIES ibuprofen 200 mg'),
('Diclofenac Sodium Delayed Release Delayed Release','diclofenac sodium','Comprimé','DICLOFENAC SODIUM 75 mg/1','Orale','Cambridge Therapeutics Technologies, LLC','US','Nonsteroidal Anti-inflammatory Drug','Diclofenac Sodium Delayed Release Delayed Release'),
('Sensorcaine MPF','bupivacaine hydrochloride','Solution','BUPIVACAINE HYDROCHLORIDE 5 mg/mL','Épidurale','Henry Schein, Inc.','US','Amide Local Anesthetic','Sensorcaine MPF'),
('Oribe Serene Scalp Anti Dandruff','oribe serene scalp anti dandruff','Lotion','SALICYLIC ACID 2 g/100g','Topique','Oribe Hair Care LLC','INT','Médicaments topiques','Oribe Serene Scalp Anti Dandruff'),
('PetSilver Teeth and Gum','argentum metallicum','Spray','SILVER .0035 g/118g','Topique','AG Essence','INT','Médicaments topiques','PetSilver Teeth and Gum'),
('Erzofri extended-release','paliperidone palmitate','Solution injectable','PALIPERIDONE PALMITATE 39 mg/.25mL','Intramusculaire','Shandong Luye Pharmaceutical Co., Ltd.','US','Atypical Antipsychotic','Erzofri extended-release'),
('basic care clearlax','polyethylene glycol 3350','Solution','POLYETHYLENE GLYCOL 3350 17 g/17g','Orale','Amazon.com Services LLC','US','Osmotic Laxative','basic care clearlax'),
('Increlex','mecasermin','Solution injectable','MECASERMIN 40 mg/4mL','Sous-cutanée','Eton Pharmaceuticals, Inc.','US',NULL,'Increlex'),
('Dorzolamide Hydrochloride Ophthalmic','dorzolamide hydrochloride ophthalmic','Solution','DORZOLAMIDE HYDROCHLORIDE 20 mg/mL','Ophtalmique','Florida Pharmaceutical Products, LLC','US','Carbonic Anhydrase Inhibitor','Dorzolamide Hydrochloride Ophthalmic'),
('Azelaic Acid Gel','azelaic acid','Gel','AZELAIC ACID .15 g/g','Topique','Bryant Ranch Prepack','US','Decreased Protein Synthesis','Azelaic Acid Gel'),
('Hydrocortisone Cream','hydrocortisone cream','Crème','HYDROCORTISONE 25 mg/g','Topique','Direct_Rx','US','Corticosteroid','Hydrocortisone Cream'),
('Hand Sanitizer(COCONUT)','hand sanitizer(coconut)','LIQUID','ALCOHOL 62 mL/100mL','Topique','ZHEJIANG JINGHUI COSMETICS SHARE CO.,LTD','INT','Médicaments topiques','Hand Sanitizer(COCONUT)'),
('Nasal Allergy','triamcinolone acetonide','Spray','TRIAMCINOLONE ACETONIDE 55 ug/1','Nasale','Rugby Laboratories, Inc.','US','Corticosteroid','Nasal Allergy'),
('Syntherma Plus','lidocaine','Kit',NULL,NULL,'V2 Pharma, LLC','INT',NULL,'Syntherma Plus'),
('PAIN RELIEF MENTHOL AND SNAKE VENOM','cobra venom (naja naja) 2x, menthol (mentholum) tinc, moccasin venom (a.piscivorus) 4x','Gel','AGKISTRODON PISCIVORUS VENOM .001 mg/mL','Topique','Green Earth Health Inc.','INT','Médicaments topiques','PAIN RELIEF MENTHOL AND SNAKE VENOM'),
('Above Dermaclinical Men 72 hours','above dermaclinical men 72 hours','Crème','ALUMINUM CHLOROHYDRATE 12 mg/100g','Topique','BASTON INDUSTRIA DE AEROSSOIS LTDA','INT','Médicaments topiques','Above Dermaclinical Men 72 hours'),
('VITA SNAIL','niacinamide, adenosine','Crème','ADENOSINE .02 g/50mL','Topique','NOKSIBCHO cosmetic Co., Ltd.','INT','Adenosine Receptor Agonist','VITA SNAIL'),
('e.l.f. Camo CC Cream SPF 30 Light 280 N','homosalate, octisalate, octocrylene, zinc oxide','Crème','HOMOSALATE 50 mg/g','Topique','e.l.f. Cosmetics, Inc.','INT','Médicaments topiques','e.l.f. Camo CC Cream SPF 30 Light 280 N'),
('Vacation Classic Mini Whip SPF 30 Broad Spectrum SPF 30','homosalate, octisalate, octocrylene, avobenzone','AEROSOL, FOAM','AVOBENZONE .03 g/g','Topique','Vacation Inc.','INT','Médicaments topiques','Vacation Classic Mini Whip SPF 30 Broad Spectrum SPF 30'),
('Seaweed Bath Co Playful Papaya Kids Sunscreen SPF 50','zinc oxide','LIQUID','ZINC OXIDE 170 mg/mL','Topique','The Seaweed Bath Co.','INT','Copper Absorption Inhibitor','Seaweed Bath Co Playful Papaya Kids Sunscreen SPF 50'),
('Toast Screamin Menthol','menthol','Crème','MENTHOL 4 g/100g','Topique','IDEAZ, LLC','INT','Médicaments topiques','Toast Screamin Menthol'),
('Base Laboratories Saline','sodium chloride','LIQUID','SODIUM CHLORIDE 9 mg/mL','Nasale','Joonem LLC','INT',NULL,'Base Laboratories Saline'),
('Povidone Iodine Prep Pad','povidone iodine prep pad','CLOTH','POVIDONE-IODINE 10 mg/100mg','Topique','Hua Jing Medical Supplies INC.','INT','Médicaments topiques','Povidone Iodine Prep Pad'),
('Tinted Mineral Sunscreen Broad Spectrum SPF 30','titanium dioxide and zinc oxide','Crème','TITANIUM DIOXIDE 7.75 g/100g','Topique','New Beginnings Tattoo Removal','INT','Médicaments topiques','Tinted Mineral Sunscreen Broad Spectrum SPF 30'),
('La Roche Posay Anthelios UV Air Serum Sunscreen Broad Spectrum SPF 50','avobenzone, homosalate, octisalate and octocrylene','LIQUID','AVOBENZONE 30 mg/mL','Topique','L''Oreal USA Products Inc','INT','Médicaments topiques','La Roche Posay Anthelios UV Air Serum Sunscreen Broad Spectrum SPF 50'),
('Herbal Utaplas External Analgesic Plaster','menthol, methyl salicylate','Patch transdermique','MENTHOL, UNSPECIFIED FORM .06 g/g','Topique','Big 5 Nutrition LLC','INT','Médicaments topiques','Herbal Utaplas External Analgesic Plaster'),
('Lemon Mint Drops','menthol','PASTILLE','MENTHOL 1.1 mg/1','Orale','Target Corporation Inc.','INT',NULL,'Lemon Mint Drops'),
('GOLDEN ROSE GLOW KISS TINTED LIP BALM BERRY PINK','avobenzone, octinoxate','LIPSTICK','AVOBENZONE 2.7 g/100g','Topique','ERKUL KOZMETIK SANAYI VE TICARET ANONIM SIRKETI','INT','Médicaments topiques','GOLDEN ROSE GLOW KISS TINTED LIP BALM BERRY PINK'),
('hand sanitizer 01','alcohol','LIQUID','ALCOHOL 62 mL/100mL','Topique','Cosmuses Cosmetics (Ningbo) Co., Ltd.','INT','Médicaments topiques','hand sanitizer 01'),
('Bestmade Natural Products BM119','calcium iod, kali iod., arsenic iod., merc bin iod., merc viv.','LIQUID','ARSENIC TRIIODIDE 60 [hp_C]/60[hp_C]','Orale','Bestmade Natural Products','INT','Blood Coagulation Factor','Bestmade Natural Products BM119'),
('Bestmade Natural Products Phos Acid','phosphoricum acidum','Comprimé','PHOSPHORIC ACID 30 [hp_C]/30[hp_C]','Orale','Bestmade Natural Products','INT',NULL,'Bestmade Natural Products Phos Acid'),
('Virex','adenoviren nosode, asclepias tuberosa, calcarea arsenicica, camphora, coxsackie a2 nosode, coxsackie a3 nosode, coxsackie a4 nosode, coxsackie a5 nosode, coxsackie a7 nosode, coxsackie b1 nosode, coxsackie b3 nosode, coxsackie b4 nosode, coxsackie b5 nosode, cytomegalovirus nosode, echinacea purpurea, epstein-barr virus nosode, euphrasia officinalis, influenzinum, lac vaccinum, morbillinum, natrum muriaticum, phytolacca decandra, thuja occidentalis, trifolium pratense, variolinum','Spray','ASCLEPIAS TUBEROSA ROOT 3 [hp_X]/mL','Orale','Nutritional Specialties, Inc.','INT','Live Human Adenovirus Type 4 Vaccine','Virex'),
('NATUHEAL ORIGINAL NASAL','naphazoline hcl 0.05% original nasal','Spray','NAPHAZOLINE HCL .05 g/100mL','Nasale','Jiangxi Yudexi Pharmaceutical Co., LTD','INT',NULL,'NATUHEAL ORIGINAL NASAL'),
('TAGOQHIA 5% Minoxidil Hair Growth Sprays Serum','minoxidil','LIQUID','BIOTIN .5 g/100mL','Topique','Guangzhou Borderless Technology Co., Ltd.','INT','Arteriolar Vasodilator','TAGOQHIA 5% Minoxidil Hair Growth Sprays Serum'),
('TAGRID TINEA VERSICOLOR','salicylic acid','Crème','SALICYLIC ACID 2 g/100g','Topique','TAGRID LLC','INT','Médicaments topiques','TAGRID TINEA VERSICOLOR'),
('Tinted Primer Anti-Aging','titanium dioxide, zinc oxide','Crème','TITANIUM DIOXIDE 80 mg/g','Topique','DERMOPERFECTION SKINCARE SERVICES, LLC','INT','Médicaments topiques','Tinted Primer Anti-Aging'),
('Tula Skincare Radiant Skin Brightening Serum Skin Tint Broad Spectrum SPF 30 15 Medium Neutral-Cool','avobenzone, and octisalate','LIQUID','AVOBENZONE 3 g/100mL','Topique','The Procter & Gamble Manufacturing Company','INT','Médicaments topiques','Tula Skincare Radiant Skin Brightening Serum Skin Tint Broad Spectrum SPF 30 15 Medium Neutral-Cool'),
('The Zoeun Skin Sturgeon Hair Essence','colloidal oatmael','LIQUID','OATMEAL .007 g/100mL','Topique','Sturgeonbio Co.,Ltd.','INT','Non-Standardized Food Allergenic Extract','The Zoeun Skin Sturgeon Hair Essence'),
('Sleep gummies','sleep gummies','Gel','AMINO ACIDS 2 g/1001','Orale','XIAN CHIANG COMPANY LIMITED','INT','Amino Acid Hypertonic Solution','Sleep gummies'),
('Hydro Boosting Eye Cream','hydro boosting eye cream','Crème','CAPRYLIC/CAPRIC TRIGLYCERIDE 3 mg/15mL','CUTANEOUS','Guangzhou Yanxi Biotechnology Co., Ltd','INT','Non-Standardized Chemical Allergen','Hydro Boosting Eye Cream'),
('Sun Shield On-the-Glow Sheer Stick SPF40','avobenzone, homosalate, octocrylene, octisalate','STICK','AVOBENZONE 3 g/100g','Topique','Koco Life LLC','INT','Médicaments topiques','Sun Shield On-the-Glow Sheer Stick SPF40'),
('Sinu-Phen Plus Sinus Pain and Pressure','acetaminophen, phenylephrine hydrochloride','Comprimé','ACETAMINOPHEN 500 mg/1','Orale','Wildman Business Group','INT','alpha-1 Adrenergic Agonist','Sinu-Phen Plus Sinus Pain and Pressure'),
('Tuberculosis Eliminator','ginsenoside compound k','GRANULE','GINSENOSIDE COMPOUND K 50 mg/10g','Orale','Hainan Zehuitang Biotechnology Co., LTD','INT',NULL,'Tuberculosis Eliminator'),
('WOODSLEEP Tallow Sunscreen','titanium dioxide','Crème','TALLOW .0114 mg/57mg','Topique','Shantou Woodsleep Biotechnology Co., Ltd.','INT','Médicaments topiques','WOODSLEEP Tallow Sunscreen'),
('OUHOE Face Body Sunscreen','titanium dioxide','Crème','BEESWAX .016 mg/80mg','Topique','Shantou Ouhoe Technology Co., Ltd.','INT','Lipid Emulsion','OUHOE Face Body Sunscreen')
) AS v(nom, dci, forme, dosage, voie, labo, pays, classe, nomcom)
WHERE NOT EXISTS (
  SELECT 1 FROM medicaments m WHERE UPPER(m.nom) = UPPER(v.nom)
);
