-- ndc_batch_081.sql (80 rows)
INSERT INTO medicaments (nom, dci, forme, dosage, voie_administration, laboratoire, pays, classe_therapeutique, nom_commercial)
SELECT v.nom, v.dci, v.forme, v.dosage, v.voie, v.labo, v.pays, v.classe, v.nomcom
FROM (VALUES
('Mens Collection Antiperspirant Deodorant Gingham','aluminum zirconium trichlorohydrex gly','STICK','ALUMINUM ZIRCONIUM TRICHLOROHYDREX GLY 16 g/100g','Topique','Bath and Body Works, Distr.','INT','Médicaments topiques','Mens Collection Antiperspirant Deodorant Gingham'),
('FAGUS GRANDIFOLIA POLLEN','beech','Solution','FAGUS GRANDIFOLIA POLLEN .05 g/mL','PERCUTANEOUS','ALK-Abello, Inc.','US','Non-Standardized Pollen Allergenic Extract','FAGUS GRANDIFOLIA POLLEN'),
('CUCUMBER','cucumis sativus','Solution','CUCUMBER .1 g/mL','PERCUTANEOUS','ALK-Abello, Inc.','US','Non-Standardized Food Allergenic Extract','CUCUMBER'),
('JUGLANS NIGRA POLLEN','black pollen walnut','Solution','JUGLANS NIGRA POLLEN .05 g/mL','PERCUTANEOUS','ALK-Abello, Inc.','US','Non-Standardized Pollen Allergenic Extract','JUGLANS NIGRA POLLEN'),
('R02 BILE DUCTS','ferrosoferric phosphate, juniperus communis stem, ribes nigrum flower bud, viscum album stem','Solution','FERROSOFERRIC PHOSPHATE 7 [hp_C]/mL','Sublinguale','Apex Energetics Inc.','INT',NULL,'R02 BILE DUCTS'),
('Unscented Hand Sanitizer','alcohol','Gel','ALCOHOL 60 mL/100mL','Topique','Raining Rose','INT','Médicaments topiques','Unscented Hand Sanitizer'),
('Quality Choice Chewable Antacid Assorted Fruit','antacid tablets','Comprimé','CALCIUM CARBONATE 500 mg/1','Orale','Chain Drug Marketing Association','INT','Blood Coagulation Factor','Quality Choice Chewable Antacid Assorted Fruit'),
('GDS-Calm','digestive balance','LIQUID','ASPIDOSPERMA QUEBRACHO-BLANCO BARK 6 [hp_X]/mL','Orale','Vitality Works, Inc.','INT','Non-Standardized Fungal Allergenic Extract','GDS-Calm'),
('Almay Smart Shade Skintone Matching Makeup Light','titanium dioxide zinc oxide','LIQUID','TITANIUM DIOXIDE 4.8 mg/mL','Topique','Almay, Inc.','INT','Copper Absorption Inhibitor','Almay Smart Shade Skintone Matching Makeup Light'),
('Blue Lizard Kids SPF 50','zinc oxide','Spray','ZINC OXIDE 24 mg/g','Topique','Crown Laboratories','INT','Médicaments topiques','Blue Lizard Kids SPF 50'),
('OHM-REN','apis mellifica, aranea diadema, berberis vulgaris, cantharis, equisetum hyemale, hydrastis canadensis, juglans regia, kali bichromicum, mercurius solubilis, sarsaparilla, solidago virgaurea','Spray','APIS MELLIFERA 12 [hp_X]/30mL','Orale','OHM PHARMA INC.','INT','Standardized Insect Venom Allergenic Extract','OHM-REN'),
('Anxiovita','aconitum napellus, anacardium orientale, cerebrum, hypericum perforatum','LIQUID','ACONITUM NAPELLUS 18 [hp_M]/59mL','Orale','RUBIMED AG','INT',NULL,'Anxiovita'),
('Motrin IB, CVP HEALTH','ibuprofen','Comprimé','IBUPROFEN 200 mg/1','Orale','Lil'' Drug Store Products, Inc.','US','Nonsteroidal Anti-inflammatory Drug','Motrin IB, CVP HEALTH'),
('MITIGO','morphine sulfate','Solution injectable','MORPHINE SULFATE 200 mg/20mL','Épidurale','Piramal Critical Care, Inc.','US','Opioid Agonist','MITIGO'),
('AGE20S SIGNATURE ESSENCE PACT INTENSE COVER 23W PACK OF 2','octinoxate, octocrylene, titanium dioxide','Crème','OCTINOXATE .91 g/14g','Topique','Aekyung Industrial Co., Ltd.','INT','Médicaments topiques','AGE20S SIGNATURE ESSENCE PACT INTENSE COVER 23W PACK OF 2'),
('Walgreens Sterile Soothing Eye Wash','purified water','LIQUID','WATER 99.05 mL/100mL','Ophtalmique','Walgreens','INT','Ophtalmologie','Walgreens Sterile Soothing Eye Wash'),
('Acne Moisturizer','salicylic acid','Crème','SALICYLIC ACID .5 mg/50mL','Topique','Spa de Soleil','INT','Médicaments topiques','Acne Moisturizer'),
('NativeRemedies Tic Tamer','chamomilla, cina, hyoscyamus, zinc met','LIQUID','ARTEMISIA CINA FLOWER 30 [hp_C]/59mL','Orale','Silver Star Brands','INT',NULL,'NativeRemedies Tic Tamer'),
('Temsirolimus','temsirolimus injection','Kit',NULL,NULL,'Gland Pharma Limited','US',NULL,'Temsirolimus'),
('Drx Choice childrens allergy chews','diphenhydramine hcl','Comprimé','DIPHENHYDRAMINE HYDROCHLORIDE 12.5 mg/1','Orale','RARITAN PHARMACEUTICALS INC','INT','Histamine-1 Receptor Antagonist','Drx Choice childrens allergy chews'),
('Maximum Strength Nighttime Severe Cold and Flu','acetaminophen, dextromethorphan hydrobromide, doxylamine succinate, phenylephrine hydrochloride','Gélule','ACETAMINOPHEN 325 mg/1','Orale','Prodose, Inc.','INT','Antihistamine','Maximum Strength Nighttime Severe Cold and Flu'),
('Always Liquid Foundation Makeup Sunscreen Broad Spectrum SPF 15 - Shell','homosalate, octisalate, zinc oxide','LIQUID','HOMOSALATE 4.25 g/100mL','Topique','Distribuidora Comercial Jafra, S.A. de C.V','INT','Médicaments topiques','Always Liquid Foundation Makeup Sunscreen Broad Spectrum SPF 15 - Shell'),
('Sun Bum Tinted Sunscreen Lip Balm Broad Spectrum SPF 15 - Bonfire Carded','homosalate, octisalate, octocrylene, zinc oxide','STICK','HOMOSALATE 100 mg/g','Topique','Sun Bum, LLC','INT','Médicaments topiques','Sun Bum Tinted Sunscreen Lip Balm Broad Spectrum SPF 15 - Bonfire Carded'),
('Verzenio','abemaciclib','Comprimé','ABEMACICLIB 50 mg/1','Orale','Eli Lilly and Company','US','Kinase Inhibitor','Verzenio'),
('Walgreen Childrens Pain plus Fever','acetaminophen','Suspension','ACETAMINOPHEN 160 mg/5mL','Orale','WALGREENS CO.','INT',NULL,'Walgreen Childrens Pain plus Fever'),
('Old Spice Krakengard','aluminum zirconium tetrachlorohydrex gly','STICK','ALUMINUM ZIRCONIUM TETRACHLOROHYDREX GLY 15 g/100g','Topique','The Procter & Gamble Manufacturing Company','INT','Médicaments topiques','Old Spice Krakengard'),
('StellaLife VEGA Oral Care Coconut','risne','RINSE','APIS MELLIFERA 12 [hp_X]/mL','DENTAL','StellaLife, Inc.','INT','Standardized Insect Venom Allergenic Extract','StellaLife VEGA Oral Care Coconut'),
('Crest Pro Health Breath Purify and Gum Deep Clean','stannous fluoride','PASTE, DENTIFRICE','STANNOUS FLUORIDE 1.4 mg/g','DENTAL','The Procter & Gamble Manufacturing Company','INT',NULL,'Crest Pro Health Breath Purify and Gum Deep Clean'),
('zinc oxide 20%','zinc oxide 20%','Pommade','ZINC OXIDE 20 g/100g','Topique','Bionpharma Inc','INT','Médicaments topiques','zinc oxide 20%'),
('AMLODIPINE BESYLATE 2.5 mg','amlodipine besylate','Comprimé','AMLODIPINE BESYLATE 2.5 mg/1','Orale','Oxford Pharmaceuticals, LLC','US','Calcium Channel Blocker','AMLODIPINE BESYLATE 2.5 mg'),
('Antibacterial Hand Wash','benzalkonium chloride 0.13%','LIQUID','BENZALKONIUM CHLORIDE 1.313 mg/mL','Topique','Uline','INT','Médicaments topiques','Antibacterial Hand Wash'),
('Neutrogena Oil-Free Acne Wash Daily Scrub','salicylic acid','Gel','SALICYLIC ACID 20 mg/mL','Topique','Kenvue Brands LLC','INT','Médicaments topiques','Neutrogena Oil-Free Acne Wash Daily Scrub'),
('Neutrogena Mineral Invisible Daily Defense Face Sunscreen Broad Spectrum SPF 30','titanium dioxide, zinc oxide','Lotion','TITANIUM DIOXIDE 49 mg/mL','Topique','Kenvue Brands LLC','INT','Médicaments topiques','Neutrogena Mineral Invisible Daily Defense Face Sunscreen Broad Spectrum SPF 30'),
('Calcium Polycarbophil','calcium polycarbophil','Comprimé','CALCIUM POLYCARBOPHIL 625 mg/1','Orale','LEADER/ Cardinal Health 110, Inc.','INT',NULL,'Calcium Polycarbophil'),
('LEADER Emergency Contraceptive Levonorgestrel','levonorgestrel','Comprimé','LEVONORGESTREL 1.5 mg/1','Orale','Cardinal Health 110, LLC. DBA Leader','US','Progestin','LEADER Emergency Contraceptive Levonorgestrel'),
('Brush Buddies DISNEY FROZEN ANTICAVITY FLUORIDE - Blizzard Berry','sodium fluoride','MOUTHWASH','SODIUM FLUORIDE .05 g/100mL','Orale','Ashtel Studios, Inc.','INT',NULL,'Brush Buddies DISNEY FROZEN ANTICAVITY FLUORIDE - Blizzard Berry'),
('TattooGirl Numbing','lidocaine hcl','Crème','LIDOCAINE HYDROCHLORIDE 4 g/100g','Topique','Prodigy Media Inc','INT','Amide Local Anesthetic','TattooGirl Numbing'),
('SPF30 Sunscreen','avobenzone, homosalate, octocrylene, octisalate','STICK','AVOBENZONE 30 mg/g','Topique','Zhejiang Ayan Biotech Co.,Ltd.','INT','Médicaments topiques','SPF30 Sunscreen'),
('RIGHT REMEDIES Pain Relief Extra Strength Caplet','acetaminophen','Comprimé','ACETAMINOPHEN 500 mg/1','Orale','Strive Pharmaceuticals Inc.','INT',NULL,'RIGHT REMEDIES Pain Relief Extra Strength Caplet'),
('Childrens First Aid','calendula officials, stellaria media, st. johns wort, rosemary oil, plantago major, commiphora myrrha, comfrey leaf, salvia officinalis, sunflower oil','SALVE','ACHILLEA MILLEFOLIUM FLOWER 1 [hp_X]/51.7g','Topique','Spry Life LLC','INT','Médicaments topiques','Childrens First Aid'),
('HealthWise Advanced Hand Sanitizer with Lavender','ethyl alcohol 70%','Gel','ALCOHOL 70 mL/100mL','Topique','Veridian Healthcare','INT','Médicaments topiques','HealthWise Advanced Hand Sanitizer with Lavender'),
('Megestrol Acetate','megestrol acetate','Comprimé','MEGESTROL ACETATE 40 mg/1','Orale','Bryant Ranch Prepack','US','Progestin','Megestrol Acetate'),
('Milani Prime Protect SPF 30 Face Primer','avobenzone, octinoxate, octocrylene, and oxybenzone','Crème','AVOBENZONE 30 mg/mL','Topique','The Milani Group, Inc.','INT','Médicaments topiques','Milani Prime Protect SPF 30 Face Primer'),
('Keep Going Alcohol Prep Pad','isopropyl alcohol','CLOTH','ISOPROPYL ALCOHOL 70 g/100g','Topique','JIANGMEN SHUIZIRUN SANITARY ARTICLES CO., LTD.','INT','Médicaments topiques','Keep Going Alcohol Prep Pad'),
('Sodium Bicarbonate Antacid','sodium bicarbonate','Comprimé','SODIUM BICARBONATE 650 mg/1','Orale','Aphena Pharma Solutions - Tennessee, LLC','INT','Osmotic Laxative','Sodium Bicarbonate Antacid'),
('PetSilver Wound 4','argentum metallicum','Spray','SILVER .0035 g/118g','Topique','AG Essence','INT','Médicaments topiques','PetSilver Wound 4'),
('AY BENDITO CBD','menthol, camphor','Spray','CAMPHOR (SYNTHETIC) 5.3 g/100mL','Topique','AY BENDITO INTERNATIONAL, INC','INT','Médicaments topiques','AY BENDITO CBD'),
('basic care stool softener','docusate sodium','Gélule','DOCUSATE SODIUM 100 mg/1','Orale','Amazon.com Services LLC','INT',NULL,'basic care stool softener'),
('Sertraline HCL','sertraline hcl','Comprimé','SERTRALINE HYDROCHLORIDE 50 mg/1','Orale','Direct_Rx','US','Serotonin Reuptake Inhibitor','Sertraline HCL'),
('Cough Drops Dollar General Menthol 160ct','menthol','Pastille','MENTHOL 5.4 mg/1','Orale','Dollar General Corporation','INT',NULL,'Cough Drops Dollar General Menthol 160ct'),
('Nourishing Sanitizing Hand Wipes Lavendula','alcohol solution','CLOTH','ALCOHOL 65 mL/100mL','Topique','Noshinku','INT','Médicaments topiques','Nourishing Sanitizing Hand Wipes Lavendula'),
('SOME BY MI TRUECICA AQUA CALMING SUNSCREEN','avobenzone, homosalate, octisalate, octocrylene','Crème','AVOBENZONE 1.5 g/50mL','Topique','PERENNEBELL Co., Ltd.','INT','Médicaments topiques','SOME BY MI TRUECICA AQUA CALMING SUNSCREEN'),
('Eversmile OrthoFoam Anticavity','0.05% sodium fluoride rinse','LIQUID','SODIUM FLUORIDE .05 g/100mL','DENTAL','Everbrands, Inc.','INT',NULL,'Eversmile OrthoFoam Anticavity'),
('Green Defense daily mineral sunscreen Broad Spectrum SPF 30','zinc oxide','Lotion','ZINC OXIDE 182.3 mg/mL','Topique','Farmacy Beauty LLC','INT','Copper Absorption Inhibitor','Green Defense daily mineral sunscreen Broad Spectrum SPF 30'),
('unpa Cha Cha Toothpaste','sodium monofluorophosphate','PASTE, DENTIFRICE','SODIUM MONOFLUOROPHOSPHATE .74 g/100g','Orale','Lycl Inc.','INT',NULL,'unpa Cha Cha Toothpaste'),
('ANTIPERSPIRANT ABOVE NEYMAR JR WOMEN','antiperspirant above neymar jr women','AEROSOL','ALUMINUM SESQUICHLOROHYDRATE 16 g/100g','Topique','BASTON INDUSTRIA DE AROSSOIS LTDA','INT','Médicaments topiques','ANTIPERSPIRANT ABOVE NEYMAR JR WOMEN'),
('ko7 Herbal MedicatedSoap','sodium palm kernelate, panax ginseng root extract','SOAP','PANAX GINSENG ROOT OIL .3 g/100g','Topique','MISOCOS','INT','Médicaments topiques','ko7 Herbal MedicatedSoap'),
('THE SKIN HOUSE Vital BrightEmulsion','niacinamide','EMULSION','NIACINAMIDE 1 g/100mL','Topique','NOKSIBCHO cosmetic Co., Ltd.','INT','Médicaments topiques','THE SKIN HOUSE Vital BrightEmulsion'),
('Dimethicone','dimethicone','Lotion','DIMETHICONE 12 mg/mL','Topique','Topco Associates LLC','INT','Skin Barrier Activity','Dimethicone'),
('e.l.f. Camo CC Cream SPF 30 Fair 140 W','homosalate, octisalate, octocrylene, zinc oxide','Crème','HOMOSALATE 50 mg/g','Topique','e.l.f. Cosmetics, Inc.','INT','Médicaments topiques','e.l.f. Camo CC Cream SPF 30 Fair 140 W'),
('Orange Gel','avobenzone octisalate octocrylene homosalate','Gel','AVOBENZONE 2.9 g/100g','Topique','Vacation Inc.','INT','Médicaments topiques','Orange Gel'),
('SEAWEED BATH CO. Super Sheer Face Serum SPF-50','zinc oxide','Solution','ZINC OXIDE 180 mg/mL','Topique','The Seaweed Bath Co.','INT','Copper Absorption Inhibitor','SEAWEED BATH CO. Super Sheer Face Serum SPF-50'),
('Caring Mill Triple Hand Sanitizer with Lavender','ethyl alcohol','Gel','ALCOHOL 70 mL/100mL','Topique','FSA Store Inc. (Caring Mills)','INT','Médicaments topiques','Caring Mill Triple Hand Sanitizer with Lavender'),
('meijer EXTRA STRENGTH Gas Relief SOFTGEL','simethicone','Gélule','DIMETHICONE, UNSPECIFIED 125 mg/1','Orale','Meijer, Inc.','INT','Skin Barrier Activity','meijer EXTRA STRENGTH Gas Relief SOFTGEL'),
('Active Recovery Pain Relief Stick','camphor, menthol','STICK','CAMPHOR (NATURAL) 10 g/100g','Topique','Charlottes Web, Inc.','INT','Médicaments topiques','Active Recovery Pain Relief Stick'),
('Nux vomica 30C - 3-Pack','nux vomica','PELLET','STRYCHNOS NUX-VOMICA SEED 30 [hp_C]/1','Sublinguale','SEVENE USA','INT','Non-Standardized Plant Allergenic Extract','Nux vomica 30C - 3-Pack'),
('Spit and Polish Mineral Lip Balm Broad Spectrum Lip Protectant SPF 30','zinc oxide','STICK','ZINC OXIDE 80 mg/g','Topique','Naturally Uncommon, LLC','INT','Copper Absorption Inhibitor','Spit and Polish Mineral Lip Balm Broad Spectrum Lip Protectant SPF 30'),
('WAXUP Numbing','lidocaine hydrochloride','LIQUID','LIDOCAINE HYDROCHLORIDE 50 mg/mL','Topique','CONSTRUSOLUTION, LLC','INT','Amide Local Anesthetic','WAXUP Numbing'),
('HCS Roll-on Antiperspirant','aluminum chlorohydrate','LIQUID','ALUMINUM CHLOROHYDRATE 45 mg/mL','Topique','Concordance Healthcare Solutions, LLC.','INT','Médicaments topiques','HCS Roll-on Antiperspirant'),
('Derman Antifungal Powder Tolnaftate','tolnaftate','Poudre','TOLNAFTATE 10 mg/g','Topique','Taisho Pharmaceutical California Inc.','INT','Médicaments topiques','Derman Antifungal Powder Tolnaftate'),
('up and up cherry nicotine','nicotine polacrilex','Pastille','NICOTINE 2 mg/1','Orale','Target Corporation','US','Cholinergic Nicotinic Agonist','up and up cherry nicotine'),
('Miranda Castros Healing Cell Salts For Bones, Hair, Nails, and Teeth','calcarea fluorica, calcarea phosphorica, silicea','LIQUID','CALCIUM FLUORIDE 6 [hp_X]/mL','Orale','MIRANDA CASTRO''S SHOP, LLC','INT',NULL,'Miranda Castros Healing Cell Salts For Bones, Hair, Nails, and Teeth'),
('GR TOTAL COVER 2 in 1 Foundation and Concealer SPF 15','octinoxate','Lotion','OCTINOXATE 1 g/100mL','Topique','ERKUL KOZMETIK SANAYI VE TICARET ANONIM SIRKETI','INT','Médicaments topiques','GR TOTAL COVER 2 in 1 Foundation and Concealer SPF 15'),
('SPF15 lip balm 01','octocrylene, octisalate','LIPSTICK','OCTISALATE 2 g/100g','Topique','Cosmuses Cosmetics (Ningbo) Co., Ltd.','INT','Médicaments topiques','SPF15 lip balm 01'),
('Bestmade Natural Products BM114','bacillus, corticotrophin, d.n.a., morgan pure, bryonia, rhus tox, nux vom','LIQUID','BRYONIA ALBA ROOT 100 [hp_C]/100[hp_C]','Orale','Bestmade Natural Products','INT','Adrenocorticotropic Hormone','Bestmade Natural Products BM114'),
('Bestmade Natural Products Nat Phos','natrum phosphoricum','Comprimé','SODIUM PHOSPHATE, DIBASIC, HEPTAHYDRATE 30 [hp_C]/30[hp_C]','Orale','Bestmade Natural Products','INT','Osmotic Laxative','Bestmade Natural Products Nat Phos'),
('Blood Liquescence','allium cepa, hyssopus officinalis, avena sativa, paloondo, urtica dioica, trifolium pratense, zingiber officinale, capsicum annuum, hepar (bovine), hypophysis suis, juglans regia, medulla ossis suis, remex crispus, spleen (bovine), camphora, magnesia phosphorica, ferrum phosphoricum, pyrogenium','LIQUID','AVENA SATIVA FLOWERING TOP 2 [hp_X]/mL','Orale','Nutritional Specialties, Inc.','INT','Calculi Dissolution Agent','Blood Liquescence'),
('CODECURE WART REMOVER','salicylic acid 17% wart remover','LIQUID','SALICYLIC ACID 17 g/100mL','Topique','Jiangxi Yudexi Pharmaceutical Co., LTD','INT','Médicaments topiques','CODECURE WART REMOVER'),
('Bed Sore and Wound Healing Cream','allantoin','Crème','ALLANTOIN 5 mg/g','Topique','TAGRID LLC','INT','Médicaments topiques','Bed Sore and Wound Healing Cream'),
('ProBliva Anti Fungal Shampoo.','antifungal','SHAMPOO','SALICYLIC ACID 4.72 g/236g','Topique','CAVTECH HOLDING LLC','INT','Médicaments topiques','ProBliva Anti Fungal Shampoo.')
) AS v(nom, dci, forme, dosage, voie, labo, pays, classe, nomcom)
WHERE NOT EXISTS (
  SELECT 1 FROM medicaments m WHERE UPPER(m.nom) = UPPER(v.nom)
);
