-- rxnorm_batch_168.sql (80 rows)
INSERT INTO medicaments (nom, dci, pays)
SELECT v.nom, v.dci, v.pays FROM (VALUES
('viridiflorol','viridiflorol','INT'),
('Virola sebifera resin','virola sebifera resin','INT'),
('Viscum album fruit extract','viscum album fruit extract','INT'),
('Viscum album fruiting top extract','viscum album fruiting top extract','INT'),
('Viscum album leaf extract','viscum album leaf extract','INT'),
('Viscum album preparation','viscum album preparation','INT'),
('Viscum album stem extract','viscum album stem extract','INT'),
('Viscum album whole extract','viscum album whole extract','INT'),
('vismodegib','vismodegib','INT'),
('vitamin A','vitamin a','INT'),
('vitamin B complex','vitamin b complex','INT'),
('vitamin B12','vitamin b12','INT'),
('vitamin B6','vitamin b6','INT'),
('vitamin D','vitamin d','INT'),
('vitamin D3','vitamin d3','INT'),
('vitamin E','vitamin e','INT'),
('vitamin K','vitamin k','INT'),
('vitamin K1','vitamin k1','INT'),
('vitamin K2','vitamin k2','INT'),
('vitamin K3','vitamin k3','INT'),
('vitamin K7','vitamin k7','INT'),
('vitamin MK6','vitamin mk6','INT'),
('vitamin MK7','vitamin mk7','INT'),
('Vitex agnus-castus whole extract','vitex agnus-castus whole extract','INT'),
('Vitex negundo flower extract','vitex negundo flower extract','INT'),
('Vitex negundo fruit extract','vitex negundo fruit extract','INT'),
('Vitex negundo whole extract','vitex negundo whole extract','INT'),
('Vitex rotundifolia fruit extract','vitex rotundifolia fruit extract','INT'),
('Vitex trifolia fruit extract','vitex trifolia fruit extract','INT'),
('vitexin','vitexin','INT'),
('Vitis extract','vitis extract','INT'),
('Vitis vinifera anthocyanins extract','vitis vinifera anthocyanins extract','INT'),
('Vitis vinifera flowering top extract','vitis vinifera flowering top extract','INT'),
('Vitis vinifera fruit oil','vitis vinifera fruit oil','INT'),
('Vitis vinifera fruit rind','vitis vinifera fruit rind','INT'),
('Vitis vinifera leaf extract','vitis vinifera leaf extract','INT'),
('Vitis vinifera leaf oil','vitis vinifera leaf oil','INT'),
('Vitis vinifera pollen extract','vitis vinifera pollen extract','INT'),
('Vitis vinifera root oil','vitis vinifera root oil','INT'),
('Vitis vinifera seed extract','vitis vinifera seed extract','INT'),
('Vitis vinifera stem extract','vitis vinifera stem extract','INT'),
('Vitis vinifera whole extract','vitis vinifera whole extract','INT'),
('Vitreoscilla lysate extract','vitreoscilla lysate extract','INT'),
('Voacanga africana seed extract','voacanga africana seed extract','INT'),
('voclosporin','voclosporin','INT'),
('volanesorsen','volanesorsen','INT'),
('von Willebrand factor','von willebrand factor','INT'),
('vonicog alfa','vonicog alfa','INT'),
('vonoprazan','vonoprazan','INT'),
('vorapaxar','vorapaxar','INT'),
('vorasidenib','vorasidenib','INT'),
('voretigene neparvovec','voretigene neparvovec','INT'),
('voriconazole','voriconazole','INT'),
('vorinostat','vorinostat','INT'),
('vortioxetine','vortioxetine','INT'),
('vosoritide','vosoritide','INT'),
('voxelotor','voxelotor','INT'),
('voxilaprevir','voxilaprevir','INT'),
('vutrisiran','vutrisiran','INT'),
('walnut allergenic extract','walnut allergenic extract','INT'),
('walnut oil','walnut oil','INT'),
('Waltheria indica leaf extract','waltheria indica leaf extract','INT'),
('warfarin','warfarin','INT'),
('wasabi preparation','wasabi preparation','INT'),
('wasabi root extract','wasabi root extract','INT'),
('wasp venom protein','wasp venom protein','INT'),
('wasp venoms','wasp venoms','INT'),
('water','water','INT'),
('water birch pollen extract','water birch pollen extract','INT'),
('water oak pollen extract','water oak pollen extract','INT'),
('watercress allergenic extract','watercress allergenic extract','INT'),
('watercress preparation','watercress preparation','INT'),
('watermelon allergenic extract','watermelon allergenic extract','INT'),
('watermelon preparation','watermelon preparation','INT'),
('watermelon seed extract','watermelon seed extract','INT'),
('watermelon seed oil','watermelon seed oil','INT'),
('weakleaf bur ragweed pollen extract','weakleaf bur ragweed pollen extract','INT'),
('West Indian lemongrass oil','west indian lemongrass oil','INT'),
('West Nile virus','west nile virus','INT'),
('western black willow pollen extract','western black willow pollen extract','INT')
) AS v(nom, dci, pays)
WHERE NOT EXISTS (SELECT 1 FROM medicaments m WHERE LOWER(m.nom) = LOWER(v.nom));
