-- rxnorm_batch_193.sql (80 rows)
INSERT INTO medicaments (nom, dci, pays)
SELECT v.nom, v.dci, v.pays FROM (VALUES
('dehydrocholate / papaverine','dehydrocholate / papaverine','INT'),
('dehydrocholate / pepsin A','dehydrocholate / pepsin a','INT'),
('dehydrosanol / triamterene','dehydrosanol / triamterene','INT'),
('demelverin / trihexyphenidyl','demelverin / trihexyphenidyl','INT'),
('deoxycholate / pepsin A','deoxycholate / pepsin a','INT'),
('deoxycytidine / thymidine','deoxycytidine / thymidine','INT'),
('deoxyribonucleases / plasmin','deoxyribonucleases / plasmin','INT'),
('dequalinium / dibunate','dequalinium / dibunate','INT'),
('dequalinium / hexetidine','dequalinium / hexetidine','INT'),
('dequalinium / polidocanol / prednisolone','dequalinium / polidocanol / prednisolone','INT'),
('dequalinium / tetracaine','dequalinium / tetracaine','INT'),
('dequalinium / tyrothricin','dequalinium / tyrothricin','INT'),
('deserpidine / hydrochlorothiazide','deserpidine / hydrochlorothiazide','INT'),
('deserpidine / methyclothiazide','deserpidine / methyclothiazide','INT'),
('desloratadine / pseudoephedrine','desloratadine / pseudoephedrine','INT'),
('desogestrel / ethinyl estradiol','desogestrel / ethinyl estradiol','INT'),
('desoximetasone / salicylic acid','desoximetasone / salicylic acid','INT'),
('deutivacaftor / tezacaftor / vanzacaftor','deutivacaftor / tezacaftor / vanzacaftor','INT'),
('dexamethasone / dobesilic acid / lidocaine','dexamethasone / dobesilic acid / lidocaine','INT'),
('dexamethasone / hypromellose','dexamethasone / hypromellose','INT'),
('dexamethasone / indomethacin','dexamethasone / indomethacin','INT'),
('dexamethasone / lidocaine','dexamethasone / lidocaine','INT'),
('dexamethasone / neomycin','dexamethasone / neomycin','INT'),
('dexamethasone / neomycin / polymyxin B','dexamethasone / neomycin / polymyxin b','INT'),
('dexamethasone / neomycin / thiabendazole','dexamethasone / neomycin / thiabendazole','INT'),
('dexamethasone / oxytetracycline','dexamethasone / oxytetracycline','INT'),
('dexamethasone / phenylephrine','dexamethasone / phenylephrine','INT'),
('dexamethasone / sodium phosphate','dexamethasone / sodium phosphate','INT'),
('dexamethasone / terfenadine','dexamethasone / terfenadine','INT'),
('dexamethasone / theophylline','dexamethasone / theophylline','INT'),
('dexamethasone / tobramycin','dexamethasone / tobramycin','INT'),
('dexamethasone / tramazoline','dexamethasone / tramazoline','INT'),
('dexbrompheniramine / guaifenesin / pseudoephedrine','dexbrompheniramine / guaifenesin / pseudoephedrine','INT'),
('dexbrompheniramine / hydrocodone / phenylephrine','dexbrompheniramine / hydrocodone / phenylephrine','INT'),
('dexbrompheniramine / phenylephrine','dexbrompheniramine / phenylephrine','INT'),
('dexbrompheniramine / phenylephrine / pyrilamine','dexbrompheniramine / phenylephrine / pyrilamine','INT'),
('dexbrompheniramine / pseudoephedrine','dexbrompheniramine / pseudoephedrine','INT'),
('dexbrompheniramine / pyrilamine','dexbrompheniramine / pyrilamine','INT'),
('dexchlorpheniramine / hydrocodone / phenylephrine','dexchlorpheniramine / hydrocodone / phenylephrine','INT'),
('dexchlorpheniramine / phenylephrine','dexchlorpheniramine / phenylephrine','INT'),
('dexchlorpheniramine / pseudoephedrine','dexchlorpheniramine / pseudoephedrine','INT'),
('dexchlorpheniramine / pseudoephedrine / pyrilamine','dexchlorpheniramine / pseudoephedrine / pyrilamine','INT'),
('dexpanthenol / diphenhydramine / lidocaine','dexpanthenol / diphenhydramine / lidocaine','INT'),
('dexpanthenol / levomenthol / salicylic acid','dexpanthenol / levomenthol / salicylic acid','INT'),
('dexpanthenol / prednisolone / salicylic acid','dexpanthenol / prednisolone / salicylic acid','INT'),
('dexpanthenol / procaine','dexpanthenol / procaine','INT'),
('dexpanthenol / salicylic acid','dexpanthenol / salicylic acid','INT'),
('dexpanthenol / zinc oxide','dexpanthenol / zinc oxide','INT'),
('dextran / phenylbutazone','dextran / phenylbutazone','INT'),
('dextran / sodium chloride','dextran / sodium chloride','INT'),
('dextran 70 / glycerin / hypromellose','dextran 70 / glycerin / hypromellose','INT'),
('dextran 70 / hypromellose','dextran 70 / hypromellose','INT'),
('dextran 70 / polyethylene glycols','dextran 70 / polyethylene glycols','INT'),
('dextran 70 / sodium chloride','dextran 70 / sodium chloride','INT'),
('dextromethorphan / diphenhydramine','dextromethorphan / diphenhydramine','INT'),
('dextromethorphan / diphenhydramine / phenylephrine','dextromethorphan / diphenhydramine / phenylephrine','INT'),
('dextromethorphan / doxylamine','dextromethorphan / doxylamine','INT'),
('dextromethorphan / doxylamine / phenylephrine','dextromethorphan / doxylamine / phenylephrine','INT'),
('dextromethorphan / doxylamine / pseudoephedrine','dextromethorphan / doxylamine / pseudoephedrine','INT'),
('dextromethorphan / ephedrine','dextromethorphan / ephedrine','INT'),
('dextromethorphan / guaiacolsulfonate','dextromethorphan / guaiacolsulfonate','INT'),
('dextromethorphan / guaiacolsulfonate / guaifenesin','dextromethorphan / guaiacolsulfonate / guaifenesin','INT'),
('dextromethorphan / guaifenesin','dextromethorphan / guaifenesin','INT'),
('dextromethorphan / guaifenesin / phenylephrine','dextromethorphan / guaifenesin / phenylephrine','INT'),
('dextromethorphan / guaifenesin / pseudoephedrine','dextromethorphan / guaifenesin / pseudoephedrine','INT'),
('dextromethorphan / guaifenesin / sodium citrate','dextromethorphan / guaifenesin / sodium citrate','INT'),
('dextromethorphan / hexylresorcinol','dextromethorphan / hexylresorcinol','INT'),
('dextromethorphan / menthol','dextromethorphan / menthol','INT'),
('dextromethorphan / menthol / phenylephrine','dextromethorphan / menthol / phenylephrine','INT'),
('dextromethorphan / methoxyphenamine','dextromethorphan / methoxyphenamine','INT'),
('dextromethorphan / pheniramine / phenylephrine','dextromethorphan / pheniramine / phenylephrine','INT'),
('dextromethorphan / phenylephrine','dextromethorphan / phenylephrine','INT'),
('dextromethorphan / phenylephrine / pyrilamine','dextromethorphan / phenylephrine / pyrilamine','INT'),
('dextromethorphan / phenylephrine / sodium citrate','dextromethorphan / phenylephrine / sodium citrate','INT'),
('dextromethorphan / phenylephrine / thonzylamine','dextromethorphan / phenylephrine / thonzylamine','INT'),
('dextromethorphan / phenylephrine / triprolidine','dextromethorphan / phenylephrine / triprolidine','INT'),
('dextromethorphan / phenylpropanolamine','dextromethorphan / phenylpropanolamine','INT'),
('dextromethorphan / potassium iodide','dextromethorphan / potassium iodide','INT'),
('dextromethorphan / promethazine','dextromethorphan / promethazine','INT'),
('dextromethorphan / pseudoephedrine','dextromethorphan / pseudoephedrine','INT')
) AS v(nom, dci, pays)
WHERE NOT EXISTS (SELECT 1 FROM medicaments m WHERE LOWER(m.nom) = LOWER(v.nom));
