-- rxnorm_batch_212.sql (80 rows)
INSERT INTO medicaments (nom, dci, pays)
SELECT v.nom, v.dci, v.pays FROM (VALUES
('adefovir dipivoxil','adefovir dipivoxil','INT'),
('adenosine monophosphate','adenosine monophosphate','INT'),
('adenosine phosphate disodium','adenosine phosphate disodium','INT'),
('adenosine triphosphate disodium','adenosine triphosphate disodium','INT'),
('adipate ion','adipate ion','INT'),
('adiphenine hydrochloride','adiphenine hydrochloride','INT'),
('ado-trastuzumab emtansine','ado-trastuzumab emtansine','INT'),
('adrenalone hydrochloride','adrenalone hydrochloride','INT'),
('aducanumab-avwa','aducanumab-avwa','INT'),
('afamelanotide acetate','afamelanotide acetate','INT'),
('afatinib dimaleate','afatinib dimaleate','INT'),
('aflibercept-ayyh','aflibercept-ayyh','INT'),
('aflibercept-boav','aflibercept-boav','INT'),
('aflibercept-mrbb','aflibercept-mrbb','INT'),
('aflibercept-yszy','aflibercept-yszy','INT'),
('agatolimod sodium','agatolimod sodium','INT'),
('alanine, DL-','alanine, dl-','INT'),
('alarelin acetate','alarelin acetate','INT'),
('alatrofloxacin mesylate','alatrofloxacin mesylate','INT'),
('albumin human-kjda','albumin human-kjda','INT'),
('albumin,microsphere human serum','albumin,microsphere human serum','INT'),
('albuterol sulfate','albuterol sulfate','INT'),
('albutrepenonacog alfa','albutrepenonacog alfa','INT'),
('alclometasone dipropionate','alclometasone dipropionate','INT'),
('alcuronium chloride','alcuronium chloride','INT'),
('alectinib hydrochloride','alectinib hydrochloride','INT'),
('alendronate sodium','alendronate sodium','INT'),
('alendronic acid','alendronic acid','INT'),
('alexitol sodium','alexitol sodium','INT'),
('alfentanil hydrochloride','alfentanil hydrochloride','INT'),
('alfuzosin hydrochloride','alfuzosin hydrochloride','INT'),
('aliskiren hemifumarate','aliskiren hemifumarate','INT'),
('allantoin glycyrrhetinic acid','allantoin glycyrrhetinic acid','INT'),
('allantoin, (+)-','allantoin, (+)-','INT'),
('allergenic extract, false ragweed pollen','allergenic extract, false ragweed pollen','INT'),
('allergenic extract, pigweed, spiny, pollen','allergenic extract, pigweed, spiny, pollen','INT'),
('allo-2-hydroxycitric acid','allo-2-hydroxycitric acid','INT'),
('allogeneic processed thymus tissue-agdc','allogeneic processed thymus tissue-agdc','INT'),
('allopurinol sodium','allopurinol sodium','INT'),
('almasilate anhydrous','almasilate anhydrous','INT'),
('almitrine dimesylate','almitrine dimesylate','INT'),
('almotriptan malate','almotriptan malate','INT'),
('alogliptin benzoate','alogliptin benzoate','INT'),
('alosetron hydrochloride','alosetron hydrochloride','INT'),
('alpha 1-proteinase inhibitor, human','alpha 1-proteinase inhibitor, human','INT'),
('alpha,alpha-dibromo-d-camphor','alpha,alpha-dibromo-d-camphor','INT'),
('alpha-aminobutyric acid, L-','alpha-aminobutyric acid, l-','INT'),
('alpha-bisabolol, (+-)-','alpha-bisabolol, (+-)-','INT'),
('alpha-methylbenzyl acetate','alpha-methylbenzyl acetate','INT'),
('alpha-terpineol, (+)-','alpha-terpineol, (+)-','INT'),
('alpha-tocopherol acetate','alpha-tocopherol acetate','INT'),
('alpha-tocopherol calcium succinate, DL-','alpha-tocopherol calcium succinate, dl-','INT'),
('alpha-tocopherol linoleate, D-','alpha-tocopherol linoleate, d-','INT'),
('alpha-tocopherol succinate','alpha-tocopherol succinate','INT'),
('alpha-tocopherol succinate, D-','alpha-tocopherol succinate, d-','INT'),
('alpha-tocopherol succinate, DL-','alpha-tocopherol succinate, dl-','INT'),
('alpha-tocopherol, L-','alpha-tocopherol, l-','INT'),
('alpha-tocopheryloxyacetic acid','alpha-tocopheryloxyacetic acid','INT'),
('alphaprodine hydrochloride','alphaprodine hydrochloride','INT'),
('alprenolol hydrochloride','alprenolol hydrochloride','INT'),
('alum, ammonium anhydrous','alum, ammonium anhydrous','INT'),
('alum, potassium anhydrous','alum, potassium anhydrous','INT'),
('aluminum chloride anhydrous','aluminum chloride anhydrous','INT'),
('aluminum chloride hexahydrate','aluminum chloride hexahydrate','INT'),
('aluminum chlorohydrate anhydrous','aluminum chlorohydrate anhydrous','INT'),
('aluminum flufenamate','aluminum flufenamate','INT'),
('aluminum hydroxide gel','aluminum hydroxide gel','INT'),
('aluminum hydroxide sulfate (Al(OH)(SO4))','aluminum hydroxide sulfate (al(oh)(so4))','INT'),
('aluminum hydroxide, dried (USP)','aluminum hydroxide, dried (usp)','INT'),
('aluminum sodium silicate','aluminum sodium silicate','INT'),
('aluminum sulfate anhydrous','aluminum sulfate anhydrous','INT'),
('aluminum sulfate octadecahydrate','aluminum sulfate octadecahydrate','INT'),
('alverine citrate','alverine citrate','INT'),
('alvimopan anhydrous','alvimopan anhydrous','INT'),
('amantadine hydrochloride','amantadine hydrochloride','INT'),
('amantadine sulfate','amantadine sulfate','INT'),
('ambenonium chloride','ambenonium chloride','INT'),
('ambroxol acefyllinate','ambroxol acefyllinate','INT'),
('ambroxol hydrochloride','ambroxol hydrochloride','INT'),
('amifampridine phosphate','amifampridine phosphate','INT')
) AS v(nom, dci, pays)
WHERE NOT EXISTS (SELECT 1 FROM medicaments m WHERE LOWER(m.nom) = LOWER(v.nom));
