-- rxnorm_batch_197.sql (80 rows)
INSERT INTO medicaments (nom, dci, pays)
SELECT v.nom, v.dci, v.pays FROM (VALUES
('estradiol / estriol / norethindrone','estradiol / estriol / norethindrone','INT'),
('estradiol / estrone','estradiol / estrone','INT'),
('estradiol / ethinyl estradiol / levonorgestrel','estradiol / ethinyl estradiol / levonorgestrel','INT'),
('estradiol / fluprednidene','estradiol / fluprednidene','INT'),
('estradiol / hexachlorophene','estradiol / hexachlorophene','INT'),
('estradiol / levonorgestrel','estradiol / levonorgestrel','INT'),
('estradiol / medroxyprogesterone','estradiol / medroxyprogesterone','INT'),
('estradiol / norethindrone','estradiol / norethindrone','INT'),
('estradiol / norethindrone / relugolix','estradiol / norethindrone / relugolix','INT'),
('estradiol / norgestimate','estradiol / norgestimate','INT'),
('estradiol / oxytetracycline','estradiol / oxytetracycline','INT'),
('estradiol / prasterone','estradiol / prasterone','INT'),
('estradiol / prednisolone','estradiol / prednisolone','INT'),
('estradiol / progesterone','estradiol / progesterone','INT'),
('estradiol / testosterone','estradiol / testosterone','INT'),
('estradiol / trenbolone','estradiol / trenbolone','INT'),
('estradiol / tyrothricin','estradiol / tyrothricin','INT'),
('estriol / Lactobacillus acidophilus','estriol / lactobacillus acidophilus','INT'),
('estriol / thymol / urea','estriol / thymol / urea','INT'),
('estrogens / testosterone','estrogens / testosterone','INT'),
('estrogens, conjugated (USP) / estrone','estrogens, conjugated (usp) / estrone','INT'),
('estrogens, conjugated (USP) / medrogestone','estrogens, conjugated (usp) / medrogestone','INT'),
('estrogens, conjugated (USP) / medroxyprogesterone','estrogens, conjugated (usp) / medroxyprogesterone','INT'),
('estrogens, conjugated (USP) / meprobamate','estrogens, conjugated (usp) / meprobamate','INT'),
('estrogens, conjugated (USP) / norgestrel','estrogens, conjugated (usp) / norgestrel','INT'),
('estrogens, conjugated (USP) / phenobarbital','estrogens, conjugated (usp) / phenobarbital','INT'),
('estrone / progesterone','estrone / progesterone','INT'),
('estrone / testosterone','estrone / testosterone','INT'),
('estropipate / medroxyprogesterone','estropipate / medroxyprogesterone','INT'),
('ethacridine / lidocaine','ethacridine / lidocaine','INT'),
('ethambutol / isoniazid','ethambutol / isoniazid','INT'),
('ethambutol / isoniazid / rifampin','ethambutol / isoniazid / rifampin','INT'),
('ethamivan / etofylline / hexobendine','ethamivan / etofylline / hexobendine','INT'),
('ethamivan / heptaminol / norfenefrine','ethamivan / heptaminol / norfenefrine','INT'),
('ethamivan / hexobendine','ethamivan / hexobendine','INT'),
('ethanol / glucose','ethanol / glucose','INT'),
('ethanol / hydrogen peroxide','ethanol / hydrogen peroxide','INT'),
('ethanol / iodine / sodium iodide','ethanol / iodine / sodium iodide','INT'),
('ethanol / isopropyl alcohol','ethanol / isopropyl alcohol','INT'),
('ethanol / isopropyl alcohol / povidone-iodine','ethanol / isopropyl alcohol / povidone-iodine','INT'),
('ethanol / lidocaine','ethanol / lidocaine','INT'),
('ethanol / menthol','ethanol / menthol','INT'),
('ethanol / povidone-iodine','ethanol / povidone-iodine','INT'),
('ethanol / resorcinol','ethanol / resorcinol','INT'),
('ethanol / resorcinol / sulfur','ethanol / resorcinol / sulfur','INT'),
('ethanol / salicylic acid','ethanol / salicylic acid','INT'),
('ethanol / sulfur / zinc oxide / zinc sulfate','ethanol / sulfur / zinc oxide / zinc sulfate','INT'),
('ethanol / triclosan','ethanol / triclosan','INT'),
('ethanolamine / framycetin','ethanolamine / framycetin','INT'),
('ethinyl estradiol / ethisterone','ethinyl estradiol / ethisterone','INT'),
('ethinyl estradiol / ethynodiol','ethinyl estradiol / ethynodiol','INT'),
('ethinyl estradiol / etonogestrel','ethinyl estradiol / etonogestrel','INT'),
('ethinyl estradiol / fluoxymesterone','ethinyl estradiol / fluoxymesterone','INT'),
('ethinyl estradiol / gestodene','ethinyl estradiol / gestodene','INT'),
('ethinyl estradiol / levonorgestrel','ethinyl estradiol / levonorgestrel','INT'),
('ethinyl estradiol / lynestrenol','ethinyl estradiol / lynestrenol','INT'),
('ethinyl estradiol / norelgestromin','ethinyl estradiol / norelgestromin','INT'),
('ethinyl estradiol / norethindrone','ethinyl estradiol / norethindrone','INT'),
('ethinyl estradiol / norgestimate','ethinyl estradiol / norgestimate','INT'),
('ethinyl estradiol / norgestrel','ethinyl estradiol / norgestrel','INT'),
('ethinyl estradiol / norgestrienone','ethinyl estradiol / norgestrienone','INT'),
('ethinyl estradiol / segesterone','ethinyl estradiol / segesterone','INT'),
('ethosuximide / quinacrine','ethosuximide / quinacrine','INT'),
('ethyl hexyl salicylate / titanium dioxide','ethyl hexyl salicylate / titanium dioxide','INT'),
('ethylmorphine / terpin hydrate','ethylmorphine / terpin hydrate','INT'),
('ethynodiol / mestranol','ethynodiol / mestranol','INT'),
('ethynodiol / quinestrol','ethynodiol / quinestrol','INT'),
('etofenamate / niacin','etofenamate / niacin','INT'),
('etofylline / theophylline','etofylline / theophylline','INT'),
('eucalyptol / guaiacol ethylglycolate','eucalyptol / guaiacol ethylglycolate','INT'),
('eucalyptol / menthol / sodium fluoride / thymol','eucalyptol / menthol / sodium fluoride / thymol','INT'),
('eucalyptol / thymol','eucalyptol / thymol','INT'),
('Eucalyptus oil / menthol','eucalyptus oil / menthol','INT'),
('Eucalyptus oil / tea tree oil','eucalyptus oil / tea tree oil','INT'),
('eugenol / guaiacol','eugenol / guaiacol','INT'),
('evening primrose oil / gamma linoleic acid','evening primrose oil / gamma linoleic acid','INT'),
('evening primrose oil / gamma-linolenate','evening primrose oil / gamma-linolenate','INT'),
('evening primrose oil / linoleate','evening primrose oil / linoleate','INT'),
('ezetimibe / rosuvastatin','ezetimibe / rosuvastatin','INT'),
('ezetimibe / simvastatin','ezetimibe / simvastatin','INT')
) AS v(nom, dci, pays)
WHERE NOT EXISTS (SELECT 1 FROM medicaments m WHERE LOWER(m.nom) = LOWER(v.nom));
