-- rxnorm_batch_032.sql (80 rows)
INSERT INTO medicaments (nom, dci, pays)
SELECT v.nom, v.dci, v.pays FROM (VALUES
('calcium bromide','calcium bromide','INT'),
('calcium carbimide','calcium carbimide','INT'),
('calcium carbonate','calcium carbonate','INT'),
('calcium carbonate, precipitated','calcium carbonate, precipitated','INT'),
('calcium chlorate dihydrate','calcium chlorate dihydrate','INT'),
('calcium chloride','calcium chloride','INT'),
('calcium citrate','calcium citrate','INT'),
('calcium citrate malate','calcium citrate malate','INT'),
('calcium creosotate','calcium creosotate','INT'),
('calcium fluoride','calcium fluoride','INT'),
('calcium fructoborate','calcium fructoborate','INT'),
('calcium galactogluconate bromide','calcium galactogluconate bromide','INT'),
('calcium glubionate','calcium glubionate','INT'),
('calcium glucarate','calcium glucarate','INT'),
('calcium gluceptate','calcium gluceptate','INT'),
('calcium gluconate','calcium gluconate','INT'),
('calcium glycerophosphate','calcium glycerophosphate','INT'),
('calcium hexafluorosilicate','calcium hexafluorosilicate','INT'),
('calcium hydride','calcium hydride','INT'),
('calcium hydroxide','calcium hydroxide','INT'),
('calcium hypophosphite','calcium hypophosphite','INT'),
('calcium iodide','calcium iodide','INT'),
('calcium iodized','calcium iodized','INT'),
('calcium ion','calcium ion','INT'),
('calcium lactate','calcium lactate','INT'),
('calcium lactobionate','calcium lactobionate','INT'),
('calcium levulinate','calcium levulinate','INT'),
('calcium malate','calcium malate','INT'),
('calcium monofluorophosphate','calcium monofluorophosphate','INT'),
('calcium orotate','calcium orotate','INT'),
('calcium oxalate','calcium oxalate','INT'),
('calcium oxide','calcium oxide','INT'),
('calcium oxoglurate','calcium oxoglurate','INT'),
('calcium peroxide','calcium peroxide','INT'),
('calcium phenoxide','calcium phenoxide','INT'),
('calcium phosphate','calcium phosphate','INT'),
('calcium polycarbophil','calcium polycarbophil','INT'),
('calcium polystyrene sulfonate product','calcium polystyrene sulfonate product','INT'),
('calcium polysulfide','calcium polysulfide','INT'),
('calcium pyrophosphate','calcium pyrophosphate','INT'),
('calcium pyruvate','calcium pyruvate','INT'),
('calcium saccharate','calcium saccharate','INT'),
('calcium silicate','calcium silicate','INT'),
('calcium stearate','calcium stearate','INT'),
('calcium sulfaloxate','calcium sulfaloxate','INT'),
('calcium sulfate','calcium sulfate','INT'),
('calcium sulfide','calcium sulfide','INT'),
('calcium threonate','calcium threonate','INT'),
('calcobutrol','calcobutrol','INT'),
('caldiamide','caldiamide','INT'),
('Calendula arvensis leaf extract','calendula arvensis leaf extract','INT'),
('Calendula arvensis whole extract','calendula arvensis whole extract','INT'),
('Calendula officinalis extract','calendula officinalis extract','INT'),
('Calendula officinalis flower extract','calendula officinalis flower extract','INT'),
('Calendula officinalis flowering top extract','calendula officinalis flowering top extract','INT'),
('Calendula officinalis seed oil','calendula officinalis seed oil','INT'),
('Calendula officinalis whole extract','calendula officinalis whole extract','INT'),
('calenduladiol','calenduladiol','INT'),
('calenduloside E','calenduloside e','INT'),
('calfactant','calfactant','INT'),
('California black oak pollen extract','california black oak pollen extract','INT'),
('California black walnut pollen extract','california black walnut pollen extract','INT'),
('California blackberry extract','california blackberry extract','INT'),
('California juniper pollen extract','california juniper pollen extract','INT'),
('California mugwort pollen extract','california mugwort pollen extract','INT'),
('California scrub oak pollen extract','california scrub oak pollen extract','INT'),
('California sheephead preparation','california sheephead preparation','INT'),
('californium','californium','INT'),
('Callicarpa japonica fruit extract','callicarpa japonica fruit extract','INT'),
('Callicarpa nudiflora leaf extract','callicarpa nudiflora leaf extract','INT'),
('Callistemon citrinus pollen extract','callistemon citrinus pollen extract','INT'),
('Callitris columellaris wood oil','callitris columellaris wood oil','INT'),
('Calluna vulgaris flowering top extract','calluna vulgaris flowering top extract','INT'),
('Calluna vulgaris whole extract','calluna vulgaris whole extract','INT'),
('Calocedrus decurrens pollen extract','calocedrus decurrens pollen extract','INT'),
('Calochortus gunnisonii whole extract','calochortus gunnisonii whole extract','INT'),
('Calochortus tolmiei whole extract','calochortus tolmiei whole extract','INT'),
('calomel','calomel','INT'),
('Calophyllum inophyllum leaf extract','calophyllum inophyllum leaf extract','INT'),
('Calophyllum inophyllum whole extract','calophyllum inophyllum whole extract','INT')
) AS v(nom, dci, pays)
WHERE NOT EXISTS (SELECT 1 FROM medicaments m WHERE LOWER(m.nom) = LOWER(v.nom));
