-- rxnorm_batch_091.sql (80 rows)
INSERT INTO medicaments (nom, dci, pays)
SELECT v.nom, v.dci, v.pays FROM (VALUES
('L1 protein, human papillomavirus type 45 vaccine','l1 protein, human papillomavirus type 45 vaccine','INT'),
('L1 protein, human papillomavirus type 52 vaccine','l1 protein, human papillomavirus type 52 vaccine','INT'),
('L1 protein, human papillomavirus type 58 vaccine','l1 protein, human papillomavirus type 58 vaccine','INT'),
('L1 protein, human papillomavirus type 6 vaccine','l1 protein, human papillomavirus type 6 vaccine','INT'),
('labdanum oil','labdanum oil','INT'),
('labetalol','labetalol','INT'),
('Laburnum anagyroides flowering top extract','laburnum anagyroides flowering top extract','INT'),
('Laccocephalum mylittae whole extract','laccocephalum mylittae whole extract','INT'),
('lachesine','lachesine','INT'),
('Lachesis muta venom','lachesis muta venom','INT'),
('Lachesis muta whole extract','lachesis muta whole extract','INT'),
('Lachnanthes caroliniana extract','lachnanthes caroliniana extract','INT'),
('lacidipine','lacidipine','INT'),
('lacosamide','lacosamide','INT'),
('Lactarius indigo whole extract','lactarius indigo whole extract','INT'),
('Lactarius rubidus whole extract','lactarius rubidus whole extract','INT'),
('lactase','lactase','INT'),
('lactate','lactate','INT'),
('lactic acid lactate, DL-','lactic acid lactate, dl-','INT'),
('lactic acid lactate, L-','lactic acid lactate, l-','INT'),
('Lacticaseibacillus casei','lacticaseibacillus casei','INT'),
('Lacticaseibacillus paracasei','lacticaseibacillus paracasei','INT'),
('Lacticaseibacillus rhamnosus','lacticaseibacillus rhamnosus','INT'),
('lactide, DL-','lactide, dl-','INT'),
('Lactiplantibacillus plantarum','lactiplantibacillus plantarum','INT'),
('lactitol','lactitol','INT'),
('lacto-N-neotetraose','lacto-n-neotetraose','INT'),
('lactobacillic acid','lactobacillic acid','INT'),
('Lactobacillus acidophilus','lactobacillus acidophilus','INT'),
('Lactobacillus bifidus','lactobacillus bifidus','INT'),
('Lactobacillus crispatus','lactobacillus crispatus','INT'),
('Lactobacillus delbrueckii subsp. bulgaricus','lactobacillus delbrueckii subsp. bulgaricus','INT'),
('Lactobacillus gasseri','lactobacillus gasseri','INT'),
('Lactobacillus helveticus','lactobacillus helveticus','INT'),
('lactobionate','lactobionate','INT'),
('Lactococcus lactis','lactococcus lactis','INT'),
('lactococcus lactis immunoserum rabbit','lactococcus lactis immunoserum rabbit','INT'),
('lactoferrin','lactoferrin','INT'),
('lactoferrin (synthetic human)','lactoferrin (synthetic human)','INT'),
('lactoperoxidase','lactoperoxidase','INT'),
('lactose','lactose','INT'),
('Lactuca indica whole extract','lactuca indica whole extract','INT'),
('Lactuca virosa extract','lactuca virosa extract','INT'),
('Lactuca virosa leaf extract','lactuca virosa leaf extract','INT'),
('lactulose','lactulose','INT'),
('Lagerstroemia indica extract','lagerstroemia indica extract','INT'),
('Lagerstroemia speciosa leaf extract','lagerstroemia speciosa leaf extract','INT'),
('Lagerstroemia speciosa whole extract','lagerstroemia speciosa whole extract','INT'),
('laidlomycin','laidlomycin','INT'),
('laidlomycin propionate','laidlomycin propionate','INT'),
('lamb allergenic extract','lamb allergenic extract','INT'),
('lamb preparation','lamb preparation','INT'),
('lambs quarters pollen extract','lambs quarters pollen extract','INT'),
('Laminaria angustata extract','laminaria angustata extract','INT'),
('Laminaria digitata hydrolized alginic acid','laminaria digitata hydrolized alginic acid','INT'),
('Laminaria digitata preparation','laminaria digitata preparation','INT'),
('Laminaria hyperborea extract','laminaria hyperborea extract','INT'),
('Laminaria japonica extract','laminaria japonica extract','INT'),
('Laminaria ochroleuca extract','laminaria ochroleuca extract','INT'),
('Lamium album extract','lamium album extract','INT'),
('Lamium album flower extract','lamium album flower extract','INT'),
('Lamium album flowering top extract','lamium album flowering top extract','INT'),
('lamivudine','lamivudine','INT'),
('lamotrigine','lamotrigine','INT'),
('Lamprocapnos spectabilis flower extract','lamprocapnos spectabilis flower extract','INT'),
('lanadelumab','lanadelumab','INT'),
('lanatoside C','lanatoside c','INT'),
('landiolol','landiolol','INT'),
('laneth-75','laneth-75','INT'),
('lanolin','lanolin','INT'),
('lanolin acid','lanolin acid','INT'),
('lanolin alcohols','lanolin alcohols','INT'),
('lanolin oil','lanolin oil','INT'),
('lanosterol','lanosterol','INT'),
('lanreotide','lanreotide','INT'),
('lansoprazole','lansoprazole','INT'),
('Lantana camara leaf extract','lantana camara leaf extract','INT'),
('Lantana camara leaf volatile oil','lantana camara leaf volatile oil','INT'),
('lanthanum','lanthanum','INT'),
('lanthanum carbonate','lanthanum carbonate','INT')
) AS v(nom, dci, pays)
WHERE NOT EXISTS (SELECT 1 FROM medicaments m WHERE LOWER(m.nom) = LOWER(v.nom));
