-- rxnorm_batch_173.sql (80 rows)
INSERT INTO medicaments (nom, dci, pays)
SELECT v.nom, v.dci, v.pays FROM (VALUES
('acetaminophen / dextromethorphan / triprolidine','acetaminophen / dextromethorphan / triprolidine','INT'),
('acetaminophen / dichloralphenazone / isometheptene','acetaminophen / dichloralphenazone / isometheptene','INT'),
('acetaminophen / diclofenac','acetaminophen / diclofenac','INT'),
('acetaminophen / dihydrocodeine','acetaminophen / dihydrocodeine','INT'),
('acetaminophen / dihydrocodeine / salicylamide','acetaminophen / dihydrocodeine / salicylamide','INT'),
('acetaminophen / dihydroergotamine','acetaminophen / dihydroergotamine','INT'),
('acetaminophen / dimenhydrinate','acetaminophen / dimenhydrinate','INT'),
('acetaminophen / diphenhydramine','acetaminophen / diphenhydramine','INT'),
('acetaminophen / diphenhydramine / phenylephrine','acetaminophen / diphenhydramine / phenylephrine','INT'),
('acetaminophen / diphenhydramine / pseudoephedrine','acetaminophen / diphenhydramine / pseudoephedrine','INT'),
('acetaminophen / dipyrone','acetaminophen / dipyrone','INT'),
('acetaminophen / domperidone','acetaminophen / domperidone','INT'),
('acetaminophen / doxylamine','acetaminophen / doxylamine','INT'),
('acetaminophen / doxylamine / phenylephrine','acetaminophen / doxylamine / phenylephrine','INT'),
('acetaminophen / doxylamine / pseudoephedrine','acetaminophen / doxylamine / pseudoephedrine','INT'),
('acetaminophen / doxylamine / salicylamide','acetaminophen / doxylamine / salicylamide','INT'),
('acetaminophen / ephedrine / guaifenesin','acetaminophen / ephedrine / guaifenesin','INT'),
('acetaminophen / fursultiamin','acetaminophen / fursultiamin','INT'),
('acetaminophen / guaifenesin','acetaminophen / guaifenesin','INT'),
('acetaminophen / guaifenesin / phenylephrine','acetaminophen / guaifenesin / phenylephrine','INT'),
('acetaminophen / guaifenesin / pseudoephedrine','acetaminophen / guaifenesin / pseudoephedrine','INT'),
('acetaminophen / hydrocodone','acetaminophen / hydrocodone','INT'),
('acetaminophen / ibuprofen','acetaminophen / ibuprofen','INT'),
('acetaminophen / isometheptene','acetaminophen / isometheptene','INT'),
('acetaminophen / ketoprofen','acetaminophen / ketoprofen','INT'),
('acetaminophen / loratadine / pseudoephedrine','acetaminophen / loratadine / pseudoephedrine','INT'),
('acetaminophen / magnesium salicylate','acetaminophen / magnesium salicylate','INT'),
('acetaminophen / magnesium salicylate / pamabrom','acetaminophen / magnesium salicylate / pamabrom','INT'),
('acetaminophen / melatonin','acetaminophen / melatonin','INT'),
('acetaminophen / meperidine','acetaminophen / meperidine','INT'),
('acetaminophen / mephenesin','acetaminophen / mephenesin','INT'),
('acetaminophen / meprobamate','acetaminophen / meprobamate','INT'),
('acetaminophen / methionine','acetaminophen / methionine','INT'),
('acetaminophen / methocarbamol','acetaminophen / methocarbamol','INT'),
('acetaminophen / metoclopramide','acetaminophen / metoclopramide','INT'),
('acetaminophen / naproxen','acetaminophen / naproxen','INT'),
('acetaminophen / orphenadrine','acetaminophen / orphenadrine','INT'),
('acetaminophen / oxycodone','acetaminophen / oxycodone','INT'),
('acetaminophen / pamabrom','acetaminophen / pamabrom','INT'),
('acetaminophen / pamabrom / pyrilamine','acetaminophen / pamabrom / pyrilamine','INT'),
('acetaminophen / pamabrom / vitamin B6','acetaminophen / pamabrom / vitamin b6','INT'),
('acetaminophen / pamabrom / vitamin E','acetaminophen / pamabrom / vitamin e','INT'),
('acetaminophen / pentazocine','acetaminophen / pentazocine','INT'),
('acetaminophen / pheniramine / phenylephrine','acetaminophen / pheniramine / phenylephrine','INT'),
('acetaminophen / phenobarbital','acetaminophen / phenobarbital','INT'),
('acetaminophen / phenylephrine','acetaminophen / phenylephrine','INT'),
('acetaminophen / phenylephrine / pyrilamine','acetaminophen / phenylephrine / pyrilamine','INT'),
('acetaminophen / phenylpropanolamine','acetaminophen / phenylpropanolamine','INT'),
('acetaminophen / phenyltoloxamine','acetaminophen / phenyltoloxamine','INT'),
('acetaminophen / phenyltoloxamine / salicylamide','acetaminophen / phenyltoloxamine / salicylamide','INT'),
('acetaminophen / piroxicam','acetaminophen / piroxicam','INT'),
('acetaminophen / promethazine','acetaminophen / promethazine','INT'),
('acetaminophen / propoxyphene','acetaminophen / propoxyphene','INT'),
('acetaminophen / propyphenazone','acetaminophen / propyphenazone','INT'),
('acetaminophen / pseudoephedrine','acetaminophen / pseudoephedrine','INT'),
('acetaminophen / pseudoephedrine / triprolidine','acetaminophen / pseudoephedrine / triprolidine','INT'),
('acetaminophen / pyrilamine','acetaminophen / pyrilamine','INT'),
('acetaminophen / racemethionine','acetaminophen / racemethionine','INT'),
('acetaminophen / salicylamide','acetaminophen / salicylamide','INT'),
('acetaminophen / salicylic acid','acetaminophen / salicylic acid','INT'),
('acetaminophen / scopolamine','acetaminophen / scopolamine','INT'),
('acetaminophen / styramate','acetaminophen / styramate','INT'),
('acetaminophen / thiamine','acetaminophen / thiamine','INT'),
('acetaminophen / thiocolchicoside','acetaminophen / thiocolchicoside','INT'),
('acetaminophen / tolperisone','acetaminophen / tolperisone','INT'),
('acetaminophen / tramadol','acetaminophen / tramadol','INT'),
('acetanilide / aspirin / caffeine / ephedrine','acetanilide / aspirin / caffeine / ephedrine','INT'),
('acetiamine / aspirin','acetiamine / aspirin','INT'),
('acetic acid / aluminum acetate','acetic acid / aluminum acetate','INT'),
('acetic acid / aluminum sulfate','acetic acid / aluminum sulfate','INT'),
('acetic acid / antipyrine / benzocaine','acetic acid / antipyrine / benzocaine','INT'),
('acetic acid / benzoate','acetic acid / benzoate','INT'),
('acetic acid / benzocaine','acetic acid / benzocaine','INT'),
('acetic acid / chlorhexidine / ketoconazole','acetic acid / chlorhexidine / ketoconazole','INT'),
('acetic acid / desonide','acetic acid / desonide','INT'),
('acetic acid / hydrocortisone','acetic acid / hydrocortisone','INT'),
('acetic acid / oxyquinoline','acetic acid / oxyquinoline','INT'),
('acetic acid / oxyquinoline / ricinoleate','acetic acid / oxyquinoline / ricinoleate','INT'),
('acetic acid / pyrethrins','acetic acid / pyrethrins','INT'),
('acetic acid / salicylic acid','acetic acid / salicylic acid','INT')
) AS v(nom, dci, pays)
WHERE NOT EXISTS (SELECT 1 FROM medicaments m WHERE LOWER(m.nom) = LOWER(v.nom));
