-- rxnorm_batch_008.sql (80 rows)
INSERT INTO medicaments (nom, dci, pays)
SELECT v.nom, v.dci, v.pays FROM (VALUES
('ACV tripeptide','acv tripeptide','INT'),
('acyclovir','acyclovir','INT'),
('adagrasib','adagrasib','INT'),
('adalimumab','adalimumab','INT'),
('ADAMTS13, recombinant','adamts13, recombinant','INT'),
('Adansonia digiata whole extract','adansonia digiata whole extract','INT'),
('Adansonia digitata fruit extract','adansonia digitata fruit extract','INT'),
('Adansonia digitata fruit pulp extract','adansonia digitata fruit pulp extract','INT'),
('Adansonia digitata leaf extract','adansonia digitata leaf extract','INT'),
('Adansonia digitata seed extract','adansonia digitata seed extract','INT'),
('Adansonia digitata seed oil','adansonia digitata seed oil','INT'),
('adapalene','adapalene','INT'),
('adefovir','adefovir','INT'),
('adenine','adenine','INT'),
('Adenium obesum whole extract','adenium obesum whole extract','INT'),
('Adenophora stricta root extract','adenophora stricta root extract','INT'),
('adenosine','adenosine','INT'),
('adenosine triphosphate','adenosine triphosphate','INT'),
('adenovirus type 4 vaccine live','adenovirus type 4 vaccine live','INT'),
('adenovirus type 7 vaccine live','adenovirus type 7 vaccine live','INT'),
('Adiantum capillus-veneris leaf extract','adiantum capillus-veneris leaf extract','INT'),
('adiastatic barley malt extract','adiastatic barley malt extract','INT'),
('Adina rubella root extract','adina rubella root extract','INT'),
('Adina rubella whole extract','adina rubella whole extract','INT'),
('adiphenine','adiphenine','INT'),
('adipic acid','adipic acid','INT'),
('Adonis vernalis extract','adonis vernalis extract','INT'),
('Adonis vernalis flowering top extract','adonis vernalis flowering top extract','INT'),
('adrafinil','adrafinil','INT'),
('adrenal cortex extract','adrenal cortex extract','INT'),
('adrenalone','adrenalone','INT'),
('adrenocorticotropin (ACTH 1-18),I-125 (TYR)','adrenocorticotropin (acth 1-18),i-125 (tyr)','INT'),
('aducanumab','aducanumab','INT'),
('advantame','advantame','INT'),
('adzuki bean extract','adzuki bean extract','INT'),
('Aesculus carnea flower extract','aesculus carnea flower extract','INT'),
('Aesculus carnea whole extract','aesculus carnea whole extract','INT'),
('Aesculus chinensis whole extract','aesculus chinensis whole extract','INT'),
('Aesculus glabra nut extract','aesculus glabra nut extract','INT'),
('Aesculus hippocastanum bark extract','aesculus hippocastanum bark extract','INT'),
('Aesculus hippocastanum flower extract','aesculus hippocastanum flower extract','INT'),
('Aesculus hippocastanum leaf extract','aesculus hippocastanum leaf extract','INT'),
('Aesculus hippocastanum seed oil','aesculus hippocastanum seed oil','INT'),
('Aethusa cynapium extract','aethusa cynapium extract','INT'),
('afamelanotide','afamelanotide','INT'),
('afamitresgene autoleucel','afamitresgene autoleucel','INT'),
('afatinib','afatinib','INT'),
('aficamten','aficamten','INT'),
('aflatoxin B1','aflatoxin b1','INT'),
('aflibercept','aflibercept','INT'),
('afoxolaner','afoxolaner','INT'),
('Aframomum angustifolium seed extract','aframomum angustifolium seed extract','INT'),
('African Pygeum extract','african pygeum extract','INT'),
('agalsidase alfa','agalsidase alfa','INT'),
('agalsidase beta','agalsidase beta','INT'),
('agar','agar','INT'),
('agaric acid','agaric acid','INT'),
('Agaricus bisporus whole extract','agaricus bisporus whole extract','INT'),
('Agaricus blazei whole extract','agaricus blazei whole extract','INT'),
('Agaricus campestris var. campestris whole extract','agaricus campestris var. campestris whole extract','INT'),
('Agaricus subrufescens extract','agaricus subrufescens extract','INT'),
('Agarum clathratum extract','agarum clathratum extract','INT'),
('Agastache foeniculum whole extract','agastache foeniculum whole extract','INT'),
('Agastache rugosa whole extract','agastache rugosa whole extract','INT'),
('Agastache urticifolia whole extract','agastache urticifolia whole extract','INT'),
('Agathosma betulina leaf extract','agathosma betulina leaf extract','INT'),
('Agathosma betulina leaf oil','agathosma betulina leaf oil','INT'),
('Agathosma crenulata leaf extract','agathosma crenulata leaf extract','INT'),
('Agathosma crenulata whole extract','agathosma crenulata whole extract','INT'),
('agatolimod','agatolimod','INT'),
('Agave americana leaf extract','agave americana leaf extract','INT'),
('Agave americana whole extract','agave americana whole extract','INT'),
('Agave atrovirens top extract','agave atrovirens top extract','INT'),
('Agave polianthes flower wax','agave polianthes flower wax','INT'),
('Agave tequilana inulin','agave tequilana inulin','INT'),
('Agave tequilana juice','agave tequilana juice','INT'),
('Agave tequilana leaf extract','agave tequilana leaf extract','INT'),
('Agave tequilana stem extract','agave tequilana stem extract','INT'),
('Agave tequilana top extract','agave tequilana top extract','INT'),
('Ageratina herbacea whole extract','ageratina herbacea whole extract','INT')
) AS v(nom, dci, pays)
WHERE NOT EXISTS (SELECT 1 FROM medicaments m WHERE LOWER(m.nom) = LOWER(v.nom));
