-- rxnorm_batch_003.sql (80 rows)
INSERT INTO medicaments (nom, dci, pays)
SELECT v.nom, v.dci, v.pays FROM (VALUES
('2,5-piperazinedione','2,5-piperazinedione','INT'),
('2,6,10-trimethyl-9-undecenal','2,6,10-trimethyl-9-undecenal','INT'),
('2,6-di-tert-butyl-4-methoxyphenol','2,6-di-tert-butyl-4-methoxyphenol','INT'),
('2,6-dimethyl-5-heptenal','2,6-dimethyl-5-heptenal','INT'),
('2,6-dimethyloctan-2-ol','2,6-dimethyloctan-2-ol','INT'),
('2-(cyclohexylamino)ethanesulfonic acid','2-(cyclohexylamino)ethanesulfonic acid','INT'),
('2-(dibutylamino)ethyl methacrylate','2-(dibutylamino)ethyl methacrylate','INT'),
('2-(dipropylamino)ethanol','2-(dipropylamino)ethanol','INT'),
('2-(L-menthoxy)ethanol','2-(l-menthoxy)ethanol','INT'),
('2-(methylamino)ethanol','2-(methylamino)ethanol','INT'),
('2-(MPEG 2000)-N,N-ditetradecylacetamide','2-(mpeg 2000)-n,n-ditetradecylacetamide','INT'),
('2-(N-morpholino)ethanesulfonic acid','2-(n-morpholino)ethanesulfonic acid','INT'),
('2-(perfluorohexyl)ethanethiol','2-(perfluorohexyl)ethanethiol','INT'),
('2-(perfluorohexyl)ethanol','2-(perfluorohexyl)ethanol','INT'),
('2-(phosphonooxy)- 2-propenoate','2-(phosphonooxy)- 2-propenoate','INT'),
('2-acetonaphthone','2-acetonaphthone','INT'),
('2-acetoxy-1, 8-cineole, (+)-endo-','2-acetoxy-1, 8-cineole, (+)-endo-','INT'),
('2-amino-1,3-propanediol','2-amino-1,3-propanediol','INT'),
('2-amino-1-butanol','2-amino-1-butanol','INT'),
('2-amino-2-ethyl-1,3-propanediol','2-amino-2-ethyl-1,3-propanediol','INT'),
('2-amino-2-methyl-1-propanol','2-amino-2-methyl-1-propanol','INT'),
('2-amino-5-nitrothiazole','2-amino-5-nitrothiazole','INT'),
('2-aminophenol','2-aminophenol','INT'),
('2-azetidinecarboxylic acid, (+)-','2-azetidinecarboxylic acid, (+)-','INT'),
('2-benzylheptanol','2-benzylheptanol','INT'),
('2-bromo-2-methylpropane','2-bromo-2-methylpropane','INT'),
('2-bromo-2-nitroethanol','2-bromo-2-nitroethanol','INT'),
('2-bromobutane','2-bromobutane','INT'),
('2-butanoyloxybenzoate','2-butanoyloxybenzoate','INT'),
('2-butoxyethanol','2-butoxyethanol','INT'),
('2-butylaminoethanol','2-butylaminoethanol','INT'),
('2-butyloctyl methacrylate','2-butyloctyl methacrylate','INT'),
('2-carboxyethyl acrylate','2-carboxyethyl acrylate','INT'),
('2-chloro-4,5-dimethylphenol','2-chloro-4,5-dimethylphenol','INT'),
('2-deoxyglucose','2-deoxyglucose','INT'),
('2-diethylaminoethanol','2-diethylaminoethanol','INT'),
('2-ethoxyethanol','2-ethoxyethanol','INT'),
('2-ethyl-1,6-hexanediol','2-ethyl-1,6-hexanediol','INT'),
('2-ethylaminoethanol','2-ethylaminoethanol','INT'),
('2-ethylhexanoic acid','2-ethylhexanoic acid','INT'),
('2-ethylhexanol','2-ethylhexanol','INT'),
('2-ethylhexyl 4-phenylbenzophenone-2''-carboxylate','2-ethylhexyl 4-phenylbenzophenone-2''-carboxylate','INT'),
('2-ethylhexyl acrylate','2-ethylhexyl acrylate','INT'),
('2-ethylhexyl benzoate','2-ethylhexyl benzoate','INT'),
('2-ethylhexyl glycidyl ether','2-ethylhexyl glycidyl ether','INT'),
('2-ethylhexyl stearate','2-ethylhexyl stearate','INT'),
('2-glyceryl capryl ether','2-glyceryl capryl ether','INT'),
('2-hydroxyacetophenone','2-hydroxyacetophenone','INT'),
('2-hydroxydecanoate','2-hydroxydecanoate','INT'),
('2-hydroxyethyl acrylate','2-hydroxyethyl acrylate','INT'),
('2-hydroxyethyl methacrylate','2-hydroxyethyl methacrylate','INT'),
('2-hydroxypropyl methacrylate','2-hydroxypropyl methacrylate','INT'),
('2-ketogluconate','2-ketogluconate','INT'),
('2-mercaptobenzothiazole','2-mercaptobenzothiazole','INT'),
('2-mercaptoethanesulfonic acid','2-mercaptoethanesulfonic acid','INT'),
('2-methacryloyloxyethyl phosphorylcholine','2-methacryloyloxyethyl phosphorylcholine','INT'),
('2-methoxy-1-propanol','2-methoxy-1-propanol','INT'),
('2-methyl 5-cyclohexylpentanol','2-methyl 5-cyclohexylpentanol','INT'),
('2-methyl-4-isothiazolin-3-one','2-methyl-4-isothiazolin-3-one','INT'),
('2-methyl-4-phenyl-2-butanol','2-methyl-4-phenyl-2-butanol','INT'),
('2-methylbutyric acid','2-methylbutyric acid','INT'),
('2-methyllactic acid','2-methyllactic acid','INT'),
('2-methylundecanal','2-methylundecanal','INT'),
('2-n-octyl-4-isothiazolin-3-one','2-n-octyl-4-isothiazolin-3-one','INT'),
('2-naphthalenesulfonate','2-naphthalenesulfonate','INT'),
('2-nitropropane','2-nitropropane','INT'),
('2-nonylphenol','2-nonylphenol','INT'),
('2-O-ethyl ascorbic acid','2-o-ethyl ascorbic acid','INT'),
('2-octanol','2-octanol','INT'),
('2-octyl cyanoacrylate','2-octyl cyanoacrylate','INT'),
('2-octyldodecyl 5-oxo-L-prolinate','2-octyldodecyl 5-oxo-l-prolinate','INT'),
('2-oleamido-1,3,4-octadecatriyl prolinate','2-oleamido-1,3,4-octadecatriyl prolinate','INT'),
('2-phenyldodecane-p-sulfonate','2-phenyldodecane-p-sulfonate','INT'),
('2-phenylphenol','2-phenylphenol','INT'),
('2-propenoic acid, 3-hydroxypropyl ester','2-propenoic acid, 3-hydroxypropyl ester','INT'),
('2-propoxy-1-propanol','2-propoxy-1-propanol','INT'),
('2-pyrrolidone','2-pyrrolidone','INT'),
('2-sec-butyl cyclohexanone','2-sec-butyl cyclohexanone','INT'),
('2-sulfolaurate','2-sulfolaurate','INT'),
('2-sulfopalmitate','2-sulfopalmitate','INT')
) AS v(nom, dci, pays)
WHERE NOT EXISTS (SELECT 1 FROM medicaments m WHERE LOWER(m.nom) = LOWER(v.nom));
