-- rxnorm_batch_111.sql (80 rows)
INSERT INTO medicaments (nom, dci, pays)
SELECT v.nom, v.dci, v.pays FROM (VALUES
('Nelumbo nucifera leaf extract','nelumbo nucifera leaf extract','INT'),
('Nelumbo nucifera root extract','nelumbo nucifera root extract','INT'),
('Nelumbo nucifera root oil','nelumbo nucifera root oil','INT'),
('Nelumbo nucifera seed extract','nelumbo nucifera seed extract','INT'),
('Nelumbo nucifera stamen extract','nelumbo nucifera stamen extract','INT'),
('Nelumbo nucifera whole extract','nelumbo nucifera whole extract','INT'),
('nemolizumab','nemolizumab','INT'),
('neo-homosalate','neo-homosalate','INT'),
('neodymium','neodymium','INT'),
('neodymium oxide','neodymium oxide','INT'),
('neohesperidin dihydrochalcone','neohesperidin dihydrochalcone','INT'),
('neomycin','neomycin','INT'),
('neon','neon','INT'),
('neopentyl gly dcapryl-dcaprate','neopentyl gly dcapryl-dcaprate','INT'),
('neopentyl glycol','neopentyl glycol','INT'),
('neopentyl glycol dicaprate','neopentyl glycol dicaprate','INT'),
('neopentyl glycol dicaprylate-dicaprate','neopentyl glycol dicaprylate-dicaprate','INT'),
('neopentyl glycol diethylhexanoate','neopentyl glycol diethylhexanoate','INT'),
('neopentyl glycol diheptanoate','neopentyl glycol diheptanoate','INT'),
('neopentyl glycol diisostearate','neopentyl glycol diisostearate','INT'),
('Neopicrorhiza scrophulariiflora root extract','neopicrorhiza scrophulariiflora root extract','INT'),
('neostigmine','neostigmine','INT'),
('neotame','neotame','INT'),
('nepafenac','nepafenac','INT'),
('Nephelium lappaceum fruit rind extract','nephelium lappaceum fruit rind extract','INT'),
('neral','neral','INT'),
('nerandomilast','nerandomilast','INT'),
('neratinib','neratinib','INT'),
('Nereocystis luetkeana','nereocystis luetkeana','INT'),
('Nerium oleander flower','nerium oleander flower','INT'),
('Nerium oleander leaf extract','nerium oleander leaf extract','INT'),
('Nerium oleander whole extract','nerium oleander whole extract','INT'),
('nerol','nerol','INT'),
('nerolidol','nerolidol','INT'),
('nerve growth factor','nerve growth factor','INT'),
('neryl acetate','neryl acetate','INT'),
('nesiritide','nesiritide','INT'),
('netarsudil','netarsudil','INT'),
('netilmicin','netilmicin','INT'),
('nettle pollen extract','nettle pollen extract','INT'),
('netupitant','netupitant','INT'),
('Neurospora crassa allergenic extract','neurospora crassa allergenic extract','INT'),
('neurospora intermedia allergenic extract','neurospora intermedia allergenic extract','INT'),
('Neurospora sitophila allergenic extract','neurospora sitophila allergenic extract','INT'),
('neurotensin','neurotensin','INT'),
('neurotrophin 3','neurotrophin 3','INT'),
('neurotrophin 4','neurotrophin 4','INT'),
('nevirapine','nevirapine','INT'),
('new coccine','new coccine','INT'),
('New Zealand green mussel extract','new zealand green mussel extract','INT'),
('niacin','niacin','INT'),
('niacinamide','niacinamide','INT'),
('niacinamide ascorbate','niacinamide ascorbate','INT'),
('nialamide','nialamide','INT'),
('niaprazine','niaprazine','INT'),
('nicarbazin','nicarbazin','INT'),
('nicardipine','nicardipine','INT'),
('nicergoline','nicergoline','INT'),
('nickel','nickel','INT'),
('nickel acetate','nickel acetate','INT'),
('nickel carbonate hydroxide','nickel carbonate hydroxide','INT'),
('nickel cation','nickel cation','INT'),
('nickel sulfate','nickel sulfate','INT'),
('niclosamide','niclosamide','INT'),
('nicoboxil','nicoboxil','INT'),
('nicofuranose','nicofuranose','INT'),
('nicorandil','nicorandil','INT'),
('Nicotiana tabacum whole extract','nicotiana tabacum whole extract','INT'),
('nicotinamide adenine dinucleotide (NAD)','nicotinamide adenine dinucleotide (nad)','INT'),
('nicotinamide ribotide','nicotinamide ribotide','INT'),
('nicotinate ethanolamine','nicotinate ethanolamine','INT'),
('nicotine','nicotine','INT'),
('nicotine bitartrate','nicotine bitartrate','INT'),
('nicotinuric acid','nicotinuric acid','INT'),
('nicotinyl alcohol','nicotinyl alcohol','INT'),
('nifedipine','nifedipine','INT'),
('niflumic acid','niflumic acid','INT'),
('nifuratel','nifuratel','INT'),
('nifuroxazide','nifuroxazide','INT'),
('nifurpipone','nifurpipone','INT')
) AS v(nom, dci, pays)
WHERE NOT EXISTS (SELECT 1 FROM medicaments m WHERE LOWER(m.nom) = LOWER(v.nom));
