-- rxnorm_batch_132.sql (80 rows)
INSERT INTO medicaments (nom, dci, pays)
SELECT v.nom, v.dci, v.pays FROM (VALUES
('pramlintide','pramlintide','INT'),
('pramoxine','pramoxine','INT'),
('praseodymium','praseodymium','INT'),
('prasterone','prasterone','INT'),
('prasugrel','prasugrel','INT'),
('Pratia purpurascens exctract','pratia purpurascens exctract','INT'),
('Pratia purpurascens extract','pratia purpurascens extract','INT'),
('pravastatin','pravastatin','INT'),
('prazepam','prazepam','INT'),
('praziquantel','praziquantel','INT'),
('prazosin','prazosin','INT'),
('precyclemone B','precyclemone b','INT'),
('prednazoline','prednazoline','INT'),
('prednicarbate','prednicarbate','INT'),
('prednimustine','prednimustine','INT'),
('prednisolone','prednisolone','INT'),
('prednisone','prednisone','INT'),
('prednylidene','prednylidene','INT'),
('pregabalin','pregabalin','INT'),
('pregna-4,17-diene-3,16-dione','pregna-4,17-diene-3,16-dione','INT'),
('pregnenolone','pregnenolone','INT'),
('prenylamine','prenylamine','INT'),
('prenylamine lactate','prenylamine lactate','INT'),
('pretomanid','pretomanid','INT'),
('Prevotella intermedia','prevotella intermedia','INT'),
('prezatide','prezatide','INT'),
('prezatide copper','prezatide copper','INT'),
('prezatide copper acetate','prezatide copper acetate','INT'),
('prickly pear fruit extract','prickly pear fruit extract','INT'),
('pridinol','pridinol','INT'),
('prifinium','prifinium','INT'),
('prilocaine','prilocaine','INT'),
('primaquine','primaquine','INT'),
('primidone','primidone','INT'),
('Primula hendersonii whole extract','primula hendersonii whole extract','INT'),
('Primula veris extract','primula veris extract','INT'),
('Primula veris flower extract','primula veris flower extract','INT'),
('primycin','primycin','INT'),
('pristinamycin','pristinamycin','INT'),
('privet pollen extract','privet pollen extract','INT'),
('probenecid','probenecid','INT'),
('probucol','probucol','INT'),
('procainamide','procainamide','INT'),
('procaine','procaine','INT'),
('procarbazine','procarbazine','INT'),
('procaterol','procaterol','INT'),
('prochlorperazine','prochlorperazine','INT'),
('procyanidin A2','procyanidin a2','INT'),
('procyanidolic oligomer','procyanidolic oligomer','INT'),
('procyclidine','procyclidine','INT'),
('profenamine','profenamine','INT'),
('proflavine','proflavine','INT'),
('profluralin','profluralin','INT'),
('progabide','progabide','INT'),
('progesterone','progesterone','INT'),
('proglumetacin','proglumetacin','INT'),
('proglumide','proglumide','INT'),
('proguanil','proguanil','INT'),
('prolactin','prolactin','INT'),
('prolinal','prolinal','INT'),
('prolinamidoethyl imidazole','prolinamidoethyl imidazole','INT'),
('proline','proline','INT'),
('prolintane','prolintane','INT'),
('promazine','promazine','INT'),
('promegestone','promegestone','INT'),
('promestriene','promestriene','INT'),
('promethazine','promethazine','INT'),
('propafenone','propafenone','INT'),
('propamidine','propamidine','INT'),
('propane','propane','INT'),
('propanediol caprylate','propanediol caprylate','INT'),
('propanediol dicaprylate','propanediol dicaprylate','INT'),
('propanidid','propanidid','INT'),
('propantheline','propantheline','INT'),
('proparacaine','proparacaine','INT'),
('propentofylline','propentofylline','INT'),
('propicillin','propicillin','INT'),
('propinox','propinox','INT'),
('propiolactone','propiolactone','INT'),
('propiomazine','propiomazine','INT')
) AS v(nom, dci, pays)
WHERE NOT EXISTS (SELECT 1 FROM medicaments m WHERE LOWER(m.nom) = LOWER(v.nom));
