-- rxnorm_batch_217.sql (80 rows)
INSERT INTO medicaments (nom, dci, pays)
SELECT v.nom, v.dci, v.pays FROM (VALUES
('calcium dobesilate','calcium dobesilate','INT'),
('calcium formate','calcium formate','INT'),
('calcium gluconate monohydrate','calcium gluconate monohydrate','INT'),
('calcium ipodate','calcium ipodate','INT'),
('calcium lactate anhydrous','calcium lactate anhydrous','INT'),
('calcium lactate pentahydrate','calcium lactate pentahydrate','INT'),
('calcium oxalate monohydrate','calcium oxalate monohydrate','INT'),
('calcium oxybate','calcium oxybate','INT'),
('calcium palmitate','calcium palmitate','INT'),
('calcium pangamate','calcium pangamate','INT'),
('calcium pantothenate','calcium pantothenate','INT'),
('calcium pantothenate, (-)-','calcium pantothenate, (-)-','INT'),
('calcium phosphate, dihydrate','calcium phosphate, dihydrate','INT'),
('calcium phosphate, monobasic, anhydrous','calcium phosphate, monobasic, anhydrous','INT'),
('calcium picrate','calcium picrate','INT'),
('calcium pidolate','calcium pidolate','INT'),
('calcium propionate','calcium propionate','INT'),
('calcium saccharate anhydrous','calcium saccharate anhydrous','INT'),
('calcium sodium phosphate','calcium sodium phosphate','INT'),
('calcium stearoyl lactylate','calcium stearoyl lactylate','INT'),
('calcium sulfate, anhydrous','calcium sulfate, anhydrous','INT'),
('calcium sulfate, dihydrate','calcium sulfate, dihydrate','INT'),
('calcium sulfate, hemihydrate','calcium sulfate, hemihydrate','INT'),
('calcium undecylenate','calcium undecylenate','INT'),
('calcium valproate','calcium valproate','INT'),
('calcium versetamide sodium','calcium versetamide sodium','INT'),
('calcobutrol sodium','calcobutrol sodium','INT'),
('caldiamide sodium','caldiamide sodium','INT'),
('californium Cf-249','californium cf-249','INT'),
('calteridol calcium','calteridol calcium','INT'),
('camphor (natural)','camphor (natural)','INT'),
('camphor oil','camphor oil','INT'),
('camylofin bis(noramid-mes)','camylofin bis(noramid-mes)','INT'),
('camylofin hydrochloride','camylofin hydrochloride','INT'),
('canagliflozin anhydrous','canagliflozin anhydrous','INT'),
('candesartan cilexetil','candesartan cilexetil','INT'),
('cangrelor tetrasodium','cangrelor tetrasodium','INT'),
('cannabigerolic acid','cannabigerolic acid','INT'),
('canrenoate potassium','canrenoate potassium','INT'),
('caplacizumab-yhdp','caplacizumab-yhdp','INT'),
('capmatinib hydrochloride','capmatinib hydrochloride','INT'),
('capreomycin sulfate','capreomycin sulfate','INT'),
('capromorelin tartrate','capromorelin tartrate','INT'),
('captodiamine hydrochloride','captodiamine hydrochloride','INT'),
('caramiphen edisylate','caramiphen edisylate','INT'),
('carbazochrome sodium sulfonate','carbazochrome sodium sulfonate','INT'),
('carbazochrome sodium sulfonate hydrate','carbazochrome sodium sulfonate hydrate','INT'),
('carbenicillin disodium','carbenicillin disodium','INT'),
('carbenicillin indanyl sodium','carbenicillin indanyl sodium','INT'),
('carbenicillin phenyl sodium','carbenicillin phenyl sodium','INT'),
('carbenoxolone sodium','carbenoxolone sodium','INT'),
('carbetapentane citrate','carbetapentane citrate','INT'),
('carbetapentane tannate','carbetapentane tannate','INT'),
('carbidopa anhydrous','carbidopa anhydrous','INT'),
('carbinoxamine maleate','carbinoxamine maleate','INT'),
('carbinoxamine tannate','carbinoxamine tannate','INT'),
('carbocysteine lysine monohydrate','carbocysteine lysine monohydrate','INT'),
('carboprost tromethamine','carboprost tromethamine','INT'),
('carboxymethylcellulose calcium','carboxymethylcellulose calcium','INT'),
('carboxymethylcellulose sodium','carboxymethylcellulose sodium','INT'),
('cariprazine hydrochloride','cariprazine hydrochloride','INT'),
('carminic acid','carminic acid','INT'),
('carnitine chloride','carnitine chloride','INT'),
('carnitine hydrochloride, (+)-','carnitine hydrochloride, (+)-','INT'),
('carnosine hydrochloride','carnosine hydrochloride','INT'),
('carpipramine dihydrochloride','carpipramine dihydrochloride','INT'),
('carrageenan calcium','carrageenan calcium','INT'),
('carrageenan sodium','carrageenan sodium','INT'),
('carteolol hydrochloride','carteolol hydrochloride','INT'),
('carvedilol phosphate','carvedilol phosphate','INT'),
('carvone, (+)-','carvone, (+)-','INT'),
('carvone, (+-)-','carvone, (+-)-','INT'),
('caspofungin acetate','caspofungin acetate','INT'),
('castor oil fish whole','castor oil fish whole','INT'),
('cathine hydrochloride','cathine hydrochloride','INT'),
('cathine polistirex','cathine polistirex','INT'),
('cefaclor anhydrous','cefaclor anhydrous','INT'),
('cefadroxil anhydrous','cefadroxil anhydrous','INT'),
('cefadroxil hemihydrate','cefadroxil hemihydrate','INT'),
('cefadroxil hydrate','cefadroxil hydrate','INT')
) AS v(nom, dci, pays)
WHERE NOT EXISTS (SELECT 1 FROM medicaments m WHERE LOWER(m.nom) = LOWER(v.nom));
