-- rxnorm_batch_185.sql (80 rows)
INSERT INTO medicaments (nom, dci, pays)
SELECT v.nom, v.dci, v.pays FROM (VALUES
('calcium carbonate / ergocalciferol / vitamin K1','calcium carbonate / ergocalciferol / vitamin k1','INT'),
('calcium carbonate / folic acid','calcium carbonate / folic acid','INT'),
('calcium carbonate / folic acid / vitamin B complex','calcium carbonate / folic acid / vitamin b complex','INT'),
('calcium carbonate / gelatin / magnesium oxide','calcium carbonate / gelatin / magnesium oxide','INT'),
('calcium carbonate / glycine','calcium carbonate / glycine','INT'),
('calcium carbonate / kaolin','calcium carbonate / kaolin','INT'),
('calcium carbonate / magnesium carbonate','calcium carbonate / magnesium carbonate','INT'),
('calcium carbonate / magnesium chloride','calcium carbonate / magnesium chloride','INT'),
('calcium carbonate / magnesium hydroxide','calcium carbonate / magnesium hydroxide','INT'),
('calcium carbonate / magnesium oxide','calcium carbonate / magnesium oxide','INT'),
('calcium carbonate / magnesium oxide / zinc oxide','calcium carbonate / magnesium oxide / zinc oxide','INT'),
('calcium carbonate / magnesium trisilicate','calcium carbonate / magnesium trisilicate','INT'),
('calcium carbonate / monofluorophosphate','calcium carbonate / monofluorophosphate','INT'),
('calcium carbonate / pectin','calcium carbonate / pectin','INT'),
('calcium carbonate / phenobarbital','calcium carbonate / phenobarbital','INT'),
('calcium carbonate / phenytoin','calcium carbonate / phenytoin','INT'),
('calcium carbonate / potassium tartrate','calcium carbonate / potassium tartrate','INT'),
('calcium carbonate / prasterone','calcium carbonate / prasterone','INT'),
('calcium carbonate / psyllium','calcium carbonate / psyllium','INT'),
('calcium carbonate / pyroglutamate','calcium carbonate / pyroglutamate','INT'),
('calcium carbonate / risedronate','calcium carbonate / risedronate','INT'),
('calcium carbonate / simethicone','calcium carbonate / simethicone','INT'),
('calcium carbonate / sodium bicarbonate','calcium carbonate / sodium bicarbonate','INT'),
('calcium carbonate / sodium fluoride','calcium carbonate / sodium fluoride','INT'),
('calcium carbonate / soy protein isolate','calcium carbonate / soy protein isolate','INT'),
('calcium carbonate / vitamin B12','calcium carbonate / vitamin b12','INT'),
('calcium carbonate / wheat dextrin','calcium carbonate / wheat dextrin','INT'),
('calcium citrate / calcium phosphate','calcium citrate / calcium phosphate','INT'),
('calcium citrate / cholecalciferol','calcium citrate / cholecalciferol','INT'),
('calcium citrate / ergocalciferol','calcium citrate / ergocalciferol','INT'),
('calcium citrate / ergocalciferol / magnesium oxide','calcium citrate / ergocalciferol / magnesium oxide','INT'),
('calcium citrate / glutamate','calcium citrate / glutamate','INT'),
('calcium citrate / magnesium oxide / vitamin E','calcium citrate / magnesium oxide / vitamin e','INT'),
('calcium creosotate / iodine','calcium creosotate / iodine','INT'),
('calcium glubionate / calcium lactobionate','calcium glubionate / calcium lactobionate','INT'),
('calcium gluceptate / calcium gluconate','calcium gluceptate / calcium gluconate','INT'),
('calcium gluconate / calcium lactate','calcium gluconate / calcium lactate','INT'),
('calcium gluconate / calcium lactobionate','calcium gluconate / calcium lactobionate','INT'),
('calcium gluconate / calcium levulinate','calcium gluconate / calcium levulinate','INT'),
('calcium gluconate / calcium saccharate','calcium gluconate / calcium saccharate','INT'),
('calcium gluconate / niacinamide / phenobarbital','calcium gluconate / niacinamide / phenobarbital','INT'),
('calcium glycerophosphate / calcium lactate','calcium glycerophosphate / calcium lactate','INT'),
('calcium glycerophosphate / calcium levulinate','calcium glycerophosphate / calcium levulinate','INT'),
('calcium glycerophosphate / monofluorophosphate','calcium glycerophosphate / monofluorophosphate','INT'),
('calcium hydroxide / zinc oxide','calcium hydroxide / zinc oxide','INT'),
('calcium iodide / codeine','calcium iodide / codeine','INT'),
('calcium iodide / isoproterenol','calcium iodide / isoproterenol','INT'),
('calcium iodized / peptone,dried / thyroid (USP)','calcium iodized / peptone,dried / thyroid (usp)','INT'),
('calcium lactate / magnesium citrate','calcium lactate / magnesium citrate','INT'),
('calcium lactate / magnesium oxide','calcium lactate / magnesium oxide','INT'),
('calcium lactate / magnesium sulfate','calcium lactate / magnesium sulfate','INT'),
('calcium lactate / niacin','calcium lactate / niacin','INT'),
('calcium lactate / thiamine','calcium lactate / thiamine','INT'),
('calcium phosphate / cholecalciferol','calcium phosphate / cholecalciferol','INT'),
('calcium phosphate / chromium picolinate','calcium phosphate / chromium picolinate','INT'),
('calcium phosphate / gamboge','calcium phosphate / gamboge','INT'),
('calcium phosphate / melatonin','calcium phosphate / melatonin','INT'),
('calcium phosphate / phosphorus','calcium phosphate / phosphorus','INT'),
('calcium phosphate / picolinic acid','calcium phosphate / picolinic acid','INT'),
('calcium phosphate / prasterone','calcium phosphate / prasterone','INT'),
('calcium phosphate / procyanidolic oligomer','calcium phosphate / procyanidolic oligomer','INT'),
('calcium phosphate / sodium fluoride','calcium phosphate / sodium fluoride','INT'),
('calcium phosphate / vitamin B12','calcium phosphate / vitamin b12','INT'),
('calcium polycarbophil / sennosides, USP','calcium polycarbophil / sennosides, usp','INT'),
('calcium pyruvate / dihydroxyacetone','calcium pyruvate / dihydroxyacetone','INT'),
('calcium undecylenate / zinc undecylenate','calcium undecylenate / zinc undecylenate','INT'),
('camphor / capsaicin','camphor / capsaicin','INT'),
('camphor / capsaicin / menthol','camphor / capsaicin / menthol','INT'),
('camphor / Capsicum extract','camphor / capsicum extract','INT'),
('camphor / Capsicum extract / levomenthol','camphor / capsicum extract / levomenthol','INT'),
('camphor / Capsicum extract / menthol','camphor / capsicum extract / menthol','INT'),
('camphor / chloroxylenol','camphor / chloroxylenol','INT'),
('camphor / colloidal oatmeal','camphor / colloidal oatmeal','INT'),
('camphor / dimethicone / lidocaine / menthol','camphor / dimethicone / lidocaine / menthol','INT'),
('camphor / dimethicone / menthol / phenol','camphor / dimethicone / menthol / phenol','INT'),
('camphor / diphenhydramine / zinc acetate','camphor / diphenhydramine / zinc acetate','INT'),
('camphor / eucalyptol / menthol','camphor / eucalyptol / menthol','INT'),
('camphor / Eucalyptus oil / eugenol','camphor / eucalyptus oil / eugenol','INT'),
('camphor / Eucalyptus oil / menthol','camphor / eucalyptus oil / menthol','INT'),
('camphor / Eucalyptus oil / menthol / turpentine','camphor / eucalyptus oil / menthol / turpentine','INT')
) AS v(nom, dci, pays)
WHERE NOT EXISTS (SELECT 1 FROM medicaments m WHERE LOWER(m.nom) = LOWER(v.nom));
