-- rxnorm_batch_162.sql (80 rows)
INSERT INTO medicaments (nom, dci, pays)
SELECT v.nom, v.dci, v.pays FROM (VALUES
('trichlorofluoromethane','trichlorofluoromethane','INT'),
('trichlorotrifluoroethane','trichlorotrifluoroethane','INT'),
('Trichoderma harzianam extract','trichoderma harzianam extract','INT'),
('Trichoderma harzianum allergenic extract','trichoderma harzianum allergenic extract','INT'),
('Trichoderma viride allergenic extract','trichoderma viride allergenic extract','INT'),
('Tricholoma magnivelare whole extract','tricholoma magnivelare whole extract','INT'),
('Trichomonas vaginalis preparation','trichomonas vaginalis preparation','INT'),
('Trichophyton (fungus)','trichophyton (fungus)','INT'),
('Trichophyton antigen','trichophyton antigen','INT'),
('Trichophyton mentagrophytes allergenic extract','trichophyton mentagrophytes allergenic extract','INT'),
('Trichophyton mentagrophytes antigen','trichophyton mentagrophytes antigen','INT'),
('Trichophyton rubrum allergenic extract','trichophyton rubrum allergenic extract','INT'),
('Trichophyton schoenleinii allergenic extract','trichophyton schoenleinii allergenic extract','INT'),
('Trichophyton tonsurans allergenic extract','trichophyton tonsurans allergenic extract','INT'),
('Trichophyton verrucosum','trichophyton verrucosum','INT'),
('Trichosanthes cucumerina seed extract','trichosanthes cucumerina seed extract','INT'),
('Trichosanthes kirilowii fruit rind','trichosanthes kirilowii fruit rind','INT'),
('Trichosanthes kirilowii root extract','trichosanthes kirilowii root extract','INT'),
('Trichosanthes kirilowii seed extract','trichosanthes kirilowii seed extract','INT'),
('Trichosporon cutaneum allergenic extract','trichosporon cutaneum allergenic extract','INT'),
('Trichothecium roseum allergenic extract','trichothecium roseum allergenic extract','INT'),
('triclabendazole','triclabendazole','INT'),
('triclocarban','triclocarban','INT'),
('triclofos','triclofos','INT'),
('triclosan','triclosan','INT'),
('tricyclodecenyl propionate','tricyclodecenyl propionate','INT'),
('tridecane','tridecane','INT'),
('trideceth-10','trideceth-10','INT'),
('trideceth-12','trideceth-12','INT'),
('trideceth-3','trideceth-3','INT'),
('trideceth-5','trideceth-5','INT'),
('trideceth-6','trideceth-6','INT'),
('trideceth-6 phosphate','trideceth-6 phosphate','INT'),
('trideceth-8','trideceth-8','INT'),
('trideceth-9','trideceth-9','INT'),
('tridecyl alcohol','tridecyl alcohol','INT'),
('tridecyl ethyleneglycol monoether','tridecyl ethyleneglycol monoether','INT'),
('tridecyl lactate','tridecyl lactate','INT'),
('tridecyl neopentanoate','tridecyl neopentanoate','INT'),
('tridecyl salicylate','tridecyl salicylate','INT'),
('tridecyl stearate','tridecyl stearate','INT'),
('tridecyl trimellitate','tridecyl trimellitate','INT'),
('tridihexethyl','tridihexethyl','INT'),
('trientine','trientine','INT'),
('triepoxycyclohexasilane','triepoxycyclohexasilane','INT'),
('triethanaolamine phenylbenzimidazole sulfonate','triethanaolamine phenylbenzimidazole sulfonate','INT'),
('triethanolamine','triethanolamine','INT'),
('triethanolamine 2-cyclohexyl-4,6-dinitrophenolate','triethanolamine 2-cyclohexyl-4,6-dinitrophenolate','INT'),
('triethanolamine benzoate','triethanolamine benzoate','INT'),
('triethanolamine cacodylate','triethanolamine cacodylate','INT'),
('triethanolamine caproyl glutamate','triethanolamine caproyl glutamate','INT'),
('triethanolamine cocoyl glutamate','triethanolamine cocoyl glutamate','INT'),
('triethanolamine cocoyl glutaminate','triethanolamine cocoyl glutaminate','INT'),
('triethanolamine glutamate','triethanolamine glutamate','INT'),
('triethanolamine lactate','triethanolamine lactate','INT'),
('triethanolamine laurate','triethanolamine laurate','INT'),
('triethanolamine lauroyl glutamate','triethanolamine lauroyl glutamate','INT'),
('triethanolamine lauryl sulfate','triethanolamine lauryl sulfate','INT'),
('triethanolamine monododecyl ether','triethanolamine monododecyl ether','INT'),
('triethanolamine polypeptide oleate condensate','triethanolamine polypeptide oleate condensate','INT'),
('triethanolamine tris(dihydrogen phosphate)','triethanolamine tris(dihydrogen phosphate)','INT'),
('triethanolamine tristearate','triethanolamine tristearate','INT'),
('triethenylmethylsilane','triethenylmethylsilane','INT'),
('triethoxysilane','triethoxysilane','INT'),
('triethoxysilylpropyl steardimonium','triethoxysilylpropyl steardimonium','INT'),
('triethoxysilylpropyl steardimonium chloride','triethoxysilylpropyl steardimonium chloride','INT'),
('triethyl citrate','triethyl citrate','INT'),
('triethylamine','triethylamine','INT'),
('triethylene amine','triethylene amine','INT'),
('triethylene glycol','triethylene glycol','INT'),
('triethylene glycoldimethacrylate','triethylene glycoldimethacrylate','INT'),
('triethylhexanoin','triethylhexanoin','INT'),
('trifarotene','trifarotene','INT'),
('trifluoperazine','trifluoperazine','INT'),
('trifluoroacetyl tripeptide-2','trifluoroacetyl tripeptide-2','INT'),
('trifluperidol','trifluperidol','INT'),
('triflupromazine','triflupromazine','INT'),
('trifluridine','trifluridine','INT'),
('triflusal','triflusal','INT'),
('Trifolium arvense whole extract','trifolium arvense whole extract','INT')
) AS v(nom, dci, pays)
WHERE NOT EXISTS (SELECT 1 FROM medicaments m WHERE LOWER(m.nom) = LOWER(v.nom));
