-- rxnorm_batch_211.sql (80 rows)
INSERT INTO medicaments (nom, dci, pays)
SELECT v.nom, v.dci, v.pays FROM (VALUES
('vitamin B6 / zinc picolinate','vitamin b6 / zinc picolinate','INT'),
('witch hazel / zinc oxide','witch hazel / zinc oxide','INT'),
('yohimbine / zinc sulfate','yohimbine / zinc sulfate','INT'),
('.alpha.-bisabolol, (-)-EPI-','.alpha.-bisabolol, (-)-epi-','INT'),
('.alpha.-pinene, (+)-','.alpha.-pinene, (+)-','INT'),
('.beta.-pinene, (+)-','.beta.-pinene, (+)-','INT'),
('.beta.-pinene, (-)-','.beta.-pinene, (-)-','INT'),
('1,2-dipalmitoylphosphatidylcholine, DL-','1,2-dipalmitoylphosphatidylcholine, dl-','INT'),
('10-hydroxycapric acid','10-hydroxycapric acid','INT'),
('12-hydroxystearic acid','12-hydroxystearic acid','INT'),
('169 ytterbium','169 ytterbium','INT'),
('2,4-diaminophenoxyethanol hydrochloride','2,4-diaminophenoxyethanol hydrochloride','INT'),
('2,4-diaminophenoxyethanol sulfate','2,4-diaminophenoxyethanol sulfate','INT'),
('2,4-dichlorophenoxyacetic acid, sodium salt','2,4-dichlorophenoxyacetic acid, sodium salt','INT'),
('2,5-diaminotoluene sulfate','2,5-diaminotoluene sulfate','INT'),
('2-(phosphonooxy)- 2-propenoic acid','2-(phosphonooxy)- 2-propenoic acid','INT'),
('2-bromobutane, (S)-','2-bromobutane, (s)-','INT'),
('2-butanoyloxybenzoic acid','2-butanoyloxybenzoic acid','INT'),
('2-hydroxydecanoic acid','2-hydroxydecanoic acid','INT'),
('2-phenylpropanal propylene glycol acetal','2-phenylpropanal propylene glycol acetal','INT'),
('2-tert-butylcyclohexyl acetate, cis-','2-tert-butylcyclohexyl acetate, cis-','INT'),
('24-homo-1,25-dihydroxyvitamin D3','24-homo-1,25-dihydroxyvitamin d3','INT'),
('3-hydroxy-4-methoxybenzenesulfonic acid','3-hydroxy-4-methoxybenzenesulfonic acid','INT'),
('3-O-ethylascorbic acid','3-o-ethylascorbic acid','INT'),
('4-desoxypyridoxine hydrochloride','4-desoxypyridoxine hydrochloride','INT'),
('4-hydroxybutyric acid','4-hydroxybutyric acid','INT'),
('4-phenylbutyric acid','4-phenylbutyric acid','INT'),
('7-behenoylstearic acid','7-behenoylstearic acid','INT'),
('82 rubidium','82 rubidium','INT'),
('82 strontium','82 strontium','INT'),
('85 strontium','85 strontium','INT'),
('99 molybdenum','99 molybdenum','INT'),
('abacavir sulfate','abacavir sulfate','INT'),
('abetimus sodium','abetimus sodium','INT'),
('abiraterone acetate','abiraterone acetate','INT'),
('abobotulinumtoxinA','abobotulinumtoxina','INT'),
('acamprosate calcium','acamprosate calcium','INT'),
('acebutolol hydrochloride','acebutolol hydrochloride','INT'),
('aceclidine hydrochloride','aceclidine hydrochloride','INT'),
('aceglutamide aluminum','aceglutamide aluminum','INT'),
('acellular tissue engineered vessel-tyod','acellular tissue engineered vessel-tyod','INT'),
('aceneuramic acid','aceneuramic acid','INT'),
('acepromazine maleate','acepromazine maleate','INT'),
('acesulfame potassium','acesulfame potassium','INT'),
('acetamidopropyl trimonium chloride','acetamidopropyl trimonium chloride','INT'),
('acetazolamide sodium','acetazolamide sodium','INT'),
('acetiamine hydrochloride','acetiamine hydrochloride','INT'),
('acetic acid C-11','acetic acid c-11','INT'),
('acetone sodium bisulfite','acetone sodium bisulfite','INT'),
('acetophenazine maleate','acetophenazine maleate','INT'),
('acetoxolone aluminum','acetoxolone aluminum','INT'),
('acetyl aspartic acid','acetyl aspartic acid','INT'),
('acetyl sulfisoxazole','acetyl sulfisoxazole','INT'),
('acetylated glycol stearate','acetylated glycol stearate','INT'),
('acetylcarnitine hydrochloride','acetylcarnitine hydrochloride','INT'),
('acetylcarnitine hydrochloride, DL-','acetylcarnitine hydrochloride, dl-','INT'),
('acetylcarnitine, DL-','acetylcarnitine, dl-','INT'),
('acetylcholine chloride','acetylcholine chloride','INT'),
('acetylcysteine amide','acetylcysteine amide','INT'),
('acetylcysteine magnesium','acetylcysteine magnesium','INT'),
('acetylcysteine sodium','acetylcysteine sodium','INT'),
('acetylcysteine zinc','acetylcysteine zinc','INT'),
('acetylsalicylate sodium','acetylsalicylate sodium','INT'),
('aclidinium bromide','aclidinium bromide','INT'),
('aconitic acid','aconitic acid','INT'),
('acoramidis hydrochloride','acoramidis hydrochloride','INT'),
('acriflavine hydrochloride','acriflavine hydrochloride','INT'),
('acrylic acid','acrylic acid','INT'),
('acyclovir sodium','acyclovir sodium','INT'),
('adalimumab-aacf','adalimumab-aacf','INT'),
('adalimumab-aaty','adalimumab-aaty','INT'),
('adalimumab-adaz','adalimumab-adaz','INT'),
('adalimumab-adbm','adalimumab-adbm','INT'),
('adalimumab-afzb','adalimumab-afzb','INT'),
('adalimumab-aqvh','adalimumab-aqvh','INT'),
('adalimumab-atto','adalimumab-atto','INT'),
('adalimumab-bwwd','adalimumab-bwwd','INT'),
('adalimumab-fkjp','adalimumab-fkjp','INT'),
('adalimumab-ryvk','adalimumab-ryvk','INT'),
('ADAMTS13, recombinant-krhn','adamts13, recombinant-krhn','INT')
) AS v(nom, dci, pays)
WHERE NOT EXISTS (SELECT 1 FROM medicaments m WHERE LOWER(m.nom) = LOWER(v.nom));
