-- rxnorm_batch_015.sql (80 rows)
INSERT INTO medicaments (nom, dci, pays)
SELECT v.nom, v.dci, v.pays FROM (VALUES
('Angelica pubescens root extract','angelica pubescens root extract','INT'),
('Angelica pubescens whole extract','angelica pubescens whole extract','INT'),
('Angelica root oil','angelica root oil','INT'),
('Angelica seed extract','angelica seed extract','INT'),
('Angelica seed oil','angelica seed oil','INT'),
('Angelica sinensis preparation','angelica sinensis preparation','INT'),
('Angelica sinensis root extract','angelica sinensis root extract','INT'),
('Angelica sinensis root oil','angelica sinensis root oil','INT'),
('Angelica sinensis whole extract','angelica sinensis whole extract','INT'),
('angelicin','angelicin','INT'),
('angiotensin II','angiotensin ii','INT'),
('Angophora costata whole extract','angophora costata whole extract','INT'),
('Angostura bark extract','angostura bark extract','INT'),
('angoumois grain moth allergenic extract','angoumois grain moth allergenic extract','INT'),
('Anguilla rostrata blood serum','anguilla rostrata blood serum','INT'),
('anhydromethylenecitric acid','anhydromethylenecitric acid','INT'),
('anhydrovitamin A','anhydrovitamin a','INT'),
('anhydroxylitol','anhydroxylitol','INT'),
('Aniba rosaeodora whole extract','aniba rosaeodora whole extract','INT'),
('Aniba rosaeodora wood extract','aniba rosaeodora wood extract','INT'),
('anidulafungin','anidulafungin','INT'),
('anifrolumab','anifrolumab','INT'),
('Anigozanthos flavidus flowering top extract','anigozanthos flavidus flowering top extract','INT'),
('anileridine','anileridine','INT'),
('aniline','aniline','INT'),
('aniracetam','aniracetam','INT'),
('anisacril','anisacril','INT'),
('anisate','anisate','INT'),
('anise oil','anise oil','INT'),
('anise seed extract','anise seed extract','INT'),
('anisindione','anisindione','INT'),
('anisole','anisole','INT'),
('anisotropine','anisotropine','INT'),
('anistreplase','anistreplase','INT'),
('anisum extract','anisum extract','INT'),
('anisyl acetate','anisyl acetate','INT'),
('anisyl alcohol','anisyl alcohol','INT'),
('annatto extract','annatto extract','INT'),
('Annickia chlorantha bark extract','annickia chlorantha bark extract','INT'),
('annual bluegrass pollen extract','annual bluegrass pollen extract','INT'),
('Anogeissus leiocarpus bark extract','anogeissus leiocarpus bark extract','INT'),
('Anredera cordifolia leaf extract','anredera cordifolia leaf extract','INT'),
('ansuvimab','ansuvimab','INT'),
('antazoline','antazoline','INT'),
('Anthemis arvensis flowering top extract','anthemis arvensis flowering top extract','INT'),
('Anthoxanthum odoratum antigen','anthoxanthum odoratum antigen','INT'),
('Anthoxanthum odoratum extract','anthoxanthum odoratum extract','INT'),
('anthralin','anthralin','INT'),
('anthraquinone glycoside','anthraquinone glycoside','INT'),
('anthrax immune globulin','anthrax immune globulin','INT'),
('anti-inhibitor coagulant complex','anti-inhibitor coagulant complex','INT'),
('anti-interleukin-1.alpha. immunoglobulin G rabbit','anti-interleukin-1.alpha. immunoglobulin g rabbit','INT'),
('Antiaris toxicara resin','antiaris toxicara resin','INT'),
('antilymphocyte immunoglobulin','antilymphocyte immunoglobulin','INT'),
('antimony','antimony','INT'),
('antimony arsenate','antimony arsenate','INT'),
('antimony pentasulfide','antimony pentasulfide','INT'),
('antimony potassium tartrate','antimony potassium tartrate','INT'),
('antimony sulfate','antimony sulfate','INT'),
('antimony tartrate ion','antimony tartrate ion','INT'),
('antimony triiodide','antimony triiodide','INT'),
('antimony trioxide','antimony trioxide','INT'),
('antimony trisulfide','antimony trisulfide','INT'),
('antioxidant 119','antioxidant 119','INT'),
('antipyrine','antipyrine','INT'),
('antirabies serum,equine','antirabies serum,equine','INT'),
('Antirrhinum majus leaf extract','antirrhinum majus leaf extract','INT'),
('antithrombin III','antithrombin iii','INT'),
('apaflurane','apaflurane','INT'),
('apalutamide','apalutamide','INT'),
('apazone','apazone','INT'),
('Aphanamixis polystachya whole extract','aphanamixis polystachya whole extract','INT'),
('Aphanizomenon flos-aquae','aphanizomenon flos-aquae','INT'),
('Aphloia theiformis leaf extract','aphloia theiformis leaf extract','INT'),
('apigenin','apigenin','INT'),
('apiole','apiole','INT'),
('Apiospora montagnei allergenic extract','apiospora montagnei allergenic extract','INT'),
('Apis cerana whole extract','apis cerana whole extract','INT'),
('Apis cerana whole preparation','apis cerana whole preparation','INT'),
('Apis cerana worker secretion preparation','apis cerana worker secretion preparation','INT')
) AS v(nom, dci, pays)
WHERE NOT EXISTS (SELECT 1 FROM medicaments m WHERE LOWER(m.nom) = LOWER(v.nom));
