-- rxnorm_batch_158.sql (80 rows)
INSERT INTO medicaments (nom, dci, pays)
SELECT v.nom, v.dci, v.pays FROM (VALUES
('Teucrium scorodonia flowering top extract','teucrium scorodonia flowering top extract','INT'),
('Teucrium scorodonia whole extract','teucrium scorodonia whole extract','INT'),
('tezacaftor','tezacaftor','INT'),
('tezepelumab','tezepelumab','INT'),
('thalidomide','thalidomide','INT'),
('thallium','thallium','INT'),
('thaumatin','thaumatin','INT'),
('Thaumatococcus daniellii fruit extract','thaumatococcus daniellii fruit extract','INT'),
('theaflavin','theaflavin','INT'),
('theanine','theanine','INT'),
('thenoate lithium','thenoate lithium','INT'),
('thenyldiamine','thenyldiamine','INT'),
('Theobroma grandiflorum seed butter extract','theobroma grandiflorum seed butter extract','INT'),
('Theobroma grandiflorum seed extract','theobroma grandiflorum seed extract','INT'),
('theobromine','theobromine','INT'),
('theodrenaline','theodrenaline','INT'),
('theofibrate','theofibrate','INT'),
('theophylline','theophylline','INT'),
('Theridion curassavicum preparation','theridion curassavicum preparation','INT'),
('Thermomyces lanuginosus allergenic extract','thermomyces lanuginosus allergenic extract','INT'),
('Thermus thermophilus extract','thermus thermophilus extract','INT'),
('Thermus thermophilus lysate','thermus thermophilus lysate','INT'),
('thiabendazole','thiabendazole','INT'),
('thiafentanil','thiafentanil','INT'),
('thiamine','thiamine','INT'),
('thiamine ion','thiamine ion','INT'),
('thiamphenicol','thiamphenicol','INT'),
('thiamylal','thiamylal','INT'),
('thiazolylalanine','thiazolylalanine','INT'),
('thiethylperazine','thiethylperazine','INT'),
('thimerosal','thimerosal','INT'),
('thiobutabarbital','thiobutabarbital','INT'),
('thiocolchicoside','thiocolchicoside','INT'),
('thioctate','thioctate','INT'),
('thioctic acid amide','thioctic acid amide','INT'),
('thiocyanate','thiocyanate','INT'),
('thiodipropionic acid','thiodipropionic acid','INT'),
('thioglycerol','thioglycerol','INT'),
('thioglycolate','thioglycolate','INT'),
('thioglycolic acid triethanolamine','thioglycolic acid triethanolamine','INT'),
('thioguanine','thioguanine','INT'),
('thiopental','thiopental','INT'),
('thiophene','thiophene','INT'),
('thiopropazate','thiopropazate','INT'),
('thioproperazine','thioproperazine','INT'),
('thioredoxin','thioredoxin','INT'),
('thioridazine','thioridazine','INT'),
('thiosalicylate','thiosalicylate','INT'),
('thiosalicylic acid','thiosalicylic acid','INT'),
('thiostrepton','thiostrepton','INT'),
('thiosulfate','thiosulfate','INT'),
('thiotaurine','thiotaurine','INT'),
('thiotepa','thiotepa','INT'),
('thiothixene','thiothixene','INT'),
('thiphenamil','thiphenamil','INT'),
('thiram','thiram','INT'),
('thonzonium','thonzonium','INT'),
('thonzylamine','thonzylamine','INT'),
('thorium','thorium','INT'),
('three-lobe sage extract','three-lobe sage extract','INT'),
('threonate','threonate','INT'),
('threonine','threonine','INT'),
('thrombin','thrombin','INT'),
('Thuja occidentalis bark extract','thuja occidentalis bark extract','INT'),
('Thuja occidentalis leaf extract','thuja occidentalis leaf extract','INT'),
('Thuja occidentalis leafy twig extract','thuja occidentalis leafy twig extract','INT'),
('Thuja occidentalis preparation','thuja occidentalis preparation','INT'),
('Thuja occidentalis root extract','thuja occidentalis root extract','INT'),
('Thuja occidentalis whole extract','thuja occidentalis whole extract','INT'),
('Thuja plicata leaf extract','thuja plicata leaf extract','INT'),
('Thujopsis dolabrata leafy twig extract','thujopsis dolabrata leafy twig extract','INT'),
('Thujopsis dolabrata whole extract','thujopsis dolabrata whole extract','INT'),
('Thujopsis dolabrata wood oil','thujopsis dolabrata wood oil','INT'),
('thulium','thulium','INT'),
('thurfyl salicylate','thurfyl salicylate','INT'),
('thuringiensin','thuringiensin','INT'),
('thymalfasin','thymalfasin','INT'),
('thyme allergenic extract','thyme allergenic extract','INT'),
('thyme oil','thyme oil','INT'),
('thyme preparation','thyme preparation','INT')
) AS v(nom, dci, pays)
WHERE NOT EXISTS (SELECT 1 FROM medicaments m WHERE LOWER(m.nom) = LOWER(v.nom));
