-- rxnorm_batch_078.sql (80 rows)
INSERT INTO medicaments (nom, dci, pays)
SELECT v.nom, v.dci, v.pays FROM (VALUES
('Guaiacum officinale resin','guaiacum officinale resin','INT'),
('Guaiacum officinale wood extract','guaiacum officinale wood extract','INT'),
('Guaiacum officinale wood oil','guaiacum officinale wood oil','INT'),
('Guaiacum sanctum resin','guaiacum sanctum resin','INT'),
('guaiazulene','guaiazulene','INT'),
('guaietolin','guaietolin','INT'),
('guaifenesin','guaifenesin','INT'),
('guaiol','guaiol','INT'),
('guanabenz','guanabenz','INT'),
('guanadrel','guanadrel','INT'),
('guanethidine','guanethidine','INT'),
('guanfacine','guanfacine','INT'),
('guanidine','guanidine','INT'),
('guanine','guanine','INT'),
('guanosine','guanosine','INT'),
('guanylcystamine','guanylcystamine','INT'),
('guar gum','guar gum','INT'),
('guarana preparation','guarana preparation','INT'),
('Guarea guidonia bark extract','guarea guidonia bark extract','INT'),
('guava extract','guava extract','INT'),
('guava juice','guava juice','INT'),
('Guazuma ulmifolia leaf extract','guazuma ulmifolia leaf extract','INT'),
('guggul lipids','guggul lipids','INT'),
('gugulu extract','gugulu extract','INT'),
('guinea pig dander','guinea pig dander','INT'),
('guinea pig hair extract','guinea pig hair extract','INT'),
('guinea pig skin extract','guinea pig skin extract','INT'),
('Guizotia abyssinica seed oil','guizotia abyssinica seed oil','INT'),
('gum talha extract','gum talha extract','INT'),
('guselkumab','guselkumab','INT'),
('Gymnadenia conopsea whole extract','gymnadenia conopsea whole extract','INT'),
('Gymnema sylvestre leaf extract','gymnema sylvestre leaf extract','INT'),
('Gymnema sylvestre preparation','gymnema sylvestre preparation','INT'),
('Gynostemma pentaphyllum leaf extract','gynostemma pentaphyllum leaf extract','INT'),
('Gynostemma pentaphyllum top extract','gynostemma pentaphyllum top extract','INT'),
('Gynostemma pentaphyllum whole extract','gynostemma pentaphyllum whole extract','INT'),
('Gypsophila paniculata root extract','gypsophila paniculata root extract','INT'),
('habanero extract','habanero extract','INT'),
('Haberlea rhodopensis leaf extract','haberlea rhodopensis leaf extract','INT'),
('Haberlea rhodopensis whole extract','haberlea rhodopensis whole extract','INT'),
('hackberry pollen extract','hackberry pollen extract','INT'),
('haddock allergenic extract','haddock allergenic extract','INT'),
('Haematococcus pluvialis extract','haematococcus pluvialis extract','INT'),
('Haematonectria haematococca allergenic extract','haematonectria haematococca allergenic extract','INT'),
('Haemophilus capsular oligosaccharide','haemophilus capsular oligosaccharide','INT'),
('Haemophilus influenzae','haemophilus influenzae','INT'),
('haemophilus influenzae immunoserum rabbit','haemophilus influenzae immunoserum rabbit','INT'),
('Haemophilus influenzae type b','haemophilus influenzae type b','INT'),
('hafnium','hafnium','INT'),
('Hagenia abyssinica flower extract','hagenia abyssinica flower extract','INT'),
('halazepam','halazepam','INT'),
('halazone','halazone','INT'),
('halcinonide','halcinonide','INT'),
('halibut liver oil','halibut liver oil','INT'),
('Halimeda opuntia extract','halimeda opuntia extract','INT'),
('halobetasol','halobetasol','INT'),
('halofantrine','halofantrine','INT'),
('halometasone','halometasone','INT'),
('haloperidol','haloperidol','INT'),
('haloprogin','haloprogin','INT'),
('halothane','halothane','INT'),
('Hamamelis virginiana bark extract','hamamelis virginiana bark extract','INT'),
('Hamamelis virginiana flower water extract','hamamelis virginiana flower water extract','INT'),
('Hamamelis virginiana leaf extract','hamamelis virginiana leaf extract','INT'),
('Hamamelis virginiana leaf water extract','hamamelis virginiana leaf water extract','INT'),
('Hamamelis virginiana root bark-stem bark extract','hamamelis virginiana root bark-stem bark extract','INT'),
('Hamamelis virginiana top extract','hamamelis virginiana top extract','INT'),
('Hamamelis virginiana top water extract','hamamelis virginiana top water extract','INT'),
('Hamamelis virginiana whole extract','hamamelis virginiana whole extract','INT'),
('hamster skin extract','hamster skin extract','INT'),
('hard fat','hard fat','INT'),
('hard maple pollen extract','hard maple pollen extract','INT'),
('Harpagophytum procumbens whole extract','harpagophytum procumbens whole extract','INT'),
('harpagoside','harpagoside','INT'),
('Harrisia pomanensis stem extract','harrisia pomanensis stem extract','INT'),
('Haslea ostrearia whole extract','haslea ostrearia whole extract','INT'),
('hawthorn berry','hawthorn berry','INT'),
('hawthorn berry extract','hawthorn berry extract','INT'),
('hawthorn flower extract','hawthorn flower extract','INT'),
('hawthorn flowering top extract','hawthorn flowering top extract','INT')
) AS v(nom, dci, pays)
WHERE NOT EXISTS (SELECT 1 FROM medicaments m WHERE LOWER(m.nom) = LOWER(v.nom));
