-- rxnorm_batch_029.sql (80 rows)
INSERT INTO medicaments (nom, dci, pays)
SELECT v.nom, v.dci, v.pays FROM (VALUES
('Brunfelsia uniflora root extract','brunfelsia uniflora root extract','INT'),
('brussels sprout allergenic extract','brussels sprout allergenic extract','INT'),
('brussels sprout extract','brussels sprout extract','INT'),
('Bryonia alba root extract','bryonia alba root extract','INT'),
('Bryonia alba whole extract','bryonia alba whole extract','INT'),
('Bryonia dioica root extract','bryonia dioica root extract','INT'),
('Bryonia preparation','bryonia preparation','INT'),
('buchu','buchu','INT'),
('buckminsterfullerene','buckminsterfullerene','INT'),
('buckthorn preparation','buckthorn preparation','INT'),
('buckwheat allergenic extract','buckwheat allergenic extract','INT'),
('buclizine','buclizine','INT'),
('Buddleja davidii leaf extract','buddleja davidii leaf extract','INT'),
('Buddleja davidii whole extract','buddleja davidii whole extract','INT'),
('Buddleja officinalis flower extract','buddleja officinalis flower extract','INT'),
('budesonide','budesonide','INT'),
('budipine','budipine','INT'),
('bufexamac','bufexamac','INT'),
('buflomedil','buflomedil','INT'),
('Bufo bufo cutaneous gland preparation','bufo bufo cutaneous gland preparation','INT'),
('Bufo bufo whole extract','bufo bufo whole extract','INT'),
('Bulbine frutescens whole extract','bulbine frutescens whole extract','INT'),
('bulbous buttercup pollen extract','bulbous buttercup pollen extract','INT'),
('Bulnesia sarmientoi wood oil','bulnesia sarmientoi wood oil','INT'),
('bumadizone','bumadizone','INT'),
('bumetanide','bumetanide','INT'),
('bunazosin','bunazosin','INT'),
('bupivacaine','bupivacaine','INT'),
('Bupleurum chinense root extract','bupleurum chinense root extract','INT'),
('Bupleurum falcatum root extract','bupleurum falcatum root extract','INT'),
('bupranolol','bupranolol','INT'),
('buprenorphine','buprenorphine','INT'),
('bupropion','bupropion','INT'),
('bur oak pollen extract','bur oak pollen extract','INT'),
('burdock root extract','burdock root extract','INT'),
('Burkholderia mallei','burkholderia mallei','INT'),
('burning bush pollen extract','burning bush pollen extract','INT'),
('burosumab','burosumab','INT'),
('burrobrush pollen extract','burrobrush pollen extract','INT'),
('Bursera graveolens fruit oil','bursera graveolens fruit oil','INT'),
('burweed marshelder pollen extract','burweed marshelder pollen extract','INT'),
('buserelin','buserelin','INT'),
('bush mango extract','bush mango extract','INT'),
('bushmaster venom','bushmaster venom','INT'),
('buspirone','buspirone','INT'),
('busulfan','busulfan','INT'),
('butabarbital','butabarbital','INT'),
('butacaine','butacaine','INT'),
('butafosfan','butafosfan','INT'),
('butalamine','butalamine','INT'),
('butalbital','butalbital','INT'),
('butamben','butamben','INT'),
('butamirate','butamirate','INT'),
('butanamide','butanamide','INT'),
('butane','butane','INT'),
('butanediol (mixed isomers)','butanediol (mixed isomers)','INT'),
('butcher''s broom preparation','butcher''s broom preparation','INT'),
('Butea monosperma flower extract','butea monosperma flower extract','INT'),
('Butea superba root extract','butea superba root extract','INT'),
('butedronate','butedronate','INT'),
('butenafine','butenafine','INT'),
('butetamate','butetamate','INT'),
('buteth-3','buteth-3','INT'),
('butethamate','butethamate','INT'),
('butethamate citrate','butethamate citrate','INT'),
('buthiazide','buthiazide','INT'),
('butibufen','butibufen','INT'),
('butidrine','butidrine','INT'),
('butobarbital','butobarbital','INT'),
('butoconazole','butoconazole','INT'),
('butorphanol','butorphanol','INT'),
('butoxycaine','butoxycaine','INT'),
('butriptyline','butriptyline','INT'),
('butterbur extract','butterbur extract','INT'),
('button mushroom extract','button mushroom extract','INT'),
('butyl acetate','butyl acetate','INT'),
('butyl alcohol','butyl alcohol','INT'),
('butyl avocadate','butyl avocadate','INT'),
('butyl butyryllactate','butyl butyryllactate','INT'),
('butyl carbamate','butyl carbamate','INT')
) AS v(nom, dci, pays)
WHERE NOT EXISTS (SELECT 1 FROM medicaments m WHERE LOWER(m.nom) = LOWER(v.nom));
