-- rxnorm_batch_195.sql (80 rows)
INSERT INTO medicaments (nom, dci, pays)
SELECT v.nom, v.dci, v.pays FROM (VALUES
('dimethicone / titanium dioxide','dimethicone / titanium dioxide','INT'),
('dimethicone / triclosan','dimethicone / triclosan','INT'),
('dimethicone / zinc oxide','dimethicone / zinc oxide','INT'),
('dimethindene / phenylephrine','dimethindene / phenylephrine','INT'),
('diosmin / hesperidin','diosmin / hesperidin','INT'),
('diperodon / hydrocortisone','diperodon / hydrocortisone','INT'),
('diperodon / hydrocortisone / zinc oxide','diperodon / hydrocortisone / zinc oxide','INT'),
('diphenhydramine / fomocain / tyrothricin','diphenhydramine / fomocain / tyrothricin','INT'),
('diphenhydramine / guaifenesin','diphenhydramine / guaifenesin','INT'),
('diphenhydramine / hydrocodone / phenylephrine','diphenhydramine / hydrocodone / phenylephrine','INT'),
('diphenhydramine / hydrocortisone','diphenhydramine / hydrocortisone','INT'),
('diphenhydramine / hydrocortisone / pramoxine','diphenhydramine / hydrocortisone / pramoxine','INT'),
('diphenhydramine / ibuprofen','diphenhydramine / ibuprofen','INT'),
('diphenhydramine / levomenthol','diphenhydramine / levomenthol','INT'),
('diphenhydramine / lidocaine','diphenhydramine / lidocaine','INT'),
('diphenhydramine / magnesium salicylate','diphenhydramine / magnesium salicylate','INT'),
('diphenhydramine / menthol','diphenhydramine / menthol','INT'),
('diphenhydramine / methaqualone','diphenhydramine / methaqualone','INT'),
('diphenhydramine / naphazoline','diphenhydramine / naphazoline','INT'),
('diphenhydramine / naproxen','diphenhydramine / naproxen','INT'),
('diphenhydramine / niacin','diphenhydramine / niacin','INT'),
('diphenhydramine / oxeladin / salicylamide','diphenhydramine / oxeladin / salicylamide','INT'),
('diphenhydramine / pentaerythritol','diphenhydramine / pentaerythritol','INT'),
('diphenhydramine / phenol','diphenhydramine / phenol','INT'),
('diphenhydramine / phenylephrine','diphenhydramine / phenylephrine','INT'),
('diphenhydramine / pramoxine','diphenhydramine / pramoxine','INT'),
('diphenhydramine / pseudoephedrine','diphenhydramine / pseudoephedrine','INT'),
('diphenhydramine / pyrilamine','diphenhydramine / pyrilamine','INT'),
('diphenhydramine / resorcinol','diphenhydramine / resorcinol','INT'),
('diphenhydramine / tripelennamine','diphenhydramine / tripelennamine','INT'),
('diphenhydramine / zinc acetate','diphenhydramine / zinc acetate','INT'),
('diphenhydramine / zinc oxide','diphenhydramine / zinc oxide','INT'),
('dipivefrin / levobunolol','dipivefrin / levobunolol','INT'),
('dipropizine / guaiacol ethylglycolate','dipropizine / guaiacol ethylglycolate','INT'),
('dipropizine / guaifenesin','dipropizine / guaifenesin','INT'),
('dipyrone / homatropine','dipyrone / homatropine','INT'),
('dipyrone / homatropine / papaverine','dipyrone / homatropine / papaverine','INT'),
('dipyrone / papaverine','dipyrone / papaverine','INT'),
('dipyrone / pramiverine','dipyrone / pramiverine','INT'),
('dipyrone / propinox','dipyrone / propinox','INT'),
('dipyrone / propoxyphene','dipyrone / propoxyphene','INT'),
('dipyrone / scopolamine','dipyrone / scopolamine','INT'),
('dipyrone / tiemonium','dipyrone / tiemonium','INT'),
('dipyrone / trospium','dipyrone / trospium','INT'),
('disofenin / stannous chloride','disofenin / stannous chloride','INT'),
('dobesilic acid / flunarizine','dobesilic acid / flunarizine','INT'),
('dobesilic acid / lidocaine','dobesilic acid / lidocaine','INT'),
('docosaenoic acid / eicosapentaenoate','docosaenoic acid / eicosapentaenoate','INT'),
('docosahexaenoate / eicosapentaenoate','docosahexaenoate / eicosapentaenoate','INT'),
('docosahexaenoate / eicosapentaenoate / vitamin E','docosahexaenoate / eicosapentaenoate / vitamin e','INT'),
('docosahexaenoate / omega-3 acid ethyl esters (USP)','docosahexaenoate / omega-3 acid ethyl esters (usp)','INT'),
('docosahexaenoate / phosphatidylserine','docosahexaenoate / phosphatidylserine','INT'),
('docusate / ferrous fumarate','docusate / ferrous fumarate','INT'),
('docusate / ferrous fumarate / folic acid','docusate / ferrous fumarate / folic acid','INT'),
('docusate / glycerin','docusate / glycerin','INT'),
('docusate / phenolphthalein','docusate / phenolphthalein','INT'),
('docusate / piperazine','docusate / piperazine','INT'),
('docusate / sennoside B','docusate / sennoside b','INT'),
('docusate / sennosides, USP','docusate / sennosides, usp','INT'),
('docusate / sorbitol','docusate / sorbitol','INT'),
('docusate / spermaceti','docusate / spermaceti','INT'),
('dodecyl sulfate / lanolin','dodecyl sulfate / lanolin','INT'),
('dodecyl sulfate / oxyquinoline','dodecyl sulfate / oxyquinoline','INT'),
('dodecyl sulfate / zinc pyrithione','dodecyl sulfate / zinc pyrithione','INT'),
('dodecylbenzenesulfonic acid / lactate','dodecylbenzenesulfonic acid / lactate','INT'),
('dog hair extract / dog skin extract','dog hair extract / dog skin extract','INT'),
('dog hair extract / English plantain pollen extract','dog hair extract / english plantain pollen extract','INT'),
('dog hair extract / short ragweed pollen extract','dog hair extract / short ragweed pollen extract','INT'),
('dolutegravir / lamivudine','dolutegravir / lamivudine','INT'),
('dolutegravir / rilpivirine','dolutegravir / rilpivirine','INT'),
('domiphen / lidocaine','domiphen / lidocaine','INT'),
('domperidone / ranitidine','domperidone / ranitidine','INT'),
('domperidone / simethicone','domperidone / simethicone','INT'),
('donepezil / memantine','donepezil / memantine','INT'),
('doramectin / levamisole','doramectin / levamisole','INT'),
('doravirine / lamivudine / tenofovir disoproxil','doravirine / lamivudine / tenofovir disoproxil','INT'),
('dornase alfa / streptokinase','dornase alfa / streptokinase','INT'),
('dorzolamide / timolol','dorzolamide / timolol','INT'),
('doxylamine / phenylephrine','doxylamine / phenylephrine','INT'),
('doxylamine / pseudoephedrine','doxylamine / pseudoephedrine','INT')
) AS v(nom, dci, pays)
WHERE NOT EXISTS (SELECT 1 FROM medicaments m WHERE LOWER(m.nom) = LOWER(v.nom));
