-- rxnorm_batch_209.sql (80 rows)
INSERT INTO medicaments (nom, dci, pays)
SELECT v.nom, v.dci, v.pays FROM (VALUES
('potassium bicarbonate / potassium tartrate','potassium bicarbonate / potassium tartrate','INT'),
('potassium bicarbonate / sodium bicarbonate','potassium bicarbonate / sodium bicarbonate','INT'),
('potassium bitartrate / sodium bicarbonate','potassium bitartrate / sodium bicarbonate','INT'),
('potassium chloride / potassium gluconate','potassium chloride / potassium gluconate','INT'),
('potassium chloride / Rauwolfia preparation','potassium chloride / rauwolfia preparation','INT'),
('potassium chloride / sodium chloride','potassium chloride / sodium chloride','INT'),
('potassium citrate / potassium gluconate','potassium citrate / potassium gluconate','INT'),
('potassium citrate / sodium citrate','potassium citrate / sodium citrate','INT'),
('potassium citrate / sodium fluoride','potassium citrate / sodium fluoride','INT'),
('potassium gluconate / vitamin B6','potassium gluconate / vitamin b6','INT'),
('potassium iodide / theophylline','potassium iodide / theophylline','INT'),
('potassium nitrate / silver nitrate','potassium nitrate / silver nitrate','INT'),
('potassium nitrate / sodium fluoride','potassium nitrate / sodium fluoride','INT'),
('potassium phosphate / sodium phosphate, dibasic','potassium phosphate / sodium phosphate, dibasic','INT'),
('potassium phosphate / sodium phosphate, monobasic','potassium phosphate / sodium phosphate, monobasic','INT'),
('potassium tartrate / sodium bicarbonate','potassium tartrate / sodium bicarbonate','INT'),
('povidone / propylene glycol','povidone / propylene glycol','INT'),
('povidone / tetrahydrozoline','povidone / tetrahydrozoline','INT'),
('pramoxine / salicyloyl phytosphingosine','pramoxine / salicyloyl phytosphingosine','INT'),
('pramoxine / zinc acetate','pramoxine / zinc acetate','INT'),
('pramoxine / zinc oxide','pramoxine / zinc oxide','INT'),
('pramoxine / zinc sulfate','pramoxine / zinc sulfate','INT'),
('praziquantel / pyrantel','praziquantel / pyrantel','INT'),
('prednisolone / propylene glycol salicylate','prednisolone / propylene glycol salicylate','INT'),
('prednisolone / rifamycins','prednisolone / rifamycins','INT'),
('prednisolone / salicylic acid','prednisolone / salicylic acid','INT'),
('prednisolone / sulfacetamide','prednisolone / sulfacetamide','INT'),
('prednisolone / trimeprazine','prednisolone / trimeprazine','INT'),
('prednisolone / zinc oxide','prednisolone / zinc oxide','INT'),
('pridinol / rofecoxib','pridinol / rofecoxib','INT'),
('prilocaine / procaine / tetracaine','prilocaine / procaine / tetracaine','INT'),
('probenecid / sulopenem','probenecid / sulopenem','INT'),
('proglumide / sulpiride','proglumide / sulpiride','INT'),
('promethazine / pseudoephedrine','promethazine / pseudoephedrine','INT'),
('propionic acid / undecylenate','propionic acid / undecylenate','INT'),
('propylene glycol / sodium chloride','propylene glycol / sodium chloride','INT'),
('pseudoephedrine / pyrilamine','pseudoephedrine / pyrilamine','INT'),
('pseudoephedrine / terfenadine','pseudoephedrine / terfenadine','INT'),
('pseudoephedrine / tripelennamine','pseudoephedrine / tripelennamine','INT'),
('pseudoephedrine / triprolidine','pseudoephedrine / triprolidine','INT'),
('psyllium / sennosides, USP','psyllium / sennosides, usp','INT'),
('pyridoxal / tyrosine','pyridoxal / tyrosine','INT'),
('pyridoxine / salicylic acid / zinc gluconate','pyridoxine / salicylic acid / zinc gluconate','INT'),
('pyridoxine / thiamine / vitamin B12','pyridoxine / thiamine / vitamin b12','INT'),
('pyridoxine / vitamin B12','pyridoxine / vitamin b12','INT'),
('pyrimethamine / sulfadiazine','pyrimethamine / sulfadiazine','INT'),
('pyrimethamine / sulfadoxine','pyrimethamine / sulfadoxine','INT'),
('pyrvinium / thiabendazole','pyrvinium / thiabendazole','INT'),
('quercetin / resveratrol','quercetin / resveratrol','INT'),
('quinethazone / reserpine','quinethazone / reserpine','INT'),
('quinidine / verapamil','quinidine / verapamil','INT'),
('quinine / vitamin E','quinine / vitamin e','INT'),
('racepinephrine / zinc chloride','racepinephrine / zinc chloride','INT'),
('red oak pollen extract / white oak pollen extract','red oak pollen extract / white oak pollen extract','INT'),
('red yeast rice / ubidecarenone','red yeast rice / ubidecarenone','INT'),
('reserpine / trichlormethiazide','reserpine / trichlormethiazide','INT'),
('reserpine / xipamide','reserpine / xipamide','INT'),
('resorcinol / sulfur','resorcinol / sulfur','INT'),
('resorcinol / sulfur / triclosan','resorcinol / sulfur / triclosan','INT'),
('riboflavin / ubidecarenone','riboflavin / ubidecarenone','INT'),
('riboflavin / vitamin B6','riboflavin / vitamin b6','INT'),
('rifampin / trimethoprim','rifampin / trimethoprim','INT'),
('ruscogenin / trimebutine','ruscogenin / trimebutine','INT'),
('rutin / vincamine','rutin / vincamine','INT'),
('sacubitril / valsartan','sacubitril / valsartan','INT'),
('salicylamide / vitamin B12','salicylamide / vitamin b12','INT'),
('salicylic acid / sulfur','salicylic acid / sulfur','INT'),
('salicylic acid / thiosulfate','salicylic acid / thiosulfate','INT'),
('salicylic acid / triamcinolone','salicylic acid / triamcinolone','INT'),
('salicylic acid / trichloroacetaldehyde','salicylic acid / trichloroacetaldehyde','INT'),
('salicylic acid / triclosan','salicylic acid / triclosan','INT'),
('salicylic acid / undecylenate','salicylic acid / undecylenate','INT'),
('salicylic acid / urea','salicylic acid / urea','INT'),
('salicylic acid / zinc oxide','salicylic acid / zinc oxide','INT'),
('salicylic acid / zinc pyrithione','salicylic acid / zinc pyrithione','INT'),
('sarolaner / selamectin','sarolaner / selamectin','INT'),
('shark liver oil / tissue respiratory factor','shark liver oil / tissue respiratory factor','INT'),
('shark liver oil / vitamin E','shark liver oil / vitamin e','INT'),
('silicon dioxide / tricalcium phosphate','silicon dioxide / tricalcium phosphate','INT'),
('silicones / simethicone','silicones / simethicone','INT')
) AS v(nom, dci, pays)
WHERE NOT EXISTS (SELECT 1 FROM medicaments m WHERE LOWER(m.nom) = LOWER(v.nom));
