-- rxnorm_batch_150.sql (80 rows)
INSERT INTO medicaments (nom, dci, pays)
SELECT v.nom, v.dci, v.pays FROM (VALUES
('spirapril','spirapril','INT'),
('spironolactone','spironolactone','INT'),
('Spirulina','spirulina','INT'),
('Spirulina maxima preparation','spirulina maxima preparation','INT'),
('Spongia officinalis preparation','spongia officinalis preparation','INT'),
('Spongia officinalis skeleton extract','spongia officinalis skeleton extract','INT'),
('spongia tosta','spongia tosta','INT'),
('Spongilla lacustris extract','spongilla lacustris extract','INT'),
('squalane','squalane','INT'),
('squalene','squalene','INT'),
('squash allergenic extract','squash allergenic extract','INT'),
('squill extract','squill extract','INT'),
('St. John''s wort extract','st. john''s wort extract','INT'),
('Stachybotrys chartarum allergenic extract','stachybotrys chartarum allergenic extract','INT'),
('Stachys officinalis extract','stachys officinalis extract','INT'),
('Stachys officinalis flower top extract','stachys officinalis flower top extract','INT'),
('Stachyurus chinensis whole extract','stachyurus chinensis whole extract','INT'),
('standardized senna concentrate','standardized senna concentrate','INT'),
('stannate','stannate','INT'),
('stannic oxide','stannic oxide','INT'),
('stannous 2-ethylhexanoate','stannous 2-ethylhexanoate','INT'),
('stannous cation','stannous cation','INT'),
('stannous chloride','stannous chloride','INT'),
('stannous fluoride','stannous fluoride','INT'),
('stannous oxide','stannous oxide','INT'),
('stannous tartrate','stannous tartrate','INT'),
('stanozolol','stanozolol','INT'),
('Staphylococcus aureus','staphylococcus aureus','INT'),
('staphylococcus aureus immunoserum','staphylococcus aureus immunoserum','INT'),
('Staphylococcus epidermidis','staphylococcus epidermidis','INT'),
('staphylococcus epidermidis immunoserum rabbit','staphylococcus epidermidis immunoserum rabbit','INT'),
('Staphylococcus haemolyticus','staphylococcus haemolyticus','INT'),
('Staphylococcus simulans','staphylococcus simulans','INT'),
('star anise extract','star anise extract','INT'),
('star anise fruit extract','star anise fruit extract','INT'),
('star anise oil','star anise oil','INT'),
('star anise whole extract','star anise whole extract','INT'),
('star fruit extract','star fruit extract','INT'),
('starch','starch','INT'),
('starch glycolate','starch glycolate','INT'),
('starch glycolate type a corn','starch glycolate type a corn','INT'),
('starch glycolate type a potato','starch glycolate type a potato','INT'),
('starch glycolate type b potato','starch glycolate type b potato','INT'),
('starch, rice','starch, rice','INT'),
('starch, tapioca','starch, tapioca','INT'),
('starch, wheat','starch, wheat','INT'),
('stavudine','stavudine','INT'),
('stearalkonium','stearalkonium','INT'),
('stearalkonium hectorite','stearalkonium hectorite','INT'),
('stearamide','stearamide','INT'),
('stearamide amp','stearamide amp','INT'),
('stearamidoethyl diethylamine','stearamidoethyl diethylamine','INT'),
('stearamidopropyl betaine','stearamidopropyl betaine','INT'),
('stearamidopropyl PG-dimonium chloride phosphate','stearamidopropyl pg-dimonium chloride phosphate','INT'),
('stearamine','stearamine','INT'),
('stearate','stearate','INT'),
('steareth-10','steareth-10','INT'),
('steareth-10 phosphate','steareth-10 phosphate','INT'),
('steareth-100','steareth-100','INT'),
('steareth-12','steareth-12','INT'),
('steareth-15','steareth-15','INT'),
('steareth-2','steareth-2','INT'),
('steareth-2 phosphate','steareth-2 phosphate','INT'),
('steareth-20','steareth-20','INT'),
('steareth-20 methacrylate','steareth-20 methacrylate','INT'),
('steareth-21','steareth-21','INT'),
('steareth-22','steareth-22','INT'),
('steareth-23','steareth-23','INT'),
('steareth-25','steareth-25','INT'),
('steareth-3','steareth-3','INT'),
('steareth-30','steareth-30','INT'),
('steareth-4','steareth-4','INT'),
('steareth-7','steareth-7','INT'),
('stearic acid D7','stearic acid d7','INT'),
('stearic diethanolamide','stearic diethanolamide','INT'),
('stearic monoethanolamide','stearic monoethanolamide','INT'),
('stearoamphoacetate','stearoamphoacetate','INT'),
('stearoxypropyltrimonium chloride','stearoxypropyltrimonium chloride','INT'),
('stearoxytrimethylsilane','stearoxytrimethylsilane','INT'),
('stearoyl glutamate','stearoyl glutamate','INT')
) AS v(nom, dci, pays)
WHERE NOT EXISTS (SELECT 1 FROM medicaments m WHERE LOWER(m.nom) = LOWER(v.nom));
