-- rxnorm_batch_170.sql (80 rows)
INSERT INTO medicaments (nom, dci, pays)
SELECT v.nom, v.dci, v.pays FROM (VALUES
('xamoterol','xamoterol','INT'),
('xanomeline','xanomeline','INT'),
('xanthan gum','xanthan gum','INT'),
('xanthine','xanthine','INT'),
('xanthinol','xanthinol','INT'),
('Xanthium extract','xanthium extract','INT'),
('Xanthium sibiricum fruit extract','xanthium sibiricum fruit extract','INT'),
('Xanthium sibiricum whole extract','xanthium sibiricum whole extract','INT'),
('Xanthium strumarium fruit extract','xanthium strumarium fruit extract','INT'),
('Xanthium strumarium leaf extract','xanthium strumarium leaf extract','INT'),
('Xanthoxylum clava-herculus bark extract','xanthoxylum clava-herculus bark extract','INT'),
('Xanthoxylum clava-herculus whole extract','xanthoxylum clava-herculus whole extract','INT'),
('xenon','xenon','INT'),
('Xerophyllum asphodeloides extract','xerophyllum asphodeloides extract','INT'),
('xibornol','xibornol','INT'),
('xipamide','xipamide','INT'),
('Xoimenia americana seed extract','xoimenia americana seed extract','INT'),
('xylazine','xylazine','INT'),
('xylene','xylene','INT'),
('xylenesulfonate','xylenesulfonate','INT'),
('xylitan','xylitan','INT'),
('xylitol','xylitol','INT'),
('xylityl sesquicaprylate','xylityl sesquicaprylate','INT'),
('xylitylglucoside','xylitylglucoside','INT'),
('xylometazoline','xylometazoline','INT'),
('xylose','xylose','INT'),
('xymenynic acid','xymenynic acid','INT'),
('yarrow flower extract','yarrow flower extract','INT'),
('yeast mannan preparation','yeast mannan preparation','INT'),
('yeast, beta-D-glucan','yeast, beta-d-glucan','INT'),
('yellow birch pollen extract','yellow birch pollen extract','INT'),
('yellow dock pollen extract','yellow dock pollen extract','INT'),
('yellow fever virus strain 17D-204 live antigen','yellow fever virus strain 17d-204 live antigen','INT'),
('yellow hornet venom','yellow hornet venom','INT'),
('yellow hornet venom protein','yellow hornet venom protein','INT'),
('yellow jacket venom protein','yellow jacket venom protein','INT'),
('yellow OB','yellow ob','INT'),
('yellow phenolphthalein','yellow phenolphthalein','INT'),
('yellow pine pollen extract','yellow pine pollen extract','INT'),
('yellow sweet clover pollen extract','yellow sweet clover pollen extract','INT'),
('yellowfin tuna allergenic extract','yellowfin tuna allergenic extract','INT'),
('Yersinia enterocolitica','yersinia enterocolitica','INT'),
('Yersinia pestis','yersinia pestis','INT'),
('yohimbe bark preparation','yohimbe bark preparation','INT'),
('yohimbine','yohimbine','INT'),
('ytterbium','ytterbium','INT'),
('ytterbium oxide','ytterbium oxide','INT'),
('yttrium','yttrium','INT'),
('yucca extract','yucca extract','INT'),
('Yucca filamentosa extract','yucca filamentosa extract','INT'),
('Yucca glauca root extract','yucca glauca root extract','INT'),
('yucca root','yucca root','INT'),
('Yucca schidigera extract','yucca schidigera extract','INT'),
('Yucca schidigera root extract','yucca schidigera root extract','INT'),
('Yucca schidigera stem','yucca schidigera stem','INT'),
('zafirlukast','zafirlukast','INT'),
('Zaire ebolavirus envelope glycoprotein','zaire ebolavirus envelope glycoprotein','INT'),
('zalcitabine','zalcitabine','INT'),
('zaleplon','zaleplon','INT'),
('zanamivir','zanamivir','INT'),
('zanidatamab','zanidatamab','INT'),
('Zantedeschia aethiopica flower extract','zantedeschia aethiopica flower extract','INT'),
('Zanthoxylum americanum bark extract','zanthoxylum americanum bark extract','INT'),
('Zanthoxylum armatum var. armatum fruit extract','zanthoxylum armatum var. armatum fruit extract','INT'),
('Zanthoxylum bungeanum fruit extract','zanthoxylum bungeanum fruit extract','INT'),
('Zanthoxylum bungeanum fruit rind extract','zanthoxylum bungeanum fruit rind extract','INT'),
('Zanthoxylum bungeanum whole extract','zanthoxylum bungeanum whole extract','INT'),
('Zanthoxylum fagara whole extract','zanthoxylum fagara whole extract','INT'),
('Zanthoxylum nitidum root extract','zanthoxylum nitidum root extract','INT'),
('Zanthoxylum piperitum fruit pulp extract','zanthoxylum piperitum fruit pulp extract','INT'),
('Zanthoxylum piperitum fruit rind extract','zanthoxylum piperitum fruit rind extract','INT'),
('Zanthoxylum piperitum whole extract','zanthoxylum piperitum whole extract','INT'),
('Zanthoxylum schinifolium fruit extract','zanthoxylum schinifolium fruit extract','INT'),
('Zanthoxylum schinifolium whole extract','zanthoxylum schinifolium whole extract','INT'),
('Zanthoxylum zanthoxyloides bark extract','zanthoxylum zanthoxyloides bark extract','INT'),
('zanubrutinib','zanubrutinib','INT'),
('Zaocys dhumnades preparation','zaocys dhumnades preparation','INT'),
('zavegepant','zavegepant','INT'),
('Zea mays subsp. mays whole extract','zea mays subsp. mays whole extract','INT'),
('zeatin','zeatin','INT')
) AS v(nom, dci, pays)
WHERE NOT EXISTS (SELECT 1 FROM medicaments m WHERE LOWER(m.nom) = LOWER(v.nom));
