-- rxnorm_batch_040.sql (80 rows)
INSERT INTO medicaments (nom, dci, pays)
SELECT v.nom, v.dci, v.pays FROM (VALUES
('chicory leaf extract','chicory leaf extract','INT'),
('chicory root extract','chicory root extract','INT'),
('Chilean hazelnut oil','chilean hazelnut oil','INT'),
('chilipepper rockfish, cooked','chilipepper rockfish, cooked','INT'),
('Chimaphila maculata extract','chimaphila maculata extract','INT'),
('Chimaphila umbellata extract','chimaphila umbellata extract','INT'),
('Chimonanthus praecox flower oil','chimonanthus praecox flower oil','INT'),
('Chimonanthus praecox whole extract','chimonanthus praecox whole extract','INT'),
('Chinese chestnut extract','chinese chestnut extract','INT'),
('Chinese cinnamon extract','chinese cinnamon extract','INT'),
('Chinese cinnamon leaf oil','chinese cinnamon leaf oil','INT'),
('Chinese cinnamon oil','chinese cinnamon oil','INT'),
('Chinese elm pollen extract','chinese elm pollen extract','INT'),
('Chinese rhubarb root exract','chinese rhubarb root exract','INT'),
('Chinese yam extract','chinese yam extract','INT'),
('chinquapin oak pollen extract','chinquapin oak pollen extract','INT'),
('Chiococca alba root extract','chiococca alba root extract','INT'),
('Chionanthus virginicus bark extract','chionanthus virginicus bark extract','INT'),
('chiro-inositol, (+)-','chiro-inositol, (+)-','INT'),
('chitosan','chitosan','INT'),
('chitosan oligosaccharide','chitosan oligosaccharide','INT'),
('Chlamydia trachomatis','chlamydia trachomatis','INT'),
('Chlamydomonas reinhardtii','chlamydomonas reinhardtii','INT'),
('chlophedianol','chlophedianol','INT'),
('chloral betaine','chloral betaine','INT'),
('chlorambucil','chlorambucil','INT'),
('chloramine-T','chloramine-t','INT'),
('chloramphenicol','chloramphenicol','INT'),
('chlorate ion','chlorate ion','INT'),
('chlorcyclizine','chlorcyclizine','INT'),
('chlordiazepoxide','chlordiazepoxide','INT'),
('Chlorella emersonii extract','chlorella emersonii extract','INT'),
('Chlorella minutissima extract','chlorella minutissima extract','INT'),
('Chlorella pyrenoidosa extract','chlorella pyrenoidosa extract','INT'),
('Chlorella vulgaris extract','chlorella vulgaris extract','INT'),
('chlorfenethazine','chlorfenethazine','INT'),
('chlorhexidine','chlorhexidine','INT'),
('chloric acid','chloric acid','INT'),
('chloride hexahydrate','chloride hexahydrate','INT'),
('chloride ion','chloride ion','INT'),
('chlorine','chlorine','INT'),
('chlorine dioxide','chlorine dioxide','INT'),
('chlorite ion','chlorite ion','INT'),
('chlormadinone','chlormadinone','INT'),
('chlormethiazole','chlormethiazole','INT'),
('chlormezanone','chlormezanone','INT'),
('chloroacetate','chloroacetate','INT'),
('chlorobutanol','chlorobutanol','INT'),
('chlorocitric acid','chlorocitric acid','INT'),
('chlorocresol','chlorocresol','INT'),
('chloroform','chloroform','INT'),
('chlorogenic acid','chlorogenic acid','INT'),
('chlorokojic acid','chlorokojic acid','INT'),
('chloromethyl methyl ether','chloromethyl methyl ether','INT'),
('chlorophyll','chlorophyll','INT'),
('chlorophyllin','chlorophyllin','INT'),
('chlorophyllin copper complex','chlorophyllin copper complex','INT'),
('Chlorophytum borivilianum whole extract','chlorophytum borivilianum whole extract','INT'),
('chloroprocaine','chloroprocaine','INT'),
('chloropropylate','chloropropylate','INT'),
('chloropyramine','chloropyramine','INT'),
('chloroquine','chloroquine','INT'),
('chlorothen','chlorothen','INT'),
('chlorotheophylline','chlorotheophylline','INT'),
('chlorothiazide','chlorothiazide','INT'),
('chlorothymol','chlorothymol','INT'),
('chlorotrianisene','chlorotrianisene','INT'),
('chlorous acid','chlorous acid','INT'),
('chloroxine','chloroxine','INT'),
('chloroxylenol','chloroxylenol','INT'),
('chlorozotocin','chlorozotocin','INT'),
('chlorphenesin','chlorphenesin','INT'),
('chlorphenindione','chlorphenindione','INT'),
('chlorpheniramine','chlorpheniramine','INT'),
('chlorphenoxamine','chlorphenoxamine','INT'),
('chlorproethazine','chlorproethazine','INT'),
('chlorpromazine','chlorpromazine','INT'),
('chlorpropamide','chlorpropamide','INT'),
('chlorprothixene','chlorprothixene','INT'),
('chlorquinaldol','chlorquinaldol','INT')
) AS v(nom, dci, pays)
WHERE NOT EXISTS (SELECT 1 FROM medicaments m WHERE LOWER(m.nom) = LOWER(v.nom));
