-- rxnorm_batch_134.sql (80 rows)
INSERT INTO medicaments (nom, dci, pays)
SELECT v.nom, v.dci, v.pays FROM (VALUES
('Proteus rettgeri','proteus rettgeri','INT'),
('Proteus vulgaris','proteus vulgaris','INT'),
('prothionamide','prothionamide','INT'),
('prothipendyl','prothipendyl','INT'),
('prothrombin','prothrombin','INT'),
('protocatechualdehyde','protocatechualdehyde','INT'),
('Protortonia cacti preparation','protortonia cacti preparation','INT'),
('protriptyline','protriptyline','INT'),
('proxibarbal','proxibarbal','INT'),
('proxigermanium','proxigermanium','INT'),
('proximadiol','proximadiol','INT'),
('proxyphylline','proxyphylline','INT'),
('prucalopride','prucalopride','INT'),
('prune preparation','prune preparation','INT'),
('Prunella vulgaris extract','prunella vulgaris extract','INT'),
('Prunella vulgaris flower extract','prunella vulgaris flower extract','INT'),
('Prunella vulgaris flowering top extract','prunella vulgaris flowering top extract','INT'),
('Prunella vulgaris leaf extract','prunella vulgaris leaf extract','INT'),
('Prunus americana whole extract','prunus americana whole extract','INT'),
('Prunus apetala whole extract','prunus apetala whole extract','INT'),
('Prunus armeniaca leaf extract','prunus armeniaca leaf extract','INT'),
('Prunus armeniaca seed extract','prunus armeniaca seed extract','INT'),
('Prunus armeniaca whole extract','prunus armeniaca whole extract','INT'),
('Prunus cerasifera flower extract','prunus cerasifera flower extract','INT'),
('Prunus cerasifera whole extract','prunus cerasifera whole extract','INT'),
('Prunus cerasus flower bud extract','prunus cerasus flower bud extract','INT'),
('Prunus cerasus flower extract','prunus cerasus flower extract','INT'),
('Prunus domestica subsp. insititia seed oil','prunus domestica subsp. insititia seed oil','INT'),
('Prunus dulcis bark extract','prunus dulcis bark extract','INT'),
('Prunus dulcis flower extract','prunus dulcis flower extract','INT'),
('Prunus dulcis pollen extract','prunus dulcis pollen extract','INT'),
('Prunus dulcis whole extract','prunus dulcis whole extract','INT'),
('Prunus lannesiana flower extract','prunus lannesiana flower extract','INT'),
('Prunus laurocerasus leaf extract','prunus laurocerasus leaf extract','INT'),
('Prunus laurocerasus whole extract','prunus laurocerasus whole extract','INT'),
('Prunus mume flower extract','prunus mume flower extract','INT'),
('Prunus mume flower oil','prunus mume flower oil','INT'),
('Prunus mume fruit extract','prunus mume fruit extract','INT'),
('Prunus mume fruit oil','prunus mume fruit oil','INT'),
('Prunus mume whole extract','prunus mume whole extract','INT'),
('Prunus persica flower bud extract','prunus persica flower bud extract','INT'),
('Prunus persica flower extract','prunus persica flower extract','INT'),
('Prunus persica fruiting top extract','prunus persica fruiting top extract','INT'),
('Prunus persica leaf extract','prunus persica leaf extract','INT'),
('Prunus persica seed extract','prunus persica seed extract','INT'),
('Prunus persica twig extract','prunus persica twig extract','INT'),
('Prunus persica var. nucipersica whole extract','prunus persica var. nucipersica whole extract','INT'),
('Prunus persica whole extract','prunus persica whole extract','INT'),
('Prunus salicina fruit extract','prunus salicina fruit extract','INT'),
('Prunus serotina bark extract','prunus serotina bark extract','INT'),
('Prunus serotina fruit extract','prunus serotina fruit extract','INT'),
('Prunus serrulata flower extract','prunus serrulata flower extract','INT'),
('Prunus speciosa flower extract','prunus speciosa flower extract','INT'),
('Prunus speciosa leaf extract','prunus speciosa leaf extract','INT'),
('Prunus spinosa flower bud extract','prunus spinosa flower bud extract','INT'),
('Prunus spinosa fruit extract','prunus spinosa fruit extract','INT'),
('Prunus spinosa whole extract','prunus spinosa whole extract','INT'),
('Prunus virginiana bark extract','prunus virginiana bark extract','INT'),
('Prunus x yedoensis flower extract','prunus x yedoensis flower extract','INT'),
('Prunus x yedoensis leaf extract','prunus x yedoensis leaf extract','INT'),
('prussian blue insoluble','prussian blue insoluble','INT'),
('pSCN5A-Neo','pscn5a-neo','INT'),
('Pseudevernia furfuracea extract','pseudevernia furfuracea extract','INT'),
('pseudoephedrine','pseudoephedrine','INT'),
('Pseudognaphalium luteoalbum leaf extract','pseudognaphalium luteoalbum leaf extract','INT'),
('Pseudognaphalium luteoalbum whole extract','pseudognaphalium luteoalbum whole extract','INT'),
('Pseudognaphalium obtusifolium extract','pseudognaphalium obtusifolium extract','INT'),
('pseudoisocytidine','pseudoisocytidine','INT'),
('Pseudolarix amabilis bark extract','pseudolarix amabilis bark extract','INT'),
('Pseudolarix amabilis whole extract','pseudolarix amabilis whole extract','INT'),
('Pseudomonas aeruginosa','pseudomonas aeruginosa','INT'),
('pseudopterogorgia elisabethae extract','pseudopterogorgia elisabethae extract','INT'),
('Pseudostellaria heterophylla whole extract','pseudostellaria heterophylla whole extract','INT'),
('Pseudotsuga menziesii resin','pseudotsuga menziesii resin','INT'),
('Psidium guajava extract','psidium guajava extract','INT'),
('Psidium guajava leaf extract','psidium guajava leaf extract','INT'),
('psyllium','psyllium','INT'),
('Ptelea trifoliata bark extract','ptelea trifoliata bark extract','INT'),
('Pteridium aquilinum root extract','pteridium aquilinum root extract','INT'),
('Pteridium aquilinum whole extract','pteridium aquilinum whole extract','INT')
) AS v(nom, dci, pays)
WHERE NOT EXISTS (SELECT 1 FROM medicaments m WHERE LOWER(m.nom) = LOWER(v.nom));
