-- rxnorm_batch_127.sql (80 rows)
INSERT INTO medicaments (nom, dci, pays)
SELECT v.nom, v.dci, v.pays FROM (VALUES
('Plantago major leaf extract','plantago major leaf extract','INT'),
('Plantago major seed extract','plantago major seed extract','INT'),
('Plantago ovata seed extract','plantago ovata seed extract','INT'),
('Plantago seed','plantago seed','INT'),
('plantain preparation','plantain preparation','INT'),
('Plantanus orientalis whole extract','plantanus orientalis whole extract','INT'),
('plasacryl T20','plasacryl t20','INT'),
('plasma protein fraction','plasma protein fraction','INT'),
('plasmin','plasmin','INT'),
('plasminogen','plasminogen','INT'),
('Plasmodium malariae','plasmodium malariae','INT'),
('Platanus occidentalis bark extract','platanus occidentalis bark extract','INT'),
('Platanus occidentalis whole extract','platanus occidentalis whole extract','INT'),
('Platanus x acerifolia whole extract','platanus x acerifolia whole extract','INT'),
('platelet glycoprotein VI','platelet glycoprotein vi','INT'),
('platinic chloride','platinic chloride','INT'),
('platinic iodide','platinic iodide','INT'),
('platinum','platinum','INT'),
('Platostoma chinensis whole extract','platostoma chinensis whole extract','INT'),
('Platycladus orientalis leaf extract','platycladus orientalis leaf extract','INT'),
('Platycladus orientalis pollen extract','platycladus orientalis pollen extract','INT'),
('Platycladus orientalis seed extract','platycladus orientalis seed extract','INT'),
('Platycladus orientalis whole extract','platycladus orientalis whole extract','INT'),
('Platycodon grandiflorum leaf extract','platycodon grandiflorum leaf extract','INT'),
('Platycodon grandiflorum root extract','platycodon grandiflorum root extract','INT'),
('Platycodon grandiflorus whole extract','platycodon grandiflorus whole extract','INT'),
('plazomicin','plazomicin','INT'),
('pLDLR-Neo','pldlr-neo','INT'),
('plecanatide','plecanatide','INT'),
('Plectranthus amboinicus whole extract','plectranthus amboinicus whole extract','INT'),
('Plectranthus barbatus root extract','plectranthus barbatus root extract','INT'),
('Plectranthus barbatus whole extract','plectranthus barbatus whole extract','INT'),
('Pleiogynium timoriense fruit extract','pleiogynium timoriense fruit extract','INT'),
('Pleione yunnanensis whole extract','pleione yunnanensis whole extract','INT'),
('Pleospora betae allergenic extract','pleospora betae allergenic extract','INT'),
('Pleospora herbarum allergenic extract','pleospora herbarum allergenic extract','INT'),
('Pleospora tarda allergenic extract','pleospora tarda allergenic extract','INT'),
('plerixafor','plerixafor','INT'),
('Pleurotus eryngii whole extract','pleurotus eryngii whole extract','INT'),
('plicamycin','plicamycin','INT'),
('plozasiran','plozasiran','INT'),
('Plukenetia volubilis seed oil','plukenetia volubilis seed oil','INT'),
('plum allergenic extract','plum allergenic extract','INT'),
('plum juice','plum juice','INT'),
('plum preparation','plum preparation','INT'),
('plum seed oil','plum seed oil','INT'),
('Plumeria alba flower extract','plumeria alba flower extract','INT'),
('Plumeria alba flower oil','plumeria alba flower oil','INT'),
('Plumeria rubra flower extract','plumeria rubra flower extract','INT'),
('Plumeria rubra whole extract','plumeria rubra whole extract','INT'),
('plutonium','plutonium','INT'),
('Poa pratensis allergenic extract','poa pratensis allergenic extract','INT'),
('Poa pratensis top extract','poa pratensis top extract','INT'),
('Podocarpus elatus fruit extract','podocarpus elatus fruit extract','INT'),
('Podocarpus elatus whole extract','podocarpus elatus whole extract','INT'),
('podofilox','podofilox','INT'),
('podophyllin','podophyllin','INT'),
('Podophyllum hexandrum root extract','podophyllum hexandrum root extract','INT'),
('Podophyllum hexandrum whole extract','podophyllum hexandrum whole extract','INT'),
('Podophyllum peltatum preparation','podophyllum peltatum preparation','INT'),
('Podophyllum peltatum root extract','podophyllum peltatum root extract','INT'),
('Podophyllum preparation','podophyllum preparation','INT'),
('Pogostemon cablin top extract','pogostemon cablin top extract','INT'),
('Pogostemon cablin whole extract','pogostemon cablin whole extract','INT'),
('poison ivy extract','poison ivy extract','INT'),
('pokeweed preparation','pokeweed preparation','INT'),
('polacrilin','polacrilin','INT'),
('polacrillin','polacrillin','INT'),
('polaprezinc','polaprezinc','INT'),
('polarcrillin','polarcrillin','INT'),
('polatuzumab vedotin','polatuzumab vedotin','INT'),
('polawax polysorbate','polawax polysorbate','INT'),
('poldine','poldine','INT'),
('policapram','policapram','INT'),
('policosanol','policosanol','INT'),
('policresulen','policresulen','INT'),
('polidocanol','polidocanol','INT'),
('polidronium','polidronium','INT'),
('polifeprosan 20','polifeprosan 20','INT'),
('polignate sodium','polignate sodium','INT')
) AS v(nom, dci, pays)
WHERE NOT EXISTS (SELECT 1 FROM medicaments m WHERE LOWER(m.nom) = LOWER(v.nom));
