-- rxnorm_batch_073.sql (80 rows)
INSERT INTO medicaments (nom, dci, pays)
SELECT v.nom, v.dci, v.pays FROM (VALUES
('gamma-aminobutyrate','gamma-aminobutyrate','INT'),
('gamma-cyclodextrin','gamma-cyclodextrin','INT'),
('gamma-interferon','gamma-interferon','INT'),
('gamma-linolenate','gamma-linolenate','INT'),
('gamma-methacryloxypropyltrimethoxysilane','gamma-methacryloxypropyltrimethoxysilane','INT'),
('gamma-nonalactone','gamma-nonalactone','INT'),
('gamma-octalactone','gamma-octalactone','INT'),
('gamma-oryzanol','gamma-oryzanol','INT'),
('gamma-terpinene','gamma-terpinene','INT'),
('gamma-undecalactone','gamma-undecalactone','INT'),
('ganaxolone','ganaxolone','INT'),
('ganciclovir','ganciclovir','INT'),
('ganirelix','ganirelix','INT'),
('Ganoderma lucidum stem extract','ganoderma lucidum stem extract','INT'),
('Ganoderma lucidum whole extract','ganoderma lucidum whole extract','INT'),
('garadacimab','garadacimab','INT'),
('Garcinia cambogia fruit extract','garcinia cambogia fruit extract','INT'),
('Garcinia cambogia preparation','garcinia cambogia preparation','INT'),
('Garcinia indica fruit extract','garcinia indica fruit extract','INT'),
('Garcinia indica seed butter extract','garcinia indica seed butter extract','INT'),
('Garcinia mangostana bark extract','garcinia mangostana bark extract','INT'),
('Garcinia mangostana fruit extract','garcinia mangostana fruit extract','INT'),
('Garcinia mangostana fruit rind extract','garcinia mangostana fruit rind extract','INT'),
('garden cress sprout extract','garden cress sprout extract','INT'),
('garden lady''s mantle extract','garden lady''s mantle extract','INT'),
('garden snail mucin preparation','garden snail mucin preparation','INT'),
('Gardenia cornuta whole extract','gardenia cornuta whole extract','INT'),
('Gardenia jasminoides flower extract','gardenia jasminoides flower extract','INT'),
('Gardenia jasminoides fruit extract','gardenia jasminoides fruit extract','INT'),
('Gardenia jasminoides whole extract','gardenia jasminoides whole extract','INT'),
('Gardenia resinifera resin','gardenia resinifera resin','INT'),
('Gardenia taitensis flower extract','gardenia taitensis flower extract','INT'),
('gardenia yellow extract','gardenia yellow extract','INT'),
('gardenian blue','gardenian blue','INT'),
('gardenoside','gardenoside','INT'),
('garlic allergenic extract','garlic allergenic extract','INT'),
('garlic powder','garlic powder','INT'),
('garlic preparation','garlic preparation','INT'),
('Garrys oak pollen extract','garrys oak pollen extract','INT'),
('gastric mucins','gastric mucins','INT'),
('Gastrodia elata tuber extract','gastrodia elata tuber extract','INT'),
('Gastrodia elata whole extract','gastrodia elata whole extract','INT'),
('gatifloxacin','gatifloxacin','INT'),
('Gaultheria procumbens leaf extract','gaultheria procumbens leaf extract','INT'),
('Gaultheria procumbens top extract','gaultheria procumbens top extract','INT'),
('Gaultheria procumbens whole extract','gaultheria procumbens whole extract','INT'),
('gefitinib','gefitinib','INT'),
('gekko gecko preparation','gekko gecko preparation','INT'),
('gelatin','gelatin','INT'),
('gelatin hydrolysate (porcine skin, MW 3000)','gelatin hydrolysate (porcine skin, mw 3000)','INT'),
('Gelidiella acerosa extract','gelidiella acerosa extract','INT'),
('Gelidium cartilagineum extract','gelidium cartilagineum extract','INT'),
('Gelidium sesquipedale extract','gelidium sesquipedale extract','INT'),
('gellan gum (high acyl)','gellan gum (high acyl)','INT'),
('gellan gum (low acyl)','gellan gum (low acyl)','INT'),
('Gelsemium sempervirens preparation','gelsemium sempervirens preparation','INT'),
('Gelsemium sempervirens root extract','gelsemium sempervirens root extract','INT'),
('Gelsemium sempervirens whole extract','gelsemium sempervirens whole extract','INT'),
('gemcitabine','gemcitabine','INT'),
('gemeprost','gemeprost','INT'),
('gemfibrozil','gemfibrozil','INT'),
('gemifloxacin','gemifloxacin','INT'),
('gemtuzumab ozogamicin','gemtuzumab ozogamicin','INT'),
('Genipa americana fruit extract','genipa americana fruit extract','INT'),
('Genista tinctoria extract','genista tinctoria extract','INT'),
('genistein','genistein','INT'),
('gentamicin','gentamicin','INT'),
('gentian preparation','gentian preparation','INT'),
('gentian violet','gentian violet','INT'),
('gentian, stemless, whole extract','gentian, stemless, whole extract','INT'),
('Gentiana crassicaulis whole extract','gentiana crassicaulis whole extract','INT'),
('Gentiana cruciata root extract','gentiana cruciata root extract','INT'),
('Gentiana lutea root extract','gentiana lutea root extract','INT'),
('Gentiana macrophylla root extract','gentiana macrophylla root extract','INT'),
('Gentiana manshurica root extract','gentiana manshurica root extract','INT'),
('Gentiana manshurica whole extract','gentiana manshurica whole extract','INT'),
('Gentiana urnula flower extract','gentiana urnula flower extract','INT'),
('Gentianella amarella flower extract','gentianella amarella flower extract','INT'),
('Gentianella amarella whole extract','gentianella amarella whole extract','INT'),
('Gentianella quinquefolia extract','gentianella quinquefolia extract','INT')
) AS v(nom, dci, pays)
WHERE NOT EXISTS (SELECT 1 FROM medicaments m WHERE LOWER(m.nom) = LOWER(v.nom));
