-- rxnorm_batch_175.sql (80 rows)
INSERT INTO medicaments (nom, dci, pays)
SELECT v.nom, v.dci, v.pays FROM (VALUES
('allantoin / coal tar / lactate','allantoin / coal tar / lactate','INT'),
('allantoin / colloidal oatmeal','allantoin / colloidal oatmeal','INT'),
('allantoin / dimethicone','allantoin / dimethicone','INT'),
('allantoin / dimethicone / menthol','allantoin / dimethicone / menthol','INT'),
('allantoin / diphenhydramine','allantoin / diphenhydramine','INT'),
('allantoin / dyclonine','allantoin / dyclonine','INT'),
('allantoin / glycerin','allantoin / glycerin','INT'),
('allantoin / glycerin / propylene glycol','allantoin / glycerin / propylene glycol','INT'),
('allantoin / hexachlorophene / squalene','allantoin / hexachlorophene / squalene','INT'),
('allantoin / hyaluronate','allantoin / hyaluronate','INT'),
('allantoin / ichthammol','allantoin / ichthammol','INT'),
('allantoin / lidocaine','allantoin / lidocaine','INT'),
('allantoin / lidocaine / menthol','allantoin / lidocaine / menthol','INT'),
('allantoin / lidocaine / petrolatum','allantoin / lidocaine / petrolatum','INT'),
('allantoin / menthol','allantoin / menthol','INT'),
('allantoin / petrolatum','allantoin / petrolatum','INT'),
('allantoin / petrolatum / zinc oxide','allantoin / petrolatum / zinc oxide','INT'),
('allantoin / pramoxine','allantoin / pramoxine','INT'),
('allantoin / sulfadiazine','allantoin / sulfadiazine','INT'),
('allantoin / thymol','allantoin / thymol','INT'),
('allantoin / zinc oxide','allantoin / zinc oxide','INT'),
('allobarbital / aminopyrine','allobarbital / aminopyrine','INT'),
('alloin / phenolphthalein','alloin / phenolphthalein','INT'),
('allopurinol / benzbromarone','allopurinol / benzbromarone','INT'),
('allopurinol / colchicine','allopurinol / colchicine','INT'),
('allopurinol / lesinurad','allopurinol / lesinurad','INT'),
('allopurinol / probenecid','allopurinol / probenecid','INT'),
('aloe polysaccharide / hydrocortisone / iodoquinol','aloe polysaccharide / hydrocortisone / iodoquinol','INT'),
('aloe polysaccharide / iodoquinol','aloe polysaccharide / iodoquinol','INT'),
('alogliptin / metformin','alogliptin / metformin','INT'),
('alogliptin / pioglitazone','alogliptin / pioglitazone','INT'),
('alpha hydroxy acids / urea','alpha hydroxy acids / urea','INT'),
('alpha tocopherol / cholecalciferol','alpha tocopherol / cholecalciferol','INT'),
('alpha tocopherol / cholecalciferol / vitamin A','alpha tocopherol / cholecalciferol / vitamin a','INT'),
('alpha tocopherol / levomenthol','alpha tocopherol / levomenthol','INT'),
('alpha tocopherol / silicon dioxide','alpha tocopherol / silicon dioxide','INT'),
('alpha-D-galactosidase enzyme / bromelains / papain','alpha-d-galactosidase enzyme / bromelains / papain','INT'),
('alpha-D-galactosidase enzyme / lactase','alpha-d-galactosidase enzyme / lactase','INT'),
('alprazolam / sulpiride','alprazolam / sulpiride','INT'),
('althiazide / spironolactone','althiazide / spironolactone','INT'),
('alum, potassium / lidocaine','alum, potassium / lidocaine','INT'),
('aluminum acetate / benzethonium','aluminum acetate / benzethonium','INT'),
('aluminum acetate / boric acid','aluminum acetate / boric acid','INT'),
('aluminum acetate / camphor / menthol / phenol','aluminum acetate / camphor / menthol / phenol','INT'),
('aluminum acetate / zinc oxide','aluminum acetate / zinc oxide','INT'),
('aluminum acetotartrate / nonoxynol-9','aluminum acetotartrate / nonoxynol-9','INT'),
('aluminum chloride / potassium chlorate','aluminum chloride / potassium chlorate','INT'),
('aluminum chlorohydrate / neomycin','aluminum chlorohydrate / neomycin','INT'),
('aluminum hydroxide / aluminum subacetate','aluminum hydroxide / aluminum subacetate','INT'),
('aluminum hydroxide / aspirin / caffeine','aluminum hydroxide / aspirin / caffeine','INT'),
('aluminum hydroxide / aspirin / magnesium hydroxide','aluminum hydroxide / aspirin / magnesium hydroxide','INT'),
('aluminum hydroxide / calcium carbonate','aluminum hydroxide / calcium carbonate','INT'),
('aluminum hydroxide / carbenoxolone','aluminum hydroxide / carbenoxolone','INT'),
('aluminum hydroxide / magnesium carbonate','aluminum hydroxide / magnesium carbonate','INT'),
('aluminum hydroxide / magnesium hydroxide','aluminum hydroxide / magnesium hydroxide','INT'),
('aluminum hydroxide / magnesium oxide','aluminum hydroxide / magnesium oxide','INT'),
('aluminum hydroxide / magnesium trisilicate','aluminum hydroxide / magnesium trisilicate','INT'),
('aluminum hydroxide / mineral oil','aluminum hydroxide / mineral oil','INT'),
('aluminum hydroxide / niflumic acid / orphenadrine','aluminum hydroxide / niflumic acid / orphenadrine','INT'),
('aluminum hydroxide / silicon dioxide','aluminum hydroxide / silicon dioxide','INT'),
('aluminum hydroxide / simethicone','aluminum hydroxide / simethicone','INT'),
('aluminum hydroxide / theophylline','aluminum hydroxide / theophylline','INT'),
('aluminum magnesium silicate / calcium carbonate','aluminum magnesium silicate / calcium carbonate','INT'),
('aluminum magnesium silicate / magnesium hydroxide','aluminum magnesium silicate / magnesium hydroxide','INT'),
('aluminum oxide / magnesium hydroxide','aluminum oxide / magnesium hydroxide','INT'),
('aluminum oxide / simethicone','aluminum oxide / simethicone','INT'),
('aluminum oxide / triclosan','aluminum oxide / triclosan','INT'),
('aluminum potassium sulfate / phenol','aluminum potassium sulfate / phenol','INT'),
('aluminum subacetate / boric acid','aluminum subacetate / boric acid','INT'),
('aluminum sulfate / calcium acetate','aluminum sulfate / calcium acetate','INT'),
('aluminum sulfate / lidocaine','aluminum sulfate / lidocaine','INT'),
('alverine / karaya gum','alverine / karaya gum','INT'),
('alverine / simethicone','alverine / simethicone','INT'),
('ambroxol / amoxicillin','ambroxol / amoxicillin','INT'),
('ambroxol / ampicillin','ambroxol / ampicillin','INT'),
('ambroxol / cefadroxil','ambroxol / cefadroxil','INT'),
('ambroxol / cephalexin','ambroxol / cephalexin','INT'),
('ambroxol / chlophedianol','ambroxol / chlophedianol','INT'),
('ambroxol / clenbuterol','ambroxol / clenbuterol','INT'),
('ambroxol / clobutinol','ambroxol / clobutinol','INT')
) AS v(nom, dci, pays)
WHERE NOT EXISTS (SELECT 1 FROM medicaments m WHERE LOWER(m.nom) = LOWER(v.nom));
