-- rxnorm_batch_169.sql (80 rows)
INSERT INTO medicaments (nom, dci, pays)
SELECT v.nom, v.dci, v.pays FROM (VALUES
('western juniper pollen extract','western juniper pollen extract','INT'),
('western larch pollen extract','western larch pollen extract','INT'),
('western ragweed pollen extract','western ragweed pollen extract','INT'),
('western sycamore pollen extract','western sycamore pollen extract','INT'),
('western waterhemp pollen extract','western waterhemp pollen extract','INT'),
('western wheatgrass pollen extract','western wheatgrass pollen extract','INT'),
('western white pine pollen extract','western white pine pollen extract','INT'),
('western yellow jacket venom protein','western yellow jacket venom protein','INT'),
('wheat bran allergenic extract','wheat bran allergenic extract','INT'),
('wheat bran extract','wheat bran extract','INT'),
('wheat dextrin','wheat dextrin','INT'),
('wheat germ oil','wheat germ oil','INT'),
('wheat germ oil unsaponifiables','wheat germ oil unsaponifiables','INT'),
('wheat germ preparation','wheat germ preparation','INT'),
('wheat gluten extract','wheat gluten extract','INT'),
('wheat middlings extract','wheat middlings extract','INT'),
('wheat pollen extract','wheat pollen extract','INT'),
('wheat preparation','wheat preparation','INT'),
('wheat smut allergenic extract','wheat smut allergenic extract','INT'),
('wheat sprout extract','wheat sprout extract','INT'),
('whey protein hydrolysate','whey protein hydrolysate','INT'),
('white (mexican) dock pollen extract','white (mexican) dock pollen extract','INT'),
('white alder pollen extract','white alder pollen extract','INT'),
('white ash pollen extract','white ash pollen extract','INT'),
('white bryony extract','white bryony extract','INT'),
('white catfish allergenic extract','white catfish allergenic extract','INT'),
('white currant fruit extract','white currant fruit extract','INT'),
('white fish allergenic extract','white fish allergenic extract','INT'),
('white hickory pollen extract','white hickory pollen extract','INT'),
('white kidney bean allergenic extract','white kidney bean allergenic extract','INT'),
('white kidney bean extract','white kidney bean extract','INT'),
('white mulberry extract','white mulberry extract','INT'),
('white mulberry pollen extract','white mulberry pollen extract','INT'),
('white mustard seed allergenic extract','white mustard seed allergenic extract','INT'),
('white mustard seed extract','white mustard seed extract','INT'),
('white oak bark extract','white oak bark extract','INT'),
('white oak pollen extract','white oak pollen extract','INT'),
('white pepper allergenic extract','white pepper allergenic extract','INT'),
('white pepper oil','white pepper oil','INT'),
('white pine oil','white pine oil','INT'),
('white poplar pollen extract','white poplar pollen extract','INT'),
('white poplar whole extract','white poplar whole extract','INT'),
('white rice extract','white rice extract','INT'),
('white seedless grape allergenic extract','white seedless grape allergenic extract','INT'),
('white spirit type 1','white spirit type 1','INT'),
('white sweet clover pollen extract','white sweet clover pollen extract','INT'),
('white sweetclover top extract','white sweetclover top extract','INT'),
('white tea extract','white tea extract','INT'),
('white wax','white wax','INT'),
('white willow pollen extract','white willow pollen extract','INT'),
('white-tailed deer hair extract','white-tailed deer hair extract','INT'),
('whole eriodictyon californicum extract','whole eriodictyon californicum extract','INT'),
('whole Melia azederach extract','whole melia azederach extract','INT'),
('whole wheat allergenic extract','whole wheat allergenic extract','INT'),
('whortleberry substance','whortleberry substance','INT'),
('wild oat whole extract','wild oat whole extract','INT'),
('wild thyme extract','wild thyme extract','INT'),
('wild yam extract','wild yam extract','INT'),
('wine grape allergenic extract','wine grape allergenic extract','INT'),
('wine grape extract','wine grape extract','INT'),
('wine grape juice','wine grape juice','INT'),
('wing scale pollen extract','wing scale pollen extract','INT'),
('winged elm whole extract','winged elm whole extract','INT'),
('winter savory oil','winter savory oil','INT'),
('winterfat pollen extract','winterfat pollen extract','INT'),
('witch hazel','witch hazel','INT'),
('Withania somnifera flower extract','withania somnifera flower extract','INT'),
('Withania somnifera leaf extract','withania somnifera leaf extract','INT'),
('Withania somnifera root extract','withania somnifera root extract','INT'),
('Withania somnifera whole extract','withania somnifera whole extract','INT'),
('withanolide D','withanolide d','INT'),
('wogonin','wogonin','INT'),
('Wolfiporia cocos sclerotium extract','wolfiporia cocos sclerotium extract','INT'),
('Wolfiporia extensa whole extract','wolfiporia extensa whole extract','INT'),
('wood ant preparation','wood ant preparation','INT'),
('wood tar hydrocarbon distillate','wood tar hydrocarbon distillate','INT'),
('wormwood extract','wormwood extract','INT'),
('wormwood oil','wormwood oil','INT'),
('wormwood sage pollen extract','wormwood sage pollen extract','INT'),
('Wyethia helenioides root extract','wyethia helenioides root extract','INT')
) AS v(nom, dci, pays)
WHERE NOT EXISTS (SELECT 1 FROM medicaments m WHERE LOWER(m.nom) = LOWER(v.nom));
