-- rxnorm_batch_118.sql (80 rows)
INSERT INTO medicaments (nom, dci, pays)
SELECT v.nom, v.dci, v.pays FROM (VALUES
('p-aminohippurate','p-aminohippurate','INT'),
('p-anisaldehyde','p-anisaldehyde','INT'),
('p-dodecylbenzenesulfonic acid','p-dodecylbenzenesulfonic acid','INT'),
('p-hydroxyamphetamine','p-hydroxyamphetamine','INT'),
('p-menthane-3,8-diol','p-menthane-3,8-diol','INT'),
('p-methylaminophenol sulfate','p-methylaminophenol sulfate','INT'),
('p-nitrobiphenyl','p-nitrobiphenyl','INT'),
('Pacific cod preparation','pacific cod preparation','INT'),
('Pacific halibut allergenic extract','pacific halibut allergenic extract','INT'),
('Pacific ocean perch allergenic extract','pacific ocean perch allergenic extract','INT'),
('Pacific oyster preparation','pacific oyster preparation','INT'),
('Pacific salmon allergenic extract','pacific salmon allergenic extract','INT'),
('Packera aurea extract','packera aurea extract','INT'),
('paclitaxel','paclitaxel','INT'),
('pacritinib','pacritinib','INT'),
('Padang cassia bark extract','padang cassia bark extract','INT'),
('Padang cassia oil','padang cassia oil','INT'),
('padimate A','padimate a','INT'),
('padimate-O','padimate-o','INT'),
('Padina pavonica extract','padina pavonica extract','INT'),
('Paecilomyces variotii allergenic extract','paecilomyces variotii allergenic extract','INT'),
('Paeonia anomala root extract','paeonia anomala root extract','INT'),
('Paeonia californica whole extract','paeonia californica whole extract','INT'),
('Paeonia lactiflora flower extract','paeonia lactiflora flower extract','INT'),
('Paeonia lactiflora root extract','paeonia lactiflora root extract','INT'),
('paeonia lactiflora root oil','paeonia lactiflora root oil','INT'),
('Paeonia lactiflora whole extract','paeonia lactiflora whole extract','INT'),
('Paeonia obovata root extract','paeonia obovata root extract','INT'),
('Paeonia officinalis root extract','paeonia officinalis root extract','INT'),
('Paeonia officinalis whole extract','paeonia officinalis whole extract','INT'),
('Paeonia suffruticosa flower oil','paeonia suffruticosa flower oil','INT'),
('Paeonia suffruticosa root bark extract','paeonia suffruticosa root bark extract','INT'),
('Paeonia suffruticosa root extract','paeonia suffruticosa root extract','INT'),
('Paeonia veitchii root extract','paeonia veitchii root extract','INT'),
('Paeonia x suffruticosa seed extract','paeonia x suffruticosa seed extract','INT'),
('pafolacianine','pafolacianine','INT'),
('pafuramidine','pafuramidine','INT'),
('palbociclib','palbociclib','INT'),
('pale dock pollen extract','pale dock pollen extract','INT'),
('palifermin','palifermin','INT'),
('paliperidone','paliperidone','INT'),
('palivizumab','palivizumab','INT'),
('palladium','palladium','INT'),
('palm acid','palm acid','INT'),
('palm kernel acid','palm kernel acid','INT'),
('palm kernel glycerides','palm kernel glycerides','INT'),
('palm kernel oil','palm kernel oil','INT'),
('palm kernelate','palm kernelate','INT'),
('palm oil','palm oil','INT'),
('palmarosa oil','palmarosa oil','INT'),
('palmate','palmate','INT'),
('palmatine','palmatine','INT'),
('palmidrol','palmidrol','INT'),
('palmitamidopropyltrimonium','palmitamidopropyltrimonium','INT'),
('palmitate','palmitate','INT'),
('palmitoleate','palmitoleate','INT'),
('palmitostearate','palmitostearate','INT'),
('palmitoyl collagen acid','palmitoyl collagen acid','INT'),
('palmitoyl dipeptide-7','palmitoyl dipeptide-7','INT'),
('palmitoyl fragment','palmitoyl fragment','INT'),
('palmitoyl glutamate','palmitoyl glutamate','INT'),
('palmitoyl glycine','palmitoyl glycine','INT'),
('palmitoyl hexapeptide-12','palmitoyl hexapeptide-12','INT'),
('palmitoyl isoleucine','palmitoyl isoleucine','INT'),
('palmitoyl lysyldioxymethionyllysine','palmitoyl lysyldioxymethionyllysine','INT'),
('palmitoyl myristyl serinate','palmitoyl myristyl serinate','INT'),
('palmitoyl oligopeptide','palmitoyl oligopeptide','INT'),
('palmitoyl pentapeptide-4','palmitoyl pentapeptide-4','INT'),
('palmitoyl proline','palmitoyl proline','INT'),
('palmitoyl sarcosinate','palmitoyl sarcosinate','INT'),
('palmitoyl sh-tripeptide-4 amide','palmitoyl sh-tripeptide-4 amide','INT'),
('palmitoyl tetrapeptide-10','palmitoyl tetrapeptide-10','INT'),
('palmitoyl tetrapeptide-7','palmitoyl tetrapeptide-7','INT'),
('palmitoyl tetrapeptide-94','palmitoyl tetrapeptide-94','INT'),
('palmitoyl tetrapeptide-95','palmitoyl tetrapeptide-95','INT'),
('palmitoyl tripeptide-1','palmitoyl tripeptide-1','INT'),
('palmitoyl tripeptide-1 acetate','palmitoyl tripeptide-1 acetate','INT'),
('palmitoyl tripeptide-5','palmitoyl tripeptide-5','INT'),
('palmitoyl tripeptide-53 amide','palmitoyl tripeptide-53 amide','INT'),
('palmitoyl tripeptide-54 amide','palmitoyl tripeptide-54 amide','INT')
) AS v(nom, dci, pays)
WHERE NOT EXISTS (SELECT 1 FROM medicaments m WHERE LOWER(m.nom) = LOWER(v.nom));
