-- rxnorm_batch_045.sql (80 rows)
INSERT INTO medicaments (nom, dci, pays)
SELECT v.nom, v.dci, v.pays FROM (VALUES
('clothiapine','clothiapine','INT'),
('clotiazepam','clotiazepam','INT'),
('cloticasone','cloticasone','INT'),
('clotrimazole','clotrimazole','INT'),
('clove allergenic extract','clove allergenic extract','INT'),
('clove leaf extract','clove leaf extract','INT'),
('clove leaf oil','clove leaf oil','INT'),
('clove oil','clove oil','INT'),
('clove preparation','clove preparation','INT'),
('clove stem oil','clove stem oil','INT'),
('cloxacillin','cloxacillin','INT'),
('cloxazolam','cloxazolam','INT'),
('clozapine','clozapine','INT'),
('cluster fig extract','cluster fig extract','INT'),
('Cnidium monnieri fruit extract','cnidium monnieri fruit extract','INT'),
('Cnidium monnieri fruit oil','cnidium monnieri fruit oil','INT'),
('Cnidium monnieri whole extract','cnidium monnieri whole extract','INT'),
('Cnidium officinale root extract','cnidium officinale root extract','INT'),
('Cnidium officinale root oil','cnidium officinale root oil','INT'),
('Cnidium officinale whole extract','cnidium officinale whole extract','INT'),
('Cnidium seed extract','cnidium seed extract','INT'),
('coachwhip stem extract','coachwhip stem extract','INT'),
('coal tar','coal tar','INT'),
('coast live oak pollen extract','coast live oak pollen extract','INT'),
('coast maple pollen extract','coast maple pollen extract','INT'),
('coast sage pollen extract','coast sage pollen extract','INT'),
('cobalt','cobalt','INT'),
('cobalt acetate','cobalt acetate','INT'),
('cobalt gluconate','cobalt gluconate','INT'),
('cobalt oxide','cobalt oxide','INT'),
('cobalt sulfate','cobalt sulfate','INT'),
('cobalt titanium oxide','cobalt titanium oxide','INT'),
('cobaltous carbonate','cobaltous carbonate','INT'),
('cobaltous cation','cobaltous cation','INT'),
('cobaltous chloride','cobaltous chloride','INT'),
('cobaltous nitrate','cobaltous nitrate','INT'),
('cobaltous phosphate','cobaltous phosphate','INT'),
('cobamamide','cobamamide','INT'),
('cobicistat','cobicistat','INT'),
('cobimetinib','cobimetinib','INT'),
('cocaine','cocaine','INT'),
('cocaine esterase','cocaine esterase','INT'),
('cocamide','cocamide','INT'),
('cocamidopropyl betaine','cocamidopropyl betaine','INT'),
('cocamidopropyl dimethylamine','cocamidopropyl dimethylamine','INT'),
('cocamidopropyl hydroxysultaine','cocamidopropyl hydroxysultaine','INT'),
('cocamidopropyl PG-dimonium chloride phosphate','cocamidopropyl pg-dimonium chloride phosphate','INT'),
('cocamidopropyl propylene glycol-dimonium chloride','cocamidopropyl propylene glycol-dimonium chloride','INT'),
('cocamidopropylamine oxide','cocamidopropylamine oxide','INT'),
('cocamine','cocamine','INT'),
('cocamine oxide','cocamine oxide','INT'),
('Coccidioides immitis spherule','coccidioides immitis spherule','INT'),
('coccidioidin','coccidioidin','INT'),
('Coccinella septempunctata preparation','coccinella septempunctata preparation','INT'),
('Coccinia grandis fruit extract','coccinia grandis fruit extract','INT'),
('Coccinia grandis leaf extract','coccinia grandis leaf extract','INT'),
('Coccinia grandis whole extract','coccinia grandis whole extract','INT'),
('coceth-7','coceth-7','INT'),
('coceth-7 carboxylic acid','coceth-7 carboxylic acid','INT'),
('cochineal','cochineal','INT'),
('Cochlearia officinalis flowering top extract','cochlearia officinalis flowering top extract','INT'),
('Cochlearia officinalis leaf extract','cochlearia officinalis leaf extract','INT'),
('Cochliobolus lunatus allergenic extract','cochliobolus lunatus allergenic extract','INT'),
('Cochliobolus sativus allergenic extract','cochliobolus sativus allergenic extract','INT'),
('cochliobolus spicifer allergenic extract','cochliobolus spicifer allergenic extract','INT'),
('cocklebur extract','cocklebur extract','INT'),
('cocklebur pollen extract','cocklebur pollen extract','INT'),
('coco diethanolamide','coco diethanolamide','INT'),
('coco diisopropanolamide','coco diisopropanolamide','INT'),
('coco glucoside','coco glucoside','INT'),
('coco monoethanolamide','coco monoethanolamide','INT'),
('coco monoisopropanolamide','coco monoisopropanolamide','INT'),
('coco-betaine','coco-betaine','INT'),
('coco-caprylate','coco-caprylate','INT'),
('coco-caprylate-caprate','coco-caprylate-caprate','INT'),
('coco-glycerides','coco-glycerides','INT'),
('coco-oleamidopropyl betaine','coco-oleamidopropyl betaine','INT'),
('coco-sulfate','coco-sulfate','INT'),
('cocoa bean allergenic extract','cocoa bean allergenic extract','INT'),
('cocoa butter','cocoa butter','INT')
) AS v(nom, dci, pays)
WHERE NOT EXISTS (SELECT 1 FROM medicaments m WHERE LOWER(m.nom) = LOWER(v.nom));
