-- rxnorm_batch_043.sql (80 rows)
INSERT INTO medicaments (nom, dci, pays)
SELECT v.nom, v.dci, v.pays FROM (VALUES
('citiolone','citiolone','INT'),
('citraconate','citraconate','INT'),
('citral','citral','INT'),
('citral propylene glycol acetal','citral propylene glycol acetal','INT'),
('citrate','citrate','INT'),
('citric acid','citric acid','INT'),
('citric acid acetate','citric acid acetate','INT'),
('citric acid isopropyl ether','citric acid isopropyl ether','INT'),
('Citrobacter koseri','citrobacter koseri','INT'),
('citronella oil','citronella oil','INT'),
('citronellal','citronellal','INT'),
('citronellene lactone','citronellene lactone','INT'),
('citronellol acetate, (R)-','citronellol acetate, (r)-','INT'),
('citronellol acetate, (S)-','citronellol acetate, (s)-','INT'),
('citronellyl acetate','citronellyl acetate','INT'),
('citronellyl methylcrotonate','citronellyl methylcrotonate','INT'),
('citronellyl nitrile, (+/-)','citronellyl nitrile, (+/-)','INT'),
('citronitrile','citronitrile','INT'),
('citrulline','citrulline','INT'),
('Citrullus colocynthis fruit extract','citrullus colocynthis fruit extract','INT'),
('Citrullus colocynthis fruit pulp extract','citrullus colocynthis fruit pulp extract','INT'),
('Citrullus colocynthis whole extract','citrullus colocynthis whole extract','INT'),
('Citrullus lanatus var. citroides whole extract','citrullus lanatus var. citroides whole extract','INT'),
('Citrullus lanatus var. lanatus whole extract','citrullus lanatus var. lanatus whole extract','INT'),
('Citrus aurantiifolia flower extract','citrus aurantiifolia flower extract','INT'),
('Citrus aurantiifolia fruit oil','citrus aurantiifolia fruit oil','INT'),
('Citrus aurantiifolia leaf oil','citrus aurantiifolia leaf oil','INT'),
('Citrus aurantiifolia seed oil','citrus aurantiifolia seed oil','INT'),
('Citrus aurantiifolia whole extract','citrus aurantiifolia whole extract','INT'),
('Citrus aurantium flower extract','citrus aurantium flower extract','INT'),
('Citrus aurantium flower oil','citrus aurantium flower oil','INT'),
('Citrus aurantium flower wax','citrus aurantium flower wax','INT'),
('Citrus aurantium fruit extract','citrus aurantium fruit extract','INT'),
('Citrus aurantium fruit oil','citrus aurantium fruit oil','INT'),
('Citrus aurantium fruit rind extract','citrus aurantium fruit rind extract','INT'),
('Citrus aurantium leafy twig extract','citrus aurantium leafy twig extract','INT'),
('Citrus aurantium leafy twig oil','citrus aurantium leafy twig oil','INT'),
('Citrus aurantium seed extract','citrus aurantium seed extract','INT'),
('Citrus bergamia leaf extract','citrus bergamia leaf extract','INT'),
('Citrus bergamia leaf oil','citrus bergamia leaf oil','INT'),
('Citrus bergamia whole extract','citrus bergamia whole extract','INT'),
('Citrus japonica fruit extract','citrus japonica fruit extract','INT'),
('citrus juice','citrus juice','INT'),
('Citrus junos fruit extract','citrus junos fruit extract','INT'),
('Citrus junos fruit oil','citrus junos fruit oil','INT'),
('citrus junos fruit rind extract','citrus junos fruit rind extract','INT'),
('Citrus junos seed extract','citrus junos seed extract','INT'),
('Citrus limon flowering top oil','citrus limon flowering top oil','INT'),
('Citrus limon fruit oil','citrus limon fruit oil','INT'),
('Citrus limon seed oil','citrus limon seed oil','INT'),
('Citrus limon whole extract','citrus limon whole extract','INT'),
('Citrus maxima fruit oil','citrus maxima fruit oil','INT'),
('Citrus maxima fruit rind extract','citrus maxima fruit rind extract','INT'),
('Citrus maxima fruit rind oil','citrus maxima fruit rind oil','INT'),
('Citrus maxima leaf extract','citrus maxima leaf extract','INT'),
('Citrus maxima seed extract','citrus maxima seed extract','INT'),
('Citrus maxima seed oil','citrus maxima seed oil','INT'),
('Citrus medica fruit extract','citrus medica fruit extract','INT'),
('Citrus medica var. sarcodactylis whole extract','citrus medica var. sarcodactylis whole extract','INT'),
('Citrus medica whole extract','citrus medica whole extract','INT'),
('Citrus nobilis extract','citrus nobilis extract','INT'),
('Citrus nobilis whole extract','citrus nobilis whole extract','INT'),
('Citrus paradisi fruit oil','citrus paradisi fruit oil','INT'),
('Citrus paradisi whole extract','citrus paradisi whole extract','INT'),
('citrus pectin','citrus pectin','INT'),
('citrus pectin extract','citrus pectin extract','INT'),
('Citrus reticulata fruit oil','citrus reticulata fruit oil','INT'),
('Citrus reticulata leaf oil','citrus reticulata leaf oil','INT'),
('Citrus reticulata whole extract','citrus reticulata whole extract','INT'),
('Citrus sinensis flower extract','citrus sinensis flower extract','INT'),
('Citrus sinensis flower oil','citrus sinensis flower oil','INT'),
('Citrus sinensis flower wax','citrus sinensis flower wax','INT'),
('Citrus sinensis fruit oil','citrus sinensis fruit oil','INT'),
('Citrus sinensis leaf extract','citrus sinensis leaf extract','INT'),
('Citrus sinensis seed oil','citrus sinensis seed oil','INT'),
('citrus sinensis whole extract','citrus sinensis whole extract','INT'),
('Cladanthus mixtus flower volatile oil','cladanthus mixtus flower volatile oil','INT'),
('Cladanthus mixtus whole extract','cladanthus mixtus whole extract','INT'),
('Cladonia cristatella whole extract','cladonia cristatella whole extract','INT'),
('Cladonia rangiferina whole extract','cladonia rangiferina whole extract','INT')
) AS v(nom, dci, pays)
WHERE NOT EXISTS (SELECT 1 FROM medicaments m WHERE LOWER(m.nom) = LOWER(v.nom));
