-- rxnorm_batch_122.sql (80 rows)
INSERT INTO medicaments (nom, dci, pays)
SELECT v.nom, v.dci, v.pays FROM (VALUES
('pentoxifylline','pentoxifylline','INT'),
('pentylamine','pentylamine','INT'),
('pentylenetetrazole','pentylenetetrazole','INT'),
('peoniflorin','peoniflorin','INT'),
('pepper extract','pepper extract','INT'),
('peppermint allergenic extract','peppermint allergenic extract','INT'),
('peppermint flowering top extract','peppermint flowering top extract','INT'),
('peppermint oil','peppermint oil','INT'),
('peppermint oil terpeneless','peppermint oil terpeneless','INT'),
('peppermint preparation','peppermint preparation','INT'),
('pepsin A','pepsin a','INT'),
('peptide-T','peptide-t','INT'),
('peptone,dried','peptone,dried','INT'),
('peptones','peptones','INT'),
('Peptostreptococcus anaerobius','peptostreptococcus anaerobius','INT'),
('Peptostreptococcus anaerobius DNA','peptostreptococcus anaerobius dna','INT'),
('peracetic acid','peracetic acid','INT'),
('peramivir','peramivir','INT'),
('perampanel','perampanel','INT'),
('perazine','perazine','INT'),
('perch allergenic extract','perch allergenic extract','INT'),
('perennial rye grass pollen extract','perennial rye grass pollen extract','INT'),
('perflenapent','perflenapent','INT'),
('perflexane','perflexane','INT'),
('perflunafene','perflunafene','INT'),
('perfluorodimethylcyclohexane','perfluorodimethylcyclohexane','INT'),
('perfluorohexyloctane','perfluorohexyloctane','INT'),
('perfluoromethylcyclopentane','perfluoromethylcyclopentane','INT'),
('perfluoromethyldecalin','perfluoromethyldecalin','INT'),
('perfluorooctyl triethoxysilane','perfluorooctyl triethoxysilane','INT'),
('perfluoroperhydrophenanthrene','perfluoroperhydrophenanthrene','INT'),
('perflutren','perflutren','INT'),
('pergolide','pergolide','INT'),
('perhexiline','perhexiline','INT'),
('periciazine','periciazine','INT'),
('Perilla frutescens fruit extract','perilla frutescens fruit extract','INT'),
('Perilla frutescens leaf extract','perilla frutescens leaf extract','INT'),
('Perilla frutescens leaf oil','perilla frutescens leaf oil','INT'),
('Perilla frutescens seed extract','perilla frutescens seed extract','INT'),
('Perilla frutescens seed oil','perilla frutescens seed oil','INT'),
('Perilla frutescens whole extract','perilla frutescens whole extract','INT'),
('perillaldehyde','perillaldehyde','INT'),
('perindopril','perindopril','INT'),
('perindoprilat','perindoprilat','INT'),
('Periplaneta australasiae extract','periplaneta australasiae extract','INT'),
('Periploca sepium root bark extract','periploca sepium root bark extract','INT'),
('perlite','perlite','INT'),
('permanganate','permanganate','INT'),
('permethrin','permethrin','INT'),
('peroxidase','peroxidase','INT'),
('perphenazine','perphenazine','INT'),
('Persea americana leaf extract','persea americana leaf extract','INT'),
('Persea americana seed butter extract','persea americana seed butter extract','INT'),
('Persea americana whole extract','persea americana whole extract','INT'),
('Persicaria filiformis flowering top extract','persicaria filiformis flowering top extract','INT'),
('Persicaria punctata extract','persicaria punctata extract','INT'),
('Persicaria tinctoria leaf extract','persicaria tinctoria leaf extract','INT'),
('Persicaria tinctoria top extract','persicaria tinctoria top extract','INT'),
('persimmon extract','persimmon extract','INT'),
('pertussis vaccine','pertussis vaccine','INT'),
('pertuzumab','pertuzumab','INT'),
('Peruvian balsam','peruvian balsam','INT'),
('Peruvian pepper tree pollen extract','peruvian pepper tree pollen extract','INT'),
('Petasites amplus whole extract','petasites amplus whole extract','INT'),
('Petasites fragrans extract','petasites fragrans extract','INT'),
('Petasites hybridus leaf extract','petasites hybridus leaf extract','INT'),
('Petasites hybridus root extract','petasites hybridus root extract','INT'),
('Petasites japonicus root extract','petasites japonicus root extract','INT'),
('Petiveria alliacea preparation','petiveria alliacea preparation','INT'),
('Petiveria alliacea root extract','petiveria alliacea root extract','INT'),
('Petiveria alliacea whole extract','petiveria alliacea whole extract','INT'),
('petrolatum','petrolatum','INT'),
('petroleum alkylate','petroleum alkylate','INT'),
('petroleum distillate','petroleum distillate','INT'),
('petroleum preparation','petroleum preparation','INT'),
('Petroselinum crispum extract','petroselinum crispum extract','INT'),
('Petroselinum crispum root extract','petroselinum crispum root extract','INT'),
('Peucedanum ostruthium leaf extract','peucedanum ostruthium leaf extract','INT'),
('Peucedanum praeruptorum root extract','peucedanum praeruptorum root extract','INT'),
('Peumus boldus leaf extract','peumus boldus leaf extract','INT')
) AS v(nom, dci, pays)
WHERE NOT EXISTS (SELECT 1 FROM medicaments m WHERE LOWER(m.nom) = LOWER(v.nom));
