-- rxnorm_batch_167.sql (80 rows)
INSERT INTO medicaments (nom, dci, pays)
SELECT v.nom, v.dci, v.pays FROM (VALUES
('Verbascum densiflorum flower extract','verbascum densiflorum flower extract','INT'),
('Verbascum densiflorum flowering top extract','verbascum densiflorum flowering top extract','INT'),
('Verbascum densiflorum leaf extract','verbascum densiflorum leaf extract','INT'),
('Verbascum densiflorum whole extract','verbascum densiflorum whole extract','INT'),
('Verbascum phlomoides flower extract','verbascum phlomoides flower extract','INT'),
('Verbascum thapsus extract','verbascum thapsus extract','INT'),
('Verbascum thapsus leaf extract','verbascum thapsus leaf extract','INT'),
('Verbena extract','verbena extract','INT'),
('Verbena hastata top extract','verbena hastata top extract','INT'),
('Verbena officinalis extract','verbena officinalis extract','INT'),
('Verbena officinalis flowering top extract','verbena officinalis flowering top extract','INT'),
('Verbena officinalis leaf extract','verbena officinalis leaf extract','INT'),
('verdinexor','verdinexor','INT'),
('vericiguat','vericiguat','INT'),
('Vernicia fordii seed oil','vernicia fordii seed oil','INT'),
('Vernonia appendiculata leaf extract','vernonia appendiculata leaf extract','INT'),
('Vernonia appendiculata whole extract','vernonia appendiculata whole extract','INT'),
('Veronica beccabunga whole extract','veronica beccabunga whole extract','INT'),
('Veronica officinalis flowering top extract','veronica officinalis flowering top extract','INT'),
('Veronica officinalis leaf extract','veronica officinalis leaf extract','INT'),
('Veronica officinalis whole extract','veronica officinalis whole extract','INT'),
('Veronicastrum virginicum root extract','veronicastrum virginicum root extract','INT'),
('Veronicastrum virginicum whole extract','veronicastrum virginicum whole extract','INT'),
('versetamide','versetamide','INT'),
('verteporfin','verteporfin','INT'),
('Verticillium albo-atrum allergenic extract','verticillium albo-atrum allergenic extract','INT'),
('Vespa crabro preparation','vespa crabro preparation','INT'),
('Vespula vulgaris whole extract','vespula vulgaris whole extract','INT'),
('vestronidase alfa','vestronidase alfa','INT'),
('vetiver oil','vetiver oil','INT'),
('Vetiveria zizanioides root extract','vetiveria zizanioides root extract','INT'),
('vibegron','vibegron','INT'),
('Vibrio cholerae','vibrio cholerae','INT'),
('Vibrio cholerae CVD 103-HGR strain live antigen','vibrio cholerae cvd 103-hgr strain live antigen','INT'),
('Viburnum lantana flower bud extract','viburnum lantana flower bud extract','INT'),
('Viburnum opulus bark extract','viburnum opulus bark extract','INT'),
('Viburnum opulus root','viburnum opulus root','INT'),
('Viburnum opulus whole extract','viburnum opulus whole extract','INT'),
('Viburnum prunifolium bark extract','viburnum prunifolium bark extract','INT'),
('vidarabine','vidarabine','INT'),
('vigabatrin','vigabatrin','INT'),
('Vigna radiata extract','vigna radiata extract','INT'),
('Vigna radiata whole extract','vigna radiata whole extract','INT'),
('vilanterol','vilanterol','INT'),
('vilazodone','vilazodone','INT'),
('vildagliptin','vildagliptin','INT'),
('vilobelimab','vilobelimab','INT'),
('viloxazine','viloxazine','INT'),
('viltolarsen','viltolarsen','INT'),
('vimseltinib','vimseltinib','INT'),
('vinbarbital','vinbarbital','INT'),
('vinblastine','vinblastine','INT'),
('vinburnine','vinburnine','INT'),
('Vinca minor extract','vinca minor extract','INT'),
('vincamine','vincamine','INT'),
('Vincetoxicum atratum root extract','vincetoxicum atratum root extract','INT'),
('Vincetoxicum atratum whole extract','vincetoxicum atratum whole extract','INT'),
('vincristine','vincristine','INT'),
('vindesine','vindesine','INT'),
('vinorelbine','vinorelbine','INT'),
('vinpocetine','vinpocetine','INT'),
('vinyl acetate','vinyl acetate','INT'),
('vinyl chloride','vinyl chloride','INT'),
('vinyl neodecanoate','vinyl neodecanoate','INT'),
('vinylpyrrolidone-eicosene copolymer','vinylpyrrolidone-eicosene copolymer','INT'),
('vinylpyrrolidone-hexadecene copolymer','vinylpyrrolidone-hexadecene copolymer','INT'),
('Viola adunca whole extract','viola adunca whole extract','INT'),
('Viola japonica extract','viola japonica extract','INT'),
('Viola mandshurica flower extract','viola mandshurica flower extract','INT'),
('Viola odorata extract','viola odorata extract','INT'),
('Viola odorata flower extract','viola odorata flower extract','INT'),
('Viola odorata flowering top extract','viola odorata flowering top extract','INT'),
('Viola odorata leaf extract','viola odorata leaf extract','INT'),
('Viola patrinii whole extract','viola patrinii whole extract','INT'),
('Viola philippica whole extract','viola philippica whole extract','INT'),
('Viola tricolor extract','viola tricolor extract','INT'),
('Vipera berus venom','vipera berus venom','INT'),
('vipivotide tetraxetan','vipivotide tetraxetan','INT'),
('viquidil','viquidil','INT'),
('virginiamycin','virginiamycin','INT')
) AS v(nom, dci, pays)
WHERE NOT EXISTS (SELECT 1 FROM medicaments m WHERE LOWER(m.nom) = LOWER(v.nom));
