-- rxnorm_batch_021.sql (80 rows)
INSERT INTO medicaments (nom, dci, pays)
SELECT v.nom, v.dci, v.pays FROM (VALUES
('Bambara groundnut extract','bambara groundnut extract','INT'),
('bambermycins','bambermycins','INT'),
('bamboo extract','bamboo extract','INT'),
('Bambusa arundinacea leaf extract','bambusa arundinacea leaf extract','INT'),
('Bambusa arundinacea stem extract','bambusa arundinacea stem extract','INT'),
('Bambusa bambos whole extract','bambusa bambos whole extract','INT'),
('Bambusa textilis stem extract','bambusa textilis stem extract','INT'),
('Bambusa vulgaris leaf extract','bambusa vulgaris leaf extract','INT'),
('Bambusa vulgaris sap extract','bambusa vulgaris sap extract','INT'),
('Bambusa vulgaris stem extract','bambusa vulgaris stem extract','INT'),
('Bambusa vulgaris top extract','bambusa vulgaris top extract','INT'),
('Bambusa vulgaris whole extract','bambusa vulgaris whole extract','INT'),
('bambuterol','bambuterol','INT'),
('bamethan','bamethan','INT'),
('bamifylline','bamifylline','INT'),
('bamipine','bamipine','INT'),
('bamlanivimab','bamlanivimab','INT'),
('banana allergenic extract','banana allergenic extract','INT'),
('banana extract','banana extract','INT'),
('banana fruit allergenic extract','banana fruit allergenic extract','INT'),
('banana peel extract','banana peel extract','INT'),
('bancha tea, leaf, twig preparation','bancha tea, leaf, twig preparation','INT'),
('Baptisia australis root extract','baptisia australis root extract','INT'),
('Baptisia tinctoria extract','baptisia tinctoria extract','INT'),
('Baptisia tinctoria root extract','baptisia tinctoria root extract','INT'),
('Baptisia tinctoria whole extract','baptisia tinctoria whole extract','INT'),
('barbasco extract','barbasco extract','INT'),
('barberry extract','barberry extract','INT'),
('barbexaclone','barbexaclone','INT'),
('barbital','barbital','INT'),
('baricitinib','baricitinib','INT'),
('barium','barium','INT'),
('barium acetate','barium acetate','INT'),
('barium bromide','barium bromide','INT'),
('barium carbonate','barium carbonate','INT'),
('barium cation','barium cation','INT'),
('barium chloride','barium chloride','INT'),
('barium chromate','barium chromate','INT'),
('barium citrate','barium citrate','INT'),
('barium iodate','barium iodate','INT'),
('barium iodide','barium iodide','INT'),
('barium oxalate','barium oxalate','INT'),
('barium oxalosuccinate','barium oxalosuccinate','INT'),
('barium oxide','barium oxide','INT'),
('barium sulfate','barium sulfate','INT'),
('Barleria prionitis whole extract','barleria prionitis whole extract','INT'),
('barley (whole grain) allergenic extract','barley (whole grain) allergenic extract','INT'),
('barley allergenic extract','barley allergenic extract','INT'),
('barley bran','barley bran','INT'),
('barley extract','barley extract','INT'),
('barley grain','barley grain','INT'),
('barley malt allergenic extract','barley malt allergenic extract','INT'),
('barley malt syrup','barley malt syrup','INT'),
('Bartonella bacilliformis','bartonella bacilliformis','INT'),
('Bartonella clarridgeiae','bartonella clarridgeiae','INT'),
('Bartonella elizabethae','bartonella elizabethae','INT'),
('Bartonella henselae','bartonella henselae','INT'),
('Bartonella quintana','bartonella quintana','INT'),
('Bartonella vinsonii','bartonella vinsonii','INT'),
('Bartonella washoensis','bartonella washoensis','INT'),
('basic aluminum carbonate gel','basic aluminum carbonate gel','INT'),
('basic blue 1','basic blue 1','INT'),
('basic fuchsin','basic fuchsin','INT'),
('basic red 46','basic red 46','INT'),
('basic red 51','basic red 51','INT'),
('basic yellow 57','basic yellow 57','INT'),
('basic yellow 87','basic yellow 87','INT'),
('basil allergenic extract','basil allergenic extract','INT'),
('basil oil','basil oil','INT'),
('basiliximab','basiliximab','INT'),
('Bassia scoparia fruit extract','bassia scoparia fruit extract','INT'),
('Bassia scoparia whole extract','bassia scoparia whole extract','INT'),
('batilol','batilol','INT'),
('bay leaf allergenic extract','bay leaf allergenic extract','INT'),
('bay leaf extract','bay leaf extract','INT'),
('bay leaf oil','bay leaf oil','INT'),
('bay oil (Pimenta racemosa)','bay oil (pimenta racemosa)','INT'),
('bazedoxifene','bazedoxifene','INT'),
('BCG, live, Connaught strain','bcg, live, connaught strain','INT'),
('BCG, live, Montreal strain','bcg, live, montreal strain','INT')
) AS v(nom, dci, pays)
WHERE NOT EXISTS (SELECT 1 FROM medicaments m WHERE LOWER(m.nom) = LOWER(v.nom));
