-- rxnorm_batch_087.sql (80 rows)
INSERT INTO medicaments (nom, dci, pays)
SELECT v.nom, v.dci, v.pays FROM (VALUES
('irbesartan','irbesartan','INT'),
('Iresine calea extract','iresine calea extract','INT'),
('iridium','iridium','INT'),
('irinotecan','irinotecan','INT'),
('Iris domestica root extract','iris domestica root extract','INT'),
('Iris domestica whole extract','iris domestica whole extract','INT'),
('Iris germanica extract','iris germanica extract','INT'),
('Iris germanica root extract','iris germanica root extract','INT'),
('Iris germanica var. florentina root extract','iris germanica var. florentina root extract','INT'),
('Iris missouriensis whole extract','iris missouriensis whole extract','INT'),
('Iris pallida root extract','iris pallida root extract','INT'),
('Iris tenax extract','iris tenax extract','INT'),
('Iris versicolor root extract','iris versicolor root extract','INT'),
('Iris versicolor whole extract','iris versicolor whole extract','INT'),
('iron','iron','INT'),
('iron bile salts','iron bile salts','INT'),
('iron carbonyl','iron carbonyl','INT'),
('iron fumarate','iron fumarate','INT'),
('iron polysaccharide','iron polysaccharide','INT'),
('iron protein succinylate','iron protein succinylate','INT'),
('iron sorbitex','iron sorbitex','INT'),
('iron succinyl milk protein complex','iron succinyl milk protein complex','INT'),
('iron sucrose','iron sucrose','INT'),
('iron,peptonized','iron,peptonized','INT'),
('iron-dextran complex','iron-dextran complex','INT'),
('Irvingia gabonensis seed butter extract','irvingia gabonensis seed butter extract','INT'),
('Irvingia gabonensis seed extract','irvingia gabonensis seed extract','INT'),
('Isatis tinctoria root extract','isatis tinctoria root extract','INT'),
('Isatis tinctoria whole extract','isatis tinctoria whole extract','INT'),
('isatuximab','isatuximab','INT'),
('isavuconazole','isavuconazole','INT'),
('isavuconazonium','isavuconazonium','INT'),
('iscotrizinol','iscotrizinol','INT'),
('isethionic acid','isethionic acid','INT'),
('iso-sulfan blue','iso-sulfan blue','INT'),
('isoambrettolide','isoambrettolide','INT'),
('isoaminile','isoaminile','INT'),
('isoamyl acetate','isoamyl acetate','INT'),
('isoamyl butyrate','isoamyl butyrate','INT'),
('isoamyl cinnamate','isoamyl cinnamate','INT'),
('isoamyl cocoate','isoamyl cocoate','INT'),
('isoamyl laurate','isoamyl laurate','INT'),
('isoamyl salicylate','isoamyl salicylate','INT'),
('isobornyl acetate','isobornyl acetate','INT'),
('isobornyl acrylate','isobornyl acrylate','INT'),
('isobornyl methacrylate','isobornyl methacrylate','INT'),
('isobutane','isobutane','INT'),
('isobutyl acetate','isobutyl acetate','INT'),
('isobutyl alcohol','isobutyl alcohol','INT'),
('isobutyl stearate','isobutyl stearate','INT'),
('isobutylene','isobutylene','INT'),
('isobutylparaben','isobutylparaben','INT'),
('isobutyramide','isobutyramide','INT'),
('isocarboxazid','isocarboxazid','INT'),
('isocetane','isocetane','INT'),
('isoceteth 20','isoceteth 20','INT'),
('isoceteth-10','isoceteth-10','INT'),
('isoceteth-25','isoceteth-25','INT'),
('isocetyl alcohol','isocetyl alcohol','INT'),
('isocetyl ethylhexanoate','isocetyl ethylhexanoate','INT'),
('isocetyl isostearate','isocetyl isostearate','INT'),
('isocetyl myristate','isocetyl myristate','INT'),
('isocetyl palmitate','isocetyl palmitate','INT'),
('isocetyl stearate','isocetyl stearate','INT'),
('isocetyl stearoyl stearate','isocetyl stearoyl stearate','INT'),
('isoconazole','isoconazole','INT'),
('isocorynoxeine','isocorynoxeine','INT'),
('isocyclocitral','isocyclocitral','INT'),
('isodeceth-6','isodeceth-6','INT'),
('isodecyl alcohol','isodecyl alcohol','INT'),
('isodecyl isononanoate','isodecyl isononanoate','INT'),
('isodecyl laurate','isodecyl laurate','INT'),
('isodecyl neopentanoate','isodecyl neopentanoate','INT'),
('isodecyl salicylate','isodecyl salicylate','INT'),
('isododecane','isododecane','INT'),
('Isodon rubescens top extract','isodon rubescens top extract','INT'),
('Isodon rubescens whole extract','isodon rubescens whole extract','INT'),
('isoeicosane','isoeicosane','INT'),
('isoetharine','isoetharine','INT'),
('isoeugenol','isoeugenol','INT')
) AS v(nom, dci, pays)
WHERE NOT EXISTS (SELECT 1 FROM medicaments m WHERE LOWER(m.nom) = LOWER(v.nom));
