-- rxnorm_batch_199.sql (80 rows)
INSERT INTO medicaments (nom, dci, pays)
SELECT v.nom, v.dci, v.pays FROM (VALUES
('formaldehyde / glutaral','formaldehyde / glutaral','INT'),
('formaldehyde / glutaral / glyoxal','formaldehyde / glutaral / glyoxal','INT'),
('formaldehyde / isopropyl alcohol','formaldehyde / isopropyl alcohol','INT'),
('formaldehyde / lidocaine','formaldehyde / lidocaine','INT'),
('formaldehyde / malachite green','formaldehyde / malachite green','INT'),
('formaldehyde / methanol','formaldehyde / methanol','INT'),
('formaldehyde / salicylic acid','formaldehyde / salicylic acid','INT'),
('formaldehyde / sodium fluoride','formaldehyde / sodium fluoride','INT'),
('formoterol / glycopyrronium','formoterol / glycopyrronium','INT'),
('formoterol / mometasone','formoterol / mometasone','INT'),
('fosinopril / hydrochlorothiazide','fosinopril / hydrochlorothiazide','INT'),
('framycetin / gramicidin','framycetin / gramicidin','INT'),
('framycetin / hydrocortisone','framycetin / hydrocortisone','INT'),
('framycetin / naphazoline','framycetin / naphazoline','INT'),
('Frangula preparation / karaya gum','frangula preparation / karaya gum','INT'),
('fructooligosaccharide / Lactobacillus acidophilus','fructooligosaccharide / lactobacillus acidophilus','INT'),
('fructooligosaccharide / Saccharomyces boulardii','fructooligosaccharide / saccharomyces boulardii','INT'),
('fructose / glucose / phosphoric acid','fructose / glucose / phosphoric acid','INT'),
('fructose / glucose / sodium citrate','fructose / glucose / sodium citrate','INT'),
('fumarate / nickel sulfate / potassium bromide','fumarate / nickel sulfate / potassium bromide','INT'),
('furosemide / penbutolol','furosemide / penbutolol','INT'),
('furosemide / potassium','furosemide / potassium','INT'),
('furosemide / potassium chloride','furosemide / potassium chloride','INT'),
('furosemide / spironolactone','furosemide / spironolactone','INT'),
('furosemide / triamterene','furosemide / triamterene','INT'),
('fusidate / hydrocortisone','fusidate / hydrocortisone','INT'),
('gamma-aminobutyrate / vitamin B6','gamma-aminobutyrate / vitamin b6','INT'),
('gamma-linolenate / linoleate','gamma-linolenate / linoleate','INT'),
('gamma-linolenate / vitamin E','gamma-linolenate / vitamin e','INT'),
('gentamicin / hydrocortisone','gentamicin / hydrocortisone','INT'),
('gentamicin / hydrocortisone / miconazole','gentamicin / hydrocortisone / miconazole','INT'),
('gentamicin / mometasone / posaconazole','gentamicin / mometasone / posaconazole','INT'),
('gentamicin / prednisolone','gentamicin / prednisolone','INT'),
('glecaprevir / pibrentasvir','glecaprevir / pibrentasvir','INT'),
('glimepiride / pioglitazone','glimepiride / pioglitazone','INT'),
('glimepiride / rosiglitazone','glimepiride / rosiglitazone','INT'),
('glipizide / metformin','glipizide / metformin','INT'),
('gluconolactone / magnesium carbonate','gluconolactone / magnesium carbonate','INT'),
('glucosamine / potassium','glucosamine / potassium','INT'),
('glucosamine / S-adenosylmethionine','glucosamine / s-adenosylmethionine','INT'),
('glucosamine hydrochloride / glucosamine sulfate','glucosamine hydrochloride / glucosamine sulfate','INT'),
('glucose / lidocaine','glucose / lidocaine','INT'),
('glucose / potassium chloride','glucose / potassium chloride','INT'),
('glucose / potassium chloride / sodium chloride','glucose / potassium chloride / sodium chloride','INT'),
('glucose / sodium chloride','glucose / sodium chloride','INT'),
('glutamate / magnesium citrate','glutamate / magnesium citrate','INT'),
('glutamate / vitamin B6','glutamate / vitamin b6','INT'),
('glutamate / zinc chloride','glutamate / zinc chloride','INT'),
('glutamine / tyrosine','glutamine / tyrosine','INT'),
('glyburide / metformin','glyburide / metformin','INT'),
('glyburide / phenformin','glyburide / phenformin','INT'),
('glycerin / hypromellose','glycerin / hypromellose','INT'),
('glycerin / hypromellose / naphazoline','glycerin / hypromellose / naphazoline','INT'),
('glycerin / hypromellose / phenylephrine','glycerin / hypromellose / phenylephrine','INT'),
('glycerin / hypromellose / polyethylene glycol 400','glycerin / hypromellose / polyethylene glycol 400','INT'),
('glycerin / hypromellose / propylene glycol','glycerin / hypromellose / propylene glycol','INT'),
('glycerin / kaolin / sodium fluoride','glycerin / kaolin / sodium fluoride','INT'),
('glycerin / lactate / petrolatum','glycerin / lactate / petrolatum','INT'),
('glycerin / lanolin / lidocaine / zinc oxide','glycerin / lanolin / lidocaine / zinc oxide','INT'),
('glycerin / lidocaine','glycerin / lidocaine','INT'),
('glycerin / lidocaine / petrolatum / phenylephrine','glycerin / lidocaine / petrolatum / phenylephrine','INT'),
('glycerin / lidocaine / phenylephrine','glycerin / lidocaine / phenylephrine','INT'),
('glycerin / lysine','glycerin / lysine','INT'),
('glycerin / menthol / witch hazel','glycerin / menthol / witch hazel','INT'),
('glycerin / naphazoline','glycerin / naphazoline','INT'),
('glycerin / naphazoline / zinc sulfate','glycerin / naphazoline / zinc sulfate','INT'),
('glycerin / paraffin','glycerin / paraffin','INT'),
('glycerin / petrolatum','glycerin / petrolatum','INT'),
('glycerin / petrolatum / phenylephrine / pramoxine','glycerin / petrolatum / phenylephrine / pramoxine','INT'),
('glycerin / phenol','glycerin / phenol','INT'),
('glycerin / phenylephrine','glycerin / phenylephrine','INT'),
('glycerin / polysorbate 80','glycerin / polysorbate 80','INT'),
('glycerin / povidone','glycerin / povidone','INT'),
('glycerin / pramoxine','glycerin / pramoxine','INT'),
('glycerin / propylene glycol','glycerin / propylene glycol','INT'),
('glycerin / salicylic acid','glycerin / salicylic acid','INT'),
('glycerin / sodium chloride','glycerin / sodium chloride','INT'),
('glycerin / thymol','glycerin / thymol','INT'),
('glycine / isoleucine / ubidecarenone','glycine / isoleucine / ubidecarenone','INT'),
('glycine / licorice','glycine / licorice','INT')
) AS v(nom, dci, pays)
WHERE NOT EXISTS (SELECT 1 FROM medicaments m WHERE LOWER(m.nom) = LOWER(v.nom));
