-- rxnorm_batch_176.sql (80 rows)
INSERT INTO medicaments (nom, dci, pays)
SELECT v.nom, v.dci, v.pays FROM (VALUES
('ambroxol / doxycycline','ambroxol / doxycycline','INT'),
('ambroxol / theophylline','ambroxol / theophylline','INT'),
('amdinocillin pivoxil / pivampicillin','amdinocillin pivoxil / pivampicillin','INT'),
('amiloride / atenolol / hydrochlorothiazide','amiloride / atenolol / hydrochlorothiazide','INT'),
('amiloride / bendroflumethiazide','amiloride / bendroflumethiazide','INT'),
('amiloride / bumetanide','amiloride / bumetanide','INT'),
('amiloride / cyclopenthiazide','amiloride / cyclopenthiazide','INT'),
('amiloride / furosemide','amiloride / furosemide','INT'),
('amiloride / furosemide / indapamide','amiloride / furosemide / indapamide','INT'),
('amiloride / hydrochlorothiazide','amiloride / hydrochlorothiazide','INT'),
('amiloride / hydrochlorothiazide / timolol','amiloride / hydrochlorothiazide / timolol','INT'),
('amiloride / metolazone','amiloride / metolazone','INT'),
('amiloride / trichlormethiazide','amiloride / trichlormethiazide','INT'),
('aminacrine / lidocaine','aminacrine / lidocaine','INT'),
('aminobutyrate / phenobarbital / phenytoin','aminobutyrate / phenobarbital / phenytoin','INT'),
('aminohydroxybutyric acid / pyrithioxin','aminohydroxybutyric acid / pyrithioxin','INT'),
('aminophylline / amobarbital / ephedrine','aminophylline / amobarbital / ephedrine','INT'),
('aminophylline / ephedrine','aminophylline / ephedrine','INT'),
('aminophylline / ephedrine / phenobarbital','aminophylline / ephedrine / phenobarbital','INT'),
('aminophylline / ephedrine / potassium iodide','aminophylline / ephedrine / potassium iodide','INT'),
('aminophylline / guaifenesin','aminophylline / guaifenesin','INT'),
('aminophylline / papaverine / phenobarbital','aminophylline / papaverine / phenobarbital','INT'),
('aminophylline / phenobarbital','aminophylline / phenobarbital','INT'),
('aminophylline / potassium iodide','aminophylline / potassium iodide','INT'),
('aminophylline / promethazine','aminophylline / promethazine','INT'),
('aminophylline / quinine','aminophylline / quinine','INT'),
('aminoquinuride / tetracaine','aminoquinuride / tetracaine','INT'),
('amitriptyline / chlordiazepoxide','amitriptyline / chlordiazepoxide','INT'),
('amitriptyline / diazepam / perphenazine','amitriptyline / diazepam / perphenazine','INT'),
('amitriptyline / perphenazine','amitriptyline / perphenazine','INT'),
('amivantamab / hyaluronidase','amivantamab / hyaluronidase','INT'),
('amlodipine / atorvastatin','amlodipine / atorvastatin','INT'),
('amlodipine / benazepril','amlodipine / benazepril','INT'),
('amlodipine / celecoxib','amlodipine / celecoxib','INT'),
('amlodipine / hydrochlorothiazide / olmesartan','amlodipine / hydrochlorothiazide / olmesartan','INT'),
('amlodipine / hydrochlorothiazide / valsartan','amlodipine / hydrochlorothiazide / valsartan','INT'),
('amlodipine / indapamide / telmisartan','amlodipine / indapamide / telmisartan','INT'),
('amlodipine / olmesartan','amlodipine / olmesartan','INT'),
('amlodipine / perindopril','amlodipine / perindopril','INT'),
('amlodipine / telmisartan','amlodipine / telmisartan','INT'),
('amlodipine / valsartan','amlodipine / valsartan','INT'),
('ammonia / camphor / menthol','ammonia / camphor / menthol','INT'),
('ammonium carbonate / sodium carbonate','ammonium carbonate / sodium carbonate','INT'),
('ammonium chloride / benzoate / clobutinol','ammonium chloride / benzoate / clobutinol','INT'),
('ammonium chloride / betaine','ammonium chloride / betaine','INT'),
('ammonium chloride / caffeine','ammonium chloride / caffeine','INT'),
('ammonium chloride / diphenhydramine','ammonium chloride / diphenhydramine','INT'),
('ammonium chloride / ephedrine','ammonium chloride / ephedrine','INT'),
('ammonium chloride / guaiacolsulfonic acid','ammonium chloride / guaiacolsulfonic acid','INT'),
('ammonium chloride / guaifenesin','ammonium chloride / guaifenesin','INT'),
('ammonium chloride / ipecac','ammonium chloride / ipecac','INT'),
('ammonium chloride / isoaminile','ammonium chloride / isoaminile','INT'),
('ammonium chloride / potassium iodide','ammonium chloride / potassium iodide','INT'),
('ammonium ferrous sulfate / folic acid','ammonium ferrous sulfate / folic acid','INT'),
('amobarbital / ephedrine','amobarbital / ephedrine','INT'),
('amobarbital / secobarbital','amobarbital / secobarbital','INT'),
('amoxicillin / bromhexine','amoxicillin / bromhexine','INT'),
('amoxicillin / brovanexine','amoxicillin / brovanexine','INT'),
('amoxicillin / carbocysteine','amoxicillin / carbocysteine','INT'),
('amoxicillin / clavulanate','amoxicillin / clavulanate','INT'),
('amoxicillin / clonixin','amoxicillin / clonixin','INT'),
('amoxicillin / diclofenac','amoxicillin / diclofenac','INT'),
('amoxicillin / floxacillin','amoxicillin / floxacillin','INT'),
('amoxicillin / nystatin','amoxicillin / nystatin','INT'),
('amoxicillin / omeprazole / rifabutin','amoxicillin / omeprazole / rifabutin','INT'),
('amoxicillin / piroxicam','amoxicillin / piroxicam','INT'),
('amoxicillin / probenecid','amoxicillin / probenecid','INT'),
('amoxicillin / sulbactam','amoxicillin / sulbactam','INT'),
('amoxicillin / sulfinpyrazone','amoxicillin / sulfinpyrazone','INT'),
('amphetamine / dextroamphetamine','amphetamine / dextroamphetamine','INT'),
('amphetamine / phenobarbital','amphetamine / phenobarbital','INT'),
('amphotericin B / tetracycline','amphotericin b / tetracycline','INT'),
('amphotericin B / triamcinolone','amphotericin b / triamcinolone','INT'),
('ampicillin / bromhexine','ampicillin / bromhexine','INT'),
('ampicillin / brovanexine','ampicillin / brovanexine','INT'),
('ampicillin / carbocysteine','ampicillin / carbocysteine','INT'),
('ampicillin / cloxacillin','ampicillin / cloxacillin','INT'),
('ampicillin / diclofenac','ampicillin / diclofenac','INT'),
('ampicillin / dicloxacillin','ampicillin / dicloxacillin','INT'),
('ampicillin / floxacillin','ampicillin / floxacillin','INT')
) AS v(nom, dci, pays)
WHERE NOT EXISTS (SELECT 1 FROM medicaments m WHERE LOWER(m.nom) = LOWER(v.nom));
