-- rxnorm_batch_072.sql (80 rows)
INSERT INTO medicaments (nom, dci, pays)
SELECT v.nom, v.dci, v.pays FROM (VALUES
('Fritillaria delavayi whole extract','fritillaria delavayi whole extract','INT'),
('Fritillaria przewalskii bulb extract','fritillaria przewalskii bulb extract','INT'),
('frovatriptan','frovatriptan','INT'),
('fructooligosaccharide','fructooligosaccharide','INT'),
('fructose','fructose','INT'),
('fructosylnystose','fructosylnystose','INT'),
('frunevetmab','frunevetmab','INT'),
('fruquintinib','fruquintinib','INT'),
('fu ling','fu ling','INT'),
('Fuchsia magellanica whole extract','fuchsia magellanica whole extract','INT'),
('fucose','fucose','INT'),
('Fucus serratus extract','fucus serratus extract','INT'),
('Fucus spiralis extract','fucus spiralis extract','INT'),
('Fucus vesiculosus extract','fucus vesiculosus extract','INT'),
('fulvestrant','fulvestrant','INT'),
('fulvic acid','fulvic acid','INT'),
('fumagillin','fumagillin','INT'),
('fumarate','fumarate','INT'),
('Fumaria officials whole extract','fumaria officials whole extract','INT'),
('Fumaria officinalis flowering top extract','fumaria officinalis flowering top extract','INT'),
('fumaryl diketopiperazine','fumaryl diketopiperazine','INT'),
('fumitory extract','fumitory extract','INT'),
('furazolidone','furazolidone','INT'),
('Furcellaria lumbricalis extract','furcellaria lumbricalis extract','INT'),
('furcelleran','furcelleran','INT'),
('furosemide','furosemide','INT'),
('fursultiamin','fursultiamin','INT'),
('furterene','furterene','INT'),
('fusafungin','fusafungin','INT'),
('Fusarium compactum allergenic extract','fusarium compactum allergenic extract','INT'),
('Fusarium moniliforme antigen','fusarium moniliforme antigen','INT'),
('Fusarium oxysporum allergenic extract','fusarium oxysporum allergenic extract','INT'),
('Fusarium oxysporum vasinfectum allergenic extract','fusarium oxysporum vasinfectum allergenic extract','INT'),
('fusel oil','fusel oil','INT'),
('fusidate','fusidate','INT'),
('futibatinib','futibatinib','INT'),
('fuzapladib','fuzapladib','INT'),
('gabapentin','gabapentin','INT'),
('gadobenate','gadobenate','INT'),
('gadobutrol','gadobutrol','INT'),
('gadodiamide','gadodiamide','INT'),
('gadofosveset','gadofosveset','INT'),
('gadolinium','gadolinium','INT'),
('gadolinium oxide','gadolinium oxide','INT'),
('gadopentetate','gadopentetate','INT'),
('gadopentetate dimeglumine','gadopentetate dimeglumine','INT'),
('gadopiclenol','gadopiclenol','INT'),
('gadoterate meglumine','gadoterate meglumine','INT'),
('gadoteridol','gadoteridol','INT'),
('gadoversetamide','gadoversetamide','INT'),
('gadoxetate','gadoxetate','INT'),
('galactoarabinan','galactoarabinan','INT'),
('galactose','galactose','INT'),
('galangal oil','galangal oil','INT'),
('galantamine','galantamine','INT'),
('Galanthus nivalis extract','galanthus nivalis extract','INT'),
('Galanthus nivalis seed extract','galanthus nivalis seed extract','INT'),
('galbanum','galbanum','INT'),
('galbanum oil','galbanum oil','INT'),
('galcanezumab','galcanezumab','INT'),
('galectin-3','galectin-3','INT'),
('Galega officinalis extract','galega officinalis extract','INT'),
('Galium aparine extract','galium aparine extract','INT'),
('Galium boreale leaf extract','galium boreale leaf extract','INT'),
('Galium boreale whole extract','galium boreale whole extract','INT'),
('Galium odoratum extract','galium odoratum extract','INT'),
('gallamine','gallamine','INT'),
('gallic acid','gallic acid','INT'),
('gallium','gallium','INT'),
('gallopamil','gallopamil','INT'),
('Gallus gallus gizzard lining preparation','gallus gallus gizzard lining preparation','INT'),
('Galphimia glauca flowering top extract','galphimia glauca flowering top extract','INT'),
('Galphimia glauca whole extract','galphimia glauca whole extract','INT'),
('galsulfase','galsulfase','INT'),
('Gambels oak pollen extract','gambels oak pollen extract','INT'),
('gambir leaf extract','gambir leaf extract','INT'),
('gamboge','gamboge','INT'),
('gamithromycin','gamithromycin','INT'),
('gamma linoleic acid','gamma linoleic acid','INT'),
('gamma linolenic oil','gamma linolenic oil','INT')
) AS v(nom, dci, pays)
WHERE NOT EXISTS (SELECT 1 FROM medicaments m WHERE LOWER(m.nom) = LOWER(v.nom));
