-- rxnorm_batch_068.sql (80 rows)
INSERT INTO medicaments (nom, dci, pays)
SELECT v.nom, v.dci, v.pays FROM (VALUES
('Fagopyrum esculentum extract','fagopyrum esculentum extract','INT'),
('Fagraea berteroana flower extract','fagraea berteroana flower extract','INT'),
('Fagraea berteroana flower oil','fagraea berteroana flower oil','INT'),
('Fagus sylvatica flower bud extract','fagus sylvatica flower bud extract','INT'),
('Fagus sylvatica flowering top','fagus sylvatica flowering top','INT'),
('Fagus sylvatica nut extract','fagus sylvatica nut extract','INT'),
('Fagus sylvatica whole extract','fagus sylvatica whole extract','INT'),
('Fallopia multiflora root extract','fallopia multiflora root extract','INT'),
('false ragweed pollen extract','false ragweed pollen extract','INT'),
('famciclovir','famciclovir','INT'),
('famotidine','famotidine','INT'),
('fanolesomab','fanolesomab','INT'),
('faricimab','faricimab','INT'),
('farnesal','farnesal','INT'),
('farnesane','farnesane','INT'),
('farnesol','farnesol','INT'),
('farnesyl acetate','farnesyl acetate','INT'),
('fast green FCF stain','fast green fcf stain','INT'),
('fatty acids, omega-6','fatty acids, omega-6','INT'),
('FD & C red no. 40 aluminum lake','fd & c red no. 40 aluminum lake','INT'),
('FD &C yellow #6 aluminum lake','fd &c yellow #6 aluminum lake','INT'),
('FD&C blue #1 aluminum lake','fd&c blue #1 aluminum lake','INT'),
('FD&C blue #10 aluminum lake','fd&c blue #10 aluminum lake','INT'),
('FD&C blue #2 aluminum lake','fd&c blue #2 aluminum lake','INT'),
('FD&C blue #2 HT aluminum lake','fd&c blue #2 ht aluminum lake','INT'),
('FD&C blue #2 lake','fd&c blue #2 lake','INT'),
('FD&C red #40 HT aluminum lake','fd&c red #40 ht aluminum lake','INT'),
('FD&C red 40 lake','fd&c red 40 lake','INT'),
('FD&C red no. 4','fd&c red no. 4','INT'),
('FD&C red no. 4 free acid','fd&c red no. 4 free acid','INT'),
('FD&C yellow #5 aluminum lake','fd&c yellow #5 aluminum lake','INT'),
('FD&C yellow no. 6','fd&c yellow no. 6','INT'),
('Fe heme polypeptide','fe heme polypeptide','INT'),
('febantel','febantel','INT'),
('febarbamate','febarbamate','INT'),
('febuprol','febuprol','INT'),
('febuxostat','febuxostat','INT'),
('fecal microbiota spores, live','fecal microbiota spores, live','INT'),
('fecal microbiota, live','fecal microbiota, live','INT'),
('feclobuzone','feclobuzone','INT'),
('fedratinib','fedratinib','INT'),
('fedrilate','fedrilate','INT'),
('felbamate','felbamate','INT'),
('felbinac','felbinac','INT'),
('Felis catus milk prepration','felis catus milk prepration','INT'),
('felodipine','felodipine','INT'),
('felypressin','felypressin','INT'),
('fenamiphos','fenamiphos','INT'),
('fenbendazole','fenbendazole','INT'),
('fenbufen','fenbufen','INT'),
('fenbutrazate','fenbutrazate','INT'),
('fendiline','fendiline','INT'),
('fenethylline','fenethylline','INT'),
('fenfluramine','fenfluramine','INT'),
('fenipentol','fenipentol','INT'),
('fennel extract','fennel extract','INT'),
('fennel oil','fennel oil','INT'),
('fennel seed preparation','fennel seed preparation','INT'),
('fenofibrate','fenofibrate','INT'),
('fenoldopam','fenoldopam','INT'),
('fenoprofen','fenoprofen','INT'),
('fenoprop triethanolamine','fenoprop triethanolamine','INT'),
('fenoprop triisopropanolamine','fenoprop triisopropanolamine','INT'),
('fenoterol','fenoterol','INT'),
('fenoverine','fenoverine','INT'),
('fenoxazoline','fenoxazoline','INT'),
('fenozolone','fenozolone','INT'),
('fenproporex','fenproporex','INT'),
('fenspiride','fenspiride','INT'),
('fentanyl','fentanyl','INT'),
('fenticonazole','fenticonazole','INT'),
('fenugreek leaf extract','fenugreek leaf extract','INT'),
('fenugreek seed meal','fenugreek seed meal','INT'),
('fenugreek seed oil','fenugreek seed oil','INT'),
('fenugreek seed preparation','fenugreek seed preparation','INT'),
('feprazone','feprazone','INT'),
('ferric acetate, basic','ferric acetate, basic','INT'),
('ferric ammonium citrate','ferric ammonium citrate','INT'),
('ferric ammonium ferrocyanide','ferric ammonium ferrocyanide','INT'),
('ferric cacodylate','ferric cacodylate','INT')
) AS v(nom, dci, pays)
WHERE NOT EXISTS (SELECT 1 FROM medicaments m WHERE LOWER(m.nom) = LOWER(v.nom));
