-- rxnorm_batch_208.sql (80 rows)
INSERT INTO medicaments (nom, dci, pays)
SELECT v.nom, v.dci, v.pays FROM (VALUES
('pentoxifylline / procyanidolic oligomer','pentoxifylline / procyanidolic oligomer','INT'),
('peppermint oil / sage oil','peppermint oil / sage oil','INT'),
('Peruvian balsam / trypsin','peruvian balsam / trypsin','INT'),
('petrolatum / resorcinol','petrolatum / resorcinol','INT'),
('petrolatum / salicylic acid','petrolatum / salicylic acid','INT'),
('petrolatum / vitamin E','petrolatum / vitamin e','INT'),
('petrolatum / zinc oxide','petrolatum / zinc oxide','INT'),
('phenazopyridine / sulfamethizole','phenazopyridine / sulfamethizole','INT'),
('phenazopyridine / sulfamethoxazole','phenazopyridine / sulfamethoxazole','INT'),
('phenazopyridine / sulfamethoxazole / trimethoprim','phenazopyridine / sulfamethoxazole / trimethoprim','INT'),
('phenazopyridine / sulfanilylurea','phenazopyridine / sulfanilylurea','INT'),
('phenazopyridine / sulfisoxazole','phenazopyridine / sulfisoxazole','INT'),
('phenazopyridine / terizidone','phenazopyridine / terizidone','INT'),
('pheniramine / phenylephrine','pheniramine / phenylephrine','INT'),
('pheniramine / phenylpropanolamine / pyrilamine','pheniramine / phenylpropanolamine / pyrilamine','INT'),
('pheniramine / phenyltoloxamine / pyrilamine','pheniramine / phenyltoloxamine / pyrilamine','INT'),
('phenobarbital / phenytoin','phenobarbital / phenytoin','INT'),
('phenobarbital / pipenzolate','phenobarbital / pipenzolate','INT'),
('phenobarbital / propantheline','phenobarbital / propantheline','INT'),
('phenobarbital / sodium nitrite','phenobarbital / sodium nitrite','INT'),
('phenol / resorcinol','phenol / resorcinol','INT'),
('phenol / scarlet red','phenol / scarlet red','INT'),
('phenol / tannic acid','phenol / tannic acid','INT'),
('phenol / zinc oxide','phenol / zinc oxide','INT'),
('phenolphthalein / sennosides, USP','phenolphthalein / sennosides, usp','INT'),
('phentermine / topiramate','phentermine / topiramate','INT'),
('phenylbutazone / salicylamide','phenylbutazone / salicylamide','INT'),
('phenylbutyrate / taurursodiol','phenylbutyrate / taurursodiol','INT'),
('phenylephrine / polyvinyl alcohol','phenylephrine / polyvinyl alcohol','INT'),
('phenylephrine / pramoxine','phenylephrine / pramoxine','INT'),
('phenylephrine / prednisolone','phenylephrine / prednisolone','INT'),
('phenylephrine / prednisolone / sulfacetamide','phenylephrine / prednisolone / sulfacetamide','INT'),
('phenylephrine / promethazine','phenylephrine / promethazine','INT'),
('phenylephrine / pyrilamine','phenylephrine / pyrilamine','INT'),
('phenylephrine / scopolamine','phenylephrine / scopolamine','INT'),
('phenylephrine / shark liver oil','phenylephrine / shark liver oil','INT'),
('phenylephrine / sulfacetamide','phenylephrine / sulfacetamide','INT'),
('phenylephrine / sulfated mucopolysaccharides','phenylephrine / sulfated mucopolysaccharides','INT'),
('phenylephrine / thonzylamine','phenylephrine / thonzylamine','INT'),
('phenylephrine / triprolidine','phenylephrine / triprolidine','INT'),
('phenylephrine / tropicamide','phenylephrine / tropicamide','INT'),
('phenylephrine / witch hazel','phenylephrine / witch hazel','INT'),
('phenylephrine / zinc oxide','phenylephrine / zinc oxide','INT'),
('phenylephrine / zinc sulfate','phenylephrine / zinc sulfate','INT'),
('phloroglucinol / trimethobenzamide','phloroglucinol / trimethobenzamide','INT'),
('phloroglucinol / trimethoxybenzene','phloroglucinol / trimethoxybenzene','INT'),
('pholcodine / pseudoephedrine','pholcodine / pseudoephedrine','INT'),
('phosphoric acid / sodium fluoride','phosphoric acid / sodium fluoride','INT'),
('phosphorus / potassium','phosphorus / potassium','INT'),
('physostigmine / pilocarpine','physostigmine / pilocarpine','INT'),
('phytosphingosine / salicylic acid','phytosphingosine / salicylic acid','INT'),
('pilocarpine / timolol','pilocarpine / timolol','INT'),
('pipenzolate / simethicone','pipenzolate / simethicone','INT'),
('piperacillin / tazobactam','piperacillin / tazobactam','INT'),
('piperonyl butoxide / pyrethrins','piperonyl butoxide / pyrethrins','INT'),
('piperonyl butoxide / pyrethrum extract','piperonyl butoxide / pyrethrum extract','INT'),
('pirenzepine / ranitidine','pirenzepine / ranitidine','INT'),
('piretanide / ramipril','piretanide / ramipril','INT'),
('piroctone olamine / salicylic acid','piroctone olamine / salicylic acid','INT'),
('piroxicam / prednisone','piroxicam / prednisone','INT'),
('piroxicam / vitamin B12','piroxicam / vitamin b12','INT'),
('Plantago seed / sennosides, USP','plantago seed / sennosides, usp','INT'),
('podophyllin / salicylic acid','podophyllin / salicylic acid','INT'),
('polidocanol / prednisolone / promethazine','polidocanol / prednisolone / promethazine','INT'),
('polidocanol / urea','polidocanol / urea','INT'),
('polidocanol / zinc oxide','polidocanol / zinc oxide','INT'),
('poloxamer 407 / simethicone','poloxamer 407 / simethicone','INT'),
('polyethylene glycol 400 / polyvinyl alcohol','polyethylene glycol 400 / polyvinyl alcohol','INT'),
('polyethylene glycol 400 / propylene glycol','polyethylene glycol 400 / propylene glycol','INT'),
('polyethylene glycol 400 / tetrahydrozoline','polyethylene glycol 400 / tetrahydrozoline','INT'),
('polyethylene glycols / polyvinyl alcohol','polyethylene glycols / polyvinyl alcohol','INT'),
('polyethylene glycols / propylene glycol','polyethylene glycols / propylene glycol','INT'),
('polymyxin B / triamcinolone','polymyxin b / triamcinolone','INT'),
('polymyxin B / trimethoprim','polymyxin b / trimethoprim','INT'),
('polyoxyethylene ether / sulfur','polyoxyethylene ether / sulfur','INT'),
('polythiazide / prazosin','polythiazide / prazosin','INT'),
('polythiazide / reserpine','polythiazide / reserpine','INT'),
('polyvinyl alcohol / povidone','polyvinyl alcohol / povidone','INT'),
('polyvinyl alcohol / povidone / tetrahydrozoline','polyvinyl alcohol / povidone / tetrahydrozoline','INT'),
('potassium bicarbonate / potassium citrate','potassium bicarbonate / potassium citrate','INT')
) AS v(nom, dci, pays)
WHERE NOT EXISTS (SELECT 1 FROM medicaments m WHERE LOWER(m.nom) = LOWER(v.nom));
