-- rxnorm_batch_013.sql (80 rows)
INSERT INTO medicaments (nom, dci, pays)
SELECT v.nom, v.dci, v.pays FROM (VALUES
('amineptin','amineptin','INT'),
('amino methacrylate copolymer','amino methacrylate copolymer','INT'),
('aminobenzoate','aminobenzoate','INT'),
('aminobutyrate','aminobutyrate','INT'),
('aminocaproate','aminocaproate','INT'),
('aminoethylphosphinic acid','aminoethylphosphinic acid','INT'),
('aminoglutethimide','aminoglutethimide','INT'),
('aminohydroxybutyric acid','aminohydroxybutyric acid','INT'),
('aminolevulinate','aminolevulinate','INT'),
('aminolevulinic acid','aminolevulinic acid','INT'),
('aminomethyl propanediol','aminomethyl propanediol','INT'),
('aminometradine','aminometradine','INT'),
('aminopentamide','aminopentamide','INT'),
('aminophylline','aminophylline','INT'),
('aminopromazine','aminopromazine','INT'),
('aminopropanediol','aminopropanediol','INT'),
('aminopropazine fumarate','aminopropazine fumarate','INT'),
('aminopropyl ascorbyl phosphate','aminopropyl ascorbyl phosphate','INT'),
('aminopropyl dihydrogen phosphate','aminopropyl dihydrogen phosphate','INT'),
('aminopterin','aminopterin','INT'),
('aminopyrine','aminopyrine','INT'),
('aminoquinuride','aminoquinuride','INT'),
('aminosalicylate','aminosalicylate','INT'),
('aminosalicylic acid','aminosalicylic acid','INT'),
('amiodarone','amiodarone','INT'),
('amisulpride','amisulpride','INT'),
('amitraz','amitraz','INT'),
('amitriptyline','amitriptyline','INT'),
('amivantamab','amivantamab','INT'),
('amlexanox','amlexanox','INT'),
('amlodipine','amlodipine','INT'),
('Ammi visnaga fruit extract','ammi visnaga fruit extract','INT'),
('ammonia','ammonia','INT'),
('ammoniac','ammoniac','INT'),
('ammonio methacrylate copolymer type A','ammonio methacrylate copolymer type a','INT'),
('ammonio methacrylate copolymer type B','ammonio methacrylate copolymer type b','INT'),
('ammonium','ammonium','INT'),
('ammonium acetate','ammonium acetate','INT'),
('ammonium benzoate','ammonium benzoate','INT'),
('ammonium bromide','ammonium bromide','INT'),
('ammonium carbonate','ammonium carbonate','INT'),
('ammonium chloride','ammonium chloride','INT'),
('ammonium ferrous sulfate','ammonium ferrous sulfate','INT'),
('ammonium hydroxide','ammonium hydroxide','INT'),
('ammonium hypophosphite','ammonium hypophosphite','INT'),
('ammonium iodide','ammonium iodide','INT'),
('ammonium ion','ammonium ion','INT'),
('ammonium laureth-12 sulfate','ammonium laureth-12 sulfate','INT'),
('ammonium laureth-2 sulfate','ammonium laureth-2 sulfate','INT'),
('ammonium laureth-3 sulfate','ammonium laureth-3 sulfate','INT'),
('ammonium laureth-5 sulfate','ammonium laureth-5 sulfate','INT'),
('ammonium laureth-7 sulfate','ammonium laureth-7 sulfate','INT'),
('ammonium lauroyl sarcosinate','ammonium lauroyl sarcosinate','INT'),
('ammonium lauryl sulfate','ammonium lauryl sulfate','INT'),
('ammonium methacrylate','ammonium methacrylate','INT'),
('ammonium phosphate','ammonium phosphate','INT'),
('ammonium salicylate','ammonium salicylate','INT'),
('ammonium silicofluoride','ammonium silicofluoride','INT'),
('ammonium stearate','ammonium stearate','INT'),
('ammonium sulfate','ammonium sulfate','INT'),
('ammonium valerate','ammonium valerate','INT'),
('ammonium xylenesulfonate','ammonium xylenesulfonate','INT'),
('Ammopiptanthus mongolicus stem extract','ammopiptanthus mongolicus stem extract','INT'),
('amniotic fluid (bovine)','amniotic fluid (bovine)','INT'),
('amobarbital','amobarbital','INT'),
('amodiaquine','amodiaquine','INT'),
('Amoeba proteus','amoeba proteus','INT'),
('Amomum subulatum fruit extract','amomum subulatum fruit extract','INT'),
('Amomum testaceum seed extract','amomum testaceum seed extract','INT'),
('Amomum villosum seed extract','amomum villosum seed extract','INT'),
('Amomum villosum var. xanthioides whole extract','amomum villosum var. xanthioides whole extract','INT'),
('amonafide','amonafide','INT'),
('amoproxan','amoproxan','INT'),
('amorolfine','amorolfine','INT'),
('Amorphophallus konjac root extract','amorphophallus konjac root extract','INT'),
('amosulalol','amosulalol','INT'),
('amoxapine','amoxapine','INT'),
('amoxicillin','amoxicillin','INT'),
('Ampelopsis delavayana root extract','ampelopsis delavayana root extract','INT'),
('Ampelopsis japonica root extract','ampelopsis japonica root extract','INT')
) AS v(nom, dci, pays)
WHERE NOT EXISTS (SELECT 1 FROM medicaments m WHERE LOWER(m.nom) = LOWER(v.nom));
