-- rxnorm_batch_191.sql (80 rows)
INSERT INTO medicaments (nom, dci, pays)
SELECT v.nom, v.dci, v.pays FROM (VALUES
('clonidine / hydrochlorothiazide / triamterene','clonidine / hydrochlorothiazide / triamterene','INT'),
('clonixin / cyclobenzaprine','clonixin / cyclobenzaprine','INT'),
('clonixin / cyproheptadine / ergotamine','clonixin / cyproheptadine / ergotamine','INT'),
('clonixin / ergotamine','clonixin / ergotamine','INT'),
('clonixin / propinox','clonixin / propinox','INT'),
('clonixin / scopolamine','clonixin / scopolamine','INT'),
('clopamide / dihydroergocristine / reserpine','clopamide / dihydroergocristine / reserpine','INT'),
('clopamide / pindolol','clopamide / pindolol','INT'),
('clopamide / reserpine','clopamide / reserpine','INT'),
('clorazepate / domperidone','clorazepate / domperidone','INT'),
('clorazepate / mazindol','clorazepate / mazindol','INT'),
('clorazepate / sulpiride','clorazepate / sulpiride','INT'),
('clorsulon / ivermectin','clorsulon / ivermectin','INT'),
('clostebol / neomycin','clostebol / neomycin','INT'),
('clotrimazole / dexamethasone','clotrimazole / dexamethasone','INT'),
('clotrimazole / gentamicin / mometasone','clotrimazole / gentamicin / mometasone','INT'),
('clotrimazole / hexamidine','clotrimazole / hexamidine','INT'),
('clotrimazole / hexamidine / prednisolone','clotrimazole / hexamidine / prednisolone','INT'),
('clotrimazole / hydrocortisone','clotrimazole / hydrocortisone','INT'),
('clotrimazole / miconazole','clotrimazole / miconazole','INT'),
('clotrimazole / phenylethyl alcohol','clotrimazole / phenylethyl alcohol','INT'),
('clotrimazole / urea','clotrimazole / urea','INT'),
('clotrimazole / zinc oxide','clotrimazole / zinc oxide','INT'),
('clove oil / Eucalyptus oil / menthol','clove oil / eucalyptus oil / menthol','INT'),
('coal tar / dodecyl sulfate','coal tar / dodecyl sulfate','INT'),
('coal tar / flumethasone / salicylic acid','coal tar / flumethasone / salicylic acid','INT'),
('coal tar / fluocinolone','coal tar / fluocinolone','INT'),
('coal tar / hydrocortisone','coal tar / hydrocortisone','INT'),
('coal tar / juniper tar / pine tar','coal tar / juniper tar / pine tar','INT'),
('coal tar / lactate / salicylic acid','coal tar / lactate / salicylic acid','INT'),
('coal tar / lecithin','coal tar / lecithin','INT'),
('coal tar / menthol','coal tar / menthol','INT'),
('coal tar / menthol / salicylic acid','coal tar / menthol / salicylic acid','INT'),
('coal tar / mercury, ammoniated / methenamine','coal tar / mercury, ammoniated / methenamine','INT'),
('coal tar / pine tar','coal tar / pine tar','INT'),
('coal tar / polysorbate 80','coal tar / polysorbate 80','INT'),
('coal tar / pyrithione','coal tar / pyrithione','INT'),
('coal tar / resorcinol / salicylic acid','coal tar / resorcinol / salicylic acid','INT'),
('coal tar / salicylic acid','coal tar / salicylic acid','INT'),
('coal tar / salicylic acid / sulfur','coal tar / salicylic acid / sulfur','INT'),
('coal tar / salicylic acid / sulfur, colloidal','coal tar / salicylic acid / sulfur, colloidal','INT'),
('coal tar / sulfur','coal tar / sulfur','INT'),
('coal tar / triamcinolone','coal tar / triamcinolone','INT'),
('cobalt gluconate / manganese gluconate','cobalt gluconate / manganese gluconate','INT'),
('cobamamide / cyproheptadine','cobamamide / cyproheptadine','INT'),
('cobamamide / folic acid','cobamamide / folic acid','INT'),
('cobamamide / vitamin B12','cobamamide / vitamin b12','INT'),
('cobicistat / darunavir','cobicistat / darunavir','INT'),
('cocaine / epinephrine','cocaine / epinephrine','INT'),
('cocaine / homatropine','cocaine / homatropine','INT'),
('cocoa butter / phenylephrine','cocoa butter / phenylephrine','INT'),
('cocoa butter / phenylephrine / shark liver oil','cocoa butter / phenylephrine / shark liver oil','INT'),
('cocoa butter / shark liver oil','cocoa butter / shark liver oil','INT'),
('cocoa butter / zinc oxide','cocoa butter / zinc oxide','INT'),
('coconut oil / linseed oil','coconut oil / linseed oil','INT'),
('cod liver oil / petrolatum','cod liver oil / petrolatum','INT'),
('cod liver oil / zinc oxide','cod liver oil / zinc oxide','INT'),
('codeine / dexbrompheniramine','codeine / dexbrompheniramine','INT'),
('codeine / dexbrompheniramine / pseudoephedrine','codeine / dexbrompheniramine / pseudoephedrine','INT'),
('codeine / dexchlorpheniramine / phenylephrine','codeine / dexchlorpheniramine / phenylephrine','INT'),
('codeine / diclofenac','codeine / diclofenac','INT'),
('codeine / diphenhydramine','codeine / diphenhydramine','INT'),
('codeine / diphenhydramine / phenylephrine','codeine / diphenhydramine / phenylephrine','INT'),
('codeine / ephedrine','codeine / ephedrine','INT'),
('codeine / ephedrine / guaifenesin','codeine / ephedrine / guaifenesin','INT'),
('codeine / Erysimum preparation','codeine / erysimum preparation','INT'),
('codeine / ethylmorphine','codeine / ethylmorphine','INT'),
('codeine / guaiacolsulfonate','codeine / guaiacolsulfonate','INT'),
('codeine / guaiacolsulfonic acid / promethazine','codeine / guaiacolsulfonic acid / promethazine','INT'),
('codeine / guaifenesin','codeine / guaifenesin','INT'),
('codeine / guaifenesin / pheniramine','codeine / guaifenesin / pheniramine','INT'),
('codeine / guaifenesin / phenylephrine','codeine / guaifenesin / phenylephrine','INT'),
('codeine / guaifenesin / phenylpropanolamine','codeine / guaifenesin / phenylpropanolamine','INT'),
('codeine / guaifenesin / promethazine','codeine / guaifenesin / promethazine','INT'),
('codeine / guaifenesin / pseudoephedrine','codeine / guaifenesin / pseudoephedrine','INT'),
('codeine / ibuprofen','codeine / ibuprofen','INT'),
('codeine / iodinated glycerol','codeine / iodinated glycerol','INT'),
('codeine / kaolin','codeine / kaolin','INT'),
('codeine / menthol / pheniramine / phenylephrine','codeine / menthol / pheniramine / phenylephrine','INT'),
('codeine / papaverine','codeine / papaverine','INT')
) AS v(nom, dci, pays)
WHERE NOT EXISTS (SELECT 1 FROM medicaments m WHERE LOWER(m.nom) = LOWER(v.nom));
