-- rxnorm_batch_149.sql (80 rows)
INSERT INTO medicaments (nom, dci, pays)
SELECT v.nom, v.dci, v.pays FROM (VALUES
('sorbitan distearate','sorbitan distearate','INT'),
('sorbitan isostearate','sorbitan isostearate','INT'),
('sorbitan monocaprylate','sorbitan monocaprylate','INT'),
('sorbitan monolaurate','sorbitan monolaurate','INT'),
('sorbitan monooleate','sorbitan monooleate','INT'),
('sorbitan monopalmitate','sorbitan monopalmitate','INT'),
('sorbitan monostearate','sorbitan monostearate','INT'),
('sorbitan olivate','sorbitan olivate','INT'),
('sorbitan sesquiisostearate','sorbitan sesquiisostearate','INT'),
('sorbitan sesquioleate','sorbitan sesquioleate','INT'),
('sorbitan trioleate','sorbitan trioleate','INT'),
('sorbitan tristearate','sorbitan tristearate','INT'),
('sorbitol','sorbitol','INT'),
('sorbitol monooleate','sorbitol monooleate','INT'),
('sorbityl laurate','sorbityl laurate','INT'),
('Sorbus aucuparia fruit extract','sorbus aucuparia fruit extract','INT'),
('Sorbus domestica whole extract','sorbus domestica whole extract','INT'),
('Sorghum bicolor pollen extract','sorghum bicolor pollen extract','INT'),
('Sorghum bicolor stem juice','sorghum bicolor stem juice','INT'),
('Sorghum bicolor whole extract','sorghum bicolor whole extract','INT'),
('sorghum extract','sorghum extract','INT'),
('sotagliflozin','sotagliflozin','INT'),
('sotalol','sotalol','INT'),
('sotatercept','sotatercept','INT'),
('sotorasib','sotorasib','INT'),
('sotrovimab','sotrovimab','INT'),
('sour cherry allergenic extract','sour cherry allergenic extract','INT'),
('sour cherry seed oil','sour cherry seed oil','INT'),
('soursop extract','soursop extract','INT'),
('southern bayberry pollen extract','southern bayberry pollen extract','INT'),
('southern flounder allergenic extract','southern flounder allergenic extract','INT'),
('southern ragweed pollen extract','southern ragweed pollen extract','INT'),
('southern yellow jacket venom protein','southern yellow jacket venom protein','INT'),
('soy acid','soy acid','INT'),
('soy germ','soy germ','INT'),
('soy protein isolate','soy protein isolate','INT'),
('soy protein-iron complex','soy protein-iron complex','INT'),
('soy sphingolipids','soy sphingolipids','INT'),
('soy sterol','soy sterol','INT'),
('soybean allergenic extract','soybean allergenic extract','INT'),
('soybean germ extract','soybean germ extract','INT'),
('soybean lecithin','soybean lecithin','INT'),
('soybean oil','soybean oil','INT'),
('soybean preparation','soybean preparation','INT'),
('soybean seed oil','soybean seed oil','INT'),
('soyethyl morpholinium ethosulfate','soyethyl morpholinium ethosulfate','INT'),
('Spanish chestnut extract','spanish chestnut extract','INT'),
('spanish sardine preparation','spanish sardine preparation','INT'),
('Spanish thyme oil','spanish thyme oil','INT'),
('Sparassis crispa fruiting body extract','sparassis crispa fruiting body extract','INT'),
('Sparassis crispa whole extract','sparassis crispa whole extract','INT'),
('sparfloxacin','sparfloxacin','INT'),
('Sparganium stoloniferium whole extract','sparganium stoloniferium whole extract','INT'),
('Sparganium stoloniferum root extract','sparganium stoloniferum root extract','INT'),
('sparsentan','sparsentan','INT'),
('Spatholobus suberectus stem extract','spatholobus suberectus stem extract','INT'),
('spearmint allergenic extract','spearmint allergenic extract','INT'),
('spearmint extract','spearmint extract','INT'),
('spearmint oil','spearmint oil','INT'),
('spectinomycin','spectinomycin','INT'),
('spelt seed extract','spelt seed extract','INT'),
('Speranskia tuberculata whole extract','speranskia tuberculata whole extract','INT'),
('spermaceti','spermaceti','INT'),
('spermidine','spermidine','INT'),
('spermine','spermine','INT'),
('spesolimab','spesolimab','INT'),
('Sphaeranthus indicus flowering top extract','sphaeranthus indicus flowering top extract','INT'),
('Sphagnum squarrosum extract','sphagnum squarrosum extract','INT'),
('sphinganine','sphinganine','INT'),
('Spigelia anthelmia preparation','spigelia anthelmia preparation','INT'),
('Spigelia marilandica preparation','spigelia marilandica preparation','INT'),
('Spigelia marilandica root extract','spigelia marilandica root extract','INT'),
('spike lavender oil','spike lavender oil','INT'),
('spinach allergenic extract','spinach allergenic extract','INT'),
('spinach extract','spinach extract','INT'),
('Spinacia oleracea root extract','spinacia oleracea root extract','INT'),
('spinosad','spinosad','INT'),
('spiny pigweed pollen extract','spiny pigweed pollen extract','INT'),
('spiramycin','spiramycin','INT'),
('Spiranthes spiralis root extract','spiranthes spiralis root extract','INT')
) AS v(nom, dci, pays)
WHERE NOT EXISTS (SELECT 1 FROM medicaments m WHERE LOWER(m.nom) = LOWER(v.nom));
