-- rxnorm_batch_225.sql (80 rows)
INSERT INTO medicaments (nom, dci, pays)
SELECT v.nom, v.dci, v.pays FROM (VALUES
('eliglustat tartrate','eliglustat tartrate','INT'),
('elranatamab-bcmm','elranatamab-bcmm','INT'),
('eltrombopag choline','eltrombopag choline','INT'),
('eltrombopag olamine','eltrombopag olamine','INT'),
('emapalumab-lzsg','emapalumab-lzsg','INT'),
('emedastine difumarate','emedastine difumarate','INT'),
('emepronium bromide','emepronium bromide','INT'),
('emepronium carrageenate','emepronium carrageenate','INT'),
('emetine hydrochloride','emetine hydrochloride','INT'),
('emicizumab-kxwh','emicizumab-kxwh','INT'),
('enalapril maleate','enalapril maleate','INT'),
('enalaprilat anhydrous','enalaprilat anhydrous','INT'),
('enalaprilat dihydrate','enalaprilat dihydrate','INT'),
('enasidenib mesylate','enasidenib mesylate','INT'),
('encainide hydrochloride','encainide hydrochloride','INT'),
('endothelial growth factor A, human vascular','endothelial growth factor a, human vascular','INT'),
('enfortumab vedotin','enfortumab vedotin','INT'),
('enfortumab vedotin-ejfv','enfortumab vedotin-ejfv','INT'),
('enoxaparin sodium','enoxaparin sodium','INT'),
('ensartinib hydrochloride','ensartinib hydrochloride','INT'),
('entecavir anhydrous','entecavir anhydrous','INT'),
('entsufon sodium','entsufon sodium','INT'),
('epcoritamab-bysp','epcoritamab-bysp','INT'),
('ephedrine hydrate','ephedrine hydrate','INT'),
('ephedrine hydrochloride','ephedrine hydrochloride','INT'),
('ephedrine sulfate','ephedrine sulfate','INT'),
('ephedrine tannate','ephedrine tannate','INT'),
('epigallocatechin gallate palmitates','epigallocatechin gallate palmitates','INT'),
('epigallocatechin gallate stearates','epigallocatechin gallate stearates','INT'),
('epinastine hydrochloride','epinastine hydrochloride','INT'),
('epinephrine bitartrate','epinephrine bitartrate','INT'),
('epinephrine hydrochloride','epinephrine hydrochloride','INT'),
('epinephrine sulfate','epinephrine sulfate','INT'),
('epinephryl borate','epinephryl borate','INT'),
('epirubicin hydrochloride','epirubicin hydrochloride','INT'),
('eplontersen sodium','eplontersen sodium','INT'),
('epoetin alfa-epbx','epoetin alfa-epbx','INT'),
('epoprostenol sodium','epoprostenol sodium','INT'),
('eprazinone HCl','eprazinone hcl','INT'),
('eprosartan mesylate','eprosartan mesylate','INT'),
('eprozinol hydrochloride','eprozinol hydrochloride','INT'),
('eptacog alfa activated','eptacog alfa activated','INT'),
('eptinezumab-jjmr','eptinezumab-jjmr','INT'),
('equol, (+-)-','equol, (+-)-','INT'),
('Equus caballus collagen','equus caballus collagen','INT'),
('eravacycline dihydrochloride','eravacycline dihydrochloride','INT'),
('erbium sulfate octahydrate','erbium sulfate octahydrate','INT'),
('erenumab-aooe','erenumab-aooe','INT'),
('ergonovine maleate','ergonovine maleate','INT'),
('ergotamine tartrate','ergotamine tartrate','INT'),
('eribulin mesylate','eribulin mesylate','INT'),
('erlotinib hydrochloride','erlotinib hydrochloride','INT'),
('ertapenem sodium','ertapenem sodium','INT'),
('ertugliflozin pidolate','ertugliflozin pidolate','INT'),
('erythromycin estolate','erythromycin estolate','INT'),
('erythromycin ethylsuccinate','erythromycin ethylsuccinate','INT'),
('erythromycin gluceptate','erythromycin gluceptate','INT'),
('erythromycin lactobionate','erythromycin lactobionate','INT'),
('erythromycin phosphate','erythromycin phosphate','INT'),
('erythromycin stearate','erythromycin stearate','INT'),
('erythromycin stinoprate','erythromycin stinoprate','INT'),
('erythrosine sodium','erythrosine sodium','INT'),
('erythrosine sodium anhydrous','erythrosine sodium anhydrous','INT'),
('escitalopram oxalate','escitalopram oxalate','INT'),
('esketamine hydrochloride','esketamine hydrochloride','INT'),
('eslicarbazepine acetate','eslicarbazepine acetate','INT'),
('esmolol hydrochloride','esmolol hydrochloride','INT'),
('esomeprazole magnesium','esomeprazole magnesium','INT'),
('esomeprazole magnesium dihydrate','esomeprazole magnesium dihydrate','INT'),
('esomeprazole magnesium trihydrate','esomeprazole magnesium trihydrate','INT'),
('esomeprazole sodium','esomeprazole sodium','INT'),
('esomeprazole strontium','esomeprazole strontium','INT'),
('estetrol monohydrate','estetrol monohydrate','INT'),
('estradiol 3-benzoate','estradiol 3-benzoate','INT'),
('estradiol acetate','estradiol acetate','INT'),
('estradiol cypionate','estradiol cypionate','INT'),
('estradiol hemihydrate','estradiol hemihydrate','INT'),
('estradiol valerate','estradiol valerate','INT'),
('estramustine phosphate','estramustine phosphate','INT'),
('estramustine phosphate sodium','estramustine phosphate sodium','INT')
) AS v(nom, dci, pays)
WHERE NOT EXISTS (SELECT 1 FROM medicaments m WHERE LOWER(m.nom) = LOWER(v.nom));
