-- rxnorm_batch_204.sql (80 rows)
INSERT INTO medicaments (nom, dci, pays)
SELECT v.nom, v.dci, v.pays FROM (VALUES
('lidocaine / ruscogenin','lidocaine / ruscogenin','INT'),
('lidocaine / sodium chloride','lidocaine / sodium chloride','INT'),
('lidocaine / tetracaine','lidocaine / tetracaine','INT'),
('lidocaine / tetracaine / witch hazel','lidocaine / tetracaine / witch hazel','INT'),
('lidocaine / triamcinolone','lidocaine / triamcinolone','INT'),
('lidocaine / tribenoside','lidocaine / tribenoside','INT'),
('lidocaine / tyrothricin','lidocaine / tyrothricin','INT'),
('lidocaine / zinc oxide','lidocaine / zinc oxide','INT'),
('lidocaine / zinc sulfate','lidocaine / zinc sulfate','INT'),
('linagliptin / metformin','linagliptin / metformin','INT'),
('lincomycin / niacin','lincomycin / niacin','INT'),
('linoleate / ricinoleate','linoleate / ricinoleate','INT'),
('linoleate / sunflower oil','linoleate / sunflower oil','INT'),
('linseed oil / soy protein isolate','linseed oil / soy protein isolate','INT'),
('linseed oil / vitamin E','linseed oil / vitamin e','INT'),
('lipase / simethicone','lipase / simethicone','INT'),
('lithium carbonate / sodium chloride','lithium carbonate / sodium chloride','INT'),
('lithium succinate / zinc sulfate','lithium succinate / zinc sulfate','INT'),
('liver,desiccated / phenobarbital','liver,desiccated / phenobarbital','INT'),
('loperamide / neomycin','loperamide / neomycin','INT'),
('loperamide / simethicone','loperamide / simethicone','INT'),
('lopinavir / ritonavir','lopinavir / ritonavir','INT'),
('loratadine / povidone','loratadine / povidone','INT'),
('loratadine / pseudoephedrine','loratadine / pseudoephedrine','INT'),
('loteprednol etabonate / tobramycin','loteprednol etabonate / tobramycin','INT'),
('lovastatin / niacin','lovastatin / niacin','INT'),
('lufenuron / milbemycin oxime','lufenuron / milbemycin oxime','INT'),
('lufenuron / milbemycin oxime / praziquantel','lufenuron / milbemycin oxime / praziquantel','INT'),
('lutein / vitamin E / zeaxanthin','lutein / vitamin e / zeaxanthin','INT'),
('lutein / zeaxanthin','lutein / zeaxanthin','INT'),
('lyapolate / niacin','lyapolate / niacin','INT'),
('lycopene / vitamin E','lycopene / vitamin e','INT'),
('lysine / niacinamide / thiamine','lysine / niacinamide / thiamine','INT'),
('lysine / phenylalanine','lysine / phenylalanine','INT'),
('lysine / proline','lysine / proline','INT'),
('lysine / zinc oxide','lysine / zinc oxide','INT'),
('macitentan / tadalafil','macitentan / tadalafil','INT'),
('magaldrate / simethicone','magaldrate / simethicone','INT'),
('magnesium aspartate / potassium aspartate','magnesium aspartate / potassium aspartate','INT'),
('magnesium carbonate / magnesium oxide','magnesium carbonate / magnesium oxide','INT'),
('magnesium carbonate / sodium bicarbonate','magnesium carbonate / sodium bicarbonate','INT'),
('magnesium chloride / sodium chloride','magnesium chloride / sodium chloride','INT'),
('magnesium chloride / tubocurarine','magnesium chloride / tubocurarine','INT'),
('magnesium citrate / magnesium gluconate','magnesium citrate / magnesium gluconate','INT'),
('magnesium citrate / magnesium phosphate','magnesium citrate / magnesium phosphate','INT'),
('magnesium citrate / potassium citrate','magnesium citrate / potassium citrate','INT'),
('magnesium gluconate / magnesium oxide','magnesium gluconate / magnesium oxide','INT'),
('magnesium gluconate / potassium tartrate','magnesium gluconate / potassium tartrate','INT'),
('magnesium hydroxide / malic acid','magnesium hydroxide / malic acid','INT'),
('magnesium hydroxide / mineral oil','magnesium hydroxide / mineral oil','INT'),
('magnesium hydroxide / simethicone','magnesium hydroxide / simethicone','INT'),
('magnesium lactate / vitamin B6','magnesium lactate / vitamin b6','INT'),
('magnesium malate / malic acid / vitamin B6','magnesium malate / malic acid / vitamin b6','INT'),
('magnesium oxide / magnesium sulfate','magnesium oxide / magnesium sulfate','INT'),
('magnesium oxide / pyridoxine','magnesium oxide / pyridoxine','INT'),
('magnesium oxide / sodium bicarbonate','magnesium oxide / sodium bicarbonate','INT'),
('magnesium oxide / vitamin B6','magnesium oxide / vitamin b6','INT'),
('magnesium oxide / zinc oxide','magnesium oxide / zinc oxide','INT'),
('magnesium salicylate / phenyltoloxamine','magnesium salicylate / phenyltoloxamine','INT'),
('magnesium sulfate / peptones','magnesium sulfate / peptones','INT'),
('magnesium sulfate / phenolphthalein','magnesium sulfate / phenolphthalein','INT'),
('malic acid / xylitol','malic acid / xylitol','INT'),
('mannitol / mecobalamin','mannitol / mecobalamin','INT'),
('mannitol / menthol','mannitol / menthol','INT'),
('mannitol / phenobarbital','mannitol / phenobarbital','INT'),
('mannitol / sorbitol','mannitol / sorbitol','INT'),
('matrine / salicylic acid','matrine / salicylic acid','INT'),
('mazindol / tiratricol','mazindol / tiratricol','INT'),
('mebendazole / niclosamide / tinidazole','mebendazole / niclosamide / tinidazole','INT'),
('mebendazole / tinidazole','mebendazole / tinidazole','INT'),
('mechlorethamine / quinine / terpin hydrate','mechlorethamine / quinine / terpin hydrate','INT'),
('mechlorethamine / terpin hydrate','mechlorethamine / terpin hydrate','INT'),
('meclizine / niacin','meclizine / niacin','INT'),
('meclizine / vitamin B6','meclizine / vitamin b6','INT'),
('mecobalamin / vitamin B12','mecobalamin / vitamin b12','INT'),
('medetomidine / vatinoxan','medetomidine / vatinoxan','INT'),
('mefruside / methyldopa','mefruside / methyldopa','INT'),
('mefruside / nifedipine','mefruside / nifedipine','INT'),
('mefruside / reserpine','mefruside / reserpine','INT'),
('meglumine benzoate / polysorbates','meglumine benzoate / polysorbates','INT')
) AS v(nom, dci, pays)
WHERE NOT EXISTS (SELECT 1 FROM medicaments m WHERE LOWER(m.nom) = LOWER(v.nom));
