-- rxnorm_batch_130.sql (80 rows)
INSERT INTO medicaments (nom, dci, pays)
SELECT v.nom, v.dci, v.pays FROM (VALUES
('polyoxyl 60 hydrogenated castor oil','polyoxyl 60 hydrogenated castor oil','INT'),
('polyoxyl 8 stearate','polyoxyl 8 stearate','INT'),
('Polypodium lepidopteris root extract','polypodium lepidopteris root extract','INT'),
('Polypodium leucotomos','polypodium leucotomos','INT'),
('Polypodium virginianum root extract','polypodium virginianum root extract','INT'),
('polyquaternium-44','polyquaternium-44','INT'),
('polyquaternium-5','polyquaternium-5','INT'),
('polyquaternium-53','polyquaternium-53','INT'),
('polyquaternium-55','polyquaternium-55','INT'),
('polyquaternium-68','polyquaternium-68','INT'),
('polysaccharide iron complex','polysaccharide iron complex','INT'),
('polysaccharide-K','polysaccharide-k','INT'),
('polysilicone-15','polysilicone-15','INT'),
('polysorbate 20','polysorbate 20','INT'),
('polysorbate 21','polysorbate 21','INT'),
('polysorbate 40','polysorbate 40','INT'),
('polysorbate 60','polysorbate 60','INT'),
('polysorbate 61','polysorbate 61','INT'),
('polysorbate 65','polysorbate 65','INT'),
('polysorbate 80','polysorbate 80','INT'),
('polysorbate 81','polysorbate 81','INT'),
('polysorbate 85','polysorbate 85','INT'),
('polysorbates','polysorbates','INT'),
('polystyrene sulfonate','polystyrene sulfonate','INT'),
('polysulfated glycosaminoglycan','polysulfated glycosaminoglycan','INT'),
('polytetrafluoroethylene','polytetrafluoroethylene','INT'),
('polythiazide','polythiazide','INT'),
('polyurethane-35 (not more than MPA.S at 40 %)','polyurethane-35 (not more than mpa.s at 40 %)','INT'),
('polyurethane-39','polyurethane-39','INT'),
('polyurethane-62','polyurethane-62','INT'),
('polyvalent Crotalidae antivenin','polyvalent crotalidae antivenin','INT'),
('polyvinyl acetate','polyvinyl acetate','INT'),
('polyvinyl acetate phthalate','polyvinyl acetate phthalate','INT'),
('polyvinyl alcohol','polyvinyl alcohol','INT'),
('pomalidomide','pomalidomide','INT'),
('pomegranate extract','pomegranate extract','INT'),
('pomegranate fruit extract','pomegranate fruit extract','INT'),
('pomegranate fruit rind extract','pomegranate fruit rind extract','INT'),
('pomegranate juice','pomegranate juice','INT'),
('pomegranate seed oil','pomegranate seed oil','INT'),
('pomiferin','pomiferin','INT'),
('ponatinib','ponatinib','INT'),
('ponazuril','ponazuril','INT'),
('Poncirus trifoliata fruit extract','poncirus trifoliata fruit extract','INT'),
('ponesimod','ponesimod','INT'),
('Pongamia pinnata fruit extract','pongamia pinnata fruit extract','INT'),
('pongamol','pongamol','INT'),
('poppy seed allergenic extract','poppy seed allergenic extract','INT'),
('poppy seed oil','poppy seed oil','INT'),
('Populus alba bark extract','populus alba bark extract','INT'),
('Populus alba leaf extract','populus alba leaf extract','INT'),
('Populus balsamifera leaf bud extract','populus balsamifera leaf bud extract','INT'),
('Populus nigra leaf bud extract','populus nigra leaf bud extract','INT'),
('Populus tremula flowering top extract','populus tremula flowering top extract','INT'),
('Populus tremula whole extract','populus tremula whole extract','INT'),
('Populus tremuloides bark extract','populus tremuloides bark extract','INT'),
('Populus tremuloides leaf extract','populus tremuloides leaf extract','INT'),
('Populus tremuloides whole extract','populus tremuloides whole extract','INT'),
('Populus trichocarpa whole extract','populus trichocarpa whole extract','INT'),
('poractant alfa','poractant alfa','INT'),
('porcine heart preparation','porcine heart preparation','INT'),
('pork allergenic extract','pork allergenic extract','INT'),
('pork brain preparation','pork brain preparation','INT'),
('pork collagen preparation','pork collagen preparation','INT'),
('pork intestine preparation','pork intestine preparation','INT'),
('pork kidney preparation','pork kidney preparation','INT'),
('pork liver preparation','pork liver preparation','INT'),
('Porphyra tenera extract','porphyra tenera extract','INT'),
('Porphyra umbilicalis extract','porphyra umbilicalis extract','INT'),
('Porphyra yezoensis extract','porphyra yezoensis extract','INT'),
('Porphyridium purpureum extract','porphyridium purpureum extract','INT'),
('Portulaca grandiflora seed extract','portulaca grandiflora seed extract','INT'),
('Portulaca grandiflora whole extract','portulaca grandiflora whole extract','INT'),
('Portulaca oleracea leaf extract','portulaca oleracea leaf extract','INT'),
('Portulaca oleracea whole extract','portulaca oleracea whole extract','INT'),
('Portulaca oreracea seed extract','portulaca oreracea seed extract','INT'),
('Portulaca pilosa whole extract','portulaca pilosa whole extract','INT'),
('posaconazole','posaconazole','INT'),
('post oak pollen extract','post oak pollen extract','INT'),
('posterior pituitary hormones','posterior pituitary hormones','INT')
) AS v(nom, dci, pays)
WHERE NOT EXISTS (SELECT 1 FROM medicaments m WHERE LOWER(m.nom) = LOWER(v.nom));
