-- rxnorm_batch_063.sql (80 rows)
INSERT INTO medicaments (nom, dci, pays)
SELECT v.nom, v.dci, v.pays FROM (VALUES
('enoxolone dipotassium','enoxolone dipotassium','INT'),
('enrofloxacin','enrofloxacin','INT'),
('ensartinib','ensartinib','INT'),
('ensifentrine','ensifentrine','INT'),
('ensulizole','ensulizole','INT'),
('entacapone','entacapone','INT'),
('Entada phaseoloides leaf extract','entada phaseoloides leaf extract','INT'),
('Entada phaseoloides whole extract','entada phaseoloides whole extract','INT'),
('Entamoeba histolytica','entamoeba histolytica','INT'),
('entecavir','entecavir','INT'),
('Enterobacter aerogenes','enterobacter aerogenes','INT'),
('Enterobacter cloacae','enterobacter cloacae','INT'),
('Enterobius vermicularis preparation','enterobius vermicularis preparation','INT'),
('Enterococcus faecalis','enterococcus faecalis','INT'),
('Enterococcus faecium','enterococcus faecium','INT'),
('entrectinib','entrectinib','INT'),
('entsufon','entsufon','INT'),
('enzacamene','enzacamene','INT'),
('enzalutamide','enzalutamide','INT'),
('eosine yellowish','eosine yellowish','INT'),
('epcoritamab','epcoritamab','INT'),
('Eperua falcata bark extract','eperua falcata bark extract','INT'),
('Ephedra distachya flowering twig extract','ephedra distachya flowering twig extract','INT'),
('Ephedra nevadensis whole extract','ephedra nevadensis whole extract','INT'),
('Ephedra sinica root extract','ephedra sinica root extract','INT'),
('Ephedra sinica stem extract','ephedra sinica stem extract','INT'),
('ephedrine','ephedrine','INT'),
('epicatechin','epicatechin','INT'),
('Epicoccum nigrum allergenic extract','epicoccum nigrum allergenic extract','INT'),
('epicriptine','epicriptine','INT'),
('epidermal growth factor','epidermal growth factor','INT'),
('epidermophyton floccosum allergenic extract','epidermophyton floccosum allergenic extract','INT'),
('Epifagus virginiana extract','epifagus virginiana extract','INT'),
('Epigaea repens extract','epigaea repens extract','INT'),
('epigallocatechin gallate','epigallocatechin gallate','INT'),
('epigallocatechin gallatyl glucoside','epigallocatechin gallatyl glucoside','INT'),
('Epilobium angustifolium flowering top extract','epilobium angustifolium flowering top extract','INT'),
('Epilobium angustifolium leaf extract','epilobium angustifolium leaf extract','INT'),
('Epilobium angustifolium whole extract','epilobium angustifolium whole extract','INT'),
('Epilobium fleischeri whole extract','epilobium fleischeri whole extract','INT'),
('Epimedium brevicornu whole extract','epimedium brevicornu whole extract','INT'),
('Epimedium grandiflorum flowering top extract','epimedium grandiflorum flowering top extract','INT'),
('Epimedium grandiflorum top extract','epimedium grandiflorum top extract','INT'),
('Epimedium grandiflorum whole extract','epimedium grandiflorum whole extract','INT'),
('Epimedium pubescens whole extract','epimedium pubescens whole extract','INT'),
('Epimedium sagittatum leaf extract','epimedium sagittatum leaf extract','INT'),
('Epimedium sagittatum top extract','epimedium sagittatum top extract','INT'),
('Epimedium wushanense whole extract','epimedium wushanense whole extract','INT'),
('epinastine','epinastine','INT'),
('epinephrine','epinephrine','INT'),
('epirubicin','epirubicin','INT'),
('eplerenone','eplerenone','INT'),
('eplontersen','eplontersen','INT'),
('epoetin alfa','epoetin alfa','INT'),
('epoetin beta','epoetin beta','INT'),
('epomediol','epomediol','INT'),
('epoprostenol','epoprostenol','INT'),
('epoxiconazole','epoxiconazole','INT'),
('eprazinone','eprazinone','INT'),
('eprinomectin','eprinomectin','INT'),
('eprosartan','eprosartan','INT'),
('eprozinol','eprozinol','INT'),
('epsiprantel','epsiprantel','INT'),
('Epstein-Barr virus','epstein-barr virus','INT'),
('eptifibatide','eptifibatide','INT'),
('eptinezumab','eptinezumab','INT'),
('equine diphtheria antitoxin','equine diphtheria antitoxin','INT'),
('Equisetum arvense branch extract','equisetum arvense branch extract','INT'),
('Equisetum arvense stem oil','equisetum arvense stem oil','INT'),
('Equisetum arvense top extract','equisetum arvense top extract','INT'),
('Equisetum arvense whole extract','equisetum arvense whole extract','INT'),
('Equisetum fluviatile whole extract','equisetum fluviatile whole extract','INT'),
('Equisetum hyemale extract','equisetum hyemale extract','INT'),
('Equisetum hyemale top extract','equisetum hyemale top extract','INT'),
('equol, (+)','equol, (+)','INT'),
('equol, (-)-','equol, (-)-','INT'),
('Equus caballus leg callous preparation','equus caballus leg callous preparation','INT'),
('Equus caballus whole preparation','equus caballus whole preparation','INT'),
('eravacycline','eravacycline','INT'),
('erbium','erbium','INT')
) AS v(nom, dci, pays)
WHERE NOT EXISTS (SELECT 1 FROM medicaments m WHERE LOWER(m.nom) = LOWER(v.nom));
