-- rxnorm_batch_026.sql (80 rows)
INSERT INTO medicaments (nom, dci, pays)
SELECT v.nom, v.dci, v.pays FROM (VALUES
('black walnut pollen extract','black walnut pollen extract','INT'),
('black walnut shell extract','black walnut shell extract','INT'),
('black widow spider preparation','black widow spider preparation','INT'),
('black widow spider venom','black widow spider venom','INT'),
('black willow pollen extract','black willow pollen extract','INT'),
('black-eyed pea allergenic extract','black-eyed pea allergenic extract','INT'),
('blackback founder extract','blackback founder extract','INT'),
('blackberry allergenic extract','blackberry allergenic extract','INT'),
('blackberry flavor','blackberry flavor','INT'),
('blackfoot abalone extract','blackfoot abalone extract','INT'),
('blancophor R','blancophor r','INT'),
('Blastocystis hominis','blastocystis hominis','INT'),
('Blatta orientalis preparation','blatta orientalis preparation','INT'),
('bleomycin','bleomycin','INT'),
('Bletilla striata bulb extract','bletilla striata bulb extract','INT'),
('Bletilla striata whole extract','bletilla striata whole extract','INT'),
('blinatumomab','blinatumomab','INT'),
('Blitum bonus-henricus pollen extract','blitum bonus-henricus pollen extract','INT'),
('blue beech pollen extract','blue beech pollen extract','INT'),
('blue cohosh extract','blue cohosh extract','INT'),
('blue crab preparation','blue crab preparation','INT'),
('blue spruce pollen extract','blue spruce pollen extract','INT'),
('blueberry allergenic extract','blueberry allergenic extract','INT'),
('blueberry extract','blueberry extract','INT'),
('bluefish allergenic extract','bluefish allergenic extract','INT'),
('boceprevir','boceprevir','INT'),
('Boerhavia diffusa root extract','boerhavia diffusa root extract','INT'),
('Boesenbergia rotunda root extract','boesenbergia rotunda root extract','INT'),
('boldenone','boldenone','INT'),
('Boletus luridus fruiting body extract','boletus luridus fruiting body extract','INT'),
('Boletus satanas fruiting body extract','boletus satanas fruiting body extract','INT'),
('Bombyx mori larva preparation','bombyx mori larva preparation','INT'),
('Bombyx mori whole preparation','bombyx mori whole preparation','INT'),
('bone meal','bone meal','INT'),
('bopindolol','bopindolol','INT'),
('borage extract','borage extract','INT'),
('borage oil','borage oil','INT'),
('Borago officinalis flower extract','borago officinalis flower extract','INT'),
('Borago officinalis seed extract','borago officinalis seed extract','INT'),
('Borago officinialis whole extract','borago officinialis whole extract','INT'),
('borate ion','borate ion','INT'),
('Bordetella pertussis','bordetella pertussis','INT'),
('boric acid','boric acid','INT'),
('bornaprine','bornaprine','INT'),
('borneol','borneol','INT'),
('borneol, (+)-','borneol, (+)-','INT'),
('borneol, (-)-','borneol, (-)-','INT'),
('bornyl acetate','bornyl acetate','INT'),
('bornyl acetate, (-)-','bornyl acetate, (-)-','INT'),
('borogluconate','borogluconate','INT'),
('boroglycerin','boroglycerin','INT'),
('boron','boron','INT'),
('boron citrate','boron citrate','INT'),
('boron gluconate','boron gluconate','INT'),
('boron nitride','boron nitride','INT'),
('Borrelia burgdorferi','borrelia burgdorferi','INT'),
('bortezomib','bortezomib','INT'),
('Bos taurus achilles tendon preparation','bos taurus achilles tendon preparation','INT'),
('Bos taurus adrenal cortex preparation','bos taurus adrenal cortex preparation','INT'),
('Bos taurus adrenal gland preparation','bos taurus adrenal gland preparation','INT'),
('Bos taurus ankle joint preparation','bos taurus ankle joint preparation','INT'),
('Bos taurus artery preparation','bos taurus artery preparation','INT'),
('Bos taurus bile preparation','bos taurus bile preparation','INT'),
('Bos taurus bone marrow preparation','bos taurus bone marrow preparation','INT'),
('Bos taurus bone preparation','bos taurus bone preparation','INT'),
('Bos taurus brain preparation','bos taurus brain preparation','INT'),
('Bos taurus brainstem preparation','bos taurus brainstem preparation','INT'),
('Bos taurus cartilage preparation','bos taurus cartilage preparation','INT'),
('Bos taurus catalase preparation','bos taurus catalase preparation','INT'),
('Bos taurus cerebelum preparation','bos taurus cerebelum preparation','INT'),
('Bos taurus colon preparation','bos taurus colon preparation','INT'),
('Bos taurus colostrum preparation','bos taurus colostrum preparation','INT'),
('Bos taurus conjunctiva preparation','bos taurus conjunctiva preparation','INT'),
('Bos taurus diencephalon preparation','bos taurus diencephalon preparation','INT'),
('Bos taurus duodenum preparation','bos taurus duodenum preparation','INT'),
('Bos taurus esophagus preparation','bos taurus esophagus preparation','INT'),
('Bos taurus eye preparation','bos taurus eye preparation','INT'),
('Bos taurus frontal lobe preparation','bos taurus frontal lobe preparation','INT'),
('Bos taurus gallbladder preparation','bos taurus gallbladder preparation','INT'),
('Bos taurus gallstone preparation','bos taurus gallstone preparation','INT')
) AS v(nom, dci, pays)
WHERE NOT EXISTS (SELECT 1 FROM medicaments m WHERE LOWER(m.nom) = LOWER(v.nom));
