-- rxnorm_batch_103.sql (80 rows)
INSERT INTO medicaments (nom, dci, pays)
SELECT v.nom, v.dci, v.pays FROM (VALUES
('menthone, (+)-','menthone, (+)-','INT'),
('menthone, (+/-)-','menthone, (+/-)-','INT'),
('menthyl acetate, (+/-)-','menthyl acetate, (+/-)-','INT'),
('menthyl acetate, (-)-','menthyl acetate, (-)-','INT'),
('menthyl ethylamido oxalate','menthyl ethylamido oxalate','INT'),
('menthyl ethylene glycol carbonate, (-)-','menthyl ethylene glycol carbonate, (-)-','INT'),
('menthyl lactate','menthyl lactate','INT'),
('menthyl pyrrolidone carboxylate, (-),DL-','menthyl pyrrolidone carboxylate, (-),dl-','INT'),
('menthyl salicylate','menthyl salicylate','INT'),
('Menyanthes trifoliata extract','menyanthes trifoliata extract','INT'),
('Menyanthes trifoliata leaf extract','menyanthes trifoliata leaf extract','INT'),
('mepenzolate','mepenzolate','INT'),
('meperidine','meperidine','INT'),
('mephenesin','mephenesin','INT'),
('mephentermine','mephentermine','INT'),
('mephenytoin','mephenytoin','INT'),
('Mephitis mephitis anal gland fluid preparation','mephitis mephitis anal gland fluid preparation','INT'),
('mephobarbital','mephobarbital','INT'),
('mepindolol','mepindolol','INT'),
('mepirodipine','mepirodipine','INT'),
('mepivacaine','mepivacaine','INT'),
('mepolizumab','mepolizumab','INT'),
('meprednisone','meprednisone','INT'),
('meprobamate','meprobamate','INT'),
('meptazinol','meptazinol','INT'),
('mequinol','mequinol','INT'),
('mequitazine','mequitazine','INT'),
('meradimate','meradimate','INT'),
('merbromin','merbromin','INT'),
('mercaptopurine','mercaptopurine','INT'),
('Mercurialis annua flowering top extract','mercurialis annua flowering top extract','INT'),
('Mercurialis perennis extract','mercurialis perennis extract','INT'),
('Mercurialis perennis whole extract','mercurialis perennis whole extract','INT'),
('mercuric cation','mercuric cation','INT'),
('mercuric chloride','mercuric chloride','INT'),
('mercuric cyanide','mercuric cyanide','INT'),
('mercuric iodide','mercuric iodide','INT'),
('mercuric oxide','mercuric oxide','INT'),
('mercuric sulfate','mercuric sulfate','INT'),
('mercuric sulfide','mercuric sulfide','INT'),
('mercurius solubilis preparation','mercurius solubilis preparation','INT'),
('mercurous iodide preparation','mercurous iodide preparation','INT'),
('mercury','mercury','INT'),
('mercury, ammoniated','mercury, ammoniated','INT'),
('meropenem','meropenem','INT'),
('mersalyl','mersalyl','INT'),
('mesalamine','mesalamine','INT'),
('Mesembryanthemum crystallinum whole extract','mesembryanthemum crystallinum whole extract','INT'),
('Mesembryanthemum tortuosum whole extract','mesembryanthemum tortuosum whole extract','INT'),
('mesna','mesna','INT'),
('Mesophyllum lichenoides extract','mesophyllum lichenoides extract','INT'),
('mesoridazine','mesoridazine','INT'),
('mesquite pollen extract','mesquite pollen extract','INT'),
('mesterolone','mesterolone','INT'),
('mestranol','mestranol','INT'),
('mesulfen','mesulfen','INT'),
('mesylate','mesylate','INT'),
('mesyloxybenzyl methoxyethyl chlorobenzamide','mesyloxybenzyl methoxyethyl chlorobenzamide','INT'),
('metabisulfite ion','metabisulfite ion','INT'),
('metaclazepam','metaclazepam','INT'),
('metacresol','metacresol','INT'),
('metaflumizone','metaflumizone','INT'),
('metahomomenthol, (+/-)-','metahomomenthol, (+/-)-','INT'),
('metanil yellow','metanil yellow','INT'),
('metaproterenol','metaproterenol','INT'),
('metaraminol','metaraminol','INT'),
('metavanadate','metavanadate','INT'),
('metaxalone','metaxalone','INT'),
('metenkefalin','metenkefalin','INT'),
('metergoline','metergoline','INT'),
('metformin','metformin','INT'),
('methacholine','methacholine','INT'),
('methacrylate','methacrylate','INT'),
('methacrylic acid copolymer','methacrylic acid copolymer','INT'),
('methacycline','methacycline','INT'),
('methadone','methadone','INT'),
('methadyl acetate','methadyl acetate','INT'),
('methamphetamine','methamphetamine','INT'),
('methampicillin','methampicillin','INT'),
('methandriol','methandriol','INT')
) AS v(nom, dci, pays)
WHERE NOT EXISTS (SELECT 1 FROM medicaments m WHERE LOWER(m.nom) = LOWER(v.nom));
