-- rxnorm_batch_142.sql (80 rows)
INSERT INTO medicaments (nom, dci, pays)
SELECT v.nom, v.dci, v.pays FROM (VALUES
('salcaprozate','salcaprozate','INT'),
('salicin','salicin','INT'),
('salicin extract','salicin extract','INT'),
('Salicornia depressa whole extract','salicornia depressa whole extract','INT'),
('Salicornia europaea extract','salicornia europaea extract','INT'),
('salicyl alcohol','salicyl alcohol','INT'),
('salicylamide','salicylamide','INT'),
('salicylic acid','salicylic acid','INT'),
('salicyloyl phytosphingosine','salicyloyl phytosphingosine','INT'),
('salinomycin','salinomycin','INT'),
('Salix alba bark extract','salix alba bark extract','INT'),
('Salix alba bark volatile oil','salix alba bark volatile oil','INT'),
('Salix alba flower extract','salix alba flower extract','INT'),
('Salix alba flowering top extract','salix alba flowering top extract','INT'),
('Salix alba leaf extract','salix alba leaf extract','INT'),
('Salix alba whole extract','salix alba whole extract','INT'),
('Salix babylonica whole extract','salix babylonica whole extract','INT'),
('Salix lutea pollen extract','salix lutea pollen extract','INT'),
('Salix nigra bark extract','salix nigra bark extract','INT'),
('Salix purpurea bark extract','salix purpurea bark extract','INT'),
('Salix repens pollen extract','salix repens pollen extract','INT'),
('salmeterol','salmeterol','INT'),
('salmon allergenic extract','salmon allergenic extract','INT'),
('salmon calcitonin','salmon calcitonin','INT'),
('salmon oil','salmon oil','INT'),
('salmon preparation','salmon preparation','INT'),
('Salmonella enterica subsp. enterica serovar typhi','salmonella enterica subsp. enterica serovar typhi','INT'),
('Salmonella typhi Ty21a live antigen','salmonella typhi ty21a live antigen','INT'),
('salsalate','salsalate','INT'),
('Salsola kali whole extract','salsola kali whole extract','INT'),
('Salsola tragus pollen extract','salsola tragus pollen extract','INT'),
('salsolinol','salsolinol','INT'),
('salt cedar pollen','salt cedar pollen','INT'),
('salt cedar pollen extract','salt cedar pollen extract','INT'),
('salt grass pollen extract','salt grass pollen extract','INT'),
('saltbush pollen extract','saltbush pollen extract','INT'),
('Salvadora persica root extract','salvadora persica root extract','INT'),
('Salvia apiana leaf extract','salvia apiana leaf extract','INT'),
('Salvia hispanica seed extract','salvia hispanica seed extract','INT'),
('Salvia lavandulifolia leaf oil','salvia lavandulifolia leaf oil','INT'),
('Salvia microphylla whole extract','salvia microphylla whole extract','INT'),
('Salvia miltiorrhiza root extract','salvia miltiorrhiza root extract','INT'),
('Salvia officinalis flowering top extract','salvia officinalis flowering top extract','INT'),
('Salvia officinalis leaf extract','salvia officinalis leaf extract','INT'),
('Salvia officinalis root extract','salvia officinalis root extract','INT'),
('Salvia officinalis whole extract','salvia officinalis whole extract','INT'),
('Salvia pratenis leaf extract','salvia pratenis leaf extract','INT'),
('Salvia sclarea seed oil','salvia sclarea seed oil','INT'),
('Salvia sclarea whole extract','salvia sclarea whole extract','INT'),
('samarium','samarium','INT'),
('samarium Sm 153 lexidronam','samarium sm 153 lexidronam','INT'),
('Sambucus canadensis flower extract','sambucus canadensis flower extract','INT'),
('Sambucus nigra flower extract','sambucus nigra flower extract','INT'),
('Sambucus nigra flower oil','sambucus nigra flower oil','INT'),
('Sambucus nigra flowering top','sambucus nigra flowering top','INT'),
('Sambucus nigra seed oil','sambucus nigra seed oil','INT'),
('Sambucus nigra subsp. cerulea fruit extract','sambucus nigra subsp. cerulea fruit extract','INT'),
('Sambucus nigra whole extract','sambucus nigra whole extract','INT'),
('samidorphan','samidorphan','INT'),
('sandalore','sandalore','INT'),
('sandalwood extract','sandalwood extract','INT'),
('sandalwood oil','sandalwood oil','INT'),
('sandbur ragweed pollen extract','sandbur ragweed pollen extract','INT'),
('sangre de grado','sangre de grado','INT'),
('Sanguinaria canadensis extract','sanguinaria canadensis extract','INT'),
('Sanguinaria canadensis root extract','sanguinaria canadensis root extract','INT'),
('sanguinarine','sanguinarine','INT'),
('Sanguisorba minor root extract','sanguisorba minor root extract','INT'),
('Sanguisorba officinalis leaf extract','sanguisorba officinalis leaf extract','INT'),
('Sanguisorba officinalis root extract','sanguisorba officinalis root extract','INT'),
('Sanguisorba officinalis top extract','sanguisorba officinalis top extract','INT'),
('Sanguisorba officinalis whole extract','sanguisorba officinalis whole extract','INT'),
('Sanicula europaea extract','sanicula europaea extract','INT'),
('Sanicula europaea leaf extract','sanicula europaea leaf extract','INT'),
('Sanicula europaea top extract','sanicula europaea top extract','INT'),
('Sansevieria trifasciata leaf extract','sansevieria trifasciata leaf extract','INT'),
('Santalum album seed extract','santalum album seed extract','INT'),
('Santalum album seed oil','santalum album seed oil','INT'),
('Santalum paniculatum wood oil','santalum paniculatum wood oil','INT'),
('Santalum spicatum oil','santalum spicatum oil','INT')
) AS v(nom, dci, pays)
WHERE NOT EXISTS (SELECT 1 FROM medicaments m WHERE LOWER(m.nom) = LOWER(v.nom));
