-- rxnorm_batch_240.sql (80 rows)
INSERT INTO medicaments (nom, dci, pays)
SELECT v.nom, v.dci, v.pays FROM (VALUES
('pentetate calcium trisodium','pentetate calcium trisodium','INT'),
('pentetate zinc trisodium','pentetate zinc trisodium','INT'),
('pentetic acid','pentetic acid','INT'),
('pentobarbital sodium','pentobarbital sodium','INT'),
('pentosan polysulphate sodium','pentosan polysulphate sodium','INT'),
('peramivir anhydrous','peramivir anhydrous','INT'),
('perazine dimalonate','perazine dimalonate','INT'),
('pergolide mesylate','pergolide mesylate','INT'),
('perhexiline maleate','perhexiline maleate','INT'),
('perindopril arginine','perindopril arginine','INT'),
('perindopril erbumine','perindopril erbumine','INT'),
('perphenazine enanthate','perphenazine enanthate','INT'),
('pertuzumab-zzxf','pertuzumab-zzxf','INT'),
('pexidartinib hydrochloride','pexidartinib hydrochloride','INT'),
('phenazocine hydrobromide','phenazocine hydrobromide','INT'),
('phenazopyridine hydrochloride','phenazopyridine hydrochloride','INT'),
('phendimetrazine hydrochloride','phendimetrazine hydrochloride','INT'),
('phendimetrazine tartrate','phendimetrazine tartrate','INT'),
('phenelzine sulfate','phenelzine sulfate','INT'),
('phenethyl benzoate','phenethyl benzoate','INT'),
('phenethylamine hydrochloride','phenethylamine hydrochloride','INT'),
('phenformin hydrochloride','phenformin hydrochloride','INT'),
('phenindamine tartrate','phenindamine tartrate','INT'),
('pheniramine aminosalicylate','pheniramine aminosalicylate','INT'),
('pheniramine maleate','pheniramine maleate','INT'),
('phenmetrazine hydrochloride','phenmetrazine hydrochloride','INT'),
('phenmetrazine theoclate','phenmetrazine theoclate','INT'),
('phenobarbital sodium','phenobarbital sodium','INT'),
('phenolate sodium','phenolate sodium','INT'),
('phenolsulfonic acid','phenolsulfonic acid','INT'),
('phenoperidine hydrochloride','phenoperidine hydrochloride','INT'),
('phenoxyacetic acid','phenoxyacetic acid','INT'),
('phenoxybenzamine hydrochloride','phenoxybenzamine hydrochloride','INT'),
('phentermine hydrochloride','phentermine hydrochloride','INT'),
('phentermine resin','phentermine resin','INT'),
('phentolamine mesylate','phentolamine mesylate','INT'),
('phenylacetic acid','phenylacetic acid','INT'),
('phenylalanine,DL-','phenylalanine,dl-','INT'),
('phenylbutazone piperazine','phenylbutazone piperazine','INT'),
('phenylbutazone sodium','phenylbutazone sodium','INT'),
('phenylephrine bitartrate','phenylephrine bitartrate','INT'),
('phenylephrine hydrochloride','phenylephrine hydrochloride','INT'),
('phenylephrine hydrochloride, DL-','phenylephrine hydrochloride, dl-','INT'),
('phenylephrine tannate','phenylephrine tannate','INT'),
('phenylhydrazine hydrochloride','phenylhydrazine hydrochloride','INT'),
('phenylmercuric acetate','phenylmercuric acetate','INT'),
('phenylpropanolamine bitartrate','phenylpropanolamine bitartrate','INT'),
('phenylpropanolamine hydrochloride','phenylpropanolamine hydrochloride','INT'),
('phenyltoloxamine citrate','phenyltoloxamine citrate','INT'),
('phenyltoloxamine polistirex','phenyltoloxamine polistirex','INT'),
('phenyltoloxamine resin complex','phenyltoloxamine resin complex','INT'),
('phenytoin sodium','phenytoin sodium','INT'),
('pholedrine sulfate','pholedrine sulfate','INT'),
('phosphorus 32','phosphorus 32','INT'),
('physostigmine salicylate','physostigmine salicylate','INT'),
('physostigmine sulfate','physostigmine sulfate','INT'),
('phytosphingosine hydrochloride','phytosphingosine hydrochloride','INT'),
('picosulfate sodium','picosulfate sodium','INT'),
('picosulfuric acid','picosulfuric acid','INT'),
('picric acid','picric acid','INT'),
('piflufolastat F-18','piflufolastat f-18','INT'),
('pilocarpine hydrochloride','pilocarpine hydrochloride','INT'),
('pilocarpine nitrate','pilocarpine nitrate','INT'),
('pimagedine hydrochloride','pimagedine hydrochloride','INT'),
('pimavanserin tartrate','pimavanserin tartrate','INT'),
('pimeclone hydrochloride','pimeclone hydrochloride','INT'),
('pinaverium bromide','pinaverium bromide','INT'),
('pioglitazone hydrochloride','pioglitazone hydrochloride','INT'),
('pipamperone dihydrochloride','pipamperone dihydrochloride','INT'),
('pipazetate hydrochloride','pipazetate hydrochloride','INT'),
('pipecuronium bromide','pipecuronium bromide','INT'),
('pipemidic acid','pipemidic acid','INT'),
('pipenzolate bromide','pipenzolate bromide','INT'),
('piperacillin anhydrous','piperacillin anhydrous','INT'),
('piperacillin sodium','piperacillin sodium','INT'),
('piperazine adipate','piperazine adipate','INT'),
('piperazine citrate','piperazine citrate','INT'),
('piperazine dihydrochloride','piperazine dihydrochloride','INT'),
('piperazine hexahydrate','piperazine hexahydrate','INT'),
('piperazine hydrate','piperazine hydrate','INT')
) AS v(nom, dci, pays)
WHERE NOT EXISTS (SELECT 1 FROM medicaments m WHERE LOWER(m.nom) = LOWER(v.nom));
