-- rxnorm_batch_188.sql (80 rows)
INSERT INTO medicaments (nom, dci, pays)
SELECT v.nom, v.dci, v.pays FROM (VALUES
('chloramphenicol / naphazoline / neomycin','chloramphenicol / naphazoline / neomycin','INT'),
('chloramphenicol / neomycin','chloramphenicol / neomycin','INT'),
('chloramphenicol / oxyphenbutazone','chloramphenicol / oxyphenbutazone','INT'),
('chloramphenicol / prednisolone','chloramphenicol / prednisolone','INT'),
('chloramphenicol / prednisone','chloramphenicol / prednisone','INT'),
('chloramphenicol / resorcinol / salicylic acid','chloramphenicol / resorcinol / salicylic acid','INT'),
('chlorcyclizine / codeine','chlorcyclizine / codeine','INT'),
('chlorcyclizine / codeine / phenylephrine','chlorcyclizine / codeine / phenylephrine','INT'),
('chlorcyclizine / codeine / pseudoephedrine','chlorcyclizine / codeine / pseudoephedrine','INT'),
('chlorcyclizine / hydrocortisone','chlorcyclizine / hydrocortisone','INT'),
('chlorcyclizine / phenylephrine','chlorcyclizine / phenylephrine','INT'),
('chlorcyclizine / pseudoephedrine','chlorcyclizine / pseudoephedrine','INT'),
('chlordiazepoxide / clidinium','chlordiazepoxide / clidinium','INT'),
('chlordiazepoxide / desipramine','chlordiazepoxide / desipramine','INT'),
('chlordiazepoxide / estrogens, esterified (USP)','chlordiazepoxide / estrogens, esterified (usp)','INT'),
('chlordiazepoxide / methscopolamine','chlordiazepoxide / methscopolamine','INT'),
('chlordiazepoxide / pentaerythritol','chlordiazepoxide / pentaerythritol','INT'),
('chlorhexidine / chlorobutanol','chlorhexidine / chlorobutanol','INT'),
('chlorhexidine / climbazole','chlorhexidine / climbazole','INT'),
('chlorhexidine / coal tar','chlorhexidine / coal tar','INT'),
('chlorhexidine / dexpanthenol','chlorhexidine / dexpanthenol','INT'),
('chlorhexidine / ethanol','chlorhexidine / ethanol','INT'),
('chlorhexidine / felypressin','chlorhexidine / felypressin','INT'),
('chlorhexidine / glycerin','chlorhexidine / glycerin','INT'),
('chlorhexidine / hydrocortisone','chlorhexidine / hydrocortisone','INT'),
('chlorhexidine / hydrocortisone / ketoconazole','chlorhexidine / hydrocortisone / ketoconazole','INT'),
('chlorhexidine / isopropyl alcohol','chlorhexidine / isopropyl alcohol','INT'),
('chlorhexidine / ketoconazole','chlorhexidine / ketoconazole','INT'),
('chlorhexidine / lidocaine','chlorhexidine / lidocaine','INT'),
('chlorhexidine / lidocaine / pramoxine','chlorhexidine / lidocaine / pramoxine','INT'),
('chlorhexidine / metronidazole','chlorhexidine / metronidazole','INT'),
('chlorhexidine / miconazole','chlorhexidine / miconazole','INT'),
('chlorhexidine / muramidase / tetracaine','chlorhexidine / muramidase / tetracaine','INT'),
('chlorhexidine / neomycin','chlorhexidine / neomycin','INT'),
('chlorhexidine / phenol','chlorhexidine / phenol','INT'),
('chlorhexidine / phenylephrine','chlorhexidine / phenylephrine','INT'),
('chlorhexidine / salicylic acid','chlorhexidine / salicylic acid','INT'),
('chlorhexidine / salicyloyl phytosphingosine','chlorhexidine / salicyloyl phytosphingosine','INT'),
('chlorhexidine / silver sulfadiazine','chlorhexidine / silver sulfadiazine','INT'),
('chlorhexidine / simethicone','chlorhexidine / simethicone','INT'),
('chlorhexidine / sodium fluoride','chlorhexidine / sodium fluoride','INT'),
('chlorhexidine / sodium nitrite','chlorhexidine / sodium nitrite','INT'),
('chlorhexidine / tetracaine','chlorhexidine / tetracaine','INT'),
('chlorhexidine / tolnaftate','chlorhexidine / tolnaftate','INT'),
('chlormadinone / ethinyl estradiol','chlormadinone / ethinyl estradiol','INT'),
('chlormadinone / mestranol','chlormadinone / mestranol','INT'),
('chlormezanone / dipyrone','chlormezanone / dipyrone','INT'),
('chlorobutanol / dichlorobenzene / peanut oil','chlorobutanol / dichlorobenzene / peanut oil','INT'),
('chlorobutanol / posterior pituitary hormones','chlorobutanol / posterior pituitary hormones','INT'),
('chlorobutanol / pyrogallol','chlorobutanol / pyrogallol','INT'),
('chlorobutanol / tannic acid','chlorobutanol / tannic acid','INT'),
('chlorocresol / clorophene','chlorocresol / clorophene','INT'),
('chlorophyll / papain / urea','chlorophyll / papain / urea','INT'),
('chlorophyllin / soybean oil','chlorophyllin / soybean oil','INT'),
('chlorophyllin / thymol','chlorophyllin / thymol','INT'),
('chlorophyllin copper complex / papain / urea','chlorophyllin copper complex / papain / urea','INT'),
('chlorophyllin copper complex / sodium chloride','chlorophyllin copper complex / sodium chloride','INT'),
('chlorophyllin copper complex / sodium propionate','chlorophyllin copper complex / sodium propionate','INT'),
('chloroquine / primaquine','chloroquine / primaquine','INT'),
('chloroquine / proguanil','chloroquine / proguanil','INT'),
('chlorothen / methapyrilene / pyrilamine','chlorothen / methapyrilene / pyrilamine','INT'),
('chlorotheophylline / diphenhydramine','chlorotheophylline / diphenhydramine','INT'),
('chlorothiazide / methyldopa','chlorothiazide / methyldopa','INT'),
('chlorothiazide / reserpine','chlorothiazide / reserpine','INT'),
('chloroxylenol / coal tar','chloroxylenol / coal tar','INT'),
('chloroxylenol / copper sulfate','chloroxylenol / copper sulfate','INT'),
('chloroxylenol / ethanol','chloroxylenol / ethanol','INT'),
('chloroxylenol / hydrocortisone / pramoxine','chloroxylenol / hydrocortisone / pramoxine','INT'),
('chloroxylenol / iodine / menthol','chloroxylenol / iodine / menthol','INT'),
('chloroxylenol / isopropyl alcohol','chloroxylenol / isopropyl alcohol','INT'),
('chloroxylenol / ketoconazole','chloroxylenol / ketoconazole','INT'),
('chloroxylenol / lidocaine','chloroxylenol / lidocaine','INT'),
('chloroxylenol / menthol','chloroxylenol / menthol','INT'),
('chloroxylenol / miconazole / salicylic acid','chloroxylenol / miconazole / salicylic acid','INT'),
('chloroxylenol / petrolatum','chloroxylenol / petrolatum','INT'),
('chloroxylenol / pramoxine','chloroxylenol / pramoxine','INT'),
('chloroxylenol / pramoxine / zinc acetate','chloroxylenol / pramoxine / zinc acetate','INT'),
('chloroxylenol / resorcinol / sulfur','chloroxylenol / resorcinol / sulfur','INT'),
('chloroxylenol / salicylic acid','chloroxylenol / salicylic acid','INT'),
('chloroxylenol / salicylic acid / thiosulfate','chloroxylenol / salicylic acid / thiosulfate','INT')
) AS v(nom, dci, pays)
WHERE NOT EXISTS (SELECT 1 FROM medicaments m WHERE LOWER(m.nom) = LOWER(v.nom));
