-- rxnorm_batch_030.sql (80 rows)
INSERT INTO medicaments (nom, dci, pays)
SELECT v.nom, v.dci, v.pays FROM (VALUES
('butyl chloride','butyl chloride','INT'),
('butyl cyanoacetate','butyl cyanoacetate','INT'),
('butyl ether','butyl ether','INT'),
('butyl glycolate','butyl glycolate','INT'),
('butyl hexanoate','butyl hexanoate','INT'),
('butyl isovalerate','butyl isovalerate','INT'),
('butyl levulinate','butyl levulinate','INT'),
('butyl maleurate','butyl maleurate','INT'),
('butyl octyl phthalate','butyl octyl phthalate','INT'),
('butyl oxoacetate','butyl oxoacetate','INT'),
('butyl salicylate','butyl salicylate','INT'),
('butyl stearate','butyl stearate','INT'),
('butylated hydroxyanisole','butylated hydroxyanisole','INT'),
('butylated hydroxytoluene','butylated hydroxytoluene','INT'),
('butylbenzene','butylbenzene','INT'),
('butylene glycol 1-caprate 3-caprylate','butylene glycol 1-caprate 3-caprylate','INT'),
('butylene glycol 2-laurate','butylene glycol 2-laurate','INT'),
('butylene glycol behenate','butylene glycol behenate','INT'),
('butylene glycol dicaprate','butylene glycol dicaprate','INT'),
('butylene glycol dicaprylate','butylene glycol dicaprylate','INT'),
('butylene glycol dicaprylate-dicaprate','butylene glycol dicaprylate-dicaprate','INT'),
('butylene glycol monolaurate','butylene glycol monolaurate','INT'),
('butyloctanol','butyloctanol','INT'),
('butyloctyl benzoate','butyloctyl benzoate','INT'),
('butyloctyl oleate','butyloctyl oleate','INT'),
('butyloctyl palmitate','butyloctyl palmitate','INT'),
('butyloctyl salicylate','butyloctyl salicylate','INT'),
('butylparaben','butylparaben','INT'),
('butylphenyl methylpropional','butylphenyl methylpropional','INT'),
('butylscopolamine','butylscopolamine','INT'),
('butylvinal','butylvinal','INT'),
('butyrate','butyrate','INT'),
('butyrospermol','butyrospermol','INT'),
('Buxus sempervirens leafy twig extract','buxus sempervirens leafy twig extract','INT'),
('buzepide metiodide','buzepide metiodide','INT'),
('C.I. acid blue 324','c.i. acid blue 324','INT'),
('C.I. direct red 28 parent','c.i. direct red 28 parent','INT'),
('C.I. food yellow 3 (free acid)','c.i. food yellow 3 (free acid)','INT'),
('C1 esterase inhibitor','c1 esterase inhibitor','INT'),
('C10-16 pareth-1','c10-16 pareth-1','INT'),
('C10-18 triglycerides','c10-18 triglycerides','INT'),
('C10-30 cholesterol-lanosterol esters','c10-30 cholesterol-lanosterol esters','INT'),
('C10-36 olefin','c10-36 olefin','INT'),
('C11-12 isoparaffin','c11-12 isoparaffin','INT'),
('C11-13 pareth-6','c11-13 pareth-6','INT'),
('C11-15 pareth-12','c11-15 pareth-12','INT'),
('C11-15 pareth-20','c11-15 pareth-20','INT'),
('C11-15 pareth-40','c11-15 pareth-40','INT'),
('C11-15 pareth-5','c11-15 pareth-5','INT'),
('C11-15 pareth-7','c11-15 pareth-7','INT'),
('C12 olefin sulfonate','c12 olefin sulfonate','INT'),
('C12-13 alcohols','c12-13 alcohols','INT'),
('C12-13 alkyl lactate','c12-13 alkyl lactate','INT'),
('C12-13 pareth-23','c12-13 pareth-23','INT'),
('C12-13 pareth-3','c12-13 pareth-3','INT'),
('C12-13 pareth-9','c12-13 pareth-9','INT'),
('C12-14 isoparaffin','c12-14 isoparaffin','INT'),
('C12-14 olefin sulfonate','c12-14 olefin sulfonate','INT'),
('C12-14 pareth-12','c12-14 pareth-12','INT'),
('C12-14 pareth-3','c12-14 pareth-3','INT'),
('C12-14 pareth-7','c12-14 pareth-7','INT'),
('C12-14 pareth-9','c12-14 pareth-9','INT'),
('C12-14 sec-pareth-12 sulfosuccinate','c12-14 sec-pareth-12 sulfosuccinate','INT'),
('C12-15 alcohols','c12-15 alcohols','INT'),
('C12-15 alkyl ethylhexanoate','c12-15 alkyl ethylhexanoate','INT'),
('C12-15 alkyl lactate','c12-15 alkyl lactate','INT'),
('C12-15 pareth-10','c12-15 pareth-10','INT'),
('C12-15 pareth-12','c12-15 pareth-12','INT'),
('C12-15 pareth-15 sulfonate','c12-15 pareth-15 sulfonate','INT'),
('C12-15 pareth-3','c12-15 pareth-3','INT'),
('C12-15 pareth-3 sulfate','c12-15 pareth-3 sulfate','INT'),
('C12-15 pareth-7','c12-15 pareth-7','INT'),
('C12-15 pareth-9','c12-15 pareth-9','INT'),
('C12-16 alcohols','c12-16 alcohols','INT'),
('C12-16 pareth-5','c12-16 pareth-5','INT'),
('C12-16 pareth-7','c12-16 pareth-7','INT'),
('C12-16 pareth-9','c12-16 pareth-9','INT'),
('C12-17 alkane','c12-17 alkane','INT'),
('C12-19 alkane','c12-19 alkane','INT'),
('C12-20 acid PEG-8 ester','c12-20 acid peg-8 ester','INT')
) AS v(nom, dci, pays)
WHERE NOT EXISTS (SELECT 1 FROM medicaments m WHERE LOWER(m.nom) = LOWER(v.nom));
