-- rxnorm_batch_146.sql (80 rows)
INSERT INTO medicaments (nom, dci, pays)
SELECT v.nom, v.dci, v.pays FROM (VALUES
('silanol','silanol','INT'),
('sildenafil','sildenafil','INT'),
('Silene laciniata whole extract','silene laciniata whole extract','INT'),
('silica dimethyl silylate','silica dimethyl silylate','INT'),
('silica, trimethylsilyl capped','silica, trimethylsilyl capped','INT'),
('silicon','silicon','INT'),
('silicon dioxide','silicon dioxide','INT'),
('silicon dioxide, colloidal','silicon dioxide, colloidal','INT'),
('silicon disulfide','silicon disulfide','INT'),
('silicones','silicones','INT'),
('silk allergenic extract','silk allergenic extract','INT'),
('silk amino acids','silk amino acids','INT'),
('silk sericin','silk sericin','INT'),
('silodosin','silodosin','INT'),
('silodrate','silodrate','INT'),
('siltuximab','siltuximab','INT'),
('silver','silver','INT'),
('silver acetate','silver acetate','INT'),
('silver birch pollen allergenic extract','silver birch pollen allergenic extract','INT'),
('silver carbonate','silver carbonate','INT'),
('silver cation','silver cation','INT'),
('silver chloride','silver chloride','INT'),
('silver citrate','silver citrate','INT'),
('silver cyanide','silver cyanide','INT'),
('silver fluoride','silver fluoride','INT'),
('silver iodide','silver iodide','INT'),
('silver maple pollen extract','silver maple pollen extract','INT'),
('silver nitrate','silver nitrate','INT'),
('silver nitrite','silver nitrite','INT'),
('silver phosphate','silver phosphate','INT'),
('silver ragweed pollen extract','silver ragweed pollen extract','INT'),
('silver stearate','silver stearate','INT'),
('silver sulfadiazine','silver sulfadiazine','INT'),
('silver sulfate','silver sulfate','INT'),
('silver sulfide','silver sulfide','INT'),
('silybin','silybin','INT'),
('silybum marianum seed oil','silybum marianum seed oil','INT'),
('Silybum marianum whole extract','silybum marianum whole extract','INT'),
('silymarin','silymarin','INT'),
('simaba cedron seed extract','simaba cedron seed extract','INT'),
('Simaba cedron whole extract','simaba cedron whole extract','INT'),
('simaldrate','simaldrate','INT'),
('simeprevir','simeprevir','INT'),
('simethicone','simethicone','INT'),
('simetone','simetone','INT'),
('Simmondsia chinensis leaf extract','simmondsia chinensis leaf extract','INT'),
('Simmondsia chinensis seed wax extract','simmondsia chinensis seed wax extract','INT'),
('Simmondsia chinensis whole extract','simmondsia chinensis whole extract','INT'),
('Simmondsia chinesis seed extract','simmondsia chinesis seed extract','INT'),
('simvastatin','simvastatin','INT'),
('Sinapis alba whole extract','sinapis alba whole extract','INT'),
('Sinapis arvensis whole extract','sinapis arvensis whole extract','INT'),
('Sinapsis arvensis flowering-fruiting top extract','sinapsis arvensis flowering-fruiting top extract','INT'),
('sinapultide','sinapultide','INT'),
('sincalide','sincalide','INT'),
('sinecatechins','sinecatechins','INT'),
('Sinomenium acutum stem extract','sinomenium acutum stem extract','INT'),
('sinusitisinum','sinusitisinum','INT'),
('siponimod','siponimod','INT'),
('sipuleucel-T','sipuleucel-t','INT'),
('Siraitia grosvenorii fruit extract','siraitia grosvenorii fruit extract','INT'),
('Siraitia grosvenorii whole extract','siraitia grosvenorii whole extract','INT'),
('sirolimus','sirolimus','INT'),
('sisal fiber allergenic extract','sisal fiber allergenic extract','INT'),
('sisomicin','sisomicin','INT'),
('Sisymbrium officianale whole extract','sisymbrium officianale whole extract','INT'),
('sitagliptin','sitagliptin','INT'),
('sitocalciferol','sitocalciferol','INT'),
('sitosterols','sitosterols','INT'),
('skatole','skatole','INT'),
('skim milk','skim milk','INT'),
('skullcap preparation','skullcap preparation','INT'),
('slash pine pollen extract','slash pine pollen extract','INT'),
('slender ragweed pollen extract','slender ragweed pollen extract','INT'),
('slippery elm bark','slippery elm bark','INT'),
('Smallanthus sonchifolius leaf extract','smallanthus sonchifolius leaf extract','INT'),
('Smallanthus sonchifolius root juice','smallanthus sonchifolius root juice','INT'),
('Smallanthus sonchifolius whole extract','smallanthus sonchifolius whole extract','INT'),
('smelt allergenic extract','smelt allergenic extract','INT'),
('Smilax aristolochiaefolia root extract','smilax aristolochiaefolia root extract','INT')
) AS v(nom, dci, pays)
WHERE NOT EXISTS (SELECT 1 FROM medicaments m WHERE LOWER(m.nom) = LOWER(v.nom));
