-- rxnorm_batch_136.sql (80 rows)
INSERT INTO medicaments (nom, dci, pays)
SELECT v.nom, v.dci, v.pays FROM (VALUES
('quarternium-15','quarternium-15','INT'),
('Quassia amara whole extract','quassia amara whole extract','INT'),
('Quassia amara wood extract','quassia amara wood extract','INT'),
('quaternium-14','quaternium-14','INT'),
('quaternium-15','quaternium-15','INT'),
('quaternium-15 cis-form','quaternium-15 cis-form','INT'),
('quaternium-15 trans-form','quaternium-15 trans-form','INT'),
('quaternium-16','quaternium-16','INT'),
('quaternium-18','quaternium-18','INT'),
('quaternium-18 hectorite','quaternium-18 hectorite','INT'),
('quaternium-22','quaternium-22','INT'),
('quaternium-24','quaternium-24','INT'),
('quaternium-27','quaternium-27','INT'),
('quaternium-33','quaternium-33','INT'),
('quaternium-52','quaternium-52','INT'),
('quaternium-53','quaternium-53','INT'),
('quaternium-73','quaternium-73','INT'),
('quaternium-82','quaternium-82','INT'),
('quaternium-90','quaternium-90','INT'),
('quaternium-90 bentonite','quaternium-90 bentonite','INT'),
('quaternium-90 montmorillonite','quaternium-90 montmorillonite','INT'),
('quaternium-90 sepiolite','quaternium-90 sepiolite','INT'),
('quaternium-91','quaternium-91','INT'),
('quazepam','quazepam','INT'),
('quebracho bark extract','quebracho bark extract','INT'),
('queen palm pollen extract','queen palm pollen extract','INT'),
('quercetin','quercetin','INT'),
('quercetin caprylate','quercetin caprylate','INT'),
('Quercus agrifolia whole extract','quercus agrifolia whole extract','INT'),
('Quercus alba extract','quercus alba extract','INT'),
('Quercus garryana whole extract','quercus garryana whole extract','INT'),
('Quercus kelloggii whole extract','quercus kelloggii whole extract','INT'),
('Quercus marilandica pollen extract','quercus marilandica pollen extract','INT'),
('Quercus petraea whole extract','quercus petraea whole extract','INT'),
('Quercus robur flower bud extract','quercus robur flower bud extract','INT'),
('Quercus robur flower extract','quercus robur flower extract','INT'),
('Quercus robur nut extract','quercus robur nut extract','INT'),
('Quercus robur twig bark extract','quercus robur twig bark extract','INT'),
('Quercus robur whole extract','quercus robur whole extract','INT'),
('Quercus robur wood extract','quercus robur wood extract','INT'),
('Quercus rubra bark extract','quercus rubra bark extract','INT'),
('Quercus rubra whole extract','quercus rubra whole extract','INT'),
('Quercus spp. whole extract','quercus spp. whole extract','INT'),
('Quercus suber bark extract','quercus suber bark extract','INT'),
('Quercus velutina whole extract','quercus velutina whole extract','INT'),
('quetiapine','quetiapine','INT'),
('Quillaja saponaria bark extract','quillaja saponaria bark extract','INT'),
('Quillaja saponaria whole extract','quillaja saponaria whole extract','INT'),
('Quillaja saponaria wood extract','quillaja saponaria wood extract','INT'),
('quinacrine','quinacrine','INT'),
('quinagolide','quinagolide','INT'),
('quinapril','quinapril','INT'),
('quinaprilat','quinaprilat','INT'),
('quinate','quinate','INT'),
('quince extract','quince extract','INT'),
('quinestradol','quinestradol','INT'),
('quinestrol','quinestrol','INT'),
('quinethazone','quinethazone','INT'),
('quinfamide','quinfamide','INT'),
('quinhydrone','quinhydrone','INT'),
('quinidine','quinidine','INT'),
('quinine','quinine','INT'),
('quinine arsenate','quinine arsenate','INT'),
('quinine arsenite','quinine arsenite','INT'),
('quinoa oil','quinoa oil','INT'),
('quinoline yellow','quinoline yellow','INT'),
('quinupramine','quinupramine','INT'),
('quinupristin','quinupristin','INT'),
('quizartinib','quizartinib','INT'),
('rabacfosadine','rabacfosadine','INT'),
('rabbit allergenic extract','rabbit allergenic extract','INT'),
('rabbit bush pollen extract','rabbit bush pollen extract','INT'),
('rabbit skin extract','rabbit skin extract','INT'),
('rabeprazole','rabeprazole','INT'),
('rabies immune globulin, human','rabies immune globulin, human','INT'),
('rabies virus','rabies virus','INT'),
('rabies virus vaccine flury-lep strain','rabies virus vaccine flury-lep strain','INT'),
('racecadotril','racecadotril','INT'),
('racementhol','racementhol','INT'),
('racemethionine','racemethionine','INT')
) AS v(nom, dci, pays)
WHERE NOT EXISTS (SELECT 1 FROM medicaments m WHERE LOWER(m.nom) = LOWER(v.nom));
