-- rxnorm_batch_133.sql (80 rows)
INSERT INTO medicaments (nom, dci, pays)
SELECT v.nom, v.dci, v.pays FROM (VALUES
('propionaldehyde','propionaldehyde','INT'),
('propionamide','propionamide','INT'),
('propionate','propionate','INT'),
('Propionibacterium acnes','propionibacterium acnes','INT'),
('Propionibacterium avidum','propionibacterium avidum','INT'),
('propionic acid','propionic acid','INT'),
('propiverine','propiverine','INT'),
('propofol','propofol','INT'),
('propolis','propolis','INT'),
('propolis wax','propolis wax','INT'),
('propoxyphene','propoxyphene','INT'),
('propranolol','propranolol','INT'),
('propranolol glycol','propranolol glycol','INT'),
('propyl acetate','propyl acetate','INT'),
('propyl gallate','propyl gallate','INT'),
('propylene','propylene','INT'),
('propylene carbonate','propylene carbonate','INT'),
('propylene glycol','propylene glycol','INT'),
('propylene glycol 1,2-distearate','propylene glycol 1,2-distearate','INT'),
('propylene glycol 1-allyl ether','propylene glycol 1-allyl ether','INT'),
('propylene glycol 1-behenate','propylene glycol 1-behenate','INT'),
('propylene glycol 1-butyrate','propylene glycol 1-butyrate','INT'),
('propylene glycol 1-caprylate','propylene glycol 1-caprylate','INT'),
('propylene glycol 1-myristate','propylene glycol 1-myristate','INT'),
('propylene glycol 1-oleate','propylene glycol 1-oleate','INT'),
('propylene glycol 1-palmitate','propylene glycol 1-palmitate','INT'),
('propylene glycol 1-stearate','propylene glycol 1-stearate','INT'),
('propylene glycol 2-behenate','propylene glycol 2-behenate','INT'),
('propylene glycol 2-myristate','propylene glycol 2-myristate','INT'),
('propylene glycol 2-oleate','propylene glycol 2-oleate','INT'),
('propylene glycol 2-stearate','propylene glycol 2-stearate','INT'),
('propylene glycol alginate','propylene glycol alginate','INT'),
('propylene glycol behenate','propylene glycol behenate','INT'),
('propylene glycol butyl ether','propylene glycol butyl ether','INT'),
('propylene glycol caprylate','propylene glycol caprylate','INT'),
('propylene glycol diacetate','propylene glycol diacetate','INT'),
('propylene glycol dibenzoate','propylene glycol dibenzoate','INT'),
('propylene glycol dibutyrate','propylene glycol dibutyrate','INT'),
('propylene glycol dicaprate','propylene glycol dicaprate','INT'),
('propylene glycol dicaprylate','propylene glycol dicaprylate','INT'),
('propylene glycol dicaprylate-dicaprate','propylene glycol dicaprylate-dicaprate','INT'),
('propylene glycol diethylhexanoate','propylene glycol diethylhexanoate','INT'),
('propylene glycol dilaurate','propylene glycol dilaurate','INT'),
('propylene glycol dinitrate','propylene glycol dinitrate','INT'),
('propylene glycol dioleate','propylene glycol dioleate','INT'),
('propylene glycol dipropionate','propylene glycol dipropionate','INT'),
('propylene glycol ethyl ether','propylene glycol ethyl ether','INT'),
('propylene glycol heptanoate','propylene glycol heptanoate','INT'),
('propylene glycol hydroxystearate','propylene glycol hydroxystearate','INT'),
('propylene glycol methyl ether','propylene glycol methyl ether','INT'),
('propylene glycol monocaprate','propylene glycol monocaprate','INT'),
('propylene glycol monolaurate','propylene glycol monolaurate','INT'),
('propylene glycol monopalmitostearate','propylene glycol monopalmitostearate','INT'),
('propylene glycol monostearate','propylene glycol monostearate','INT'),
('propylene glycol myristyl ether acetate','propylene glycol myristyl ether acetate','INT'),
('propylene glycol ricinoleate','propylene glycol ricinoleate','INT'),
('propylene glycol salicylate','propylene glycol salicylate','INT'),
('propylene glycol t-butyl ether','propylene glycol t-butyl ether','INT'),
('propylene glycol, (R)-','propylene glycol, (r)-','INT'),
('propylene oxide','propylene oxide','INT'),
('propylheptyl caprylate','propylheptyl caprylate','INT'),
('propylhexedrine','propylhexedrine','INT'),
('propyliodone','propyliodone','INT'),
('propylparaben','propylparaben','INT'),
('propylthiouracil','propylthiouracil','INT'),
('propyperone','propyperone','INT'),
('propyphenazone','propyphenazone','INT'),
('proquazone','proquazone','INT'),
('proscillaridin','proscillaridin','INT'),
('prosolv SMCC 50','prosolv smcc 50','INT'),
('Prosopis cineraria wood extract','prosopis cineraria wood extract','INT'),
('protamine sulfate (USP)','protamine sulfate (usp)','INT'),
('protamines','protamines','INT'),
('protamone','protamone','INT'),
('protease','protease','INT'),
('protein C','protein c','INT'),
('protein S','protein s','INT'),
('proteoglycan 4','proteoglycan 4','INT'),
('Proteus inconstans','proteus inconstans','INT'),
('Proteus mirabilis','proteus mirabilis','INT')
) AS v(nom, dci, pays)
WHERE NOT EXISTS (SELECT 1 FROM medicaments m WHERE LOWER(m.nom) = LOWER(v.nom));
