-- rxnorm_batch_002.sql (80 rows)
INSERT INTO medicaments (nom, dci, pays)
SELECT v.nom, v.dci, v.pays FROM (VALUES
('1-aminobutan-2-ol','1-aminobutan-2-ol','INT'),
('1-aminocyclopropanol','1-aminocyclopropanol','INT'),
('1-butanol, 4-(ethenyloxy)-','1-butanol, 4-(ethenyloxy)-','INT'),
('1-butene','1-butene','INT'),
('1-butyl oleate','1-butyl oleate','INT'),
('1-chloro-2-methyl-1-propene','1-chloro-2-methyl-1-propene','INT'),
('1-chloronaphthalene','1-chloronaphthalene','INT'),
('1-decene','1-decene','INT'),
('1-dodecylperhydroazepine-1-oxide','1-dodecylperhydroazepine-1-oxide','INT'),
('1-eicosene','1-eicosene','INT'),
('1-ethoxyundecane','1-ethoxyundecane','INT'),
('1-ethyl citrate','1-ethyl citrate','INT'),
('1-ethyl-2-pyrrolecarboxaldehyde','1-ethyl-2-pyrrolecarboxaldehyde','INT'),
('1-glyceryl monooleate','1-glyceryl monooleate','INT'),
('1-hexadecene','1-hexadecene','INT'),
('1-kestose','1-kestose','INT'),
('1-methyl-2-pyrrolidinone','1-methyl-2-pyrrolidinone','INT'),
('1-methylcyclohexa-1,3-diene','1-methylcyclohexa-1,3-diene','INT'),
('1-methylhydantoin','1-methylhydantoin','INT'),
('1-myristylpicolinium','1-myristylpicolinium','INT'),
('1-naphthalenesulfonic acid','1-naphthalenesulfonic acid','INT'),
('1-naphthol','1-naphthol','INT'),
('1-O-tetradecylglycerol','1-o-tetradecylglycerol','INT'),
('1-octacosanol','1-octacosanol','INT'),
('1-octanesulfonic acid','1-octanesulfonic acid','INT'),
('1-octanol','1-octanol','INT'),
('1-octen-3-ol','1-octen-3-ol','INT'),
('1-octen-3-yl acetate','1-octen-3-yl acetate','INT'),
('1-octenylsuccinic acid','1-octenylsuccinic acid','INT'),
('1-p-menthene-8-thiol','1-p-menthene-8-thiol','INT'),
('1-phenylazo-2-naphthylamine','1-phenylazo-2-naphthylamine','INT'),
('1-phenylethanol','1-phenylethanol','INT'),
('1-propanol','1-propanol','INT'),
('1-propoxy-2-propanol','1-propoxy-2-propanol','INT'),
('1-stearoyl-sn-glycero-3-phosphocholine','1-stearoyl-sn-glycero-3-phosphocholine','INT'),
('1-tetracosanol','1-tetracosanol','INT'),
('1-vinyl-2-pyrrolidone','1-vinyl-2-pyrrolidone','INT'),
('1.alpha.,24S-dihydroxyvitamin D2','1.alpha.,24s-dihydroxyvitamin d2','INT'),
('10-hydroxydecanoate','10-hydroxydecanoate','INT'),
('10-hydroxystearic acid','10-hydroxystearic acid','INT'),
('10-undecenal','10-undecenal','INT'),
('12-hydroxystearate','12-hydroxystearate','INT'),
('12-oxooctadecanoic acid','12-oxooctadecanoic acid','INT'),
('16-methylheptadecanoic acid','16-methylheptadecanoic acid','INT'),
('17-alpha-hydroxyprogesterone','17-alpha-hydroxyprogesterone','INT'),
('17-hydroxystearic acid','17-hydroxystearic acid','INT'),
('2'',3''-dihydroxyacetophenone','2'',3''-dihydroxyacetophenone','INT'),
('2''-deoxyadenosine','2''-deoxyadenosine','INT'),
('2''-deoxyguanosine','2''-deoxyguanosine','INT'),
('2''-fucosyllactose','2''-fucosyllactose','INT'),
('2''-hydroxyacetophenone','2''-hydroxyacetophenone','INT'),
('2,10,15,19,23-pentahydrosqualene','2,10,15,19,23-pentahydrosqualene','INT'),
('2,2'',3,3'',4,4'',5,5'',6-nonachlorodiphenyl either','2,2'',3,3'',4,4'',5,5'',6-nonachlorodiphenyl either','INT'),
('2,2''-dithiobisbenzothiazole','2,2''-dithiobisbenzothiazole','INT'),
('2,2''-oxydipropanol','2,2''-oxydipropanol','INT'),
('2,2,2-trifluoroacetophenone','2,2,2-trifluoroacetophenone','INT'),
('2,2,5-trimethylhexane','2,2,5-trimethylhexane','INT'),
('2,2-dinitropropyl acrylate','2,2-dinitropropyl acrylate','INT'),
('2,3 di-o-methyl-d-glucose','2,3 di-o-methyl-d-glucose','INT'),
('2,3''-iminodi-benzoic acid','2,3''-iminodi-benzoic acid','INT'),
('2,3,5,6-tetrafluorophenol','2,3,5,6-tetrafluorophenol','INT'),
('2,3-dichloro-5,6-dicyanobenzoquinone','2,3-dichloro-5,6-dicyanobenzoquinone','INT'),
('2,3-dichlorobenzoic acid','2,3-dichlorobenzoic acid','INT'),
('2,3-dihydroxyacetophenone','2,3-dihydroxyacetophenone','INT'),
('2,3-dihydroxybenzoic acid','2,3-dihydroxybenzoic acid','INT'),
('2,3-dimercapto-1-propanesulfonic acid','2,3-dimercapto-1-propanesulfonic acid','INT'),
('2,3-dimethylacrylic acid, (E)-','2,3-dimethylacrylic acid, (e)-','INT'),
('2,3-pentanedione','2,3-pentanedione','INT'),
('2,4,5-T dimethylammonium','2,4,5-t dimethylammonium','INT'),
('2,4,5-T triethylammonium','2,4,5-t triethylammonium','INT'),
('2,4,5-T-isopropyl','2,4,5-t-isopropyl','INT'),
('2,4,5-T-trolamine','2,4,5-t-trolamine','INT'),
('2,4-D diethylethanolamine','2,4-d diethylethanolamine','INT'),
('2,4-D morpholine','2,4-d morpholine','INT'),
('2,4-D-trolamine','2,4-d-trolamine','INT'),
('2,4-diaminophenoxyethanol','2,4-diaminophenoxyethanol','INT'),
('2,4-dichlorophenoxyacetate','2,4-dichlorophenoxyacetate','INT'),
('2,4-dimethylnonan-4-ol','2,4-dimethylnonan-4-ol','INT'),
('2,5-di-tert-pentylhydroquinone','2,5-di-tert-pentylhydroquinone','INT'),
('2,5-diaminotoluene','2,5-diaminotoluene','INT')
) AS v(nom, dci, pays)
WHERE NOT EXISTS (SELECT 1 FROM medicaments m WHERE LOWER(m.nom) = LOWER(v.nom));
