-- rxnorm_batch_028.sql (80 rows)
INSERT INTO medicaments (nom, dci, pays)
SELECT v.nom, v.dci, v.pays FROM (VALUES
('Brassica napus whole extract','brassica napus whole extract','INT'),
('Brassica oleracea var. botrytis whole extract','brassica oleracea var. botrytis whole extract','INT'),
('Brassica oleracea var. gemmifera whole extract','brassica oleracea var. gemmifera whole extract','INT'),
('Brassica oleracea var. italica whole extract','brassica oleracea var. italica whole extract','INT'),
('Brassica oleracea whole extract','brassica oleracea whole extract','INT'),
('Brassica rapa subsp. oleifera whole extract','brassica rapa subsp. oleifera whole extract','INT'),
('Brassica rapa subsp. rapa seed extract','brassica rapa subsp. rapa seed extract','INT'),
('Brassica rapa var. rapa extract','brassica rapa var. rapa extract','INT'),
('Brassica rapa var. rapa oil','brassica rapa var. rapa oil','INT'),
('brazil nut allergenic extract','brazil nut allergenic extract','INT'),
('Brazil nut oil','brazil nut oil','INT'),
('brazil nut whole allergenic extract','brazil nut whole allergenic extract','INT'),
('Brazilian pepper tree pollen extract','brazilian pepper tree pollen extract','INT'),
('Brazillian pepper extract','brazillian pepper extract','INT'),
('Breea segeta whole extract','breea segeta whole extract','INT'),
('bremelanotide','bremelanotide','INT'),
('brensocatib','brensocatib','INT'),
('brentuximab vedotin','brentuximab vedotin','INT'),
('bretylium','bretylium','INT'),
('Brevibacterium stationis','brevibacterium stationis','INT'),
('brexanolone','brexanolone','INT'),
('brexpiprazole','brexpiprazole','INT'),
('brexucabtagene autoleucel','brexucabtagene autoleucel','INT'),
('brigatinib','brigatinib','INT'),
('brillant blue','brillant blue','INT'),
('brilliant blue FCF','brilliant blue fcf','INT'),
('brilliant blue G','brilliant blue g','INT'),
('brilliant green','brilliant green','INT'),
('brimonidine','brimonidine','INT'),
('brincidofovir','brincidofovir','INT'),
('brine shrimp extract','brine shrimp extract','INT'),
('brinzolamide','brinzolamide','INT'),
('brivaracetam','brivaracetam','INT'),
('brivudine','brivudine','INT'),
('Briza maxima whole extract','briza maxima whole extract','INT'),
('broad leaved paperbark pollen extract','broad leaved paperbark pollen extract','INT'),
('broadleaf cattail pollen extract','broadleaf cattail pollen extract','INT'),
('broadleaf plantain pollen extract','broadleaf plantain pollen extract','INT'),
('broccoli allergenic extract','broccoli allergenic extract','INT'),
('broccoli extract','broccoli extract','INT'),
('broccoli preparation','broccoli preparation','INT'),
('broccoli seed oil','broccoli seed oil','INT'),
('broccoli sprout extract','broccoli sprout extract','INT'),
('brodalumab','brodalumab','INT'),
('brodimoprim','brodimoprim','INT'),
('brolucizumab','brolucizumab','INT'),
('bromazepam','bromazepam','INT'),
('bromelains','bromelains','INT'),
('bromfenac','bromfenac','INT'),
('bromhexine','bromhexine','INT'),
('bromide ion','bromide ion','INT'),
('bromine','bromine','INT'),
('bromocriptine','bromocriptine','INT'),
('bromodiphenhydramine','bromodiphenhydramine','INT'),
('bromopride','bromopride','INT'),
('bromotheophylline','bromotheophylline','INT'),
('bromperidol','bromperidol','INT'),
('brompheniramine','brompheniramine','INT'),
('Bromus ramosus flower extract','bromus ramosus flower extract','INT'),
('Bromus ramosus whole extract','bromus ramosus whole extract','INT'),
('Bromus secalinus top extract','bromus secalinus top extract','INT'),
('bronopol','bronopol','INT'),
('broomweed pollen extract','broomweed pollen extract','INT'),
('Brosimum acutifolium bark extract','brosimum acutifolium bark extract','INT'),
('brotizolam','brotizolam','INT'),
('Broussonetia kazinoki root extract','broussonetia kazinoki root extract','INT'),
('Broussonetia kazinoki whole extract','broussonetia kazinoki whole extract','INT'),
('Broussonetia papyrifera whole extract','broussonetia papyrifera whole extract','INT'),
('brovanexine','brovanexine','INT'),
('brown iron oxide','brown iron oxide','INT'),
('brown mixture','brown mixture','INT'),
('brown rice allergenic extract','brown rice allergenic extract','INT'),
('brown rice preparation','brown rice preparation','INT'),
('Brucea javanica fruit extract','brucea javanica fruit extract','INT'),
('Brucea javanica whole extract','brucea javanica whole extract','INT'),
('bruceantin','bruceantin','INT'),
('Brucella abortus','brucella abortus','INT'),
('Brucella melitensis','brucella melitensis','INT'),
('brucine','brucine','INT'),
('Brugia malayi preparation','brugia malayi preparation','INT')
) AS v(nom, dci, pays)
WHERE NOT EXISTS (SELECT 1 FROM medicaments m WHERE LOWER(m.nom) = LOWER(v.nom));
