-- rxnorm_batch_033.sql (80 rows)
INSERT INTO medicaments (nom, dci, pays)
SELECT v.nom, v.dci, v.pays FROM (VALUES
('Calophyllum membranaceum root extract','calophyllum membranaceum root extract','INT'),
('Calophyllum membranaceum whole extract','calophyllum membranaceum whole extract','INT'),
('Calophyllum tacamahaca seed oil','calophyllum tacamahaca seed oil','INT'),
('Calophyllum tacamahaca whole extract','calophyllum tacamahaca whole extract','INT'),
('Calotropis procera whole extract','calotropis procera whole extract','INT'),
('calteridol','calteridol','INT'),
('Caltha palustris extract','caltha palustris extract','INT'),
('Calvatia gigantea extract','calvatia gigantea extract','INT'),
('cambendazole','cambendazole','INT'),
('Camelina sativa seed oil','camelina sativa seed oil','INT'),
('Camelina sativa whole extract','camelina sativa whole extract','INT'),
('Camellia chekiangoleosa seed oil','camellia chekiangoleosa seed oil','INT'),
('Camellia japonica flower extract','camellia japonica flower extract','INT'),
('Camellia japonica flower oil','camellia japonica flower oil','INT'),
('Camellia japonica leaf extract','camellia japonica leaf extract','INT'),
('Camellia japonica seed extract','camellia japonica seed extract','INT'),
('Camellia japonica seed oil','camellia japonica seed oil','INT'),
('Camellia kissii seed oil','camellia kissii seed oil','INT'),
('Camellia oil','camellia oil','INT'),
('Camellia oleifera leaf extract','camellia oleifera leaf extract','INT'),
('Camellia oleifera seed extract','camellia oleifera seed extract','INT'),
('Camellia oleifera whole extract','camellia oleifera whole extract','INT'),
('camellia reticulata seed oil','camellia reticulata seed oil','INT'),
('Camellia reticulata whole extract','camellia reticulata whole extract','INT'),
('Camellia sinensis flower extract','camellia sinensis flower extract','INT'),
('Camellia sinensis root extract','camellia sinensis root extract','INT'),
('camellia sinensis seed extract','camellia sinensis seed extract','INT'),
('Camellia sinensis seed oil','camellia sinensis seed oil','INT'),
('Camellia sinensis var. assamica whole extract','camellia sinensis var. assamica whole extract','INT'),
('Camellia sinensis whole extract','camellia sinensis whole extract','INT'),
('Camelus bactrianus hair extract','camelus bactrianus hair extract','INT'),
('campesterol','campesterol','INT'),
('camphene','camphene','INT'),
('camphor','camphor','INT'),
('camphor leaf oil','camphor leaf oil','INT'),
('camphor oil, white','camphor oil, white','INT'),
('camphor, (-)-','camphor, (-)-','INT'),
('camphoric acid 1-methyl ester','camphoric acid 1-methyl ester','INT'),
('camphoric acid, (+)-','camphoric acid, (+)-','INT'),
('Campsis radicans flower extract','campsis radicans flower extract','INT'),
('Campylobacter jejuni','campylobacter jejuni','INT'),
('camylofine','camylofine','INT'),
('Canada balsam extract','canada balsam extract','INT'),
('Canada goldenrod pollen extract','canada goldenrod pollen extract','INT'),
('Canadian bluegrass pollen extract','canadian bluegrass pollen extract','INT'),
('canagliflozin','canagliflozin','INT'),
('canakinumab','canakinumab','INT'),
('Cananga odorata flower extract','cananga odorata flower extract','INT'),
('Cananga odorata flower wax','cananga odorata flower wax','INT'),
('Cananga odorata leaf oil','cananga odorata leaf oil','INT'),
('Cananga oil','cananga oil','INT'),
('Canarium album whole extract','canarium album whole extract','INT'),
('Canarium indicum seed oil','canarium indicum seed oil','INT'),
('Canarium luzonicum whole extract','canarium luzonicum whole extract','INT'),
('canary feather extract','canary feather extract','INT'),
('canary grass pollen extract','canary grass pollen extract','INT'),
('Canavalia ensiformis whole extract','canavalia ensiformis whole extract','INT'),
('Canavalia gladiata seed pod extract','canavalia gladiata seed pod extract','INT'),
('Canavalia gladiata whole extract','canavalia gladiata whole extract','INT'),
('candelilla wax','candelilla wax','INT'),
('candelilla wax powder','candelilla wax powder','INT'),
('candesartan','candesartan','INT'),
('Candida albicans','candida albicans','INT'),
('Candida albicans allergenic extract','candida albicans allergenic extract','INT'),
('Candida parapsilosis','candida parapsilosis','INT'),
('Candida torresii','candida torresii','INT'),
('Candida tropicalis allergenic extract','candida tropicalis allergenic extract','INT'),
('cangrelor','cangrelor','INT'),
('Canis lupus familiaris extract','canis lupus familiaris extract','INT'),
('Canis lupus familiaris hair extract','canis lupus familiaris hair extract','INT'),
('Canis lupus familiaris milk preparation','canis lupus familiaris milk preparation','INT'),
('Canna indica root extract','canna indica root extract','INT'),
('cannabichromene','cannabichromene','INT'),
('cannabidiol','cannabidiol','INT'),
('cannabigerol','cannabigerol','INT'),
('cannabigerolate','cannabigerolate','INT'),
('cannabinol','cannabinol','INT'),
('Cannabis sativa pollen extract','cannabis sativa pollen extract','INT'),
('Cannabis sativa seed extract','cannabis sativa seed extract','INT'),
('Cannabis sativa seed oil','cannabis sativa seed oil','INT')
) AS v(nom, dci, pays)
WHERE NOT EXISTS (SELECT 1 FROM medicaments m WHERE LOWER(m.nom) = LOWER(v.nom));
