-- rxnorm_batch_189.sql (80 rows)
INSERT INTO medicaments (nom, dci, pays)
SELECT v.nom, v.dci, v.pays FROM (VALUES
('chloroxylenol / triclosan','chloroxylenol / triclosan','INT'),
('chloroxylenol / undecylenate','chloroxylenol / undecylenate','INT'),
('chlorpheniramine / codeine','chlorpheniramine / codeine','INT'),
('chlorpheniramine / codeine / iodinated glycerol','chlorpheniramine / codeine / iodinated glycerol','INT'),
('chlorpheniramine / codeine / phenylephrine','chlorpheniramine / codeine / phenylephrine','INT'),
('chlorpheniramine / codeine / phenylpropanolamine','chlorpheniramine / codeine / phenylpropanolamine','INT'),
('chlorpheniramine / codeine / pseudoephedrine','chlorpheniramine / codeine / pseudoephedrine','INT'),
('chlorpheniramine / dextromethorphan','chlorpheniramine / dextromethorphan','INT'),
('chlorpheniramine / dextromethorphan / guaifenesin','chlorpheniramine / dextromethorphan / guaifenesin','INT'),
('chlorpheniramine / dextromethorphan / scopolamine','chlorpheniramine / dextromethorphan / scopolamine','INT'),
('chlorpheniramine / dihydrocodeine / phenylephrine','chlorpheniramine / dihydrocodeine / phenylephrine','INT'),
('chlorpheniramine / ephedrine','chlorpheniramine / ephedrine','INT'),
('chlorpheniramine / ephedrine / guaifenesin','chlorpheniramine / ephedrine / guaifenesin','INT'),
('chlorpheniramine / guaifenesin','chlorpheniramine / guaifenesin','INT'),
('chlorpheniramine / guaifenesin / phenylephrine','chlorpheniramine / guaifenesin / phenylephrine','INT'),
('chlorpheniramine / guaifenesin / pseudoephedrine','chlorpheniramine / guaifenesin / pseudoephedrine','INT'),
('chlorpheniramine / hydrocodone','chlorpheniramine / hydrocodone','INT'),
('chlorpheniramine / hydrocodone / phenylephrine','chlorpheniramine / hydrocodone / phenylephrine','INT'),
('chlorpheniramine / hydrocodone / pseudoephedrine','chlorpheniramine / hydrocodone / pseudoephedrine','INT'),
('chlorpheniramine / hydrocortisone / pyrilamine','chlorpheniramine / hydrocortisone / pyrilamine','INT'),
('chlorpheniramine / ibuprofen / phenylephrine','chlorpheniramine / ibuprofen / phenylephrine','INT'),
('chlorpheniramine / ibuprofen / pseudoephedrine','chlorpheniramine / ibuprofen / pseudoephedrine','INT'),
('chlorpheniramine / methscopolamine','chlorpheniramine / methscopolamine','INT'),
('chlorpheniramine / methscopolamine / phenylephrine','chlorpheniramine / methscopolamine / phenylephrine','INT'),
('chlorpheniramine / phenylephrine','chlorpheniramine / phenylephrine','INT'),
('chlorpheniramine / phenylephrine / pyrilamine','chlorpheniramine / phenylephrine / pyrilamine','INT'),
('chlorpheniramine / phenylephrine / scopolamine','chlorpheniramine / phenylephrine / scopolamine','INT'),
('chlorpheniramine / phenylpropanolamine','chlorpheniramine / phenylpropanolamine','INT'),
('chlorpheniramine / pseudoephedrine','chlorpheniramine / pseudoephedrine','INT'),
('chlorpheniramine / pseudoephedrine / scopolamine','chlorpheniramine / pseudoephedrine / scopolamine','INT'),
('chlorpheniramine / pyrilamine','chlorpheniramine / pyrilamine','INT'),
('chlorpromazine / dipyrone','chlorpromazine / dipyrone','INT'),
('chlorpropamide / metformin','chlorpropamide / metformin','INT'),
('chlorpropamide / phenformin','chlorpropamide / phenformin','INT'),
('chlorquinaldol / diflucortolone','chlorquinaldol / diflucortolone','INT'),
('chlorquinaldol / hydrocortisone','chlorquinaldol / hydrocortisone','INT'),
('chlorquinaldol / promestriene','chlorquinaldol / promestriene','INT'),
('chlortetracycline / demeclocycline / tetracycline','chlortetracycline / demeclocycline / tetracycline','INT'),
('chlortetracycline / triamcinolone','chlortetracycline / triamcinolone','INT'),
('chlorthalidone / clonidine','chlorthalidone / clonidine','INT'),
('chlorthalidone / hydralazine / oxprenolol','chlorthalidone / hydralazine / oxprenolol','INT'),
('chlorthalidone / metoprolol','chlorthalidone / metoprolol','INT'),
('chlorthalidone / oxprenolol','chlorthalidone / oxprenolol','INT'),
('chlorthalidone / reserpine','chlorthalidone / reserpine','INT'),
('chlorthalidone / triamterene','chlorthalidone / triamterene','INT'),
('chlorzoxazone / clonixin','chlorzoxazone / clonixin','INT'),
('chlorzoxazone / flufenamate','chlorzoxazone / flufenamate','INT'),
('chlorzoxazone / flufenamic acid','chlorzoxazone / flufenamic acid','INT'),
('chlorzoxazone / ibuprofen','chlorzoxazone / ibuprofen','INT'),
('chlorzoxazone / ketoprofen','chlorzoxazone / ketoprofen','INT'),
('chlorzoxazone / piroxicam','chlorzoxazone / piroxicam','INT'),
('cholecalciferol / chromium picolinate','cholecalciferol / chromium picolinate','INT'),
('cholecalciferol / folic acid','cholecalciferol / folic acid','INT'),
('cholecalciferol / glucosamine','cholecalciferol / glucosamine','INT'),
('cholecalciferol / glucose','cholecalciferol / glucose','INT'),
('cholecalciferol / inulin','cholecalciferol / inulin','INT'),
('cholecalciferol / levocarnitine','cholecalciferol / levocarnitine','INT'),
('cholecalciferol / levomefolate','cholecalciferol / levomefolate','INT'),
('cholecalciferol / Limosilactobacillus reuteri','cholecalciferol / limosilactobacillus reuteri','INT'),
('cholecalciferol / menatetrenone','cholecalciferol / menatetrenone','INT'),
('cholecalciferol / omega-3 acid ethyl esters (USP)','cholecalciferol / omega-3 acid ethyl esters (usp)','INT'),
('cholecalciferol / polysaccharide iron complex','cholecalciferol / polysaccharide iron complex','INT'),
('cholecalciferol / sodium fluoride','cholecalciferol / sodium fluoride','INT'),
('cholecalciferol / soy protein isolate','cholecalciferol / soy protein isolate','INT'),
('cholecalciferol / tricalcium phosphate','cholecalciferol / tricalcium phosphate','INT'),
('cholecalciferol / vitamin A','cholecalciferol / vitamin a','INT'),
('cholecalciferol / vitamin E','cholecalciferol / vitamin e','INT'),
('cholecalciferol / vitamin K2','cholecalciferol / vitamin k2','INT'),
('cholestyramine resin / diclofenac','cholestyramine resin / diclofenac','INT'),
('choline / cysteine','choline / cysteine','INT'),
('choline / dexpanthenol','choline / dexpanthenol','INT'),
('choline / dextromethorphan / guaifenesin','choline / dextromethorphan / guaifenesin','INT'),
('choline / diphenhydramine','choline / diphenhydramine','INT'),
('choline / diphenhydramine / phenylephrine','choline / diphenhydramine / phenylephrine','INT'),
('choline / glutamine / inositol','choline / glutamine / inositol','INT'),
('choline / glycerin','choline / glycerin','INT'),
('choline / guaifenesin','choline / guaifenesin','INT'),
('choline / guaifenesin / phenylephrine','choline / guaifenesin / phenylephrine','INT'),
('choline / inositol','choline / inositol','INT'),
('choline / inositol / niacin','choline / inositol / niacin','INT')
) AS v(nom, dci, pays)
WHERE NOT EXISTS (SELECT 1 FROM medicaments m WHERE LOWER(m.nom) = LOWER(v.nom));
