-- rxnorm_batch_006.sql (80 rows)
INSERT INTO medicaments (nom, dci, pays)
SELECT v.nom, v.dci, v.pays FROM (VALUES
('acebutolol','acebutolol','INT'),
('acecarbromal','acecarbromal','INT'),
('aceclidine','aceclidine','INT'),
('aceclofenac','aceclofenac','INT'),
('aceglutamide','aceglutamide','INT'),
('acellular pertussis vaccine, inactivated','acellular pertussis vaccine, inactivated','INT'),
('acellular tissue engineered vessel','acellular tissue engineered vessel','INT'),
('acemannan','acemannan','INT'),
('acemetacin','acemetacin','INT'),
('aceneuramate','aceneuramate','INT'),
('acenocoumarol','acenocoumarol','INT'),
('acepromazine','acepromazine','INT'),
('aceprometazine','aceprometazine','INT'),
('Acer campestre leaf bud extract','acer campestre leaf bud extract','INT'),
('Acer negundo inner bark extract','acer negundo inner bark extract','INT'),
('Acer negundo root bark extract','acer negundo root bark extract','INT'),
('Acer negundo wood extract','acer negundo wood extract','INT'),
('Acer nigrum whole extract','acer nigrum whole extract','INT'),
('Acer pensylvanicum whole extract','acer pensylvanicum whole extract','INT'),
('Acer pseudoplatanus pollen extract','acer pseudoplatanus pollen extract','INT'),
('Acer saccharinum whole extract','acer saccharinum whole extract','INT'),
('Acer saccharum bark-sap extract','acer saccharum bark-sap extract','INT'),
('Acer saccharum leaf extract','acer saccharum leaf extract','INT'),
('Acer saccharum sap extract','acer saccharum sap extract','INT'),
('Acer saccharum whole extract','acer saccharum whole extract','INT'),
('acesulfame','acesulfame','INT'),
('acetaldehyde','acetaldehyde','INT'),
('acetamide','acetamide','INT'),
('acetamidoethoxyethanol','acetamidoethoxyethanol','INT'),
('acetamidopropyl trimonium','acetamidopropyl trimonium','INT'),
('acetaminophen','acetaminophen','INT'),
('acetanilide','acetanilide','INT'),
('acetate','acetate','INT'),
('acetazolamide','acetazolamide','INT'),
('acetiamine','acetiamine','INT'),
('acetic acid','acetic acid','INT'),
('acetic anhydride','acetic anhydride','INT'),
('acetic monoethanolamide','acetic monoethanolamide','INT'),
('acetohexamide','acetohexamide','INT'),
('acetohydroxamic acid','acetohydroxamic acid','INT'),
('acetoin','acetoin','INT'),
('acetone','acetone','INT'),
('acetophenazine','acetophenazine','INT'),
('acetophenone','acetophenone','INT'),
('acetoxolone','acetoxolone','INT'),
('acetyl arginine','acetyl arginine','INT'),
('acetyl cedrene','acetyl cedrene','INT'),
('acetyl coenzyme A','acetyl coenzyme a','INT'),
('acetyl decapeptide-3','acetyl decapeptide-3','INT'),
('acetyl dipeptide-1 cetyl ester','acetyl dipeptide-1 cetyl ester','INT'),
('acetyl farnesylcysteine','acetyl farnesylcysteine','INT'),
('acetyl glutamic acid','acetyl glutamic acid','INT'),
('acetyl hexamethyl tetralin','acetyl hexamethyl tetralin','INT'),
('acetyl hexapeptide-1','acetyl hexapeptide-1','INT'),
('acetyl hexapeptide-49','acetyl hexapeptide-49','INT'),
('acetyl hexapeptide-8','acetyl hexapeptide-8','INT'),
('acetyl octapeptide-3','acetyl octapeptide-3','INT'),
('acetyl salicylate','acetyl salicylate','INT'),
('acetyl tetrapeptide-11','acetyl tetrapeptide-11','INT'),
('acetyl tetrapeptide-15','acetyl tetrapeptide-15','INT'),
('acetyl tetrapeptide-2','acetyl tetrapeptide-2','INT'),
('acetyl tetrapeptide-3','acetyl tetrapeptide-3','INT'),
('acetyl tetrapeptide-5','acetyl tetrapeptide-5','INT'),
('acetyl tetrapeptide-9','acetyl tetrapeptide-9','INT'),
('acetyl triethylhexyl citrate','acetyl triethylhexyl citrate','INT'),
('acetylarginyltryptophyl diphenylglycine','acetylarginyltryptophyl diphenylglycine','INT'),
('acetylated lanolin','acetylated lanolin','INT'),
('acetylated lanolin alcohols','acetylated lanolin alcohols','INT'),
('acetylated sucrose distearate','acetylated sucrose distearate','INT'),
('acetylcarnitine','acetylcarnitine','INT'),
('acetylcellulose','acetylcellulose','INT'),
('acetylcholine','acetylcholine','INT'),
('acetylcholinesterase','acetylcholinesterase','INT'),
('acetylcholinesterase human','acetylcholinesterase human','INT'),
('acetylcysteine','acetylcysteine','INT'),
('acetyldigitoxin','acetyldigitoxin','INT'),
('acetyldigoxins','acetyldigoxins','INT'),
('acetylene','acetylene','INT'),
('acetylglucosamine','acetylglucosamine','INT'),
('acetylmandelic acid, (+)-','acetylmandelic acid, (+)-','INT')
) AS v(nom, dci, pays)
WHERE NOT EXISTS (SELECT 1 FROM medicaments m WHERE LOWER(m.nom) = LOWER(v.nom));
