-- sql_pathologies.sql
-- Généré automatiquement par import-pathologies.mjs
-- Date: 2026-04-24T00:00:00.000Z
-- Total: 156 pathologies

-- Ce script doit être exécuté via MCP execute_sql (service_role implicite)

INSERT INTO pathologies (nom_fr, nom_en, categorie, icd10_code, description_fr)
VALUES
  ('Hypertension artérielle', 'Arterial hypertension', 'Cardiovasculaire', 'I10', 'Élévation chronique de la pression artérielle > 140/90 mmHg'),
  ('Insuffisance cardiaque', 'Heart failure', 'Cardiovasculaire', 'I50', 'Incapacité du cœur à assurer un débit sanguin suffisant aux besoins de l''organisme'),
  ('Infarctus du myocarde', 'Myocardial infarction', 'Cardiovasculaire', 'I21', 'Nécrose d''une zone du muscle cardiaque par obstruction coronarienne'),
  ('Angine de poitrine', 'Angina pectoris', 'Cardiovasculaire', 'I20', 'Douleur thoracique ischémique par insuffisance coronarienne'),
  ('Fibrillation auriculaire', 'Atrial fibrillation', 'Cardiovasculaire', 'I48', 'Arythmie cardiaque avec activité électrique auriculaire chaotique'),
  ('Tachycardie supraventriculaire', 'Supraventricular tachycardia', 'Cardiovasculaire', 'I47.1', 'Accélération du rythme cardiaque d''origine supraventriculaire'),
  ('Bradycardie sinusale', 'Sinus bradycardia', 'Cardiovasculaire', 'R00.1', 'Ralentissement du rythme cardiaque < 60 bpm'),
  ('Bloc auriculo-ventriculaire', 'Atrioventricular block', 'Cardiovasculaire', 'I44', 'Trouble de la conduction entre oreillettes et ventricules'),
  ('Cardiomyopathie dilatée', 'Dilated cardiomyopathy', 'Cardiovasculaire', 'I42.0', 'Dilatation et dysfonction du ventricule gauche'),
  ('Péricardite', 'Pericarditis', 'Cardiovasculaire', 'I30', 'Inflammation du péricarde entourant le cœur'),
  ('Endocardite infectieuse', 'Infective endocarditis', 'Cardiovasculaire', 'I33', 'Infection bactérienne des valves cardiaques'),
  ('Valvulopathie mitrale', 'Mitral valve disease', 'Cardiovasculaire', 'I05', 'Atteinte de la valve mitrale (sténose ou insuffisance)'),
  ('Valvulopathie aortique', 'Aortic valve disease', 'Cardiovasculaire', 'I06', 'Atteinte de la valve aortique (sténose ou insuffisance)'),
  ('Artériopathie oblitérante des membres inférieurs', 'Peripheral arterial disease', 'Cardiovasculaire', 'I70.2', 'Obstruction artérielle des membres inférieurs par athérosclérose'),
  ('Thrombose veineuse profonde', 'Deep vein thrombosis', 'Cardiovasculaire', 'I80', 'Formation d''un caillot dans les veines profondes'),
  ('Embolie pulmonaire', 'Pulmonary embolism', 'Cardiovasculaire', 'I26', 'Obstruction d''une artère pulmonaire par un embole'),
  ('Anévrisme aortique', 'Aortic aneurysm', 'Cardiovasculaire', 'I71', 'Dilatation localisée pathologique de l''aorte'),
  ('Hypertension pulmonaire', 'Pulmonary hypertension', 'Cardiovasculaire', 'I27.0', 'Élévation de la pression dans la circulation pulmonaire'),
  ('Insuffisance veineuse chronique', 'Chronic venous insufficiency', 'Cardiovasculaire', 'I87.2', 'Dysfonction des valves veineuses avec reflux chronique'),
  ('Choc cardiogénique', 'Cardiogenic shock', 'Cardiovasculaire', 'R57.0', 'Défaillance circulatoire aiguë d''origine cardiaque'),
  ('Diabète type 1', 'Type 1 diabetes mellitus', 'Endocrinien et métabolique', 'E10', 'Destruction auto-immune des cellules bêta pancréatiques avec carence absolue en insuline'),
  ('Diabète type 2', 'Type 2 diabetes mellitus', 'Endocrinien et métabolique', 'E11', 'Résistance à l''insuline et déficit relatif de sécrétion insulinique'),
  ('Diabète gestationnel', 'Gestational diabetes mellitus', 'Endocrinien et métabolique', 'O24', 'Intolérance au glucose apparue ou diagnostiquée pendant la grossesse'),
  ('Hypothyroïdie', 'Hypothyroidism', 'Endocrinien et métabolique', 'E03', 'Insuffisance de production des hormones thyroïdiennes'),
  ('Hyperthyroïdie', 'Hyperthyroidism', 'Endocrinien et métabolique', 'E05', 'Excès de production des hormones thyroïdiennes'),
  ('Thyroïdite de Hashimoto', 'Hashimoto thyroiditis', 'Endocrinien et métabolique', 'E06.3', 'Thyroïdite auto-immune avec destruction progressive du tissu thyroïdien'),
  ('Maladie de Basedow', 'Graves disease', 'Endocrinien et métabolique', 'E05.0', 'Hyperthyroïdie auto-immune avec anticorps anti-récepteur TSH'),
  ('Syndrome de Cushing', 'Cushing syndrome', 'Endocrinien et métabolique', 'E24', 'Hypercorticisme chronique par excès de cortisol endogène ou exogène'),
  ('Maladie d''Addison', 'Addison disease', 'Endocrinien et métabolique', 'E27.1', 'Insuffisance surrénalienne primaire par destruction des glandes surrénales'),
  ('Hyperaldostéronisme primaire', 'Primary hyperaldosteronism', 'Endocrinien et métabolique', 'E26.0', 'Hypersécrétion autonome d''aldostérone avec hypertension et hypokaliémie'),
  ('Phéochromocytome', 'Pheochromocytoma', 'Endocrinien et métabolique', 'D35.0', 'Tumeur des glandes surrénales sécrétant des catécholamines'),
  ('Acromégalie', 'Acromegaly', 'Endocrinien et métabolique', 'E22.0', 'Hypersécrétion d''hormone de croissance après fusion des cartilages'),
  ('Hyperprolactinémie', 'Hyperprolactinemia', 'Endocrinien et métabolique', 'E22.1', 'Élévation du taux de prolactine avec troubles menstruels et galactorrhée'),
  ('Obésité', 'Obesity', 'Endocrinien et métabolique', 'E66', 'Excès de masse grasse corporelle avec IMC > 30 kg/m²'),
  ('Dyslipidémie', 'Dyslipidemia', 'Endocrinien et métabolique', 'E78', 'Anomalie des taux de lipides sanguins (cholestérol, triglycérides)'),
  ('Hyperuricémie', 'Hyperuricemia', 'Endocrinien et métabolique', 'E79.0', 'Élévation du taux d''acide urique sérique > 420 µmol/L'),
  ('Goutte', 'Gout', 'Endocrinien et métabolique', 'M10', 'Arthropathie microcristalline par dépôts d''urate monosodique'),
  ('Syndrome métabolique', 'Metabolic syndrome', 'Endocrinien et métabolique', 'E88.81', 'Association obésité abdominale, dyslipidémie, hyperglycémie et HTA'),
  ('Ostéoporose', 'Osteoporosis', 'Endocrinien et métabolique', 'M81', 'Réduction de la densité osseuse avec risque fracturaire élevé'),
  ('Ostéomalacie', 'Osteomalacia', 'Endocrinien et métabolique', 'M83', 'Défaut de minéralisation osseuse par carence en vitamine D ou phosphore'),
  ('Insuffisance surrénalienne secondaire', 'Secondary adrenal insufficiency', 'Endocrinien et métabolique', 'E27.4', 'Insuffisance surrénalienne par déficit en ACTH hypophysaire'),
  ('Diabète insipide', 'Diabetes insipidus', 'Endocrinien et métabolique', 'E23.2', 'Déficit en ADH ou résistance rénale avec polyurie et polydipsie'),
  ('Hypoparathyroïdie', 'Hypoparathyroidism', 'Endocrinien et métabolique', 'E20', 'Insuffisance de production de PTH avec hypocalcémie'),
  ('Asthme', 'Asthma', 'Respiratoire', 'J45', 'Maladie inflammatoire chronique des voies aériennes avec hyperréactivité bronchique'),
  ('BPCO', 'Chronic obstructive pulmonary disease', 'Respiratoire', 'J44', 'Obstruction bronchique chronique progressive principalement due au tabac'),
  ('Pneumonie', 'Pneumonia', 'Respiratoire', 'J18', 'Infection du parenchyme pulmonaire avec syndrome infectieux et condensation alvéolaire'),
  ('Bronchite chronique', 'Chronic bronchitis', 'Respiratoire', 'J42', 'Toux productive quotidienne pendant plus de 3 mois sur 2 années consécutives'),
  ('Emphysème', 'Emphysema', 'Respiratoire', 'J43', 'Destruction des parois alvéolaires avec distension pulmonaire permanente'),
  ('Fibrose pulmonaire idiopathique', 'Idiopathic pulmonary fibrosis', 'Respiratoire', 'J84.1', 'Fibrose progressive du parenchyme pulmonaire de cause inconnue'),
  ('Sarcoïdose pulmonaire', 'Pulmonary sarcoidosis', 'Respiratoire', 'D86.0', 'Granulomatose systémique touchant préférentiellement le poumon'),
  ('Tuberculose pulmonaire', 'Pulmonary tuberculosis', 'Respiratoire', 'A15', 'Infection pulmonaire à Mycobacterium tuberculosis'),
  ('Pleurésie', 'Pleuritis', 'Respiratoire', 'J90', 'Épanchement liquidien dans la cavité pleurale'),
  ('Pneumothorax', 'Pneumothorax', 'Respiratoire', 'J93', 'Présence d''air dans l''espace pleural'),
  ('Apnée obstructive du sommeil', 'Obstructive sleep apnea', 'Respiratoire', 'G47.3', 'Obstruction répétée des voies aériennes supérieures pendant le sommeil'),
  ('Rhinite allergique', 'Allergic rhinitis', 'Respiratoire', 'J30', 'Inflammation nasale IgE-médiée par aéroallergènes'),
  ('Sinusite chronique', 'Chronic sinusitis', 'Respiratoire', 'J32', 'Inflammation persistante des sinus paranasaux'),
  ('Bronchectasie', 'Bronchiectasis', 'Respiratoire', 'J47', 'Dilatation permanente et irréversible des bronches'),
  ('Mucoviscidose', 'Cystic fibrosis', 'Respiratoire', 'E84', 'Maladie génétique avec sécrétion de mucus épais affectant poumons et pancréas'),
  ('Cancer broncho-pulmonaire', 'Lung cancer', 'Respiratoire', 'C34', 'Tumeur maligne primitive du parenchyme pulmonaire'),
  ('Ulcère gastrique', 'Gastric ulcer', 'Gastro-intestinal', 'K25', 'Perte de substance de la muqueuse gastrique'),
  ('Ulcère duodénal', 'Duodenal ulcer', 'Gastro-intestinal', 'K26', 'Perte de substance de la muqueuse duodénale'),
  ('Gastrite chronique', 'Chronic gastritis', 'Gastro-intestinal', 'K29', 'Inflammation chronique de la muqueuse gastrique'),
  ('Reflux gastro-œsophagien', 'Gastroesophageal reflux disease', 'Gastro-intestinal', 'K21', 'Remontée du contenu gastrique acide dans l''œsophage'),
  ('Maladie de Crohn', 'Crohn disease', 'Gastro-intestinal', 'K50', 'Maladie inflammatoire chronique transmurale pouvant toucher tout le tube digestif'),
  ('Rectocolite hémorragique', 'Ulcerative colitis', 'Gastro-intestinal', 'K51', 'Maladie inflammatoire chronique limitée au côlon et rectum'),
  ('Syndrome de l''intestin irritable', 'Irritable bowel syndrome', 'Gastro-intestinal', 'K58', 'Troubles fonctionnels digestifs chroniques sans lésion organique'),
  ('Hépatite B chronique', 'Chronic hepatitis B', 'Gastro-intestinal', 'B18.1', 'Infection chronique par le virus de l''hépatite B avec atteinte hépatique'),
  ('Hépatite C chronique', 'Chronic hepatitis C', 'Gastro-intestinal', 'B18.2', 'Infection chronique par le virus de l''hépatite C'),
  ('Cirrhose hépatique', 'Hepatic cirrhosis', 'Gastro-intestinal', 'K74', 'Fibrose diffuse du foie avec nodules de régénération'),
  ('Insuffisance hépatique', 'Hepatic insufficiency', 'Gastro-intestinal', 'K72', 'Défaillance des fonctions de synthèse et d''épuration hépatiques'),
  ('Stéatose hépatique non alcoolique', 'Non-alcoholic fatty liver disease', 'Gastro-intestinal', 'K76.0', 'Accumulation de graisse dans le foie sans alcool'),
  ('Cholécystite chronique', 'Chronic cholecystitis', 'Gastro-intestinal', 'K81.1', 'Inflammation chronique de la vésicule biliaire'),
  ('Lithiase biliaire', 'Cholelithiasis', 'Gastro-intestinal', 'K80', 'Présence de calculs dans la vésicule ou les voies biliaires'),
  ('Pancréatite chronique', 'Chronic pancreatitis', 'Gastro-intestinal', 'K86.1', 'Inflammation chronique du pancréas avec fibrose progressive'),
  ('Cancer colorectal', 'Colorectal cancer', 'Gastro-intestinal', 'C18', 'Tumeur maligne du côlon ou du rectum'),
  ('Cancer gastrique', 'Gastric cancer', 'Gastro-intestinal', 'C16', 'Adénocarcinome de l''estomac'),
  ('Insuffisance rénale aiguë', 'Acute kidney injury', 'Rénal et urologique', 'N17', 'Réduction brutale et rapide du débit de filtration glomérulaire'),
  ('Insuffisance rénale chronique stade 3', 'Chronic kidney disease stage 3', 'Rénal et urologique', 'N18.3', 'DFG entre 30 et 59 mL/min/1.73m² depuis plus de 3 mois'),
  ('Insuffisance rénale chronique stade 4', 'Chronic kidney disease stage 4', 'Rénal et urologique', 'N18.4', 'DFG entre 15 et 29 mL/min/1.73m² avec atteinte structurale rénale'),
  ('Insuffisance rénale chronique stade 5', 'Chronic kidney disease stage 5', 'Rénal et urologique', 'N18.5', 'DFG < 15 mL/min/1.73m² nécessitant suppléance rénale'),
  ('Néphropathie diabétique', 'Diabetic nephropathy', 'Rénal et urologique', 'N08', 'Atteinte rénale spécifique du diabète avec protéinurie et déclin du DFG'),
  ('Glomérulonéphrite', 'Glomerulonephritis', 'Rénal et urologique', 'N03', 'Inflammation des glomérules rénaux avec hématurie et protéinurie'),
  ('Syndrome néphrotique', 'Nephrotic syndrome', 'Rénal et urologique', 'N04', 'Protéinurie massive avec hypoalbuminémie, œdèmes et hyperlipidémie'),
  ('Lithiase rénale', 'Nephrolithiasis', 'Rénal et urologique', 'N20', 'Présence de calculs dans les voies urinaires'),
  ('Pyélonéphrite chronique', 'Chronic pyelonephritis', 'Rénal et urologique', 'N11', 'Infection rénale chronique avec cicatrices parenchymateuses'),
  ('Incontinence urinaire', 'Urinary incontinence', 'Rénal et urologique', 'N39.3', 'Perte involontaire d''urine socialement gênante'),
  ('Hypertrophie bénigne de la prostate', 'Benign prostatic hyperplasia', 'Rénal et urologique', 'N40', 'Augmentation bénigne du volume prostatique avec troubles mictionnels'),
  ('Cancer de la prostate', 'Prostate cancer', 'Rénal et urologique', 'C61', 'Adénocarcinome de la prostate'),
  ('Cancer du rein', 'Renal cancer', 'Rénal et urologique', 'C64', 'Tumeur maligne du parenchyme rénal'),
  ('Épilepsie', 'Epilepsy', 'Neurologique', 'G40', 'Affection cérébrale chronique caractérisée par des crises épileptiques récurrentes'),
  ('Migraine', 'Migraine', 'Neurologique', 'G43', 'Céphalées récurrentes unilatérales pulsatiles avec nausées et phonophobie'),
  ('Maladie de Parkinson', 'Parkinson disease', 'Neurologique', 'G20', 'Dégénérescence des neurones dopaminergiques avec tremblements et akinésie'),
  ('Maladie d''Alzheimer', 'Alzheimer disease', 'Neurologique', 'G30', 'Démence neurodégénérative progressive avec atteinte mémorielle et cognitive'),
  ('Sclérose en plaques', 'Multiple sclerosis', 'Neurologique', 'G35', 'Maladie démyélinisante auto-immune du système nerveux central'),
  ('AVC ischémique', 'Ischemic stroke', 'Neurologique', 'I63', 'Infarctus cérébral par obstruction artérielle'),
  ('AVC hémorragique', 'Hemorrhagic stroke', 'Neurologique', 'I61', 'Saignement intraparenchymateux cérébral'),
  ('Neuropathie périphérique', 'Peripheral neuropathy', 'Neurologique', 'G62', 'Atteinte des nerfs périphériques avec troubles sensitifs et moteurs'),
  ('Myasthénie grave', 'Myasthenia gravis', 'Neurologique', 'G70.0', 'Maladie auto-immune de la jonction neuromusculaire'),
  ('Sclérose latérale amyotrophique', 'Amyotrophic lateral sclerosis', 'Neurologique', 'G12.2', 'Dégénérescence progressive des motoneurones centraux et périphériques'),
  ('Méningite bactérienne', 'Bacterial meningitis', 'Neurologique', 'G00', 'Infection bactérienne des méninges avec syndrome méningé'),
  ('Névralgie du trijumeau', 'Trigeminal neuralgia', 'Neurologique', 'G50.0', 'Douleurs faciales paroxystiques intenses dans le territoire du nerf trijumeau'),
  ('Syndrome de Guillain-Barré', 'Guillain-Barre syndrome', 'Neurologique', 'G61.0', 'Polyradiculonévrite aiguë inflammatoire post-infectieuse'),
  ('Narcolepsie', 'Narcolepsy', 'Neurologique', 'G47.4', 'Trouble du sommeil avec accès irrésistibles de sommeil diurne'),
  ('Tremblement essentiel', 'Essential tremor', 'Neurologique', 'G25.0', 'Tremblement postural et cinétique chronique sans autre cause identifiée'),
  ('Hydrocéphalie', 'Hydrocephalus', 'Neurologique', 'G91', 'Accumulation excessive de LCR avec dilatation des ventricules cérébraux'),
  ('Dépression majeure', 'Major depressive disorder', 'Psychiatrique', 'F32', 'Episode dépressif caractérisé avec humeur dépressive et anhédonie persistantes'),
  ('Trouble bipolaire', 'Bipolar disorder', 'Psychiatrique', 'F31', 'Alternance d''épisodes maniaques et dépressifs'),
  ('Schizophrénie', 'Schizophrenia', 'Psychiatrique', 'F20', 'Psychose chronique avec hallucinations, délires et désorganisation de la pensée'),
  ('Trouble anxieux généralisé', 'Generalized anxiety disorder', 'Psychiatrique', 'F41.1', 'Anxiété excessive et incontrôlable concernant différents domaines'),
  ('Trouble panique', 'Panic disorder', 'Psychiatrique', 'F41.0', 'Crises d''angoisse aiguë récurrentes imprévisibles'),
  ('Phobie sociale', 'Social phobia', 'Psychiatrique', 'F40.1', 'Peur persistante des situations sociales avec comportement d''évitement'),
  ('Trouble obsessionnel compulsif', 'Obsessive-compulsive disorder', 'Psychiatrique', 'F42', 'Pensées intrusives récurrentes avec comportements compulsifs'),
  ('État de stress post-traumatique', 'Post-traumatic stress disorder', 'Psychiatrique', 'F43.1', 'Réaction différée à un événement traumatique avec reviviscences'),
  ('TDAH', 'Attention deficit hyperactivity disorder', 'Psychiatrique', 'F90', 'Trouble neurodéveloppemental avec inattention et hyperactivité'),
  ('Anorexie mentale', 'Anorexia nervosa', 'Psychiatrique', 'F50.0', 'Restriction alimentaire sévère avec dysmorphophobie corporelle'),
  ('Boulimie', 'Bulimia nervosa', 'Psychiatrique', 'F50.2', 'Crises alimentaires compulsives suivies de comportements compensatoires'),
  ('Insomnie chronique', 'Chronic insomnia', 'Psychiatrique', 'G47.0', 'Difficultés persistantes d''endormissement ou de maintien du sommeil'),
  ('Addiction à l''alcool', 'Alcohol use disorder', 'Psychiatrique', 'F10', 'Dépendance à l''alcool avec tolérance et syndrome de sevrage'),
  ('Addiction aux opioïdes', 'Opioid use disorder', 'Psychiatrique', 'F11', 'Dépendance aux opioïdes avec craving et syndrome de manque'),
  ('Psychose aiguë', 'Acute psychosis', 'Psychiatrique', 'F23', 'Episode psychotique aigu avec délires et hallucinations'),
  ('Polyarthrite rhumatoïde', 'Rheumatoid arthritis', 'Rhumatologique', 'M05', 'Rhumatisme inflammatoire chronique auto-immune touchant les articulations'),
  ('Lupus érythémateux systémique', 'Systemic lupus erythematosus', 'Rhumatologique', 'M32', 'Connectivite auto-immune systémique avec atteintes multiviscérales'),
  ('Sclérodermie systémique', 'Systemic sclerosis', 'Rhumatologique', 'M34', 'Maladie auto-immune avec fibrose cutanée et viscérale'),
  ('Spondylarthrite ankylosante', 'Ankylosing spondylitis', 'Rhumatologique', 'M45', 'Rhumatisme inflammatoire touchant le rachis et les sacro-iliaques'),
  ('Arthrose', 'Osteoarthritis', 'Rhumatologique', 'M15', 'Dégénérescence progressive du cartilage articulaire'),
  ('Fibromyalgie', 'Fibromyalgia', 'Rhumatologique', 'M79.7', 'Syndrome douloureux chronique diffus avec fatigue et troubles du sommeil'),
  ('Pseudogoutte', 'Calcium pyrophosphate deposition', 'Rhumatologique', 'M11', 'Arthropathie microcristalline par dépôts de pyrophosphate de calcium'),
  ('Polymyosite', 'Polymyositis', 'Rhumatologique', 'M33', 'Myopathie inflammatoire idiopathique avec faiblesse musculaire proximale'),
  ('Vascularite systémique', 'Systemic vasculitis', 'Rhumatologique', 'M30', 'Inflammation des parois vasculaires avec atteinte multisystémique'),
  ('Syndrome de Sjögren', 'Sjogren syndrome', 'Rhumatologique', 'M35.0', 'Exocrinopathie auto-immune avec sécheresse oculaire et buccale'),
  ('VIH/SIDA', 'HIV/AIDS', 'Infectieuse', 'B20', 'Infection par le virus de l''immunodéficience humaine avec immunodépression'),
  ('Tuberculose active', 'Active tuberculosis', 'Infectieuse', 'A15', 'Infection active à Mycobacterium tuberculosis'),
  ('Paludisme', 'Malaria', 'Infectieuse', 'B50', 'Infection à Plasmodium transmise par moustique Anophèle'),
  ('Infections fongiques systémiques', 'Systemic fungal infections', 'Infectieuse', 'B44', 'Infections disséminées à champignons pathogènes'),
  ('COVID-19', 'COVID-19', 'Infectieuse', 'U07.1', 'Infection respiratoire aiguë au SARS-CoV-2'),
  ('Anémie ferriprive', 'Iron deficiency anemia', 'Hématologique', 'D50', 'Anémie par carence martiale avec microcytose et hypochromie'),
  ('Anémie mégaloblastique', 'Megaloblastic anemia', 'Hématologique', 'D51', 'Anémie par carence en vitamine B12 ou folates'),
  ('Drépanocytose', 'Sickle cell disease', 'Hématologique', 'D57', 'Hémoglobinopathie héréditaire avec érythrocytes falciformes'),
  ('Thalassémie', 'Thalassemia', 'Hématologique', 'D56', 'Hémoglobinopathie héréditaire avec réduction de synthèse des chaînes de globine'),
  ('Leucémie lymphoïde chronique', 'Chronic lymphocytic leukemia', 'Hématologique', 'C91.1', 'Prolifération maligne de lymphocytes B matures'),
  ('Lymphome non hodgkinien', 'Non-Hodgkin lymphoma', 'Hématologique', 'C85', 'Prolifération maligne des lymphocytes en dehors de la moelle'),
  ('Myélome multiple', 'Multiple myeloma', 'Hématologique', 'C90', 'Prolifération maligne des plasmocytes médullaires'),
  ('Thrombopénie immunologique', 'Immune thrombocytopenia', 'Hématologique', 'D69.3', 'Réduction des plaquettes par mécanisme auto-immun'),
  ('Hémophilie A', 'Hemophilia A', 'Hématologique', 'D66', 'Déficit en facteur VIII de coagulation héréditaire lié à l''X'),
  ('Polycythémie vraie', 'Polycythemia vera', 'Hématologique', 'D45', 'Prolifération clonale érythroïde avec augmentation de la masse érythrocytaire'),
  ('Psoriasis', 'Psoriasis', 'Dermatologique', 'L40', 'Dermatose inflammatoire chronique avec plaques érythémato-squameuses'),
  ('Eczéma atopique', 'Atopic dermatitis', 'Dermatologique', 'L20', 'Dermatite inflammatoire chronique prurigineuse à terrain atopique'),
  ('Urticaire chronique', 'Chronic urticaria', 'Dermatologique', 'L50', 'Éruption urticarienne récurrente persistant plus de 6 semaines'),
  ('Acné sévère', 'Severe acne', 'Dermatologique', 'L70', 'Dermatose inflammatoire du follicule pilo-sébacé'),
  ('Rosacée', 'Rosacea', 'Dermatologique', 'L71', 'Dermatose chronique du visage avec érythème, papules et pustules'),
  ('Vitiligo', 'Vitiligo', 'Dermatologique', 'L80', 'Dépigmentation cutanée par destruction des mélanocytes'),
  ('Pemphigus vulgaire', 'Pemphigus vulgaris', 'Dermatologique', 'L10', 'Dermatose bulleuse auto-immune intraépidermique grave'),
  ('Grossesse', 'Pregnancy', 'Gynécologique et obstétrical', 'Z34', 'État physiologique de gestation nécessitant une adaptation thérapeutique'),
  ('Allaitement maternel', 'Breastfeeding', 'Gynécologique et obstétrical', 'Z39.1', 'Lactation nécessitant précautions pour médicaments excrétés dans le lait'),
  ('Endométriose', 'Endometriosis', 'Gynécologique et obstétrical', 'N80', 'Présence de tissu endométrial en dehors de la cavité utérine'),
  ('Syndrome des ovaires polykystiques', 'Polycystic ovary syndrome', 'Gynécologique et obstétrical', 'E28.2', 'Dysfonction ovarienne avec hyperandrogénisme et kystes multiples'),
  ('Ménopause', 'Menopause', 'Gynécologique et obstétrical', 'N95.1', 'Arrêt définitif des cycles menstruels avec carence oestrogénique'),
  ('Fibrome utérin', 'Uterine fibroid', 'Gynécologique et obstétrical', 'D25', 'Tumeur bénigne du muscle utérin (léiomyome)'),
  ('Cancer du sein', 'Breast cancer', 'Gynécologique et obstétrical', 'C50', 'Tumeur maligne du tissu mammaire'),
  ('Prééclampsie', 'Preeclampsia', 'Gynécologique et obstétrical', 'O14', 'HTA gestationnelle avec protéinurie après 20 semaines de grossesse'),
  ('Glaucome à angle ouvert', 'Open-angle glaucoma', 'Ophtalmologique', 'H40.1', 'Neuropathie optique progressive par hypertonie oculaire chronique'),
  ('Cataracte', 'Cataract', 'Ophtalmologique', 'H26', 'Opacification du cristallin avec baisse progressive de l''acuité visuelle'),
  ('Dégénérescence maculaire liée à l''âge', 'Age-related macular degeneration', 'Ophtalmologique', 'H35.3', 'Atteinte dégénérative de la macula avec perte centrale de vision'),
  ('Rétinopathie diabétique', 'Diabetic retinopathy', 'Ophtalmologique', 'H36', 'Complication microvasculaire du diabète touchant la rétine'),
  ('Uvéite', 'Uveitis', 'Ophtalmologique', 'H20', 'Inflammation de l''uvée (iris, corps ciliaire, choroïde)'),
  ('Otite moyenne chronique', 'Chronic otitis media', 'ORL', 'H66', 'Infection chronique de l''oreille moyenne avec perforation tympanique'),
  ('Surdité de perception', 'Sensorineural hearing loss', 'ORL', 'H90.3', 'Perte auditive par atteinte cochléaire ou du nerf auditif'),
  ('Vertiges de Ménière', 'Meniere disease', 'ORL', 'H81.0', 'Hydrops endolymphatique avec crises vertigineuses et hypoacousie')
ON CONFLICT (nom_fr) DO UPDATE SET
  nom_en = EXCLUDED.nom_en,
  categorie = EXCLUDED.categorie,
  icd10_code = EXCLUDED.icd10_code,
  description_fr = EXCLUDED.description_fr;

-- Fin du script (156 lignes insérées/mises à jour)
