-- Sprint 4e-A — Doublons thérapeutiques : canal additionnel du moteur de sécurité.
-- Généré par scripts/gen_regles_doublons.mjs (source unique, partagée avec les tests).
-- La RPC check_interactions_v2, la table contraindications et leur matching ne changent pas.

-- 1. Classes à risque : motifs normalisés (minuscules, sans accents), en début de mot.
create table if not exists public.doublon_classes (
  id uuid primary key default gen_random_uuid(),
  classe text not null,
  label text not null,
  motif text not null check (length(motif) >= 3 and motif = lower(motif)),
  unique (classe, motif)
);

-- 2. Substances : synonymes (une seule clé par substance) et adjuvants (caféine, vitamine C…).
create table if not exists public.doublon_substances (
  id uuid primary key default gen_random_uuid(),
  substance text not null,
  label text not null,
  type text not null check (type in ('synonyme','adjuvant')),
  motif text not null check (length(motif) >= 3 and motif = lower(motif)),
  unique (substance, motif)
);

-- 3. Règles. classe « * » = même principe actif ; « + » = même substance d'appoint.
create table if not exists public.regles_doublons (
  id uuid primary key default gen_random_uuid(),
  code text not null,
  ordre integer not null,
  classe_a text not null,
  classe_b text not null,
  severite text not null check (severite in ('majeure','attention')),
  titre text not null,
  conduite text not null,
  source text not null default 'Proposition Ordosur d''après RCP — à valider',
  actif boolean not null default true,
  created_at timestamptz not null default now(),
  unique (code, classe_a, classe_b)
);

-- 4. RLS : lecture pour tout utilisateur authentifié, aucune écriture client.
alter table public.doublon_classes enable row level security;
alter table public.doublon_substances enable row level security;
alter table public.regles_doublons enable row level security;
drop policy if exists doublon_classes_read on public.doublon_classes;
create policy doublon_classes_read on public.doublon_classes for select to authenticated using (true);
drop policy if exists doublon_substances_read on public.doublon_substances;
create policy doublon_substances_read on public.doublon_substances for select to authenticated using (true);
drop policy if exists regles_doublons_read on public.regles_doublons;
create policy regles_doublons_read on public.regles_doublons for select to authenticated using (true);
revoke insert, update, delete on public.doublon_classes from anon, authenticated;
revoke insert, update, delete on public.doublon_substances from anon, authenticated;
revoke insert, update, delete on public.regles_doublons from anon, authenticated;

-- 5. Données.
insert into public.doublon_classes (classe, label, motif) values
  ('ipp', 'inhibiteurs de la pompe à protons', 'omeprazol'),
  ('ipp', 'inhibiteurs de la pompe à protons', 'esomeprazol'),
  ('ipp', 'inhibiteurs de la pompe à protons', 'lansoprazol'),
  ('ipp', 'inhibiteurs de la pompe à protons', 'dexlansoprazol'),
  ('ipp', 'inhibiteurs de la pompe à protons', 'pantoprazol'),
  ('ipp', 'inhibiteurs de la pompe à protons', 'rabeprazol'),
  ('iec', 'IEC', 'captopril'),
  ('iec', 'IEC', 'enalapril'),
  ('iec', 'IEC', 'lisinopril'),
  ('iec', 'IEC', 'perindopril'),
  ('iec', 'IEC', 'ramipril'),
  ('iec', 'IEC', 'quinapril'),
  ('iec', 'IEC', 'benazepril'),
  ('iec', 'IEC', 'fosinopril'),
  ('iec', 'IEC', 'trandolapril'),
  ('iec', 'IEC', 'zofenopril'),
  ('iec', 'IEC', 'cilazapril'),
  ('iec', 'IEC', 'imidapril'),
  ('iec', 'IEC', 'moexipril'),
  ('ara2', 'ARA2 (sartans)', 'losartan'),
  ('ara2', 'ARA2 (sartans)', 'valsartan'),
  ('ara2', 'ARA2 (sartans)', 'irbesartan'),
  ('ara2', 'ARA2 (sartans)', 'candesartan'),
  ('ara2', 'ARA2 (sartans)', 'telmisartan'),
  ('ara2', 'ARA2 (sartans)', 'olmesartan'),
  ('ara2', 'ARA2 (sartans)', 'azilsartan'),
  ('ara2', 'ARA2 (sartans)', 'eprosartan'),
  ('benzodiazepines', 'benzodiazépines et apparentés', 'diazepam'),
  ('benzodiazepines', 'benzodiazépines et apparentés', 'alprazolam'),
  ('benzodiazepines', 'benzodiazépines et apparentés', 'lorazepam'),
  ('benzodiazepines', 'benzodiazépines et apparentés', 'bromazepam'),
  ('benzodiazepines', 'benzodiazépines et apparentés', 'clonazepam'),
  ('benzodiazepines', 'benzodiazépines et apparentés', 'oxazepam'),
  ('benzodiazepines', 'benzodiazépines et apparentés', 'prazepam'),
  ('benzodiazepines', 'benzodiazépines et apparentés', 'nordazepam'),
  ('benzodiazepines', 'benzodiazépines et apparentés', 'clorazepat'),
  ('benzodiazepines', 'benzodiazépines et apparentés', 'clobazam'),
  ('benzodiazepines', 'benzodiazépines et apparentés', 'nitrazepam'),
  ('benzodiazepines', 'benzodiazépines et apparentés', 'lormetazepam'),
  ('benzodiazepines', 'benzodiazépines et apparentés', 'temazepam'),
  ('benzodiazepines', 'benzodiazépines et apparentés', 'midazolam'),
  ('benzodiazepines', 'benzodiazépines et apparentés', 'tetrazepam'),
  ('benzodiazepines', 'benzodiazépines et apparentés', 'loprazolam'),
  ('benzodiazepines', 'benzodiazépines et apparentés', 'estazolam'),
  ('benzodiazepines', 'benzodiazépines et apparentés', 'flunitrazepam'),
  ('benzodiazepines', 'benzodiazépines et apparentés', 'triazolam'),
  ('benzodiazepines', 'benzodiazépines et apparentés', 'chlordiazepoxid'),
  ('benzodiazepines', 'benzodiazépines et apparentés', 'zolpidem'),
  ('benzodiazepines', 'benzodiazépines et apparentés', 'zopiclon'),
  ('benzodiazepines', 'benzodiazépines et apparentés', 'eszopiclon'),
  ('statines', 'statines', 'simvastatin'),
  ('statines', 'statines', 'atorvastatin'),
  ('statines', 'statines', 'rosuvastatin'),
  ('statines', 'statines', 'pravastatin'),
  ('statines', 'statines', 'fluvastatin'),
  ('statines', 'statines', 'pitavastatin'),
  ('statines', 'statines', 'lovastatin'),
  ('opioides', 'opioïdes', 'codein'),
  ('opioides', 'opioïdes', 'dihydrocodein'),
  ('opioides', 'opioïdes', 'morphin'),
  ('opioides', 'opioïdes', 'ethylmorphin'),
  ('opioides', 'opioïdes', 'tramadol'),
  ('opioides', 'opioïdes', 'oxycodon'),
  ('opioides', 'opioïdes', 'hydromorphon'),
  ('opioides', 'opioïdes', 'fentanyl'),
  ('opioides', 'opioïdes', 'buprenorphin'),
  ('opioides', 'opioïdes', 'nalbuphin'),
  ('opioides', 'opioïdes', 'methadon'),
  ('opioides', 'opioïdes', 'pethidin'),
  ('opioides', 'opioïdes', 'tapentadol'),
  ('opioides', 'opioïdes', 'pholcodin'),
  ('opioides', 'opioïdes', 'opium'),
  ('isrs_irsna', 'antidépresseurs ISRS / IRSNA', 'fluoxetin'),
  ('isrs_irsna', 'antidépresseurs ISRS / IRSNA', 'paroxetin'),
  ('isrs_irsna', 'antidépresseurs ISRS / IRSNA', 'sertralin'),
  ('isrs_irsna', 'antidépresseurs ISRS / IRSNA', 'citalopram'),
  ('isrs_irsna', 'antidépresseurs ISRS / IRSNA', 'escitalopram'),
  ('isrs_irsna', 'antidépresseurs ISRS / IRSNA', 'fluvoxamin'),
  ('isrs_irsna', 'antidépresseurs ISRS / IRSNA', 'venlafaxin'),
  ('isrs_irsna', 'antidépresseurs ISRS / IRSNA', 'desvenlafaxin'),
  ('isrs_irsna', 'antidépresseurs ISRS / IRSNA', 'duloxetin'),
  ('isrs_irsna', 'antidépresseurs ISRS / IRSNA', 'milnacipran'),
  ('sulfamides_hypoglycemiants', 'sulfamides hypoglycémiants', 'glibenclamid'),
  ('sulfamides_hypoglycemiants', 'sulfamides hypoglycémiants', 'glyburid'),
  ('sulfamides_hypoglycemiants', 'sulfamides hypoglycémiants', 'gliclazid'),
  ('sulfamides_hypoglycemiants', 'sulfamides hypoglycémiants', 'glimepirid'),
  ('sulfamides_hypoglycemiants', 'sulfamides hypoglycémiants', 'glipizid'),
  ('sulfamides_hypoglycemiants', 'sulfamides hypoglycémiants', 'gliquidon'),
  ('betabloquants', 'bêtabloquants', 'atenolol'),
  ('betabloquants', 'bêtabloquants', 'bisoprolol'),
  ('betabloquants', 'bêtabloquants', 'metoprolol'),
  ('betabloquants', 'bêtabloquants', 'propranolol'),
  ('betabloquants', 'bêtabloquants', 'carvedilol'),
  ('betabloquants', 'bêtabloquants', 'nebivolol'),
  ('betabloquants', 'bêtabloquants', 'acebutolol'),
  ('betabloquants', 'bêtabloquants', 'sotalol'),
  ('betabloquants', 'bêtabloquants', 'celiprolol'),
  ('betabloquants', 'bêtabloquants', 'labetalol'),
  ('betabloquants', 'bêtabloquants', 'nadolol'),
  ('betabloquants', 'bêtabloquants', 'betaxolol'),
  ('betabloquants', 'bêtabloquants', 'pindolol'),
  ('betabloquants', 'bêtabloquants', 'esmolol'),
  ('betabloquants', 'bêtabloquants', 'tertatolol'),
  ('betabloquants', 'bêtabloquants', 'timolol'),
  ('antihistaminiques_h1_sedatifs', 'antihistaminiques H1 sédatifs', 'hydroxyzin'),
  ('antihistaminiques_h1_sedatifs', 'antihistaminiques H1 sédatifs', 'dexchlorpheniramin'),
  ('antihistaminiques_h1_sedatifs', 'antihistaminiques H1 sédatifs', 'chlorphenamin'),
  ('antihistaminiques_h1_sedatifs', 'antihistaminiques H1 sédatifs', 'chlorpheniramin'),
  ('antihistaminiques_h1_sedatifs', 'antihistaminiques H1 sédatifs', 'brompheniramin'),
  ('antihistaminiques_h1_sedatifs', 'antihistaminiques H1 sédatifs', 'pheniramin'),
  ('antihistaminiques_h1_sedatifs', 'antihistaminiques H1 sédatifs', 'promethazin'),
  ('antihistaminiques_h1_sedatifs', 'antihistaminiques H1 sédatifs', 'alimemazin'),
  ('antihistaminiques_h1_sedatifs', 'antihistaminiques H1 sédatifs', 'oxomemazin'),
  ('antihistaminiques_h1_sedatifs', 'antihistaminiques H1 sédatifs', 'doxylamin'),
  ('antihistaminiques_h1_sedatifs', 'antihistaminiques H1 sédatifs', 'diphenhydramin'),
  ('antihistaminiques_h1_sedatifs', 'antihistaminiques H1 sédatifs', 'mequitazin'),
  ('antihistaminiques_h1_sedatifs', 'antihistaminiques H1 sédatifs', 'cyproheptadin'),
  ('antihistaminiques_h1_sedatifs', 'antihistaminiques H1 sédatifs', 'ketotifen'),
  ('antihistaminiques_h1_sedatifs', 'antihistaminiques H1 sédatifs', 'triprolidin'),
  ('antihistaminiques_h1_sedatifs', 'antihistaminiques H1 sédatifs', 'clemastin'),
  ('antihistaminiques_h1_sedatifs', 'antihistaminiques H1 sédatifs', 'buclizin'),
  ('antihistaminiques_h1_sedatifs', 'antihistaminiques H1 sédatifs', 'carbinoxamin')
on conflict (classe, motif) do nothing;

insert into public.doublon_substances (substance, label, type, motif) values
  ('paracetamol', 'paracétamol', 'synonyme', 'paracetamol'),
  ('paracetamol', 'paracétamol', 'synonyme', 'acetaminophen'),
  ('aspirine', 'aspirine', 'synonyme', 'aspirin'),
  ('aspirine', 'aspirine', 'synonyme', 'acetylsalicyl'),
  ('aspirine', 'aspirine', 'synonyme', 'acetilsalicyl'),
  ('aspirine', 'aspirine', 'synonyme', 'acide acetylsalicylique'),
  ('valproate', 'valproate', 'synonyme', 'valpro'),
  ('valproate', 'valproate', 'synonyme', 'divalpro'),
  ('salbutamol', 'salbutamol', 'synonyme', 'salbutamol'),
  ('salbutamol', 'salbutamol', 'synonyme', 'albuterol'),
  ('adrenaline', 'adrénaline', 'synonyme', 'adrenalin'),
  ('adrenaline', 'adrénaline', 'synonyme', 'epinephrin'),
  ('noradrenaline', 'noradrénaline', 'synonyme', 'noradrenalin'),
  ('noradrenaline', 'noradrénaline', 'synonyme', 'norepinephrin'),
  ('glibenclamide', 'glibenclamide', 'synonyme', 'glibenclamid'),
  ('glibenclamide', 'glibenclamide', 'synonyme', 'glyburid'),
  ('metamizole', 'métamizole', 'synonyme', 'metamizol'),
  ('metamizole', 'métamizole', 'synonyme', 'dipyron'),
  ('metamizole', 'métamizole', 'synonyme', 'noramidopyrin'),
  ('ciclosporine', 'ciclosporine', 'synonyme', 'ciclosporin'),
  ('ciclosporine', 'ciclosporine', 'synonyme', 'cyclosporin'),
  ('rifampicine', 'rifampicine', 'synonyme', 'rifampicin'),
  ('rifampicine', 'rifampicine', 'synonyme', 'rifampin'),
  ('lidocaine', 'lidocaïne', 'synonyme', 'lidocain'),
  ('lidocaine', 'lidocaïne', 'synonyme', 'lignocain'),
  ('furosemide', 'furosémide', 'synonyme', 'furosemid'),
  ('furosemide', 'furosémide', 'synonyme', 'frusemid'),
  ('pethidine', 'péthidine', 'synonyme', 'pethidin'),
  ('pethidine', 'péthidine', 'synonyme', 'meperidin'),
  ('vitamine_d3', 'vitamine D3', 'synonyme', 'colecalciferol'),
  ('vitamine_d3', 'vitamine D3', 'synonyme', 'cholecalciferol'),
  ('vitamine_d3', 'vitamine D3', 'synonyme', 'vitamine d3'),
  ('vitamine_d3', 'vitamine D3', 'synonyme', 'vitamin d3'),
  ('levothyroxine', 'lévothyroxine', 'synonyme', 'levothyrox'),
  ('aciclovir', 'aciclovir', 'synonyme', 'aciclovir'),
  ('aciclovir', 'aciclovir', 'synonyme', 'acyclovir'),
  ('cefalexine', 'céfalexine', 'synonyme', 'cefalexin'),
  ('cefalexine', 'céfalexine', 'synonyme', 'cephalexin'),
  ('acetylcysteine', 'acétylcystéine', 'synonyme', 'acetylcystein'),
  ('acetylcysteine', 'acétylcystéine', 'synonyme', 'n acetylcystein'),
  ('cafeine', 'caféine', 'adjuvant', 'cafein'),
  ('cafeine', 'caféine', 'adjuvant', 'caffein'),
  ('vitamine_c', 'vitamine C', 'adjuvant', 'acide ascorbique'),
  ('vitamine_c', 'vitamine C', 'adjuvant', 'ascorbic'),
  ('vitamine_c', 'vitamine C', 'adjuvant', 'ascorbique'),
  ('vitamine_c', 'vitamine C', 'adjuvant', 'vitamine c'),
  ('vitamine_c', 'vitamine C', 'adjuvant', 'vitamin c'),
  ('menthol', 'menthol', 'adjuvant', 'menthol'),
  ('menthol', 'menthol', 'adjuvant', 'levomenthol'),
  ('camphre', 'camphre', 'adjuvant', 'camphre'),
  ('camphre', 'camphre', 'adjuvant', 'camphor'),
  ('eucalyptus', 'eucalyptus', 'adjuvant', 'eucalypt'),
  ('eucalyptus', 'eucalyptus', 'adjuvant', 'niaouli'),
  ('eucalyptus', 'eucalyptus', 'adjuvant', 'cineol')
on conflict (substance, motif) do nothing;

insert into public.regles_doublons (code, ordre, classe_a, classe_b, severite, titre, conduite, source) values
  ('D1', 10, '*', '*', 'majeure', 'Même principe actif', 'Risque de surdosage. Ne garder qu’une seule spécialité, ou vérifier la dose totale journalière.', 'Proposition Ordosur d''après RCP — à valider'),
  ('D1b', 20, '+', '+', 'attention', 'Même substance d’appoint', 'Substance présente dans les deux spécialités : vérifier la dose totale.', 'Proposition Ordosur d''après RCP — à valider'),
  ('D2', 30, 'ipp', 'ipp', 'attention', 'Deux médicaments de la même classe (inhibiteurs de la pompe à protons)', 'Association de deux IPP sans bénéfice : n’en garder qu’un.', 'Proposition Ordosur d''après RCP — à valider'),
  ('D2', 40, 'iec', 'iec', 'attention', 'Deux médicaments de la même classe (IEC)', 'Association de deux IEC sans bénéfice : risque d’hypotension, d’hyperkaliémie et d’insuffisance rénale. N’en garder qu’un.', 'Proposition Ordosur d''après RCP — à valider'),
  ('D2', 50, 'ara2', 'ara2', 'attention', 'Deux médicaments de la même classe (ARA2 (sartans))', 'Association de deux sartans sans bénéfice : risque d’hypotension, d’hyperkaliémie et d’insuffisance rénale. N’en garder qu’un.', 'Proposition Ordosur d''après RCP — à valider'),
  ('D2', 60, 'benzodiazepines', 'benzodiazepines', 'attention', 'Deux médicaments de la même classe (benzodiazépines et apparentés)', 'Cumul des effets sédatifs et du risque de dépendance : n’en garder qu’une.', 'Proposition Ordosur d''après RCP — à valider'),
  ('D2', 70, 'statines', 'statines', 'attention', 'Deux médicaments de la même classe (statines)', 'Association de deux statines sans bénéfice : risque musculaire majoré. N’en garder qu’une.', 'Proposition Ordosur d''après RCP — à valider'),
  ('D2', 80, 'opioides', 'opioides', 'attention', 'Deux médicaments de la même classe (opioïdes)', 'Cumul des effets dépresseurs respiratoires et sédatifs : vérifier que l’association est voulue et la dose totale.', 'Proposition Ordosur d''après RCP — à valider'),
  ('D2', 90, 'isrs_irsna', 'isrs_irsna', 'attention', 'Deux médicaments de la même classe (antidépresseurs ISRS / IRSNA)', 'Risque de syndrome sérotoninergique : n’en garder qu’un.', 'Proposition Ordosur d''après RCP — à valider'),
  ('D2', 100, 'sulfamides_hypoglycemiants', 'sulfamides_hypoglycemiants', 'attention', 'Deux médicaments de la même classe (sulfamides hypoglycémiants)', 'Association de deux sulfamides hypoglycémiants : risque d’hypoglycémie. N’en garder qu’un.', 'Proposition Ordosur d''après RCP — à valider'),
  ('D2', 110, 'betabloquants', 'betabloquants', 'attention', 'Deux médicaments de la même classe (bêtabloquants)', 'Association de deux bêtabloquants : risque de bradycardie et de troubles de la conduction. N’en garder qu’un (collyres compris).', 'Proposition Ordosur d''après RCP — à valider'),
  ('D2', 120, 'antihistaminiques_h1_sedatifs', 'antihistaminiques_h1_sedatifs', 'attention', 'Deux médicaments de la même classe (antihistaminiques H1 sédatifs)', 'Cumul des effets sédatifs et atropiniques : n’en garder qu’un.', 'Proposition Ordosur d''après RCP — à valider'),
  ('D2', 130, 'ara2', 'iec', 'attention', 'Association IEC + ARA2 (double blocage du système rénine-angiotensine)', 'Double blocage déconseillé : risque d’hyperkaliémie, d’hypotension et d’insuffisance rénale. Vérifier que l’association est voulue ; surveillance de la kaliémie et de la créatinine.', 'Proposition Ordosur d''après RCP — à valider')
on conflict (code, classe_a, classe_b) do update set
  ordre = excluded.ordre, severite = excluded.severite, titre = excluded.titre,
  conduite = excluded.conduite, source = excluded.source;
